### ISSUE TITLE
认领翻译

### ISSUE THREAD

**Issue by Zhangjd** [xitu/gold-miner#1]
我先来认领一篇
How do Promises Work? (http://gold.xitu.io/entry/5665281460b21eab5d5c41fa)

**Comment by Glowin** [comment]
好啊好啊，Fork 一下这个仓库，然后直接在 markdown 上修改就好。

**Comment by Zhangjd** [comment]
是直接替换掉markdown原本的英文内容吗？预计两天内完成。

**Comment by Glowin** [comment]
是的呢，直接替换掉就好

**Comment by Yves-X** [comment]
上面的 reference 出于 commit message 的笔误……
