### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by frankyzj** [xitu/gold-miner#1002]
我是frankyzj，本科毕业于北京林业大学，现在在一家软件公司做Android开发。啃完《 Educational Psychology Theory and Practice》后，英文水平突飞猛进，有段时间每天翻译“Human of New York”。现在经常游荡在developer.android.com、github和stackoverflow，有阅读英文原著的习惯。希望能够加入计划，共同学习进步。

**Comment by waychane** [comment]
@frankyzj Hi，感谢支持掘金翻译计划，有没有个人博客，或者之前的翻译作品看看呢？

**Comment by frankyzj** [comment]
https://frankyzj.gitbooks.io/android/content/chapter1.html，这是我前几天翻译的Android开发者文档

**Comment by frankyzj** [comment]
@waychane 你好，这是我前几天翻译的Android开发者文档，是按照自己的需要翻译的，所以没有所有内容都翻译，https://frankyzj.gitbooks.io/android/content/chapter1.html。

**Comment by waychane** [comment]
@frankyzj Hi，加我微信 waychane，我加你进译者群。
