### ISSUE TITLE
关于程序员被要求做不道德甚至非法的事情的激烈讨论

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1006]
* 原文链接：[Programmers are having a huge discussion about the unethical and illegal things they’ve been asked to do](http://www.businessinsider.com/programmers-confess-unethical-illegal-tasks-asked-of-them-2016-11)
* 掘金链接：[Programmers are having a huge discussion about the unethical and illegal things they’ve been asked to do](http://gold.xitu.io/entry/5833fdcd8ac2470063901c5e)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/programmers-confess-unethical-illegal-tasks-asked-of-them.md)
* PR 地址：#1027
* 文章分类：**反正是编程**

----
* 翻译时间：`4` 天
* 校对时间：`2` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by phxnirvana** [comment]
我推的我领~

**Comment by sqrthree** [comment]
@phxnirvana Go ahead.

**Comment by sqrthree** [comment]
@phxnirvana 小哥，这篇进度如何了呀

**Comment by phxnirvana** [comment]
#1027
