### ISSUE TITLE
简明 TensorFlow 教程 —— 第一部分：基础知识

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1007]
* 原文链接：[TensorFlow in a Nutshell — Part One: Basics](https://medium.com/@camrongodbout/tensorflow-in-a-nutshell-part-one-basics-3f4403709c9d#.y95bdu5wy)
* 掘金链接：[TensorFlow in a Nutshell  —  Part One: Basics](http://gold.xitu.io/entry/5836a0ee128fe178553e85a6)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/tensorflow-in-a-nutshell-part-one-basics.md)
* PR 地址：#1028
* 文章分类：**Python**
----
#### 关联任务：

* 第二部分：#1008

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
@sqrthree 反正也没有人翻译，我准备承包这个系列了。

**Comment by sqrthree** [comment]
@yifili09 好样的~ 给你点赞 💯

**Comment by yifili09** [comment]
[计算图？](http://www.open-open.com/lib/view/open1441541390219.html)

**Comment by cdpath** [comment]
认领～

**Comment by sqrthree** [comment]
@cdpath  好的

**Comment by sqrthree** [comment]
@cdpath 这篇文章的进度怎么样了？

**Comment by cdpath** [comment]
来啦来啦 https://github.com/xitu/gold-miner/pull/1028

**Comment by sqrthree** [comment]
棒棒哒

**Comment by cdpath** [comment]
最近太忙啦。已经分享到[掘金](https://gold.xitu.io/entry/5850c11cac502e0067cd7ea5/detail)。
@sqrthree
