### ISSUE TITLE
简明 TensorFlow 教程 —第二部分：混合学习

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1008]
* 原文链接：[TensorFlow in a Nutshell — Part Two: Hybrid Learning](https://chatbotnewsdaily.com/tensorflow-in-a-nutshell-part-two-hybrid-learning-98c121d35392#.5mqhrid6c)
* 掘金链接：[TensorFlow in a Nutshell — Part Two: Hybrid Learning](http://gold.xitu.io/entry/5836aa4e880741006c095410)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/tensorflow-in-a-nutshell-part-two-hybrid-learning.md)
* PR 地址：#1046
* 文章分类：**Python**
----
#### 关联任务：

* 第一部分：#1007

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
@sqrthree 反正也没有人翻译，我准备承包这个系列了。

**Comment by sqrthree** [comment]
@yifili09 好样的~ 给你点赞 💯

**Comment by yifili09** [comment]
@sqrthree 我准备去接 「特别任务」去了，这个我还是割爱让给其他人吧。。

**Comment by lovelyCiTY** [comment]
@sqrthree 认领啦

**Comment by sqrthree** [comment]
@lovelyCiTY 好的

**Comment by sqrthree** [comment]
Note. 本篇文章现在仍处于待认领状态.

**Comment by edvardHua** [comment]
之前认领了3，还琢磨着承包这个系列的。

**Comment by edvardHua** [comment]
认领

**Comment by sqrthree** [comment]
@edvardHua 组织要给你发小红花~

**Comment by sqrthree** [comment]
@edvardHua 这篇进度如何了呀

**Comment by edvardHua** [comment]
@sqrthree 今天就交哒。
