### ISSUE TITLE
Swift 面向协议编程，灵丹妙药或是饮鸩止渴？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1009]
* 原文链接：[Protocol Oriented Programming is Not a Silver Bullet](http://chris.eidhof.nl/post/protocol-oriented-programming/)
* 掘金链接：[慎重对待「面向协议编程」](http://gold.xitu.io/entry/583bf09261ff4b007ed30636)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/protocol-oriented-programming.md)
* PR 地址：#1020
* 文章分类：**Swift**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
I like it, and I want it @sqrthree

**Comment by sqrthree** [comment]
@Romeo0906 Go ahead.

**Comment by Romeo0906** [comment]
找半天才找到原来我认领的是这篇

**Comment by sqrthree** [comment]
@Romeo0906 ╭(╯^╰)╮你还没开始翻译
