### ISSUE TITLE
响应式邮件设计

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1010]
* 原文链接：[Can Email Be Responsive?](http://alistapart.com/article/can-email-be-responsive)
* 掘金链接：[响应式邮件设计](http://gold.xitu.io/entry/583bfdc7a22b9d006dcf47a9/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/can-email-be-responsive.md)
* PR 地址：#1030
* 文章分类：**前端**
----
* 翻译时间：`5` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xuzaixian** [comment]
无情认领

**Comment by sqrthree** [comment]
@xuzaixian 好的，顺便看下这个 [wiki](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E8%80%85%E6%93%85%E9%95%BF%E9%A2%86%E5%9F%9F%E8%A1%A8) 哈

**Comment by sqrthree** [comment]
@xuzaixian 这篇文章的进度怎么样了呀

**Comment by xuzaixian** [comment]
@sqrthree  今晚或者明天吧…实在抱歉拖稿了……

**Comment by sqrthree** [comment]
@xuzaixian 好的~ 辛苦啦，没事没事保证质量就好

**Comment by xuzaixian** [comment]
啊啊啊啊  这个好难啊… 有些名词请教外国小伙伴才搞懂。估计校对人员会很辛苦的校对…[PR](https://github.com/xitu/gold-miner/pull/1030)
