### ISSUE TITLE
『特殊任务』macOS Security and Privacy Guide

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1011]
* 原文链接：[macOS Security and Privacy Guide](https://github.com/drduh/macOS-Security-and-Privacy-Guide)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/macOS-Security-and-Privacy-Guide.md)
* 文章分类：**macOS**

---

该篇文章已获作者授权，翻译后会进行投稿到原文仓库。由于该篇文章内容过多，因此需要 3 ~ 4 人进行合作翻译。

**该任务属于特殊任务，对翻译质量要求比较严格，大家申请后需要审核才能进行翻译。**

**Comment by lovelyCiTY** [comment]
@sqrthree 认领~~~

**Comment by ZiXYu** [comment]
@sqrthree 认领~

**Comment by yifili09** [comment]
@sqrthree 抢座位!

**Comment by MAYDAY1993** [comment]
认领

**Comment by DeadLion** [comment]
认领

**Comment by sqrthree** [comment]
@lovelyCiTY @ZiXYu 两位是第一次在翻译计划认领任务么？

**Comment by lovelyCiTY** [comment]
@sqrthree 我昨天完成了一篇文章的校对，之前没有在掘金参加过翻译工作。

**Comment by sqrthree** [comment]
@lovelyCiTY 这篇文章属于特殊任务，要求比普通文章高一些~ 你要是感兴趣的话可以参与这篇文章的校对工作哈

**Comment by lovelyCiTY** [comment]
@sqrthree  好，那这个文章的翻译我不参与翻译了，因为我本身就是做iOS的所以还是挺希望参与翻译的。给我留个校对的坑哈~~~

**Comment by sqrthree** [comment]
@lovelyCiTY 好的

**Comment by sqrthree** [comment]
@lovelyCiTY @ZiXYu 两位如果没翻译过的话可以先认领篇感兴趣的文章翻译哈，[传送门](https://github.com/xitu/gold-miner/issues?q=is%3Aissue+is%3Aopen+label%3A%E6%96%87%E7%AB%A0%E8%AE%A4%E9%A2%86)

**Comment by ZiXYu** [comment]
@sqrthree 好的~

**Comment by Danny1451** [comment]
传说中的 精英任务嘛  占个坑哈 😏

**Comment by sqrthree** [comment]
@Danny1451 哈哈，来晚了啦，下次早点嘛

**Comment by sqrthree** [comment]
文章地址：https://github.com/xitu/macOS-Security-and-Privacy-Guide/blob/master/README-cn.md
