### ISSUE TITLE
代码复用的风险性

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1013]
* 原文链接：[The perils of shared code](https://www.innoq.com/en/blog/the-perils-of-shared-code)
* 掘金链接：[代码复用，一定要小心](https://gold.xitu.io/entry/583bfed661ff4b006cc34a94/detail)
* Markdown文件：[文章地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-perils-of-shared-code.md)
* PR 地址：#1022
* 文章分类：**编程**
---

* 翻译时间：`4` 天
* 校对时间：`2` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gocy015** [comment]
我要我要～ @sqrthree

**Comment by sqrthree** [comment]
@Gocy015 好的
