### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by FrankXiong** [xitu/gold-miner#1015]
你好，我叫FrankXiong，重庆大学计算机科学与技术专业大四学生。具有较好的英语基础，英语六级，经常访问Github/Stackoverflow/Medium社区，有完整阅读英语原著和翻译技术文章的经验。我的博客voidman.xyz,希望能互相交流学习。

**Comment by waychane** [comment]
Hi，添加掘金翻译计划的负责人（微信：L-511249910），他会加你进译者群。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `L-511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，方便拉你进译者群。
