### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Germxu** [xitu/gold-miner#1016]
你好，我叫Germxu，郑州轻工业学院本科生，Frontend Programmer，面向Google编程。具有较好的英语基础，英语六级，经常访问Github/Quora/Google Developer，习惯阅读翻译技术文档。我的博客 funxu.cc，偶有发布喜爱文章，希望能互相交流学习。

**Comment by waychane** [comment]
Hi，添加掘金翻译计划的负责人（微信：L-511249910），他会加你进译者群。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `L-511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，方便拉你进译者群。
