### ISSUE TITLE
英文 6级， 安卓开发6年了。现在阿里，准备定个计划，每天翻译一篇英文

### ISSUE THREAD

**Issue by gybin02** [xitu/gold-miner#102]
英文 6级， 安卓开发6年了。现在阿里，准备定个计划，每天翻译一篇英文

**Comment by Glowin** [comment]
哇咔咔，不错啊，欢迎加入我们翻译计划。加我微信 Glowjiang

**Comment by Glowin** [comment]
你好，请问你有没有加我微信好友呢？

**Comment by Glowin** [comment]
@gybin02 早上好，我们又有一批新的文章等待你的翻译，欢迎来认领文章，谢谢啦。
