### ISSUE TITLE
如何用 Sketch 打造「前端框架」

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1024]
* 原文链接：[How to create a FRONT END FRAMEWORK with Sketch](https://medium.com/sketch-app-sources/how-to-create-a-front-end-framework-with-sketch-2379edb5e7df#.r6g3tx6wk)
* 掘金链接：[掘金翻译计划](https://github.com/xitu/gold-miner)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-create-a-front-end-framework-with-sketch.md)
* PR 地址：#1042
* 文章分类：**设计**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ruixi** [comment]
来了来了！！！

**Comment by sqrthree** [comment]
@Ruixi 终于等到你~

**Comment by Ruixi** [comment]
翻译初稿完成～
https://github.com/xitu/gold-miner/pull/1042/files
