### ISSUE TITLE
CSS 继承深度解析

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1032]
* 原文链接：[CSS Inheritance, The Cascade And Global Scope: Your New Old Worst Best Friends](https://www.smashingmagazine.com/2016/11/css-inheritance-cascade-global-scope-new-old-worst-best-friends)
* 掘金链接：[[英] CSS 继承深度解析](https://gold.xitu.io/entry/583fe5232f301e005cf5a47b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/css-inheritance-cascade-global-scope-new-old-worst-best-friends.md)
* PR 地址：#1060
* 文章分类：**前端**
----
* 翻译时间：`5` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by llp0574** [comment]
我来

**Comment by sqrthree** [comment]
@llp0574 好的~

**Comment by sqrthree** [comment]
@llp0574 这篇文章的进度如何了？

**Comment by llp0574** [comment]
[PR](https://github.com/xitu/gold-miner/pull/1060)
