### ISSUE TITLE
如何在 Swift 3 中用 Spirit Kit 框架编写游戏 (Part 1)

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1033]
* 原文链接：[How To Build A SpriteKit Game In Swift 3 (Part 1)](https://www.smashingmagazine.com/2016/11/how-to-build-a-spritekit-game-in-swift-3-part-1/)
* 掘金链接：[如何在 Swift 3 中用 Spirit Kit 框架编写游戏](https://gold.xitu.io/entry/583ec23c128fe1006bfa687a/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-build-a-spritekit-game-in-swift-3-part-1.md)
* PR 地址：#1056
* 文章分类：**iOS**
----
#### 关联任务：

* 第二部分：#1039
* 第三部分：#1068

----
* 翻译时间：`5 ~ 6` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gocy015** [comment]
@sqrthree ，可不可以先认领了，过两天不那么忙了我再跟一遍教程 & 翻译

**Comment by sqrthree** [comment]
@Gocy015 这篇文章比较长，你估计一下大概什么时候能完成翻译哈。

**Comment by Gocy015** [comment]
@sqrthree  ,我只能说这周六晚之前肯定把part1给翻译完。。第二部分我就不知道了，因为不知道下周会多忙

**Comment by sqrthree** [comment]
@Gocy015 好的~ 那你先翻译第一部分吧~ 第二部分看看有人认领没再说~
