### ISSUE TITLE
使用强大的调查技巧了解用户的动机

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1036]
* 原文链接：[USE THESE POWERFUL RESEARCH TECHNIQUES TO UNDERSTAND WHAT MOTIVATES YOUR USERS](http://blog.invisionapp.com/generative-research-ux/)
* 掘金链接：[[英] 理解你的用户动机](https://gold.xitu.io/entry/583d546ca22b9d006a9362b8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/generative-research-ux.md)
* PR 地址：#1044
* 文章分类：**设计**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
@sqrthree I think I've found a cute girl~ Can I have her?

**Comment by sqrthree** [comment]
@Romeo0906 Sure, go ahead.

**Comment by Romeo0906** [comment]
明天翻好啊~这两天比较忙，都没动呢 @sqrthree
