### ISSUE TITLE
如何建立高效推送通知

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1037]
* 原文链接：[How to create effective push notifications](https://blog.intercom.com/create-effective-push-notifications/)
* 掘金链接：[如何让推送通知更有效？](https://github.com/xitu/gold-miner/blob/master/TODO/create-effective-push-notifications.md)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/commit/08a4d1073d4621f4652742d6ddad5ef426fcd5d2)
* PR 地址：#1052
* 文章分类：**产品**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by acechao** [comment]
终于等到产品相关的啦，来认领

**Comment by sqrthree** [comment]
@acechao 新译者要从校对任务开始哟~

**Comment by phxnirvana** [comment]
如果ls是新人的话我来横刀夺爱（滑稽.jpg

**Comment by sqrthree** [comment]
@phxnirvana 好的

**Comment by sqrthree** [comment]
@acechao 可以先看看待认领的校对任务里有没有感兴趣的哈~ 校对一篇之后就可以认领翻译任务啦

**Comment by sqrthree** [comment]
@phxnirvana 这篇文章的进度如何了

**Comment by phxnirvana** [comment]
@sqrthree #1052 完工
