### ISSUE TITLE
如何在 Swift 3 中用 SpriteKit 框架编写游戏 (Part 2)

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1039]
* 原文链接：[ How To Build A SpriteKit Game In Swift 3 (Part 2) ](https://www.smashingmagazine.com/2016/12/how-to-build-a-spritekit-game-in-swift-3-part-2/ )
* 掘金链接：[如何在 Swift 3 中用 Spirit Kit 框架编写游戏（第二部分）](https://gold.xitu.io/entry/58498238128fe100690daa93)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-build-a-spritekit-game-in-swift-3-part-2.md)
* PR 地址：#1059
* 文章分类：**iOS**
----
#### 关联任务：

* 第一部分：#1033
* 第三部分：#1068

----
* 翻译时间：`5` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZiXYu** [comment]
领~

**Comment by sqrthree** [comment]
@ZiXYu 好的~ 顺便看下这个 [wiki](https://github.com/xitu/gold-miner/wiki/译者擅长领域表) 哈

**Comment by ZiXYu** [comment]
@sqrthree 好的呀~

**Comment by Gocy015** [comment]
@ZiXYu  , hello , 我是这篇文章第一部分的译者，和你共同定一个标题的译名吧？

我的想法是：如何用 Swift 3 以及 SpriteKit 框架编写游戏。

你觉得可以吗

**Comment by ZiXYu** [comment]
@Gocy015 我觉得按照标题来的话 “如何在 Swift 3 中用 SpriteKit 框架编写游戏” 就挺好的，因为 SpriteKit 是基于 Swift 的框架，翻译成 Swift 3 及 SpriteKit 会有点奇怪。

**Comment by Gocy015** [comment]
@ZiXYu 好的

**Comment by Gocy015** [comment]
@ZiXYu  ，还有一个问题，原作者文章中有许多 Github 无法正确解析的脚注跳转，你是怎么处理的？

**Comment by Gocy015** [comment]
@ZiXYu ，还要和你统一一下一些词语的翻译，这些词略偏术语，不确定第二篇是否出现，和你对一下：

physics body --> 物理实体
scene --> 场景
node --> 结点
world boundary --> 全局边界
SpriteKit scene editor (SKS) file  --> SpriteKit 场景编辑器文件
sprite --> 精灵
texture --> 纹理

**Comment by ZiXYu** [comment]
@Gocy015 跳转我还没有检查~等我全部翻完以后再看一下~要有好的解决方案记得告诉我呀
术语我们翻得基本一样~很赞

**Comment by Gocy015** [comment]
@ZiXYu ，跳转链接。。 要不就改成普通样式吧，好像 github 页内跳转挺麻烦的
