### ISSUE TITLE
Google Cloud Functions 文档

### ISSUE THREAD

**Issue by Glowin** [xitu/gold-miner#104]
文章链接：[What are Google Cloud Functions? - Cloud Functions — Google Cloud Platform](https://cloud.google.com/functions/docs)
掘金链接：[稀土掘金：Google Cloud Functions](http://gold.xitu.io/entry/56bae984128fe10052f9ce77)
文档列表：

- [x] [Quickstarts - Guides](https://cloud.google.com/functions/docs)
- [x] [Getting Started](https://cloud.google.com/functions/getting-started)
- [x] [Writing Cloud Functions](https://cloud.google.com/functions/writing)
- [x] [Deploying Cloud Functions](https://cloud.google.com/functions/deploying)
- [x] [Calling Cloud Functions](https://cloud.google.com/functions/calling)
- [x] [Walkthroughs](https://cloud.google.com/functions/walkthroughs)
- [x] [Command Reference](https://cloud.google.com/functions/reference)

PR 校对地址：https://github.com/xitu/gold-miner/pull/116/files?diff=split

**Comment by huanglizhuo** [comment]
认领   
Quickstarts - Guides
Getting Started
Writing Cloud Functions

**Comment by Glowin** [comment]
@huanglizhuo 好的呢，我来把文字版放在 TODO 文件夹里面，这样就可以直接开始翻译啦。

**Comment by huanglizhuo** [comment]
之前认领的翻译完了  我直接在 TODO 文件夹下新建了一个 GoogleCloudFunctions 目录

继续翻译下面的  等全部翻译完发 pr
 Deploying Cloud Functions
 Calling Cloud Functions
 Walkthroughs
 Command Reference

**Comment by huanglizhuo** [comment]
@Glowin 
之前认领的翻译完了 我直接在 TODO 文件夹下新建了一个 GoogleCloudFunctions 目录

继续翻译下面的 等全部翻译完发 pr  :)
Deploying Cloud Functions
Calling Cloud Functions
Walkthroughs
Command Reference

**Comment by Glowin** [comment]
太棒啦，把我要做的内容都给完成了，期待你的 PR。

**Comment by Glowin** [comment]
@xitu/miners 大家对 Google Cloud 感兴趣的欢迎来认领校对，这是 Google Cloud 发布的一个文档。

**Comment by Glowin** [comment]
我花了半个小时把这个文档的 markdown 给整理好，但是不知道为什么 diff 里面还是看不到新添加的文件。

**Comment by huanglizhuo** [comment]
diff 有可能是按照提交时间节点比较  :(  等合并我 pr 是就会有冲突了 得手工解决冲突

**Comment by Glowin** [comment]
嗯哪，你可以尝试merge一下我新增加的文章

**Comment by edvardHua** [comment]
认领校对 澳门科技大学 咨询科技研一学生

**Comment by antonia0912** [comment]
@edvardHua PR 校对地址：https://github.com/xitu/gold-miner/pull/116/files?diff=split  直接在里边添加note就可以咯

**Comment by edvardHua** [comment]
@antonia0912 好的，谢谢！

**Comment by antonia0912** [comment]
@edvardHua 你是不是还没有加入我们的译者群  你可以加我微信 antonia0912  然后我来拉你进译者群哈

**Comment by CoderBOBO** [comment]
改完了这篇文章

**Comment by antonia0912** [comment]
辛苦各位啦   @huanglizhuo @edvardHua @CoderBOBO   蟹蟹对掘金翻译计划的支持
