### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Zhiw** [xitu/gold-miner#1040]
学校：电子科技大学
工作内容：Android 开发
常浏览的国外网站：Google , StackOverflow , developer.android.com , medium
英语水平：六级
翻译经验：无
个人博客：http://yuzhiw.com
补充：目前毕业在做 Android 开发，没有翻译经验，但很想为社区做贡献，也想提高自己的英语水平与专业能力。希望将技术前沿文章分析给大家，一起玩耍，一起进步。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
