### ISSUE TITLE
GitHub 是如何防治网络暴力的

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1043]
* 原文链接：[What GitHub did to kill its trolls](http://fusion.net/story/369325/how-to-stop-online-harassment/)
* 掘金链接：[GitHub 是如何防治网络暴力的](https://gold.xitu.io/entry/584a977dac502e00691d6593)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-stop-online-harassment.md)
* PR 地址：#1065
* 文章分类：**后端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wild-flame** [comment]
这篇文章可以认领么？

**Comment by sqrthree** [comment]
@wild-flame 好的

**Comment by wild-flame** [comment]
在翻译ing

**Comment by wild-flame** [comment]
@sqrthree 翻译完啦…这是我翻译过的最难的一篇文章，还麻烦校对多看看：D
