### ISSUE TITLE
为何而设计？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1045]
* 原文链接：[Why Design](https://medium.com/the-year-of-the-looking-glass/why-design-f3c8546c9672)
* 掘金链接：[为什么要设计？]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-design.md)
* PR 地址：#1058
* 文章分类：**设计**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
又一篇产品类的文章，其实我是拒绝的，但其实我是没得选择的 Come on~ @sqrthree

**Comment by sqrthree** [comment]
@Romeo0906 哈哈哈好的好的
