### ISSUE TITLE
Android 中的 Effective Java(速查表)

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1047]
* 原文地址：[Effective Java for Android (cheatsheet) ](https://medium.com/rocknnull/effective-java-for-android-cheatsheet-bf4e3433889a#.hmlqxkmzh)
* 掘金链接：[Effective Java for Android (cheatsheet)]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/effective-java-for-android-cheatsheet.md)
* PR 地址：#1055
* 文章分类：**Android**
----

* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jamweak** [comment]
认领。

**Comment by sqrthree** [comment]
@jamweak 好哒

**Comment by jacksonke** [comment]
校对
