### ISSUE TITLE
直观设计 vs. 共享式设计

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1048]
* 原文链接：[Intuitive Design vs. Shareable Design](https://news.greylock.com/intuitive-design-vs-shareable-design-88ff6bb184bb#.pvcpqeddr)
* 掘金链接：[Intuitive Design vs. Shareable Design](https://gold.xitu.io/entry/584fc339ac502e006c7d4217)
* PR 地址： #1070
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/edit/master/TODO/intuitive-design-vs-shareable-design.md)
* 文章分类：**产品 / 设计**
----

* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by funtrip** [comment]
领一发

**Comment by sqrthree** [comment]
好的👌🏻

**Comment by sqrthree** [comment]
@funtrip  这篇文章还没翻译好么？
