### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by uglybachelor** [xitu/gold-miner#1049]
你好，我叫uglybachelor，天津大学通信专业毕业，现在在有信网络任职技术顾问，业余JavaScript开发者。英语流利，曾在国外工作一年，托福114分，曾为美剧字幕精校。常浏览stackoverflow、github、Engadget等国外网站。没有专门维护的技术博客，segmentdefault专栏中有几篇Node相关的译文。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O

**Comment by sandytt** [comment]
你好，我叫 coolfe，在六度人和担任前端工程师，有空会去浏览 medium，英语水平是4级 ，没有翻译经验，没有专门维护的技术博客。

**Comment by sqrthree** [comment]
@uglybachelor  @sandytt Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O

**Comment by JerryMissTom** [comment]
hi,我叫JerryMissTom，在一家外企担任mobile app developer，前端初学者，英语6级水平，暂无翻译经验，暂无专门维护的博客。

**Comment by sqrthree** [comment]
@JerryMissTom Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O

**Comment by sqrthree** [comment]
我关闭这个 Issue 啦，免得以后的新译者在这里接龙了 _(:з」∠)_
