### ISSUE TITLE
渐进增强的 Web AMP

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1050]
* 原文链接：[Progressive Web AMPs](https://www.smashingmagazine.com/2016/12/progressive-web-amps)
* 掘金链接：[Progressive Web AMPs]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/progressive-web-amps.md)
* PR 地址：#1064
* 文章分类：**前端**
----

* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by L9m** [comment]
认领

**Comment by sqrthree** [comment]
@L9m 好的

**Comment by sqrthree** [comment]
@L9m 这篇文章的进度如何了呀
