### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by sulihuang** [xitu/gold-miner#1051]
你好， 我是小米前端工程师苏理煌。 我平时喜欢看一些国外网上的资料，包括medium stackoverflow sitepoint css-tricks等， 有时候看到经典的也会进行翻译分享到掘金。 我经常看掘金翻译计划相关的文章，我也希望能成为其中一员，一起进步

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
