### ISSUE TITLE
高效的工程师一步一步来 —— 开发者影响力中的模式

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1053]
* 原文链接：[Prolific Engineers Take Small Bites](https://blog.gitprime.com/check-in-frequency-and-codebase-impact-the-surprising-correlation/)
* 掘金链接：[Prolific Engineers Take Small Bites](https://gold.xitu.io/entry/58520d398e450a006c4bdf56)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/check-in-frequency-and-codebase-impact-the-surprising-correlation.md)
* PR 地址：#1071
* 文章分类：**编程**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cdpath** [comment]
我来吧~

**Comment by sqrthree** [comment]
@cdpath 好的
