### ISSUE TITLE
在算法横行的时代，我们更需要人类来把关

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1061]
* 原文链接：[In the age of the algorithm, the human gatekeeper is back](https://www.theguardian.com/technology/2016/sep/30/age-of-algorithm-human-gatekeeper)
* 掘金链接：[在算法横行的时代，我们更需要人类来把关](https://gold.xitu.io/entry/5857a3741b69e6006ca68ad0)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/age-of-algorithm-human-gatekeeper.md)
* PR 地址：#1073
* 文章分类：**后端**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by AceLeeWinnie** [comment]
我来吧

**Comment by sqrthree** [comment]
@AceLeeWinnie 好的

**Comment by AceLeeWinnie** [comment]
@sqrthree  翻译完成
#1073
