### ISSUE TITLE
容器时代的分布式日志架构

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1062]
* 原文链接：[Distributed Logging Architecture in the Container Era](https://blog.treasuredata.com/blog/2016/08/03/distributed-logging-architecture-in-the-container-era/)
* 掘金链接：[容器时代的分布式日志架构](https://gold.xitu.io/entry/5857a96a128fe10069a7f17e/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/distributed-logging-architecture-in-the-container-era.md)
* PR 地址：#1091
* 文章分类：**后端**
----
* 翻译时间：`5` 天
* 校对时间：`2` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Airmacho** [comment]
认领

**Comment by sqrthree** [comment]
@Airmacho  好的

**Comment by sqrthree** [comment]
@Airmacho 这篇的进度如何了呀

**Comment by Airmacho** [comment]
@sqrthree 不好意思，这两天比较忙，我明天把这个推上去

**Comment by sqrthree** [comment]
好的

**Comment by GiggleAll** [comment]
校对

**Comment by sqrthree** [comment]
好的👌🏻

**Comment by sqrthree** [comment]
@GiggleAll PR地址是 #1091 哈，校对的方式是直接在 PR 下 review  哈

**Comment by GiggleAll** [comment]
收到
