### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by imink** [xitu/gold-miner#1063]
你好, 我叫imink, 刚刚从UCL计算机网络系统专业毕业, 在英国留学3年. 英语交流无障碍, 目前自由职业, 对Web应用开发感兴趣. 经常浏览的社区: V2EX, HN News, StackOverFlow. 

有翻译过若干技术文章: [Extracting meaningful content from raw HTML](https://www.evernote.com/l/AIeekWF83EpMoZPIe2rZiiDVJSjkRAiE9iw), [How to Create Your Own PHP Framework](https://www.evernote.com/shard/s135/sh/aa27d8c4-7714-44a9-abb5-8fb8c99ed454/789ecb6e880b03ff) (未经排版)

非常希望通过翻译技术文章, 认识一群志同道合的朋友.

**Comment by sqrthree** [comment]
@imink Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
