### ISSUE TITLE
网络请求框架 Retrofit 2 使用详解

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1066]
* 原文链接：[Get Started With Retrofit 2 HTTP Client](https://code.tutsplus.com/tutorials/getting-started-with-retrofit-2--cms-27792)
* 掘金链接：[[英] Get Started With Retrofit 2 HTTP Client](https://gold.xitu.io/entry/58593abd61ff4b006cbb8559/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/getting-started-with-retrofit.md)
* PR 地址：#1072
* 文章分类：**Android**
----
* 翻译时间：`4` 天
* 校对时间：`2` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zhiw** [comment]
第一次翻译认领

**Comment by sqrthree** [comment]
@Zhiw 棒棒哒~ 有问题可以随时问我哈

**Comment by draftbk** [comment]
要怎么认领，规则没看完呢！

**Comment by draftbk** [comment]
认领校对

**Comment by sqrthree** [comment]
@draftbk 棒棒哒~ 💯

**Comment by draftbk** [comment]
@sqrthree 哈哈哈~

**Comment by sqrthree** [comment]
@draftbk 这是校对地址啊，[pull/1072/files](https://github.com/xitu/gold-miner/pull/1072/files)

**Comment by draftbk** [comment]
@sqrthree 好的！
