### ISSUE TITLE
如何在 Swift 3 中用 Spirit Kit 框架编写游戏 (Part 3) 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1068]
* 文章链接：[How To Build A SpriteKit Game In Swift 3](https://www.smashingmagazine.com/2016/12/how-to-build-a-spritekit-game-in-swift-3-part-3/)
* 掘金链接：[How To Build A SpriteKit Game In Swift 3]()
* markdown文件：[文章地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-build-a-spritekit-game-in-swift-3-part-3.md)
* PR 地址：#1083
* 文章分类：**iOS**
----
#### 关联任务：

* 第一部分：#1033
* 第二部分：#1039
----

* 翻译时间：`5 ~ 6` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeepMissea** [comment]
@sqrthree 认领。

**Comment by sqrthree** [comment]
@DeepMissea  好的

**Comment by Gocy015** [comment]
@DeepMissea ，壮士！

**Comment by sqrthree** [comment]
点个赞
