### ISSUE TITLE
Design words with data

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1069]
* 原文链接：[Design words with data](https://medium.com/dropbox-design/design-words-with-data-fe3c525994e7#.75tkuz1xw)
* 掘金链接：[Design words with data]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/design-words-with-data.md)
* PR 地址：#1095
* 文章分类：**设计 / 产品**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
@sqrthree  收一篇。

**Comment by sqrthree** [comment]
@yifili09 好哒

**Comment by sqrthree** [comment]
@yifili09 这篇的进度如何了呀

**Comment by yifili09** [comment]
@sqrthree 最近休假给忘记了。。 😿 😿 再给我几天时间，赶工出来。

**Comment by sqrthree** [comment]
😯 😠

**Comment by sqrthree** [comment]
@yifili09 大概什么时候能交稿啊？

**Comment by yifili09** [comment]
@sqrthree 抱歉了，年末事情多 -。-
