### ISSUE TITLE
React or Vue: Which Javascript UI Library Should You Be Using?

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1074]
* 原文链接：[React or Vue: Which Javascript UI Library Should You Be Using?](https://medium.com/js-dojo/react-or-vue-which-javascript-ui-library-should-you-be-using-543a383608d#.h4msj6qsw)
* 掘金链接：[选择 Vue 还是 React](https://gold.xitu.io/entry/585ca8ffda2f60006580fa78/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/react-or-vue-which-javascript-ui-library-should-you-be-using.md)
* PR 地址：待添加
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by llp0574** [comment]
get

**Comment by sqrthree** [comment]
@llp0574 好的

**Comment by sqrthree** [comment]
_(:з」∠)_ 发现 [译文](https://zhuanlan.zhihu.com/p/24548677) 了，so~ I have to close it.
