### ISSUE TITLE
10 things I learned making the fastest site in the world

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1075]
* 原文链接：[10 things I learned making the fastest site in the world](https://hackernoon.com/10-things-i-learned-making-the-fastest-site-in-the-world-18a0e1cdf4a7#.rrk6z37hk)
* 掘金链接：[10 things I learned making the fastest site in the world]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/10-things-i-learned-making-the-fastest-site-in-the-world.md)
* PR 地址：待添加
* 文章分类：**前端**
----
* 翻译时间：`6` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Airmacho** [comment]
认领

**Comment by sqrthree** [comment]
@Airmacho 好的

**Comment by sqrthree** [comment]
发现了网上存在 [译文](https://zhuanlan.zhihu.com/p/24577980)，已和译者沟通过。
