### ISSUE TITLE
使用约束控件创建界面

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1076]
* 原文链接：[Building interfaces with ConstraintLayout](https://medium.com/google-developers/building-interfaces-with-constraintlayout-3958fa38a9f7#.r8rz263y9)
* 掘金链接：[Building interfaces with ConstraintLayout]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/building-interfaces-with-constraintlayout.md)
* PR 地址： #1084
* 文章分类：**Android**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
我又来晚了，但好像并没有什么影响，哈哈 @sqrthree

**Comment by sqrthree** [comment]
@Romeo0906 哈哈哈~ 棒棒哒
