### ISSUE TITLE
Android Studio Tips 文章中有个姿势不对

### ISSUE THREAD

**Issue by act262** [xitu/gold-miner#1078]
原文这里 https://github.com/xitu/gold-miner/blob/master/TODO/Android-Studio-Tips.md
第53个`扩大选择（Shrink Selection）`姿势不对,
正确的姿势是这个:
扩大选择(Extend Selection) `Ctrl+W`
缩小选择(Shrink Selection) `Ctrl+Shift+W`

**Comment by sqrthree** [comment]
@act262 Thanks for your feedback, I will correct it at once.
