### ISSUE TITLE
在 Node.js 和 C++ 之间使用 Buffer 共享数据

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1079]
* 原文链接：[Using Buffers to share data between Node.js and C++](https://community.risingstack.com/using-buffers-node-js-c-plus-plus/)
* 掘金链接：[Using Buffers to share data between Node.js and C++]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/using-buffers-node-js-c-plus-plus.md)
* PR 地址：#1098
* 文章分类：**后端 Node**
----
* 翻译时间：`5` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by AceLeeWinnie** [comment]
认领

**Comment by sqrthree** [comment]
好

**Comment by AceLeeWinnie** [comment]
@sqrthree  #1098
