### ISSUE TITLE
认领faster-photos-in-facebook-for-ios

### ISSUE THREAD

**Issue by bobmayuze** [xitu/gold-miner#108]
我是Bob！
[伦斯勒理工新生一枚，个人[blog](bobmayuze.github.io)
希望能翻译这篇文章－ －个位大大多多指教

**Comment by Glowin** [comment]
好的呢，我来给你添加到 README 里面，你可以直接开始翻译啦。

**Comment by SatanWoo** [comment]
我是satanwoo，上海交大学生一枚，个人<a href = "http://satanwoo.github.io">博客</a>，这篇文章还需要人校对吗？

**Comment by bobmayuze** [comment]
嗯嗯，需要的！

**Comment by SatanWoo** [comment]
那我能认领不？

**Comment by bobmayuze** [comment]
果断走起啊哥们儿！

**Comment by antonia0912** [comment]
@SatanWoo 兄弟~校对的怎么样啦

**Comment by SatanWoo** [comment]
@antonia0912 不是已经校对完了吗？

https://github.com/xitu/gold-miner/pull/115#issuecomment-187568551

**Comment by Tuccuay** [comment]
认领校对 😘

**Comment by Tuccuay** [comment]
1. line 8 [#r53793385](https://github.com/xitu/gold-miner/pull/115/files?diff=split#r53793385)
 - 「这其中有些照片是你想要在手机进行浏览的」
 - 改为「也许你会想要在手机上也能重温那些场景」
2. line 14 [#r53793871](https://github.com/xitu/gold-miner/pull/115/files?diff=split#r53793871)
 - 「照片的链接首先会被获取」
 - 改为「我们先拿到这个图片的所有链接」
 - (因为原文使用 **"URLs"**，说明 **不止有一个** 链接被获取，并且下文提到同时下载多个图片)
3. line 17 [#r53794364](https://github.com/xitu/gold-miner/pull/115/files?diff=split#r53794364)
 - 「储存在用户的硬盘中」
 - 改为「储存在设备的闪存中」
4. line 29 [#r53795017](https://github.com/xitu/gold-miner/pull/115/files?diff=split#r53795017)
 - 原文：「数据消耗：PJPEG使得我们可以无需下载小尺寸的图片的过程。」
 - [#r53773386](https://github.com/xitu/gold-miner/pull/115/files?diff=split#r53773386) by [nathanwhy](https://github.com/nathanwhy) 「数据消耗：使用PJPEG无需下载小尺寸的图片。」
 - 「数据消耗：使用 PJPEG 让我们无需再额外下载一个小尺寸的图片。」

**Comment by nathanwhy** [comment]
额  难道审核要这里先认领？我昨晚已经审核了。

**Comment by antonia0912** [comment]
@nathanwhy 要先留言 认领校对 哎。。。。

**Comment by antonia0912** [comment]
辛苦译者 @bobmayuze 和三位校对者啦 @SatanWoo @nathanwhy @Tuccuay ~~~
