### ISSUE TITLE
为 Async-Await 唱一曲赞歌

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1080]
* 原文链接：[An Ode to Async-Await](https://hackernoon.com/an-ode-to-async-await-7da2dd3c2056#.xyj5kw3zh)
* 掘金链接：[An Ode to Async-Await]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/an-ode-to-async-await.md)
* PR 地址：#1096
* 文章分类：**后端 Node**
----
* 翻译时间：`5` 天
* 校对时间：`2` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xekri** [comment]
额，想认领这篇，虽然不是后端 Node 程序员，但是这是 ES7 里面很重要的特性啊，想深入了解一下。

**Comment by sqrthree** [comment]
@xekri 好的~ 注意保证翻译质量哈~

**Comment by xekri** [comment]
翻译完成 #1096
