### ISSUE TITLE
React Native at WalmartLabs

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1081]
* 原文链接：[React Native at WalmartLabs](https://medium.com/walmartlabs/react-native-at-walmartlabs-cdd140589560#.evyi919yl)
* 掘金链接：[React Native at WalmartLabs](https://gold.xitu.io/entry/58625fbb1b69e6006ce93c1a/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/react-native-at-walmartlabs.md)
* PR 地址：#1085
* 文章分类：**前端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by draftbk** [comment]
想收🌝

**Comment by sqrthree** [comment]
@draftbk 好的

**Comment by draftbk** [comment]
@sqrthree 第一次翻译~两点半了~应该算翻译完了吧~
