### ISSUE TITLE
书写干净的 CSS 代码 PART1

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1086]
* 原文链接：[How to Write Clean CSS in 10 Simple Steps Pt1](http://blog.alexdevero.com/write-clean-css-10-simple-steps-pt1/)
* 掘金链接：[How to Write Clean CSS in 10 Simple Steps Pt1]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/write-clean-css-10-simple-steps-pt1.md)
* PR 地址：#1099
* 文章分类：**前端**
----
#### 相关任务；
* 第二部分：#1087
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
我要来~

**Comment by Romeo0906** [comment]
@sqrthree

**Comment by sqrthree** [comment]
@Romeo0906 Go ahead.
