### ISSUE TITLE
书写干净的 CSS 代码的十个方法 PART2

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1087]
* 原文链接：[How to Write Clean CSS in 10 Simple Steps Pt2](http://blog.alexdevero.com/write-clean-css-10-simple-steps-pt2/)
* 掘金链接：[How to Write Clean CSS in 10 Simple Steps Pt2]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/write-clean-css-10-simple-steps-pt2.md)
* PR 地址：#1107
* 文章分类：**前端**
----
#### 相关任务；
* 第一部分：#1086
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
这两个可以都给我么？哈哈哈

**Comment by Romeo0906** [comment]
@sqrthree

**Comment by sqrthree** [comment]
@Romeo0906 别拦我，我要给你发大红花。

**Comment by sqrthree** [comment]
@Romeo0906 哈这篇进度如何啦？

**Comment by Romeo0906** [comment]
@sqrthree 本来打算昨天翻译完的，结果昨天晚上迷路了 [Cry] 今天应该差不多

**Comment by Romeo0906** [comment]
@sqrthree 两篇文章不得给一周时间嘛？哈哈哈哈

**Comment by sqrthree** [comment]
嗯嗯好哒
