### ISSUE TITLE
SOLID 原则：权威指南

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1088]
* 原文链接：[SOLID Principles : The Definitive Guide](https://android.jlelse.eu/solid-principles-the-definitive-guide-75e30a284dea#.ythsxr6uh)
* 掘金链接：[SOLID Principles : The Definitive Guide]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/solid-principles-the-definitive-guide.md)
* PR 地址：#1119
* 文章分类：**编程**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sqrthree** [comment]
_(:з」∠)_  我看是 Java 写的，那应该是属于后端了？

**Comment by phxnirvana** [comment]
==我觉得是面向对象之类的。。算语言基础这种

**Comment by XHShirley** [comment]
终于有假期了，我来认领一个。

**Comment by sqrthree** [comment]
@XHShirley 好的

**Comment by sqrthree** [comment]
@XHShirley 这篇文章进度如何啦？

**Comment by XHShirley** [comment]
@sqrthree 今天翻译完了，但是我还需要全部自己过一遍，明天会推上来～

**Comment by sqrthree** [comment]
@XHShirley 恩恩~ 辛苦啦
