### ISSUE TITLE
创建一个移动应用的终极指导

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1089]
* 原文链接：[The Ultimate Guide to Creating a Mobile Application](https://uxplanet.org/the-ultimate-guide-to-creating-a-mobile-application-8e2b265580d9#.55i1ncuse)
* 掘金链接：[The Ultimate Guide to Creating a Mobile Application]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-ultimate-guide-to-creating-a-mobile-application.md)
* PR 地址：#1118
* 文章分类：**产品**
----
* 翻译时间：`6~7` 天
* 校对时间：`2~3` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by phxnirvana** [comment]
收了，作为开年第一篇

**Comment by sqrthree** [comment]
@phxnirvana 妥妥哒

**Comment by sqrthree** [comment]
@phxnirvana 这第一篇开超时了呀小哥

**Comment by phxnirvana** [comment]
@sqrthree Orz长就算了还一堆从句和倒装。。容我再拖一天TAT
