### ISSUE TITLE
认领《如何更高效的使用 okhttp》

### ISSUE THREAD

**Issue by brucezz** [xitu/gold-miner#109]
我是brucezz, 博客在这里 -> [brucezz.github.io/](http://brucezz.github.io/)
之前参与了 [Android-Studio-Tips](https://github.com/xitu/gold-miner/blob/master/TODO/Android-Studio-Tips.md) 部分翻译。

目前在做 Android App 开发，希望翻译此篇文章 ～

:)

**Comment by Glowin** [comment]
好的呢，我来给你添加到 README 里面，你可以直接开始翻译啦。
