### ISSUE TITLE
Vue in 2016

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1090]
* 原文链接：[Vue in 2016](https://medium.com/the-vue-point/vue-in-2016-8df71d98bfb3#.yjphcbkph)
* 掘金链接：[Vue in 2016](https://gold.xitu.io/entry/5864b8c361ff4b006cfd1630)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/vue-in-2016.md)
* PR 地址：
* 文章分类：**前端 Vue**
----
* 翻译时间：当天
* 校对时间：当天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
总有一天，我会驾着七彩祥云来翻译 @sqrthree

**Comment by sqrthree** [comment]
@Romeo0906 棒棒哒
