### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by bensonlove** [xitu/gold-miner#1092]
你好，我是naivebenson。目前在一家金融公司做全栈开发。对iOS、node、vue等技术有着深刻的认识,  经常阅读英文原版资料，也经常游荡在github和stackoverflow上。 本着学习和为服务社区的目的,希望能够加入翻译组。

**Comment by sqrthree** [comment]
你好，请问有翻译经验或者是自己的博客或者体现英语能力之类的么？

**Comment by bensonlove** [comment]
暂无翻译经验, 这是我的博客地址http://blog.csdn.net/baixiangqiang/，很久没更新了。大部分都是看原版英文文档的总结

**Comment by bensonlove** [comment]
暂无翻译经验。这是我的博客地址:http://blog.csdn.net/baixiangqiang/ 很久没更新了。大部分都是看原版英文文档实践之后的总结。

**Comment by sqrthree** [comment]
@bensonlove Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
