### ISSUE TITLE
为什么我关闭了你的 PR

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1093]
* 原文链接：[Why I close PRs (OSS project maintainer notes)](http://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes)
* 掘金链接：[Why I close PRs (OSS project maintainer notes)]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-i-close-prs-oss-project-maintainer-notes.md
)
* PR 地址：#1108
* 文章分类：**编程**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cdpath** [comment]
认领一篇~

**Comment by sqrthree** [comment]
@cdpath 好的

**Comment by sqrthree** [comment]
@cdpath 这篇进度如何了？
