### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ZetaoYang** [xitu/gold-miner#1094]
你好，我叫 Vitzy ，哈尔滨工业大学大三计算机专业学生。英语四六级。解惑经常在 StackOverflow，Github, Medium, Hacker News, Reddit “溜达”。还有国内的 gank.io , liqi.io, sspai.com, 当然也有 掘金 了。
今年就在 [众成翻译](http://zcfy.cc/) 翻译了三篇国外技术文章。个人的技术博客在 https://zetaoyang.github.io 。简书以及 CSDN 也发过几篇文章，不过现在主要维护个人的独立博客。希望能加入稀土翻译计划，提高自己的英文水平以及能够接触到更多国外大牛的文章。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
