### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by GiggleAll** [xitu/gold-miner#1097]
你好，我叫GiggleAll，南阳理工学院软件设计专业，现在在北京微函工坊科技有限公司任职PHP开发工程师。具有较好的英语基础，经常访问Github/Stackoverflow社区，没有完整的翻译经验但有完整阅读英语原著经验。这是我的博客http://blog.csdn.net/qq_28832135   ， 希望能互相交流学习。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
