### ISSUE TITLE
HTTP/2 For Web Developers

### ISSUE THREAD

**Issue by Glowin** [xitu/gold-miner#110]
文章链接：[HTTP/2 For Web Developers](https://blog.cloudflare.com/http-2-for-web-developers/)
掘金链接：[稀土掘金：HTTP/2 For Web Developers](http://gold.xitu.io/entry/56c42070d342d3005dd27d5f)
markdown文件：后续添加

**Comment by geeeeeeeeek** [comment]
@Glowin 直接认领就可以了吗？

**Comment by Glowin** [comment]
@geeeeeeeeek 欢迎co-editor和字幕组的朋友，这篇文章交给你我就放心啦。你直接 fork 一份代码，然后再在 markdown 上翻译，可以看看前面被 merge 的 PR 参考一下。

另外请问这篇文章需要多久能翻译完成呢？

**Comment by geeeeeeeeek** [comment]
@Glowin 周一吧，这个时间可以么？

**Comment by Glowin** [comment]
@geeeeeeeeek 可以的呢，麻烦你加一下我微信 Glowjiang 我来拉你进译者群。

**Comment by geeeeeeeeek** [comment]
@Glowin 我看markdown文件还没有添加，自己add了一个`http2-for-web-developers.md`。说一下，免得重复创建了。

**Comment by Glowin** [comment]
@geeeeeeeeek 赞赞赞，谢谢你替我们的 @antonia0912 妹子完成 markdown 哈

**Comment by geeeeeeeeek** [comment]
@Glowin Translation finished. See PR #124.

**Comment by Evaxtt** [comment]
申请认领校对。

**Comment by Glowin** [comment]
@Evaxtt 你可以进入这个 issue 的校对地址然后直接在 diff 的文章里面添加 note。

**Comment by lekenny** [comment]
举爪

**Comment by antonia0912** [comment]
辛苦两位啦 @geeeeeeeeek @Evaxtt   期待你们后续翻译更多更好的文章
