### ISSUE TITLE
某篇文章的翻译质量投诉！

### ISSUE THREAD

**Issue by lastcc** [xitu/gold-miner#1100]
我平常很少看翻译的资料，昨晚无意间从Google点进GitHub，发现翻译有点问题。我昨晚在GitHub上留了个review。但是我今天又读了下全文，简直就是乱翻。

如果只是少数地方错了，我指出来就算了，但我看到的更多的是译者根本就是毫无责任心。

https://gold.xitu.io/entry/580444efa34131005fe77197?utm_source=gold-miner&utm_medium=readme&utm_campaign=github

https://github.com/xitu/gold-miner/blob/master/TODO/25-core-data-in-ios10-nspersistentcontainer.md

1. 译者没有理解原文的能力。
2. 译者不懂Core Data相关技术，基本IT素养缺乏。
3. 译者没有Google不懂的译处，查阅Core Data文档。
4. 译者没有看文章中的代码。
5. 译者没有责任心。

---

> +多年来，在尝试了很多种 Core Data stack 之后，我们选定了两个简单的 stack，融合成一个使用。

这句严重理解错误。我试着提供一种理解，并不是经过斟酌的译文，当然要翻译得简洁有难点，但是最重要的是【准确】：
长期以来，尝试过多种Core Data Stack配置方式之后，我们认定了一种简单的配置方式：两个context的stack架构，一个context保存(save)时，另一个context合并(merge)变化。

> Over years, after trying many Core Data stacks we have settled on simple two context stack with a merge on save.

其实这句话很好翻译，因为作者提供了代码。任何能看懂基本代码的人都能推断该如何翻译。如果这是一篇阅读理解，那么译者得**零分**：

> 就算作者不提供代码，任何懂Core Data基本配置的人都懂。就算再不懂，花十分钟看下苹果的Programming Guide就能明白stack是什么意思。

1. 代码注册了2个 context-did-save notification.     (**save**)
2. 在上述通知的回调方法中，调用了对方context的mergeChanges方法 (**merge**)

 two context stack with a merge on save - 也就是说，两个context，一个是main, 一个是background, 在一方did save时，另一方context调用merge方法来合并变化。

而且作者居然曾把stack翻译成“堆”，起码也是“栈”吧。

> + ... 他获得 NSManagedObjectModel 的 getter 方法，用它来初始化有我们模型的 NSPersistentStoreCoordinator。
这句话中文处理不正确。
用这个属性获取我们的model，来初始化NSPersistentStoreCoordinator。

...this extracted NSManagedObjectModel getter is used to initialize NSPersistentStoreCoordinator with our model.

> 这就是这些神奇的代码干的事情。

这句理解不正确。This is where翻译错误。
正确翻译应该是：在这里，各个部件之间被连接起来。（下面说了是怎样连接起来的。）
This is where all the wiring up magic is done. 

> 首先，我们创建有模型的 NSPersistentStoreCoordinator

这句翻译错误。首先，我们用model来初始化NSPersitentStoreCoordinator。代码很明确，create，这里就是指初始化，with model这里译者理解错了。
First, we create NSPersitentStoreCoordinator with model.

> 最后，我们在这些文档目录内为某些类型的 NSPersistentStoreCoordinator 增加一个持久化的存储。

最后，为NSPersitentStoreCoordinator添加特定类型的persistent store，persistent store位于文档目录。
Finally we add a persitent store of certain type to NSPersitentStoreCoordinator at documents directory.

特定类型 是指的persistent store，而不是NSPersitentStoreCoordinator。译者语言能力堪忧。

后面还有，我也懒得写了，总之，谁看了这篇译文，谁就看不懂。

**Comment by sqrthree** [comment]
@lastcc 😯 非常感谢您的反馈，我们马上处理这件事情。

**Comment by lastcc** [comment]
@sqrthree 我觉得大家很积极，这很好。但是翻译文章要有克制。每个人都有不懂的地方，懂不懂自己知道，不懂的时候还是不要乱翻。

另外我认为这篇文章原文的含金量就不是很高，比起官方发布的what's new in core data。

**Comment by yifili09** [comment]
@lastcc 
感谢你的指正。首先，我对 Core Data 确实理解不深刻。回看了 PR，大部分的内容也都是进过校对的小伙伴们一起完成的。

@sqrthree 
以后没有把握的主题，我尽量就不抢了。 😢
