### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Luolc** [xitu/gold-miner#1101]
你好，我叫Luolc，北京大学GIS专业，现在担任由你单车技术VP，Android开发者。经常在Gopher、Ruby等开源语言的IRC频道同国外友人探讨问题。常浏览Github/Stackoverflow/Facebook等国外网站。[博客](http://blog.luolc.com)

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
