### ISSUE TITLE
为何我抵制使用缓存？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1102]
* 原文链接：[The Caching Antipattern](https://www.hidefsoftware.co.uk/2016/12/25/the-caching-antipattern/)
* 掘金链接：[The Caching Antipattern](https://gold.xitu.io/entry/586b1f7a128fe1005709ef87)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-caching-antipattern.md)
* PR 地址：#1155
* 文章分类：**后端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
@sqrthree 我喜欢这篇文章，我又来了

**Comment by sqrthree** [comment]
@Romeo0906 太高产了

**Comment by Romeo0906** [comment]
@sqrthree 哈哈，刚被你夸完，最近特别忙，我这篇要晚一点才能做完

**Comment by sqrthree** [comment]
@Romeo0906 好的

**Comment by Romeo0906** [comment]
@sqrthree 我明天做完，么么哒

**Comment by sqrthree** [comment]
好的
