### ISSUE TITLE
防守式编程的艺术

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1103]
* 原文链接：[The Art of Defensive Programming](https://dev.to/0x13a/the-art-of-defensive-programming)
* 掘金链接：[防守式编程的艺术](https://gold.xitu.io/entry/586b20811b69e60063f35f9d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-art-of-defensive-programming.md)
* PR 地址：#1127
* 文章分类：**后端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by imink** [comment]
认领文章. 正好自己也是写PHP的. 文章难度适中, 比较适合自己. THX

**Comment by imink** [comment]
@sqrthree  好的.谢谢.

**Comment by GiggleAll** [comment]
我可以认领了么？已经校对过一篇了。我也是主要用PHP的，要是可以的话，希望认领

**Comment by sqrthree** [comment]
@GiggleAll 恩恩~ 棒棒哒~

**Comment by GiggleAll** [comment]
那我就fork 之后开始翻译了

**Comment by sqrthree** [comment]
恩恩~ 记得新开一个分支哈~ 直接在源文件上修改就好。

**Comment by JeepShen** [comment]
@sqrthree 校对该文章，需要fork么，还是如果有意见的话@翻译的同学，由他修改

**Comment by sqrthree** [comment]
不需要fork哈，直接在 diff 里 comment 就好

**Comment by tanglie1993** [comment]
认领校对

**Comment by sqrthree** [comment]
@tanglie1993 好哒~ 不过下次为了避免冲突还是到 PR 下面申请校对好一点哈~ PR 地址是 #1127
