### ISSUE TITLE
Story Thought and System Thought

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1104]
* 原文链接：[Story Thought and System Thought](https://medium.com/quora-design/story-thought-and-system-thought-188dce7a87e6#.lriaw6doa)
* 掘金链接：[Story Thought and System Thought](https://gold.xitu.io/entry/586b22e7128fe100570a0999)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/story-thought-and-system-thought.md)
* PR 地址：待添加
* 文章分类：**产品**
----
* 翻译时间：`5` 天
* 校对时间：`2` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
@sqrthree 
虽然又被怼了，但是热情不能减啊。 抢一票。

**Comment by sqrthree** [comment]
@yifili09 你不是一个没有故事的男同学~
