### ISSUE TITLE
极简设计最佳实践

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1105]
* 原文链接：[Best Practices for Minimalist Design](https://uxplanet.org/best-practices-for-minimalist-design-7af4a9b61ad7#.duchio78y)
* 掘金链接：[极简设计最佳实践]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/best-practices-for-minimalist-design.md)
* PR 地址：待添加
* 文章分类：**设计**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Germxu** [comment]
虽然项目急得头疼, 我也要忙里偷闲, 来翻译一个,  权当放松了

**Comment by sqrthree** [comment]
@Germxu 新译者要从校对开始哦~

**Comment by funtrip** [comment]
手痒的我又来领取啦~

**Comment by sqrthree** [comment]
@funtrip 妥妥哒

**Comment by sqrthree** [comment]
意外撞车 =,= http://www.uisdc.com/best-practices-for-minimalist-design
