### ISSUE TITLE
设计思考，不只是流行词而已

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1106]
* 原文链接：[Design Thinking, Not Just Another Buzzword](https://blog.prototypr.io/design-thinking-not-just-another-buzzword-3075722b51c8#.g6z3e5oz7)
* 掘金链接：[Design Thinking, Not Just Another Buzzword]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/design-thinking-not-just-another-buzzword.md)
* PR 地址：#1109
* 文章分类：**设计**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by bobmayuze** [comment]
请求翻译

**Comment by sqrthree** [comment]
@bobmayuze 好哒

**Comment by sqrthree** [comment]
辛苦啦
