### ISSUE TITLE
世界级的 Android 测试流程（一）

### ISSUE THREAD

**Issue by Glowin** [xitu/gold-miner#111]
文章链接：[World-Class Testing Development Pipeline for Android - Part 1.](http://blog.karumi.com/world-class-testing-development-pipeline-for-android/)
掘金链接：[稀土掘金：[英] 世界级的 Android 测试流程（一）](http://gold.xitu.io/entry/568a953760b21c09c02c9102)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/world-class-testing-development-pipeline-for-android.md)
PR 地址：#122

此文最好与《世界级的 Android 测试流程（二）》 #112 一起翻译

**Comment by markzhai** [comment]
认领

**Comment by lfkdsk** [comment]
大连理工大二在读，有3年Android开发经验，有个人分享的的技术博客[Blog](http://www.cnblogs.com/lfk-dsk/)，Android原生游戏框架[JustWeEngine](https://github.com/lfkdsk/JustWeEngine)作者，稀土用户，冲着小章鱼手办来的。

**Comment by lfkdsk** [comment]
大连理工大二在读，有3年Android开发经验，有个人分享的的技术博客[Blog](http://www.cnblogs.com/lfk-dsk/)，Android原生游戏框架[JustWeEngine](https://github.com/lfkdsk/JustWeEngine)作者，稀土用户，冲着小章鱼手办来的。

**Comment by Glowin** [comment]
@markzhai 你好，能不能麻烦你介绍自己一下呢，以及翻译相关的经验，谢谢了。

**Comment by markzhai** [comment]
@Glowin 上海交通大学计算机本科，香港科技大学计算机硕士（英语教学）。前腾讯，现阿里Android工程师。

**Comment by Glowin** [comment]
@markzhai 棒棒哒，那这两篇文章就交给您啦。你可以加一下我微信，我来拉你进译者群 Glowjiang。

@lfkdsk 你好，因为这两篇文章是一个系列的，我们希望能让同一个人翻译来保证一致性，所以交给 @markzhai 同学啦。也麻烦你加一下我微信，我来拉你进群。

**Comment by lfkdsk** [comment]
@Glowin 你的微信是？

**Comment by markzhai** [comment]
https://github.com/xitu/gold-miner/pull/122 @Glowin 已完成

**Comment by Glowin** [comment]
@markzhai 辛苦啦，还需要邀请两位译者来审核一下文章呢，审核通过后就可以merge啦。

**Comment by markzhai** [comment]
已经根据第一次https://github.com/lfkdsk校对的意见进行了修改

**Comment by Glowin** [comment]
看到啦，还需要一位译者来校对一下

**Comment by xcc3641** [comment]
申请校对。
