### ISSUE TITLE
在 CSS 中使用恒定角度的斜边

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1110]
* 原文链接：[Sloped edges with consistent angle in CSS](https://kilianvalkhof.com/2017/design/sloped-edges-with-consistent-angle-in-css/)
* 掘金链接：[Sloped edges with consistent angle in CSS]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/sloped-edges-with-consistent-angle-in-css.md)
* PR 地址：#1116
* 文章分类：**CSS**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
@sqrthree 不知道你允不允许我认领两篇，我保证五天之内完成，哈哈

**Comment by sqrthree** [comment]
@Romeo0906 羡慕你有一个好工作 2333
