### ISSUE TITLE
如何为复杂应用设计表单

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1111]
* 原文链接：[Form Design for Complex Applications](https://uxdesign.cc/form-design-for-complex-applications-d8a1d025eba6#.l08bq0kbt)
* 掘金链接：[Form Design for Complex Applications]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/form-design-for-complex-applications.md)
* PR 地址：#1117
* 文章分类：**设计**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by funtrip** [comment]
认领认领，感觉是干货

**Comment by sqrthree** [comment]
@funtrip Just do it.
