### ISSUE TITLE
在 `setState` 中使用函数替代对象

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1112]
* 原文链接：[Using a function in `setState` instead of an object](https://medium.com/@shopsifter/using-a-function-in-setstate-instead-of-an-object-1f5cfd6e55d1#.hwznlbxsa)
* 掘金链接：[Using a function in `setState` instead of an object]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/using-a-function-in-setstate-instead-of-an-object.md)
* PR 地址：#1114
* 文章分类：**前端**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
@sqrthree 轻轻的，我来了~
