### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by jincan39** [xitu/gold-miner#1113]
- ZaojiuTV
- front end dev/software engineer
- feedly,google,facebook,stackoverflow
- 6级
- 暂无
- [chan.science 没用一年多了](chan.science)

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
