### ISSUE TITLE
12 条设计 Buttons 的建议

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1115]
* 原文链接：[Buttons in Design Systems](https://medium.com/eightshapes-llc/buttons-in-design-systems-eac3acf7e23#.u8m3qun1i)
* 掘金链接：[12 条设计 Buttons 的建议](https://gold.xitu.io/entry/5729e44c1ea493006069105e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/buttons-in-design-systems.md)
* PR 地址：#1179
* 文章分类：**设计**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by funtrip** [comment]
认领。妈呀怎么突然这么多文章。

**Comment by sqrthree** [comment]
@funtrip 好的~ 貌似过年了大家都忙着玩呢~ 哈哈哈

**Comment by sqrthree** [comment]
@funtrip 啦啦啦，拥抱工作啦，也该交稿啦
