### ISSUE TITLE
世界级的 Android 测试流程（二）

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#112]
文章链接：[World-Class Testing Development Pipeline for Android - Part 2.](http://blog.karumi.com/world-class-testing-development-pipeline-for-android-part-2/)
掘金链接：[稀土掘金：世界级的 Android 测试流程（二）](http://gold.xitu.io/entry/568bb05d60b24d71fecf80a6)
markdown文件：[文章地址](https://github.com/xitu/gold-miner/blob/master/TODO/world-class-testing-development-pipeline-for-android-part-2.md)

此文最好与《世界级的 Android 测试流程（一）》 #111 一起翻译

**Comment by markzhai** [comment]
认领

**Comment by Glowin** [comment]
@markzhai 请问您是希望和 #111 一起翻译么？

**Comment by markzhai** [comment]
https://github.com/xitu/gold-miner/pull/122 @Glowin 已完成

**Comment by Glowin** [comment]
辛苦啦，再找两位译者来审核一下就好啦。

**Comment by markzhai** [comment]
已经根据第一次https://github.com/lfkdsk校对的意见进行了修改

**Comment by Glowin** [comment]
赞，现在还需要一位译者来校对一下呢

**Comment by xcc3641** [comment]
申请校对。

**Comment by antonia0912** [comment]
@xcc3641 你可以进入这个 issue 的校对地址然后直接在file change 里面添加 note。 因为世界级的 Android 测试流程（二）和（一）是一起的 为了保证翻译的一致性  两篇就都交给你啦  辛苦咯~~~
