### ISSUE TITLE
每一个表单都渴望验证

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1120]
* 原文链接：[Forms Need Validation](https://uxdesign.cc/forms-need-validation-2ecbccbacea1#.qeqexxaek)
* 掘金链接：[Forms Need Validation]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/forms-need-validation.md)
* PR 地址：#1129
* 文章分类：**设计**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZiXYu** [comment]
领~

**Comment by sqrthree** [comment]
@ZiXYu 妥
