### ISSUE TITLE
如何让用户发掘移动应用中的“隐藏”手势

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1121]
* 原文链接：[How To Communicate Hidden Gestures in Mobile App](https://uxplanet.org/how-to-communicate-hidden-gestures-in-mobile-app-e55397f4006b#.po5wdv20m)
* 掘金链接：[How To Communicate Hidden Gestures in Mobile App]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-communicate-hidden-gestures-in-mobile-app.md)
* PR 地址：#1138
* 文章分类：**设计**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gocy015** [comment]
好短，可以认领吗！ @sqrthree 。

**Comment by sqrthree** [comment]
@Gocy015 可以啊
