### ISSUE TITLE
色彩如何影响 UX 和用户行为

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1122]
* 原文链接：[How Color Affects UX And Behavior](https://blog.prototypr.io/how-color-affects-ux-and-behavior-c242c895a8a4#.1p7zujou5)
* 掘金链接：[How Color Affects UX And Behavior]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-color-affects-ux-and-behavior.md)
* PR 地址：#1186
* 文章分类：**设计**
----
* 翻译时间：`5` 天
* 校对时间：`2` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by AceLeeWinnie** [comment]
认领 @sqrthree

**Comment by sqrthree** [comment]
@AceLeeWinnie 好的

**Comment by sqrthree** [comment]
@AceLeeWinnie 进度如何了哈？

**Comment by AceLeeWinnie** [comment]
这二日赶路，明儿哦了


发自网易邮箱大师
在2017年02月03日 17:34，根号三 写道：

@AceLeeWinnie 进度如何了哈？

**Comment by AceLeeWinnie** [comment]
https://github.com/xitu/gold-miner/pull/1186
@sqrthree 翻译完成~
