### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by breadcrumbzsy** [xitu/gold-miner#1123]
- 公司/学校：山东大学
- 工作内容/专业：软件工程
- 常浏览的国外网站：Quora
- 英语水平：四六级、托福84
- 有无翻译经验：无
- 个人博客：http://blog.csdn.net/breadcrumb
- 个人介绍：对数据科学等方向比较感兴趣，学习过程中发现英文资料比中文资料多太多了，而且顺便可以练习英语，哈哈~

**Comment by sqrthree** [comment]
@breadcrumbzsy Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O

**Comment by draftbk** [comment]
@sqrthree 哈哈哈

**Comment by sqrthree** [comment]
这可能是我回应最及时的译者申请了。

**Comment by draftbk** [comment]
那承认你超帅好了

**Comment by breadcrumbzsy** [comment]
不得不承认超级快！
