### ISSUE TITLE
Android 响应式编程的未来展望

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1124]
* 原文链接：[The Next Step for Reactive Android Programming](http://futurice.com/blog/the-next-step-for-reactive-android-programming)
* 掘金链接：[The Next Step for Reactive Android Programming]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-next-step-for-reactive-android-programming.md)
* PR 地址：#1139
* 文章分类：**Android**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Goshin** [comment]
希望能认领这篇文章。

**Comment by sqrthree** [comment]
@Goshin 好哒

**Comment by Goshin** [comment]
翻译完成。

https://github.com/xitu/gold-miner/pull/1139
