### ISSUE TITLE
希望翻译得通顺一点

### ISSUE THREAD

**Issue by PointerFLY** [xitu/gold-miner#1126]
可以采用意译，变换句子顺序、结构，不用逐字逐句。
这些不符合中文语感的文章太难读了。

**Comment by sqrthree** [comment]
@PointerFLY Hello，能否告知是哪一篇文章呢？

**Comment by PointerFLY** [comment]
我读过的几篇都是。比如这篇：
https://gold.xitu.io/entry/579cba75165abd006104d65c?utm_source=gold-miner&utm_medium=readme&utm_campaign=github
比如就说第一句话吧：
> 我们又回到了讨论泛型的另一个章节，来讨论泛型，有其他类型的协议和在 Swift 2 中的其他类型的系统限制。
这都不通顺。基本上感觉是谷歌翻译过了一遍，然后修修改改的感觉。

**Comment by sqrthree** [comment]
@PointerFLY 好的，非常感谢你的反馈，我马上和译者联系沟通哈~ 同时也欢迎你来翻译计划玩~
