### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by skyar2009** [xitu/gold-miner#1128]
- 公司/学校：车满满
- 工作内容/专业：android开发
- 常浏览的国外网站：Android Weekly、android developer、tuicool英文部分
- 英语水平：4级
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：三年android工作经验

**Comment by sqrthree** [comment]
@skyar2009 Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
