### ISSUE TITLE
选择使用正确的 Markdown Parser

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#113]
文章链接：[Choosing the Right Markdown Parser](https://css-tricks.com/choosing-right-markdown-parser/)
掘金链接：[选择使用正确的 Markdown Parser](http://gold.xitu.io/entry/56b2cb85df0eea0054353bf6)
markdown文件：[文章位置]
(https://github.com/xitu/gold-miner/blob/master/TODO/choosing-right-markdown-parser.md)
PR 地址：#123

**Comment by lfkdsk** [comment]
大连理工大二在读，有3年Android开发经验，有个人分享的的技术博客[Blog](http://www.cnblogs.com/lfk-dsk/)，Android原生游戏框架[JustWeEngine](https://github.com/lfkdsk/JustWeEngine)作者，稀土用户，冲着小章鱼手办来的。

**Comment by Sanster** [comment]
工作半年，在某公司做内部[Gitlab](https://about.gitlab.com/)的开发，平常Markdown用的也比较多。

**Comment by Glowin** [comment]
@lfkdsk 赞，欢迎来翻译文章，请问你预估什么时候能翻译完成呢？

@Sanster 你好，因为这个文章被 @lfkdsk 抢在前面申请，但我们这几天还会有文章释放出来，请不要担心没有文章翻译。如果可以的话，麻烦你加一下我的微信 Glowjiang 拉你进译者群，谢谢你的理解。

**Comment by lfkdsk** [comment]
@Glowin 周一好吗？

**Comment by Glowin** [comment]
@lfkdsk 好的呢，等你的PR

**Comment by Sanster** [comment]
@Glowin :smile:

**Comment by lfkdsk** [comment]
@Glowin 完成

**Comment by lfkdsk** [comment]
choosing-right-markdown-parser翻译完成 https://github.com/xitu/gold-miner/pull/123

**Comment by Glowin** [comment]
@lfkdsk 收到，需要两位译者来审核你的文章呢

**Comment by lfkdsk** [comment]
@Glowin 帮忙@一下吧

**Comment by brucezz** [comment]
举手，我来审核 :)

**Comment by lekenny** [comment]
举手,学习一下

**Comment by Glowin** [comment]
@brucezz @lekenny 非常欢迎二位来校对文章，直接在 https://github.com/xitu/gold-miner/pull/123/files?diff=split 上面添加 note 就好呢

**Comment by antonia0912** [comment]
好的 @lfkdsk 请把这篇文章分享到掘金 加标签掘金翻译计划 蟹蟹 同时感谢两位校对者 @brucezz @lekenny 校对的很认真 辛苦了

**Comment by Glowin** [comment]
@Sanster 你好，请问你有加我微信么？

**Comment by Glowin** [comment]
昨天我在群里面说过了，这个 PR 有很多细节没有弄好，详细可以看我的 [修改commit](https://github.com/xitu/gold-miner/commit/712709f912c4021144c9a199d170a20b5f1e908f)。希望译者 @lfkdsk 下次翻译的时候能在本地测试好了后发 PR，两位校对译者 @brucezz @lekenny 在校对的时候不仅仅需要校对内容，排版相关的问题也请多留意。

另外， 有 merge 权限的@antonia0912 也请 merge 的时候认真认真又认真。

@xitu/miners 抄送给各位译者。
