### ISSUE TITLE
Android 写测试用例的注意事项

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1130]
* 原文链接：[The Do’s and Don’ts of Writing Test cases in Android.](https://blog.mindorks.com/the-dos-and-don-ts-of-writing-test-cases-in-android-70f1b5dab3e1#.sjelh11mm)
* 掘金链接：[The Do’s and Don’ts of Writing Test cases in Android.](https://gold.xitu.io/entry/5875a757128fe1006b49151f/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-dos-and-don-ts-of-writing-test-cases-in-android.md)
* PR 地址：#1133
* 文章分类：**Android**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zhiw** [comment]
申请校对

**Comment by sqrthree** [comment]
好的👌🏻👌🏻
