### ISSUE TITLE
Design Doesn’t Scale.

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1131]
* 原文链接：[Design Doesn’t Scale.](https://medium.com/@hellostanley/design-doesnt-scale-4d81e12cbc3e#.pp9zks7wq)
* 掘金链接：[Design Doesn’t Scale.](https://gold.xitu.io/entry/5875b34db123db4a2ed418d3)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/design-doesnt-scale.md)
* PR 地址：待添加
* 文章分类：**设计**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ruixi** [comment]
没人认领就还是我来吧……
大概周六晚上完成……

**Comment by sqrthree** [comment]
哈哈哈好~ 棒棒哒

**Comment by Ruixi** [comment]
https://intersection.tw/%E8%A8%AD%E8%A8%88%E7%84%A1%E6%B3%95%E8%A1%A1%E9%87%8F-b284a5c204c4#.j9sojhy3g

**Comment by sqrthree** [comment]
[存在译文 简体中文](https://mp.weixin.qq.com/s?__biz=MzA4OTQ2ODg5MA==&mid=2647722314&idx=1&sn=18eb05b2871975291436767dc1bac49b&chksm=883fd3ffbf485ae98e6f257587d31ee0c839a819e6aff9e5b1d3693454072c3d865bc90c5377&mpshare=1&scene=1&srcid=0215w3bOYWDDNhuJ6SpqkwuE&key=2ccadf0e66b9e88e5ad3eadd3f2a47d9805226de61c23016427c01a06c8db5355225bf676d751bab7d796f3beac5d3950ae2c906ec9868e4c0e0d06d09cdb1d2c6785ba69ed69853cec66e8edbecb83e&ascene=0&uin=MjE3MzY4NzIyMA%3D%3D&devicetype=iMac+MacBookPro11%2C1+OSX+OSX+10.12.3+build(16D17a)&version=12010310&nettype=WIFI&fontScale=100&pass_ticket=ACGk0ABZ1TxNweRqcrpVbKXkxlLZAcRTODo2%2Fqa3QyjUWpsOQtjI0OFcqvdQBzp1)
