### ISSUE TITLE
Android 数据绑定之: RecyclerView 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1132]
* 原文链接：[Android Data Binding: RecyclerView](https://medium.com/google-developers/android-data-binding-recyclerview-db7c40d9f0e4#.dnlarrt8w)
* 掘金链接：[Android Data Binding: RecyclerView]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/android-data-binding-recyclerview.md)
* PR 地址：#1136
* 文章分类：**Android**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jamweak** [comment]
认领翻译！

**Comment by sqrthree** [comment]
@jamweak 棒棒哒
