### ISSUE TITLE
如何搭建安卓开发持续化集成环境（Ubuntu + Jenkins + SonarQube）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1134]
* 原文链接：[How to set up a Continuous Integration server for Android development (Ubuntu + Jenkins + SonarQube)](https://pamartinezandres.com/how-to-set-up-a-continuous-integration-server-for-android-development-ubuntu-jenkins-sonarqube-43c1ed6b08d3#.sylq0wmfq)
* 掘金链接：[How to set up a Continuous Integration server for Android development (Ubuntu + Jenkins + SonarQube)]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-set-up-a-continuous-integration-server-for-android-development-ubuntu-jenkins-sonarqube.md)
* PR 地址：#1188
* 文章分类：**Android**
----
* 翻译时间：`6` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分

**Comment by skyar2009** [comment]
@sqrthree 我试试这个

**Comment by sqrthree** [comment]
@skyar2009 新译者要从校对文章开始，熟悉一下流程哈~ 请问你之前参与过校对么？

**Comment by skyar2009** [comment]
@sqrthree 今天刚刚校对过1088

**Comment by sqrthree** [comment]
好哒~ 那你 Fork 下这个仓库就可以开始翻译了哈~ 有问题可以@我

**Comment by sqrthree** [comment]
@skyar2009 拥抱工作拥抱翻译啦~ 这篇进度如何了呀？

**Comment by skyar2009** [comment]
https://github.com/xitu/gold-miner/pull/1188
