### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by bluedazzle** [xitu/gold-miner#1135]
- 公司/学校：北京江山如画网络科技有限责任公司
- 工作内容/专业：web 前后端开发
- 常浏览的国外网站：Github、Stackoverflow、YouTube、Quora
- 英语水平：CET-4
- 有无翻译经验：有  ( http://django-redis-chs.readthedocs.io/zh_CN/latest/ )
- 个人博客：https://www.rapospectre.com
- 个人介绍：web 开发者，喜爱开源，喜爱分享。

**Comment by sqrthree** [comment]
@bluedazzle Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
