### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by JeepShen** [xitu/gold-miner#1137]
- 公司/学校：北京邮电大学
- 工作内容/专业：后端/运维/开发/linux
- 常浏览的国外网站：
- 英语水平：CET6
- 有无翻译经验：无
- 个人博客：www.kfinder.cn
- 个人介绍：暂时想不出什么好的(挠头)...努力学习技能和知识，想找个外企参与工作。

**Comment by sqrthree** [comment]
@JeepShen Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
