### ISSUE TITLE
How we "CSS" at BigCommerce

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#114]
文章链接：[How we "CSS" at BigCommerce](http://www.bigeng.io/how-we-css-at-bigcommerce/)
掘金链接：[How we "CSS" at BigCommerce](http://gold.xitu.io/entry/56bcce4271cfe478b57b3dca)
markdown文件：[文章地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-we-css-at-bigcommerce.md)
PR 校对地址：https://github.com/xitu/gold-miner/pull/120/files?diff=split

**Comment by shenxn** [comment]
我来认领，下半年赴美读本科学生，已收普渡CS录取通知，3年前端开发经历。

**Comment by Glowin** [comment]
@shenxn 欢迎来翻译，你直接 fork 一份代码，然后再在 markdown 上翻译，可以看看前面被 merge 的 PR 参考一下。

请问这篇文章需要多久能翻译完成呢？

**Comment by shenxn** [comment]
@Glowin 大概一两天能翻译完吧

**Comment by Glowin** [comment]
@shenxn 方便的话加一下我微信glowjiang吧，我来拉你进译者微信群。

**Comment by CoderBOBO** [comment]
这个被认领了就不能再认领了吧。去年六月份回国，现在在阿里就职，在南加利福尼亚大学

**Comment by antonia0912** [comment]
@CoderBOBO 这个可以认领校对喔~

**Comment by antonia0912** [comment]
@CoderBOBO 你可以加我微信 antonia0912  我直接拉你进译者群哈

**Comment by Evaxtt** [comment]
申请认领校对。

**Comment by Glowin** [comment]
@Evaxtt 你可以进入这个 issue 的校对地址然后直接在 diff 的文章里面添加 note。你可以参考 #120 里面 @aleen42 的校对内容。

**Comment by Evaxtt** [comment]
完成校对@Glowin

**Comment by antonia0912** [comment]
辛苦译者 @shenxn 和三位校对者啦 @bobmayuze @aleen42 @Evaxtt 翻译和校对的很认真 感谢各位的积极参加~~

**Comment by aleen42** [comment]
@shenxn @Evaxtt :raised_hands: :raised_hands: :raised_hands:  乾爸爹~
