### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by fghpdf** [xitu/gold-miner#1140]
- 公司/学校：武汉初心科技有限公司
- 工作内容/专业：node 开发
- 常浏览的国外网站：stackoverflow github
- 英语水平：cet 6
- 有无翻译经验：yes
- 个人博客：[博客](http://www.jianshu.com/u/3cbc1982c4f3)
- 个人介绍：来自于石墨的圈圈想为优质文章献一份力

**Comment by sqrthree** [comment]
@fghpdf 哇哦，我喜欢石墨~ 欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
