### ISSUE TITLE
React 中“灵光乍现”的那些瞬息

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1141]
* 原文链接：[React “Aha” Moments](https://medium.freecodecamp.com/react-aha-moments-4b92bd36cc4e#.jxiocbkv5)
* 掘金链接：[React “Aha” Moments]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/react-aha-moments.md)
* PR 地址：#1225
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by aleen42** [comment]
不对，我还是翻译这篇吧

**Comment by sqrthree** [comment]
@aleen42 好哒
