### ISSUE TITLE
漂亮的字体组合的秘密

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1143]
* 原文链接：[The Secret of Nice Typeface Combinations](https://blog.prototypr.io/the-secret-of-successful-typeface-combinations-2e30c740255c#.280jx4ij6)
* 掘金链接：[漂亮的字体组合的秘密](https://gold.xitu.io/entry/587c42b1b123db005df53dbf)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-secret-of-successful-typeface-combinations.md)
* PR 地址：#1180
* 文章分类：**设计**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ruixi** [comment]
先认一下，但是我估计要下周才有时间翻译……
如果到下周还没有其他人来认领的话就我来辣～

**Comment by sqrthree** [comment]
好哒

**Comment by sqrthree** [comment]
@Ruixi 啦啦啦~ 已经到了拥抱工作的时候啦，这篇进度如何了呀？

**Comment by Ruixi** [comment]
@sqrthree 我终于能登录 Git 了……
明天 check 最后一遍，然后就可以发出来了……
大概是晚上下班后😂
