### ISSUE TITLE
安卓应用栏的滚动效果

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1146]
* 原文链接：[Scrolling Behavior for Appbars in Android](https://android.jlelse.eu/scrolling-behavior-for-appbars-in-android-41aff9c5c468#.4fzku8r1x)
* 掘金链接：[Scrolling Behavior for Appbars in Android]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/scrolling-behavior-for-appbars-in-android.md)
* PR 地址：#1171
* 文章分类：**Android**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XHShirley** [comment]
认领。

**Comment by sqrthree** [comment]
@XHShirley 好哒
