### ISSUE TITLE
怎样写一个能同时用于 Node 和浏览器的 JavaScript 包？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1147]
* 原文链接：[How to write a JavaScript package for both Node and the browser](https://nolanlawson.com/2017/01/09/how-to-write-a-javascript-package-for-both-node-and-the-browser/)
* 掘金链接：[How to write a JavaScript package for both Node and the browser]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-write-a-javascript-package-for-both-node-and-the-browser.md)
* PR 地址：#1169
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luoyaqifei** [comment]
认领

**Comment by sqrthree** [comment]
@luoyaqifei 妥妥哒

**Comment by luoyaqifei** [comment]
https://gold.xitu.io/entry/5899bc6e61ff4b006b21d0bc/detail

**Comment by sqrthree** [comment]
copythat
