### ISSUE TITLE
RxAndroid Tutorial

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1148]
* 原文链接：[RxAndroid Tutorial](https://www.raywenderlich.com/141980/rxandroid-tutorial)
* 掘金链接：[RxAndroid Tutorial]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/rxandroid-tutorial.md)
* PR 地址：#1164
* 文章分类：**Android**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jamweak** [comment]
这个是什么情况？？认？
@sqrthree

**Comment by sqrthree** [comment]
@jamweak 改好啦~ 妥妥哒
