### ISSUE TITLE
Model-View-Intent 模式下的响应式应用 － 第一部分 － Model（模型）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1149]
* 原文链接：[REACTIVE APPS WITH MODEL-VIEW-INTENT - PART1 - MODEL](http://hannesdorfmann.com/android/mosby3-mvi-1)
* 掘金链接：[REACTIVE APPS WITH MODEL-VIEW-INTENT - PART1 - MODEL]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/mosby3-mvi.md)
* PR 地址：#1185
* 文章分类：**Android**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XHShirley** [comment]
能认领吗。。。

**Comment by sqrthree** [comment]
@XHShirley 能的~ 里面有个排版，我调整下就好啦。

**Comment by sqrthree** [comment]
@XHShirley 好啦~

**Comment by sqrthree** [comment]
@XHShirley 雪梨姐这篇进度如何了哈

**Comment by XHShirley** [comment]
今晚推上来～

**Comment by XHShirley** [comment]
@sqrthree 今晚推上来～
