### ISSUE TITLE
iOS 应用测试

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1150]
* 原文链接：[Testing iOS Apps](http://merowing.info/2017/01/testing-ios-apps/)
* 掘金链接：[Testing iOS Apps]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/testing-ios-apps.md)
* PR 地址： #1176
* 文章分类：**iOS**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by thanksdanny** [comment]
翻译认领

**Comment by sqrthree** [comment]
@thanksdanny Go ahead.
