### ISSUE TITLE
Swift 面向协议编程入门

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1151]
* 原文链接：[Introduction to Protocol Oriented Programming in Swift](https://medium.com/ios-geek-community/introduction-to-protocol-oriented-programming-in-swift-b358fe4974f#.ezvkbpy7o)
* 掘金链接：[Introduction to Protocol Oriented Programming in Swift]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/introduction-to-protocol-oriented-programming-in-swift.md)
* PR 地址：#1157
* 文章分类：**iOS**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Danny1451** [comment]
@sqrthree 年前不忙，认领一波，之前翻过 POP 的文章。

**Comment by sqrthree** [comment]
@Danny1451 好的
