### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by NothShow** [xitu/gold-miner#1153]
- 公司/学校：青岛理工大学
- 工作内容/专业：计算机科学与技术
- 常浏览的国外网站：medium infoQ
- 英语水平：六级
- 有无翻译经验：有
- 个人博客：暂无
- 个人介绍：个人平时喜欢看一写外文书籍，希望通过这个活动可以精进自己的专业知识和英语水平。

**Comment by sqrthree** [comment]
@NothShow Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
