### ISSUE TITLE
让 Node.js 核心库更大

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1154]
* 原文链接：[Make Node.js Core Bigger](https://medium.com/node-js-javascript/make-node-js-core-bigger-97ca7ef62b77#.7ofxzzhpt)
* 掘金链接：[Make Node.js Core Bigger]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/make-node-js-core-bigger.md)
* PR 地址：#1165
* 文章分类：**后端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by imink** [comment]
@sqrthree 快速浏览一遍, 感觉还蛮好翻译, 来认领啦.

**Comment by sqrthree** [comment]
@imink  好哒
