### ISSUE TITLE
推荐优秀英文文章：Netflix：使用 React 构建高性能的 TV 用户界面

### ISSUE THREAD

**Issue by Glowin** [xitu/gold-miner#1156]
- 原文链接：https://gold.xitu.io/entry/587ef290128fe1006b13339e/detail
- 简要介绍：Netflix 在 2015 年就选择 React 作为前端架构，这篇文章总结了 Netflix 在解决性能问题的经验。

**Comment by sqrthree** [comment]
棒棒哒~
