### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by jifaxu** [xitu/gold-miner#1158]
- 公司/学校：华中科技大学，百纳信息科技有限公司实习生
- 工作内容/专业：计算机科学与技术 / android 及 java 开发
- 常浏览的国外网站：stackoverflow github feedly
- 英语水平：cet6
- 有无翻译经验：有
- 个人博客：blog.csdn.net/u013538630/ 和 blog.xujifa.cn
- 个人介绍：希望参与掘金翻译计划，看了这个计划里产出的很多文章，所以也想参与进来，一是锻炼自己，二是做点贡献

**Comment by sqrthree** [comment]
@jifaxu Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
