### ISSUE TITLE
Netflix：使用 React 构建高性能的 TV 用户界面

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1159]
* 原文链接：[Crafting a high-performance TV user interface using React](http://techblog.netflix.com/2017/01/crafting-high-performance-tv-user.html)
* 掘金链接：[Netflix：使用 React 构建高性能的 TV 用户界面](https://gold.xitu.io/entry/587ef290128fe1006b13339e/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/crafting-high-performance-tv-user.md)
* PR 地址：#1173
* 文章分类：**前端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Professor-Z** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
@Professor-Z  好的
