### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by 70data** [xitu/gold-miner#1160]
- 公司/学校：Sogou.com
- 工作内容/专业：Developer
- 常浏览的国外网站：www.pythonweekly.com、frontenddevweekly.com、stackoverflow.com
- 英语水平：只考过CET4。能正常浏览英文文档。
- 有无翻译经验：有翻译及组织翻译的经验。翻译过kubernetes、elasticsearch、beats英文文档。组织翻译vue2.0文档并merge到官方，以及后续更新维护。
- 个人博客：70data.net
- 个人介绍：有时间。喜欢分享、热爱开源，希望能为国人开源事业做点共享。

**Comment by sqrthree** [comment]
@70data Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
