### ISSUE TITLE
2017 年要去学的 3 个 CSS 新属性

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1161]
* 原文链接：[3 New CSS Features to Learn in 2017](https://bitsofco.de/3-new-css-features-to-learn-in-2017/)
* 掘金链接：[2017 年要去学的 3 个 CSS 新属性](https://gold.xitu.io/entry/587f9e738d6d810058e734b6/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/3-new-css-features-to-learn-in-2017.md)
* PR 地址：#1170
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by FrankXiong** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
@FrankXiong 好的

**Comment by aleen42** [comment]
认领校对

**Comment by sqrthree** [comment]
@aleen42 好哒
