### ISSUE TITLE
在 Swift 3 上对视图控件实践面向协议编程

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1162]
* 原文链接：[Protocol Oriented Programming View in Swift 3](https://medium.com/ios-geek-community/protocol-oriented-programming-view-in-swift-3-8bcb3305c427#.7skyb26dz)
* 掘金链接：[Protocol Oriented Programming View in Swift 3](https://gold.xitu.io/entry/5880366b8fd9c50067ddbac6/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/protocol-oriented-programming-view-in-swift-3.md)
* PR 地址：#1172
* 文章分类：**iOS**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tuccuay** [comment]
收（

**Comment by sqrthree** [comment]
@Tuccuay 好的
