### ISSUE TITLE
快来和你的 Font Icons 说 Goodbye 吧

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1163]
* 原文链接：[Align SVG Icons to Text and Say Goodbye to Font Icons](https://blog.prototypr.io/align-svg-icons-to-text-and-say-goodbye-to-font-icons-d44b3d7b26b4#.n7fpslivm)
* 掘金链接：[快来和你的 Font Icons 说 Goodbye 吧](https://gold.xitu.io/entry/5880370e1b69e60059010991/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/align-svg-icons-to-text-and-say-goodbye-to-font-icons.md)
* PR 地址：#1175
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by aleen42** [comment]
最近放假，來認領一篇

**Comment by sqrthree** [comment]
@aleen42 好哒

**Comment by aleen42** [comment]
@sqrthree 可以申请校对了
