### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Eamonnzhang** [xitu/gold-miner#1166]
- 公司/学校：郑州市珑凌科技有限公司
- 工作内容/专业：前端工程师
- 常浏览的国外网站：stackoverflow.com, css-tricks.com
- 英语水平：CET6
- 有无翻译经验：略有
- 个人博客：blog.eamonn.cn
- 个人介绍：略有强迫症的前端

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
