### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by yazhi1992** [xitu/gold-miner#1168]
- 公司/学校：杭州微著网络有限公司
- 工作内容/专业：Android开发
- 常浏览的国外网站：infoQ、stackoverflow
- 英语水平：六级
- 有无翻译经验：毕设时翻译过两篇
- 个人博客：http://blog.csdn.net/yazhi1992
- 个人介绍：希望能为社区贡献点绵薄之力，同时也提高自己的英语水平

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
