### ISSUE TITLE
OAuth2 Authentication with Lua

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#117]
文章链接：[OAuth2 Authentication with Lua](http://lua.space/webdev/oauth2-authentication-with-lua)
掘金链接：[OAuth2 Authentication with Lua](http://gold.xitu.io/entry/5697e2279d22e8a3acbac56a)
markdown文件：[文章地址](https://github.com/xitu/gold-miner/blob/master/TODO/OAuth2%20Authentication%20with%20Lua.md)

**Comment by CoderBOBO** [comment]
我来认领这篇文章

**Comment by Glowin** [comment]
好的呢，你可以 fork 一份这个 repo，然后直接在 markdown 文件上翻译，期待你的 PR。

**Comment by CoderBOBO** [comment]
ok

**Comment by antonia0912** [comment]
感谢我们亲爱的译者@CoderBOBO 同学，翻译的太仔细啦！两位校对者@shenxn  @iThreeKing 也辛苦啦  期待你们的后续参与哈~~
