### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Vivienmm** [xitu/gold-miner#1177]
- 公司/学校：北京邮电大学
- 工作内容/专业：信息与通信工程专业，互联网方向
- 常浏览的国外网站：https://developer.android.google.cn/
- 英语水平：英语六级
- 有无翻译经验：曾经翻译过通信方面的开发文档
- 个人博客：http://my.csdn.net/beiyouzidonghua?locationNum=0&fps=1
- 个人介绍：英语学习爱好者，业余进击

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
