### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ilumer** [xitu/gold-miner#1178]
- 公司/学校：盐城师范学院
- 工作内容/专业：网络工程
- 常浏览的国外网站：github,medium android dev twitter
- 英语水平：四级
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：一个立志成为合格工程师的初级Anroid开发

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
