### ISSUE TITLE
RecyclerView 数据预取

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1181]
* 原文链接：[RecyclerView Prefetch](https://medium.com/google-developers/recyclerview-prefetch-c2f269075710#.b1or0k6l3)
* 掘金链接：[RecyclerView 预加载](https://gold.xitu.io/entry/5861e1b7128fe1006d013cc7/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/recyclerview-prefetch.md)
* PR 地址：#1235
* 文章分类：**Android**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
认领翻译

**Comment by sqrthree** [comment]
@tanglie1993 好哒

**Comment by tanglie1993** [comment]
抱歉最近几天非常忙。可以过几天再提交吗？

**Comment by sqrthree** [comment]
适当可以，质量第一。但是也不要拖太久哈
