### ISSUE TITLE
使用神经网络的文本分类

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1182]
* 原文链接：[Text Classification using Neural Networks](https://machinelearnings.co/text-classification-using-neural-networks-f5cd7b8765c6#.vvfa01t9r)
* 掘金链接：[使用神经网络的文本分类](https://gold.xitu.io/entry/5895b5018d6d8100583a10c0/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/text-classification-using-neural-networks.md)
* PR 地址：#1210
* 文章分类：**后端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Kulbear** [comment]
认领。

**Comment by sqrthree** [comment]
@Kulbear 好哒

**Comment by Zheaoli** [comment]
@sqrthree 把这王八犊子盯严实点，不修改三遍不准过！

**Comment by sqrthree** [comment]
以后要对主持人好点
