### ISSUE TITLE
让内存管理重振雄风

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1183]
* 原文链接：[Make Memory Management Great Again](https://medium.com/ios-geek-community/make-memory-management-great-again-f781fb29cea1#.w6wgnw1og)
* 掘金链接：[Make Memory Management Great Again]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/make-memory-management-great-again.md)
* PR 地址：#1187
* 文章分类：**iOS**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeepMissea** [comment]
收了~

**Comment by sqrthree** [comment]
@DeepMissea 好哒

**Comment by xiaoheiai4719** [comment]
校对认领～

**Comment by sqrthree** [comment]
@xiaoheiai4719 下次记得在对应的 [PR](#1187) 下认领哈，对应 PR 地址：#1187
