### ISSUE TITLE
几张 GIF 动图让你看懂弹性盒模型（Flexbox）如何工作

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1189]
* 原文链接：[How Flexbox works — explained with big, colorful, animated gifs](https://medium.freecodecamp.com/an-animated-guide-to-flexbox-d280cf6afc35#.u44ga6k7p)
* 掘金链接：[How Flexbox works — explained with big, colorful, animated gifs]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/an-animated-guide-to-flexbox.md)
* PR 地址：#1214
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by llp0574** [comment]
我来这篇吧

**Comment by sqrthree** [comment]
@llp0574 好的
