### ISSUE TITLE
像开发人员一样做设计

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1192]
* 原文链接：[Design like a Developer](https://medium.com/going-your-way-anyway/design-like-a-developer-b92f7a8f4520#.ohgf4aagn)
* 掘金链接：[Design like a Developer]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/design-like-a-developer.md)
* PR 地址：#1255
* 文章分类：**设计**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Airmacho** [comment]
认领17年第一篇

**Comment by sqrthree** [comment]
@Airmacho 好哒
