### ISSUE TITLE
ConstraintLayout (这到底是什么)

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1194]
* 原文链接：[Constraint Layout ( What the hell is this )](http://www.uwanttolearn.com/android/constraint-layout-hell/)
* 掘金链接：[Constraint Layout ( What the hell is this )]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/constraint-layout-hell.md)
* PR 地址：#1209
* 文章分类：**Android**
---
关联任务：

* [第二部分](https://github.com/xitu/gold-miner/issues/1195)
* [第三部分](https://github.com/xitu/gold-miner/issues/1196)
* [第四部分](https://github.com/xitu/gold-miner/issues/1197)

> 该文章属于系列中的一部分，请译者在翻译之前和其他几篇的译者协同商量好关键术语等特定词汇的译法。
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jifaxu** [comment]
@sqrthree 申请翻译

**Comment by sqrthree** [comment]
@jifaxu 好的，这是一个系列的文章，注意和其他几篇的译者沟通好哈。
