### ISSUE TITLE
Constraint Layout Concepts ( What the hell is this ) (Tips and Tricks) Part 2 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1195]
* 原文链接：[Constraint Layout Concepts ( What the hell is this ) (Tips and Tricks) Part 2 ](http://www.uwanttolearn.com/android/constraint-layout-concepts-hell-tips-tricks-part-2/)
* 掘金链接：[Constraint Layout Concepts ( What the hell is this ) (Tips and Tricks) Part 2 ]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/constraint-layout-concepts-hell-tips-tricks-part-2.md)
* PR 地址：#1211
* 文章分类：**Android**
----
关联任务：

* [第一部分](https://github.com/xitu/gold-miner/issues/1194)
* [第三部分](https://github.com/xitu/gold-miner/issues/1196)
* [第四部分](https://github.com/xitu/gold-miner/issues/1197)

> 该文章属于系列中的一部分，请译者在翻译之前和其他几篇的译者协同商量好关键术语等特定词汇的译法。
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jamweak** [comment]
认领翻译！

**Comment by sqrthree** [comment]
@jamweak 好哒
