### ISSUE TITLE
Constraint Layout 动画 |动态 Constraint |用 Java 实现的 UI[Part3]

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1196]
* 原文链接：[Constraint Layout [Animations | Dynamic Constraints | UI by Java] ( What the hell is this )[Part3]](http://www.uwanttolearn.com/android/constraint-layout-animations-dynamic-constraints-ui-java-hell/)
* 掘金链接：[Constraint Layout [Animations | Dynamic Constraints | UI by Java] ( What the hell is this )]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/constraint-layout-animations-dynamic-constraints-ui-java-hell.md)
* PR 地址：#1271
* 文章分类：**Android**
---
关联任务：

* [第一部分](https://github.com/xitu/gold-miner/issues/1194)
* [第二部分](https://github.com/xitu/gold-miner/issues/1195)
* [第四部分](https://github.com/xitu/gold-miner/issues/1197)

> 该文章属于系列中的一部分，请译者在翻译之前和其他几篇的译者协同商量好关键术语等特定词汇的译法。
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by siegeout** [comment]
认领

**Comment by sqrthree** [comment]
@siegeout 好哒

**Comment by sqrthree** [comment]
抓紧啦 _(:з」∠)_
