### ISSUE TITLE
ConstaintLayout 可视化[Design]编辑器 （这到底是什么）[第四部分]

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1197]
* 原文链接：[Constraint Layout Visual [Design] Editor ( What the hell is this )[Part4]](http://www.uwanttolearn.com/android/constraint-layout-visual-design-editor-hell/)
* 掘金链接：[Constraint Layout Visual [Design] Editor ( What the hell is this )[Part4]]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/constraint-layout-visual-design-editor-hell.md)
* PR 地址：#1261
* 文章分类：**Android** 
---
关联任务：

* [第一部分](https://github.com/xitu/gold-miner/issues/1194)
* [第二部分](https://github.com/xitu/gold-miner/issues/1195)
* [第三部分](https://github.com/xitu/gold-miner/issues/1196)

> 该文章属于系列中的一部分，请译者在翻译之前和其他几篇的译者协同商量好关键术语等特定词汇的译法。

----
* 翻译时间：`7` 天
* 校对时间：`1` 天
* 翻译积分：`7` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yazhi1992** [comment]
认领个翻译~ @sqrthree

**Comment by sqrthree** [comment]
@yazhi1992 好哒

**Comment by sqrthree** [comment]
@yazhi1992 这篇文章进度如何了呀？
