### ISSUE TITLE
在线进行大规模的数据迁移

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1198]
* 原文链接：[Online migrations at scale](https://stripe.com/blog/online-migrations)
* 掘金链接：[Online migrations at scale]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/online-migrations.md)
* PR 地址：#1250
* 文章分类：**后端**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by steinliber** [comment]
领一个 @sqrthree

**Comment by sqrthree** [comment]
@steinliber 好哒

**Comment by Zheaoli** [comment]
@sqrthree my part is done
@steinliber Good job
