### ISSUE TITLE
认领Android 的一个 MVP 基础项目模板

### ISSUE THREAD

**Issue by foolishgao** [xitu/gold-miner#12]
认领翻译Android 的一个 MVP 基础项目模板

**Comment by Glowin** [comment]
你好，能否介绍一下自己呢？

**Comment by Glowin** [comment]
你好，我拉了一个掘金翻译计划译者的微信群，译者都在群里面，我会在群里面更新活动的最新进展，如果方便的话可以加我一下微信 Glowjiang。
