### ISSUE TITLE
Android MVP 架构必要知识：第一部分

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1202]
* 原文链接：[Essential Guide For Designing Your Android App Architecture: MVP: Part 1](https://blog.mindorks.com/essential-guide-for-designing-your-android-app-architecture-mvp-part-1-74efaf1cda40#.3lyk8t57x)
* 掘金链接：[Essential Guide For Designing Your Android App Architecture: MVP: Part 1]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/essential-guide-for-designing-your-android-app-architecture-mvp-part.md)
* PR 地址：#1221
* 文章分类：**Android**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jifaxu** [comment]
@sqrthree 再领一篇好了

**Comment by sqrthree** [comment]
@jifaxu 好哒
