### ISSUE TITLE
iOS 开发中使用 Swift 进行 iBeacons 交互指南

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1204]
* 原文链接：[A Guide to Interacting with iBeacons in iOS using Swift](https://spin.atomicobject.com/2017/01/31/ibeacon-in-swift/)
* 掘金链接：[A Guide to Interacting with iBeacons in iOS using Swift]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/ibeacon-in-swift.md)
* PR 地址：#1226
* 文章分类：**iOS**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lovelyCiTY** [comment]
认领啦@sqrthree

**Comment by sqrthree** [comment]
@lovelyCiTY 好呀好呀
