### ISSUE TITLE
设计预期的用户体验

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1205]
* 原文链接：[Designing Anticipated User Experiences](https://uxdesign.cc/designing-anticipated-user-experiences-c419b574a417#.k46dd8myv)
* 掘金链接：[Designing Anticipated User Experiences]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/designing-anticipated-user-experiences.md)
* PR 地址：#1277
* 文章分类：**设计**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by aleen42** [comment]
要了

**Comment by aleen42** [comment]
我还是翻译前端的 #1141

**Comment by sqrthree** [comment]
好哒

**Comment by jifaxu** [comment]
我来翻这篇吧，感觉挺有意思的 @sqrthree

**Comment by sqrthree** [comment]
@jifaxu 好的
