### ISSUE TITLE
步入 Swift 3

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1206]
* 原文链接：[Getting to Swift 3](https://medium.com/airbnb-engineering/getting-to-swift-3-at-airbnb-79a257d2b656#.lb5fvph0v)
* 掘金链接：[Getting to Swift 3]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/getting-to-swift-3-at-airbnb.md)
* PR 地址：#1249
* 文章分类：**iOS**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeepMissea** [comment]
认领，@sqrthree

**Comment by sqrthree** [comment]
@DeepMissea  好哒

**Comment by DeepMissea** [comment]
@sqrthree  [地址](https://gold.xitu.io/entry/58aa701fda2f60006fa9978f/detail)
