### ISSUE TITLE
iOS 开发者一定要知道的 14 个知识点

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1207]
* 原文链接：[14 must knows for an iOS developer](https://swiftsailing.net/14-must-knows-for-an-ios-developer-5ae502d7d87f#.x0p52vfq6)
* 掘金链接：[14 must knows for an iOS developer](https://gold.xitu.io/entry/589a91430ce4630056193bab)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/14-must-knows-for-an-ios-developer.md)
* PR 地址：#1236
* 文章分类：**iOS**
----
* 翻译时间：`9` 天
* 校对时间：`2` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeepMissea** [comment]
@sqrthree 收了

**Comment by sqrthree** [comment]
@DeepMissea 好的
