### ISSUE TITLE
老司机手把手带你在 Swift 中应用代理（Delegate）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1208]
* 原文链接：[Implementing delegates in Swift, step by step](https://medium.com/@jamesrochabrun/implementing-delegates-in-swift-step-by-step-d3211cbac3ef#.hvhtexfyo)
* 掘金链接：[Implementing delegates in Swift, step by step]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/implementing-delegates-in-swift-step-by-step.md)
* PR 地址：#1213
* 文章分类：**iOS**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gocy015** [comment]
@sqrthree ，好久没翻译了，搞起。

**Comment by sqrthree** [comment]
@Gocy015 好哒

**Comment by thanksdanny** [comment]
申请校对

**Comment by sqrthree** [comment]
@thanksdanny 为什么不去对应的 PR 下面申请捏？

**Comment by thanksdanny** [comment]
@sqrthree 😂一时没反应过来..最近感冒有点头昏
