### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by lekenny** [xitu/gold-miner#121]
android一年开发经验 英语四级

**Comment by Glowin** [comment]
欢迎来翻译计划认领翻译，你可以在 issue 里面查看待翻译和待审核的文章，直接在 issue 下留言即可。

如果方便的话，可以加我微信 Glowjiang，我来拉你进译者群。

**Comment by lekenny** [comment]
@Glowin 我可以先审核一段时间  多学习学习么

**Comment by Glowin** [comment]
非常欢迎你先来校对文章，你可以在 PR 里面找那些 label 是「校对认领」的 PR 来校对。
