### ISSUE TITLE
JavaScript 启动性能探究

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1216]
* 原文链接：[JavaScript Start-up Performance](https://medium.com/@addyosmani/javascript-start-up-performance-69200f43b201#.f2ifedbt2)
* 掘金链接：[JavaScript Start-up Performance](https://gold.xitu.io/entry/589d2da4b123db16a3c7c072/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/javascript-start-up-performance.md)
* PR 地址：#1237
* 文章分类：**前端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Professor-Z** [comment]
@sqrthree 认领翻译~

**Comment by sqrthree** [comment]
@Professor-Z 好的

**Comment by Professor-Z** [comment]
@sqrthree #1237 翻译完啦，等待校对

**Comment by sqrthree** [comment]
copythat
