### ISSUE TITLE
何为 HTML API，如何设计之？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1217]
* 原文链接：[HTML APIs: What They Are And How To Design A Good One](https://www.smashingmagazine.com/2017/02/designing-html-apis/)
* 掘金链接：[HTML APIs: What They Are And How To Design A Good One]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/designing-html-apis.md)
* PR 地址：#1610
* 文章分类：**前端**
----
* 翻译时间：`9` 天
* 校对时间：`2` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
@sqrthree 认领一个大姑娘

**Comment by sqrthree** [comment]
@Romeo0906 双击666

**Comment by Aladdin-ADD** [comment]
认领校对。

**Comment by sqrthree** [comment]
@Aladdin-ADD 这篇还在翻译（(ノへ￣、)捂脸）

**Comment by Aladdin-ADD** [comment]
先占位😜
