### ISSUE TITLE
再谈 CSS 中的代码味道

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1218]
* 原文链接：[Code Smells in CSS Revisited](https://csswizardry.com/2017/02/code-smells-in-css-revisited/)
* 掘金链接：[Code Smells in CSS Revisited]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/code-smells-in-css-revisited.md)
* PR 地址：#1342
* 文章分类：**前端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by malcolmyu** [comment]
认领

**Comment by sqrthree** [comment]
@malcolmyu 好哒~~

**Comment by malcolmyu** [comment]
@sqrthree 最近太忙，资源释放😂

**Comment by sqrthree** [comment]
好吧~ 下次不要拖这么长时间了啊

**Comment by IridescentMia** [comment]
@sqrthree 认领翻译

**Comment by sqrthree** [comment]
@IridescentMia 好哒~

**Comment by Germxu** [comment]
我先来个一校 @sqrthree

**Comment by sqrthree** [comment]
@Germxu 到 PR 下认领啊哈

**Comment by Germxu** [comment]
咳咳, 看错了
