### ISSUE TITLE
Web 分享 API 赋予浏览器原生分享能力

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1219]
* 原文链接：[Web Share API brings the native sharing capabilities to the browser](https://blog.hospodarets.com/web-share-api#why-do-we-need-a-new-api)
* 掘金链接：[Web Share API brings the native sharing capabilities to the browser]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-do-we-need-a-new-api.md)
* PR 地址：#1308
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by AceLeeWinnie** [comment]
@sqrthree 认领

**Comment by sqrthree** [comment]
@AceLeeWinnie 好哒

**Comment by AceLeeWinnie** [comment]
#1308 
@sqrthree 翻译完成 球校对~
