### ISSUE TITLE
A Look into Navigation in Web Design

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1220]
* 原文链接：[A Look into Navigation in Web Design](https://cmd-t.webydo.com/from-simple-to-unusual-a-look-at-navigation-in-web-design-1057d0baef7b#.163gvilh8)
* 掘金链接：[A Look into Navigation in Web Design](https://gold.xitu.io/entry/589d37e82f301e0069b9e7af/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/rom-simple-to-unusual-a-look-at-navigation-in-web-design.md)
* PR 地址：待添加
* 文章分类：**设计**
----
* 翻译时间：`8` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jiaowoyongqi** [comment]
认领！

**Comment by sqrthree** [comment]
@jiaowoyongqi 好哒

**Comment by jiaowoyongqi** [comment]
@sqrthree 最近太忙了，抱歉不能翻译这篇文章，是否可以转给其他人？

**Comment by sqrthree** [comment]
_(:з」∠)_ 下次早点说啦

**Comment by jiaowoyongqi** [comment]
@sqrthree sorry，下次我还是找校对吧

**Comment by osirism** [comment]
这篇有人认领了么

**Comment by sqrthree** [comment]
没有呢

**Comment by osirism** [comment]
那我认领咯~

**Comment by sqrthree** [comment]
好哒~ 有问题随时@我哈

**Comment by sqrthree** [comment]
@osirism Hello，这篇进度如何了呀？

**Comment by ylq167** [comment]
提前申请校对～ @sqrthree

**Comment by sqrthree** [comment]
_(:з」∠)_  [发现译文](https://zhuanlan.zhihu.com/p/25116133)，已和译者沟通。
