### ISSUE TITLE
优秀产品背后的设计原则

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1228]
* 原文链接：[Design Principles Behind Great Products](https://medium.muz.li/design-principles-behind-great-products-6ef13cd74ccf#.uo9ssig6q)
* 掘金链接：[Design Principles Behind Great Products](https://gold.xitu.io/entry/58a0398e1b69e60059ce177d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/design-principles-behind-great-products.md)
* PR 地址：#1268
* 文章分类：**设计**
----
* 翻译时间：`10` 天
* 校对时间：`2` 天
* 翻译积分：`10` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by llp0574** [comment]
我来

**Comment by sqrthree** [comment]
好的

**Comment by xiaohansc** [comment]
您好，请问可以转载贵方翻译的文章吗？我们会标明出处的。

**Comment by sqrthree** [comment]
@xiaohansc 如果是单指这一篇的话，你可以直接联系这篇文章的译者 @jifaxu 哈。
