### ISSUE TITLE
如何实现 React 组件的可复用性

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1229]
* 原文链接：[How to Achieve Reusability with React Components](https://medium.com/walmartlabs/how-to-achieve-reusability-with-react-components-81edeb7fb0e0#.czocsk5l0)
* 掘金链接：[How to Achieve Reusability with React Components]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-achieve-reusability-with-react-components.md)
* PR 地址：#1259
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by aleen42** [comment]
认领

**Comment by sqrthree** [comment]
@aleen42 好哒
