### ISSUE TITLE
Node.js 支持 ES6 模块的进展

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1230]
* 原文链接：[An Update on ES6 Modules in Node.js](https://medium.com/@jasnell/an-update-on-es6-modules-in-node-js-42c958b890c#.o3doprfmu)
* 掘金链接：[An Update on ES6 Modules in Node.js]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/an-update-on-es6-modules-in-node-js.md)
* PR 地址：#1263
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hikerpig** [comment]
认领翻译哟~

**Comment by sqrthree** [comment]
好
