### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by dubuqingfeng** [xitu/gold-miner#1231]
- 公司/学校：CFCA/山西农业大学
- 工作内容/专业：信息安全、软件工程、后端
- 常浏览的国外网站：Google、medium、stackoverflow、Quora
- 英语水平：CET-4
- 有无翻译经验：无
- 个人博客：https://dbqf.xyz
- 个人介绍：回忆过去，珍惜现在，努力做一个更自由更开放的计算机爱好者

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
