### ISSUE TITLE
某些2017年的 UX 趋势啊，扎心了

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1232]
* 原文链接：[Terrible UX Trends for 2017](https://medium.com/ux-power-tools/terrible-ux-trends-for-2017-de6faebf099e#.reygjk2nv)
* 掘金链接：[Terrible UX Trends for 2017]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/terrible-ux-trends-for.md)
* PR 地址：#1358
* 文章分类：**设计**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ruixi** [comment]
嗯……没人和我抢……

**Comment by sqrthree** [comment]
嗯。。你要翻译么？┏ (゜ω゜)=☞

**Comment by Ruixi** [comment]
对的呀～周末搞出来

**Comment by sqrthree** [comment]
好哒

**Comment by Ruixi** [comment]
周末加完之后现在也加班中……
求后延2天QAQ

**Comment by sqrthree** [comment]
It's ok.

**Comment by sqrthree** [comment]
@Ruixi 小姐姐，周末能搞定么？

**Comment by Ruixi** [comment]
@sqrthree 能，今天……
这是我翻过的最烧脑的一篇，没有之一……

**Comment by Ruixi** [comment]
@sqrthree 好了……
但是感觉这篇我翻的不太好……
https://github.com/xitu/gold-miner/pull/1358/files

**Comment by bobmayuze** [comment]
请求校对

**Comment by sqrthree** [comment]
@bobmayuze 好哒
