### ISSUE TITLE
Bob，我要怎样才能成为一名 iOS 开发者

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1233]
* 原文链接：[How to become an iOS developer, Bob](https://medium.com/ios-geek-community/how-to-become-an-ios-developer-bob-82944188ea7d#.dpn3k2gk1)
* 掘金链接：[How to become an iOS developer, Bob]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-become-an-ios-developer-bob.md)
* PR 地址：#1274
* 文章分类：**iOS**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by thanksdanny** [comment]
翻译认领

**Comment by sqrthree** [comment]
@thanksdanny 好哒

**Comment by sqrthree** [comment]
@thanksdanny 组织托我给您带个话，这篇文章已经过了 deadline 啦，为啥子还不交稿捏？

**Comment by thanksdanny** [comment]
@sqrthree 已经调整完毕，这是pr地址：[传送门](https://github.com/xitu/gold-miner/pull/1274)
