### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ChenDongnan** [xitu/gold-miner#1234]
- 公司/学校：杭州兔狗科技有限公司/上海对外经贸大学
- 工作内容/专业：iOS开发工程师/物流管理
- 常浏览的国外网站：StackOverflow,YouTube
- 英语水平：CET-6,BEC高级 
- 有无翻译经验：无
- 个人博客：www.chendongnan.com
- 个人介绍：对iOS开发和英文翻译都抱有很大的热情，希望能够翻译国外优秀文章为国内开发者提供帮助

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
