### ISSUE TITLE
为什么安卓测试如此困难：历史版本

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1239]
* 原文链接：[Why Android Testing is so Hard: Historical Edition
](https://www.philosophicalhacker.com/post/why-android-testing-is-so-hard-historical-edition/)
* 掘金链接：[Why Android Testing is so Hard: Historical Edition
]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-android-testing-is-so-hard-historical-edition.md)
* PR 地址：#1260
* 文章分类：**Android**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
我把这个也认领了算了。刚领的一篇都快翻译完了。

**Comment by sqrthree** [comment]
@tanglie1993 666~ 碉堡了
