### ISSUE TITLE
Nougat 中通过 Intents 共享文件，你准备好了吗？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1240]
* 原文链接：[Sharing files through Intents: are you ready for Nougat?](https://medium.com/@quiro91/sharing-files-though-intents-are-you-ready-for-nougat-70f7e9294a0b#.8d2johavz)
* 掘金链接：[Sharing files through Intents: are you ready for Nougat?]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/sharing-files-though-intents-are-you-ready-for-nougat.md)
* PR 地址：#1248
* 文章分类：**Android**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by skyar2009** [comment]
@sqrthree 来一发

**Comment by sqrthree** [comment]
@skyar2009 好的

**Comment by skyar2009** [comment]
@sqrthree  https://github.com/xitu/gold-miner/pull/1248
