### ISSUE TITLE
观察者模式 – 响应式编程 [Android RxJava2]（这到底是什么）：第一部分

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1241]
* 原文链接：[Observer Pattern – Reactive Programming [Android RxJava2] ( What the hell is this ) Part1]()
* 掘金链接：[Observer Pattern – Reactive Programming [Android RxJava2] ( What the hell is this ) Part1]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/reactive-programming-android-rxjava2-hell-part1.md)
* PR 地址：#1273
* 文章分类：**Android**
----
相关文章：

- [Part 2](https://github.com/xitu/gold-miner/issues/1242)
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zhiw** [comment]
翻译认领，看来工作量不小哦

**Comment by sqrthree** [comment]
@Zhiw  是的呢，辛苦啦

**Comment by Vivienmm** [comment]
是不是还缺一个校对？

**Comment by sqrthree** [comment]
@Vivienmm 是的呢~ 你要是想校对的话，可以在这篇文章对应的 PR 下认领校对呀
