### ISSUE TITLE
拉模式和推模式，命令式和响应式 – 响应式编程 [Android RxJava2]（这到底是什么）：第二部分

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1242]
* 原文链接：[Pull vs Push & Imperative vs Reactive – Reactive Programming [Android RxJava2] ( What the hell is this ) Part2](http://www.uwanttolearn.com/android/pull-vs-push-imperative-vs-reactive-reactive-programming-android-rxjava2-hell-part2/)
* 掘金链接：[Pull vs Push & Imperative vs Reactive – Reactive Programming [Android RxJava2] ( What the hell is this ) Part2]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/pull-vs-push-imperative-vs-reactive-reactive-programming-android-rxjava2-hell-part2.md)
* PR 地址：#1377
* 文章分类：**Android**
----
相关文章：

- [Part 1](https://github.com/xitu/gold-miner/issues/1241)
- [part 3](https://github.com/xitu/gold-miner/issues/1419)
- [part 4](https://github.com/xitu/gold-miner/issues/1423)

----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XHShirley** [comment]
可以认领吗？

**Comment by sqrthree** [comment]
可以哈

**Comment by sqrthree** [comment]
@XHShirley 小姐姐在翻译的时候可以先看下第一部分，如果有关键词的话可以和第一部分的译者协商下哈~

**Comment by sqrthree** [comment]
@XHShirley 小姐姐，这篇进度如何了呀？

**Comment by zhaochuanxing** [comment]
可以认领校对吗？

**Comment by sqrthree** [comment]
@zhaochuanxing 译者还没有翻译完...
