### ISSUE TITLE
在 Xcode 项目中使用 swift package fetch

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1243]
* 原文链接：[Using 'swift package fetch' in an Xcode project](http://www.cocoawithlove.com/blog/package-manager-fetch.html)
* 掘金链接：[Using 'swift package fetch' in an Xcode project]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/package-manager-fetch.md)
* PR 地址：#1316
* 文章分类：**iOS**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gocy015** [comment]
放着我来

**Comment by sqrthree** [comment]
好哒
