### ISSUE TITLE
用 Python 实现每秒百万级请求

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1244]
* 原文链接：[A million requests per second with Python](https://medium.freecodecamp.com/million-requests-per-second-with-python-95c137af319#.59n519vvy)
* 掘金链接：[A million requests per second with Python]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/million-requests-per-second-with-python.md)
* PR 地址：#1278
* 文章分类：**后端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cdpath** [comment]
认领 Python 文章~

**Comment by sqrthree** [comment]
@cdpath 好哒

**Comment by sqrthree** [comment]
@cdpath 组织托我给您带个话，这篇文章的翻译进度如何了呀？

**Comment by shaunlee** [comment]
我翻译过啊：https://shaunli.com/blog/6-a-million-requests-per-second-with-python.html

**Comment by sqrthree** [comment]
@shaunlee Hello，抱歉啦，意外撞车啦，不过不知你有没有兴趣加入我们的翻译计划，一起发光发热呢？
