### ISSUE TITLE
这项浏览器改进使发向 Facebook 的网络请求节省了 60%

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1245]
* 原文链接：[This browser tweak saved 60% of requests to Facebook](https://code.facebook.com/posts/557147474482256)
* 掘金链接：[This browser tweak saved 60% of requests to Facebook]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/this-browser-tweak-saved-60%25-of-requests-to-facebook.md)
* PR 地址：#1291
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Professor-Z** [comment]
看了一眼其实算是前端的呀，想认领~ @sqrthree

**Comment by sqrthree** [comment]
@Professor-Z 好的
