### ISSUE TITLE
Android MVP 架构必要知识：第二部分

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1246]
* 原文链接：[Essential Guide For Designing Your Android App Architecture: MVP: Part 2](https://blog.mindorks.com/essential-guide-for-designing-your-android-app-architecture-mvp-part-2-b2ac6f3f9637#.k8ic3b2b3)
* 掘金链接：[Essential Guide For Designing Your Android App Architecture: MVP: Part 2]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/essential-guide-for-designing-your-android-app-architecture-mvp-part-2.md)
* PR 地址：#1254
* 文章分类：**Android**
----
相关文章：

- [第一部分](https://github.com/xitu/gold-miner/issues/1202)
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
认领翻译。

**Comment by sqrthree** [comment]
@tanglie1993 好的
