### ISSUE TITLE
World-Class Testing Development Pipeline for Android3，4

### ISSUE THREAD

**Issue by kassadin** [xitu/gold-miner#125]
World-Class Testing Development Pipeline for Android  更新了3，4

http://blog.karumi.com/world-class-testing-development-pipeline-for-android-part-4/

**Comment by Glowin** [comment]
@kassadin 感谢提醒
@antonia0912 可以把新的文章加到翻译计划里面

**Comment by kassadin** [comment]
:laughing: 是必须自己关闭吗
