### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Karthus1110** [xitu/gold-miner#1251]
- 公司/学校：龙渊网络科技有限公司/西南大学
- 工作内容/专业：iOS开发/软件工程
- 常浏览的国外网站：github,stackoverflow,apple官方文档
- 英语水平： CET-4 
- 有无翻译经验：无
- 个人博客：https://karthus1110.github.io/
- 个人介绍：经常阅读英文文档，对技术文档有好奇心，并且希望通过翻译提升自己的英文水平

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
