### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by meifans** [xitu/gold-miner#1256]
- 公司/学校：宜人贷/西安电子科技大学
- 工作内容/专业：基础架构-研发工程师/软件工程
- 常浏览的国外网站：stackoverflow，https://dzone.com/，spring.io，github so on.
- 英语水平：4级
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：我是一个热爱技术，热爱分享的人。平时喜欢看各种技术文档，愿意为翻译外国技术，让大家更容易阅读奉献一份力量。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
