### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by Evaxtt** [xitu/gold-miner#126]
你好，我是苏州大学计算机学院本科大四学生，英语水平良好，CET4:527, CET6:483, 考研英语一：72，希望加入稀土的掘金翻译计划。

**Comment by antonia0912** [comment]
@Evaxtt 欢迎来翻译计划认领翻译，你可以在 issue 里面查看待翻译和待审核的文章，直接在 issue 下留言即可。

如果方便的话，可以加我微信 antonia0912，我来拉你进译者群。
