### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by forezp** [xitu/gold-miner#1262]
- 公司/学校：深圳魔饭科技  毕业武汉理工大学/ 硕士
- 工作内容/专业： 后端开发 安卓开发
- 常浏览的国外网站：github stackoverflow
- 英语水平：cet6 英语第二学位
- 有无翻译经验：无计算机技术翻译经验
- 个人博客：http://www.jianshu.com/u/f2550db5eca3
 https://gold.xitu.io/user/580382465bbb50005b76ad36
- 个人介绍：
工作三年多，热爱互联网，爱好开源，期望为开源社区做点贡献。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
