### ISSUE TITLE
编写 React 组件的最佳实践

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1264]
* 原文链接：[Our Best Practices for Writing React Components](https://medium.com/code-life/our-best-practices-for-writing-react-components-dec3eb5c3fc8#.7gs49tw81)
* 掘金链接：[Our Best Practices for Writing React Components]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/our-best-practices-for-writing-react-components.md)
* PR 地址： #1287
* 文章分类：**前端**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by imink** [comment]
翻译认领！ THX

**Comment by sqrthree** [comment]
@imink 好哒
