### ISSUE TITLE
循环引用问题

### ISSUE THREAD

**Issue by pengshengsongcode** [xitu/gold-miner#1265]
第九条

1)如果需要使用optional

@objc protocol FireStationDelegate {
   optional func handleEmergency()
}

2)如果不需要使用optional

protocol FireStationDelegate : NSObjectProtocol {
   func handleEmergency()
}

消防站将处理紧急情况的的行动委托给消防员。

class FireStation {
   weak var delegate: FireStationDelegate?

   fun emergencyCallReceived() {
      delegate?.handleEmergency()
   }
}

**Comment by sqrthree** [comment]
@pengshengsongcode Hello，能否详细的描述一下你要表达的意思呢？

**Comment by pengshengsongcode** [comment]
如果按照你那么写，会造成循环引用，亲测，控制器不会被释放

**Comment by sqrthree** [comment]
@DeepMissea 麻烦来看下这个问题哈~

**Comment by DeepMissea** [comment]
@sqrthree ，@pengshengsongcode，不会造成循环引用。
首先这里一共 2 个实例，第一个是FireMan，另一个是 FireStation。FireStation 持有一个 FireMan 的引用（即 delegate），而 FireMan 本身并未持有任何引用，所以释放不会有问题。这是代理模式的一种正向使用，而我猜测你可能理解成了反向传值。

**Comment by sqrthree** [comment]
So, Can I close it?
