### ISSUE TITLE
为多个品牌和应用构建React组件

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1266]
* 原文链接：[Building React Components for Multiple Brands and Applications](https://medium.com/walmartlabs/building-react-components-for-multiple-brands-and-applications-7e9157a39db4#.iuko902fp)
* 掘金链接：[Building React Components for Multiple Brands and Applications]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/building-react-components-for-multiple-brands-and-applications.md)
* PR 地址：#1290
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
翻译认领

**Comment by sqrthree** [comment]
@XatMassacrE 棒棒哒
