### ISSUE TITLE
Google 是如何构建 web 框架的

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1267]
* 原文链接：[How Google builds web frameworks](https://medium.freecodecamp.com/how-google-builds-a-web-framework-5eeddd691dea#.8mtg3rqqw)
* 掘金链接：[How Google builds web frameworks]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-google-builds-a-web-framework.md)
* PR 地址：#1289
* 文章分类：**后端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fghpdf** [comment]
@sqrthree 是不是没人敢领。。。。那我的第一次翻译就要挑战这个了。。。。。

**Comment by sqrthree** [comment]
@fghpdf 哈哈哈~ 双击666
