### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by iloveivyxuan** [xitu/gold-miner#1269]
- 公司/学校：中国传媒大学
- 工作内容/专业：数字媒体艺术专业
- 常浏览的国外网站：github  Quora
- 英语水平：CET6
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：在学习前端和设计，希望可以参与翻译，能做出一点贡献，同时也提高自己的能力。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
