### ISSUE TITLE
无缝迁移 Angular 1 项目到 Angular 2

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#127]
文章链接：[Seamless Ways to Upgrade Angular 1.x to Angular 2](https://scotch.io/tutorials/seamless-ways-to-upgrade-angular-1-x-to-angular-2)
掘金链接：[无缝迁移 Angular 1 项目到 Angular 2](http://gold.xitu.io/entry/569c6ab800b04bbf350e458a)
markdown文件：[文章地址](https://github.com/xitu/gold-miner/blob/master/TODO/seamless-ways-to-upgrade-angular-1-x-to-angular-2.md)

**Comment by CoderBOBO** [comment]
我认领这个文章

**Comment by Glowin** [comment]
好啊，欢迎你的 PR

**Comment by CoderBOBO** [comment]
大概明天翻译给你

**Comment by antonia0912** [comment]
@CoderBOBO gooooooooooooood ~等你的PR

**Comment by CoderBOBO** [comment]
@antonia0912 美女怎么进你们的组织，拉一下我呗

**Comment by CoderBOBO** [comment]
@antonia0912  @Glowin   我的翻译完了

**Comment by antonia0912** [comment]
@CoderBOBO 好的辛苦啦 你可以发pr 我找人来校对

**Comment by CoderBOBO** [comment]
@antonia0912 美女美女，我翻译完了，可以merge

**Comment by CoderBOBO** [comment]
校对也完了

**Comment by antonia0912** [comment]
辛苦三位啦  翻译和校对的很认真   看到你们如此积极的配合我的工作  我也就安心了哈哈哈 @CoderBOBO @sqrthree @shenxn
