### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ZhangFe** [xitu/gold-miner#1270]
- 公司/学校：去哪儿网
- 工作内容/专业：前端开发工程师
- 常浏览的国外网站：medium，css-tricks，Github
- 英语水平：CET6
- 有无翻译经验：很少
- 个人博客：http://zhangfe.github.io/
- 个人介绍：一年半前端开发经验，有阅读英文文档的能力，想通过翻译和阅读英文文章进一步提升自己的技术水平和英文水平

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
