### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ylq167** [xitu/gold-miner#1272]
- 公司/学校：江苏金智教育信息股份有限公司
- 工作内容/专业：交互设计师
- 常浏览的国外网站：Dribble Quora behance UXmag
- 英语水平：日常沟通无障碍，能看懂汽车设计方面英文书籍，能在工具辅助下看懂用户体验设计英文资料
- 有无翻译经验：有汽车专业英语翻译经验
- 个人博客：11167.xyz 
- 个人介绍：95后。本科毕业。爱好消费级电子产品。从事交互设计工作。学习python中。喜欢掘金。希望能参与到项目中来。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
