### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by osirism** [xitu/gold-miner#1275]
- 公司/学校：武汉纺织大学
- 工作内容/专业：UI设计师
- 常浏览的国外网站：
http://www.behance.com  
http://www.medium.com  
http://www.producthunt.com  
http://www.designyourway.net

- 英语水平：商务英语中级
- 有无翻译经验：有
- 个人博客：无
- 个人介绍：3年UI设计经验

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
