### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by a243845305** [xitu/gold-miner#1276]
- 公司/学校：山西农业大学
- 工作内容/专业：软件工程专业
- 常浏览的国外网站：github、YouTube、v2ex
- 英语水平：四级水平
- 有无翻译经验：无翻译经验
- 个人博客：blog.csdn.net/a243845305
- 个人介绍：正在准备成为研究生，在增强自己的外语能力，希望在学习外语的同时在专业课上有所提升

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
