### ISSUE TITLE
在 chrome 的开发者工具里 debug node.js 代码

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#128]
文章链接：[Debugging Node.js in Chrome DevTools](http://mattdesl.svbtle.com/debugging-nodejs-in-chrome-devtools)
掘金链接：[在 chrome 的开发者工具里 debug node.js 代码](http://gold.xitu.io/entry/56af348e71cfe4005c19e82b)
markdown文件：[文章地址](https://github.com/xitu/gold-miner/blob/master/TODO/debugging-nodejs-in-chrome-devtools.md)

**Comment by sqrthree** [comment]
我来认领这一篇来咯 p( ^ O ^ )q

**Comment by vlux** [comment]
我也来认领这一篇来咯 p( ^ O ^ )q

**Comment by antonia0912** [comment]
@sqrthree 像之前那样翻译就可以啦 期待你的 PR。

@vlux 根号三抢在你前边啦  你可以等翻译完来校对  或者下午我们还会上传几篇文章  到时候可以来看看有没有感兴趣的哈~~~

**Comment by vlux** [comment]
@antonia0912 
嘤嘤嘤，好吧，下次手要快点了 :D

**Comment by antonia0912** [comment]
辛苦各位~~~
