### ISSUE TITLE
React JSX 与 Vue 模板的对比：前端界的一次对决

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1280]
* 原文链接：[React’s JSX vs Vue’s templates: a showdown on the front end](https://medium.freecodecamp.com/reacts-jsx-vs-vue-s-templates-a-showdown-on-the-front-end-b00a70470409#.wbkkiga1e)
* 掘金链接：[React’s JSX vs Vue’s templates: a showdown on the front end]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/reacts-jsx-vs-vue-s-templates-a-showdown-on-the-front-end.md)
* PR 地址：#1298
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by aleen42** [comment]
領咯, 雖然不會 Vue = =

**Comment by aleen42** [comment]
不對, 還是暫且先不接翻譯

**Comment by ZhangFe** [comment]
@sqrthree 翻译认领 :)

**Comment by sqrthree** [comment]
@ZhangFe 好哒
