### ISSUE TITLE
Android 开发者如何使用函数式编程 （一）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1282]
* 原文链接：[Functional Programming for Android developers — Part 1](https://medium.com/@anupcowkur/functional-programming-for-android-developers-part-1-a58d40d6e742#.it6ndspj6)
* 掘金链接：[Functional Programming for Android developers — Part 1]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/functional-programming-for-android-developers-part-1.md)
* PR 地址：#1292
* 文章分类：**Android**
----
相关任务：

- 第二部分：#1320
---
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by skyar2009** [comment]
@sqrthree 申请，顺便学习下

**Comment by sqrthree** [comment]
@skyar2009 好哒

**Comment by skyar2009** [comment]
https://github.com/xitu/gold-miner/pull/1292

**Comment by sqrthree** [comment]
这么快~ 666 辛苦啦
