### ISSUE TITLE
RxJava 中的 Subscriptions 是怎样泄露内存的

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1283]
* 原文链接：[How to leak memory with Subscriptions in RxJava](https://medium.com/@scanarch/how-to-leak-memory-with-subscriptions-in-rxjava-ae0ef01ad361#.frvn3pkux)
* 掘金链接：[How to leak memory with Subscriptions in RxJava]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-leak-memory-with-subscriptions-in-rxjava.md)
* PR 地址：#1296
* 文章分类：**Android**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分

**Comment by tanglie1993** [comment]
认领翻译。

**Comment by sqrthree** [comment]
@tanglie1993 好的

**Comment by jamweak** [comment]
认领校对。
