### ISSUE TITLE
重构 Swift 中单例的用法

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1284]
* 原文链接：[Refactoring singleton usage in Swift](http://www.jessesquires.com/refactoring-singletons-in-swift/)
* 掘金链接：[Refactoring singleton usage in Swift]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/refactoring-singletons-in-swift.md)
* PR 地址：#1295
* 文章分类：**iOS**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Karthus1110** [comment]
认领

**Comment by sqrthree** [comment]
@Karthus1110 好哒
