### ISSUE TITLE
Swift 中的关键字

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1285]
* 原文链接：[Swift + Keywords (V 3.0.1)](https://medium.com/the-traveled-ios-developers-guide/swift-keywords-v-3-0-1-f59783bf26c#.lidpy4e6q)
* 掘金链接：[Swift + Keywords (V 3.0.1)]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/swift-keywords.md)
* PR 地址：#1325
* 文章分类：**iOS**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeepMissea** [comment]
收，@sqrthree

**Comment by sqrthree** [comment]
好哒

**Comment by ylq167** [comment]
校对认领

**Comment by sqrthree** [comment]
@ylq167 好哒~ [校对地址](https://github.com/xitu/gold-miner/pull/1325/files)

**Comment by atuooo** [comment]
校对认领

**Comment by sqrthree** [comment]
@atuooo Hello，你是我们的译者么？

**Comment by atuooo** [comment]
@sqrthree 是的，申请过了

**Comment by sqrthree** [comment]
@atuooo 好哒~ [校对地址 #1325](https://github.com/xitu/gold-miner/pull/1325)
