### ISSUE TITLE
RESTful API Designing guidelines — The best practices

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1286]
* 原文链接：[RESTful API Designing guidelines — The best practices](https://hackernoon.com/restful-api-designing-guidelines-the-best-practices-60e1d954e7c9#.u0yjcmonc)
* 掘金链接：[RESTful API Designing guidelines — The best practices]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/restful-api-designing-guidelines-the-best-practices.md)
* PR 地址：待添加
* 文章分类：**后端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Airmacho** [comment]
认领，擅长

**Comment by jifaxu** [comment]
这篇看过，我来 @sqrthree

**Comment by sqrthree** [comment]
好哒

**Comment by sqrthree** [comment]
This post had been translated at [http://www.oschina.net/translate/restful-api-designing-guidelines-the-best-practices](http://www.oschina.net/translate/restful-api-designing-guidelines-the-best-practices), so I have to close it.
