### ISSUE TITLE
面向无神论安卓开发：如何和为什么要干掉上帝对象

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1293]
* 原文链接：[Towards Godless Android Development: How and Why I Kill God Objects](https://www.philosophicalhacker.com/post/towards-godless-android-development-how-and-why-i-kill-god-objects/)
* 掘金链接：[Towards Godless Android Development: How and Why I Kill God Objects]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/towards-godless-android-development-how-and-why-i-kill-god-objects.md)
* PR 地址：#1339
* 文章分类：**Android**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jifaxu** [comment]
这篇貌似以前看过啊，我来译 @sqrthree

**Comment by jifaxu** [comment]
不对，我发错地方了，当我没说。。。

**Comment by sqrthree** [comment]
2333, OK.

**Comment by Danny1451** [comment]
看上去蛮有意思的 认领一波！

**Comment by sqrthree** [comment]
@Danny1451 好哒

**Comment by Danny1451** [comment]
已经分享，地址： https://juejin.im/post/58c748891b69e6006be9f834
