### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by nicebug** [xitu/gold-miner#1294]
- 公司/学校：腾讯
- 工作内容/专业：自动化测试
- 常浏览的国外网站：github，stackoverflow
- 英语水平：英语四级
- 有无翻译经验：无
- 个人博客：http://nicebug.github.io/niceblogs/
- 个人介绍：一名自动化测试开发，掌握一定的python，希望为开源贡献一点点力量，能共同进步

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
