### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by reid3290** [xitu/gold-miner#1297]
- 公司/学校：上海交通大学
- 工作内容/专业：电子与通信工程
- 常浏览的国外网站：
    - [css-tricks](https://css-tricks.com/)
    - [mediem](https://medium.com/)
    - [24ways](https://24ways.org/)
    - [cssmojo](http://cssmojo.com/)
    - [nczonline](https://www.nczonline.net/)
    - [Modern JS with React](http://andrewhfarmer.com/)
- 英语水平：6级
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：上交小硕 热爱前端 正在折腾React

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
