### ISSUE TITLE
认领Android Guides 

### ISSUE THREAD

**Issue by SeniorZhai** [xitu/gold-miner#13]

**Comment by Glowin** [comment]
宅学长是你么？

**Comment by Glowin** [comment]
这篇链接到掘金[稀土掘金：Android Guides - Github](http://gold.xitu.io/entry/5584f8e9e4b09e372efeca9a) 的文章只是这个手册的前言部分，[这个手册](http://guides.codepath.com/android)里面包含了160多篇技术文章，感觉可以作为一个新的翻译活动了。

**Comment by SeniorZhai** [comment]
我说怎么就翻个前言呢~
