### ISSUE TITLE
单元测试试图告诉我们关于 Activity 的什么事情：第一部分

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1302]
* 原文链接：[What Unit Tests are Trying to Tell us about Activities: Pt. 1](https://www.philosophicalhacker.com/post/what-unit-tests-are-trying-to-tell-us-about-activities-pt1/)
* 掘金链接：[What Unit Tests are Trying to Tell us about Activities: Pt. 1]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-unit-tests-are-trying-to-tell-us-about-activities-pt1.md)
* PR 地址：#1329
* 文章分类：**Anriod**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
认领翻译。

**Comment by sqrthree** [comment]
@tanglie1993 棒棒哒

**Comment by tanglie1993** [comment]
我给原作者提了一个问题，正在等待回复中。
要不等他回我了我再提交？

**Comment by sqrthree** [comment]
先提交吧，可以随时修改呀，如果要修改的话，到时候再修改就好了

**Comment by tanglie1993** [comment]
问题是我觉得原文的意思没表达清楚。

**Comment by sqrthree** [comment]
那看看明天作者是否回复吧~ : )
