### ISSUE TITLE
处理 Redux 异步 Action 的 4 种方式

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1305]
* 原文链接：[Redux 4 Ways](https://medium.com/react-native-training/redux-4-ways-95a130da0cdc#.nyb3hqtgb)
* 掘金链接：[Redux 4 Ways]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/redux-4-ways.md)
* PR 地址：#1351
* 文章分类：**前端**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by reid3290** [comment]
认领翻译 @sqrthree

**Comment by sqrthree** [comment]
好哒~ 有问题随时@我蛤
