### ISSUE TITLE
跨站请求伪造已死！

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1306]
* 原文链接：[Cross-Site Request Forgery is dead!](https://scotthelme.co.uk/csrf-is-dead/?utm_source=webopsweekly&utm_medium=email)
* 掘金链接：[Cross-Site Request Forgery is dead!]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/csrf-is-dead.md)
* PR 地址：#1356
* 文章分类：**后端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
好哒
