### ISSUE TITLE
Universal JavaScript Apps with React Router 4

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1307]
* 原文链接：[Universal JavaScript Apps with React Router 4](https://ebaytech.berlin/universal-web-apps-with-react-router-4-15002bb30ccb#.yo42mjuo1)
* 掘金链接：[Universal JavaScript Apps with React Router 4]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/universal-web-apps-with-react-router-4.md)
* PR 地址：待添加
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xekri** [comment]
申请翻译@sqrthree 周末尽量抽出时间～

**Comment by sqrthree** [comment]
[存在译文](https://www.oschina.net/translate/universal-web-apps-with-react-router-4)
