### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by xcc3641** [xitu/gold-miner#131]
你好，我是重庆邮电大学软件学院大三学生。在努力学习Android开发，在稀土里看了很多优秀的译者对Android文章的翻译，受益匪浅，所以也想尽自己的力量帮助翻译。

这是我的一个项目地址，里面有中英文介绍。

https://github.com/xcc3641/SeeWeather

**Comment by antonia0912** [comment]
@xcc3641 欢迎加入我们掘金翻译计划的大家庭  ~~  也希望以后能有你的翻译文章分享到掘金  加我微信吧 antonia0912 我拉你进译者群  在群里你可以跟更多译者交流哈   你对哪部分比较感兴趣   可以在issue里选一两篇文章校对一下喔

**Comment by xcc3641** [comment]
谢谢，马上加。
