### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by Ruixi** [xitu/gold-miner#1310]
- 原文链接：https://medium.com/@benjaminbannister/why-typography-matters-especially-at-the-oscars-f7b00e202f22?from=timeline&isappinstalled=0#.22h37fgqr
- 简要介绍：
由最近的奥斯卡乌龙事件引申，讲述如何用设计来避免这类问题。版式设计相关。

**Comment by sqrthree** [comment]
快到碗里来

**Comment by sqrthree** [comment]
[发现译文](https://zhuanlan.zhihu.com/p/25501210) Closed #1321.
