### ISSUE TITLE
掌握 Swift 的字符串细节

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1313]
* 原文链接：[Mastering Swift: essential details about strings](https://rainsoft.io/mastering-swift-essential-details-about-strings/)
* 掘金链接：[Mastering Swift: essential details about strings]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/mastering-swift-essential-details-about-strings.md)
* PR 地址：#1521
* 文章分类：**iOS**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tuccuay** [comment]
收（

**Comment by sqrthree** [comment]
好哒

**Comment by sqrthree** [comment]
@Tuccuay 哈~ 这篇进度如何了呀？

**Comment by Tuccuay** [comment]
🌚🌚🌚🌚🌚🌚🌚🌚🌚🌚


________________________________

**Comment by Tuccuay** [comment]
https://juejin.im/post/58f822ff5c497d0058e0e427
