### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by yunshuipiao** [xitu/gold-miner#1314]
- 公司/学校：广州华多网络科技有限公司
- 工作内容/专业：android开发工程师
- 常浏览的国外网站：github，stackoverflow
- 英语水平：4级
- 有无翻译经验：有，翻译过stackoverflow的java相关问题
- 个人博客：大学时期写过几本的数据结构
- 个人介绍：本科毕业工作近一年，希望提高安卓开发能力，认识更多朋友。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
