### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zhangqippp** [xitu/gold-miner#1315]
- 公司/学校：情非得已（北京）科技有限公司
- 工作内容/专业：iOS开发工程师
- 常浏览的国外网站：github，stackoverflow，infoq
- 英语水平：六级
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：北京航空航天大学软件工程硕士，两年实习经验，三年工作经验，一直奋斗在代码搬砖第一线，主攻方向iOS开发，常年与App Store审核互撕，英语水平得到了良好的锻炼。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
