### ISSUE TITLE
Pull request review 的十大错误

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1317]
* 原文链接：[Top ten pull request review mistakes](https://blog.scottnonnenberg.com/top-ten-pull-request-review-mistakes/)
* 掘金链接：[Top ten pull request review mistakes]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/top-ten-pull-request-review-mistakes.md)
* PR 地址：#1359
* 文章分类：
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luoyaqifei** [comment]
认

**Comment by sqrthree** [comment]
哈哈好哒~

**Comment by sqrthree** [comment]
@luoyaqifei 小姐姐，这篇进度如何了呀？

**Comment by luoyaqifei** [comment]
最近有点小事情～这篇争取这周末完工！

**Comment by sqrthree** [comment]
好哒
