### ISSUE TITLE
如何让你的 React Native 应用在键盘弹出时优雅地响应

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1318]
* 原文链接：[How to make your React Native app respond gracefully when the keyboard pops up](https://medium.freecodecamp.com/how-to-make-your-react-native-app-respond-gracefully-when-the-keyboard-pops-up-7442c1535580#.ptllrq403)
* 掘金链接：[How to make your React Native app respond gracefully when the keyboard pops up]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-make-your-react-native-app-respond-gracefully-when-the-keyboard-pops-up.md)
* PR 地址：#1340
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rccoder** [comment]
认领翻译

**Comment by sqrthree** [comment]
好的

**Comment by rccoder** [comment]
Done: https://github.com/xitu/gold-miner/pull/1340
