### ISSUE TITLE
RxJava 5 点不那么明显的事

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1319]
* 原文链接：[5 Not So Obvious Things About RxJava](https://medium.com/@jagsaund/5-not-so-obvious-things-about-rxjava-c388bd19efbc#.nvd7qkl6n)
* 掘金链接：[5 Not So Obvious Things About RxJava]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/5-not-so-obvious-things-about-rxjava.md)
* PR 地址：#1338
* 文章分类：**后端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by skyar2009** [comment]
@sqrthree 认领

**Comment by sqrthree** [comment]
好哒

**Comment by skyar2009** [comment]
https://github.com/xitu/gold-miner/pull/1338
