### ISSUE TITLE
深入浅出 Android 权限（一）

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#132]
文章链接：[Permissions – Part 1](https://blog.stylingandroid.com/permissions-part-1/)
掘金链接：[深入浅出 Android 权限（一）](http://gold.xitu.io/entry/568cfad500b01b9f12af1d35)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/permissions-part-1.md)

**Comment by xcc3641** [comment]
@antonia0912 文章认领

**Comment by antonia0912** [comment]
欢迎来翻译，你直接 fork 一份代码，然后再在 markdown 上翻译，可以看看前面被 merge 的 PR 参考一下。 @xcc3641

**Comment by xcc3641** [comment]
@antonia0912 完成翻译

**Comment by markzhai** [comment]
我来校对

**Comment by lekenny** [comment]
举爪

**Comment by antonia0912** [comment]
@xcc3641 翻译完成要发PR喔  留言翻译完成  然后由 @markzhai @lekenny 两位来校对

**Comment by antonia0912** [comment]
辛苦三位啦~~ @xcc3641 @markzhai @lekenny
