### ISSUE TITLE
Android 开发者如何使用函数式编程 （二）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1320]
* 原文链接：[Functional Programming for Android developers — Part 2](https://medium.com/@anupcowkur/functional-programming-for-android-developers-part-2-5c0834669d1a#.5ie7xkqw7)
* 掘金链接：[Functional Programming for Android developers — Part 2]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/functional-programming-for-android-developers-part-2.md)
* PR 地址：#1336
* 文章分类：**Android**
----
相关任务：

- 第一部分：#1282
---
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
认领翻译。

**Comment by sqrthree** [comment]
好哒
