### ISSUE TITLE
你阅读的关于用户体验的文章在试图向你推销什么吗？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1326]
* 原文链接：[Are the UX articles you’re reading trying to sell you something?](https://uxdesign.cc/are-the-ux-articles-youre-reading-trying-to-sell-you-something-48b67d987a21#.ddsal4rj4)
* 掘金链接：[Are the UX articles you’re reading trying to sell you something?]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/are-the-ux-articles-youre-reading-trying-to-sell-you-something.md)
* PR 地址：#1383
* 文章分类：**产品**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ylq167** [comment]
翻译认领

**Comment by sqrthree** [comment]
@ylq167 棒棒哒~ come on.

**Comment by sqrthree** [comment]
@ylq167 Hello，这篇翻译进度如何了呀？
