### ISSUE TITLE
JIT 编译器快速入门 [ part 2 ]

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1327]
* 原文链接：[A crash course in just-in-time (JIT) compilers](https://hacks.mozilla.org/2017/02/a-crash-course-in-just-in-time-jit-compilers/)
* 掘金链接：[A crash course in just-in-time (JIT) compilers]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-crash-course-in-just-in-time-jit-compilers.md)
* PR 地址：#1348
* 文章分类：**前端**
----
> 本文章属于同一个系列，希望译者在翻译的时候能够和其他几篇的文章译者协同好关键术语等的翻译约定。为了提升翻译质量，系列文章参与相互校对形式，每位译者可以随意选取两篇参与校对。

相关任务：
- [part 1](https://github.com/xitu/gold-miner/issues/1330)
- [part 3](https://github.com/xitu/gold-miner/issues/1331)
- [part 4](https://github.com/xitu/gold-miner/issues/1332)
- [part 5](https://github.com/xitu/gold-miner/issues/1333)
- [part 6](https://github.com/xitu/gold-miner/issues/1328)

**备注：本系列文章已获得作者授权，翻译完成之后会经 mozilla 社区 review 后更新至原文中。**

----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhouzihanntu** [comment]
我来了！

**Comment by sqrthree** [comment]
棒棒哒~~
