### ISSUE TITLE
深入浅出 Android 权限（二）

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#133]
文章链接：[Permissions – Part 2](https://blog.stylingandroid.com/permissions-part-2/)
掘金链接：[深入浅出 Android 权限（二）](http://gold.xitu.io/entry/56af3af16240b8005a5627af)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/permissions-part-2.md)

翻译积分：4 
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by xcc3641** [comment]
@antonia0912 这个是我前一个系列的，就一起翻译了吧？

**Comment by antonia0912** [comment]
@xcc3641 好的  可以保持翻译风格一致  你一起翻译了吧

**Comment by xcc3641** [comment]
翻译完成，寻求校对。

**Comment by Sausure** [comment]
我校对

**Comment by lekenny** [comment]
请问pr链接在哪里

**Comment by Sausure** [comment]
已校对
