### ISSUE TITLE
看漫画，学 WebAssembly [part 1]

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1330]
* 原文链接：[A cartoon intro to WebAssembly](https://hacks.mozilla.org/2017/02/a-cartoon-intro-to-webassembly/)
* 掘金链接：[A cartoon intro to WebAssembly]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-cartoon-intro-to-webassembly.md)
* PR 地址：#1335
* 文章分类：**前端**
----
> 本文章属于同一个系列，希望译者在翻译的时候能够和其他几篇的文章译者协同好关键术语等的翻译约定。为了提升翻译质量，推荐系列文章之间采用译者相互校对形式，每位译者可以随意选取参与校对。

相关任务：

- [part 2](https://github.com/xitu/gold-miner/issues/1327)
- [part 3](https://github.com/xitu/gold-miner/issues/1331)
- [part 4](https://github.com/xitu/gold-miner/issues/1332)
- [part 5](https://github.com/xitu/gold-miner/issues/1333)
- [part 6](https://github.com/xitu/gold-miner/issues/1328)

**备注：本系列文章已获得作者授权，翻译完成之后会经 mozilla 社区 review 后更新至原文中。**

----
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhouzihanntu** [comment]
认领一发~

**Comment by sqrthree** [comment]
@zhouzihanntu 这篇太短了，翻译也就是 1 积分，我都不敢往外放了，要不你换一篇？

**Comment by sqrthree** [comment]
这篇太短了，还是我来吧。/阴笑

**Comment by zhouzihanntu** [comment]
@sqrthree 哈哈哈哈哈哈好
