### ISSUE TITLE
设计师的理解字距设计指南

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#134]
文章链接：[A Beginner’s Guide to Kerning Like a Designer](https://designschool.canva.com/blog/kerning/)
掘金链接：[设计师的理解字距设计指南](http://gold.xitu.io/entry/56b2bb6f128fe10052a7219f)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/kerning.md)

翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by cdpath** [comment]
认领这篇~

**Comment by antonia0912** [comment]
@cdpath 下班前最后一件事是把你这个解决了。。。。。我要去上厕所了。。。。老办法翻译吧  等你pr

**Comment by Glowin** [comment]
这个文章的中文名字翻译的有点怪怪的，麻烦 @cdpath 把把关选个顺口的标题。

**Comment by antonia0912** [comment]
@cdpath honey这篇文章翻译的怎么样啦  我看都已经差不多半个月啦  我着急给你汇总成二月份的积分给你换礼品呐
