### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by rockjins** [xitu/gold-miner#1343]
- 公司/学校：深圳智美运动科技有限公司
- 工作内容/专业：前端开发工程师/电吉他手
- 常浏览的国外网站：[http://javascriptplayground.com/](http://javascriptplayground.com/)、[https://dev.to/](https://dev.to/)、[https://www.reddit.com/r/javascript/](https://www.reddit.com/r/javascript/)
- 英语水平：大学英语没考证，全是出来自学的
- 有无翻译经验：有
- 个人博客：[https://rockjins.js.org](https://rockjins.js.org)
- 个人介绍：大学毕业后一直坚持自学英语，自己也不知道自己的英语水平到底什么样了，不过翻译的文章还是得到了很多朋友的认可，可以去我博客看看，希望能成为掘金翻译小组的一员，阿们！

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O

**Comment by sqrthree** [comment]
看到域名就要赞一个

**Comment by rockjins** [comment]
这个域名就是为了装逼，不然有何意义😏
