### ISSUE TITLE
当发布安卓开源库时我希望知道的东西 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1344]
* 原文链接：[Things I wish I knew when I started building Android SDK/Libraries](https://android.jlelse.eu/things-i-wish-i-knew-when-i-started-building-android-sdk-libraries-dba1a524d619#.bw591tw8c)
* 掘金链接：[Things I wish I knew when I started building Android SDK/Libraries](https://juejin.im/entry/58c0c15144d9040069720982/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/things-i-wish-i-knew-when-i-started-building-android-sdk-libraries.md)
* PR 地址：#1390
* 文章分类：**Android**
----
* 翻译时间：`10` 天
* 校对时间：`2` 天
* 翻译积分：`10` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jifaxu** [comment]
好长的一篇，认领 @sqrthree

**Comment by sqrthree** [comment]
@jifaxu 勇士~ 👍
