### ISSUE TITLE
Model-View-Presenter: Android guidelines

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1345]
* 原文链接：[Model-View-Presenter: Android guidelines](https://medium.com/@cervonefrancesco/model-view-presenter-android-guidelines-94970b430ddf#.e55fepeg1)
* 掘金链接：[Model-View-Presenter: Android guidelines]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/model-view-presenter-android-guidelines.md)
* PR 地址：待添加
* 文章分类：**Android**
----
* 翻译时间：`6` 天
* 校对时间：`2` 天
* 翻译积分：`6` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
认领翻译。

**Comment by sqrthree** [comment]
@tanglie1993 好哒

**Comment by tanglie1993** [comment]
http://mafei.me/2017/03/10/Model-View-Presenter:Android%E6%8C%87%E5%8D%97/
已经被翻译掉了。

**Comment by sqrthree** [comment]
@tanglie1993 你翻译了么？

**Comment by tanglie1993** [comment]
翻译了一半怎么办？

**Comment by sqrthree** [comment]
😯 那你觉得他翻译的质量如何？

**Comment by tanglie1993** [comment]
还可以吧，反正我继续翻译下去好像也没什么意义。

**Comment by sqrthree** [comment]
_(:з」∠)_ 那就取消翻译好了~
