### ISSUE TITLE
原生 iOS(Swift) 和 React-Native 的性能比较

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1346]
* 原文链接：[Comparing the Performance between Native iOS (Swift) and React-Native](https://medium.com/the-react-native-log/comparing-the-performance-between-native-ios-swift-and-react-native-7b5490d363e2#.ads9p0f4n)
* 掘金链接：[Comparing the Performance between Native iOS (Swift) and React-Native](https://juejin.im/entry/58c0c0bd0ce463005457d7c7/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/comparing-the-performance-between-native-ios-swift-and-react-native.md)
* PR 地址：#1371
* 文章分类：**iOS**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeepMissea** [comment]
收

**Comment by sqrthree** [comment]
@DeepMissea 妥
