### ISSUE TITLE
如果只有一个月入门 iOS：我该如何学习呢？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1347]
* 原文链接：[If I have one month to learn iOS: How would I spend it?](https://android.jlelse.eu/if-i-have-one-month-to-learn-ios-how-would-i-spend-it-a5b2aba87cc2#.8dh9co4nl)
* 掘金链接：[If I have one month to learn iOS: How would I spend it?]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/if-i-have-one-month-to-learn-ios-how-would-i-spend-it.md)
* PR 地址：#1370
* 文章分类：**iOS**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gocy015** [comment]
@sqrthree  ，拿了。

**Comment by sqrthree** [comment]
@Gocy015 好哒

**Comment by Gocy015** [comment]
@sqrthree ，这个我翻译完了，不过和另一个任务放同一个分支了。。等那个pr merge了我再pr哈

**Comment by sqrthree** [comment]
@Gocy015 好哒，尽快把那个搞定，另外，以后不要这样搞了。（假装生气脸）

**Comment by zhaochuanxing** [comment]
@sqrthree  可以申请校对吗？

**Comment by sqrthree** [comment]
@zhaochuanxing 好久没来玩啦~ 下次到对应的 PR #1370 下申请校对哈 : )
