### ISSUE TITLE
在你沉迷于包的海洋之前，还是了解一下运行时 Node.js 的本身

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1349]
* 原文链接：[Before you bury yourself in packages, learn the Node.js runtime itself](https://github.com/xitu/gold-miner/blob/master/TODO/before-you-bury-yourself-in-packages-learn-the-node-js-runtime-itself.md)
* 掘金链接：[Before you bury yourself in packages, learn the Node.js runtime itself]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/before-you-bury-yourself-in-packages-learn-the-node-js-runtime-itself.md)
* PR 地址：#1392
* 文章分类：**后端**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fghpdf** [comment]
@sqrthree 认领

本周去三亚，周一回来，如果有同学在此期间想翻译，这个机会就送给他/她了

**Comment by sqrthree** [comment]
好哒~

**Comment by sqrthree** [comment]
@fghpdf 主子发话了，就你了。
