### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by newbieYoung** [xitu/gold-miner#1350]
- 公司/学校：富途网络科技有限公司／东北师范大学
- 工作内容/专业：前端工程师／软件工程
- 常浏览的国外网站：stackoverflow／threejs
- 英语水平：cet4
- 有无翻译经验：无
- 个人博客：https://newbieweb.lione.me
- 个人介绍：乐于分享（喜欢装逼）的菜鸟程序员，对视觉编程有浓厚兴趣

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
