### ISSUE TITLE
如何让你的 React 应用完全的函数式、响应式，并且能处理所有令人发狂的副作用

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1352]
* 原文链接：[How to make your React app fully functional, fully reactive, and able to handle all those crazy side effects](https://medium.freecodecamp.com/how-to-make-your-react-app-fully-functional-fully-reactive-and-able-to-handle-all-those-crazy-e5da8e7dac10#.5punl8w1e)
* 掘金链接：[How to make your React app fully functional, fully reactive, and able to handle all those crazy side effects]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-make-your-react-app-fully-functional-fully-reactive-and-able-to-handle-all-those-crazy.md)
* PR 地址：#1404
* 文章分类：**前端**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZhangFe** [comment]
翻译认领 :) @sqrthree

**Comment by sqrthree** [comment]
@ZhangFe 好哒
