### ISSUE TITLE
React 未来之函数式 setState

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1353]
* 原文链接：[Functional setState is the future of React](https://medium.freecodecamp.com/functional-setstate-is-the-future-of-react-374f30401b6b#.oqusb1mlq)
* 掘金链接：[Functional setState is the future of React]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/functional-setstate-is-the-future-of-react.md)
* PR 地址：#1382
* 文章分类：**前端**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by reid3290** [comment]
@sqrthree  认领翻译

**Comment by sqrthree** [comment]
@reid3290 好哒
