### ISSUE TITLE
离线支持：不要再『稍后重试』了。

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1354]
* 原文链接：[Offline support: “Try again, later”, no more.](https://medium.com/@yonatanvlevin/offline-support-try-again-later-no-more-afc33eba79dc#.nntx3mvwx)
* 掘金链接：[Offline support: “Try again, later”, no more.]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/offline-support-try-again-later-no-more.md)
* PR 地址：#1406
* 文章分类：**Android**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by skyar2009** [comment]
领

**Comment by sqrthree** [comment]
@skyar2009 好哒

**Comment by skyar2009** [comment]
@sqrthree 最近比较忙，晚几天交

**Comment by sqrthree** [comment]
好

**Comment by skyar2009** [comment]
https://github.com/xitu/gold-miner/pull/1406
@sqrthree 不好意思，耽误太久了
