### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by goodmorningNiceday** [xitu/gold-miner#1355]
- 公司/学校：燕山大学
- 工作内容/专业：通信工程
- 常浏览的国外网站：
       https://developer.apple.com/library/content/navigation/
       http://nshipster.com
       http://iosarsenal.com
- 英语水平：cet6
- 有无翻译经验：无
- 个人博客：http://www.jianshu.com/u/8c2409cd7dfb
- 个人介绍：已经做了四年iOS开发，经常翻阅苹果官方文档，定期在公司内部做技术分享，希望加入翻译者计划，将更多iOS优质资源带给中国读者。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
