### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by weapon-xx** [xitu/gold-miner#1357]
公司/学校：广州大学
工作内容/专业：前端/计算机
常浏览的国外网站：https://medium.com/  
https://hackernoon.com/
英语水平：cet4
有无翻译经验：有
个人博客：https://weapon-xx.github.io/
http://www.jianshu.com/u/aa07ee55a85d
个人介绍：热爱前端技术，平时有写作习惯，也会去翻译一些好的英文文章，希望能够加入到翻译组，一方面提升自己的英文水平，一方面为社区做出一点点贡献 :D

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
