### ISSUE TITLE
RxSwift at first sight

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#136]
文章链接：[RxSwift at first sight](https://blog.alltheflow.com/rxswift-at-first-sight/?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=email&utm_source=iOS_Dev_Weekly_Issue_236)
掘金链接：[RxSwift at first sight](http://gold.xitu.io/entry/56b6e4a3816dfa005ae9fb21)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/rxswift-at-first-sight.md)

**Comment by davidear** [comment]
我认领！

**Comment by antonia0912** [comment]
@davidear 是在我们的译者群里嘛 我怎么没什么印章

**Comment by davidear** [comment]
@antonia0912 还要加群啊，不知道啊，我看我同事在这里翻译得了贴纸，我也过来翻译了，可以加个群么？

**Comment by iThreeKing** [comment]
🐑3⃣️ 我也想翻译这篇诶

**Comment by SatanWoo** [comment]
到底谁翻译？

**Comment by antonia0912** [comment]
@SatanWoo 可以的  你来翻译吧  期待你的pr哈~辛苦啦

**Comment by davidear** [comment]
申请校对

**Comment by antonia0912** [comment]
@davidear OK  有不明白的直接在译者群里问大家或者at我就行

**Comment by antonia0912** [comment]
@davidear  @SatanWoo @iThreeKing 辛苦三位啦~~~翻译和校对都很认真   点赞~
