### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by gy134340** [xitu/gold-miner#1361]
- 公司/学校：Machinist
- 工作内容/专业：FED
- 常浏览的国外网站：so, hn, quora
- 英语水平：cet6
- 有无翻译经验：一丢丢
- 个人博客：gy134340.com
- 个人介绍：: )

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
