### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by gaozp** [xitu/gold-miner#1364]
- 公司/学校：乐视
- 工作内容/专业：Android研发
- 常浏览的国外网站：medium stackoverflow xda java-tutorials quora
- 英语水平：CET-6
- 有无翻译经验：无（自己翻译在自己blog里算么？）
- 个人博客：gaozhipeng.me
- 个人介绍：做一些力所能及的事情吧

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
