### ISSUE TITLE
特殊任务：github.com/xitu/interviews

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1365]
文章地址：[github.com/xitu/interviews](https://github.com/xitu/interviews)

本任务属于特殊任务，需要 3 名译者协作进行翻译，翻译之后采取互相校对的方式。翻译时间尽量控制在一天内，校对时间一天。该文章已经获得作者授权，完成之后将会发 PR 至原 repo。

**Comment by llp0574** [comment]
我来

**Comment by luoyaqifei** [comment]
占坑

**Comment by phxnirvana** [comment]
+1

**Comment by sqrthree** [comment]
妥~ 加群来说。
