### ISSUE TITLE
搜索结果的最佳实践

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1372]
* 原文链接：[Best Practices for Search Results](https://uxplanet.org/best-practices-for-search-results-1bbed9d7a311#.8pysknjlm)
* 掘金链接：[Best Practices for Search Results]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/best-practices-for-search-results.md)
* PR 地址：#1395
* 文章分类：**产品 / 设计**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
领这篇
