### ISSUE TITLE
单元测试试图告诉我们关于 Activity 的什么事情：第二部分

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1373]
* 原文链接：[What Unit Tests are Trying to Tell us About Activities Pt 2](https://www.philosophicalhacker.com/post/what-unit-tests-are-trying-to-tell-us-about-activities-pt-2/)
* 掘金链接：[What Unit Tests are Trying to Tell us About Activities Pt 2]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-unit-tests-are-trying-to-tell-us-about-activities-pt-2.md)
* PR 地址：#1378
* 文章分类：**Android**
----
相关任务：

- part1: [#1302](https://github.com/xitu/gold-miner/issues/1302)

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
认领。

**Comment by sqrthree** [comment]
好的

**Comment by zhaochuanxing** [comment]
申请校对 @sqrthree
