### ISSUE TITLE
提高 Swift 的编译时间 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1374]
* 原文链接：[Improving Swift compile times](https://medium.com/@johnsundell/improving-swift-compile-times-ee1d52fb9bd#.hfqaeq76p)
* 掘金链接：[Improving Swift compile times]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/improving-swift-compile-times.md)
* PR 地址：#1402
* 文章分类：**iOS**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeepMissea** [comment]
收

**Comment by sqrthree** [comment]
好
