### ISSUE TITLE
如何在 ChromeOS 下用 Go 搭建 Web 服务

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1375]
* 原文链接：[How I built a web server using Go — and on ChromeOS](https://medium.freecodecamp.com/how-i-built-a-web-server-using-go-and-on-chromeos-3b83e4c2da5f#.rwir5yc1k)
* 掘金链接：[How I built a web server using Go — and on ChromeOS]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-i-built-a-web-server-using-go-and-on-chromeos.md)
* PR 地址：#1422
* 文章分类：**后端**
----
* 翻译时间：`8` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xiaoyusilen** [comment]
我来我来~~~终于看到我Go了~~~

**Comment by sqrthree** [comment]
@xiaoyusilen 好哒~ 哈哈还怕 Go 没人翻译呢~ 没敢加太多

**Comment by xiaoyusilen** [comment]
放着我来~保证按时完成任务~~\(≧▽≦)/~ @sqrthree
