### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by avocadowang** [xitu/gold-miner#1381]
* 公司/学校：北京中科金财科技有限公司
* 工作内容/专业：前端
* 常浏览的国外网站：
  * github
  *  stackoverflow 
* 英语水平：CET-4
* 有无翻译经验：无
* 个人博客：
  * http://www.jianshu.com/u/b2564ea1e8a7
  * https://avocadowang.github.io/
---(最近练习用hexo+githubpage搭建博客,目前没全完成,有时间会慢慢完善)
* 个人介绍：爱好编程,喜欢字母,乐于挑战,想用自己的努力为开源世界做一点点贡献

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
