### ISSUE TITLE
我是如何做到在 5 分钟之内将应用大小减少 60% 的

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1384]
* 原文链接：[How you can decrease application size by 60% (In only 5 minutes)?](https://medium.com/@kevalpatel2106/how-you-can-decrease-application-size-by-60-in-only-5-minutes-47eff3e7874e#.n28fz5n36)
* 掘金链接：[我是如何做到在 5 分钟之内将应用大小减少 60% 的](https://juejin.im/entry/58c9fda061ff4b0060161d81/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-you-can-decrease-application-size-by-60-in-only-5-minutes.md)
* PR 地址：#1425
* 文章分类：**Android**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jifaxu** [comment]
@sqrthree 领了，顺便学学

**Comment by sqrthree** [comment]
@jifaxu 好哒
