### ISSUE TITLE
在 Apache & Nginx 日志里检测爬虫机器人

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1385]
* 原文链接：[Detecting Bots in Apache & Nginx Logs](http://tech.marksblogg.com/detect-bots-apache-nginx-logs.html)
* 掘金链接：[Detecting Bots in Apache & Nginx Logs]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/detect-bots-apache-nginx-logs.md)
* PR 地址：#1449
* 文章分类：**后端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luoyaqifei** [comment]
认

**Comment by sqrthree** [comment]
好哒
