### ISSUE TITLE
编写整洁 CSS 代码的黄金法则

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1386]
* 原文链接：[Golden Guidelines for Writing Clean CSS](https://www.sitepoint.com/golden-guidelines-for-writing-clean-css/)
* 掘金链接：[Golden Guidelines for Writing Clean CSS]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/golden-guidelines-for-writing-clean-css.md)
* PR 地址：#1413
* 文章分类：**前端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by reid3290** [comment]
@sqrthree 认领翻译

**Comment by sqrthree** [comment]
好哒

**Comment by reid3290** [comment]
这个还不 close 吗？

**Comment by sqrthree** [comment]
遗忘了
