### ISSUE TITLE
单元测试，精益创业，以及两者之间的关系

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1387]
* 原文链接：[Unit testing, Lean Startup, and everything in-between](https://codewithoutrules.com/2017/03/12/software-testing-big-picture/)
* 掘金链接：[Unit testing, Lean Startup, and everything in-between](https://github.com/xitu/gold-miner/blob/master/TODO/software-testing-big-picture.md)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/software-testing-big-picture.md)
* PR 地址：#1393
* 文章分类：**开发**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gy134340** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@gy134340 好哒
