### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#1388]
- 公司/学校：东华软件
- 工作内容/专业：前端开发工程师
- 常浏览的国外网站：FreeCodeCamp Github MDN Google CodeCademy ...
- 英语水平：较好
- 有无翻译经验：无
- 个人博客：suncafe.cc
- 个人介绍：前端开发者,目前专攻 React , 英语还不错, 而且最近一直也在继续学英语,经常看英文网站和技术文档基本无障碍.

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
