### ISSUE TITLE
现代的 JavaScript 开发地图(2017) 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1389]
* 原文链接：[A Map To Modern JavaScript Development](https://hackernoon.com/a-map-to-modern-javascript-development-2017-16d9eb86309c#.5veb58lh7)
* 掘金链接：[A Map To Modern JavaScript Development]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-map-to-modern-javascript-development.md)
* PR 地址：#1396
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gy134340** [comment]
@ 认领翻译

**Comment by sqrthree** [comment]
好哒
