### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by BoilerYao** [xitu/gold-miner#1391]
学校：西安电子科技大学
专业：软件工程
常浏览的国外网站：developer.android.com; bignerdranch.com; futurestud.io等
英语水平：四级裸考优秀，比较熟练地阅读Android英文文档
有无翻译经验：翻译过一些片段
个人博客：boileryao.com备案中，可通过http://182.254.155.168访问
个人介绍：软件工程2015级在读，接触Android开发两年，算是入门。常见的库用过一些，写得都是些小东西。希望通过高质量得翻译高质量的文章助力中国开发者的进步。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
