### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by liucaihua9** [xitu/gold-miner#1394]
公司/学校：星网锐捷
工作内容/专业：Android开发实习生
常浏览的国外网站：Github、SoloLearn、
英语水平：四级裸考优秀
有无翻译经验：翻译过一些常用库的使用，见个人博客
个人博客：https://liucaihua9.github.io/
个人介绍：Android开发者，刚接触React-Native,开始看React、和React-Native的官方文档，基本没有什么大的障碍。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
