### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by bambooom** [xitu/gold-miner#1397]
- 公司/学校：开智学堂
- 工作内容/专业：主要web前端, 偶尔后端及运维
- 常浏览的国外网站：Github, SO, medium, MDN
- 英语水平：大学在香港读的, 90%英文教学
- 有无翻译经验：翻译过一两篇普通的文章, 没有翻译过技术类文章
- 个人博客：http://bambooom.github.io/ (没有啥关于技术的文章...😅
- 个人介绍：转行快一年, 觉得自己基础很差, 还需多多学习

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
