### ISSUE TITLE
震惊，还可以用这种姿势学习编程 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1398]
* 原文链接：[Unconventional way of learning a new programming language](https://hackernoon.com/unconventional-way-of-learning-a-new-programming-language-e4d1f600342c#.cf1xsucx1)
* 掘金链接：[Unconventional way of learning a new programming language]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/unconventional-way-of-learning-a-new-programming-language.md)
* PR 地址：待添加
* 文章分类：****
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iloveivyxuan** [comment]
认领

**Comment by sqrthree** [comment]
@iloveivyxuan 好哒
