### ISSUE TITLE
看！Swift 里竟然有红绿灯 🚦！

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1399]
* 原文链接：[A Quick Look at Semaphores in Swift 🚦](https://medium.com/swiftly-swift/a-quick-look-at-semaphores-6b7b85233ddb#.8rlc0cx4h)
* 掘金链接：[A Quick Look at Semaphores in Swift 🚦]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-quick-look-at-semaphores.md)
* PR 地址：#1433
* 文章分类：**iOS**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeepMissea** [comment]
收

**Comment by sqrthree** [comment]
好哒
