### ISSUE TITLE
认领Facebook iOS 应用是如何加速图片显示的？

### ISSUE THREAD

**Issue by skcheer** [xitu/gold-miner#14]

**Comment by Glowin** [comment]
好的，我给你添加到 README 里面。

另外，能不能介绍一下你呢，想认识一下你。

**Comment by Glowin** [comment]
你好，我拉了一个掘金翻译计划译者的微信群，译者都在群里面，我会在群里面更新活动的最新进展，如果方便的话可以加我一下微信 Glowjiang。

**Comment by Glowin** [comment]
请问一下这篇文章的翻译进度如何呢？

**Comment by Glowin** [comment]
你好，请问你翻译进度如何呢？

**Comment by skcheer** [comment]
Sorry，刚看到。
前段时间在赶一个项目。没有把翻译记录到GTD下来，导致忘记了。非常抱歉。这周周六会提交。希望没有对你们造成太大影响。

2016-02-18 19:52 GMT+08:00 Glow Chiang <notifications@github.com>:

**Comment by Glowin** [comment]
@skcheer 你好，这篇文章因为好久没有联系到您，我重新安排人翻译了。但是我们还是欢迎你加入我们译者微信群，来翻译其他的文章。
