### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by lovexiaov** [xitu/gold-miner#140]
Android 开发，测试爱好者。在[简书](http://www.jianshu.com/users/7378dce2d52c/latest_articles)上翻译过一些国外优秀文章，并有长期的翻译计划。

希望加入这个大家庭，一来贡献自己的一份力量，二来锻炼自己的英文水平。

**Comment by antonia0912** [comment]
@lovexiaov 欢迎欢迎  请加我微信antonia0912  我拉你进译者群
