### ISSUE TITLE
解析 Go 中的函数调用

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1400]
* 原文链接：[Anatomy of a function call in Go](https://syslog.ravelin.com/anatomy-of-a-function-call-in-go-f6fc81b80ecc#.povigaliw)
* 掘金链接：[Anatomy of a function call in Go]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/anatomy-of-a-function-call-in-go.md)
* PR 地址：#1482
* 文章分类：**后端**

----

该任务和 #1401 任务为同一任务。认领该任务后也需要翻译 #1401。

----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xiaoyusilen** [comment]
应该今晚可以把上一篇Go的review完.没问题的话明天过来认领.如果中间有其他小伙伴认领的话就归他啦~没有的话就我来~

**Comment by sqrthree** [comment]
哈哈好哒

**Comment by xiaoyusilen** [comment]
@sqrthree 看这篇一直没人领，我领了，和刚才那篇加一起，可能会稍微慢一丢丢，我会尽量按时完成的..

**Comment by sqrthree** [comment]
好的

**Comment by sqrthree** [comment]
@xiaoyusilen 这个任务是两篇文章哈~ 还请知悉。

**Comment by xiaoyusilen** [comment]
@sqrthree  了解~
