### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by danielglh** [xitu/gold-miner#1403]
- 公司/学校：Strikingly
- 工作内容/专业：Strikingly 首席架构师，同时负责 Strikingly 服务端技术团队
- 常浏览的国外网站：Hacker News, Reddit, ProductHunt, High Scalability, Airbnb Engineering blog, Paul Graham blog, Sam Altman blog, The Macro, The Netflix Tech Blog, Wait but why
- 英语水平：工作语言英语，团队中有几位外籍员工
- 有无翻译经验：
  - http://blog.jobbole.com/48521/
  - http://blog.jobbole.com/48252/
- 个人博客：无
- 个人介绍：2013年加入硅谷初创公司 Strikingly，2014年起至今担任Backend Team Leader，负责Backend，DevOps以及Data Engineering等部门的项目研发和团队管理。

**Comment by Glowin** [comment]
欢迎 Strikingly 的首席架构师

**Comment by sqrthree** [comment]
欢迎 Strikingly 的首席架构师参与我们的翻译计划一起搞点事情，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
