### ISSUE TITLE
setState() Gate

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1407]
* 原文链接：[setState() Gate](https://medium.com/javascript-scene/setstate-gate-abc10a9b2d82#.z148awo8n)
* 掘金链接：[setState() Gate]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/setstate-gate-abc.md)
* PR 地址：#1447
* 文章分类：**前端**
----
* 翻译时间：`9` 天
* 校对时间：`2` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by reid3290** [comment]
@sqrthree 占个坑先

**Comment by sqrthree** [comment]
好
