### ISSUE TITLE
关于在 Node.js 中引用模块，知道这些就够了

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1408]
* 原文链接：[Requiring modules in Node.js: Everything you need to know](https://medium.freecodecamp.com/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8#.wcrwm9c81)
* 掘金链接：[Requiring modules in Node.js: Everything you need to know]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/requiring-modules-in-node-js-everything-you-need-to-know.md)
* PR 地址：#1496
* 文章分类：**后端**
----
* 翻译时间：`9` 天
* 校对时间：`2` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhouzihanntu** [comment]
哇九分！认…认领

**Comment by sqrthree** [comment]
好哒
