### ISSUE TITLE
RxJava 中的多线程

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1409]
* 原文链接：[Multithreading with RxJava](https://android.jlelse.eu/multithreading-with-rxjava-dadddc4f7a63#.yghtx4u43)
* 掘金链接：[Multithreading with RxJava]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/multithreading-with-rxjava-dadddc.md)
* PR 地址：#1544
* 文章分类：**Android**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by phxnirvana** [comment]
领~

**Comment by sqrthree** [comment]
@phxnirvana 好哒
