### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by SansaZhang** [xitu/gold-miner#141]
前端爱好者,现任某互联网公司js工程师,坐标北京.2015届计算机专业本科毕业生,英语四六级,阅读英文文献无障碍.希望能成为你们的译者,共同进步.

**Comment by antonia0912** [comment]
你可以先尝试校对一篇文章哈 在issue里有校对认领label的标签是需要校对的 你在下边留言申请校对   @SansaZhang
