### ISSUE TITLE
Android 如何实现气泡选择动画

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1410]
* 原文链接：[How to Create a Bubble Selection Animation on Android](https://medium.com/@igalata13/how-to-create-a-bubble-selection-animation-on-android-627044da4854#.7iwkfupy7)
* 掘金链接：[How to Create a Bubble Selection Animation on Android]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-create-a-bubble-selection-animation-on-android.md)
* PR 地址：#1466
* 文章分类：**Android**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by skyar2009** [comment]
领

**Comment by sqrthree** [comment]
好哒

**Comment by skyar2009** [comment]
https://github.com/xitu/gold-miner/pull/1466

**Comment by ylq167** [comment]
校对认领

**Comment by sqrthree** [comment]
@ylq167 好哒

**Comment by ylq167** [comment]
@sqrthree [捂脸]因为太久没人管就关闭了吗？

**Comment by sqrthree** [comment]
@ylq167 这篇不是已经翻译完成了么？PR 在 #1466

**Comment by ylq167** [comment]
@sqrthree  就我一个人校对嘛

**Comment by sqrthree** [comment]
zhaochuanxing 也校对了啊~ 233 校对是在 PR 下认领的啦
