### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by nanflower** [xitu/gold-miner#1411]
-\ 公司/学校：西安交通大学
-\ 工作内容/专业：前端开发 通信工程
-\ 常浏览的国外网站：www.github.com
-\ 英语水平：英语六级
-\ 有无翻译经验：有
-\ 个人博客：
-\ 个人介绍：前端新人，爱学习，爱分享

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
