### ISSUE TITLE
如何使用 JavaScript 构建响应式引擎 —— Part 1：可观察的对象

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1414]
* 原文链接：[How to build a reactive engine in JavaScript. Part 1: Observable objects](https://monterail.com/blog/2016/how-to-build-a-reactive-engine-in-javascript-part-1-observable-objects)
* 掘金链接：[How to build a reactive engine in JavaScript. Part 1: Observable objects]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-build-a-reactive-engine-in-javascript-part-1-observable-objects.md)
* PR 地址：#1421
* 文章分类：**前端**

----
相关任务：

- Part 2: #1417
----

* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by IridescentMia** [comment]
@sqrthree 认领这篇

**Comment by sqrthree** [comment]
好哒
