### ISSUE TITLE
如何使用 JavaScript 构建响应式引擎 —— Part 2：计算属性和依赖追踪

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1417]
* 原文链接：[How to build a reactive engine in JavaScript. Part 2: Computed properties and dependency tracking](https://monterail.com/blog/2017/computed-properties-javascript-dependency-tracking)
* 掘金链接：[How to build a reactive engine in JavaScript. Part 2: Computed properties and dependency tracking]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/computed-properties-javascript-dependency-tracking.md)
* PR 地址：#1442
* 文章分类：**前端**
----

相关任务：

- Part 1: #1414
----

* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by IridescentMia** [comment]
@sqrthree 这个也我来吧

**Comment by sqrthree** [comment]
好啊好啊~ 注意在两个分支上翻译哈，并单独发 PR。

**Comment by IridescentMia** [comment]
好的
