### ISSUE TITLE
函数式接口，默认方法，纯函数，函数的副作用，高阶函数，可变的和不可变的，函数式编程和 Lambda 表达式 - 响应式编程 ［Android RxJava 2］（这到底是什么）第三部分

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1419]
* 原文链接：[Reactive Programming [ Android RxJava2 ] ( What the hell is this ) Part3](http://www.uwanttolearn.com/android/functional-interfaces-functional-programming-and-lambda-expressions-reactive-programming-android-rxjava2-what-the-hell-is-this-part3/)
* 掘金链接：[Reactive Programming [ Android RxJava2 ] ( What the hell is this ) Part3]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/functional-interfaces-functional-programming-and-lambda-expressions-reactive-programming-android-rxjava2-what-the-hell-is-this-part3.md)
* PR 地址：#1578
* 文章分类：**Android**
----
相关文章：

- [Part 1](https://github.com/xitu/gold-miner/issues/1241)
- [part 2](https://github.com/xitu/gold-miner/issues/1242)
- [part 4](https://github.com/xitu/gold-miner/issues/1423)
- [part 5](https://github.com/xitu/gold-miner/issues/1554)

----
* 翻译时间：`9` 天
* 校对时间：`2` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XHShirley** [comment]
作死认领吧。

**Comment by sqrthree** [comment]
哈哈哈好~ 你先翻译这篇吧，如果这个翻译完了，第四部分还没有人翻译的话你就来吧。

**Comment by sqrthree** [comment]
小姐姐，这篇文章的进度如何了呀？
