### ISSUE TITLE
大战 RxJava2 和 Java8 Stream [ Android RxJava2 ] （这到底是什么） 第四部分

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1423]
* 原文链接：[War against Learning Curve of Rx Java 2 + Java 8 Stream [ Android RxJava2 ] ( What the hell is this ) Part4](http://www.uwanttolearn.com/android/war-learning-curve-rx-java-2-java-8-stream-android-rxjava2-hell-part4/)
* 掘金链接：[War against Learning Curve of Rx Java 2 + Java 8 Stream [ Android RxJava2 ] ( What the hell is this ) Part4]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/war-learning-curve-rx-java-2-java-8-stream-android-rxjava2-hell-part4.md)
* PR 地址：#1499
* 文章分类：**Android**
----
相关文章：

- [Part 1](https://github.com/xitu/gold-miner/issues/1241)
- [part 2](https://github.com/xitu/gold-miner/issues/1242)
- [part 3](https://github.com/xitu/gold-miner/issues/1419)

----
* 翻译时间：`8` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XHShirley** [comment]
可以承包这个部分，如果小哥不怕我工作太忙会有点拖延。。

**Comment by BoilerYao** [comment]
刚简单看了一遍，申请翻译~ @sqrthree

**Comment by sqrthree** [comment]
@BoilerYao 好哒~ 那就你来翻译吧。 之前几篇的译者是 @XHShirley 目前在翻译 part 3，有问题你们协商一下哈。

**Comment by Vivienmm** [comment]
还缺人不，校对认领
