### ISSUE TITLE
生活在 JavaScript 之中：学习第二门语言的好处

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1424]
* 原文链接：[Life after JavaScript: The Benefits of Learning a 2nd Language](https://www.sitepoint.com/life-after-js-learning-2nd-language/)
* 掘金链接：[Life after JavaScript: The Benefits of Learning a 2nd Language](https://juejin.im/entry/58d5db47570c350058d1090a/detail)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/life-after-js-learning-2nd-language.md)
* PR 地址：#1440
* 文章分类：**不分类**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gy134340** [comment]
@sqrthree 认领翻译

**Comment by sqrthree** [comment]
好哒
