### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by cfanlife** [xitu/gold-miner#1426]
-\ 公司/学校：沪江
-\ 工作内容/专业：前端工程师
-\ 常浏览的国外网站：Google,Quora,StackOverflow,GitHub...
-\ 英语水平：英语六级
-\ 有无翻译经验：有
-\ 个人博客：http://www.jianshu.com/u/d6e83ee69161
-\ 个人介绍：翻译=锻炼英语+提升技术+分享知识,所以何乐而不为?

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
