### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by yanyixin** [xitu/gold-miner#1427]
-\ 公司/学校：上海沪江教育有限公司
-\ 工作内容/专业：web前端开发工程师
-\ 常浏览的国外网站：http://stackoverflow.com, Google, GitHub
-\ 英语水平：四级
-\ 有无翻译经验：无
-\ 个人博客： www.iyanmeng.com
-\ 个人介绍：在翻译中学习知识，在翻译中提升自己。通过翻译分享更过的内容给小伙伴。

**Comment by sqrthree** [comment]
欢迎泸江的小伙伴们组队加入啦，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
