### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zhengxiaowai** [xitu/gold-miner#1428]
-\ 公司/学校：TCL 互联网事业部
-\ 工作内容/专业：Python工程师、Web 全栈工程师
-\ 常浏览的国外网站：GitHub、Stackoverflow、Reddit、Hacker News
-\ 英语水平：CET-4
-\ 有无翻译经验：有
-\ 个人博客：https://hexiangyu.me
-\ 个人介绍：热爱开源、Python、JavaScript、Linux、Docker 爱好者、擅长 Web 领域开发

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
