### ISSUE TITLE
关于 The System Design Primer 的翻译任务

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1430]
### 
[The System Design Primer](https://github.com/donnemartin/system-design-primer) 该文档我们已经拿到简体中文翻译授权，负责简体中文版的翻译及后续更新，目前全文共计一万词左右，计划由 5 位译者进行翻译和校对。该文档将分成五部分，每位译者分别负责一部分，翻译完成之后互相校对。

校对关系为：
```
1 => 2, 3
2 => 3, 4
3 => 4, 5
4 => 5, 1
5 => 1, 2
```

- 翻译时间： 7 天
- 校对时间： 4 天

### 相关链接

- 英文 Repo 地址：[donnemartin/system-design-primer](https://github.com/donnemartin/system-design-primer)
- 翻译 Repo 地址：[xitu/system-design-primer](https://github.com/xitu/system-design-primer)
- Markdown 文件：[README-zh-Hant.md](https://github.com/xitu/system-design-primer/blob/master/README-zh-Hant.md)

### 任务划分：

- 1：从文章开始 —— 到 [#object-oriented-design-interview-questions-with-solutions](https://github.com/xitu/system-design-primer/blob/master/README-zh-Hant.md#object-oriented-design-interview-questions-with-solutions) 之前，由 @XatMassacrE 负责翻译
- 2：第二部分：从 [#object-oriented-design-interview-questions-with-solutions](https://github.com/xitu/system-design-primer/blob/master/README-zh-Hant.md#object-oriented-design-interview-questions-with-solutions) —— 到 [#reverse-proxy-web-server](https://github.com/xitu/system-design-primer/blob/master/README-zh-Hant.md#reverse-proxy-web-server) 之前，由 @L9m 负责翻译
- 3：第三部分：从  [#reverse-proxy-web-server](https://github.com/xitu/system-design-primer/blob/master/README-zh-Hant.md#reverse-proxy-web-server) —— 到 [#sources-and-further-reading-graph](https://github.com/xitu/system-design-primer/blob/master/README-zh-Hant.md#sources-and-further-reading-graph) 之前，由 @Airmacho  负责翻译
- 4：第四部分：从 [#sources-and-further-reading-graph](https://github.com/xitu/system-design-primer/blob/master/README-zh-Hant.md#sources-and-further-reading-graph) —— 到 [#user-datagram-protocol-udp](https://github.com/xitu/system-design-primer/blob/master/README-zh-Hant.md#user-datagram-protocol-udp) 之前，由 @xiaoyusilen 负责翻译
- 5：第五部分：从 [#user-datagram-protocol-udp](https://github.com/xitu/system-design-primer/blob/master/README-zh-Hant.md#user-datagram-protocol-udp) —— 到最后，@jifaxu 负责翻译。

**Comment by XatMassacrE** [comment]
搞起

**Comment by L9m** [comment]
翻译认领

**Comment by aleen42** [comment]
认领吧

**Comment by XatMassacrE** [comment]
@sqrthree 标题多了个 r

**Comment by Airmacho** [comment]
有兴趣，这个时间是怎么预定义的？

**Comment by xiaoyusilen** [comment]
同问时间。

**Comment by sqrthree** [comment]
- 翻译时间： 7 天
- 校对时间： 2 天

这个大家感觉如何？时间这个可以协商，尽快搞定就 OK 了。质量第一。

**Comment by aleen42** [comment]
我看大部分都是标题的翻译，具体文字应该没多少

**Comment by sqrthree** [comment]
OK, @Airmacho @xiaoyusilen 确认一下是否参与咯~ 人满就发车。

**Comment by xiaoyusilen** [comment]
@sqrthree  领了..

**Comment by aleen42** [comment]
校对时间长一点吧 = =，刚入职怕应付不过来，因为还要校对两部分

**Comment by sqrthree** [comment]
嗯，我原本的意思校对一部分是 2 天。表达有误，哈哈那我改成 4 天好了。

**Comment by Airmacho** [comment]
认领，然后请问每一部分是怎么划的？

**Comment by aleen42** [comment]
三爷来划分吧

**Comment by sqrthree** [comment]
现在还差第五部分需要翻译哈。

**Comment by jifaxu** [comment]
@sqrthree 举手，申请上车

**Comment by sqrthree** [comment]
@jifaxu 坐好第五个座，我们发车啦。
