### ISSUE TITLE
用 Dagger 2 实现依赖注入

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1434]
* 原文链接：[Dependency Injection with Dagger 2](https://github.com/codepath/android_guides/wiki/Dependency-Injection-with-Dagger-2)
* 掘金链接：[Dependency Injection with Dagger 2]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/Dependency-Injection-with-Dagger-2.md)
* PR 地址：#1484
* 文章分类：**Android**
----
* 翻译时间：`9` 天
* 校对时间：`2` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
认领翻译。

**Comment by sqrthree** [comment]
好哒

**Comment by tanglie1993** [comment]
https://github.com/xitu/gold-miner/blob/master/TODO/Dependency-Injection-with-Dagger-2.md 
无法分享。显示“该文章已被分享”。
