### ISSUE TITLE
超越浏览器：从 web 应用到桌面应用

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1435]
* 原文链接：[Beyond The Browser: From Web Apps To Desktop Apps](https://www.smashingmagazine.com/2017/03/beyond-browser-web-desktop-apps/)
* 掘金链接：[Beyond The Browser: From Web Apps To Desktop Apps]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/beyond-browser-web-desktop-apps.md)
* PR 地址：待添加
* 文章分类：**前端**
----
* 翻译时间：`10` 天
* 校对时间：`4` 天
* 翻译积分：`20` 分
* 校对积分：`4` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

该文章因为过长，需要两人翻译，另外译者互相校对，再需要一位译者负责单独整体校对，一共三位译者参与。以第 230 行为分界线。

**Comment by bambooom** [comment]
认领一个~ 两个人怎么分?

**Comment by sqrthree** [comment]
@bambooom 以 230 行为分界线哈。

**Comment by bambooom** [comment]
@sqrthree 👌 那我就前面一半啦~

**Comment by sqrthree** [comment]
好的

**Comment by imink** [comment]
@sqrthree 我来翻译230行之后的吧，到时候pull & request是在一个issue里面完成么？

**Comment by sqrthree** [comment]
@imink 好哒~ PR 的话你们看怎么方便吧，如果能放到一个 PR 里最好的啦，方便校对嘛。 : )

**Comment by bambooom** [comment]
@imink 我的[前半](https://github.com/bambooom/gold-miner/blob/translate/TODO/beyond-browser-web-desktop-apps.md)终于搞完了。。。你的部分如何了？如何只提交一个 PR？

**Comment by imink** [comment]
@bambooom 我写完了之后，直接在你的pr上comment，然后就辛苦你粘贴复制了。我就不单独发pr了。

**Comment by bambooom** [comment]
@imink 或者你完成了的话直接把你的部分发我邮箱，我再一起提 pr，如何？我邮箱：nmz89825@gmail.com

**Comment by sqrthree** [comment]
二位辛苦啦

**Comment by imink** [comment]
@bambooom  发给你了。

**Comment by imink** [comment]
@bambooom  回头麻烦把分享后的链接也发给我下吧。THX！

**Comment by bambooom** [comment]
@imink 啊 其实膜法小编还没给我搞好原创权限....要不你来分享吧~

**Comment by imink** [comment]
@bambooom 你说联合编辑的权限么，我这边可以分享。要不然就我来分享吧。

**Comment by sqrthree** [comment]
现在是分享到专栏，需要有专栏权限。我帮你问下膜法小编。

**Comment by bambooom** [comment]
@sqrthree 嗯嗯 权限已经搞定~
@imink 嗯好的~👌

**Comment by imink** [comment]
@sqrthree  @bambooom  文章分享过了。地址在 https://juejin.im/entry/58f07ea5ac502e006c1e0301/detail

**Comment by sqrthree** [comment]
@imink 以后用专栏发布哈~ 策略改了，[wiki](https://github.com/xitu/gold-miner/wiki/%E5%88%86%E4%BA%AB%E5%88%B0%E6%8E%98%E9%87%91%E6%8C%87%E5%8D%97) 中已经更新了你可以看下。

**Comment by imink** [comment]
@sqrthree  我好像还没有权限发专栏，没有找到专栏发布的入口。还是说，默认添加 翻译计划的标签，就自动发布到专栏？

**Comment by bambooom** [comment]
@imink 不是的呢 要找膜法小编开通权限

**Comment by sqrthree** [comment]
是的，可以在群里找 `膜法小编` 给你开权限哈。
