### ISSUE TITLE
nginScript 入门

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1436]
* 原文链接：[Introduction to nginScript](https://www.nginx.com/blog/introduction-nginscript/)
* 掘金链接：[Introduction to nginScript]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/introduction-nginscript.md)
* PR 地址：#1490
* 文章分类：**后端**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by 1992chenlu** [comment]
认领～ @sqrthree

**Comment by sqrthree** [comment]
好哒
