### ISSUE TITLE
一个人的 Android 开发

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1437]
* 原文链接：[Flying Solo with Android Development](https://hackernoon.com/flying-solo-with-android-development-c52d911b62bf#.yhgjjtwz1)
* 掘金链接：[Flying Solo with Android Development]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/flying-solo-with-android-development.md)
* PR 地址：#1444
* 文章分类：**Android**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by BoilerYao** [comment]
申请翻译~  @sqrthree

**Comment by sqrthree** [comment]
@BoilerYao 好哒
