### ISSUE TITLE
一名 iOS 开发者的 React Native 开发经历

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1438]
* 原文链接：[An iOS Dev’s Experience with React Native](https://blog.madebywindmill.com/an-ios-devs-experience-with-react-native-559275b5a4e8#.qvkcgzpaa)
* 掘金链接：[An iOS Dev’s Experience with React Native]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/an-ios-devs-experience-with-react-native.md)
* PR 地址：#1473
* 文章分类：**iOS**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
没人认领我认领翻译算了XD  @sqrthree 

..感觉这篇文章会引战

**Comment by sqrthree** [comment]
2333 好的

**Comment by lsvih** [comment]
前两天突然有事，耽误了些时间。今天晚上一定完成

**Comment by sqrthree** [comment]
好~ 没事，质量第一啦
