### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by carvinlo** [xitu/gold-miner#1443]
-\ 原文链接：https://marmelab.com/blog/2017/02/06/react-is-slow-react-is-fast.html
-\ 简要介绍：前端react性能优化，从谷歌浏览器性能分析入手

**Comment by sqrthree** [comment]
好哒~ 非常感谢

**Comment by carvinlo** [comment]
这篇推荐文章对我很重要，请问我怎么知道已经被翻译，目前都是刷页面查找对

**Comment by sqrthree** [comment]
Issue 地址在 #1467 ，目前来说你可以 watch 这个项目，等译者完成发 PR 时，可以收到邮件通知。

**Comment by sqrthree** [comment]
我们正在开发一个更为完善的通知机制，不过还需要一段时间。😂

**Comment by carvinlo** [comment]
thx，看到翻译推文了，通知机制确实需要改进，目前我是通过掘金推文，不是在邮件通知里知道已翻译完毕，不过貌似贵方已有好的方案在计划着😄

**Comment by carvinlo** [comment]
噢，我说的是掘金ios app的推文

**Comment by carvinlo** [comment]
https://www.awesomes.cn/
你们是否考虑将翻译做成一个产品，提高用户体验，类似以上

**Comment by sqrthree** [comment]
我们已经在开始做啦~ 😄
