### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by 1992chenlu** [xitu/gold-miner#1445]
-\ 公司/学校
-\ 工作内容/专业：Software Development Engineer
-\ 常浏览的国外网站：stackoverflow.com ; geeksforgeeks.org
-\ 英语水平： 托福 106; 六级 613
-\ 有无翻译经验：无
-\ 个人博客：http://codechen.blogspot.com/
-\ 个人介绍：目前在美国做码农，希望利用空闲时间参与翻译计划，学习一些优秀的技术文章，与大家共同进步！：）

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
