### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by chuchu2016** [xitu/gold-miner#1446]
-\ 公司/学校：搜狐
-\ 工作内容/专业：前端
-\ 常浏览的国外网站：risingstack，medium
-\ 英语水平：大学英语四级
-\ 有无翻译经验：有，https://www.w3ctech.com/topic/1970，https://www.w3ctech.com/topic/1969
-\ 个人博客：无
-\ 个人介绍：擅长前端，Nodejs

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
