### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Labmem003** [xitu/gold-miner#1448]
-\ 公司/学校：Nonolive
-\ 工作内容/专业：Android工程师
-\ 常浏览的国外网站：medium.com，android-developers.googleblog.com，androidweekly.net
-\ 英语水平：CET-6
-\ 有无翻译经验：无
-\ 个人博客：http://greens1995.com/
-\ 个人介绍：持续关注Android 性能调优、单元测试和重构、实用中间件、各种好玩的特效和黑科技。希望能参加翻译计划，分享一些这方面的好内容。

**Comment by Pre-Fantasy** [comment]
-\ 公司/学校 : 云杉领金
-\ 工作内容/专业 : Java工程师
-\ 常浏览的论坛 : CSDN, InforQ, gold-miner, cnblogs.com
-\ 英语水平 : CET-4
-\ 有无翻译经验 : 无
-\ 个人博客 : http://blog.csdn.net/pre_fantasy
-\ 个人介绍 : 从事java一线开发, 熟悉js等前端技术. 希望能有机会参加翻译计划的工作, 和所有喜爱编程的朋友梦分享成长的快乐.

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
