### ISSUE TITLE
webpack 拾翠：充分利用 CommonsChunkPlugin() 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1451]
* 原文链接：[webpack bits: Getting the most out of the CommonsChunkPlugin()](https://medium.com/webpack/webpack-bits-getting-the-most-out-of-the-commonschunkplugin-ab389e5f318#.hn8v7ul1f)
* 掘金链接：[webpack bits: Getting the most out of the CommonsChunkPlugin()]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/webpack-bits-getting-the-most-out-of-the-commonschunkplugin.md)
* PR 地址：#1508
* 文章分类：**前端**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by reid3290** [comment]
占坑~ @sqrthree

**Comment by sqrthree** [comment]
好哒

**Comment by reid3290** [comment]
@sqrthree [已分享](https://juejin.im/post/58ec4e3f5c497d0062c470bf)
