### ISSUE TITLE
写给“古代” Web 开发者的“现代” JavaScript 指南

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1452]
* 原文链接：[Modern JavaScript for Ancient Web Developers](https://trackchanges.postlight.com/modern-javascript-for-ancient-web-developers-58e7cae050f9#.ibsx51ylz)
* 掘金链接：[Modern JavaScript for Ancient Web Developers]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/modern-javascript-for-ancient-web-developers.md)
* PR 地址：#1506
* 文章分类：**前端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
@sqrthree  领

**Comment by sqrthree** [comment]
好哒
