### ISSUE TITLE
细节是产品设计的重中之重

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1453]
* 原文链接：[The Details That Matter](https://uxplanet.org/the-details-that-matter-8b962ca58b49#.ypigeruoq)
* 掘金链接：[The Details That Matter]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-details-that-matter.md)
* PR 地址：#1489
* 文章分类：**产品**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iloveivyxuan** [comment]
认领

**Comment by sqrthree** [comment]
好哒

**Comment by ylq167** [comment]
校对认领 @sqrthree

**Comment by sqrthree** [comment]
@ylq167 好哒~ PR 地址在 #1489，下次直接到对应的 PR 下申请就可以啦。
