### ISSUE TITLE
Swift 闭包和代理中的保留周期

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1454]
* 原文链接：[Swift Retention Cycle in Closures and Delegate](https://blog.bobthedeveloper.io/swift-retention-cycle-in-closures-and-delegate-836c469ef128#.8z0z62321)
* 掘金链接：[Swift Retention Cycle in Closures and Delegate]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/swift-retention-cycle-in-closures-and-delegate.md)
* PR 地址：#1480
* 文章分类：**iOS**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
这是ios的好吗……

**Comment by sqrthree** [comment]
_(:з」∠)_ 已改。

**Comment by atuooo** [comment]
@sqrthree 认领

**Comment by sqrthree** [comment]
@atuooo 好的
