### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Pre-Fantasy** [xitu/gold-miner#1455]
- 公司/学校：云杉领金
- 工作内容/专业：java工程师
- 常浏览的国外网站：stackoverflow.com,  medium.com
- 英语水平：CET-4
- 有无翻译经验：无翻译经验
- 个人博客：http://blog.csdn.net/pre_fantasy
- 个人介绍：本人从事java一线工作, 熟悉js等前端技术. 对翻译文献拥有热情, 希望能够和各位译者一起完成翻译工作.

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
