### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by sunyuhui** [xitu/gold-miner#1458]
- 公司/学校：美团
- 工作内容/专业：前端
- 常浏览的国外网站：MDN
- 英语水平：CET-6
- 有无翻译经验：无
- 个人博客：https://sunyuhui.com/
- 个人介绍：本来想在团队内推动大家一起来翻译，但是没什么人一起做，非常希望参与到翻译计划中，会长期投入精力

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
