### ISSUE TITLE
Reactive GraphQL Architecture

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#146]
文章链接：[Reactive GraphQL Architecture](https://github.com/apollostack/apollo/blob/master/design/high-level-reactivity.md)
掘金链接：[Reactive GraphQL Architecture](http://gold.xitu.io/entry/56be959232132c0052a70cee)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/high-level-reactivity.md)

[PR地址](https://github.com/xitu/gold-miner/pull/156/files?diff=split)

翻译积分：8
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by shenxn** [comment]
认领！

**Comment by lekenny** [comment]
手真快 @shenxn

**Comment by antonia0912** [comment]
@shenxn 好的 期待你的pr喔~~~

**Comment by antonia0912** [comment]
@lekenny 你可以来校对喔~~~

**Comment by lekenny** [comment]
@antonia0912    好的

**Comment by antonia0912** [comment]
@lekenny pr地址 https://github.com/xitu/gold-miner/pull/156/files?diff=split
