### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by hlk-1135** [xitu/gold-miner#1460]
- 公司/学校：鲁东大学
- 工作内容/专业：软件工程
- 常浏览的国外网站：http://stackoverflow.com/
- 英语水平：CET-4
- 有无翻译经验：无
- 个人博客：http://blog.csdn.net/HLK_1135
- 个人介绍：学生党一枚，希望通过翻译文章更好的学习知识。英语水平虽不是很突出，但是会倾尽所能。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
