### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by warjiang** [xitu/gold-miner#1462]
- 公司/学校：东南大学
- 工作内容/专业：SDN、Spark、前端
- 常浏览的国外网站：quora、google+、medium
- 英语水平：CET6
- 有无翻译经验：暂无
- 个人博客：http://warjiang.github.io/devcat/
- 个人介绍：在读学生，主要方向是SDN,全栈开发，喜欢前端开发，喜欢尝试各种新奇技术。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
