### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by hudson6666** [xitu/gold-miner#1464]
- 公司/学校：东北大学
- 工作内容/专业：自动化/在校任团委先锋网开发工作
- 常浏览的国外网站：wikipedia github stackoverflow
- 英语水平：TOEFL 91， CET6 543
- 有无翻译经验：无
- 个人博客：https://blog.cool2645.com
- 个人介绍：学生党一枚、希望未来从业IT

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
