### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by reid3290** [xitu/gold-miner#1465]
原文链接： [Preload, Prefetch And Priorities in Chrome](https://medium.com/reloading/preload-prefetch-and-priorities-in-chrome-776165961bbf)
简要介绍：深入阐述了 Chome 浏览器中的 `preload` 和 `prefetch` 机制

**Comment by sqrthree** [comment]
棒棒哒~ 非常感谢

**Comment by sqrthree** [comment]
#1470
