### ISSUE TITLE
React 的慢与快：优化 React 应用实战

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1467]
* 原文链接：[React is Slow, React is Fast: Optimizing React Apps in Practice](https://marmelab.com/blog/2017/02/06/react-is-slow-react-is-fast.html)
* 掘金链接：[React is Slow, React is Fast: Optimizing React Apps in Practice]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/react-is-slow-react-is-fast.md)
* PR 地址：#1494
* 文章分类：**前端**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by AceLeeWinnie** [comment]
@sqrthree 认领

**Comment by sqrthree** [comment]
好哒

**Comment by AceLeeWinnie** [comment]
#1494 翻译完成 @sqrthree
