### ISSUE TITLE
模块化 vs 微服务

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1468]
* 原文链接：[Modules vs. microservices](https://www.oreilly.com/ideas/modules-vs-microservices)
* 掘金链接：[Modules vs. microservices]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/modules-vs-microservices.md)
* PR 地址：#1483
* 文章分类：**后端**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
没人认领我来算啦~ @sqrthree 认领翻译

**Comment by sqrthree** [comment]
好哒
