### ISSUE TITLE
O-h yeah! What we look forward to in Android O

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1469]
* 原文链接：[O-h yeah! What we look forward to in Android O](https://www.novoda.com/blog/o-h-yeah-what-we-look-forward-to-in-android-o/)
* 掘金链接：[O-h yeah! What we look forward to in Android O]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/o-h-yeah-what-we-look-forward-to-in-android-o.md)
* PR 地址：待添加
* 文章分类：**Android**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
看这篇文章这么可怜，我认领了算了。

**Comment by sqrthree** [comment]
好的

**Comment by sqrthree** [comment]
@tanglie1993 你先看下这篇文章的翻译价值如何哈？如果要是没什么太大的价值的话就不翻译了。

**Comment by sqrthree** [comment]
@tanglie1993 Hello，这篇文章的进度如何了呀？

**Comment by tanglie1993** [comment]
呃……不太想翻译这篇文章。有很多地方我不确定应该怎么翻译。

**Comment by sqrthree** [comment]
那你开始翻译了么？没有的话就取消翻译 close 掉了。
