### ISSUE TITLE
Preload，Prefetch 和它们在 Chrome 之中的优先级

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1470]
* 原文链接：[Preload, Prefetch And Priorities in Chrome](https://medium.com/reloading/preload-prefetch-and-priorities-in-chrome-776165961bbf)
* 掘金链接：[Preload, Prefetch And Priorities in Chrome]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/preload-prefetch-and-priorities-in-chrome.md)
* PR 地址：#1485
* 文章分类：**前端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gy134340** [comment]
@sqrthree 认领翻译。     老哥，原文链接放错了吧

**Comment by sqrthree** [comment]
已修正啦~
