### ISSUE TITLE
使用开发者工具在浏览器中调整设计

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1471]
* 原文链接：[Using DevTools to Tweak Designs in the Browser](https://css-tricks.com/using-devtools-tweak-designs-browser/)
* 掘金链接：[Using DevTools to Tweak Designs in the Browser]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/using-devtools-tweak-designs-browser.md)
* PR 地址：#1488
* 文章分类：**前端**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
里面有些图片挂掉了0.0

**Comment by sqrthree** [comment]
应该是你网络的问题吧，我这边一切正常。 : )

**Comment by bambooom** [comment]
想认领这个，但是想问里面有几个是视频，视频内容需要翻译？ @sqrthree

**Comment by sqrthree** [comment]
视频不需要翻译啦。

**Comment by sqrthree** [comment]
@bambooom 确认下是否要认领翻译任务哈~ 然后我改下 label

**Comment by bambooom** [comment]
@sqrthree 好的~确认认领啦~

**Comment by sqrthree** [comment]
OK
