### ISSUE TITLE
真正行动之前 你将一无所成

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1472]
* 原文链接：[Nothing will change until you start building.](https://medium.freecodecamp.com/nothing-will-change-until-you-start-building-2681e85e7bdc)
* 掘金链接：[Nothing will change until you start building.]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/nothing-will-change-until-you-start-building.md)
* PR 地址：#1519
* 文章分类：**不分类**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by owenlyn** [comment]
认领翻译

**Comment by sqrthree** [comment]
好哒

**Comment by owenlyn** [comment]
@sqrthree 好啦。[校对地址](https://github.com/owenlyn/gold-miner/commit/f4857dd5c82e2387af2c9ffbd88d767f974a0866#diff-f844f2b71cb35e7e1ac448cb471a954b)

**Comment by sqrthree** [comment]
@owenlyn 小哥你发错 PR 了吧。

**Comment by sqrthree** [comment]
PR 应该发到掘金的仓库上
