### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by GitFuture** [xitu/gold-miner#1474]
学校：武汉大学
专业：微电子
常浏览的国外网站：stackoverflow  twitter
英语水平： CET6 
翻译经验：参与过 LCTT 翻译项目（[已翻译 10 篇](https://linux.cn/lctt/GitFuture)），翻译过[《文明 5 模组制作手册》](https://github.com/GitFuture/MyTranslation/blob/master/translated/civ5_Modders_Guide_index.md)
个人博客：http://www.cnblogs.com/brifuture/
个人介绍：热爱计算机技术，擅长Java，C++，乐于分享

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
