### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by luoqiuyu** [xitu/gold-miner#1475]
- 公司/学校：华中科技大学
- 工作内容/专业 Android开发
- 常浏览的国外网站：http://androidweekly.net/
- 英语水平：CET6
- 有无翻译经验：无
- 个人博客：http://www.cnblogs.com/luoqiuyu/
- 个人介绍：从事Android开发将近1年，对英语和技术有极大的兴趣

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
