### ISSUE TITLE
CSS 很棒，只是真的太难了

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1476]
* 原文链接：[CSS is Fine, It’s Just Really Hard](https://medium.com/@jdan/css-is-fine-its-just-really-hard-638da7a3dce0)
* 掘金链接：[CSS is Fine, It’s Just Really Hard]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/css-is-fine-its-just-really-hard.md)
* PR 地址：#1493
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZhangFe** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@ZhangFe 好哒
