### ISSUE TITLE
从形式到功能，设计思维的改变

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1477]
* 原文链接：[From Form to Function, Our Thoughts On Design Are Changing](https://medium.com/thinking-design/from-form-to-function-our-thoughts-on-design-are-changing-ed556d8f2b58)
* 掘金链接：[From Form to Function, Our Thoughts On Design Are Changing]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/from-form-to-function-our-thoughts-on-design-are-changing.md)
* PR 地址：#1525
* 文章分类：**设计**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ruixi** [comment]
认领～

**Comment by sqrthree** [comment]
好哒

**Comment by Ruixi** [comment]
@sqrthree 翻译完成
https://github.com/xitu/gold-miner/pull/1525
