### ISSUE TITLE
设计准则：用户死活不使用新功能怎么办

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1478]
* 原文链接：[Design principles: what to do when nobody is using your feature](https://blog.intercom.com/design-principles-what-to-do-when-nobody-is-using-your-feature/)
* 掘金链接：[Design principles: what to do when nobody is using your feature]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/design-principles-what-to-do-when-nobody-is-using-your-feature.md)
* PR 地址：#1615
* 文章分类：**设计**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iloveivyxuan** [comment]
认领

**Comment by sqrthree** [comment]
好哒

**Comment by sqrthree** [comment]
Hello，这篇文章的进度如何了呀？

**Comment by iloveivyxuan** [comment]
抱歉抱歉，还有一部分，今天晚上就能翻译好了
