### ISSUE TITLE
MVVM-C 竟然和 Swift 发生了这种事情！

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1479]
* 原文链接：[MVVM-C with Swift](https://marcosantadev.com/mvvmc-with-swift/)
* 掘金链接：[MVVM-C with Swift]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/mvvmc-with-swift.md)
* PR 地址：#1509
* 文章分类：**iOS**
----
* 翻译时间：`6` 天
* 校对时间：`2` 天
* 翻译积分：`6` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeepMissea** [comment]
收

**Comment by sqrthree** [comment]
好哒
