### ISSUE TITLE
Composing Software

### ISSUE THREAD

**Issue by yoyoyohamapi** [xitu/gold-miner#1486]
-\ 原文链接：https://medium.com/javascript-scene/the-rise-and-fall-and-rise-of-functional-programming-composable-software-c2d91b424c8c
-\ 简要介绍：Eric Elliott大神的函数式编程系列文章，从函数式的发展到应用，讲的非常通俗又不失仔细，ES6语法哦

**Comment by sqrthree** [comment]
感谢推荐 : )
