### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by yoyoyohamapi** [xitu/gold-miner#1487]
- 公司/学校：腾讯/电子科技大学
- 工作内容/专业：前端开发/机器学习
- 常浏览的国外网站：medium.com,stackoverflow,gitbook.io,youtube（大部分技术教程可以无字幕观看）
- 英语水平：CET6 513
- 有无翻译经验：有
- 个人博客：http://yoyoyohamapi.me
- 个人介绍：热爱coding，持续学习

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
