### ISSUE TITLE
利用 input-placeholder 属性来实现 input label 特殊效果

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#149]
文章链接：[Revisiting the Float Label pattern with CSS](http://thatemil.com/blog/2016/01/23/floating-label-no-js-pure-css/)
掘金链接：[利用 input-placeholder 属性来实现 input label 特殊效果](http://gold.xitu.io/entry/56a6ddfda633bd02578f90f3)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/floating-label-no-js-pure-css.md)

[PR地址](https://github.com/xitu/gold-miner/pull/169/files?diff=split)

翻译积分：5
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zhangjd** [comment]
认领

**Comment by antonia0912** [comment]
@Zhangjd 好的  按照之前方法翻译就好了  等你pr哈

**Comment by jingkecn** [comment]
達仔 @Zhangjd 這個有人在校對嗎？沒有的話我來校對試試看？

**Comment by Zhangjd** [comment]
Welcome to comment on #169 @jingkecn

**Comment by antonia0912** [comment]
辛苦三位啦 @Zhangjd @jingkecn @shenxn
