### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Aladdin-ADD** [xitu/gold-miner#1497]
- 公司：美团网
- 工作内容/专业：FE
- 常浏览的国外网站：github
- 英语水平：CET6
- 有无翻译经验：一点
- 个人介绍：对JS有比较深入的理解，开源文化爱好者。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
