### ISSUE TITLE
使用速率限制扩展你的 API 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1498]
* 原文链接：[Scaling your API with rate limiters](https://stripe.com/blog/rate-limiters)
* 掘金链接：[Scaling your API with rate limiters]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/rate-limiters.md)
* PR 地址：#1553
* 文章分类：**后端**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by 1992chenlu** [comment]
认领 @sqrthree

**Comment by sqrthree** [comment]
@1992chenlu 好哒~ 棒棒哒
