### ISSUE TITLE
一个专业的 Web 开发者却无法在 10 天内开发出一个简单的产品

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#150]
文章链接：[I’m a web developer and I’ve been stuck with the simplest app for the last 10 days](https://medium.com/@pistacchio/i-m-a-web-developer-and-i-ve-been-stuck-with-the-simplest-app-for-the-last-10-days-fb5c50917df#.re46lmozh)
掘金链接：[一个专业的 Web 开发者却无法在 10 天内开发出一个简单的产品](http://gold.xitu.io/entry/56c0b014128fe1005badad10)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/i-m-a-web-developer-and-i-ve-been-stuck-with-the-simplest-app-for-the-last-10-days.md)

**Comment by chemzqm** [comment]
全是 fuck，你确定这文章翻了能发表吗 :smiley:

**Comment by shenxn** [comment]
@chemzqm 然而所有的 fuck 都出现在 fuck with it 里面，可以试着翻译地优雅一点

**Comment by chemzqm** [comment]
@shenxn 优雅就没有原来气势了

**Comment by chemzqm** [comment]
就应该翻译成 草他妈的

**Comment by woota** [comment]
看完文章，个人觉得标题转译为“JavaScript生态之乱象”比较合适，如果照字面直译过来则略显生硬。有人认领么？没人认领，我先收了。

**Comment by antonia0912** [comment]
@chemzqm @shenxn @woota 请问哪一位认领了这篇文章？

**Comment by woota** [comment]
@antonia0912 好像是我

**Comment by antonia0912** [comment]
@woota 没有在掘金译者群的要先发issue译者申请喔  issue里边有相关标签  可以看一下别人怎么发的  要先进译者群才能认领文章哈

**Comment by woota** [comment]
@antonia0912 已经在群里，微信群里的id和github一样。

**Comment by antonia0912** [comment]
@woota 那这篇文章就由你认领啦  等你pr 哈  P.S  我也觉得题目应该改改~~

**Comment by antonia0912** [comment]
@woota honey这篇文章翻译的怎么样啦  在等给你发二月份的礼品喔

**Comment by woota** [comment]
@antonia0912 翻了一半，这几天被事情缠住了。周末收收尾，润色一下，就给你pr。

**Comment by antonia0912** [comment]
好哒  等你 PR @woota

**Comment by woota** [comment]
@antonia0912 耽误了两天，翻译完了。
