### ISSUE TITLE
跌宕起伏的函数式编程（组成化软件）（第一部分）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1500]
* 原文链接：[The Rise and Fall and Rise of Functional Programming (Composing Software)(part 1)](https://medium.com/javascript-scene/the-rise-and-fall-and-rise-of-functional-programming-composable-software-c2d91b424c8c)
* 掘金链接：[The Rise and Fall and Rise of Functional Programming (Composing Software)(part 1)]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-rise-and-fall-and-rise-of-functional-programming-composable-software.md)
* PR 地址：#1520
* 文章分类：**前端**
----
相关任务：

- part 2：[#1502](https://github.com/xitu/gold-miner/issues/1502)
- part 3：[#1503](https://github.com/xitu/gold-miner/issues/1503)
- part 4：[#1504](https://github.com/xitu/gold-miner/issues/1504)
- part 5：[#1505](https://github.com/xitu/gold-miner/issues/1505)
- part 6：[#1510](https://github.com/xitu/gold-miner/issues/1510)

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gy134340** [comment]
@sqrthree 认领翻译

**Comment by sqrthree** [comment]
@gy134340 好哒
