### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by huanshen** [xitu/gold-miner#1501]
- 公司/学校：华中科技大学
- 工作内容/专业：前端
- 常浏览的国外网站：stackoverflow.com
- 英语水平：cet6
- 有无翻译经验：无
- 个人博客：http://www.cnblogs.com/huansky/
- 个人介绍：本人目前是华中科技大学研三学生，方向是前端，愿意在空闲时候参与翻译或校队，顺便提升自己的英语能力

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
