### ISSUE TITLE
为什么用 JavaScript 学习函数式编程？（组成化软件）（第二部分）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1502]
* 原文链接：[Why Learn Functional Programming in JavaScript? (Composing Software)(part 2)](https://medium.com/javascript-scene/why-learn-functional-programming-in-javascript-composing-software-ea13afc7a257)
* 掘金链接：[Why Learn Functional Programming in JavaScript? (Composing Software)(part 2)]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-learn-functional-programming-in-javascript-composing-software.md)
* PR 地址：#1523
* 文章分类：**前端**
----
相关任务：

- part 1：[#1500](https://github.com/xitu/gold-miner/issues/1500)
- part 3：[#1503](https://github.com/xitu/gold-miner/issues/1503)
- part 4：[#1504](https://github.com/xitu/gold-miner/issues/1504)
- part 5：[#1505](https://github.com/xitu/gold-miner/issues/1505)
- part 6：[#1510](https://github.com/xitu/gold-miner/issues/1510)

----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gy134340** [comment]
@sqrthree 认领翻译

**Comment by sqrthree** [comment]
@gy134340 好哒
