### ISSUE TITLE
函数式程序员的 JavaScript 简介（软件编写）（第三部分）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1503]
* 原文链接：[A Functional Programmer’s Introduction to JavaScript (Composing Software)(part 3)](https://medium.com/javascript-scene/a-functional-programmers-introduction-to-javascript-composing-software-d670d14ede30)
* 掘金链接：[A Functional Programmer’s Introduction to JavaScript (Composing Software)(part 3)]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-functional-programmers-introduction-to-javascript-composing-software.md)
* PR 地址：#1552
* 文章分类：**前端**
----
相关任务：

- part 1：[#1500](https://github.com/xitu/gold-miner/issues/1500)
- part 2：[#1502](https://github.com/xitu/gold-miner/issues/1502)
- part 4：[#1504](https://github.com/xitu/gold-miner/issues/1504)
- part 5：[#1505](https://github.com/xitu/gold-miner/issues/1505)
- part 6：[#1510](https://github.com/xitu/gold-miner/issues/1510)

----
* 翻译时间：`8` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
@sqrthree  认领翻译

**Comment by sqrthree** [comment]
@sunui 好哒
