### ISSUE TITLE
高阶函数（软件编写）（第四部分）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1504]
* 原文链接：[Higher Order Functions (Composing Software)(part 4)](https://medium.com/javascript-scene/higher-order-functions-composing-software-5365cf2cbe99)
* 掘金链接：[Higher Order Functions (Composing Software)(part 4)]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/higher-order-functions-composing-software.md)
* PR 地址：#1531
* 文章分类：**前端**
----
相关任务：

- part 1：[#1500](https://github.com/xitu/gold-miner/issues/1500)
- part 2：[#1502](https://github.com/xitu/gold-miner/issues/1502)
- part 3：[#1503](https://github.com/xitu/gold-miner/issues/1503)
- part 5：[#1505](https://github.com/xitu/gold-miner/issues/1505)
- part 6：[#1510](https://github.com/xitu/gold-miner/issues/1510)

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by reid3290** [comment]
认领翻译

**Comment by sqrthree** [comment]
@reid3290 好哒
