### ISSUE TITLE
Reduce (软件编写) (第五部分)

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1505]
* 原文链接：[Reduce (Composing Software)(part 5)](https://medium.com/javascript-scene/reduce-composing-software-fe22f0c39a1d)
* 掘金链接：[Reduce (Composing Software)(part 5)]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/reduce-composing-software.md)
* PR 地址： #1546
* 文章分类：**前端**
----
相关任务：

- part 1：[#1500](https://github.com/xitu/gold-miner/issues/1500)
- part 2：[#1502](https://github.com/xitu/gold-miner/issues/1502)
- part 3：[#1503](https://github.com/xitu/gold-miner/issues/1503)
- part 4：[#1504](https://github.com/xitu/gold-miner/issues/1504)
- part 6：[#1510](https://github.com/xitu/gold-miner/issues/1510)

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yoyoyohamapi** [comment]
认领翻译

**Comment by sqrthree** [comment]
@yoyoyohamapi 好哒

**Comment by yoyoyohamapi** [comment]
@sqrthree 麻烦改下标题，这个应该是第五部分，之前弄乱了，么么哒
