### ISSUE TITLE
「保存」图标用哪个好？

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#151]
文章链接：[Is this the perfect save icon?](https://medium.com/@etchuk/is-this-the-perfect-save-icon-9651129bda85#.g4tnzvngm)
掘金链接：[「保存」图标用哪个好？](http://gold.xitu.io/entry/56b1a69b71cfe4005442204d)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/is-this-the-perfect-save-icon.md)

[PR地址](https://github.com/xitu/gold-miner/pull/166/files?diff=split)

翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by circlelove** [comment]
研一，物理化学，做过一段时间设计网站编辑，想认领它～！

**Comment by iThreeKing** [comment]
举手

**Comment by antonia0912** [comment]
@circlelove 不是我们掘金翻译计划的译者要先发issue申请喔~~等你的申请

**Comment by antonia0912** [comment]
@iThreeKing 说！手头现在有几篇文章啦！给新人一个机会嘛！先把产品那篇给你  这个留给别人好不啦么么哒

**Comment by vlux** [comment]
认领认领！

**Comment by antonia0912** [comment]
@vlux 新人要先来发issue译者申请喔~

**Comment by vlux** [comment]
@antonia0912 
#70 这里就来过了T T 早早就混迹在译者群里了>。< 
@江江大大认得~

**Comment by antonia0912** [comment]
@vlux soga  原来是我们掘金翻译计划的元老~ sorry~  麻烦你在译者群里单独at我一下  然后就可以认领这篇文章啦

**Comment by antonia0912** [comment]
期待你的pr~~ @vlux

**Comment by mdluo** [comment]
已认领校对

**Comment by antonia0912** [comment]
@mdluo 好的
