### ISSUE TITLE
Functor 与 Category （软件编写）（第六部分）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1510]
* 原文链接：[Functors & Categories](https://medium.com/javascript-scene/functors-categories-61e031bac53f)
* 掘金链接：[Functors & Categories]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/functors-categories.md)
* PR 地址：#1543
* 文章分类：**前端**
----
相关任务：

- part 1：[#1500](https://github.com/xitu/gold-miner/issues/1500)
- part 2：[#1502](https://github.com/xitu/gold-miner/issues/1502)
- part 3：[#1503](https://github.com/xitu/gold-miner/issues/1503)
- part 4：[#1504](https://github.com/xitu/gold-miner/issues/1504)
- part 5：[#1505](https://github.com/xitu/gold-miner/issues/1505)

----

* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yoyoyohamapi** [comment]
认领翻译

**Comment by sqrthree** [comment]
@yoyoyohamapi 好哒

**Comment by sqrthree** [comment]
注意两篇文章分别在两个分支上翻译哈。
