### ISSUE TITLE
如何使用 HTTP Headers 来保护你的 Web 应用

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1511]
* 原文链接：[How To Secure Your Web App With HTTP Headers](https://www.smashingmagazine.com/2017/04/secure-web-app-http-headers/)
* 掘金链接：[How To Secure Your Web App With HTTP Headers]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/secure-web-app-http-headers.md)
* PR 地址：#1549
* 文章分类：**后端**
----
* 翻译时间：`9` 天
* 校对时间：`2` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by bambooom** [comment]
好像很有用~
认领翻译~ @sqrthree

**Comment by sqrthree** [comment]
@bambooom 好哒
