### ISSUE TITLE
同中有异的 Webpack 与 Rollup

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1512]
* 原文链接：[Webpack and Rollup: the same but different](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c)
* 掘金链接：[Webpack and Rollup: the same but different]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/webpack-and-rollup-the-same-but-different.md)
* PR 地址：#1522
* 文章分类：**前端**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
认领翻译 @sqrthree

**Comment by sqrthree** [comment]
@lsvih 好哒
