### ISSUE TITLE
我是如何找回 Reddit 密码的

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1514]
* 原文链接：[That time I had to crack my own Reddit password](https://medium.freecodecamp.com/the-time-i-had-to-crack-my-own-reddit-password-a6077c0a13b4)
* 掘金链接：[That time I had to crack my own Reddit password]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-time-i-had-to-crack-my-own-reddit-password.md)
* PR 地址：#1567
* 文章分类：**不分类**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cdpath** [comment]
🙋‍♂️

**Comment by sqrthree** [comment]
You got it.
