### ISSUE TITLE
用动效创建的可用性：动效中的用户体验宣言

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1515]
* 原文链接：[Creating Usability with Motion: The UX in Motion Manifesto](https://medium.com/@ux_in_motion/creating-usability-with-motion-the-ux-in-motion-manifesto-a87a4584ddc)
* 掘金链接：[Creating Usability with Motion: The UX in Motion Manifesto]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/creating-usability-with-motion-the-ux-in-motion-manifesto.md)
* PR 地址：#1725
* 文章分类：**设计**
----
* 翻译时间：`12` 天
* 校对时间：`2` 天
* 翻译积分：`12` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ruixi** [comment]
我来吧……

**Comment by sqrthree** [comment]
好哒

**Comment by Ruixi** [comment]
这篇好长……
然后有点难……
我还没肝完……
大概还需要几天😭
sorry……

**Comment by sqrthree** [comment]
辛苦啦~

**Comment by Ruixi** [comment]
https://github.com/xitu/gold-miner/pull/1725/files

我再也不作死了☠️
