### ISSUE TITLE
在 Swift 中使用闭包实现懒加载

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1516]
* 原文链接：[Swift Lazy Initialization with Closures](https://blog.bobthedeveloper.io/swift-lazy-initialization-with-closures-a9ef6f6312c)
* 掘金链接：[Swift Lazy Initialization with Closures]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/swift-lazy-initialization-with-closures.md)
* PR 地址：#1541
* 文章分类：**iOS**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@lsvih 好哒
