### ISSUE TITLE
针对失败者的体验设计

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1517]
* 原文链接：[On Loser Experience Design](https://medium.com/on-human-centric-systems/on-loser-experience-design-1916629c36fc)
* 掘金链接：[On Loser Experience Design]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/on-loser-experience-design.md)
* PR 地址：#1564
* 文章分类：**产品**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ylq167** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
@ylq167 好哒
