### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by mnikn** [xitu/gold-miner#1518]
- 公司/学校：RIB Software
- 工作内容/专业：后端开发
- 常浏览的国外网站：edx、quora、udacity
- 英语水平：CET6
- 有无翻译经验：一篇
- 个人博客：https://mnikn.github.io/
- 个人介绍：刚工作的应届毕业生，熟悉Android开发和Java后端开发，对新技术有好奇心，希望能通过翻译计划了解更多的新技术和锻炼英语。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
