### ISSUE TITLE
产品文案要说人话

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#152]
文章链接：[The Secret To Writing Killer Product Copy](https://mng.lincolnwdaniel.com/the-secret-to-writing-killer-product-copy-4f23b7d0c842#.cdbnonpna)
掘金链接：[产品文案要说人话](http://gold.xitu.io/entry/56b6be6b816dfa005ae6c55b)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/the-secret-to-writing-killer-product-copy.md)
[PR地址](https://github.com/xitu/gold-miner/pull/203/files?diff=split)
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by iThreeKing** [comment]
🐑3⃣️我要认领！

**Comment by devSC** [comment]
愿意试试。

**Comment by antonia0912** [comment]
@iThreeKing 好的 你来翻译吧  等你的pr哈~~ @devSC 下手晚了你可以来校对呀嘿嘿

**Comment by antonia0912** [comment]
@iThreeKing 三金！！！！！！！11天啦都！！！你晓得我想说什么不！！！！！！！！
