### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by loveky** [xitu/gold-miner#1524]
- 公司/学校：京东
- 工作内容/专业：前端开发
- 常浏览的国外网站：github stackoverflow 各种前端框架的官方网站
- 英语水平：熟练，3年外企工作经验，英文工作环境
- 有无翻译经验：有 https://loveky.github.io/archive/ 博客里有几篇之前翻译的文章，众成翻译上翻译了20多篇文章，可以现在zcfy.cc这个域名暂时无法访问，所以没办法贴链接
- 个人博客：https://loveky.github.io
- 个人介绍：

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
