### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by midahai** [xitu/gold-miner#1526]
- 公司/学校：美洽网络科技有限公司
- 工作内容/专业：前端开发
- 常浏览的国外网站：stackoverflow, mdn, egghead, udacity
- 英语水平：六级526分
- 有无翻译经验：有
- 个人博客： http://mimimic.coding.me/blooog
- 个人介绍：
### 熟悉的框架：
- vue
- react
### 读过的原版：
- Professional Javascript for web developers
- css secrets
- you don't know JS serious (on going)

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
