### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by 0x4ec7** [xitu/gold-miner#1527]
- 公司/学校：BISTU(北京信息科技大学)
- 工作内容/专业：Python Engineer(Python工程师)
- 常浏览的国外网站：Github, Quora, Google, Youtube, Stackoverflow, ...
- 英语水平：CET6
- 有无翻译经验：No
- 个人博客：NA
- 个人介绍：能够快速处理英文文档, 熟悉各种标记语法, 理解各种计算机专业词汇. 希望利用空闲时间贡献翻译!

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
