### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by coderall** [xitu/gold-miner#1528]
学校：XJTU
学历：研究生
英语表达良好，希望帮助翻译文章，主要方向为后端偏底层操作系统，数据库，编译器方向

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
