### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by xunge0613** [xitu/gold-miner#1530]
- 公司/学校：爱回收 / 上海大学本科
- 工作内容/专业：前端开发 / 计算机科学与技术
- 常浏览的国外网站：medium.com, MDN
- 英语水平：CET-6
- 有无翻译经验：有，较少
- 个人博客：http://xuxun.me/blog/
- 个人介绍： 前端开发一枚，3年多经验，关注前端开发、UI交互设计，英文读写能力尚可，曾经在MDN上翻译过一些比较简单的英文文档，https://developer.mozilla.org/en-US/dashboards/revisions?user=xuxun

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
