### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by StonerZhu** [xitu/gold-miner#1533]
- 公司/学校：LOGO记
- 工作内容/专业：UI／UX／平面设计
- 常浏览的国外网站：behance / dribbble / pinterest / issuu
- 英语水平：优秀
- 有无翻译经验：有
- 个人博客：
- 个人介绍：全栈设计师

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
