### ISSUE TITLE
申请(是这个标题吗2333）

### ISSUE THREAD

**Issue by andrea2516** [xitu/gold-miner#1534]
University of Southampton
BSc ComputerScience

有Swift，javascript，java项目经验
其次dota2天梯500分选手？（这个可以算附加分吗）2333

此致

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
