### ISSUE TITLE
Function as Child Components

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1535]
* 原文链接：[Function as Child Components](http://merrickchristensen.com/articles/function-as-child-components.html)
* 掘金链接：[Function as Child Components]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/function-as-child-components.md)
* PR 地址：#1577
* 文章分类：**前端**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rottenpen** [comment]
认领

**Comment by sqrthree** [comment]
好的

**Comment by loveky** [comment]
@sqrthree  认领校对

**Comment by sqrthree** [comment]
@loveky 到 PR 下认领哈_(:з」∠)_
