### ISSUE TITLE
Node.js 之战: 如何在生产环境中调试错误

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1536]
* 原文链接：[Node.js War Stories: Debugging Issues in Production](https://blog.risingstack.com/node-js-war-stories-solving-issues-in-production-2/)
* 掘金链接：[Node.js War Stories: Debugging Issues in Production]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/node-js-war-stories-solving-issues-in-production.md)
* PR 地址：#1551
* 文章分类：**后端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mnikn** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@mnikn 好哒

**Comment by andrea2516** [comment]
@sqrthree 校对认领
