### ISSUE TITLE
设计师装逼指南

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1537]
* 原文链接：[How to pretend you’re a great designer](https://thedesignteam.io/how-to-pretend-youre-a-great-designer-3625de90d79f)
* 掘金链接：[How to pretend you’re a great designer](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-pretend-youre-a-great-designer.md)
* Markdown文件：[文件地址]()
* PR 地址：#1604
* 文章分类：**设计**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
@sqrthree 认领

**Comment by sqrthree** [comment]
好哒

**Comment by ylq167** [comment]
@sqrthree  [腼腆笑]现在推荐文章还有没有积分奖励呀？

**Comment by sqrthree** [comment]
@ylq167 嗯~ 已更新啦。
