### ISSUE TITLE
Typography can make your design… or it can break it

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1538]
* 原文链接：[Typography can make your design… or it can break it](https://medium.freecodecamp.com/typography-can-make-your-design-or-break-it-7be710aadcfe)
* 掘金链接：[Typography can make your design… or it can break it]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/typography-can-make-your-design-or-break-it.md)
* PR 地址：待添加
* 文章分类：**设计**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by AceLeeWinnie** [comment]
@sqrthree 我来吧

**Comment by sqrthree** [comment]
@AceLeeWinnie 好的。

**Comment by AceLeeWinnie** [comment]
@sqrthree  sorry! 一忙给忘了... 放给别人吧

**Comment by sqrthree** [comment]
=。= 25 天了，你这样很过粪了啦

**Comment by sqrthree** [comment]
[出现译文](http://www.woshipm.com/ucd/647543.html) =。=

**Comment by AceLeeWinnie** [comment]
我错了...
