### ISSUE TITLE
我经常听到的 GraphQL 到底是什么？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1539]
* 原文链接：[So what’s this GraphQL thing I keep hearing about?](https://medium.freecodecamp.com/so-whats-this-graphql-thing-i-keep-hearing-about-baf4d36c20cf)
* 掘金链接：[So what’s this GraphQL thing I keep hearing about?]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/so-whats-this-graphql-thing-i-keep-hearing-about.md)
* PR 地址：#1570
* 文章分类：**后端**
----
* 翻译时间：`8` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
好哒
