### ISSUE TITLE
Design principle: Consistency

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1540]
* 原文链接：[Design principle: Consistency](https://uxplanet.org/design-principle-consistency-6b0cf7e7339f)
* 掘金链接：[Design principle: Consistency]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/design-principle-consistency.md)
* PR 地址：待添加
* 文章分类：**设计**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xunge0613** [comment]
感觉这篇不错~ 萌新来申请翻译了~ @sqrthree

**Comment by sqrthree** [comment]
好哒

**Comment by xunge0613** [comment]
@sqrthree 囧了，我刚刚在查阅一致性相关的设计资料的时候…… 发现之前有其他小伙伴在简书上已经翻译过此文啦，而且感觉她翻译得很好哈~  http://www.jianshu.com/p/08faab98c79b

**Comment by sqrthree** [comment]
_(:з」∠)_ 好吧~ 那你换一篇吧，我把这个 close 掉。
