### ISSUE TITLE
前端 Debug 技巧与诀窍

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1547]
* 原文链接：[Debugging Tips and Tricks](https://css-tricks.com/debugging-tips-tricks/)
* 掘金链接：[Debugging Tips and Tricks]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/debugging-tips-tricks.md)
* PR 地址：#1582
* 文章分类：**前端**
----
* 翻译时间：`8` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
@lsvih 好哒

**Comment by ymz1124** [comment]
校对认领 @sqrthree

**Comment by sqrthree** [comment]
@ymz1124 以后直接在 PR 下回复一次就 OK 了哈~
