### ISSUE TITLE
我与被观察君的一段对话 [ Android RxJava2 ] ( 这是什么鬼？ ) Part5

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1554]
* 原文链接：[Dialogue between Rx Observable and a Developer (Me) [ Android RxJava2 ] ( What the hell is this ) Part5](http://www.uwanttolearn.com/android/dialogue-rx-observable-developer-android-rxjava2-hell-part5/)
* 掘金链接：[Dialogue between Rx Observable and a Developer (Me) [ Android RxJava2 ] ( What the hell is this ) Part5]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/dialogue-rx-observable-developer-android-rxjava2-hell-part5.md)
* PR 地址：#1574
* 文章分类：**Android**

----
相关文章：

- [Part 1](https://github.com/xitu/gold-miner/issues/1241)
- [part 2](https://github.com/xitu/gold-miner/issues/1242)
- [part 3](https://github.com/xitu/gold-miner/issues/1419)
- [part 4](https://github.com/xitu/gold-miner/issues/1423)

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by stormrabbit** [comment]
申请翻译@sqrthree

**Comment by sqrthree** [comment]
@stormrabbit 好的
