### ISSUE TITLE
Android O: Fonts – Part 1

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1555]
* 原文链接：[Android O: Fonts – Part 1](https://blog.stylingandroid.com/android-o-fonts/)
* 掘金链接：[Android O: Fonts – Part 1]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/android-o-fonts.md)
* PR 地址：待添加
* 文章分类：**Android**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by stormrabbit** [comment]
申请翻译@sqrthree

**Comment by sqrthree** [comment]
@stormrabbit Sorry, 发现 [译文](https://zhuanlan.zhihu.com/p/26437573) 了，要不你换篇其他的？
