### ISSUE TITLE
使用 Espresso 隔离测试视图

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1556]
* 原文链接：[Testing Views in Isolation with Espresso](https://www.novoda.com/blog/testing-views-in-isolation-with-espresso/)
* 掘金链接：[Testing Views in Isolation with Espresso]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/testing-views-in-isolation-with-espresso.md)
* PR 地址：#1575
* 文章分类：**Android**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yazhi1992** [comment]
领个翻译~

**Comment by sqrthree** [comment]
@yazhi1992 好哒

**Comment by yazhi1992** [comment]
@sqrthree 三哥我再拖两天 (´・ω・`)，最近公司项目进度有点赶。。。

**Comment by sqrthree** [comment]
OK

**Comment by yazhi1992** [comment]
@sqrthree 翻译好了，这篇文章读起来感觉有点怪怪的。。。如有翻译不好的地方，校对者们多指正，谢谢
