### ISSUE TITLE
ES6 模块原生支持在浏览器中落地，是时候该重新考虑打包了吗？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1557]
* 原文链接：[ES6 modules support lands in browsers: is it time to rethink bundling?](https://www.contentful.com/blog/2017/04/04/es6-modules-support-lands-in-browsers-is-it-time-to-rethink-bundling/)
* 掘金链接：[ES6 modules support lands in browsers: is it time to rethink bundling?]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/es6-modules-support-lands-in-browsers-is-it-time-to-rethink-bundling.md)
* PR 地址：#1589
* 文章分类：**前端**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@sqrthree apply for translation....I will finish the other two articles in this day.

**Comment by sqrthree** [comment]
@lsvih This's awesome.
