### ISSUE TITLE
人人都是设计师。我们可以的。

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1558]
* 原文链接：[Everyone is a designer. Get over it.](https://library.gv.com/everyone-is-a-designer-get-over-it-501cc9a2f434)
* 掘金链接：[Everyone is a designer. Get over it.]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/everyone-is-a-designer-get-over-it.md)
* PR 地址：#1603
* 文章分类：**设计**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ylq167** [comment]
翻译认领

**Comment by sqrthree** [comment]
@ylq167 好哒
