### ISSUE TITLE
通过测试来解耦Activity

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1560]
* 原文链接：[Test Driving away Coupling in Activities](https://www.philosophicalhacker.com/post/test-driving-away-coupling-in-activities/)
* 掘金链接：[Test Driving away Coupling in Activities]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/test-driving-away-coupling-in-activities.md)
* PR 地址：#1613
* 文章分类：**Android**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mnikn** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
好哒
