### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ilovejlj** [xitu/gold-miner#1561]
- 公司/学校：上海南花网络/上海交通大学
- 工作内容/专业：web前端/全栈开发
- 常浏览的国外网站：javascript weekly / node.js weekly / database weekly
- 英语水平：有国外全英语环境工作经历
- 有无翻译经验：无
- 个人博客：暂无
- 个人介绍：web前端开发，有7年互联网从业经验，精通js，了解node、php、python等，对函数式编程、数据库原理、编译原理等有初步的了解。对web开发相关的技术栈都感兴趣。也很希望能参与到分享知识的行列中。这是我尝试自己翻译的第一篇文章：https://github.com/ilovejlj/we-create/issues/12

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
