### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by michellemxm** [xitu/gold-miner#1565]
- 公司/学校：武汉初心科技有限公司（石墨文档）；
- 工作内容/专业：用户体验设计，交互设计，产品设计 / 香港理工大学交互设计硕士；
- 常浏览的国外网站：Behance/Dribbble/Pinterest/Google Scholar，专业相关以读原文为主；
- 英语水平：本硕英文教学，G330，T112；
- 有无翻译经验：目前只有中译英的经验，为网络工具 surge 英文版的译者；
- 个人博客：http://michellema.design/
- 个人介绍：http://michellema.design/about.html

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
