### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by stormrabbit** [xitu/gold-miner#1566]
- 公司/学校：北京欧德斯软件公司
- 工作内容/专业：移动开发/前端web开发
- 常浏览的国外网站：GitHub AngularNews YouTube
- 英语水平：CET-4 ,基本正常浏览国外技术文档
- 有无翻译经验：无
- 个人博客：http://blog.csdn.net/catwindboy
- 个人介绍：5年编程经验,技术涉猎广泛但不够专精.态度认真负责,工作踏实本分.已经觉醒了编程之魂,决定在技术上好好的磨砺自己.

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
