### ISSUE TITLE
PHP 7 Virtual Machine

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1568]
* 原文链接：[PHP 7 Virtual Machine](http://nikic.github.io/2017/04/14/PHP-7-Virtual-machine.html)
* 掘金链接：[PHP 7 Virtual Machine]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/PHP-7-Virtual-machine.md)
* PR 地址：待添加
* 文章分类：**后端**
----
* 翻译时间：`10` 天
* 校对时间：`4` 天
* 翻译积分：`10` 分
* 校对积分：`4` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

该篇文章过长，需要两位译者进行翻译，然后互相校对，再需要一位校对者校对全文。

**Comment by Romeo0906** [comment]
我……想试试 233 @sqrthree

**Comment by sqrthree** [comment]
哈哈哈哈~ 祝好。(◍•ᴗ•`◍)*＊

**Comment by leviding** [comment]
@Romeo0906 小哥哥，这篇文章怎么样了？ :joy:

**Comment by Romeo0906** [comment]
@leviding 我要说实话吗？233
