### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by dmodaii** [xitu/gold-miner#1571]
- 公司/学校：重庆邮电大学/网龙/理才网
- 工作内容/专业：web前端/PHP/信息管理
- 常浏览的国外网站：stackoverflow.com,  github.com
- 英语水平：6级
- 有无翻译经验：有一点， 但是只是翻译文章的某部分，不是全书
- 个人博客：https://dmodaii.github.io
- 个人介绍：保持好奇心，保持激情， 坚持学习

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
