### ISSUE TITLE
优质文章推荐

### ISSUE THREAD

**Issue by DreamYHD** [xitu/gold-miner#1572]
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0
帮助大家从RxJava1.0过渡到RxJava2.0

**Comment by sqrthree** [comment]
_(:з」∠)_ 已经有 [译文](http://www.jcodecraeer.com/a/anzhuokaifa/androidkaifa/2017/0420/7855.html) 了

**Comment by DreamYHD** [comment]
哇 感谢提醒
