### ISSUE TITLE
代码中添加注释之好坏丑

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1573]
* 原文链接：[Putting comments in code: the good, the bad, and the ugly. ](https://medium.freecodecamp.com/code-comments-the-good-the-bad-and-the-ugly-be9cc65fbf83)
* 掘金链接：[Putting comments in code: the good, the bad, and the ugly. ]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/code-comments-the-good-the-bad-and-the-ugly.md)
* PR 地址：#1576
* 文章分类：**不分类**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by bambooom** [comment]
认领翻译~ @sqrthree

**Comment by sqrthree** [comment]
@bambooom 好哒
