### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by changkun** [xitu/gold-miner#1579]
- 公司/学校：暂无 / 慕尼黑大学(硕士在读)
- 工作内容/专业：全端开发 / 人机交互 - 交互技术方向
- 常浏览的国外网站：`github` / `hacker news` / `raddit` / `medium`
- 英语水平：流利
- 有无翻译经验：有
  + 2016-08-24 [Leap Motion 开发文档](https://github.com/changkun/LeapDocCN) `全文翻译`
  + 2016-05-11  [Swift 3 API 设计指南](https://changkun.us/archives/2016/05/79/) `全文翻译`
  + 2016-05-09 [Swift 编程语言](https://github.com/numbbbbb/the-swift-programming-language-in-chinese/blob/gh-pages/source/chapter1/03_revision_history.md) `Release Changes - 章节翻译`
- 个人博客：https://changkun.us/
- 个人介绍：Think Difficulty.

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
