### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by leozhang2018** [xitu/gold-miner#158]
**前端开发人员，Google 爱好者，业余技术翻译**。[GDG 字幕组][1]成员，负责翻译和润稿 Google 技术视频，偶尔翻译技术文章。部分[成品][2]已经加入[谷歌开发者视频中文频道][3]午餐，或成为 U2B 官方中文候选字幕。欢迎前去观赏，提供建议，指出不足 ：）。
很有兴趣加入掘金的翻译计划哈，ID：leozhang2018 
Antonia 快来接客。

  [1]: http://www.gfansub.com/
  [2]: https://github.com/leozhang2018/GDGsrt
  [3]: https://www.youtube.com/channel/UCQqa5UIHtrnpiADC3eHFupw

**Comment by antonia0912** [comment]
@leozhang2018 客官我来啦~~~先来加我微信 antonia0912~~~

**Comment by Glowin** [comment]
欢迎我们GDG大家族的朋友加入掘金翻译计划，期待你的翻译哈。
