### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by L9m** [xitu/gold-miner#1580]
-\ 原文链接：https://www.smashingmagazine.com/2016/12/gpu-animation-doing-it-right/
-\ 简要介绍：大多数人都了解浏览器会用 GPU 渲染内容，特别是动画的部分。使用 `transform` 比使用类似 `left` 或 `top` 等属性的动画更加顺滑。大多数人会告诉你，如果你想使用 GPU 加速的动画，可以添加 `transform: translateZ(0)` 或 `will-change: transform` 等属性。但有时，在 demo 中运行流畅的动画，在真实的网站却是非常卡顿，能耗增加甚至会让浏览器直接崩溃。这一切背后的原因是什么？我们该怎样修复呢？

**ps:这种文章如果要翻译需要先向作者询问授权吗？**

**Comment by L9m** [comment]
ps：这种文章如果翻译需要先向作者询问授权吗？

**Comment by sqrthree** [comment]
发现译文啦：https://ruby-china.org/topics/32052
