### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by aresowj** [xitu/gold-miner#1583]
- 公司/学校：Chartboost, Inc.
- 工作内容/专业：Software Engineer
- 常浏览的国外网站：各类博客及Reddit
- 英语水平：六级560，八级56，在美国生活
- 有无翻译经验：有英语和日语翻译经验
- 个人博客：http://aresou.net
- 个人介绍：一年半经验的后端工程师。

**Comment by sqrthree** [comment]
Hi，欢迎大佬参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
