### ISSUE TITLE
是的，重新设计（第一部分）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1588]
* 原文链接：[Yeah, redesign(Part 1)](https://medium.muz.li/yeah-redesign-part-1-b61af07eb41a)
* 掘金链接：[Yeah, redesign(Part 1)]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/yeah-redesign-part-1.md)
* PR 地址：#1731
* 文章分类：**设计**
----
* 翻译时间：`8` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by dongpeiguo** [comment]
申请翻译

**Comment by sqrthree** [comment]
好的
