### ISSUE TITLE
别让你的偏爱拖了后腿：快拥抱箭头函数吧！

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1590]
* 原文链接：[Familiarity Bias is Holding You Back: It’s Time to Embrace Arrow Functions](https://medium.com/javascript-scene/familiarity-bias-is-holding-you-back-its-time-to-embrace-arrow-functions-3d37e1a9bb75)
* 掘金链接：[Familiarity Bias is Holding You Back: It’s Time to Embrace Arrow Functions]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/familiarity-bias-is-holding-you-back-its-time-to-embrace-arrow-functions.md)
* PR 地址：#1650
* 文章分类：**前端**
----
* 翻译时间：`8` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@lsvih 好哒

**Comment by lsvih** [comment]
@sqrthree 啊我忘记这个了！明天内一定弄完。。。

**Comment by GangsterHyj** [comment]
@sqrthree 校对认领

**Comment by sqrthree** [comment]
@GangsterHyj 好的，PR 地址在：https://github.com/xitu/gold-miner/pull/1650
