### ISSUE TITLE
使用 Espresso 和 Mockito 测试 MVP

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1591]
* 原文链接：[TESTING MVP USING ESPRESSO AND MOCKITO](https://josiassena.com/testing-mvp-using-espresso-and-mockito/)
* 掘金链接：[TESTING MVP USING ESPRESSO AND MOCKITO]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/testing-mvp-using-espresso-and-mockito.md)
* PR 地址：#1666
* 文章分类：**Android**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by skyar2009** [comment]
@sqrthree 来一发

**Comment by sqrthree** [comment]
好哒

**Comment by skyar2009** [comment]
--！忘个屁的了，这两天弄完提了

**Comment by sqrthree** [comment]
=。= 要抓紧呀

**Comment by skyar2009** [comment]
https://github.com/xitu/gold-miner/pull/1666
