### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by aresowj** [xitu/gold-miner#1592]
- 原文链接：https://engineering.instagram.com/dismissing-python-garbage-collection-at-instagram-4dca40b29172
- 简要介绍：介绍了Instagram如何通过关闭Python的GC来提升性能。

**Comment by sqrthree** [comment]
非常感谢你的推荐，已经有译文了，http://mt.sohu.com/it/d20170212/126039896_355140.shtml

**Comment by aresowj** [comment]
好的，谢谢
