### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by percyluan** [xitu/gold-miner#1593]
- 公司/学校：哈尔滨工业大学
- 工作内容/专业：前端/ios 开发  计算机专业
- 常浏览的国外网站：medium
- 英语水平：6级:585 GRE: 304/340
- 有无翻译经验：做过字幕组
- 个人博客：
- 个人介绍：热爱英语翻译，喜欢接触新技术，有责任心

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
