### ISSUE TITLE
真相在代码中

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1595]
* 原文链接：[The truth is in the code](https://medium.freecodecamp.com/the-truth-is-in-the-code-86a712362c99)
* 掘金链接：[The truth is in the code]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-truth-is-in-the-code.md)
* PR 地址：#1617
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by loveky** [comment]
@sqrthree  认领翻译

**Comment by sqrthree** [comment]
好的
