### ISSUE TITLE
A Case For Using Storyboards on iOS

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1596]
* 原文链接：[A Case For Using Storyboards on iOS](https://medium.cobeisfresh.com/a-case-for-using-storyboards-on-ios-3bbe69efbdf4)
* 掘金链接：[A Case For Using Storyboards on iOS]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-case-for-using-storyboards-on-ios.md)
* PR 地址：待添加
* 文章分类：**iOS**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Danny1451** [comment]
来来来 好久没翻了

**Comment by sqrthree** [comment]
哈哈哈好哒

**Comment by Danny1451** [comment]
把原文看了一下感觉内容好熟悉。。。
原来就是这篇文章的本体啊，下面这个文章好多开发者都看过了，还要把原文翻译么?
http://www.jianshu.com/p/478998f0a274

**Comment by sqrthree** [comment]
啊，那不翻译了，之前没收搜索到~ _(:з」∠)_ 失误
