### ISSUE TITLE
JavaScript 中的 CSS：基于组件的样式的未来

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1597]
* 原文链接：[CSS in JavaScript: The future of component-based styling](https://medium.freecodecamp.com/css-in-javascript-the-future-of-component-based-styling-70b161a79a32)
* 掘金链接：[CSS in JavaScript: The future of component-based styling]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/css-in-javascript-the-future-of-component-based-styling.md)
* PR 地址：#1606
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by bambooom** [comment]
@sqrthree 认领翻译~

**Comment by sqrthree** [comment]
好哒
