### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by SareaYu** [xitu/gold-miner#1598]
- 公司/学校：北京盈禾优仕科技有限责任公司/湖北第二师范学院
- 工作内容/专业：GRE/GMAT辅导老师/ 财务管理
- 常浏览的国外网站：Quora，
- 英语水平：GRE321分，托福89分
- 有无翻译经验：有。曾经在集智翻译群参与过几次协同翻译活动。
- 个人博客：
- 个人介绍：

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O

**Comment by Glowin** [comment]
@SareaYu 刚 Google 了一下集智俱乐部，发现贵组织很厉害，孵化了很多牛逼的项目。
掘金作为一个技术社区能不能一起来合作一下呢？
