### ISSUE TITLE
认领如何发布一个 React components

### ISSUE THREAD

**Issue by aleen42** [xitu/gold-miner#16]

**Comment by aleen42** [comment]
认领 React的 如何发布一个 React components

**Comment by xcatliu** [comment]
被认领了😂
@aleen42 如果没有时间，我也可以翻译~

**Comment by aleen42** [comment]
@xcatliu 你选择另一个吧

**Comment by Glowin** [comment]
@aleen42 我给你加到 README 里面了，欢迎做一下自我介绍。

@xcatliu 这篇文章已经被认领了，你可以再挑选其他的文章，欢迎加入我们。
