### ISSUE TITLE
项目什么时候需要 React 框架呢？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1601]
* 原文链接：[When Does a Project Need React?](https://css-tricks.com/project-need-react/)
* 掘金链接：[When Does a Project Need React?]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/project-need-react.md)
* PR 地址：#1608
* 文章分类：**前端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by stormrabbit** [comment]
翻译认领@sqrthree

**Comment by owenlyn** [comment]
@sqrthree 认领~

**Comment by sqrthree** [comment]
@stormrabbit 抱歉，刚看到这个消息~ 确认下你还要翻译这篇文章吗？

**Comment by stormrabbit** [comment]
嗯嗯，确认翻译哈。
@sqrthree

**Comment by sqrthree** [comment]
@stormrabbit 好哒~ 

@owenlyn 抱歉来晚咯，你可以看看有没有其他感兴趣的文章哈

**Comment by sqrthree** [comment]
二位有没有兴趣尝试一下这篇：#1618 一个大拿针对当前这一篇写的文章~
