### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by wbinarytree** [xitu/gold-miner#1602]
- 公司/学校：法国 INSA Toulouse
- 工作内容/专业：软件工程专业
- 常浏览的国外网站：Reddit/andoridev, Medium, StackOverFlow 
- 英语水平：大二时考取CET4 550+。 目前研究生快毕业。
- 有无翻译经验：没有专业翻译经验，但是对行业专业英语拿捏还算可以
- 个人博客：https://wbinarytree.github.io/ http://www.jianshu.com/u/a502db06530c
- 个人介绍：一个在法国的Android开发。 RxJava big fan

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O

**Comment by Glowin** [comment]
@wbinarytree 欢迎多推荐一些 RxJava 的好文章来翻译

**Comment by Glowin** [comment]
刚好看到一篇 RxJava 的文章正在校对 #1554
