### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#1605]
- 公司/学校：学生/中国地质大学（武汉）
- 工作内容/专业：Web开发/从自动化
- 常浏览的国外网站：Quora、CSS TRICKS、Sitepoint
- 英语水平：英语六级
- 有无翻译经验：有，在知乎等平台参与过翻译，在掘金也分享过我翻译的文章，反响还可以。
- 个人博客：http://www.dingxuewen.com
- 个人介绍：热爱技术，正在学习Web开发。希望能为社区贡献自己的一份力量

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
