### ISSUE TITLE
推荐优秀英文文章 How I wrote the world's fastest JavaScript memoization library

### ISSUE THREAD

**Issue by Aladdin-ADD** [xitu/gold-miner#1607]
- 原文链接：https://community.risingstack.com/the-worlds-fastest-javascript-memoization-library/
- 简要介绍：本文介绍了世界上最快的memoization库 fast-memoize.js 的实现--它能够进行500万次操作/每秒。

**Comment by Aladdin-ADD** [comment]
认领翻译。

**Comment by sqrthree** [comment]
@Aladdin-ADD You can get it at #1631.
