### ISSUE TITLE
 Android 开发中利用异步来优化运行速度和性能

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#161]
文章链接：[Using concurrency to improve speed and performance in Android](https://medium.com/@ali.muzaffar/using-concurrency-and-speed-and-performance-on-android-d00ab4c5c8e3#.rt9z1k25u)
掘金链接：[[英] Android 开发中利用异步来优化运行速度和性能](http://gold.xitu.io/entry/568aa66560b2c297ddf9e453/)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/using-concurrency-and-speed-and-performance-on-android.md)

PR地址：https://github.com/xitu/gold-miner/pull/183/files?diff=split

翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by edvardHua** [comment]
@antonia0912 认领!

**Comment by antonia0912** [comment]
收到！！等你pr @edvardHua

**Comment by Sausure** [comment]
翻译完记得 @ 我，我来校对哈
