### ISSUE TITLE
哪些项目需要 React？都需要！

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1618]
* 原文链接：[Which Projects Need React? All Of Them!](https://css-tricks.com/projects-need-react/)
* 掘金链接：[Which Projects Need React? All Of Them!]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/projects-need-react.md)
* PR 地址：#1634
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@sunui 好的
