### ISSUE TITLE
Leveling Up Your JavaScript

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#162]
文章链接：[Leveling Up Your JavaScript](http://developer.telerik.com/featured/leveling-up-your-javascript/)
掘金链接：[Leveling Up Your JavaScript](http://gold.xitu.io/entry/56c13e226be3ff005d76684d)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/leveling-up-your-javascript.md)

翻译积分：8
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by vlux** [comment]
是JS的就要冲到前面！
但是文章好长，怕坑一时半会填不完（趴
有没有小伙伴一起来翻译>。<
（一周以后没有人就自己来填坑23333）

**Comment by antonia0912** [comment]
@vlux 好的  先等等看看有没有人想跟你一起翻译  不过你可以开始翻译前边了

**Comment by CoderBOBO** [comment]
你要是翻不完我来，没多少，全是代码和图片

**Comment by vlux** [comment]
@CoderBOBO 
那你来吧，最近手头有工作要结，过了这两周我再来接班

**Comment by antonia0912** [comment]
好的 那这篇文章就交给波波了 @vlux @CoderBOBO

**Comment by CoderBOBO** [comment]
ok

**Comment by jingkecn** [comment]
如果。。。還需要人。。。幫忙的話。。。我也可以。。。幫忙翻譯一下的。。。

**Comment by Glowin** [comment]
@CoderBOBO 波波，翻译的怎么样啦？

**Comment by CoderBOBO** [comment]
@Glowin，还有一点点就OK了

**Comment by CoderBOBO** [comment]
@jingkecn 你也要翻译？

**Comment by jingkecn** [comment]
@CoderBOBO 之前看這文章這麼長所以想看看有沒什麼能幫上忙的，不過現在我手頭已有兩篇文章要翻譯啦，我還是等你們翻譯完來校對好了

**Comment by CoderBOBO** [comment]
@jingkecn 哦哦我还以为你没文章翻译

**Comment by jingkecn** [comment]
@CoderBOBO 一領就領到要連翻上下集的文章2333333⋯⋯

**Comment by antonia0912** [comment]
@CoderBOBO 波波 这都上个世纪的文章的你居然还没有提交 PR 我请了半个月的假又回来上班了你居然还没有提交！！！你想怎么着 横竖是一死 自个儿看着办

**Comment by vlux** [comment]
现在完不成的活儿都是之前立的flag。。

**Comment by CommanderXL** [comment]
我来校对啦~

**Comment by hikerpig** [comment]
这篇文章在认领和正在翻译之间来来回回是怎么回事...

**Comment by antonia0912** [comment]
@hikerpig 这篇文章之前的译者临时有事翻译不了了  要不你来翻译 可以吗

**Comment by hikerpig** [comment]
接下翻译 o(￣▽￣)d @antonia0912

**Comment by antonia0912** [comment]
@hikerpig 么么哒~~~

**Comment by narcotics726** [comment]
这篇还有信儿没？手痒啊，还有之前的 Functional JavaScript 那一系列的还有好几篇没翻呢

**Comment by hikerpig** [comment]
@narcotics726  我已经在翻了哟

**Comment by antonia0912** [comment]
这篇已经被 @hikerpig 拿去翻译啦，@narcotics726 可以来校对

**Comment by narcotics726** [comment]
既然译者已经完成 #277 ，认领校对！

**Comment by hikerpig** [comment]
@narcotics726 申请校对去PR 里说声嘛

**Comment by antonia0912** [comment]
@narcotics726 好的  请仔细校对喔~
