### ISSUE TITLE
Workcation App – 第一部分 . 自定义 Fragment 转场动画

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1620]
* 原文链接：[Workcation App – Part 1. Fragment custom transition](https://www.thedroidsonroids.com/blog/android/workcation-app-part-1-fragments-custom-transition/)
* 掘金链接：[Workcation App – Part 1. Fragment custom transition]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/workcation-app-part-1-fragments-custom-transition.md)
* PR 地址：#1635
* 文章分类：**Android**
----
相关任务：

- part2: #1621
- part3: #1624 
- part4: #1625
----
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by stormrabbit** [comment]
翻译认领
@sqrthree

**Comment by sqrthree** [comment]
好哒

**Comment by Vivienmm** [comment]
校对完成。@sqrthree
