### ISSUE TITLE
Workcation App – 第二部分. 有动画的标记和 MapOverlayLayout

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1621]
* 原文链接：[Workcation App – Part 2. Animating Markers with MapOverlayLayout](https://www.thedroidsonroids.com/blog/workcation-app-part-2-animating-markers-with-mapoverlaylayout/)
* 掘金链接：[Workcation App – Part 2. Animating Markers with MapOverlayLayout]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/workcation-app-part-2-animating-markers-with-mapoverlaylayout.md)
* PR 地址：#1640
* 文章分类：**Android**
----
相关任务：

- part1: #1620
- part3: #1624 
- part4: #1625
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by stormrabbit** [comment]
翻译认领 
@sqrthree

**Comment by sqrthree** [comment]
@stormrabbit 好哒

**Comment by Vivienmm** [comment]
校对认领。

**Comment by sqrthree** [comment]
好哒

**Comment by Vivienmm** [comment]
校对完成~
