### ISSUE TITLE
Workcation App – 第三部分.Animated Markers 与 RecyclerView 的互动

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1624]
* 原文链接：[Workcation App – Part 3. RecyclerView interaction with Animated Markers](https://www.thedroidsonroids.com/blog/workcation-app-part-3-recyclerview-interaction-with-animated-markers/)
* 掘金链接：[Workcation App – Part 3. RecyclerView interaction with Animated Markers]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/workcation-app-part-3-recyclerview-interaction-with-animated-markers.md)
* PR 地址：#1657
* 文章分类：**Android**
----
相关任务：

- part1: #1620
- part2: #1621
- part4: #1625
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by stormrabbit** [comment]
@sqrthree
翻译认领

**Comment by sqrthree** [comment]
好的

**Comment by Vivienmm** [comment]
校对认领。@sqrthree

**Comment by sqrthree** [comment]
棒棒哒

**Comment by Vivienmm** [comment]
校对完成~@sqrthree
