### ISSUE TITLE
Workcation App – 第四部分. 场景（Scenes）和 RecyclerView 的可共享的转场动画（Shared Element Transition）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1625]
* 原文链接：[Workcation App – Part 4. Shared Element Transition with RecyclerView and Scenes](https://www.thedroidsonroids.com/blog/workcation-app-part-4-shared-element-transition-recyclerview-scenes/)
* 掘金链接：[Workcation App – Part 4. Shared Element Transition with RecyclerView and Scenes]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/workcation-app-part-4-shared-element-transition-recyclerview-scenes.md)
* PR 地址：#1668
* 文章分类：**Android**
----
相关任务：

- part1: #1620
- part2: #1621
- part3: #1624 
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sqrthree** [comment]
@stormrabbit 要来第四部分吗？(◍•ᴗ•`◍)*＊

**Comment by stormrabbit** [comment]
翻译认领
@sqrthree

**Comment by sqrthree** [comment]
哈哈好哒~
