### ISSUE TITLE
最激动人心的视觉系统其实是最枯燥乏味的!

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1626]
* 原文链接：[The Most Exciting Design Systems Are Boring](https://bigmedium.com/ideas/boring-design-systems.html)
* 掘金链接：[The Most Exciting Design Systems Are Boring]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/boring-design-systems.md)
* PR 地址：#1662
* 文章分类：**不分类**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
@sqrthree 看上去很好玩的样子。 收一篇。

**Comment by sqrthree** [comment]
好的

**Comment by yifili09** [comment]
@sqrthree 

#1662  已经准备好。 ：）

**Comment by sqrthree** [comment]
Gook Job.
