### ISSUE TITLE
为何 TypeScript 愈发流行了？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1627]
* 原文链接：[Why TypeScript Is Growing More Popular](https://thenewstack.io/typescript-getting-popular/)
* 掘金链接：[Why TypeScript Is Growing More Popular]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/typescript-getting-popular.md)
* PR 地址：#1645
* 文章分类：**前端**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by loveky** [comment]
翻译认领

**Comment by sqrthree** [comment]
OK

**Comment by Aladdin-ADD** [comment]
校对认领。 ^-^
