### ISSUE TITLE
如何创建 BubblePicker – Android 多彩菜单动画

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1628]
* 原文链接：[How We Created BubblePicker – a Colorful Menu Animation for Android](https://yalantis.com/blog/how-we-created-bubblepicker-a-colourful-animation-for-android/)
* 掘金链接：[How We Created BubblePicker – a Colorful Menu Animation for Android]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-we-created-bubblepicker-a-colourful-animation-for-android.md)
* PR 地址：#1646
* 文章分类：**Android**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hackerkevin** [comment]
认领认领

**Comment by sqrthree** [comment]
好的

**Comment by phxnirvana** [comment]
卧槽没抢到。。
