### ISSUE TITLE
为复杂产品制定设计规范

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1629]
* 原文链接：[Designing Design System for Complex Products](https://uxdesign.cc/designing-design-system-for-complex-products-5ff2d3051fa1)
* 掘金链接：[Designing Design System for Complex Products]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/designing-design-system-for-complex-products.md)
* PR 地址：#1755
* 文章分类：**设计**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
@sqrthree 翻译认领~

**Comment by sqrthree** [comment]
好的
