### ISSUE TITLE
Introducing Swift 3.0

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#163]
文章链接：[Introducing Swift 3.0](http://dev.iachieved.it/iachievedit/)
掘金链接：[Introducing Swift 3.0](http://gold.xitu.io/entry/56c40788128fe10059519314)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/Introducing-Swift%203.0.md)

**Comment by iThreeKing** [comment]
虽然我还有个产品的文章，但是这个请务必给我，好久没有翻译iOS的文章了，明早就发这个pr，谢谢🐑3⃣️。

**Comment by iThreeKing** [comment]
已经翻译完了，但是发pr有点问题，起床咨询一下你们。

**Comment by antonia0912** [comment]
@iThreeKing ok

**Comment by CoderBOBO** [comment]
我来校对咯

**Comment by antonia0912** [comment]
@CoderBOBO ok

**Comment by antonia0912** [comment]
辛苦三位 @iThreeKing @CoderBOBO @shenxn
