### ISSUE TITLE
光速 React

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1630]
* 原文链接：[React at Light Speed](https://blog.vixlet.com/react-at-light-speed-78cd172a6411)
* 掘金链接：[React at Light Speed]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/react-at-light-speed.md)
* PR 地址：#1652
* 文章分类：**前端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZhangFe** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
好的
