### ISSUE TITLE
我是如何实现世界上最快的 JavaScript 记忆化（memoization）的

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1631]
* 原文链接：[How I wrote the world's fastest JavaScript memoization library](https://community.risingstack.com/the-worlds-fastest-javascript-memoization-library/)
* 掘金链接：[How I wrote the world's fastest JavaScript memoization library]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-worlds-fastest-javascript-memoization-library.md)
* PR 地址：#1638
* 文章分类：**前端**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Aladdin-ADD** [comment]
翻译认领。时间2017.05.05~2017.05.10

**Comment by sqrthree** [comment]
好哒

**Comment by Aladdin-ADD** [comment]
重新提了一个PR： #1638  @sqrthree

**Comment by sqrthree** [comment]
copythat

**Comment by GangsterHyj** [comment]
@sqrthree 申请校对

**Comment by sqrthree** [comment]
@GangsterHyj OK，PR 地址在 #1638

**Comment by Aladdin-ADD** [comment]
@sqrthree  linking:  https://juejin.im/post/5912b635a0bb9f0058b44c60
