### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by wangfeihang** [xitu/gold-miner#1633]
- 公司/学校：欢聚时代公司（YY）
- 工作内容/专业：Android开发
- 常浏览的国外网站：androidweekly.net, https://www.androiddevdigest.com/, https://medium.com/, github, stackoverflow 
- 英语水平：六级
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：热爱技术，热爱分享，希望能加入该团队，为大家知识的获取贡献一份力量！

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O

**Comment by wangfeihang** [comment]
已加O(∩_∩)O
