### ISSUE TITLE
在 Android 下进行实时模糊渲染

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#164]
文章链接：[A Blurring View for Android](http://developers.500px.com/2015/03/17/a-blurring-view-for-android.html)
掘金链接：[在 Android 下进行实时模糊渲染](http://gold.xitu.io/entry/56b8621271cfe4005488191d)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/a-blurring-view-for-android.md)

翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Sausure** [comment]
我认领哈

**Comment by antonia0912** [comment]
@Sausure 好哒

**Comment by Sausure** [comment]
翻译完成，求校对，PR地址：https://github.com/xitu/gold-miner/pull/176

**Comment by antonia0912** [comment]
好的  辛苦啦 @Sausure   PR地址 #176

**Comment by antonia0912** [comment]
辛苦译者 @Sausure 以及两位校对者
