### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by BoilerYao** [xitu/gold-miner#1642]
- 原文链接： https://labs.ribot.co.uk/approaching-android-with-mvvm-8ceec02d5442
- 简要介绍：现在 Android 开发的架构主要以 MVP 为主，MVVM 相对于 MVP 有很多优势，随着 Data Binding 的发展成熟，新兴的 MVVM 会成为一个很好的选择。

**Comment by sqrthree** [comment]
感谢推荐，不过我们已经翻译过了哈 https://github.com/xitu/gold-miner/blob/master/TODO/approaching-android-with-mvvm.md
