### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by windmxf** [xitu/gold-miner#1643]
- 公司/学校：工行软开/东华大学
- 工作内容/专业：安卓开发/架构师
- 常浏览的国外网站：facebook，youtube
- 英语水平：英语6级
- 有无翻译经验：大学期间曾通过中级口译，工作后无翻译实践
- 个人博客：无
- 个人介绍：8年工作经验，有一定英语基础，对移动端技术有一定经验，希望通过阅读和翻译原始英文技术资料提升自己，也为同仁提供更易学习的译文。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
