### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Liqihan** [xitu/gold-miner#1644]
- 公司/学校：杭州橙群网络科技有限公司/华中农业大学
- 工作内容/专业：前端开发,nodejs/信息与计算科学
- 常浏览的国外网站：github、google、facebook
- 英语水平：CET-6
- 有无翻译经验：无
- 个人博客：https://github.com/Liqihan
- 个人介绍：Problem Solver

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
