### ISSUE TITLE
走近 Quantum：浏览器引擎解密

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1651]
* 原文链接：[Quantum Up Close: What is a browser engine?](https://hacks.mozilla.org/2017/05/quantum-up-close-what-is-a-browser-engine/)
* 掘金链接：[Quantum Up Close: What is a browser engine?]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/quantum-up-close-what-is-a-browser-engine.md)
* PR 地址：#1660
* 文章分类：**前端**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xunge0613** [comment]
interesting~
@sqrthree  窝来认领翻译~ =w=

**Comment by sqrthree** [comment]
好的
