### ISSUE TITLE
理解NodeJS中基于事件驱动的架构

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1653]
* 原文链接：[Understanding Node.js Event-Driven Architecture](https://medium.freecodecamp.com/understanding-node-js-event-driven-architecture-223292fcbc2d)
* 掘金链接：[Understanding Node.js Event-Driven Architecture]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/understanding-node-js-event-driven-architecture.md)
* PR 地址：#1705
* 文章分类：**后端**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Aladdin-ADD** [comment]
翻译认领。

**Comment by sqrthree** [comment]
好哒

**Comment by Aladdin-ADD** [comment]
上周末有事情，这周末翻译，估计延期2天， so sorry~~ @sqrthree

**Comment by sqrthree** [comment]
好

**Comment by fghpdf** [comment]
还有校对的位置吗 @sqrthree

**Comment by sqrthree** [comment]
@fghpdf 2333 已经发车啦~ 下次赶早哟

**Comment by fghpdf** [comment]
@sqrthree 好的
