### ISSUE TITLE
Floating Action Button in UX Design

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1654]
* 原文链接：[Floating Action Button in UX Design](https://uxplanet.org/floating-action-button-in-ux-design-7dd06e49144e)
* 掘金链接：[Floating Action Button in UX Design]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/floating-action-button-in-ux-design.md)
* PR 地址：待添加
* 文章分类：**设计**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ylq167** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
好哒

**Comment by sqrthree** [comment]
[发现译文](https://media.weibo.cn/article?id=2309404106917143269162&jumpfrom=weibocom&retcode=6102) 已和译者沟通，取消任务 sad
