### ISSUE TITLE
再谈如何安全地在 Android 中存储令牌

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1655]
* 原文链接：[A follow-up on how to store tokens securely in Android](https://medium.com/@enriquelopezmanas/a-follow-up-on-how-to-store-tokens-securely-in-android-e84ac5f15f17)
* 掘金链接：[A follow-up on how to store tokens securely in Android]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-follow-up-on-how-to-store-tokens-securely-in-android.md)
* PR 地址：#1706
* 文章分类：**Android**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jacksonke** [comment]
没人领，加点分看看，实在没人领，可以给我。

**Comment by sqrthree** [comment]
加了~ 你要不要收了？

**Comment by jacksonke** [comment]
我领了一篇了，翻译完后，没人的话，我也收了。我算不算接盘侠？

**Comment by lovexiaov** [comment]
我来翻译吧~

**Comment by hackerkevin** [comment]
认领认领 @sqrthree

**Comment by sqrthree** [comment]
抱歉回复这么晚，@lovexiaov 先认领的，那就 @lovexiaov 来翻译吧~ @hackerkevin 抱歉了哈，你可以看看有没有其他感兴趣的啦。

**Comment by lovexiaov** [comment]
@sqrthree ok

**Comment by sqrthree** [comment]
@lovexiaov @hackerkevin 二位不知可否有兴趣参与校对呢？这篇已经翻译好了，PR 地址是 #1706。

**Comment by hackerkevin** [comment]
校对

**Comment by lovexiaov** [comment]
@sqrthree 我翻译的，自己校对不太好吧：）

**Comment by sqrthree** [comment]
噗，傻×了 _(:з」∠)_

@jacksonke 感兴趣的话可以参与校对哈

**Comment by jacksonke** [comment]
校对

**Comment by sqrthree** [comment]
@jacksonke 这篇文章已经有两个校对了哈~

**Comment by hackerkevin** [comment]
@sqrthree done
