### ISSUE TITLE
消息同步 —— 在 Airbnb 我们是怎样扩展移动消息的

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1656]
* 原文链接：[Messaging Sync — Scaling Mobile Messaging at Airbnb](https://medium.com/airbnb-engineering/messaging-sync-scaling-mobile-messaging-at-airbnb-659142036f06)
* 掘金链接：[Messaging Sync — Scaling Mobile Messaging at Airbnb]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/messaging-sync-scaling-mobile-messaging-at-airbnb.md)
* PR 地址：#1723
* 文章分类：**iOS**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tuccuay** [comment]
收（

**Comment by sqrthree** [comment]
好的
