### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by horizon13th** [xitu/gold-miner#1658]
- 公司/学校：US-Penn State University 美国宾州州立大学
- 工作内容/专业：Information Sciences and Technology 信息科学技术
- 常浏览的国外网站：medium.com, d3js.org, 技术博客
- 英语水平：六级，托福
- 有无翻译经验：有 
- 个人博客：无
- 个人介绍：擅长英文论文写作，撰写英文技术报告，研究方向为 信息可视化 数据可视化 人机交互 等

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
