### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by yingjie0904** [xitu/gold-miner#1663]
- 公司/学校：北京你我他互学数据科技股份有限公司 / 燕京理工学院
- 工作内容/专业：前端开发 / 英语
- 常浏览的国外网站：stackoverflow.com，ycombinator.com
- 英语水平：8级
- 有无翻译经验：1年半
- 个人博客：没有
- 个人介绍：英语专业毕业的小前端

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
