### ISSUE TITLE
Airbnb 的前端重构

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1664]
* 原文链接：[Rearchitecting Airbnb’s Frontend](https://medium.com/airbnb-engineering/rearchitecting-airbnbs-frontend-5e213efc24d2)
* 掘金链接：[Rearchitecting Airbnb’s Frontend]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/rearchitecting-airbnbs-frontend.md)
* PR 地址： #1690
* 文章分类：**前端**
----
* 翻译时间：`9` 天
* 校对时间：`2` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
@sqrthree  认领翻译

**Comment by sqrthree** [comment]
@sunui 好哒
