### ISSUE TITLE
Make or break… with Gradle

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1665]
* 原文链接：[Make or break… with Gradle](https://medium.com/contentsquare-engineering-blog/make-or-break-with-gradle-dac2e858868d)
* 掘金链接：[Make or break… with Gradle]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/make-or-break-with-gradle.md)
* PR 地址：#1691
* 文章分类：**Android**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jacksonke** [comment]
Get it.

**Comment by sqrthree** [comment]
好的

**Comment by jacksonke** [comment]
昨晚提交了，这里咋看不到。。。
回去检查下。。。
