### ISSUE TITLE
建立更好的代码审查制度

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1667]
* 原文链接：[Crafting Better Code Reviews](https://medium.com/@vaidehijoshi/crafting-better-code-reviews-1a5fc00a9312)
* 掘金链接：[Crafting Better Code Reviews]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/crafting-better-code-reviews.md)
* PR 地址：#1673
* 文章分类：**不分类**
----
* 翻译时间：`10` 天
* 校对时间：`2` 天
* 翻译积分：`10` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by bobmayuze** [comment]
请求翻译

**Comment by sqrthree** [comment]
好的

**Comment by bobmayuze** [comment]
翻译完成
