### ISSUE TITLE
推荐优秀英文文章：给 Web 开发者的安全检查列表

### ISSUE THREAD

**Issue by Glowin** [xitu/gold-miner#1669]
- 原文链接：https://juejin.im/entry/591b71b72f301e006bc9d93b/detail
- 简要介绍：前几天的比特币勒索事件造成全球恐慌，作为一个 Web 开发者，如何在日常开发中避免安全隐患呢，这篇文章记录了 Web 开发者可能犯的错误，快来检查一下吧。

**Comment by sqrthree** [comment]
b(￣▽￣)d 棒
