### ISSUE TITLE
Web 开发者安全清单

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1672]
* 原文链接：[Web Developer Security Checklist](https://simplesecurity.sensedeep.com/web-developer-security-checklist-f2e4f43c9c56)
* 掘金链接：[Web Developer Security Checklist]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/web-developer-security-checklist.md)
* PR 地址：#1686
* 文章分类：**不分类**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by GangsterHyj** [comment]
@sqrthree 申领翻译~

**Comment by sqrthree** [comment]
@GangsterHyj 好哒
