### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ZhangRuixiang** [xitu/gold-miner#1674]
- 公司/学校：掌合天下（北京）信息技术有限公司
- 工作内容/专业：iOS开发
- 常浏览的国外网站：github，stackoverflow
- 英语水平：CET-6
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：热爱技术，热爱分享

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
