### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zaraguo** [xitu/gold-miner#1675]
- 公司/学校：杭州多杰网络科技有限公司/浙江工业大学
- 工作内容/专业：后端/计算机科学与技术
- 常浏览的国外网站：Medium/GitHub
- 英语水平：CET-6
- 有无翻译经验：较少
- 个人博客：http://zaraguo.me/
- 个人介绍：正经使用过 .NET，Node.js 进行后端开发，也杂食各种有趣技术

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
