### ISSUE TITLE
Django 基于 Postgres 的全文搜索

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1677]
* 原文链接：[Postgres Full-Text Search With Django](http://blog.lotech.org/postgres-full-text-search-with-django.html)
* 掘金链接：[Postgres Full-Text Search With Django]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/postgres-full-text-search-with-django.md)
* PR 地址：#1704
* 文章分类：**后端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by steinliber** [comment]
认领了

**Comment by sqrthree** [comment]
好的
