### ISSUE TITLE
Swift 中关于并发的一切：第一部分 — 当前

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1678]
* 原文链接：[All about Concurrency in Swift - Part 1: The Present](https://www.uraimo.com/2017/05/07/all-about-concurrency-in-swift-1-the-present/)
* 掘金链接：[All about Concurrency in Swift - Part 1: The Present]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/all-about-concurrency-in-swift-1-the-present.md)
* PR 地址：#1739
* 文章分类：**iOS**
----
* 翻译时间：`14` 天
* 校对时间：`3` 天
* 翻译积分：`14` 分
* 校对积分：`3` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeepMissea** [comment]
卧槽，iOS 开发没人要了？？三天都没人收
我收

**Comment by sqrthree** [comment]
好

**Comment by Danny1451** [comment]
吓尿 14 天 / 14 分 这么长的文章也是可以
