### ISSUE TITLE
对元素持有弱引用的Swift数组

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1679]
* 原文链接：[Swift Arrays Holding Elements With Weak References](https://marcosantadev.com/swift-arrays-holding-elements-weak-references/)
* 掘金链接：[Swift Arrays Holding Elements With Weak References]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/swift-arrays-holding-elements-weak-references.md)
* PR 地址：#1692
* 文章分类：**iOS**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhangqippp** [comment]
翻译认领

**Comment by sqrthree** [comment]
好的

**Comment by ZhangRuixiang** [comment]
@sqrthree 
翻译认领
