### ISSUE TITLE
如何从一个业余爱好者成长成为专业开发者

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1680]
* 原文链接：[How to Go From Hobbyist to Professional Developer](https://medium.freecodecamp.com/how-to-go-from-hobbyist-to-professional-developer-11a8b8a52b5f)
* 掘金链接：[How to Go From Hobbyist to Professional Developer]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-go-from-hobbyist-to-professional-developer.md)
* PR 地址：#1703
* 文章分类：**不分类**
----
* 翻译时间：`9` 天
* 校对时间：`2` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zaraguo** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
@zaraguo 好的
