### ISSUE TITLE
如何不失理智的构建复杂用户界面

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1682]
* 原文链接：[How to build complex user interfaces without going completely insane](https://medium.freecodecamp.com/3-tips-to-keep-in-mind-while-developing-complex-ui-in-web-b56312310390)
* 掘金链接：[How to build complex user interfaces without going completely insane]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/tips-to-keep-in-mind-while-developing-complex-ui-in-web.md)
* PR 地址：#1710
* 文章分类：**设计**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
@sqrthree 认领~

**Comment by sqrthree** [comment]
@changkun 好哒~~
