### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by sysuKinthon** [xitu/gold-miner#1683]
- 公司/学校：中山大学
- 工作内容/专业：软件工程
- 常浏览的国外网站：stackoverflow
- 英语水平：英语六级
- 有无翻译经验：无
- 个人博客：http://blog.csdn.net/sysushui
- 个人介绍：目前在校大学生，之前从事前端相关工作，目前在学java后台

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
