### ISSUE TITLE
利用“Immutability（不可变性）”编写更为简洁高效的代码

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1684]
* 原文链接：[Write safer and cleaner code by leveraging the power of “Immutability”
](https://medium.freecodecamp.com/write-safer-and-cleaner-code-by-leveraging-the-power-of-immutability-7862df04b7b6)
* 掘金链接：[Write safer and cleaner code by leveraging the power of “Immutability”
]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/write-safer-and-cleaner-code-by-leveraging-the-power-of-immutability.md)
* PR 地址：#1688
* 文章分类：**前端**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gy134340** [comment]
@sqrthree 认领翻译

**Comment by sqrthree** [comment]
好的
