### ISSUE TITLE
A Mindful Design Process

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1685]
* 原文链接：[A Mindful Design Process](https://headspace.design/a-mindful-design-process-f4a4641ee88f)
* 掘金链接：[A Mindful Design Process]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-mindful-design-process.md)
* PR 地址：待添加
* 文章分类：**设计**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
@sqrthree 

好像没有小伙伴领走么，那我拿走啦。

**Comment by sqrthree** [comment]
噗，抱歉刚去查了下，发现有 [译文](http://www.jianshu.com/p/e30769766f6c) 了。要不你换一篇？
