### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by MRLP0524** [xitu/gold-miner#1689]
- 公司/学校：
                   育知同创科技有限公司
- 工作内容/专业：
                   教师
- 常浏览的国外网站：
                   segmentfault
- 英语水平：
                   CET-4
- 有无翻译经验：
                   有（但是是个人翻译，无其他人员校对）
- 个人博客：
                    https://juejin.im/user/578749b7128fe10063867323
                    http://www.jianshu.com/u/5a2fd0b8fb30
- 个人介绍：
                    一个普通 IT 男，喜欢分享，喜欢写文章，用文字来记录自己的生活。
                    英语水平一般，但是也想帮助其他人一起看到更新更好的文章。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
