### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by noturnot** [xitu/gold-miner#1694]
- 公司/学校：武汉大学
- 工作内容/专业：新闻与传播学院网络传播学
- 常浏览的国外网站：Medium、Dribbble、Producthunt、Quora .etc
- 英语水平：CET-4：620（六级还没考……）
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：热爱设计与观察互联网产品。虽然没有翻译经验，但有一颗绝对认真的心和一份确定的热情。希望可以加入~

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
