### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by yzgyyang** [xitu/gold-miner#1696]
“UX Review and Redesign of the CocaCola Freestyle Kiosk Interface” @WeighedAnt https://medium.com/@vedantha/ux-review-and-redesign-of-the-cocacola-freestyle-kiosk-interface-f77fc087c09

**Comment by sqrthree** [comment]
感谢推荐~

**Comment by sqrthree** [comment]
Issue: #1699
