### ISSUE TITLE
Why Empathy Matters as a UX Designer

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1697]
* 原文链接：[Why Empathy Matters as a UX Designer](https://careerfoundry.com/en/blog/ux-design/empathy-and-ux-design)
* 掘金链接：[Why Empathy Matters as a UX Designer]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/empathy-and-ux-design.md)
* PR 地址：待添加
* 文章分类：**设计**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xfffrank** [comment]
翻译认领～ @sqrthree
