### ISSUE TITLE
深度学习在 iOS 上的实践 —— 通过 YOLO 在 iOS 上实现实时物体检测 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1698]
* 原文链接：[Real-time object detection with YOLO](http://machinethink.net/blog/object-detection-with-yolo/)
* 掘金链接：[Real-time object detection with YOLO]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/object-detection-with-yolo.md)
* PR 地址：#1734
* 文章分类：**iOS**
----
* 翻译时间：`10` 天
* 校对时间：`2` 天
* 翻译积分：`10` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Danny1451** [comment]
这个好像很有趣的样子  认领了 端午研究研究

**Comment by sqrthree** [comment]
好的
