### ISSUE TITLE
可口可乐自由风格售卖亭界面用户体验的回顾和重新设计

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1699]
* 原文链接：[UX Review and Redesign of the CocaCola Freestyle Kiosk Interface](https://medium.com/@vedantha/ux-review-and-redesign-of-the-cocacola-freestyle-kiosk-interface-f77fc087c09)
* 掘金链接：[UX Review and Redesign of the CocaCola Freestyle Kiosk Interface]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/ux-review-and-redesign-of-the-cocacola-freestyle-kiosk-interface.md)
* PR 地址：#1758
* 文章分类：**设计**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ylq167** [comment]
翻译认领

**Comment by sqrthree** [comment]
好哒
