### ISSUE TITLE
REST 2.0 在此，它的名字叫 GraphQL

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1701]
* 原文链接：[REST 2.0 Is Here and Its Name Is GraphQL](https://www.sitepoint.com/rest-2-0-graphql/)
* 掘金链接：[REST 2.0 Is Here and Its Name Is GraphQL]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/rest-2-0-graphql.md)
* PR 地址：#1753
* 文章分类：**后端**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mnikn** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
好的
