### ISSUE TITLE
Node.js 流: 你需要知道的一切

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1702]
* 原文链接：[Node.js Streams: Everything you need to know](https://medium.freecodecamp.com/node-js-streams-everything-you-need-to-know-c9141306be93)
* 掘金链接：[Node.js Streams: Everything you need to know]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/node-js-streams-everything-you-need-to-know.md)
* PR 地址：#1730
* 文章分类：**后端**
----
* 翻译时间：`10` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by loveky** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
好的
