### ISSUE TITLE
读完 flexbox 细则之后学到的 11 件事

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1709]
* 原文链接：[11 things I learned reading the flexbox spec](https://hackernoon.com/11-things-i-learned-reading-the-flexbox-spec-5f0c799c776b)
* 掘金链接：[11 things I learned reading the flexbox spec]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/11-things-i-learned-reading-the-flexbox-spec.md)
* PR 地址：#1744
* 文章分类：**前端**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
翻译认领

**Comment by sqrthree** [comment]
好哒
