### ISSUE TITLE
统一样式语言

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1711]
* 原文链接：[A Unified Styling Language](https://medium.com/seek-blog/a-unified-styling-language-d0c208de2660)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-unified-styling-language.md)
* PR 地址：#1778
* 文章分类：**前端**
----
* 翻译时间：`12` 天
* 校对时间：`4` 天
* 翻译积分：`12` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZhangFe** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
好的

**Comment by fanyijihua** [comment]
PR 地址：#2212
