### ISSUE TITLE
What is the Future of Front End Web Development?

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1712]
* 原文链接：[What is the Future of Front End Web Development?](https://css-tricks.com/future-front-end-web-development/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/future-front-end-web-development.md)
* PR 地址：待添加
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xunge0613** [comment]
@sqrthree =w= 窝来认领啦~~~嘿嘿嘿~

**Comment by sqrthree** [comment]
@xunge0613 棒棒哒 b(￣▽￣)d

**Comment by xunge0613** [comment]
hi @sqrthree 这篇文章众城翻译那边已经翻译过啦 =。= 
 http://mp.weixin.qq.com/s/3RDHW1OmZRNLRB0tPkfE1

**Comment by sqrthree** [comment]
好的
