### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by icersummer** [xitu/gold-miner#1713]
- 公司/学校：平安科技；
- 工作内容/专业：Java开发、前端后端、大并发、多线程、NoSQL；
- 常浏览的国外网站：javacodegeeks.com，infoq.com，Twitter，Facebook，google.com，LinkedIn.com，ebay.com，coursera，dzone.com
- 英语水平：优。
- 有无翻译经验： javacodegeeks.com 翻译过5篇文章。
- 个人博客： http://icersummer.github.io/
- 个人介绍：本人具有10+年开发经验，主要专注于Java语言相关技术，工作、项目中涉及到前端、后端各种技术；目前从事于支付、互联网金融行业；对分布式、大并发、互联网金融、SQL、NoSQL、Oracle、Redis、MySQL、HBase、Maven、JQuery、freemarker、Android、Python等都有研究和涉猎；特申请加入技术翻译团队。

**Comment by sqrthree** [comment]
欢迎大大参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
