### ISSUE TITLE
Hot vs Cold Observables

### ISSUE THREAD

**Issue by yoyoyohamapi** [xitu/gold-miner#1716]
- 原文链接：https://medium.com/@benlesh/hot-vs-cold-observables-f8094ed53339
- 简要介绍：RxJS：Hot 和 Cold 类型的 Observable，来自 RxJS 的主要贡献者 Ben lesh

想自己认领翻译

**Comment by yoyoyohamapi** [comment]
认领

**Comment by sqrthree** [comment]
感谢推荐，链接在 #1729
