### ISSUE TITLE
UNIDIRECTIONAL USER INTERFACE ARCHITECTURES

### ISSUE THREAD

**Issue by yoyoyohamapi** [xitu/gold-miner#1718]
- 原文链接：https://staltz.com/unidirectional-user-interface-architectures.html
- 简要介绍：staltz（Cycle.js 作者）分析了流行的前端数据流结构，非常全面、深入

**Comment by yoyoyohamapi** [comment]
认领翻译

**Comment by sqrthree** [comment]
稍等，明天加

**Comment by sqrthree** [comment]
抱歉，[已经存在译文了](https://github.com/rabbitlive/SoILikeElm/blob/master/unidirectional-user-interface-architectures.md)。
