### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by CACppuccino** [xitu/gold-miner#1719]
- 公司/学校：澳洲国立大学 ANU
- 工作内容/专业：B.Software Engineering
- 常浏览的国外网站：StackOverflow/ Wallstreet
- 英语水平：IELTS 7.0
- 有无翻译经验：一篇AI历史博客文章翻译
- 个人博客：暂无
- 个人介绍：对算法、机器学习较为熟悉，希望能够贡献自己的力量让更多国内的伙伴们看到优质技术文章

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
