### ISSUE TITLE
11 Top Designers Share Honest Career Advice

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#172]
文章链接：[11 Top Designers Share Honest Career Advice](https://studio.uxpin.com/blog/11-top-designers-give-11-pieces-of-realistic-ux-advice/)
掘金链接：[11 Top Designers Share Honest Career Advice](http://gold.xitu.io/entry/56c025616be3ff005d6ac9fd)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/11-top-designers-give-11-pieces-of-realistic-ux-advice.md)

[PR地址](https://github.com/xitu/gold-miner/pull/200/files?diff=split)
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by L9m** [comment]
我来认领

**Comment by antonia0912** [comment]
@L9m 好的 那就交给你啊

**Comment by shenxn** [comment]
那就给我啦

**Comment by antonia0912** [comment]
@shenxn 交给小朋友
