### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by IAMSHENSH** [xitu/gold-miner#1720]
- 公司/学校： 海格通信
- 工作内容/专业： 应用软件设计师
- 常浏览的国外网站： [github](github.com) , [quora](quora.com)
- 英语水平：`CET-4`
- 有无翻译经验：暂无
- 个人博客：[iamshensh](iamshensh.github.io) 
- 个人介绍：前端与移动端开发者，热爱学习，喜欢分享！希望为知识传播贡献力量。 O(∩_∩)O

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
