### ISSUE TITLE
推荐优秀英文系列文章

### ISSUE THREAD

**Issue by xunge0613** [xitu/gold-miner#1721]
@sqrthree 大佬有条新大鱼

The Modern JavaScript Tutorial 系列文章
- 主页：http://javascript.info/
- GitHub：https://github.com/iliakan/javascript-tutorial

The JavaScript language
Here we learn JavaScript, starting from the scratch and to advanced concepts like OOP.

We concentrate on the language itself here, with the minimum of environment-specific notes.

**Comment by sqrthree** [comment]
感谢推荐，已经在沟通中。
