### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ppJuan** [xitu/gold-miner#1722]
- 公司/学校：同济大学
- 工作内容/专业：计算机科学与技术
- 常浏览的国外网站：GitHub
- 英语水平：四级
- 有无翻译经验：无
- 个人博客：有个人博客，暂时还没写过文章
- 个人介绍：本人妹纸，有一定前端开发经验，熟悉 HTML、CSS、原生 JavaScript，正在学习 VueJs、ES6，希望能加入翻译小组，做出一点贡献的同时也提升自己。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
