### ISSUE TITLE
使登录页面变得正确

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1726]
* 原文链接：[Getting the login page right](https://blog.prototypr.io/getting-the-login-page-right-d1ce6015235e)
* 掘金链接：[Getting the login page right]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/getting-the-login-page-right.md)
* PR 地址：#1774
* 文章分类：**设计**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LisaPeng** [comment]
@sqrthree 认领

**Comment by sqrthree** [comment]
@LisaPeng 好哒
