### ISSUE TITLE
高阶函数一点通

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1727]
* 原文链接：[Understanding Higher Order Components](https://medium.freecodecamp.com/understanding-higher-order-components-6ce359d761b)
* 掘金链接：[Understanding Higher Order Components]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/understanding-higher-order-components.md)
* PR 地址：#1775
* 文章分类：**前端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by AceLeeWinnie** [comment]
认领

**Comment by sqrthree** [comment]
OK

**Comment by AceLeeWinnie** [comment]
#1775 @sqrthree 翻译完成，求校对
