### ISSUE TITLE
用 Go 语言理解 Tensorflow

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1728]
* 原文链接：[Understanding Tensorflow using Go](https://pgaleone.eu/tensorflow/go/2017/05/29/understanding-tensorflow-using-go/)
* 掘金链接：[Understanding Tensorflow using Go]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/understanding-tensorflow-using-go.md)
* PR 地址：#1754
* 文章分类：**后端**
----
* 翻译时间：`7` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
认领

**Comment by lsvih** [comment]
话说是不是要加个新的 机器学习 分类。。。

**Comment by sqrthree** [comment]
@lsvih 好哒~
