### ISSUE TITLE
Observable 之冷热

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1729]
* 原文链接：[Hot vs Cold Observables](https://medium.com/@benlesh/hot-vs-cold-observables-f8094ed53339)
* 掘金链接：[Hot vs Cold Observables]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/hot-vs-cold-observables.md)
* PR 地址：#1751
* 文章分类：**前端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hikerpig** [comment]
认领翻译~

**Comment by sqrthree** [comment]
好的
