### ISSUE TITLE
Python3.5 协程原理

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#173]
文章链接：[How the heck does async/await work in Python 3.5?](http://www.snarky.ca/how-the-heck-does-async-await-work-in-python-3-5)
掘金链接：[Python3.5 协程原理](http://gold.xitu.io/entry/56c1d7bb1532bc0054ab1b6a)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/how-the-heck-does-async-await-work-in-python-3-5.md)
[PR地址](https://github.com/xitu/gold-miner/pull/199/files?diff=split)
翻译积分：8
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by rainyear** [comment]
认领

**Comment by antonia0912** [comment]
@rainyear 好的  等你pr

**Comment by antonia0912** [comment]
@rainyear 老弟呀  翻译的怎么样啦  ！！！！这次是大砍刀还是小皮鞭呐（傲娇脸）

**Comment by rainyear** [comment]
@antonia0912 这篇好长呐，已经每天熬夜到3点翻译啦:cry:

**Comment by Glowin** [comment]
@rainyear 辛苦啦

**Comment by rainyear** [comment]
已提交pr！

这篇太长了翻译好累！不过作者写得太棒了，收获非常大，我要先贴到自己blog里~
