### ISSUE TITLE
在 Reddit 中代码部署的演进

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1735]
* 原文链接：[The Evolution of Code Deploys at Reddit](https://redditblog.com/2017/06/02/the-evolution-of-code-deploys-at-reddit/)
* 掘金链接：[The Evolution of Code Deploys at Reddit]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-evolution-of-code-deploys-at-reddit.md)
* PR 地址：#1777
* 文章分类：**运维**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by steinliber** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
好的
