### ISSUE TITLE
Kotlin 中我讨厌什么

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1737]
* 原文链接：[What do I hate in Kotlin](http://marcinmoskala.com/kotlin/2017/05/31/what-i-hate-in-kotlin.html)
* 掘金链接：[What do I hate in Kotlin]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-i-hate-in-kotlin.md)
* PR 地址：#1750
* 文章分类：**Android**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zhiw** [comment]
好久没来了，认领一下

**Comment by sqrthree** [comment]
好哒

**Comment by stormrabbit** [comment]
@sqrthree 
预订校对

**Comment by sqrthree** [comment]
@stormrabbit 好的，校对地址在 #1750
