### ISSUE TITLE
一封写给 CSS 的情书

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1738]
* 原文链接：[A Love Letter to CSS](http://developer.telerik.com/topics/web-development/love-letter-css/)
* 掘金链接：[A Love Letter to CSS]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/love-letter-css.md)
* PR 地址：#1773
* 文章分类：**前端**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by reid3290** [comment]
@sqrthree 认领翻译

**Comment by sqrthree** [comment]
好的
