### ISSUE TITLE
Disassembling JavaScript's IIFE Syntax

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#174]
文章链接：[Disassembling JavaScript's IIFE Syntax](https://blog.mariusschulz.com/2016/01/13/disassembling-javascripts-iife-syntax)
掘金链接：[Disassembling JavaScript's IIFE Syntax](http://gold.xitu.io/entry/56af8b49c4c971005331bee1)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/disassembling-javascripts-iife-syntax.md)
[PR地址](https://github.com/xitu/gold-miner/pull/202/files?diff=split)
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Huxpro** [comment]
@antonia0912 
Interested in that.

**Comment by antonia0912** [comment]
要先发issue申请成为我们掘金翻译计划的译者才可以来认领文章并翻译喔~~ @Huxpro  而且需要介绍一下自己   有没有相关翻译经验呀  对哪个板块比较感兴趣呀  之类的  等你issue哈

**Comment by antonia0912** [comment]
这篇文章就交给你啦 @Huxpro

**Comment by Huxpro** [comment]
Sure~

> On Mar 1 2016, at 9:01 pm, antonia0912 &lt;notifications@github.com&gt;
wrote:  

>

> 这篇文章就交给你啦 [@Huxpro](https://github.com/Huxpro)

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/xitu
/gold-miner/issues/174#issuecomment-191062655).![](https://github.com/notifica
tions/beacon/AFTjsy-NlcSZ4aMQPvi_4yl2S_iJD03jks5ppRm_gaJpZM4HmMNY.gif)

**Comment by sqrthree** [comment]
申请校对。

**Comment by antonia0912** [comment]
@sqrthree OK  PR地址 https://github.com/xitu/gold-miner/pull/202/files?diff=split
