### ISSUE TITLE
时间复杂度 O(log n) 意味着什么

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1740]
* 原文链接：[What does the time complexity O(log n) actually mean?](https://hackernoon.com/what-does-the-time-complexity-o-log-n-actually-mean-45f94bb5bfbf)
* 掘金链接：[What does the time complexity O(log n) actually mean?]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-does-the-time-complexity-o-log-n-actually-mean.md)
* PR 地址：#1757
* 文章分类：**编程**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cdpath** [comment]
这个简单 我来吧

**Comment by sqrthree** [comment]
好哒
