### ISSUE TITLE
Android 中的定时任务调度

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1741]
* 原文链接：[Schedule tasks and jobs intelligently in Android](https://android.jlelse.eu/schedule-tasks-and-jobs-intelligently-in-android-e0b0d9201777)
* 掘金链接：[Schedule tasks and jobs intelligently in Android]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/schedule-tasks-and-jobs-intelligently-in-android.md)
* PR 地址： #1823
* 文章分类：**Android**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by phxnirvana** [comment]
蹭点分，领了

**Comment by sqrthree** [comment]
@phxnirvana 好的
