### ISSUE TITLE
如何在无损的情况下让图片变的更小 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1742]
* 原文地址：[Making Photos Smaller Without Quality Loss](https://engineeringblog.yelp.com/2017/06/making-photos-smaller.html)
* 掘金链接：[Making Photos Smaller Without Quality Loss]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/making-photos-smaller.md)
* PR 地址：#1795
* 文章分类：**后端**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
翻译认领

**Comment by sqrthree** [comment]
@XatMassacrE 好哒~ 

@icersummer 来晚咯，你可以看看有没有其他感兴趣的文章哈。

**Comment by sqrthree** [comment]
PR 地址：#1795
