### ISSUE TITLE
iOS 11：UIKit 中重要的新能力

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1743]
* 原文链接：[iOS 11: Notable UIKit Additions](https://medium.com/the-traveled-ios-developers-guide/ios-11-notable-uikit-additions-92e5eb421c3b)
* 掘金链接：[iOS 11: Notable UIKit Additions](https://github.com/xitu/gold-miner/blob/master/TODO/ios-11-notable-uikit-additions.md)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/ios-11-notable-uikit-additions.md)
* PR 地址：#1764
* 文章分类：**iOS**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhangqippp** [comment]
翻译认领

**Comment by sqrthree** [comment]
好的
