### ISSUE TITLE
Functional Mixins

### ISSUE THREAD

**Issue by yoyoyohamapi** [xitu/gold-miner#1745]
- 原文链接：https://medium.com/javascript-scene/functional-mixins-composing-software-ffb66d5e731c
- 简要介绍：Elliot 大神 Composing Software 最新一篇

自领翻译了，之前两篇参与翻译了 @sqrthree

**Comment by sqrthree** [comment]
好的

**Comment by sqrthree** [comment]
这是第七部分吗？

**Comment by sqrthree** [comment]
#1746
