### ISSUE TITLE
函数式 Mixin

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1746]
* 原文链接：[Functional Mixins](https://medium.com/javascript-scene/functional-mixins-composing-software-ffb66d5e731c)
* 掘金链接：[Functional Mixins]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/functional-mixins-composing-software.md)
* PR 地址：#1759
* 文章分类：**前端**
----
* 翻译时间：`7` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sqrthree** [comment]
译者 @yoyoyohamapi

**Comment by yoyoyohamapi** [comment]
@sqrthree 发布啦！https://juejin.im/post/594a2cf6ac502e006bc0bc3a
