### ISSUE TITLE
Node.js 子进程：你应该知道的一切

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1747]
* 原文链接：[Node.js Child Processes: Everything you need to know](https://medium.freecodecamp.com/node-js-child-processes-everything-you-need-to-know-e69498fe970a)
* 掘金链接：[Node.js Child Processes: Everything you need to know]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/node-js-child-processes-everything-you-need-to-know.md)
* PR 地址：#1838
* 文章分类：**后端**
----
* 翻译时间：`9` 天
* 校对时间：`2` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by FrankXiong** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
好的
