### ISSUE TITLE
理解 NPM 5 中的 lock 文件

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1748]
* 原文链接：[Understanding lock files in NPM 5](http://jpospisil.com/2017/06/02/understanding-lock-files-in-npm-5.html)
* 掘金链接：[Understanding lock files in NPM 5]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/understanding-lock-files-in-npm-5.md)
* PR 地址：#1763
* 文章分类：**后端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
这个应该是前端内容吧。。

**Comment by changkun** [comment]
@sqrthree 认领

**Comment by sqrthree** [comment]
@changkun 好哒

**Comment by Aladdin-ADD** [comment]
校对认领~~

**Comment by sqrthree** [comment]
好的
