### ISSUE TITLE
A day without Javascript

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1749]
* 原文链接：[A day without Javascript](https://sonniesedge.co.uk/blog/a-day-without-javascript)
* 掘金链接：[A day without Javascript]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-day-without-javascript.md)
* PR 地址：待添加
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
这篇文章好像我在哪看到过完成版的....

**Comment by sqrthree** [comment]
发现[译文](https://sdk.cn/news/7070)了 _(:з」∠)_
