### ISSUE TITLE
Simplify Your Life With an SSH Config File

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#175]
文章链接：[Simplify Your Life With an SSH Config File](http://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/)
掘金链接：[Simplify Your Life With an SSH Config File](http://gold.xitu.io/entry/56af6afcc4c9710053308b3f)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/simplify-your-life-with-an-ssh-config-file.md)
[PR地址](https://github.com/xitu/gold-miner/pull/197/files?diff=split)
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by circlelove** [comment]
认!

**Comment by antonia0912** [comment]
@circlelove 得嘞！！！

**Comment by sqrthree** [comment]
认领校对╭(′▽`)╯

**Comment by antonia0912** [comment]
@sqrthree ok

**Comment by circlelove** [comment]
@antonia0912  修完了，看看原来自己好像快睡了翻的真烂
