### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by JackGit** [xitu/gold-miner#1752]
- 公司/学校：自由职业 / 武汉理工大学2011年本科毕业
- 工作内容/专业：WEB，前端 / 本科GIS专业
- 常浏览的国外网站：stackoverflow, medium, http://3dscanexpert.com/, youtube, https://www.smashingmagazine.com, etc
- 英语水平：CET6
- 有无翻译经验：没有专门的做过翻译
- 个人博客：https://segmentfault.com/u/ygjack/articles
- 个人介绍：热爱coding，热爱开源

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
