### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Weiting-Zhang** [xitu/gold-miner#1756]
- 公司/学校：大连理工大学
- 工作内容/专业：化学专业
- 常浏览的国外网站：Quara github facebook
- 英语水平：CET-6
- 有无翻译经验：有过翻译TED字幕的经验
- 个人博客：https://weiting-zhang.github.io/
- 个人介绍：大三学生。前端学习者爱好者。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
