### ISSUE TITLE
当设计模式遇上 Kotlin 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1761]
* 原文链接：[Gang of Four Patterns in Kotlin](https://dev.to/lovis/gang-of-four-patterns-in-kotlin)
* 掘金链接：[Gang of Four Patterns in Kotlin]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/gang-of-four-patterns-in-kotlin.md)
* PR 地址：#1780
* 文章分类：**Android**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by BoilerYao** [comment]
来一篇~

**Comment by sqrthree** [comment]
好的
