### ISSUE TITLE
以排印为本：从内容出发

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1762]
* 原文链接：[Typography as Base: From the Content Out](https://medium.com/subvisual/typography-as-base-from-the-content-out-c59fe7bfb633)
* 掘金链接：[Typography as Base: From the Content Out]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/typography-as-base-from-the-content-out.md)
* PR 地址：#1841
* 文章分类：**设计**
----
* 翻译时间：`9` 天
* 校对时间：`2` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cdpath** [comment]
我来可以吗？字体排印爱好者

**Comment by sqrthree** [comment]
好哒~ 那辛苦你啦

**Comment by cdpath** [comment]
@sqrthree 掘金地址[在此](https://juejin.im/entry/5965c5b26fb9a06ba025074c/detail#comment)
