### ISSUE TITLE
V8 性能优化杀手

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1769]
* 原文链接：[Optimization killers](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/Optimization-killers.md)
* PR 地址：#1828
* 文章分类：**前端**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
认领！

**Comment by sqrthree** [comment]
好哒

**Comment by Aladdin-ADD** [comment]
校对认领，先占坑~~

**Comment by lsvih** [comment]
@sqrthree 这篇文章是 @Aladdin-ADD 推荐的，他来翻译吧= =我就不抢了。。。

**Comment by Aladdin-ADD** [comment]
何必客气，你翻译吧，我来校对就好 😄

**Comment by lsvih** [comment]
@Aladdin-ADD 那我不客气啦！😆

**Comment by sqrthree** [comment]
这篇进度如何了呀？

**Comment by lsvih** [comment]
@sqrthree 。。发现这篇文章很老了，已经有好些版本的了  例如 http://dev.zm1v1.com/2015/08/19/javascript-optimization-killers/

**Comment by Aladdin-ADD** [comment]
v8的优化策略也在进化，这篇wiki也在更新，比如最新发布的TurboFan优化编译器，以前不能优化的现在已经能够优化了，感觉还是有必要更新一下译文。

just my 2c :(

**Comment by lsvih** [comment]
T_T  I'm terribly sorry that i wasted a lot of time. Actually this translation has almost been accomplished, i'll send pr tomorrow.

**Comment by zhaochuanxing** [comment]
@sqrthree  校对认领

**Comment by zhaochuanxing** [comment]
@sqrthree  校对完成
