### ISSUE TITLE
前端框架选择：Angular vs Ember vs React]

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#177]
文章链接：[CHOOSING A FRONT END FRAMEWORK: ANGULAR VS. EMBER VS. REACT](http://smashingboxes.com/blog/choosing-a-front-end-framework-angular-ember-react)
掘金链接：[前端框架选择：Angular vs Ember vs React](http://gold.xitu.io/entry/5698d06560b21c048731e15d)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/choosing-a-front-end-framework-angular-ember-react.md)

**Comment by L9m** [comment]
我来认领这篇

**Comment by antonia0912** [comment]
@L9m 请问你是我们掘金翻译计划的译者吗？不是的话要先发issue申请译者喔~简单介绍一下自己

**Comment by antonia0912** [comment]
好的  期待你的pr @L9m  有不明白的直接在群里问大家或者at我就可以了
