### ISSUE TITLE
ESLint v4.0.0 升级指南

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1770]
* 原文链接：[ESLint Migrating to v4.0.0](http://eslint.org/docs/user-guide/migrating-to-4.0.0)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/eslint-migrating-to-4.0.0.md)
* PR 地址：#1816
* 文章分类：**前端**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xunge0613** [comment]
认领 =。= @sqrthree

**Comment by sqrthree** [comment]
好的

**Comment by Aladdin-ADD** [comment]
@xunge0613 , 这个什么进度了？ (no rush... :(

**Comment by sqrthree** [comment]
PR 地址：#1816

**Comment by sqrthree** [comment]
@Aladdin-ADD 这篇已经翻译好了，可否参与校对呢？我们速战速决

**Comment by Aladdin-ADD** [comment]
@sqrthree @xunge0613 正在校对，晚上提交~ 🤝
