### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by swants** [xitu/gold-miner#1771]
- 公司/学校：北京亿苗通生物科技
- 工作内容/专业：iOS开发
- 常浏览的国外网站：NSHipster stackoverflow. GitHub
- 英语水平：CET-6
- 有无翻译经验：有
- 个人博客：-
- 个人介绍：iOS开发 喜欢了解最新技术文章

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
