### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by lileizhenshuai** [xitu/gold-miner#1772]
- 公司/学校：西安电子科技大学
- 工作内容/专业：软件工程
- 常浏览的国外网站：Github, StackOverFlow, LeetCode, Coursera
- 英语水平：四级
- 有无翻译经验：无
- 个人博客：tobiaslee.top
- 个人介绍：热爱Java、Python以及Android开发；英语尚可，喜欢阅读英文原版书籍，看英文文档没有太大障碍；希望能够加入掘金翻译计划，贡献一份绵薄之力。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
