### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Endone** [xitu/gold-miner#1776]
- 公司/学校：网易/浙大
- 工作内容/专业：游戏开发/计算机
- 常浏览的国外网站：StackOverflow, CodeProject, Gaffer on Games, Quora
- 英语水平：六级
- 有无翻译经验：无
- 个人博客：http://www.jackyzhao.com/
- 个人介绍：毕业没多久，目前从事游戏服务端开发，对.Net，网络方向有较多的学习和积累

**Comment by sqrthree** [comment]
两位校对者都已经校对好了~ 可以来根据校对意见进行调整了哈 ┏ (゜ω゜)=☞
