### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by wilsonandusa** [xitu/gold-miner#1779]
- 公司/学校：IBM实习/UIUC(美本)
- 工作内容/专业：前端+android / 计算机工程
- 常浏览的国外网站：stackoverflow, GitHub, TechCrunch, LeetCode
- 英语水平：托福100+（五年前）
- 有无翻译经验：自己翻译过一点算法题总结
- 个人博客：http://xiaoshengwilsonwu.com/about.html
- 个人介绍：本科毕业暑假中 即将读研

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
