### ISSUE TITLE
2016 - the year of web streams

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#178]
文章链接：[2016 - the year of web streams](https://jakearchibald.com/2016/streams-ftw/)
掘金链接：[2016 - the year of web streams](http://gold.xitu.io/entry/56a982fc7db2a2005a4fde40)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/streams-ftw.md)

**Comment by sqrthree** [comment]
我来翻译这一篇吧。

**Comment by antonia0912** [comment]
好的  我马上添加文章md @sqrthree

**Comment by antonia0912** [comment]
@sqrthree markdown文件已经添加  请注意表格内的文字也要一起翻译了哈  就是那个黄的红的绿的蓝的条条里的英文也要翻译喔

**Comment by L9m** [comment]
@antonia0912 @sqrthree 这篇网上已经有翻译了 http://www.w3ctech.com/topic/1693

**Comment by antonia0912** [comment]
@L9m 谢谢提醒
