### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by xx1124961758** [xitu/gold-miner#1781]
- 公司/学校： 杭州壹点灵
- 工作内容/专业： 前端开发/电子商务
- 常浏览的国外网站：stackoverflow/mdn/w3c
- 英语水平：4级
- 有无翻译经验：无
- 个人博客：
- 个人介绍：我是一名前端开发人员，明白英语能力对于前端开发的重要性，希望通过自己的努力让国外优秀的文章传进国内。也希望在参与到掘金这个平台，共同维护一个纯碎的技术社区努力。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
