### ISSUE TITLE
webpack 3.0 正式发布

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1782]
* 原文链接：[webpack 3: Official Release!!](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b)
* 掘金链接：[webpack 3.0 正式发布 | 新增 Scope Hosting](https://juejin.im/entry/59487d8aa0bb9f006beb3d39)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/webpack-3-official-release.md)
* PR 地址：#1790
* 文章分类：**前端**
----
* 翻译时间：`2` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xilihuasi** [comment]
@sqrthree 认领认领

**Comment by sqrthree** [comment]
@xilihuasi 老铁 6666
