### ISSUE TITLE
开发者眼中 iOS 11 都更新了什么？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1783]
* 原文链接：[What's new in iOS 11 for developers](https://www.hackingwithswift.com/whats-new-in-ios-11)
* 掘金链接：[What's new in iOS 11 for developers]()
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/whats-new-in-ios-11.md)
* PR 地址：#1851
* 文章分类：**iOS**
----
* 翻译时间：`15` 天
* 校对时间：`3` 天
* 翻译积分：`15` 分
* 校对积分：`3` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by swants** [comment]
认领 @sqrthree

**Comment by sqrthree** [comment]
@swants 辛苦了老铁 ❤

**Comment by sqrthree** [comment]
PR 地址：#1851
