### ISSUE TITLE
把 UUID 或者 GUID 作为主键？你得小心啦！

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1784]
* 原文链接：[UUID or GUID as Primary Keys? Be Careful!](https://tomharrisonjr.com/uuid-or-guid-as-primary-keys-be-careful-7b2aa3dcb439)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/uuid-or-guid-as-primary-keys-be-careful.md)
* PR 地址：#1804
* 文章分类：**后端**
----
* 翻译时间：`6` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zaraguo** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@zaraguo 好哒
