### ISSUE TITLE
JavaScript：回调是什么鬼？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1785]
* 原文链接：[JavaScript: What the heck is a Callback?](https://codeburst.io/javascript-what-the-heck-is-a-callback-aba4da2deced)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/javascript-what-the-heck-is-a-callback.md)
* PR 地址：#1792
* 文章分类：**前端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
@sqrthree  翻译认领

**Comment by sqrthree** [comment]
好哒
