### ISSUE TITLE
说服Kotlin编译器代码安全

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1786]
* 原文链接：[Convincing the Kotlin compiler that code is safe](http://blog.danlew.net/2017/06/14/convincing-the-kotlin-compiler-that-code-is-safe/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/convincing-the-kotlin-compiler-that-code-is-safe.md)
* PR 地址：#1803
* 文章分类：**Android**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wilsonandusa** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
好哒
