### ISSUE TITLE
Kotlin：小菜一碟

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1787]
* 原文链接：[Kotlin: It’s the little things](https://m.signalvnoise.com/kotlin-its-the-little-things-8c0f501bc6ea)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/kotlin-its-the-little-things.md)
* PR 地址：#1793
* 文章分类：**Android**
----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CACppuccino** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
好的
