### ISSUE TITLE
Node.js 和 Python 对比 —— 哪里使用 Node.js 哪里使用 Python ？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1789]
* 原文链接：[Node.js vs Python – Where to Use and Where not?](https://www.agriya.com/blog/2016/07/13/nodejs-vs-python-where-to-use-and-where-not/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/nodejs-vs-python-where-to-use-and-where-not.md)
* PR 地址：#1807
* 文章分类：**后端**
----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ymz1124** [comment]
翻译认领

**Comment by ymz1124** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
OK
