### ISSUE TITLE
第一次走进 Android 中的 Kotlin 协程

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1797]
* 原文链接：[A first walk into Kotlin coroutines on Android](https://android.jlelse.eu/a-first-walk-into-kotlin-coroutines-on-android-fe4a6e25f46a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-first-walk-into-kotlin-coroutines-on-android.md)
* PR 地址：#1808
* 文章分类：**Android**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Feximin** [comment]
@sqrthree 认领，尝试一下哈

**Comment by sqrthree** [comment]
好的

**Comment by atuooo** [comment]
@sqrthree 校对认领

**Comment by sqrthree** [comment]
到 PR 下认领校对啦
