### ISSUE TITLE
如何充分利用 JavaScript 控制台

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1798]
* 原文链接：[How to get the most out of the JavaScript console](https://medium.freecodecamp.com/how-to-get-the-most-out-of-the-javascript-console-b57ca9db3e6d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-get-the-most-out-of-the-javascript-console.md)
* PR 地址：#1805
* 文章分类：**前端**
----
* 翻译时间：`5` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
认领翻译

**Comment by sqrthree** [comment]
@sunui 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#1805
