### ISSUE TITLE
理解 Python 中的异步编程

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1799]
* 原文链接：[Understanding Asynchronous Programming in Python](https://dbader.org/blog/understanding-asynchronous-programming-in-python)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/understanding-asynchronous-programming-in-python.md)
* PR 地址：#1875
* 文章分类：**Python**
----
* 翻译时间：`15` 天
* 校对时间：`4` 天
* 翻译积分：`12` 分
* 校对积分：`3` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by steinliber** [comment]
翻译认领😄 @sqrthree

**Comment by sqrthree** [comment]
@steinliber 棒极啦 :tada:
