### ISSUE TITLE
认领 Absolute Beginner's Guide to Swift

### ISSUE THREAD

**Issue by cdpath** [xitu/gold-miner#18]
_Absolute Beginner's Guide to Swift_

**Comment by cdpath** [comment]
翻译完了。语法错误太多了，已经醉了。查了一下作者好像是印度人。

**Comment by Glowin** [comment]
已经加你到readme，辛苦你翻译印度式英语了。

欢迎加入组织 :+1:

**Comment by Glowin** [comment]
你好，我拉了一个掘金翻译计划译者的微信群，译者都在群里面，我会在群里面更新活动的最新进展，如果方便的话可以加我一下微信 Glowjiang。
