### ISSUE TITLE
用简洁的 Architecture Pattern 来开发 Android 应用

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#180]
文章链接：[A detailed guide on developing Android apps using the Clean Architecture pattern](https://medium.com/@dmilicic/a-detailed-guide-on-developing-android-apps-using-the-clean-architecture-pattern-d38d71e94029#.7cz5w0dp3)
掘金链接：[用简洁的 Architecture Pattern 来开发 Android 应用](http://gold.xitu.io/entry/56b9ee58df0eea00547fe710)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/a-detailed-guide-on-developing-android-apps-using-the-clean-architecture-pattern.md)

**Comment by Glowin** [comment]
这个为什么关掉了呢？

**Comment by antonia0912** [comment]
@Glowin 网上有译文
