### ISSUE TITLE
iOS 11：机器学习人人有份

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1800]
* 原文链接：[iOS 11: Machine Learning for everyone](http://machinethink.net/blog/ios-11-machine-learning-for-everyone/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/ios-11-machine-learning-for-everyone.md)
* PR 地址：#1802
* 文章分类：**iOS**
----
* 翻译时间：`10` 天
* 校对时间：`2` 天
* 翻译积分：`10` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
@sqrthree 认领

**Comment by sqrthree** [comment]
辛苦啦
