### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by laiyun90** [xitu/gold-miner#1806]
- 公司/学校：小米科技有限公司
- 工作内容/专业：海外社区产品经理
- 常浏览的国外网站：c.mi.com(自己的产品)
- 英语水平：专业八级
- 有无翻译经验：有
- 个人博客：无
- 个人介绍：一枚试图涉猎翻译的产品

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
