### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by canonxu** [xitu/gold-miner#1809]
- 公司/学校：阿里巴巴-菜鸟网络/上海交通大学
- 工作内容/专业：JAVA开发
- 常浏览的国外网站：reddit/quora/infoq
- 英语水平：CET-6(580)
- 有无翻译经验：有
- 个人博客：canonxu.com(云主机到期，暂时访问不了)
- 个人介绍：JAVA开发，关注Spring相关，尤其是Spring Boot

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
