### ISSUE TITLE
Wrapping Existing Libraries With RxJava

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#181]
文章链接：[Wrapping Existing Libraries With RxJava](http://ryanharter.com/blog/2015/07/07/wrapping-existing-libraries-with-rxjava/)
掘金链接：[Wrapping Existing Libraries With RxJava](http://gold.xitu.io/entry/56ac93956240b8005a41c391)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/wrapping-existing-libraries-with-rxjava.md)

[PR地址](https://github.com/xitu/gold-miner/pull/201/files?diff=split)

翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Sausure** [comment]
有点挑战，我来试试@antonia0912

**Comment by antonia0912** [comment]
@Sausure ok

**Comment by Sausure** [comment]
@antonia0912 抱歉，最近校招的事情有点多，我担心这篇文章无法按时翻译，能否转给别人

**Comment by antonia0912** [comment]
好的 我change一下label就可以了  你先忙 @Sausure

**Comment by Sausure** [comment]
多谢

**Comment by yinshudi** [comment]
这个我来翻吧

**Comment by edvardHua** [comment]
认领！

**Comment by antonia0912** [comment]
@yinshudi 好的  那就交给你啦

**Comment by markzhai** [comment]
能预定一下校对么

**Comment by antonia0912** [comment]
@markzhai 当然可以啦  译者@yinshudi 翻译完麻烦@一下markzhai

**Comment by yinshudi** [comment]
@markzhai  抱歉，由于最近刚换工作和城市，导致翻译拖了几天。现在翻译完了，求校对。

**Comment by antonia0912** [comment]
@markzhai 译者翻译完成啦  可以去校对啦 PR地址 https://github.com/xitu/gold-miner/pull/201/files?diff=split

**Comment by markzhai** [comment]
我来看看

**Comment by Sausure** [comment]
校对+1

**Comment by antonia0912** [comment]
@Sausure 好的  PR地址 https://github.com/xitu/gold-miner/pull/201/files?diff=split
