### ISSUE TITLE
更好的表单设计: 每一页，一件事（实例研究）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1810]
* 原文链接：[Better Form Design: One Thing Per Page (Case Study)](https://www.smashingmagazine.com/2017/05/better-form-design-one-thing-per-page/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/better-form-design-one-thing-per-page.md)
* PR 地址：#1862
* 文章分类：**设计&产品**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：7 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by horizon13th** [comment]
认领翻译 @sqrthree

**Comment by sqrthree** [comment]
@horizon13th 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#1862
