### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by zaraguo** [xitu/gold-miner#1811]
原文链接：https://hackernoon.com/functional-programming-in-javascript-is-an-antipattern-58526819f21e
简要介绍：安利一发 Clojurescript

**Comment by sqrthree** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by zaraguo** [comment]
@sqrthree こんな可愛い子が女の子のはずがない

**Comment by sqrthree** [comment]
文章已添加在 #1815 (◍•ᴗ•`◍)*＊
