### ISSUE TITLE
探索 Kotlin 中的隐性成本（第一部分）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1812]
* 原文链接：[Exploring Kotlin’s hidden costs — Part 1](https://medium.com/@BladeCoder/exploring-kotlins-hidden-costs-part-1-fbb9935d9b62)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/exploring-kotlins-hidden-costs-part-1.md)
* PR 地址：#1843
* 文章分类：**Android**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：6 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Feximin** [comment]
@sqrthree 认领

**Comment by sqrthree** [comment]
好的

**Comment by wbinarytree** [comment]
刚要说问下这一系列有没有人翻译。回来看下果然有了。非常棒的一些列文章，希望翻译的时候多用心，辛苦了！

**Comment by sqrthree** [comment]
@wbinarytree 有没有兴趣考虑后面的两篇？
