### ISSUE TITLE
探索 Kotlin 中的隐性成本（第二部分）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1813]
* 原文链接：[Exploring Kotlin’s hidden costs — Part 2](https://medium.com/@BladeCoder/exploring-kotlins-hidden-costs-part-2-324a4a50b70)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/exploring-kotlins-hidden-costs-part-2.md)
* PR 地址：#1878
* 文章分类：**Android**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Feximin** [comment]
周末还没有人翻译的话就给我吧。。 @sqrthree

**Comment by sqrthree** [comment]
好

**Comment by Feximin** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
@Feximin 棒极啦 :tada:

**Comment by zhaochuanxing** [comment]
@sqrthree  校对认领

**Comment by sqrthree** [comment]
@zhaochuanxing 抱歉这个 PR 地址写错了，原 PR 已经有两位校对者了。你可以换一篇哈。
