### ISSUE TITLE
探索 Kotlin 的隐性成本（第三部分）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1814]
* 原文链接：[Exploring Kotlin’s hidden costs — Part 3](https://medium.com/@BladeCoder/exploring-kotlins-hidden-costs-part-3-3bf6e0dbf0a4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/exploring-kotlins-hidden-costs-part-3.md)
* PR 地址： #1939
* 文章分类：**Android**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：6 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by phxnirvana** [comment]
领~@sqrthree

**Comment by sqrthree** [comment]
好的

**Comment by sqrthree** [comment]
这篇进度如何了？

**Comment by Feximin** [comment]
@phxnirvana 大佬，你翻译完了，我认领个校对~

**Comment by phxnirvana** [comment]
==立flag，今天完成
