### ISSUE TITLE
Javascript 的函数式编程是一种反模式

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1815]
* 原文链接：[Functional programming in Javascript is an antipattern](https://hackernoon.com/functional-programming-in-javascript-is-an-antipattern-58526819f21e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/functional-programming-in-javascript-is-an-antipattern.md)
* PR 地址：#1842
* 文章分类：**前端**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：6 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
@sqrthree  翻译认领

**Comment by sqrthree** [comment]
@sunui 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#1842

**Comment by leviding** [comment]
校对认领 @sqrthree

**Comment by sqrthree** [comment]
小哥，你搞错地方啦，到 PR 下认领哈。
