### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by xunge0613** [xitu/gold-miner#1818]
https://opensource.guide/starting-a-project/

**Starting an Open Source Project**
Learn more about the world of open source and get ready to launch your own project.

github - insights - community 上推荐的……
https://github.com/xunge0613/front-end-growth/community

**Comment by sqrthree** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by xunge0613** [comment]
尴尬尴尬~ 发现好像已经有中文翻译在进行了 =.=

https://github.com/github/opensource.guide/issues/328 

不过这篇文章确实还没被认领…………

**Comment by sqrthree** [comment]
我记得好像有中文翻译在进行

**Comment by sqrthree** [comment]
哈哈哈~ 那我 close 掉啦
