### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zsp322** [xitu/gold-miner#1819]
- 公司/学校：ADP/Georgia Institute of Technology 
- 工作内容/专业：Front-end Engineer 
- 常浏览的国外网站：Quora, StackOverFlow
- 英语水平： :)
- 有无翻译经验：None
- 个人博客：
- 个人介绍： Interested at contributing to the community if needed

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
