### ISSUE TITLE
为什么有些设计初衷很好，结果却很糟糕？

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#182]
文章链接：[Deconstructing the Poor Design of a Well-Intentioned Microinteraction](https://medium.com/ux-immersion-interactions/deconstructing-the-poor-design-of-a-well-intentioned-microinteraction-e667e022e628#.u41e59zgi)
掘金链接：[为什么有些设计初衷很好，结果却很糟糕？](http://gold.xitu.io/entry/56c43c201532bc0054badad3)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/deconstructing-the-poor-design-of-a-well-intentioned-microinteraction.md)

翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by L9m** [comment]
我来认领这篇

**Comment by L9m** [comment]
我来认领这篇

**Comment by antonia0912** [comment]
@L9m 好的好的呀  等你pr  有不清楚的直接在群里问大家或者at我就好啦
