### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Svtter** [xitu/gold-miner#1821]
- 公司/学校：烟台大学
- 工作内容/专业：free lancer / 软件工程
- 常浏览的国外网站：google.com
- 英语水平：6
- 有无翻译经验：参见Linux.cn
- 个人博客：svtter.info
- 个人介绍：技术热爱者

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
