### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by canonxu** [xitu/gold-miner#1822]
- 原文链接：[What Archive Format Should You Use, WAR or JAR?](https://dzone.com/articles/what-archive-format-should-you-use-war-or-jar)
- 简要介绍：Java应用打war包还是打jar包？尤其是在Spring boot引领的新开发模式下。作者阐述了技术迭代的过程，以及各自的应用场景。目前没有找到类似的中文文章，值得翻译过来看看。

**Comment by sqrthree** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by sqrthree** [comment]
已添加在 #1824
