### ISSUE TITLE
WAR 还是 JAR，你应该用哪种格式打包？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1824]
* 原文链接：[What Archive Format Should You Use, WAR or JAR?](https://dzone.com/articles/what-archive-format-should-you-use-war-or-jar)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-archive-format-should-you-use-war-or-jar.md)
* PR 地址：#1839
* 文章分类：**后端**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by windmxf** [comment]
@sqrthree  翻译认领~

**Comment by sqrthree** [comment]
@windmxf 棒极啦 :tada:
