### ISSUE TITLE
React 在服务端渲染的实现

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1825]
* 原文链接：[Server-Side React Rendering](https://css-tricks.com/server-side-react-rendering/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/server-side-react-rendering.md)
* PR 地址：#1837
* 文章分类：**前端**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xx1124961758** [comment]
@sqrthree   我尝试下，可以吗

**Comment by sqrthree** [comment]
好哒~ @xx1124961758

**Comment by sqrthree** [comment]
@xx1124961758 抱歉这篇文章的推荐者 @MuYunyun 已经在翻译了，要不你看有没有其他感兴趣的文章翻译或者参与这篇文章的校对呢？今天还会有一些翻译任务要发布。

**Comment by MuYunyun** [comment]
@sqrthree 来认领下，不好意思了

**Comment by sqrthree** [comment]
ok
