### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by RichardLeeH** [xitu/gold-miner#1827]
- 公司/学校：vipkid/北京航空航天大学
- 工作内容/专业：iOS研发
- 常浏览的国外网站：https://www.raywenderlich.com https://www.clickz.com https://www.kaggle.com 
- 英语水平：cet-4
- 有无翻译经验：有
- 个人博客：http://blog.csdn.net/lihuinihao
- 个人介绍：

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
