### ISSUE TITLE
任何网站都可以成为渐进型网络应用 - 但我们需要做的更好

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1829]
* 原文链接：[Any web site can become a PWA – but we need to do better](https://christianheilmann.com/2017/06/27/any-web-site-can-become-a-pwa-but-we-need-to-do-better/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/any-web-site-can-become-a-pwa-but-we-need-to-do-better.md)
* PR 地址：#1850
* 文章分类：**前端**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：8 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wilsonandusa** [comment]
认领 @sqrthree

**Comment by sqrthree** [comment]
好的

**Comment by wilsonandusa** [comment]
@sqrthree 链接在此： https://juejin.im/post/5966bf2451882568b20dc2af
