### ISSUE TITLE
我们对数千个编程面试的分析结果

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1830]
* 原文链接：[We analyzed thousands of coding interviews. Here’s what we learned](https://medium.freecodecamp.org/we-analyzed-thousands-of-coding-interviews-heres-what-we-learned-99384b1fda50)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/we-analyzed-thousands-of-coding-interviews-heres-what-we-learned.md)
* PR 地址：#1887
* 文章分类：**编程**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：11 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
认领。

**Comment by sqrthree** [comment]
好的
