### ISSUE TITLE
UX 基于背后的合理化，而非设计

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1831]
* 原文链接：[UX is Grounded in Rationale, not Design](https://uxplanet.org/ux-is-grounded-in-rationale-not-design-49e8f77b8f58)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/ux-is-grounded-in-rationale-not-design.md)
* PR 地址：#1903
* 文章分类：**设计&产品**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by horizon13th** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
@horizon13th 棒极啦 :tada:
