### ISSUE TITLE
将 Kotlin 应用于现有 Java 代码的策略

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1832]
* 原文链接：[On Strategies to apply Kotlin to existing Java code](https://medium.com/@enriquelopezmanas/on-strategies-to-apply-kotlin-to-existing-java-code-6317974717ec)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/on-strategies-to-apply-kotlin-to-existing-java-code.md)
* PR 地址：#1849
* 文章分类：**Android**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Luolc** [comment]
认领

**Comment by sqrthree** [comment]
好的

**Comment by sqrthree** [comment]
PR 地址：#1849
