### ISSUE TITLE
语句，消息和归约器

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1833]
* 原文链接：[Statements, messages and reducers](https://www.cocoawithlove.com/blog/statements-messages-reducers.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/statements-messages-reducers.md)
* PR 地址：#1882
* 文章分类：**iOS**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：6 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhangqippp** [comment]
翻译认领

**Comment by sqrthree** [comment]
@zhangqippp 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#1901
