### ISSUE TITLE
Ultimate Guide to JSON Parsing With Swift 4

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1834]
* 原文链接：[Ultimate Guide to JSON Parsing With Swift 4](http://benscheirman.com/2017/06/ultimate-guide-to-json-parsing-with-swift-4/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/ultimate-guide-to-json-parsing-with-swift-4.md)
* PR 地址：待添加
* 文章分类：**iOS**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：10 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeepMissea** [comment]
收

**Comment by sqrthree** [comment]
不要『收』，要『 `认领翻译`、`申请翻译`、 `翻译认领`』哈哈哈
