### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by iOSleep** [xitu/gold-miner#1835]
- 公司/学校：智课教育
- 工作内容/专业：iOS 开发 / 加密算法实现
- 常浏览的国外网站：StackOverFlow, GitHub
- 英语水平：CET 4
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：没有梦想的人和咸鱼有什么分别, 不为开源做贡献的开发者和码农有什么区别.

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
