### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by hizoubin** [xitu/gold-miner#1836]
公司/学校：合肥工业大学
工作内容/专业：web前端开发
常浏览的国外网站：https://stackoverflow.com/  https://medium.com/
英语水平：cet-4
有无翻译经验：有
个人博客：hizoubin.github.io
个人介绍：大三在读,时间较多。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
