### ISSUE TITLE
你不需要基于 CSS Grid 的栅格布局系统

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1845]
* 原文链接：[You do not need a CSS Grid based Grid System](https://rachelandrew.co.uk/archives/2017/07/01/you-do-not-need-a-css-grid-based-grid-system)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/you-do-not-need-a-css-grid-based-grid-system.md)
* PR 地址：#1863
* 文章分类：**前端**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
@leviding 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#1863
