### ISSUE TITLE
你会给想学习机器学习的软件工程师提出什么建议？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1847]
* 原文链接：[What would be your advice to a software engineer who wants to learn machine learning?](https://www.quora.com/What-would-be-your-advice-to-a-software-engineer-who-wants-to-learn-machine-learning-3/answer/Alex-Smola-1)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/What-would-be-your-advice-to-a-software-engineer-who-wants-to-learn-machine-learning.md)
* PR 地址：#1861
* 文章分类：**AI**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：6 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wilsonandusa** [comment]
@sqrthree 认领

**Comment by lsvih** [comment]
认领翻译
@sqrthree

**Comment by sqrthree** [comment]
@lsvih 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#1861

**Comment by RichardLeeH** [comment]
@sqrthree 校对认领

**Comment by sqrthree** [comment]
@RichardLeeH 这篇文章已经有两位校对者了，你可以看看其他的哈。（PS：下次请到对应的 PR 下申请哈。）

**Comment by RichardLeeH** [comment]
@sqrthree 好的，我是看到群里有小伙伴说 AI 专业词汇太多不好弄，正好我也是学大数据的，机器学习方面的东西看的也多。哈哈
