### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by tonylua** [xitu/gold-miner#1848]
- 公司/学校：点评微生活(https://www.welcrm.com/)
- 工作内容/专业：前端开发
- 常浏览的国外网站：https://www.smashingmagazine.com/
- 英语水平：大学英语四级
- 有无翻译经验：有
- 个人博客：公众号fewelife
- 个人介绍：十余年前端开发经验和as3开发经历，习惯阅读英文文档，较好的语言组织能力

> 参考[该网址][link1]中mobx、nwjs、react几篇文章，都是从官网英文文档中总结成章：
[link1]: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzI0MDYzOTEyOA==&scene=124&#wechat_redirect

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
