### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by geniuslt** [xitu/gold-miner#1854]
- 公司/学校：成都品果科技有限公司/北京邮电大学
- 工作内容/专业：技术总监/计算机科学与技术
- 常浏览的国外网站：medium/udacity/github/stackoverflow/Android developer/iOS developer/
- 英语水平：CET6/一般听说读写
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：
早期在华为作为软件工程师进行了3年嵌入式研发工作，后来个人创业到加入新的创业公司持续进行了6年Android研发工作，主导过亿级App产品项目和研发管理工作，也经历过新产品从0到1过程，对研发、产品、项目和团队管理均有一定经验。技术栈方面偏向Android，C/C++时间比较久了需要补一下，iOS/前端正在学习中。

申请原因主要有下面两个原因：
1、在技术路线上对外分享与知识积累上做的不太好，进行文章翻译我觉得是促使自己进行有体系分享和积累的一个方法
2、长期做管理工作，在技术上面深度不足，进行文章翻译是一种有效提升自己技术学习的一种方式

**Comment by sqrthree** [comment]
Hi，欢迎大佬参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
