### ISSUE TITLE
从金属巨人到深度学习

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1855]
* 原文链接：[From Automatons to Deep Learning](https://medium.com/towards-data-science/from-automatons-to-deep-learning-388f7969be34)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/from-automatons-to-deep-learning.md)
* PR 地址：#1901
* 文章分类：**AI**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：8 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
@sqrthree 我来

**Comment by sqrthree** [comment]
好的，（PS：下次可以回复 '认领翻译'、'申请翻译'、'翻译认领'快速获得反馈啦。）

**Comment by XatMassacrE** [comment]
哦哦，自动化了，666
