### ISSUE TITLE
Scratch 平台的神经网络（R 语言）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1856]
* 原文链接：[Neural Networks from Scratch (in R)](https://medium.com/@iliakarmanov/neural-networks-from-scratch-in-r-dcf97867c238)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/neural-networks-from-scratch-in-r.md)
* PR 地址：#1867
* 文章分类：**AI**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：10 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CACppuccino** [comment]
@sqrthree 我来我来哈哈哈哈

**Comment by sqrthree** [comment]
好哒

**Comment by sqrthree** [comment]
PR 地址：#1867
