### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by RichardLeeH** [xitu/gold-miner#1857]
- 原文链接：https://www.analyticsvidhya.com/blog/2017/04/natural-language-processing-made-easy-using-spacy-%E2%80%8Bin-python/
- 简要介绍：使用Python 第三方库SpaCy-自然语言处理如此简单

**Comment by sqrthree** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by sqrthree** [comment]
感谢推荐，文章已发布在 #1858。
