### ISSUE TITLE
使用 Python+spaCy 进行简易自然语言处理

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1858]
* 原文链接：[Natural Language Processing Made Easy – using SpaCy (​in Python)](https://www.analyticsvidhya.com/blog/2017/04/natural-language-processing-made-easy-using-spacy-%E2%80%8Bin-python/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/natural-language-processing-made-easy-using-spacy-in-python.md)
* PR 地址：#1904
* 文章分类：**AI**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@sqrthree 认领翻译

上一篇明天上午完成

**Comment by sqrthree** [comment]
@lsvih 棒极啦 :tada:

**Comment by lsvih** [comment]
@sqrthree 抱歉抱歉，前段时间天天加班，把这个给忘了，延期了。。今天晚饭前一定给弄完！
