### ISSUE TITLE
2017 年了，这么多前端框架，你会怎样选择？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1859]
* 原文链接：[Choosing a frontend framework in 2017](https://medium.com/this-dot-labs/building-modern-web-applications-in-2017-791d2ef2e341)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/building-modern-web-applications-in-2017.md)
* PR 地址：#1885
* 文章分类：**前端**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：6 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
@leviding 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#1885
