### ISSUE TITLE
在使用过采样或欠采样处理类别不均衡的数据后，如何正确的做交叉验证？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1860]
* 原文链接：[DEALING WITH IMBALANCED DATA: UNDERSAMPLING, OVERSAMPLING AND PROPER CROSS-VALIDATION](http://www.marcoaltini.com/blog/dealing-with-imbalanced-data-undersampling-oversampling-and-proper-cross-validation)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/dealing-with-imbalanced-data-undersampling-oversampling-and-proper-cross-validation.md)
* PR 地址：#1909
* 文章分类：**AI**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：9 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by edvardHua** [comment]
翻译认领

**Comment by sqrthree** [comment]
@edvardHua 棒极啦 :tada:

**Comment by edvardHua** [comment]
校对认领啦
