### ISSUE TITLE
Redux 并不慢，只是你使用姿势不对 —— 一份优化指南

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1864]
* 原文链接：[Redux isn't slow, you're just doing it wrong - An optimization guide](http://reactrocket.com/post/react-redux-optimization/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/react-redux-optimization.md)
* PR 地址：#1897
* 文章分类：**前端**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by reid3290** [comment]
@sqrthree  认领翻译

**Comment by sqrthree** [comment]
@reid3290 棒极啦 :tada:

**Comment by reid3290** [comment]
@sqrthree  [已分享](https://juejin.im/post/596db2f9f265da6c4602ffc3)
