### ISSUE TITLE
在大型应用中使用 Redux 的五个技巧

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1865]
* 原文链接：[Five Tips for Working with Redux in Large Applications](https://techblog.appnexus.com/five-tips-for-working-with-redux-in-large-applications-89452af4fdcb)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/five-tips-for-working-with-redux-in-large-applications.md)
* PR 地址：#1933
* 文章分类：**前端**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：10 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by loveky** [comment]
@sqrthree  翻译认领

**Comment by sqrthree** [comment]
@loveky 棒极啦 :tada:

**Comment by loveky** [comment]
@sqrthree  你的状态是自动回复的吗。。秒回啊
