### ISSUE TITLE
如何处理机器学习中的不平衡类别

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1866]
* 原文链接：[How to Handle Imbalanced Classes in Machine Learning](https://elitedatascience.com/imbalanced-classes)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-handle-imbalanced-classes-in-machine-learning.md)
* PR 地址：#1870
* 文章分类：**AI**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：6 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by RichardLeeH** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@RichardLeeH 棒极啦 :tada:
