### ISSUE TITLE
如果你的产品停止成长，你该怎么做？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1871]
* 原文链接：[What To Do If Your Product Isn’t Growing](https://medium.com/initialized-capital/what-to-do-if-your-product-isnt-growing-7eb9d158fc)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-to-do-if-your-product-isnt-growing.md)
* PR 地址：#1978
* 文章分类：**设计&产品**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by swants** [comment]
翻译占坑  @sqrthree

**Comment by sqrthree** [comment]
好的

**Comment by sqrthree** [comment]
译者有一些特殊情况无法继续，资源释放。

**Comment by funtrip** [comment]
我来吧

**Comment by sqrthree** [comment]
@funtrip 好哒~ 特伦叔 V5
