### ISSUE TITLE
为企业应用设计更好的表格 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1872]
* 原文链接：[Designing better tables for enterprise applications](https://uxdesign.cc/designing-better-tables-for-enterprise-applications-f9ef545e9fbd)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/designing-better-tables-for-enterprise-applications.md)
* PR 地址：#1905
* 文章分类：**设计&产品**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：6 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by laiyun90** [comment]
申请翻译~ @sqrthree

**Comment by sqrthree** [comment]
@laiyun90 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#1905
