### ISSUE TITLE
原子设计：如何设计组件系统

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1873]
* 原文链接：[Atomic design: how to design systems of components](https://uxdesign.cc/atomic-design-how-to-design-systems-of-components-ab41f24f260e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/atomic-design-how-to-design-systems-of-components.md)
* PR 地址：#1913
* 文章分类：**前端**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：7 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by H2O-2** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
@H2O-2 棒极啦 :tada:

**Comment by H2O-2** [comment]
@sqrthree 这篇文章总体是在说设计原则的，是不是加上一个设计的标签比较好
