### ISSUE TITLE
即将到来的正则表达式新特性

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1874]
* 原文链接：[Upcoming Regular Expression Features](https://developers.google.com/web/updates/2017/07/upcoming-regexp-features)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/upcoming-regexp-features.md)
* PR 地址：#1883
* 文章分类：**前端**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
@sqrthree   翻译认领

**Comment by sqrthree** [comment]
@sunui 棒极啦 :tada:
