### ISSUE TITLE
GraphQL vs. REST

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1877]
* 原文链接：[GraphQL vs. REST](https://dev-blog.apollodata.com/graphql-vs-rest-5d425123e34b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/graphql-vs-rest.md)
* PR 地址：#1920
* 文章分类：**后端**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：7 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wilsonandusa** [comment]
@sqrthree 认领

**Comment by sqrthree** [comment]
好哒

**Comment by sqrthree** [comment]
PR 地址：#1920
