### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ToBeNumerOne** [xitu/gold-miner#1879]
- 学校：The George Washington University
- 专业：Computer Science
- 常浏览的国外网站：Medium、Stackoverflow等
- 英语水平：Good
- 有无翻译经验：有
- 个人博客：
- 个人介绍：毕业之后，目前从事前端开发工作，主要使用react相关的技术栈，angularjs以及vue也有所了解。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
