### ISSUE TITLE
申请成为译者 

### ISSUE THREAD

**Issue by mdluo** [xitu/gold-miner#188]
待业伪前端 / Ruby 爱好者，掘金早期用户、粉丝群第 24 号成员

贡献过一篇掘金热门：http://gold.xitu.io/#/entry/56d4f9be816dfa00593a9b84

博客地址：https://mdluo.github.io/

英语六级，有美国参加开源项目活动经历，理解英美文化

**Comment by antonia0912** [comment]
@mdluo 欢迎欢迎~请加我微信  我拉你进译者群~

**Comment by Glowin** [comment]
原来是东锅子同学，欢迎加入掘金翻译计划。
