### ISSUE TITLE
ES8 was Released and here are its Main New Features 🔥

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1880]
* 原文链接：[ES8 was Released and here are its Main New Features 🔥](https://hackernoon.com/es8-was-released-and-here-are-its-main-new-features-ee9c394adf66)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/es8-was-released-and-here-are-its-main-new-features.md)
* PR 地址：待添加
* 文章分类：**前端**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ToBeNumerOne** [comment]
认领翻译

**Comment by sqrthree** [comment]
@ToBeNumerOne 棒极啦 :tada:

**Comment by loveky** [comment]
坐等校对

**Comment by sqrthree** [comment]
[发现译文](https://zhuanlan.zhihu.com/p/27844393)

**Comment by sqrthree** [comment]
PR 地址：#1886
