### ISSUE TITLE
高性能 React：3 个新工具加速你的应用

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1888]
* 原文链接：[High Performance React: 3 New Tools to Speed Up Your Apps](https://medium.freecodecamp.org/make-react-fast-again-tools-and-techniques-for-speeding-up-your-react-app-7ad39d3c1b82)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/make-react-fast-again-tools-and-techniques-for-speeding-up-your-react-app.md)
* PR 地址：#1911
* 文章分类：**前端**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@sunui 棒极啦 :tada:
