### ISSUE TITLE
在css中使用特征查询

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1889]
* 原文链接：[Using Feature Queries in CSS](https://hacks.mozilla.org/2016/08/using-feature-queries-in-css/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/using-feature-queries-in-css.md)
* PR 地址：#1938
* 文章分类：**前端**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：8 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@sqrthree 翻译认领

**Comment by sunshine940326** [comment]
翻译认领

**Comment by sqrthree** [comment]
@sunshine940326 棒极啦 :tada:
