### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by dasunsy** [xitu/gold-miner#189]
hello, 我是一名Androider, 目前在广州恒拓, 喜欢稀土掘金里高质量的文章, 希望加入稀土翻译计划:)

**Comment by antonia0912** [comment]
请问之前有翻译过英文技术文章的相关经验吗？英语水平呢？ @dasunsy

**Comment by dasunsy** [comment]
在开源中国有翻译过技术文章, 常阅读英文文章,英语是 cet-6水平 @antonia0912

**Comment by antonia0912** [comment]
@dasunsy 好的 欢迎加入我们的译者群  你可以先加我微信 antonia0912  我拉你进群
