### ISSUE TITLE
构建渐进式 Web 应用入门指南 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1890]
* 原文链接：[A beginner’s guide to making Progressive Web Apps](https://medium.com/samsung-internet-dev/a-beginners-guide-to-making-progressive-web-apps-beb56224948e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-beginners-guide-to-making-progressive-web-apps.md)
* PR 地址：#1944
* 文章分类：**前端**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by AceLeeWinnie** [comment]
认领

**Comment by sqrthree** [comment]
好的

**Comment by sqrthree** [comment]
@AceLeeWinnie Hello，这篇进度如何了？

**Comment by AceLeeWinnie** [comment]
#1944
