### ISSUE TITLE
将现有的 API 从 REST 迁移到 GraphQL 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1891]
* 原文链接：[Moving existing API from REST to GraphQL](https://medium.com/@raxwunter/moving-existing-api-from-rest-to-graphql-205bab22c184)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/moving-existing-api-from-rest-to-graphql.md)
* PR 地址：#2002
* 文章分类：**后端**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zaraguo** [comment]
@sqrthree  翻译认领

**Comment by sqrthree** [comment]
@zaraguo 棒极啦 :tada:

**Comment by sqrthree** [comment]
@zaraguo Hello，这篇进度如何了呀？

**Comment by zaraguo** [comment]
@sqrthree 哎呀！我自己忘记了，我是罪人，我今晚赶出来
