### ISSUE TITLE
Swift 中的通用数据源

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1892]
* 原文链接：[Generic Data Sources in Swift](https://medium.com/capital-one-developers/generic-data-sources-in-swift-c6fbb531520e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/generic-data-sources-in-swift.md)
* PR 地址：#1965
* 文章分类：**iOS**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：9 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by swants** [comment]
翻译认领  上一篇不好实在意思  @sqrthree

**Comment by sqrthree** [comment]
@swants 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#1965
