### ISSUE TITLE
CSS 才不是什么黑魔法呢

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1893]
* 原文链接：[CSS Isn’t Black Magic](https://medium.freecodecamp.org/its-not-dark-magic-pulling-back-the-curtains-from-your-stylesheets-c8d677fa21b2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/its-not-dark-magic-pulling-back-the-curtains-from-your-stylesheets.md)
* PR 地址：#1946
* 文章分类：**前端**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：7 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xunge0613** [comment]
@sqrthree 翻译认领~ 很不错的一篇文章，会对初学者有不少帮助

**Comment by sqrthree** [comment]
好的

**Comment by Aladdin-ADD** [comment]
校对认领~

**Comment by sqrthree** [comment]
PR 地址：#1946
