### ISSUE TITLE
模块化 Swift 中的状态

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1894]
* 原文链接：[Modelling state in Swift](https://www.swiftbysundell.com/posts/modelling-state-in-swift)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/modelling-state-in-swift.md)
* PR 地址：#1906
* 文章分类：**iOS**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeepMissea** [comment]
认领翻译认领

**Comment by sqrthree** [comment]
@DeepMissea 棒极啦 :tada:
