### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by GreatV** [xitu/gold-miner#1895]
- 原文链接：[Qt versus Wx: How do two of the most popular Python frameworks compare?](https://opensource.com/article/17/4/pyqt-versus-wxpython)
- 简要介绍：比较了 PyQt 与 WxPython 两个图形框架的优缺点，并给出实现同一功能两种框架的代码。

**Comment by sqrthree** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by sqrthree** [comment]
已发布在 #1900
