### ISSUE TITLE
安卓界面导航初识

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1896]
* 原文链接：[A Primer on Android navigation](https://medium.com/google-design/a-primer-on-android-navigation-75e57d9d63fe)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-primer-on-android-navigation.md)
* PR 地址：#2005
* 文章分类：**设计&产品**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：8 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by horizon13th** [comment]
翻译认领

**Comment by sqrthree** [comment]
@horizon13th 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#2005
