### ISSUE TITLE
基于 TensorFlow 的上下文聊天机器人

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1898]
* 原文链接：[Contextual Chatbots with Tensorflow](https://chatbotsmagazine.com/contextual-chat-bots-with-tensorflow-4391749d0077)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/contextual-chat-bots-with-tensorflow.md)
* PR 地址：#1982
* 文章分类：**AI**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by edvardHua** [comment]
翻译认领

**Comment by sqrthree** [comment]
@edvardHua 棒极啦 :tada:

**Comment by edvardHua** [comment]
完成翻译，[pr在此](https://github.com/xitu/gold-miner/pull/1982)
