### ISSUE TITLE
如何将时间序列问题用 Python 转换成为监督学习问题

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1899]
* 原文链接：[How to Convert a Time Series to a Supervised Learning Problem in Python](http://machinelearningmastery.com/convert-time-series-supervised-learning-problem-python/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/convert-time-series-supervised-learning-problem-python.md)
* PR 地址：#1977
* 文章分类：**AI**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@sqrthree 认领翻译

**Comment by sqrthree** [comment]
好的，抱歉回复晚了。
