### ISSUE TITLE
Qt versus Wx: How do two of the most popular Python frameworks compare?

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1900]
* 原文链接：[Qt versus Wx: How do two of the most popular Python frameworks compare?](https://opensource.com/article/17/4/pyqt-versus-wxpython)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/pyqt-versus-wxpython.md)
* PR 地址：待添加
* 文章分类：**后端**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：7 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@lsvih 棒极啦 :tada:

**Comment by lsvih** [comment]
看来并不会自动移除 closing soon 的 label 嘛
