### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by MrShayne** [xitu/gold-miner#1902]
- 公司/学校：pp
- 工作内容/专业：Java开发
- 常浏览的国外网站：reddit
- 英语水平：六级500分，可进行
- 有无翻译经验：有初级翻译经验
- 个人博客：
- 个人介绍：喜欢新鲜事物，对开源事物感兴趣

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
