### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by terrykingcha** [xitu/gold-miner#1907]
- 原文链接：https://webkit.org/blog/7380/next-generation-3d-graphics-on-the-web/
- 简要介绍：Apple提出的新一代Web图形接口技术，此文介绍了新技术的API提案，以及相关的一些社区和知识拓展。

**Comment by sqrthree** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by sqrthree** [comment]
Posted on #1923
