### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zyziyun** [xitu/gold-miner#1908]
- 公司：美团网
- 工作内容/专业：前端开发工程师
- 常浏览的国外网站：https://developer.mozilla.org/en-US/docs/Web & https://github.com
- 英语水平：大学英语阅读水平
- 有无翻译经验：基本没有成熟的翻译过，但是经常自己看英文文章
- 个人博客：https://zyziyun.github.io/ （没写啥）
- 个人介绍：做前端开发3年，喜欢新技术，希望提高英语水平，认真负责有责任心；

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
