### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by wobegoone** [xitu/gold-miner#1916]
- 公司/学校：上海润和软件信息技术有限公司/上海电力学院
- 工作内容/专业：前端开发工程师/应用物理学
- 常浏览的国外网站：Hacknews
- 英语水平：CET-4
- 有无翻译经验：无
- 个人博客：http://blog.csdn.net/baoman_wu
- 个人介绍：2年的前端开发经验，热爱coding，英语水平一。但是希望能够加入掘金翻译计划，学习英文，增长知识

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
