### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by luisliuchao** [xitu/gold-miner#1917]
- 公司/学校：Smartkarma Innovations / Nanyang Technological University
- 工作内容/专业：Frontend Developer 
- 常浏览的国外网站：medium.com, github.com, youtube.com, stackoverflow.com, developer.mozilla.org 
- 英语水平：听说读写熟练
- 有无翻译经验：没有
- 个人博客：null
- 个人介绍：拥有三年的前端经验，对前端科技拥有浓厚的兴趣，关注前端的最新发展，希望将好的资源、内容传播给更多需要的人，引导中文科技社区的思想碰撞。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
