### ISSUE TITLE
Web 端的下一代三维图形

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1923]
* 原文链接：[Next-generation 3D Graphics on the Web](https://webkit.org/blog/7380/next-generation-3d-graphics-on-the-web/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/next-generation-3d-graphics-on-the-web.md)
* PR 地址：#1964
* 文章分类：**前端**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：7 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by reid3290** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@reid3290 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#1964
