### ISSUE TITLE
回顾 ESLint 的成功

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1924]
* 原文链接：[Reflections on ESLint's success](https://www.nczonline.net/blog/2016/02/reflections-on-eslints-success/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/reflections-on-eslints-success.md)
* PR 地址：#1932
* 文章分类：**前端**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：8 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sqrthree** [comment]
@Aladdin-ADD 来确认下哈。

**Comment by Aladdin-ADD** [comment]
翻译~

**Comment by sqrthree** [comment]
OK
