### ISSUE TITLE
Xcode 中的用户断点

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1925]
* 原文链接：[User Breakpoints in Xcode](https://pspdfkit.com/blog/2017/user-breakpoints-in-xcode/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/user-breakpoints-in-xcode.md)
* PR 地址：#1943
* 文章分类：**iOS**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by atuooo** [comment]
@sqrthree 认领

**Comment by sqrthree** [comment]
好的

**Comment by sqrthree** [comment]
PR 地址：#1943
