### ISSUE TITLE
深度学习系列1：设置 AWS & 图像识别

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1926]
* 原文链接：[Deep Learning #1: Setting up AWS & Image Recognition](https://medium.com/towards-data-science/deep-learning-1-1a7e7d9e3c07)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/deep-learning-1-setting-up-aws-image-recognition.md)
* PR 地址：#1967
* 文章分类：**AI**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：6 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lileizhenshuai** [comment]
@sqrthree  翻译认领

**Comment by sqrthree** [comment]
@lileizhenshuai 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#1967
