### ISSUE TITLE
深度学习系列2：卷积神经网络

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1927]
* 原文链接：[Deep Learning 2: Convolutional Neural Networks](https://medium.com/towards-data-science/deep-learning-2-f81ebe632d5c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/deep-learning-2-convolutional-neural-networks.md)
* PR 地址：#2010
* 文章分类：**AI**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@lsvih 棒极啦 :tada:

**Comment by sqrthree** [comment]
@lsvih Hello，这篇进度如何了？

**Comment by lsvih** [comment]
@sqrthree ....明天

**Comment by sqrthree** [comment]
PR 地址：#2010
