### ISSUE TITLE
深度学习系列3 - CNNs 以及应对过拟合的详细探讨

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1928]
* 原文链接：[Deep Learning-3-more-on-cnns-handling-overfitting](https://medium.com/towards-data-science/deep-learning-3-more-on-cnns-handling-overfitting-2bd5d99abe5d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/deep-learning-3-more-on-cnns-handling-overfitting.md)
* PR 地址：#2026
* 文章分类：**AI**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LJ147** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@LJ147 棒极啦 :tada:

**Comment by LJ147** [comment]
@sqrthree   翻译完成
