### ISSUE TITLE
论深度学习的局限性

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1929]
* 原文链接：[The limitations of deep learning](https://blog.keras.io/the-limitations-of-deep-learning.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-limitations-of-deep-learning.md)
* PR 地址：#1945
* 文章分类：**AI**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：7 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CACppuccino** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@CACppuccino 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#1945

**Comment by lileizhenshuai** [comment]
@sqrthree 校对认领
