### ISSUE TITLE
Building a Kotlin project - Part 1

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#193]
文章链接：[Building a Kotlin project 1/2](http://cirorizzo.net/2016/03/04/building-a-kotlin-project/)
掘金链接：[Building a Kotlin project - Part 1](http://gold.xitu.io/entry/56de4ed01532bc005621538a)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/building-a-kotlin-project.md)

校对 [PR 地址](https://github.com/xitu/gold-miner/pull/196/files?diff=split)

与 #194 一起翻译

翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by jingkecn** [comment]
認領這個的同時，是不是同時也要認領part 2？

**Comment by huanglizhuo** [comment]
认领

**Comment by antonia0912** [comment]
@jingkecn 好的  part 1 和 2  要一起翻译哈  辛苦啦

**Comment by antonia0912** [comment]
@huanglizhuo 要不等翻译完了来校对吧  可以吗

**Comment by jingkecn** [comment]
好的 @antonia0912

**Comment by huanglizhuo** [comment]
ok

**Comment by antonia0912** [comment]
@huanglizhuo part 1 已经翻译完了  在 #196 你可以去校对了  记得先在下边发 comment 校对认领

**Comment by huanglizhuo** [comment]
校对过了 ：）

**Comment by Sausure** [comment]
校对认领

**Comment by antonia0912** [comment]
@Sausure 好的

**Comment by antonia0912** [comment]
辛苦译者 @jingkecn 和两位校对者 @huanglizhuo @Sausure
