### ISSUE TITLE
深度学习的未来

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1930]
* 原文链接：[The future of deep learning](https://blog.keras.io/the-future-of-deep-learning.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-future-of-deep-learning.md)
* PR 地址：#1941
* 文章分类：**AI**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：9 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@changkun 棒极啦 :tada:
