### ISSUE TITLE
如何在 iOS 上实现类似 Airbnb 中的可展开式菜单

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1931]
* 原文链接：[How to implement expandable menu on iOS (like in Airbnb)](https://blog.uptech.team/how-to-implement-expandable-menu-on-ios-like-in-airbnb-3d2bdd97b049)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-implement-expandable-menu-on-ios-like-in-airbnb.md)
* PR 地址：#2089
* 文章分类：**iOS**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by RichardLeeH** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@RichardLeeH 棒极啦 :tada:

**Comment by iOSleep** [comment]
@sqrthree 校对认领

**Comment by puddingofzaoni** [comment]
亲，你好，我是CocoaChina开发者社区的编辑，请问您翻译的这篇文章可以授权转载到我们的公众号吗？我们会注明作者和出处的~非常感谢~

**Comment by leviding** [comment]
@puddingofzaoni 您好，我是掘金翻译计划的管理员，您如需转载可以加个好友聊下。加微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注相关信息。
