### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by loveky** [xitu/gold-miner#1934]
- 原文链接：https://www.dynatrace.com/blog/all-you-need-to-know-to-really-understand-the-node-js-event-loop-and-its-metrics/
- 简要介绍：帮你彻底理解 NodeJS 中的 Event Loop

**Comment by sqrthree** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by sqrthree** [comment]
已添加在 #1953
