### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by willchengusa** [xitu/gold-miner#1935]
- 公司/学校：旧金山艺术大学
- 工作内容/专业：网页设计&新媒体
- 常浏览的国外网站：awwwards , behance, medium 
- 英语水平：基本水平
- 有无翻译经验：无
- 个人博客：暂无
- 个人介绍：小硕一枚

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
