### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by MoutainOne** [xitu/gold-miner#1937]
- 公司/学校：北京科技大学/新浪微博feed研发部
- 工作内容/专业：参与新浪微博混合云项目的研发/物联网工程
- 常浏览的国外网站：github、stackoverflow、
- 英语水平：6级505
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：
北京科技大学大三学生，已保研本校，现在新浪微博feed研发部实习，参与微博混合云项目[opendcp](https://github.com/weibocom/opendcp)的研发,对docker和go非常感兴趣，平时也经常阅读相关的文章和博客，希望能参与go和docker相关的英文文献的翻译。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
