### ISSUE TITLE
Building a Kotlin project - Part 2

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#194]
文章链接：[Building a Kotlin project 2/2](http://www.cirorizzo.net/2016/03/04/building-a-kotlin-project-2/)
掘金链接：[Building a Kotlin project - Part 2](http://gold.xitu.io/entry/56de4f06da2f600055af4ec1)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/building-a-kotlin-project-2.md)

与 #193 一起翻译

翻译积分：5
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by huanglizhuo** [comment]
认领

**Comment by antonia0912** [comment]
@huanglizhuo sorry  你可以来校对  认领的话 part 1 和 2 要一起翻译

**Comment by DianaZhou** [comment]
校对认领

**Comment by jingkecn** [comment]
@DianaZhou 请前往 #218 校对第二部分？（如果你愿意的话o(^▽^)o）

**Comment by antonia0912** [comment]
@DianaZhou 好的 [校对地址](https://github.com/xitu/gold-miner/pull/218/files?diff=split)
