### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by undead25** [xitu/gold-miner#1940]
- 公司/学校：公司不透露，学校二本...
- 工作内容/专业：前端开发/英语
- 常浏览的国外网站：stackoverflow, twitter,  behance, 前端工程化涉及日常工作的各官方网站
- 英语水平：TEM8
- 有无翻译经验：有
- 个人博客：无
- 个人介绍：无

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
