### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by aaronCZ80** [xitu/gold-miner#1942]
- 公司/学校: 广东广州远东外贸外语学院
- 工作内容/专业：android/商务英语
- 常浏览的国外网站：gittub/stackoverflow
- 英语水平：公关英语中级
- 有无翻译经验：念书期间翻译过电影和电视剧
- 个人博客：
- 个人介绍：热爱编程的汉子

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
