### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Joursion** [xitu/gold-miner#1949]
- 公司/学校：多啦衣梦
- 工作内容/专业：Node.js服务端、React.js 后台
- 常浏览的国外网站：github.com, stackoverflow, 一些框架的英文文档
- 英语水平：CET-4
- 有无翻译经验：翻译过RabbitMQ的tutorials：https://joursion.gitbooks.io/rabbitmq-tutorials-zh/content/
- 个人博客：https://joursion.github.io/
- 个人介绍：刚入职场的新人

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
