### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by YESUNFEI** [xitu/gold-miner#1950]
- 公司/学校：杭州数梦工场／杭州电子科技大学
- 工作内容/专业：前端开发／信息安全
- 常浏览的国外网站：stackoverflow、awwwards 、 behance
- 英语水平：过了英语四级，平时喜欢看美剧，好莱坞电影
- 有无翻译经验：目前正在参加Cycle.js翻译计划
- 个人博客：只发表过几篇博客，算暂无吧
- 个人介绍：热爱编程的前端菜鸟

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
