### ISSUE TITLE
使用 `-force` 被认为是有害的；了解 Git 的 `-force-with-lease` 命令

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1951]
* 原文链接：[-force considered harmful; understanding git's --force-with-lease](https://developer.atlassian.com/blog/2015/04/force-with-lease/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/force-with-lease.md)
* PR 地址：#1980
* 文章分类：**不分类**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
翻译认领
@sqrthree

**Comment by sqrthree** [comment]
@leviding 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#1980
