### ISSUE TITLE
保护我们的 Git Repos，立刻停止“狐步舞”

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1952]
* 原文链接：[Protect our Git Repos, Stop Foxtrots Now!](https://developer.atlassian.com/blog/2016/04/stop-foxtrots-now/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/stop-foxtrots-now.md)
* PR 地址：#1974
* 文章分类：**不分类**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
翻译认领
@sqrthree

**Comment by sqrthree** [comment]
@leviding 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#1974
