### ISSUE TITLE
我们所需理解的 Node.js 事件循环及其度量

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1953]
* 原文链接：[All you need to know to really understand the Node.js Event Loop and its Metrics](https://www.dynatrace.com/blog/all-you-need-to-know-to-really-understand-the-node-js-event-loop-and-its-metrics/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/all-you-need-to-know-to-really-understand-the-node-js-event-loop-and-its-metrics.md)
* PR 地址：#1962
* 文章分类：**后端**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：6 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MuYunyun** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@MuYunyun 棒极啦 :tada:

**Comment by MuYunyun** [comment]
@sqrthree 这是机器人自动回复嘛~

**Comment by sqrthree** [comment]
哈哈哈哈( ⊙ o ⊙ )是
