### ISSUE TITLE
深度学习系列4: 为什么你需要使用嵌入层

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1954]
* 原文链接：[Deep Learning 4: Why You Need to Start Using Embedding Layers](https://medium.com/towards-data-science/deep-learning-4-embedding-layers-f9a02d55ac12)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/deep-learning-4-embedding-layers.md)
* PR 地址：#2018
* 文章分类：**AI**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lileizhenshuai** [comment]
@sqrthree  翻译认领

**Comment by sqrthree** [comment]
@lileizhenshuai 棒极啦 :tada:

**Comment by lileizhenshuai** [comment]
@sqrthree  翻译完成

**Comment by sqrthree** [comment]
@lileizhenshuai 小哥，你是不是也把 PR 发错了？

**Comment by sqrthree** [comment]
PR 地址：#2018
