### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by freerambo** [xitu/gold-miner#1955]
- 公司/学校：南洋理工大学
- 工作内容/专业：软件工程师
- 常浏览的国外网站：https://techcrunch.com, https://www.techinasia.com, stackoverflow.com 
- 英语水平：工作语言
- 有无翻译经验：有
- 个人博客：http://freerambo.com/
- 个人介绍：朱渊博，特普通一人，渊为深，博为广，一直努力做一个有深度有广度的人。南洋某技术学院创新与创业硕士，北洋某工学院计算机硕士. 多混迹于Github, Stackoverflow, ITeye, 知乎, Linkedin 等地带。蹉跎中练就了一身码农好本领。 酷爱编程，但绝不宅。爱生活，爱思考，性情温和但充满激情，做事有主见，信奉读万卷书行万里路。

**Comment by leviding** [comment]
个人简介有特色，好棒~\(≧▽≦)/~

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O

**Comment by freerambo** [comment]
@leviding 嗨 确实特别色， 交个朋友.看你也刷 freecamp, 握个抓。 wechat: rambolchina  来刷leetcode
