### ISSUE TITLE
结构体指针

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1957]
* 原文链接：[Struct References](http://chris.eidhof.nl/post/references/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/swift-struct-references.md)
* PR 地址：#2057
* 文章分类：**iOS**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by swants** [comment]
认领 @sqrthree

**Comment by sqrthree** [comment]
好的

**Comment by sqrthree** [comment]
PR 地址：#2054

**Comment by FlyOceanFish** [comment]
校对@sqrthree
