### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ethansure** [xitu/gold-miner#1960]
- 公司/学校：同济大学/ UC Irvine
- 工作内容/专业：CS
- 常浏览的国外网站：Medium
- 英语水平：Toefl 100
- 有无翻译经验：有
- 个人博客：ethansure.me
- 个人介绍：不浪漫也不GEEK的全干工程师

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
