### ISSUE TITLE
设计作品集网站的真正角色是什么？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1968]
* 原文链接：[What is the real role of a design portfolio website?](https://uxdesign.cc/what-is-the-real-role-of-a-design-portfolio-website-ee0b5b76112b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-is-the-real-role-of-a-design-portfolio-website.md)
* PR 地址：#1985
* 文章分类：**设计&产品**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by noturnot** [comment]
小白申请翻译（〜^㉨^)〜 @sqrthree

**Comment by sqrthree** [comment]
@noturnot 棒极啦 :tada:
