### ISSUE TITLE
将 Android 程序移植为 Kotlin 程序

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1969]
* 原文链接：[Migrating an Android project to Kotlin](https://medium.com/google-developers/migrating-an-android-project-to-kotlin-f93ecaa329b7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/migrating-an-android-project-to-kotlin.md)
* PR 地址：#2039
* 文章分类：**Android**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wilsonandusa** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
@wilsonandusa 棒极啦 :tada:
