### ISSUE TITLE
扩展 Node.js 应用

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1971]
* 原文链接：[Scaling Node.js Applications](https://medium.freecodecamp.org/scaling-node-js-applications-8492bd8afadc)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/scaling-node-js-applications.md)
* PR 地址：#2060
* 文章分类：**后端**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：12 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mnikn** [comment]
@sqrthree 翻译认领一个~

**Comment by sqrthree** [comment]
@mnikn 棒极啦 :tada:
