### ISSUE TITLE
iOS 响应式编程：Swift 中的轻量级状态容器

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1973]
* 原文链接：[Reactive iOS Programming: Lightweight State Containers in Swift](https://www.captechconsulting.com/blogs/state-containers-in-swift)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/state-containers-in-swift.md)
* PR 地址：#2013
* 文章分类：**iOS**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：6 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeepMissea** [comment]
翻译认领翻译

**Comment by sqrthree** [comment]
@DeepMissea 棒极啦 :tada:
