### ISSUE TITLE
Contextual chatbots with Tensorflow

### ISSUE THREAD

**Issue by shauravg** [xitu/gold-miner#1975]
Sorry I am not sure if this is the right place to post this. I followed your tutorial here:
https://github.com/xitu/gold-miner/blob/master/TODO/contextual-chat-bots-with-tensorflow.md

One question I have is how to better handle cases where the user input is nowhere close to any of the target intents. Right now, if I input even complete gibberish "lsdjkfjlkjsdf" I sometimes get a high score classification match to one of the intents (generally the one with the most patterns). Instead, I would like to detect that condition and then respond differently (maybe something like "we do not understand what you are saying. Please wait for a human").

**Comment by edvardHua** [comment]
Well, the post mainly illustrates how to design a goal-driven chat-bots. The response of chat-bot is based on the string matching the tag and pattern according to the user input. Therefore, I think maybe you can define the threshold of matching proportion to determine whether the input is valid or not and then output the proper response.
