### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Brucexz** [xitu/gold-miner#1979]
- 公司/学校：Xidian University
- 工作内容/专业：College student  Software Engineering
- 常浏览的国外网站：codeforce youtube cousera edx cnn 
- 英语水平：2/5000 in the english exam of school
- 有无翻译经验：some translation test and homework
- 个人博客：none
- 个人介绍： Eager to make contributions to the development of the technology,I find that taking part in the translation project can be a good way to reaching such purpose.

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O

**Comment by ziyanyan** [comment]
总算看到中文文字了~
