### ISSUE TITLE
What is Product Design?

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#198]
文章链接：[What is Product Design?](https://medium.com/intro-to-digital-product-design/lecture-1-what-is-product-design-c290bfe799a9#.7qqx6nj3k)
掘金链接：[What is Product Design?](http://gold.xitu.io/entry/56df931a7664bf0052c49a29)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/lecture-1-what-is-product-design.md)

翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zhangjd** [comment]
认领

**Comment by antonia0912** [comment]
文章没添加呢  等添加了你就可以直接翻译啦 @Zhangjd

**Comment by antonia0912** [comment]
@Zhangjd markdown 文件已经添加了 现在可以开始翻译咯

**Comment by Zhangjd** [comment]
好的

**Comment by hikerpig** [comment]
认领校对

**Comment by iThreeKing** [comment]
认领校对 @antonia0912

**Comment by antonia0912** [comment]
@hikerpig @iThreeKing 好的  可以去校对啦 校对地址 [PR](https://github.com/xitu/gold-miner/pull/219/files?diff=split)
