### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by LJ147** [xitu/gold-miner#1981]
- 公司/学校：武汉大学
- 工作内容/专业：软件工程
- 常浏览的国外网站：https://medium.com https://twitter.com
- 英语水平：6级
- 有无翻译经验：暂无
- 个人博客：http://www.jianshu.com/u/fc5814d052af
- 个人介绍：热爱英语，热爱编程，热爱开源，近期正在实验室学习深度学习中的视频跟踪技术，希望能加入掘金翻译计划！

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
