### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by JasinYip** [xitu/gold-miner#1983]
- 原文链接：https://staltz.com/unidirectional-user-interface-architectures.html
- 简要介绍：This post is a non-exhaustive quick overview of the so-called “unidirectional data flow” architectures. Not meant to be taken as a beginner tutorial, but rather as an overview of their differences and peculiarities. At the end, I’ll introduce a new architecture which deviates significantly from the others. This post assumes client-side Web UI frameworks only.

**Comment by sqrthree** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by sqrthree** [comment]
感谢鸡腿哥~

**Comment by sqrthree** [comment]
_(:з」∠)_ 发现[译文](https://github.com/rabbitlive/SoILikeElm/blob/master/unidirectional-user-interface-architectures.md)了。

**Comment by JasinYip** [comment]
> (:з」∠) 发现译文了。

手动尴尬……
