### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by sigoden** [xitu/gold-miner#1984]
公司/学校：初创/武汉理工大学
工作内容/专业：后端开发(nodejs)/信息与计算科学
常浏览的国外网站：twitter, stackoverflow, quora，youtube
英语水平：CET-6
有无翻译经验：有
个人博客：https://blog.sigoden.com
个人介绍：热爱开源，热爱分享！

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
