### ISSUE TITLE
REST API 已死，GraphQL 长存

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1986]
* 原文链接：[REST APIs are REST-in-Peace APIs. Long Live GraphQL](https://medium.freecodecamp.org/rest-apis-are-rest-in-peace-apis-long-live-graphql-d412e559d8e4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/rest-apis-are-rest-in-peace-apis-long-live-graphql.md)
* PR 地址：#2017
* 文章分类：**后端**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：12 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sigoden** [comment]
翻译认领

**Comment by sqrthree** [comment]
@sigoden 棒极啦 :tada:

**Comment by sigoden** [comment]
@sqrthree 翻译完成

**Comment by sqrthree** [comment]
@sigoden 你把 PR 发错了吧。

**Comment by sqrthree** [comment]
PR 地址：#2017
