### ISSUE TITLE
MVVM, Coordinators 和 RxSwift 的抽丝剥茧

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1989]
* 原文链接：[Taming Great Complexity: MVVM, Coordinators and RxSwift](https://blog.uptech.team/taming-great-complexity-mvvm-coordinators-and-rxswift-8daf8a76e7fd)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/taming-great-complexity-mvvm-coordinators-and-rxswift.md)
* PR 地址：#2136
* 文章分类：**iOS**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jingzhilehuakai** [comment]
@sqrthree 翻译认领

**Comment by fanyijihua** [comment]
@jingzhilehuakai 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2136
