### ISSUE TITLE
ARKit 为什么如此优秀？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1991]
* 原文链接：[Why is ARKit better than the alternatives?](https://medium.com/super-ventures-blog/why-is-arkit-better-than-the-alternatives-af8871889d6a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-is-arkit-better-than-the-alternatives.md)
* PR 地址：#2127
* 文章分类：**iOS**
----
* 翻译时间：14 天
* 校对时间：3 天
* 翻译积分：14 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LJ147** [comment]
@sqrthree  翻译认领

**Comment by sqrthree** [comment]
@LJ147 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2127
