### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by dzzxjl** [xitu/gold-miner#1993]
- 公司/学校：南京邮电大学
- 工作内容/专业：计算机应用技术
- 常浏览的国外网站：stackoverflow.com/google.com
- 英语水平：CET6
- 有无翻译经验：较少
- 个人博客：dzzxjl.github.io
- 个人介绍：希望能翻译一些好文章，让更多的人了解国外一些新的技术与思想

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
