### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Pines-Cheng** [xitu/gold-miner#1994]
公司/学校：中北大学
工作内容/专业：机械电子工程
常浏览的国外网站：stackoverflow.com/google.com/medium.com/
英语水平：CET4
有无翻译经验：有
个人博客：https://pines-cheng.github.io/blog/
个人介绍：前端工程师，React爱好者，希望能为社区贡献自己一份力量，结识一些爱好开源，翻译的同道中人。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
