### ISSUE TITLE
学习 React.js 比你想象的要简单

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1995]
* 原文链接：[Learning React.js is easier than you think](https://edgecoders.com/learning-react-js-is-easier-than-you-think-fbd6dc4d935a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/learning-react-js-is-easier-than-you-think.md)
* PR 地址：#2036
* 文章分类：**前端**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：11 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunshine940326** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@sunshine940326 棒极啦 :tada:

**Comment by MJingv** [comment]
@sqrthree 校对认领

**Comment by sqrthree** [comment]
@MJingv 这篇译者还没有翻译完呢，你可以保持关注或者先看看有没有其他感兴趣的哈。[文章列表](https://github.com/xitu/gold-miner/pulls?q=is%3Apr+is%3Aopen+label%3A%E6%A0%A1%E5%AF%B9%E8%AE%A4%E9%A2%86)

**Comment by sqrthree** [comment]
PR 地址：#2036
