### ISSUE TITLE
SQL 事务隔离实用指南

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1996]
* 原文链接：[Practical Guide to SQL Transaction Isolation](https://begriffs.com/posts/2017-08-01-practical-guide-sql-isolation.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/practical-guide-sql-isolation.md)
* PR 地址：#2134
* 文章分类：**后端**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：12 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sigoden** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sigoden 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2134
