### ISSUE TITLE
自定义 Babel 和 ESLint 插件是如何提高生产率与用户体验的

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1997]
* 原文链接：[How writing custom Babel & ESLint plugins can increase productivity & improve user experience](https://medium.com/@kentcdodds/how-writing-custom-babel-and-eslint-plugins-can-increase-your-productivity-and-improve-user-fd6dd8076e26)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-writing-custom-babel-and-eslint-plugins-can-increase-your-productivity-and-improve-user.md)
* PR 地址：#2025
* 文章分类：**前端**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by H2O-2** [comment]
@sqrthree 翻译认领~

**Comment by sqrthree** [comment]
@H2O-2 棒极啦 :tada:
