### ISSUE TITLE
函数式响应型编程（Functional Reactive Programming）入门指南

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#1998]
* 原文链接：[An Introduction to Functional Reactive Programming](http://blog.danlew.net/2017/07/27/an-introduction-to-functional-reactive-programming/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/an-introduction-to-functional-reactive-programming.md)
* PR 地址：#2056
* 文章分类：**Android**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：11 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by stormrabbit** [comment]
路过领翻译.
话说翻了翻 markdown 文件发现原文的图片基本都扑街了怎么破....
@sqrthree

**Comment by stormrabbit** [comment]
路过领翻译.
话说翻了翻 markdown 文件发现原文的图片基本都扑街了怎么破....
@sqrthree

**Comment by sqrthree** [comment]
@stormrabbit 图片地址已经修正了，可以开始翻译了。
