### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by FlyOceanFish** [xitu/gold-miner#1999]
- 公司/学校：圆通信息技术有限公司/上海商学院
- 工作内容/专业：iOS开发/电子商务
- 常浏览的国外网站：https://developer.apple.com/library/content/navigation/  https://www.raywenderlich.com https://www.objc.io http://nshipster.com https://stackoverflow.com
- 英语水平：英语六级
- 有无翻译经验：无
- 个人博客：http://www.jianshu.com/u/48277aa2055d
- 个人介绍：一个目前在搬砖的iOS开发者，英语阅读水平不错，经常浏览国外的技术文章。对RN、ReactiveCocoa这些热门技术比较感兴趣，目前也致力于研究学习这些新技术

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
