### ISSUE TITLE
申请翻译《通过 Electron 开发一个简单地桌面应用》

### ISSUE THREAD

**Issue by Zhangdroid** [xitu/gold-miner#2]
申请翻译[通过 Electron 开发一个简单地桌面应用](https://github.com/xitu/gold-miner/blob/master/TODO/creating-your-first-desktop.md) 
预计两天可以完成～

**Comment by Glowin** [comment]
少侠好眼光，给你添加到 README 里面咯。

**Comment by Zhangdroid** [comment]
翻译完成 #62

**Comment by Glowin** [comment]
好的，辛苦你啦。
