### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by shawnchenxmu** [xitu/gold-miner#2000]
- 公司/学校：厦门大学
- 工作内容/专业：目前从事前端开发实习岗位
- 常浏览的国外网站：https://www.infoq.com/， https://medium.com/
- 英语水平：CET6
- 有无翻译经验：无
- 个人博客：alloween.top
- 个人介绍：前端工作者，热爱新技术，关注前端发展方向，并热爱分享所发现的新事物，文艺型程序员，喜欢写写写

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
