### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by hikerpig** [xitu/gold-miner#2001]
- 原文链接： [Building an API Gateway using Node.js](https://blog.risingstack.com/building-an-api-gateway-using-nodejs/)
- 简介：介绍一些微服务的基本概念，以及简单的 Node.js 实现

**Comment by sqrthree** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by zhangchen91** [comment]
- 原文链接： [The 10 Unique Ways Slack Hacked Growth to Become a $4 Billion Company](https://blog.markgrowth.com/the-10-unique-ways-slack-hacked-growth-to-become-a-4-billion-company-2d7c50b4df25)
- 简介：介绍Slack这个估值40亿美金公司的10个做增长的独特方法

**Comment by sqrthree** [comment]
分别发布在 #2006 、#2007
