### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by lileizhenshuai** [xitu/gold-miner#2004]
- 原文链接：https://medium.com/@gk_/how-chat-bots-work-dfff656a35e2
- 简要介绍：比较通俗形象地讲解了聊天机器人的工作原理，涉及到了意图分类、神经网络等话题，和正在校对的那篇用TensorFlow做聊天机器人挺相关的，可以相互参考

**Comment by sqrthree** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by sqrthree** [comment]
已发布在 #2008
