### ISSUE TITLE
使用 Node.js 搭建一个 API 网关

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2006]
* 原文链接：[Building an API Gateway using Node.js](https://blog.risingstack.com/building-an-api-gateway-using-nodejs/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/building-an-api-gateway-using-nodejs.md)
  * PR 地址：#2042
  * 文章分类：**后端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MuYunyun** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@MuYunyun 棒极啦 :tada:
