### ISSUE TITLE
The 10 Unique Ways Slack Hacked Growth to Become a $4 Billion Company

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2007]
* 原文链接：[The 10 Unique Ways Slack Hacked Growth to Become a $4 Billion Company](https://blog.markgrowth.com/the-10-unique-ways-slack-hacked-growth-to-become-a-4-billion-company-2d7c50b4df25)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-10-unique-ways-slack-hacked-growth-to-become-a-4-billion-company.md)
  * PR 地址：待添加
  * 文章分类：**设计&产品**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by noturnot** [comment]
求认领~ @sqrthree

**Comment by sqrthree** [comment]
@noturnot OK

**Comment by noturnot** [comment]
抱歉，可能要拖一下下稿，最近都在外出(๑°3°๑)

**Comment by leviding** [comment]
@noturnot 进度怎么样啦~

**Comment by leviding** [comment]
@noturnot 进度怎么样啦~
