### ISSUE TITLE
机器之魂：聊天机器人是怎么工作的 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2008]
* 原文链接：[Soul of the Machine: How Chatbots Work](https://medium.com/@gk_/how-chat-bots-work-dfff656a35e2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-chat-bots-work.md)
  * PR 地址：#2011
  * 文章分类：**AI**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@lsvih 棒极啦 :tada:
