### ISSUE TITLE
在 Airbnb 使用机器学习预测房源的价值

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2009]
* 原文链接：[Using Machine Learning to Predict Value of Homes On Airbnb](https://medium.com/airbnb-engineering/using-machine-learning-to-predict-value-of-homes-on-airbnb-9272d3d4739d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/using-machine-learning-to-predict-value-of-homes-on-airbnb.md)
  * PR 地址：#2103
  * 文章分类：**AI**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@lsvih 棒极啦 :tada:

**Comment by sqrthree** [comment]
@lsvih Hello 这篇进度如何了呀？

**Comment by lsvih** [comment]
@sqrthree 忘了。。还有 2 个章节，明天传。。
