### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by helloworldzxy** [xitu/gold-miner#2012]
- 公司/学校：北京邮电大学
- 工作内容/专业：计算机技术
- 常浏览的国外网站：https://medium.com/,  https://stackoverflow.com/, https://www.quora.com/,  https://code.tutsplus.com/, https://tympanus.net/codrops/
- 英语水平：BEC Higher Certificate, CET-6 (589), TOEIC (890)
- 有无翻译经验：有
- 个人博客：https://helloworldzxy.github.io/
- 个人介绍：热爱英语和前端开发，乐于分享，善于表达。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
