### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by razertory** [xitu/gold-miner#2014]
* 公司／学校：湖南工业大学
* 工作内容／专业：后端相关的研发工作
* 常浏览的国外网站：[HackerRank](https://www.hackerrank.com/)
* 英语水平：CET-4
* 有无翻译经验：无
* 个人博客：无
* 个人介绍：后端研发，喜欢数据库，架构，算法，操作系统等技术类型；吉他指弹手

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
