### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by MJingv** [xitu/gold-miner#2015]
- 公司/学校：滴滴出行／中南大学
- 工作内容/专业：前端工程师／物联网工程
- 常浏览的国外网站：github／codepen ／大牛博客 
- 英语水平：一般
- 有无翻译经验：无
- 个人博客：https://github.com/MJingv
- 个人介绍：前端菜鸟一枚，喜欢学习新鲜知识，希望可以尝试翻译文章分享给大家

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
