### ISSUE TITLE
推荐优秀英文文章 深入浅出 Service workers

### ISSUE THREAD

**Issue by Glowin** [xitu/gold-miner#2016]
- 原文链接：[深入浅出 Service workers \- 文章 \- 掘金](https://juejin.im/entry/5987478c6fb9a03c3e38eeab/detail)
- 简要介绍：本文使用ember带你理解 Service workers 概念。

**Comment by sqrthree** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by sqrthree** [comment]
已发布在 #2019
