### ISSUE TITLE
理解 Service Workers

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2019]
* 原文链接：[Understanding Service Workers](http://blog.88mph.io/2017/07/28/understanding-service-workers/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/understanding-service-workers.md)
  * PR 地址：#2024
  * 文章分类：**前端**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zyziyun** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@zyziyun 棒极啦 :tada:

**Comment by zyziyun** [comment]
@sqrthree 翻译完成

**Comment by undead25** [comment]
@sqrthree 校对认领

**Comment by MJingv** [comment]
@sqrthree 校对认领

**Comment by sqrthree** [comment]
@MJingv 这篇已经有两位校对者在校对了，你可以看看有没有 [其他感兴趣的文章](https://github.com/xitu/gold-miner/issues?q=is%3Apr+is%3Aopen+label%3A%E6%A0%A1%E5%AF%B9%E8%AE%A4%E9%A2%86) 哈。
