### ISSUE TITLE
为什么我还没 Fix 你的 Issue

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2027]
* 原文链接：[Why I Haven’t Fixed Your Issue Yet](https://medium.com/@michlbrmly/why-i-havent-fixed-your-issue-yet-a24ab4bc0d55)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-i-havent-fixed-your-issue-yet.md)
  * PR 地址：#2050
  * 文章分类：**不分类**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
翻译认领
@sqrthree

**Comment by sqrthree** [comment]
@leviding 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2128
