### ISSUE TITLE
虚拟现实是如何改变用户体验的：从原型到设备的设计

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2028]
* 原文链接：[How VR Is Changing UX: From Prototyping To Device Design](https://uxplanet.org/how-vr-is-changing-ux-from-prototyping-to-device-design-a75e6b45e5f8)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-vr-is-changing-ux-from-prototyping-to-device-design.md)
  * PR 地址：#2028
  * 文章分类：**设计&产品**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by laiyun90** [comment]
翻译认领~

**Comment by sqrthree** [comment]
好的

**Comment by sqrthree** [comment]
PR 地址：#2053
