### ISSUE TITLE
UI vs UX: 到底有什么差别

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2029]
* 原文链接：[UI vs UX: What is the Difference?](https://www.sitepoint.com/ui-vs-ux-what-is-the-difference/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/ui-vs-ux-what-is-the-difference.md)
  * PR 地址：#2082
  * 文章分类：**设计&产品**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
@sqrthree 认领

**Comment by sqrthree** [comment]
好哒

**Comment by sqrthree** [comment]
PR 地址：#2082
