### ISSUE TITLE
JavaScript 二进制的 AST

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2031]
* 原文链接：[Towards a JavaScript Binary AST](https://yoric.github.io/post/binary-ast-newsletter-1/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/binary-ast-newsletter-1.md)
  * PR 地址：#2069
  * 文章分类：**前端**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunshine940326** [comment]
翻译认领

**Comment by sqrthree** [comment]
@sunshine940326 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#2069
