### ISSUE TITLE
别再使用图片轮播了

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2032]
* 原文链接：[Don’t Use Automatic Image Sliders or Carousels](https://conversionxl.com/dont-use-automatic-image-sliders-or-carousels/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/dont-use-automatic-image-sliders-or-carousels.md)
  * PR 地址：#2073
  * 文章分类：**设计&产品**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shawnchenxmu** [comment]
@sqrthree  翻译认领

**Comment by sqrthree** [comment]
@shawnchenxmu 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#2073
