### ISSUE TITLE
RxJava 中的错误处理

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2033]
* 原文链接：[Error handling in RxJava](https://rongi.github.io/kotlin-blog/rxjava/rx/2017/08/01/error-handling-in-rxjava.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/error-handling-in-rxjava.md)
  * PR 地址：#2101
  * 文章分类：**Android**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tmpbook** [comment]
@sqrthree 翻译认领，之前正好看了一篇类似的文章

**Comment by fanyijihua** [comment]
@tmpbook 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2101
