### ISSUE TITLE
关于 Node.js 的认证方面的教程（很可能）是有误的

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2034]
* 原文链接：[Your Node.js authentication tutorial is (probably) wrong](https://medium.com/@micaksica/your-node-js-authentication-tutorial-is-wrong-f1a3bf831a46)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/your-node-js-authentication-tutorial-is-wrong.md)
  * PR 地址：#2091
  * 文章分类：**后端**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MuYunyun** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@MuYunyun 棒极啦 :tada:
