### ISSUE TITLE
搭建账户系统

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2035]
* 原文链接：[Building account systems](https://blog.plan99.net/building-account-systems-f790bf5fdbe0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/building-account-systems.md)
  * PR 地址：#2140
  * 文章分类：**后端**
  ----
  * 翻译时间：10 天
  * 校对时间：2 天
  * 翻译积分：10 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shawnchenxmu** [comment]
翻译认领 @sqrthree

**Comment by sqrthree** [comment]
@shawnchenxmu 棒极啦 :tada:

**Comment by leviding** [comment]
@shawnchenxmu 进度怎么样了啊 :joy:

**Comment by shawnchenxmu** [comment]
已经大致翻译完了，先自己修改修改🙄

**Comment by leviding** [comment]
哈哈 :100:

**Comment by michaelia** [comment]
已经校对完了

**Comment by leviding** [comment]
@michaelia 微信私聊下。
