### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by KnightJoker** [xitu/gold-miner#2041]
- 公司/学校：无业
- 工作内容/专业：iOS开发
- 常浏览的国外网站：GitHub、StackOverFlow、LeetCode、iOS Developer 、Google
- 英语水平：CET-4
- 有无翻译经验：LCTT译者
- 个人博客：http://dbcxl.com/
- 个人介绍：比较喜欢接触一些新的技术，喜欢开源

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
