### ISSUE TITLE
AI 能解决你的 UX 设计问题吗？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2044]
* 原文链接：[Can AI Solve Your UX Design Problems?](https://www.sitepoint.com/artificial-intelligence-in-ux-design/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/artificial-intelligence-in-ux-design.md)
  * PR 地址：#2049
  * 文章分类：**设计**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
@sqrthree 翻译认领

试读了一下此文，觉得可以加上「产品」这个标签

**Comment by sqrthree** [comment]
@changkun 棒极啦 :tada:

**Comment by sqrthree** [comment]
好哒
