### ISSUE TITLE
为什么我们渴求女性来设计 AI

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2045]
* 原文链接：[Why we desperately need women to design AI](https://medium.freecodecamp.org/why-we-desperately-need-women-to-design-ai-72cb061051df)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-we-desperately-need-women-to-design-ai.md)
  * PR 地址：#2074
  * 文章分类：**AI**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lileizhenshuai** [comment]
@sqrthree  翻译认领

**Comment by sqrthree** [comment]
@lileizhenshuai 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#2074
