### ISSUE TITLE
关于 React Router 4 的一切

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2046]
* 原文链接：[All About React Router 4](https://css-tricks.com/react-router-4/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/all-about-react-router-4.md)
  * PR 地址：#2059
  * 文章分类：**前端**
  ----
  * 翻译时间：9 天
  * 校对时间：2 天
  * 翻译积分：9 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by undead25** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@undead25 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#2059

**Comment by MJingv** [comment]
@sqrthree 校对认领

**Comment by sqrthree** [comment]
@MJingv 这篇已经有两位校对者啦，你可以看看有没有别的感兴趣的哈。

**Comment by undead25** [comment]
@sqrthree 
这篇已经发布了哦。
https://juejin.im/post/5995a2506fb9a0249975a1a4
@sqrthree @sunui @LouisaNikita
