### ISSUE TITLE
SQL 指引：如何写出更好的查询

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2047]
* 原文链接：[SQL Tutorial: How To Write Better Queries](https://medium.com/towards-data-science/sql-tutorial-how-to-write-better-queries-108ae91d5f4e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/sql-tutorial-how-to-write-better-queries.md)
  * PR 地址：#2202
  * 文章分类：**后端**
  ----
  * 翻译时间：15 天
  * 校对时间：4 天
  * 翻译积分：15 分
  * 校对积分：4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zyziyun** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@zyziyun 棒极啦 :tada:

**Comment by leviding** [comment]
@zyziyun  :joy:

**Comment by sqrthree** [comment]
@leviding 经和 @zyziyun 沟通，表示没有时间继续完成了，需要更换译者。_(:з」∠)_

**Comment by tmpbook** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@tmpbook 棒极啦 :tada:

**Comment by xiaoyusilen** [comment]
能预约校对吗😂。

**Comment by tmpbook** [comment]
@xiaoyusilen 可以啊，翻译完at你

**Comment by xiaoyusilen** [comment]
👌妥妥的， @tmpbook

**Comment by fanyijihua** [comment]
PR 地址：#2202
