### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by lileizhenshuai** [xitu/gold-miner#2051]
- 原文链接：http://www.wildml.com/2016/01/attention-and-memory-in-deep-learning-and-nlp/
- 简要介绍：比较通俗地讲解了最近在 NLP 和 Deep Learning 领域比较热门的 Attention Mechanism，可以和前面深度学习系列配合作为参考

**Comment by sqrthree** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by sqrthree** [comment]
[存在翻译](http://blog.csdn.net/u010223750/article/details/51537656)
