### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by linesh-simplicity** [xitu/gold-miner#2052]
- 公司/学校：[ThoughtWorks][]
- 工作内容/专业：Java & JavaScript & React 
- 常浏览的国外网站：最近都是直接订阅大牛的 Github 和 Twitter
- 英语水平：CET-6
- 有无翻译经验：[Spring MVC 4.2.4.RELEASE 中文文档](https://github.com/linesh-simplicity/translation-spring-mvc-4-documentation) 译者
- 个人博客：https://github.com/linesh-simplicity/linesh-simplicity.github.io/issues

[ThoughtWorks]: https://www.thoughtworks.com/

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
