### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ChendayUP** [xitu/gold-miner#2055]
公司/学校：新梦创科
工作内容/专业：iOS
常浏览的国外网站：stackoverflow.com/google.com
英语水平：基本水平
有无翻译经验：较少,[Moya官方文档翻译](http://www.jianshu.com/p/c4b57ce13a56)
个人博客：[http://www.jianshu.com/u/1423d543a51b](http://www.jianshu.com/u/1423d543a51b)

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
