### ISSUE TITLE
在网站 Logo 上右击时提示下载网站的 Logo 素材下载

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#206]
文章链接：[Right Click Logo to Show Logo Download Options](https://css-tricks.com/right-click-logo-show-logo-download-options/)
掘金链接：[在网站 Logo 上右击时提示下载网站的 Logo 素材下载](http://gold.xitu.io/entry/56e90af3a3413100548517e7)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/right-click-logo-show-logo-download-options.md)

翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by rainyear** [comment]
好短，抢认领！

**Comment by antonia0912** [comment]
@rainyear ok

**Comment by rainyear** [comment]
@antonia0912 已提交，https://github.com/xitu/gold-miner/pull/217

**Comment by circlelove** [comment]
认认

**Comment by ZhaofengWu** [comment]
认领校对

**Comment by ZhaofengWu** [comment]
校对完毕

**Comment by antonia0912** [comment]
@circlelove @ZhaofengWu 好的 [校对地址](https://github.com/xitu/gold-miner/pull/217/files?diff=split)

**Comment by circlelove** [comment]
看完了~ @antonia0912
