### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by lampui** [xitu/gold-miner#2062]
- 学校：广州大学华软软件学院
- 专业：软件工程
- 常浏览的国外网站：medium.com, hackernoon.com
- 英语水平：尚可
- 有无翻译经验：有
- 个人博客：https://lampui.github.io
- 个人介绍：想成为稀土的一位矿工

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
