### ISSUE TITLE
V8: Behind the Scenes

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2063]
* 原文链接：[V8: Behind the Scenes](http://benediktmeurer.de/2016/11/25/v8-behind-the-scenes-november-edition/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/v8-behind-the-scenes-november-edition.md)
  * PR 地址：#2143
  * 文章分类：**前端**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by H2O-2** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@H2O-2 棒极啦 :tada:

**Comment by sqrthree** [comment]
和译者沟通之后，需要新译者进行翻译。

**Comment by thisisandy** [comment]
@sqrthree  翻译认领

**Comment by fanyijihua** [comment]
@thisisandy 棒极啦 :tada:

**Comment by leviding** [comment]
@thisisandy 别忘啦翻译啦 :kissing_heart:
