### ISSUE TITLE
我是如何在谷歌做开发者的用户体验的

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2064]
* 原文链接：[How I do Developer UX at Google](https://medium.com/google-design/how-i-do-developer-ux-at-google-b21646c2c4df)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-i-do-developer-ux-at-google.md)
  * PR 地址：#2099
  * 文章分类：**设计&产品**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by laiyun90** [comment]
翻译认领~~

**Comment by sqrthree** [comment]
@laiyun90 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2099
