### ISSUE TITLE
怎么写出完美的错误消息

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2065]
* 原文链接：[How to Write a Perfect Error Message](https://uxplanet.org/how-to-write-a-perfect-error-message-da1ca65a8f36)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-write-a-perfect-error-message.md)
  * PR 地址：#2080
  * 文章分类：**设计&产品**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunshine940326** [comment]
翻译认领

**Comment by sqrthree** [comment]
@sunshine940326 棒极啦 :tada:

**Comment by sqrthree** [comment]
PR 地址：#2077

**Comment by sqrthree** [comment]
PR 地址：#2078

**Comment by sqrthree** [comment]
PR 地址：#2080
