### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by isiyin** [xitu/gold-miner#2068]
- 公司/学校： SCUT
- 工作内容/专业：软件工程
- 常浏览的国外网站：GitHub, StackOverFlow, Quora, Android Weekly, Android  Blog
- 英语水平：CET6
- 有无翻译经验：有，android-tech-frontier 翻译组成员
- 个人介绍：一名喜爱开源社区的 Android 开发者，进击的全栈工程师

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
