### ISSUE TITLE
掀起 Swift 的 Futures & Promises 的红盖头

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2070]
* 原文链接：[Under the hood of Futures & Promises in Swift](https://www.swiftbysundell.com/posts/under-the-hood-of-futures-and-promises-in-swift)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/under-the-hood-of-futures-and-promises-in-swift.md)
  * PR 地址：#2128
  * 文章分类：**iOS**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by atuooo** [comment]
@sqrthree 认领

**Comment by sqrthree** [comment]
好的

**Comment by leviding** [comment]
@atuooo 进度怎么样啦:no_mouth:

**Comment by atuooo** [comment]
@leviding  已经翻译完啦，等校对啊

**Comment by leviding** [comment]
啊哈哈哈，我的锅，看错了 :flushed: 大老原谅

**Comment by sqrthree** [comment]
已更新

**Comment by sqrthree** [comment]
PR 的对应 resolve 写错了，导致匹配错了，已经更正了。
