### ISSUE TITLE
网络字体：什么时候需要，什么时候不需要

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2071]
* 原文链接：[Web fonts: when you need them, when you don’t](https://hackernoon.com/web-fonts-when-you-need-them-when-you-dont-a3b4b39fe0ae)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/web-fonts-when-you-need-them-when-you-dont.md)
  * PR 地址：#2109
  * 文章分类：**前端**
  ----
  * 翻译时间：12 天
  * 校对时间：2 天
  * 翻译积分：12 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by undead25** [comment]
@sqrthree 翻译认领

**Comment by sqrthree** [comment]
@undead25 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2109
