### ISSUE TITLE
如何在 webpack2 中使用 tree-shaking

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2075]
* 原文链接：[How to do proper tree-shaking in Webpack 2](https://blog.craftlab.hu/how-to-do-proper-tree-shaking-in-webpack-2-e27852af8b21)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-do-proper-tree-shaking-in-webpack-2.md)
  * PR 地址：#2076
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Aladdin-ADD** [comment]
翻译认领。

**Comment by sqrthree** [comment]
@Aladdin-ADD 棒极啦 :tada:
