### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by toypipi** [xitu/gold-miner#2079]
- 公司/学校：格力电器股份有限公司
- 工作内容/专业：程序员
- 常浏览的国外网站：google
- 英语水平：CET-6
- 有无翻译经验：有，参见https://coyee.com/网同名账户
- 个人博客：https://toypipi.github.io/
- 个人介绍：爱英语，爱编程，爱美食，爱读书，爱电影，爱运动，爱喵咪，爱狗子……

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
