### ISSUE TITLE
申请参与翻译

### ISSUE THREAD

**Issue by Jonwei** [xitu/gold-miner#208]

**Comment by Glowin** [comment]
你好，麻烦你做一下自我介绍以及过往的翻译经历，方便大家更好的认识你，谢谢

**Comment by Jonwei** [comment]
翻译新人。
曾经参与翻译过Ranorex使用文档。
[这是自己翻译Ranorex文档的保留稿](https://www.douban.com/note/264836204/)

**Comment by antonia0912** [comment]
@Jonwei 请加我微信  antonia0912  我来拉你进译者群

**Comment by Jonwei** [comment]
已加入。Closed.
