### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by tmpbook** [xitu/gold-miner#2081]
- 公司/学校：西北大学（中国）
- 工作内容/专业：后台开发/软件工程
- 常浏览的国外网站：Quora，Twitch 等，大量 manual
- 英语水平：CET - 4
- 有无翻译经验：暂无
- 个人博客：https://zhuanlan.zhihu.com/heart-devops
- 个人介绍：UCloud实验室 后台开发，着急了也自己写前端（VueJS），有点轻度的代码洁癖

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
