### ISSUE TITLE
翻译计划管理员公开招募

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2083]
Hello，各位译者们，光阴荏苒，日月如梭，转眼间翻译计划成立已经接近两年了。这两年来我们取得了一些成就，翻译了 600 多篇文章以及很多优秀的项目。我们项目的每一颗星星都离不开每一位译者的辛苦和贡献。翻译计划和掘金团队在此非常感谢你的奉献。

伴随着翻译计划译者队伍越来越壮大，产出新文章速度也愈来愈快，我们也需要更多的译者和成员一起来协作管理和运营翻译计划。因此经过讨论，翻译计划决定要开疆扩土、广纳贤士啦。

我们的计划目前是这样的：

- 成立翻译计划管理组，负责商讨和探索翻译计划的各种事项。
- 针对目前已有分类建立不同的 team，负责该分类下译文的质量把控。
- 每位成员至少加入一个分类下的 team，每个 team 下有 1 ~ 2 位成员。
- 每篇译文（PR）在 merge 之前至少需要一个该分类下的 team 成员进行 approve。
- 把控英文源文章质量。

我们期望你是这样的：

- 在翻译计划翻译过 2 篇以上文章，熟悉我们的流程。
- 对 GitHub 的使用非常熟悉。
- 英文水平非常好，能够负责把控译文的质量。
- 有一定的空闲时间，能及时的处理翻译计划的事项。

目前 Team 成员如下：

| 分类 | 管理员 |
| - | - |
| AI  | @reid3290 @changkun @TobiasLee |
| Android | @phxnirvana @tanglie1993 |
| iOS | @Danny1451 |
| 前端 | @Aladdin-ADD @undead25 |
| 后端 | @tmpbook |
| 设计 | |

如果你对我们翻译计划很感兴趣，同时又想参与社区协作的话，欢迎一起来将翻译计划做的更好啦。选择你擅长的分类，然后在下面留言即可。

如果你有任何建议或是意见，欢迎告诉我们。

**Comment by phxnirvana** [comment]
==我来打酱油
另外前端的管理员有一种钦定的感觉啊

**Comment by sqrthree** [comment]
@phxnirvana  _(:з」∠)_ 我本职工作也是前端开发啦，并且每个分类也不是只限定一个的。

**Comment by undead25** [comment]
我支持 sqrthree @sqrthree
前端。

**Comment by ataboyOrz** [comment]
支持！ 前端

**Comment by Aladdin-ADD** [comment]
来报个名，前端~~

**Comment by ArrayBuffer** [comment]
报个名 前端

**Comment by gostfather** [comment]
前端报名！

**Comment by reid3290** [comment]
报个名，AI

**Comment by liuixun** [comment]
后端，报名学习中，请多多指教

**Comment by changkun** [comment]
报个名: AI, 设计

**Comment by kinfie** [comment]
报名：Android

**Comment by LJade** [comment]
前端...在这

**Comment by hexianzhi** [comment]
前端报名咯...

**Comment by lileizhenshuai** [comment]
报名，AI

**Comment by tanglie1993** [comment]
报名Android

**Comment by gong12339** [comment]
报名，前端

**Comment by leviding** [comment]
前端，报名。

**Comment by swants** [comment]
iOS 报名

**Comment by Liu-Young** [comment]
报名，前端

**Comment by TanNingMeng** [comment]
报名 后端

**Comment by Miss-violet** [comment]
报名 前端

**Comment by YogiAi** [comment]
报名 Android

**Comment by xingqiwu55555** [comment]
报名 前端

**Comment by boileryao** [comment]
报名~ Android

**Comment by mnikn** [comment]
报个名，后端～～

**Comment by Danny1451** [comment]
报个名 iOS

**Comment by zhangchao** [comment]
报个名后端

**Comment by tmpbook** [comment]
报名后端

**Comment by MAYDAY1993** [comment]
报名前端

**Comment by Tina92** [comment]
报名前端

**Comment by edsum** [comment]
报名iOS @Danny1451  掘金主页：https://juejin.im/user/591facd1da2f60005d3a3fb8

**Comment by Jackieliu789** [comment]
报名后端和Android

**Comment by JohnJiangLA** [comment]
报名，后端
