### ISSUE TITLE
Understanding V8’s Bytecode

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2084]
* 原文链接：[Understanding V8’s Bytecode](https://medium.com/dailyjs/understanding-v8s-bytecode-317d46c94775)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/understanding-v8s-bytecode.md)
  * PR 地址：待添加
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lampui** [comment]
@sqrthree 认领翻译

**Comment by fanyijihua** [comment]
@lampui 棒极啦 :tada:
