### ISSUE TITLE
为什么 context.Value 重要，如何改进

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2085]
* 原文链接：[Why context.Value matters and how to improve it](https://blog.merovius.de/2017/08/14/why-context-value-matters-and-how-to-improve-it.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-context-value-matters-and-how-to-improve-it.md)
  * PR 地址：#2129
  * 文章分类：**后端**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tmpbook** [comment]
@sqrthree 翻译认领

**Comment by fanyijihua** [comment]
@tmpbook 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2129
