### ISSUE TITLE
优化 Facebook 新鲜事，使其为您提供更好的服务

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2086]
* 原文链接：[Evolving the Facebook News Feed to Serve You Better](https://medium.com/facebook-design/evolving-the-facebook-news-feed-to-serve-you-better-f844a5cb903d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/evolving-the-facebook-news-feed-to-serve-you-better.md)
  * PR 地址：#2116
  * 文章分类：**设计&产品**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by laiyun90** [comment]
@sqrthree 翻译认领~

**Comment by fanyijihua** [comment]
@laiyun90 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2116
