### ISSUE TITLE
Angular 与 React：谁更适合前端开发

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2087]
* 原文链接：[Angular vs. React: Which Is Better for Web Development?](https://codeburst.io/angular-vs-react-which-is-better-for-web-development-e0dd1fefab5b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/angular-vs-react-which-is-better-for-web-development.md)
  * PR 地址：#2135
  * 文章分类：**前端**
  ----
  * 翻译时间：13 天
  * 校对时间：3 天
  * 翻译积分：13 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by stormrabbit** [comment]
领翻译，请叫我勤劳的小蜜蜂。
@sqrthree

**Comment by sqrthree** [comment]
好哒

**Comment by leviding** [comment]
@stormrabbit 进度怎么样啦:no_mouth:

**Comment by sqrthree** [comment]
@leviding 翻译完了，PR 在 #2135。PR 的内容里没有写 resolve，所以没有触发机器人。

**Comment by leviding** [comment]
收到
