### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by jingzhilehuakai** [xitu/gold-miner#2088]
- 公司/学校：139 邮箱
- 工作内容/专业：程序员 & 计算机科学与技术
- 常浏览的国外网站：github 
- 英语水平：四级
- 有无翻译经验：个人博客有翻译
- 个人博客： http://jingzhilehuakai.com
- 个人介绍：非典型程序媛。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
