### ISSUE TITLE
设计一款移动应用前你应该知道这些事情

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#209]
文章链接：[the basics of designing mobile apps](http://www.designyourway.net/blog/inspiration/the-basics-of-designing-mobile-apps/)
掘金链接：[设计一款移动应用前你应该知道这些事情](http://gold.xitu.io/entry/56e91b81731956005c0fa25d)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/the-basics-of-designing-mobile-apps.md)

翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by shenxn** [comment]
认领！哈哈哈哈哈哈哈我又抢到了！！！

**Comment by antonia0912** [comment]
@shenxn 小朋友手蛮快的哈~

**Comment by ZhaofengWu** [comment]
认领校对！

**Comment by markzhai** [comment]
认领校对！

**Comment by markzhai** [comment]
我校对好了

**Comment by ZhaofengWu** [comment]
校对完成

**Comment by antonia0912** [comment]
@markzhai @ZhaofengWu 辛苦两位校对者啦
