### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Calinas** [xitu/gold-miner#2090]
- 公司/学校：商界传媒
- 工作内容/专业：web前端开发
- 常浏览的国外网站: youtube, https://css-tricks.com/
- 英语水平：六级
- 有无翻译经验：有
- 个人博客：www.webfront.online
- 个人介绍：希望加入掘金翻译计划锻炼自己

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
