### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by xingqiwu55555** [xitu/gold-miner#2092]
- 公司/学校：成都东软学院
- 工作内容/专业：软件工程
- 常浏览的国外网站：经济学人
- 英语水平：cet4
- 有无翻译经验：有
- 个人博客：无
- 个人介绍：我是一只勤劳的小蜜蜂

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
