### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by thisisandy** [xitu/gold-miner#2093]
- 公司/学校： 新东方教育培训集团
- 工作内容/专业：前端开发
- 常浏览的国外网站： 经济学人， BBC， 油管，FT
- 英语水平：BEC-Advanced
- 有无翻译经验：有
- 个人博客：https://thisisandy.github.io/YouthLegacy/
- 个人介绍：本科就读国际新闻专业，有口译笔译经验

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
