### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by LynnShaw** [xitu/gold-miner#2096]
公司/学校：电子科技大学
工作内容/专业：后台开发，机器学习
常浏览的国外网站：github，youtube，quora
英语水平：六级
有无翻译经验：在伯乐在线翻译十余篇
个人博客：无

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
