### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by TanNingMeng** [xitu/gold-miner#2097]
- 公司/学校：广东科学技术职业学院
- 工作内容/专业：软件技术
- 常浏览的国外网站：google  stackflow(偶尔)和油管(偶尔)
- 英语水平：cet4
- 有无翻译经验：无
- 个人博客：有,不过因为服务器没续费所以停用了
- 个人介绍：加入翻译计划不仅提高一下技术水平，也可以提高一下英语水平。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
