### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Shelly-xlb** [xitu/gold-miner#2098]
- 公司/学校：杭州微著网络有限公司
- 工作内容/专业：web前端开发（实习）
- 常浏览的国外网站：github
- 英语水平：六级
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：希望可以通过翻译一些文章，提高自己的技术水平，同时提升英文水平。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
