### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Jocs** [xitu/gold-miner#2102]
- 公司/学校：饿了么/北京师范大学
- 工作内容/专业：前端工程师/生物科学
- 常浏览的国外网站：[Lin Clark](https://hacks.mozilla.org/author/lclarkmozilla-com/)
- 英语水平：商务英语、CET-4
- 有无翻译经验：有
- 个人博客：[blogs](https://github.com/Jocs/jocs.github.io/issues)
- 个人介绍：饿了么前端工程师，平时在阅读一些英文技术文献的时候，喜欢通过将其翻译成中文来加深自己的理解。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
