### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Rachel-chen** [xitu/gold-miner#2104]
- 公司/学校：河北建筑工程学院
- 工作内容/专业：计算机科学与技术
- 常浏览的国外网站：https://news.ycombinator.com/；http://www.reddit.com/；https://medium.com/；http://www.smashingmagazine.com/等
- 英语水平：四级
- 有无翻译经验：有一定的经验
- 个人博客：https://github.com/Rachel-chen/blog
- 个人介绍：前端技术爱好者，经常在国外技术网站上溜达，时不时翻译自己感兴趣的技术文章。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
