### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by angilent** [xitu/gold-miner#2105]
- 公司/学校： 神州数码
- 工作内容/专业： 网站开发运营
- 常浏览的国外网站： 各类技术相关网站
- 英语水平： 6 级
- 有无翻译经验： 有
- 个人博客：无
- 个人介绍： 关注云计算，网站开发运营的各个方面。

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
