### ISSUE TITLE
CSS 的十六进制颜色揭秘

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2106]
* 原文链接：[CSS Hex Colors Demystified](https://medium.com/dev-channel/css-hex-colors-demystified-51c712179982)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/css-hex-colors-demystified.md)
  * PR 地址：#2157
  * 文章分类：**前端**
  ----
  * 翻译时间：13 天
  * 校对时间：3 天
  * 翻译积分：13 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunshine940326** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sunshine940326 棒极啦 :tada:
