### ISSUE TITLE
Web 设计准则

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2107]
* 原文链接：[Do’s and Don’ts of Web Design](https://uxplanet.org/dos-and-don-ts-of-web-design-8c9d6a5de7c6)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/dos-and-don-ts-of-web-design.md)
  * PR 地址：#2200
  * 文章分类：**设计&产品**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xunge0613** [comment]
翻译认领 @sqrthree

**Comment by fanyijihua** [comment]
@xunge0613 棒极啦 :tada:

**Comment by leviding** [comment]
@xunge0613 进度怎么样啦:no_mouth:

**Comment by xunge0613** [comment]
=。= 翻译了一半左右…… 大佬，我会加速加速加速的 =。=

**Comment by leviding** [comment]
打捞辛苦，按你的节奏来。

**Comment by fanyijihua** [comment]
PR 地址：#2200

**Comment by HydeSong** [comment]
@xunge0613 @fanyijihua 译者来查看了么

**Comment by leviding** [comment]
@HydeSong 还没，我艾特了。
