### ISSUE TITLE
使用 AI 为 Web 网页增加无障碍功能

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2108]
* 原文链接：[Making the Web More Accessible With AI](https://hackernoon.com/making-the-web-more-accessible-with-ai-1fb2ed6ea2a4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/making-the-web-more-accessible-with-ai.md)
  * PR 地址：#2113
  * 文章分类：**AI**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@sqrthree 翻译认领

立个 flag，今晚搞定

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2113
