### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by rockzhai** [xitu/gold-miner#211]
你好，我是来自重庆邮电大学通信与信息工程学院的学生，正在学习Android开发的道路上努力奔跑奔跑(●ˇ∀ˇ●)……

大一开始接触编程，对PHP和WEB前端也有过些许涉猎，最近在稀土掘金上读到了很多优秀的文章，希望自己可以为我们的翻译计划出一份力(～￣▽￣)～*。

个人博客：http://imzhai.com/

**Comment by antonia0912** [comment]
@rockzhai 请问英语水平怎么样  之前有翻译过类似的英文文章吗  可以先加我微信  antonia0912

**Comment by rockzhai** [comment]
@antonia0912 之前没有翻译过类似的英文文章呢，英语只去考了CET4……六级还没去考过（囧） 微信已加~
