### ISSUE TITLE
你的站点如你所想的移动友好吗？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2110]
* 原文链接：[Is your site as mobile friendly as you think?](https://boagworld.com/mobile-web/mobile-friendly/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/mobile-friendly.md)
  * PR 地址：#2146
  * 文章分类：**设计&产品**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by laiyun90** [comment]
翻译认领~

**Comment by fanyijihua** [comment]
@laiyun90 棒极啦 :tada:

**Comment by leviding** [comment]
@laiyun90  别忘啦来哟 :no_mouth:

**Comment by laiyun90** [comment]
sorry 这两天有点点忙 请求稍微拖延两天 @leviding

**Comment by leviding** [comment]
(๑‾ ꇴ ‾๑) 好哒 :blush:

**Comment by laiyun90** [comment]
@leviding @sqrthree 翻译完成~请求校对
