### ISSUE TITLE
原生 JavaScript 值得学习吗？答案是肯定的

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2111]
* 原文链接：[Is Vanilla JavaScript worth learning? Absolutely.](https://medium.freecodecamp.org/is-vanilla-javascript-worth-learning-absolutely-c2c67140ac34)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/is-vanilla-javascript-worth-learning-absolutely.md)
  * PR 地址：#2119
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lampui** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lampui 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2119
