### ISSUE TITLE
2017年，日志系统的一次概述

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2112]
* 原文链接：[An Overview of the Logging Ecosystem in 2017](https://blog.codeship.com/an-overview-of-the-logging-ecosystem-in-2017/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/an-overview-of-the-logging-ecosystem-in-2017.md)
  * PR 地址：待添加
  * 文章分类：**后端**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TanNingMeng** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@TanNingMeng 棒极啦 :tada:

**Comment by leviding** [comment]
@TanNingMeng 别忘啦来哟~
