### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by KKKyrie** [xitu/gold-miner#2114]
- 公司/学校：桔子理财
- 工作内容/专业：前端
- 常浏览的国外网站：（网站倒是没有...美剧倒成天看）
- 英语水平：CET6（515）， CET4（590）
- 有无翻译经验：无
- 个人博客：kkkyrie.github.io
- 个人介绍：性别男爱好女，17年毕业生，慢热，低调，有趣；关注前端&产品，大三曾经在微信当过三个月的临时工（估计也是这段时间激发了我的产品思维）

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
