### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Usey95** [xitu/gold-miner#2115]
- 公司/学校：深圳点猫科技有限公司/西南交通大学
- 工作内容/专业：web前端/软件工程
- 常浏览的国外网站：没有经常浏览的网站，一般遇到问题都直接google英文
- 英语水平：CET-6，流利交流
- 有无翻译经验：有，udacity前端进阶字幕组成员
- 个人博客：usey95.github.io
- 个人介绍：踏实！

**Comment by sqrthree** [comment]
Hi，欢迎参与翻译计划，加我微信 `511249910` 或者扫描 [二维码](http://7xl8me.com1.z0.glb.clouddn.com/Wechat.jpeg) 加好友，备注下 GitHub ID，方便拉你进译者群哈。O(∩_∩)O
