### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by funtrip** [xitu/gold-miner#2120]
- 原文链接：https://blog.prototypr.io/are-notifications-a-dark-pattern-2c1a177b26e0
- 简要介绍：这篇讲「通知」是不是一个隐藏的功能。并举了一些 linkedin 和 twitter 的例子来讲他们如何用「伪通知」引导用户进行操作以增长活跃度。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by sqrthree** [comment]
已发布在 #2121
