### ISSUE TITLE
通知是一种「暗模式」吗？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2121]
* 原文链接：[Are Notifications A Dark Pattern?](https://blog.prototypr.io/are-notifications-a-dark-pattern-2c1a177b26e0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/are-notifications-a-dark-pattern.md)
  * PR 地址：待添加
  * 文章分类：**设计&产品**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@changkun 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2141
