### ISSUE TITLE
混乱世界中的稳定：Postgres 如何使事务原子化

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2122]
* 原文链接：[Stability in a Chaotic World: How Postgres Makes Transactions Atomic](https://brandur.org/postgres-atomicity)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/postgres-atomicity.md)
  * PR 地址：#2265
  * 文章分类：**后端**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TanNingMeng** [comment]
21天都没人领。。我领了！

**Comment by TanNingMeng** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@TanNingMeng 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2265
