### ISSUE TITLE
你是如何拆分组件的？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2123]
* 原文链接：[How do you separate components?](https://reactarmory.com/answers/how-should-i-separate-components)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-should-i-separate-components.md)
  * PR 地址：#2139
  * 文章分类：**前端**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by undead25** [comment]
@sqrthree 翻译认领

**Comment by fanyijihua** [comment]
@undead25 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2139
