### ISSUE TITLE
在 Go 语言中增强 Cookie 的安全性 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#2124]
* 原文链接：[Securing Cookies in Go](https://www.calhoun.io/securing-cookies-in-go/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/securing-cookies-in-go.md)
  * PR 地址：￥2144
  * 文章分类：**后端**
  ----
  * 翻译时间：9 天
  * 校对时间：2 天
  * 翻译积分：9 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by tmpbook** [comment]
@lsvih 校对预定，兄弟译完@我校对啊
