### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by gcyStar** [xitu/gold-miner#2132]
- 公司/学校：五阿哥
- 工作内容/专业：web开发
- 常浏览的国外网站：stackoverflow,segmentfault,tympanus 等等
- 英语水平：6级
- 有无翻译经验：有
- 个人博客：https://segmentfault.com/blog/gcystar
- 个人介绍：web开发爱好者，喜欢读书，散步

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O
