### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by qinglin** [xitu/gold-miner#2133]
- 公司/学校：前海信息技术有限公司/University of California, Irvine
- 工作内容/专业：大数据工程师
- 常浏览的国外网站：TechCrunch
- 英语水平：六级，托福GRE
- 有无翻译经验：有，在虎扑字幕组担任过视频校对，在译言翻译过文章
- 个人博客：https://qinglin.github.io/
- 个人介绍： 毕业于武汉大学本科，在UC, Irvine读研，在美国有过3年工作经验，与去年回国在创业公司担任大数据工程师职位，想更多地参与进翻译工作，督促自己学习前沿知识，也把知识分享给国内的大家

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 <a href="http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg" target="_blank">二维码</a> 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O
