### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Yuuoniy** [xitu/gold-miner#2138]
- 公司/学校：中山大学
- 工作内容/专业：软件工程
- 常浏览的国外网站： stackoverflow udacity  quora
- 英语水平：六级579
- 有无翻译经验：无
- 个人博客：https://yuuoniy.github.io/
- 个人介绍：大二学生，希望参与计划提升自己。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O @Yuuoniy
