### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by 415400396** [xitu/gold-miner#2145]
- 公司/学校：浙江工业大学
- 工作内容/专业：
- 常浏览的国外网站：
- 英语水平：6级
- 有无翻译经验：无
- 个人博客：
- 个人介绍：

**Comment by leviding** [comment]
@415400396  Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O
