### ISSUE TITLE
Coursera 的 GraphQL 之路

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2147]
* 原文链接：[Coursera’s journey to GraphQL](https://dev-blog.apollodata.com/courseras-journey-to-graphql-a5ad3b77f39a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/courseras-journey-to-graphql.md)
  * PR 地址：待添加
  * 文章分类：**后端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@bambooom 你要的文章。这篇给你？

其他两篇，有一个太长了，另外一个被翻译过了。感谢推荐，还有好文直接微信给我就行。

**Comment by bambooom** [comment]
啊好的~ 谢谢 @leviding 

翻译认领

**Comment by fanyijihua** [comment]
@bambooom 棒极啦 :tada:
