### ISSUE TITLE
V8 引擎中的快速属性

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2150]
* 原文链接：[Fast Properties in V8](https://v8project.blogspot.jp/2017/08/fast-properties.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/fast-properties-in-v8.md)
  * PR 地址：#2204
  * 文章分类：**前端**
  ----
  * 翻译时间：9 天
  * 校对时间：2 天
  * 翻译积分：9 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Usey95** [comment]
申请认领

**Comment by junhey** [comment]
校对认领

**Comment by sunshine940326** [comment]
翻译认领

**Comment by leviding** [comment]
@sunshine940326 好的呢

**Comment by fanyijihua** [comment]
PR 地址：#2204
