### ISSUE TITLE
今年最好的文章被译的体无完肤

### ISSUE THREAD

**Issue by rainjay** [xitu/gold-miner#2151]
https://github.com/xitu/gold-miner/blob/master/TODO/a-unified-styling-language.md

这篇原文是我今年看过的最好的文章，但是看了原版再看了下掘金这里的翻译，发现几个问题：
1. https://juejin.im/post/595311fa6fb9a06b9d5b5f08 文章中的说明代码部分都有问题，可能是掘金的bug，希望可以尽快修复

2. 翻译者资历尚浅，翻译以后的文章读起来不清晰，不准确，甚至有几处和原文意思完全相反，也许校验者也不够吧。举几个翻译有误的地方说明下：

Many people, particularly those already intimately familiar with CSS, have looked on in disbelief.
掘金译文： 很多人，尤其是那些已经对 CSS 非常熟悉的人都表示难以置信
问题描述：原文意思是很精通CSS的人都对此持怀疑态度，难以置信对应的英文是unbelivable

 It wasn’t long after this that I became obsessed with separating our concerns, using unobtrusive JavaScript to decorate our server-rendered markup with client-side interactions.
掘金译文：不久之后，我开始专注于前后端分离，使用非侵入式 JavaScript 和客户端的交互来装饰服务端渲染的 HTML。
问题描述：这个翻译完全错误，原文的意思是：不久我开始痴迷于关注分离，在服务器渲染出来的页面中使用 非侵入式JavaScript 同客户端交互。作者一直说是用服务器端渲染，何来的前后端分离？

Scoped styles
掘金译文：局部样式
问题描述：不知道翻译者是否真的读懂原文，这里强调的是具有作用域的样式，应该翻译为“拥有作用域的样式”

 but the critical flaw in this model is that ‘style’ attributes can’t do everything that CSS can do
掘金译文： 但是这个模式有个严重的缺点，'styles' 属性并不能做到 CSS 可以做到的每件事
问题描述：是style属性，而不是styles属性，不要忽视这些细节，这些细节决定了对与错，译者的责任就是确保文章可以准确无误地被另一种语言描述出来，不严谨的人翻译的东西就是误人子弟

Most new libraries instead focus on dynamic style sheets, inserting and removing rules at runtime from a global set of styles.
掘金译文：大多数新的库不再关注于动态样式表，而是在运行时在全局样式中插入和删除规则。
问题描述：这是一个完全错误和原文意思相反的翻译，原文的意思是：取而代之的是，绝大多数新的CSS-in-JS库关注于动态样式表，在运行时从一个全局的样式集中插入和删除样式规则

These generated classes can then be used instead of hard-coded class strings when generating markup in JavaScript. This pattern works regardless of whether you’re using a full-blown framework, or something as simple as innerHTML.
掘金译文：无论你是使用一个完整的框架，还是简单的使用 innerHTML，你都可以在 JavaScript 中使用这些生成的 class，而不是硬编码你的 class 字符串。
问题描述：翻译的不准确，有误。原文意思是：不管你是使用一个完整的框架，还是简单粗暴地使用innerHTML，当用JavaScript生成HTML时，都可以使用这些生成的类代替硬编码的类名。

By focusing our styles around components, integrating them more closely at the code level, we’re effectively taking BEM to its logical conclusion. So much so that many in the CSS-in-JS community felt like the importance of extracting, naming and reusing components was being lost in all the style-binding boilerplate.
掘金译文：通过将我们的样式集中到组件上，可以将他们和代码跟紧密的结合，这不就是 BEM 的思想么？所以 CSS-in-JS 社区的很多人觉得在所有的样式绑定样板中，提取、命名和复用组件的重要性都丢失了。
问题描述：原文的意思是通过将样式集中在组件周围，并在代码层面上将它们紧密地结合在一起，我们有效地得到了合乎BEM逻辑的结果。不是将样式集中到组件上导致样式和代码紧密结合。

等等等等，我看不下去了

对于翻译这篇文章的译者，我这里先说声对不起，上面的话我讲的比较重，但这是因为我看到需要被所有前端认真阅读的好文章，却被有一定影响力的社区议的有些误人子弟，这焦急的心情

对于掘金，希望重视译文的质量，加大审核力度，否则，掘金就不是传播知识的社区了，而是传播错误的社区！话虽重，道理大家平心而论

如果继续发这种质量的译文，掘金前途堪忧

**Comment by Aladdin-ADD** [comment]
谢谢您的反馈！

一直以来我们都很关注译文的质量，对于出现质量不高的译文，深表歉意。

我新开了一个 issue #2152，我们一起来讨论有哪些是流程上可以改进的，希望以后能避免此类事故。 ❤️

**Comment by Aladdin-ADD** [comment]
这篇文章也需要另外的校对者，减少对读者的误导。

**Comment by ZhangFe** [comment]
不好意思，我是这篇文章的译者。
首先谢谢 @rainjay 同学指出的这些问题，您不用抱歉，确实是我的问题，很多地方翻译的有失偏颇，翻译完后自己也没有很认真的 review，导致了一些细节性的问题。在 CSS 相关的知识和翻译水平上我确实还需要提升，在参与翻译时也需要更加仔细，避免犯一些低级错误。
对于这篇文章给读者造成的误导，以及给翻译组同学造成的麻烦，我先这里对说一声抱歉。也谢谢 @Aladdin-ADD 同学重开校对，我会先重新阅读一遍文章，后续参考 @rainjay 同学的翻译、新的校对者的校对再次核对一下译文，并且去修改掘金上的译文。
非常抱歉！也希望我犯的错可以提醒大家，以后对待翻译和校对都更认真一些，把咱们的翻译计划做的越来好。

**Comment by rainjay** [comment]
我当初写这个issue的时候有些激动，所以 @ZhangFe 童鞋请不要有压力，请继续保持对翻译的积极性。这篇文章是对今年对前端发展最重要的文章之一，所以请大家一起努力让这篇文章可以被更多前端开发者读到，并真正领会原文的意思。

**Comment by kalasoo** [comment]
@rainjay 谢谢您的反馈，您的建议可以帮 [掘金翻译计划](https://github.com/xitu/gold-miner) 更好的发展。
