### ISSUE TITLE
统一样式语言

### ISSUE THREAD

**Issue by Aladdin-ADD** [xitu/gold-miner#2153]
* 原文链接：[A Unified Styling Language](https://medium.com/seek-blog/a-unified-styling-language-d0c208de2660)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-unified-styling-language.md)
* PR 地址：
*  原 PR 地址：#1778
* 文章分类：**前端**
----
* 翻译时间：`12` 天
* 校对时间：`4` 天
* 翻译积分：`12` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by undead25** [comment]
@Aladdin-ADD 校对认领

**Comment by Usey95** [comment]
校对认领~

**Comment by leviding** [comment]
@Aladdin-ADD @undead25 @Usey95 https://github.com/rainjay/blog/issues/3
校对的时候可以参考上面这个链接的译文，这是反馈者翻译的。暂时还没翻译完，但是他说会翻译完的。大家一起为译文质量的提升努力 :kissing_heart:

**Comment by Usey95** [comment]
@leviding 好的👌

**Comment by ZhangFe** [comment]
给大家添麻烦了，我也会重新读一遍，然后参考大家的校对好好修改一下，真是抱歉

**Comment by Aladdin-ADD** [comment]
@ZhangFe 为了方便对比校对，之前翻译的PR先revert了（#2154 ）。

可以先修改一下，重新提个PR~ 🤝

**Comment by ZhangFe** [comment]
@Aladdin-ADD 收到，我这周比较忙，可能周末也要加班，加上这篇文章确实比较长，可能进度会慢一些，见谅哈，我尽可能快的修改完，好了之后通知你和校对的同学

**Comment by Aladdin-ADD** [comment]
好的呢！ 🍺

**Comment by leviding** [comment]
@ZhangFe 大概什么时候能重新翻译出来？已经过了十天了。或者如果没时间的话，直接让其他译者进行校对吧

**Comment by leviding** [comment]
那我重提 PR 了，这个问题拖了这么久，不能再等了。

**Comment by leviding** [comment]
请见：https://github.com/xitu/gold-miner/pull/2210

**Comment by ZhangFe** [comment]
@leviding  抱歉啊，忘记回复了，我这边应该今天能结束

**Comment by leviding** [comment]
好的，那你就新提 PR 吧，我把我那个关掉。
