### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by derekhuangxu** [xitu/gold-miner#2159]
- 公司/学校：HIGO
- 工作内容/专业：iOS 工程师
- 常浏览的国外网站：StackOverflow、Quora、Twitter
- 英语水平：CET- 4
- 有无翻译经验：有
- 个人博客：https://juejin.im/user/5730b373f38c840067d0d602
                     http://www.jianshu.com/u/ac41d8480d04
- 个人介绍：iOS工程师，对国外的技术发展充满了兴趣，希望加入翻译计划，把国外的技术发展情况带给国内的开发者

**Comment by leviding** [comment]
@derekhuangxu  Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O
