### ISSUE TITLE
「小键盘」难题：用户在手机上填写表单吗？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2163]
* 原文链接：[The Tiny Keyboard Problem: Do People Complete Forms on Their Phones?](https://priceonomics.com/the-tiny-keyboard-problem-do-people-complete-forms/?utm_source=SitePoint&utm_medium=email&utm_campaign=Versioning)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-tiny-keyboard-problem-do-people-complete-forms.md)
  * PR 地址：#2189
  * 文章分类：**产品设计**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@changkun 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2189

**Comment by ylq167** [comment]
校对认领
