### ISSUE TITLE
Switching Your Site to HTTPS on a Shoestring Budget

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2164]
* 原文链接：[Switching Your Site to HTTPS on a Shoestring Budget](https://css-tricks.com/switching-site-https-shoestring-budget/?utm_source=SitePoint&utm_medium=email&utm_campaign=Versioning)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/switching-site-https-shoestring-budget.md)
  * PR 地址：待添加
  * 文章分类：**后端**
  ----
  * 翻译时间：4 天
  * 校对时间：1.5 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
认领翻译，今晚完成

**Comment by tmpbook** [comment]
@lsvih 好高产呀
