### ISSUE TITLE
Using ARKit with Metal part 2

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2165]
* 原文链接：[Using ARKit with Metal part 2](http://metalkit.org/2017/08/31/using-arkit-with-metal-part-2.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/using-arkit-with-metal-part-2.md)
  * PR 地址：待添加
  * 文章分类：**iOS**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by swants** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@swants 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2186
