### ISSUE TITLE
Uber 机器学习平台 — 米开朗基罗

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2166]
* 原文链接：[MEET MICHELANGELO: UBER’S MACHINE LEARNING PLATFORM](https://eng.uber.com/michelangelo/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/meet-michelangelo-ubers-mechine-learning-plantform.md)
  * PR 地址：#2233
  * 文章分类：**机器学习**
  ----
  * 翻译时间：11 天
  * 校对时间：3.5 天
  * 翻译积分：11 分
  * 校对积分：3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领。话说最近两篇都是讲大厂（Airbnb 和 Uber）的机器学习架构的，比较务虚，并且一般读者看了也用不到。这样真的没问题吗？

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by leviding** [comment]
多推荐些好文章哈，之后排些具体技术细节的 @lsvih

**Comment by fanyijihua** [comment]
PR 地址：#2233
