### ISSUE TITLE
如何使用 Golang 中的 Go-Routines 写出高性能的代码

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2167]
* 原文链接：[How to write high-performance code in Golang using Go-Routines](https://medium.com/@vigneshsk/how-to-write-high-performance-code-in-golang-using-go-routines-227edf979c3c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-write-high-performance-code-in-golang-using-go-routines.md)
  * PR 地址：#2468
  * 文章分类：**Golang**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tmpbook** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@tmpbook 棒极啦 :tada:

**Comment by tmpbook** [comment]
Update：不好意思，之前的有点太费时间，今天开始翻译这篇

**Comment by leviding** [comment]
进度怎么样啦~

**Comment by tmpbook** [comment]
@leviding 有人离职了有些忙，不好意思，之前完成了 1/3 争取今天搞定 😅

**Comment by leviding** [comment]
@tmpbook 好的好的，辛苦了。按你时间来，别累到。

**Comment by leviding** [comment]
@tmpbook 还翻译吗，如果翻译就翻译好了发上去，不方便的话我就把这个关了也行。

**Comment by tmpbook** [comment]
@leviding 还翻译的，不好意思，先别关

**Comment by leviding** [comment]
好的 @tmpbook

**Comment by leviding** [comment]
@tmpbook 怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#2468
