### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by alfred-zhong** [xitu/gold-miner#2170]
- 公司/学校：扬州大学
- 工作内容/专业：后端开发。Java / Go
- 常浏览的国外网站：Medium，各类技术博客
- 英语水平：6 级
- 有无翻译经验：有
- 个人博客：http://www.cnblogs.com/snowInPluto/
- 个人介绍：

**Comment by leviding** [comment]
@alfred-zhong  Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

**Comment by tmpbook** [comment]
又来一名后端，欢迎~~~
