### ISSUE TITLE
使用 CSS 的 font-size-adjust 属性改善网页排版

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2172]
* 原文链接：[Improve Web Typography with CSS Font Size Adjust](https://www.sitepoint.com/improve-web-typography-css-font-size-adjust/?utm_source=SitePoint&utm_medium=email&utm_campaign=Versioning)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/improve-web-typography-css-font-size-adjust.md)
  * PR 地址：#2180
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lampui** [comment]
翻译认领

**Comment by leviding** [comment]
@lampui 好的呢
