### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by TobiasLee** [xitu/gold-miner#2173]
- 原文链接： http://guanghan.info/blog/en/my-works/building-our-personal-deep-learning-rig-gtx-1080-ubuntu-16-04-cuda-8-0rc-cudnn-7-tensorflowmxnetcaffedarknet/
- 简要介绍：介绍了如何搭建深度学习环境，覆盖硬件和软件等方面，非常具有操作性的一篇指导博客

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ
