### ISSUE TITLE
学习 JavaScript：9个常见错误阻碍你进步

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2175]
* 原文链接：[Learning JavaScript: 9 Common Mistakes That Are Holding You Back](https://www.sitepoint.com/learning-javascript-9-common-mistakes/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/learning-javascript-9-common-mistakes.md)
  * PR 地址：#2195
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lekenny** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lekenny 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2195
