### ISSUE TITLE
离线友好的表单

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2176]
* 原文链接：[Offline-Friendly Forms](https://mxb.at/blog/offline-forms/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/offline-friendly-forms.md)
  * PR 地址：#2194
  * 文章分类：**设计**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sunui 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2194

**Comment by thisisandy** [comment]
校对认领
