### ISSUE TITLE
在 HTTP/2 的世界里管理 CSS 和 JS

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2177]
* 原文链接：[Managing CSS & JS in an HTTP/2 World](https://www.viget.com/articles/managing-css-js-http-2/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/managing-css-js-http-2.md)
  * PR 地址：#2190
  * 文章分类：**前端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sunui 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2190
