### ISSUE TITLE
网络现状：性能提升指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2178]
* 原文链接：[The State of the Web](https://medium.com/@fox/talk-the-state-of-the-web-3e12f8e413b3)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/talk-the-state-of-the-web.md)
  * PR 地址：#2220
  * 文章分类：**前端**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by undead25** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@undead25 棒极啦 :tada:

**Comment by undead25** [comment]
@leviding 这篇延迟2天，最近家里和公司都比较事多...才翻译 1/3

**Comment by leviding** [comment]
好的 @undead25

**Comment by fanyijihua** [comment]
PR 地址：#2220
