### ISSUE TITLE
搭建个人深度学习平台：GTX 1080 + Ubuntu 16.04 + CUDA 8.0RC + CuDnn 7 + Tensorflow/Mxnet/Caffe/Darknet

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2179]
* 原文链接：[Build Personal Deep Learning Rig: GTX 1080 + Ubuntu 16.04 + CUDA 8.0RC + CuDnn 7 + Tensorflow/Mxnet/Caffe/Darknet](http://guanghan.info/blog/en/my-works/building-our-personal-deep-learning-rig-gtx-1080-ubuntu-16-04-cuda-8-0rc-cudnn-7-tensorflowmxnetcaffedarknet/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/building-our-personal-deep-learning-rig-gtx-1080-ubuntu-16-04-cuda-8-0rc-cudnn-7-tensorflowmxnetcaffedarknet.md)
  * PR 地址：[#2208](https://github.com/xitu/gold-miner/pull/2208)
  * 文章分类：**人工智能**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by RichardLeeH** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@RichardLeeH 棒极啦 :tada:

**Comment by fghpdf** [comment]
66666666，用 1080 跑机器学习，我最近在这方面有所涉猎，可以翻译吗

**Comment by leviding** [comment]
@fghpdf 可以啊，到时候去 PR 下校对。

**Comment by RichardLeeH** [comment]
@leviding @sqrthree 翻译完成

**Comment by leviding** [comment]
@RichardLeeH 没看到对应的 PR 呢？

相关流程可以参考 https://github.com/xitu/gold-miner/wiki

**Comment by RichardLeeH** [comment]
@leviding 忘了提 PR了
