### ISSUE TITLE
使用 CSS 栅格和 Flexbox 打造 Trello 布局

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2181]
* 原文链接：[Building a Trello Layout with CSS Grid and Flexbox](https://www.sitepoint.com/building-trello-layout-css-grid-flexbox/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/building-trello-layout-css-grid-flexbox.md)
  * PR 地址：#2188
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sunui 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2188
