### ISSUE TITLE
扁平化的 UI 元素既朴实又玄乎

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2182]
* 原文链接：[Flat UI Elements Attract Less Attention and Cause Uncertainty](https://www.nngroup.com/articles/flat-ui-less-attention-cause-uncertainty/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/flat-ui-less-attention-cause-uncertainty.md)
  * PR 地址：#2217
  * 文章分类：**设计**
  ----
  * 翻译时间：6 天
  * 校对时间：1.5 天
  * 翻译积分：6 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@changkun 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2217
