### ISSUE TITLE
如何安全地使用 CSS-in-JS？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2183]
* 原文链接：[How can I use CSS-in-JS securely?](https://reactarmory.com/answers/how-can-i-use-css-in-js-securely)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-can-i-use-css-in-js-securely.md)
  * PR 地址：#2187
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Yuuoniy** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Yuuoniy 棒极啦 :tada:
