### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by TobiasLee** [xitu/gold-miner#2185]
- 原文链接：https://theneuralperspective.com/2016/10/04/05-recurrent-neural-networks-rnn-part-1-basic-rnn-char-rnn/ 
https://theneuralperspective.com/2016/10/06/recurrent-neural-networks-rnn-part-2-text-classification/ 
https://theneuralperspective.com/2016/11/20/recurrent-neural-networks-rnn-part-3-encoder-decoder/ 
https://theneuralperspective.com/2016/11/20/recurrent-neural-network-rnn-part-4-attentional-interfaces/ 
https://theneuralperspective.com/2016/11/17/recurrent-neural-network-rnn-part-4-custom-cells/ 
- 简要介绍：这是一个系列的教程，介绍了深度学习用于处理序列最常用的模型循环神经网络（RNN）以及效果最好的Attention Based LSTM 模型，结合论文深入浅出的讲解理论，利用TensorFlow 实现，具有很强的实战性。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢推荐，我会尽快添加。
