### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by liusining** [xitu/gold-miner#2191]
- 公司/学校：北京理工大学
- 工作内容/专业：后端开发（Ruby）
- 常浏览的国外网站：youtube.com, docs.aws.amazon.com
- 英语水平：曾经托福102，在英语学习app流利说上能见到我的配音
- 有无翻译经验：翻译过天文科普文章
- 个人博客：[http://www.jianshu.com/u/99f3318bcc01](http://www.jianshu.com/u/99f3318bcc01)
- 个人介绍：希望能和工程师们交朋友的后端开发

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O
