### ISSUE TITLE
关于翻译coding-interview-university文章

### ISSUE THREAD

**Issue by longjj** [xitu/gold-miner#2192]
你好，最近我在浏览[coding-interview-university](https://github.com/jwasham/coding-interview-university)的时候发现现在版本的中文翻译已经过期，**我已经取得了[该库作者的同意进行翻译](https://github.com/jwasham/coding-interview-university/issues/243)**，在翻译过程中我发现里面由掘金计划的相关内容，请问我继续翻译是否还需要保存你们的相关信息？如果把相关信息去除会不会有什么问题？

**Comment by sqrthree** [comment]
我觉得在译文的基础上更新改动是一个更好的选择，可以在 [这个链接](https://github.com/xitu/google-interview-university/compare/master...jwasham:master#diff-04c6e90faac2675aa89e2176d2eec7d8) 查看到所有的最新改动。

关于分支管理，我的想法是：新建一个 `zh-hans` 分支用于生产译文，接受新提交，`master` 分支只用于同步上游 repo 使用，不允许本地提交。出现原文更新之后，先从上面的链接中获取改动，然后发 PR 至 `zh-hans`，待 review 通过并 merge 之后，提交改动至上游 repo，作者接受之后，同步我们的 `master` 分支至最新状态。

@leviding @longjj 你们的想法呢？

**Comment by leviding** [comment]
支持 @sqrthree 的想法，也可以在之前的基础上，减少一定的工作量。 @longjj 有什么意见呢

**Comment by longjj** [comment]
@sqrthree @leviding 
好的，我最初也是有这种想法。所以来这边询问一下意见。那么我应该是fork[这个](https://github.com/xitu/google-interview-university/compare/master...jwasham:master#diff-04c6e90faac2675aa89e2176d2eec7d8)，保留掘金计划的相关信息，然后在这里的zh-hans分支添加自己的个人信息，进行翻译然后再给这个库发pull request？

我是第一次涉及到GitHub上在fork库上进行二次开发的情况，一些分支管理的情况希望可以交流清楚一点，谢谢。

**Comment by sqrthree** [comment]
@longjj 是的，你可以根据上面那个对比链接查看所有的改动。

@leviding 你先基于我们的 `master` 分支新建一个 `zh-hans` 分支吧，然后 @longjj Fork 我们的 repo，并在 `zh-hans` 上翻译、提交就行了。

**Comment by leviding** [comment]
@sqrthree 分支已经建立， @longjj 可以 fork 并进行翻译了。翻译中会有一些标准化的东西，参考 https://github.com/xitu/gold-miner/wiki 。不知你是否在掘金翻译计划译者群，如果不在是否有意愿加入。想加入翻译计划译者群或者想更方便沟通，可以加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID。

**Comment by longjj** [comment]
@leviding 实际上我只是一个软件工程本科大三的学生，这篇英文文章只是我在浏览GitHub的时候觉得挺好所以想要贡献一下，目前学业比较繁忙，自己本身暂时没有想专门从事翻译工作的意愿，所以暂时还是不加入译者群了。

另外，我参考到wiki，需要校对者，请问校对者是译者群直接进行的就行了对么？我只需要正常翻译文章即可了对么？

**Comment by leviding** [comment]
@longjj 哈哈，咱们没有全职译者啊，都是大家在自己空闲时间或者打游戏的时间自愿翻译，这个你先翻译吧，翻译好每一部分，提交的时候艾特我就好了。校对的东西我这处理，你最后根据校对意见修改内容就好了。

**Comment by longjj** [comment]
好的明白了！
