### ISSUE TITLE
Angular vs. React vs. Vue: A 2017 comparison

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2193]
* 原文链接：[Angular vs. React vs. Vue: A 2017 comparison](https://medium.com/unicorn-supplies/angular-vs-react-vs-vue-a-2017-comparison-c5c52d620176)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/angular-vs-react-vs-vue-a-2017-comparison.md)
  * PR 地址：#2461
  * 文章分类：**前端**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LouisaNikita** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@LouisaNikita 棒极啦 :tada:

**Comment by leviding** [comment]
@LouisaNikita 翻译怎么样啦

**Comment by leviding** [comment]
@LouisaNikita 翻译怎么样啦

**Comment by HydeSong** [comment]
这篇怎么没动静了？

**Comment by HydeSong** [comment]
要不我来翻译这篇

**Comment by HydeSong** [comment]
@leviding

**Comment by leviding** [comment]
你来吧

**Comment by HydeSong** [comment]
@leviding 好呀

**Comment by leviding** [comment]
@HydeSong 翻译的怎么样了

**Comment by HydeSong** [comment]
@leviding 差不多了
今天提交上去，不好意思，最近在准备面试，耽搁了

**Comment by leviding** [comment]
好，辛苦啦 @LouisaNikita

**Comment by HydeSong** [comment]
@leviding 翻译完成

**Comment by Raoul1996** [comment]
校对认领

**Comment by Raoul1996** [comment]
@leviding

**Comment by fanyijihua** [comment]
PR 地址：#2489
