### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by carmen0208** [xitu/gold-miner#2197]
- 公司/学校：Orion Health, New Zealand
- 工作内容/专业：software engineer/ computer science
- 常浏览的国外网站：all kinds of tech or non-tech websites
- 英语水平：国外工作生活工作一年，无障碍交流。出国前雅思6.5
- 有无翻译经验：无
- 个人博客：carmen0208.github.io
- 个人介绍：现居奥克兰，在奥克兰一家做医疗系统解决方案的软件公司做软件开发，主要的开发语言是ruby 和java. 整整一年的工作生活都用英语，出国之前雅思6.5。在此之前在国内一家美资公司任职开发经理7年，每天都需要跟北美同事有书信来往。一周会至少同两次电话。
业余时间喜欢户外的一切活动，滑雪，滑翔伞。练习跑步，巴西柔术。
希望参加成为译者目的事锻炼自己的英语能力和线上沟通能力。同时希望成为社区成员为社区做贡献，

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O
