### ISSUE TITLE
认领 UIKit 里如何面向协议编程

### ISSUE THREAD

**Issue by walkingway** [xitu/gold-miner#22]
最近刚好要学习一下面向协议编程，这篇我来翻译吧。文章比较长，可能要放到元旦去做了。预计元旦后交工。

**Comment by walkingway** [comment]
这篇文章提供的 Markdown 格式好像有点问题啊，从第一个代码块那开始后面都乱了

**Comment by Glowin** [comment]
好的，元旦以后再提交没问题的，保证质量就好。

我给你添加到 readme 里面了，欢迎加入我们 :+1:
