### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by alfred-zhong** [xitu/gold-miner#2203]
- 原文链接：https://medium.com/digg-data/the-way-of-the-gopher-6693db15ae1f
- 简要介绍：服务从 Node.js 迁移至 Golang。作者受文章 [<<Handling 1 Million Requests per Minute with Go>>](http://marcio.io/2015/07/handling-1-million-requests-per-minute-with-golang/)([使用Go语言每分钟处理1百万请求](https://github.com/itfanr/articles-about-golang/blob/master/2016-10/1.handling-1-million-requests-per-minute-with-golang.md)) 启发。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢推荐，本周添加。
