### ISSUE TITLE
基于 Metal 的 ARKit 使用指南（上）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2207]
* 原文链接：[Using ARKit with Metal](http://metalkit.org/2017/07/29/using-arkit-with-metal.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/using-arkit-with-metal.md)
  * PR 地址：待添加
  * 文章分类：**iOS**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by RichardLeeH** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@RichardLeeH 棒极啦 :tada:

**Comment by leviding** [comment]
@RichardLeeH 翻译好了吗

**Comment by leviding** [comment]
@RichardLeeH 翻译的怎么样啦

**Comment by RichardLeeH** [comment]
@leviding 抱歉，一直在翻译 开源库， 忘了这个了。明天给翻译完。

**Comment by leviding** [comment]
ok
