### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by VernonVan** [xitu/gold-miner#2209]
- 公司/学校：广州坚和网络科技有限公司
- 工作内容/专业：iOS开发工程师
- 常浏览的国外网站：https://www.raywenderlich.com，http://nshipster.com，https://www.objc.io
- 英语水平：4级
- 有无翻译经验：有
- 个人博客：http://www.jianshu.com/u/0da7f56c0a41，https://vernonvan.github.io
- 个人介绍：热爱开源，业余时间有开发自己的个人项目，现在期待在翻译上做出一点贡献。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
