### ISSUE TITLE
【特殊任务】开源库翻译概括（持续招人）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2219]
### 特殊任务来啦

- 特殊任务来啦，掘金开源库功能大家知道吧，不知道的可以点击 [我](https://juejin.im/repos) 和 [我](https://juejin.im/post/59a7a72b6fb9a0248d24f308) 了解更多。

### 任务描述

- 为了让国内开发者更容易找到需要的开源库，我们决定对开源库进行概括性翻译，即 『一句话概括』+『一小段描述』。

- 一句话概括：主要包含该库的名字，用途，若为大厂或者大牛开发的，也需要做一下标注。
- 一小段描述：50 ~ 100 字的总体概括。说明该库的用途，以及该库的特点和其他需要强调的地方。
- 翻译示例参考：[JavaScript 开源库翻译](http://owih3rbbs.bkt.clouddn.com/JavaScript%20%E5%BC%80%E6%BA%90%E5%BA%93%E5%88%97%E8%A1%A8.xlsx)

### 工作内容

- 我们在确定你为相应人选后，我们提供给你一个云端的 Excel 表格链接，你直接在该表格上进行翻译即可。该表格包含 『repo 名』和『repo 链接』，你需要对该库进行概括，然后填写『一句话概括』+『一小段描述』即可。因为是云端 Excel，所以你的进度，以及我们新增加的库都一目了然。

- 我们供选择了 18 个编程语言，一个语言对应几个 Excel 文件，每个译者每次负责一个 Excel。译者以 80
 个/每周 的速度进行翻译归纳。

- 审核校对机制：此处采用管理员抽查的方式，以保证大家翻译的质量。

**说明**：在云文档进行协作，云文档会有详细的修改记录。大家根据自己的时间来进行翻译。并在翻译的项目后边相应处填写你的个人信息。最后根据每个人贡献数量（也保质量）统计积分。

### 参与方式

- 加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，然后发送『开源库翻译』这几个关键字即可。

### 奖励

- 每总结 10 个开源库将获得 1 个翻译积分，积分可[兑换相应礼品](https://github.com/xitu/gold-miner/wiki)。
- 在掘金的每个你所翻译的开源库页面放置您的个人主页连接，注明您为贡献者。
- 敬请期待... 

---

**人是不会招满的，想参与的赶紧联系管理员吧！**

| 分类 |
| ------ |
| JavaScript |
| CSS |
| Vue |
| Swift |
| Objective-C |
| Python |
| Java |
| PHP |
| Go |
| Ruby |
| C++ |
| C# |
| Shell |
| Perl |
| Lua |
| Erlang |
| R |
| Kotlin |

---

> 管理员 @leviding

---

**Comment by tmpbook** [comment]
👍

**Comment by leviding** [comment]
**有什么想法欢迎在下方留言，或者微信私聊我。**

**Comment by ericjjj** [comment]
建议增加 `Rust` 语言

**Comment by leviding** [comment]
谢谢反馈，加了的时候艾特你 @ericjjj

**Comment by fghpdf** [comment]
建议区分一下 node 和 js
node 一些库是为后端准备的，js 不会用到

**Comment by leviding** [comment]
@fghpdf 现在不太好分，翻译的时候碰到不会的可以放下，交给其他人做。不是必须全做的。

**Comment by HydeSong** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@HydeSong 棒极啦 :tada:

**Comment by leviding** [comment]
@HydeSong 加我微信 517010193，备注 GitHub ID，私聊我。

**Comment by GreenHero** [comment]
建议增加 C 语言

**Comment by leviding** [comment]
@GreenHero 嗯嗯，谢谢
