### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by bryantchan** [xitu/gold-miner#222]
你好，我叫Detray，大学专业是英语，后来自学前端。目前有3年前端开发和产品经验。日常工作就是看各种国外的资讯网站和技术文档，听的也是国外的podcast，所以英文无论交流和使用应该都没有什么问题。

**Comment by antonia0912** [comment]
@bryantchan 好的  麻烦加我微信  antonia0912  我来拉你进译者群~

**Comment by xlover135** [comment]
你好，可以叫我大肠君，CS 专业毕业，英语停留在了 CET 6 水平，目前是一只运营实习生，正在一点点自学前端，希望可以加入翻译计划，一边翻译一边成长。

**Comment by antonia0912** [comment]
@bryantchan 请加我微信 antonia0912 我来拉你进译者群
