### ISSUE TITLE
ES6+ 中的 JavaScript 工厂函数

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2221]
* 原文链接：[JavaScript Factory Functions with ES6+](https://medium.com/javascript-scene/javascript-factory-functions-with-es6-4d224591a8b1)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/javascript-factory-functions-with-es6.md)
  * PR 地址：#2232
  * 文章分类：**前端**
  ----
  * 翻译时间：3.5 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@yoyoyohamapi

**Comment by lampui** [comment]
翻译认领？

**Comment by fanyijihua** [comment]
@lampui 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2232

**Comment by HydeSong** [comment]
校对认领

**Comment by lampui** [comment]
@HydeSong 到 PR： #2232 下认领校对，不过这篇文章校对已经够 2 位了。有兴趣可以 review 给点意见

**Comment by HydeSong** [comment]
@lampui 好的
