### ISSUE TITLE
处理 iOS 中复杂的 Table Views 并保持优雅

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2222]
* 原文链接：[Dealing with Complex Table Views in iOS and Keeping Your Sanity](https://medium.cobeisfresh.com/dealing-with-complex-table-views-in-ios-and-keeping-your-sanity-ff5fee1fbb83)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/dealing-with-complex-table-views-in-ios-and-keeping-your-sanity.md)
  * PR 地址：待添加
  * 文章分类：**iOS**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhangqippp** [comment]
@leviding ，翻译认领

**Comment by fanyijihua** [comment]
@zhangqippp 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2392
