### ISSUE TITLE
修改 JavaScript 帧

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2223]
* 原文链接：[Altering JavaScript frames](https://ripsawridge.github.io/articles/stack-changes/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/altering-javascript-frames.md)
  * PR 地址：#2240
  * 文章分类：**前端**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by AceLeeWinnie** [comment]
认领

**Comment by leviding** [comment]
@AceLeeWinnie 请打对关键词

更多说明请见 https://github.com/xitu/gold-miner/wiki

**Comment by AceLeeWinnie** [comment]
认领翻译。（离开了一段时间都变了哈哈，更规范了，好赞👍 ）

**Comment by fanyijihua** [comment]
@AceLeeWinnie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2240

**Comment by HydeSong** [comment]
认领校对
