### ISSUE TITLE
为什么在使用了类之后会使得组合变得愈发困难（第九部分）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2225]
* 原文链接：[Why Composition is Harder with Classes](https://medium.com/javascript-scene/why-composition-is-harder-with-classes-c3e627dcd0aa)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-composition-is-harder-with-classes.md)
  * PR 地址：#2254
  * 文章分类：**前端**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yoyoyohamapi** [comment]
认领

**Comment by yoyoyohamapi** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@yoyoyohamapi 棒极啦 :tada:

**Comment by IridescentMia** [comment]
@fanyijihua 想提前预约这篇的校对，求批准~

**Comment by leviding** [comment]
翻译完了，你让 @yoyoyohamapi  艾特 @IridescentMia

**Comment by IridescentMia** [comment]
大佬，翻译完求艾特，我来校对，相中这篇了 @yoyoyohamapi

**Comment by yoyoyohamapi** [comment]
@IridescentMia 恩恩，快翻译完了

**Comment by fanyijihua** [comment]
PR 地址：#2254
