### ISSUE TITLE
借助函数完成可组合的数据类型（软件编写）（第十部分）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2226]
* 原文链接：[Composable Datatypes with Functions](https://medium.com/javascript-scene/composable-datatypes-with-functions-aec72db3b093)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/composable-datatypes-with-functions.md)
  * PR 地址：#2260
  * 文章分类：**前端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：1.5 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yoyoyohamapi** [comment]
认领

**Comment by yoyoyohamapi** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@yoyoyohamapi 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2260
