### ISSUE TITLE
JavaScript 让 Monad 更简单（软件编写）（第十一部分）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2227]
* 原文链接：[JavaScript Monads Made Simple](https://medium.com/javascript-scene/javascript-monads-made-simple-7856be57bfe8)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/javascript-monads-made-simple.md)
  * PR 地址：#2276
  * 文章分类：**前端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yoyoyohamapi** [comment]
认领

**Comment by yoyoyohamapi** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@yoyoyohamapi 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2276
