### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by HydeSong** [xitu/gold-miner#2228]
- 公司/学校：第五区运动科技（上海）有限公司
- 工作内容/专业：负责web官网、后台、微信公众号、微信小程序、web app的前端开发
- 常浏览的国外网站：stackoverflow、medium、github
- 英语水平：四级
- 有无翻译经验：无
- 个人博客：https://hydesong.github.io/
- 个人介绍：“因为有梦，所以坚持。热爱生活，追求技术。大家好，我是Hyde”

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
