### ISSUE TITLE
申请译者

### ISSUE THREAD

**Issue by Tuccuay** [xitu/gold-miner#223]
半个月前校对过一篇稀土掘金翻译计划的文章：
[Facebook iOS 应用是如何加速图片显示的？](https://github.com/xitu/gold-miner/blob/master/TODO/faster-photos-in-facebook-for-ios.md)
[https://github.com/xitu/gold-miner/blob/master/TODO/faster-photos-in-facebook-for-ios.md](https://github.com/xitu/gold-miner/blob/master/TODO/faster-photos-in-facebook-for-ios.md)

昨天翻译的一篇关于 VR 的文章：
[在 iOS 上开始创建你的虚拟现实应用](https://www.tuccuay.com/2016/03/cardboard-ios-sdk-getting-started/)
[https://www.tuccuay.com/2016/03/cardboard-ios-sdk-getting-started/](https://www.tuccuay.com/2016/03/cardboard-ios-sdk-getting-started/)

另外，正在稀土掘金申请成为 Co-Editor，求通过，profile url：
[http://gold.xitu.io/#/user/5676493300b0023c618747b2](http://gold.xitu.io/#/user/5676493300b0023c618747b2)

**Comment by Glowin** [comment]
1、加我微信 Glowjiang 我来拉你进我们的微信群
2、已经添加好分享权限，欢迎来掘金分享
