### ISSUE TITLE
找出可能影响性能的代码模式

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2230]
* 原文链接：[Tracing Patterns that Might Hinder Performance](https://www.netguru.co/blog/tracing-patterns-hinder-performance)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/tracing-patterns-hinder-performance.md)
  * PR 地址：#2282
  * 文章分类：**待分类**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by blizzardzheng** [comment]
认领

**Comment by Aladdin-ADD** [comment]
翻译认领。

**Comment by leviding** [comment]
@Aladdin-ADD 好的呢

**Comment by HydeSong** [comment]
校对认领

**Comment by leviding** [comment]
@HydeSong 在 PR 下认领
