### ISSUE TITLE
Rewriting RxJava with Kotlin Coroutines?

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2231]
* 原文链接：[Rewriting RxJava with Kotlin Coroutines?](https://akarnokd.blogspot.jp/2017/09/rewriting-rxjava-with-kotlin-coroutines.html?utm_source=Android+Weekly&utm_campaign=9eae73d7b8-androidweekly-274&utm_medium=email&utm_term=0_4eb677ad19-9eae73d7b8-338020353)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/rewriting-rxjava-with-kotlin-coroutines.md)
  * PR 地址：待添加
  * 文章分类：**Android**
  ----
  * 翻译时间：4 天
  * ~校对时间：1 天~
  * 翻译积分：4 分
  * ~校对积分：1 分~
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by phxnirvana** [comment]
推荐认领一条龙

**Comment by phxnirvana** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@phxnirvana 棒极啦 :tada:

**Comment by leviding** [comment]
超时太久啦，翻译怎么样啦

**Comment by phxnirvana** [comment]
好多句子写的乱七八糟。。给自己挖了个大坑。。争取这周末提交个beta吧。。

**Comment by leviding** [comment]
好的
