### ISSUE TITLE
区块链中的共识机制 DBFT

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2236]
* 原文链接：[Consensus](https://github.com/neo-project/docs/blob/master/en-us/node/consensus.md)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/neo-project-docs-consensus.md)
  * PR 地址：#2239
  * 文章分类：**区块链**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：8 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
我来吧，正好明天周六了 @leviding

**Comment by Romeo0906** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Romeo0906 棒极啦 :tada:
