### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by blizzardzheng** [xitu/gold-miner#2237]
- 公司/学校：Coding.net
- 工作内容/专业：JS全栈工程师
- 常浏览的国外网站：medium、hacknoon、reddit、developers.facebook、code.google、mdn、github、twitter。
- 英语水平：中级口译，cet 6
- 有无翻译经验：之前很少做翻译, 翻译更喜欢理解的基础异译
- 个人博客：https://zhuanlan.zhihu.com/FrontendArchitecture 我的专栏
- 个人介绍：狂热前端，爱好社区，毕业后一直使用react和nodejs。coding WebIDE 前端核心贡献者，Coding Gist开发者，开发自家的git熟悉git。《rxjs 实践指南》 已签约作者(正在编写中)，elm中文社区开拓者，希望有时间可以翻译点文章

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
