### ISSUE TITLE
在硅谷如何应聘一个产品设计实习生？

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#224]
文章链接：[在硅谷如何应聘一个产品设计实习生？](https://medium.com/facebook-design/a-guide-to-interviewing-for-product-design-internships-d719dd4c146c#.jhgjr12c)
掘金链接：[在硅谷如何应聘一个产品设计实习生？](http://gold.xitu.io/entry/56f23d23731956005c644835)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/guide-to-interviewing-for-product-design-internships.md)

翻译时间：5天
校对时间：3天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by iThreeKing** [comment]
认领翻译 @antonia0912

**Comment by antonia0912** [comment]
@iThreeKing OK 三金注意时间哈

**Comment by iThreeKing** [comment]
妥  这周没课

**Comment by iThreeKing** [comment]
翻译完成可以校对 @antonia0912

**Comment by shaohui10086** [comment]
申请校对

**Comment by antonia0912** [comment]
@iThreeKing 三金这办事效率我喜欢  101个赞

**Comment by antonia0912** [comment]
@shaohui10086 好的 校对完成后记得在PR里发comment“校对完成”哈  [校对地址](https://github.com/xitu/gold-miner/pull/242/files?diff=split)

**Comment by circlelove** [comment]
认校对～

**Comment by antonia0912** [comment]
@circlelove 好的  [校对地址](https://github.com/xitu/gold-miner/pull/242/files?diff=split)
