### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by blizzardzheng** [xitu/gold-miner#2242]
- 原文链接：https://github.com/Bogdan-Lyashenko/Under-the-hood-ReactJS
- 简要介绍：对react核心源码的深度解析，对其使用的设计模式，开发规范，思想理念讲解的很清晰，是非常好的学习材料。全文总共14个章节，每一节有比较详细的图解，不过对图的解析不够小白化，个别章节理解略有困难，如果可以需要补一些解释。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by blizzardzheng** [comment]
有意愿自认领

**Comment by leviding** [comment]
@blizzardzheng 详见 https://github.com/xitu/Under-the-hood-ReactJS/issues
