### ISSUE TITLE
你不知道的 Node

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2244]
* 原文链接：[You don’t know Node](https://medium.com/@samerbuna/you-dont-know-node-6515a658a1ed)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/you-dont-know-node.md)
  * PR 地址：待添加
  * 文章分类：**后端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lampui** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lampui 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2264
