### ISSUE TITLE
在 Facebook 发一张登机牌，你就有可能被盗号了

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2245]
* 原文链接：[Post a boarding pass on Facebook, get your account stolen](https://www.michalspacek.com/post-a-boarding-pass-on-facebook-get-your-account-stolen)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/post-a-boarding-pass-on-facebook-get-your-account-stolen.md)
  * PR 地址：#2259
  * 文章分类：**待分类**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lampui** [comment]
校对认领

**Comment by lampui** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lampui 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2259
