### ISSUE TITLE
React 16 带来了什么以及对 Fiber 架构的解释

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2246]
* 原文链接：[What’s New in React 16 and Fiber Explanation](https://edgecoders.com/react-16-features-and-fiber-explanation-e779544bb1b7)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/react-16-features-and-fiber-explanation.md)
  * PR 地址：#2281
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yoyoyohamapi** [comment]
@leviding 认领翻译

**Comment by fanyijihua** [comment]
@yoyoyohamapi 棒极啦 :tada:
