### ISSUE TITLE
RNN 循环神经网络系列 1：基本 RNN 与 CHAR-RNN

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2247]
* 原文链接：[RECURRENT NEURAL NETWORKS (RNN) – PART 1: BASIC RNN / CHAR-RNN](https://theneuralperspective.com/2016/10/04/05-recurrent-neural-networks-rnn-part-1-basic-rnn-char-rnn/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/recurrent-neural-networks-rnn-part-1-basic-rnn-char-rnn.md)
  * PR 地址：#2277
  * 文章分类：**机器学习**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@changkun 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2277
