### ISSUE TITLE
RNN 循环神经网络系列 2：文本分类

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2248]
* 原文链接：[RECURRENT NEURAL NETWORKS (RNN) – PART 2: TEXT CLASSIFICATION](https://theneuralperspective.com/2016/10/06/recurrent-neural-networks-rnn-part-2-text-classification/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/recurrent-neural-networks-rnn-part-2-text-classification.md)
  * PR 地址：#2270
  * 文章分类：**机器学习**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@changkun 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2270
