### ISSUE TITLE
RNN 循环神经网络系列 3：编码、解码器

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2249]
* 原文链接：[RECURRENT NEURAL NETWORKS (RNN) – PART 3: ENCODER-DECODER](https://theneuralperspective.com/2016/11/20/recurrent-neural-networks-rnn-part-3-encoder-decoder/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/recurrent-neural-networks-rnn-part-3-encoder-decoder.md)
  * PR 地址：#2267
  * 文章分类：**机器学习**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@changkun 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2267
