### ISSUE TITLE
我是如何为 Mac 应用 Flinto 设计 UI 图标的

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#225]
原文链接：[Designing the Icons for Flinto’s UI](https://medium.com/flinto-software/designing-the-icons-for-flinto-s-ui-ddd9e5788cce#.yr5asvf9c)
掘金链接：[我是如何为 Mac 应用 Flinto 设计 UI 图标的](http://gold.xitu.io/entry/56f256fcd342d30054bb5a84)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/designing-the-icons-for-flinto-s-ui.md)

翻译时间：6天
校对时间：3天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by edvardHua** [comment]
@antonia0912 码农来尝试翻译下！

**Comment by antonia0912** [comment]
@edvardHua 好的呀  加油 等你PR

**Comment by Ruixi** [comment]
求校对！

**Comment by antonia0912** [comment]
@edvardHua 译者翻译完后请 at 我们家睿奚姑娘@Ruixi 来校对哈~

**Comment by antonia0912** [comment]
@Ruixi 睿奚可以来校对啦 [校对地址](https://github.com/xitu/gold-miner/pull/314/files?diff=split)

**Comment by funtrip** [comment]
申请校对

**Comment by Ruixi** [comment]
我来啦～

**Comment by CoderBOBO** [comment]
校对

**Comment by antonia0912** [comment]
@CoderBOBO 收到

**Comment by Ruixi** [comment]
我翻译完了……专有名词好多［吐血
另外还种草了Flinto……已经下了一个……［算是意外收获吗……

**Comment by edvardHua** [comment]
@Ruixi 谢谢睿奚的校队啦，Flinto感觉很不错哦。

**Comment by Ruixi** [comment]
@edvardHua 已成功入教，请组织放心！

**Comment by edvardHua** [comment]
哈哈
