### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by newraina** [xitu/gold-miner#2250]
- 公司：百姓网
- 工作内容：前端工程师，负责中后台系统搭建
- 常浏览的国外网站：https://medium.com
- 英语水平：CET-6
- 有无翻译经验：无
- 个人博客： www.newraina.com
- 个人介绍：关注前端单页应用相关的开发技术，偶尔画画图 :)

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
