### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Becklin** [xitu/gold-miner#2251]
- 公司/学校：台灣私立銘傳大學設計所，澳洲悉尼新南威爾斯大學筆譯所
- 工作内容/专业：台灣電商東森購物前端工程師
- 常浏览的国外网站：Stackoverflow, Medium
- 英语水平：TOEIC 855 (2014) ILTS 6.5(2011)
- 有无翻译经验：無
- 个人博客：
- 个人介绍：平常喜歡看前端技術性相關文章，打電動、喝咖啡、爬山。目前專案用的技術是react, reflux。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
