### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by fengsehng** [xitu/gold-miner#2252]
- 公司/学校：链家网
- 工作内容/专业：Android
- 常浏览的国外网站：medium
- 英语水平：6级以上
- 有无翻译经验：有
- 个人博客：http://blog.csdn.net/lpjishu
- 个人介绍：2016年csdn博客专家

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
