### ISSUE TITLE
RNN 循环神经网络系列 4: 注意力机制

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2253]
* 原文链接：[RECURRENT NEURAL NETWORK (RNN) – PART 4: ATTENTIONAL INTERFACES](https://theneuralperspective.com/2016/11/20/recurrent-neural-network-rnn-part-4-attentional-interfaces/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/recurrent-neural-network-rnn-part-4-attentional-interfaces.md)
  * PR 地址：#2280
  * 文章分类：**机器学习**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TobiasLee** [comment]
@fanyijihua  翻译认领

**Comment by fanyijihua** [comment]
@TobiasLee 棒极啦 :tada:

**Comment by Brucexz** [comment]
@校对认领

**Comment by Brucexz** [comment]
@fanyijihua  校对认领
