### ISSUE TITLE
RNN 循环神经网络系列 5: 自定义单元

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2255]
* 原文链接：[RECURRENT NEURAL NETWORK (RNN) – PART 5: CUSTOM CELLS](https://theneuralperspective.com/2016/11/17/recurrent-neural-network-rnn-part-4-custom-cells/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/recurrent-neural-network-rnn-part-5-custom-cells.md)
  * PR 地址：待添加
  * 文章分类：**机器学习**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by leviding** [comment]
@lsvih 翻译怎么样啦

**Comment by lsvih** [comment]
@leviding 这段时间总在翻新的，这篇老的给漏了，明天的样子赶完。

**Comment by leviding** [comment]
💝

**Comment by fanyijihua** [comment]
PR 地址：#2380
