### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by rust-in** [xitu/gold-miner#2257]
- 公司/学校：北京航空航天大学
- 工作内容/专业：软件工程
- 常浏览的国外网站：Wiki, Coursera, StackOverflow...
- 英语水平：CET6
- 有无翻译经验：无
- 个人博客：搭建中
- 个人介绍：掘金用户，菜鸡程序员一只，希望加入掘金翻译计划，在学习中成长。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
