### ISSUE TITLE
管中窥豹：RxJava 与 Kotlin 协程的对比

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2258]
* 原文链接：[RxJava vs. Kotlin Coroutines, a quick look](http://akarnokd.blogspot.jp/2017/09/rxjava-vs-kotlin-coroutines-quick-look.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/rxjava-vs-kotlin-coroutines-quick-look.md)
  * PR 地址：#2287
  * 文章分类：**安卓**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by phxnirvana** [comment]
翻译认领Orz

**Comment by fanyijihua** [comment]
@phxnirvana 棒极啦 :tada:

**Comment by DymanZy** [comment]
翻译认领 : )

**Comment by leviding** [comment]
本文已经翻译好了哦 @DymanZy
