### ISSUE TITLE
在 @media 中，px、em、rem 用哪个比较好？

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#226]
原文链接：[PX, EM or REM Media Queries?](http://zellwk.com/blog/media-query-units/)
掘金链接：[在 @media 中，px、em、rem 用哪个比较好？](http://gold.xitu.io/entry/56f396cb7db2a200524bfb78)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/media-query-units.md)

翻译时间：5天
校对时间：3天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by L9m** [comment]
我来认领

**Comment by MuYunyun** [comment]
这篇文章还能被认领翻译吗？

**Comment by MuYunyun** [comment]
@antonia0912 这篇文章还能被认领翻译吗？

**Comment by sqrthree** [comment]
Sorry, Looks like this article has been translated. See https://www.w3cplus.com/css/media-query-units.html to get translation.
