### ISSUE TITLE
iPhone X 网页设计

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2261]
* 原文链接：[Designing Websites for iPhone X](https://webkit.org/blog/7929/designing-websites-for-iphone-x/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/designing-websites-for-iphone-x.md)
  * PR 地址：#2278
  * 文章分类：**设计**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by HydeSong** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@HydeSong 棒极啦 :tada:

**Comment by HydeSong** [comment]
@fanyijihua 完成翻译，PR #2274

**Comment by fanyijihua** [comment]
PR 地址：#2278

**Comment by HydeSong** [comment]
@fanyijihua PR: #2278 重新提交了原来的PR关了吧
