### ISSUE TITLE
Under-the-hood-ReactJS 系列教程翻译 — 共 17 篇

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2262]
详见：https://github.com/xitu/Under-the-hood-ReactJS/issues

> [在该 Issues 下认领翻译和校对。](https://github.com/xitu/Under-the-hood-ReactJS/issues)

> **大家在 *translation* 分支下进行翻译和 PR，不要修改 *master*。**

**Comment by HydeSong** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@HydeSong 棒极啦 :tada:

**Comment by leviding** [comment]
@HydeSong 进去认领：https://github.com/xitu/Under-the-hood-ReactJS/issues
