### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Hermaz** [xitu/gold-miner#2266]
- 公司/学校：东北林业大学
- 工作内容/专业：机械电子工程
- 常浏览的国外网站：stackoverflow.com、github.com
- 英语水平：CET6
- 有无翻译经验：翻译过《The Art of Public Speaking》
- 个人博客：无
- 个人介绍：自学前端编程，希望通过翻译英文文档来提高编程和英语阅读能力。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
