### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by xueshuai** [xitu/gold-miner#2269]
- 公司/学校：京东
- 工作内容/专业：computer science and technology
- 常浏览的国外网站：github.com, facebook.com, stackoverflow.com
- 英语水平：英语水平感觉还不错，法国留学经历，国内的认证有过6级，托业900分
- 有无翻译经验：暂无
- 个人博客：暂时没有搭建好呢，ixueshuai.com
- 个人介绍：我是一个开朗且有责任心的人，觉得掘进社区非常好，想为这个社区做出自己的贡献，希望能够有幸获得这个机会

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
