### ISSUE TITLE
使用 CSS 和 jQuery 来做一个墨水晕开的效果

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#227]
原文链接：[Ink Transition Effect](https://codyhouse.co/gem/ink-transition-effect/)
掘金链接：[使用 CSS 和 jQuery 来做一个墨水晕开的效果](http://gold.xitu.io/entry/56f39908efa6310055a9813b)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/ink-transition-effect.md)

翻译时间：5天
校对时间：3天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

[校对地址](https://github.com/xitu/gold-miner/pull/234/files?diff=split)

**Comment by L9m** [comment]
认领

**Comment by antonia0912** [comment]
@L9m 好的  老样子翻译就可以了  翻译完之后麻烦把校对地址放到这里  还有请注意翻译时间限制  辛苦啦

**Comment by hikerpig** [comment]
赶紧先认领下校对

**Comment by sqrthree** [comment]
认领校对 p( ^ O ^ )q

**Comment by CommanderXL** [comment]
认领校对~~~~

**Comment by antonia0912** [comment]
@hikerpig @sqrthree 好的 校对地址上边有标注喔

**Comment by antonia0912** [comment]
@CommanderXL 这篇文章已经被上边两位译者认领校对了  下次下手要快哈（偷笑）
