### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by smile-soul** [xitu/gold-miner#2272]
- 公司/学校：
  - 上海汉得信息技术股份有限公司 / 西南交通大学
- 工作内容/专业：
  - Web前端开发，架构设计 / 通信工程
- 常浏览的国外网站：
  - https://stackoverflow.com
  - https://www.quora.com
- 英语水平：
  - 可阅读英文文档
- 有无翻译经验：
  - 无
- 个人博客：
  - smilesoul.cn
  - https://github.com/smile-soul
- 个人介绍：
  - 热爱编程，喜欢编写插件，喜欢新知识，对英语感兴趣。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
