### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by CommanderXL** [xitu/gold-miner#228]
帝都某高校烟酒生一枚。

本科和研究生专业和计算机八竿子打不着。然而研一接触到前端后一发不可收拾。我发现FE才是我的真爱。

现阶段在学校准备毕业论文。时间各种充沛。英语能力能无障碍看油管上的字幕视频(无字幕的听起来还是有点吃力)。

thx.~

**Comment by antonia0912** [comment]
好的 请加我微信 antonia0912，我来拉你进译者群
