### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zerosrat** [xitu/gold-miner#2283]
- 公司/学校：电子科技大学
- 工作内容/专业：信息与软件工程
- 常浏览的国外网站：Medium, hackernoon, JavaScript Weekly
- 英语水平：CET6
- 有无翻译经验：无
- 个人博客：http://zerosrat.com/
- 个人介绍：前端，在读研一。希望提高学术英语水平~

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
