### ISSUE TITLE
自制区块链：学习区块链的最快方式

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2284]
* 原文链接：[Learn Blockchains by Building One: The fastest way to learn how Blockchains work is to build one](https://hackernoon.com/learn-blockchains-by-building-one-117428612f46)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/learn-blockchains-by-building-one.md)
  * PR 地址：待添加
  * 文章分类：**区块链**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cdpath** [comment]
认领 🙋‍♂️

**Comment by leviding** [comment]
@cdpath 好的呢

**Comment by leviding** [comment]
@cdpath 进度怎么样啦~
