### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by fighting300** [xitu/gold-miner#2286]
公司/学校：去哪儿
工作内容/专业：iOS
常浏览的国外网站：Google，StackOverflow，Coursera，Medium...
英语水平：英语6级，可以几乎无障碍看各种原版文档
有无翻译经验：有
个人博客：http://fighting300.com
个人介绍：热爱新技术，喜欢并关注各类开源项目

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』

**Comment by leviding** [comment]
@加微信了吗？
