### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by lzwaiwai** [xitu/gold-miner#2288]
- 公司/学校：情非得已科技有限公司
- 工作内容/专业：前端
- 常浏览的国外网站：StackOverflow，Medium，Codrops，Pinterest等
- 英语水平：4级
- 有无翻译经验：无
- 个人博客：http://lzwai.me
- 个人介绍：喜欢倒腾前端各种东西，希望成为"技术懒惰者"。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
