### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ppp-man** [xitu/gold-miner#2289]
公司/学校：Antalis
工作内容/专业：Business Analyst
常浏览的国外网站：Materialistic，StackOverflow，Lynda，BBC... 
英语水平：留学美国，可以无障碍看各种原版文档
有无翻译经验：有
个人博客：无
个人介绍：热爱新技术，喜欢分享有用的资讯

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
