### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by shaohui10086** [xitu/gold-miner#229]
帝都Android开发实习生一名，94🐶，大四在读，专业 计科，目前在一家创业公司专职Android开发，英语水平还好，主要得力于英语专业的女友...上次在稀土新居参加GDG茶话会的时候，听大大说到翻译文章这个项目，很感兴趣，想加入

**Comment by antonia0912** [comment]
@shaohui10086 好的  请加我微信 antonia0912 我拉你进译者群
