### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by kobehaha** [xitu/gold-miner#2291]
- 公司/学校：北京多贝兄弟有限公司
- 工作内容/专业：后端服务器研发
- 常浏览的国外网站：github, youtube, stackoverflow,
- 英语水平：熟练查看英文技术文档
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：github:https://github.com/kobehaha  熟练使用java/python/golang后端研发,喜欢技术,最近正在开发基于go的tcp代理 tcp-proxy https://github.com/kobehaha/tcp-proxy-system, 热爱的热爱新技术，喜欢看各种技术文档，书籍

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
