### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by cnJason** [xitu/gold-miner#2292]
- 公司/学校：原搜狐畅游、原51信用卡管家
- 工作内容/专业：资深Java开发工程师、运维开发全栈架构师
- 常浏览的国外网站：reddit.com、stackoverflow.com
- 英语水平：CET-6
- 有无翻译经验：曾参加美剧字幕组
- 个人博客：http://blog.csdn.net/jasonchris
- 个人介绍：bug制造机

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
