### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by witmax** [xitu/gold-miner#2295]
- 公司/学校：百姓网股份有限公司
- 工作内容/专业：资深开发工程师
- 常浏览的国外网站：谷歌、stackoverflow、Github
- 英语水平：熟练阅读英文技术文档
- 有无翻译经验：无
- 个人博客：http://witmax.cn
- 个人介绍：热爱新技术，喜欢看各种技术文档、书籍，关注架构和DevOps

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
