### ISSUE TITLE
RICE - 给产品经理的简易优先级法则

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#230]
原文链接：[RICE: SIMPLE PRIORITIZATION FOR PRODUCT MANAGERS](https://blog.intercom.io/rice-simple-prioritization-for-product-managers/)
掘金链接：[RICE - 给产品经理的简易优先级法则](http://gold.xitu.io/entry/56fa3672d342d3005c8333ac)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/rice-simple-prioritization-for-product-managers.md)

翻译时间：5天
校对时间：3天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by ZhaofengWu** [comment]
认领翻译

**Comment by antonia0912** [comment]
@ZhaofengWu markdown文件已经添加 请注意翻译时间，表超过5天喔~

**Comment by lynulzy** [comment]
认领校对

**Comment by antonia0912** [comment]
@lynulzy 好的 [校对地址](https://github.com/xitu/gold-miner/pull/237/files?diff=split) ，不清楚的可以参照其他译文的校对方法来校对，也可以[看这里](https://github.com/xitu/gold-miner/blob/master/README.md) ， 校对完成后记得在下边留言“校对完成”，再有不明白的可以在群里问大家或者圈我，加油！

**Comment by lynulzy** [comment]
收到

**Comment by dongpeiguo** [comment]
认领校对

**Comment by dongpeiguo** [comment]
@antonia0912  群里大神说要艾特羊羊羊

**Comment by antonia0912** [comment]
@dongpeiguo 嘿嘿嘿  妹子收到啦 [校对地址](https://github.com/xitu/gold-miner/pull/237/files?diff=split)

**Comment by ZhaofengWu** [comment]
修改完成
