### ISSUE TITLE
webpack & HTTP/2

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2300]
* 原文链接：[webpack & HTTP/2](https://medium.com/webpack/webpack-http-2-7083ec3f3ce6)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/webpack-http-2.md)
  * PR 地址：#2301
  * 文章分类：**前端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@Aladdin-ADD

**Comment by Aladdin-ADD** [comment]
翻译认领。 🍺  @leviding

**Comment by leviding** [comment]
好的呢
