### ISSUE TITLE
The Right Way to Bundle Your Assets for Faster Sites over HTTP/2

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2302]
* 原文链接：[The Right Way to Bundle Your Assets for Faster Sites over HTTP/2](https://medium.com/@asyncmax/the-right-way-to-bundle-your-assets-for-faster-sites-over-http-2-437c37efe3ff)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-right-way-to-bundle-your-assets-for-faster-sites-over-http-2.md)
  * PR 地址：待添加
  * 文章分类：**后端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@Aladdin-ADD 你的

**Comment by Aladdin-ADD** [comment]
翻译认领。 :)

**Comment by fanyijihua** [comment]
@Aladdin-ADD 棒极啦 :tada:

**Comment by yct21** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@yct21 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2373
