### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by terrykingcha** [xitu/gold-miner#2303]
- 原文链接：https://hacks.mozilla.org/2017/10/the-whole-web-at-maximum-fps-how-webrender-gets-rid-of-jank/
- 简要介绍：Moziila在最新的Quantum Render Project引入了让Web渲染变的非常轻薄的新技术（WebRender），文中着重科普了Web渲染的主要流程和WebRender技术的改进已经特点。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
你是要认领这篇吗，是的话，我放上去之后艾特你

**Comment by terrykingcha** [comment]
@leviding 我是推荐这篇，没时间精力认领翻译，抱歉哈:-)

**Comment by leviding** [comment]
哈哈，感谢推荐。我就是问问，感谢支持！
