### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by undead25** [xitu/gold-miner#2304]
- 原文链接：<https://medium.freecodecamp.org/8-key-react-component-decisions-cc965db11594>
- 简要介绍：在选择 React 技术栈（组件）的时候我们要做很多选型，文章介绍了  8 个主要的。最重要的是提供了统计数据，这有助于我们选型时提供参考。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢，明天放上去。@undead25
