### ISSUE TITLE
Javascript 中各种各样的 this

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2309]
* 原文链接：[The many faces of `this` in javascript](https://blog.pragmatists.com/the-many-faces-of-this-in-javascript-5f8be40df52e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-many-faces-of-this-in-javascript.md)
  * PR 地址：待添加
  * 文章分类：**前端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2316
