### ISSUE TITLE
设计师如何跟开发打好关系？

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#231]
原文链接：[Design Systems Ops](https://medium.com/salesforce-ux/introducing-design-systems-ops-7f34c4561ba7#.iumcuwu3v)
掘金链接：[设计师如何跟开发打好关系？](http://gold.xitu.io/entry/56f51a12128fe1005196a5ad)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/introducing-design-systems-ops.md)

翻译时间：5天
校对时间：3天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Sausure** [comment]
三只羊，我来哈

**Comment by antonia0912** [comment]
@Sausure 好的  等你 PR 哈

**Comment by Sausure** [comment]
这篇文章俚语好多，挑战好大，申请换人。。。

**Comment by antonia0912** [comment]
@Sausure 没关系的

**Comment by L9m** [comment]
我来认领

**Comment by antonia0912** [comment]
@L9m 好的  注意翻译时间限制喔

**Comment by Ruixi** [comment]
这篇还需要校对吗？

**Comment by antonia0912** [comment]
@Ruixi 需要校对的  [校对地址](https://github.com/xitu/gold-miner/pull/296/files?diff=split)

**Comment by Ruixi** [comment]
好好好下班就开工～

**Comment by Ruixi** [comment]
完成，前面两位已经把问题说的差不多了……觉得我也没啥可提的了……
