### ISSUE TITLE
Performance metrics. What’s this all about?

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2312]
* 原文链接：[Performance metrics. What’s this all about?](https://codeburst.io/performance-metrics-whats-this-all-about-1128461ad6b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/performance-metrics-whats-this-all-about.md)
  * PR 地址：待添加
  * 文章分类：**前端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by llp0574** [comment]
领了

**Comment by leviding** [comment]
@llp0574 发关键字哈，否则触发不了。

![image](https://user-images.githubusercontent.com/26959437/31487121-484e8106-af6c-11e7-8621-d45eb905b7d5.png)

**Comment by llp0574** [comment]
@leviding 改了哈哈

**Comment by leviding** [comment]
@llp0574 别改，重新发一个

**Comment by llp0574** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@llp0574 棒极啦 :tada:

**Comment by leviding** [comment]
@llp0574 ok 了，哈哈。

**Comment by llp0574** [comment]
@leviding 厉害了，好久没过来翻了哈哈

**Comment by leviding** [comment]
@llp0574 欢迎回归，撒花

**Comment by fanyijihua** [comment]
PR 地址：#2341

**Comment by ppp-man** [comment]
校对认领
