### ISSUE TITLE
如何为通知设计更好的用户体验

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2313]
* 原文链接：[How To Design Notifications For Better UX](https://uxplanet.org/how-to-design-notifications-for-better-ux-6fb0711be54d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-design-notifications-for-better-ux.md)
  * PR 地址：#2366
  * 文章分类：**设计**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@dongpeiguo

**Comment by dongpeiguo** [comment]
翻译认领~么么哒

**Comment by fanyijihua** [comment]
@dongpeiguo 棒极啦 :tada:

**Comment by leviding** [comment]
@dongpeiguo 你好啊，你的 Pull request 地址弄错了，应该 PR 到这个仓库，不是你自己的仓库
