### ISSUE TITLE
CSV 注入：被人低估的风险

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2314]
* 原文链接：[The Absurdly Underestimated Dangers of CSV Injection](http://georgemauer.net/2017/10/07/csv-injection.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/csv-injection.md)
  * PR 地址：#2349
  * 文章分类：**后端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mnikn** [comment]
@leviding 翻译认领～

**Comment by fanyijihua** [comment]
@mnikn 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2349
