### ISSUE TITLE
推荐优秀英文文章 The whole web at maximum FPS: How WebRender gets rid of jank

### ISSUE THREAD

**Issue by hikerpig** [xitu/gold-miner#2318]
原文链接：https://hacks.mozilla.org/2017/10/the-whole-web-at-maximum-fps-how-webrender-gets-rid-of-jank/
简要介绍：介绍了浏览器渲染的流程，以及 Firefox 团队下 WebRender 对应的一些技术细节

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
这篇有小伙伴推荐了，正在整理中，尽快发布，反写您的推荐 ❤️
