### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by GreenLim** [xitu/gold-miner#2319]
- 公司/学校：蚂蚁
- 工作内容/专业：开发
- 常浏览的国外网站：medium/hackernoon
- 英语水平：还好。。
- 有无翻译经验：有翻译文章经验
- 个人博客：无
- 个人介绍：热爱开源、热爱分享

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
