### ISSUE TITLE
我们应该更多地喜欢那些「丑、混乱」但是好用的界面

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#232]
原文链接：[Why I love ugly, messy interfaces — and you probably do too](https://m.signalvnoise.com/why-i-love-ugly-messy-interfaces-and-you-probably-do-too-edff4a896a83#.9ktye0b9m)
掘金链接：[我们应该更多地喜欢那些「丑、混乱」但是好用的界面](http://gold.xitu.io/entry/57072cf8c4c9710051701749)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/why-i-love-ugly-messy-interfaces-and-you-probably-do-too.md)

翻译时间：5天
校对时间：3天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by circlelove** [comment]
认！

**Comment by Jonwei** [comment]
被人抢先了啊？
建议中文译名：让产品形态来决定产品界面

**Comment by antonia0912** [comment]
@circlelove 好的  注意细节还有翻译时间

**Comment by antonia0912** [comment]
@Jonwei 可以来校对  @circlelove 翻译完记得圈这位译者来校对哈

**Comment by circlelove** [comment]
好的杨哥

**Comment by antonia0912** [comment]
@Jonwei 译者翻译完了  可以去校对了喔  [校对地址](https://github.com/xitu/gold-miner/pull/244/files?diff=split)

**Comment by Ruixi** [comment]
求校对～

**Comment by antonia0912** [comment]
@Ruixi 好的睿奚， [校对地址](https://github.com/xitu/gold-miner/pull/244/files?diff=split)，直接加note就可以啦

**Comment by Jonwei** [comment]
@antonia0912 好的。

**Comment by Jonwei** [comment]
@circlelove  已经尝试校对了一遍了。建议将中文部分摘出来成一个文章，然后朗读几遍。朗读过程中，对我们给得建议的部分，或者读起来觉得不顺畅的，尝试重新翻译下。

**Comment by Ruixi** [comment]
@circlelove 校对完毕，主要对一些设计相关词汇和行文语气给了点建议。觉得原作者的文风是带一点俏皮的那种嗯··· ···

另外Pinterest coffeeshop fever dream这几个词组合在一起啥意思我真是没懂··· ···

**Comment by antonia0912** [comment]
辛苦两位校对者 @Jonwei @Jonwei ， 请译者 @circlelove 根据校对者意见进行修改完善，注意细节喔~

**Comment by circlelove** [comment]
@antonia0912  收到！ 责令自己晚上整改·

**Comment by muzidx** [comment]
认领校对

**Comment by antonia0912** [comment]
@muzidx 要注意看label喔  这个的label是正在校对，说明已经有两位校对者了，要去选那种有校对认领的label的文章
