### ISSUE TITLE
5 Step Life-Cycle for Neural Network Models in Keras

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2322]
* 原文链接：[5 Step Life-Cycle for Neural Network Models in Keras](https://machinelearningmastery.com/5-step-life-cycle-neural-network-models-keras/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/5-step-life-cycle-neural-network-models-keras.md)
  * PR 地址：#2326
  * 文章分类：**机器学习**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@CACppuccino

**Comment by lsvih** [comment]
翻译认领，马上完成

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by CACppuccino** [comment]
好快TAT

**Comment by leviding** [comment]
@CACppuccino 哈哈，还有没有想翻译的，我加班呢，可以马上推

**Comment by CACppuccino** [comment]
有的有的~~~

**Comment by fanyijihua** [comment]
PR 地址：#2326

**Comment by lsvih** [comment]
@CACppuccino 啊！实在抱歉。。。我没注意到是您推的文章然后提前认领了。。看到老本行一激动直接就认领掉了。。。

**Comment by lsvih** [comment]
@CACppuccino 已经完成了，要不您来校对这篇。。

**Comment by CACppuccino** [comment]
@lsvih 哈哈没事的没事的
