### ISSUE TITLE
算法文章推荐

### ISSUE THREAD

**Issue by CACppuccino** [xitu/gold-miner#2323]
http://www.cameronius.com/research/mcts/about/index.html

蒙特卡洛树搜索，比较清晰的overview

**Comment by leviding** [comment]
收到，我现在处理哈

**Comment by leviding** [comment]
咦，这篇被翻译了。详见：http://mobile.acfun.cn/a/ac2594826

**Comment by CACppuccino** [comment]
唔~~~那我再找找~~
