### ISSUE TITLE
ES6 中的元编程： 第三部分 - 代理（Proxies）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2324]
* 原文链接：[Metaprogramming in ES6: Part 3 - Proxies](https://www.keithcirkel.co.uk/metaprogramming-in-es6-part-3-proxies/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/metaprogramming-in-es6-part-3-proxies.md)
  * PR 地址：待添加
  * 文章分类：**前端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@yoyoyohamapi

**Comment by yoyoyohamapi** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@yoyoyohamapi 棒极啦 :tada:

**Comment by yoyoyohamapi** [comment]
@Leviding

**Comment by ParadeTo** [comment]
怎么认领校对？

**Comment by leviding** [comment]
@ParadeTo https://github.com/xitu/gold-miner/wiki/%E5%8F%82%E4%B8%8E%E6%A0%A1%E5%AF%B9%E7%9A%84%E6%AD%A3%E7%A1%AE%E5%A7%BF%E5%8A%BF

**Comment by leviding** [comment]
@yoyoyohamapi 翻译怎么样了

**Comment by yoyoyohamapi** [comment]
@leviding 还在继续啊，公司最近业务比较忙

**Comment by leviding** [comment]
嗯嗯
