### ISSUE TITLE
什么是蒙特卡洛树搜索

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2325]
* 原文链接：[What is MCTS?](http://www.cameronius.com/research/mcts/about/index.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-is-mcts.md)
  * PR 地址：#2331
  * 文章分类：**AI**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 + 1 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@CACppuccino

**Comment by leviding** [comment]
这篇文章翻译得时候，需要译者进到原文把文中图片进行转存（也就是上传图床）然后更新文中图片链接。

完成图片转存，在 3 分基础上加 1 个奖励积分哈

**Comment by CACppuccino** [comment]
哈哈好的呢

**Comment by leviding** [comment]
用关键词认领哈 @CACppuccino

**Comment by CACppuccino** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@CACppuccino 棒极啦 :tada:

**Comment by CACppuccino** [comment]
@leviding 是只要最后在掘金发的时候转存图片就可以了吧？

**Comment by leviding** [comment]
@CACppuccino 掘金发文的那个转存不好使，需要你手动转一下，然后更新本 MarkDown 中的相关图片链接。
