### ISSUE TITLE
ES6 中的元编程：第二部分 —— 反射（Reflect）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2327]
* 原文链接：[Metaprogramming in ES6: Part 2 - Reflect](https://www.keithcirkel.co.uk/metaprogramming-in-es6-part-2-reflect/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/metaprogramming-in-es6-part-2-reflect.md)
  * PR 地址：#2470
  * 文章分类：**前端**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@yoyoyohamapi

**Comment by yoyoyohamapi** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@yoyoyohamapi 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2470
