### ISSUE TITLE
On Performant Arrays in Swift

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2329]
* 原文链接：[On Performant Arrays in Swift](http://jordansmith.io/on-performant-arrays-in-swift/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/on-performant-arrays-in-swift.md)
  * PR 地址：#2350
  * 文章分类：**iOS**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2.5 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jingzhilehuakai** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jingzhilehuakai 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2350
