### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by AhianZhang** [xitu/gold-miner#2332]
- 公司/学校：河北外国语学院
- 工作内容/专业：软件工程专业 擅长java
- 常浏览的国外网站：Twitter  Quora  YouTube StackOverflow  Google+
- 英语水平：基础
- 有无翻译经验：无
- 个人博客：www.richmanroad.top
- 个人介绍：一直关注互联网技术发展方向，对于学习抱有持续热情，今年大四马上毕业。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
