### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ts5210ts** [xitu/gold-miner#2334]
- 公司/学校：天津智冠科技有限公司
- 工作内容/专业：Android应用开发/信息管理与信息系统
- 常浏览的国外网站：https://stackoverflow.com/
- 英语水平：4级
- 有无翻译经验：无
- 个人博客：https://juejin.im/user/58823651b123db75e093b493
- 个人介绍：主职安卓，目标大前端。无翻译经验，对英语不排除，有兴趣。希望加入！

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
