### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ZhangCheng-zh** [xitu/gold-miner#2335]
- 公司/学校：网易/北京大学
- 工作内容/专业：前端/地图学与地理信息系统
- 常浏览的国外网站：medium/instagram
- 英语水平：六级550/考研72
- 有无翻译经验：有写过sci论文
- 个人博客：无
- 个人介绍：北京大学理科硕士，平时学术和写代码的英语水平还不错

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
