### ISSUE TITLE
小建议：是否考虑增加视频栏目和 PDF 栏目

### ISSUE THREAD

**Issue by kobehaha** [xitu/gold-miner#2337]
提小小的建议:

可以考虑

1 增加视频栏目,国外很多公司分享都在YouTube 例如 https://www.youtube.com/watch?v=jgVhBThJdXc
2 增加pdf栏目，很多公司分享都用pdf 例如: https://talks.golang.org/2015/go-gc.pdf , https://talks.golang.org/2010/gofrontend-gcc-summit-2010.pdf 这样

可以丰富一下类型

**Comment by leviding** [comment]
增加栏目的意思是？增加相应翻译吗？

**Comment by kobehaha** [comment]
我的理解是现在这个平台是一个分享知识的平台，现在最热的功能是在线翻译国外的优质文献。知识共享可以再多元化一些，例如另外建一个repository 专门整理一些优质视频，例如阿里云栖大会，google/io大会等等内容，而往往这些视频都会有相关的pdf,这一部分可以相关联。如果国外pdf 可以增加翻译, 将pdf 转换成 图片 ,然后在原文上注释一些关键性解释，不过这可能对降低阅读性。

我这是最简单的建议，只是昨天逛社区突然想到这样一个点，还有很多地方没有考虑,谢谢

**Comment by leviding** [comment]
是个很好的想法呢，只不过现在网上有很多类似的书单整理、学习资料整理。不知道咱们这的译者们是否有兴趣弄这个。

您有什么想要推荐的吗？欢迎在本项目 `TODO` 文件夹里新建文件发 PR，如果真的稍具规模，则考虑新建 repo。感谢支持！:heart:

**Comment by kobehaha** [comment]
好的，谢谢。
