### ISSUE TITLE
Key Reinstallation Attacks: Breaking WPA2 by forcing nonce reuse

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2339]
* 原文链接：[Key Reinstallation Attacks: Breaking WPA2 by forcing nonce reuse](https://www.krackattacks.com/?from=groupmessage&isappinstalled=0#faq)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/breaking-wpa2-by-forcubg-nonce-reuse.md)
  * PR 地址：
  * 文章分类：**安全**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
有译者翻译完了，待其来走流程

**Comment by fengsehng** [comment]
认领本篇

**Comment by leviding** [comment]
在要认领的文章 Issue 下发送 `翻译认领` 或 `认领翻译` @fengsehng

**Comment by fengsehng** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@fengsehng 棒极啦 :tada:
