### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by redman9** [xitu/gold-miner#2340]
- 公司/学校：杭州新麦科技有限公司／华北水利水电大学
- 工作内容/专业：前端／电子科学与技术
- 常浏览的国外网站：stackoverflow、medium
- 英语水平：大学六级，参与过考研（分数忘了）
- 有无翻译经验：无，自己尝试翻译过文章
- 个人博客：无
- 个人介绍：两年前端经验，平时阅读英文文章总有种想要去翻译的冲动

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
