### ISSUE TITLE
并发编程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2342]
* 原文链接：[Concurrent programming](https://www.nada.kth.se/~snilsson/concurrency/#Parallel)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/concurrent-programming.md)
  * PR 地址：#2362
  * 文章分类：**后端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@kobehaha 你的

**Comment by kobehaha** [comment]
好的

**Comment by leviding** [comment]
好的呢
