### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by china2015wyp** [xitu/gold-miner#2343]
- 公司/学校：软通动力/西安工业大学
- 工作内容/专业：前端、h5、react开发
- 常浏览的国外网站：github、npm、letcode等
- 英语水平：四级--六级之间
- 有无翻译经验：有（经验一般）
- 个人博客：暂无
- 个人介绍：本人爱好运动，喜欢英语，大多时间都泡在网上！

**Comment by china2015wyp** [comment]
希望能为社区尽一份力，不仅能服务大家还能提高自己！

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
