### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by yct21** [xitu/gold-miner#2344]
- 公司/学校：NSN / 华东师范大学
- 工作内容/专业：前端开发, web 开发
- 常浏览的国外网站：reddit, stackoverflow, Github
- 英语水平：CET6, 熟练阅读英文技术文档
- 有无翻译经验：参与过虎扑翻译团
- 个人博客：无
- 个人介绍：热爱新技术, 热爱开源社区

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
