### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by wann-he** [xitu/gold-miner#2346]
- 公司/学校：陕西卡漠网络科技有限公司/西安电子科技大学
- 工作内容/专业：java后台开发/计算机科学与技术
- 常浏览的国外网站：google,instagram,stackoverflow,etc.
- 英语水平：大学英语四级
- 有无翻译经验：无
- 个人博客：暂无
- 个人介绍：性别男，宅，工作1.5年，希望能在业余时间提升自己

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
