### ISSUE TITLE
React 组件的 8 个关键决策

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2347]
* 原文链接：[8 Key React Component Decisions: Standardize your React development with these key decisions](https://medium.freecodecamp.org/8-key-react-component-decisions-cc965db11594)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/8-key-react-component-decisions.md)
  * PR 地址：#2364
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by undead25** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@undead25 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2364

**Comment by smileforward123** [comment]
@leviding 认领校对
