### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zhxsh** [xitu/gold-miner#2351]
- 公司/学校：金蝶软件有限公司/广州中医药大学
- 工作内容/专业：前端工程师/计算机科学与技术
- 常浏览的国外网站：https://webpack.js.org/
- 英语水平：4级
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：希望通过翻译帮助大家，也帮助自己

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
