### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by smileforward123** [xitu/gold-miner#2352]
- 公司/学校：公司：中国网库股份有限公司/河南省安阳师范学院
- 工作内容/专业：前端开发工程师/计算机科学与技术
- 常浏览的国外网站：
- 英语水平：CET 6
- 有无翻译经验：无经验
- 个人博客：
- 个人介绍：前端开发工程师，一枚乐观，细心，热情，爱学习，钻研前端开发技术，不断成长的前端程序媛！

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』

**Comment by gzponline** [comment]
学校：合肥工业大学
工作内容/专业：前端开发工程师/计算机科学与技术
常浏览的国外网站：MDN github W3C 
英语水平：CET 6
有无翻译经验：无经验
个人博客：gzponline.github.io
个人介绍：前端小白

**Comment by leviding** [comment]
@gzponline Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
