### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Aceyclee** [xitu/gold-miner#2353]
- 公司/学校：河海大学
- 工作内容/专业：计算机科学与技术
- 常浏览的国外网站：Medium、Hacknews、湾区日报
- 英语水平：CET-6
- 有无翻译经验：有
- 个人博客：知乎主页：https://www.zhihu.com/people/Aceyclee/activities
- 个人介绍：拍照挺好看

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』

**Comment by leviding** [comment]
哈哈，刚刚知乎关注你了

**Comment by achilleo** [comment]
欢迎大佬~
