### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by charsdavy** [xitu/gold-miner#2357]
公司/学校：@ZAKER/西安科技大学
工作内容/专业：iOS
常浏览的国外网站：github，objc.io
英语水平：CET-4
有无翻译经验：有
个人博客：http://chars.tech
个人介绍：现从事iOS开发

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
