### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zcgeng** [xitu/gold-miner#2358]
- 公司/学校：复旦大学
- 工作内容/专业：计算机科学技术
- 常浏览的国外网站：GitHub, LeetCode, Google, YouTube, Facebook, Amazon, 各种常用网站。。。
- 英语水平：TOEFL 97
- 有无翻译经验：翻译过三篇微电子方面的专利，中翻英，总字数超过十万汉字
- 个人博客：[www.zcgeng.space](http://www.zcgeng.space)
- 个人介绍：复旦大学CS专业大四在校生，感兴趣的方向为分布式系统、数据库、深度学习等。在纽约大学有过交流经验，希望能做出我的贡献！

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
