### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by sasa-m** [xitu/gold-miner#2359]
- 公司/学校：江西师范大学
- 工作内容/专业：信息管理和信息系统
- 常浏览的国外网站：google,stackoverflow.com,github,youtube
- 英语水平：cet-4
- 有无翻译经验：无
- 个人博客：http://sasa.leanote.com/
- 个人介绍：不宅不闹，想努力做个优秀的程序员

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
