### ISSUE TITLE
用户体验思考：好的应用推送应该如何发送？

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#236]
原文链接：[Mobile UX Design: What Makes a Good Notification?](https://uxplanet.org/how-to-craft-mobile-notifications-that-users-actually-want-7b585e0e1fa1#.z4z05lc5u)
掘金链接：[用户体验思考：好的应用推送应该如何发送？](http://gold.xitu.io/entry/56f8ad4a39b0570054042807)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-craft-mobile-notifications-that-users-actually-want.md)

翻译时间：5天
校对时间：3天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by shenxn** [comment]
认领！

**Comment by antonia0912** [comment]
@shenxn OK

**Comment by antonia0912** [comment]
小朋友我找到那个译文了  这个issue就删掉了哈  一会上传新文章  你重新去选一篇哈  sorry  欧尼错了
