### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by caomengsi** [xitu/gold-miner#2363]
- 公司/学校：美团/中国传媒大学
- 工作内容/专业：前端开发/计算机应用技术
- 常浏览的国外网站：Google/stackoverflow/大数据的一些官网
- 英语水平：英语六级/本科英语双学位
- 有无翻译经验：无
- 个人博客：http://www.jianshu.com/u/b8f9de680a08
- 个人介绍：知识没有边界，我只想好好了解这个世界。一个正在前端世界打滚的程序媛。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
