### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by winjeysong** [xitu/gold-miner#2375]
- 公司/学校：浙江工业大学
- 工作内容/专业：机械自动化
- 常浏览的国外网站：medium, mdn, npm
- 英语水平：英语六级 580+
- 有无翻译经验：无
- 个人博客：winjeysong.com
- 个人介绍：机械转前端的小白，希望通过翻译接触到更多前端新知识

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
