### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by boileryao** [xitu/gold-miner#2377]
- 原文链接：https://guides.codepath.com/android/handling-scrolls-with-coordinatorlayout
- 简要介绍：滑动的处理是 Android 的重要部分，CoordinatorLayout 是对嵌套滑动的封装。使用
 CoordinatorLayout 处理滑动很有价值。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢您的推荐，文章会尽快发布 :gift_heart:
