### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by MarkoCen** [xitu/gold-miner#2378]
- 公司/学校：NetBrain Technologies
- 工作内容/专业：js全栈, C#.Net
- 常浏览的国外网站：github, medium, twitter, pony foo, david walsh, scotch.io ....
- 英语水平：工作为全英语环境，听说可以达到流利水平
- 有无翻译经验：平日阅读很多，但基本没有翻译经验，想通过这个项目锻炼下
- 个人博客：markocen.com
- 个人介绍：

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
