### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ParadeTo** [xitu/gold-miner#2379]
- 公司/学校： 深圳极视角科技有限公司
- 工作内容/专业： 前端工程师
- 常浏览的国外网站： github, stackoverflow
- 英语水平： 6级
- 有无翻译经验： 有
- 个人博客： www.paradeto.com
- 个人介绍： 英语阅读良好，研究生期间发表过英文文献(http://www.mdpi.com/2072-4292/5/7/3190)，特别想通过从事该翻译工作提升自己的专业能力和英语水平

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
