### ISSUE TITLE
为什么 Spotify 的付费转化率如此之高？

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#238]
原文链接：[Freemium Conversion Rate: Why Spotify Destroys Dropbox by 667%](https://www.process.st/freemium-conversion-rate/)
掘金链接：[为什么 Spotify 的付费转化率如此之高？](http://gold.xitu.io/entry/5704b3c171cfe4005dc5c0b9)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/freemium-conversion-rate.md)

翻译时间：5天
校对时间：3天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by SatanWoo** [comment]
我认领!!

**Comment by antonia0912** [comment]
@SatanWoo 好的

**Comment by iThreeKing** [comment]
认领校对 @antonia0912 @SatanWoo

**Comment by antonia0912** [comment]
@iThreeKing 收到三金 话说三金你头像奇奇丑  我会看到一次说一次的（冷漠脸）

**Comment by DeadLion** [comment]
认领校对

**Comment by antonia0912** [comment]
@DeadLion 好的 [校对地址](https://github.com/xitu/gold-miner/pull/278/files?diff=split)
