### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by scaret** [xitu/gold-miner#2382]
- 公司/学校：Agora.io
- 工作内容/专业：前端/全栈/信息安全
- 常浏览的国外网站：xxxxhub, 湾区日报
- 英语水平：一般吧
- 有无翻译经验：翻译并出版《JavaScript面向对象编程指南》和《Python算法教程》
- 个人博客：无
- 个人介绍：普通程序员

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
