### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by icetum15** [xitu/gold-miner#2385]
- 公司/学校：兔狗科技／浙江工业大学
- 工作内容/专业：android开发／计算机科学与技术
- 常浏览的国外网站：GitHub／https://stackoverflow.com
- 英语水平：英语六级／雅思5.5
- 有无翻译经验：无
- 个人博客：http://blog.csdn.net/ice_tum15
- 个人介绍：希望参与项目后能够提高主动浏览英文文献的习惯

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
