### ISSUE TITLE
ProGuard 在 Android 上的使用姿势

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2387]
* 原文链接：[Troubleshooting ProGuard issues on Android](https://medium.com/google-developers/troubleshooting-proguard-issues-on-android-bce9de4f8a74)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/troubleshooting-proguard-issues-on-android.md)
  * PR 地址：#3014
  * 文章分类：**Android**
  * **注：本文为 Google 约稿，由他们将文章发布在掘金。译者可以发布在自己博客等处。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：2 分 corresponding 3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by dieyidezui** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@dieyidezui 棒极啦 :tada:

**Comment by JayZhaoBoy** [comment]
翻译认领

**Comment by leviding** [comment]
@JayZhaoBoy Sorry，本文已被认领，请认领或者校对其他文章。

**Comment by leviding** [comment]
@dieyidezui 翻译的怎么样了

**Comment by leviding** [comment]
@dieyidezui 翻译的怎么样了

**Comment by IllllllIIl** [comment]
@leviding  这篇我之前自己翻译过一些了,但看到被认领了就没再翻译,如果他还没翻译,要我来替他翻吗

**Comment by dieyidezui** [comment]
@IllllllIIl 多谢好意，我今晚会翻译完提交的~

**Comment by dieyidezui** [comment]
@leviding 实在不好意思哈，GitHub很少上，没看到消息。这次翻译不要算我积分好了~是我的锅

**Comment by fanyijihua** [comment]
PR 地址：#3014

**Comment by leviding** [comment]
哈哈哈，正常来吧。辛苦啦
