### ISSUE TITLE
ViewModel 和 LiveData：为设计模式打 Call 还是唱反调？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2388]
* 原文链接：[ViewModels and LiveData: Patterns + AntiPatterns](https://medium.com/google-developers/viewmodels-and-livedata-patterns-antipatterns-21efaef74a54)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/viewmodels-and-livedata-patterns-antipatterns.md)
  * PR 地址：
  * 文章分类：**Android**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by boileryao** [comment]
认领翻译 @leviding

**Comment by fanyijihua** [comment]
@boileryao 棒极啦 :tada:
