### ISSUE TITLE
在 Android O 上用到 MediaStyle 的提醒功能

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2389]
* 原文链接：[Migrating MediaStyle notifications to support Android O](https://medium.com/google-developers/migrating-mediastyle-notifications-to-support-android-o-29c7edeca9b7)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/migrating-mediastyle-notifications-to-support-android-o.md)
  * PR 地址：#2400
  * 文章分类：**Android**
  ----
  * 翻译时间：1 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
@ppp-man 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2400
