### ISSUE TITLE
ViewModel：持久化、onSaveInstanceState()、UI 状态恢复和 Loader

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2390]
* 原文链接：[ViewModels: Persistence, onSaveInstanceState(), Restoring UI State and Loaders](https://medium.com/google-developers/viewmodels-persistence-onsaveinstancestate-restoring-ui-state-and-loaders-fc7cc4a6c090)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/viewmodels-persistence-onsaveinstancestate-restoring-ui-state-and-loaders.md)
  * PR 地址：#2434
  * 文章分类：**Android**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Feximin** [comment]
认领

**Comment by leviding** [comment]
翻译认领

**Comment by leviding** [comment]
认领翻译
