### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by superxieshushu** [xitu/gold-miner#2391]
- 公司/学校：数梦工场 / 香港浸会大学
- 工作内容/专业：Android开发 / 计算机科学与技术
- 常浏览的国外网站：Github、Android Developers、stackoverflow
- 英语水平：雅思 6 
- 有无翻译经验：无
- 个人博客：https://juejin.im/user/5899b919128fe1006cc3edae/collection
- 个人介绍：一个做了两年Android开发的程序狗。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
