### ISSUE TITLE
ViewModels 简单入门指北

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2393]
* 原文链接：[ViewModels : A Simple Example](https://medium.com/google-developers/viewmodels-a-simple-example-ed5ac416317e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/viewmodels-a-simple-example.md)
  * PR 地址：#2405
  * 文章分类：**Android**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by huanglizhuo** [comment]
认领 @leviding

**Comment by fanyijihua** [comment]
PR 地址：#2405
