### ISSUE TITLE
14 个你可能不知道的 JavaScript 调试技巧

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2397]
* 原文链接：[The 14 JavaScript debugging tips you probably didn't know](https://raygun.com/javascript-debugging-tips)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/javascript-debugging-tips.md)
  * PR 地址：#2404
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ParadeTo** [comment]
@leviding 认领

**Comment by leviding** [comment]
好的，下次注意回复关键字 `翻译认领` 或 `认领翻译`。

**Comment by fanyijihua** [comment]
PR 地址：#2404
