### ISSUE TITLE
五天拿下硅谷五家顶级互联网公司 offer

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2399]
* 原文链接：[I interviewed at five top companies in Silicon Valley in five days, and luckily got five job offers](https://medium.com/@XiaohanZeng/i-interviewed-at-five-top-companies-in-silicon-valley-in-five-days-and-luckily-got-five-job-offers-25178cf74e0f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/i-interviewed-at-five-top-companies-in-silicon-valley-in-five-days-and-luckily-got-five-job-offers.md)
  * PR 地址：
  * 文章分类：**阅读**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
这篇有人啦

**Comment by freerambo** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@freerambo 棒极啦 :tada:
