### ISSUE TITLE
认领“每个 Android 开发者都应该读的 Android Studio Tips”

### ISSUE THREAD

**Issue by laobie** [xitu/gold-miner#24]
之前我已经翻译了一大半了，正好看到这个，翻译完更加有动力了，希望审核通过。

**Comment by Glowin** [comment]
真不错，这篇文章里面有五十多个 tips，你已经翻译多少了呢？

欢迎加入组织 :+1:

**Comment by laobie** [comment]
我已经翻译到30了～

**Comment by Glowin** [comment]
赞，你可以把这50个 tips 放在这个文章的 markdown 文件下面（包括图片链接），期待你的 PR。
