### ISSUE TITLE
Why Building Community Is the New “Growth Hack”

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#240]
原文链接：[Why Building Community Is the New “Growth Hack”](http://thehustle.co/why-building-community-is-the-new-growth-hack)
掘金链接：[Why Building Community Is the New “Growth Hack”](http://gold.xitu.io/entry/570c97278ac2470064227719)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/why-building-community-is-the-new-growth-hack.md)

翻译时间：5天
校对时间：3天
翻译积分：8
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by geeeeeeeeek** [comment]
认领

**Comment by antonia0912** [comment]
@geeeeeeeeek 得嘞！！

**Comment by geeeeeeeeek** [comment]
@antonia0912 翻译终于完成了！

**Comment by antonia0912** [comment]
@geeeeeeeeek 收到！ 辛苦啦~

**Comment by godofchina** [comment]
申请校对

**Comment by godofchina** [comment]
@antonia0912 申请校对

**Comment by antonia0912** [comment]
@godofchina 好的  老方法~

**Comment by antonia0912** [comment]
@godofchina honey 另一位校对者已经校对完成咯  就等你啦 [校对地址](https://github.com/xitu/gold-miner/pull/287/files?diff=split)

**Comment by godofchina** [comment]
@godofchina 收到 懒病又犯了 ..

**Comment by godofchina** [comment]
@antonia0912  校对完毕
