### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by crossoverJie** [xitu/gold-miner#2402]
- 公司/学校：亚信科技
- 工作内容/专业：Java后端工程师
- 常浏览的国外网站：GitHub Medium 
- 英语水平：CET - 4
- 有无翻译经验：无
- 个人博客：https://crossoverjie.top
- 个人介绍：热爱coding,热爱开源。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
