### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by oaosj** [xitu/gold-miner#2407]
- 公司/学校：高菲云智科技有限公司
- 工作内容/专业：android音视频、iOS
- 常浏览的国外网站： medium 、twitter、google blog、stackoverflow、ins、
- 英语水平：4~6级
- 有无翻译经验：有，但是少。
- 个人博客：http://www.jianshu.com/u/feeb8b74656a
- 个人介绍：一直从事android开发，去年智能家居类网络通信，近一年音视频编解码。偶尔参与下iOS。关于掘金的，去年五~十月在掘金分享文章，参加了一次掘金线下、今天码到这个点儿了，去年在社区还算活跃，今年工作原因把，只是自己消化理解知识了，现在又想分享一些，申请

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
