### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by AhianZhang** [xitu/gold-miner#2408]
- 原文链接：http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html
- 简要介绍：thymeleaf的使用文档，国内应该是没有完全对应的翻译。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢推荐，我看了下这个东西，量有点大，最近翻译计划在全力翻译 TensorFlow 文档和 Vue 2017 报告。这个我先记下了，有空的时候翻译。
