### ISSUE TITLE
用工厂流水线的方式来理解 RxJava 的概念

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#241]
原文链接：[RxJava – the production line](http://www.thedroidsonroids.com/blog/android/rxjava-production-line/)
掘金链接：[用工厂流水线的方式来理解 RxJava 的概念](http://gold.xitu.io/entry/570c909b2e958a0069c8925f)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/rxjava-production-line.md)

翻译时间：5天
校对时间：3天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Sausure** [comment]
羊三，我看了下，这篇文章我会翻译，我认领了哈，多谢啦

**Comment by antonia0912** [comment]
@Sausure 好的  这篇拿去吧  嘿嘿

**Comment by Sausure** [comment]
翻译完成，PR地址：https://github.com/xitu/gold-miner/pull/265

**Comment by antonia0912** [comment]
@Sausure 好的 我来联系校对者

**Comment by huanglizhuo** [comment]
认领校对 @antonia0912

**Comment by antonia0912** [comment]
@huanglizhuo 好的 [校对地址](https://github.com/xitu/gold-miner/pull/265/files?diff=split)

**Comment by huanglizhuo** [comment]
第一遍校对完成 @Sausure

**Comment by rockzhai** [comment]
申请校对 @antonia0912

**Comment by antonia0912** [comment]
@rockzhai 请问是我们翻译计划的译者咩  不是的话要先发译者申请喔  发完译者申请我来拉你进译者群 [翻译计划怎么玩点这里](https://github.com/xitu/gold-miner/blob/master/README.md)

**Comment by rockzhai** [comment]
@antonia0912 我已经进了译者群的呢~ 只是前面一直在准备考试，没有怎么参与我们的翻译计划呢,,ԾㅂԾ,,

**Comment by Sausure** [comment]
@rockzhai 希望能早点校对，多谢

**Comment by chengdazhi** [comment]
还需要校对吗？需要的话我可以

**Comment by rockzhai** [comment]
@antonia0912 @Sausure 校对完成~ 感觉翻译的挺好的(～￣▽￣)～*

**Comment by antonia0912** [comment]
@rockzhai 原来是之前的元老级译者呀  好的 辛苦啦  @chengdazhi 这个已经不需要校对者咯  等新文章哈
