### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by xdlrt** [xitu/gold-miner#2410]
- 公司/学校：阿里云
- 工作内容/专业：web前端工程师
- 常浏览的国外网站：Quora Medium CSS-tricks
- 英语水平：六级通过
- 有无翻译经验：有
- 个人博客：xdlrt.github.io
- 个人介绍：两年前就关注了掘金翻译计划，当时的自己还比较稚嫩，经过一段时间的翻译尝试和锻炼，完成了多篇优质文章的翻译，现在也想要加入掘金翻译计划，为社区的技术发展贡献自己的一份力量。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
