### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by LilianYe** [xitu/gold-miner#2412]
- 公司/学校：天壤网络科技
- 工作内容/专业：算法工程师
- 常浏览的国外网站：https://machinelearningmastery.com/  
https://blog.acolyer.org/ 
- 英语水平：CET-6
- 有无翻译经验：之前翻译过公开课的字幕
- 个人博客：无
- 个人介绍：研究生毕业于上海交通大学，平时喜欢听因为播客，也看过一些英文小说。目前工作做的是图像分类和物体识别这块的内容。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
