### ISSUE TITLE
Handling Scrolls with CoordinatorLayout

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2413]
* 原文链接：[Handling Scrolls with CoordinatorLayout](https://guides.codepath.com/android/handling-scrolls-with-coordinatorlayout)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/handling-scrolls-with-coordinatorlayout.md)
  * PR 地址：#2490
  * 文章分类：**Android**
  * **注：本文为 Google 约稿，由他们将文章发布在掘金。译者可以发布在自己博客等处。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Feximin** [comment]
认领

**Comment by Feximin** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Feximin 棒极啦 :tada:
