### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by hadeswith666** [xitu/gold-miner#2414]
- 公司/学校：宁波大学
- 工作内容/专业：前端/通信与信息系统
- 常浏览的国外网站：github,facebook,nodejs,reddit，Dreamincode
- 英语水平：cet-6， 479
- 有无翻译经验：翻译英语paper
- 个人博客：https://juejin.im/user/59ffcc9051882578da0d40fe
- 个人介绍：前端工程师

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
