### ISSUE TITLE
Rollup - 下一代 ES6 模块化打包工具 - 对 Rich Harris 的采访

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2415]
* 原文链接：[Rollup - Next-generation ES6 module bundler - Interview with Rich Harris](https://survivejs.com/blog/rollup-interview/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/#)
  * PR 地址：#2429
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Raoul1996** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Raoul1996 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2429
