### ISSUE TITLE
20 年后比特币将会变成什么样 - 第一部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2425]
* 原文链接：[What Will Bitcoin Look Like in Twenty Years?](https://hackernoon.com/what-will-bitcoin-look-like-in-twenty-years-7e75481a798c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-will-bitcoin-look-like-in-twenty-years-1.md)
  * PR 地址：#2503
  * 文章分类：**区块链**
  ----
  * 翻译时间：4 天
  * 校对时间：1.5 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZiXYu** [comment]
领~

**Comment by leviding** [comment]
@ZiXYu  
![image](https://user-images.githubusercontent.com/26959437/32543447-a05a6514-c4b0-11e7-9664-4c2e3f6637a3.png)

**Comment by ZiXYu** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@ZiXYu 棒极啦 :tada:
