### ISSUE TITLE
僵尸币时代即将到来?

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2426]
* 原文链接：[The Coming Era of the Zombie Token?](https://hackernoon.com/the-coming-era-of-the-zombie-token-707350b34b42)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-coming-era-of-the-zombie-token.md)
  * PR 地址：#2466
  * 文章分类：**区块链**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wendylinlin** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@wendylinlin 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2466
