### ISSUE TITLE
20 年后比特币将会变成什么样 - 第 3 部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2428]
* 原文链接：[What Will Bitcoin Look Like in Twenty Years?](https://hackernoon.com/what-will-bitcoin-look-like-in-twenty-years-7e75481a798c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-will-bitcoin-look-like-in-twenty-years-3.md)
  * PR 地址：#3282
  * 文章分类：**区块链**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sakila1012** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sakila1012 棒极啦 :tada:
