### ISSUE TITLE
互联网公司真的是「看重能力，不看重学历」吗？

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#243]
原文链接：[Dropouts Need Not Apply: Silicon Valley Asks Mostly for Developers With Degrees](http://blogs.wsj.com/economics/2016/03/30/dropouts-need-not-apply-silicon-valley-asks-mostly-for-developers-with-degrees/)
掘金链接：[互联网公司真的是「看重能力，不看重学历」吗？](http://gold.xitu.io/entry/570483c4128fe10052505887)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/dropouts-need-not-apply-silicon-valley-asks-mostly-for-developers-with-degrees.md)

翻译时间：4天
校对时间：3天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zhangjd** [comment]
认领

**Comment by antonia0912** [comment]
@Zhangdroid OK 注意翻译时间就可以啦！

**Comment by Zhangjd** [comment]
你 at 错人啦 @antonia0912

**Comment by shaohui10086** [comment]
申请校对

**Comment by antonia0912** [comment]
@shaohui10086 好的 [校对地址](https://github.com/xitu/gold-miner/pull/257/files?diff=split)

**Comment by yangzj1992** [comment]
申请校对

**Comment by antonia0912** [comment]
@yangzj1992 好的 [校对地址](https://github.com/xitu/gold-miner/pull/257/files?diff=split)

**Comment by antonia0912** [comment]
@shaohui10086 记得来校对这篇文章喔

**Comment by shaohui10086** [comment]
嗯呢  前两天有点事，今天就校对 @antonia0912

**Comment by antonia0912** [comment]
@shaohui10086 好哒 没问题
