### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by xiaolvzi** [xitu/gold-miner#2431]
- 公司/学校：上海微创/河南理工大学
- 工作内容/专业：Xamarin.Android 技术支持/信息与计算科学
- 常浏览的国外网站：SO社区：Stackoverflow ，Android开发官网：https://developer.android.com.
- 英语水平: 英语四级
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：热爱技术，想成为一名翻译员，利用自己的职业和专业技能为广大开发者提供自己的力量。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
