### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by Raoul1996** [xitu/gold-miner#2433]
- 原文链接：https://css-tricks.com/emulating-css-timing-functions-javascript/
- 简要介绍：这篇文章将使用大量的例子去阐明如何仅仅使用一点JavaScript，以一种类似常见CSS时序功能的方式，平滑地从一个状态过渡到另一个状态，而不必依靠库。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ
