### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by MinjiaLi** [xitu/gold-miner#2436]
- 公司/学校：武汉大学
- 工作内容/专业：金融工程
- 常浏览的国外网站：Youtube，Quosera
- 英语水平：TOEFL108, GRE329
- 有无翻译经验：有
- 个人博客：无
- 个人介绍：Python熟练，正在学习机器学习，对TensorFlow翻译有极大热情~日常负责武汉大学英文官网内容发布，英语水平较高

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
