### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by mysterytony** [xitu/gold-miner#2438]
- 公司/学校：University of Waterloo
- 工作内容/专业：计算机科学
- 常浏览的国外网站：Youtube, Github
- 英语水平：还行吧，毕竟在加待了7年
- 有无翻译经验：无
- 个人博客：http://tonyli.me/
- 个人介绍：UW CS专业在读大三学生，喜欢架构和算法。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
