### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by springbear** [xitu/gold-miner#2439]
- 公司/学校：途家网
- 工作内容/专业：后端开发
- 常浏览的国外网站：quora，boardgamegeek
- 英语水平：TOEFL（老）630分。雅思7分。
- 有无翻译经验：参与过游戏汉化。
- 个人博客：
- 个人介绍：英文不错，汉语也还阔以，对翻译有较大兴趣。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
