### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by linbaiwpi** [xitu/gold-miner#2440]
- 公司/学校：Worcester Polytechnic Institute
- 工作内容/专业： 人工智能
- 常浏览的国外网站： youtube, github, 以及各种其他
- 英语水平： 海外学习工作～10年，毕竟活下来了
- 有无翻译经验： 偶尔几次，技术文章+生活文章
- 个人博客： 并没有，不过即将有
- 个人介绍： 前FPGA工程师，现深度学习+无人驾驶在读PhD

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
