### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by carriecc** [xitu/gold-miner#2441]
- 公司/学校：深圳市创客工场科技有限公司
- 工作内容/专业：技术文档工程师
- 常浏览的国外网站：Medium
- 英语水平：CET-6
- 有无翻译经验：有
- 个人博客：无
- 个人介绍：文字经验丰富，工作严谨、细致。熟悉通信、机器人教育领域。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
