### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by PCAaron** [xitu/gold-miner#2442]
- 公司/学校：斑马亲子
- 工作内容/专业：前端开发
- 常浏览的国外网站：stackoverflow，twitter
- 英语水平：CET4
- 有无翻译经验：无
- 个人博客：http://www.cnblogs.com/aaron-pan/
- 个人介绍：前端开发经验两年，主要用于技术栈为JavaScript，vue，node等。希望通过翻译大咖的文章能来提升个人的技术水平。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
