### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by wizardforcel** [xitu/gold-miner#2443]
- 原文链接：<https://github.com/fastai/numerical-linear-algebra>
- 简要介绍：Fast.ai 数值线性代数讲义

Fast.ai（和 USF 合办）的一门课程，讲了 AI 中常用的矩阵算法，比如矩阵乘法、EVD/SVD、QR 分解的实现和应用。

有完善的讲义，一共八章。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
你好，感谢推荐。我仔细看了下这个内容，非常棒。只不过感觉并不是很适合翻译。内容中英文句子并不多，主要是公式和矩阵等。这样其实翻译起来效果并不好。还有一点就是，这个教程真正能帮助到的人，英文一般也挺好的，至少能看懂。

英文不好的一般也不太会有这种需求，或者说，有这种需求的，英文不好，他也会好好学英文让自己能看懂这个了。因为对于需要这种理论知识的人来说，这是刚需。

感谢您的推荐。
