### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by mtobeiyf** [xitu/gold-miner#2447]
- 公司/学校：大学本科在读
- 工作内容/专业：通信相关
- 常浏览的国外网站：太多了，比如gayhub
- 英语水平：托福100 六级607
- 有无翻译经验：翻译过scikit-learn的部分文档
- 个人博客：fingr8.cn
- 个人介绍：希望能够贡献自己的一份力量！

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
