### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by foolish-boy** [xitu/gold-miner#2448]
在掘金上发表翻译的文章被 @LeviDing 推荐过来的。

- 公司/学校： 浙江大学计算机硕士， 杭州英坦(Instanza)网络
- 工作内容/专业： iOS开发工程师
- 常浏览的国外网站： https://www.objc.io/    http://nshipster.com/等
- 英语水平：六级
- 有无翻译经验：有，掘金上发表过：
                            1:  https://juejin.im/post/5a02ebae5188252964211f49
                            2:  https://juejin.im/post/5a02ec5e6fb9a045293630ff
                            3:  https://juejin.im/post/5a02ec8cf265da432717a89b
- 个人博客：https://foolish-boy.github.io/
- 个人介绍：爱iOS，爱看大牛博客，爱产品设计

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
