### ISSUE TITLE
Functional Programming for Android Developers — Part 3

### ISSUE THREAD

**Issue by zhouzl18** [xitu/gold-miner#2451]
- 原文链接：https://medium.freecodecamp.org/functional-programming-for-android-developers-part-3-f9e521e96788
- 简要介绍：之前已经翻译了前两篇，今天出了第3部分，麻烦翻译下

**Comment by leviding** [comment]
@zhouzl18 收到，之前的两篇译文链接方便贴一下吗

**Comment by leviding** [comment]
@zhouzl18 已经在 #2451 发布了，能给下之前的两个译文链接吗

**Comment by leviding** [comment]
找到了
