### ISSUE TITLE
Android 开发者如何函数式编程 （三）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2452]
* 原文链接：[Functional Programming for Android Developers — Part 3](https://medium.freecodecamp.org/functional-programming-for-android-developers-part-3-f9e521e96788)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/functional-programming-for-android-developers-part-3.md)
  * PR 地址：#2478
  * 文章分类：**Android**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分 第二位校对积分翻倍
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by miguoer** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@miguoer 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2478
