### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zhanghaiqiangshigezhu** [xitu/gold-miner#2459]
- 公司/学校：青岛浩海网络科技股份有限公司
- 工作内容/专业：c#客户端开发、asp.net mvc开发、java web后端开发。
- 常浏览的国外网站：stackoverflow、voa、bbc、cnn、quora。
- 英语水平：CET6。参加过上海中级口译的考试。学习过雅思。
- 有无翻译经验：在校期间翻译过本专业论文。工作期间翻译过部分技术文档。
- 个人博客：暂时无个人博客。
- 个人介绍：本人对英语一直很感兴趣，无论是上大学期间还是工作之后，从没停止过英语的学习，平时会看一些英文杂志和书籍，也会扩展一下自己的词汇。做软件开发后，平时看英文技术文档比较多，对计算机方面的专业词汇和英语日益熟悉，希望借此机会，加入掘金翻译计划，对社区做出一些有益的贡献。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
