### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by lynulzy** [xitu/gold-miner#246]
你好，我是lynulzy，一线 iOS 开发从业者，之前参与过CocoaChina的翻译组，英语水平还不错能够熟练翻译技术文章。
这是我的博客  www.lzyshare.me

**Comment by CommanderXL** [comment]
请问blog的主题是什么呀？

**Comment by antonia0912** [comment]
@lynulzy 好的 请加我微信 antonia0912 我来拉你进译者群

**Comment by lynulzy** [comment]
@CommanderXL   这个主题   https://github.com/forsigner/fexo

**Comment by lynulzy** [comment]
@antonia0912   已加
