### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by guanpengchn** [xitu/gold-miner#2465]
- 公司/学校：中科院计算技术研究所
- 工作内容/专业：计算机
- 常浏览的国外网站：Wikipedia，StackOverflow，quora
- 英语水平：国家6级
- 有无翻译经验：比较少
- 个人博客：http://blog.csdn.net/grape875499765
- 个人介绍：现在主要关注人工智能和区块链领域

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，备注下姓名和 GitHub ID。

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
