### ISSUE TITLE
在 Android N 预览版中使用 Java 8 的新特性

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#247]
原文链接：[Java 8 in Android N Preview](https://medium.com/@sergii/java-8-in-android-n-preview-76184e2ab7ad#.ywf5x3l8w)
掘金链接：[在 Android N 预览版中使用 Java 8 的新特性](http://gold.xitu.io/entry/570c7c9c79bc44005f4fe821)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/java-8-in-android-n-preview.md)

翻译时间：5天
校对时间：3天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by markzhai** [comment]
认领

**Comment by antonia0912** [comment]
@markzhai 好哒（偷笑）

**Comment by markzhai** [comment]
翻译完成：https://github.com/xitu/gold-miner/pull/256

**Comment by antonia0912** [comment]
@markzhai 我的妈呀 你是搭乘了哈雷彗星的速度嘛 这么快

**Comment by MiJack** [comment]
@mijack 认领校对

**Comment by antonia0912** [comment]
@MiJack 好的 [校对地址](https://github.com/xitu/gold-miner/pull/256/files?diff=split)

**Comment by narcotics726** [comment]
新人投名状！申请校对~

**Comment by antonia0912** [comment]
@narcotics726 好的 [校对地址](https://github.com/xitu/gold-miner/pull/256/files?diff=split)

**Comment by antonia0912** [comment]
@MiJack 校对者要尽快喔  一校已经完成并且译者已经进行修改了，就差二校了，要加快速度喔

**Comment by markzhai** [comment]
@antonia0912 第二篇长文都翻译好啦
@MiJack 这位同学还是声音都没有。。

**Comment by antonia0912** [comment]
@markzhai 我来微信催一催

**Comment by markzhai** [comment]
@antonia0912 都改好了

**Comment by antonia0912** [comment]
@markzhai 已经merge了  分享到掘金后告诉我 我给你们加到积分里哈

**Comment by markzhai** [comment]
@antonia0912 http://gold.xitu.io/#/entry/5716fc67ebcb7d005cad214c 发布啦
