### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by chimywang** [xitu/gold-miner#2471]
- 公司/学校：马上消费金融股份有限公司
- 工作内容/专业：web前端开发工程师
- 常浏览的国外网站：overstackflow、github、https://javascript30.com/、react、angular、MDN、
- 英语水平：六级
- 有无翻译经验：无
- 个人博客：暂无
- 个人介绍：两年经验的web前端工程师，喜欢阅读英文文献，并希望成为一个翻译者、一位知识传达者，熟悉es5、es6；react；angular2/4/5；RXJS；希望加入掘金翻译大家庭，通过翻译文献，提升自己的专业水平，同时也能帮助别人

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
