### ISSUE TITLE
推荐文章 Steps Towards Understanding Deep Learning: The Information Bottleneck Connection (Part 1)

### ISSUE THREAD

**Issue by whatbeg** [xitu/gold-miner#2473]
[Steps Towards Understanding Deep Learning: The Information Bottleneck Connection (Part 1)](https://weberna.github.io/jekyll/update/2017/11/08/Information-Bottleneck-Part1.html)

试图用信息瓶颈理论来理解深度学习

**Comment by leviding** [comment]
感谢您的推荐，文章会尽快发布 :gift_heart:
