### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by JohnJiangLA** [xitu/gold-miner#2474]
- 公司/学校：华中师范大学
- 工作内容/专业：医疗数据AI研发/现代教育技术
- 常浏览的国外网站：StackOverFlow，github，Leetcode，Youtube
- 英语水平：六级左右
- 有无翻译经验：《Scratch Playground》群包翻译
- 个人博客：
- 个人介绍：爱学习、爱折腾的一个人，刚从事业单位离职进入公司从事技术研发工作，在职研究生在读，有一定教育数据研究资源。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
