### ISSUE TITLE
JavaScript 如何工作：在 V8 引擎里 5 个优化代码的技巧

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2476]
* 原文链接：[How JavaScript works: inside the V8 engine + 5 tips on how to write optimized code](https://blog.sessionstack.com/how-javascript-works-inside-the-v8-engine-5-tips-on-how-to-write-optimized-code-ac089e62b12e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-javascript-works-inside-the-v8-engine-5-tips-on-how-to-write-optimized-code.md)
  * PR 地址：
  * 文章分类：**前端**
  ----
  * 翻译时间：7 天
  * 校对时间：1 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by llp0574** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@llp0574 棒极啦 :tada:

**Comment by leviding** [comment]
@llp0574 老哥，sorry，这篇文章，有个译者翻译一半了。他翻译这篇吧

**Comment by balancelove** [comment]
翻译认领

**Comment by llp0574** [comment]
好的，没关系，暂时没有文章推荐哈
