### ISSUE TITLE
JavaScript 工作原理：内存管理 + 处理常见的 4 种内存泄漏

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2477]
* 原文链接：[How JavaScript works: memory management + how to handle 4 common memory leaks](https://blog.sessionstack.com/how-javascript-works-memory-management-how-to-handle-4-common-memory-leaks-3f28b94cfbec)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-javascript-works-memory-management-how-to-handle-4-common-memory-leaks.md)
  * PR 地址：#2521
  * 文章分类：**前端**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by caoxiaoshuai1** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@caoxiaoshuai1 棒极啦 :tada:

**Comment by ParadeTo** [comment]
认领校对

**Comment by PCAaron** [comment]
@leviding @fanyijihua 校对认领

**Comment by leviding** [comment]
@ParadeTo  @PCAaron 在对应 PR 下认领校对

**Comment by caoxiaoshuai1** [comment]
已提交翻译完成PR @leviding  @ParadeTo @PCAaron
