### ISSUE TITLE
JavaScript 如何工作的: 事件循环和异步编程的崛起 + 5 个关于如何使用 async/await 编写更好的技巧

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2479]
* 原文链接：[How JavaScript works: Event loop and the rise of Async programming + 5 ways to better coding with async/await](https://blog.sessionstack.com/how-javascript-works-event-loop-and-the-rise-of-async-programming-5-ways-to-better-coding-with-2f077c4438b5)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-javascript-works-event-loop-and-the-rise-of-async-programming-5-ways-to-better-coding-with.md)
  * PR 地址：#2542
  * 文章分类：**前端**
  ----
  * 翻译时间：10 天
  * 校对时间：2 天
  * 翻译积分：10 分
  * 校对积分：3+1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by balancelove** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@balancelove 棒极啦 :tada:

**Comment by PCAaron** [comment]
@leviding @fanyijihua 校对认领

**Comment by leviding** [comment]
@PCAaron 在对应 PR 下认领校对.

**Comment by tvChan** [comment]
@leviding @fanyijihua 校对认领

**Comment by PCAaron** [comment]
ok

**Comment by naihe138** [comment]
@leviding @balancelove @PCAaron  校对认领

**Comment by leviding** [comment]
@naihe138 认真看译者教程，应该是在对应的 pull request 下认领。
