### ISSUE TITLE
利用 GCM 网络管理工具来优化电池使用

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#248]
原文链接：[Optimize Battery Life with Android's GCM Network Manager](https://www.bignerdranch.com/blog/optimize-battery-life-with-androids-gcm-network-manager/)
掘金链接：[利用 GCM 网络管理工具来优化电池使用](http://gold.xitu.io/entry/570c84b039b057006b849001)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/optimize-battery-life-with-androids-gcm-network-manager.md)

PR地址：#271
翻译时间：4天
校对时间：3天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by chengdazhi** [comment]
终于发现了未被认领的！认领！

**Comment by antonia0912** [comment]
@chengdazhi OK~第一次在翻译计划翻译文章，可以参考其他译者的方法喔  不明白在群里圈我或者问大家就可以啦

**Comment by chengdazhi** [comment]
@antonia0912 好的谢啦

**Comment by leokelly** [comment]
这个还可以认领吗？可以的话，我要了~

**Comment by antonia0912** [comment]
@leokelly 可以的 [校对地址](https://github.com/xitu/gold-miner/pull/271/files?diff=split)

**Comment by leokelly** [comment]
校对完毕～　@antonia0912

**Comment by geeeeeeeeek** [comment]
@antonia0912 校对

**Comment by antonia0912** [comment]
@geeeeeeeeek 童童你逗死你了 哈哈哈[校对地址](https://github.com/xitu/gold-miner/pull/271/files?diff=split)
