### ISSUE TITLE
JavaScript 是如何工作的：深入 WebSockets 和使用了 SSE+ 的 HTTP/2，如何在二者当中做出选择

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2481]
* 原文链接：[How JavaScript works: Deep dive into WebSockets and HTTP/2 with SSE + how to pick the right path](https://blog.sessionstack.com/how-javascript-works-deep-dive-into-websockets-and-http-2-with-sse-how-to-pick-the-right-path-584e6b8e3bf7)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-javascript-works-deep-dive-into-websockets-and-http-2-with-sse-how-to-pick-the-right-path.md)
  * PR 地址：#3024
  * 文章分类：**前端**
  ----
  * 翻译时间：7 天
  * 校对时间：1 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by balancelove** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@balancelove 棒极啦 :tada:

**Comment by PCAaron** [comment]
@leviding @fanyijihua 校对认领

**Comment by leviding** [comment]
@PCAaron 在对应 PR 下认领校对

**Comment by leviding** [comment]
@balancelove 翻译的怎么样啦，是不是忘啦

**Comment by leviding** [comment]
@balancelove 翻译的怎么样啦

**Comment by balancelove** [comment]
@leviding 最近公司年末，事情很多，基本没什么时间- -

**Comment by balancelove** [comment]
@leviding 不好意思啦，要是其他人要翻译的话，我就让了吧，能让吗？最近估计也抽不出时间

**Comment by leviding** [comment]
好的，可以转让，祝工作愉快 👍

**Comment by yoyoyohamapi** [comment]
@leviding 认领翻译

**Comment by fanyijihua** [comment]
@yoyoyohamapi 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3024
