### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by winnerineast** [xitu/gold-miner#2485]
- 公司/学校：Humachine Studio
- 工作内容/专业：计算机视觉，机器学习，深度学习
- 常浏览的国外网站：Quora, InfoQ
- 英语水平：旅居海外
- 有无翻译经验：曾经参加翻译和校对吴恩达机器学习视频课程
- 个人博客：无博客
- 个人介绍：www.github.com/winnerineast

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
