### ISSUE TITLE
模拟是一种代码异味（软件编写）（第十二部分）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2487]
* 原文链接：[Mocking is a Code Smell](https://medium.com/javascript-scene/mocking-is-a-code-smell-944a70c90a6a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/#)
  * PR 地址：#2574
  * 文章分类：**前端**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@yoyoyohamapi 认领

**Comment by yoyoyohamapi** [comment]
认领翻译

**Comment by fanyijihua** [comment]
PR 地址：#2574
