### ISSUE TITLE
Use a Render Prop!

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2488]
* 原文链接：[Use a Render Prop!](https://cdb.reacttraining.com/use-a-render-prop-50de598f11ce)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/use-a-render-prop.md)
  * PR 地址：#2594
  * 文章分类：**前端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@yoyoyohamapi 认领

**Comment by yoyoyohamapi** [comment]
认领翻译

**Comment by fanyijihua** [comment]
PR 地址：#2594
