### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by yangzj1992** [xitu/gold-miner#249]
你好，我叫yangzj1992，USTB信管专业毕业，现在在美菜网任职前端工程师。具有较好的英语基础，经常访问Github/Stackoverflow/Medium社区，至今每天坚持扇贝打卡[(打卡记录)](http://weibo.com/p/1005051213877975/home?from=page_100505_profile&wvr=6&mod=data&is_all=1#place)，有完整阅读英语原著和翻译扇贝读书文章的经验。这是我的博客[qcyoung.com](http://qcyoung.com),希望能互相交流学习。

**Comment by antonia0912** [comment]
@yangzj1992 好的  请加我微信 antonia0912 我来拉你进译者群 请备注 github 用户名

**Comment by Glowin** [comment]
@yangzj1992 欢迎加入掘金翻译计划 PS：我下午还去 People Square 看到你们团队啦。

**Comment by jiaowoyongqi** [comment]
您好！我叫yongqi，现在一家设计体验公司做交互设计师。具有较好的英语水平，经常访问Medium/Github/Quora/Behance/Dribbble等。我的博客是http://lilianlun.lofter.com/ 内有之前翻译的译文，公众号是jiaowoyongqi。希望加入翻译计划！互相学习！

**Comment by antonia0912** [comment]
@jiaowoyongqi 要去新发issue 不是在这个已经close掉的issue底下发呀 bro

**Comment by lizwangying** [comment]
您好，我叫王颖，英文名Liz，现在在两只老虎理财公司担任Android开发。英语六级水平，经常访问Github/Stackoverflow/，我的博客是http://lizwangying.github.io/   希望加入翻译计划。
