### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by johnxianghui** [xitu/gold-miner#2492]
- 公司/学校：华中科技大学（已毕业现在北京贝塔科技有限公司）
- 工作内容/专业：ios开发
- 常浏览的国外网站：youtobe，raywenderlich
- 英语水平：英语六级
- 有无翻译经验：曾经当过中国独立动画电影翻译外国文献的志愿者
- 个人博客：无
- 个人介绍：对ios应用，ios游戏开发有很大的兴趣和激情，而且我也一直在学习英语，希望在学习国外优秀教程的过程中，可以翻译一些国外优质的文章，让大家一起学习，，一起成长

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
