### ISSUE TITLE
推荐优秀英文文章 - iOS

### ISSUE THREAD

**Issue by Danny1451** [xitu/gold-miner#2493]
- 原文链接：https://mobiletestingblog.com/2017/11/05/the-essentials-of-ios-app-testing-for-iphone-x/
- 简要介绍：iPhone X 的适配需要注意的地方，分别从设计和开发的角度。

😷 iOS 好久没有文章推荐了啊

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
收到，多推荐几篇哈哈哈
