### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by tvChan** [xitu/gold-miner#2494]
- 公司/学校：FollowMe
- 工作内容/专业：前端开发工程师
- 常浏览的国外网站：google，medium，quora
- 英语水平：CET 6
- 有无翻译经验：开源中国翻译频道参与翻译
- 个人博客：无
- 个人介绍：爱折腾，爱英语的前端er，希望能为社区出一份力，大家共同学习，一起进步。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
