### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zouyongzou** [xitu/gold-miner#2498]
- 公司/学校：广州
- 工作内容/专业：前端开发/网络工程
- 常浏览的国外网站：googl, twitter, stackoverflow, medium
- 英语水平：四级
- 有无翻译经验：无
- 个人博客：https://zouyongzou.github.io/
- 个人介绍：热爱技术，通过社区学习到了很多，希望能为社区发展贡献一份力量，帮助到更多的人。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
