### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by athena0304** [xitu/gold-miner#2499]
- 公司/学校：360
- 工作内容/专业：web前端开发工程师
- 常浏览的国外网站：wired, gizmodo
- 英语水平：CET-6 GRE
- 有无翻译经验：有
- 个人博客：http://athena0304.github.io/
- 个人介绍：
曾经是果壳译者
https://www.guokr.com/i/1787053282/articles/
最近年也偶尔翻译一些技术文章

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
