### ISSUE TITLE
下拉菜单为何是一种不好的用户体验？

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#250]
原文链接：[Why drop-down lists are bad for the user experience.](https://medium.com/apegroup-texts/why-drop-down-lists-are-bad-for-the-user-experience-eeda5cbbd315#.p1yny0k15)
掘金链接：[下拉菜单为何是一种不好的用户体验？](http://gold.xitu.io/entry/570caab639b057006b863659)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/why-drop-down-lists-are-bad-for-the-user-experience.md)

翻译时间：4天
校对时间：3天
翻译积分：5
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by yangzj1992** [comment]
认领，第一次认领，个人介绍见[申请译者issue]吧(https://github.com/xitu/gold-miner/issues/249)

**Comment by yangzj1992** [comment]
另外想问下翻译时间是按认领后第一天开始算吗？还是认领当天开始计算，如果因为各种原因超时会怎样？

**Comment by antonia0912** [comment]
@yangzj1992 新译者加入要从校对开始喔  先去认领一篇label是“校对认领”的文章吧

**Comment by yangzj1992** [comment]
好的

**Comment by antonia0912** [comment]
@yangzj1992 等你的comment哈~

**Comment by shaohui10086** [comment]
认领 认领

**Comment by antonia0912** [comment]
@shaohui10086 好的  等你PR

**Comment by circlelove** [comment]
认校

**Comment by antonia0912** [comment]
@circlelove 好的 [校对地址](https://github.com/xitu/gold-miner/pull/288/files?diff=split)
