### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by shi-xiaopeng** [xitu/gold-miner#2501]
- 公司/学校：陕西师范大学
- 工作内容/专业：电子商务(计算机python编程)
- 常浏览的国外网站：leetcode, github, stackoverflow
- 英语水平：证书只考了6级，但是阅读无障碍，词汇量9000左右
- 有无翻译经验：有一些，之前为了方便翻译过几篇Andoid官方文档
- 个人博客：
- 个人介绍：从事软件开发，python后台，由于工作需要，经常会看写英文技术文档。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
