### ISSUE TITLE
汉娜申请成为译者

### ISSUE THREAD

**Issue by hannahGu** [xitu/gold-miner#2502]
- 公司/学校：万达网络科技
- 工作内容/专业：前端开发
- 常浏览的国外网站：https://codepen.io/，https://stackoverflow.com/ ，npmjs.com
- 英语水平：CET4
- 有无翻译经验：无专业书面翻译，有口译经验
- 个人博客：无
- 个人介绍：喜欢英语，热爱技术，翻译是很好的结合点，选我，选我，选我 ✌️

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
