### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by wsh540677278** [xitu/gold-miner#2507]
- 公司/学校：Northeastern University, Master of Science in Computer Science; Beihang University, Bachelor of Engineering in Software Engineering
- 工作内容/专业：Computer Science; Software development; Machine Learning; Deep Learning; Information Retrieval.
- 常浏览的国外网站：StackOverFlow, Github, Google Scholar
- 英语水平：Professional working proficiency
- 有无翻译经验：有，并且有论文发表经验
- 个人博客：https://www.linkedin.com/in/shihao-wang/
- 个人介绍：目前在美国东北大学读计算机硕士，对于tensorflow教程的翻译很感兴趣，自己也阅读过TF的相关教程（包括原版google教程和极客学院版本），希望可以参与到工作中来

**Comment by leviding** [comment]
非常欢迎，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
