### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Yaoming95** [xitu/gold-miner#2508]
- 公司/学校：上海交通大学(大四在读) 
- 工作内容/专业：计算机科学 深度强化学习 自然语言处理
                              Computer Science, Deep Reinforcement Learning, Natrual Language Processing
- 常浏览的国外网站：google scholar, reddit, github, Udacity, Coursera, YouTube
- 英语水平：六级， 有CCF列表会议与期刊的论文发表经历
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：对互联网技术拥有浓厚兴趣，曾有过软件定义网络与数据中心网络的研究经历，曾在滴滴出行实习负责Java Web开发工作。目前大四在校已保研，现在的科研方向是深度强化学习在自然语言处理，特别是文本生成中的应用。希望能加入掘金译者计划，为深度学习与强化学习的中文社区添砖加瓦！

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
