### ISSUE TITLE
ECMAScript 6 里面的私有变量

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#251]
原文链接：[Private members in ES6 classes](https://gist.github.com/greim/44e54c2f23eab955bb73b31426e96d6c)
掘金链接：[ ECMAScript 6 里面的私有变量](http://gold.xitu.io/entry/570e11d81ea4930068ed3eef)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/es6-private-members.md)

翻译时间：3天
校对时间：2天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by CommanderXL** [comment]
文章认领

**Comment by antonia0912** [comment]
@CommanderXL OK 注意翻译期限哈

**Comment by CommanderXL** [comment]
翻译完毕~

请其他同学校对~

**Comment by antonia0912** [comment]
@CommanderXL 好的  辛苦啦

**Comment by narcotics726** [comment]
刚才报名错地方了=。=，校对认领！

**Comment by yangzj1992** [comment]
@antonia0912  这才一个校对同学啊=.=怎么就不需要校对的了..

**Comment by Jack-Kingdom** [comment]
还需要叫对吗，校对+1， @antonia0912

**Comment by antonia0912** [comment]
@yangzj1992 另一位校对者已经在PR里发申请了  另外 @Jack-Kingdom label是正在校对的就是这篇文章已经有两位校对者了   你可以去看看有 校对认领 label的文章
