### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by c1ay** [xitu/gold-miner#2511]
* 公司/学校：中国网安
* 工作内容/专业：python web 开发/数据统计
* 常浏览的国外网站：github/reddit/stackoverflow
* 英语水平：四级
* 有无翻译经验：无
* 个人博客：blog.c1ay.cc
* 个人介绍：喜欢玩游戏，篮球，偶尔爬爬山

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
