### ISSUE TITLE
加密货币泡沫为什么会破裂？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2512]
* 原文链接：[Why and how the Cryptobubble will burst](https://medium.com/@dennyk/why-and-how-the-cryptobubble-will-burst-de9bc7fc5332)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-and-how-the-cryptobubble-will-burst.md)
  * PR 地址：#2570
  * 文章分类：**区块链**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by GreenLim** [comment]
认领翻译

**Comment by GreenLim** [comment]
翻译认领

**Comment by leviding** [comment]
@GreenLim 认领的时候要艾特我

**Comment by fanyijihua** [comment]
PR 地址：#2570
