### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by EricHedgedog** [xitu/gold-miner#2514]
- 公司/学校：苏州磐荣科技有限公司
- 工作内容/专业：Web前端
- 常浏览的国外网站：https://medium.com/
- 英语水平：雅思6.5
- 有无翻译经验：有
- 个人博客：http://blog.csdn.net/mayuehua0729
- 个人介绍：不只是一个Web前端工程师

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
