### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by water-law** [xitu/gold-miner#2517]
- 公司/学校：快云信息科技有限公司/福州大学
- 工作内容/专业：软件开发工程师/计算机科学与技术
- 常浏览的国外网站：Google、StackOverFlow、Github
- 英语水平：CET4
- 有无翻译经验：暂无
- 个人博客：waterlaw.cn
- 个人介绍：我是个乐于分享、积极的年轻人，希望我能加入掘金翻译计划，让我的工作能和大家分享，然大家能读到国外的一些优质文章。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
