### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by wowotou1998** [xitu/gold-miner#2519]
- 公司/学校：安徽工业大学
- 工作内容/专业：信息管理与信息系统
- 常浏览的国外网站：BBC还有MSDN
- 英语水平：四级494正在备考英语六级
- 有无翻译经验：无
- 个人博客：无
- 个人介绍：因为自己的专业是信息管理，而且自己偏向于计算机这一块，所以掌握好英语很重要，所以本着学以致用的原则，想在翻译中学习英语，不断提高自己，谢谢掘金给我这个平台。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
