### ISSUE TITLE
React.js 新手村教程

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#252]
原文链接：[HOMEBLOG React JS: newbies tutorial](http://www.leanpanda.com/blog/2016/04/06/react-newbies-tutorial/)
掘金链接：[React.js 新手村教程](http://gold.xitu.io/entry/570e1912128fe1006cbde018)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/react-newbies-tutorial.md)

翻译时间：5天
校对时间：4天
翻译积分：8
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by antonia0912** [comment]
markdown文件有点问题

**Comment by markzhai** [comment]
抢下了

**Comment by icepy** [comment]
好疯狂啊，抢都抢不到0.0

**Comment by Glowin** [comment]
@icepy 可以先找一篇校对的文章练手哈，欢迎加入掘金翻译计划。

**Comment by antonia0912** [comment]
@icepy 请简单介绍一下自己  可以参考[这里](https://github.com/xitu/gold-miner/issues/249)，翻译计划怎么玩点[这里](https://github.com/xitu/gold-miner/blob/master/README.md)

**Comment by markzhai** [comment]
@antonia0912 羊羊羊快召唤神兽修复markdown文件

**Comment by antonia0912** [comment]
@markzhai markdown文件已经修改好了 可以开始翻译啦

**Comment by markzhai** [comment]
@antonia0912 翻译好了

**Comment by antonia0912** [comment]
@markzhai 好哒 辛苦啦

**Comment by antonia0912** [comment]
@icepy honey 交了译者申请了咩  提交后就可以来校对这篇文章啦

**Comment by malcolmyu** [comment]
申请校对~

**Comment by antonia0912** [comment]
@malcolmyu 好的 [校对地址](https://github.com/xitu/gold-miner/pull/279/files?diff=split)

**Comment by markzhai** [comment]
@antonia0912 http://gold.xitu.io/#/entry/5719b6acebcb7d006a007d9b 分享好了，加了tag
