### ISSUE TITLE
IBM 工程师的 TensorFlow 入门指北

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2520]
* 原文链接：[Getting started with TensorFlow — IBM](https://www.ibm.com/developerworks/opensource/library/cc-get-started-tensorflow/index.html?social_post=1166248547&fst=Learn)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/get-started-tensorflow.md)
  * PR 地址：#2812
  * 文章分类：**机器学习**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by duyixian1234** [comment]
申请翻译

**Comment by fanyijihua** [comment]
@duyixian1234 棒极啦 :tada:

**Comment by duyixian1234** [comment]
不好意思，最近在出差很忙，翻译要搁置一段时间

**Comment by leviding** [comment]
@JohnJiangLA

**Comment by JohnJiangLA** [comment]
OK，下周之前搞定它

**Comment by fanyijihua** [comment]
PR 地址：#2812
