### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Yangbin1110** [xitu/gold-miner#2522]
- 公司/学校：中国地质大学
- 工作内容/专业：计算机科学与技术
- 常浏览的国外网站：stackoverflow 
- 英语水平：6级
- 有无翻译经验：有, 参与翻译过Elasticsearch 5.x
- 个人博客：jotting.cn
- 个人介绍：熟悉linux, python等, 近期对docker容器技术比较感兴趣.

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』

**Comment by leviding** [comment]
地大武汉还是北京喔
