### ISSUE TITLE
React 应用性能调优

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2525]
* 原文链接：[Performance-tuning a React application](https://codeburst.io/performance-tuning-a-react-application-f480f46dc1a2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/performance-tuning-a-react-application.md)
  * PR 地址：#2556
  * 文章分类：**前端**
  ----
  * 翻译时间：6 天
  * 校对时间：1.5 天
  * 翻译积分：6 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZhangFe** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ZhangFe 棒极啦 :tada:
