### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by duyixian1234** [xitu/gold-miner#2526]
- 公司/学校：浙江成功软件/浙江大学
- 工作内容/专业：研发（Java）/软件工程
- 常浏览的国外网站：HackerNews, StackOverflow, Github, Medium, Dzone
- 英语水平：六级以上的阅读能力，四级的听说能力
- 有无翻译经验：不多
- 个人博客：https://segmentfault.com/blog/yixian
- 个人介绍：从事Java,爱好Python、DotNetCore、Rust，具有较好的文字表达能力

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
