### ISSUE TITLE
Google 约稿：缩小 APK，增加下载量

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2527]
* 原文链接：[Shrinking APKs, growing installs: How your app’s APK size impacts install conversion rates](https://medium.com/googleplaydev/shrinking-apks-growing-installs-5d3fcba23ce2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/shrinking-apks-growing-installs.md)
  * PR 地址：#2567
  * 文章分类：**Android**
  * **注意：本文为 [Google](https://juejin.im/user/59e847cd6fb9a0451c3980d1) 约稿，由他们在掘金发布。译者亦可发布于任何平台。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
认领翻译。

**Comment by leviding** [comment]
@tanglie1993 认领的时候记得艾特我

**Comment by leviding** [comment]
@tanglie1993 ok
