### ISSUE TITLE
Google 约稿：从应用探索者到初次购买者

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2528]
* 原文链接：[From app explorer to first-time buyer: A look at how rising star apps and games engage users through in-app purchases](https://medium.com/googleplaydev/from-app-explorer-to-first-time-buyer-6476be50893)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/from-app-explorer-to-first-time-buyer.md)
  * PR 地址：#2559
  * 文章分类：**Android**
  * **注意：本文为 [Google](https://juejin.im/user/59e847cd6fb9a0451c3980d1) 约稿，由他们在掘金发布。译者亦可发布于任何平台。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ppp-man** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ppp-man 棒极啦 :tada:

**Comment by leviding** [comment]
* **注意：本文为 [Google](https://juejin.im/user/59e847cd6fb9a0451c3980d1) 约稿，有他们在掘金发布。译者亦可发布于任何平台。**
