### ISSUE TITLE
智对订阅难点：教你如何应对工作中 10 种常见订阅问题

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2529]
* 原文链接：[Outsmarting subscription challenges: Solutions to 10 common challenges developers face with subscription businesses](https://medium.com/googleplaydev/outsmarting-subscription-challenges-711216b6292c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/outsmarting-subscription-challenges.md)
  * PR 地址：#2806
  * 文章分类：**Android**
  * **注意：本文为 [Google](https://juejin.im/user/59e847cd6fb9a0451c3980d1) 约稿，由他们在掘金发布。译者亦可发布于任何平台。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pot-code** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@pot-code 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2806
