### ISSUE TITLE
The Two Types of Product Virality

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#253]
原文链接：[The Two Types of Product Virality](https://medium.com/@philipla/the-two-types-of-product-virality-8ae744b1c4d7#.lwgcxzx4d)
掘金链接：[The Two Types of Product Virality](http://gold.xitu.io/entry/570f344779bc44005f68e0b6)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/the-two-types-of-product-virality.md)

翻译时间：5天
校对时间：4天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by huanglizhuo** [comment]
认领  @antonia0912

**Comment by antonia0912** [comment]
@huanglizhuo get~

**Comment by huanglizhuo** [comment]
翻译结束  #261  
要麻烦 三岁妹纸 @antonia0912  找人校对了

**Comment by antonia0912** [comment]
@huanglizhuo 已经merge了  分享到掘金后告诉我哈 我给你们加积分

**Comment by huanglizhuo** [comment]
分享了  ：）
