### ISSUE TITLE
Google 约稿：app 里的 A／B 测试简介

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2531]
* 原文链接：[An introduction to in-app A/B testing: How A/B testing can help you get more out of your app](https://medium.com/googleplaydev/an-introduction-to-in-app-a-b-testing-c5a9a69a3791)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/an-introduction-to-in-app-a-b-testing.md)
  * PR 地址：#2573
  * 文章分类：**Android**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mnikn** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@mnikn 棒极啦 :tada:

**Comment by leviding** [comment]
@mnikn 翻译怎么样啦

**Comment by mnikn** [comment]
最近有点忙😂，目前翻译了一大半，争取这周搞定

**Comment by fanyijihua** [comment]
PR 地址：#2573
