### ISSUE TITLE
How To Make A Chart Using AJAX & REST API's

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2532]
* 原文链接：[How To Make A Chart Using AJAX & REST API's](https://blog.zingchart.com/2017/11/16/how-to-make-a-chart-using-ajax-rest-apis/?utm_source=frontendfocus&utm_medium=email)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-make-a-chart-using-ajax-rest-apis.md)
  * PR 地址：#2541
  * 文章分类：**前端**
  ----
  * 翻译时间：2 天
  * 翻译积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sakila1012** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@sakila1012 棒极啦 :tada:
