### ISSUE TITLE
如何禁用链接

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2533]
* 原文链接：[How to Disable Links](https://css-tricks.com/how-to-disable-links/?utm_source=frontendfocus&utm_medium=email)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-disable-links.md)
  * PR 地址：
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Usey95** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Usey95 棒极啦 :tada:
