### ISSUE TITLE
使用 CSS Grid：以兼容不支持栅格化布局的浏览器

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2535]
* 原文链接：[Using CSS Grid: Supporting Browsers Without Grid](https://www.smashingmagazine.com/2017/11/css-grid-supporting-browsers-without-grid/?utm_source=SitePoint&utm_medium=email&utm_campaign=Versioning)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/css-grid-supporting-browsers-without-grid.md)
  * PR 地址：#2621
  * 文章分类：**前端**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Raoul1996** [comment]
翻译认领

**Comment by Raoul1996** [comment]
@leviding

**Comment by leviding** [comment]
@Raoul1996 ok
