### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by hexianga** [xitu/gold-miner#2543]
- 公司/学校：西南交通大学
- 工作内容/专业：电子信息工程
- 常浏览的国外网站：stackOverflow
- 英语水平：英语四级
- 有无翻译经验：无
- 个人博客：http://blog.csdn.net/extendworld?ref=toolbar
- 个人介绍：前端爱好者，喜欢了解接触行业的动态前沿，了解大牛们的丰富思想，向大牛们学习。个人私下比较喜欢英语，喜欢阅读英文文档，希望通过翻译实践提高自己的英语水平。同时也为社区提供一些中文文档，方便喜欢阅读中文文档的朋友阅读。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
