### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zhaoruofeiji** [xitu/gold-miner#2544]
- 公司/学校：长沙理工大学
- 工作内容/专业：计算机科学与技术
- 常浏览的国外网站：
https://developer.mozilla.org/en-US/
https://leetcode.com/
https://github.com/
https://stackoverflow.com/
- 英语水平：英语四级548分，正在准备雅思考试。
- 有无翻译经验：无
- 个人博客：http://blog.csdn.net/android_depon
- 个人介绍：
初入前端的小白，英语爱好者。平时看到很多前辈翻译相关的技术文章，受益匪浅，希望也能贡献自己的一点微薄力量。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
