### ISSUE TITLE
推荐优秀英文文章 使用 Rust 来写原生 Node\.js 模块

### ISSUE THREAD

**Issue by Glowin** [xitu/gold-miner#2545]
- 原文链接：[使用 Rust 来写原生 Node\.js 模块](https://juejin.im/entry/5a1bae3cf265da4314406b37/detail)
- 简要介绍：使用 Rust 来取代 C++ 写 node.js module.

**Comment by leviding** [comment]
感谢您的推荐，文章会尽快发布 :gift_heart:
