### ISSUE TITLE
自动化持续集成/持续分发，以节省更多时间编写代码

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2547]
* 原文链接：[Automate CI/CD and Spend More Time Writing Code](https://www.sitepoint.com/automate-cicd-visual-app-center/?utm_source=SitePoint&utm_medium=email&utm_campaign=Versioning)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/automate-cicd-visual-app-center.md)
  * PR 地址：
  * 文章分类：**教程**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by NeilLi1992** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@NeilLi1992 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2921

**Comment by leviding** [comment]
神速 👍
