### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by godofchina** [xitu/gold-miner#255]
如何申请成为译者，告知下流程

**Comment by antonia0912** [comment]
@godofchina 这就是在申请呀  介绍一下自己 可以参考[这里](https://github.com/xitu/gold-miner/issues/249)，翻译计划怎么玩点[这里](https://github.com/xitu/gold-miner/blob/master/README.md)

**Comment by antonia0912** [comment]
@godofchina 请加我微信 antonia0912 我来拉你进译者群
