### ISSUE TITLE
使用 Rust 来写原生 Node.js 模块

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2550]
* 原文链接：[Writing fast and safe native Node.js modules with Rust](https://blog.risingstack.com/node-js-native-modules-with-rust/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/node-js-native-modules-with-rust.md)
  * PR 地址：#2584
  * 文章分类：**后端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LeopPro** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@LeopPro 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2584
