### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Cielsk** [xitu/gold-miner#2551]
- 公司/学校：中山大学
- 工作内容/专业：软件工程（计算机应用软件）
- 常浏览的国外网站：Medium、Youtube、StackOverflow、Android Developer
- 英语水平：CET 6
- 有无翻译经验：在个人博客有过个人翻译文章：[利用注解改善 Android 代码检查](http://cielsk43.gitee.io/%E5%88%A9%E7%94%A8%E6%B3%A8%E8%A7%A3%E6%94%B9%E5%96%84-Android-%E4%BB%A3%E7%A0%81%E6%A3%80%E6%9F%A5/) 和 [Android XML 中 tools 命名空间的作用](http://cielsk43.gitee.io/Android-XML-%E4%B8%AD-tools-%E5%91%BD%E5%90%8D%E7%A9%BA%E9%97%B4%E7%9A%84%E4%BD%9C%E7%94%A8/)
- 个人博客：http://cielsk43.gitee.io/
- 个人介绍：Android 爱好者，现在正在努力自学 Android 相关知识，经常通过英文网站浏览相关文章与前沿资讯。希望能通过翻译和校对工作阅读、学习优秀外文资料，提高专业英文水平，也希望尽可能地为中文社区尽一份自己的力量。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
