### ISSUE TITLE
从 Gzip 压缩 SVG 说起 — 论如何减小资源文件的大小

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2553]
* 原文链接：[Of SVG, Minification and Gzip](https://blog.usejournal.com/of-svg-minification-and-gzip-21cd26a5d007)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/of-svg-minification-and-gzip.md)
  * PR 地址：#2610
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2610
