### ISSUE TITLE
A Comprehensive Guide To Web Design

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2554]
* 原文链接：[A Comprehensive Guide To Web Design](https://www.smashingmagazine.com/2017/11/comprehensive-guide-web-design/?utm_source=frontendfocus&utm_medium=email)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/comprehensive-guide-web-design.md)
  * PR 地址：#3053
  * 文章分类：**设计**
  ----
  * 翻译时间：12 天
  * 校对时间：4 天
  * 翻译积分：12 分
  * 校对积分：4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by horizon13th** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@horizon13th 棒极啦 :tada:

**Comment by leviding** [comment]
@horizon13th 翻译的怎么样啦

**Comment by horizon13th** [comment]
翻译中///。///

**Comment by leviding** [comment]
@horizon13th 怎么样了，是不是有点长

**Comment by horizon13th** [comment]
@leviding 节日期间拖稿严重，本周末交稿~~

**Comment by fanyijihua** [comment]
PR 地址：#3053
