### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Everfighting** [xitu/gold-miner#2555]
- 公司/学校：华东师范大学
- 工作内容/专业：python开发/ 信息管理与信息系统
- 常浏览的国外网站：github facebook youtube quora
- 英语水平：英语六级 550
- 有无翻译经验： 无
- 个人博客：http://everfight.club/
- 个人介绍：python爱好者，希望为开源技术翻译贡献一份力。

**Comment by leviding** [comment]
Hi，欢迎参与翻译计划，加我微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) 加好友，**备注下姓名和 GitHub ID**，方便拉你进译者群哈 O(∩_∩)O

> 请认真阅读 『**[译者注意事项](https://github.com/xitu/gold-miner/wiki)**』
