### ISSUE TITLE
推荐 Android 方面优秀英文文章

### ISSUE THREAD

**Issue by Cielsk** [xitu/gold-miner#2557]
原文连接：

-  [New Android Injector with Dagger 2 — part 1](https://medium.com/@iammert/new-android-injector-with-dagger-2-part-1-8baa60152abe)
- [New Android Injector with Dagger 2 — part 2](https://medium.com/@iammert/new-android-injector-with-dagger-2-part-2-4af05fd783d0)

简介：
今年 3 月 21 号 Dagger 2 在 2.10 版本之后针对 Android 方面做了很大的优化，使用方法也随之有了不少变化。
文章的第一部分介绍了本次大改的前因后果，以及新 API 的基本使用方式；第二部分介绍了如何利用新注解简化注入操作。

**Comment by leviding** [comment]
感谢您的推荐，文章会尽快发布 :gift_heart:
