### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by aiceflower** [xitu/gold-miner#2560]
- 公司/学校：运通信息
- 工作内容/专业：java软件开发
- 常浏览的国外网站：无
- 英语水平：CET-4
- 有无翻译经验：无
- 个人博客：https://my.oschina.net/u/2546185/blog
- 个人介绍：一个充满活力，拥用梦想的青年，志力于成于java大牛，虽然现在离目标还有点距离，但我相信，事在人为，目标会离我越来越近。

**Comment by leviding** [comment]
Hi @aiceflower ，感谢你申请加入掘金翻译计划，但是你需要先做做功课：

1. 认真学习 [掘金翻译计划译者教程](https://github.com/xitu/gold-miner/wiki)，校对和翻译文章时，严格遵循教程，杜绝不看教程，只知道问的伸手党。

2. 再次学习 [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)，翻译文章时严格遵循，校对文章时也要指出译者的格式错误。

3. 认真学习 [翻译和校对文章的注意事项](https://github.com/xitu/gold-miner/wiki/%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88#%E7%BF%BB%E8%AF%91)，避免翻译校对过程中出错。

4. 如果以上内容都学习完，则加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式：**姓名 + GitHub 昵称 + 学习完全部教程。

**注意**：加微信时，验证信息正确才能被通过，否则一律拒绝。管理员每天集中处理一次，稍安勿躁。加完微信后，管理员会在当天拉你进译者群，进群之后主动做下简单的自我介绍。
