### ISSUE TITLE
推荐优秀英文文章 - Announcing Ant Design 3.0

### ISSUE THREAD

**Issue by freebirdy-2000** [xitu/gold-miner#2577]
- 原文链接：https://medium.com/ant-design/announcing-ant-design-3-0-70e3e65eca0c
- 简要介绍：Ant Design 发布了 3.0 新版本，进行了大改版，有很多新特性。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
收到，今天加上，辛苦了

**Comment by Lyndon001** [comment]
Mark
