### ISSUE TITLE
10 步带你做一个棒棒的 Hybrid 应用

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#258]
原文链接：[10 steps to better hybrid apps](https://medium.com/net-magazine/10-steps-to-better-hybrid-apps-e8e33831ea5e#.4fh1wbsy9)
掘金链接：[10 步带你做一个棒棒的 Hybrid 应用](http://gold.xitu.io/entry/570fb3e271cfe4006751404d)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/10-steps-to-better-hybrid-apps.md)

翻译时间：5天
校对时间：4天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Yves-X** [comment]
认领

**Comment by antonia0912** [comment]
@Yves-X 好的  等你PR

**Comment by malcolmyu** [comment]
申请校对~

**Comment by antonia0912** [comment]
@malcolmyu 不是译者的要先去issue里发译者申请喔~ 翻译计划怎么玩[点这里](https://github.com/xitu/gold-miner/blob/master/README.md)

**Comment by malcolmyu** [comment]
@antonia0912 可是我看到申请校对好像不用申请译者……

**Comment by antonia0912** [comment]
@malcolmyu 都需要的呀，无论是翻译还是校对，都是我们翻译计划的自有译者，所以还是先去申请一下吧，然后我可以拉你进译者群，翻译和校对都有一定的积分，可以兑换 Octocat 等奖品的

**Comment by malcolmyu** [comment]
@antonia0912 好滴好滴

**Comment by malcolmyu** [comment]
继续申请校对🌚

**Comment by antonia0912** [comment]
@malcolmyu [校对地址](https://github.com/xitu/gold-miner/pull/264/files?diff=split)

**Comment by malcolmyu** [comment]
@antonia0912 校对完成

**Comment by antonia0912** [comment]
@malcolmyu 好的 辛苦啦

**Comment by malcolmyu** [comment]
@antonia0912 新手村那个我也申请校对了😁

**Comment by circlelove** [comment]
申请校对~

**Comment by antonia0912** [comment]
@circlelove 好的  [校对地址](https://github.com/xitu/gold-miner/pull/264/files?diff=split)

**Comment by circlelove** [comment]
@antonia0912  我看完了，译的挺好的

**Comment by antonia0912** [comment]
辛苦两位校对者啦@malcolmyu @circlelove  ，译者可以根据校对者意见进行修改和完善啦 @Yves-X

**Comment by Yves-X** [comment]
@antonia0912 Done~
