### ISSUE TITLE
自主权身份简介

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2585]
* 原文链接：[A gentle introduction to self-sovereign identity](https://bitsonblocks.net/2017/05/17/a-gentle-introduction-to-self-sovereign-identity/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-gentle-introduction-to-self-sovereign-identity.md)
  * PR 地址：#3248
  * 文章分类：**区块链**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by foxxnuaa** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@foxxnuaa 棒极啦 :tada:
