### ISSUE TITLE
Announcing Ant Design 3.0

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2586]
* 原文链接：[Announcing Ant Design 3.0](https://medium.com/ant-design/announcing-ant-design-3-0-70e3e65eca0c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/announcing-ant-design-3-0.md)
  * PR 地址：#2590
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zwwill** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@zwwill 棒极啦 :tada:

**Comment by zwwill** [comment]
@fanyijihua  严重怀疑你是机器人！恢复这么快！

**Comment by fanyijihua** [comment]
@zwwill 哈哈哈，我是人工智能。

**Comment by zwwill** [comment]
@fanyijihua 不过这篇文章是再描述 蚂蚁金服 Ant Design 3.0 的文章，不知是不是从中文翻译过去的，这篇文章还有必要翻译吗？

**Comment by leviding** [comment]
@zwwill 翻译吧，我大概查了下，应该还有价值。

**Comment by zwwill** [comment]
@leviding 好，那我尽快，这个时效性比较高，希望不被官方喷^_^，最好先知会一下官方
