### ISSUE TITLE
Breaking Swift with reference counted structs

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#259]
原文链接：[Breaking Swift with reference counted structs](http://www.cocoawithlove.com/blog/2016/03/27/on-delete.html)
掘金链接：[Breaking Swift with reference counted structs](http://gold.xitu.io/entry/570fbe428ac247006440b6b7)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/Breaking-Swift-with-reference-counted-structs.md)

翻译时间：5天
校对时间：4天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Tuccuay** [comment]
认（

**Comment by antonia0912** [comment]
@Tuccuay 收收收收到~

**Comment by Tuccuay** [comment]
😂但是文件名真的不改吗...就 `blog.md`?

**Comment by antonia0912** [comment]
@Tuccuay markdown文件名已经改好啦

**Comment by Tuccuay** [comment]
@antonia0912  ![Sticker](http://ww1.sinaimg.cn/large/0060lm7Tgw1f2xf3vmop6j303e032q2t.jpg)

**Comment by Tuccuay** [comment]
@antonia0912  但是为什么文件名最前面有一个空格呢（

**Comment by Tuccuay** [comment]
![Sticker](http://ww1.sinaimg.cn/large/0060lm7Tgw1f2z4perpfnj305403c3yi.jpg)

@antonia0912 校对辣~

**Comment by antonia0912** [comment]
@Tuccuay gooooooooooood boy~我来联系校对者吼~

**Comment by Jack-Kingdom** [comment]
还能认领吗，校对+1

**Comment by antonia0912** [comment]
@Jack-Kingdom 好哒 [校对地址](https://github.com/xitu/gold-miner/pull/268/files?diff=split)
