### ISSUE TITLE
Face ID 对易用性意味着什么

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2595]
* 原文链接：[What Face ID Means for Accessibility](https://www.stevensblog.co/blogs/what-face-id-means-for-accessibility?utm_source=SitePoint&utm_medium=email&utm_campaign=Versioning)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-face-id-means-for-accessibility.md)
  * PR 地址：#2782
  * 文章分类：**产品**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by winry01** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@winry01 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2782
