### ISSUE TITLE
Why we never thank open source maintainers

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2597]
* 原文链接：[Why we never thank open source maintainers](https://www.codementor.io/windsonyang/why-we-never-thank-open-source-maintainers-ed0nsw3zd)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-we-never-thank-open-source-maintainers.md)
  * 文章分类：**其他**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
翻译认领

**Comment by leviding** [comment]
@fanyijihua 认领翻译

**Comment by jonjia** [comment]
”手太快了”

**Comment by leviding** [comment]
哈哈哈

**Comment by leviding** [comment]
https://juejin.im/post/5a40c20b518825696f7e3c23
