### ISSUE TITLE
你想学 React.js 吗？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2599]
* 原文链接：[So you want to learn React.js?](https://edgecoders.com/so-you-want-to-learn-react-js-a78801d3cd4d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/so-you-want-to-learn-react-js.md)
  * PR 地址：#2618
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分 kangkai 翻倍
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tvChan** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@tvChan 棒极啦 :tada:
