### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by narcotics726** [xitu/gold-miner#260]
你好，一直订阅着稀土掘金的RSS，之前都是读者身份，偶尔发现这个翻译计划，非常感兴趣，希望可以加入。

主要工作内容是 C# / Java 与 Node.js，对前端也有浓厚兴趣和一定的经验，希望把自己打造成一个全栈工程师。

**Comment by antonia0912** [comment]
@narcotics726 来吧全栈工程师~加我微信 antonia0912 我来拉你进译者群

**Comment by yangzj1992** [comment]
话说稀土掘金的RSS地址在哪？貌似没有找到..

**Comment by antonia0912** [comment]
@yangzj1992 在这里 http://gold.xitu.io/rss

**Comment by yangzj1992** [comment]
@antonia0912 感谢~
