### ISSUE TITLE
如何取消你的 Promise？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2601]
* 原文链接：[How to Cancel Your Promise](http://blog.bloomca.me/2017/12/04/how-to-cancel-your-promise.html)
  * 原文作者：[Seva Zaikov](http://blog.bloomca.me/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-cancel-your-promise.md)
  * PR 地址：#2609
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jonjia** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@jonjia 棒极啦 :tada:
