### ISSUE TITLE
How to start with backend TypeScript and use it’s full potential.

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2606]
* 原文链接：[How to start with backend TypeScript and use it’s full potential.](https://medium.com/@igorandreev/how-to-start-with-backend-typescript-and-use-its-full-potential-5114e52012b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-start-with-backend-typescript-and-use-its-full-potential.md)
  * PR 地址：#2679
  * 文章分类：**后端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xilihuasi** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@xilihuasi 棒极啦 :tada:
