### ISSUE TITLE
垂直排版：重提 writing-mode

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2607]
* 原文链接：[Vertical typesetting with writing-mode revisited](https://www.chenhuijing.com/blog/vertical-typesetting-revisited/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/vertical-typesetting-revisited.md)
  * PR 地址：#2997
  * 文章分类：**前端**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Usey95** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Usey95 棒极啦 :tada:

**Comment by leviding** [comment]
@Usey95 翻译的怎么样啦

**Comment by Usey95** [comment]
@leviding 已经翻了一半了 不过最近爆炸忙 可能需要再等两天

**Comment by leviding** [comment]
好的

**Comment by fanyijihua** [comment]
PR 地址：#2997
