### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by u5656487** [xitu/gold-miner#2608]
- 公司/学校：Australian National University
- 工作内容/专业：Bachelor of Software Engineering (honour)
- 常浏览的国外网站：stackoverflow,github,reddit,quora
- 英语水平：雅思6.5, NAATI(The National Accreditation Authority for Translators and Interpreters)澳洲官方三级笔译(英译中)认证
- 有无翻译经验：有过八个月NAATI专业翻译学习,并通过最终考试
- 个人介绍：喜欢逛各种技术社区和开发者博客,资深潜水党,时时关注最新科技技术话题, 想成为一名合格优秀的AI learner,希望能有机会翻译AI,DL或者Spark方面的文章.

**Comment by leviding** [comment]
Hi @u5656487 ，感谢你申请加入掘金翻译计划，你需要做以下的事：

**1.** 加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**：姓名 + GitHub 昵称。

**2.** 认真学习 [掘金翻译计划译者教程](https://github.com/xitu/gold-miner/wiki)，校对和翻译文章时，严格遵循教程，杜绝不看教程，只知道问的伸手党。

**3.** 复习 [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)，翻译文章时严格遵循，校对文章时也要指出译者的格式错误。

**4.** 复习 [翻译和校对文章的注意事项](https://github.com/xitu/gold-miner/wiki/%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88)，避免翻译校对过程中出错。

**注意**：管理员每天集中处理一次，稍安勿躁。加完微信后，管理员会在当天拉你进译者群，进群之后做下简单的自我介绍。加入微信群则代表申请译者成功，接下来你需要看译者教程，然后先校对至少一篇文章才能开始正式翻译文章。当然也可以继续校对文章。
