### ISSUE TITLE
比特币的三个经济阶段

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2611]
* 原文链接：[The Three Economic Eras of Bitcoin](https://medium.com/@rusty_lightning/the-three-economic-eras-of-bitcoin-d43bf0cf058a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-three-economic-eras-of-bitcoin.md)
  * PR 地址：#3112
  * 文章分类：**区块链**
  ----
  * 翻译时间：5 天
  * 校对时间：1.5 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by huanglizhuo** [comment]
认领 @leviding

**Comment by leviding** [comment]
@huanglizhuo 用关键字，翻译认领或认领翻译

**Comment by huanglizhuo** [comment]
ok 下次注意 :)

**Comment by leviding** [comment]
@huanglizhuo 好的，辛苦了

**Comment by huanglizhuo** [comment]
@leviding  sorry sorry sorry 决定放弃翻译 
开始翻译后表示有些术语完全不会翻译，对区块链了解太少，以及一些应该是经济相关的概念用语完全不懂 :( 
还是等懂区块链的同学翻译吧

**Comment by leviding** [comment]
@ok

**Comment by ppp-man** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ppp-man 棒极啦 :tada:

**Comment by leviding** [comment]
@ppp-man 翻译的怎么样啦

**Comment by ppp-man** [comment]
@leviding 明天前大概可以完成初译

**Comment by fanyijihua** [comment]
PR 地址：#3112
