### ISSUE TITLE
全新 Android 注入器 : Dagger 2 （一）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2613]
* 原文链接：[New Android Injector with Dagger 2 — part 1](https://medium.com/@iammert/new-android-injector-with-dagger-2-part-1-8baa60152abe)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/new-android-injector-with-dagger-2-part-1.md)
  * PR 地址：
  * 文章分类：**Android**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MummyDing** [comment]
还没有人认领吗？ 有兴趣翻译一下

**Comment by leviding** [comment]
@MummyDing ok

**Comment by leviding** [comment]
之后认领任务要按照译者教程来哈

**Comment by MummyDing** [comment]
好的，谢谢提醒

**Comment by fanyijihua** [comment]
PR 地址：#2799
