### ISSUE TITLE
New Android Injector with Dagger 2 — part 2

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2614]
* 原文链接：[New Android Injector with Dagger 2 — part 2](https://medium.com/@iammert/new-android-injector-with-dagger-2-part-2-4af05fd783d0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/new-android-injector-with-dagger-2-part-2.md)
  * PR 地址：#2808
  * 文章分类：**Android**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by woitaylor** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@woitaylor 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2808
