### ISSUE TITLE
JWT：JSON Web Tokens 全方位指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2615]
* 原文链接：[JWT: The Complete Guide to JSON Web Tokens](https://blog.angular-university.io/angular-jwt/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/angular-jwt.md)
  * PR 地址：#2916
  * 文章分类：**前端**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：13 分
  * 校对积分：4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rottenpen** [comment]
认领

**Comment by leviding** [comment]
@rottenpen ok

**Comment by leviding** [comment]
@rottenpen 翻译的怎么样啦
