### ISSUE TITLE
Angular 安全 —— 使用 JSON 网络令牌（JWT）验证：完全指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2616]
* 原文链接：[Angular Security - Authentication With JSON Web Tokens (JWT): The Complete Guide](https://blog.angular-university.io/angular-jwt-authentication/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/angular-jwt-authentication.md)
  * PR 地址：#3123
  * 文章分类：**前端**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Raoul1996** [comment]
@leviding 想翻译认领，但是文章有点太长了。。。qwq

**Comment by fanyijihua** [comment]
@Raoul1996 棒极啦 :tada:

**Comment by Raoul1996** [comment]
oh my god.....
WTF.......

**Comment by Raoul1996** [comment]
领了就领了吧，气哭

**Comment by leviding** [comment]
哈哈哈

**Comment by leviding** [comment]
@Raoul1996 哈哈，翻译的怎么样啦

**Comment by Raoul1996** [comment]
最近期末考试。。。过几天翻译。。。qwq。。。
原谅我。。。

**Comment by leviding** [comment]
嗯啊，考试加油！

**Comment by Raoul1996** [comment]
严重延期，十分抱歉

**Comment by leviding** [comment]
老铁啊

**Comment by leviding** [comment]
@Raoul1996 咋样了，2333，流产了？

**Comment by Raoul1996** [comment]
哎呦我天。。。

**Comment by Raoul1996** [comment]
难产。。

**Comment by Raoul1996** [comment]
正在翻译中

**Comment by leviding** [comment]
2333

**Comment by Raoul1996** [comment]
翻译 75% 了，明天预计能出第一版

**Comment by Raoul1996** [comment]
提交了，真的长
