### ISSUE TITLE
创建无障碍 React 应用

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2617]
* 原文链接：[Creating accessible React apps](http://simplyaccessible.com/article/react-a11y/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/creating-accessible-react-apps.md)
  * PR 地址：#2784
  * 文章分类：**前端**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by llp0574** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@llp0574 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2784
