### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2620]
- 在这认领翻译：https://github.com/xitu/tensorflow/issues/
- 在这认领校对：https://github.com/xitu/tensorflow/pulls/

**Comment by winry01** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@winry01 棒极啦 :tada:

**Comment by winry01** [comment]
本来要发另一篇文章的，不知道为何点到这里了，实在是灰常抱歉，我不是要翻译这个T T
