### ISSUE TITLE
针对 Airbnb 清单页的 React 性能优化

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2624]
* 原文链接：[React Performance Fixes on Airbnb Listing Pages](https://medium.com/airbnb-engineering/recent-web-performance-fixes-on-airbnb-listing-pages-6cd8d93df6f4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/recent-web-performance-fixes-on-airbnb-listing-pages.md)
  * PR 地址：#2767
  * 文章分类：**前端**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zwwill** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@zwwill 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2767
