### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by haowf1** [xitu/gold-miner#2628]
- 公司/学校：蚁视科技
- 工作内容/专业：Android开发工程师
- 常浏览的国外网站：starkoverflow
- 英语水平：4级
- 有无翻译经验：无
- 个人博客：
- 个人介绍：4年工作经验，有提交问题和解决问题行动力，翻译没干过比较感兴趣。

**Comment by leviding** [comment]
Hi @haowf1 ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
