### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by laalaguer** [xitu/gold-miner#2629]
- 公司/学校： 保密
- 工作内容/专业：S1宅社区 CTO
- 常浏览的国外网站：Stackoverflow上的高积分用户
- 英语水平：海外计算机专业硕士水平
- 有无翻译经验：已经帮你们翻过RxJS 的书
- 个人博客：保密
- 个人介绍：保密

**Comment by leviding** [comment]
Hi @laalaguer ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
