### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by oaosj** [xitu/gold-miner#2630]
- 公司/学校：hikam/上师大
- 工作内容/专业：Android、IOS 开发。/计算机软件
- 常浏览的国外网站：Medium 、github、sf、推特
- 英语水平：四六级左右吧
- 有无翻译经验：有
- 个人博客：简书/oaosj
- 个人介绍：从事android IPC音视频开发、IOS几个模块业务逻辑、业余目前看看python，学学Django、研究一些音视频，机器学习文档。

**Comment by leviding** [comment]
Hi @oaosj ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
