### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by LiJiahaoCoder** [xitu/gold-miner#2631]
- 公司/学校：成都信息工程大学
- 工作内容/专业：数字媒体技术专业
- 常浏览的国外网站：github,bbc news,mozilla developer network 
- 英语水平：英语6级516
- 有无翻译经验：曾参与翻译过导师论文
- 个人博客：无
- 个人介绍：个人英语能力较强，暑期在新加坡国立大学参加过学习夏令营，学习内容为webgl

**Comment by leviding** [comment]
Hi @LiJiahaoCoder ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
