### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by yimun** [xitu/gold-miner#2632]
- 公司/学校：Bigo/大连理工大学
- 工作内容/专业：Android开发工程师/计算机科学与技术
- 常浏览的国外网站：Github、Google、Quora
- 英语水平：六级
- 有无翻译经验：无
- 个人博客：https://yimu.me
- 个人介绍：从事Android开发，业余涉猎Python web开发，以及最近在研究深度学习。靠谱细致，工程经验丰富

**Comment by leviding** [comment]
Hi @yimun ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
