### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by lknlll** [xitu/gold-miner#2633]
- 公司/学校：融聚邻里社区教育
- 工作内容/专业：Android
- 常浏览的国外网站：StackOverFlow
- 英语水平：一般
- 有无翻译经验：有
- 个人博客：http://blog.csdn.net/lknlll
- 个人介绍：从事安卓开发2年，13-14年赴Florida交流，有热情参于Android方面的学习和翻译。

**Comment by leviding** [comment]
Hi @lknlll ，感谢你申请加入掘金翻译计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
