### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by lywlefan** [xitu/gold-miner#2634]
- 公司/学校：兰州理工大学
- 工作内容/专业：制药工程专业
- 常浏览的国外网站：gihub
- 英语水平：六级
- 有无翻译经验：无
- 个人博客：简书（Share猿）
- 个人介绍：一个走心的猿！

**Comment by leviding** [comment]
Hi @lywlefan ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
