### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by chenjerry18** [xitu/gold-miner#2635]
- 公司/学校：UMass Amherst
- 工作内容/专业：计算机科学
- 常浏览的国外网站：reddit, theverge, github
- 英语水平：GRE 330, TOEFL 108
- 有无翻译经验：少量
- 个人博客：https://github.com/chenjerry18
- 个人介绍：美国计算机专业研二在读，有一定的安卓开发经验，了解安卓基本架构。

**Comment by leviding** [comment]
Hi @chenjerry18 ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
