### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by jameslee612** [xitu/gold-miner#2636]
- 公司/学校：成都信息工程大学
- 工作内容/专业：数字媒体技术
- 常浏览的国外网站：facebook news,bbc,google scholar,Reddit
- 英语水平：英语六级
- 有无翻译经验：少量
- 个人博客：
- 个人介绍：目前从事网页前端设计

**Comment by leviding** [comment]
Hi @jameslee612  ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
