### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by YangKaka** [xitu/gold-miner#2637]
- 公司/学校：北京琥珀创想科技有限公司
- 工作内容/专业：Android开发工程师/软件工程
- 常浏览的国外网站：google,github
- 英语水平：4级
- 有无翻译经验：有
- 个人博客：http://blog.csdn.net/qq_16558621
- 个人介绍：通过微信交流不是了解的更加深入么  ^_^

**Comment by leviding** [comment]
Hi @YangKaka ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
