### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by MummyDing** [xitu/gold-miner#2638]
- 公司/学校：网易
- 工作内容/专业：Android开发工程师
- 常浏览的国外网站：Quora、stackoverflow
- 英语水平：阅读无障碍，写作&口语一般
- 有无翻译经验：无
- 个人博客：[https://github.com/MummyDing](https://github.com/MummyDing)  [http://blog.csdn.net/mummyding](http://blog.csdn.net/mummyding)
- 个人介绍：日常技术学习英语环境居多，每天还在学习英语

**Comment by leviding** [comment]
Hi @MummyDing ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
