### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by pcdack** [xitu/gold-miner#2639]
- 公司/学校：广东工业大学
- 工作内容/专业：计算机科学与技术
- 常浏览的国外网站：medium
- 英语水平：4级
- 有无翻译经验：翻译过rxjava相关内容
- 个人博客：
- 个人介绍：热爱安卓开发，有安卓开发经验，自认为英语阅读能力可以

**Comment by leviding** [comment]
Hi @pcdack ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
