### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by lytasky** [xitu/gold-miner#2640]
- 公司/学校  蘑菇街
- 工作内容/专业：android基础开发
- 常浏览的国外网站：Twitter、Instagram以及android、tensorflow的官方网站等
- 英语水平：CET6 550+
- 有无翻译经验：在浙大读研究生时期翻译过多篇论文
- 个人博客：无
- 个人介绍：一个在深度学习和android之间徘徊的职场菜鸟

**Comment by leviding** [comment]
Hi @lytasky ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
