### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by ReturnHttp402** [xitu/gold-miner#2641]
- 公司/学校：SAP Labs China/ 华东师范大学
- 工作内容/专业：Java后端开发/ 计算机科学
- 常浏览的国外网站：StackOverflow/ Martin Fowler's blog/ documentation sites...
- 英语水平：六级+中级口译
- 有无翻译经验：有
- 个人博客：https://returnhttp402.github.io/
- 个人介绍：正在研究Android开发

**Comment by leviding** [comment]
Hi @ReturnHttp402 ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
