### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by RoarTiger** [xitu/gold-miner#2643]
- 公司/学校：中国地质大学（武汉）
- 工作内容/专业：自动化
- 常浏览的国外网站：github
- 英语水平：英语六级
- 有无翻译经验：参与过文章校对
- 个人博客：无
- 个人介绍：无

**Comment by leviding** [comment]
Hi @RoarTiger  ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
