### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by noahziheng** [xitu/gold-miner#2644]
- 公司/学校：天津科技大学
- 工作内容/专业：自动化/大前端学习中
- 常浏览的国外网站：Google,Facebook,Github
- 英语水平：CET-4/自学
- 有无翻译经验：无
- 个人博客：https://noahgao.net
- 个人介绍：希望通过翻译学到更多，提高英语应用能力

**Comment by leviding** [comment]
Hi @noahziheng ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
