### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by luoqiuyu** [xitu/gold-miner#2646]
- 公司/学校：华中科技大学
- 工作内容/专业：Android开发
- 常浏览的国外网站：https://medium.com/
- 英语水平：CET6
- 有无翻译经验：校对过文章，目前还没有翻译过
- 个人博客：http://www.cnblogs.com/luoqiuyu/
- 个人介绍：从事Android开发一年

**Comment by leviding** [comment]
Hi @luoqiuyu  ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
