### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by zhiyuanyuan** [xitu/gold-miner#2648]
- 公司/学校：
- 工作内容/专业：android程序员
- 常浏览的国外网站：github，stackoverflow
- 英语水平：四级
- 有无翻译经验：暂无
- 个人博客：https://github.com/zhiyuanyuan
- 个人介绍：英语好，专业相关，对这份计划很有兴趣

**Comment by leviding** [comment]
Hi @zhiyuanyuan ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
