### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by jianhui1012** [xitu/gold-miner#2652]
- 公司/学校：浙江海洋大学
- 工作内容/专业：计算机科学与技术
- 常浏览的国外网站：stackoverflow，hacker news
- 英语水平：一般
- 有无翻译经验：无
- 个人博客：http://www.cnblogs.com/lmf-techniques/
- 个人介绍：热爱开源，喜欢分享，做点值得写的事

**Comment by leviding** [comment]
Hi @jianhui1012 ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
