### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by menogen** [xitu/gold-miner#2653]
- 公司/学校：阿里巴巴/华中科技大学
- 工作内容/专业： 手机淘宝Android开发工程师/计算机科学与技术硕士
- 常浏览的国外网站：stackoverflow，quaro
- 英语水平：六级，托福(93)，GRE(149+165)
- 有无翻译经验：无
- 个人博客：
- 个人介绍：

**Comment by leviding** [comment]
Hi @menogen ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
