### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by xiaohaibin** [xitu/gold-miner#2654]
- 公司/学校：通威集团/重庆邮电大学移通学院
- 工作内容/专业：Android研发工程师/通信工程
- 常浏览的国外网站：GitHub Stackoverflow...
- 英语水平：CET-4
- 有无翻译经验：有
- 个人博客：http://www.jianshu.com/u/42aed90cf5af
- 个人介绍：热衷于移动端研发的Coder

**Comment by leviding** [comment]
Hi @xiaohaibin ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
