### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by wenmin92** [xitu/gold-miner#2655]
- 公司/学校：北京物通时空
- 工作内容/专业：Android
- 常浏览的国外网站：developer.android.com，stackoverflow.com
- 英语水平：CET-4
- 有无翻译经验：无
- 个人博客：
- 个人介绍：佩服国外文档的专业和详细。虽然没有翻译过，但经常看英文文档。

**Comment by leviding** [comment]
Hi @wenmin92  ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
