### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by jacksonke** [xitu/gold-miner#2656]
- 公司/学校：
- 工作内容/专业：
- 常浏览的国外网站：
- 英语水平：
- 有无翻译经验：
- 个人博客：
- 个人介绍：掘金翻译计划Android翻译者，工作多年，目前专注于移动开发。

**Comment by leviding** [comment]
Hi @jacksonke ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。

**Comment by jacksonke** [comment]
Close.
