### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by Yunme** [xitu/gold-miner#2657]
- 公司/学校：浙江雄猫/浙江工业大学
- 工作内容/专业：Android开发工程师/计算机科学与技术
- 常浏览的国外网站：medium.com stackoverflow.com
- 英语水平：大学英语四级
- 有无翻译经验：无
- 个人博客：
- 个人介绍：

**Comment by leviding** [comment]
Hi @Yunme ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
