### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by createBean** [xitu/gold-miner#2658]
- 公司/学校：广州市品高软件股份有限公司/华南理工大学
- 工作内容/专业：Android开发工程师/计算机软件与技术
- 常浏览的国外网站：无
- 英语水平：CET-4
- 有无翻译经验：有
- 个人博客：无
- 个人介绍：无

**Comment by leviding** [comment]
Hi @createBean ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
