### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by JudithOnly** [xitu/gold-miner#266]
点击文章认领发现没一篇文章了，所以来申请成为译者，简单介绍一下我是iOS开发的，五年多的开发经验，在国外呆过一段时间，英文还可以。

**Comment by antonia0912** [comment]
@JudithOnly 欢迎~请加我微信 antonia0912 我来拉你进译者群

**Comment by antonia0912** [comment]
@JudithOnly 欢迎~请加我微信 antonia0912 我来拉你进译者群
