### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by yuzhuguan** [xitu/gold-miner#2660]
- 公司/学校：哈尔滨工程大学
- 工作内容/专业：计算机科学技术
- 常浏览的国外网站：https://developer.android.google.cn/sdk/api_diff/26/changes.html  https://guides.codepath.com/android
- 英语水平：四级
- 有无翻译经验：有
- 个人博客：https://github.com/yuzhuguan
- 个人介绍：android 开发者-开发者-开发者

**Comment by leviding** [comment]
Hi @yuzhuguan ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
