### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by archurcode** [xitu/gold-miner#2661]
- 公司/学校：西安交通大学
- 工作内容/专业：计算机
- 常浏览的国外网站：YouTube，Android官网，GitHub等
- 英语水平：CET-6
- 有无翻译经验：无
- 个人博客：CSDN ArchurSpace
- 个人介绍：热爱生活，热爱技术，有Android开发经验

**Comment by leviding** [comment]
Hi @archurcode ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
