### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by alicemmm** [xitu/gold-miner#2662]
- 公司/学校：网易
- 工作内容/专业：android开发
- 常浏览的国外网站：google
- 英语水平：英语硕士
- 有无翻译经验：有
- 个人博客：
- 个人介绍：android开发4年经验，熟练阅读英文文献。

**Comment by leviding** [comment]
Hi @alicemmm ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
