### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by listen-lavender** [xitu/gold-miner#2663]
- 公司/学校：云南大学
- 工作内容/专业：移动互联网
- 常浏览的国外网站：https://medium.com/；https://github.com；https://stackoverflow.com/；https://news.ycombinator.com/
- 英语水平：六级
- 有无翻译经验：无
- 个人博客：https://github.com/listen-lavender/；http://kuanshijiao.com/
- 个人介绍：技术宅男

**Comment by leviding** [comment]
Hi @listen-lavender ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
