### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by SunnyZYFBoy** [xitu/gold-miner#2665]
- 公司/学校：西安工程大学
- 工作内容/专业：测控技术与仪器
- 常浏览的国外网站：Google、Facebook、TensorFlow
- 英语水平：4级
- 有无翻译经验：无
- 个人博客：https://github.com/SunnyZYFBoy
- 个人介绍：I'm an Android Developer.

**Comment by leviding** [comment]
Hi @SunnyZYFBoy ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
