### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by shawnlinboy** [xitu/gold-miner#2666]
- 公司/学校：Meizu
- 工作内容/专业：Android developer
- 常浏览的国外网站：d.android.com  stackoverflow.com  medium.com 等
- 英语水平：CET-6 / BEC  Vantage Level
- 有无翻译经验：有
- 个人博客：linshen.me
- 个人介绍：http://linshen.me/about-me/

**Comment by leviding** [comment]
Hi @shawnlinboy ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
