### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Jack-Kingdom** [xitu/gold-miner#267]
这是很不错的一个项目啊，在稀土圈的微博上看见的。
简单介绍一下我自己：计算机专业大学生一枚，很喜欢翻译，之前我翻译过scrapy的官方文档，有空常在google translate community 中做一点贡献。
认领的文章都没了，先从校对入手吧~~

**Comment by antonia0912** [comment]
@Jack-Kingdom 欢迎~请加我微信 antonia0912 我来拉你进译者群
