### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by xurui1995** [xitu/gold-miner#2670]
- 公司/学校：上海二三四五网络科技
- 工作内容/专业：Android开发
- 常浏览的国外网站：推特，reddit，youtube，quora
- 英语水平：英语六级
- 有无翻译经验：有
- 个人博客：http://www.cnblogs.com/xurui1995   (大学时候写的)
- 个人介绍：喜欢美剧，喜欢摇滚，谷歌粉，今年刚毕业。

**Comment by leviding** [comment]
Hi @xurui1995 ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
