### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by SouthernBox** [xitu/gold-miner#2676]
- 公司/学校：支点科技
- 工作内容/专业：Android 开发
- 常浏览的国外网站：GitHub
- 英语水平：CET - 4
- 翻译经验：音乐 MV 歌词翻译
- 个人博客：https://juejin.im/user/57c61e43d342d3006b3b7093
- 个人介绍：吃饭睡觉写代码

**Comment by leviding** [comment]
Hi @SouthernBox ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
