### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by wbinarytree** [xitu/gold-miner#2677]
- 公司/学校：[airweb](http://airweb.fr/)
- 工作内容/专业：Android开发
- 常浏览的国外网站：Reddit/androiddev medium/Android官方文档
- 英语水平：托业890
- 翻译经验：在稀土翻译计划校对多篇Android相关文章
- 个人博客：[W_BinaryTree](https://juejin.im/user/590210f4ac502e0063d338f5)
- 个人介绍：在法国的Android开发。经常阅读文档，对官方文档的英文风格非常熟悉。

**Comment by leviding** [comment]
Hi @wbinarytree ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
