### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by songford** [xitu/gold-miner#2678]
- 公司/学校：SAP
- 工作内容/专业：Developer Associate
- 常浏览的国外网站：StackOverflow/GitHub/Wikipedia
- 英语水平：PTE 88/90 ，IELTS 8/9
- 翻译经验：在Wikipedia上帮忙翻译了几篇冷门文章
- 个人博客：chuningsong.com
- 个人介绍：你好，我是宋楚宁。之前在澳洲留学读的硕士，英语水平优秀。希望为谷歌技术引入中国添砖加瓦。谢谢！

**Comment by leviding** [comment]
Hi @songford ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
