### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by emotionl** [xitu/gold-miner#2680]
- 原文链接：https://github.com/Chalarangelo/30-seconds-of-code
- 简要介绍：精心收集的有用的JavaScript代码片段，你可以在30秒或更少的时间内理解。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
Great！感谢推荐，很不错的内容，收藏了。
这个翻译您有兴趣吗？感觉很多东西其实是英文术语，翻译有点变味，有想法可以微信私聊下吗？我微信：517010193。
