### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by huangmaohuoshaoxuexia** [xitu/gold-miner#2685]
- 公司/学校：成都丹露科技有限公司/重庆大学
- 工作内容/专业：Android开发/软件工程
- 常浏览的国外网站：https://developer.android.com/   ；https://github.com/  ;  www.stackoverflow.com/ 
- 英语水平：英语4级
- 有无翻译经验：有
- 个人博客：http://blog.csdn.net/u010194271
- 个人介绍：自从上大学，开始接触的第一门语言便是C语言，逐渐的编程产生了兴趣，到后来主要学Java，毕业后从事Android开发3年的时间，了解了很多新的知识，对原本的基础知识进行了不断巩固，从刚开始的SVN到后来git的对项目管理，在学习过程中，工作中总结出来的及时写博客和大家一起分享，感觉很棒，喜欢和更多的小伙伴一起学习，进步，成长。昨天在掘金正好看到这条消息，希望尽自己微薄的力量帮到他人，所以今天就立即申请， 很期待加入Android文档抓虫计划。谢谢

**Comment by leviding** [comment]
Hi @huangmaohuoshaoxuexia ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
