### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by fredzzt** [xitu/gold-miner#2689]
- 公司/学校：美团
- 工作内容/专业：Android研发
- 常浏览的国外网站：reddit、medium、stackoverflow
- 英语水平：CET-6
- 翻译经验：研究生时期帮导师翻译paper
- 个人博客：无
- 个人介绍：从事Android研发工作2.5年有一定的项目经验和英文水平，活细

**Comment by leviding** [comment]
Hi @fredzzt ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。

**Comment by fanyijihua** [comment]
PR 地址：#6364
