### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by dreamhb** [xitu/gold-miner#2690]
- 公司/学校：科沃斯
- 工作内容/专业：Android开发
- 常浏览的国外网站：github.com stackoverflow
- 英语水平：cet6
- 翻译经验：自己翻译过部分effective java
- 个人博客：dreamhb.github.io
- 个人介绍：对英文和技术很感兴趣

**Comment by leviding** [comment]
Hi @dreamhb ，本次活动是安卓文档捉虫，也就是将安卓官方的中文文档与英文文档进行比对，进行严格校对。挑出术语等翻译不当的地方，然后填充 Android Glossary，这个 Glossary 之后可能就会成为全球开发者英译中的翻译规范。所以需要较高的水平。有几点要求：

1. 有较好的英语水平。
2. 你是有经验的安卓开发，懂得相关术语。
3. 有翻译经验，明确什么样的安卓术语是否应该翻译，怎么翻译。

感觉自己合适的话，可以加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。

感觉不合适的话，你也可以申请加入掘金翻译计划，锻炼自己技术文的翻译，积累翻译经验，方法如下：

**1.** 加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**：姓名 + GitHub 昵称。

**2.** 认真学习 [掘金翻译计划译者教程](https://github.com/xitu/gold-miner/wiki)，校对和翻译文章时，严格遵循教程，杜绝不看教程，只知道问的伸手党。

**3.** 复习 [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)，翻译文章时严格遵循，校对文章时也要指出译者的格式错误。

**4.** 复习 [翻译和校对文章的注意事项](https://github.com/xitu/gold-miner/wiki/%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88)，避免翻译校对过程中出错。

**注意**：请认真正确填写验证信息，否则无法通过审核。管理员每天集中处理一次，稍安勿躁。加完微信后，管理员会在当天拉你进译者群，进群之后做下简单的自我介绍。加入微信群则代表申请译者成功，接下来你需要看译者教程，然后先校对至少一篇文章才能开始正式翻译文章。当然也可以继续校对文章。

**Comment by dreamhb** [comment]
好的，我先申请加入翻译计划吧
