### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by Jadyli** [xitu/gold-miner#2692]
- 公司/学校：上海哔哩哔哩科技有限公司
- 工作内容/专业：Android开发
- 常浏览的国外网站：github,stackoverflow
- 英语水平：六级
- 翻译经验：翻译过bolts文档
- 个人博客：http://blog.csdn.net/u013005791
- 个人介绍：我是一个Android开发程序员，一直觉得系统性地读文档对自己技术提升最有帮助，也开了一个微信公众号“三七文档库”，和大家一起读Android官方文档。

**Comment by leviding** [comment]
Hi @Jadyli ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
