### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by sahadev** [xitu/gold-miner#2695]
- 公司/学校：每日优鲜
- 工作内容/专业：Android应用开发，小程序开发
- 常浏览的国外网站：github，stackoverflow，twitter，ecosia，developer.android.com，google developers，mdn
- 英语水平：大学6级
- 翻译经验：Android官方文档Training整个系列翻译
- 个人博客：http://blog.csdn.net/sahadev_
- 个人介绍：5年工作经验程序狗一枚

**Comment by leviding** [comment]
Hi @sahadev ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
