### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by JasinYip** [xitu/gold-miner#270]
在知乎看到掘金发的专栏文章，知道了这个 repo。

目前是前端工程师，平时会翻译一些觉得不错的文章，这是我以前翻译过的文章可以在 [这里](http://jasinyip.com/search/%E8%AF%91/) 看到，之前也参与过校对：https://github.com/xitu/gold-miner/pull/261 ，只是之前并不知道需要申请成为译者才能校对，所以特意来申请一下。

希望能跟大家一起进步！

**Comment by antonia0912** [comment]
晓得啦！请加我微信antonia0912，我来拉你进译者群
