### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by DXDRush** [xitu/gold-miner#2703]
- 公司/学校：即将入职百度/天津大学
- 工作内容/专业：android研发工程师/计算机科学与技术
- 常浏览的国外网站：https://stackoverflow.com/
- 英语水平：cet-6
- 翻译经验：大学期间参与实验室文献翻译
- 个人博客：http://blog.csdn.net/dxdrush
- 个人介绍：14年毕业，从事android开发工作已有三年时间，很期望参与到此次活动中来，想必一定是一次职业生涯中难忘的体验和经历。

**Comment by leviding** [comment]
Hi @DXDRush ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
