### ISSUE TITLE
mijack申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by MiJack** [xitu/gold-miner#2708]
- 公司/学校：华东师范大学
- 工作内容/专业：计算机科学
- 常浏览的国外网站：github，stackoverflow
- 英语水平：英语四级
- 翻译经验：参与过掘金翻译计划以及android-tech-frontier计划
- 个人博客：mijack.github.io
- 个人介绍：袁宇杰，Android应用和Java开发者，2013年开始接触Android开发，对Android应用开发有较为深入了解，可以熟练阅读Android官方文档。

**Comment by leviding** [comment]
Hi @MiJack ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
