### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by DarkAtlantis** [xitu/gold-miner#2711]
- 公司/学校：轻客智能(江苏)有限公司
- 工作内容/专业：Android 应用开发
- 常浏览的国外网站：Google, Github, StackOverflow
- 英语水平：沟通阅读无障碍，有海外留学经验。
- 翻译经验：暂无，但资料均是查阅英文版，有自己的心得体会。
- 个人博客：暂无
- 个人介绍：从事安卓应用开发三年，经常阅读Google API文档，并有一定见解。期间有两年在跨国企业就职，对文档规范了解较多。同时非常热爱Android，希望能出一份力帮助需要的人。也借此机会与更多的开发者交流提升自己。非常期待加入抓虫计划！

**Comment by leviding** [comment]
Hi @DarkAtlantis ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。

**Comment by DarkAtlantis** [comment]
非常感谢
