### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by wuchengithub** [xitu/gold-miner#2712]
- 公司/学校：京东商城
- 工作内容/专业：Android开发
- 常浏览的国外网站 Android开发者官网
- 英语水平：四级
- 翻译经验：无
- 个人博客：掘金https://juejin.im/entry/5a225c1c51882554bd50de0e
- 个人介绍：android

**Comment by leviding** [comment]
Hi @wuchengithub ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
