### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by SumiMakito** [xitu/gold-miner#2716]
- 公司/学校：本科在校生
- 工作内容/专业：Android 开发者；英语专业
- 常浏览的国外网站：stackoverflow、Google Groups
- 英语水平：CET-4: 630+；CET-6: 610+；专业四级: 优秀
- 翻译经验：参与掘金翻译计划；为自己的开源项目翻译双语版文档
- 个人博客：https://keep.moe
- 个人介绍：平时喜欢开发软件及了解新知识，目前有少量的个人的开源项目。因专业原因，平时也经常接触翻译相关的理论知识及参与翻译任务。希望能为文档本地化做出一份贡献。

**Comment by leviding** [comment]
Hi @SumiMakito ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
