### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by panthole** [xitu/gold-miner#2718]
- 公司/学校：北京爱奇艺科技有限公司
- 工作内容/专业：Android 高级工程师
- 常浏览的国外网站：medium stackoverflow
- 英语水平：英语六级
- 翻译经验：翻译过多篇科技文章
- 个人博客：book.panthole.com 
- 个人介绍：热爱技术，一直在慕课网上学习英文课程

**Comment by leviding** [comment]
Hi @panthole ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
