### ISSUE TITLE
使用 Xcode 的 Scheme 来跑不同的测试集合

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#272]
原文链接：[Using Xcode's Schemes to run a subset of your tests](http://artsy.github.io/blog/2016/04/06/Testing-Schemes/)
掘金链接：[使用 Xcode 的 Scheme 来跑不同的测试集合](http://gold.xitu.io/entry/5710f4b6df0eea0064791e9d)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/Testing-Schemes.md)

翻译时间：5天
校对时间：4天
翻译积分：5
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Tuccuay** [comment]
![Sticker](http://ww1.sinaimg.cn/large/0060lm7Tgw1f2xf3vmop6j303e032q2t.jpg)
要了~

**Comment by antonia0912** [comment]
@Tuccuay 收到~

**Comment by ldhlfzysys** [comment]
我来校对吧~

**Comment by antonia0912** [comment]
@ldhlfzysys 好的 [校对地址](https://github.com/xitu/gold-miner/pull/284/files?diff=split)

**Comment by LoneyIsError** [comment]
@antonia0912 校对完了。

**Comment by LoneyIsError** [comment]
@antonia0912 改好了
