### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by ShaunWilson** [xitu/gold-miner#2726]
- 公司/学校：京东金融
- 工作内容/专业：Android/C/C++开发
- 常浏览的国外网站：github、stackoverflow、android weekly、google developers、youtube、500px、6park
- 英语水平：6级
- 翻译经验:  部门内AI/NVIDIA文献翻译
- 个人博客：https://github.com/ShaunWilson
- 个人介绍：喜欢跑步、阅读，坚持每天背单词、听新概念英语。

**Comment by leviding** [comment]
Hi @ShaunWilson ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
