### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by freedomofme** [xitu/gold-miner#2729]
- 公司/学校：中山大学
- 工作内容/专业：Android开发工程师，软件工程专业，曾在Tencent和Netease实习过Android开发。
- 常浏览的国外网站：https://developer.android  https://stackoverflow.com/
- 英语水平：CET-6
- 翻译经验：为Firefox提供过帮助文档翻译，（例如 https://support.mozilla.org/zh-CN/kb/%E8%8B%B9%E6%9E%9C%E7%94%B5%E8%84%91-%E5%AE%89%E5%85%A8-%E8%AE%BE%E7%BD%AE-%E7%81%AB%E7%8B%90-%E5%BA%94%E7%94%A8%E5%B8%82%E5%9C%BA）
- 个人博客：http://freedomofme.github.io/
- 个人介绍：致力于从事Android开发，希望能为社区尽一份力所能及的绵薄之力。

**Comment by leviding** [comment]
Hi @freedomofme ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
