### ISSUE TITLE
Starlight - 当前端开始写服务端，APP 的时候，写 Lua 的又去准备写前端了 Lua to JavaScript translator :: Embedding Lua in the Web

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#273]
原文链接：[Embedding Lua in the Web](http://starlight.paulcuth.me.uk/docs/embedding-lua-in-the-web)
掘金链接：[Starlight - 当前端开始写服务端，APP 的时候，写 Lua 的又去准备写前端了 Lua to JavaScript translator :: Embedding Lua in the Web](http://gold.xitu.io/entry/570effe55bbb500050ae1b86/view)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/embedding-lua-in-the-web.md)

翻译时间：5天
校对时间：4天
翻译积分：5
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by narcotics726** [comment]
认！

**Comment by antonia0912** [comment]
@narcotics726 得嘞！

**Comment by narcotics726** [comment]
初翻完成，PR已发，待校对

**Comment by yangzj1992** [comment]
申请校验 @antonia0912

**Comment by antonia0912** [comment]
@yangzj1992 [校对地址](https://github.com/xitu/gold-miner/pull/274/files?diff=split)

**Comment by markzhai** [comment]
申请校对

**Comment by antonia0912** [comment]
@markzhai  好的 [校对地址](https://github.com/xitu/gold-miner/pull/274/files?diff=split)
