### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by huanglizhuo** [xitu/gold-miner#2736]
- 公司/学校：中科大
- 工作内容/专业：android 开发
- 常浏览的国外网站：github hackernews
- 英语水平：cet6
- 翻译经验：kotlin 官方文档  掘金翻译计划多篇文章 
- 个人博客：
- 个人介绍：android 开发者，大爱google

**Comment by leviding** [comment]
Hi @huanglizhuo ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
