### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by mmlovesyy** [xitu/gold-miner#2737]
- 公司/学校：美团·大众点评
- 工作内容/专业：安卓开发工程师
- 常浏览的国外网站：developer.android.com，stackoverflow.com，blogspot.com，medium.com
- 英语水平：cet-6（540分）
- 翻译经验：良
- 个人博客：http://blog.csdn.net/zhaizu
- 个人介绍：爱写作，爱技术，爱生活

**Comment by leviding** [comment]
Hi @mmlovesyy ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
