### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by Vsevorod** [xitu/gold-miner#2739]
- 公司/学校：同济大学
- 工作内容/专业：软件工程
- 常浏览的国外网站：github, glassdoor, washingtonpost, nytimes 
- 英语水平：六级538
- 翻译经验：参与过sap product support bw onpremise 文档翻译 
- 个人博客：
- 个人介绍：

**Comment by leviding** [comment]
希望能够认真对待每件事，想参加应该认真填写个人资料。

**Comment by Vsevorod** [comment]
公司/学校：同济大学
工作内容/专业：软件工程
常浏览的国外网站：github, glassdoor, washingtonpost, nytimes，pixiv
英语水平：六级538
翻译经验：参与过sap product support bw onpremise 文档翻译
个人博客：没有。。
个人介绍：之前在sap实习，参与了BW一款产品和内部培训文档的用户手册的翻译和校对工作。之前几年因为学业关系，接触的技术书籍当中英文参考资料较多，看MSDN，StackOverflow, C++primer，AngularJS，和IBM关于大型机和cobol的红宝书和一些学术论文【做过一段时间生物信息学，制药容错方面的工作】并没遇到过很多压力。目前在准备考研中，下个礼拜也就结束了。之后比较闲【实际没有任何事】，能够有充分的精力做好校对工作。

**Comment by leviding** [comment]
Hi @Vsevorod ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
