### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by zhangzhigang168** [xitu/gold-miner#2740]
- 公司/学校：新安金融
- 工作内容/专业：android开发
- 常浏览的国外网站: stackoverflow ，CodeGuru
- 英语水平：四级
- 翻译经验：平时翻译一些零星短文
- 个人博客：oschina
- 个人介绍：从事java android 开发多年

**Comment by leviding** [comment]
Hi @zhangzhigang168 ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
