### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by yazhi1992** [xitu/gold-miner#2743]
- 公司/学校：杭州小余小余教育科技有限公司
- 工作内容/专业：Android开发
- 常浏览的国外网站：InfoQ、stackoverflow
- 英语水平：六级
- 有无翻译经验：为掘金翻译计划贡献过2篇翻译+6篇校对
- 个人博客：http://www.jianshu.com/u/a5eb0a8294e1
- 个人介绍：Android 爱好者，本身也从事 Android 开发工作，对相关技术有一定的了解和经验，也在掘金认领过翻译和校对，对翻译也有一定的经验，这次难得和 Google 爸爸合作，很希望为 Android 贡献自己的一份力量！

**Comment by leviding** [comment]
Hi @yangzj1992 ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。

**Comment by yangzj1992** [comment]
@leviding 呼叫友军错误了(｡･∀･)

**Comment by leviding** [comment]
Hi @yazhi1992 ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。

**Comment by leviding** [comment]
@yangzj1992 哈哈哈，感谢提醒
