### ISSUE TITLE
如何紧跟未来的设计趋势：15 个让你永远不过时的资料

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2755]
* 原文链接：[Where to Spot New Design Trends: 15 Sources to Stay Fresh](https://medium.com/building-creative-market/where-to-spot-new-design-trends-15-sources-to-stay-fresh-8877d6e097b8)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/where-to-spot-new-design-trends-15-sources-to-stay-fresh.md)
  * PR 地址：#2922
  * 文章分类：**设计**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kangkai124** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@kangkai124 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2922
