### ISSUE TITLE
论原子 CSS 的日益普及

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2756]
* 原文链接：[On the Growing Popularity of Atomic CSS](https://css-tricks.com/growing-popularity-atomic-css/?utm_source=SitePoint&utm_medium=email&utm_campaign=Versioning)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/growing-popularity-atomic-css.md)
  * PR 地址：#2897
  * 文章分类：**前端**
  ----
  * 翻译时间：5 天
  * 校对时间：1.5 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunshine940326** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sunshine940326 棒极啦 :tada:

**Comment by leviding** [comment]
@sunshine940326 翻译的怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#2897
