### ISSUE TITLE
将网站转换为渐进式 Web 应用程序之简易教程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2757]
* 原文链接：[The easy way to turn a website into a Progressive Web App](https://dev.to/pixeline/the-easy-way-to-turn-a-website-into-a-progressive-web-app-77g)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-easy-way-to-turn-a-website-into-a-progressive-web-app.md)
  * PR 地址：#2849
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by bambooom** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@bambooom 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2849
