### ISSUE TITLE
Chrome DevTools - 性能监控

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2758]
* 原文链接：[Chrome DevTools- Performance monitor](https://hospodarets.com/chrome-devtools-performance-monitor?utm_source=SitePoint&utm_medium=email&utm_campaign=Versioning)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/chrome-devtools-performance-monitor.md)
  * PR 地址：#2766
  * 文章分类：**前端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunshine940326** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sunshine940326 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2766

**Comment by leviding** [comment]
@sunshine940326 真速度
