### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by muzidx** [xitu/gold-miner#276]
我是一名已经工作了的FER，前端工程师；我喜欢记录技术文章和情感心得等好玩的故事；
刚接触稀土掘金是在几个月之前，看到文章分享的内容，感觉很不错，对于感兴趣的文章已经看了很多，这里成为了我业余时间必逛的博客网站之一；我希望加入掘金译者的活动中来，同时学习更多的外国新技术，附上我的博客地址：http://www.muzidx.com  ，谢谢～

**Comment by antonia0912** [comment]
欢迎欢迎~请加我微信 antonia0912 我来拉你进译者群喔~
