### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by d260752139** [xitu/gold-miner#2763]
- 公司/学校：DesaySV
- 工作内容/专业：Framework工程师
- 常浏览的国外网站：developer.android.com,source.android.com
- 英语水平：CET-4
- 有无翻译经验：无
- 个人博客：
- 个人介绍：

**Comment by leviding** [comment]
Hi ，因为本次活动有人数限制，报名人数也非常多，所以我们会根据申请者所填写的内容进行筛选。主要是需要较高的英语等级和翻译经验。
