### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by caiyongji** [xitu/gold-miner#2764]
- 公司/学校：CITI
- 工作内容/专业：Application Programming Expert
- 常浏览的国外网站：stackoverflow, google, bbc(News websites)
- 英语水平：IETLS 7688
- 翻译经验：
- 个人博客：caiyongji.com
- 个人介绍：I LOOOOVE GOOGLE VERY MUCH!

**Comment by leviding** [comment]
Hi @caiyongji ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
