### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by silencezwm** [xitu/gold-miner#2775]
- 公司/学校：邢帅教育  吉首大学
- 工作内容/专业：负责邢帅教育Android App整体研发工作。  电子信息工程
- 常浏览的国外网站：github  google  StackOverFlow
- 英语水平：国家英语四级
- 翻译经验：暂无，但我细心，有激情，有掘金团队、伙伴在身边呀！难不倒我
- 个人博客：https://juejin.im/user/56f73b6cd342d30055a9aab1
- 个人介绍：15年毕业至今一直从事安卓开发，现在更喜欢在掘金上分享自己的所学，掘金多次线下活动在北京，可以广州的我无法参加，此次抓虫我来了！让我加入吧！一起抓虫，一起吃虫！

**Comment by leviding** [comment]
Hi @silencezwm ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
