### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by Jaapin** [xitu/gold-miner#2779]
- 公司/学校：中国计量大学
- 工作内容/专业：计算机
- 常浏览的国外网站：github 
- 英语水平：英语6级
- 翻译经验：暂无
- 个人博客：http://blog.csdn.net/u014213965/article/category/6405224
- 个人介绍：

**Comment by leviding** [comment]
@Jaapin 请认真填写以上信息、
