### ISSUE TITLE
Android文档抓虫校对

### ISSUE THREAD

**Issue by xurui1995** [xitu/gold-miner#2780]
- 哪一项：API
- 问题描述：原译者提交的翻译为API版本3, 备注也有问题
- 怎样是正确的：中文 API ,备注：This is a well-known term. Keep English name.

**Comment by leviding** [comment]
![](https://i.loli.net/2017/12/18/5a3749583dec8.png)

有译者在前面提交了较好的 API 翻译，nazhegejiuguanliha那这个就关了哈
