### ISSUE TITLE
Android文档抓虫校对

### ISSUE THREAD

**Issue by shawnlinboy** [xitu/gold-miner#2783]
- 哪一项：Context
- 问题描述：Context 在国内被普遍翻译成“上下文”，但这实在是一处“为了有中文翻译而有的一个翻译”，因为它本身并不是“上下文”的意思，而且基本上做 android 开发的人都会理解它是什么意思，就像 apk 一样
- 怎样是正确的：建议保留英文原文

**Comment by SumiMakito** [comment]
个人认为此问题有待讨论，一方面「Context」可以指 Android 中用来传递代码运行中存储环境信息的对象，也即「Context 类」，此时不译更好，因其指代的类名是英文，翻译可能会对搜索带来困难；然而，另一方面「Context」也可以指这个「Context 类」的实例化对象所存储的环境信息其本身，此时的「Context」就相对抽象，此处并非「为了有中文翻译而有的一个翻译」，可能「上下文」会给人带来一定要找到回指的实体的感觉，但其意在指可供代码正常执行逻辑的「环境」或「语境」。

**Comment by leviding** [comment]
@SumiMakito 这种情况你需要在中文翻译处用 `上下文/Context` 来表示有两种译法，并且在备注中进行详细解释。
@shawnlinboy 本次校对成功，本词条每人算一个贡献度。
