### ISSUE TITLE
Android文档抓虫校对

### ISSUE THREAD

**Issue by shawnlinboy** [xitu/gold-miner#2785]
- 哪一项：Android Emulator
- 问题描述：应当避免对 Android 本身进行翻译
- 怎样是正确的：Android 模拟器

**Comment by leviding** [comment]
![image](https://user-images.githubusercontent.com/26959437/34090814-a7947f96-e3f4-11e7-825e-d90adc8ebaa5.png)

译者在备注里标注了，欢迎校对更多内容。
