### ISSUE TITLE
Android文档抓虫校对

### ISSUE THREAD

**Issue by lifangwang** [xitu/gold-miner#2791]
- 哪一项：out-of-memory
- 问题描述：译文为"内存溢出“，实际的含义为内存用尽，内存不足
- 怎样是正确的：内存不足(OOM)

**Comment by yiguohan** [comment]
有待商榷。out of memory本意是表达所需内存超出机器本身所有的大小，内存不足的翻译是经过一步的逻辑推理得出的结论，没有还原英文本来的信息。个人认为“内存溢出”的翻译是可以的。

**Comment by lifangwang** [comment]
技术上没有"内存溢出”这个概念， 你可以说buffer溢出，但没有说内存溢出的。换句话说"内存溢出"意思是跑到内存能容纳的范围之外了，这是不可能发生的。所以我觉得不管是从字面理解还是从技术理解，OOM都是内存用尽不够用的含义。

**Comment by wzasd** [comment]
New configuration options let OEMs tune out-of-memory levels for processes原文在这里，就是新的配置可以让OEMs把进程的OOM等级调高，我觉得是内存溢出的意思，我觉得这个只是一个语义

**Comment by SouthernBox** [comment]
out-of-memory 和 OOM 重复，已删除。
当前讨论同样适用于 OOM 词条。

**Comment by lifangwang** [comment]
“溢出”这个词对应的是overrun/overflow，感觉“内存溢出”是出了bug，像堆栈溢出一样。。。
