### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by adonis-lsh** [xitu/gold-miner#2792]
- 公司/学校：用友网络科技股份有限公司
- 工作内容/专业：Android开发工程师
- 常浏览的国外网站：StackOVerflow,googleblog,android-arsenal,Android官网
- 英语水平：四级
- 翻译经验：FileProvider的官方文档翻译
- 个人博客：www.bendaidai.top
- 个人介绍：我愿意成为别人嘴中那个别人家的孩子,朋友

**Comment by leviding** [comment]
Hi @adonis-lsh ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 用户名 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
