### ISSUE TITLE
Android 文档抓虫校对（成功）

### ISSUE THREAD

**Issue by Yunme** [xitu/gold-miner#2794]
- 哪一项：instrumented test
- 问题描述：原翻译为工具测试，其实际意思应为在设备上进行测试。
- 怎样是正确的：设备化测试

**Comment by wzasd** [comment]
The Android Instrumented Tests template is for an instrumented test. The Android JUnit template is for a local unit test. 原文在这里，The Android Instrumented Tests 就是算是工具测试，是为了单元测试，所以个人认为不是设备化测试，是Android内部工具测试

**Comment by lifangwang** [comment]
Android Instrumented Test建议不翻译，这个是指基于Instrumentation测试框架所做的测试，在注释部分增加相应的中文说明就可以了

**Comment by Yunme** [comment]
这里说的是字面意思上的 instrumented test , 而非 Android Instrumented Tests , 后者可以认为是专有名词，可以不翻译，前者可以翻译为真机测试，或设备化测试，但个人觉得真机测试有些口语化，设备化测试更好一些。

**Comment by leviding** [comment]
@Yunme 校对成功
