### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by jelychow** [xitu/gold-miner#2797]
- 公司/学校：苏州良医汇网络科技有限公司/南京林业大学
- 工作内容/专业：android
- 常浏览的国外网站：github/stackoverflow
- 英语水平：cet-4
- 翻译经验：negtive
- 个人博客：http://www.jianshu.com/u/817916e1e55a
- 个人介绍：我目前从事android开发三年有余，业余也会翻译一些官方文档，我博客的前三篇文章皆是翻译自官方文档。

**Comment by leviding** [comment]
Hi @jelychow ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 昵称 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
