### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by Keith-Gong** [xitu/gold-miner#2798]
- 公司/学校：Movoto
- 工作内容/专业：Android Developer
- 常浏览的国外网站：StackOverFlow， Quora， Facebook， Android Doc
- 英语水平：CET-6
- 翻译经验：无
- 个人博客：无
- 个人介绍：无

**Comment by leviding** [comment]
@Keith-Gong 请认真填写相关信息
