### ISSUE TITLE
在 React & Redux 中使用 AJAX 轮询

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2800]
* 原文链接：[AJAX POLLING IN REACT WITH REDUX](http://notjoshmiller.com/ajax-polling-in-react-with-redux/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/ajax-polling-in-react-with-redux.md)
  * PR 地址：#2888
  * 文章分类：**前端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@yoyoyohamapi 你的。

**Comment by yoyoyohamapi** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@yoyoyohamapi 棒极啦 :tada:

**Comment by lcx-seima** [comment]
认领翻译

**Comment by leviding** [comment]
@lcx-seima 已经被认领啦

**Comment by yoyoyohamapi** [comment]
@leviding 你好，转给@lcx-seima 吧，我做校对

**Comment by leviding** [comment]
@yoyoyohamapi ok
@lcx-seima 辛苦了

**Comment by leviding** [comment]
@yoyoyohamapi ok
@lcx-seima 辛苦了

**Comment by FateZeros** [comment]
还需要校对吗

**Comment by leviding** [comment]
@FateZeros 需要，等本文翻译完， 到 pull request 下认领。

**Comment by leviding** [comment]
@yoyoyohamapi 翻译的怎么样啦

**Comment by lcx-seima** [comment]
@leviding 不好意思慢了点。今晚给一篇，明天给一篇吧。

**Comment by fanyijihua** [comment]
PR 地址：#2888
