### ISSUE TITLE
在 Redux 中使用 AJAX 轮询（二）：Saga 篇

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2801]
* 原文链接：[AJAX POLLING IN REDUX PART 2: SAGAS](http://notjoshmiller.com/ajax-polling-part-2-sagas/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/ajax-polling-part-2-sagas.md)
  * PR 地址：#2892
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@yoyoyohamapi 你的

**Comment by yoyoyohamapi** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@yoyoyohamapi 棒极啦 :tada:

**Comment by lcx-seima** [comment]
认领翻译

**Comment by leviding** [comment]
@lcx-seima 已经被认领啦

**Comment by yoyoyohamapi** [comment]
@leviding 你好，转给@lcx-seima 吧，我做校对

**Comment by leviding** [comment]
@yoyoyohamapi ok
@lcx-seima 辛苦了

**Comment by leviding** [comment]
@lcx-seima 翻译的怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#2892
