### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by ronalmessi** [xitu/gold-miner#2803]
- 公司/学校：宁波爱班信息技术有限公司/宁波大学
- 工作内容/专业：android客户端开发/计算机应用与技术
- 常浏览的国外网站：http://androidweekly.net
- 英语水平：六级
- 翻译经验：研究生期间翻译了一些国外的学术论文
- 个人博客：
- 个人介绍：

**Comment by leviding** [comment]
@ronalmessi 请认真填写上述信息
