### ISSUE TITLE
请求翻译“Android MVP 架构必要知识第三部分”

### ISSUE THREAD

**Issue by zhouzl18** [xitu/gold-miner#2807]
原文链接：https://blog.mindorks.com/essential-guide-for-designing-your-android-app-architecture-mvp-part-3-dialog-viewpager-and-7bdfab86aabb

第一部分翻译：https://juejin.im/entry/58a27b2d2f301e006958d4aa?utm_source=gold-miner&utm_medium=readme&utm_campaign=github
第二部分翻译：https://juejin.im/entry/58a5992961ff4b006c4455e3?utm_source=gold-miner&utm_medium=readme&utm_campaign=github
前面两部分已经翻译了，但我没找到第三部分的翻译，请翻译下，非常感谢！

**Comment by leviding** [comment]
@zhouzl18 好的，感谢推荐，本文明天放上来进行翻译

**Comment by zhouzl18** [comment]
好的，非常感谢😗

2017-12-18 19:46 GMT+08:00 LeviDing <notifications@github.com>:

**Comment by leviding** [comment]
已经放上去啦 https://github.com/xitu/gold-miner/issues/2822
有需求的话可以及时关注 @zhouzl18
