### ISSUE TITLE
Android 文档抓虫校对（成功）

### ISSUE THREAD

**Issue by SumiMakito** [xitu/gold-miner#2810]
- 哪一项：Picture-in-picture
- 问题描述：是 Android 8.0 以后新加入的特性，此项译为「画中画」是否更好些呢？记得这个特性最早在家用电视机上出现过，当时也译为「画中画」，感觉比较容易说明其样式和作用。
- 怎样是正确的：画中画

**Comment by leviding** [comment]
@SumiMakito 校对成功
