### ISSUE TITLE
全新 Android 注入器 : Dagger 2（三）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2817]
* 原文链接：[New Android Injector with Dagger 2 — part 3](https://android.jlelse.eu/new-android-injector-with-dagger-2-part-3-fe3924df6a89)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/new-android-injector-with-dagger-2-part-3.md)
  * PR 地址：#2820
  * 文章分类：**Android**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@woitaylor 你的

**Comment by woitaylor** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@woitaylor 好的

**Comment by fanyijihua** [comment]
PR 地址：#2820
