### ISSUE TITLE
Android文档抓虫校对

### ISSUE THREAD

**Issue by jianhui1012** [xitu/gold-miner#2819]
- 哪一项：best practice
- 问题描述：第一个问题不是术语，另外，中文版本翻译成最佳做法比较自然，改成最佳实践反而生硬。
- 怎样是正确的：最佳做法
![image](https://user-images.githubusercontent.com/8265384/34150738-3510588c-e4e4-11e7-8c14-6ec16538ac3c.png)

**Comment by leviding** [comment]
@jianhui1012 一般是翻译为最佳实践。通过你的校对，我找到了几个不符合要求的词条，所以加 1 个贡献度。
