### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by xuexzgit** [xitu/gold-miner#282]
从事Android开发2年多，平时会阅读一些Android相关的英文技术文档，也会上StackOverflow等英文网站，非常喜欢掘金翻译的一些文章，也希望自己能翻译/校对一些英文文章。

**Comment by antonia0912** [comment]
已通过 稍等拉你进译者群

**Comment by gdgzjuck** [comment]
已经接触Android大概3年多了，从事开发也两年了，目前觉得自己英语阅读能力比较强，也经常在看谷歌官网的Android指南，也希望自己能翻译/校对一些英文文章。

**Comment by warcryDoggie** [comment]
- 大三在校生，一年web前端开发经验
- 英语CET6水平，阅读stackOverflow、英文文档、参加Coursera课程基本无障碍。
- 本科专业印刷工程。对字体设计，图像处理，桌面排版有一定了解，可以辅助相关术语校对。

**Comment by antonia0912** [comment]
@gdgzjuck 要单独发issue申请成为译者喔~点[这里](https://github.com/xitu/gold-miner/issues)
