### ISSUE TITLE
漫画图解 JavaScript 引擎： let jsCartoons = ‘Awesome’;

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2821]
* 原文链接：[Understanding JavaScript’s Engine with Cartoons](https://codeburst.io/understanding-javascripts-engine-with-cartoons-3ef56487a987)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/understanding-javascripts-engine-with-cartoons.md)
  * PR 地址：#3043
  * 文章分类：**前端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@MechanicianW 你的

**Comment by MechanicianW** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MechanicianW 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3043
