### ISSUE TITLE
Android MVP 架构必要知识：第三部分（Dialog，ViewPager，RecyclerView 以及 Adapters)

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2822]
* 原文链接：[Essential Guide For Designing Your Android App Architecture: MVP: Part 3 (Dialog, ViewPager, RecyclerView, and Adapters)](https://blog.mindorks.com/essential-guide-for-designing-your-android-app-architecture-mvp-part-3-dialog-viewpager-and-7bdfab86aabb)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/essential-guide-for-designing-your-android-app-architecture-mvp-part-3.md)
  * PR 地址：#2920
  * 文章分类：**Android**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by woitaylor** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@woitaylor 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2920
