### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by onlynight** [xitu/gold-miner#2844]
- 公司/学校：西南科技大学
- 工作内容/专业：软件工程
- 常浏览的国外网站：google,github,stackoverflow,androiddev
- 英语水平：大学英语四级
- 翻译经验：做过一些单片机技术文档翻译
- 个人博客：http://blog.csdn.net/tgbus18990140382
- 个人介绍：极客程序员

**Comment by leviding** [comment]
Hi @onlynight ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 用户名 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
