### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by hanliuxin5** [xitu/gold-miner#2852]
- 公司/学校：四川弘和集团
- 工作内容/专业：Android开发者
- 常浏览的国外网站：medium, Instagram, Facebook, YouTube
- 英语水平：工作后在英孚英语培训已经2年，能和外教谈笑风生
- 翻译经验：只粗略翻译过一次dagger2的文档(在个人博客有提到)
- 个人博客：https://segmentfault.com/u/lizhiwodage
- 个人介绍：从事安卓开发3年，小谷歌粉一枚，热血自己的事业，希望条件允许的话出自己的一份力

**Comment by leviding** [comment]
Hi @hanliuxin5 ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 用户名 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
