### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by MartinCN** [xitu/gold-miner#2853]
- 公司/学校：新浪
- 工作内容/专业：Android App开发
- 常浏览的国外网站：developer.android.com
- 英语水平：能懂英文文档
- 翻译经验：暂时还没有
- 个人博客：无
- 个人介绍：5年Android开发经验，一致在做Android 应用层面app开发。

**Comment by leviding** [comment]
Hi @MartinCN ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 用户名 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
