### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by tracyliu1** [xitu/gold-miner#2854]
- 公司/学校：沈阳大学
- 工作内容/专业：通信工程  Android 开发（机顶盒 TV方向）
- 常浏览的国外网站：YouTube Google Stackoverflow Facebook twitter ...
- 英语水平：四级
- 翻译经验：大学时参加过一些体育论坛的新闻翻译以及球员百科（唉，虎扑上找不到了）
- 个人博客：http://www.jianshu.com/u/f3e983f3f303 （简书马上注销了，个人的GitPage上的刚刚搭建）
- 个人介绍：阅读水平还可以，高考分123。高中之后就没有在学习过，水平提高全靠看剧。17年初去了趟LA,在一家叫Verimatrix的公司上了听了一周课。大体水平就是比上不足比下有余吧。跟重点的学霸不能比，只希望贡献自己一份力量。

**Comment by leviding** [comment]
Hi @tracyliu1 ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 用户名 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
