### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by XiaMuYaoDQX** [xitu/gold-miner#2857]
- 公司/学校：哈尔滨远东理工学院
- 工作内容/专业：计算机网络
- 常浏览的国外网站：leetcode,bbc
- 英语水平：四级
- 翻译经验：暂无
- 个人博客：http://www.jianshu.com/u/90f8ae492138
- 个人介绍：希望通过自己的一些成果帮助别人更提高自己

**Comment by XiaMuYaoDQX** [comment]
谢谢😏

**Comment by leviding** [comment]
Hi @XiaMuYaoDQX ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 用户名 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。

**Comment by XiaMuYaoDQX** [comment]
thank you


2017-12-21 13:42 GMT+08:00 LeviDing <notifications@github.com>:
