### ISSUE TITLE
申请加入新文章

### ISSUE THREAD

**Issue by huanglizhuo** [xitu/gold-miner#286]
这篇android studio 的文章挺好的
https://medium.com/google-developers/about-10-things-you-probably-didn-t-know-you-could-do-in-android-studio-de231071b375#.2xje2hkf4

建议加入翻译计划
@antonia0912

**Comment by antonia0912** [comment]
@huanglizhuo 好的 已经反馈给领导了  我听指示~蟹蟹推荐~
