### ISSUE TITLE
Android文档抓虫校对

### ISSUE THREAD

**Issue by yiguohan** [xitu/gold-miner#2860]
- 哪一项：circular reveal
- 问题描述：译者给出的glossary翻译“圆形揭露”不通顺。"circular"有"循环"的意思，“reveal”有“展示”之意。而且在原文中应该是三个词 circular reveal animations连起来是一个固定的glossary
- 怎样是正确的：circular reveal animations按原文翻译“循环展示动画”或“圆形循环展示动画”即可。

**Comment by leviding** [comment]
@yiguohan 校对成功
