### ISSUE TITLE
Android 文档抓虫校对（成功）

### ISSUE THREAD

**Issue by yiguohan** [xitu/gold-miner#2861]
- 哪一项：Signing
- 问题描述：原页面对应的四个地方分别是 signing your app in Android Studio/signing settings/signing configuration/signing 其中有三个地方是和 名词/名词短语 连接 形成动宾短语。因此signing在此处应翻译为动词“签署”，不能翻译成名词“签名”
- 怎样是正确的：原翻译 “签署”是正确的

**Comment by livmortis** [comment]
“签名”也可当做不及物动词看，signing your app 这种短语中sign作为及物动词，只需译成“为app添加签名”即可，个人看法。

**Comment by yiguohan** [comment]
signing做不及物动词的情况在该页面就是 signing的那个title(也就是上面四种情况的最后一种)，那里表示的是签署的这个动作
