### ISSUE TITLE
申请加入Android文档抓虫计划

### ISSUE THREAD

**Issue by shoewann0402** [xitu/gold-miner#2873]
- 公司/学校：成都聚联互动科技有限公司
- 工作内容/专业：Android development
- 常浏览的国外网站：All of Google websites, Stackoverflow, Github, Medium
- 英语水平：中级
- 翻译经验：较熟练
- 个人博客：Shoewann0402.github.io
- 个人介绍：Android Developer & Google 爱好者、原上海GDG社区成员、自主搭建博客翻译总结Google相关技术文档博客，部分内容还早于国内官方博客翻译发布。参与微博@Google谷歌爱好者的微信公众号(GoogleNews)内容的发布。

**Comment by shoewann0402** [comment]
申请加入Android文档抓虫计划

**Comment by leviding** [comment]
Hi @shoewann0402 ，感谢你申请加入Android 官方文档抓虫计划，加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**： GitHub 用户名 + 捉虫。管理员集中处理，稍安勿躁。已经加群了的请忽略。
