### ISSUE TITLE
Xcode 环境配置最佳实践

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2889]
* 原文链接：[Effective Environment Switching in iOS](https://medium.com/@volbap/effective-environment-switching-in-ios-6df0b08e9556)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/effective-environment-switching-in-ios.md)
  * PR 地址：#3015
  * 文章分类：**iOS**
  ----
  * 翻译时间：5 天
  * 校对时间：1.5 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by swants** [comment]
翻译认领   终于有 iOS 的文章了 老泪纵横

**Comment by fanyijihua** [comment]
@swants 棒极啦 :tada:

**Comment by leviding** [comment]
哈哈哈哈，我尽量找吧，不会 iOS，找起来有点费劲 2333

**Comment by fanyijihua** [comment]
PR 地址：#3015
