### ISSUE TITLE
开启你的开源生涯

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2890]
* 原文链接：[Start your open-source career](https://blog.algolia.com/start-your-open-source-career/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/start-your-open-source-career.md)
  * PR 地址：#3085
  * 文章分类：**教程**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@jonjia 你的

**Comment by zwwill** [comment]
翻译认领

**Comment by zwwill** [comment]
咦~被领了？

**Comment by leviding** [comment]
嗯 🤣 ， https://dev.to/munamohamed94/front-end-web-development-is-not-what-you-think-it-is-1ib
这篇你翻译不，翻译我就现在放上去 @zwwill

**Comment by zwwill** [comment]
@leviding 这篇就算了。质量不高

**Comment by leviding** [comment]
还有推荐的可以给我哈

**Comment by zwwill** [comment]
届时我来校对吧。

**Comment by leviding** [comment]
ok 的

**Comment by jonjia** [comment]
翻译认领

**Comment by zwwill** [comment]
还没翻译完？

**Comment by zwwill** [comment]
还要不要转给我

**Comment by leviding** [comment]
@zwwill 你来翻译吧

**Comment by jonjia** [comment]
@leviding 不好意思，最近时间紧张，辛苦了 @zwwill
