### ISSUE TITLE
Object Composition 中的宝藏

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2891]
* 原文链接：[The Hidden Treasures of Object Composition](https://medium.com/javascript-scene/the-hidden-treasures-of-object-composition-60cd89480381)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-hidden-treasures-of-object-composition.md)
  * PR 地址：#3063
  * 文章分类：**前端**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@yoyoyohamapi 你的了

**Comment by yoyoyohamapi** [comment]
认领翻译

**Comment by leviding** [comment]
@yoyoyohamapi ok

**Comment by IridescentMia** [comment]
想预约这篇的认领校对，求艾特 @yoyoyohamapi
