### ISSUE TITLE
如何打造以人为本的移动游戏

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2893]
* 原文链接：[How to build mobile games with people in mind](https://medium.com/googleplaydev/how-to-build-mobile-games-with-people-in-mind-cdc480967fcc)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-build-mobile-games-with-people-in-mind.md)
  * PR 地址：#3040
  * 文章分类：**Android**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hanliuxin5** [comment]
感觉这篇文章分类到 Android 里会不会有些不合适呢

**Comment by leviding** [comment]
@hanliuxin5 Design？

**Comment by hanliuxin5** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@hanliuxin5 棒极啦 :tada:

**Comment by hanliuxin5** [comment]
@leviding 申请完成时间到延后到1月7日, 错误估计了工作量.

**Comment by leviding** [comment]
@hanliuxin5 好的，辛苦啦
