### ISSUE TITLE
开发者须知：女性用户和手机游戏

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2894]
* 原文链接：[Women and mobile games: learnings for developers](https://medium.com/googleplaydev/women-and-mobile-games-learnings-for-developers-cc4ac63da3f2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/women-and-mobile-games-learnings-for-developers.md)
  * PR 地址：#2990
  * 文章分类：**Android**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分  hanliuxin5 4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by corresponding** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@corresponding 棒极啦 :tada:
