### ISSUE TITLE
开发者也是用户 - 简介

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2895]
* 原文链接：[Developers are users too — Introduction](https://medium.com/google-developers/developers-are-users-too-introduction-fefdb42f05a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/developers-are-users-too-introduction.md)
  * PR 地址：#3094
  * 文章分类：**Android**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by huangbryant210707** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@huangbryant210707 棒极啦 :tada:

**Comment by leviding** [comment]
@huangbryant210707 你好，翻译的怎么样啦，有点超期了呢

**Comment by leviding** [comment]
本文重新释放，等待新译者

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3094
