### ISSUE TITLE
函数式 Java 到函数式 Kotlin 的转换

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2896]
* 原文链接：[From functional Java to functioning Kotlin](https://medium.com/google-developers/from-functional-java-to-functioning-kotlin-a4874a4a7a5)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/from-functional-java-to-functioning-kotlin.md)
  * PR 地址：#
  * 文章分类：**Android**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by huanglizhuo** [comment]
认领翻译 @leviding

**Comment by fanyijihua** [comment]
@huanglizhuo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2899
