### ISSUE TITLE
认领google-design

### ISSUE THREAD

**Issue by CaesarPan** [xitu/gold-miner#29]
我翻译这篇吧～

**Comment by CaesarPan** [comment]
额不过这篇貌似不在ReadMe的列表里＝＝如果这篇不行我就翻译那篇Absolute Beginner's Guide to Swift吧

**Comment by Zhangjd** [comment]
列表里面叫 Making Learning Easy by Design

**Comment by CaesarPan** [comment]
哦哦那我就认领这篇Making Learning Easy by Design吧～

**Comment by Glowin** [comment]
你好，Making Learning Easy by Design 这篇文章已经被掘金的 Co-editor 认领了 #57 ，Absolute Beginner's Guide to Swift 这篇文章也在昨天晚上被认领了，翻译的初稿已经完成了 #18 

你可以看看其他的没有被认领的文章，不好意思了。

**Comment by CaesarPan** [comment]
那《探索Stripe Dashboard设计之道》这篇文章可以吗？

**Comment by Glowin** [comment]
@CaesarPan 这个暂时没有呢，你可以再重新开一个 issue 来认领，谢谢。

**Comment by CaesarPan** [comment]
已开issue，谢谢～
