### ISSUE TITLE
怎样在不使用框架的基础上开发一个 Javascript 组件

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#291]
原文链接：[Developing small JavaScript components WITHOUT frameworks
You too can write vanilla JavaScript!](https://jack.ofspades.com/developing-small-javascript-components-without-frameworks/)
掘金链接：[怎样在不使用框架的基础上开发一个 Javascript 组件](http://gold.xitu.io/entry/571c36de5bbb500064e4fa82)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/developing-small-javascript-components-without-frameworks.md)

翻译时间：5天
校对时间：4天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by L9m** [comment]
Javascript 的我喜欢，认领

**Comment by antonia0912** [comment]
@L9m 下手够快~markdown文件已经添加了

**Comment by hikerpig** [comment]
下手好快/(ㄒoㄒ)/~~，那我就先排队认领校对好了

**Comment by antonia0912** [comment]
@hikerpig 已经翻译完可以校对啦  [校对地址](https://github.com/xitu/gold-miner/pull/311/files?diff=split)

**Comment by geeeeeeeeek** [comment]
@antonia0912 校对

**Comment by wild-flame** [comment]
申请校对~~ ：D

**Comment by antonia0912** [comment]
@wild-flame 好的 [校对地址](https://github.com/xitu/gold-miner/pull/311/files?diff=split)

**Comment by antonia0912** [comment]
@geeeeeeeeek 童童这篇就不给你了哈~羊哥就是这样强买强卖

**Comment by wild-flame** [comment]
校对完啦 :D !

**Comment by antonia0912** [comment]
@L9m 可以分享到掘金啦  分享完告诉我  我给你们加积分

**Comment by L9m** [comment]
@antonia0912 已经发了
