### ISSUE TITLE
基于 Meteor1.3 和 React 创建简单 App

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#292]
原文链接：[Build A Journaling App with Meteor 1.3 (Beta), React, React-Bootstrap, and Mantra](https://medium.com/@kenrogers/build-a-journaling-app-with-meteor-1-3-beta-react-react-bootstrap-and-mantra-7965d9e9fc23#.bjcr4yhbf)
掘金链接：[基于 Meteor1.3 和 React 创建简单 App](http://gold.xitu.io/entry/570062192e958a00591a6aed)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/build-a-journaling-app-with-meteor-1-3-beta-react-react-bootstrap-and-mantra.md)

翻译时间：5天
校对时间：4天
翻译积分：8
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by antonia0912** [comment]
特别鸣谢 @lx7575000 为我们提供优质英文文章

**Comment by yangzj1992** [comment]
翻译认领。

**Comment by antonia0912** [comment]
@yangzj1992 OK 等你 PR

**Comment by yangzj1992** [comment]
[初步翻译完成](https://github.com/xitu/gold-miner/pull/313) ，晚了几天十分抱歉.. @antonia0912

**Comment by antonia0912** [comment]
@yangzj1992 OK 我来联系校对者

**Comment by lx7575000** [comment]
校对认领

**Comment by antonia0912** [comment]
@lx7575000 好哒 [校对地址](https://github.com/xitu/gold-miner/pull/313/files?diff=split)

**Comment by geeeeeeeeek** [comment]
@antonia0912 校对

**Comment by antonia0912** [comment]
@geeeeeeeeek 惊呆了  。。。[校对地址](https://github.com/xitu/gold-miner/pull/313/files?diff=split)
