### ISSUE TITLE
使用 web 应用打包工具 Parcel 实现代码分割

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2923]
* 原文链接：[Code Splitting with Parcel Web App Bundler](https://hackernoon.com/code-splitting-with-parcel-web-app-bundler-fe06cc3a20da)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/code-splitting-with-parcel-web-app-bundler.md)
  * PR 地址：#2988
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kangkai124** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@kangkai124 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2988
