### ISSUE TITLE
Redux-recompose 介绍：优雅的编写 Redux 中的 action 和 reducer

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2924]
* 原文链接：[Introducing redux-recompose: Tools to ease Redux actions and reducers development](https://medium.com/wolox-driving-innovation/932e746b0198)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/introducing-redux-recompose.md)
  * PR 地址：#2987
  * 文章分类：**前端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pot-code** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@pot-code 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#2987

**Comment by fanyijihua** [comment]
PR 地址：#3007
