### ISSUE TITLE
使用 webP 减少图片的大小

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#293]
#原文链接：[Shaving Our Image Size](http://engineering.dollarshaveclub.com/shaving-our-image-size/?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=email&utm_source=iOS_Dev_Weekly_Issue_247)
掘金链接：[使用 webP 减少图片的大小](http://gold.xitu.io/entry/571de7bfc4c97100543d1f44)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/shaving-our-image-size.md)

翻译时间：3天
校对时间：3天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by circlelove** [comment]
咦，翻译时间限制压缩了！ 认

**Comment by antonia0912** [comment]
@circlelove goooooooooooood

**Comment by circlelove** [comment]
@antonia0912  好了

**Comment by antonia0912** [comment]
@circlelove 收到

**Comment by antonia0912** [comment]
@circlelove honey  PR 是不是忘记发了。。。

**Comment by geeeeeeeeek** [comment]
@antonia0912 校对

**Comment by rockzhai** [comment]
认领校对 @antonia0912

**Comment by antonia0912** [comment]
@rockzhai 好的 [校对地址](https://github.com/xitu/gold-miner/pull/310/files?diff=split)

**Comment by ldhlfzysys** [comment]
认领校对 @antonia0912

**Comment by antonia0912** [comment]
@ldhlfzysys 好的 [校对地址](https://github.com/xitu/gold-miner/pull/310/files?diff=split)

**Comment by rockzhai** [comment]
@circlelove 第一遍校对完成(●ˇ∀ˇ●)~有点强迫症的大晚上来校对了，哈哈

**Comment by ldhlfzysys** [comment]
@circlelove  校对完成了~
