### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by xingwanying** [xitu/gold-miner#295]
前端开发学习中，平时需要阅读大量英文文档，借此机会锻炼自己的表达能力～

**Comment by antonia0912** [comment]
@xingwanying 组织欢迎新译者~请加我微信 antonia0912 我来拉你进译者群~

**Comment by zongkelong** [comment]
作为掘金的真爱粉，也想通过自己的努力让掘金越来越好，同时也是一种自我锻炼

**Comment by zongkelong** [comment]
#289 #

**Comment by zongkelong** [comment]
#289

**Comment by antonia0912** [comment]
@zongkelong 加我微信呀亲
