### ISSUE TITLE
网页端字体加载优化

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#298]
原文链接：[Web Font Loading Patterns](https://www.bramstein.com/writing/web-font-loading-patterns.html)
掘金链接：[网页端字体加载优化](http://gold.xitu.io/entry/571d94bc79bc440064c51153)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/web-font-loading-patterns.md)

翻译时间：5天
校对时间：3天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by shenxn** [comment]
认领！

**Comment by JasinYip** [comment]
@antonia0912 写错标题啦，应该是「网页端字体加载优化」

**Comment by antonia0912** [comment]
@shenxn 收到小朋友 ， @JasinYip 改过来啦已经（最近不知道脑袋里在想些什么。。。）
