### ISSUE TITLE
[问题] 关于版权

### ISSUE THREAD

**Issue by FingerLiu** [xitu/gold-miner#2985]
这些文章翻译前，是否获得了文章原作者的翻译许可？

**Comment by leviding** [comment]
@FingerLiu 翻译前会尽量去联系原文作者，有很多作者会回复授权。但是有时候可能原作者比较忙，消息多，并未回复。总之会遵循 https://creativecommons.org/licenses/by-nc-sa/4.0/ ，不做商业用途，不盈利。

请问您还有什么疑问吗？

**Comment by leviding** [comment]
@FingerLiu 如果原作者未声明使用的协议，且未得到作者的授权回复时使用，确有不妥，感谢提醒。
