### ISSUE TITLE
Redux 的工作原理

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#2986]
* 原文链接：[How Redux Works: A Counter-Example](https://daveceddia.com/how-does-redux-work/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-does-redux-work.md)
  * PR 地址：#2999
  * 文章分类：**前端**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hexianga** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@hexianga 棒极啦 :tada:
