### ISSUE TITLE
 这篇归我了  http://gold.xitu.io/entry/5665ac0f60b202595a710eb6

### ISSUE THREAD

**Issue by boolstudio** [xitu/gold-miner#3]

**Comment by Glowin** [comment]
[如何更高效的使用 okhttp](http://gold.xitu.io/entry/5665ac0f60b202595a710eb6) okhttp 很多人在用啦，希望你翻译的这篇文章能帮助到大家。

另外，预估翻译时间是多久呢？

**Comment by boolstudio** [comment]
周末可以搞定！说不定今天晚上就好了 哈哈
- Sent from Smartisan T1 -
Glow Chiang <notifications@github.com>
于 2015年12月25日，20:26写道：如何更高效的使用 okhttp okhttp 很多人在用啦，希望你翻译的这篇文章能帮助到大家。

另外，预估翻译时间是多久呢？

**Comment by Glowin** [comment]
赞，但是多多查看一下质量哟。

**Comment by boolstudio** [comment]
好的 
- Sent from Smartisan T1 -
Glow Chiang <notifications@github.com>
于 2015年12月25日，20:31写道：赞，但是多多查看一下质量哟。
