### ISSUE TITLE
使用ES6写更好的JavaScript part I：广受欢迎新特性

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#300]
原文链接：[Better Node with ES6, Pt. I](https://scotch.io/tutorials/better-node-with-es6-pt-i)
掘金链接：[使用ES6写更好的JavaScript part I：广受欢迎新特性](http://gold.xitu.io/entry/571df8982e958a006b0df81a)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/better-node-with-es6-pt-i.md)

翻译时间：5天
校对时间：3天
翻译积分：8
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by huanglizhuo** [comment]
认领 
看了下这有3篇是一个系列，得是需要认领3篇喽

**Comment by antonia0912** [comment]
@huanglizhuo 哈哈哈  你要翻译多久   觉得压力大的话  先翻译一篇也行  我看了看感觉挺多的

**Comment by huanglizhuo** [comment]
@antonia0912  一点点来吧 啊哈哈

**Comment by antonia0912** [comment]
@huanglizhuo 好的  那就先翻译这一篇，三篇都给你我好担心你翻译完就再也不跟我们玩了  直接退出译者群了哈哈哈

**Comment by Jack-Kingdom** [comment]
校对+1 @antonia0912

**Comment by antonia0912** [comment]
@Jack-Kingdom 不可以一次性认领这么多喔~给其他新人一个机会嘛 这个校对就不给你啦  乖~

**Comment by yllziv** [comment]
校对  +1

**Comment by yllziv** [comment]
校对 +1  @antonia0912

**Comment by antonia0912** [comment]
@yllziv 好哒 [校对地址](https://github.com/xitu/gold-miner/pull/308/files?diff=split)

**Comment by yllziv** [comment]
有翻译规范可以不？ @antonia0912

**Comment by antonia0912** [comment]
@yllziv 什么意思？readme里有介绍 你可以看看  或者不懂的在译者群里问大家就可以了

**Comment by yllziv** [comment]
噢，没事了，我看之前一篇PR的文章，有人回复校对前先follow一下翻译规范，我没找到。 @antonia0912

**Comment by antonia0912** [comment]
@yllziv 翻译规范就是readme里边的 [点这里查看](https://github.com/xitu/gold-miner/blob/master/README.md)

**Comment by yllziv** [comment]
ok，校对完成  @antonia0912 ， @huanglizhuo 翻译的不错，修改了一些小地方。
