### ISSUE TITLE
PWA 实战：Tinder 的性能优化之道

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3000]
* 原文链接：[A Tinder Progressive Web App Performance Case Study](https://medium.com/@addyosmani/a-tinder-progressive-web-app-performance-case-study-78919d98ece0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-tinder-progressive-web-app-performance-case-study.md)
  * PR 地址：#3037
  * 文章分类：**前端**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pot-code** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pot-code 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3037
