### ISSUE TITLE
When and how to use Value and Reference Types in Swift

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3001]
* 原文链接：[When and how to use Value and Reference Types in Swift](https://khawerkhaliq.com/blog/swift-value-types-reference-types/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/swift-value-types-reference-types.md)
  * PR 地址：#3060
  * 文章分类：**iOS**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeepMissea** [comment]
翻译认领，自己推荐的自己翻译吧，不然多半是凉了。。

**Comment by fanyijihua** [comment]
@DeepMissea 棒极啦 :tada:

**Comment by VernonVan** [comment]
校对认领 @leviding

**Comment by leviding** [comment]
@VernonVan 在对应 pull request 下进行校对人领。现在译者还没翻译完， @DeepMissea 翻译好了可以艾特下这位大兄弟

**Comment by fanyijihua** [comment]
PR 地址：#3058

**Comment by fanyijihua** [comment]
PR 地址：#3060
