### ISSUE TITLE
2018 年要学习的优秀 JavaScript 库与知识

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3002]
* 原文链接：[Top JavaScript Libraries & Tech to Learn in 2018](https://medium.com/javascript-scene/top-javascript-libraries-tech-to-learn-in-2018-c38028e028e6)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/top-javascript-libraries-tech-to-learn-in-2018.md)
  * PR 地址：#3006
  * 文章分类：**前端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gy134340** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@gy134340 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3006
