### ISSUE TITLE
前端 2017: 举要删芜

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3003]
* 原文链接：[Frontend in 2017: The important parts](https://blog.logrocket.com/frontend-in-2017-the-important-parts-4548d085977f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/frontend-in-2017-the-important-parts.md)
  * PR 地址：#3005
  * 文章分类：**前端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gy134340** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@gy134340 棒极啦 :tada:

**Comment by leviding** [comment]
@gy134340 你同时认领的两个文章都不短，要是认领，需要按时完成哈

**Comment by gy134340** [comment]
![14243932](https://user-images.githubusercontent.com/14243932/34458530-a1d8d356-ee10-11e7-8ee5-42e43c5b5b48.png)

**Comment by fanyijihua** [comment]
PR 地址：#3005
