### ISSUE TITLE
使用ES6写更好的JavaScript part II：A Deep Dive into Classes

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#301]
原文链接：[Better JavaScript with ES6, Pt. II: A Deep Dive into Classes](https://scotch.io/tutorials/better-javascript-with-es6-pt-ii-a-deep-dive-into-classes)
掘金链接：[使用ES6写更好的JavaScript part II：A Deep Dive into Classes](http://gold.xitu.io/entry/57162377128fe1005409c0dc)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/better-javascript-with-es6-pt-ii-a-deep-dive-into-classes.md)

翻译时间：5天
校对时间：3天
翻译积分：9
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by malcolmyu** [comment]
专业对口，抢一个翻译

**Comment by antonia0912** [comment]
@malcolmyu 收到~等你 PR

**Comment by malcolmyu** [comment]
翻译完成，好长啊快翻吐了……[#312](https://github.com/xitu/gold-miner/pull/312)

**Comment by antonia0912** [comment]
@malcolmyu ok  我来联系校对者  辛苦啦

**Comment by xingwanying** [comment]
我来校对胖西糊的～₍₍⁽⁽(ી( ･◡･ )ʃ)₎₎⁾⁾嚯哈 @antonia0912 🐑爷～

**Comment by antonia0912** [comment]
@xingwanying 好哒 [校对地址](https://github.com/xitu/gold-miner/pull/312/files?diff=split)

**Comment by wild-flame** [comment]
这篇是不是也已经被人领啦？

**Comment by antonia0912** [comment]
@wild-flame 新译者不可以一下认领多篇喔  先去把那篇我给了校对地址的校对完成吧 乖~

**Comment by Jack-Kingdom** [comment]
校对+1 @antonia0912

**Comment by antonia0912** [comment]
@Jack-Kingdom 好哒 [校对地址](https://github.com/xitu/gold-miner/pull/312/files?diff=split)

**Comment by Jack-Kingdom** [comment]
校对完毕。 @antonia0912

**Comment by Jack-Kingdom** [comment]
文章有点长，译者的翻译很细致，不得不点个赞。

**Comment by malcolmyu** [comment]
感谢两位校对者 @Jack-Kingdom @xingwanying 羊三我改完了你啥时候 merge 啊……
