### ISSUE TITLE
使用ES6写更好的JavaScript part III : 好用的集合和反引号

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#302]
原文链接：[Better JavaScript with ES6, Pt. III: Cool Collections & Slicker Strings](https://scotch.io/tutorials/better-javascript-with-es6-pt-iii-cool-collections-slicker-strings)
掘金链接：[使用ES6写更好的JavaScript part III : 好用的集合和反引号](http://gold.xitu.io/entry/571df7ab2e958a00550fc8d7)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/better-javascript-with-es6-pt-iii-cool-collections-slicker-strings.md)

翻译时间：5天
校对时间：3天
翻译积分：8
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by godofchina** [comment]
@antonia0912  申请翻译，终于抢到一回 哈哈

**Comment by antonia0912** [comment]
@godofchina 好的  等你 PR

**Comment by godofchina** [comment]
@antonia0912  羊哥  我已经提交了 找不到校对地址啊 求助

**Comment by antonia0912** [comment]
@godofchina 看上边的conversation  你申请的是翻译不是校对呀  PR是翻译完之后译者 也就是你发的

**Comment by godofchina** [comment]
现在是这样的 我已经翻译完 提交了 想找到校对地址 贴出来方便 后面的人校对 结果没找到 我在想是不是我哪里操作错了

**Comment by godofchina** [comment]
@antonia0912 现在是这样的 我已经翻译完 提交了 想找到校对地址 贴出来方便 后面的人校对 结果没找到 我在想是不是我哪里操作错了

**Comment by godofchina** [comment]
@羊哥 pr 已发

**Comment by godofchina** [comment]
@antonia0912  羊哥 pr已发

**Comment by antonia0912** [comment]
@godofchina coooooool~~

**Comment by godofchina** [comment]
@antonia0912  翻的比较烂 求校对的哥们 别打我

**Comment by godofchina** [comment]
这个 是[校对地址](https://github.com/godofchina/gold-miner/commit/0eaa8fc42073154805a870add3db45afd30112a6)

**Comment by Jack-Kingdom** [comment]
校对+1， @antonia0912

**Comment by godofchina** [comment]
@Jack-Kingdom 哥们辛苦啊,我第一次翻，有什么不对的地方告我一声

**Comment by antonia0912** [comment]
@Jack-Kingdom 收到 [校对地址](https://github.com/xitu/gold-miner/pull/318/files?diff=split)

**Comment by malcolmyu** [comment]
@antonia0912 校对认领~

**Comment by antonia0912** [comment]
@malcolmyu 辛苦啦思密达~
