### ISSUE TITLE
Android文档抓虫校对

### ISSUE THREAD

**Issue by SumiMakito** [xitu/gold-miner#3026]
- 哪一项：Clean Project
- 问题描述：「Clean Project」是 Android Studio 中的菜单选项
<img width="463" alt="2018-01-04 11 52 10" src="https://user-images.githubusercontent.com/5277268/34549705-bae0f198-f145-11e7-89fc-c57c6125b3b6.png">

- 怎样是正确的：个人认为不应作为术语收录

**Comment by leviding** [comment]
嗯嗯，这个还是放着吧，还有其他例如 Make Project
