### ISSUE TITLE
Android O 中安全加固

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3027]
* 原文链接：[Double Stuffed Security in Android Oreo](https://android-developers.googleblog.com/2017/12/double-stuffed-security-in-android-oreo.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/double-stuffed-security-in-android-oreo.md)
  * PR 地址：#3029
  * 文章分类：**Android**
  * **本文为 Google 约稿，需要较有经验的 Android 译者认领，质量好则可能发布于 Google 官方公众号**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：6 分 +3
  * 校对积分：2 分 +2
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XPGSnail** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@XPGSnail 棒极啦 :tada:
