### ISSUE TITLE
利用双环 TDD 进行由外向内的开发

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3032]
* 原文链接：[Outside-In development with Double Loop TDD](http://coding-is-like-cooking.info/2013/04/outside-in-development-with-double-loop-tdd/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/#)
  * PR 地址：#3042
  * 文章分类：**后端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by NeilLi1992** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@NeilLi1992 棒极啦 :tada:

**Comment by NeilLi1992** [comment]
@leviding 想问一下里面的图片需要弄吗？图片里面也有些文字

**Comment by leviding** [comment]
@NeilLi1992 图片里的文字，有兴趣就弄，不想弄就不弄。

对了，这篇文章属于什么分类？我改下。

**Comment by NeilLi1992** [comment]
@leviding 应该是 测试 吧

**Comment by fanyijihua** [comment]
PR 地址：#3042
