### ISSUE TITLE
Node.js 最佳实践 —— 如何在 2018 年成为更好的 Node.js 开发者

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3034]
* 原文链接：[Node.js Best Practices - How to become a better Node.js developer in 2018](https://nemethgergely.com/nodejs-best-practices-how-to-become-a-better-developer-in-2018/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/nodejs-best-practices-how-to-become-a-better-developer-in-2018.md)
  * PR 地址：#3039
  * 文章分类：**后端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by NeilLi1992** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@NeilLi1992 棒极啦 :tada:

**Comment by NeilLi1992** [comment]
@leviding 同时接两个可以吗…… 正好周末了……

**Comment by leviding** [comment]
@NeilLi1992 哈哈，可以

**Comment by fanyijihua** [comment]
PR 地址：#3039
