### ISSUE TITLE
状态管理的未来: 在 Apollo Client 中使用 apollo-link-state管理本地数据

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3035]
* 原文链接：[The future of state management](https://dev-blog.apollodata.com/the-future-of-state-management-dd410864cae2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-future-of-state-management.md)
  * PR 地址：#3075
  * 文章分类：**后端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yct21** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@yct21 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3075
