### ISSUE TITLE
关于 Parcel 你所需要知道的一切：快速的 Web 应用打包器 🚀

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3036]
* 原文链接：[Everything You Need To Know About Parcel: The Blazing Fast Web App Bundler 🚀](https://medium.freecodecamp.org/all-you-need-to-know-about-parcel-dbe151b70082)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/all-you-need-to-know-about-parce.md)
  * PR 地址：#3041
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by FateZeros** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@FateZeros 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3041
