### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by Quorafind** [xitu/gold-miner#3038]
- 原文链接：https://googleprojectzero.blogspot.hk/2018/01/reading-privileged-memory-with-side.html
- 简要介绍：近日引起轰动的一篇阐述了intel架构乃至所有CPU架构的漏洞的文章。该漏洞如果被利用，能直接读取内核内存，那么密码之类的安全不复存在。以上为核心思想。内容则为技术层面解释这次的漏洞的产生原因。
- 额外内容：此外还有关于这两个漏洞的专门解释的论文，如若也属于推荐范围。此为汇总连接：https://meltdownattack.com/

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
这篇文章很长，可能翻译出来已经失去时效性了，你有意向翻译吗，有的话我再编辑放上去。
