### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by LynnShaw** [xitu/gold-miner#3045]
- 原文链接：[How to Configure NGINX for a Flask Web Application](http://www.patricksoftwareblog.com/how-to-configure-nginx-for-a-flask-web-application/)
- 简要介绍：如何给一个Flask Web应用配置NGINX

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@LynnShaw 收到，感谢推荐，今天放上去
