### ISSUE TITLE
现代浏览器是如何提升性能的：网络层

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3048]
* 原文链接：[How Modern Web Browsers Accelerate Performance: The Networking Layer](https://blog.sessionstack.com/how-modern-web-browsers-accelerate-performance-the-networking-layer-f6efaf7bfcf4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-modern-web-browsers-accelerate-performance-the-networking-layer.md)
  * PR 地址：#3178
  * 文章分类：**前端**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@yoyoyohamapi 你的了

**Comment by yoyoyohamapi** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@yoyoyohamapi 棒极啦 :tada:

**Comment by leviding** [comment]
@yoyoyohamapi 翻译的怎么样啦

**Comment by yoyoyohamapi** [comment]
@leviding 这周弄好

**Comment by yoyoyohamapi** [comment]
@leviding 周末提交pr

**Comment by fanyijihua** [comment]
PR 地址：#3178
