### ISSUE TITLE
为 Flask Web 应用配置 Nginx

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3049]
* 原文链接：[How to Configure NGINX for a Flask Web Application](http://www.patricksoftwareblog.com/how-to-configure-nginx-for-a-flask-web-application/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-configure-nginx-for-a-flask-web-application.md)
  * PR 地址：#3224
  * 文章分类：**后端**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by lsvih** [comment]
@leviding 这一篇明天下午交

**Comment by lsvih** [comment]
@leviding 忘了。。现在搞！

**Comment by fanyijihua** [comment]
PR 地址：#3224
