### ISSUE TITLE
构建更具可用性的 UI 与 API 的 5 个方针

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3050]
* 原文链接：[Developers are users too — part 1: 5 Guidelines for a better UI and API usability](https://medium.com/google-developers/developers-are-users-too-part-1-c753483a50dc)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/developers-are-users-too-part-1.md)
  * PR 地址：#3105
  * 文章分类：**Android**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by leviding** [comment]
@lsvih 这篇怎么样啦

**Comment by lsvih** [comment]
@leviding 还差一节，下午提交

**Comment by fanyijihua** [comment]
PR 地址：#3105
