### ISSUE TITLE
开发者也是用户 - 第二部分：改善 UI 和 API 可用性的五条指导原则

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3051]
* 原文链接：[Developers are users too — part 2: 5 More guidelines for a better UI and API usability](https://medium.com/google-developers/developers-are-users-too-part-2-96e03fe17535)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/developers-are-users-too-part-2.md)
  * PR 地址：#3109
  * 文章分类：**Android**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
这个我来吧。

**Comment by leviding** [comment]
@tanglie1993 ok，下次用关键词认领哈

**Comment by leviding** [comment]
@tanglie1993 翻译的怎么样啦

**Comment by tanglie1993** [comment]
啊？4天这么快过去了？不好意思前几天一直忙。
我争取今晚搞定吧。

**Comment by lsvih** [comment]
@tanglie1993 老哥可以参考一下 https://github.com/xitu/gold-miner/blob/master/TODO/developers-are-users-too-introduction.md 哈
