### ISSUE TITLE
Android 生命周期备忘录 — 第一部分: 单一 Activities

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3052]
* 原文链接：[The Android Lifecycle cheat sheet — part I: Single Activities](https://medium.com/google-developers/the-android-lifecycle-cheat-sheet-part-i-single-activities-e49fd3d202ab)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-android-lifecycle-cheat-sheet-part-i-single-activities.md)
  * PR 地址：#3064
  * 文章分类：**Android**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by IllllllIIl** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@IllllllIIl 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3064
