### ISSUE TITLE
优秀英文文章推荐

### ISSUE THREAD

**Issue by LeopPro** [xitu/gold-miner#3056]
原文链接：
http://joelmccracken.github.io/entries/a-simple-web-app-in-rust-pt-1/
http://joelmccracken.github.io/entries/a-simple-web-app-in-rust-pt-2a/
http://joelmccracken.github.io/entries/a-simple-web-app-in-rust-pt-2b/
http://joelmccracken.github.io/entries/a-simple-web-app-in-rust-pt-3/
http://joelmccracken.github.io/entries/a-simple-web-app-in-rust-pt-4-cli-option-parsing/
http://joelmccracken.github.io/entries/a-simple-web-app-in-rust-conclusion/
简要介绍：使用 Rust 编写一个简单的 Web 应用，上面六个链接是一篇文章的六个部分。

 @leviding （PS：老大，我想翻译这个）

**Comment by LeopPro** [comment]
标签应该是后端，我觉得咱们后端的内容比较少

**Comment by leviding** [comment]
@LeopPro 哈哈哈，辛苦啦，你是六篇都想自己翻译吗

**Comment by leviding** [comment]
推荐多篇文章奖励 3 分

**Comment by leviding** [comment]
@LeopPro 你推荐的所有文章已经发布啦，想认领几个就认领几个吧
