### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by wild-flame** [xitu/gold-miner#306]
新加坡CS留学，现在 Gap Year 中，英语很好，口语和书面都没问题，平时技术书籍和文档都可以看英文，偶尔读读英文小说。本科时兼职做过一年半的 Rails 开发，后来兴趣转到 Node.js，另对交互设计感兴趣。

**Comment by antonia0912** [comment]
@wild-flame Bienvenu~ 请加我微信 antonia0912 备注 github ID 我来拉你进译者群
