### ISSUE TITLE
使用 Rust 开发一个简单的 Web 应用，第 1 部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3065]
* 原文链接：[A Simple Web App in Rust, Part 1](http://joelmccracken.github.io/entries/a-simple-web-app-in-rust-pt-1/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-simple-web-app-in-rust-pt-1.md)
  * PR 地址：#3088
  * 文章分类：**后端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LeopPro** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@LeopPro 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3088

**Comment by fanyijihua** [comment]
PR 地址：#3113
