### ISSUE TITLE
使用 Rust 开发一个简单的 Web 应用，第 2a 部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3066]
* 原文链接：[A Simple Web App in Rust, Part 2a](http://joelmccracken.github.io/entries/a-simple-web-app-in-rust-pt-2a/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-simple-web-app-in-rust-pt-2a.md)
  * PR 地址：#3114
  * 文章分类：**后端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LeopPro** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@LeopPro 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3114
