### ISSUE TITLE
使用 Rust 开发一个简单的 Web 应用，第 4 部分 —— CLI 选项解析

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3069]
* 原文链接：[A Simple Web App in Rust, Part 4 -- CLI Option Parsing](http://joelmccracken.github.io/entries/a-simple-web-app-in-rust-pt-4-cli-option-parsing/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-simple-web-app-in-rust-pt-4-cli-option-parsing.md)
  * PR 地址：#3247
  * 文章分类：**后端**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LeopPro** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@LeopPro 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3247
