### ISSUE TITLE
使用 Rust 开发一个简单的 Web 应用之总结篇：还是先把 Rust 放一边吧

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3070]
* 原文链接：[A Simple Web App in Rust, Conclusion: Putting Rust Aside for Now](http://joelmccracken.github.io/entries/a-simple-web-app-in-rust-conclusion/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-simple-web-app-in-rust-conclusion.md)
  * PR 地址：#3156
  * 文章分类：**后端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mysterytony** [comment]
@leviding 认领翻译

**Comment by fanyijihua** [comment]
@mysterytony 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3156

**Comment by pthtc** [comment]
校对认领
