### ISSUE TITLE
2018 前端性能优化清单——第一部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3071]
* 原文链接：[Front-End Performance Checklist 2018 - Part 1](https://www.smashingmagazine.com/2018/01/front-end-performance-checklist-2018-pdf-pages/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/front-end-performance-checklist-2018-1.md)
  * PR 地址：#3143
  * 文章分类：**前端**
  ----
  * 翻译时间：8 天
  * 校对时间：3 天
  * 翻译积分：8 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tvChan** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@tvChan 棒极啦 :tada:

**Comment by leviding** [comment]
@tvChan 翻译的怎么样啦

**Comment by tvChan** [comment]
有点忙，周末搞定哈

**Comment by leviding** [comment]
好，辛苦啦

**Comment by fanyijihua** [comment]
PR 地址：#3143
