### ISSUE TITLE
2018 设计趋势

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3076]
* 原文链接：[2018 Design Trends](https://www.behance.net/gallery/59540015/2018-Design-Trends)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/2018-design-trends.md)
  * PR 地址：#3136
  * 文章分类：**设计**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pot-code** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pot-code 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3136
