### ISSUE TITLE
新兴技术领域中以用户为中心的设计的应用

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3077]
* 原文链接：[Applying human-centered design to emerging technologies](https://medium.com/googleplaydev/applying-human-centered-design-to-emerging-technologies-6ad7f39d8d30)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/applying-human-centered-design-to-emerging-technologies.md)
  * PR 地址：#3149
  * 文章分类：**设计**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by dongpeiguo** [comment]
申请翻译

**Comment by fanyijihua** [comment]
@dongpeiguo 棒极啦 :tada:

**Comment by leviding** [comment]
@dongpeiguo 怎么样啦
