### ISSUE TITLE
游戏即服务的五条建议，提升游戏变现能力

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3078]
* 原文链接：[Five tips to improve your games-as-a-service monetization](https://medium.com/googleplaydev/five-tips-to-improve-your-games-as-a-service-monetization-1a99cccdf21)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/five-tips-to-improve-your-games-as-a-service-monetization.md)
  * PR 地址：#3198
  * 文章分类：**产品**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 + 1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pthtc** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pthtc 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3198
