### ISSUE TITLE
一文教你预测 APP 未来的货币化情况

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3079]
* 原文链接：[Predicting your app’s monetization future](https://medium.com/googleplaydev/predicting-your-apps-monetization-future-27180e82ae34)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/predicting-your-apps-monetization-future.md)
  * PR 地址：#3189
  * 文章分类：**产品**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pthtc** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pthtc 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3189
