### ISSUE TITLE
想帮助用户做决定？你的 APP 可以这样设计！

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3080]
* 原文链接：[Design your app for decision-making](https://medium.com/googleplaydev/design-your-app-for-decision-making-e9e5745508e4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/design-your-app-for-decision-making.md)
  * PR 地址：#3179
  * 文章分类：**设计**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pthtc** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pthtc 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3179
