### ISSUE TITLE
如果你想让用户回来，为什么前十分钟是至关重要的？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3081]
* 原文链接：[Why the first ten minutes are crucial if you want to keep players coming back](https://medium.com/googleplaydev/why-the-first-ten-minutes-is-crucial-if-you-want-to-keep-players-coming-back-to-your-mobile-game-4a89031b6308)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-the-first-ten-minutes-is-crucial-if-you-want-to-keep-players-coming-back-to-your-mobile-game.md)
  * PR 地址：#3215
  * 文章分类：**产品**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by dongpeiguo** [comment]
申请翻译

**Comment by fanyijihua** [comment]
@dongpeiguo 棒极啦 :tada:

**Comment by sunshine940326** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sunshine940326 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3215
