### ISSUE TITLE
是谁在玩手机游戏？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3082]
* 原文链接：[Who plays mobile games: Player insights to help developers win](https://medium.com/googleplaydev/who-plays-mobile-games-8b33f76bb6d8)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/who-plays-mobile-games.md)
  * PR 地址：#3211
  * 文章分类：**产品**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by laiyun90** [comment]
翻译认领~ @leviding

**Comment by fanyijihua** [comment]
@laiyun90 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3211
