### ISSUE TITLE
使用深度学习自动生成HTML代码 - 第 1 部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3089]
* 原文链接：[Turning Design Mockups Into Code With Deep Learning - Part 1](https://blog.floydhub.com/turning-design-mockups-into-code-with-deep-learning/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/turning-design-mockups-into-code-with-deep-learning-1.md)
  * PR 地址：#3184
  * 文章分类：**机器学习**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sakila1012** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@sakila1012 棒极啦 :tada:

**Comment by leviding** [comment]
@sakila1012 这篇怎么样啦

**Comment by sakila1012** [comment]
@leviding 翻译完成

**Comment by leviding** [comment]
@sakila1012 对应的 pull request 在哪呢

**Comment by sakila1012** [comment]
@leviding 已经pull request了
