### ISSUE TITLE
使用 BEM 来模块化你的 CSS 代码

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#309]
原文链接：[How we use BEM to modularise our CSS](https://m.alphasights.com/how-we-use-bem-to-modularise-our-css-82a0c39463b0#.qjqyfixfr)
掘金链接：[使用 BEM 来模块化你的 CSS 代码](http://gold.xitu.io/entry/5720a01d71cfe4006b32a172)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/how-we-use-bem-to-modularise-our-css.md)

翻译时间：5天
校对时间：3天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by JasinYip** [comment]
文章认领！

**Comment by antonia0912** [comment]
@JasinYip 大鸡腿  well done~

**Comment by JasinYip** [comment]
@antonia0912 抱歉羊羊，最近任务太多无暇翻译了……申请换人……不好意思

**Comment by antonia0912** [comment]
@JasinYip 收到 先忙~

**Comment by yllziv** [comment]
羊哥，文章认领！ @antonia0912

**Comment by antonia0912** [comment]
@yllziv 收到~

**Comment by yllziv** [comment]
羊哥，翻译完成，已PR。 @antonia0912

**Comment by antonia0912** [comment]
@yllziv 收到~校对者也已经找好啦~
