### ISSUE TITLE
Turning Design Mockups Into Code With Deep Learning - Part 2

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3090]
* 原文链接：[Turning Design Mockups Into Code With Deep Learning - Part 2](https://blog.floydhub.com/turning-design-mockups-into-code-with-deep-learning/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/turning-design-mockups-into-code-with-deep-learning-2.md)
  * PR 地址：#
  * 文章分类：**机器学习**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by bambooom** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@bambooom 棒极啦 :tada:

**Comment by bambooom** [comment]
- 已有翻译好的 -> https://mp.weixin.qq.com/s/4b4TPkIRPJ3VBkCOA6kbxw
- 我个人并不太看得懂

综上，我想放弃，如果有人不介意已有翻译，愿意继续翻译的，求接手。。。
@leviding

**Comment by leviding** [comment]
ok

**Comment by leviding** [comment]
ok
