### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by douMax** [xitu/gold-miner#3098]
- 公司/学校：自由职业（目前在一家相机租赁公司开发预订系统）
- 工作内容/专业：Full Stack Web Developer
- 常浏览的国外网站：Hacker Noon 等 Medium 研发类相关博客，The Verge 等科技媒体
- 英语水平：雅思总分8分，在澳大利亚学习生活4年，在英语环境工作超过1年
- 有无翻译经验：曾经做过一段时间体育类稿件翻译，纪录片字幕翻译经验
- 个人博客：无
- 个人介绍：曾经在国内媒体公司工作，来澳大利亚学习传媒，后来学习了一个三个月全职的 Web Development Bootcamp 课程，开启程序员生涯。目前属于 Freelancer，在一家小公司做 Contractor，开发定制的订单系统。喜欢科幻，科技，足球主队利物浦，支持性别平等
很高兴认识大家 ；）

**Comment by leviding** [comment]
Hi @douMax ，感谢你申请加入掘金翻译计划，你需要做以下的事：

**1.** 加管理员微信 517010193 或者扫描 [二维码](http://oiiyyn1t0.bkt.clouddn.com/wechat-517010193.jpg) ，**验证信息格式**：姓名 + GitHub 用户名；

**2.** 认真学习 [掘金翻译计划译者教程](https://github.com/xitu/gold-miner/wiki)，校对和翻译文章时，严格遵循教程，杜绝不看教程，只知道问的伸手党；

**3.** 复习 [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)，翻译文章时严格遵循，校对文章时也要指出译者的格式错误；

**4.** 复习 [翻译和校对文章的注意事项](https://github.com/xitu/gold-miner/wiki/%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88)，避免翻译校对过程中出错。

**注意**：管理员每天集中处理一次，稍安勿躁。加完微信后，管理员会在当天拉你进译者群，进群之后做下简单的自我介绍。加入微信群则代表申请译者成功，接下来你需要看译者教程，然后先校对至少一篇文章才能开始正式翻译文章。当然也可以继续校对文章。
