### ISSUE TITLE
认领creating-your-first-desktop.md

### ISSUE THREAD

**Issue by xdujiang** [xitu/gold-miner#31]

**Comment by qiuyuntao** [comment]
认领

**Comment by Glowin** [comment]
@xdujiang @qiuyuntao 二位好，[这篇文章](https://github.com/xitu/gold-miner/blob/master/TODO/creating-your-first-desktop.md) 已经被@Zhangdroid 认领#2，你可以看看其他未被认领的文章，谢谢理解哈。
