### ISSUE TITLE
请求翻译“Android RxJava 2” 第6、7、8三个部分

### ISSUE THREAD

**Issue by zhouzl18** [xitu/gold-miner#3101]
part1——part5已经翻译，翻译地址如下：
[Part1](https://juejin.im/entry/58ada9738fd9c5006704f5a1?utm_source=gold-miner&utm_medium=readme&utm_campaign=github)、[Part2](https://juejin.im/entry/58d78547a22b9d006465ca57/?utm_source=gold-miner&utm_medium=readme&utm_campaign=github)、[Part3](https://juejin.im/entry/591298eea0bb9f0058b35c7f/?utm_source=gold-miner&utm_medium=readme&utm_campaign=github)、[Part4](https://github.com/xitu/gold-miner/blob/master/TODO/war-learning-curve-rx-java-2-java-8-stream-android-rxjava2-hell-part4.md)、[Part5](https://juejin.im/post/590ab4f7128fe10058f35119/?utm_source=gold-miner&utm_medium=readme&utm_campaign=github)
剩余部分part6——part8，原文地址如下：
[Part6](http://www.uwanttolearn.com/android/continuation-summer-vs-winter-observable-dialogue-rx-observable-developer-android-rxjava2-hell-part6/)
[Part7](http://www.uwanttolearn.com/android/continuation-observable-marriage-proposal-observer-dialogue-rx-observable-developer-android-rxjava2-hell-part7/)
[Part8](http://www.uwanttolearn.com/android/confusion-subject-observable-observer-android-rxjava2-hell-part8/)
如果已经翻译了，麻烦分享下链接，非常感谢！

**Comment by leviding** [comment]
还没有翻译呢，感谢推荐，会安排翻译的。
