### ISSUE TITLE
8 个技巧让你在 2018 年构建更好的 Node.js 应用程序

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3103]
* 原文链接：[8 Tips to Build Better Node.js Apps in 2018](https://blog.risingstack.com/node-js-development-tips-2018/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/node-js-development-tips-2018.md)
  * PR 地址：#3107
  * 文章分类：**后端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PLDaily** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@PLDaily 棒极啦 :tada:
