### ISSUE TITLE
What’s New in HTML 5.2?

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3104]
* 原文链接：[What’s New in HTML 5.2?](https://bitsofco.de/whats-new-in-html-5-2/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/whats-new-in-html-5-2.md)
  * PR 地址：#3106
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3106
