### ISSUE TITLE
Vue Devtools 4.0 有哪些新内容

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3115]
* 原文链接：[What’s new in Vue Devtools 4.0](https://medium.com/the-vue-point/whats-new-in-vue-devtools-4-0-9361e75e05d0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/whats-new-in-vue-devtools-4-0.md)
  * PR 地址：#3145
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MechanicianW** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MechanicianW 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3145
