### ISSUE TITLE
构造函数已死，构造函数万岁！

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3116]
* 原文链接：[The constructor is dead, long live the constructor!](https://hackernoon.com/the-constructor-is-dead-long-live-the-constructor-c10871bea599)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-constructor-is-dead-long-live-the-constructor.md)
  * PR 地址：#3127
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by unicar9** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@unicar9 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3127
