### ISSUE TITLE
玩转 Android paths

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3117]
* 原文链接：[Playing with Paths](https://medium.com/google-developers/playing-with-paths-3fbc679a6f77)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/playing-with-paths.md)
  * PR 地址：#3244
  * 文章分类：**Android**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by IllllllIIl** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@IllllllIIl 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3244
