### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by CNBlackJ** [xitu/gold-miner#3120]
- 原文链接：[An Undervalued Blockchain Market In China Is Good News For You](https://medium.com/theblock1/an-undervalued-blockchain-market-in-china-is-good-news-for-you-d0c010170622)
- 简要介绍：关于区块链在中国的情况

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@感谢推荐，本周放上去
