### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by wizardforcel** [xitu/gold-miner#3128]
pythonprogramming.net 上有很多不错的文章，用 Python 实现人工智能

机器人

+   [树莓派](https://pythonprogramming.net/introduction-raspberry-pi-tutorials/)
+   [自走小车](https://pythonprogramming.net/robotics-raspberry-pi-tutorial-gopigo-introduction/)
+   [四轴飞行器](https://pythonprogramming.net/building-quadcopter-tutorial-intro/)

图像

+   [OpenCV](https://pythonprogramming.net/loading-images-python-opencv-tutorial/)
+   [TensorFlow 目标检测](https://pythonprogramming.net/introduction-use-tensorflow-object-detection-api-tutorial/)
+   [Python GTA5 自动驾驶](https://pythonprogramming.net/game-frames-open-cv-python-plays-gta-v/)

金融

+   [Pandas](https://pythonprogramming.net/data-analysis-python-pandas-tutorial-introduction/)
+   [Python 金融](https://pythonprogramming.net/getting-stock-prices-python-programming-for-finance/)

NLP

+   [NLTK](https://pythonprogramming.net/tokenizing-words-sentences-nltk-tutorial/)
+   [TensorFlow 聊天机器人](https://pythonprogramming.net/chatbot-deep-learning-python-tensorflow/)

> p.s. 我已经翻译了机器学习和可视化部分：[wizardforcel/py-ds-intro-tut-zh](https://github.com/wizardforcel/py-ds-intro-tut-zh)

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@wizardforcel 赞，感谢推荐优秀英文文章， 奖励积分 5 分。
