### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by NeoyeElf** [xitu/gold-miner#3129]
- 原文链接：https://engineering.instagram.com/improving-performance-with-background-data-prefetching-b191acb39898
- 简要介绍：instagram的官方技术文章。阐述了如何通过后台数据预获取技术来提升性能

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
已发布
