### ISSUE TITLE
通过后台数据预获取技术实现性能提升

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3132]
* 原文链接：[Improving performance with background data prefetching](https://engineering.instagram.com/improving-performance-with-background-data-prefetching-b191acb39898)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/improving-performance-with-background-data-prefetching.md)
  * PR 地址：#3167
  * 文章分类：**后端**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by NeoyeElf** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@NeoyeElf 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3167
