### ISSUE TITLE
这些 CSS 命名规范将省下你大把调试时间

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3134]
* 原文链接：[CSS Naming Conventions that Will Save You Hours of Debugging](https://medium.freecodecamp.org/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/css-naming-conventions-that-will-save-you-hours-of-debugging.md)
  * PR 地址：#3163
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by unicar9** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@unicar9 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3163
