### ISSUE TITLE
迎接新的 Dialog 元素

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3135]
* 原文链接：[Meet the New Dialog Element](https://keithjgrant.com/posts/2018/meet-the-new-dialog-element/?utm_source=frontendfocus&utm_medium=email)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/meet-the-new-dialog-element.md)
  * PR 地址：#3148
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by FateZeros** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@FateZeros 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3146

**Comment by fanyijihua** [comment]
PR 地址：#3147
