### ISSUE TITLE
大话（Summer vs winter Observable）之我与 Rx Observable[Android RxJava2]（这是什么鬼）第六话

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3140]
* 原文链接：[Continuation (Summer vs Winter Observable) of Dialogue between Rx Observable and a Developer (Me) [ Android RxJava2 ] ( What the hell is this ) Part6](http://www.uwanttolearn.com/android/continuation-summer-vs-winter-observable-dialogue-rx-observable-developer-android-rxjava2-hell-part6/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/continuation-summer-vs-winter-observable-dialogue-rx-observable-developer-android-rxjava2-hell-part6.md)
  * PR 地址：#3223
  * 文章分类：**Android**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：3 分 LeeSniper 4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hanliuxin5** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@hanliuxin5 棒极啦 :tada:

**Comment by hanliuxin5** [comment]
@leviding 本来打算今天翻译完的，有点事耽搁了...
2月4号周日之前搞定
