### ISSUE TITLE
Subject 和 Observable + Observer 的混淆指北[ Android RxJava2 ] ( 这什么鬼系列 ) 第八话

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3142]
* 原文链接：[Confusion between Subject and Observable + Observer [ Android RxJava2 ] ( What the hell is this ) Part8](http://www.uwanttolearn.com/android/confusion-subject-observable-observer-android-rxjava2-hell-part8/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/confusion-subject-observable-observer-android-rxjava2-hell-part8.md)
  * PR 地址：#3303
  * 文章分类：**Android**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分 + 1
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rockzhai** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@rockzhai 棒极啦 :tada:

**Comment by rockzhai** [comment]
领了忘记了，超期了……最近忙一点，这两天搞了=-=..

**Comment by leviding** [comment]
@rockzhai 吼的哈

**Comment by leviding** [comment]
@rockzhai 翻译的怎么样啦

**Comment by leviding** [comment]
@rockzhai 翻译的怎么样啦
