### ISSUE TITLE
Turbocharged JavaScript refactoring with codemods

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#315]
原文链接：[Turbocharged JavaScript refactoring with codemods](https://medium.com/airbnb-engineering/turbocharged-javascript-refactoring-with-codemods-b0cae8b326b9#.tjerodd52)
掘金链接：[Turbocharged JavaScript refactoring with codemods](http://gold.xitu.io/entry/572760cc128fe100605199fa)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/turbocharged-javascript-refactoring-with-codemods.md)
PR地址：#335
翻译时间：5天
校对时间：3天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by hikerpig** [comment]
认领翻译~

**Comment by antonia0912** [comment]
@hikerpig ok 等你PR

**Comment by Jack-Kingdom** [comment]
校对+1。 @antonia0912

**Comment by antonia0912** [comment]
@Jack-Kingdom 好的 [校对地址](https://github.com/xitu/gold-miner/pull/335/files?diff=split)

**Comment by godofchina** [comment]
@antonia0912  申请校对

**Comment by antonia0912** [comment]
@godofchina 好的 [校对地址](https://github.com/xitu/gold-miner/pull/335/files?diff=split)

**Comment by godofchina** [comment]
@antonia0912  第二次校对 完毕
