### ISSUE TITLE
关于排版指南中脚注方案的修改建议

### ISSUE THREAD

**Issue by LeopPro** [xitu/gold-miner#3153]
[译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E5%A6%82%E6%9E%9C%E6%96%87%E7%AB%A0%E4%B8%AD%E6%9C%89%E8%84%9A%E6%B3%A8%E6%80%8E%E4%B9%88%E5%8A%9E)中脚注方案是支持Github的，但是不支持掘金。
原因如下：  
markdown中的超链接在Github中被解析为 `<a href="xxx">yyy</a>`，但是在掘金中被解析为`< target="_blank" href="xxx">yyy</a>`。因此原脚注方案`<sup>[\[1\]](#note1)</sup>
`在掘金中会弹出新窗口。  
修改建议，该方案同时支持掘金与Github：
```
这里是修改后的脚注显示方案 <sup><a href="#note1">[1]</a></sup>

1. <a name="note1"></a> [how-to-add-footnotes-to-github-flavoured-markdown](http://stackoverflow.com/questions/25579868/how-to-add-footnotes-to-github-flavoured-markdown)
```
预览效果如下：

> 这里是修改后的脚注显示方案 <sup><a href="#note1">[1]</a></sup>  

1. <a name="note1"></a> [how-to-add-footnotes-to-github-flavoured-markdown](http://stackoverflow.com/questions/25579868/how-to-add-footnotes-to-github-flavoured-markdown)

**Comment by leviding** [comment]
@LeopPro 很赞，已经修改，详见： https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E5%A6%82%E6%9E%9C%E6%96%87%E7%AB%A0%E4%B8%AD%E6%9C%89%E8%84%9A%E6%B3%A8%E6%80%8E%E4%B9%88%E5%8A%9E
