### ISSUE TITLE
Facebook 开源了物体检测研究项目 Detectron

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3158]
* 原文链接：[Facebook open sources Detectron](https://research.fb.com/facebook-open-sources-detectron/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/facebook-open-sources-detectron.md)
  * PR 地址：#3168
  * 文章分类：**深度学习**
  ----
  * 翻译时间：1 天
  * 校对时间：1 天
  * 翻译积分：1 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
本篇已被认领

**Comment by SeanW20** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@SeanW20 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3168

**Comment by SeanW20** [comment]
https://juejin.im/post/5a6c2ba56fb9a01cb64f0591
