### ISSUE TITLE
Facebook 的 AI 万金油：StarSpace 神经网络模型简介

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3159]
* 原文链接：[The Introduction of StarSpace](https://github.com/facebookresearch/StarSpace/blob/master/README.md)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-introduction-of-starspace.md)
  * PR 地址：#3208
  * 文章分类：**机器学习**
  ----
  * 翻译时间：7 天 和 SeanW20 双译者
  * 校对时间：2 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
本篇已被认领

**Comment by noahziheng** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@noahziheng 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3208
