### ISSUE TITLE
10 个你可能不知道的 Facebook 内部开发环境是如何使用 JavaScript 和 GraphQL 的

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#316]
原文链接：[10 things you probably didn't know about JavaScript (React and Node.js) and GraphQL development at Facebook](https://hashnode.com/post/10-things-you-probably-didnt-know-about-javascript-react-and-nodejs-and-graphql-development-at-facebook-cink0r0e500h5io53fpl7ediu)
掘金链接：[10 个你可能不知道的 Facebook 内部开发环境是如何使用 JavaScript 和 GraphQL 的](http://gold.xitu.io/entry/5724eac039b057006aedefe7)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/10-things-you-probably-didnt-know-about-javascript-react-and-nodejs-and-graphql-development-at-facebook.md)

翻译时间：3天
校对时间：2天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Jack-Kingdom** [comment]
认领+1 @antonia0912

**Comment by antonia0912** [comment]
@Jack-Kingdom 请问你之前有校对过文章咩  新译者加入要先从校对文章开始喔~

**Comment by DeadLion** [comment]
校对认领 @antonia0912

**Comment by antonia0912** [comment]
@DeadLion 好的 [校对地址](https://github.com/xitu/gold-miner/pull/326/files?diff=split)

**Comment by DeadLion** [comment]
中英文间隔有些地方有，有些地方又没有。
@Jack-Kingdom 

校稿完成 @antonia0912

**Comment by antonia0912** [comment]
@DeadLion 辛苦校对者啦  请译者注意 中英文之间要有空格 @Jack-Kingdom
