### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by damonYuan** [xitu/gold-miner#3166]
区块链

- [*Proof of Work* vs *Proof of Stake*](https://blockgeeks.com/guides/proof-of-work-vs-proof-of-stake/)

觉得PoS是区块链发展趋势，可以让这个技术更加环保而不是无谓的比拼算力。现在比较成功的币种是[EOS](https://eos.io/)。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
已经发布任务，有兴趣可以去认领一下 https://github.com/xitu/gold-miner/issues/3174
