### ISSUE TITLE
给 iOS 开发者的 GCD 用户手册

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#317]
原文链接：[The GCD Handbook](http://khanlou.com/2016/04/the-GCD-handbook/)
掘金链接：[给 iOS 开发者的 GCD 用户手册](http://gold.xitu.io/entry/57276930128fe10060520386)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/the-GCD-handbook.md)

翻译时间：5天
校对时间：3天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by woopqww111** [comment]
对于ios有着极大热情的普通学生。
如果我合格了名字是这个。(woopqww111/seven_words)
认领此篇

**Comment by antonia0912** [comment]
@woopqww111 不是译者要先去issue里发译者申请喔~ [翻译计划怎么玩点这里](https://github.com/xitu/gold-miner/blob/master/README.md)

**Comment by LoneyIsError** [comment]
我要认领这个！认领这个

**Comment by antonia0912** [comment]
@LoneyIsError 好的  等你PR

**Comment by hsinshufan** [comment]
校对认领^^

**Comment by hsinshufan** [comment]
校对认领^^
