### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by lcx-seima** [xitu/gold-miner#3171]
- 原文链接：https://blog.sessionstack.com/how-javascript-works-the-building-blocks-of-web-workers-5-cases-when-you-should-use-them-a547c0757f6a
- 简要介绍：新鲜刚出炉的好前端文章，来自 SessionStack 团队。讲解了 Web Workers 的使用 case。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by lcx-seima** [comment]
@fanyijihua 如果审核通过，我直接认领本文翻译。谢谢。

**Comment by leviding** [comment]
已发出
