### ISSUE TITLE
嵌套三元表达式棒极了（软件编写）（第十四部分）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3172]
* 原文链接：[Nested Ternaries are Great](https://medium.com/javascript-scene/nested-ternaries-are-great-361bddd0f340)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/nested-ternaries-are-great.md)
  * PR 地址：#3220
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@yoyoyohamapi 你的

**Comment by yoyoyohamapi** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@yoyoyohamapi 棒极啦 :tada:
