### ISSUE TITLE
JavaScript 工作原理：Web Worker 的内部构造以及 5 种你应当使用它的场景

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3173]
* 原文链接：[How JavaScript works: The building blocks of Web Workers + 5 cases when you should use them](https://blog.sessionstack.com/how-javascript-works-the-building-blocks-of-web-workers-5-cases-when-you-should-use-them-a547c0757f6a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-javascript-works-the-building-blocks-of-web-workers-5-cases-when-you-should-use-them.md)
  * PR 地址：#3278
  * 文章分类：**前端**
  ----
  * 翻译时间：7 天
  * 校对时间：2  天
  * 翻译积分：8 分
  * 校对积分：2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@lcx-seima 你的了

**Comment by lcx-seima** [comment]
谢谢

**Comment by leviding** [comment]
@lcx-seima 翻译的怎么样啦

**Comment by lcx-seima** [comment]
@leviding 这边差不多了。自己再润色一下，最迟明天发。

**Comment by leviding** [comment]
@chemzqm 好，辛苦啦

**Comment by fanyijihua** [comment]
PR 地址：#3278
