### ISSUE TITLE
🚀webpack 4 测试版 —— 现在让我们先一睹为快吧!🚀

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3175]
* 原文链接：[🚀webpack 4 beta — try it today!🚀](https://medium.com/webpack/webpack-4-beta-try-it-today-6b1d27d7d7e2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/webpack-4-beta-try-it-today.md)
  * PR 地址：#3203
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by FateZeros** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@FateZeros 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3203
