### ISSUE TITLE
标准化的包布局

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3176]
* 原文链接：[Standard Package Layout](https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/standard-package-layout.md)
  * PR 地址：#3238
  * 文章分类：**前端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by steinliber** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@steinliber 棒极啦 :tada:
