### ISSUE TITLE
我未曾见过的 JS 特性

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3177]
* 原文链接：[JS things I never knew existed](https://air.ghost.io/js-things-i-never-knew-existed/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/js-things-i-never-knew-existed.md)
  * PR 地址：#3186
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by NeilLi1992** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@NeilLi1992 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3186
