### ISSUE TITLE
swift 网络单元测试完全手册

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3180]
* 原文链接：[The complete guide to Network Unit Testing in Swift](https://medium.com/flawless-app-stories/the-complete-guide-to-network-unit-testing-in-swift-db8b3ee2c327)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-complete-guide-to-network-unit-testing-in-swift.md)
  * PR 地址：#3214
  * 文章分类：**iOS**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by swants** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@swants 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3214
