### ISSUE TITLE
用 LLDB 调试 Swift 代码

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3181]
* 原文链接：[Debugging Swift code with LLDB](https://medium.com/flawless-app-stories/debugging-swift-code-with-lldb-b30c5cf2fd49)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/debugging-swift-code-with-lldb.md)
  * PR 地址：#3210
  * 文章分类：**iOS**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by VernonVan** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@VernonVan 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3210

**Comment by charsdavy** [comment]
校对认领 @leviding
