### ISSUE TITLE
断点：像专家一样调试代码

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3182]
* 原文链接：[Breakpoints: Debugging like a Pro](https://cheesecakelabs.com/blog/breakpoints-debugging-like-pro/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/breakpoints-debugging-like-pro.md)
  * PR 地址：#3191
  * 文章分类：**iOS**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iOSleep** [comment]
这篇的质量有点低...

**Comment by leviding** [comment]
@iOSleep 那我把这篇 close 怎么样

**Comment by pthtc** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pthtc 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3191
