### ISSUE TITLE
17 个 Xcode 小技巧，每个 iOS 开发者都该知道

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3183]
* 原文链接：[17 Xcode Tips and Tricks That Every iOS Developer Should Know](https://www.detroitlabs.com/blog/2017/04/13/17-xcode-tips-and-tricks-that-every-ios-developer-should-know/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/17-xcode-tips-and-tricks-that-every-ios-developer-should-know.md)
  * PR 地址：#3185
  * 文章分类：**iOS**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pthtc** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pthtc 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3185
