### ISSUE TITLE
JavaScript Standard Style 

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#319]
原文链接：[JavaScript Standard Style ](http://standardjs.com/)
掘金链接：[JavaScript Standard Style](http://gold.xitu.io/entry/57298e4671cfe4006c7220b1)
markdown文件：[文件位置待添加]()

翻译时间：5天
校对时间：3天
翻译积分：8
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by AndyChen2005121** [comment]
？
