### ISSUE TITLE
https://medium.com/styled-components/v3-1-0-such-perf-wow-many-streams-c45c434dbd03

### ISSUE THREAD

**Issue by sakila1012** [xitu/gold-miner#3192]
* 原文链接：https://medium.com/styled-components/v3-1-0-such-perf-wow-many-streams-c45c434dbd03
* 简要介绍：css in js，改善服务端渲染

**Comment by sakila1012** [comment]
@leviding

**Comment by leviding** [comment]
@sakila1012 已经发了，快来认领吧
