### ISSUE TITLE
在 Android 应用里使用 RenderScript 来简单快速的处理图片

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#320]
原文链接：[Android : Simple and fast image processing with RenderScript](https://medium.com/@qhutch/android-simple-and-fast-image-processing-with-renderscript-2fa8316273e1#.4u5p41sil)
掘金链接：[在 Android 应用里使用 RenderScript 来简单快速的处理图片](http://gold.xitu.io/entry/5726300d49830c0053517570)
markdown文件：[文件位置待添加]()

翻译时间：5天
校对时间：3天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Sausure** [comment]
认领，我看过这文章

**Comment by antonia0912** [comment]
@Sausure ok

**Comment by Sausure** [comment]
咦，怎么关闭了

发自我的 iPhone

**Comment by antonia0912** [comment]
@Sausure 网上已经有译文了。。。。

**Comment by Sausure** [comment]
哦哦，那没法了

发自我的 iPhone
