### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by LynnShaw** [xitu/gold-miner#3201]
- 原文链接：[Contributing to Django Framework is easier than you think](https://www.vinta.com.br/blog/2017/contributing-hugh-lib/?hmsr=pycourses.com&utm_source=pycourses.com&utm_medium=pycourses.com)
- 简要介绍：给 Django 框架贡献代码远比你想象的容易

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@LynnShaw 感谢推荐，已发布任务
