### ISSUE TITLE
为 Django Framework 贡献你的力量并没有想象中的那么难

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3205]
* 原文链接：[Contributing to Django Framework is easier than you think](https://www.vinta.com.br/blog/2017/contributing-hugh-lib/?hmsr=pycourses.com&utm_source=pycourses.com&utm_medium=pycourses.com)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/contributing-hugh-lib.md)
  * PR 地址：#3213
  * 文章分类：**后端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JayZhaoBoy** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@JayZhaoBoy 棒极啦 :tada:

**Comment by JayZhaoBoy** [comment]
@leviding 
https://juejin.im/post/5a77cd6e5188257a79247fe1
