### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by Serendipity96** [xitu/gold-miner#3207]
分类：前端
原文链接：https://www.smashingmagazine.com/2018/02/javascript-firefox-debugger/
关键词：javascript-firefox-debugger
简介：你前所未知的JavaScript调试器

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢推荐，明天放上去
