### ISSUE TITLE
你前所未知的 JavaScript 调试器

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3217]
* 原文链接：[Debugging JavaScript With A Real Debugger You Did Not Know You Already Have](https://www.smashingmagazine.com/2018/02/javascript-firefox-debugger/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/javascript-firefox-debugger.md)
  * PR 地址：#3250
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Serendipity96** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Serendipity96 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3250
