### ISSUE TITLE
探索 ECMAScript 装饰器

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3218]
* 原文链接：[Exploring EcmaScript Decorators](https://medium.com/google-developers/exploring-es7-decorators-76ecb65fb841)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/exploring-es7-decorators.md)
  * PR 地址：#3249
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4.5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by goldEli** [comment]
@leviding @fanyijihua 翻译认领

**Comment by fanyijihua** [comment]
PR 地址：#3241

**Comment by fanyijihua** [comment]
PR 地址：#3249
