### ISSUE TITLE
使用 SVG 符号和 CSS 变量实现多彩图标

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3219]
* 原文链接：[Let’s make multi-colored icons with SVG symbols and CSS variables](https://medium.freecodecamp.org/lets-make-your-svg-symbol-icons-multi-colored-with-css-variables-cddd1769fca4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/lets-make-your-svg-symbol-icons-multi-colored-with-css-variables.md)
  * PR 地址：#3258
  * 文章分类：**前端**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pthtc** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pthtc 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3258
