### ISSUE TITLE
深度剖析 Swift 编译与运行时的类型检查

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#322]
原文链接：[Compile Time vs. Run Time Type Checking in Swift](http://blog.benjamin-encz.de/post/compile-time-vs-runtime-type-checking-swift/)
掘金链接：[深度剖析 Swift 编译与运行时的类型检查](http://gold.xitu.io/entry/572aef3a1532bc0065d73013)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/compile-time-vs-runtime-type-checking-swift.md)

翻译时间：5天
校对时间：3天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by fantangxi** [comment]
我来试试吧~要是我真不行就把我换掉。。。

**Comment by antonia0912** [comment]
@fantangxi 新加入的译者还不能翻译  只能从校对开始喔

**Comment by Jack-Kingdom** [comment]
翻译+1 @antonia0912

**Comment by antonia0912** [comment]
@Jack-Kingdom OK 等你PR

**Comment by Jack-Kingdom** [comment]
翻译完成 @antonia0912 

拖延癌发作了，迟到了两周，我很抱歉。

**Comment by Tuccuay** [comment]
认 （

**Comment by antonia0912** [comment]
@Tuccuay ok

**Comment by void-main** [comment]
认领校对～

**Comment by antonia0912** [comment]
@void-main 乖~~~小手摸摸大头~~

**Comment by void-main** [comment]
我这边校对完了～

**Comment by antonia0912** [comment]
@void-main wonderful~
