### ISSUE TITLE
不再对 MVVM 感到绝望

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3221]
* 原文链接：[How not to get desperate with MVVM implementation](https://medium.com/flawless-app-stories/how-to-use-a-model-view-viewmodel-architecture-for-ios-46963c67be1b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-use-a-model-view-viewmodel-architecture-for-ios.md)
  * PR 地址：#3222
  * 文章分类：**iOS**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JayZhaoBoy** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@JayZhaoBoy 棒极啦 :tada:
