### ISSUE TITLE
用户账户、授权和密码管理的 12 个最佳方法

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3236]
* 原文链接：[12 best practices for user account, authorization and password management](https://cloudplatform.googleblog.com/2018/01/12-best-practices-for-user-account.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/12-best-practices-for-user-account.md)
  * PR 地址：#3288
  * 文章分类：**后端**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Wangalan30** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Wangalan30 棒极啦 :tada:
