### ISSUE TITLE
在 production 使用 nodejs 一年后

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#324]
原文链接：[AFTER A YEAR OF USING NODEJS IN PRODUCTION](http://geekforbrains.com/post/after-a-year-of-nodejs-in-production)
掘金链接：[在 production 使用 nodejs 一年后](http://gold.xitu.io/entry/572c28ae1ea4930064c63a6b)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/after-a-year-of-nodejs-in-production.md)
PR 地址 https://github.com/xitu/gold-miner/pull/340
翻译时间：5天
校对时间：3天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by cdpath** [comment]
认领这篇~

**Comment by antonia0912** [comment]
@cdpath 好的  等你PR

**Comment by cdpath** [comment]
@antonia0912 翻译好了，
PR 地址 https://github.com/xitu/gold-miner/pull/340

**Comment by godofchina** [comment]
校对认领

**Comment by antonia0912** [comment]
@godofchina 好的 [校对地址](https://github.com/xitu/gold-miner/pull/340/files?diff=split)

**Comment by godofchina** [comment]
@antonia0912  第一次校对完毕
