### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by NeoyeElf** [xitu/gold-miner#3246]
- 原文链接：https://medium.com/programmers-blockchain/create-simple-blockchain-java-tutorial-from-scratch-6eeed3cb03fa（part 1）
https://medium.com/programmers-blockchain/creating-your-first-blockchain-with-java-part-2-transactions-2cdac335e0ce（part 2）

- 简要介绍：区块链相关，使用Java实现简单的区块链。是一个系列文章，现在有第一部分和第二部分，第三部分敬请期待。先推荐这2篇

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
收到，感谢推荐，本周内放上去

**Comment by leviding** [comment]
感谢推荐，已经放上去啦
