### ISSUE TITLE
也谈 React 16.3(.0-alpha)

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3251]
* 原文链接：[What’s new in React 16.3(.0-alpha)](https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/whats-new-in-react-16-3.md)
  * PR 地址：#3273
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pot-code** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pot-code 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3273
