### ISSUE TITLE
用 Java 创造你的第一个区块链 — 第一部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3255]
* 原文链接：[Creating Your First Blockchain with Java. Part 1](https://medium.com/programmers-blockchain/create-simple-blockchain-java-tutorial-from-scratch-6eeed3cb03fa)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/create-simple-blockchain-java-tutorial-from-scratch.md)
  * PR 地址：#3274
  * 文章分类：**区块链**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by NeoyeElf** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@NeoyeElf 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3274
