### ISSUE TITLE
用 Java 创造你的第一个区块链之第二部分 — 交易

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3256]
* 原文链接：[Jan 20 Creating Your First Blockchain with Java. Part 2 — Transactions](https://medium.com/programmers-blockchain/creating-your-first-blockchain-with-java-part-2-transactions-2cdac335e0ce)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/creating-your-first-blockchain-with-java-part-2-transactions.md)
  * PR 地址：#3287
  * 文章分类：**区块链**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#3287
