### ISSUE TITLE
Using CSS Counters

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3257]
* 原文链接：[Using CSS Counters](https://pineco.de/using-css-counters/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/using-css-counters.md)
  * PR 地址：#3263
  * 文章分类：**前端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2.5 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sakila1012** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sakila1012 棒极啦 :tada:

**Comment by sakila1012** [comment]
翻译完成 @leviding

**Comment by leviding** [comment]
@sakila1012 没看到 pull request 请认真检查

**Comment by sakila1012** [comment]
@leviding 已提交
