### ISSUE TITLE
使用 MVI 开发响应式 APP - 第三部分 - 状态减少（state reducer）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3264]
* 原文链接：[REACTIVE APPS WITH MODEL-VIEW-INTENT - PART3 - STATE REDUCER](http://hannesdorfmann.com/android/mosby3-mvi-3)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/mosby3-mvi-3.md)
  * PR 地址：#3285
  * 文章分类：**Android**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@pcdack 你的了

**Comment by pcdack** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@pcdack 棒极啦 :tada:

**Comment by hanliuxin5** [comment]
校对认领
