### ISSUE TITLE
通过 Quick 和 Nimble 在 Swift 中进行测试驱动开发

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3265]
* 原文链接：[Test Driven Development (TDD) in Swift with Quick and Nimble](https://www.appcoda.com/tdd-quick-nimble/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/tdd-quick-nimble.md)
  * PR 地址：#
  * 文章分类：**iOS**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by 94haox** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@94haox 棒极啦 :tada:

**Comment by 94haox** [comment]
@leviding  翻译完成

**Comment by leviding** [comment]
@94haox 没看到 pull request 呢
