### ISSUE TITLE
在 Swift playground 中编写单元测试

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3266]
* 原文链接：[Writing unit tests in Swift playgrounds](https://www.swiftbysundell.com/posts/writing-unit-tests-in-a-swift-playground)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/writing-unit-tests-in-a-swift-playground.md)
  * PR 地址：#3286
  * 文章分类：**iOS**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3286
