### ISSUE TITLE
避免 Swift 单元测试中的强制解析

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3267]
* 原文链接：[Avoiding force unwrapping in Swift unit tests](https://www.swiftbysundell.com/posts/avoiding-force-unwrapping-in-swift-unit-tests)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/avoiding-force-unwrapping-in-swift-unit-tests.md)
  * PR 地址：#3317
  * 文章分类：**iOS**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by RickeyBoy** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@RickeyBoy 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3317
