### ISSUE TITLE
使用 leanback 的 DiffCallback：和 DiffUtil 回调之间的区别

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3268]
* 原文链接：[Using leanback’s DiffCallback: The difference between the DiffUtil callbacks](https://medium.com/google-developers/using-leanbacks-diffcallback-77d47949212b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/using-leanbacks-diffcallback.md)
  * PR 地址：#3275
  * 文章分类：**Android**
  ----
  * 翻译时间：1 天
  * 翻译积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LeeSniper** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@LeeSniper 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3275
