### ISSUE TITLE
CSS Grid 之列宽自适应：`auto-fill` vs `auto-fit`

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3269]
* 原文链接：[Auto-Sizing Columns in CSS Grid: `auto-fill` vs `auto-fit`](https://css-tricks.com/auto-sizing-columns-css-grid-auto-fill-vs-auto-fit/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/auto-sizing-columns-css-grid-auto-fill-vs-auto-fit.md)
  * PR 地址：#3291
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pot-code** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pot-code 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3290

**Comment by fanyijihua** [comment]
PR 地址：#3291
