### ISSUE TITLE
json — JavaScript 对象表示法

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3270]
* 原文链接：[json — JavaScript Object Notation](https://pymotw.com/3/json/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/json-javascript-object-notation.md)
  * PR 地址：#3284
  * 文章分类：**前端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by snowyYU** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@snowyYU 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3284
