### ISSUE TITLE
Service workers：Progressive Web Apps 背后的小英雄

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3271]
* 原文链接：[Service workers: the little heroes behind Progressive Web Apps](https://medium.freecodecamp.org/service-workers-the-little-heroes-behind-progressive-web-apps-431cc22d0f16)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/service-workers-the-little-heroes-behind-progressive-web-apps.md)
  * PR 地址：#3328
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by FateZeros** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@FateZeros 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3328
