### ISSUE TITLE
从 SQLite 逐步迁移到 Room

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3272]
* 原文链接：[Incrementally migrate from SQLite to Room](https://medium.com/google-developers/incrementally-migrate-from-sqlite-to-room-66c2f655b377)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/incrementally-migrate-from-sqlite-to-room.md)
  * PR 地址：#3280
  * 文章分类：**Android**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#3280
