### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by iOSleep** [xitu/gold-miner#3276]
- 原文链接：推荐文章前 Google 一下，尽量保证本文未被翻译
[Why Your App Looks Better in Sketch](https://medium.com/@nathangitter/why-your-app-looks-better-in-sketch-3a01b22c43d7)

- 简要介绍：介绍一下好不好啦，毕竟小编也看不太懂哎_(:з」∠)_
介绍如何让你的 iOS 代码效果和 Sketch 的设计稿看起来“一样”

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@iOSleep 感谢推荐，本周放上去，届时我关闭此 issue
