### ISSUE TITLE
关于 Swift 编译时性能优化的一些思考

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#329]
原文链接：[Regarding Swift build time optimizations](https://medium.com/@RobertGummesson/regarding-swift-build-time-optimizations-fc92cdd91e31#.w81y3zhjr)
掘金链接：[关于 Swift 编译时性能优化的一些思考](http://gold.xitu.io/entry/572cb4142e958a006682b18b)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/regarding-swift-build-time-optimizations.md)

翻译时间：3天
校对时间：2天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by yllziv** [comment]
认领，研究过一段时间swift。@antonia0912

**Comment by antonia0912** [comment]
@yllziv OK 前面那篇文章校对完了要发comment “校对完成”哈  我好跟进进度

**Comment by yllziv** [comment]
OK，发了嘿嘿

**Comment by yllziv** [comment]
翻译完成 @antonia0912 ，已发PR

**Comment by antonia0912** [comment]
@yllziv 辛苦啦  我来联系校对者

**Comment by shenAlexy** [comment]
申请二校 @antonia0912

**Comment by antonia0912** [comment]
@shenAlexy 好的 [校对地址](https://github.com/xitu/gold-miner/pull/334/files?diff=split)
