### ISSUE TITLE
为什么你的 APP 在 Sketch 上看起来更好：探索 Sketch 和 iOS 的渲染差异

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3294]
* 原文链接：[Why Your App Looks Better in Sketch: Exploring rendering differences between Sketch and iOS](https://medium.com/@nathangitter/why-your-app-looks-better-in-sketch-3a01b22c43d7)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-your-app-looks-better-in-sketch.md)
  * PR 地址：#3307
  * 文章分类：**iOS**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rydensun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@rydensun 棒极啦 :tada:
