### ISSUE TITLE
建立一个像科幻小说一样的虚拟世界：设计一个全球性的虚拟世界

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3296]
* 原文链接：[Building a Virtual World Worthy of Sci-Fi: Designing a global metaverse](https://medium.com/google-developers/building-a-virtual-world-worthy-of-sci-fi-3d48e2fd05e3)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/building-a-virtual-world-worthy-of-sci-fi.md)
  * PR 地址：#3432
  * 文章分类：**Android**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LeeSniper** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@LeeSniper 棒极啦 :tada:

**Comment by hanliuxin5** [comment]
期待这篇的翻译

**Comment by leviding** [comment]
@LeeSniper 翻译的怎么样啦

**Comment by LeeSniper** [comment]
@leviding 翻译了一半了，不过这两周一直在忙，没抽出时间来，这周末有空，应该能翻完。

**Comment by leviding** [comment]
@LeeSniper ok

**Comment by leviding** [comment]
@LeeSniper 本文怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#3432

**Comment by LeeSniper** [comment]
@leviding 已提交 PR
