### ISSUE TITLE
利用 Android 构建 TV 的未来

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3297]
* 原文链接：[Building for the future of TV with Android](https://medium.com/googleplaydev/building-for-the-future-of-tv-with-android-1f4916f3cc3e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/building-for-the-future-of-tv-with-android.md)
  * PR 地址：#3319
  * 文章分类：**Android**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JayZhaoBoy** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@JayZhaoBoy 棒极啦 :tada:
