### ISSUE TITLE
在 Android Instant App（安卓即时应用程序）中启用 ProGuard（混淆）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3298]
* 原文链接：[Enabling ProGuard in an Android Instant App](https://medium.com/google-developers/enabling-proguard-in-an-android-instant-app-fbd4fc014518)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/enabling-proguard-in-an-android-instant-app.md)
  * PR 地址：#3362
  * 文章分类：**Android**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JayZhaoBoy** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@JayZhaoBoy 棒极啦 :tada:
