### ISSUE TITLE
How to Build and Publish ES6 Modules Today, with Babel and Rollup

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#330]
原文链接：[How to Build and Publish ES6 Modules Today, with Babel and Rollup](https://medium.com/@tarkus/how-to-build-and-publish-es6-modules-today-with-babel-and-rollup-4426d9c7ca71#.oqt9xunbj)
掘金链接：[How to Build and Publish ES6 Modules Today, with Babel and Rollup](http://gold.xitu.io/entry/572eb87b49830c0061a60a64)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-build-and-publish-es6-modules-today-with-babel-and-rollup.md)

翻译时间：3天
校对时间：2天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by L9m** [comment]
刚校对完，就看到 JavaScript 的 认领

**Comment by antonia0912** [comment]
@L9m markdown 文件已经添加好了  等你PR

**Comment by yangzj1992** [comment]
校对认领

**Comment by antonia0912** [comment]
@yangzj1992 收到

**Comment by malcolmyu** [comment]
校对认领

**Comment by antonia0912** [comment]
@malcolmyu 收到~
