### ISSUE TITLE
推荐优秀英文文章《带你了解以太坊第2层扩容方案：State Channels、Plasma 和 Truebit》

### ISSUE THREAD

**Issue by Glowin** [xitu/gold-miner#3309]
- 原文链接：[带你了解以太坊第2层扩容方案：State Channels、Plasma 和 Truebit
](https://medium.com/l4-media/making-sense-of-ethereums-layer-2-scaling-solutions-state-channels-plasma-and-truebit-22cb40dcc2f4)
- 简要介绍：CryptoKitties 和 ICO 的火热让以太坊网络的拥堵问题排上日程，本文介绍了以太坊的三种扩容方案：State Channels、Plasma 和 Truebit。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@Glowin get

**Comment by leviding** [comment]
@Glowin 发布了
