### ISSUE TITLE
UX: Infinite Scrolling vs. Pagination

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#331]
原文链接：[UX: Infinite Scrolling vs. Pagination](https://uxplanet.org/ux-infinite-scrolling-vs-pagination-1030d29376f1#.4mfu0ijhu)
掘金链接：[UX: Infinite Scrolling vs. Pagination](http://gold.xitu.io/entry/57304a6a79df540060ca5f4d)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/ux-infinite-scrolling-vs-pagination.md)

翻译时间：5天
校对时间：3天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Ruixi** [comment]
来了！

**Comment by antonia0912** [comment]
@Ruixi love U~

**Comment by Velacielad** [comment]
认领校对～

**Comment by Ruixi** [comment]
那个……我先去解决一下分支冲突的问题😂
还好之前的翻译有备份……

**Comment by wild-flame** [comment]
认领校对：D

**Comment by Ruixi** [comment]
分支冲突问题已解决……［趴

**Comment by Velacielad** [comment]
第一遍校对完成 =w= @antonia0912 @Ruixi

**Comment by antonia0912** [comment]
@wild-flame 好的 [校对地址](https://github.com/xitu/gold-miner/pull/349/files?diff=split)
