### ISSUE TITLE
带你了解以太坊第 2 层扩容方案：State Channels、Plasma 和 Truebit

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3310]
* 原文链接：[带你了解以太坊第 2 层扩容方案：State Channels、Plasma 和 Truebit](https://medium.com/l4-media/making-sense-of-ethereums-layer-2-scaling-solutions-state-channels-plasma-and-truebit-22cb40dcc2f4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/making-sense-of-ethereums-layer-2-scaling-solutions-state-channels-plasma-and-truebit.md)
  * PR 地址：#3373
  * 文章分类：**区块链**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：11 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnJiangLA** [comment]
这么快， @leviding ，翻译认领

**Comment by fanyijihua** [comment]
@JohnJiangLA 棒极啦 :tada:

**Comment by Zheaoli** [comment]
窝草，居然被抢了。。
@JohnJiangLA 翻译完给我说，我来校对

**Comment by foxxnuaa** [comment]
我也来预领 校对 @JohnJiangLA

**Comment by Glowin** [comment]
@JohnJiangLA 请问一下翻译进度咋样啦？

**Comment by JohnJiangLA** [comment]
@Glowin 这周完成，抱歉，工作事务比较忙一点。 @foxxnuaa @Zheaoli  好的，PR时会通知的

**Comment by Glowin** [comment]
@JohnJiangLA 请问文章翻译进度咋样啦？

**Comment by fanyijihua** [comment]
PR 地址：#3373

**Comment by foxxnuaa** [comment]
认领校对
