### ISSUE TITLE
第三方 SDK 的信任问题

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3313]
* 原文链接：[Trusting third party SDKs](https://krausefx.com/blog/trusting-sdks)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/trusting-sdks.md)
  * PR 地址：#3358
  * 文章分类：**Android**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CACppuccino** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@CACppuccino 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3358
