### ISSUE TITLE
React 应用中 “神奇” 的多态—性能隐患

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3314]
* 原文链接：[Surprising polymorphism in React applications](https://medium.com/@bmeurer/surprising-polymorphism-in-react-applications-63015b50abc)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/surprising-polymorphism-in-react-applications.md)
  * PR 地址：#3372
  * 文章分类：**前端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by blizzardzheng** [comment]
认领

**Comment by leviding** [comment]
@blizzardzheng ok，下次记得口令写全，例如 `认领翻译` 或 `翻译认领`。

**Comment by fanyijihua** [comment]
PR 地址：#3372
