### ISSUE TITLE
在 V8 引擎中设置原型（prototypes）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3315]
* 原文链接：[Setting up prototypes in V8](https://medium.com/@tverwaes/setting-up-prototypes-in-v8-ec9c9491dfe2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/setting-up-prototypes-in-v8.md)
  * PR 地址：#3326
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by goldEli** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@goldEli 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3326

**Comment by xui666** [comment]
@leviding校对认领

**Comment by leviding** [comment]
@xui666 在对应的 pull request 下进行认领哈
