### ISSUE TITLE
9 Promising Promise Tips

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3316]
* 原文链接：[9 Promising Promise Tips](https://dev.to/kepta/promising-promise-tips--c8f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/promising-promise-tips.md)
  * PR 地址：#3321
  * 文章分类：**前端**
  ----
  * 翻译时间：3 天
  * 校对时间：3.5 天
  * 翻译积分：1 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yanyixin** [comment]
@leviding翻译认领

**Comment by fanyijihua** [comment]
@yanyixin 棒极啦 :tada:

**Comment by yanyixin** [comment]
想请问一下，这篇文章翻译的积分是 1 分吗

**Comment by pkuwwt** [comment]
@leviding 校对认领

**Comment by leviding** [comment]
@pkuwwt 本文还没翻译完，翻译完在对应 pull request 下进行校对认领。
