### ISSUE TITLE
Vectors For All (almost)

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#332]
原文链接：[Vectors For All (almost)](https://blog.stylingandroid.com/vectors-for-all-almost/)
掘金链接：[Vectors For All (almost)](http://gold.xitu.io/entry/57306cf52e958a0066a30f69)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/vectors-for-all-almost.md)
校对[地址](https://github.com/xitu/gold-miner/pull/346)
翻译时间：5天
校对时间：3天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by edvardHua** [comment]
@antonia0912 羊哥，羊哥。 我来认领翻译！

**Comment by antonia0912** [comment]
@edvardHua 好的  等你PR

**Comment by antonia0912** [comment]
@edvardHua markdown文件已经添加啦

**Comment by edvardHua** [comment]
@antonia0912 好的。

**Comment by edvardHua** [comment]
@antonia0912 翻译完成，校对[地址](https://github.com/xitu/gold-miner/pull/346)

**Comment by SatanWoo** [comment]
认领校对

**Comment by antonia0912** [comment]
@SatanWoo 收到

**Comment by SatanWoo** [comment]
校对完啦

**Comment by SatanWoo** [comment]
@antonia0912

**Comment by joddiy** [comment]
看起来这个issue时间很久了，校对 + 1
