### ISSUE TITLE
产品设计的环状循环

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3322]
* 原文链接：[The Circle of Product Design](https://blog.prototypr.io/the-circle-of-product-design-6c78ade2010e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-circle-of-product-design.md)
  * PR 地址：#3347
  * 文章分类：**设计**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rydensun** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@rydensun 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3347
