### ISSUE TITLE
Android 上为什么 Canvas 画出的形状不够平滑

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#333]
原文链接：[Android: Why your Canvas shapes aren’t smooth](https://medium.com/@ali.muzaffar/android-why-your-canvas-shapes-arent-smooth-aa2a3f450eb5#.p3w0sj7cf)
掘金链接：[Android 上为什么 Canvas 画出的形状不够平滑](http://gold.xitu.io/entry/572f3ba41ea4930064e3b925)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/android-why-your-canvas-shapes-arent-smooth.md)
PR地址：https://github.com/xitu/gold-miner/pull/341
翻译时间：5天
校对时间：3天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Sausure** [comment]
认领哈

**Comment by antonia0912** [comment]
@Sausure OK markdown 文件已经添加好了

**Comment by Sausure** [comment]
已 PR，申请校对，地址：https://github.com/xitu/gold-miner/pull/341

**Comment by lovexiaov** [comment]
校对认领

**Comment by antonia0912** [comment]
@lovexiaov 收到~老样子校对就可以了

**Comment by joddiy** [comment]
校对+1

**Comment by antonia0912** [comment]
@joddiy 好的 [校对地址](https://github.com/xitu/gold-miner/pull/341/files?diff=split)

**Comment by lovexiaov** [comment]
@antonia0912 校对完成啦
