### ISSUE TITLE
2018 如何玩转 JavaScript

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3334]
* 原文链接：[How to JavaScript in 2018](https://www.telerik.com/blogs/how-to-javascript-in-2018)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-javascript-in-2018.md)
  * PR 地址：#3390
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@jonjia 你的

**Comment by llp0574** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@llp0574 棒极啦 :tada:

**Comment by llp0574** [comment]
@leviding 周末有点事情耽误了一下，申请延期一两天提交

**Comment by leviding** [comment]
@llp0574 ok

**Comment by fanyijihua** [comment]
PR 地址：#3390
