### ISSUE TITLE
Typescript : 类 vs 接口

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3335]
* 原文链接：[Typescript : class vs interface](https://medium.com/front-end-hacking/typescript-class-vs-interface-99c0ae1c2136)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/typescript-class-vs-interface.md)
  * PR 地址：#3375
  * 文章分类：**前端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xueshuai** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@xueshuai 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3375
