### ISSUE TITLE
使用 MODEL-VIEW-INTENT 第四部分 — 独立 UI 组件

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3336]
* 原文链接：[REACTIVE APPS WITH MODEL-VIEW-INTENT - PART4 - INDEPENDENT UI COMPONENTS](http://hannesdorfmann.com/android/mosby3-mvi-4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/mosby3-mvi-4.md)
  * PR 地址：#3361
  * 文章分类：**Android**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pcdack** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@pcdack 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3361
