### ISSUE TITLE
为 Python Web 应用编写 Dockerfiles

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3339]
* 原文链接：[How to write Dockerfiles for Python Web Apps](https://blog.hasura.io/how-to-write-dockerfiles-for-python-web-apps-6d173842ae1d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-write-dockerfiles-for-python-web-apps.md)
  * PR 地址：#3415
  * 文章分类：**后端**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3415
