### ISSUE TITLE
用户领域 API 监控和代码注入检测

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3341]
* 原文链接：[Userland API Monitoring and Code Injection Detection](https://0x00sec.org/t/userland-api-monitoring-and-code-injection-detection/5565)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/userland-api-monitoring-and-code-injection-detection.md)
  * PR 地址：#3562
  * 文章分类：**安全**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：2 天
  * 翻译积分：11 分
  * 校对积分：4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Xekin-FE** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@Xekin-FE 棒极啦 :tada:

**Comment by Starriers** [comment]
校对认领

**Comment by leviding** [comment]
@Starriers ok
