### ISSUE TITLE
测试 React & Redux 应用真实引导

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3342]
* 原文链接：[Genuine guide to testing React & Redux applications](https://blog.pragmatists.com/genuine-guide-to-testing-react-redux-applications-6f3265c11f63)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/genuine-guide-to-testing-react-redux-applications.md)
  * PR 地址：#3370
  * 文章分类：**前端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@jonjia 你的

**Comment by jonjia** [comment]
翻译认领

**Comment by leviding** [comment]
@jonjia ok

**Comment by fanyijihua** [comment]
PR 地址：#3370
