### ISSUE TITLE
为你的 React 应用制作 SVG 图标库

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3343]
* 原文链接：[Making SVG icon libraries for React apps](http://nicolasgallagher.com/making-svg-icon-libraries-for-react-apps/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/making-svg-icon-libraries-for-react-apps)
  * PR 地址：#3364
  * 文章分类：**前端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Albertao** [comment]
@leviding @fanyijihua 翻译认领

**Comment by fanyijihua** [comment]
@Albertao 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3364
