### ISSUE TITLE
Python 是解决任何问题的完美工具

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3346]
* 原文链接：[Python is the Perfect Tool for any Problem](https://towardsdatascience.com/python-is-the-perfect-tool-for-any-problem-f2ba42889a85)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/python-is-the-perfect-tool-for-any-problem.md)
  * PR 地址：#3356
  * 文章分类：**后端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rydensun** [comment]
@leviding  @fanyijihua  翻译认领

**Comment by fanyijihua** [comment]
@rydensun 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3356
