### ISSUE TITLE
设计研究的 9 条规则

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3348]
* 原文链接：[The 9 Rules of Design Research](https://medium.com/mule-design/the-9-rules-of-design-research-1a273fdd1d3b?ref=uxdesignweekly)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-9-rules-of-design-research.md)
  * PR 地址：#3406
  * 文章分类：**设计**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5.5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhmhhu** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@zhmhhu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3406
