### ISSUE TITLE
Express.js 与 AWS Lambda  —  一场关于 serverless 的爱情故事

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3349]
* 原文链接：[Express.js and AWS Lambda — a serverless love story](https://medium.freecodecamp.org/express-js-and-aws-lambda-a-serverless-love-story-7c77ba0eaa35)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/express-js-and-aws-lambda-a-serverless-love-story.md)
  * PR 地址：#3368
  * 文章分类：**后端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4.5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lcx-seima** [comment]
认领本篇翻译。（日常工作中也做 Node.js 后端）

**Comment by leviding** [comment]
@lcx-seima ok，下次可以用关键词 `翻译认领` 或 `认领翻译` 进行文章认领。

**Comment by fanyijihua** [comment]
PR 地址：#3368
