### ISSUE TITLE
Flutter — 五个你会爱上它的原因

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3350]
* 原文链接：[Flutter — 5 reasons why you may love it](https://hackernoon.com/flutter-5-reasons-why-you-may-love-it-55021fdbf1aa)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/flutter-5-reasons-why-you-may-love-it.md)
  * PR 地址：#3369
  * 文章分类：**Android**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rockzhai** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@rockzhai 棒极啦 :tada:

**Comment by Starriers** [comment]
校对认领
