### ISSUE TITLE
如何在中国使用 Flutter

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3363]
* 原文链接：[Using Flutter in China](https://github.com/flutter/flutter/wiki/Using-Flutter-in-China)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/Using-Flutter-in-China.md)
  * PR 地址：#3371
  * 文章分类：**Android**
  ----
  * 翻译时间：1 天
  * 校对时间：1 天
  * 翻译积分：1.5 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@mysterytony

**Comment by mysterytony** [comment]
翻译认领

**Comment by leviding** [comment]
@mysterytony ok

**Comment by fanyijihua** [comment]
PR 地址：#3371
