### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by rpgmakervx** [xitu/gold-miner#3374]
- 原文链接：https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html
- 简要介绍：这是Elasticsearch官方文档参考说明，elasticsearch是一款高性能可扩展高可用的近实时搜索分析引擎。调查过此前有人翻译过User Guide权威指南，但是此篇翻译的很少，没有完整翻译过的。我使用该引擎半年有余，算不上专业但为了加深学习希望翻译此文。简书上有部分我翻译的内容：https://www.jianshu.com/p/64a49f841101

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by rpgmakervx** [comment]
请问校对这块，我只需要在Pull Request下留言文章中不合理处即可实现校对吗？目前的PullRequest很少但是文章很多的样子，没有我想要校对的文章怎么办呢

**Comment by rpgmakervx** [comment]
我已经参与过校对了，请问什么时候我能够开始译文工作呢？@fanyijihua  @leviding

**Comment by leviding** [comment]
@rpgmakervx 再看到想翻译的文章就可以认领了

**Comment by rpgmakervx** [comment]
那我想翻译我自己推荐的文章，不会被别人领了吗？而且我想知道我推荐的文章大概多久会出现在pull request里面呢？

**Comment by leviding** [comment]
这个直接和我微信说就行，说明下想翻译自己推荐的这篇，我就马上推上去给你翻译了。
微信：517010193
