### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by razertory** [xitu/gold-miner#3377]
* 原文链接：https://medium.com/@zavilla90/best-practices-in-designing-graphql-apis-395225bdcd1
* 简要介绍：我司已用GraphQL超过半年了，多数的客户端请求也都通过我们的GraphQL服务器。这里推荐一个GraphQL替代了Rest之后的Best Practice

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@razertory 感谢推荐，一会儿发布
