### ISSUE TITLE
关于 CSS 变量，你需要了解的一切

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3378]
* 原文链接：[Everything you need to know about CSS Variables](https://medium.freecodecamp.org/everything-you-need-to-know-about-css-variables-c74d922ea855)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/everything-you-need-to-know-about-css-variables.md)
  * PR 地址：#3474
  * 文章分类：**前端**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：10 分
  * 校对积分：3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MechanicianW** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MechanicianW 棒极啦 :tada:

**Comment by MechanicianW** [comment]
@leviding 文章太长了，进度 delay，目前翻译完成 70%，周末结束前会提 PR

**Comment by leviding** [comment]
收到

**Comment by fanyijihua** [comment]
PR 地址：#3474
