### ISSUE TITLE
function.caller 被认为是有害的

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3379]
* 原文链接：[function.caller considered harmful](https://medium.com/@bmeurer/function-caller-considered-harmful-45f06916c907)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/function-caller-considered-harmful.md)
  * PR 地址：#3393
  * 文章分类：**前端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yankwan** [comment]
@leviding 申请翻译

**Comment by fanyijihua** [comment]
@yankwan 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3393
