### ISSUE TITLE
Vectors For All (slight return)

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#338]
原文链接：[Vectors For All (slight return)](https://blog.stylingandroid.com/vectors-for-all-slight-return/)
掘金链接：[[英] Vectors For All (slight return)](http://gold.xitu.io/entry/57319d69c4c9710060d6c1a3)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/vectors-for-all-slight-return.md)
PR地址：#351
翻译时间：4天
校对时间：3天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by huanglizhuo** [comment]
@antonia0912  wo lai

**Comment by antonia0912** [comment]
@huanglizhuo ok

**Comment by huanglizhuo** [comment]
完成 vectors-for-all-slight-return #351 @antonia0912

**Comment by antonia0912** [comment]
@huanglizhuo 收到，我来联系校对者

**Comment by edvardHua** [comment]
@antonia0912 我来校对啦。

**Comment by antonia0912** [comment]
@edvardHua 收到~

**Comment by edvardHua** [comment]
@antonia0912 羊哥，校对完成~

**Comment by antonia0912** [comment]
@edvardHua 收到

**Comment by circlelove** [comment]
@antonia0912  完成
