### ISSUE TITLE
做好准备：新的 V8 即将到来，Node.js 的性能正在改变。

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3380]
* 原文链接：[GET READY: A NEW V8 IS COMING, NODE.JS PERFORMANCE IS CHANGING.](https://medium.com/the-node-js-collection/get-ready-a-new-v8-is-coming-node-js-performance-is-changing-46a63d6da4de)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/get-ready-a-new-v8-is-coming-node-js-performance-is-changing.md)
  * PR 地址：#3438
  * 文章分类：**前端**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：10 分
  * 校对积分：3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3435

**Comment by fanyijihua** [comment]
PR 地址：#3438
