### ISSUE TITLE
这可能是 2018 年最好的一篇 PHP 性能测评（包含 5.6 到 7.2，以及HHVM）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3381]
* 原文链接：[The Definitive PHP 5.6, 7.0, 7.1, 7.2 & HHVM Benchmarks (2018)](https://kinsta.com/blog/php-7-hhvm-benchmarks/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/php-7-hhvm-benchmarks.md)
  * PR 地址：#3434
  * 文章分类：**后端**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Albertao** [comment]
@leviding @fanyijihua 翻译认领

**Comment by fanyijihua** [comment]
PR 地址：#3434
