### ISSUE TITLE
Vectors For All (finally)

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#339]
原文链接：[Vectors For All (finally)](https://blog.stylingandroid.com/vectors-for-all-finally/)
掘金链接：[[英] Vectors For All (finally)](http://gold.xitu.io/entry/5731b42f2e958a0066af97eb)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/vectors-for-all-finally.md)

翻译时间：4天
校对时间：3天
翻译积分：5
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by laobie** [comment]
认领@antonia0912

**Comment by antonia0912** [comment]
@laobie OK
