### ISSUE TITLE
使用 MVI 编写响应式 APP — 第 5 部分 — 简单的调试

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3394]
* 原文链接：[REACTIVE APPS WITH MODEL-VIEW-INTENT - PART5 - DEBUGGING WITH EASE](http://hannesdorfmann.com/android/mosby3-mvi-5)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/mosby3-mvi-5.md)
  * PR 地址：#3414
  * 文章分类：**Android**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pcdack** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@pcdack 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3414
