### ISSUE TITLE
GraphQL API 设计最佳实践

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3395]
* 原文链接：[Best Practices in Designing GraphQL APIs](https://medium.com/@zavilla90/best-practices-in-designing-graphql-apis-395225bdcd1)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/best-practices-in-designing-graphql-apis.md)
  * PR 地址：#3410
  * 文章分类：**后端**
  ----
  * 翻译时间：1 天
  * 校对时间：1 天
  * 翻译积分：1.5 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by AceLeeWinnie** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@AceLeeWinnie 棒极啦 :tada:

**Comment by AceLeeWinnie** [comment]
翻译完成 #3410

**Comment by goldEli** [comment]
校对认领
