### ISSUE TITLE
用 Flutter 开发你的第一个应用程序

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3396]
* 原文链接：[Develop your first Application with Flutter](https://hackernoon.com/develop-your-first-application-with-flutter-60c4308d18b7)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/develop-your-first-application-with-flutter.md)
  * PR 地址：#3417
  * 文章分类：**Android**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mysterytony** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@mysterytony 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3417
