### ISSUE TITLE
让 Apache Cassandra 尾部延迟减小 10 倍（已开源）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3397]
* 原文链接：[Open-sourcing a 10x reduction in Apache Cassandra tail latency](https://engineering.instagram.com/open-sourcing-a-10x-reduction-in-apache-cassandra-tail-latency-d64f86b43589)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/open-sourcing-a-10x-reduction-in-apache-cassandra-tail-latency.md)
  * PR 地址：#3546
  * 文章分类：**开源**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 + 1 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by stormluke** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@stormluke 棒极啦 :tada:
