### ISSUE TITLE
使用 python 和 keras 实现卷积神经网络

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3398]
* 原文链接：[Implementation of Convolutional Neural Network using Python and Keras](https://rubikscode.net/2018/03/05/implementation-of-convolutional-neural-network-using-python-and-keras/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/implementation-of-convolutional-neural-network-using-python-and-keras.md)
  * PR 地址：#3744
  * 文章分类：**后端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4.5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnJiangLA** [comment]
翻译认领 @leviding

**Comment by leviding** [comment]
@JohnJiangLA 这篇还记得吗

**Comment by leviding** [comment]
@JohnJiangLA 这篇翻译的怎么样了 😆

**Comment by fanyijihua** [comment]
PR 地址：#3744
