### ISSUE TITLE
认领 Retrofit 入门教程

### ISSUE THREAD

**Issue by huanglizhuo** [xitu/gold-miner#34]

**Comment by huanglizhuo** [comment]
之前有自己翻译 kotlin 官方文档  以及android training course in chinese

**Comment by kassadin** [comment]
#25

**Comment by huanglizhuo** [comment]
sorry 没注意到

**Comment by Glowin** [comment]
@huanglizhuo 你好，这篇文章已经被 @kassadin 认领了，麻烦你看看其他的文章，非常感谢你的理解。

**Comment by huanglizhuo** [comment]
恩知道了 谢谢

> On Dec 26 2015, at 2:54 pm, Glow Chiang &lt;notifications@github.com&gt;
wrote:  

>

> Closed [#34](https://github.com/xitu/gold-miner/issues/34).

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/xitu
/gold-miner/issues/34#event-500662478).![](https://github.com/notifications/be
acon/ADseFMs75fqu4NN4J6jG9u6jTECcfhoNks5pTjExgaJpZM4G7VOR.gif)
