### ISSUE TITLE
使用 Web3 和 Vue.js 来创建你的第一个以太坊 dAPP（第一部分）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3404]
* 原文链接：[Create your first Ethereum dAPP with Web3 and Vue.JS (Part 1)](https://itnext.io/create-your-first-ethereum-dapp-with-web3-and-vue-js-c7221af1ed82)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/create-your-first-ethereum-dapp-with-web3-and-vue-js.md)
  * PR 地址：#3407
  * 文章分类：**区块链**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by foxxnuaa** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@foxxnuaa 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3407
