### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by ClarenceC** [xitu/gold-miner#3413]
- 原文链接：https://air.ghost.io/js-things-i-never-knew-existed/
- 简要介绍：主要是介绍 JS 一些不为大家熟悉的小功能
自己翻译

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@ClarenceC 这一篇，网上已经有译文了，推荐之前可以先查查 http://zcfy.baomitu.com/article/js-things-i-never-knew-existed-4854.html

**Comment by ClarenceC** [comment]
@leviding  哦如果其它地方有译文，我们这边就不能翻译了是么。

**Comment by leviding** [comment]
@ClarenceC 对的，不做重复劳动。
