### ISSUE TITLE
iOS App 上一种灵活的路由方式

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3419]
* 原文链接：[A Flexible Routing Approach in an iOS App](https://medium.com/rosberryapps/the-flexible-routing-approach-in-an-ios-app-eb4b05aa7f52)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-flexible-routing-approach-in-an-ios-app.md)
  * PR 地址：#3436
  * 文章分类：**iOS**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@YinTokey

**Comment by YinTokey** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@YinTokey 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3436
