### ISSUE TITLE
拖放库中 React 性能的优化

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3420]
* 原文链接：[Dragging React performance forward](https://medium.com/@alexandereardon/dragging-react-performance-forward-688b30d40a33)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/dragging-react-performance-forward.md)
  * PR 地址：#3437
  * 文章分类：**前端**
  ----
  * 翻译时间：9 天
  * 校对时间：3 天
  * 翻译积分：9 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hexianga** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@hexianga 棒极啦 :tada:
