### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by yankwan** [xitu/gold-miner#3424]
- 原文链接：[https://jsblog.insiderattack.net/event-loop-and-the-big-picture-nodejs-event-loop-part-1-1cb67a182810](https://jsblog.insiderattack.net/event-loop-and-the-big-picture-nodejs-event-loop-part-1-1cb67a182810)
- 简要介绍：目前看到讲解JavaScript event loop 最详细的文章，该篇是该系列的第一篇。希望由本人自己翻译。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@yankwan 网上查查，这一篇已经有译文了呢
