### ISSUE TITLE
TypeScript：拥有超能力的 JavaScript（下）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3425]
* 原文链接：[TypeScript — JavaScript with superpowers — Part II](https://medium.com/@wesharehoodies/typescript-javascript-with-superpowers-part-ii-69a6bd2c6842)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/typescript-javascript-with-superpowers-part-ii.md)
  * PR 地址：#3478
  * 文章分类：**前端**
  ----
  * 翻译时间：1 天
  * 校对时间：1 天
  * 翻译积分：1.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@jonjia

**Comment by jonjia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jonjia 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3478
