### ISSUE TITLE
斐波那契数列中的偶数（Python vs. JavaScript）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3426]
* 原文链接：[Even Fibonacci numbers (Python vs. JavaScript)](https://hackernoon.com/even-fibonacci-numbers-python-vs-javascript-55590ccb2fd6)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/even-fibonacci-numbers-python-vs-javascript.md)
  * PR 地址：#3433
  * 文章分类：**算法**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zephyrJS** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@zephyrJS 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3433
