### ISSUE TITLE
JanusGraph 为 PHP 助力

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3428]
* 原文链接：[Powering PHP With JanusGraph](https://compose.com/articles/powering-php-with-janusgraph/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/powering-php-with-janusgraph.md)
  * PR 地址：#3514
  * 文章分类：**后端**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by GanymedeNil** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@GanymedeNil 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3514
