### ISSUE TITLE
用 Python 做一个 H5 游戏机器人

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3429]
* 原文链接：[Creating An HTML5 Game Bot Using Python](https://vesche.github.io/articles/01-stabbybot.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/creating-an-html5-game-bot-using-python.md)
  * PR 地址：#3443
  * 文章分类：**后端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4.5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3443
