### ISSUE TITLE
Data Pre-Processing in Python: How I learned to love parallelized applies with Dask and Numba

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3430]
* 原文链接：[Data Pre-Processing in Python: How I learned to love parallelized applies with Dask and Numba](https://medium.com/@ernestk.social/how-i-learned-to-love-parallelized-applies-with-python-pandas-dask-and-numba-f06b0b367138)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-i-learned-to-love-parallelized-applies-with-python-pandas-dask-and-numba)
  * PR 地址：#
  * 文章分类：**后端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by leviding** [comment]
@lsvih 这篇翻译的怎么样了 😆

**Comment by lsvih** [comment]
@leviding 实在抱歉，这篇完全忘了......争取明天内弄完

**Comment by leviding** [comment]
@lsvih 本周内就行

**Comment by lsvih** [comment]
@leviding 
今天读到了这篇：https://zhuanlan.zhihu.com/p/34471271

Give up..

**Comment by leviding** [comment]
@lsvih get
