### ISSUE TITLE
为 JavaScript 程序员准备的 Flutter 指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3431]
* 原文链接：[Flutter for JavaScript Developers](https://hackernoon.com/flutter-for-javascript-developers-35515e533317)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/flutter-for-javascript-developers.md)
  * PR 地址：#3563
  * 文章分类：**Android**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by lsvih** [comment]
@leviding 这篇明天完成

**Comment by fanyijihua** [comment]
PR 地址：#3563
