### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by rydensun** [xitu/gold-miner#3441]
原文链接：https://blog.zeplin.io/life-without-interface-builder-adbb009d2068
简要介绍：客户端开发与设计师交互神器 Zeplin团队的文章， 讨论的也是iOS开发届很具争议的一个问题
：使用纯代码开发还是IB/Storyboard开发。 从多个角度 解释了 他们团队在开发Zeplin客户端的时候， 为什么使用了纯代码开发的方式。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by rydensun** [comment]
申请翻译
