### ISSUE TITLE
Google Play 控制台指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3442]
* 原文链接：[A guide to the Google Play Console](https://medium.com/googleplaydev/a-guide-to-the-google-play-console-1bdc79ca956f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-guide-to-the-google-play-console.md)
  * PR 地址：#3475
  * 文章分类：**Android**
  **本文为 Google 约稿，由他们发布。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：12 分
  * 校对积分：4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JayZhaoBoy** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@JayZhaoBoy 棒极啦 :tada:

**Comment by JayZhaoBoy** [comment]
@leviding  这翻译积分没写错吗

**Comment by leviding** [comment]
@JayZhaoBoy 写错了，现在更新了，这篇文章是 Google 约稿，需要本周完成，最晚周日提交哈

**Comment by JayZhaoBoy** [comment]
好的 @leviding

**Comment by leviding** [comment]
@JayZhaoBoy 这篇翻译的怎么样啦

**Comment by JayZhaoBoy** [comment]
@leviding 完成了，实在是长啊，好几个词抠了很久都找不到合适的中文词😂

**Comment by leviding** [comment]
@JayZhaoBoy 哈哈哈，辛苦啦
