### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by goldEli** [xitu/gold-miner#3444]
原文链接：https://medium.freecodecamp.org/what-i-learned-from-reading-the-redux-source-code-836793a48768
简要介绍：通过学习 Redux 的源码，学会如何阅读源码，以及为什么要阅读源码

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by goldEli** [comment]
@leviding 我想翻译这篇文章，请@我哈 (^_^)!

**Comment by leviding** [comment]
好的哈
