### ISSUE TITLE
没有 Interface Builder 的生活

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3445]
* 原文链接：[Life without Interface Builder](https://blog.zeplin.io/life-without-interface-builder-adbb009d2068)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/life-without-interface-builder.md)
  * PR 地址：#3461
  * 文章分类：**iOS**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@rydensun

**Comment by rydensun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@rydensun 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3461
