### ISSUE TITLE
我们能从 Redux 源码中学到什么？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3446]
* 原文链接：[What I learned from reading the Redux source code](https://medium.freecodecamp.org/what-i-learned-from-reading-the-redux-source-code-836793a48768)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-i-learned-from-reading-the-redux-source-code.md)
  * PR 地址：#3464
  * 文章分类：**前端**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@goldEli

**Comment by goldEli** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@goldEli 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3464
