### ISSUE TITLE
写给前端开发者的 GraphQL 指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3447]
* 原文链接：[A Front End Developer’s Guide to GraphQL](https://css-tricks.com/front-end-developers-guide-graphql/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/front-end-developers-guide-graphql.md)
  * PR 地址：#3470
  * 文章分类：**前端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ellcyyang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ellcyyang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3470
