### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Zheaoli** [xitu/gold-miner#345]
自我介绍:目前主攻方向Python服务器及爬虫数据开发,同时有较为良好的计算机修养,对iOS感兴趣,掌握常用数据结构及算法
想翻译的类型:Python开发相关,分布式处理相关,iOS开发相关

**Comment by antonia0912** [comment]
@Zheaoli 请加我微信 antonia0912 备注 github ID 我来拉你进译者群
