### ISSUE TITLE
Reducers VS Transducers

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3465]
* 原文链接：[Reducers VS Transducers](http://maksimivanov.com/posts/reducers-vs-transducers)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/reducers-vs-transducers.md)
  * PR 地址：#3510
  * 文章分类：**前端**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@jonjia

**Comment by jonjia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jonjia 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3510
