### ISSUE TITLE
使用 React、Redux、SVG 开发游戏 - Part 1

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3466]
* 原文链接：[Developing Games with React, Redux, and SVG - Part 1](https://auth0.com/blog/developing-games-with-react-redux-and-svg-part-1/?utm_source=mybridge&utm_medium=blog&utm_campaign=read_more)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/developing-games-with-react-redux-and-svg-part-1.md)
  * PR 地址：#3518
  * 文章分类：**前端**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@zephyrJS

**Comment by zephyrJS** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@zephyrJS 棒极啦 :tada:
