### ISSUE TITLE
使用 Web3 和 Vue.js 来创建你的第一个以太坊 dAPP（第三部分）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3472]
* 原文链接：[Create your first Ethereum dAPP with Web3 and Vue.JS (Part 3)](https://itnext.io/create-your-first-ethereum-dapp-with-web3-and-vue-js-part-3-dc4f82fba4b4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/create-your-first-ethereum-dapp-with-web3-and-vue-js-part-3.md)
  * PR 地址：#3548
  * 文章分类：**区块链**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sakila1012** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@sakila1012 棒极啦 :tada:

**Comment by leviding** [comment]
@sakila1012 PR 有问题，重新开吧

**Comment by leviding** [comment]
记得 resolve 到这个 issue

**Comment by sakila1012** [comment]
@leviding 已经重新 PR了
