### ISSUE TITLE
这里的翻译有错误反馈机制吗？看到翻的错误的想提修改怎么办

### ISSUE THREAD

**Issue by Medildley** [xitu/gold-miner#3483]
The System Design Primer这篇才看了开头，就看到2，3处不通顺的地方

a high level design 翻译成高级的设计

given the constraints 翻译成以及一些限制

Back-of-the-envelope calculations 翻译成信封背面的计算

读的感觉明显的不通顺，我去翻原文才发现问题，感觉明显译者没有程序员背景，还有明显的语法错误

说实话，我才看了10分之1都没有，这错误也太密集了，完全曲解了原文的意思。

这个计划的出发点是好事，但是希望能把好质量关；

看到错误很想提交修改意见，不知道有通道吗？

**Comment by leviding** [comment]
@Medildley 你好，感谢你的 issue，有反馈机制的，只是没在 wiki 里写明，那近期我会在 wiki 里增加一项关于错误修改机制的说明。

您现在如果发现某篇文章出现明显错误，可以 fork 翻译计划的 repo，找到对应文章进行修改，然后通过 pull request 的方式提交过来即可。

我们也会通知到对应的译者和校对者作相应处理，感谢您的提议。

**Comment by leviding** [comment]
@Medildley 你好，有任何问题欢迎加微信 517010193，更方便沟通。如果您感兴趣，也欢迎您加入掘金翻译计划。

在译文质量把控上，首先是负责人的翻译者进行翻译，接下来是校对者对文章进行 review，最后管理员负责格式等整体审核的相关问题。最后一个层次就是读者发现问题来进行反馈和修改，并对相应的译者和校对者做处理。
