### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by fghpdf** [xitu/gold-miner#3485]
原文地址: [https://raygun.com/blog/javascript-unit-testing-frameworks/](https://raygun.com/blog/javascript-unit-testing-frameworks/)
简要描述：JavaScript 流行单元测试框架比较

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
收到，明天放上去
