### ISSUE TITLE
推荐网络安全博文

### ISSUE THREAD

**Issue by vsTianhao** [xitu/gold-miner#3489]
https://codahale.com/a-lesson-in-timing-attacks/
https://codahale.com/how-to-safely-store-a-password/

十分感谢

**Comment by leviding** [comment]
@vsTianhao 感谢推荐，本周末发布一下。

**Comment by leviding** [comment]
文章仔细看了下，内容咱是不是太适合呢，欢迎有更多的优秀文章推荐过来。
