### ISSUE TITLE
Web 爬虫下的 Python 数据分析：中情局全球概况图解

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3495]
* 原文链接：[Data Analytics with Python by Web scraping: Illustration with CIA World Factbook](https://towardsdatascience.com/data-analytics-with-python-by-web-scraping-illustration-with-cia-world-factbook-abbdaa687a84)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/data-analytics-with-python-by-web-scraping-illustration-with-cia-world-factbook.md)
  * PR 地址：#3520
  * 文章分类：**后端**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@Starriers

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3519

**Comment by fanyijihua** [comment]
PR 地址：#3520
