### ISSUE TITLE
Redux-Saga 为你打 call：管理你的异步 action （上）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3496]
* 原文链接：[Don’t call me, I’ll call you: Side effects management with Redux-Saga (Part 1)](https://medium.com/appsflyer/dont-call-me-i-ll-call-you-side-effects-management-with-redux-saga-part-1-d0a92c3f81be)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/dont-call-me-i-ll-call-you-side-effects-management-with-redux-saga-part-1.md)
  * PR 地址：#3552
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@jonjia

**Comment by jonjia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jonjia 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3552
