### ISSUE TITLE
React 的内联函数和性能

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3497]
* 原文链接：[React, Inline Functions, and Performance](https://cdb.reacttraining.com/react-inline-functions-and-performance-bdff784f5578)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/react-inline-functions-and-performance.md)
  * PR 地址：#3537
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@wznonstop

**Comment by wznonstop** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@wznonstop 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3537
