### ISSUE TITLE
让我们来简化 UserDefaults 的使用

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3498]
* 原文链接：[Let’s Simplify the Work with UserDefaults](https://medium.com/rosberryapps/lets-simplify-the-work-with-userdefaults-93d142d47741)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/lets-simplify-the-work-with-userdefaults.md)
  * PR 地址：#3508
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：1 天
  * 校对时间：1 天
  * 翻译积分：1.5 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@RickeyBoy

**Comment by talisk** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@talisk 棒极啦 :tada:
