### ISSUE TITLE
热爱 JavaScript，但是讨厌 CSS？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3499]
* 原文链接：[Love JavaScript, but hate CSS?](https://daveceddia.com/love-js-hate-css/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/love-js-hate-css.md)
  * PR 地址：#3511
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4.5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by allenlongbaobao** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@allenlongbaobao 棒极啦 :tada:
