### ISSUE TITLE
How to NOT React：React 中常见的反模式与陷阱

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3500]
* 原文链接：[How to NOT React: Common Anti-Patterns and Gotchas in React](https://codeburst.io/how-to-not-react-common-anti-patterns-and-gotchas-in-react-40141fe0dcd)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-not-react-common-anti-patterns-and-gotchas-in-react.md)
  * PR 地址：#3557
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MechanicianW** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MechanicianW 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3557
