### ISSUE TITLE
深入浅出 JavaScript 关键词 — this

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3501]
* 原文链接：[Mastering JavaScript this Keyword – Detailed Guide](https://www.thecodingdelight.com/javascript-this/#ftoc-heading-2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/mastering-javascript-this-keyword-detailed-guide.md)
  * PR 地址：#3715
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by weberpan** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@weberpan 棒极啦 :tada:

**Comment by leviding** [comment]
@weberpan 这篇怎么样啦

**Comment by weberpan** [comment]
@leviding 前两天在微信上和你单聊了哈，最近太忙，需要延些时间，清明赶一赶

**Comment by leviding** [comment]
@weberpan 喔喔，忘了，好的哈，不急，我就是例行看一遍。按照你的时间来就行啦~

**Comment by leviding** [comment]
@weberpan 这篇还记得吗，翻译的怎么样了 😆

**Comment by fanyijihua** [comment]
PR 地址：#3715

**Comment by weberpan** [comment]
@leviding 一直都记得，这次是拖了有点久，但这一个多月每天11点下班回来抽点时间翻译，也请理解哈

**Comment by leviding** [comment]
@weberpan 嗯嗯，很赞 😁
