### ISSUE TITLE
良好的编码习惯 — 5 个提高代码质量的技巧

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3506]
* 原文链接：[Good Coding Practices – Five Tips to Enhance Code Quality](https://www.thecodingdelight.com/good-coding-practices-tips-enhance-code-quality/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/good-coding-practices-tips-enhance-code-quality.md)
  * PR 地址：#3531
  * 文章分类：**教程**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by NeoyeElf** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@NeoyeElf 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3531
