### ISSUE TITLE
怎样用 JRebel 启动 Android

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#352]
原文链接：[Getting started with JRebel for Android](https://medium.com/@shelajev/getting-started-with-jrebel-for-android-426633cde736#.dtldka9ua)
掘金链接：[怎样用 JRebel 启动 Android](http://gold.xitu.io/entry/5739a72b79df5400601dc2f3)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/getting-started-with-jrebel-for-android.md)

翻译时间：5天
校对时间：3天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by edvardHua** [comment]
认领~

**Comment by antonia0912** [comment]
@edvardHua 好哒~

**Comment by edvardHua** [comment]
@antonia0912 羊哥，完成翻译~

校对[地址](https://github.com/xitu/gold-miner/pull/378/commits/b1d3c8ef0bd5d818009041d674f990776df9e007)

**Comment by circlelove** [comment]
认校对

**Comment by DeadLion** [comment]
认领校对 @antonia0912

**Comment by antonia0912** [comment]
@circlelove @DeadLion 收到~ [校对地址](https://github.com/xitu/gold-miner/pull/378/files?diff=split)

**Comment by DeadLion** [comment]
@antonia0912 校对完成

**Comment by antonia0912** [comment]
@DeadLion 辛苦啦~

**Comment by antonia0912** [comment]
@circlelove 赶快来校对呀~另一位校对者已经校对完啦

**Comment by circlelove** [comment]
嗯嗯我知道了，这两天被老师吊打来着 @antonia0912

**Comment by circlelove** [comment]
@antonia0912  迟到完成校对
