### ISSUE TITLE
简短而又完全精确的编程语言历史

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3524]
* 原文链接：[A Brief Totally Accurate History Of Programming Languages](https://medium.com/@caspervonb/a-brief-totally-accurate-history-of-programming-languages-cd93ec806124)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-brief-totally-accurate-history-of-programming-languages.md)
  * PR 地址：#3542
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3542
