### ISSUE TITLE
使用MVI构建响应式 APP — 第七部分 — TIMING (SINGLELIVEEVENT 问题)

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3530]
* 原文链接：[REACTIVE APPS WITH MODEL-VIEW-INTENT - PART7 - TIMING (SINGLELIVEEVENT PROBLEM)](http://hannesdorfmann.com/android/mosby3-mvi-7)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/mosby3-mvi-7.md)
  * PR 地址：#3550
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@pcdack

**Comment by pcdack** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pcdack 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3550
