### ISSUE TITLE
使用 React、Redux 和 SVG 开发游戏 - Part 2

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3539]
* 原文链接：[Developing Games with React, Redux, and SVG - Part 2](https://auth0.com/blog/developing-games-with-react-redux-and-svg-part-2/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/developing-games-with-react-redux-and-svg-part-2.md)
  * PR 地址：#3594
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@zephyrJS

**Comment by zephyrJS** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@zephyrJS 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3594
