### ISSUE TITLE
如何在移动 APP 中设计输入框

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#354]
原文链接：[Text Fields in Mobile App](https://uxplanet.org/text-fields-in-mobile-app-11d41f13e31#.pjomtd59r)
掘金链接：[如何在移动 APP 中设计输入框](http://gold.xitu.io/entry/573a7c681ea4930060fbe102)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/text-fields-in-mobile-app.md)

翻译时间：6天
校对时间：4天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zhangjd** [comment]
认领

**Comment by antonia0912** [comment]
@Zhangjd markdown 文件已经添加啦 可以翻译了

**Comment by Velacielad** [comment]
认领校对

**Comment by antonia0912** [comment]
@Velacielad 好的 [校对地址](https://github.com/xitu/gold-miner/pull/364/files?diff=split)

**Comment by DeadLion** [comment]
认领校对 @antonia0912

**Comment by antonia0912** [comment]
@DeadLion 好的 [校对地址](https://github.com/xitu/gold-miner/pull/364/files?diff=split)
