### ISSUE TITLE
React & Redux 顶级开发伴侣

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3540]
* 原文链接：[Top React and Redux Packages for Faster Development](https://codeburst.io/top-react-and-redux-packages-for-faster-development-5fa0ace42fe7)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/top-react-and-redux-packages-for-faster-development.md)
  * PR 地址：#3571
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 + 1 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lcx-seima** [comment]
@leviding 认领翻译

**Comment by fanyijihua** [comment]
@lcx-seima 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3571
