### ISSUE TITLE
VINE：一种开源的神经进化（Neuroevolution）交互式数据可视化工具

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3547]
* 原文链接：[VINE: An Open Source Interactive Data Visualization Tool for Neuroevolution](https://eng.uber.com/vine/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/an-open-source-interactive-data-visualization-tool-for-neuroevolution.md)
  * PR 地址：#3560
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3558

**Comment by fanyijihua** [comment]
PR 地址：#3560
