### ISSUE TITLE
不用 Class，如何写一个类

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3556]
* 原文链接：[Classes Without Classes](https://veriny.tf/classes-without-classes/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/classes-without-classes.md)
  * PR 地址：#3564
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:
