### ISSUE TITLE
单向用户界面架构问题研究

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3559]
* 原文链接：[UNIDIRECTIONAL USER INTERFACE ARCHITECTURES](https://staltz.com/unidirectional-user-interface-architectures.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/unidirectional-user-interface-architectures.md)
  * PR 地址：#3582
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@proYang

**Comment by allenlongbaobao** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@allenlongbaobao 棒极啦 :tada:

**Comment by allenlongbaobao** [comment]
好像有人占了，不夺人之美，取消认领。

**Comment by proYang** [comment]
@allenlongbaobao  我没有认领，这是我推荐的文章，所以`@`了我 👨‍🚒

**Comment by EmilyQiRabbit** [comment]
！啊前端！认领翻译！

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by EmilyQiRabbit** [comment]
哈哈神速👍

**Comment by fanyijihua** [comment]
PR 地址：#3582
