### ISSUE TITLE
Overview of Pandas Data Types

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3566]
* 原文链接：[Overview of Pandas Data Types](http://pbpython.com/pandas_dtypes.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/pandas-dtypes.md)
  * PR 地址：#
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by stormluke** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@stormluke 棒极啦 :tada:
