### ISSUE TITLE
JavaScript 单元测试框架：Jasmine, Mocha, AVA, Tape 和 Jest 的比较

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3567]
* 原文链接：[JavaScript unit testing frameworks: Comparing Jasmine, Mocha, AVA, Tape and Jest](https://raygun.com/blog/javascript-unit-testing-frameworks/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/javascript-unit-testing-frameworks.md)
  * PR 地址：#3588
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ClarenceC** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ClarenceC 棒极啦 :tada:
