### ISSUE TITLE
提高 10 倍性能：优化静态网站

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3568]
* 原文链接：[10x Performance Increases: Optimizing a Static Site](https://hackernoon.com/optimizing-a-static-site-d5ab6899f249)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/optimizing-a-static-site.md)
  * PR 地址：#3577
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3577

**Comment by Raoul1996** [comment]
校对认领

**Comment by Starriers** [comment]
文章已经发布：https://juejin.im/post/5ac9e430f265da2392369ec0
