### ISSUE TITLE
区块链如何帮助重塑医疗保健行业

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3569]
* 原文链接：[How Blockchain Can Help Re-invent Healthcare](https://www.sitepoint.com/how-blockchain-can-help-re-invent-healthcare/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-blockchain-can-help-re-invent-healthcare.md)
  * PR 地址：#3604
  * 文章分类：**区块链**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by EmilyQiRabbit** [comment]
早该猜到这是个机器人.....🤦‍♀️Too naive~

**Comment by fanyijihua** [comment]
PR 地址：#3604
