### ISSUE TITLE
申请Android翻译

### ISSUE THREAD

**Issue by Froyo91** [xitu/gold-miner#357]
希望可以挑战自己，翻译一些关于Android开发的文章，谢谢~

**Comment by Froyo91** [comment]
我目前在职~

**Comment by antonia0912** [comment]
@Froyo91 hey  你需要介绍一下自己喔  工作是什么方面的  英语水平怎么样  之前有没有翻译过类似的英文文章  有看英文文献/文章的习惯吗  等等

**Comment by Froyo91** [comment]
你好，我的工作是Android程序员，这是我之前翻译的文章：http://blog.csdn.net/y505772146/article/details/51291609
http://blog.csdn.net/y505772146/article/details/51235436
英语水平：大学6级
之前会看一下Android Developer上的一些文档

**Comment by antonia0912** [comment]
@Froyo91 好的  请加我微信 antonia0912 备注 github ID 我拉你进译者群
