### ISSUE TITLE
移动游戏发行的新时代

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3572]
* 原文链接：[A new era of launching mobile games: How mobile game developers are evolving their go-to-market strategies.](https://medium.com/googleplaydev/a-new-era-of-launching-mobile-games-ef2453686f73)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-new-era-of-launching-mobile-games.md)
  * PR 地址：#3765
  * 文章分类：**Android**，本文由 Google 进行发布
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@IllllllIIl 翻译好了吗

**Comment by leviding** [comment]
@IllllllIIl 这篇翻译的怎么样啦

**Comment by leviding** [comment]
@IllllllIIl 好的哈

**Comment by fanyijihua** [comment]
PR 地址：#3765
