### ISSUE TITLE
设计师与工程师协作的 5 项准则

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3573]
* 原文链接：[5-rules-for-designer-engineer-collaboration: Tips to Improve Quality and Productivity](https://medium.com/tradecraft-traction/5-rules-for-designer-engineer-collaboration-182fd74bd09f?ref=uxdesignweekly)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/5-rules-for-designer-engineer-collaboration.md)
  * PR 地址：#3592
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3592
