### ISSUE TITLE
Android 支持库 21.1.0 中的 Loaders

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3574]
* 原文链接：[Loaders in Support Library 27.1.0](https://medium.com/google-developers/loaders-in-support-library-27-1-0-b1a1f0fee638)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/loaders-in-support-library-27-1-0.md)
  * PR 地址：#3731
  * 文章分类：**Android**，本文由 Google 进行发布
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：1 天
  * 校对时间：1 天
  * 翻译积分：1.5 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rockzhai** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@rockzhai 棒极啦 :tada:

**Comment by rockzhai** [comment]
这周工作都有点忙，可能来不及翻这个了，不然先释放掉给其他人翻吧，或者等这周末我再来，这几天事情贼多，见谅T_T @leviding

**Comment by leviding** [comment]
@rockzhai 不急，记得就好

**Comment by leviding** [comment]
@rockzhai 这篇翻译的怎么样啦 😆

**Comment by rockzhai** [comment]
@leviding 这篇给别人翻吧，最近事情多也状态不好，释放掉吧T_T

**Comment by dreamhb** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@dreamhb 棒极啦 :tada:
