### ISSUE TITLE
关于 SPA 你需要掌握的 4 层

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3578]
* 原文链接：[The 4 Layers of Single Page Applications You Need to Know](https://hackernoon.com/architecting-single-page-applications-b842ea633c2e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/architecting-single-page-applications.md)
  * PR 地址：#
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zwwill** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@zwwill 棒极啦 :tada:
