### ISSUE TITLE
申请Android翻译

### ISSUE THREAD

**Issue by Tikitoo** [xitu/gold-miner#358]
我的博客：http://tikitoo.github.io
我的微博：[@安卓同学](http://weibo.com/lyf0306/home?wvr=5)
英语水平：4 级未过

一个Android 菜鸟，一个英语 学渣。平常学习都会用Google 搜索和看官方文档。

这是我之前翻译的文章：
- [教你写一个炫酷的Material Design 风格的登录和注册页面 | Tikitoo Blog](http://tikitoo.github.io/2016/05/17/beautiful-android-login-and-signup-screens-with-material-design-zh/)
- [Android Studio 提示与技巧（官方文档翻译） | Tikitoo Blog](http://tikitoo.github.io/2016/05/10/android-studio-tips-and-tricks-zh/)

@antonia0912 眼熟我，我的Markdown 文档写的规范不？？？

**Comment by antonia0912** [comment]
@Tikitoo 我微信有你  直接拉你进译者群哈~
