### ISSUE TITLE
[1] + [2] - [3] === 9!? Looking into assembly code of coercion

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3586]
* 原文链接：[[1] + [2] - [3] === 9!? Looking into assembly code of coercion](https://wanago.io/2018/04/02/1-2-3-9-looking-into-assembly-code-of-coercion/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/1-2-3-9-looking-into-assembly-code-of-coercion.md)
  * PR 地址：#3606
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@jonjia

**Comment by sunhaokk** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sunhaokk 棒极啦 :tada:

**Comment by sunhaokk** [comment]
收到
