### ISSUE TITLE
文章格式反馈建议

### ISSUE THREAD

**Issue by monsterooo** [xitu/gold-miner#359]
比如[这篇文章](http://gold.xitu.io/entry/56aae5e4a633bd0257ae4ab8?utm_source=gold-miner&utm_medium=readme&utm_campaign=github)，特殊转意成了html字符，还有代码显示格式问题是markdown转换问题吗？这样很影响阅读

**Comment by antonia0912** [comment]
@monsterooo 应该是我们的转换器的问题  目前用的是 stackedit 转换器
