### ISSUE TITLE
使用 NumPy 和 Pandas 进行 Python 式数据清理

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3597]
* 原文链接：[Pythonic Data Cleaning With NumPy and Pandas](https://realpython.com/python-data-cleaning-numpy-pandas/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/python-data-cleaning-numpy-pandas.md)
  * PR 地址：#3641
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by bambooom** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@bambooom 棒极啦 :tada:
