### ISSUE TITLE
<Designing the icons for Flinto's UI>错误反馈

### ISSUE THREAD

**Issue by vere** [xitu/gold-miner#360]
“对于使用retina显示屏的读者，我们显示“一半尺寸”的位图，如图1x的全像素图标。对于非retina显示屏的读者，则使用“双倍尺寸”的位图，如图2x的全像素图标。”这段翻译明显有误，retina屏自动调用的是2x位图，单从这个角度这样翻译就是错误的。
“Half Size” bitmaps shown for readers using a retina display, to see the 1x icon in full pixels. “Double Size” shown for readers using a non-retina display, to see the 2x icon in full pixels.
原文的意思是，“Half Size”展示的是在retina屏上显示1x位图的效果，“Double Size”展示的是在非retina屏上显示2x位图的效果。

**Comment by antonia0912** [comment]
@edvardHua @CoderBOBO @Ruixi 请来看一下这个问题  谢谢 @vere 的反馈 如果有兴趣成为翻译计划的译者请在issue里发译者申请 欢迎

**Comment by Ruixi** [comment]
啊确实……

**Comment by edvardHua** [comment]
@antonia0912 收到，我再核查一遍，然后更新一下！

**Comment by antonia0912** [comment]
@edvardHua 把这段话相应的需要修改的地方直接告诉我就可以啦  我直接在主仓库修改  这样快一点

**Comment by edvardHua** [comment]
@antonia0912 嗯，羊哥把

对于使用retina显示屏的读者，我们显示“一半尺寸”的位图，如图1x的全像素图标。对于非retina显示屏的读者，则使用“双倍尺寸”的位图，如图2x的全像素图标。

修改成

“Half Size”展示的是在retina屏上显示1x位图的效果，“Double Size”展示的是在非retina屏上显示2x位图的效果。

这句话就好了，麻烦羊哥啦！

**Comment by antonia0912** [comment]
@vere @Ruixi @edvardHua 已经修改了
