### ISSUE TITLE
请问这个项目停止维护了吗？xitu/interviews

### ISSUE THREAD

**Issue by maskleo** [xitu/gold-miner#3600]
https://github.com/xitu/interviews 
停止翻译了吗？

**Comment by leviding** [comment]
@maskleo 这个已经翻译完了，是有什么问题吗？

**Comment by maskleo** [comment]
@leviding   https://github.com/xitu/interviews/compare/master...kdn251:master
新增了不少

**Comment by leviding** [comment]
@maskleo 嗯嗯，感谢提醒，我新增了一个 PR，后续会跟进翻译的
