### ISSUE TITLE
利用 Keras 深度学习库进行词性标注教程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3602]
* 原文链接：[Part-of-Speech tagging tutorial with the Keras Deep Learning library](https://medium.com/@cdiscountdatascience/part-of-speech-tagging-tutorial-with-the-keras-deep-learning-library-d7f93fa05537)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/part-of-speech-tagging-tutorial-with-the-keras-deep-learning-library.md)
  * PR 地址：#3621
  * 文章分类：**深度学习**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luochen1992** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@luochen1992 棒极啦 :tada:
