### ISSUE TITLE
WindowsInsets 和 Fragment 过渡动画

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3603]
* 原文链接：[Windows Insets + Fragment Transitions: A tale of woe](https://medium.com/google-developers/windows-insets-fragment-transitions-9024b239a436)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/windows-insets-fragment-transitions.md)
  * PR 地址：#3745
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LeeSniper** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@LeeSniper 棒极啦 :tada:

**Comment by leviding** [comment]
@LeeSniper 这篇翻译的怎么样啦 😆

**Comment by leviding** [comment]
@LeeSniper 这篇翻译的怎么样啦 😆

**Comment by fanyijihua** [comment]
PR 地址：#3745

**Comment by LeeSniper** [comment]
@leviding 抱歉啦，最近换工作没抽出时间来，刚翻译完。

**Comment by leviding** [comment]
@LeeSniper 收到，辛苦啦~
