### ISSUE TITLE
以太坊钱包详解

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3608]
* 原文链接：[ethereumbook-wallets](https://github.com/ethereumbook/ethereumbook/blob/develop/wallets.asciidoc)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/ethereumbook-wallets.md)
  * PR 地址：#3653
  * 文章分类：**区块链**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：12 天
  * 校对时间：4 天
  * 翻译积分：12 分
  * 校对积分：4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@XatMassacrE 棒极啦 :tada:
