### ISSUE TITLE
How to write low garbage real-time Javascript

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#361]
原文链接：[How to write low garbage real-time Javascript](https://www.scirra.com/blog/76/how-to-write-low-garbage-real-time-javascript)
掘金链接：[How to write low garbage real-time Javascript](http://gold.xitu.io/entry/5739484e79df5400601a23f5)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-write-low-garbage-real-time-javascript.md)

翻译时间：5天
校对时间：3天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by yangzj1992** [comment]
翻译认领

**Comment by antonia0912** [comment]
@yangzj1992 markdown文件已添加 可以翻译了

**Comment by yangzj1992** [comment]
@antonia0912  初译完成，请求校对 [校对地址](https://github.com/xitu/gold-miner/pull/376)

**Comment by L9m** [comment]
校对认领

**Comment by antonia0912** [comment]
@L9m 收到

**Comment by ldhlfzysys** [comment]
校对认领...

**Comment by antonia0912** [comment]
@ldhlfzysys 乖~摸摸大头~
