### ISSUE TITLE
用 Python 编程进行糖尿病相关的机器学习

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3610]
* 原文链接：[PROGRAMMING Machine Learning for Diabetes with Python](https://datascienceplus.com/machine-learning-for-diabetes-with-python/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/machine-learning-for-diabetes-with-python.md)
  * PR 地址：#3622
  * 文章分类：**机器学习**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
@leviding 认领翻译

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3622
