### ISSUE TITLE
用行为经济学来传达付费应用订阅的价值

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3612]
* 原文链接：[Using behavioural economics to convey the value of paid app subscriptions](https://medium.com/googleplaydev/using-behavioural-economics-to-convey-the-value-of-paid-app-subscriptions-cd96ca171d5b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/using-behavioural-economics-to-convey-the-value-of-paid-app-subscriptions.md)
  * PR 地址：#3633
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ALVINYEH** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ALVINYEH 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3633
