### ISSUE TITLE
预测你的游戏的货币化未来

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3616]
* 原文链接：[Predicting your game’s monetization future: An analysis on how top games developers calculate lifetime value](https://medium.com/googleplaydev/predicting-your-games-monetization-future-ce176169b056)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/predicting-your-games-monetization-future.md)
  * PR 地址：#3626
  * 文章分类：**产品**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by NoName4Me** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@NoName4Me 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3626
