### ISSUE TITLE
引导员手册：24 个设计冲刺技巧

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3617]
* 原文链接：[The Facilitator’s Handbook: 24 Design Sprint Tips](https://sprintstories.com/23-facilitation-tips-for-design-sprints-34d876aa5317?ref=uxdesignweekly)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/23-facilitation-tips-for-design-sprints.md)
  * PR 地址：#3652
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PokerF** [comment]
申请翻译

**Comment by fanyijihua** [comment]
@PokerF 棒极啦 :tada:

**Comment by rydensun** [comment]
提前认领校对

**Comment by fanyijihua** [comment]
PR 地址：#3652
