### ISSUE TITLE
HOW TO BUILD A MATERIAL DESIGN PROTOTYPE USING SKETCH AND PIXATE - PART ONE

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#362]
原文链接：[HOW TO BUILD A MATERIAL DESIGN PROTOTYPE USING SKETCH AND PIXATE - PART ONE](http://createdineden.com/blog/post/material-design-prototype-tutorial-part-1/)
掘金链接：[[英] HOW TO BUILD A MATERIAL DESIGN PROTOTYPE USING SKETCH AND PIXATE - PART ONE](gold.xitu.io/entry/573ea300f38c840067735ef4)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/material-design-prototype-tutorial-part-1.md)

翻译时间：5天
校对时间：4天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by joddiy** [comment]
能同时翻译两篇吗？ ：D

**Comment by antonia0912** [comment]
@joddiy 最近文章比较紧缺  所以只能翻译一篇喔~想翻1还是2呀  快选一个

**Comment by Sausure** [comment]
我认领这篇吧

**Comment by joddiy** [comment]
那我翻译2吧 @antonia0912

**Comment by Sausure** [comment]
@joddiy 抱歉呀，我根据上面的聊天记录以为你已经和羊三商量好翻译第二篇了所以我才认领第一篇

**Comment by Ruixi** [comment]
求校对

**Comment by wild-flame** [comment]
关于material design 的呢，我也求校对+1

**Comment by joddiy** [comment]
没关系的，而且我已经开始翻译第二篇了 @Sausure

**Comment by Sausure** [comment]
@antonia0912 我发现一个问题，这篇文章是 part one，还有一篇是 part two，两篇文章对应的 markdown 文件名体现不出两者是对应关系

**Comment by Sausure** [comment]
@Ruixi @wild-flame 已 PR，可以校对了。地址：https://github.com/xitu/gold-miner/pull/365

**Comment by Ruixi** [comment]
好的

**Comment by antonia0912** [comment]
ok，part 2 由 @joddiy 翻译，part 1 由 @Sausure 翻译，由 @Ruixi @wild-flame 校对，关于两个markdown的文件名是按英文原文走的，不碍事啦 ~ 周一早安~

**Comment by wild-flame** [comment]
好的

**Comment by Sausure** [comment]
@Ruixi @wild-flame 希望两位能尽早完成校对，多谢！

**Comment by Ruixi** [comment]
我走完一遍啦，被 text field 迷惑的不行··· ···
深深体会到原作者在语言表达上的某种恶趣味··· ···译者辛苦啦。
@wild-flame 那个text field 的坑拜托了，我是晕了··· ···

**Comment by wild-flame** [comment]
累死了终于校对完啦。这篇文章作者用词用的很活，句式也比较多，所以一定按句子的意思理解才好翻译，按词翻译容易搞错意思。

@Ruixi  text field的坑帮你填啦，写在 comment 里面了。后面校对的我没前面仔细了，读着通顺的我就不大看原文了……

@antonia0912 这篇这么难校对你不睿希和我加加分呀，相当于以前三四篇的工作量了。羊哥~~~~~

**Comment by Sausure** [comment]
感谢 @Ruixi @wild-flame 的校对，辛苦了！！ @antonia0912 三只羊，我对你们的校对积分的评定也有异议，希望能改改
