### ISSUE TITLE
用 Skater 解读预测模型：打开模型的黑箱

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3620]
* 原文链接：[Interpreting predictive models with Skater: Unboxing model opacity](https://www.oreilly.com/ideas/interpreting-predictive-models-with-skater-unboxing-model-opacity)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/interpreting-predictive-models-with-skater-unboxing-model-opacity.md)
  * PR 地址：#3665
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by radialine** [comment]
有期限要求吗

**Comment by leviding** [comment]
@radialine 上面不是写了吗

**Comment by fanyijihua** [comment]
PR 地址：#3665
