### ISSUE TITLE
互联汽车是什么以及如何开发用于它的应用？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3629]
* 原文链接：[Connected cars 🏎 — what are they and how to get started developing connected car apps](https://hackernoon.com/connected-cars-what-are-they-and-how-to-get-started-developing-connected-car-apps-5c6fbbf1f157)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/connected-cars-what-are-they-and-how-to-get-started-developing-connected-car-apps.md)
  * PR 地址：#3630
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jonjia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jonjia 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3630

**Comment by HydeSong** [comment]
校对认领
