### ISSUE TITLE
HOW TO BUILD A MATERIAL DESIGN PROTOTYPE USING SKETCH AND PIXATE - PART TWO

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#363]
原文链接：[HOW TO BUILD A MATERIAL DESIGN PROTOTYPE USING SKETCH AND PIXATE - PART TWO](http://createdineden.com/blog/post/how-to-build-a-material-design-prototype-using-sketch-and-pixate-part-two/)
掘金链接：[HOW TO BUILD A MATERIAL DESIGN PROTOTYPE USING SKETCH AND PIXATE - PART TWO](http://gold.xitu.io/entry/573ea96271cfe448aa9e8a2d)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-build-a-material-design-prototype-using-sketch-and-pixate-part-two.md)

翻译时间：5天
校对时间：4天
翻译积分：7
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by joddiy** [comment]
Material Design 啊！！ 认领翻译！！

**Comment by antonia0912** [comment]
@joddiy 收到

**Comment by Sausure** [comment]
哈哈，我认领

**Comment by Velacielad** [comment]
预定个校对

**Comment by Zheaoli** [comment]
预定一个二校

**Comment by antonia0912** [comment]
@joddiy 请译者PR之后圈两位校对者来校对~

**Comment by joddiy** [comment]
@antonia0912 羊哥，翻译完了，强烈要求加积分，这篇太长太长太长了，170行啊，而且这作者以前是不是写小说的，各种活泼写法，都不知道怎么对应到汉语了。辛苦校对者了！

**Comment by antonia0912** [comment]
@Velacielad @Zheaoli [校对地址](https://github.com/xitu/gold-miner/pull/371/files?diff=split)

**Comment by antonia0912** [comment]
@joddiy 是的 校对积分加了  辛苦了honey

**Comment by joddiy** [comment]
@Velacielad @Zheaoli 抱歉抱歉抱歉，昨晚最后一次提交被reject了，没提交上去。刚才重新提交了下。

**Comment by Zheaoli** [comment]
@joddiy 卧槽。。。我之前的校对的全部没了。。

**Comment by joddiy** [comment]
@Zheaoli @Velacielad 两位校对者完成了吗？ok了我就开始整理了撒。

**Comment by Velacielad** [comment]
@joddiy 稍等，我还没看完= =

**Comment by Zheaoli** [comment]
我这边的校对差不多了，。

**Comment by Velacielad** [comment]
校对完毕 @joddiy ..辛苦翻译了...

**Comment by joddiy** [comment]
好的，前几天出远门了，今天修改一下，幸苦两位！
