### ISSUE TITLE
React 中的 Immutability：可变对象并没有什么问题

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3635]
* 原文链接：[Immutability in React: There’s nothing wrong with mutating objects](https://blog.logrocket.com/immutability-in-react-ebe55253a1cc)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/immutability-in-react-theres-nothing-wrong-with-mutating-objects.md)
  * PR 地址：#3658
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：2 天
  * 翻译积分：4.5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MechanicianW** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MechanicianW 棒极啦 :tada:

**Comment by jonjia** [comment]
翻译认领

**Comment by MechanicianW** [comment]
@leviding 沟通了下，这篇文章由 @jonjia  翻译

**Comment by jonjia** [comment]
谢谢 @MechanicianW

**Comment by leviding** [comment]
ok

**Comment by fanyijihua** [comment]
PR 地址：#3658
