### ISSUE TITLE
Deploy != Release（第一部分）：Deploy 与 Release 的区别及为什么很重要？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3639]
* 原文链接：[Deploy != Release (Part 1): The difference between deploy and release and why it matters.](https://blog.turbinelabs.io/deploy-not-equal-release-part-one-4724bc1e726b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/deploy-not-equal-release-part-one.md)
  * PR 地址：#3664
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
@stormluke 棒极啦 :tada:
