### ISSUE TITLE
那些好玩却没有被 ECMAScript 2017 采纳的提案

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3644]
* 原文链接：[Interesting ECMAScript 2017 proposals that weren’t adopted](https://blog.logrocket.com/interesting-ecmascript-2017-proposals-163b787cf27c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/interesting-ecmascript-2017-proposals.md)
  * PR 地址：#3725
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@MechanicianW 你的啦

**Comment by MechanicianW** [comment]
翻译认领 
@leviding 多谢！

**Comment by fanyijihua** [comment]
@MechanicianW 棒极啦 :tada:

**Comment by leviding** [comment]
@Colafornia 这篇翻译的怎么样啦 😆

**Comment by Colafornia** [comment]
@leviding 刚到成都忙着租房子，文章翻译了80%了，最晚周五会发PR
认领的另一个 #3674 也要接着顺延三天左右

**Comment by leviding** [comment]
@Colafornia 好的 😊

**Comment by fanyijihua** [comment]
PR 地址：#3725
