### ISSUE TITLE
用 Redis 和 Python 构建一个共享单车的 app

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3646]
* 原文链接：[Build a bikesharing app with Redis and Python](https://opensource.com/article/18/2/building-bikesharing-application-open-source-tools)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/building-bikesharing-application-open-source-tools.md)
  * PR 地址：#3651
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by leviding** [comment]
@Starriers 高产

**Comment by fanyijihua** [comment]
PR 地址：#3651

**Comment by Starriers** [comment]
已经发布：https://juejin.im/post/5adc861a51882567161a2799
