### ISSUE TITLE
如何调试前端：优化网络资源

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3659]
* 原文链接：[How to debug front-end: optimising network assets](https://blog.pragmatists.com/how-to-debug-front-end-optimising-network-assets-c0bfcad29b40)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-debug-front-end-optimising-network-assets.md)
  * PR 地址：#3688
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by stormluke** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@stormluke 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3688

**Comment by stormluke** [comment]
发布啦 https://juejin.im/post/5ade828751882567137dd2da @leviding

**Comment by stormluke** [comment]
发布啦 https://juejin.im/post/5ade828751882567137dd2da @leviding
