### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by shenAlexy** [xitu/gold-miner#366]
您好，我是名iOS开发者，喜欢分享iOS开发，申请成为译者。

**Comment by antonia0912** [comment]
@shenAlexy 请问英语水平怎么样 之前有翻译过类似的英文技术文章吗  平时会从外文网站获取相关咨询吗

**Comment by shenAlexy** [comment]
经常使用Github和StackOverFlow，能看懂并写英语.

**Comment by antonia0912** [comment]
@shenAlexy ok 已经添加你微信了  我来拉你进译者群
