### ISSUE TITLE
漫画深入浅出 ES 模块

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3660]
* 原文链接：[ES modules: A cartoon deep-dive](https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/es-modules-a-cartoon-deep-dive.md)
  * PR 地址：#3732
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：8 天
  * 校对时间：3 天
  * 翻译积分：8 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by stormluke** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@stormluke 棒极啦 :tada:
