### ISSUE TITLE
快拍中 Type Mode 在 iOS 和 Android 上的实现

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3661]
* 原文链接：[Building Type Mode for Stories on iOS and Android](https://instagram-engineering.com/building-type-mode-for-stories-on-ios-and-android-8804e927feba)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/building-type-mode-for-stories-on-ios-and-android.md)
  * PR 地址：#3707
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by melon8** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@melon8 棒极啦 :tada:
