### ISSUE TITLE
推荐英文文档

### ISSUE THREAD

**Issue by ShaofeiZi** [xitu/gold-miner#3672]
- 原文链接：http://typeorm.io
- 简要介绍：TypeORM是一个采用TypeScript编写的用于Node.js的优秀ORM框架，支持使用TypeScript或Javascript(ES5, ES6, ES7)开发。
目标是保持支持最新的Javascript特性来帮助开发各种用到数据库的应用 - 不管是轻应用还是企业级的。

TypeORM可以做到：

根据Models自动创建数据库Table
可以透明的insert/update/delete数据库对象
映射数据库table到javascript对象，映射table column到javascript对象属性
提供表的一对一，多对一，一对多，多对多关系处理
还有更多 ...
不同于其他的JavaScript ORM，TypeORM使用的是数据映射模式，可以很轻松的创建出松耦合、可伸缩、可维护的应用。

TypeORM可以帮助开发者专注于业务逻辑，而不用过于担心数据存储的问题。

TypeORM参考了很多其他优秀ORM的实现, 比如 Hibernate, Doctrine 和 Entity Framework.

**Comment by ShaofeiZi** [comment]
http://typeorm.noonme.com/
翻到了。。

**Comment by leviding** [comment]
🤣 好吧，有别的也欢迎推荐哈
