### ISSUE TITLE
如何逃离 async/await 地狱

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3674]
* 原文链接：[How to escape async/await hell](https://medium.freecodecamp.org/avoiding-the-async-await-hell-c77a0fb71c4c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/avoiding-the-async-await-hell.md)
  * PR 地址：#3738
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Colafornia** [comment]
翻译认领😁

**Comment by fanyijihua** [comment]
@Colafornia 棒极啦 :tada:

**Comment by leviding** [comment]
@Colafornia 这篇翻译的怎么样啦 😆

**Comment by Colafornia** [comment]
@leviding 晚上回家再检查一下格式，就发PR
我的github id 从之前的 MechanicianW 改成 Colafornia 了，麻烦管理员更新下译者积分表上的名字哈

**Comment by leviding** [comment]
@Colafornia 赞。

2333 怪不得，我说看这个头像这么眼熟

**Comment by fanyijihua** [comment]
PR 地址：#3738
