### ISSUE TITLE
使用 React, Redux, and SVG 开发游戏 - 第3部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3677]
* 原文链接：[Developing Games with React, Redux, and SVG - Part 3](https://auth0.com/blog/developing-games-with-react-redux-and-svg-part-3/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/developing-games-with-react-redux-and-svg-part-3.md)
  * PR 地址：#3757
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：9 天
  * 校对时间：3 天
  * 翻译积分：9 分
  * 校对积分：1-3 分 jasonxia23 4 分，smileforward123 1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@zephyrJS 你的啦

**Comment by xueshuai** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@xueshuai 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3757
