### ISSUE TITLE
优化 WEBPACK 以更快地构建 REACT

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3678]
* 原文链接：[OPTIMIZING WEBPACK FOR FASTER REACT BUILDS](http://engineering.invisionapp.com/post/optimizing-webpack/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/optimizing-webpack-for-faster-react-builds.md)
  * PR 地址：#3691
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@EmilyQiRabbit 你的哈

**Comment by fanyijihua** [comment]
PR 地址：#3691
