### ISSUE TITLE
如何写出更好的 React 代码

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3679]
* 原文链接：[How To Write Better Code In React](https://blog.bitsrc.io/how-to-write-better-code-in-react-best-practices-b8ca87d462b0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-write-better-code-in-react-best-practices.md)
  * PR 地址：#3713
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@jonjia 你的

**Comment by jonjia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jonjia 棒极啦 :tada:
