### ISSUE TITLE
减小 JPG 文件大小

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#368]
原文链接：[Reducing JPG File size](https://medium.com/@duhroach/reducing-jpg-file-size-e5b27df3257c#.l67l1mxg8)
掘金链接：[减小 JPG 文件大小](http://gold.xitu.io/entry/57429820c4c971006065b731)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/reducing-jpg-file-size.md)

翻译时间：5天
校对时间：4天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by shenxn** [comment]
认领！

**Comment by antonia0912** [comment]
@shenxn ok

**Comment by shenAlexy** [comment]
申请校对！

**Comment by xcc3641** [comment]
申请校对 :)

**Comment by galenyuan** [comment]
认领校对

**Comment by antonia0912** [comment]
@xcc3641 @galenyuan 译者翻译完来圈两位校对者校对哈~ @shenxn

**Comment by galenyuan** [comment]
校对完成 @antonia0912 @shenxn
