### ISSUE TITLE
为什么 Flutter 能最好地改变移动开发

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3681]
* 原文链接：[Why Flutter Will Change Mobile Development for the Best](https://android.jlelse.eu/why-flutter-will-change-mobile-development-for-the-best-c249f71fa63c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-flutter-will-change-mobile-development-for-the-best.md)
  * PR 地址：#3690
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ALVINYEH** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ALVINYEH 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3690
