### ISSUE TITLE
为什么你应该开始使用 Kotlin

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3682]
* 原文链接：[Why you should totally switch to Kotlin](https://medium.com/@magnus.chatt/why-you-should-totally-switch-to-kotlin-c7bbde9e10d5)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-you-should-totally-switch-to-kotlin.md)
  * PR 地址：#3685
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ALVINYEH** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ALVINYEH 棒极啦 :tada:

**Comment by Scyano** [comment]
标签错了吧, 是 Android 的

**Comment by fanyijihua** [comment]
PR 地址：#3685

**Comment by Starriers** [comment]
@Scyano  kotlin 现在也是支持 IOS 开发的。Kotlin 的范围不应该仅仅局限于 Android，而且校对之后，本文是推广 Kotlin，所以严格意义上来说，用 Android 也是不对的，只不过去年被人们所知，是因为 Google。就像是 JS（可能要改名字了）的文章，一定就是前段的么！我本人也是 Kotlin 的开发者。

**Comment by jellycsc** [comment]
我觉得可以上两个标签😆
