### ISSUE TITLE
推荐 Passport 文档

### ISSUE THREAD

**Issue by initial-wu** [xitu/gold-miner#3683]
- 原文链接：http://www.passportjs.org/docs/
- 简要介绍：Passport 是一个 Node 平台的身份认证中间件。它为一个简单的目的：身份认证请求而设计。编写模块时，封装是一个美德，所以 Passport 把所有其他功能委托给应用。这种关注点的分离可以保持代码整洁并且可维护，同时使得 Passport 极其容易地集成到一个应用中。
> 已完成翻译，发表在 [知乎](https://zhuanlan.zhihu.com/p/35877677)

**Comment by leviding** [comment]
@initial-wu 很赞，可以加我微信私聊 517010193
