### ISSUE TITLE
电商的商品列表里都应该包含啥信息？

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#369]
原文链接：[E-Commerce UX: What Information to Display in Product Listings (46% Get it Wrong)](http://baymard.com/blog/product-listing-information)
掘金链接：[电商的商品列表里都应该包含啥信息？](http://gold.xitu.io/entry/573b02b879df540060282f94)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/product-listing-information.md)
PR:#385
翻译时间：5天
校对时间：4天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by godofchina** [comment]
@antonia0912  认领

**Comment by antonia0912** [comment]
@godofchina ok

**Comment by joddiy** [comment]
提前占个校对坑

**Comment by Ruixi** [comment]
占坑＋1

**Comment by godofchina** [comment]
@antonia0912  羊老师我作业写完了

**Comment by Ruixi** [comment]
3天假期网络挂了两天··· ···
今天终于爬上来惹··· ···
又过了一遍，觉得剩下的应该问题不大啦~

**Comment by godofchina** [comment]
@antonia0912 已分享，求加分。http://gold.xitu.io/entry/575cd2f31532bc00608d241c/detail
