### ISSUE TITLE
用 Java 代码实现区块链

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3693]
* 原文链接：[Blockchain Implementation With Java Code](https://dzone.com/articles/blockchain-implementation-with-java-code)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/blockchain-implementation-with-java-code.md)
  * PR 地址：#3701
  * 文章分类：**区块链**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分 sisibeloved * 2
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yanzhennan** [comment]
看看

**Comment by Starriers** [comment]
@yanzhennan 什么意思这个是你推荐的然后想自己翻译？
