### ISSUE TITLE
用户体验中的稀缺性：成为常态的心理偏见

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3698]
* 原文链接：[Scarcity in UX: The psychological bias that became the norm](https://uxdesign.cc/scarcity-in-ux-the-psychological-bias-that-became-the-norm-3e666b749a9a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/scarcity-in-ux-the-psychological-bias-that-became-the-norm.md)
  * PR 地址：#3729
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#3729

**Comment by wavezhang** [comment]
@Starriers @leviding 校对完成
