### ISSUE TITLE
抢先看 Swift 3.0

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#370]
原文链接：[Swift 3.0 Release Process](https://swift.org/blog/swift-3-0-release-process/)
掘金链接：[抢先看 Swift 3.0](http://gold.xitu.io/entry/573aa5551ea4930060fd2c0c)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/swift-3-0-release-process.md)

翻译时间：5天
校对时间：4天
翻译积分：5
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zheaoli** [comment]
认领翻译

**Comment by Tuccuay** [comment]
认（

**Comment by antonia0912** [comment]
@Tuccuay ok

**Comment by DeadLion** [comment]
@antonia0912  校对认领

**Comment by antonia0912** [comment]
@DeadLion ok

**Comment by DeadLion** [comment]
@antonia0912  还没有翻译完是么？

**Comment by Tuccuay** [comment]
@DeadLion 这里这里 #373

**Comment by DeadLion** [comment]
校稿完成
