### ISSUE TITLE
构建、测试、分发！运用 Fastlane 与 Jenkins，完整的 iOS 持交付指南。

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3703]
* 原文链接：[Build it, Test it, Deliver it! Complete iOS Guide on Continuous Delivery with fastlane and Jenkins](https://medium.com/flawless-app-stories/build-it-test-it-deliver-it-complete-ios-guide-on-continuous-delivery-with-fastlane-and-jenkins-cbe44e996ac5)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/build-it-test-it-deliver-it-complete-ios-guide-on-continuous-delivery-with-fastlane-and-jenkins.md)
  * PR 地址：#3743
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by talisk** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@talisk 棒极啦 :tada:

**Comment by leviding** [comment]
@talisk 这篇翻译的怎么样啦 😆
