### ISSUE TITLE
给初学者的 Jupyter Notebook 教程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3705]
* 原文链接：[Jupyter Notebook for Beginners: A Tutorial](https://www.dataquest.io/blog/jupyter-notebook-tutorial/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/jupyter-notebook-tutorial.md)
  * PR 地址：#3784
  * 文章分类：**教程**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by SergeyChang** [comment]
认领

**Comment by leviding** [comment]
@SergeyChang ok

**Comment by fanyijihua** [comment]
PR 地址：#3784
