### ISSUE TITLE
我是如何修复 Python 3.7 中一个非常古老的 GIL 竞态条件 bug 的

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3714]
* 原文链接：[How I fixed a very old GIL race condition in Python 3.7](https://vstinner.github.io/python37-gil-change.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-i-fixed-a-very-old-gil-race-condition-in-python-3-7.md)
  * PR 地址：#3719
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kezhenxu94** [comment]
翻译认领

目前没有可以核对的文章，不如这个我来翻译吧？

**Comment by fanyijihua** [comment]
@kezhenxu94 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3719
