### ISSUE TITLE
介绍 Google Play 上新的优质 Android 应用与游戏

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3718]
* 原文链接：[Introducing new Android Excellence apps and games on Google Play](https://android-developers.googleblog.com/2018/04/introducing-new-android-excellence-apps.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/introducing-new-android-excellence-apps.md)
  * PR 地址：#3734
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sisibeloved** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@sisibeloved 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3734
