### ISSUE TITLE
Python 3-- 探索加密技术

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#372]
原文链接：[Python 3: An Intro to Encryption](http://www.blog.pythonlibrary.org/2016/05/18/python-3-an-intro-to-encryption/)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/python-3-an-intro-to-encryption.md)

翻译时间：5天
校对时间：4天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by rainyear** [comment]
认领。

**Comment by antonia0912** [comment]
@rainyear 收到

**Comment by rainyear** [comment]
@antonia0912 初稿翻译完成，等待校对。#375

**Comment by iThreeKing** [comment]
最近写项目一直用Python,认领校对 @antonia0912 @rainyear

**Comment by rainyear** [comment]
@iThreeKing 加到我们群里来啊~

**Comment by Zheaoli** [comment]
认领二教

**Comment by Zheaoli** [comment]
@rainyear 吼了，我的校对完成了，修改了四处一点小问题，请查阅 @antonia0912 @iThreeKing
