### ISSUE TITLE
Web 应用的未来：Heroku vs Docker

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3722]
* 原文链接：[It's The Future](https://circleci.com/blog/its-the-future/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/its-the-future.md)
  * PR 地址：#3726
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Hopsken** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Hopsken 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3726
