### ISSUE TITLE
我在编程初级阶段常犯的错误

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3723]
* 原文链接：[The Mistakes I Made As a Beginner Programmer](https://medium.com/@samerbuna/the-mistakes-i-made-as-a-beginner-programmer-ac8b3e54c312)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-mistakes-i-made-as-a-beginner-programmer.md)
  * PR 地址：#3730
  * 文章分类：**教程**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：12 分
  * 校对积分：4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kezhenxu94** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@kezhenxu94 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3730
