### ISSUE TITLE
 JavaScript 是如何工作的：对比 WebAssembly + 为什么在某些场景下它比 JavaScript 更合适

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3735]
* 原文链接：[How JavaScript works: A comparison with WebAssembly + why in certain cases it’s better to use it over JavaScript](https://blog.sessionstack.com/how-javascript-works-a-comparison-with-webassembly-why-in-certain-cases-its-better-to-use-it-d80945172d79)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-javascript-works-a-comparison-with-webassembly-why-in-certain-cases-its-better-to-use-it.md)
  * PR 地址：#3817
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by stormluke** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@stormluke 棒极啦 :tada:

**Comment by leviding** [comment]
@stormluke 翻译的怎么样了，严重超期了

**Comment by stormluke** [comment]
抱歉 忘了翻译……周六会补上

**Comment by fanyijihua** [comment]
PR 地址：#3817
