### ISSUE TITLE
轻松管理 Swift 项目中的不同环境

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3736]
* 原文链接：[Managing different environments in your Swift project with ease](https://medium.com/flawless-app-stories/manage-different-environments-in-your-swift-project-with-ease-659f7f3fb1a6)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/manage-different-environments-in-your-swift-project-with-ease.md)
  * PR 地址：#3767
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by melon8** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@melon8 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3767
