### ISSUE TITLE
部署！=发布（第二部分）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3739]
* 原文链接：[Deploy != Release (Part 2)](https://blog.turbinelabs.io/deploy-not-equal-release-part-two-acbfe402a91c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/deploy-not-equal-release-part-two.md)
  * PR 地址：3752
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3752

**Comment by fanyijihua** [comment]
PR 地址：#3869
