### ISSUE TITLE
使用 Go 语言的流模式来解析 DrugBank 的 XML（或者任何大的 XML 文件）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3746]
* 原文链接：[Parsing DrugBank XML (or any large XML file) in streaming mode in Go](http://bionics.it/posts/parsing-drugbank-xml-or-any-large-xml-file-in-streaming-mode-in-go)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/parsing-drugbank-xml-or-any-large-xml-file-in-streaming-mode-in-go.md)
  * PR 地址：#3849
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by steinliber** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@steinliber 棒极啦 :tada:

**Comment by steinliber** [comment]
翻译完成 @fanyijihua
