### ISSUE TITLE
论 Android 中 Span 的正确打开方式

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3747]
* 原文链接：[Underspanding spans](https://medium.com/google-developers/underspanding-spans-1b91008b97e4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/underspanding-spans.md)
  * PR 地址：#3774
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分 质量不够高 2 分
  * 校对积分：1.5 分 dandyxu 校对不认真 1 分，ALVINYEH 认真 2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
翻译认领。

**Comment by fanyijihua** [comment]
@tanglie1993 棒极啦 :tada:
