### ISSUE TITLE
JavaScript 是如何工作的：Service Worker 的生命周期与用例

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3748]
* 原文链接：[How JavaScript works: Service Workers, their lifecycle and use cases](https://blog.sessionstack.com/how-javascript-works-service-workers-their-life-cycle-and-use-cases-52b19ad98b58)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-javascript-works-service-workers-their-life-cycle-and-use-cases.md)
  * PR 地址：#3874
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by talisk** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@talisk 棒极啦 :tada:

**Comment by leviding** [comment]
@talisk 翻译的怎么样啦

**Comment by talisk** [comment]
@leviding 一会儿就发出来
