### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by funtrip** [xitu/gold-miner#3750]
- 原文链接：10 cheat codes for designing User Interfaces
- 简要介绍：10个关于 UI 设计的小技巧，主要是关于字体层次和配色

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
一篇很棒的文章，就是有人翻译过了 http://caiyunsky.me/2018/03/19/design/
感谢推荐，欢迎推荐更多文章 ❤️
