### ISSUE TITLE
在 Google I/O 2018 观看 Flutter 的正确姿势

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3751]
* 原文链接：[How to watch Flutter at Google I/O 2018](https://medium.com/flutter-io/how-to-watch-flutter-at-google-i-o-2018-c7e082fc836f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-watch-flutter-at-google-i-o-2018.md)
  * PR 地址：#3753
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：0.5 天
  * 校对时间：0.5 天
  * 翻译积分：1.5 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wzasd** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@wzasd 棒极啦 :tada:

**Comment by faintz** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
PR 地址：#3753
