### ISSUE TITLE
Java 桥接方法详解

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3759]
* 原文链接：[Java bridge methods explained](http://stas-blogspot.blogspot.jp/2010/03/java-bridge-methods-explained.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/java-bridge-methods-explained.md)
  * PR 地址：#3763
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kezhenxu94** [comment]
必须 翻译认领 啊

**Comment by fanyijihua** [comment]
@kezhenxu94 棒极啦 :tada:
