### ISSUE TITLE
JavaScript 是如何工作的：Web 推送通知的机制

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3761]
* 原文链接：[How JavaScript works: the mechanics of Web Push Notifications](https://blog.sessionstack.com/how-javascript-works-the-mechanics-of-web-push-notifications-290176c5c55d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-javascript-works-the-mechanics-of-web-push-notifications.md)
  * PR 地址：#3770
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天 Starriers 4 分
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分 weberpan 3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3770
