### ISSUE TITLE
更为详细的地图、导航和助手功能 —— Google I/O 2018 的 Android 应用更新

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3762]
* 原文链接：[Google I/O 2018 for Android updated w/ more detailed map, navigation, & Assistant Action](https://9to5google.com/2018/05/02/google-i-o-2018-for-android-updated-w-more-detailed-map-navigation-assistant-action/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/google-i-o-2018-for-android-updated-w-more-detailed-map-navigation-assistant-action.md)
  * PR 地址：#3766
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：0.5 天
  * 校对时间：0.5 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sisibeloved** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@sisibeloved 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3766
