### ISSUE TITLE
在 Laravel 应用程序之间共享数据库

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3771]
* 原文链接：[Sharing databases between Laravel applications](https://dyrynda.com.au/blog/sharing-databases-between-laravel-applications)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/sharing-databases-between-laravel-applications.md)
  * PR 地址：#3892
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by elliott-zhao** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@elliott-zhao 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3892
