### ISSUE TITLE
JavaScript 是如何工作的：深入网络层 + 如何优化性能和安全

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3776]
* 原文链接：[How JavaScript Works: Inside the Networking Layer + How to Optimize Its Performance and Security](https://blog.sessionstack.com/how-javascript-works-inside-the-networking-layer-how-to-optimize-its-performance-and-security-f71b7414d34c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-javascript-works-inside-the-networking-layer-how-to-optimize-its-performance-and-security.md)
  * PR 地址：#3858
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by FateZeros** [comment]
@fanyijihua 翻译认领

**Comment by fanyijihua** [comment]
@FateZeros 棒极啦 :tada:

**Comment by Hopsken** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Hopsken 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3858
