### ISSUE TITLE
JavaScript 是如何工作的：CSS 和 JS 动画背后的原理 + 如何优化性能

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3777]
* 原文链接：[How JavaScript works: Under the hood of CSS and JS animations + how to optimize their performance](https://blog.sessionstack.com/how-javascript-works-under-the-hood-of-css-and-js-animations-how-to-optimize-their-performance-db0e79586216)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-javascript-works-under-the-hood-of-css-and-js-animations-how-to-optimize-their-performance.md)
  * PR 地址：#3829
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wznonstop** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@wznonstop 棒极啦 :tada:

**Comment by wznonstop** [comment]
@leviding @fanyijihua 这周项目要加班，来不及翻译了，麻烦重新认领翻译，不好意思

**Comment by NoName4Me** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@NoName4Me 棒极啦 :tada:
