### ISSUE TITLE
BigQuery 中的比特币：使用公共数据分析区块链

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3778]
* 原文链接：[Bitcoin in BigQuery: blockchain analytics on public data](https://cloud.google.com/blog/big-data/2018/02/bitcoin-in-bigquery-blockchain-analytics-on-public-data)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/bitcoin-in-bigquery-blockchain-analytics-on-public-data.md)
  * PR 地址：#3813
  * 文章分类：**区块链**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LeopPro** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@LeopPro 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3813
