### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by whuzxq** [xitu/gold-miner#3790]
原文链接：https://medium.freecodecamp.org/this-is-why-we-need-to-bind-event-handlers-in-class-components-in-react-f7ea1a6f93eb
简要介绍：为什么我们需要在react的class中绑定this【前端】

希望自己翻译^ ^

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ
