### ISSUE TITLE
使用 Puppeteer 和 Jest 测试你的 React 应用

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3791]
* 原文链接：[Testing your React App with Puppeteer and Jest](https://blog.bitsrc.io/testing-your-react-app-with-puppeteer-and-jest-c72b3dfcde59)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/testing-your-react-app-with-puppeteer-and-jest.md)
  * PR 地址：#3803
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8 分 jonjia 7
  * 校对积分：1-3 分 weberpan 2 sunhaokk 1
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@jonjia

**Comment by jonjia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jonjia 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3803
