### ISSUE TITLE
⚛ React 状态管理工具博物馆

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3792]
* 原文链接：[⚛ The React State Museum: ⚡️View the hottest state management libs for React](https://hackernoon.com/the-react-state-museum-a278c726315)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-react-state-museum.md)
  * PR 地址：#3834
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-8 分
  * 校对积分：2-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@jonjia

**Comment by jonjia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jonjia 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3833
