### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by kezhenxu94** [xitu/gold-miner#3795]
原文链接：http://javabypatel.blogspot.hk/2016/01/infinite-loop-in-hashmap.html
文章标题：HashMap 的死循环
推荐理由：关于 Java 中 HashMap 在多线程环境下产生死循环的原因分析

如果可能的话，assign 给我

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
这篇拿出来在掘金上阅读效果可能不太好，没有图放大。如果有其他的换一篇吧
