### ISSUE TITLE
我们距离 Babel 7.0 发布很近了。这里是所有我们一直在做的很酷的事情。

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3797]
* 原文链接：[We’re nearing the 7.0 Babel release. Here’s all the cool stuff we’ve been doing.](https://medium.freecodecamp.org/were-nearing-the-7-0-babel-release-here-s-all-the-cool-stuff-we-ve-been-doing-8c1ade684039)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/were-nearing-the-7-0-babel-release-here-s-all-the-cool-stuff-we-ve-been-doing.md)
  * PR 地址：#3927
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-9 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xueshuai** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@xueshuai 棒极啦 :tada:

**Comment by leviding** [comment]
@xueshuai 这篇翻译的怎么样啦~

**Comment by xueshuai** [comment]
这两天在办婚礼，太忙了，明天回北京，就翻译好，实在不好意思

发自我的 iPhone

在 2018年5月27日，17:47，LeviDing <notifications@github.com<mailto:notifications@github.com>> 写道：


@xueshuai<https://github.com/xueshuai> 这篇翻译的怎么样啦~

**Comment by leviding** [comment]
@xueshuai 好的，不急，辛苦啦

**Comment by fanyijihua** [comment]
PR 地址：#3927
