### ISSUE TITLE
如何在 5 分钟之内写出一个不错的 loading 界面

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3799]
* 原文链接：[How to Build a Delightful Loading Screen in 5 Minutes](https://medium.freecodecamp.org/how-to-build-a-delightful-loading-screen-in-5-minutes-847991da509f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-build-a-delightful-loading-screen-in-5-minutes.md)
  * PR 地址：#3801
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@whuzxq 你的哈

**Comment by whuzxq** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@whuzxq 棒极啦 :tada:
