### ISSUE TITLE
教程：使用 Passport.js 来做后台用户验证

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#380]
原文链接：[Node Hero - Node.js Authentication using Passport.js](https://blog.risingstack.com/node-hero-node-js-authentication-passport-js/)
掘金链接：[教程：使用 Passport.js 来做后台用户验证](http://gold.xitu.io/entry/574836d7c26a38006c5adbcd)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/node-hero-node-js-authentication-passport-js.md)

翻译时间：5天
校对时间：3天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by circlelove** [comment]
抢

**Comment by antonia0912** [comment]
@circlelove 已经添加了markdown文件，可以开始翻译啦

**Comment by godofchina** [comment]
@antonia0912 校对 占坑

**Comment by circlelove** [comment]
@antonia0912  报告羊羊，我连滚带爬的翻译完了

**Comment by antonia0912** [comment]
@circlelove ok， @godofchina 可以来校对了

**Comment by antonia0912** [comment]
@circlelove 你又没发PR。。。。

**Comment by circlelove** [comment]
我去，我傻了= = ！ @ antonia0912

**Comment by wild-flame** [comment]
校对+1

**Comment by godofchina** [comment]
@circlelove  求校对地址

**Comment by antonia0912** [comment]
@wild-flame @godofchina [校对地址](https://github.com/xitu/gold-miner/pull/399/files?diff=split)

**Comment by wild-flame** [comment]
校对完毕。感觉格式上的问题比较多：D，还有一些术语上的，别的都还不错。
