### ISSUE TITLE
这就是为什么我们需要在 React 的类组件中为事件处理程序绑定 this

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3804]
* 原文链接：[This is why we need to bind event handlers in Class Components in React](https://medium.freecodecamp.org/this-is-why-we-need-to-bind-event-handlers-in-class-components-in-react-f7ea1a6f93eb)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/this-is-why-we-need-to-bind-event-handlers-in-class-components-in-react.md)
  * PR 地址：#3814
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：2-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@whuzxq

**Comment by whuzxq** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@whuzxq 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3814
