### ISSUE TITLE
Awesome Flutter

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3805]
* 翻译认领：[Awesome Flutter](https://github.com/xitu/awesome-flutter)
  * **校对认领地址**：https://github.com/xitu/awesome-flutter/pulls
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：4-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@LeeSniper 这篇翻译的怎么样啦~

**Comment by LeeSniper** [comment]
@leviding 正在翻译，里面好多库只有简短的描述，翻译起来有点难度，最近这几天弄完吧。

**Comment by leviding** [comment]
@LeeSniper 好的，辛苦了

**Comment by LeeSniper** [comment]
@leviding 翻译完成，已经[提交到 Awesome Flutter 的仓库了](https://github.com/xitu/awesome-flutter/pull/1)。好多专有名词还有库的名称，感觉翻译也不是不翻译也不是。希望校对的同学更给力一点，帮我好好改一改吧。

**Comment by leviding** [comment]
@LeeSniper 赞 👍

**Comment by SpielbergGao** [comment]
@leviding 校对认领

**Comment by leviding** [comment]
@SpielbergGao ok

**Comment by leviding** [comment]
@SpielbergGao 记得进行校对哈

**Comment by androidxiao** [comment]
@leviding  校对认领

**Comment by leviding** [comment]
@androidxiao 终于等到你
