### ISSUE TITLE
如何在安卓应用中使用 TensorFlow Mobile

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3806]
* 原文链接：[How to Use TensorFlow Mobile in Android Apps](https://code.tutsplus.com/tutorials/how-to-use-tensorflow-mobile-in-android-apps--cms-30957?utm_source=mobiledevweekly&utm_medium=email)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-use-tensorflow-mobile-in-android-apps.md)
  * PR 地址：#3819
  * 文章分类：**机器学习**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：3-5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luochen1992** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@luochen1992 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3819
