### ISSUE TITLE
使用 Span 来修改文本样式的优质体验

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3807]
* 原文链接：[Spantastic text styling with Spans](https://medium.com/google-developers/spantastic-text-styling-with-spans-17b0c16b4568)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/spantastic-text-styling-with-spans.md)
  * PR 地址：#3853
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-8 分
  * 校对积分：1-3 分 luochen1992 2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wzasd** [comment]
认领翻译 @leviding

**Comment by fanyijihua** [comment]
@wzasd 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3853
