### ISSUE TITLE
在浏览器里使用 TenserFlow.js 实时估计人体姿态

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3808]
* 原文链接：[Real-time Human Pose Estimation in the Browser with TensorFlow.js](https://medium.com/tensorflow/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js-7dd0bc881cd5)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js.md)
  * PR 地址：#3815
  * 文章分类：**机器学习**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-8 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by NoName4Me** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@NoName4Me 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3815
