### ISSUE TITLE
监测 iPhone 的「低电量模式」

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#381]
原文链接：[Detecting low power mode](http://useyourloaf.com/blog/detecting-low-power-mode/)
掘金链接：[监测 iPhone 的「低电量模式」](http://gold.xitu.io/entry/574c3c1a2e958a00692f1940/)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/detecting-low-power-mode.md)

翻译时间：5天
校对时间：3天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zheaoli** [comment]
认领翻译

**Comment by antonia0912** [comment]
@Zheaoli 收到~

**Comment by wild-flame** [comment]
又没有抢到翻译，申请一个校对吧。。

**Comment by antonia0912** [comment]
@Zheaoli 请译者翻译完了记得at校对者 @wild-flame 来校对哈~

**Comment by Zheaoli** [comment]
@antonia0912 Sir yes sir

**Comment by antonia0912** [comment]
@wild-flame [校对地址](https://github.com/xitu/gold-miner/pull/383/files?diff=split)

**Comment by Zheaoli** [comment]
@wild-flame 低电量模式翻译错误已经修改，
@antonia0912 羊姐姐，麻烦merge一下最新的PR
