### ISSUE TITLE
不越狱探索 App

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3810]
* 原文链接：[Exploring Apps Without Jailbreaking](https://medium.com/@nathangitter/exploring-apps-without-jailbreaking-e932904f9863)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/exploring-apps-without-jailbreaking.md)
  * PR 地址：#3877
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-8 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by melon8** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@melon8 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3877
