### ISSUE TITLE
从零开始，在 Redux 中构建时间旅行式调试

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3812]
* 原文链接：[Build time travel debugging in Redux from scratch](https://levelup.gitconnected.com/build-time-travel-debugging-in-redux-from-scratch-665fea8fc6cc)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/build-time-travel-debugging-in-redux-from-scratch.md)
  * PR 地址：#3910
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by weberpan** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@weberpan 棒极啦 :tada:

**Comment by weberpan** [comment]
最近还是很忙，我争取这周末两天翻译完 @leviding

**Comment by leviding** [comment]
@weberpan 好的

**Comment by fanyijihua** [comment]
PR 地址：#3910
