### ISSUE TITLE
React 应用的性能优化之路

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#382]
原文链接：[Performance optimisations for React applications](https://medium.com/@alexandereardon/performance-optimisations-for-react-applications-b453c597b191#.cymwuepwo)
掘金链接：[React 应用的性能优化之路](http://gold.xitu.io/entry/574574102b51e900697b3817)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/performance-optimisations-for-react-applications.md)

翻译时间：7天
校对时间：4天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by woota** [comment]
收了

**Comment by antonia0912** [comment]
@woota ok

**Comment by Zheaoli** [comment]
预定个校对吧，我要刷分。。。。。。。。。

**Comment by malcolmyu** [comment]
校对+1，羊三怎么推荐原文文章啊，直接在掘金上推荐么

**Comment by antonia0912** [comment]
@malcolmyu 直接分享到掘金就好啦  不是co-editor的话没有分享权限 先去个人主页申请 然后告诉我掘金用户名 我优先通过，话说人家还没翻译完呢你们就认领校对。。。。

**Comment by malcolmyu** [comment]
@antonia0912 没办法抢不到翻译只能抢校对了。。。攒点积分兑换章鱼猫🌚

**Comment by woota** [comment]
@antonia0912 @Zheaoli @malcolmyu 翻译完成。

**Comment by malcolmyu** [comment]
校完了，翻译的不错 👍🏿

**Comment by antonia0912** [comment]
@Zheaoli [校对地址](https://github.com/xitu/gold-miner/pull/398/files?diff=split) ， @Zheaoli 收到了

**Comment by Zheaoli** [comment]
@antonia0912 二校OK，建议给译者多加分，，，翻译的确蛮不容易

**Comment by woota** [comment]
@malcolmyu @Zheaoli 感谢二位抬爱！二位辛苦了！！！

**Comment by Zheaoli** [comment]
@woota 都是为羊三姐打工的，彼此就别这么多客套了，Hhhhhhhh
