### ISSUE TITLE
Swift 中的内存泄漏

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3821]
* 原文链接：[Memory Leaks in Swift: Unit Testing and other tools to avoid them.](https://medium.com/flawless-app-stories/memory-leaks-in-swift-bfd5f95f3a74)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/memory-leaks-in-swift.md)
  * PR 地址：#3859
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：4-7 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by RickeyBoy** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@RickeyBoy 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3859

**Comment by RickeyBoy** [comment]
@leviding 掘金链接 https://juejin.im/post/5b07a1c251882538914a5d3e，感谢！
