### ISSUE TITLE
30 分钟 Python 爬虫教程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3822]
* 原文链接：[30-minute Python Web Scraper](https://hackernoon.com/30-minute-python-web-scraper-39d6d038e5da)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/30-minute-python-web-scraper.md)
  * PR 地址：#3826
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分 kezhenxu94 3 分
  * 校对积分：0.5-1.5 分 luochen1992 1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kezhenxu94** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@kezhenxu94 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3826
