### ISSUE TITLE
带你领略 ConstraintLayout 1.1 的新功能

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3830]
* 原文链接：[Introducing Constraint Layout 1.1](https://medium.com/google-developers/introducing-constraint-layout-1-1-d07fc02406bc)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/introducing-constraint-layout-1-1.md)
  * PR 地址：#3844
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-4 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Moosphan** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Moosphan 棒极啦 :tada:
