### ISSUE TITLE
关于你的编程生涯的一些告诫

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3836]
* 原文链接：[Warning: Your programming career](https://medium.com/sololearn/warning-your-programming-career-b9579b3a878b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/warning-your-programming-career.md)
  * PR 地址：#3854
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：4-7 分 kezhenxu94 6 分
  * 校对积分：1-3 分 swants 和 luochen1992
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kezhenxu94** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@kezhenxu94 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3854
