### ISSUE TITLE
给人类的机器学习指南🤖👶

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3837]
* 原文链接：[Machine Learning for Humans🤖👶](https://medium.com/machine-learning-for-humans/why-machine-learning-matters-6164faf1df12)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-machine-learning-matters.md)
  * PR 地址：#3904
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：4-8 分
  * 校对积分：1-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sisibeloved** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@sisibeloved 棒极啦 :tada:

**Comment by leviding** [comment]
@sisibeloved 这篇翻译的怎么样啦~

**Comment by fanyijihua** [comment]
PR 地址：#3904

**Comment by sisibeloved** [comment]
@leviding 不好意思，有事耽搁了，已经翻完上传 PR 了
