### ISSUE TITLE
Swift 中的 Playground 驱动开发

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3838]
* 原文链接：[Playground driven development in Swift](https://medium.com/flawless-app-stories/playground-driven-development-in-swift-cf167489fe7b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/playground-driven-development-in-swift.md)
  * PR 地址：#3850
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：5-9 分
  * 校对积分：1-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ALVINYEH** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ALVINYEH 棒极啦 :tada:

**Comment by pmwangyang** [comment]
校对认领

**Comment by leviding** [comment]
@pmwangyang 在对应的 PR 下认领校对
