### ISSUE TITLE
支撑现代存储系统的算法

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3842]
* 原文链接：[Algorithms Behind Modern Storage Systems](https://queue.acm.org/detail.cfm?id=3220266)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/algorithms-behind-modern-storage-systems.md)
  * PR 地址：#3907
  * 文章分类：**算法**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：8-12 分
  * 校对积分：1-5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LeopPro** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@LeopPro 棒极啦 :tada:

**Comment by leviding** [comment]
@LeopPro 这篇翻译的怎么样啦~

**Comment by LeopPro** [comment]
@leviding 抱歉超过deadline了。
前段时间在忙软考，加之这篇文章难度比较大，翻译进度稍慢。
目前已翻译完成 4/5，再有1-2天就可以搞定。
可以在我个人fork的仓库查看当前翻译进度：https://github.com/LeopPro/gold-miner/commit/142ee66438a6d2f61aeefdeae081b9cac64b8a45

**Comment by leviding** [comment]
@LeopPro 好的哈，这篇有点长，你按照你的速度来就可以了。

**Comment by fanyijihua** [comment]
PR 地址：#3907

**Comment by LeopPro** [comment]
@leviding 翻译完了，https://queue.acm.org/上面的文章都不错，含金量很高。但是难度挺大的。

**Comment by leviding** [comment]
@LeopPro Get，辛苦啦
