### ISSUE TITLE
什么是 JavaScript 生成器？如何使用生成器？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3846]
* 原文链接：[What are JavaScript Generators and how to use them](https://codeburst.io/what-are-javascript-generators-and-how-to-use-them-c6f2713fd12e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-are-javascript-generators-and-how-to-use-them.md)
  * PR 地址：#3932
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by lsvih** [comment]
这篇还剩一点，这两天比较忙，要拖个1-2天

**Comment by leviding** [comment]
@lsvih ok‘’

**Comment by fanyijihua** [comment]
PR 地址：#3932
