### ISSUE TITLE
创造华丽 UI 的 7 个规则（Part 1）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3847]
* 原文链接：[7 Rules for Creating Gorgeous UI (Part 1)](https://medium.com/@erikdkennedy/7-rules-for-creating-gorgeous-ui-part-1-559d4e805cda)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/7-rules-for-creating-gorgeous-ui-part-1.md)
  * PR 地址：#3885
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：5-8 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#3885
