### ISSUE TITLE
在 Android P 中使用默认的 TLS 来保护你的用户

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3851]
* 原文链接：[Protecting users with TLS by default in Android P](https://android-developers.googleblog.com/2018/04/protecting-users-with-tls-by-default-in.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/protecting-users-with-tls-by-default-in.md)
  * PR 地址：#3866
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hanliuxin5** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@hanliuxin5 棒极啦 :tada:

**Comment by z3896823** [comment]
忘了认领，，其实我已经翻译完了。。那我认领校对吧

**Comment by androidxiao** [comment]
校对认领

**Comment by leviding** [comment]
@androidxiao 请在对应的 PR 下认领，在此处无法认领。
