### ISSUE TITLE
如何用Flexbox构建一个新闻网站布局

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#386]
原文链接：[How to Build a News Website Layout with Flexbox](http://webdesign.tutsplus.com/tutorials/how-to-build-a-news-website-layout-with-flexbox--cms-26611)
掘金链接：[How to Build a News Website Layout with Flexbox](http://gold.xitu.io/entry/574fc7a42e958a00683ff697)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-build-a-news-website-layout-with-flexbox.md)

翻译时间：5天
校对时间：4天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by joddiy** [comment]
羊哥，我认领

**Comment by antonia0912** [comment]
@joddiy ok

**Comment by galenyuan** [comment]
校对认领

**Comment by antonia0912** [comment]
@galenyuan 还没翻译完呢。。。。。你们这些不乖的宝宝。。。。

**Comment by galenyuan** [comment]
@antonia0912 ..先占上啊，不然就没了

**Comment by joddiy** [comment]
@antonia0912 羊哥，翻译完了。https://github.com/xitu/gold-miner/pull/390

**Comment by galenyuan** [comment]
校对完毕 @antonia0912 @joddiy

**Comment by joddiy** [comment]
@antonia0912 羊哥，第一位校对者意见修改完啦，有没有第二个啊？

**Comment by DeadLion** [comment]
@antonia0912  校对认领

**Comment by antonia0912** [comment]
@DeadLion ok [校对地址](https://github.com/xitu/gold-miner/pull/390/files?diff=split)

**Comment by DeadLion** [comment]
校对完成

**Comment by antonia0912** [comment]
@DeadLion 好的，辛苦了
