### ISSUE TITLE
使用 Sketch 和 Pixate 构建 Material Design 原型 - 第三部分

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#387]
原文链接：[HOW TO BUILD A MATERIAL DESIGN PROTOTYPE USING SKETCH AND PIXATE - PART THREE](http://createdineden.com/blog/post/how-to-build-a-material-design-prototype-using-sketch-and-pixate-part-three/?utm_source=androiddevdigest)
掘金链接：[使用 Sketch 和 Pixate 构建 Material Design 原型 - 第三部分](http://gold.xitu.io/entry/5751161c1532bc00647b5073)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-build-a-material-design-prototype-using-sketch-and-pixate-part-three.md)

翻译时间：8天
校对时间：6天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by xcc3641** [comment]
@antonia0912 三岁学姐~文章认领。

**Comment by Zheaoli** [comment]
@antonia0912 三岁学姐，我要和楼上 @xcc3641 进行py trade，所以校对预定

**Comment by rockzhai** [comment]
@antonia0912  我也来预定一波小三哥的校对，顺带trade.py @xcc3641 (●ˇ∀ˇ●)

**Comment by antonia0912** [comment]
@xcc3641 收到 等你PR

**Comment by antonia0912** [comment]
@xcc3641 兄弟开开门，羊哥让我问问你PR啥时候发（黑社会脸）

**Comment by xcc3641** [comment]
@antonia0912 
求饶，明天。

**Comment by xcc3641** [comment]
@rockzhai 
@Zheaoli 
完成翻译，各位小伙伴快去校对吧~

**Comment by antonia0912** [comment]
@Zheaoli @rockzhai 可以去校对啦  楼上译者已经给出PR地址啦  也辛苦我们的译者 @xcc3641 啦  来帝都羊哥给买喔喔奶糖

**Comment by Zheaoli** [comment]
@antonia0912 羊姐姐，我也要吃糖糖（就是恶意卖萌，其余人等不服打我啊

**Comment by rockzhai** [comment]
@antonia0912 羊咩咩姐姐，第一遍校对好了，晚上回去再看一遍，先抓紧去撸期末大作业了，嘿嘿嘿
ps：@Zheaoli  大兄弟加油(●ˇ∀ˇ●)

**Comment by Zheaoli** [comment]
@rockzhai 喵喵喵，今晚搞定

**Comment by Zheaoli** [comment]
@antonia0912 @rockzhai @xcc3641 二校check
