### ISSUE TITLE
Erlang 之禅第一部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3870]
* 原文链接：[As bad as anything else: Part 1](https://ferd.ca/the-zen-of-erlang.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-zen-of-erlang-1.md)
  * PR 地址：#3929
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：5-8 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by steinliber** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@steinliber 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3929
