### ISSUE TITLE
WWDC 2018：关于iOS 12、iPad Pro、新MacBooks或者更多产品的所有预测

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3873]
* 原文链接：[WWDC 2018: All the rumors on iOS 12, iPad Pro, new MacBooks and more](https://www.cnet.com/news/wwdc-2018-rumors-ios-12-new-macbook-air-ipad-pro-homepod/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/wwdc-2018-rumors-ios-12-new-macbook-air-ipad-pro-homepod.md)
  * PR 地址：#3879
  * 文章分类：**产品**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：4-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by dandyxu** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@dandyxu ok
