### ISSUE TITLE
让 Webpack 来帮你打包吧

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#388]
原文链接：[Webpack your bags](https://blog.madewithlove.be/post/webpack-your-bags/)
掘金链接：[让 Webpack 来帮你打包吧](http://gold.xitu.io/entry/574fe0ba79bc440052f68fea/)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/webpack-your-bags.md)

翻译时间：8天
校对时间：6天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zhangjd** [comment]
认领

**Comment by malcolmyu** [comment]
有人认领了还能认领么😂

**Comment by malcolmyu** [comment]
😂又晚了一步，认领校对吧

**Comment by antonia0912** [comment]
@Zhangjd 达仔翻译完圈 @malcolmyu 来校对哈

**Comment by L9m** [comment]
校对认领

**Comment by Zhangjd** [comment]
放假出去浪了，只能明天再交了。。

**Comment by antonia0912** [comment]
@malcolmyu @L9m [校对地址](https://github.com/xitu/gold-miner/pull/408/files?diff=split)
