### ISSUE TITLE
通过安全浏览保护WebView

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3881]
* 原文链接：[Protecting WebView with Safe Browsing](https://android-developers.googleblog.com/2018/04/protecting-webview-with-safe-browsing.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/protecting-webview-with-safe-browsing.md)
  * PR 地址：#3890
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：1 天
  * 校对时间：1 天
  * 翻译积分：1.5 分
  * 校对积分：0.5 分 jasonxia23
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by androidxiao** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@androidxiao 棒极啦 :tada:
