### ISSUE TITLE
情景活动感知识别的 Transition API 新特性面向全体开发者开放

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3882]
* 原文链接：[Activity Recognition’s new Transition API makes context-aware features accessible to all developers](https://android-developers.googleblog.com/2018/03/activity-recognitions-new-transition.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/activity-recognitions-new-transition.md)
  * PR 地址：#3926
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2.5 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#3925

**Comment by fanyijihua** [comment]
PR 地址：#3926
