### ISSUE TITLE
使用 styled-components 的 React 服务器端渲染极简指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3883]
* 原文链接：[The simple guide to server-side rendering React with styled-components](https://medium.com/styled-components/the-simple-guide-to-server-side-rendering-react-with-styled-components-d31c6b2b8fbf)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-simple-guide-to-server-side-rendering-react-with-styled-components.md)
  * PR 地址：#3889
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4.5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by elliott-zhao** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@elliott-zhao 棒极啦 :tada:
