### ISSUE TITLE
React Native 中使用转场动画！

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3884]
* 原文链接：[Animated Transition in React Native!](https://medium.com/react-native-motion/transition-challenge-9bc9fdef56c7)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/animated-transition-in-react-native.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4226
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by talisk** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@talisk 棒极啦 :tada:

**Comment by leviding** [comment]
@talisk 超期太久了，翻译的怎么样了

**Comment by leviding** [comment]
@talisk 翻译的怎么样了

**Comment by leviding** [comment]
@talisk 翻译的怎么样了？

**Comment by leviding** [comment]
@talisk 翻译的怎么样了？如果有事请早点说，可以释放哈。如果没有特殊的事，麻烦按时翻译完。

**Comment by fanyijihua** [comment]
PR 地址：#4226
