### ISSUE TITLE
Swift 的撤销操作

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#389]
原文链接：[Undo History in Swift](http://chris.eidhof.nl/post/undo-history-in-swift/)
掘金链接：[Swift 的撤销操作](http://gold.xitu.io/entry/574f0656a34131005942ea42)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/undo-history-in-swift.md)

翻译时间：5天
校对时间：4天
翻译积分：5
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zheaoli** [comment]
Swift，yeah，收了，0.0

**Comment by antonia0912** [comment]
@Zheaoli ok

**Comment by xcc3641** [comment]
= = 好久没有 Android 的文章了。挖个坑，占个校对。

**Comment by Zheaoli** [comment]
@antonia0912 初稿翻译完成 @xcc3641 麻烦译者进行校对啦

**Comment by Zheaoli** [comment]
@xcc3641 [校对地址](https://github.com/xitu/gold-miner/pull/391/files)

**Comment by xcc3641** [comment]
@Zheaoli 
我这里第一次校对完了，译者翻译的很好啊都有备注~

**Comment by Zheaoli** [comment]
@xcc3641 蛤，我刚刚上线就看到，我马上修改，另外，别夸我，我会骄傲的

**Comment by laobie** [comment]
@antonia0912 校对一个

**Comment by Zheaoli** [comment]
@laobie py trade+1

**Comment by antonia0912** [comment]
@laobie @xcc3641 收到！

**Comment by laobie** [comment]
@antonia0912 @Zheaoli 第一次校对完成，准备等译者修改好再看一遍
