### ISSUE TITLE
一个简单的 ES6 Promises 指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3895]
* 原文链接：[A Simple Guide to ES6 Promises](https://codeburst.io/a-simple-guide-to-es6-promises-d71bacd2e13a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-simple-guide-to-es6-promises.md)
  * PR 地址：#3908
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：5-7 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sophiayang1997** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@sophiayang1997 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3908
