### ISSUE TITLE
为什么 VueX 是前端与 API 之间的完美接口

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3896]
* 原文链接：[Why VueX Is The Perfect Interface Between Frontend and API](https://zendev.com/2018/05/21/vuex-perfect-interface-frontend-backend.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/vuex-perfect-interface-frontend-backend.md)
  * PR 地址：#3909
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：4-6.5 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhmhhu** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@zhmhhu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3909
