### ISSUE TITLE
[字幕翻译] James Bennett — 理解 Python 字节码 — PyCon 2018

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3897]
* 原视频地址：[James Bennett - A Bit about Bytes: Understanding Python Bytecode - PyCon 2018](https://www.youtube.com/watch?v=cSSpnq362Bk)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/understanding-python-bytecode-pycon-2018.md)
  * PR 地址：#3968
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：10-14 分 奖励积分 +3
  * 校对积分：1-5 分 奖励积分 +1~2
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cdpath** [comment]
🙋‍♂️

**Comment by leviding** [comment]
@cdpath OK 哒 ~

**Comment by leviding** [comment]
@cdpath 视频上传至百度云啦，翻译前先看下视频，对英文字幕的 MarkDown 文件做一下校对，如果有问题可以先对英文文件进行修改和 PR，然后再进行翻译，翻译好之后再对译文进行 PR。
百度云视频链接：https://pan.baidu.com/s/1I-1VaMK6M3nHQFjjiCCD0A
感谢贡献者 @JohnJiangLA

**Comment by leviding** [comment]
@cdpath 翻译的怎么样啦

**Comment by cdpath** [comment]
@leviding 今天搞定~

**Comment by leviding** [comment]
@cdpath 辛苦了，内容挺多的

**Comment by cdpath** [comment]
@leviding  出于质量考虑还要再延迟一天 😂

**Comment by leviding** [comment]
@cdpath 好好，辛苦啦 🤣

**Comment by leviding** [comment]
这个好了记得 PR 哈，后端小编周末给加到视频上

**Comment by cdpath** [comment]
@leviding 更啦
