### ISSUE TITLE
[字幕翻译] Andrew Godwin — Django 异步 — PyCon 2018

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3898]
* 原文链接：[Andrew Godwin - Taking Django Async - PyCon 2018](https://www.youtube.com/watch?v=-7taKQnndfo)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/talking-django-async-pycon-2018.md)
  * PR 地址：#3943
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：8-10 分 奖励积分 +3
  * 校对积分：1-3 分 奖励积分 +1~2
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
视频上传至百度云啦，翻译前先看下视频，对英文字幕的 MarkDown 文件做一下校对，如果有问题可以先对英文文件进行修改和 PR，然后再进行翻译，翻译好之后再对译文进行 PR。
百度云视频链接：https://pan.baidu.com/s/1I-1VaMK6M3nHQFjjiCCD0A
感谢贡献者 @JohnJiangLA

**Comment by geniusq1981** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@geniusq1981 棒极啦 :tada:

**Comment by leviding** [comment]
@geniusq1981 翻译的怎么样啦

**Comment by geniusq1981** [comment]
@leviding 校对是需要自己校对吗，还是其他人校对呢？

**Comment by leviding** [comment]
@geniusq1981 其他人校对
