### ISSUE TITLE
认领Chrome Devtools Tips & Tricks(markdown)

### ISSUE THREAD

**Issue by woota** [xitu/gold-miner#39]
自己从上个月开始就有翻译计划，抛个链接：https://github.com/woota/spring

**Comment by Glowin** [comment]
不好意思啊，这篇文章已经被@chemzqm 认领了 #19 ，麻烦你挑一个其他未被认领的文章吧。谢谢了。

看了你的翻译计划里面的译文，挑选的文章质量不错，翻的也很用心，快来加入我们吧 :+1:

**Comment by Glowin** [comment]
你好，现在挑选出来的文章已经被认领完了，但是这个翻译计划还是会一直更新维护下去，我新建了一个掘金翻译计划的微信群，并会在群里面通报翻译活动的最新进展，希望你能加一下我微信 Glowjiang，感谢你的支持和理解。

**Comment by Glowin** [comment]
@woota 早上好，我们又有一批新的文章等待你的翻译，欢迎来认领文章，谢谢啦。
