### ISSUE TITLE
[字幕翻译] 玛利亚塔·维加亚 — 什么是 Python 核心开发者？— PyCon 2018

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3900]
* 原文链接：[Mariatta Wijaya - What is a Python Core Developer? - PyCon 2018](https://www.youtube.com/watch?v=hhj7eb6TrtI)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-is-a-python-core-developer-pycon-2018.md)
  * PR 地址：#3919
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-6 分 奖励积分 +2
  * 校对积分：1-2.5 分 +1~2
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@elliott-zhao 视频上传至百度云啦，翻译前先看下视频，对英文字幕的 MarkDown 文件做一下校对，如果有问题可以先对英文文件进行修改和 PR，然后再进行翻译，翻译好之后再对译文进行 PR。
百度云视频链接：https://pan.baidu.com/s/1I-1VaMK6M3nHQFjjiCCD0A
感谢贡献者 @JohnJiangLA

**Comment by fanyijihua** [comment]
PR 地址：#3906

**Comment by fanyijihua** [comment]
PR 地址：#3918

**Comment by fanyijihua** [comment]
PR 地址：#3919
