### ISSUE TITLE
字幕翻译 Jack Diederich - HOWTO Write a Function - PyCon 2018

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3901]
* 原文链接：[Jack Diederich - HOWTO Write a Function - PyCon 2018](https://www.youtube.com/watch?v=rrBJVMyD-Gs)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-write-a-function-pycon-2018.md)
  * PR 地址：#
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：6-9 分 奖励积分 +3
  * 校对积分：1-3 分 +1~2
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnJiangLA** [comment]
翻译认领....

**Comment by fanyijihua** [comment]
@JohnJiangLA 棒极啦 :tada:

**Comment by leviding** [comment]
@JohnJiangLA 视频上传至百度云啦，翻译前先看下视频，对英文字幕的 MarkDown 文件做一下校对，如果有问题可以先对英文文件进行修改和 PR，然后再进行翻译，翻译好之后再对译文进行 PR。
百度云视频链接：https://pan.baidu.com/s/1I-1VaMK6M3nHQFjjiCCD0A

**Comment by leviding** [comment]
@JohnJiangLA 翻译的怎么样啦

**Comment by JohnJiangLA** [comment]
@leviding 捂脸，我加油，今明两天吧，自动翻译的有些地方要听。已炸....

**Comment by leviding** [comment]
@JohnJiangLA ok 🤣

**Comment by leviding** [comment]
@JohnJiangLA 怎么样啦

**Comment by leviding** [comment]
@JohnJiangLA 这篇怎么样了

**Comment by leviding** [comment]
@JohnJiangLA 你这进度怎么样了，要是不想翻译了就 close 🤣
