### ISSUE TITLE
为何前端开发如此不稳定

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3914]
* 原文链接：[Why is Front-End Development So Unstable?](http://www.breck-mckye.com/blog/2018/05/why-is-front-end-development-so-unstable/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-is-front-end-development-so-unstable.md)
  * PR 地址：#3976
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Colafornia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Colafornia 棒极啦 :tada:

**Comment by zhmhhu** [comment]
这篇文章很久没提交了

**Comment by Colafornia** [comment]
@zhmhhu 工作略忙，周末发PR
