### ISSUE TITLE
Why UX, UI, CX, IA, IxD, and Other Sorts of Design Are Dumb

### ISSUE THREAD

**Issue by zhmhhu** [xitu/gold-miner#3915]
- 原文链接：https://medium.muz.li/design-types-7d75839a20ea
- 简要介绍：为什么UX，UI，CX，IA，IxD和其他类型的设计都是愚蠢的

**Comment by leviding** [comment]
@zhmhhu 感谢推荐，这篇已经有一些译文了，例如 https://juejin.im/post/5b067ea66fb9a07a9d70bc2b
