### ISSUE TITLE
扫盲贴--PostCSS是什么？它能做什么？

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#392]
原文链接：[PostCSS – What It Is And What It Can Do](https://web-design-weekly.com/2016/06/04/postcss-what-it-is-and-what-it-can-do/)
掘金链接：[扫盲帖--PostCSS是什么？它能做什么？](http://gold.xitu.io/entry/57541c831532bc0064935e8b)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/postcss-what-it-is-and-what-it-can-do.md)

翻译时间：5天
校对时间：4天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zheaoli** [comment]
收了。。。。

**Comment by antonia0912** [comment]
@Zheaoli ok

**Comment by Zheaoli** [comment]
@antonia0912 初稿翻译完成，[校对地址](https://github.com/xitu/gold-miner/pull/391/commits/76b34ef7c8d535c07299f0733f71b64f82790419)不过不知道为啥两次的PR合并在一起了。。。。

**Comment by Zheaoli** [comment]
@antonia0912 [校对地址](https://github.com/Zheaoli/gold-miner/commit/03f3d42d51707b838a2b27d7386fb478b5f8f4c3)

**Comment by aidistan** [comment]
@antonia0912 申请校对

不是应该在 PR 里校对吗？怎么给的是 commit 的地址...

**Comment by JolsonZhu** [comment]
申请校对。

**Comment by antonia0912** [comment]
@JolsonZhu @aidistan 先不要校对哈  译者需要重新发PR

**Comment by Zheaoli** [comment]
@antonia0912 [更新校对地址](https://github.com/xitu/gold-miner/pull/411/files)
@JolsonZhu @aidistan 麻烦两位了

**Comment by antonia0912** [comment]
@aidistan @JolsonZhu [最终校对地址](https://github.com/xitu/gold-miner/pull/411/files?diff=split)

**Comment by aidistan** [comment]
校对完毕

**Comment by Zheaoli** [comment]
@aidistan 抄收，马上修改，不过，感觉好萌的校对啊

**Comment by JolsonZhu** [comment]
校对完成。第一次校对感觉你们都好厉害。。。

**Comment by Zheaoli** [comment]
@JolsonZhu 抄收，校对的很不错啊，赞~
