### ISSUE TITLE
关于 HomePod WWDC 的愿望清单: 测试版程序、新的语音资源、Echo 等功能

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3920]
* 原文链接：[HomePod WWDC Wish List: Beta program, new audio sources, Echo features](https://9to5mac.com/2018/05/29/homepod-12-wish-list/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/homepod-12-wish-list.md)
  * PR 地址：#3937
  * 文章分类：**产品**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4.5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by dandyxu** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@dandyxu 棒极啦 :tada:
