### ISSUE TITLE
watchOS 5 愿望清单：Apple Watch Podcasts、open Siri face 和更新 Control Center 等

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3921]
* 原文链接：[watchOS 5 Wish List: Apple Watch Podcasts, open Siri face, rethought Control Center, more](https://9to5mac.com/2018/04/04/watchos-5-wish-list/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/watchos-5-wish-list.md)
  * PR 地址：#3940
  * 文章分类：**产品**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by talisk** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@talisk 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3940
