### ISSUE TITLE
如何针对 Android 优化您的应用（Go 版）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3923]
* 原文链接：[How to optimize your app for Android (Go edition)](https://medium.com/googleplaydev/how-to-optimize-your-app-for-android-go-edition-f0d2bedf9e03)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-optimize-your-app-for-android-go-edition.md)
  * PR 地址：#3964
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：5-7 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hannahGu** [comment]
校对认领

**Comment by androidxiao** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@androidxiao 棒极啦 :tada:
