### ISSUE TITLE
如何避免拍脑袋想出的产品优先策略

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3924]
* 原文链接：[How to avoid opinion-based product prioritization](https://medium.com/googleplaydev/how-to-avoid-opinion-based-product-prioritization-d398fd047ab7)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-avoid-opinion-based-product-prioritization.md)
  * PR 地址：#3958
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：6-8 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by bobmayuze** [comment]
申请翻译

**Comment by fanyijihua** [comment]
@bobmayuze 棒极啦 :tada:
