### ISSUE TITLE
较为完整的 React.js / Vue.js 的性能比较 Part 2

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#393]
原文链接：["A fairer Vue of React" - Comparing React to Vue for dynamic tabular data, part 2](https://engineering.footballradar.com/a-fairer-vue-of-react-comparing-react-to-vue-for-dynamic-tabular-data-part-2/)
掘金链接：[较为完整的 React.js / Vue.js 的性能比较](http://gold.xitu.io/entry/574b026ba34131005917b40c)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/a-fairer-vue-of-react-comparing-react-to-vue-for-dynamic-tabular-data-part-2.md)
[校对地址](https://github.com/xitu/gold-miner/pull/400/files?diff=split)
翻译时间：5天
校对时间：4天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by galenyuan** [comment]
这文章分两部分的吧..
https://engineering.footballradar.com/from-a-react-point-of-vue-comparing-reactjs-to-vuejs-for-dynamic-tabular-data/
这里还有第一部分

**Comment by wild-flame** [comment]
翻译~

**Comment by antonia0912** [comment]
@galenyuan 看了part 1 感觉干货没有part 2 多，更像是做铺垫，你觉得呢

**Comment by antonia0912** [comment]
@wild-flame ok

**Comment by galenyuan** [comment]
@antonia0912 我觉得第一篇干货多一点，第二篇基本上就是展示第一篇的结果了

**Comment by antonia0912** [comment]
@galenyuan ok 因为我也不太懂技术，还是以你们的意见为主，第一篇也放到翻译计划，抢得到的话你可以翻译哈哈哈

**Comment by galenyuan** [comment]
@antonia0912 端午难得能陪媳妇..要不这篇就下手了...

**Comment by wild-flame** [comment]
@antonia0912 翻译完了，让小伙伴们来领校对吧：D [地址](https://github.com/xitu/gold-miner/pull/400/files) 帮你都粘过来了

@antonia0912 @galenyuan 我翻译完这篇文章说它是第一篇文章的改进：D，第一篇文章是在 Development mode 下面的，这篇是在 Production mode

**Comment by antonia0912** [comment]
@wild-flame 收到，part 1 的题目会让相应的译者做一下修改

**Comment by hikerpig** [comment]
认领校对

**Comment by antonia0912** [comment]
@hikerpig ok，校对地址已经补充在issue的description里啦

**Comment by JolsonZhu** [comment]
校对认领

**Comment by antonia0912** [comment]
@JolsonZhu ok，[校对地址](https://github.com/xitu/gold-miner/pull/400/files?diff=split)

**Comment by JolsonZhu** [comment]
校对完成，感觉这篇还有挺多可以改进的地方，但是明天有考试。。。过两天再来一次。

**Comment by wild-flame** [comment]
@hikerpig @JolsonZhu 收到啦，两位校对大大很给力。欢迎多多指出来，共同进步 。<(^_^)>

**Comment by wild-flame** [comment]
@JolsonZhu 等你再看一次以后，我就修改一遍然后就 pull request 了哈，不然重新提交批注就都没了就。

**Comment by JolsonZhu** [comment]
要是基本没啥大问题就pr了吧～这两天考试实在有点多，可能没时间再仔细校对了，sorry～

**Comment by wild-flame** [comment]
好的~~ @JolsonZhu 没关系 ：D 我是因为看你说还要再看一次来着。
