### ISSUE TITLE
或许你并不需要 Rust 和 WASM 来提升 JS 的执行效率 — 第一部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3930]
* 原文链接：[Maybe you don't need Rust and WASM to speed up your JS — Part 1](https://mrale.ph/blog/2018/02/03/maybe-you-dont-need-rust-to-speed-up-your-js.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/maybe-you-dont-need-rust-to-speed-up-your-js-1.md)
  * PR 地址：#3965
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@shery15 你的啦

**Comment by shery15** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@shery15 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3965
