### ISSUE TITLE
WOFF文件格式 1.0

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3934]
* 原文链接：[WOFF File Format 1.0](https://www.w3.org/TR/2012/REC-WOFF-20121213/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/recommendation-woff-2012-12-13.md)
  * PR 地址：#3982
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：8-12 分
  * 校对积分：0.5-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
这是要参与 W3C 文档的 i18n 了？

**Comment by zhmhhu** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@zhmhhu 棒极啦 :tada:

**Comment by leviding** [comment]
@lsvih 没有

**Comment by fanyijihua** [comment]
PR 地址：#3982
