### ISSUE TITLE
A Real-World Comparison of Front-End Frameworks with Benchmarks (2018 update)

### ISSUE THREAD

**Issue by zhmhhu** [xitu/gold-miner#3936]
- 原文链接：https://medium.freecodecamp.org/a-real-world-comparison-of-front-end-frameworks-with-benchmarks-e1cb62fd526c
- 简要介绍：同一基准下前端框架的真实比较（2018年更新）

**Comment by leviding** [comment]
@zhmhhu 收到，感谢推荐
