### ISSUE TITLE
八个造成 Android 应用内存泄露的原因

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#394]
原文链接：[Eight Ways Your Android App Can Leak Memory](http://blog.nimbledroid.com/2016/05/23/memory-leaks.html)
掘金链接：[八个造成 Android 应用内存泄露的原因](http://gold.xitu.io/entry/57566b52530fd30068151104)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/Eight-Ways-Your-Android-App-Can-Leak-Memory.md)

翻译时间：5天
校对时间：4天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by halibobo** [comment]
怎么认领？

**Comment by antonia0912** [comment]
@halibobo 要先发issue申请成我我们的译者才能参加呢，翻译计划怎么玩[点这里](https://github.com/xitu/gold-miner/blob/master/README.md)

**Comment by joddiy** [comment]
抢地主

**Comment by circlelove** [comment]
哈哈，我也想抢

**Comment by antonia0912** [comment]
@joddiy ok， @circlelove 下手晚了哈哈

**Comment by MiJack** [comment]
@mijack 校对认领

**Comment by joddiy** [comment]
@antonia0912 羊老师，我交作业了，https://github.com/xitu/gold-miner/pull/409

**Comment by antonia0912** [comment]
@joddiy 收到~ @circlelove 还校对吗？ @MiJack [校对地址](https://github.com/xitu/gold-miner/pull/409/files?diff=split)

**Comment by DeadLion** [comment]
@antonia0912  校对认领

**Comment by edvardHua** [comment]
@antonia0912 校对认领，估计应该是晚了

**Comment by antonia0912** [comment]
@joddiy  吼~[校对地址](https://github.com/xitu/gold-miner/pull/409/files?diff=split)， @edvardHua 下手晚了  下次吧哈哈哈

**Comment by DeadLion** [comment]
@antonia0912 是我的咩

**Comment by antonia0912** [comment]
@DeadLion 是你哒 我at错人啦。。。

**Comment by DeadLion** [comment]
@antonia0912  校稿完成

**Comment by antonia0912** [comment]
@MiJack 快喔honey  另一位校对者已经校对完啦  就等你啦

**Comment by joddiy** [comment]
@MiJack OK了不？

**Comment by MiJack** [comment]
改了一些，你看看需要修改吗？

**Comment by joddiy** [comment]
@antonia0912 羊老师，改完了！
