### ISSUE TITLE
将项目迁移到 Yarn 然后又迁回到 npm

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3947]
* 原文链接：[To Yarn and Back (to npm) Again](https://mixmax.com/blog/to-yarn-and-back-again-npm)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/to-yarn-and-back-again-npm.m)
  * PR 地址：#4045
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@Aladdin-ADD 你的

**Comment by leviding** [comment]
@Aladdin-ADD 来回复个

**Comment by Aladdin-ADD** [comment]
蛤？

**Comment by leviding** [comment]
2333 蛤蛤蛤

**Comment by leviding** [comment]
@Aladdin-ADD 翻译的怎么样了

**Comment by zhongdeming428** [comment]
这文章我看到好久了哈哈哈，译者消失了的话这篇也给我吧。 @leviding

**Comment by Aladdin-ADD** [comment]
Sorry, it looks like I don’t have time to do this.

**Comment by leviding** [comment]
@zhongdeming428 ok

**Comment by zhongdeming428** [comment]
翻译完成，PR地址：https://github.com/xitu/gold-miner/pull/4045
