### ISSUE TITLE
深度学习中所需的线性代数知识

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3948]
* 原文链接：[Linear Algebra for Deep Learning](https://towardsdatascience.com/linear-algebra-for-deep-learning-506c19c0d6fa)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/linear-algebra-for-deep-learning.md)
  * PR 地址：#3953
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3.5 天
  * 校对时间：1 天
  * 翻译积分：3-4.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by maoqyhz** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@maoqyhz 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3953
