### ISSUE TITLE
为什么 UX，UI，CX，IA，IxD 和其他类型的设计都是愚蠢的

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3949]
* 原文链接：[Why UX, UI, CX, IA, IxD, and Other Sorts of Design Are Dumb](https://medium.muz.li/design-types-7d75839a20ea)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/design-types-7d75839a20ea.md)
  * PR 地址：#3986
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhmhhu** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@zhmhhu 棒极啦 :tada:

**Comment by leviding** [comment]
@zhmhhu 翻译的怎么样了

**Comment by zhmhhu** [comment]
今天或明天可以完成 @leviding

**Comment by fanyijihua** [comment]
PR 地址：#3986
