### ISSUE TITLE
使用多重赋值与元组解包提升 Python 代码的可读性

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3959]
* 原文链接：[Multiple assignment and tuple unpacking improve Python code readability](http://treyhunner.com/2018/03/tuple-unpacking-improves-python-code-readability/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/tuple-unpacking-improves-python-code-readability.md)
  * PR 地址：#4019
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：4-6 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4019

**Comment by zhangshiqin** [comment]
校对认领

**Comment by lsvih** [comment]
@zhangshiqin 要到pr里去校对哈
