### ISSUE TITLE
申请译者

### ISSUE THREAD

**Issue by carlhong** [xitu/gold-miner#396]
目前大三，有上海市中级口译证书，喜欢新技术～

**Comment by antonia0912** [comment]
@carlhong 请问平时对哪一方面研究比较多呢  都从什么网站获取技术知识？有没有翻译过类似的英文技术文章？

**Comment by carlhong** [comment]
前端和安卓比较熟悉。通过rss订阅一些技术博客来了解新技术。没有翻译过技术文章。 @antonia0912

**Comment by antonia0912** [comment]
@carlhong 好的  请加我微信 antonia0912 我来拉你进译者群
