### ISSUE TITLE
一种更简单的途径在 Java 中进行函数式编程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3960]
* 原文链接：[An easier path to functional programming in Java](https://www.ibm.com/developerworks/library/j-java8idioms1/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/an-easier-path-to-functional-programming-in-java.md)
  * PR 地址：#3972
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4.5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by maoqyhz** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@maoqyhz 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3972
