### ISSUE TITLE
较为完整的 React.js / Vue.js 的性能比较 Part 1

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#397]
原文链接：["From a React point of Vue..." - comparing React.js to Vue.js for dynamic tabular data](https://engineering.footballradar.com/from-a-react-point-of-vue-comparing-reactjs-to-vuejs-for-dynamic-tabular-data/)
掘金链接：[较为完整的 React.js / Vue.js 的性能比较 Part 1](http://gold.xitu.io/entry/5758070679bc440061f64bbb)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/from-a-react-point-of-vue-comparing-reactjs-to-vuejs-for-dynamic-tabular-data.md)
[校对地址](https://github.com/xitu/gold-miner/pull/457/files?diff=split)
翻译时间：7天
校对时间：5天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by circlelove** [comment]
认

**Comment by antonia0912** [comment]
@circlelove ok

**Comment by circlelove** [comment]
羊羊羊终于出来了～ @antonia0912

**Comment by antonia0912** [comment]
@circlelove 再不交PR就带你去卧轨 哼（黑社会脸）

**Comment by circlelove** [comment]
@antonia0912  拖延扣4分

**Comment by liangbijie** [comment]
预约一波校对哈~~~

**Comment by antonia0912** [comment]
@circlelove 你知道的积分并不是最终目的  part 2 已经都分享到掘金了  你part 1 还这样拖着  我又没办法让别人接手  所以最好你赶紧交了 pr

**Comment by antonia0912** [comment]
@liangbijie 校对地址看issue描述里 可以开始校对了

**Comment by Gjetertaske** [comment]
申请校对

**Comment by jamweak** [comment]
我是新来的，申请校对~

**Comment by buccoji** [comment]
申请校对

**Comment by cyseria** [comment]
嗷嗷嗷，新人申请校对～

**Comment by antonia0912** [comment]
@jamweak 校对地址看issue描述， @cyseria sorry honey 每篇文章两个校对 这篇文章已经够啦  你等等别的文章呗~么么哒

**Comment by jamweak** [comment]
@antonia0912 校对完毕，问题较多。

**Comment by circlelove** [comment]
@antonia0912
