### ISSUE TITLE
Kubernetes 分布式应用部署和人脸识别 app 实例

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3970]
* 原文链接：[KUBERNETES DISTRIBUTED APPLICATION DEPLOYMENT WITH SAMPLE FACE RECOGNITION APP](https://skarlso.github.io/2018/03/15/kubernetes-distributed-application/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/kubernetes-distributed-application.md)
  * PR 地址：#3993
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：7-12 分
  * 校对积分：0.5-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by maoqyhz** [comment]
翻译认领

**Comment by fanyijihua** [comment]
PR 地址：#3993
