### ISSUE TITLE
一份在你的 iPhone 上平衡实用和美观的指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3971]
* 原文链接：[Beautility, My Ultimate iPhone Setup](https://betterhumans.coach.me/beautility-my-ultimate-iphone-setup-1b3dd0c588a0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/beautility-my-ultimate-iphone-setup.md)
  * PR 地址：#4091
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by 94haox** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@94haox 棒极啦 :tada:

**Comment by leviding** [comment]
@94haox 翻译的怎么样啦，超期啦

**Comment by 94haox** [comment]
@leviding  帮我延期一下，我今天晚上完成，最近换了工作，很烦😂

**Comment by leviding** [comment]
好的哈
