### ISSUE TITLE
Android 应用和游戏的无障碍开发介绍

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3973]
* 原文链接：[Introduction to accessibility for Android apps and games](https://medium.com/googleplaydev/introduction-to-accessibility-for-android-apps-and-games-d0e7af5384d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/introduction-to-accessibility-for-android-apps-and-games.md)
  * PR 地址：#3979
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by geniusq1981** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@geniusq1981 棒极啦 :tada:
