### ISSUE TITLE
Vue.js 还是 React？你会选择哪一个？为什么?

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3978]
* 原文链接：[Vue.js or React ? Which you would chose and why?](https://www.reddit.com/r/javascript/comments/8o781t/vuejs_or_react_which_you_would_chose_and_why/e01qn55/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/vuejs-or-react-which-you-would-chose-and-why.md)
  * PR 地址：#3983
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4.5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by allenlongbaobao** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@allenlongbaobao 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3983

**Comment by KyleLan329** [comment]
@leviding 校对认领
