### ISSUE TITLE
论 Rust 和 WebAssembly 对源码地址索引的极限优化

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3980]
* 原文链接：[Oxidizing Source Maps with Rust and WebAssembly](https://hacks.mozilla.org/2018/01/oxidizing-source-maps-with-rust-and-webassembly/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/oxidizing-source-maps-with-rust-and-webassembly.md)
  * PR 地址：#4047
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：12-15 分
  * 校对积分：1-5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by D-kylin** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@D-kylin 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4047
