### ISSUE TITLE
如何用 Android vitals 解决应用程序的质量问题

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3981]
* 原文链接：[How to fix app quality issues with Android vitals](https://medium.com/googleplaydev/how-to-fix-app-quality-issues-with-android-vitals-and-improve-performance-on-the-play-store-part-498dde9f4ef6)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-fix-app-quality-issues-with-android-vitals-and-improve-performance-on-the-play-store-part.md)
  * PR 地址：#4012
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-6 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LeeSniper** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@LeeSniper 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4012
