### ISSUE TITLE
PWA 再进化，可以生成一个安卓原生的 WebAPK 了

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3984]
* 原文链接：[WebAPKs on Android](https://developers.google.cn/web/fundamentals/integration/webapks?hl=zh-cn)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/webapks-on-android.md)
  * PR 地址：#3991
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Yuhanlolo** [comment]
@leviding 认领翻译

**Comment by fanyijihua** [comment]
@Yuhanlolo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#3991
