### ISSUE TITLE
怎样（以及为什么要）保持你的 Git 提交记录的整洁

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3985]
* 原文链接：[How (and why!) to keep your Git commit history clean](https://about.gitlab.com/2018/06/07/keeping-git-commit-history-clean/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/keeping-git-commit-history-clean.md)
  * PR 地址：#3996
  * 文章分类：**Git**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhongdeming428** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@zhongdeming428 棒极啦 :tada:

**Comment by zhongdeming428** [comment]
PR地址：https://github.com/xitu/gold-miner/pull/3996
