### ISSUE TITLE
推荐优秀文章

### ISSUE THREAD

**Issue by maoqyhz** [xitu/gold-miner#3989]
[The beginner's guide to contributing to a GitHub project](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project)
内容主要是新手如何贡献开源代码到 GitHub 的项目中。

**Comment by leviding** [comment]
@maoqyhz 很赞的推荐，明天发布上去。

**Comment by leviding** [comment]
@maoqyhz 已经发布啦，感谢推荐
