### ISSUE TITLE
使用 Python 进行自动化特征工程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3990]
* 原文链接：[Automated Feature Engineering in Python](https://towardsdatascience.com/automated-feature-engineering-in-python-99baf11cc219)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/automated-feature-engineering-in-python.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4262
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：5-8 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mingxing47** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@mingxing47 棒极啦 :tada:

**Comment by zhangshiqin** [comment]
校对认领

**Comment by leviding** [comment]
@zhangshiqin 校对认领是在对应的 PR 下进行的，译者教程有哈。如果想认领，请自行到 PR 下重新认领。

**Comment by leviding** [comment]
@mingxing47 翻译的怎么样啦，超期啦

**Comment by mingxing47** [comment]
@leviding 今天内提交哈~

**Comment by leviding** [comment]
@mingxing47 翻译的怎么样了？
