### ISSUE TITLE
为 GitHub 项目做出贡献的初学者指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3994]
* 原文链接：[The beginner's guide to contributing to a GitHub project](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-beginners-guide-to-contributing-to-a-github-project.md)
  * PR 地址：#4002
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sophiayang1997** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sophiayang1997 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4002
