### ISSUE TITLE
使用 PhpFastCache 提升网站性能

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3995]
* 原文链接：[Boost Your Website Performance With PhpFastCache](https://code.tutsplus.com/tutorials/boost-your-website-performance-with-phpfastcache--cms-31031)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/boost-your-website-performance-with-phpfastcache.md)
  * PR 地址：#4168
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by lsvih** [comment]
明天弄好

**Comment by leviding** [comment]
@lsvih 翻译的怎么样了？

**Comment by lsvih** [comment]
@leviding 抱歉，晚上传

**Comment by fanyijihua** [comment]
PR 地址：#4168
