### ISSUE TITLE
怎样使用简单的三角函数来创建更好的加载动画

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3997]
* 原文链接：[How you can use simple Trigonometry to create better loaders](https://uxdesign.cc/how-you-can-use-simple-trigonometry-to-create-better-loaders-32a573577eb4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-you-can-use-simple-trigonometry-to-create-better-loaders.md)
  * PR 地址：#4022
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5.5-7 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhongdeming428** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@zhongdeming428 棒极啦 :tada:

**Comment by zhongdeming428** [comment]
翻译完成 https://github.com/xitu/gold-miner/pull/4022
