### ISSUE TITLE
苹果公司如何修复 3D Touch

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#3998]
* 原文链接：[How Apple can fix 3D Touch](https://medium.com/@eliz_kilic/how-apple-can-fix-3d-touch-2f0ca5ea589e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-apple-can-fix-3d-touch.md)
  * PR 地址：#4010
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：1-2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Wangalan30** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Wangalan30 棒极啦 :tada:
