### ISSUE TITLE
认领Facebook iOS 应用是如何加速图片显示的

### ISSUE THREAD

**Issue by SatanWoo** [xitu/gold-miner#40]
个人介绍：

天猫无线工程师。
之前在Intel, 英语流利说从事JavaScript和iOS开发。

对iOS充满热情和能量，因此想要翻译这篇文章。

**Comment by Glowin** [comment]
你好，这篇文章被@skcheer 在昨天认领了#14 ，现在 iOS 的文章已经认领完了，你看看其他的文章有没有兴趣呢？

**Comment by SatanWoo** [comment]
我擦，一个都没了哎~

**Comment by Glowin** [comment]
你好，现在挑选出来的文章已经被认领完了，但是这个翻译计划还是会一直更新维护下去，我新建了一个掘金翻译计划的微信群，并会在群里面通报翻译活动的最新进展，希望你能加一下我微信 Glowjiang，感谢你的支持和理解。

**Comment by Glowin** [comment]
@SatanWoo 早上好，我们又有一些新的文章正在认领，请问你有兴趣翻译么？

**Comment by SatanWoo** [comment]
@Glowin 有！

**Comment by Glowin** [comment]
@SatanWoo 哈哈，加我微信 Glowjiang 我来拉你进群，你也可以 watching 我们这个 repo，我们认领文章的时候都是发 issue 的。

**Comment by SatanWoo** [comment]
Hi, 加你微信了，麻烦你通过下呗~
