### ISSUE TITLE
通过插图学习 Go 的并发

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4000]
* 原文链接：[Learning Go’s Concurrency Through Illustrations](https://medium.com/@trevor4e/learning-gos-concurrency-through-illustrations-8c4aff603b3)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/learning-gos-concurrency-through-illustrations.md)
  * PR 地址：#4001
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5.5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by elliott-zhao** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@elliott-zhao 棒极啦 :tada:
