### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by Colafornia** [xitu/gold-miner#4005]
- 原文链接：[Algorithms Behind Modern Storage Systems
](https://queue.acm.org/detail.cfm?id=3220266)
- 简要叙述：介绍了现代存储系统所使用的常见的读优化算法 B-Tree 和写优化算法 LSM-Tree。看起来翻译难度比较高，但干货很多。等后端大佬翻译

**Comment by leviding** [comment]
@Colafornia 已经翻译好了发布了呢 https://github.com/xitu/gold-miner/blob/master/TODO1/algorithms-behind-modern-storage-systems.md
