### ISSUE TITLE
绘图技巧的快速入门之：6 个绘图练习，让你立即上手！

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4007]
* 原文链接：[A quick beginner’s guide to drawing: 6 drawing exercises to get you started right now!](https://medium.com/personal-growth/a-quick-beginners-guide-to-drawing-58213877715e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-quick-beginners-guide-to-drawing.md)
  * PR 地址：#4024
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4024

**Comment by androidxiao** [comment]
校对认领

**Comment by leviding** [comment]
@androidxiao 在对应的 PR 下认领校对
