### ISSUE TITLE
Airbnb 中的 React Native

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4011]
* 原文链接：[React Native at Airbnb](https://medium.com/airbnb-engineering/react-native-at-airbnb-f95aa460be1c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/react-native-at-airbnb.md)
  * PR 地址：#4015
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ALVINYEH** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ALVINYEH 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4015
