### ISSUE TITLE
React 实现条件渲染的多种方式和性能考量

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4016]
* 原文链接：[8 React conditional rendering methods](https://blog.logrocket.com/conditional-rendering-in-react-c6b0e5af381e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/conditional-rendering-in-react.md)
  * PR 地址：#4055
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-6 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by IveHD** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@IveHD 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4055
