### ISSUE TITLE
About loop.run_until_complete()

### ISSUE THREAD

**Issue by wyzane** [xitu/gold-miner#4023]
hello, I am a beginner for async/await, and I want to ask for advice about the code.That is
loop = asyncio.get_event_loop()
loop.run_until_complete(test1())
loop.run_until_complete(test2()).
And I want to know wheather the functions test1(),test2() are running in order and wheather they are running in one EventLoop. I expect to receive your apply.Thank you

**Comment by leviding** [comment]
Hello @wyzane. Could you pleasee confirm that whether this is the right repo you want to submit the issue?
