### ISSUE TITLE
使用 Python 实现接缝裁剪算法

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4026]
* 原文链接：[Implementing Seam Carving with Python](https://karthikkaranth.me/blog/implementing-seam-carving-with-python?utm_source=mybridge&utm_medium=blog&utm_campaign=read_more)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/implementing-seam-carving-with-python.md)
  * PR 地址：#4096
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@caoyi0905 翻译的怎么样啦，超期啦

**Comment by fanyijihua** [comment]
PR 地址：#4096

**Comment by caoyi0905** [comment]
@leviding 抱歉延期了。。翻译已经提交
