### ISSUE TITLE
Envion 通过区块链采矿来支持可再生能源的发展

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4031]
* 原文链接：[Envion a name of mining in block chain to support renewable energy](https://medium.com/@darrellshelton964/envion-a-name-of-mining-in-block-chain-to-support-renewable-energy-e346aba33336)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/envion-a-name-of-mining-in-block-chain-to-support-renewable-energy.md)
  * PR 地址：#4064
  * 文章分类：**区块链**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by geniusq1981** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@geniusq1981 棒极啦 :tada:
