### ISSUE TITLE
从 Java EE 8 Security API 开始 — 第二部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4036]
* 原文链接：[Get started with the Java EE 8 Security API Part 2: Web authentication with HttpAuthenticationMechanis](https://www.ibm.com/developerworks/java/library/j-javaee8-security-api-2/index.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/j-javaee8-security-api-2.md)
  * PR 地址：#4042
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4042
