### ISSUE TITLE
能源行业聚焦基于区块链技术的加密货币

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4048]
* 原文链接：[Energy sector now on blockchain-based cryptocurrency](https://medium.com/@dungvinh50956756/energy-sector-now-on-blockchain-based-cryptocurrency-b89b09c8117e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/energy-sector-now-on-blockchain-based-cryptocurrency.md)
  * PR 地址：#4057
  * 文章分类：**区块链**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by geniusq1981** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@geniusq1981 棒极啦 :tada:
