### ISSUE TITLE
单元素组件模式简介

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4049]
* 原文链接：[Introducing the Single Element Pattern: Rules and best practices for creating reliable building blocks with React and other component-based libraries.](https://medium.freecodecamp.org/introducing-the-single-element-pattern-dfbd2c295c5d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/introducing-the-single-element-pattern.md)
  * PR 地址：#4065
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-6 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4065
