### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by langxuan** [xitu/gold-miner#405]
你好，我是Hal，申请加入掘金翻译计划。
CS硕士，毕业后已有2年多的服务器端开发经验，读研期间阅读了一定量的英文论文，选修过一些MOOC的英文课程，日常开发中遇到问题也会使用google、stackoverflow等寻找答案，总体上有一定的英文读写和翻译能力。
希望能够为掘金翻译计划贡献一点绵薄之力:-)

**Comment by antonia0912** [comment]
@langxuan 组织欢迎你~请加我微信 antonia0912，备注github ID，我来拉你进译者群~
