### ISSUE TITLE
ECMAScript 修饰器微指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4050]
* 原文链接：[A minimal guide to ECMAScript Decorators: A short introduction to “decorators” proposal in JavaScript with basic examples and little bit about ECMAScript](https://itnext.io/a-minimal-guide-to-ecmascript-decorators-55b70338215e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-minimal-guide-to-ecmascript-decorators.md)
  * PR 地址：#4164
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5-7 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@jonjia

**Comment by jonjia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jonjia 棒极啦 :tada:

**Comment by leviding** [comment]
@jonjia 翻译的怎么样了？

**Comment by jonjia** [comment]
@leviding 明天 18:00 前提交 PR

**Comment by fanyijihua** [comment]
PR 地址：#4164
