### ISSUE TITLE
Get started with the Java EE 8 Security API Part 4: Interrogating caller data with SecurityContext

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4052]
* 原文链接：[Get started with the Java EE 8 Security API Part 4: Interrogating caller data with SecurityContext](https://www.ibm.com/developerworks/java/library/j-javaee8-security-api-4/index.html?ca=drs-)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/j-javaee8-security-api-4.md)
  * PR 地址：#
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1.5 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:
