### ISSUE TITLE
Airbnb 中的 React Native （三）：建立一个跨平台的移动端团队

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4053]
* 原文链接：[Building a Cross-Platform Mobile Team: Adapting mobile for a world with React Native](https://medium.com/airbnb-engineering/building-a-cross-platform-mobile-team-3e1837b40a88)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/building-a-cross-platform-mobile-team.md)
  * PR 地址：#4063
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ALVINYEH** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ALVINYEH 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4063
