### ISSUE TITLE
编程语言和平台：一条被评论的推文串

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4054]
* 原文链接：[Programming Languages and Platforms: an annotated twitter thread](https://medium.learningbyshipping.com/platforms-and-languages-f41960af9ec)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/platforms-and-languages.md)
  * PR 地址：#4087
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-8 分
  * 校对积分：0.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cf020031308** [comment]
翻译认领

**Comment by cf020031308** [comment]
@leviding 上面标注说 8 分，但我看 `integrals.md` 中只加了 3 分，麻烦修正下。

**Comment by leviding** [comment]
@cf020031308 修改了，加的时候加错，不好意思。
