### ISSUE TITLE
如何在 Flutter 中设计 LinearLayout？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4056]
* 原文链接：[Flutter For Android Developers : How to design LinearLayout in Flutter ?](https://proandroiddev.com/flutter-for-android-developers-how-to-design-linearlayout-in-flutter-5d819c0ddf1a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/flutter-for-android-developers-how-to-design-linearlayout-in-flutter.md)
  * PR 地址：#4062
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5.5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by androidxiao** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@androidxiao 棒极啦 :tada:
