### ISSUE TITLE
海量视频时代下的内容发现之旅

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4059]
* 原文链接：[Discovery in the age of abundant video](https://medium.com/googleplaydev/discovery-in-the-age-of-abundant-video-294b1e3fe7c4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/discovery-in-the-age-of-abundant-video.md)
  * PR 地址：#4076
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Yuhanlolo** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@Yuhanlolo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4073

**Comment by fanyijihua** [comment]
PR 地址：#4075

**Comment by fanyijihua** [comment]
PR 地址：#4107
