### ISSUE TITLE
申请译者

### ISSUE THREAD

**Issue by aidistan** [xitu/gold-miner#406]
生物信息博士生，兼职从事全栈开发工作。能够顺利阅读各种英文文档和期刊论文，曾在博客里翻译过一点技术文章。目前感兴趣的领域是前端（尤其是 Vue）、后端（主要是 Ruby 和 Node）、设计和产品。

**Comment by antonia0912** [comment]
@aidistan 代表组织欢迎你~请加我微信 antonia0912，备注github ID，我来拉你进译者群~
