### ISSUE TITLE
关于 React Motion 的简要介绍

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4060]
* 原文链接：[A gentle introduction to React Motion](https://medium.com/@nashvail/a-gentle-introduction-to-react-motion-dc50dd9f2459)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-gentle-introduction-to-react-motion.md)
  * PR 地址：#
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by doctype233** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@doctype233 棒极啦 :tada:
