### ISSUE TITLE
通过 SSH 远程使用 Python 解释器来运行 Flask

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4061]
* 原文链接：[Running Flask with an SSH Remote Python Interpreter](https://blog.jetbrains.com/pycharm/2018/04/running-flask-with-an-ssh-remote-python-interpreter/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/running-flask-with-an-ssh-remote-python-interpreter.md)
  * PR 地址：#4072
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4072
