### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by Yuhanlolo** [xitu/gold-miner#4077]
- 原文链接：[Announcing the Alexa skill kit for Node JS](https://developer.amazon.com/blogs/post/Tx213D2XQIYH864/announcing-the-alexa-skills-kit-for-node-js)
- 简要介绍：这篇文章主要介绍了如何用 Node JS 开发 Alexa skill 。Alexa 就是2014 年面市的亚马逊智能音箱 Echo 中的语音机器人。这里的 skill 对于 Alexa 来说，就像 ios App 对于 iPhone、iPad，Android app 对于 Android 设备一样。亚马逊现在已经有一个很成熟的 skill 市场，类似于 app store，开发者们可以开发基于语音的 skill 或者为已有的 app 开发语音版本的 skill 上传到 Alexa skill market。虽然网上有一些介绍 Alexa skill 的中文博客，但大多数都是列出一些步骤和代码，并没有太多深入的讲解。这篇文章从后台的角度很详细地解释了 Alexa skill kit 的框架，包括每个 handler 是怎么执行的，代码例子，以及一些有用的链接。虽然文章是 2016 年的，但我没有找到它的文中翻译。希望小编采纳 :)

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@Yuhanlolo 感谢认真的推荐，任务已发布。
