### ISSUE TITLE
无头用户界面组件

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4079]
* 原文链接：[Headless User Interface Components](https://medium.com/merrickchristensen/headless-user-interface-components-565b0c0f2e18)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/headless-user-interface-components.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4213
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5.5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by leviding** [comment]
@Starriers 翻译的怎么样了？
