### ISSUE TITLE
移动技术在改善财务健康方面的作用

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4081]
* 原文链接：[The role of mobile technology in improving financial health](https://medium.com/googleplaydev/the-role-of-mobile-technology-in-improving-financial-health-f42b509f0433)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-role-of-mobile-technology-in-improving-financial-health.md)
  * PR 地址：#4121
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DateBro** [comment]
@leviding, 翻译认领

**Comment by fanyijihua** [comment]
@DateBro 棒极啦 :tada:
