### ISSUE TITLE
Kotlin 揭秘：理解速记 Lambda 语法

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4083]
* 原文链接：[Kotlin Demystified: Understanding Shorthand Lambda Syntax](https://medium.com/google-developers/kotlin-demystified-understanding-shorthand-lamba-syntax-74724028dcc5)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/kotlin-demystified-understanding-shorthand-lamba-syntax.md)
  * PR 地址：#4117
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by androidxiao** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@androidxiao 棒极啦 :tada:
