### ISSUE TITLE
React Native：回顾 Udacity 移动工程团队的使用历程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4089]
* 原文链接：[React Native: A retrospective from the mobile-engineering team at Udacity](https://engineering.udacity.com/react-native-a-retrospective-from-the-mobile-engineering-team-at-udacity-89975d6a8102)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/react-native-a-retrospective-from-the-mobile-engineering-team-at-udacity.md)
  * PR 地址：#4098
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：1 天
  * 校对时间：0.5 天
  * 翻译积分：周六翻译出来送大礼包，周日翻译出来送小礼包。
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**本文先发布，随后再根据校对意见进行更新。**

**Comment by pkuwwt** [comment]
认领 @leviding

**Comment by leviding** [comment]
@pkuwwt ok

**Comment by pkuwwt** [comment]
翻译完成 https://github.com/xitu/gold-miner/pull/4098 @leviding
