### ISSUE TITLE
Airbnb 中的 React Native（四）：React Native 退役

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4093]
* 原文链接：[Sunsetting React Native](https://medium.com/airbnb-engineering/sunsetting-react-native-1868ba28e30a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/sunsetting-react-native.md)
  * PR 地址：#4095
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ALVINYEH** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ALVINYEH 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4095
