### ISSUE TITLE
Airbnb 中的 React Native（五）：Airbnb 移动端路在何方？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4094]
* 原文链接：[What’s Next for Mobile at Airbnb: Bringing the best back to native](https://medium.com/airbnb-engineering/whats-next-for-mobile-at-airbnb-5e71618576ab)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/whats-next-for-mobile-at-airbnb.md)
  * PR 地址：#4115
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ALVINYEH** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ALVINYEH 棒极啦 :tada:
