### ISSUE TITLE
2018 年，如何选择最好的静态站点生成器

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4099]
* 原文链接：[How to Choose the Best Static Site Generator in 2018](https://medium.com/dailyjs/how-to-choose-the-best-static-site-generator-in-2018-98bff61c8184)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-choose-the-best-static-site-generator-in-2018.md)
  * PR 地址：#4103
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-8 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4103
