### ISSUE TITLE
Introducing JUnit 5 Part 1: The JUnit 5 Jupiter API

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4105]
* 原文链接：[Introducing JUnit 5 Part 1: The JUnit 5 Jupiter API](https://www.ibm.com/developerworks/library/j-introducing-junit5-part1-jupiter-api/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/j-introducing-junit5-part1-jupiter-api.md)
  * PR 地址：#
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：7-10 分
  * 校对积分：0.5-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sisibeloved** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@sisibeloved 棒极啦 :tada:
