### ISSUE TITLE
Robinhood 为什么使用 Airflow

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4110]
* 原文链接：[Why Robinhood uses Airflow](https://robinhood.engineering/why-robinhood-uses-airflow-aed13a9a90c8)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-robinhood-uses-airflow.md)
  * PR 地址：#4119
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cf020031308** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cf020031308 棒极啦 :tada:

**Comment by yqian1991** [comment]
@leviding 校对认领
