### ISSUE TITLE
在 Flutter 中实现微光闪烁效果

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4113]
* 原文链接：[Make shimmer effect in Flutter: Learn Flutter from UI challenges](https://medium.com/flutter-community/make-shimmer-effect-in-flutter-dbe7a1bfd980)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/make-shimmer-effect-in-flutter.md)
  * PR 地址：#4142
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-4 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by geniusq1981** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@geniusq1981 棒极啦 :tada:
