### ISSUE TITLE
怎样在 5 分钟内使 Drawer 在状态栏下可见？

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#412]
原文链接：[IT TAKES LESS THAN 5 MINS, MAKE THAT DRAWER VISIBLE UNDER YOUR STATUS BAR](http://matthewwear.xyz/no-excuses-it-takes-5-mins-make-that-drawer-visible-under-your-status-bar-2/)
掘金链接：[怎样在 5 分钟内使 Drawer 在状态栏下可见？](http://gold.xitu.io/entry/575e2b732e958a0059d0dff5)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/no-excuses-it-takes-5-mins-make-that-drawer-visible-under-your-status-bar-2.md)

翻译时间：4天
校对时间：3天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Goshin** [comment]
认领

**Comment by antonia0912** [comment]
@Goshin 新加入的译者只能从校对文章开始喔 还不能翻译呢  目前没有待校对的文章  要稍微等等

**Comment by Goshin** [comment]
好的，抱歉没搞清楚。

**Comment by ldhlfzysys** [comment]
认领

**Comment by antonia0912** [comment]
@ldhlfzysys ok 翻译完来圈 @Goshin 校对哈~

**Comment by antonia0912** [comment]
@Goshin 可以来校对啦 [校对地址](https://github.com/xitu/gold-miner/pull/415/files?diff=split)

**Comment by Goshin** [comment]
@antonia0912 好的

**Comment by aidistan** [comment]
认领校对

**Comment by antonia0912** [comment]
@aidistan ok [校对地址](https://github.com/xitu/gold-miner/pull/415/files?diff=split)
