### ISSUE TITLE
用 Flutter 写一个待办事项应用

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4124]
* 原文链接：[Making a Todo App with Flutter](https://medium.com/the-web-tub/making-a-todo-app-with-flutter-5c63dab88190)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/making-a-todo-app-with-flutter.md)
  * PR 地址：#4147
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：5-7 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DateBro** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@DateBro 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4144

**Comment by fanyijihua** [comment]
PR 地址：#4147
