### ISSUE TITLE
Javascript（ES6）Generator 入门

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4127]
* 原文链接：[A Simple Guide to Understanding Javascript (ES6) Generators](https://medium.com/dailyjs/a-simple-guide-to-understanding-javascript-es6-generators-d1c350551950)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-simple-guide-to-understanding-javascript-es6-generators.md)
  * PR 地址：#4138
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-6 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ssshooter** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ssshooter 棒极啦 :tada:

**Comment by ssshooter** [comment]
@leviding 请问 Generator、Iterator 等名词是翻译成中文还是保留英文？

**Comment by leviding** [comment]
@ssshooter 保留吧

**Comment by fanyijihua** [comment]
PR 地址：#4138

**Comment by Hopsken** [comment]
@leviding 校对认领
