### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by xiaoyusilen** [xitu/gold-miner#4128]
- 原文链接：https://blog.ably.io/how-to-implement-consistent-hashing-efficiently-fe038d59fff2
- 简要介绍：如何有效的实现一致性 hash

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@xiaoyusilen 已发布任务，感谢推荐
