### ISSUE TITLE
我如何使用 Node.js 来实现工作自动化

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4129]
* 原文链接：[How I automated my job with Node.js](https://medium.com/dailyjs/how-i-automated-my-job-with-node-js-94bf4e423017)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-i-automated-my-job-with-node-js.md)
  * PR 地址：#4148
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by geniusq1981** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@geniusq1981 棒极啦 :tada:
