### ISSUE TITLE
jQuery 3.0 终于发布啦

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#413]
原文链接：[jQuery 3.0 Final Released!](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/)
掘金链接：[jQuery 3.0 终于发布啦](http://gold.xitu.io/entry/575cd4fb816dfa0056bc9c6d)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/jquery-3-0-final-released.md)

翻译时间：6天
校对时间：5天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by ldhlfzysys** [comment]
翻译认领

**Comment by antonia0912** [comment]
@ldhlfzysys 女子白勺。。。

**Comment by buccoji** [comment]
申请认领校对

**Comment by thanksdanny** [comment]
申请认领校对

**Comment by antonia0912** [comment]
@buccoji @thanksdanny 好的 [校对地址](https://github.com/xitu/gold-miner/pull/438/files?diff=split)

**Comment by buccoji** [comment]
收到
