### ISSUE TITLE
从 Cron 到 Airflow 的迁移中我们学到了什么

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4130]
* 原文链接：[What we learned migrating off Cron to Airflow](https://medium.com/videoamp/what-we-learned-migrating-off-cron-to-airflow-b391841a0da4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-we-learned-migrating-off-cron-to-airflow.md)
  * PR 地址：#4145
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3.5 天
  * 校对时间：1 天
  * 翻译积分：3-4.5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cf020031308** [comment]
翻译认领

**Comment by leviding** [comment]
@cf020031308 好的呢

**Comment by fanyijihua** [comment]
PR 地址：#4145
