### ISSUE TITLE
我们是如何高效实现一致性哈希的

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4131]
* 原文链接：[How we implemented consistent hashing efficiently](https://blog.ably.io/how-to-implement-consistent-hashing-efficiently-fe038d59fff2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-implement-consistent-hashing-efficiently.md)
  * PR 地址：#4152
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-8 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yqian1991** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@yqian1991 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4152
