### ISSUE TITLE
Flutter 中的原生应用程序状态

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4133]
* 原文链接：[Reactive app state in Flutter](https://medium.com/@maksimrv/reactive-app-state-in-flutter-73f829bcf6a7)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/reactive-app-state-in-flutter.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4216
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
@leviding  md 文件内容呢

**Comment by leviding** [comment]
@Starriers 现在再看看呢，好了吧？

**Comment by Starriers** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by leviding** [comment]
@Starriers 这个怎么样了

**Comment by Starriers** [comment]
@leviding  过一会就上传

**Comment by fanyijihua** [comment]
PR 地址：#4216

**Comment by fanyijihua** [comment]
PR 地址：#4250
