### ISSUE TITLE
2018 来谈谈 Web 组件

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4135]
* 原文链接：[Web Components in 2018](https://www.sitepen.com/blog/2018/07/06/web-components-in-2018/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/web-components-in-2018.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4286
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天 weberpan 6 分
  * 校对时间：1.5 天
  * 翻译积分：5-7 分
  * 校对积分：0.5-3 分 xutaogit 3 分 zyziyun 1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by weberpan** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@weberpan 棒极啦 :tada:

**Comment by iFwu** [comment]
@weberpan 进度咋样，我想申请校对来着

**Comment by weberpan** [comment]
@iFwu 翻译了大半，这篇文章不少术语不好翻译。等我翻译好发出来我@一下你吧~

**Comment by leviding** [comment]
@weberpan 翻译的怎么样啦

**Comment by iFwu** [comment]
@weberpan 有空能看下这个翻译吗。。。

**Comment by weberpan** [comment]
最近工作日太忙，进度不太理想，唉，我再赶一下 @leviding

**Comment by fanyijihua** [comment]
PR 地址：#4286

**Comment by zyziyun** [comment]
校对认领
