### ISSUE TITLE
在 Sketch 中使用一个设计体系创作：第一部分 [教程]

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4137]
* 原文链接：[Creating with a Design System in Sketch: Part One [Tutorial]](https://medium.com/sketch-app-sources/creating-with-a-design-system-in-sketch-part-one-tutorial-5116e36213f9)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/creating-with-a-design-system-in-sketch-part-one-tutorial.md)
  * PR 地址：#4162
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5.5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pmwangyang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pmwangyang 棒极啦 :tada:
