### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by siegeout** [xitu/gold-miner#414]
你好，我是Siegen,Android开发两年经验,目前在职。

日常浏览github,stackoverflow,android developers ,对前沿技术很感兴趣，很喜欢稀土掘进出的文章，

希望能为掘金翻译计划出一份力。

**Comment by antonia0912** [comment]
@siegeout 代表组织欢迎你~请加我微信 antonia0912 备注github ID 我来拉你进译者群
