### ISSUE TITLE
Web 应用架构基础课

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4141]
* 原文链接：[Web Architecture 101: The basic architecture concepts I wish I knew when I was getting started as a web developer](https://engineering.videoblocks.com/web-architecture-101-a3224e126947)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/web-architecture-101.md)
  * PR 地址：#
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1.5 天
  * 翻译积分：5-7 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by horizon13th** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@horizon13th 棒极啦 :tada:

**Comment by leviding** [comment]
@horizon13th 这篇翻译的怎么样啦

**Comment by horizon13th** [comment]
@leviding 抱歉忙忘记了 已翻译了一部分 三天内提交

**Comment by fanyijihua** [comment]
PR 地址：#4237
