### ISSUE TITLE
设计 React 组件 API

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4150]
* 原文链接：[Defining Component APIs in React](http://jxnblk.com/writing/posts/defining-component-apis-in-react/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/defining-component-apis-in-react.md)
  * PR 地址：#4161
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gavin-Gong** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Gavin-Gong 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4161
