### ISSUE TITLE
创建一个 Sketch 的设计体系: 第二讲 [教程]

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4154]
* 原文链接：[Creating with a Design System in Sketch: Part Two [Tutorial]](https://medium.com/sketch-app-sources/creating-with-a-design-system-in-sketch-part-two-tutorial-445e0264556a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/creating-with-a-design-system-in-sketch-part-two-tutoria.md)
  * PR 地址：#4163
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zheng7426** [comment]
翻译认领@leviding， 第一次翻。

**Comment by fanyijihua** [comment]
@Zheng7426 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4163
