### ISSUE TITLE
UI 的黑暗面！暗色背景的优势

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#416]
原文链接：[Dark Side of UI. Benefits of Dark Background](https://medium.com/@tubikstudio/dark-side-of-ui-benefits-of-dark-background-12f560bf7165#.k0d00u47a)
掘金链接：[UI 的黑暗面！暗色背景的优势](http://gold.xitu.io/entry/575e1e7c7db2a200543f1d4d)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/dark-side-of-ui-benefits-of-dark-background.md)

翻译时间：6天
校对时间：5天
翻译积分：8
校对积分：3
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by antonia0912** [comment]
感谢@Ruixi 提供优质英文文章，凡为翻译计划提供文章的，积分+1~

**Comment by yangzj1992** [comment]
文章认领

**Comment by wild-flame** [comment]
大家手太快了，那这个我就校对吧

**Comment by antonia0912** [comment]
@yangzj1992 吼！

**Comment by Ruixi** [comment]
我自己想翻译我自己都没抢到啊啊啊啊啊啊！！！
求校对［怨念脸

**Comment by yangzj1992** [comment]
@antonia0912 翻译完成，申请校对

**Comment by antonia0912** [comment]
@Ruixi @wild-flame [校对地址在这里啦](https://github.com/xitu/gold-miner/pull/461/files?diff=split)

**Comment by wild-flame** [comment]
收到

**Comment by Ruixi** [comment]
好哒～

**Comment by antonia0912** [comment]
@Ruixi 睿奚快来校对呀~ @wild-flame 校对完了留言哈~

**Comment by Ruixi** [comment]
已完毕～
