### ISSUE TITLE
Python 与大数据：Airflow & Jupyter Notebook with Hadoop 3, Spark & Presto

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4165]
* 原文链接：[Python & Big Data: Airflow & Jupyter Notebook with Hadoop 3, Spark & Presto](http://tech.marksblogg.com/python-big-data-airflow-jupyter-notebook-hadoop-3-hive-presto.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/python-big-data-airflow-jupyter-notebook-hadoop-3-hive-presto.md)
  * PR 地址：#4173
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4173
