### ISSUE TITLE
深入了解 Flutter

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4166]
* 原文链接：[Out of Depth with Flutter](https://medium.com/flutter-io/out-of-depth-with-flutter-f683c29305a8)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/out-of-depth-with-flutter.md)
  * PR 地址：#4177
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DateBro** [comment]
翻译认领，这个文章的例子程序我好像在官网的文档跟着敲过 😆

**Comment by fanyijihua** [comment]
@DateBro 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4177
