### ISSUE TITLE
用 30 分钟建立一个网站的方式来学习 Bootstrap 4

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4167]
* 原文链接：[Learn Bootstrap 4 in 30 minutes by building a landing page website](https://medium.freecodecamp.org/learn-bootstrap-4-in-30-minute-by-building-a-landing-page-website-guide-for-beginners-f64e03833f33)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/learn-bootstrap-4-in-30-minute-by-building-a-landing-page-website-guide-for-beginners.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4214
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zheng7426** [comment]
翻译认领@leviding

**Comment by fanyijihua** [comment]
@Zheng7426 棒极啦 :tada:
