### ISSUE TITLE
Airflow: 一个工作流程管理平台

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4176]
* 原文链接：[Airflow: a workflow management platform](https://medium.com/airbnb-engineering/airflow-a-workflow-management-platform-46318b977fd8)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/airflow-a-workflow-management-platform.md)
  * PR 地址：#4192
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yqian1991** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@yqian1991 棒极啦 :tada:

**Comment by yqian1991** [comment]
@leviding 可以把这篇文章的后缀名改一改吗？现在是
`TODO1/airflow-a-workflow-management-platform.md)`
我改的话，校对者可能不太好校对，因为需要删除这个文件然后增加一个新文件

**Comment by leviding** [comment]
@yqian1991 改好了，感谢提醒

**Comment by fanyijihua** [comment]
PR 地址：#4192
