### ISSUE TITLE
Slidable：一个 Flutter 的故事

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4178]
* 原文链接：[Slidable: A Flutter story](https://medium.com/flutter-community/slidable-a-flutter-story-f4a5f55f6a96)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/slidable-a-flutter-story.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4215
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
申请翻译

**Comment by fanyijihua** [comment]
@YueYongDev 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4215
