### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by YGfishbone** [xitu/gold-miner#418]
您好，我是一名前端学习者，最近了解了掘金翻译计划。我比较喜欢英语，大专的时候过了六级，看美剧的时候经常用生肉字幕，希望能参加掘金翻译计划，出一份绵薄之力，也能提升自己的技术能力。
我的GitHub: [YGfishbone](https://github.com/YGfishbone)

**Comment by antonia0912** [comment]
@YGfishbone 代表组织欢迎你~请加我微信 antonia0912 我来拉你进译者群
