### ISSUE TITLE
让我们一起解决“this”难题  —  第一部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4181]
* 原文链接：[Let’s settle ‘this’ — Part One](https://medium.com/@nashvail/lets-settle-this-part-one-ef36471c7d97)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/lets-settle-this-part-one.md)
  * PR 地址：#4210
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天 
  * 校对时间：2 天
  * 翻译积分：7-8 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by geniusq1981** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@geniusq1981 棒极啦 :tada:

**Comment by coconilu** [comment]
@leviding 校对认领

**Comment by leviding** [comment]
@coconilu 请阅读翻译计划译者教程，校对是在对应 PR 下认领，本文校对已被认领完毕。
