### ISSUE TITLE
苹果公司对下一步的计划毫无头绪，它们仅在原地踏步

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4184]
* 原文链接：[Apple has no idea what’s next, so it’s just banging on the same old drum](https://medium.com/@ow/apple-has-no-idea-whats-next-so-it-s-just-banging-on-the-same-old-drum-dcfd0179cf80)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/apple-has-no-idea-whats-next-so-it-s-just-banging-on-the-same-old-drum.md)
  * PR 地址：
  * 文章分类：**产品**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8 分
  * 校对积分：0.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by dandyxu** [comment]
翻译认领

**Comment by leviding** [comment]
@dandyxu 翻译的怎么样啦

**Comment by dandyxu** [comment]
@leviding 不好意思，最迟明天晚上一定完成。

**Comment by BillShiyaoZhang** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@BillShiyaoZhang 棒极啦 :tada:

**Comment by leviding** [comment]
@BillShiyaoZhang 翻译的怎么样啦

**Comment by leviding** [comment]
@BillShiyaoZhang 超期太久，本 issue 关闭。
