### ISSUE TITLE
The Best Explanation of JavaScript Reactivity 🎆

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4185]
* 原文链接：[The Best Explanation of JavaScript Reactivity 🎆](https://medium.com/vue-mastery/the-best-explanation-of-javascript-reactivity-fea6112dd80d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-best-explanation-of-javascript-reactivity.md)
  * PR 地址：#
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jonjia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jonjia 棒极啦 :tada:

**Comment by jonjia** [comment]
@leviding ，不好意思，发现已经有人翻译过了：https://juejin.im/post/5b558e266fb9a04f980cc937，应该没必要翻译了

**Comment by leviding** [comment]
好的
