### ISSUE TITLE
IT工作时间虽然长，但是真正感兴趣IT龄有点短，不过一旦认准了，就是付出热情

### ISSUE THREAD

**Issue by AlexDavidLucky** [xitu/gold-miner#419]
做Java开发快3年了，OC和swift从去年也开始陆续接触，这也是我真正对IT开始感兴趣的起点吧，但是我对英语一直都是怀抱热情(本人非常希望外语)，现在希望我对英语的热情和工作的兴趣，也能够做一点小小的贡献，不再是一直的索取者。

**Comment by antonia0912** [comment]
@AlexDavidLucky 请加我微信 antonia0912 备注github ID 我拉你进译者群
