### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by DAA233** [xitu/gold-miner#4190]
- 原文链接：https://kevinzakka.github.io/2016/09/26/applying-deep-learning/
- 简要介绍：本文是作者 Kevin Zakaa 在观看 Andrew Ng 的 Nuts and Bolts of Applying Deep Learning 报告后做的一些总结，内容涵盖对深度学习发展趋势的概述以及一些应用深度学习的技巧。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@DAA233 本文有译文了
