### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by ssshooter** [xitu/gold-miner#4196]
- 原文链接：https://medium.com/@george3d6/imaginary-problems-d4f2921bd1b8
- 简要介绍：关于产品的过度设计和一些设计误区

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@ssshooter 感谢推荐，已发布认领
