### ISSUE TITLE
认领《2015 年底 JS 必备工具集》

### ISSUE THREAD

**Issue by zxc0328** [xitu/gold-miner#42]
这是我以前翻译的一些文章
[居中一切(centering all the directions)](http://zxc0328.github.io/2015/05/21/centering-all-the-directions/)
[Web Animation Using Javascript ](http://zxc0328.github.io/2015/05/23/Web-Animation-Using-Javascript-part-one/)

**Comment by Glowin** [comment]
好的，我给你添加上 readme，欢迎加入组织 :+1: 

另外，你是少数几个在 issue 里写上自己翻译经历的人，赞

**Comment by zxc0328** [comment]
好的。已fork

**Comment by Glowin** [comment]
你好，我拉了一个掘金翻译计划译者的微信群，译者都在群里面，我会在群里面更新活动的最新进展，如果方便的话可以加我一下微信 Glowjiang。
