### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by warcryDoggie** [xitu/gold-miner#420]
- 大三在校生，一年web前端开发经验
- 英语CET6水平，阅读stackOverflow、英文文档、参加Coursera课程基本无障碍。
- 本科专业印刷工程。对字体设计，图像处理，桌面排版有一定了解，可以辅助相关术语校对。

**Comment by antonia0912** [comment]
@warcryDoggie 请加我微信 antonia0912 备注github ID 我拉你进译者群
