### ISSUE TITLE
深入 Flutter 之手势

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4201]
* 原文链接：[Flutter Deep Dive: Gestures](https://medium.com/flutter-community/flutter-deep-dive-gestures-c16203b3434f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/flutter-deep-dive-gestures.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4246
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-6 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MeFelixWang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MeFelixWang 棒极啦 :tada:
