### ISSUE TITLE
虚构问题，低质量软件的根源

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4203]
* 原文链接：[Imaginary problems, the root of bad software](https://medium.com/@george3d6/imaginary-problems-d4f2921bd1b8)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/imaginary-problems.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4217
  * 文章分类：**设计，产品**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ssshooter** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ssshooter 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4217
