### ISSUE TITLE
Tab Bar 就是新的汉堡菜单

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4204]
* 原文链接：[Tab Bars are the new Hamburger Menus](https://uxplanet.org/tab-bars-are-the-new-hamburger-menus-9138891e98f4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/tab-bars-are-the-new-hamburger-menus.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4223
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rydensun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@rydensun 棒极啦 :tada:
