### ISSUE TITLE
在 UNIX 中，一切皆文件

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4207]
* 原文链接：[In UNIX Everything is a File](https://ph7spot.com/musings/in-unix-everything-is-a-file)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/in-unix-everything-is-a-file.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4225
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4.5 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pmwangyang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pmwangyang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4225
