### ISSUE TITLE
重写 loadView() 方法使 Swift 视图代码更加简洁

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4211]
* 原文链接：[Writing Cleaner View Code in Swift By Overriding loadView()](https://swiftrocks.com/writing-cleaner-view-code-by-overriding-loadview.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/writing-cleaner-view-code-by-overriding-loadview.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4235
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2.5 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4235
