### ISSUE TITLE
 自然语言处理真是有趣

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4220]
* 原文链接：[Natural Language Processing is Fun!](https://medium.com/@ageitgey/natural-language-processing-is-fun-9a0bff37854e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/natural-language-processing-is-fun.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4238
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：8-10 分
  * 校对积分：0.5-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4238

**Comment by leviding** [comment]
@sakila1012 到 PR 下认领校对
