### ISSUE TITLE
让我们一起解决“this”难题  —  第二部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4221]
* 原文链接：[Let’s settle ‘this’ — Part Two](https://medium.com/@nashvail/lets-settle-this-part-two-2d68e6cb7dba)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/lets-settle-this-part-two.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4244
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-6 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by geniusq1981** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@geniusq1981 棒极啦 :tada:

**Comment by coconilu** [comment]
@leviding 校对认领

**Comment by leviding** [comment]
@coconilu 请到对应 PR 下认领
