### ISSUE TITLE
用 React 和 Vue 创建了两个完全相同的应用后，发现了这些差异

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4230]
* 原文链接：[I created the exact same app in React and Vue. Here are the differences.](https://medium.com/javascript-in-plain-english/i-created-the-exact-same-app-in-react-and-vue-here-are-the-differences-e9a1ae8077fd)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/i-created-the-exact-same-app-in-react-and-vue-here-are-the-differences.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4236
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-6 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jonjia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jonjia 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4236
