### ISSUE TITLE
如何设计移动应用的搜索功能？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4233]
* 原文链接：[Designing search for mobile apps](https://medium.muz.li/designing-search-for-mobile-apps-ab2593e9e413)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/designing-search-for-mobile-apps.md)
  * PR 地址：#
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xunge0613** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@xunge0613 棒极啦 :tada:
