### ISSUE TITLE
如何向带有插槽的 React 组件传递多个 Children

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4234]
* 原文链接：[Pass Multiple Children to a React Component with Slots](https://daveceddia.com/pluggable-slots-in-react-components/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/pluggable-slots-in-react-components.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4294
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zheng7426** [comment]
翻译认领@leviding

**Comment by fanyijihua** [comment]
@Zheng7426 棒极啦 :tada:

**Comment by leviding** [comment]
@Zheng7426 翻译的怎么样了，超期有点久了
