### ISSUE TITLE
Flutter 的英雄和流氓们 —— 为 Flutterverse 带来平衡

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4239]
* 原文链接：[Flutter Heroes and Villains — bringing balance to the Flutterverse.](https://medium.com/flutter-community/flutter-heroes-and-villains-bringing-balance-to-the-flutterverse-2e900222de41)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/flutter-heroes-and-villains-bringing-balance-to-the-flutterverse.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4371
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-6 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DateBro** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@DateBro 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4342

**Comment by fanyijihua** [comment]
PR 地址：#4371
