### ISSUE TITLE
使用 Web Beacon API 记录活动

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4240]
* 原文链接：[Logging Activity With The Web Beacon API](https://www.smashingmagazine.com/2018/07/logging-activity-web-beacon-api/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/logging-activity-web-beacon-api.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4245
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-6 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by elliott-zhao** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@elliott-zhao 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4245
