### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by DerekDick** [xitu/gold-miner#4241]
- 原文链接：[Practical ProGuard rules examples](https://medium.com/google-developers/practical-proguard-rules-examples-5640a3907dc9)
- 简要介绍：通过一个实际的Android项目来举例介绍一些实用的ProGuard规则。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@DerekDick 感谢推荐，查无译文后今晚会发布
