### ISSUE TITLE
翻译者申请：Android 开发者 ｜ 英汉双语使用者 ｜ 技术与翻译爱好者

### ISSUE THREAD

**Issue by buccoji** [xitu/gold-miner#425]
四年 Android 开发，目前已转为全栈开发者。对 Android 和移动开发领域有一些浅显的理解，也因为自己是英文和中文的双语使用者，希望能通过掘金计划为中文的开发者们译进最新的英文社区的技术见解和讨论。

即请健安

**Comment by antonia0912** [comment]
@buccoji 组织欢迎你~请加我微信 antonia0912 备注github ID 我拉你进译者群
