### ISSUE TITLE
实用 ProGuard 规则示例

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4251]
* 原文链接：[Practical ProGuard rules examples](https://medium.com/google-developers/practical-proguard-rules-examples-5640a3907dc9)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/practical-proguard-rules-examples.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4293
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DerekDick** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@DerekDick 棒极啦 :tada:

**Comment by leviding** [comment]
@DerekDick 这篇怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#4293

**Comment by DerekDick** [comment]
翻译完啦~
