### ISSUE TITLE
The Cost Of JavaScript In 2018

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4252]
* 原文链接：[The Cost Of JavaScript In 2018](https://medium.com/@addyosmani/the-cost-of-javascript-in-2018-7d8950fbb5d4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-cost-of-javascript-in-2018.md)
  * PR 地址：#
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：11-13 分
  * 校对积分：0.5-5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by leviding** [comment]
@Starriers 这篇你翻译了吗？没的话就不翻译了，别人已经出了好几个版本译文了

**Comment by Starriers** [comment]
因为这个文章的语法 非常有意思 所以我自己会翻译完的。这个就换掉好了 下次领的会第一时间完成

**Comment by Starriers** [comment]
@leviding

**Comment by leviding** [comment]
好的哈
