### ISSUE TITLE
使用原生 JavaScript 构建状态管理系统

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4253]
* 原文链接：[Build a state management system with vanilla JavaScript](https://css-tricks.com/build-a-state-management-system-with-vanilla-javascript/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/build-a-state-management-system-with-vanilla-javascript.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4302
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6-7.5 分
  * 校对积分：0.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shery** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@shery 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4302
