### ISSUE TITLE
挑战 Flutter 之 Twitter

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4254]
* 原文链接：[Flutter Challenge: Twitter](https://itnext.io/flutter-challenge-twitter-a1cb17f1e21b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/flutter-challenge-twitter.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4258
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MeFelixWang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MeFelixWang 棒极啦 :tada:
