### ISSUE TITLE
我是如何使用 Python 在 Medium 上找到并关注有趣的人

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4256]
* 原文链接：[How I used Python to find interesting people to follow on Medium](https://medium.freecodecamp.org/how-i-used-python-to-find-interesting-people-on-medium-be9261b924b0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-i-used-python-to-find-interesting-people-on-medium.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4276
  * 文章分类：**Python**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Park-ma** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Park-ma 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4276
