### ISSUE TITLE
如何使用 Python 和 BeautifulSoup 抓取网站内容

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4257]
* 原文链接：[How to scrape websites with Python and BeautifulSoup](https://medium.freecodecamp.org/how-to-scrape-websites-with-python-and-beautifulsoup-5946935d93fe)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-scrape-websites-with-python-and-beautifulsoup.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4277
  * 文章分类：**前端/后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by geniusq1981** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@geniusq1981 棒极啦 :tada:
