### ISSUE TITLE
如何应用最新版的谷歌表格 API

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#426]
原文链接：[Using the new Google Sheets API](http://wescpy.blogspot.hk/2016/06/using-new-google-sheets-api.html)
掘金链接：[如何应用最新版的谷歌表格 API](http://gold.xitu.io/entry/5760fb56df0eea0062cda7fb)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/using-new-google-sheets-api.md)
[校对地址](https://github.com/xitu/gold-miner/pull/443/files?diff=split)
翻译时间：6天
校对时间：5天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Goshin** [comment]
想要。。。要校对几篇才能认领翻译啊？

**Comment by antonia0912** [comment]
@Goshin 校对一篇就可以翻译了

**Comment by Goshin** [comment]
那我可以开始了吗？😋

**Comment by antonia0912** [comment]
@Goshin 可以啦  翻译完发PR就可以啦  有问题在译者群里问大家或者圈我就可以啦

**Comment by warcryDoggie** [comment]
认领校对

**Comment by jkjk77** [comment]
嘤嘤嘤 楼上欺负我网速慢

**Comment by warcryDoggie** [comment]
买个好梯子很重要 0v0

**Comment by jkjk77** [comment]
有梯子也抢不过QAQ

**Comment by antonia0912** [comment]
@warcryDoggie @jkjk77 每篇文章需要两位校对者喔~所以你们俩都可以去校对啦  校对地址见issue描述~come on~baby go~

**Comment by jkjk77** [comment]
@antonia0912 喔~我也申请校对 😀  我以为只能一个人呢

**Comment by antonia0912** [comment]
@jkjk77 可以哒  校对地址见issue描述哈
