### ISSUE TITLE
Flutter 挑战之 WhatsApp 

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4263]
* 原文链接：[Flutter Challenge: WhatsApp](https://medium.com/@dev.n/flutter-challenge-whatsapp-b4dcca52217b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/flutter-challenge-whatsapp.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4282
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：1.5-2.5 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@YueYongDev 棒极啦 :tada:
