### ISSUE TITLE
挑战 Flutter 之 YouTube

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4264]
* 原文链接：[Flutter Challenge: YouTube (Picture-In-Picture)](https://proandroiddev.com/flutter-challenge-youtube-ec5ff36eca9b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/flutter-challenge-youtube.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4271
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
@MeFelixWang 棒极啦 :tada:
