### ISSUE TITLE
探寻 Android N 中通知的新变化

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#427]
原文链接：[Notifications in Android N](https://android-developers.blogspot.hk/2016/06/notifications-in-android-n.html)
掘金链接：[探寻 Android N 中通知的新变化](http://gold.xitu.io/entry/576123df207703006bf61cd3)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/notifications-in-android-n.md)

翻译时间：6天
校对时间：5天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by danke77** [comment]
文章认领

**Comment by DeadLion** [comment]
认领 @antonia0912

**Comment by antonia0912** [comment]
@danke77 新译者要从校对开始喔 校对一篇文章之后才可以认领翻译的  这篇文章校对可以给你啦 @DeadLion 去翻译吧 PR发了之后圈上面这位译者来校对哈

**Comment by danke77** [comment]
@antonia0912 好的

**Comment by xcc3641** [comment]
@antonia0912 强势预定校对一波~终于有 Android 啦

**Comment by DeadLion** [comment]
@antonia0912 @xcc3641 @danke77    完成翻译，[校稿地址](https://github.com/xitu/gold-miner/pull/453)

**Comment by danke77** [comment]
校对认领

**Comment by antonia0912** [comment]
@xcc3641 @danke77 校对地址译者已经给出来了  快去校对吧

**Comment by danke77** [comment]
校对完成 @antonia0912 @DeadLion
