### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by HaoChuan9421** [xitu/gold-miner#4270]
- 原文链接：[Optimizing MP4 Video for Fast Streaming](https://rigor.com/blog/2016/01/optimizing-mp4-video-for-fast-streaming)
- 简要介绍：本文主要介绍如何优化 MP4 视频在网页中的流媒体传输速度。之所以推荐这篇文章是因为今天在掘金的前端首页出现的这篇文章 —— [[贝聊科技]首屏视频优化过程](https://juejin.im/post/5b68288df265da0fa21aa6bf)。该文介绍的优化方案很有实战价值，但是文中存在纰漏，我在评论区已经和作者反馈了，而主要的参考文章就是这篇优秀的英文博客。所以，希望可以把这篇文章翻译之后附在该文后面，来更好的帮助后面阅读该文的掘金读者。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢推荐，已发布认领
