### ISSUE TITLE
优化 MP4 视频以获得更快的流传输速度

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4272]
* 原文链接：[Optimizing MP4 Video for Fast Streaming](https://rigor.com/blog/2016/01/optimizing-mp4-video-for-fast-streaming)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/optimizing-mp4-video-for-fast-streaming.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4278
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4.5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by HaoChuan9421** [comment]
翻译认领（自己认领一波😁）

**Comment by fanyijihua** [comment]
@HaoChuan9421 棒极啦 :tada:

**Comment by HaoChuan9421** [comment]
@leviding 这个属于文章分类应该属于前端吧？

**Comment by leviding** [comment]
@HaoChuan9421 改过来了

**Comment by fanyijihua** [comment]
PR 地址：#4278
