### ISSUE TITLE
SpaceAce 了解一下，一个新的前端状态管理库

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4274]
* 原文链接：[Introducing SpaceAce, a new kind of front-end state library](https://medium.com/dailyjs/introducing-spaceace-a-new-kind-of-front-end-state-library-5215b18adc11)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/introducing-spaceace-a-new-kind-of-front-end-state-library.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4296
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by noahziheng** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@noahziheng 棒极啦 :tada:
