### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by elliott-zhao** [xitu/gold-miner#4283]
* 原文链接：[How to think like a programmer — lessons in problem solving](https://medium.freecodecamp.org/how-to-think-like-a-programmer-lessons-in-problem-solving-d1d8bf1de7d2)
* 简要介绍：怎样像程序员一样思考——教你解决问题
现代社会，每个人都应该学一点编程。不是为了谋生，而是为了更科学、更有效的思维方式。这篇文章不涉及太多的技术，而是对这种思维方式进行了介绍。实际上，我发现到现在仍然有很多五六年的程序员都没办法“像程序员一样思考”，所以我推荐这篇文章，算是个科普吧。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@elliott-zhao 感谢推荐，已发布认领
