### ISSUE TITLE
如何使用纯函数式 JavaScript 处理脏副作用

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4288]
* 原文链接：[HOW TO DEAL WITH DIRTY SIDE EFFECTS IN YOUR PURE FUNCTIONAL JAVASCRIPT](https://jrsinclair.com/articles/2018/how-to-deal-with-dirty-side-effects-in-your-pure-functional-javascript/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-deal-with-dirty-side-effects-in-your-pure-functional-javascript.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4333
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：8-10 分
  * 校对积分：0.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gavin-Gong** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Gavin-Gong 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4333
