### ISSUE TITLE
WWDC 2016：假如 Mac 上也有 iOS 应用

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#429]
原文链接：[How iOS Apps on the Mac Could Work](https://medium.com/@sandofsky/how-ios-apps-on-the-mac-could-work-13aa32a2647b)
掘金链接：[Mac 归来 - WWDC 2016](http://gold.xitu.io/entry/576127f9df0eea0062ce538a)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/how-ios-apps-on-the-mac-could-work.md)

翻译时间：6天
校对时间：5天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by warcryDoggie** [comment]
申请翻译

**Comment by warcryDoggie** [comment]
翻译认领

**Comment by warcryDoggie** [comment]
说起来这文章标题是back to the Mac
How iOS Apps on the Mac Could Work  是段落提要

**Comment by warcryDoggie** [comment]
虽然源站How iOS Apps on the Mac Could Work放在<h3>里面，看完全文，文章题目应该是Back to the Mac.
How iOS Apps on the Mac Could Work   应该理解为 现在在Mac上能运行的iOS Apps怎么样？
主要要是吐槽年旧失修的mac app store和MAC UIKit，提些建议关于Apple应该如何降低不同设备间兼容的难度。

想了一会，中文太差，Back to the Mac怎么翻都没味道，还是放弃认领了。

**Comment by wild-flame** [comment]
扫了一眼，感觉这篇写的还不错😁，貌似是设计类的不是开发类的，认领啦

**Comment by antonia0912** [comment]
@wild-flame ok 题目是我翻译的 如果觉得不太好可以改一下 毕竟羊哥是门外羊哈哈哈

**Comment by wild-flame** [comment]
@antonia0912 好的羊羊羊 确实感觉题目意思有点不对劲

**Comment by antonia0912** [comment]
@wild-flame 以你翻译的为准啦

**Comment by thanksdanny** [comment]
可以提前占坑校对么！

**Comment by antonia0912** [comment]
@wild-flame 发了PR记得圈 @thanksdanny 来校对吼~

**Comment by owenlyn** [comment]
刚加入翻译组 每篇文章是需要两个校对吗？ 我来占第二个坑~  (^o^)

**Comment by antonia0912** [comment]
@owenlyn 吼~

**Comment by wild-flame** [comment]
@antonia0912 羊哥你改一下issue 的标题吧。改成 

## Mac 归来 -  WWDC 2016

原来标题完全文不对题。

另外文章我已经全部翻译完初稿了，校对亲们@owenlyn @thanksdanny 可以预热一下，这篇文章有点难度。（我大概明后天会 pull request，文章还有一些我还要多推敲一下的地方，所以还没 request）。

**Comment by antonia0912** [comment]
@wild-flame 吼 辛苦啦~为你的认真点10个赞 一个手指头一个~

**Comment by thanksdanny** [comment]
@wild-flame 突然你这么一说搞得我紧张又期待了！

**Comment by wild-flame** [comment]
@thanksdanny @owenlyn 我已经 pull-request 了。 大意应该是没问题的，怎么说呢，总觉得有一些细节和原文可能有些出入，这篇文章用词比较不是那么书面，或者说我翻译的时候总感觉有很有一些具有衍生意义的用法，不能直接照词直翻的...原文的题目应该是“bcak to the mac”，我翻译成了“ Mac 归来”，小标题 WWDC2016 是我自己yy加上去的，如果有更好的建议也可以提哦：D

**Comment by wild-flame** [comment]
[校对地址](https://github.com/xitu/gold-miner/pull/464/files) 

还有就是这次我保留了英文原文在 markdown 里，之前有人说校对的时候可以保留原文比较好，方便预览可以看图，加上也有些人比较习惯上下排版。

**Comment by antonia0912** [comment]
@wild-flame 辛苦啦 么么哒~（雷好乖巧哈哈哈）

**Comment by antonia0912** [comment]
@thanksdanny @owenlyn [校对地址在这里啦](https://github.com/xitu/gold-miner/pull/464/files?diff=split)

**Comment by owenlyn** [comment]
@antonia0912 抱歉这几天比较忙 校对来晚了😭  我终于校对完成啦~
@wild-flame 谢谢你的上下排版 特别方便呢~~

**Comment by wild-flame** [comment]
@owenlyn @thanksdanny  谢谢两位，我已经改好了。另外纠结了好久，还是觉得中文标题叫 **假如 Mac 上也有 iOS 应用？** 比较好
