### ISSUE TITLE
常见网页设计错误一览

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4290]
* 原文链接：[Common webpage design mistakes](http://blog-en.tilda.cc/articles-website-design-mistakes)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/articles-website-design-mistakes.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4308
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-6 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by StellaBauhinia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@StellaBauhinia 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4308
