### ISSUE TITLE
Python 的多线程与多进程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4291]
* 原文链接：[Intro to Threads and Processes in Python](https://medium.com/@bfortuner/python-multithreading-vs-multiprocessing-73072ce5600b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/python-multithreading-vs-multiprocessing.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4360
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
好

**Comment by lsvih** [comment]
@leviding 收尾了，明天应该能交

**Comment by fanyijihua** [comment]
PR 地址：#4360
