### ISSUE TITLE
构建流畅的交互界面

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4292]
* 原文链接：[Building Fluid Interfaces: How to create natural gestures and animations on iOS](https://medium.com/@nathangitter/building-fluid-interfaces-ios-swift-9732bb934bf5)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/building-fluid-interfaces-ios-swift.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4328
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-9 分
  * 校对积分：0.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rydensun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@rydensun 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4328
