### ISSUE TITLE
认领 Absolute Beginner's Guide to Swift

### ISSUE THREAD

**Issue by vulgur** [xitu/gold-miner#43]
自己用 Swift 写的小游戏刚刚上架不久，想就此文章巩固一下

**Comment by Glowin** [comment]
你好，这篇文章已经被@cdpath 认领了#18，你看看能不能挑一个其他未被认领的文章呢，谢谢理解。

**Comment by Glowin** [comment]
你好，现在挑选出来的文章已经被认领完了，但是这个翻译计划还是会一直更新维护下去，我新建了一个掘金翻译计划的微信群，并会在群里面通报翻译活动的最新进展，希望你能加一下我微信 Glowjiang，感谢你的支持和理解。
