### ISSUE TITLE
2018 年 iOS 开发找工作完全指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4310]
* 原文链接：[A Complete Guide to Getting Hired as an iOS Developer in 2018](https://blog.usejournal.com/a-complete-guide-to-getting-hired-as-an-ios-developer-in-2018-d7dcf50dc25)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-complete-guide-to-getting-hired-as-an-ios-developer-in-2018.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4334
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by melon8** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@melon8 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4334
