### ISSUE TITLE
使用 Go 编写微服务及其 GraphQL 网关

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4311]
* 原文链接：[Using GraphQL with Microservices in Go](https://outcrawl.com/go-graphql-gateway-microservices/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/go-graphql-gateway-microservices.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4375
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
@leviding 认领

**Comment by lsvih** [comment]
@changkun 没成功。。

**Comment by changkun** [comment]
哈？@lsvih

**Comment by changkun** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@changkun 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4375

**Comment by razertory** [comment]
校对认领

**Comment by leviding** [comment]
@razertory 下次请在 PR 下认领校对哈

**Comment by razertory** [comment]
@leviding  ok
