### ISSUE TITLE
用 Scikit-Learn 实现 SVM 和 Kernel SVM

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4312]
* 原文链接：[Implementing SVM and Kernel SVM with Python's Scikit-Learn](https://stackabuse.com/implementing-svm-and-kernel-svm-with-pythons-scikit-learn/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/implementing-svm-and-kernel-svm-with-pythons-scikit-learn.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4327
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5-7 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rockyzhengwu** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@rockyzhengwu 棒极啦 :tada:
