### ISSUE TITLE
使用 Nexmo 和微软语音翻译 API 构建 Babel 鱼

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4313]
* 原文链接：[Build a Babel Fish with Nexmo, and the Microsoft Translator Speech API](https://www.nexmo.com/blog/2018/03/14/speech-voice-translation-microsoft-dr/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/speech-voice-translation-microsoft-dr.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4343
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4343
