### ISSUE TITLE
申请成为Android译者

### ISSUE THREAD

**Issue by wavever** [xitu/gold-miner#432]
知道自己是英语渣，可挑战也是一种动力，不是么

**Comment by antonia0912** [comment]
@wavever 请问主要从事什么方向的工作  平时都从哪些渠道获得技术类信息

**Comment by wavever** [comment]
现在是大三的学生，主要的学习方向是Android，获取信息的渠道有很多啊，微博啊，公众号啊，官网啊，之类的。

**Comment by antonia0912** [comment]
@wavever 我是说  看外文网站嘛  medium 呀  stackoverflow 之类的

**Comment by wavever** [comment]
官网也是外文的啊。。遇到一些问题的时候会去stackoverflow上看看

**Comment by antonia0912** [comment]
@wavever 组织欢迎你~请加我微信 antonia0912 备注github ID 我拉你进译者群
