### ISSUE TITLE
Databook：通过元数据，Uber 将大数据转化为知识

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4321]
* 原文链接：[Databook: Turning Big Data into Knowledge with Metadata at Uber](https://eng.uber.com/databook/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/databook-turning-big-data-into-knowledge-with-metadata-at-uber.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4351
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5-7 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cf020031308** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cf020031308 棒极啦 :tada:
