### ISSUE TITLE
SmartyStreets 的 Go 测试探索之路

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4322]
* 原文链接：[A History of Testing in Go at SmartyStreets](https://smartystreets.com/blog/2018/03/history-of-go-testing)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/history-of-go-testing.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4448
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kasheemlew** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@kasheemlew 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4448
