### ISSUE TITLE
Sklearn 中的朴素贝叶斯分类器

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4323]
* 原文链接：[Naive Bayes Classification With Sklearn](https://blog.sicara.com/naive-bayes-classifier-sklearn-python-example-tips-42d100429e44)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/#)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4349
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sisibeloved** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sisibeloved 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4349
