### ISSUE TITLE
函数式 JavaScript 编程的简短介绍

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4324]
* 原文链接：[A Quick Introduction to Functional Javascript](https://hackernoon.com/a-quick-introduction-to-functional-javascript-7e6fe520e7fa)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-quick-introduction-to-functional-javascript.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4357
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zheng7426** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Zheng7426 棒极啦 :tada:
