### ISSUE TITLE
明日之布局

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4329]
* 原文链接：[The Layouts of Tomorrow](https://mxb.at/blog/layouts-of-tomorrow/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/layouts-of-tomorrow.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4359
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MeFelixWang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MeFelixWang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4359

**Comment by Raoul1996** [comment]
校对认领

**Comment by leviding** [comment]
@Raoul1996 PR 下认领
