### ISSUE TITLE
申请成为iOS译者

### ISSUE THREAD

**Issue by thanksdanny** [xitu/gold-miner#433]
从事测试行业，一直偏好iOS平台，通过看官方文档学习iOS开发。通过ss与世界连接，能在一堆外文章找到自己想要的答案。一直希望为开源贡献分力量，同时也能锻炼自己！

**Comment by antonia0912** [comment]
@thanksdanny 组织欢迎你~请加我微信 antonia0912 备注github ID 我拉你进译者群
