### ISSUE TITLE
设计 QA 在应用程序设计中的重要性

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4330]
* 原文链接：[The importance of Design QA in digital product design](https://uxdesign.cc/the-importance-of-design-qa-in-digital-product-design-c3f3d128270?ref=uxdesignweekly)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-importance-of-design-qa-in-digital-product-design.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4350
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lihanxiang** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@lihanxiang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4350

**Comment by lihanxiang** [comment]
https://juejin.im/post/5b89421651882542da339868
