### ISSUE TITLE
 如何优化企业级规模的 Node.js 应用程序

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4331]
* 原文链接：[How to Optimize Enterprise-Scale Node.js Applications](https://www.javacodegeeks.com/2018/08/optimize-enterprise-scale-node-js.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/optimize-enterprise-scale-node-js.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4345
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:
