### ISSUE TITLE
为什么设计师讨厌政治

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4335]
* 原文链接：[Why Designers Hate Politics (And What To Do About It)](https://medium.com/@berkun/why-designers-hate-politics-and-what-to-do-about-it-54d170a298cc)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-designers-hate-politics-and-what-to-do-about-it.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4358
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4358
