### ISSUE TITLE
React Native 对 Flutter: 哪一个对创业公司更加友好？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4337]
* 原文链接：[React Native vs Flutter: Which Is More Startup friendly?](https://hackernoon.com/react-native-vs-flutter-which-is-more-startup-friendly-c6e412d0b9ab)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/react-native-vs-flutter-which-is-more-startup-friendly.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4366
  * 文章分类：**移动端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
翻译认领。

**Comment by fanyijihua** [comment]
@tanglie1993 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4366
