### ISSUE TITLE
你 Ladar 中该珍藏的：iOS 布局语言

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4340]
* 原文链接：[What's in your Larder: iOS layout DSLs](https://larder.io/blog/larder-links-06-iOS-Auto-Layout-DSLs/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/larder-links-06-iOS-Auto-Layout-DSLs.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4352
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pmwangyang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pmwangyang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4352
