### ISSUE TITLE
探索 SMACSS：可扩展的模块化 CSS 框架

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4341]
* 原文链接：[Exploring SMACSS: Scalable and Modular Architecture for CSS](https://www.toptal.com/css/smacss-scalable-modular-architecture-css)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/smacss-scalable-modular-architecture-css.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4417
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-8 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Park-ma** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Park-ma 棒极啦 :tada:

**Comment by leviding** [comment]
@Park-ma 翻译的怎么样了

**Comment by Park-ma** [comment]
@leviding  刚开学课有点多，可能要延期啦

**Comment by fanyijihua** [comment]
PR 地址：#4417
