### ISSUE TITLE
如何提升设计到开发的协作效率

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4346]
* 原文链接：[How to Save UI Designers & Front-End Developers up to 50% of Their Time](https://uxplanet.org/how-to-save-ui-designers-front-end-developers-up-to-50-of-their-time-39a30254ec05)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-save-ui-designers-front-end-developers-up-to-50-of-their-time.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4347
  * 文章分类：**设计/前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：7-9 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@meterscao

**Comment by meterscao** [comment]
确认，翻译认领

**Comment by fanyijihua** [comment]
@meterscao 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4347

**Comment by meterscao** [comment]
收到，多谢各位的校对和帮助，看来细节问题还是要更细心才是哈
