### ISSUE TITLE
申请成为Android/Python译者

### ISSUE THREAD

**Issue by shixinzhang** [xitu/gold-miner#435]
大学时通过CET-6，英语读写能力良好，从事Android开发1年多，经常去墙外逛，国外一些社交网站、技术博客、开源社区均有涉猎，翻译过官方文档和开发者文章，支持开源，喜欢掘金翻译文章的活动，希望自己能够有机会参与，谢谢。

**Comment by antonia0912** [comment]
@shixinzhang 组织欢迎你~请加我微信 antonia0912 备注github ID 我拉你进译者群
