### ISSUE TITLE
关于工程师和影响力

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4353]
* 原文链接：[ON ENGINEERS AND INFLUENCE](https://charity.wtf/2018/08/17/on-engineers-and-influence/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/on-engineers-and-influence.md)
  * PR 地址：
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1.5 天
  * 翻译积分：4-5.5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cf020031308** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cf020031308 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4380
