### ISSUE TITLE
在 iOS 中使用 UITests 测试 Facebook 登录功能

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4354]
* 原文链接：[Running UITests with Facebook login in iOS](https://hackernoon.com/running-uitests-with-facebook-login-in-ios-4ac998940c42)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/running-uitests-with-facebook-login-in-ios.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4367
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LoneyIsError** [comment]
翻译认领！

**Comment by fanyijihua** [comment]
@LoneyIsError 棒极啦 :tada:

**Comment by razertory** [comment]
校对认领
