### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by hikerpig** [xitu/gold-miner#4365]
- 原文链接：https://mathiasbynens.be/notes/prototypes

- 简要介绍：介绍了通用 JavaScript 引擎优化代码执行的方式，着重介绍了加速原型链查找的优化，了解引擎工作的方式能帮助工程师们写出性能更高的 JS 代码

**Comment by leviding** [comment]
@hikerpig 感谢推荐，本周安排发布翻译认领

**Comment by CoolRice** [comment]
@leviding ，这个文章已经有人翻译并发到知乎上了
https://zhuanlan.zhihu.com/p/42630183

**Comment by leviding** [comment]
@CoolRice 好的，感谢

@hikerpig 感谢推荐
