### ISSUE TITLE
使用 Node 和 OAuth 2.0 构建一个简单的 REST API

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4368]
* 原文链接：[Build a Simple REST API with Node and OAuth 2.0](https://developer.okta.com/blog/2018/08/21/build-secure-rest-api-with-node)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/build-secure-rest-api-with-node.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4458
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5-6.5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by leviding** [comment]
@Starriers 翻译的怎么样了

**Comment by leviding** [comment]
@Starriers 翻译的怎么样了

**Comment by Starriers** [comment]
@leviding   晚上回去就上传

**Comment by fanyijihua** [comment]
PR 地址：#4458
