### ISSUE TITLE
Android 的多摄像头支持

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4379]
* 原文链接：[Camera Enumeration on Android](https://medium.com/androiddevelopers/camera-enumeration-on-android-9a053b910cb5)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/camera-enumeration-on-android.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4393
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2-2.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luoqiuyu** [comment]
认领

**Comment by leviding** [comment]
@luoqiuyu 好的呢

**Comment by fanyijihua** [comment]
PR 地址：#4393
