### ISSUE TITLE
想翻译校对哪个分类文章请留言，也可以在下方推荐文章

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4383]

**Comment by rydensun** [comment]
着重 iOS 产品 和设计。   其余所有分类也都可以考虑

**Comment by leviding** [comment]
@rydensun 收到

**Comment by ShiqinHuo** [comment]
deep learning / computer vision / Django Flask等python后端框架 / React前端

**Comment by Zheng7426** [comment]
前端

**Comment by razertory** [comment]
linux中的异步IO：select， poll 和 epoll https://jvns.ca/blog/2017/06/03/async-io-on-linux--select--poll--and-epoll/ 

开源项目架构之nginx http://aosabook.org/en/nginx.html

**Comment by leviding** [comment]
@Zheng7426 @razertory 收到，感谢

**Comment by leviding** [comment]
@razertory 收到，经核查未被翻译，则会在本周发布翻译认领。欢迎多多推荐相关内容

**Comment by Colafornia** [comment]
推荐优秀英文文章 [Inside look at modern web browser](https://developers.google.com/web/updates/2018/09/inside-browser-part1)

若决定收录，自荐翻译

**Comment by leviding** [comment]
@Colafornia 已发布，认领吧

**Comment by leviding** [comment]
@razertory 您推荐的第一篇一有译文，第二篇已发布翻译认领。

**Comment by leviding** [comment]
* iOS
* 产品
* 设计
* Linux
* deep learning
* computer vision
* Django Flask
* 后端
* 前端
