### ISSUE TITLE
CSS 变量和 JavaScript 让应用支持动态主题 🎨

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4384]
* 原文链接：[Dynamic App Themes with CSS Variables and JavaScript 🎨](https://itnext.io/css-variables-dynamic-app-themes-86c0db61cbbb)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/css-variables-dynamic-app-themes.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4399
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoolRice** [comment]
@leviding , 翻译认领

**Comment by fanyijihua** [comment]
@CoolRice 棒极啦 :tada:
