### ISSUE TITLE
JavaScript 2018 中即将迎来的新功能：异步生成器及更好的正则表达式

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4385]
* 原文链接：[What’s Coming Up in JavaScript 2018: Async Generators, Better Regex](https://thenewstack.io/whats-coming-up-in-javascript-2018-async-generators-better-regex/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4394
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MeFelixWang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MeFelixWang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4394
