### ISSUE TITLE
在 JavaScript 中 为什么你应当使用 map 和 filter 来替代 forEach

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4388]
* 原文链接：[Why you should replace forEach with map and filter in JavaScript](https://gofore.com/en/why-you-should-replace-foreach/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-you-should-replace-foreach.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4411
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhmhhu** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@zhmhhu 棒极啦 :tada:
