### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by raoenhui** [xitu/gold-miner#4390]
- 原文链接：https://github.com/zeit/next.js/blob/canary/README.md
- 简要介绍：next.js官方文档
我已经翻译好，想放入掘金翻译计划中https://raoenhui.github.io/nextjs/2018/08/31/Nextjs%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3/

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@raoenhui 好的，感谢推荐，加一下微信 517010193，明天白天和您确认下详细信息，加入掘金翻译计划。

**Comment by raoenhui** [comment]
已加
