### ISSUE TITLE
如何使用原生 JavaScript 构建简单的 Chrome 扩展程序

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4395]
* 原文链接：[How to Build a Simple Chrome Extension in Vanilla JavaScript](https://medium.com/javascript-in-plain-english/https-medium-com-javascript-in-plain-english-how-to-build-a-simple-chrome-extension-in-vanilla-javascript-e52b2994aeeb)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-build-a-simple-chrome-extension-in-vanilla-javascript.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4418
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：4-6 分
  * 校对积分：2-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shery** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@shery 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4418
