### ISSUE TITLE
认领【编写高质量的 Swift 代码(markdown)】

### ISSUE THREAD

**Issue by vizlabxt** [xitu/gold-miner#44]
支付宝iOS开发，曾经写过一篇关于swift的文章http://vizlabxt.github.io/blog/2014/12/23/Swift-Memory/

可以胜任翻译工作

**Comment by Glowin** [comment]
你好，看了你的 swift 文章，把  Swift 中对象的内存模型讲解的很清晰，欢迎来翻译技术文章，我给你加入到 readme 了 :+1:

**Comment by Glowin** [comment]
不好意思出了个小插曲，这篇文章昨天晚上被@skcheer 认领了，你看看能不能选一个其他的文章呢？谢谢理解。

**Comment by vizlabxt** [comment]
我看到所有文章都已经被认领了。。。

**Comment by Glowin** [comment]
你好，现在挑选出来的文章已经被认领完了，但是这个翻译计划还是会一直更新维护下去，我新建了一个掘金翻译计划的微信群，并会在群里面通报翻译活动的最新进展，希望你能加一下我微信 Glowjiang，感谢你的支持和理解。

**Comment by Glowin** [comment]
@vizlabxt 早上好，我们又有一批新的文章等待你的翻译，欢迎来认领文章，谢谢啦。
