### ISSUE TITLE
GopherCon 2018：揭秘二叉查找树算法

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4400]
* 原文链接：[GopherCon 2018 - Demystifying Binary Search Tree Algorithms](https://about.sourcegraph.com/go/gophercon-2018-binary-search-tree-algorithms/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/gophercon-2018-binary-search-tree-algorithms.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4402
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@changkun 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4402
