### ISSUE TITLE
为 APP 设计通知提醒

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4401]
* 原文链接：[Designing notifications for apps: Explore different notification models and when to use which](https://medium.muz.li/designing-notifications-for-applications-3cad56fecf96)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/designing-notifications-for-applications.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4445
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rydensun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@rydensun 棒极啦 :tada:

**Comment by rydensun** [comment]
不好意思，这篇可能会拖几天，想校对的同学对不起了。最近公司突然有业务过来。

**Comment by leviding** [comment]
好的哈，辛苦啦

**Comment by pkuwwt** [comment]
校对认领

**Comment by leviding** [comment]
@pkuwwt 👌
