### ISSUE TITLE
构建未来的设计生态系统

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4405]
* 原文链接：[Building the Design Ecosystem of the Future](https://medium.com/@pablostanley/building-the-design-ecosystem-of-the-future-d22b663fed1f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/building-the-design-ecosystem-of-the-future.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4414
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MeFelixWang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MeFelixWang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4414
