### ISSUE TITLE
this 到底指向什么 — 理解 JavaScript 中的 this、call、apply 和 bind

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4406]
* 原文链接：[WTF is this - Understanding the this keyword, call, apply, and bind in JavaScript](https://tylermcginnis.com/this-keyword-call-apply-bind-javascript/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/this-keyword-call-apply-bind-javascript.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4442
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5-7 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoolRice** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@CoolRice 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4442
