### ISSUE TITLE
正确实现 linkedPurchaseToken 以避免重复订阅 

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4408]
* 原文链接：[Implementing linkedPurchaseToken correctly to prevent duplicate subscriptions](https://medium.com/androiddevelopers/implementing-linkedpurchasetoken-correctly-to-prevent-duplicate-subscriptions-82dfbf7167da)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/implementing-linkedpurchasetoken-correctly-to-prevent-duplicate-subscriptions.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4510
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
Awesome！

**Comment by fanyijihua** [comment]
PR 地址：#4510
