### ISSUE TITLE
现代浏览器内部揭秘（第一部分）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4409]
* 原文链接：[Inside look at modern web browser (part 1)](https://developers.google.com/web/updates/2018/09/inside-browser-part1)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/inside-look-at-modern-web-browser-part1.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4419
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@Colafornia 你的

**Comment by Colafornia** [comment]
翻译认领
@leviding 谢啦

**Comment by fanyijihua** [comment]
@Colafornia 棒极啦 :tada:
