### ISSUE TITLE
申请成为前端开发译者

### ISSUE THREAD

**Issue by emmiter** [xitu/gold-miner#441]
13年毕业于南方某211大学计算机科学与技术专业。毕业后先是从事了6个月iOS开发，后在公司内部转岗到前端岗。

在无人带领的情况下，用一周多点时间在 www.w3schools.com 学习了前端技术栈中最基本的知识点:HTML/CSS/Javascript/jQuery/PHP. 并且独立完成了公司微信公众号第三方页面的开发工作.后续工作中也陆续接触到一些其他库如Zepto/Underscore和部分当下热议的框架(Angular和Vue)。

工作中我学习新技术的方法几乎全部来自官方文档(包括社区)/国外博客/stackoverflow和Youtube视频。 比如在工作中先开始只是手动引入第三方库，后来gulp代替grunt成为新的宠儿时，我便通过在youtube上学习gulp教程，很快就将gulp应用到自己的前端自动化构建流程中，立即提升了项目质量和工作效率。

最近在着手做React+Redux+webpack的项目，更是看了很多社区牛人的文章，受益匪浅。 鉴于对自己对新技术的关注，以及对自己英文水平的认可，希望也能加入掘金翻译计划，回馈社区的同时不断提升自己。

感谢鼓励我尝试申请的 @zerob13 (github Id && weibo Id，掘金社区成员) 一个在我前端成长过程中给过我很多指点的人。

**Comment by antonia0912** [comment]
@emmiter 组织欢迎你~请加我微信 antonia0912 备注github ID 我拉你进译者群
