### ISSUE TITLE
开源项目之Nginx

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4410]
* 原文链接：[The Open Source Project Nginx](http://aosabook.org/en/nginx.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-open-source-project-nginx.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4570
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10-12 分
  * 校对积分：3-5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by leviding** [comment]
@lsvih 翻译的怎么样啦

**Comment by leviding** [comment]
@lsvih 释放了哈

**Comment by razertory** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@razertory 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4570
