### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by unimp** [xitu/gold-miner#4416]
- 原文链接：http://t.cn/Rs6poQS
- 简要介绍：从四个角度分析用户选择一款产品背后的驱动因素。
1.稀缺资源
2.六种需求
3.七宗罪
4.人生目标

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@unimp 感谢推荐，已发布翻译认领，奖励 0.5 积分/篇。
