### ISSUE TITLE
四个「为什么」：是什么在背后驱动你的产品？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4421]
* 原文链接：[The 4 types of ‘Why’: What is the driving force behind your product?](https://medium.com/@kit_ulrich/the-4-types-of-why-what-is-the-driving-force-behind-your-product-1b06fb4ef7bc)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-4-types-of-why-what-is-the-driving-force-behind-your-product.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4496
  * 文章分类：**产品**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4439

**Comment by fanyijihua** [comment]
PR 地址：#4496

**Comment by pmwangyang** [comment]
@leviding 已重新发PR，麻烦更新下ISSUE中对应的PR地址。
