### ISSUE TITLE
Better stats for better decisions

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4422]
* 原文链接：[Better stats for better decisions](https://medium.com/googleplaydev/better-stats-for-better-decisions-3661717b4f2d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/better-stats-for-better-decisions.md)
  * PR 地址：
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5-7 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by siegeout** [comment]
认领一发♂

**Comment by leviding** [comment]
@siegeout 好的，可以翻译啦

**Comment by leviding** [comment]
@zx-Zhu sorry，先来后到，欢迎您认领另一篇 Android 的哈

**Comment by leviding** [comment]
@siegeout 这篇翻译的怎么样了？超期了呢，超期过久会被重新释放并记录。
