### ISSUE TITLE
另外 5 种关于视觉和认知间差异的绘画练习

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4423]
* 原文链接：[5 more drawing exercises on the difference between seeing and knowing](https://medium.com/personal-growth/5-more-drawing-exercises-9c0df4645387)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/5-more-drawing-exercises.md)
  * PR 地址：#4462
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1-2 天
  * 翻译积分：3-5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ruixi** [comment]
翻译认领
好久没弄了😂

**Comment by fanyijihua** [comment]
@Ruixi 棒极啦 :tada:

**Comment by leviding** [comment]
@Ruixi 欢迎欢迎 🎉 🎉

**Comment by Ruixi** [comment]
连着加了两天班，还剩一点尾巴，今天24点之前初稿会出来。

**Comment by leviding** [comment]
@Ruixi 好的

**Comment by fanyijihua** [comment]
PR 地址：#4462
