### ISSUE TITLE
2018 年度最佳数据库即服务解决方案

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4425]
* 原文链接：[The Best Database-as-a-Service Solutions of 2018](https://uk.pcmag.com/software/116526/guide/the-best-database-as-a-service-solutions-of-2018)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-best-database-as-a-service-solutions-of-2018.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4460
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6-7 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cf020031308** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cf020031308 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4460
