### ISSUE TITLE
JAVASCRIPT 日期权威指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4426]
* 原文链接：[THE DEFINITIVE GUIDE TO JAVASCRIPT DATES](https://flaviocopes.com/javascript-dates/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-definitive-guide-to-javascript-dates.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4437
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoderMing** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@CoderMing 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4437
