### ISSUE TITLE
用 API​​ 请求制作赏心悦目的 UX

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4427]
* 原文链接：[Crafting beautiful UX with API requests](https://uxdesign.cc/crafting-beautiful-ux-with-api-requests-56e7dcc2f58e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/crafting-beautiful-ux-with-api-requests.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4435
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MeFelixWang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MeFelixWang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4435
