### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by alowkeyguy** [xitu/gold-miner#4433]
- 原文链接：http://davidshariff.com/blog/what-is-the-execution-context-in-javascript/
- 简要介绍：David Shariff（Yahoo, RBS, Richi and Trend Micro.）从浏览器解释器的工作原理，通过分析执行上下文来阐述js变量、函数提升是怎么回事，这是面试中高频考点。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@alowkeyguy 感谢推荐，但是很遗憾，经查询本文已经有译文了。
