### ISSUE TITLE
以申请大学流程来解释 JavaScript 的 filter

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4436]
* 原文链接：[JavaScript’s Filter Function Explained By Applying To College](https://codeburst.io/javascripts-filter-function-explained-by-applying-to-college-a21bceeba041)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/javascripts-filter-function-explained-by-applying-to-college.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4441
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@calpa

**Comment by calpa** [comment]
@leviding 我要认领

**Comment by leviding** [comment]
@calpa 👌

**Comment by fanyijihua** [comment]
PR 地址：#4441
