### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by c6n** [xitu/gold-miner#4440]
- 公司/学校：暂无
- 工作内容/专业：暂无
- 常浏览的国外网站：reddit, medium, ycombinator
- 英语水平：大概 CEFR B2
- 翻译经验：不多
- 主要翻译方向：前端
- 个人博客：暂无
- 个人介绍：编程爱好者

目前，已经认真学习了：
- [x] [掘金翻译计划译者教程](https://github.com/xitu/gold-miner/wiki)
   - [x] [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)
   - [x] [翻译和校对文章的注意事项](https://github.com/xitu/gold-miner/wiki/%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88)

同时，也添加了管理员微信 517010193

**Comment by leviding** [comment]
Welcome
