### ISSUE TITLE
理解 JavaScript 中的执行上下文和执行栈

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4444]
* 原文链接：[Understanding Execution Context and Execution Stack in Javascript](https://blog.bitsrc.io/understanding-execution-context-and-execution-stack-in-javascript-1c9ea8642dd0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/understanding-execution-context-and-execution-stack-in-javascript.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4456
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：4-5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoolRice** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@CoolRice 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4456
