### ISSUE TITLE
下一代包管理工具

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4446]
* 原文链接：[Next Generation Package Management](https://blog.npmjs.org/post/178027064160/next-generation-package-management)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/next-generation-package-management.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4466
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：1-2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by diliburong** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@diliburong 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4466
