### ISSUE TITLE
React Profiler 介绍

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4447]
* 原文链接：[Introducing the React Profiler](https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/introducing-the-react-profiler.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4459
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoderMing** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@CoderMing 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4459
