### ISSUE TITLE
现代浏览器内部揭秘（第二部分）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4449]
* 原文链接：[Inside look at modern web browser (part 2)](https://developers.google.com/web/updates/2018/09/inside-browser-part2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/inside-browser-part2.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4555
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6-7 分
  * 校对积分：2-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zheng7426** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Zheng7426 棒极啦 :tada:

**Comment by leviding** [comment]
@Zheng7426 这篇翻译的怎么样了，超期了呢，超期过久会被重新释放并记录。

**Comment by fanyijihua** [comment]
PR 地址：#4555

**Comment by ThomasWhyne** [comment]
@leviding  校对认领
@CoolRice  我在翻译第四篇，可以相互校对啊^^

**Comment by CoolRice** [comment]
@ThomasWhyne ,好哒

**Comment by tian-li** [comment]
@leviding 校对认领
