### ISSUE TITLE
用 Python 实现马尔可夫链的初学者教程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4451]
* 原文链接：[Markov Chains in Python: Beginner Tutorial](https://www.datacamp.com/community/tutorials/markov-chains-python-tutorial)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/markov-chains-python-tutorial.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4499
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6-7 分
  * 校对积分：2-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cdpath** [comment]
🙋‍♂️

**Comment by leviding** [comment]
@cdpath 👌 🤙

**Comment by kasheemlew** [comment]
校对认领
