### ISSUE TITLE
Swift 中的惰性序列及其原理

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4452]
* 原文链接：[Lazy Sequences in Swift And How They Work](https://swiftrocks.com/lazy-sequences-in-swift-and-how-they-work.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/lazy-sequences-in-swift-and-how-they-work.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4477
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by RickeyBoy** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@RickeyBoy 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4477
