### ISSUE TITLE
容器，虚拟机以及 Docker 的初学者入门介绍

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4453]
* 原文链接：[A Beginner-Friendly Introduction to Containers, VMs and Docker](https://medium.freecodecamp.org/a-beginner-friendly-introduction-to-containers-vms-and-docker-79a9e3e119b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-beginner-friendly-introduction-to-containers-vms-and-docker.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4482
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-9 分
  * 校对积分：2-5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by steinliber** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@steinliber 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4482
