### ISSUE TITLE
如何创建一个设计体系来赋能团队 —— 关注人，而非像素

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4454]
* 原文链接：[How building a design system empowers your team to focus on people — not pixels.](https://medium.com/hubspot-product/people-over-pixels-b962c359a14d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-building-a-design-system-empowers-your-team-to-focus-on-people-not-pixels.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4471
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-8 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pmwangyang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@pmwangyang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4471
