### ISSUE TITLE
从产品设计到虚拟现实

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#446]
原文链接：[From product design to virtual reality](https://medium.com/google-design/from-product-design-to-virtual-reality-be46fa793e9b#.mq9cnov35)
掘金链接：[从产品设计到虚拟现实](https://gold.xitu.io/entry/57675b33df0eea0062fcd16b)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/from-product-design-to-virtual-reality.md)

翻译时间：6天
校对时间：5天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Goshin** [comment]
文件链接写错了。。

**Comment by cdpath** [comment]
认领一下 ~

**Comment by antonia0912** [comment]
@cdpath 神速呀  我就吃了俩樱桃。。。。

**Comment by thanksdanny** [comment]
那...我继续占校对坑

**Comment by antonia0912** [comment]
@thanksdanny 先把手里的校对完再认领 现在文章少  好多新译者都没有文章校对  不可以一人占两个的

**Comment by thanksdanny** [comment]
@antonia0912 get！谨遵羊哥教诲！

**Comment by antonia0912** [comment]
@thanksdanny 乖~真上道儿这孩子~~

**Comment by emmiter** [comment]
校对1号报道~

**Comment by antonia0912** [comment]
@emmiter @ldhlfzysys [校对地址](https://github.com/xitu/gold-miner/pull/481/files?diff=split)
