### ISSUE TITLE
./dogs.html 和 /dogs.html 间有什么区别？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4469]
* 原文链接：[What’s the difference between ./dogs.html and /dogs.html?](https://css-tricks.com/whats-the-difference-between-dogs-html-and-dogs-html/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/whats-the-difference-between-dogs-html-and-dogs-html.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4476
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shery** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@shery 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4476

**Comment by kasheemlew** [comment]
校对认领
