### ISSUE TITLE
白雪公主如何帮助 Airbnb 证明在设计中最重要的技能是讲故事

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4484]
* 原文链接：[How Snow White helped Airbnb prove that storytelling is the most important skill in design](https://uxdesign.cc/how-airbnb-proved-that-storytelling-is-the-most-important-skill-in-design-15d04ac71039)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-airbnb-proved-that-storytelling-is-the-most-important-skill-in-design.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4501
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoolRice** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@CoolRice 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4501
