### ISSUE TITLE
新手开发者须知

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4485]
* 原文链接：[Here’s what you need to know as a new developer](https://medium.freecodecamp.org/survival-guide-for-new-developers-12d9b048bf06)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/survival-guide-for-new-developers.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4491
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@ssshooter 🌔

**Comment by fanyijihua** [comment]
PR 地址：#4491
