### ISSUE TITLE
为什么我们需要 Web 3.0

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4486]
* 原文链接：[Why We Need Web 3.0](https://medium.com/s/the-crypto-collection/why-we-need-web-3-0-5da4f2bf95ab)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-we-need-web-3-0.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4535
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoderMing** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@CoderMing 棒极啦 :tada:

**Comment by zx-Zhu** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@zx-Zhu 棒极啦 :tada:
