### ISSUE TITLE
为数字优先新闻编辑室开发文本编辑器

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4488]
* 原文链接：[Building a Text Editor for a Digital-First Newsroom](https://open.nytimes.com/building-a-text-editor-for-a-digital-first-newsroom-f1cb8367fc21)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/building-a-text-editor-for-a-digital-first-newsroom.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4518
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5.5-6.5 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by diliburong** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@diliburong 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4518
