### ISSUE TITLE
如何让你的设计系统被广泛采用

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4489]
* 原文链接：[How to gain widespread adoption of your design system](https://medium.com/hubspot-product/how-to-gain-widespread-adoption-of-your-design-system-29d1b142b158)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-gain-widespread-adoption-of-your-design-system.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4522
  * 文章分类：**产品**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rydensun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@rydensun 棒极啦 :tada:

**Comment by Moonliujk** [comment]
@leviding 校对认领

**Comment by leviding** [comment]
@Moonliujk 好的呢，下次记得在 PR 下认领
