### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by jamweak** [xitu/gold-miner#449]
两年以上的Android开发经验，英语四级601，六级566，官方技术文档习惯性阅读者。英文阅读能力不是问题，希望通过这个翻译计划提升自己的水平，也想通过这个机会认识一群志同道合的开发者。

**Comment by antonia0912** [comment]
@jamweak 组织欢迎你~请加我微信 antonia0912 备注github ID 我拉你进译者群
