### ISSUE TITLE
如果界面产品设计师设计实体产品

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4490]
* 原文链接：[If Screen Product Designers Designed Physical Products](https://thedesignteam.io/if-screen-product-designers-designed-physical-products-10cdd3ac4fdc)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/if-screen-product-designers-designed-physical-products.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4500
  * 文章分类：**产品**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2-2.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ssshooter** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ssshooter 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4500
