### ISSUE TITLE
如何在六个月或更短的时间内成为DevOps 工程师，第三部分：版本控制

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4493]
* 原文链接：[How To Become a DevOps Engineer In Six Months or Less, Part 3: Version](https://medium.com/@devfire/how-to-become-a-devops-engineer-in-six-months-or-less-part-3-version-76034885a7ab)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-become-a-devops-engineer-in-six-months-or-less-part-3-version.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4498
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jianboy** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jianboy 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4498

**Comment by tmpbook** [comment]
@jianboy 我看到你认领了第二和第三部分的翻译，而我刚翻译完第一部分，不如你认领一下校对如何？

**Comment by jianboy** [comment]
> @jianboy 我看到你认领了第二和第三部分的翻译，而我刚翻译完第一部分，不如你认领一下校对如何？

好的呀。
