### ISSUE TITLE
推荐优秀英文文章 —— 二叉树算法算法介绍

### ISSUE THREAD

**Issue by xutaogit** [xitu/gold-miner#4497]
- 原文链接：[二叉树算法算法介绍](https://about.sourcegraph.com/go/gophercon-2018-binary-search-tree-algorithms/)
- 简要介绍：用go语言介绍了二叉树算法原理，还有大量配图。包括二叉树搜索节点，插入节点和删除节点内容；以及二叉树最大值和最小值获取，可谓深入浅出。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by shery** [comment]
@xutaogit 已经翻译过了哟
