### ISSUE TITLE
认领6 Things I wish I Knew before I Wrote my first Android App |

### ISSUE THREAD

**Issue by bobmayuze** [xitu/gold-miner#45]
留学狗一枚－ －希望能贡献下自己了力量＝ ＝
Android还算了解一些，顺手看了下认为没什么问题

**Comment by bobmayuze** [comment]
@Glowin

**Comment by bobmayuze** [comment]
@Glowin  ＝ ＝东西我都交了。。。

**Comment by Glowin** [comment]
居然漏掉了你的 issue 一直没有回复。这个文章在你之前是被@404neko 认领了。但是还是欢迎你来加入翻译组织，我们以后也会有其他的技术文章列出来给大家翻译，欢迎持续关注哟。
