### ISSUE TITLE
深度讲解 Android 的主题

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#450]
原文链接：[Android Themes — An in-depth guide](https://medium.com/@Sserra90/android-themes-an-in-depth-guide-f71f9db6e5bf)
掘金链接：[深度讲解 Android 的主题](https://gold.xitu.io/entry/5768b0d77f578500549275af)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/android-themes-an-in-depth-guide.md)

翻译时间：6天
校对时间：5天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by aidistan** [comment]
申请翻译

**Comment by shixinzhang** [comment]
申请校对

**Comment by a-voyager** [comment]
申请校对

**Comment by antonia0912** [comment]
@aidistan 好的  等你 PR ， 发 PR 后记得圈 @shixinzhang @a-voyager 来校对喔

**Comment by antonia0912** [comment]
@shixinzhang @a-voyager [校对地址](https://github.com/xitu/gold-miner/pull/452/files?diff=split)

**Comment by aidistan** [comment]
请 @shixinzhang 同学抓紧校对哟~
请 @antonia0912 老师解答一下 PR 里的问的难题哟~

**Comment by shixinzhang** [comment]
@aidistan 不好意思来晚了，我抓紧！

**Comment by shixinzhang** [comment]
@aidistan 翻译的还是很好的，没有什么问题，我硬是挑了一些小瑕疵哈哈，可能有不准确的地方望保函
@antonia0912 校对完成
