### ISSUE TITLE
如何在东南亚拓展您的应用业务

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4502]
* 原文链接：[How to grow your app business in Southeast Asia](https://medium.com/googleplaydev/building-a-successful-app-or-game-business-in-southeast-asia-29e6eea0defb)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/building-a-successful-app-or-game-business-in-southeast-asia.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4519
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1.5 天
  * 翻译积分：5-6 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jianboy** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jianboy 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4519
