### ISSUE TITLE
更好的数据，更明智的决策

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4503]
* 原文链接：[Better stats for better decisions](https://medium.com/googleplaydev/better-stats-for-better-decisions-3661717b4f2d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/better-stats-for-better-decisionsbetter-stats-for-better-decisions.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4534
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5-6 分
  * 校对积分：2-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by BriFuture** [comment]
翻译申领 @leviding

**Comment by leviding** [comment]
@BriFuture 好的呢

**Comment by fanyijihua** [comment]
PR 地址：#4534
