### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by samt42** [xitu/gold-miner#4505]
- 原文链接：https://medium.com/@hatajoe/clean-architecture-in-go-4030f11ec1b1
- 简要介绍：结合领域驱动设计（DDD）的概念，提出的一种Go语言工程组织结构，值得借鉴

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@samt42 感谢推荐，已发布翻译认领，奖励推荐文章积分
