### ISSUE TITLE
Go 语言的整洁架构之道/一个使用 gRPC 的 Go 项目整洁架构例子

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4509]
* 原文链接：[Clean Architecture in Go: An example of clean architecture in Go using gRPC](https://medium.com/@hatajoe/clean-architecture-in-go-4030f11ec1b1)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/clean-architecture-in-go.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4521
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)·

**Comment by yuwhuawang** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@yuwhuawang 棒极啦 :tada:
