### ISSUE TITLE
iOS 开发者在 Swift 代码中应避免过度使用 @objc

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#451]
原文链接：[Avoiding the overuse of @objc in Swift](http://www.jessesquires.com/avoiding-objc-in-swift/)
掘金链接：[iOS 开发者在 Swift 代码中应避免过度使用 @objc](https://gold.xitu.io/entry/5767f0e96be3ff006a3af837)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/avoiding-objc-in-swift.md)

翻译时间：5天
校对时间：3天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by ldhlfzysys** [comment]
我最快！oh ye

**Comment by ldhlfzysys** [comment]
前排占位，认领

**Comment by antonia0912** [comment]
@ldhlfzysys 哈哈哈  等你PR

**Comment by owenlyn** [comment]
@antonia0912  我又来占坑校对啦~~

**Comment by jkjk77** [comment]
@ldhlfzysys 占坑校对

**Comment by antonia0912** [comment]
@owenlyn @jkjk77 译者初步翻译已经完成 [校对地址](https://github.com/xitu/gold-miner/pull/459/files?diff=split)

**Comment by owenlyn** [comment]
@antonia0912  on my way

**Comment by jk77me** [comment]
😬
