### ISSUE TITLE
Immer 下的不可突变数据和 React 的 setState

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4516]
* 原文链接：[Immutable Data with Immer and React setState](https://codeburst.io/immutable-data-with-immer-and-react-setstate-887e8f3ad667)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/immutable-data-with-immer-and-react-setstate.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4547
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by HaoChuan9421** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@HaoChuan9421 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4547
