### ISSUE TITLE
如何使用 JavaScript ES6 有条件地构造对象

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4517]
* 原文链接：[How to conditionally build an object in JavaScript with ES6](https://medium.freecodecamp.org/how-to-conditionally-build-an-object-in-javascript-with-es6-e2c49022c448)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-conditionally-build-an-object-in-javascript-with-es6.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4523
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ssshooter** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ssshooter 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4523
