### ISSUE TITLE
什么是模块化 CSS？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4520]
* 原文链接：[What is Modular CSS?](https://spaceninja.com/2018/09/17/what-is-modular-css/?utm_source=CSS-Weekly&utm_campaign=Issue-332&utm_medium=email)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-is-modular-css.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4538
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：7.5-9 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ssshooter** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ssshooter 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4538
