### ISSUE TITLE
如何组织 Hacktoberfest 主题聚会

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4524]
* 原文链接：[How to organize a Hacktoberfest-themed meetup](https://hacktoberfest.digitalocean.com/eventkit)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-organize-a-hacktoberfest-themed-meetup.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4546
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jianboy** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jianboy 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4546
