### ISSUE TITLE
初创公司的数据科学：简介

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4525]
* 原文链接：[Data Science for Startups: Introduction](https://towardsdatascience.com/data-science-for-startups-introduction-80d022a18aec)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/data-science-for-startups-introduction.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4605
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tmpbook** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@tmpbook 棒极啦 :tada:

**Comment by leviding** [comment]
@tmpbook 翻译的怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#4605
