### ISSUE TITLE
作为自由开发者，7 个步骤让你获得更多的客户

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4527]
* 原文链接：[How to get more clients as a freelance developer](https://medium.freecodecamp.org/7-steps-to-get-more-clients-as-a-freelance-developer-ee00342f9260)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/7-steps-to-get-more-clients-as-a-freelance-developer.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4623
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5-6 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rydensun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@rydensun 棒极啦 :tada:

**Comment by leviding** [comment]
@rydensun 翻译的怎么样啦
