### ISSUE TITLE
你需要知道的所有 Flexbox 排列方式

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4529]
* 原文链接：[Everything You Need To Know About Alignment In Flexbox](https://www.smashingmagazine.com/2018/08/flexbox-alignment/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/flexbox-alignment.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4588
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6-7 分
  * 校对积分：2-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoderMing** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@CoderMing 棒极啦 :tada:

**Comment by leviding** [comment]
@CoderMing 翻译的怎么样啦

**Comment by CoderMing** [comment]
@leviding  还差一点，今晚收工

**Comment by fanyijihua** [comment]
PR 地址：#4588
