### ISSUE TITLE
当你创建 Flexbox 布局时，都发生了什么

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4530]
* 原文链接：[What Happens When You Create A Flexbox Flex Container?](https://www.smashingmagazine.com/2018/08/flexbox-display-flex-container/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/flexbox-display-flex-container.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4539
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6-7 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by linxuesia** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@linxuesia 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4539

**Comment by linxuesia** [comment]
@leviding  发布啦 https://juejin.im/post/5bb9740de51d450e782647ed
