### ISSUE TITLE
Rust 开发完整的 Web 应用程序

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4532]
* 原文链接：[A web application completely in Rust](https://medium.com/@saschagrunert/a-web-application-completely-in-rust-6f6bdb6c4471)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-web-application-completely-in-rust.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4650
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-6 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Raoul1996** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Raoul1996 棒极啦 :tada:
