### ISSUE TITLE
Node.js 高性能和可扩展应用程序的最佳实践[第 1/3 部分]

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4536]
* 原文链接：[Good practices for high-performance and scalable Node.js applications [Part 1/3]](https://medium.com/iquii/good-practices-for-high-performance-and-scalable-node-js-applications-part-1-3-bb06b6204197)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/good-practices-for-high-performance-and-scalable-node-js-applications-part-1-3.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4564
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jianboy** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jianboy 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4564
