### ISSUE TITLE
Three Input element properties that I discovered while reading MDN

### ISSUE THREAD

**Issue by sakila1012** [xitu/gold-miner#4540]
- 原文链接：https://dev.to/stefanjudis/three-input-element-properties-that-i-discovered-while-reading-mdn-30fg
- 简要介绍：HTML 网页的 <input> 元素有几十个属性，本文介绍其中三个开发者比较不熟悉的属性。

**Comment by leviding** [comment]
@sakila1012 感谢推荐，已发布翻译认领，奖励推荐计积分。
