### ISSUE TITLE
我在阅读 MDN 时发现的 3 个 Input 元素属性

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4541]
* 原文链接：[Three Input element properties that I discovered while reading MDN](https://dev.to/stefanjudis/three-input-element-properties-that-i-discovered-while-reading-mdn-30fg)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/three-input-element-properties-that-i-discovered-while-reading-mdn.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4551
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：1-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ssshooter** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ssshooter 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4551
