### ISSUE TITLE
数据科学和机器学习面试问题

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4544]
* 原文链接：[Data Science and Machine Learning Interview Questions](https://towardsdatascience.com/data-science-and-machine-learning-interview-questions-3f6207cf040b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/data-science-and-machine-learning-interview-questions.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4552
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：1.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jianboy** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jianboy 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4552
