### ISSUE TITLE
深度学习将会给我们所有人的生活一个教训：工作是为了机器准备的

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4545]
* 原文链接：[Deep Learning Is Going to Teach Us All the Lesson of Our Lives: Jobs Are for Machines](https://medium.com/basic-income/deep-learning-is-going-to-teach-us-all-the-lesson-of-our-lives-jobs-are-for-machines-7c6442e37a49)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/deep-learning-is-going-to-teach-us-all-the-lesson-of-our-lives-jobs-are-for-machines.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4607
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-9 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yuwhuawang** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@yuwhuawang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4607
