### ISSUE TITLE
基于评论的机器学习在线课程排名

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4549]
* 原文链接：[Every single Machine Learning course on the internet, ranked by your reviews](https://medium.freecodecamp.org/every-single-machine-learning-course-on-the-internet-ranked-by-your-reviews-3c4a7b8026c0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/every-single-machine-learning-course-on-the-internet-ranked-by-your-reviews.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4601
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：8-12 分
  * 校对积分：3-6 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
本文虽然机器之心翻译过，但是质量并不是特别好，希望能够有 AI 方向的译者能够将这篇文章翻译好。

**Comment by davelet** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@davelet 棒极啦 :tada:
