### ISSUE TITLE
现代浏览器内部揭秘（第三部分）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4550]
* 原文链接：[Inside look at modern web browser (part 3)](https://developers.google.com/web/updates/2018/09/inside-browser-part3)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/inside-browser-part3.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4567
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6-7 分
  * 校对积分：2-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ssshooter** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ssshooter 棒极啦 :tada:

**Comment by zwwill** [comment]
刚看完就被认领了。。

**Comment by fanyijihua** [comment]
PR 地址：#4567
