### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by poppinlp** [xitu/gold-miner#456]
- 前端开发没几年经验
- 参与过几个翻译项目
- 萌萌哒 >.<

**Comment by antonia0912** [comment]
@poppinlp 请问平时都从哪些外文网站上获取新知识  翻译项目的链接有吗

**Comment by poppinlp** [comment]
新姿势的话主要是订阅的一些东西，翻译的话

- https://github.com/1sters/material_design_zh
- https://developer.mozilla.org 里面的一些中文内容
- https://github.com/html5rocks/www.html5rocks.com

**Comment by antonia0912** [comment]
@poppinlp 代表组织欢迎你  请加我微信 antonia0912 备注github ID 我来拉你进译者群
