### ISSUE TITLE
使 WebAssembly 更快：Firefox 的新流式和分层编译器

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4560]
* 原文链接：[Making WebAssembly even faster: Firefox’s new streaming and tiering compiler](https://hacks.mozilla.org/2018/01/making-webassembly-even-faster-firefoxs-new-streaming-and-tiering-compiler/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/making-webassembly-even-faster-firefoxs-new-streaming-and-tiering-compiler.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4587
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xutaogit** [comment]
翻译认领。 @leviding

**Comment by fanyijihua** [comment]
@xutaogit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4587
