### ISSUE TITLE
使用 JavaScript 和网络信息 API 实现自适应服务

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4581]
* 原文链接：[Adaptive Serving using JavaScript and the Network Information API](https://dev.to/addyosmani/adaptive-serving-using-javascript-and-the-network-information-api-331p)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/adaptive-serving-using-javascript-and-the-network-information-api.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4591
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Raoul1996** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Raoul1996 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4591
