### ISSUE TITLE
A React job interview — recruiter perspective.

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4582]
* 原文链接：[A React job interview — recruiter perspective.](https://medium.com/@baphemot/a-react-job-interview-recruiter-perspective-f1096f54dd16)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-react-job-interview-recruiter-perspective.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4615
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6-7 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoolRice** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@CoolRice 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4615
