### ISSUE TITLE
开启性能预算

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4583]
* 原文链接：[Start Performance Budgeting](https://medium.com/@addyosmani/start-performance-budgeting-dabde04cf6a3)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/start-performance-budgeting.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4617
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xutaogit** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@xutaogit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4617
