### ISSUE TITLE
动效设计可以很简单

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4584]
* 原文链接：[Motion Design Doesn’t Have to Be Hard](https://medium.com/google-design/motion-design-doesnt-have-to-be-hard-33089196e6c2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/motion-design-doesnt-have-to-be-hard.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4616
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rydensun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@rydensun 棒极啦 :tada:
