### ISSUE TITLE
认领Making React Native apps accessible

### ISSUE THREAD

**Issue by RoyTimes** [xitu/gold-miner#46]
翻译过很多文章。托福分数103 美国读过一段书 正好学习一些React Native

**Comment by RoyTimes** [comment]
@Glowin

**Comment by Glowin** [comment]
非常抱歉啊，这篇文章在你之前已经被@void-main 认领了 #73 并完成了初稿，很抱歉现在才回复你 issue。我们这个翻译计划还会有后续的活动，欢迎你继续关注我们的 repo。

另外，你可以加我微信Glowjiang，我来拉你进活动的译者群。再次对我晚回复 issue 表示歉意。

**Comment by Glowin** [comment]
@RoyTimes 早上好，我们又有一批新的文章等待你的翻译，欢迎来认领文章，谢谢啦。
