### ISSUE TITLE
申请前端译者

### ISSUE THREAD

**Issue by imyangmo** [xitu/gold-miner#460]
曾听译及翻译：
AngularJS 入门教学视频 http://blog.jobbole.com/87995/
TryjQuery：jQuery官方推出的教学视频 http://blog.jobbole.com/37699/
那天我们招了一个盲人程序员 http://blog.jobbole.com/102761/

**Comment by antonia0912** [comment]
@imyangmo 欢迎参加掘金翻译计划 请加我微信 antonia0912 备注github ID 我拉你进译者群哈
