### ISSUE TITLE
深度专注的工作 — 成为 10 倍效率的开发者的秘密武器

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4603]
* 原文链接：[Focus and Deep Work — Your Secret Weapons to Becoming a 10X Developer](https://medium.freecodecamp.org/focus-and-deep-work-your-secret-weapons-to-becoming-a-10x-developer-8e203a6ad291)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/focus-and-deep-work-your-secret-weapons-to-becoming-a-10x-developer.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4769
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-7 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tmpbook** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@tmpbook 棒极啦 :tada:

**Comment by leviding** [comment]
@tmpbook 翻译的怎么样了

**Comment by tmpbook** [comment]
再给点时间。。。最近有点忙

**Comment by leviding** [comment]
好的 🚀

**Comment by tmpbook** [comment]
> @tmpbook 这篇翻译的怎么样啦

豁出去了，今天交

**Comment by fanyijihua** [comment]
PR 地址：#4769
