### ISSUE TITLE
职业成长的内部指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4611]
* 原文链接：[The Introvert's Guide to Professional Development](https://dev.to/geekgalgroks/the-introverts-guide-to-professional-development-3408)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-introverts-guide-to-professional-development.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4618
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yuwhuawang** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@yuwhuawang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4618
