### ISSUE TITLE
在远程工作中领悟到的 10 件事

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4612]
* 原文链接：[10 things I've learned from working remotely](https://dev.to/lkopacz/10-things-ive-learned-from-working-remotely-240h)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/10-things-ive-learned-from-working-remotely.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4752
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4752
