### ISSUE TITLE
Google 工程师提升网页性能的新策略：空闲到紧急

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4619]
* 原文链接：[Idle Until Urgent](https://philipwalton.com/articles/idle-until-urgent/?utm_source=mybridge&utm_medium=blog&utm_campaign=read_more)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/idle-until-urgent.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4658
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：9-12 分
  * 校对积分：2-5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ivocin** [comment]
认领翻译， @leviding

**Comment by fanyijihua** [comment]
@Ivocin 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4658
