### ISSUE TITLE
Java 不可变类的整洁之道

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#462]
原文链接：[Clean Java immutability](http://blog.alexsimo.com/clean-java-immutability/)
掘金链接：[Java 不可变类的整洁之道](https://gold.xitu.io/entry/576babf72e958a00571652a6)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/clean-java-immutability.md)

翻译时间：5天
校对时间：3天
翻译积分：5
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Gjetertaske** [comment]
认领翻译

**Comment by a-voyager** [comment]
申请校对

**Comment by jamweak** [comment]
预约校对啊~这个名字还是我贡献的呢~

**Comment by buccoji** [comment]
认领翻译

**Comment by antonia0912** [comment]
@buccoji markdown 文件已经补充完整 可以开始翻译啦 有问题在群里问大家就可以啦 发 PR 后记得圈 @a-voyager @jamweak 来校对哈~

**Comment by buccoji** [comment]
@antonia0912 好的，收到。

完成后将会通知 WuHaojie 先生 (@a-voyager) 和 jamweak 先生 (@jamweak ) 校对。

**Comment by buccoji** [comment]
已翻译完毕：https://github.com/xitu/gold-miner/pull/465
@a-voyager @jamweak
