### ISSUE TITLE
设计师的决策树

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4621]
* 原文链接：[A Decision Tree for Designers](https://medium.com/s/story/the-design-system-decision-tree-edba9abdb83b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-design-system-decision-tree.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4675
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhmhhu** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@zhmhhu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4675
