### ISSUE TITLE
产品管理思维模式适合每一个人

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4622]
* 原文链接：[Product Management Mental Models for Everyone](https://blackboxofpm.com/product-management-mental-models-for-everyone-31e7828cb50b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/product-management-mental-models-for-everyone.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4884
  * 文章分类：**产品**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：8-10 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by noturnot** [comment]
我又来啦~翻译求认领~

**Comment by noturnot** [comment]
我又来啦~ 翻译求认领~

**Comment by leviding** [comment]
@noturnot 好呢，欢迎欢迎 👏

**Comment by leviding** [comment]
@noturnot 您超期太久了，加了几次微信都无果，不好意思，本文重新释放。望领了文章能够按时完成。

**Comment by EmilyQiRabbit** [comment]
@leviding 认领翻译

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by leviding** [comment]
@EmilyQiRabbit 这篇文章翻译的怎么样拉我

**Comment by EmilyQiRabbit** [comment]
@leviding 快好了，最晚明天嗯嗯。

**Comment by fanyijihua** [comment]
PR 地址：#4884

**Comment by EmilyQiRabbit** [comment]
@leviding 翻译完成
