### ISSUE TITLE
源代码映射（Source Map）简介

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4625]
* 原文链接：[An Introduction to Source Maps](https://blog.teamtreehouse.com/introduction-source-maps)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/introduction-source-maps.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4633
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1.2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
认领翻译 @leviding

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4633

**Comment by EmilyQiRabbit** [comment]
翻译完成 @leviding
