### ISSUE TITLE
代码评审的 8 点建议

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4632]
* 原文链接：[8 Tips for Great Code Reviews](https://kellysutton.com/2018/10/08/8-tips-for-great-code-reviews.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/8-tips-for-great-code-reviews.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4635
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xiaoxi666** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@xiaoxi666 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4635

**Comment by Augustwuli** [comment]
校对认领 @leviding

**Comment by Augustwuli** [comment]
@leviding 校对认领
