### ISSUE TITLE
GitHub Actions 介绍，了解一下？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4639]
* 原文链接：[Introducing GitHub Actions](https://css-tricks.com/introducing-github-actions/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/introducing-github-actions.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4671
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-8 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoolRice** [comment]
最近这两周比较忙，大概明天能翻完
