### ISSUE TITLE
如何停止使用 console.log() 并开始使用浏览器调试代码

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4640]
* 原文链接：[How to stop using console.log() and start using your browser’s debugger](https://medium.com/datadriveninvestor/stopping-using-console-log-and-start-using-your-browsers-debugger-62bc893d93ff)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/stopping-using-console-log-and-start-using-your-browsers-debugger.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4653
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Augustwuli** [comment]
@leviding翻译认领

**Comment by fanyijihua** [comment]
@Augustwuli 棒极啦 :tada:

**Comment by Marszht** [comment]
@fanyijihua 翻译认领

**Comment by Marszht** [comment]
翻译校对 @fanyijihua

**Comment by leviding** [comment]
@Marszht 看下译者教程，里面写了如何认领任务 https://github.com/xitu/gold-miner/wiki

**Comment by fanyijihua** [comment]
PR 地址：#4653
