### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by qdlaoyao** [xitu/gold-miner#4641]
- 原文链接：[https://tallys.github.io/color-theory/](https://tallys.github.io/color-theory/)
- 简要介绍：给程序员的色彩理论。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by qdlaoyao** [comment]
网站升级协议了。。。https://tallys.github.io/color-theory/

**Comment by leviding** [comment]
您好，本文很好，但是很难转换成 Markdown 进行翻译计划的翻译流程，所以很遗憾。希望能继续推荐其他优秀英文文章。
