### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by DMXL** [xitu/gold-miner#4642]
- 原文链接：[JavaScript for impatient programmers](http://exploringjs.com/impatient-js/toc.html)
- 简要介绍：非常好的JS教程，有别于其他同类教程或书籍，这本书专注于modern js的特性，全是干货，废话和赘述很少，辅助quiz质量也很高

> - The book covers all essential features of the language, up to and including ECMAScript 2018 (the current standard).
>   - The focus on modern JavaScript means that there are many features you don’t have to learn initially – maybe ever (e.g., var).
>   - These features are still mentioned, along with pointers to documentation.
> - There are test-driven exercises and quizzes for most chapters (paid feature).
> - Includes advanced sections, so you can occasionally dig deeper – if you want to.

**Comment by leviding** [comment]
感谢推荐，翻译书籍很难进行授权申请，这个内容很好，以放入库存，希望未来有时间可以加入翻译计划。

欢迎推荐更多优秀的英文文章。
