### ISSUE TITLE
6 个最令人满意的和编程相关的工作（和参与这些工作的人们的类型）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4644]
* 原文链接：[The 6 most desirable coding jobs (and the types of people drawn to each)](https://medium.freecodecamp.org/the-6-most-desirable-coding-jobs-and-the-types-of-people-drawn-to-each-aebac45fd7f7)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-6-most-desirable-coding-jobs-and-the-types-of-people-drawn-to-each.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4673
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Augustwuli** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@Augustwuli 棒极啦 :tada:
