### ISSUE TITLE
我是如何在谷歌找到 UX 设计的工作的

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4647]
* 原文链接：[How I landed a job in UX Design at Google](https://uxdesign.cc/how-i-landed-a-job-in-ux-design-at-google-58103f8bf766)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-i-landed-a-job-in-ux-design-at-google.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4720
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-4.5 分
  * 校对积分：1.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@rydensun 来认领吧

**Comment by rydensun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@rydensun 棒极啦 :tada:
