### ISSUE TITLE
转向三人工程小组

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4649]
* 原文链接：[Moving to three-person engineering teams](https://medium.com/do-not-erase/moving-to-three-person-engineering-teams-bcf599670c2a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/moving-to-three-person-engineering-teams.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4782
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yuwhuawang** [comment]
@leviding 认领翻译

**Comment by fanyijihua** [comment]
@yuwhuawang 棒极啦 :tada:

**Comment by yuwhuawang** [comment]
翻译完成https://github.com/xitu/gold-miner/pull/4782

**Comment by yuwhuawang** [comment]
@leviding
