### ISSUE TITLE
使用 Pandas 在 Python 中创建一个简单的推荐系统

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4654]
* 原文链接：[Creating a Simple Recommender System in Python using Pandas](https://stackabuse.com/creating-a-simple-recommender-system-in-python-using-pandas/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/creating-a-simple-recommender-system-in-python-using-pandas.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4685
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-8 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xilihuasi** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@xilihuasi 棒极啦 :tada:

**Comment by TrWestdoor** [comment]
@xilihuasi 翻译完成后可否艾特我一下，希望校对这篇文章，谢谢朋友。

**Comment by fanyijihua** [comment]
PR 地址：#4685
