### ISSUE TITLE
使用 Pandas 对 Kaggle 数据集进行统计数据分析

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4656]
* 原文链接：[EXPLORATORY STATISTICAL DATA ANALYSIS WITH A KAGGLE DATASET USING PANDAS](http://www.dataden.tech/data-science/exploratory-statistical-data-analysis-with-a-kaggle-dataset-using-pandas/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/exploratory-statistical-data-analysis-with-a-kaggle-dataset-using-pandas.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4681
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5.5-6.5 分
  * 校对积分：2-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by haiyang-tju** [comment]
翻译认领 @leviding @fanyijihua

**Comment by fanyijihua** [comment]
@haiyang-tju 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4681
