### ISSUE TITLE
使用 Python 的 Pandas 和 Seaborn 框架从 Kaggle 数据集中提取信息

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4657]
* 原文链接：[EXTRACTING INSIGHTS FROM A KAGGLE DATASET USING PYTHON’S PANDAS AND SEABORN](http://www.dataden.tech/data-science/extracting-insights-from-a-kaggle-dataset-using-pythons-pandas-and-seaborn/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/extracting-insights-from-a-kaggle-dataset-using-pythons-pandas-and-seaborn.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4687
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4687
