### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by JimmyLv** [xitu/gold-miner#466]
就职于 ThoughtWorks，长期服务于海外客户，日常全栈，专注前端。

目前产出翻译作品可以参看我的[博客](http://nobackend.website/_ng/#!/note/翻译)和 [GitBook](https://www.gitbook.com/@jimmylv)。

谢谢、

**Comment by antonia0912** [comment]
@JimmyLv 请加我微信 antonia0912 我拉你进译者群
