### ISSUE TITLE
在 Keras 中使用一维卷积神经网络处理时间序列数据

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4662]
* 原文链接：[Introduction to 1D Convolutional Neural Networks in Keras for Time Sequences](https://blog.goodaudience.com/introduction-to-1d-convolutional-neural-networks-in-keras-for-time-sequences-3a7ff801a2cf)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/introduction-to-1d-convolutional-neural-networks-in-keras-for-time-sequences.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4669
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
@haiyang-tju 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4669
