### ISSUE TITLE
理解 React 钩子（Hooks）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4666]
* 原文链接：[Making Sense of React Hooks](https://medium.com/@dan_abramov/making-sense-of-react-hooks-fdbde8803889)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/making-sense-of-react-hooks.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4688
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6.5-8 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by HaoChuan9421** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@HaoChuan9421 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4688
