### ISSUE TITLE
揭开 React Hooks 的神秘面纱:数组解构融成魔法

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4672]
* 原文链接：[React hooks: not magic, just arrays](https://medium.com/@ryardley/react-hooks-not-magic-just-arrays-cd4f1857236e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/react-hooks-not-magic-just-arrays.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4692
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Xekin-FE** [comment]
@leviding 认领翻译

**Comment by fanyijihua** [comment]
@Xekin-FE 棒极啦 :tada:
