### ISSUE TITLE
回答有关 Flutter App 开发的问题

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4678]
* 原文链接：[Answering Questions on Flutter App Development](https://medium.com/@dev.n/answering-questions-on-flutter-app-development-6d50eb7223f3)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/answering-questions-on-flutter-app-development.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4684
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@YueYongDev 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4684
