### ISSUE TITLE
用 Javascript 编写λ演算解释器

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#468]
原文链接：[A 𝝺-CALCULUS INTERPRETER](http://tadeuzagallo.com/blog/writing-a-lambda-calculus-interpreter-in-javascript/)
掘金链接：[用 Javascript 编写λ演算解释器](https://gold.xitu.io/entry/576ca64879bc44005be4b2cc)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/writing-a-lambda-calculus-interpreter-in-javascrip.md)

翻译时间：5天
校对时间：3天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by joddiy** [comment]
认领  ！

**Comment by antonia0912** [comment]
@joddiy 手好快~可以拿去翻译啦 感谢 @hikerpig 提供文章~积分+1~

**Comment by Zheaoli** [comment]
卧槽！卧槽！才10分钟啊！！我抢校对

**Comment by jamweak** [comment]
这个我熟，申请校对啊

**Comment by antonia0912** [comment]
@Zheaoli 这个就给新来的小伙伴嘛老司机 给他们个机会 你就别抢了哈~
@jamweak 好的

**Comment by Zheaoli** [comment]
@antonia0912  嘤嘤嘤嘤，好吧，忍痛割爱TAT
@jamweak 小子，你校对不好，我要砍人的啊（黑社会脸

**Comment by hikerpig** [comment]
哎呀呀这个我还想自己翻的来着，没想到狼这么多转眼肉就没了

**Comment by malcolmyu** [comment]
。。默默申个校

**Comment by joddiy** [comment]
sorry，这两天在搬家，还剩最后一点就翻译完了，明天提交：D

**Comment by joddiy** [comment]
翻译完成了，地址是：https://github.com/xitu/gold-miner/pull/482，我明天会先自己校对一遍。辛苦啦

**Comment by antonia0912** [comment]
@Zheaoli @jamweak [校对地址](https://github.com/xitu/gold-miner/pull/482/files?diff=split)  @malcolmyu 申请校对晚了  下次吧  乖~摸摸头~

**Comment by jamweak** [comment]
@antonia0912 校对完毕。

**Comment by antonia0912** [comment]
@jamweak 辛苦啦 @Zheaoli 也快来校对吧 就等你了

**Comment by Zheaoli** [comment]
@antonia0912 二校一次OK，
@joddiy 作者修改后，可以艾特我进行二次二校
