### ISSUE TITLE
 🏷 译者互粉时间，掘金 Web 端动态功能上线，个人广告福利时间

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4680]
掘金 Web 端动态功能上线，为了给大家营造更好的交流环境，开此 issue 让大家发自己掘金个人主页链接，互相关注。

> 广告时间，发个人主页链接（每人仅限一条），吸引其他译者关注（文案自定），关注 10 位译者和 20 位译者以上，自行截图兑礼物的时候发给我，尽量满足想要的文案。
>
> 关注 10 名译者以上加送 2 枚胸章，关注 20 位以上加送 5 枚胸章，关注越多送的越多，还可升级为其他礼物 🤣 快来嗨皮吧

- 掘金 Web 端动态功能体验：https://juejin.im/activities
- 翻译计划掘金主页：https://juejin.im/user/5bdc10f36fb9a049e062c2d5

> **个人主页获取方法：** 进入[掘金主页](https://juejin.im/timeline)，点击右上角个人头像，然后点击我的主页，链接栏的链接就是你的个人主页链接啦 👏

**Comment by CoolRice** [comment]
2 枚什么？

**Comment by leviding** [comment]
🚀 一楼翻译计划官方掘金账号，翻译计划的动态都在这里咯 https://juejin.im/user/5bdc10f36fb9a049e062c2d5

**Comment by leviding** [comment]
二楼三代目，都是你想看的，你关注了吗 😆 https://juejin.im/user/589881b7128fe1006cbbacec

**Comment by leviding** [comment]
@CoolRice 胸章，补上啦 😄

**Comment by GpingFeng** [comment]
对知识永远保持敬畏之心
学习技术，重在踏踏实实
https://juejin.im/user/583d0ba2a22b9d006c1b4f2a

**Comment by elliott-zhao** [comment]
https://juejin.im/user/5b062f9cf265da0dcc69b542

**Comment by pmwangyang** [comment]
https://juejin.im/user/5924e20344d904006ced9cc8

**Comment by ryouaki** [comment]
I am ryouaki
https://juejin.im/user/5881e022128fe100682735aa

**Comment by tian-li** [comment]
https://juejin.im/user/5a556a2df265da3e566168bf  交流互粉 🤣

**Comment by Glowin** [comment]
https://juejin.im/user/551ca9d6e4b0cd5b6237420e

介绍：掘金翻译计划创建者和第一个管理员😎

**Comment by Ivocin** [comment]
希望在掘金一起成长，交到志同道合的好朋友
https://juejin.im/user/58855de9128fe100683a3339

**Comment by fghpdf** [comment]
https://juejin.im/user/573e6cb171cfe448aa9c4a30

**Comment by crossoverJie** [comment]
https://juejin.im/user/576d4aaf7db2a20054ea4544

互粉互粉

**Comment by caoxiaoshuai1** [comment]
和掘金一起成长
https://juejin.im/user/5809d093d203090065770569

**Comment by FaiChou** [comment]
https://juejin.im/user/5abaf4e3f265da237506ef9a

三代目 我来啦~

**Comment by tmpbook** [comment]
拼多多内推找我 😝
https://juejin.im/user/599ba8856fb9a02473218902

**Comment by iOSleep** [comment]
三代目，我的掘金币(=@__@=)在哪里？
https://juejin.im/user/58d37be52f301e007e6ad451

**Comment by coconilu** [comment]
全栈工程师，谢谢
https://juejin.im/user/5ab38356518825558b3dd86e

**Comment by rydensun** [comment]
我，山东省第一伽罗，关注不亏。 互粉互粉。  翻译之余，之后会分享一些关于产品的看法还有有意思的东西。
https://juejin.im/user/585b9407da2f6000657a5c0c

**Comment by yikejiucai** [comment]
掘金社区有任何问题都可以来找我~
https://juejin.im/user/555426a7e4b076f1c3243993

**Comment by Gavin-Gong** [comment]
有粉必回 （捂脸）
https://juejin.im/user/574e66ae71cfe4006b0059be

**Comment by Glowin** [comment]
> 我，山东省第一伽罗，关注不亏。 互粉互粉。 翻译之余，之后会分享一些关于产品的看法还有有意思的东西。
> https://juejin.im/user/585b9407da2f6000657a5c0c

**Comment by RickeyBoy** [comment]
iOS 的小伙伴看过来呀
https://juejin.im/user/59c0ede76fb9a00a3d134e0b/posts

**Comment by zx-Zhu** [comment]
Android 正义小伙伴 永远跟党走 迈向新辉煌
https://juejin.im/user/59182ff52f301e006baa842c/activities

**Comment by jingzhilehuakai** [comment]
https://juejin.im/user/599b8dbbf265da246e6df4c8/
iOS 开发 O(∩_∩)O

**Comment by CoderMing** [comment]
前端🐶求互粉～
https://juejin.im/user/594b5215570c3500569100fe

**Comment by 4ngler** [comment]
php牛逼，一起牛逼啊
https://juejin.im/user/5b912d7d6fb9a05cd31e95d9

**Comment by Augustwuli** [comment]
前端小发小发
https://juejin.im/user/5aefd36cf265da0b981b5e61

**Comment by calpa** [comment]
一位爱写文章的江南前端工程师
https://juejin.im/user/57ce3e8d8ac247005fbb51e2

**Comment by iWeslie** [comment]
iOS developer, thx
[https://juejin.im/user/5bc836776fb9a05d1478541e](url)

**Comment by Pomelo1213** [comment]
我是一个骗关注的无耻之徒 XD
https://juejin.im/user/5a4368866fb9a044fb080a28

**Comment by noahziheng** [comment]
说点什么？布吉岛哇～～～
https://juejin.im/user/583bdbf1a22b9d006c1514f8
