### ISSUE TITLE
校对认领

### ISSUE THREAD

**Issue by jiayuewang** [xitu/gold-miner#4689]
Making Sense of React Hooks

**Comment by leviding** [comment]
@jiayuewang 认领校对是去对应 PR 下认领，详见教程 https://github.com/xitu/gold-miner/wiki/%E5%8F%82%E4%B8%8E%E6%A0%A1%E5%AF%B9%E7%9A%84%E6%AD%A3%E7%A1%AE%E5%A7%BF%E5%8A%BF
