### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by llp0574** [xitu/gold-miner#469]
工作近两年，从事前端开发三年有余，长期使用Google搜索前端方面的技术解决方案，无障碍阅读理解国外技术好文，并常年潜水github及stackoverflow等技术社区搜罗各种干货学习。

**Comment by antonia0912** [comment]
@llp0574  欢迎参加掘金翻译计划 请加我微信 antonia0912 备注github ID 我拉你进译者群哈`
