### ISSUE TITLE
推荐 JavaScript 文章

### ISSUE THREAD

**Issue by calpa** [xitu/gold-miner#4691]
文章：Javascript: call(), apply() and bind()
链接：https://medium.com/@omergoldberg/javascript-call-apply-and-bind-e5c27301f7bb

**Comment by leviding** [comment]
https://hijiangtao.github.io/2017/05/07/Full-Usage-of-Apply-Call-and-Bind-in-JavaScript/

翻译过啦

**Comment by leviding** [comment]
感谢您的推荐，已发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
