### ISSUE TITLE
我们是怎样把 Carousell 的移动 Web 体验搞快了 3 倍的？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4696]
* 原文链接：[How we made Carousell’s mobile web experience 3x faster](https://medium.com/carousell-insider/how-we-made-carousells-mobile-web-experience-3x-faster-bbb3be93e006)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-we-made-carousells-mobile-web-experience-3x-faster.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4707
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by noahziheng** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@noahziheng 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4707
