### ISSUE TITLE
Javascript: call(), apply() and bind()

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4697]
* 原文链接：[Javascript: call(), apply() and bind()](https://medium.com/@omergoldberg/javascript-call-apply-and-bind-e5c27301f7bb)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/javascript-call-apply-and-bind.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4706
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@YueYongDev 棒极啦 :tada:
