### ISSUE TITLE
在 Android 上实现 Google Inbox 的样式动画

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4698]
* 原文链接：[Implement Google Inbox Style Animation on Android](https://proandroiddev.com/implement-google-inbox-style-animation-on-android-18c261baeda6)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/implement-google-inbox-style-animation-on-android.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4705
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5.5-6.6 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@YueYongDev 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4705
