### ISSUE TITLE
用 Mockito 进行单元测试

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#470]
原文链接：[Unit tests with Mockito - Tutorial](http://www.vogella.com/tutorials/Mockito/article.html)
掘金链接：[用 Mockito 进行单元测试](https://gold.xitu.io/entry/577240d70a2b58006a2fb583)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/Unit-tests-with-Mockito.md)
[校对地址](https://github.com/xitu/gold-miner/pull/515/files?diff=split)
翻译时间：5天
校对时间：3天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by edvardHua** [comment]
抢沙发

**Comment by antonia0912** [comment]
@edvardHua ok

**Comment by hackerkevin** [comment]
抢

**Comment by antonia0912** [comment]
@hackerkevin 好的 校对地址见issue描述 注意校对时间限制哈~

**Comment by futureshine** [comment]
还需要校对的吗

**Comment by antonia0912** [comment]
@futureshine 好的 校对地址见issue描述 注意校对时间限制哈~

**Comment by tanglie1993** [comment]
认领校对

**Comment by futureshine** [comment]
完成校对了，请看一下@edvardHua

**Comment by edvardHua** [comment]
好的。辛苦了 @futureshine

**Comment by edvardHua** [comment]
@hackerkevin 请问校对完了吗？

**Comment by edvardHua** [comment]
@sqrthree @antonia0912 修改完啦。
