### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by tian-li** [xitu/gold-miner#4700]
* 原文链接： https://blog.angularindepth.com/everything-you-need-to-know-about-change-detection-in-angular-8006c51d206f
* 简要介绍： 详解 Angular 4.0+ 的 change detection 机制

**Comment by leviding** [comment]
@tian-li 这篇你在翻译了吗？

- https://www.jianshu.com/p/7fa799d735c2
- https://juejin.im/post/5b1a9e12e51d4506bf730159
- https://hk.saowen.com/a/69a21a918ce9fc8f60b4bd1a5d1c5a90f2ec626713fb374e6f4146e2083a2f64

这些地方都有译文

**Comment by tian-li** [comment]
好吧，我没去搜是不是已经有译文了，这周末我已经翻好了。如果不适合发布的话，就算了
