### ISSUE TITLE
Understanding JavaScript’s ‘undefined’

### ISSUE THREAD

**Issue by Marszht** [xitu/gold-miner#4704]
- 原文链接：[Understanding JavaScript’s ‘undefined’](https://javascriptweblog.wordpress.com/2010/08/16/understanding-undefined-and-preventing-referenceerrors/)
- 简要介绍：介绍 JavaScript  'undefined'和 null 的区别.

**Comment by leviding** [comment]
感谢您的推荐，已发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
