### ISSUE TITLE
理解 JavaScript 中的 undefined

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4708]
* 原文链接：[Understanding JavaScript’s ‘undefined’](https://javascriptweblog.wordpress.com/2010/08/16/understanding-undefined-and-preventing-referenceerrors/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/understanding-undefined-and-preventing-referenceerrors.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4735
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yanyixin** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@yanyixin 棒极啦 :tada:
