### ISSUE TITLE
使用 NodeJS 创建一个 GraphQL 服务器

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4709]
* 原文链接：[Creating a GraphQL server with NodeJS](https://medium.com/crowdbotics/creating-a-graphql-server-with-nodejs-ef9814a7e0e6)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/creating-a-graphql-server-with-nodejs.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4770
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：5.5-6.5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Raoul1996** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Raoul1996 棒极啦 :tada:

**Comment by Raoul1996** [comment]
文章难度较大。再需要一点时间

**Comment by leviding** [comment]
好滴

**Comment by leviding** [comment]
这篇记得哈

**Comment by fanyijihua** [comment]
PR 地址：#4770
