### ISSUE TITLE
用户界面中的排版

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#471]
原文链接：[Typography for User Interfaces](https://viljamis.com/2016/typography-for-user-interfaces/)
掘金链接：[用户界面中的排版](https://gold.xitu.io/entry/57709cce0a2b58006a215f90)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/typography-for-user-interfaces.md)

翻译时间：5天
校对时间：3天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by antonia0912** [comment]
@Ruixi 谢谢睿奚提供文章~么么扎~

**Comment by circlelove** [comment]
还，能抢么(*/ω＼*)

**Comment by circlelove** [comment]
还，能抢么(*/ω＼*)

**Comment by antonia0912** [comment]
@circlelove ok 这次不能拖那么久啦 否则就拉黑名单 哼 （傲娇脸）

**Comment by circlelove** [comment]
@antonia0912  好的。然后我上一篇脱稿的是没人校对了吗？

**Comment by antonia0912** [comment]
@circlelove 已经催了  太久了 都忘记自己申请了校对了

**Comment by Ruixi** [comment]
我又没有抢到翻译［大哭
求校对

**Comment by antonia0912** [comment]
@circlelove 该交PR了喔 （doggie脸）

**Comment by circlelove** [comment]
昂，我知道了 @antonia0912

**Comment by circlelove** [comment]
@Ruixi  假如生活欺骗了你，别哭泣，别犹豫。拿出钱，让他再骗一次——————————你就长记性了～～

**Comment by wild-flame** [comment]
消息提示里看到一首诗就进来了 ：D

校对占坑 +1

**Comment by circlelove** [comment]
@antonia0912

**Comment by antonia0912** [comment]
@Ruixi @wild-flame [校对地址](https://github.com/xitu/gold-miner/pull/484/files?diff=split)

**Comment by Ruixi** [comment]
来啦来啦～

**Comment by Ruixi** [comment]
校对了两段，但是这篇不是我分享的那篇文章……

**Comment by antonia0912** [comment]
@Ruixi 你分享的那篇已经分享到掘金啦睿奚  这篇你看看issue上你的留言哈哈哈

**Comment by antonia0912** [comment]
@Ruixi [新的校对地址](https://github.com/xitu/gold-miner/pull/504/files?diff=split)

**Comment by wild-flame** [comment]
那我原来的校对的 comment 可以保留么…… 花了好多时间校对。

**Comment by antonia0912** [comment]
@circlelove 校对者@wild-flame 校对完了你已经改过了吗

**Comment by circlelove** [comment]
@wild-flame 我复制到我电脑里了，不用重新校了/   @antonia0912 还没有。

**Comment by Ruixi** [comment]
校对完了

**Comment by antonia0912** [comment]
@Ruixi 辛苦啦honey

**Comment by Ruixi** [comment]
@antonia0912 么么哒～
