### ISSUE TITLE
介绍适用于 iOS 的 AloeStackView

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4711]
* 原文链接：[Introducing AloeStackView for iOS](https://medium.com/airbnb-engineering/introducing-aloestackview-for-ios-a676d253c6ba)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/introducing-aloestackview-for-ios.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4719
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LoneyIsError** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@LoneyIsError 棒极啦 :tada:
