### ISSUE TITLE
为用户提供安全可靠的体验

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4712]
* 原文链接：[Providing a safe and secure experience for our users](https://android-developers.googleblog.com/2018/10/providing-safe-and-secure-experience.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/providing-safe-and-secure-experience.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4734
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-2.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@YueYongDev 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4734
