### ISSUE TITLE
Android 内核控制流完整性

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4713]
* 原文链接：[Control Flow Integrity in the Android kernel](https://android-developers.googleblog.com/2018/10/control-flow-integrity-in-android-kernel.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/control-flow-integrity-in-android-kernel.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4850
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nanjingboy** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@nanjingboy 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4850
