### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by wangYaNan112618** [xitu/gold-miner#4714]
- 公司/学校：帮实资本/嘉兴学院
- 工作内容/专业：前端开发工程师/信息与计算科学
- 常浏览的国外网站：
- 英语水平：CET6
- 翻译经验：
- 主要翻译方向：前端
- 个人博客：
- 个人介绍：

**Comment by leviding** [comment]
@wangYaNan112618 请详细填写信息
