### ISSUE TITLE
关于 Angular 的变化检测，你需要知道的一切

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4715]
* 原文链接：[Everything you need to know about change detection in Angular](https://blog.angularindepth.com/everything-you-need-to-know-about-change-detection-in-angular-8006c51d206f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/everything-you-need-to-know-about-change-detection-in-angular.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4718
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@tian-li 来认领吧

**Comment by nanjingboy** [comment]
@leviding 认领校对
