### ISSUE TITLE
快速原型设计的新手指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4716]
* 原文链接：[A Beginner’s Guide to Rapid Prototyping](https://medium.freecodecamp.org/a-beginners-guide-to-rapid-prototyping-71e8722c17df)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-beginners-guide-to-rapid-prototyping.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4883
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rydensun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@rydensun 棒极啦 :tada:

**Comment by leviding** [comment]
@rydensun 这篇文章翻译的怎么样啦
