### ISSUE TITLE
不局限于 console.log()

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4717]
* 原文链接：[Beyond console.log()](https://medium.com/@mattburgess/beyond-console-log-2400fdf4a9d8)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/beyond-console-log.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4741
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：5.5-6.5 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
本文需要译者根据无文章内容拟出一个更能代表本文内容的文章标题

**Comment by Pomelo1213** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Pomelo1213 棒极啦 :tada:
