### ISSUE TITLE
WWDC 2016：更加安全的 Swift 3.0

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#472]
原文链接：[WWDC 2016: Increased Safety in Swift 3.0](https://www.bignerdranch.com/blog/wwdc-2016-increased-safety-in-swift-3/)
掘金链接：[WWDC 2016：更加安全的 Swift 3.0](https://gold.xitu.io/entry/57721aae165abd00548ea9b5)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/wwdc-2016-increased-safety-in-swift-3.md)

翻译时间：5天
校对时间：3天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zheaoli** [comment]
翻译，翻译！！！！

**Comment by Zheaoli** [comment]
咩，羊姐姐，这篇文章我想抢了0.0

**Comment by antonia0912** [comment]
@Zheaoli ok

**Comment by thanksdanny** [comment]
等了一天都没人来占..我来占个校对ok么~

**Comment by llp0574** [comment]
新人校对认领

**Comment by Zheaoli** [comment]
@antonia0912 
@thanksdanny @llp0574 羊姐姐，两位校者，第一次初稿我已经PR上去 [校对地址](https://github.com/xitu/gold-miner/pull/510/files)，这篇文章有很多地方我拿捏不准，可能不严谨的地方有点多，可能需要二校完后，我和两位校者讨论后进行三校，麻烦啦TAT

**Comment by antonia0912** [comment]
@Zheaoli 好的  辛苦啦思密达

**Comment by thanksdanny** [comment]
@antonia0912 get

**Comment by llp0574** [comment]
@antonia0912 来了

**Comment by Zheaoli** [comment]
@antonia0912 羊姐姐
@thanksdanny @llp0574 两位大胸弟，二校初稿已经搞定，可以进行最后一次审核了

**Comment by Zheaoli** [comment]
@antonia0912 唔，羊姐姐，您看看可以了么，唔，您这么细心，简直想把您娶回家嘞

**Comment by Zheaoli** [comment]
@sqrthree 大胸弟，帮忙看看可以Merge了么
