### ISSUE TITLE
如何让高效的代码评审成为一种文化

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4726]
* 原文链接：[Effective code review](https://engineering.linecorp.com/en/blog/detail/378/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/effective-code-review.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4761
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
本文标题需要译者根据文章内容进行扩充

**Comment by CoolRice** [comment]
翻译认领

**Comment by leviding** [comment]
@CoolRice 🆗

**Comment by fanyijihua** [comment]
PR 地址：#4761
