### ISSUE TITLE
iOS 12 占有率超过 50%，超过了 iOS 11

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4727]
* 原文链接：[iOS 12 now installed on 50% of active devices, outpacing iOS 11 adoption](https://9to5mac.com/2018/10/06/ios-12-now-installed-on-50-of-devices-outpacing-ios-11)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/ios-12-now-installed-on-50-of-devices-outpacing-ios-11.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4730
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LoneyIsError** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@LoneyIsError 棒极啦 :tada:
