### ISSUE TITLE
函数式编程：抽象与组合

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4728]
* 原文链接：[Abstraction & Composition](https://medium.com/javascript-scene/abstraction-composition-cb2849d5bdd6)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/abstraction-composition.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4748
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Xekin-FE** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Xekin-FE 棒极啦 :tada:
