### ISSUE TITLE
以太坊: 能帮我们把 Uber 换掉的非比特币加密货币

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4729]
* 原文链接：[Ethereum: The not-Bitcoin cryptocurrency that could help replace Uber](https://mashable.com/2017/03/24/ethereum-bitcoin-explainer/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/ethereum-bitcoin-explainer.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4733
  * 文章分类：**区块链**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@mingxing47 这篇感兴趣吗

**Comment by noahziheng** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@noahziheng 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4733
