### ISSUE TITLE
申请成为掘金翻译计划译者

### ISSUE THREAD

**Issue by rccoder** [xitu/gold-miner#473]
**常用昵称：** rccoder
**英语水平：** 可借助相关工具正常阅读技术文章，文档
**职业：**在校学生
**翻译过的文章：**

[在 pre-commit 的钩子中运行 npm script](https://github.com/rccoder/blog/issues/9)
[rfc7540第9节](https://github.com/abbshr/rfc7540-translation-zh_cn/blob/master/9-zh-cn.md)
......

**Comment by antonia0912** [comment]
@rccoder 请加我微信 antonia0912 备注github ID 我来拉你进译者群
