### ISSUE TITLE
Adopting Kotlin: Incorporating Kotlin in your large app

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4737]
* 原文链接：[Adopting Kotlin: Incorporating Kotlin in your large app](https://medium.com/androiddevelopers/adopting-kotlin-50c0df79b879)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/adopting-kotlin.md)
  * PR 地址：
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6-7 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zx-Zhu** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@zx-Zhu 棒极啦 :tada:
