### ISSUE TITLE
受保护的路由和使用 React 和 Node.js 进行身份验证

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4738]
* 原文链接：[Protected routes and Authentication with React and Node.js](https://blog.strapi.io/protected-routes-and-authentication-with-react-and-node-js/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/protected-routes-and-authentication-with-react-and-node-js.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4880
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@jiayuewang 认领吧

**Comment by jiayuewang** [comment]
玥儿来翻译认领~

**Comment by fanyijihua** [comment]
@jiayuewang 棒极啦 :tada:

**Comment by leviding** [comment]
@jiayuewang 翻译的怎么样啦，超期很久了

**Comment by leviding** [comment]
由 @ElizurHz 翻译

**Comment by leviding** [comment]
@ElizurHz 这篇整理的怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#4880
