### ISSUE TITLE
被遗忘的面向对象编程史（软件编写）（第十六部分）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4739]
* 原文链接：[The Forgotten History of OOP](https://medium.com/javascript-scene/the-forgotten-history-of-oop-88d71b9b2d9f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-forgotten-history-of-oop.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4821
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：7.5-8.5 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by geniusq1981** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@geniusq1981 棒极啦 :tada:

**Comment by angelasnowing** [comment]
@leviding 校对认领

**Comment by leviding** [comment]
本文还没翻译完，麻烦 @geniusq1981 翻译好后，在 PR 下艾特一下 @angelasnowing

**Comment by fanyijihua** [comment]
PR 地址：#4821

**Comment by geniusq1981** [comment]
@angelasnowing 已经翻译完了，可以校对了

**Comment by angelasnowing** [comment]
好的

> @angelasnowing 已经翻译完了，可以校对了

好的

**Comment by leviding** [comment]
@angelasnowing 在对应 PR 下校对认领一下哈

**Comment by angelasnowing** [comment]
> @angelasnowing 在对应 PR 下校对认领一下哈

好的
