### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Devilots** [xitu/gold-miner#474]
我叫三水，交互设计师，经常阅读设计类文章，下面是我翻译的一篇文章
[【译文】让设计师小伙伴含泪点头的8个经验教训](https://medium.com/@jiangmiaocn/%E8%AF%91%E6%96%87-%E4%BD%9C%E4%B8%BA%E8%AE%BE%E8%AE%A1%E5%B8%88%E7%9A%84%E4%B8%80%E4%BA%9B%E7%BB%8F%E9%AA%8C%E6%95%99%E8%AE%AD-fc9f8a8269c#.hj355s1pa)

**Comment by antonia0912** [comment]
@Devilots 请加我微信 antonia0912 备注github ID 我来拉你进译者群

**Comment by Devilots** [comment]
已加
