### ISSUE TITLE
构建软件：简介

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4740]
* 原文链接：[Composing Software: An Introduction](https://medium.com/javascript-scene/composing-software-an-introduction-27b72500d6ea)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/composing-software-an-introduction.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4795
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7.5-8.5 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4795
