### ISSUE TITLE
如何使用 Dask Dataframes 在 Python 中运行并行数据分析

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4742]
* 原文链接：[How to Run Parallel Data Analysis in Python using Dask Dataframes](https://towardsdatascience.com/trying-out-dask-dataframes-in-python-for-fast-data-analysis-in-parallel-aa960c18a915)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/trying-out-dask-dataframes-in-python-for-fast-data-analysis-in-parallel.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4840
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by snpmyn** [comment]
校对认领

**Comment by leviding** [comment]
@snpmyn 在对应 PR 下认领
