### ISSUE TITLE
Swift 中的动态特性

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4743]
* 原文链接：[Dynamic Features in Swift](https://www.raywenderlich.com/5743-dynamic-features-in-swift)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/dynamic-features-in-swift.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4763
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-9 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iWeslie** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@iWeslie 棒极啦 :tada:

**Comment by LoneyIsError** [comment]
校对认领
