### ISSUE TITLE
Kotlin 协程高级使用技巧

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4744]
* 原文链接：[Advanced Kotlin Coroutines tips and tricks](https://proandroiddev.com/coroutines-snags-6bf6fb53a3d1)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/coroutines-snags.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4802
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nanjingboy** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@nanjingboy 棒极啦 :tada:
