### ISSUE TITLE
推荐优秀 GraphQL 文章

### ISSUE THREAD

**Issue by calpa** [xitu/gold-miner#4745]
文章原标题：GraphQL Server Design @ Medium
文章标题：细看 Meidum 的 GraphQL 服务端架构
文章地址：https://medium.engineering/graphql-server-design-medium-34862677b4b8

**Comment by leviding** [comment]
感谢您的推荐，已发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
