### ISSUE TITLE
 Medium 的 GraphQL 服务设计

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4754]
* 原文链接：[GraphQL Server Design @ Medium](https://medium.engineering/graphql-server-design-medium-34862677b4b8)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/graphql-server-design-medium.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4768
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4768
