### ISSUE TITLE
关于 HTTP/3 的一些心得

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4755]
* 原文链接：[Some notes about HTTP/3](https://blog.erratasec.com/2018/11/some-notes-about-http3.html?m=1)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/some-notes-about-http3.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4762
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4762
