### ISSUE TITLE
同时使用多个相机流

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4756]
* 原文链接：[Using multiple camera streams simultaneously](https://medium.com/androiddevelopers/using-multiple-camera-streams-simultaneously-bf9488a29482)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/using-multiple-camera-streams-simultaneously.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4828
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zx-Zhu** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@zx-Zhu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4828
