### ISSUE TITLE
通过集成学习提高机器学习效果

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4757]
* 原文链接：[Ensemble Learning to Improve Machine Learning Results](https://blog.statsbot.co/ensemble-learning-d1dcd548e936)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/ensemble-learning-to-improve-machine-learning-results.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4789
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4789
