### ISSUE TITLE
Introduction to Ethereum: The Internet’s Government

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4758]
* 原文链接：[Introduction to Ethereum: The Internet’s Government](https://media.consensys.net/introduction-to-ethereum-the-internets-government-35bdd25f572a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/introduction-to-ethereum-the-internets-government.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4790
  * 文章分类：**区块链**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by newraina** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@newraina 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4790
