### ISSUE TITLE
支持向量机（SVM） 教程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4764]
* 原文链接：[Support Vector Machine (SVM) Tutorial](https://blog.statsbot.co/support-vector-machines-tutorial-c1618e635e93)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/support-vector-machines-tutorial.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4807
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：8-11 分
  * 校对积分：2-6 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhmhhu** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@zhmhhu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4807
