### ISSUE TITLE
使用 Swift 的 iOS 设计模式（第一部分）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4765]
* 原文链接：[Design Patterns on iOS using Swift – Part 1/2](https://www.raywenderlich.com/477-design-patterns-on-ios-using-swift-part-1-2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/design-patterns-on-ios-using-swift-part-1-2.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4771
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：9-11 分
  * 校对积分：2-6 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iWeslie** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@iWeslie 棒极啦 :tada:

**Comment by LoneyIsError** [comment]
校对认领
