### ISSUE TITLE
使用 Kotlin 将你的 iOS 应用程序转换为 Android

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4766]
* 原文链接：[Converting your iOS App to Android Using Kotlin](https://www.raywenderlich.com/7266-converting-your-ios-app-to-android-using-kotlin?utm_source=mobiledevweekly&utm_medium=email)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/converting-your-ios-app-to-android-using-kotlin.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4779
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iWeslie** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@iWeslie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4779
