### ISSUE TITLE
写给 React 开发者的自定义元素指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4767]
* 原文链接：[A Guide to Custom Elements for React Developers](https://css-tricks.com/a-guide-to-custom-elements-for-react-developers/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-guide-to-custom-elements-for-react-developers.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4783
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4783
