### ISSUE TITLE
让你的网站更炫酷的一些小 tips

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#477]
原文链接：[101 Ways to Make Your Website More Awesome](https://medium.freecodecamp.com/101-ways-to-make-your-website-more-awesome-79c934dd2a11)
掘金链接：[让你的网站更炫酷的一些小 tips](https://gold.xitu.io/entry/57737598c4c9710055357c2c)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/101-ways-to-make-your-website-more-awesome.md)

翻译时间：9天
校对时间：8天
翻译积分：10
校对积分：3
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zhangjd** [comment]
认领

**Comment by antonia0912** [comment]
@Zhangjd 好的达仔  我会想你们的

**Comment by Zhangjd** [comment]
羊，这篇翻译送给你，同是毕业生，很理解你的想法，祝好运～

**Comment by cyseria** [comment]
新人来占坑校对嗷嗷嗷

**Comment by jamweak** [comment]
申请校对

**Comment by antonia0912** [comment]
@cyseria @jamweak [校对地址](https://github.com/xitu/gold-miner/pull/492/files?diff=split)

**Comment by jamweak** [comment]
@antonia0912 校对完毕
