### ISSUE TITLE
鲜为人知的数据科学 Python 库

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4772]
* 原文链接：[Lesser Known Python Libraries for Data Science](https://medium.com/analytics-vidhya/python-libraries-for-data-science-other-than-pandas-and-numpy-95da30568fad)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/python-libraries-for-data-science-other-than-pandas-and-numpy.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4793
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by haiyang-tju** [comment]
翻译认领 @leviding @fanyijihua

**Comment by fanyijihua** [comment]
@haiyang-tju 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4793
