### ISSUE TITLE
推荐优秀文章

### ISSUE THREAD

**Issue by calpa** [xitu/gold-miner#4773]
文章名称：如何发布一个优雅，小而精的 npm 包
文章链接：https://medium.freecodecamp.org/how-to-make-a-beautiful-tiny-npm-package-and-publish-it-2881d4307f78

其实我想翻译这篇文章，不过还是先放链接出来吧。

**Comment by leviding** [comment]
@calpa 这篇你认领吗？

**Comment by calpa** [comment]
@leviding 认领文章

**Comment by leviding** [comment]
感谢您的推荐，已发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
