### ISSUE TITLE
创建并发布一个小而美的 npm 包

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4776]
* 原文链接：[How to make a beautiful, tiny npm package and publish it](https://medium.freecodecamp.org/how-to-make-a-beautiful-tiny-npm-package-and-publish-it-2881d4307f78)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-make-a-beautiful-tiny-npm-package-and-publish-it.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4887
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@calpa 认领吧

**Comment by calpa** [comment]
@leviding 认领文章

**Comment by leviding** [comment]
@calpa 好的！

**Comment by snowyYU** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@snowyYU 棒极啦 :tada:

**Comment by leviding** [comment]
@snowyYU 这篇文章翻译的怎么样啦

**Comment by snowyYU** [comment]
@leviding 不好意思耽误了下，明天翻好哈
