### ISSUE TITLE
怎么做：React Native 网页应用，一场开心的挣扎 

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4781]
* 原文链接：[How to: React Native Web app. A Happy Struggle.](https://blog.bitsrc.io/how-to-react-native-web-app-a-happy-struggle-aea7906f4903)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-react-native-web-app-a-happy-struggle.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4832
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5.5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by weibinzhu** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@weibinzhu 棒极啦 :tada:

**Comment by leviding** [comment]
@weibinzhu 这篇翻译的怎么样啦

**Comment by weibinzhu** [comment]
不好意思，拖进度了。尽量周六前完成

**Comment by leviding** [comment]
@weibinzhu 好的，按你进度来

**Comment by fanyijihua** [comment]
PR 地址：#4832

**Comment by nanjingboy** [comment]
@leviding 校对认领
