### ISSUE TITLE
Inside Fiber: in-depth overview of the new reconciliation algorithm in React

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4787]
* 原文链接：[Inside Fiber: in-depth overview of the new reconciliation algorithm in React](https://medium.com/react-in-depth/inside-fiber-in-depth-overview-of-the-new-reconciliation-algorithm-in-react-e1c04700ef6e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/inside-fiber-in-depth-overview-of-the-new-reconciliation-algorithm-in-react.md)
  * PR 地址：
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：9-11 分
  * 校对积分：2-5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
由 @CoolRice 翻译

**Comment by CoolRice** [comment]
翻译认领 感谢！

**Comment by fanyijihua** [comment]
@CoolRice 棒极啦 :tada:

**Comment by int64ago** [comment]
我们团队已经翻译：


掘金：https://juejin.im/post/5c052f95e51d4523d51c8300

SegmentFault：https://segmentfault.com/a/1190000017241034

语雀：https://www.yuque.com/es2049/blog/nbp4xc

知乎：https://zhuanlan.zhihu.com/p/51483167

**Comment by leviding** [comment]
@int64ago get, @CoolRice 这篇翻译的怎么样了，翻译好了就继续，没翻译好就不翻译了

**Comment by int64ago** [comment]
> @int64ago get, @CoolRice 这篇翻译的怎么样了，翻译好了就继续，没翻译好就不翻译了

不好意思哈，我们翻译之前搜了下，发现网上没有。翻译好，又搜了下，发现你们在翻译了……

**Comment by CoolRice** [comment]
@int64ago , @leviding  我还没翻译完，那我这边终止吧

**Comment by leviding** [comment]
@CoolRice 如果已经翻译了一部分，可以把这部分发出来，然后说下 @int64ago 团队已翻译好全文，把掘金链接附上就行。

**Comment by CoolRice** [comment]
@leviding , 算啦，目前翻译的不多，也没经过校对😊，对读者来说不太好。

不过我希望以后能有措施可以避免这种情况发生。

**Comment by int64ago** [comment]
我个人倒是有个建议，就是缩短翻译校审周期，我这边都是要求团队翻译的话，从接到到翻译好尽量保持在三天内。

时间长短也可以作为你们积分发放的参考项。

**Comment by leviding** [comment]
翻译认领前是经过认真搜索的，保证没有已存在的译文。有时可能已经存在译文，但是质量很差，但是文章很好，我们也会重新翻译。

本文的情况是，发布翻译认领前没有现存译文，文章翻译是存在翻译期的，从翻译认领到文章出炉是需要时间的，在这个时间段内，别人产出译文是无法控制的 @CoolRice 。

感谢 @int64ago 的建议，现在是在考虑不想给译者太大压力，那确实可以采用您的建议对译者进行奖励。

感谢支持 ❤️
