### ISSUE TITLE
Google Colab 免费 GPU 使用教程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4788]
* 原文链接：[Google Colab Free GPU Tutorial](https://medium.com/deep-learning-turkey/google-colab-free-gpu-tutorial-e113627b9f5d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/google-colab-free-gpu-tutorial.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4794
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by haiyang-tju** [comment]
翻译认领 @leviding @fanyijihua

**Comment by fanyijihua** [comment]
@haiyang-tju 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4794
