### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Chunk49** [xitu/gold-miner#4791]
- 公司/学校：Amazon
- 工作内容/专业：Java / Web
- 常浏览的国外网站：Stackoverflow
- 英语水平：CET6
- 翻译经验：First Time
- 主要翻译方向：Backend / Mobile Client
- 个人博客：Not now
- 个人介绍：正式从业3年主要从事Java Service / Web工作。有多年Mobile Client研发经验。刚刚开始开源活动，很有热情。

**Comment by Ivocin** [comment]
@leviding  是的
