### ISSUE TITLE
用 Shadow DOM v1 和 Custom Elements v1 实现一个原生 Web Component

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4796]
* 原文链接：[Make a Native Web Component with Custom Elements v1 and Shadow DOM v1](https://bendyworks.com/blog/native-web-components)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/native-web-components.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4826
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-9 分
  * 校对积分：1.5-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by newraina** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@newraina 棒极啦 :tada:

**Comment by leviding** [comment]
辛苦了，今天下午更新积分，请注意查收
