### ISSUE TITLE
了解 Android 的矢量图片格式：`VectorDrawable`

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4797]
* 原文链接：[Understanding Android’s vector image format: VectorDrawable](https://medium.com/androiddevelopers/understanding-androids-vector-image-format-vectordrawable-ab09e41d5c68)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/understanding-androids-vector-image-format-vectordrawable.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4831
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by HarderChen** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@HarderChen 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4831

**Comment by fanyijihua** [comment]
PR 地址：#4833
