### ISSUE TITLE
被污染的 npm 包：event-stream

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4798]
* 原文链接：[Compromised npm Package: event-stream](https://medium.com/intrinsic/compromised-npm-package-event-stream-d47d08605502)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/compromised-npm-package-event-stream.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4851
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4851
