### ISSUE TITLE
使用 Swift 的 iOS 设计模式（第二部分）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4799]
* 原文链接：[Design Patterns on iOS using Swift – Part 2/2](https://www.raywenderlich.com/476-design-patterns-on-ios-using-swift-part-2-2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/design-patterns-on-ios-using-swift-part-2-2.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4829
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：2 天
  * 翻译积分：9-11 分
  * 校对积分：2-5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@iWeslie

**Comment by iWeslie** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@iWeslie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4829
