### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by mypchas6fans** [xitu/gold-miner#480]
大学一年内过四六级，外企技术工作9年，英语熟练，
曾经翻译过的技术文章：
http://blog.csdn.net/mypchas6fans/article/details/1567347
http://blog.csdn.net/mypchas6fans/article/details/1568578

擅长后端和测试，但也希望同时学习前端和移动的技术

**Comment by antonia0912** [comment]
@mypchas6fans 代表组织欢迎你~请加我微信 antonia0912 备注github ID 我来拉你进译者群
