### ISSUE TITLE
React 是如何区分 Class 和 Function 的 ?

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4801]
* 原文链接：[How Does React Tell a Class from a Function?](https://overreacted.io/how-does-react-tell-a-class-from-a-function/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-does-react-tell-a-class-from-a-function.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4808
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
由 Washington Hua 翻译

**Comment by tonghuashuo** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@tonghuashuo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4808
