### ISSUE TITLE
使用 Flutter，Material Theming 和官方材质组件（MDC）构建美观，灵活的用户界面

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4804]
* 原文链接：[Building beautiful, flexible user interfaces with Flutter, Material Theming, and official Material Components (MDC)](https://medium.com/flutter-io/building-beautiful-flexible-user-interfaces-with-flutter-material-theming-and-official-material-13ae9279ef19)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/building-beautiful-flexible-user-interfaces-with-flutter-material-theming-and-official-material.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4810
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DevMcryYu** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@DevMcryYu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4810
