### ISSUE TITLE
使用 Capacitor 和 Vue.js 构建移动应用

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4805]
* 原文链接：[Building Mobile Apps With Capacitor And Vue.js](https://www.smashingmagazine.com/2018/07/mobile-apps-capacitor-vue-js/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/mobile-apps-capacitor-vue-js.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4823
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5.5-6.5 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4823
