### ISSUE TITLE
时间序列异常检测算法

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4811]
* 原文链接：[Time Series Anomaly Detection Algorithms](https://blog.statsbot.co/time-series-anomaly-detection-algorithms-1cef5519aef2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/time-series-anomaly-detection-algorithms.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4849
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-6 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by haiyang-tju** [comment]
翻译认领 @leviding @fanyijihua

**Comment by fanyijihua** [comment]
@haiyang-tju 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4849
