### ISSUE TITLE
柯里化与函数组合

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4812]
* 原文链接：[Curry and Function Composition](https://medium.com/javascript-scene/curry-and-function-composition-2c208d774983)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/curry-and-function-composition.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4847
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoolRice** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@CoolRice 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4847
