### ISSUE TITLE
以太坊入门指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4817]
* 原文链接：[A beginner’s guide to Ethereum](https://blog.coinbase.com/a-beginners-guide-to-ethereum-46dd486ceecf)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-beginners-guide-to-ethereum.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4852
  * 文章分类：**区块链**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gs666** [comment]
翻译认领@leviding

**Comment by fanyijihua** [comment]
@gs666 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4852
