### ISSUE TITLE
MDC-101 Flutter：Material Components（MDC）基础（Flutter）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4818]
* 原文链接：[MDC-101 Flutter: Material Components (MDC) Basics (Flutter)](https://codelabs.developers.google.com/codelabs/mdc-101-flutter/#0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/mdc-101-flutter.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4825
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：6-7 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@DevMcryYu

**Comment by DevMcryYu** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@DevMcryYu 棒极啦 :tada:
