### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Lv-7** [xitu/gold-miner#483]
25岁,今年硕士毕业,专业Neuroscience, 精读英文文献上千篇, 已参与翻译一本英文专著, 目前正在出版过程中,  精通iOS,python,Matlab,R. 目前职业iOS工程师.

**Comment by antonia0912** [comment]
@Lv-7 欢迎参加掘金翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群
