### ISSUE TITLE
误解 ES6 模块，升级 Babel 的一个解决方案（泪奔）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4835]
* 原文链接：[Misunderstanding ES6 Modules, Upgrading Babel, Tears, and a Solution](https://blog.kentcdodds.com/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4875
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by SinanJS** [comment]
校对认领

**Comment by leviding** [comment]
@SinanJS 本文还在翻译中 @Starriers 翻译好之后艾特下这位哈

**Comment by leviding** [comment]
@Starriers 这篇文章翻译的怎么样啦

**Comment by Starriers** [comment]
@leviding 差点忘了 晚上之前

**Comment by fanyijihua** [comment]
PR 地址：#4875

**Comment by Starriers** [comment]
@SinanJS  翻译好了
