### ISSUE TITLE
用 Flask 和 Vue.js 开发一个单页面应用

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4843]
* 原文链接：[Developing a Single Page App with Flask and Vue.js](https://testdriven.io/developing-a-single-page-app-with-flask-and-vuejs)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/developing-a-single-page-app-with-flask-and-vuejs.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4855
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mcskiller** [comment]
翻译认领

**Comment by leviding** [comment]
@Mcskiller 🆗
