### ISSUE TITLE
iOS 设计模式进阶

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4845]
* 原文链接：[Intermediate Design Patterns in Swift](https://www.raywenderlich.com/2102-intermediate-design-patterns-in-swift)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/intermediate-design-patterns-in-swift.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4982
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：9-12 分
  * 校对积分：2-6 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iWeslie** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@iWeslie 棒极啦 :tada:

**Comment by leviding** [comment]
@iWeslie 这篇文章翻译的怎么样啦

**Comment by iWeslie** [comment]
@kirinzer 有1400行呢做好心理准备哈😏

**Comment by fanyijihua** [comment]
PR 地址：#4982
