### ISSUE TITLE
再看 Flask 视频流

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4859]
* 原文链接：[Flask Video Streaming Revisited](https://blog.miguelgrinberg.com/post/flask-video-streaming-revisited)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/flask-video-streaming-revisited.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4889
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4889
