### ISSUE TITLE
深入解读 JavaScript Promises Part 1: 背景 & 要素

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#486]
原文链接：[Understanding JavaScript Promises, Pt. I: Background & Basics](https://scotch.io/tutorials/understanding-javascript-promises-pt-i-background-basics)
掘金链接：[深入解读 JavaScript Promises Part 1: 背景 & 要素](https://gold.xitu.io/entry/57721e6e2e958a005749763f)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/understanding-javascript-promises-pt-i-background-basics.md)
[校对地址](https://github.com/xitu/gold-miner/pull/532/files?diff=split)
翻译时间：8天
校对时间：8天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by huanglizhuo** [comment]
get

**Comment by huanglizhuo** [comment]
@antonia0912

**Comment by jk77me** [comment]
我擦 没赶上

**Comment by antonia0912** [comment]
@huanglizhuo 可怕~麻利的哈~

**Comment by jk77me** [comment]
占坑1号校对 😀

**Comment by antonia0912** [comment]
@jk77me 校对不可以提前占了喔  因为译者需要好几天才能翻译好 好多校对者占了坑都忘记了 所以以后校对不能提前占坑了 还是等译者发了PR 再来申请校对吧

**Comment by hpoenixf** [comment]
认领校对

**Comment by antonia0912** [comment]
@hpoenixf 好的  校对地址见issue 的description  最好今天校对完喔  因为这个文章拖得有点久了

**Comment by MAYDAY1993** [comment]
认领校对 是时候给新人一个机会了嘛

**Comment by antonia0912** [comment]
@MAYDAY1993 好的 校对地址见issue 的description 最好今天校对完喔 因为这个文章拖得有点久了

**Comment by MrYuJ** [comment]
我要校对！！

**Comment by antonia0912** [comment]
@MrYuJ 这次下手晚了  可以看看别的issue

**Comment by MAYDAY1993** [comment]
校对完成
