### ISSUE TITLE
MDC-102 Flutter：Material 结构和布局（Flutter）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4860]
* 原文链接：[MDC-102 Flutter: Material Structure and Layout (Flutter)](https://codelabs.developers.google.com/codelabs/mdc-102-flutter/#0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/mdc-102-flutter.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4890
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6-8 分
  * 校对积分：1-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
相关链接能改到翻译计划译文的，都改过来。

**Comment by DevMcryYu** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@DevMcryYu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4890
