### ISSUE TITLE
继承 JavaScript 类中的静态属性

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4861]
* 原文链接：[Static Properties in JavaScript Classes with Inheritance](http://thecodebarbarian.com/static-properties-in-javascript-with-inheritance.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/static-properties-in-javascript-with-inheritance.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4874
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Augustwuli** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Augustwuli 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4874
