### ISSUE TITLE
无容器下的云计算

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4862]
* 原文链接：[Cloud Computing without Containers](https://blog.cloudflare.com/cloud-computing-without-containers/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/cloud-computing-without-containers.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4881
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TrWestdoor** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@TrWestdoor 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4881
