### ISSUE TITLE
理解 React Render Props 和 HOC

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4864]
* 原文链接：[Understanding React Render Props and HOC](https://blog.bitsrc.io/understanding-react-render-props-and-hoc-b37a9576e196)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/understanding-react-render-props-and-hoc.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4882
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wuzhengyan2015** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@wuzhengyan2015 棒极啦 :tada:

**Comment by wuzhengyan2015** [comment]
@leviding 文中 twitter 图片博文需要翻译吗，如果要的话是什么格式

**Comment by leviding** [comment]
@wuzhengyan2015 不需要

**Comment by fanyijihua** [comment]
PR 地址：#4882
