### ISSUE TITLE
利用 Python中的 Bokeh 实现数据可视化，第一部分：入门

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4866]
* 原文链接：[Data Visualization with Bokeh in Python, Part I: Getting Started](https://towardsdatascience.com/data-visualization-with-bokeh-in-python-part-one-getting-started-a11655a467d4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/data-visualization-with-bokeh-in-python-part-one-getting-started.md)
  * PR 地址：#4945
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：5.5-7 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by leviding** [comment]
@Starriers 这篇翻译的怎么样啦

**Comment by leviding** [comment]
@Starriers 记得这篇文章
