### ISSUE TITLE
我无法想象没有 Git 别名的的场景

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4867]
* 原文链接：[Git aliases I can't live without](http://mjk.space/git-aliases-i-cant-live-without/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/git-aliases-i-cant-live-without.md)
  * PR 地址：
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4869
