### ISSUE TITLE
使用自定义文件模板加快你的应用开发速度

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4868]
* 原文链接：[Supercharging your app development speed with custom file templates](https://android.jlelse.eu/supercharging-your-app-development-speed-with-custom-file-templates-3e6acb6db6c3)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/supercharging-your-app-development-speed-with-custom-file-templates.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4877
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nanjingboy** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@nanjingboy 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4877
