### ISSUE TITLE
Android 里更美腻的下划线

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#487]
原文链接：[A better underline for Android](https://medium.com/google-developers/a-better-underline-for-android-90ba3a2e4fb)
掘金链接：[Android 里更美腻的下划线](https://gold.xitu.io/entry/577a3f8ba633bd005732cb10)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/a-better-underline-for-android.md)

翻译时间：5天
校对时间：4天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by jamweak** [comment]
认领翻译！

**Comment by antonia0912** [comment]
@jamweak ok 注意时间限制吼~

**Comment by jamweak** [comment]
@antonia0912 ok，我会很快翻完的。

**Comment by whyalwaysmea** [comment]
申请校对

**Comment by antonia0912** [comment]
@whyalwaysmea 译者还没有翻译完 不可以提前占坑喔 等译者提交了PR再申请吧

**Comment by jamweak** [comment]
@antonia0912 翻译完成，已经提交PR了。

**Comment by yifili09** [comment]
@antonia0912 认领一个校对。 ：）

**Comment by antonia0912** [comment]
@whyalwaysmea [校对地址](https://github.com/xitu/gold-miner/pull/506/files?diff=split) 可以开始校对了  另一位校对者已经校对完了  校对完记得留言哈~辛苦 @yifili09 啦~

**Comment by jamweak** [comment]
@antonia0912 两位校对者都已经校对完了，而且我也根据意见改好了，你再看看有没有什么问题。
