### ISSUE TITLE
Patchwork Plaid — A modularization story

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4873]
* 原文链接：[Patchwork Plaid — A modularization story](https://medium.com/androiddevelopers/a-patchwork-plaid-monolith-to-modularized-app-60235d9f212e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-patchwork-plaid-monolith-to-modularized-app.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4932
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-7 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by snpmyn** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@snpmyn 棒极啦 :tada:

**Comment by leviding** [comment]
@snpmyn 这篇翻译的怎么样啦

**Comment by snpmyn** [comment]
翻译完毕

**Comment by snpmyn** [comment]
已发 PR 麻烦你看姿势是否正确？
