### ISSUE TITLE
5 Tools for Faster Development in React

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4879]
* 原文链接：[5 Tools for Faster Development in React](https://blog.bitsrc.io/5-tools-for-faster-development-in-react-676f134050f2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/5-tools-for-faster-development-in-react.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4898
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ivocin** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@Ivocin 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4898
