### ISSUE TITLE
为你定制的 React 学习路线

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#488]
原文链接：[Your Timeline for Learning React](https://daveceddia.com/timeline-for-learning-react/)
掘金链接：[为你定制的 React 学习路线](https://gold.xitu.io/entry/573c388e71cfe448aa8af3e2)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/timeline-for-learning-react.md)
[校对地址](https://github.com/xitu/gold-miner/pull/500/files?diff=split)
翻译时间：4天
校对时间：3天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by wild-flame** [comment]
Get react : )

**Comment by antonia0912** [comment]
@wild-flame 手里有文章的就不给机会咯 留给别人嘛  谢谢老司机~ 最近文章少 给新人个机会哈~

**Comment by aleen42** [comment]
抢

**Comment by wild-flame** [comment]
@wild-flame  可是羊三……我我没有文章啊 T_T

**Comment by wild-flame** [comment]
我那篇已经 merge 了都……那就让给 @aleen42 吧

**Comment by aleen42** [comment]
@antonia0912  _(: 」∠)_

**Comment by aleen42** [comment]
@wild-flame 只是最近在搞，所以抢了_(: 」∠)_

**Comment by wild-flame** [comment]
@aleen42 好的就给你啦！

**Comment by aleen42** [comment]
@wild-flame 哈哈，要看羊三心情

**Comment by antonia0912** [comment]
@wild-flame 谢谢老司机理解~ 这篇文章就让@aleen42 去翻译吧

**Comment by aleen42** [comment]
@antonia0912  锡晒你～

**Comment by llp0574** [comment]
占坑校对，之前那篇占坑校对的好久都没有翻译完 @antonia0912

**Comment by antonia0912** [comment]
@llp0574 现在不允许提前占坑了  等译者提交了pr再来申请校对吧  之前认领的是哪一篇 我去催催

**Comment by llp0574** [comment]
@antonia0912 更加安全的Swift那篇，新人到现在还没抢到过校对。。。

**Comment by jiaowoyongqi** [comment]
认领处女校

**Comment by antonia0912** [comment]
@jiaowoyongqi @llp0574 [校对地址](https://github.com/xitu/gold-miner/pull/500/files?diff=split)

**Comment by llp0574** [comment]
@antonia0912 耶，来了

**Comment by llp0574** [comment]
@antonia0912 校对完成~

**Comment by jiaowoyongqi** [comment]
校对好咯 @antonia0912

**Comment by aleen42** [comment]
thx both @jiaowoyongqi  @llp0574 , I will commit soon!
