### ISSUE TITLE
懒加载图片？不要依赖 JavaScript ！

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#489]
原文链接：[Lazy Loading Images? Don’t Rely On JavaScript!](http://robinosborne.co.uk/2016/05/16/lazy-loading-images-dont-rely-on-javascript/)
掘金链接：[懒加载图片？不要依赖 JavaScript ！](https://gold.xitu.io/entry/573c385d1532bc0065711deb)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/lazy-loading-images-dont-rely-on-javascript.md)

翻译时间：5天
校对时间：3天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by jk77me** [comment]
get

**Comment by jk77me** [comment]
@antonia0912 天了噜 终于撸到一篇了

**Comment by antonia0912** [comment]
@jk77me ok 注意翻译时间限制哈~等你PR

**Comment by owenlyn** [comment]
@antonia0912 @jk77me 占坑校对

**Comment by antonia0912** [comment]
@owenlyn 现在不可以在PR还没有发的时候来占校对了  等译者初稿发了pr再来申请校对吧

**Comment by owenlyn** [comment]
@antonia0912 T.T 😭

**Comment by hpoenixf** [comment]
认领校对

**Comment by mypchas6fans** [comment]
认领校对

**Comment by zhangchen91** [comment]
认领校对

**Comment by zhangchen91** [comment]
认领校对

**Comment by antonia0912** [comment]
@hpoenixf @mypchas6fans [校对地址](https://github.com/xitu/gold-miner/pull/511/files?diff=split)
