### ISSUE TITLE
渐进增强的含义及意义

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4891]
* 原文链接：[What is Progressive Enhancement, and why it matters](https://medium.freecodecamp.org/what-is-progressive-enhancement-and-why-it-matters-e80c7aaf834a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-is-progressive-enhancement-and-why-it-matters.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4900
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by RicardoCao-Biker** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@RicardoCao-Biker 棒极啦 :tada:
