### ISSUE TITLE
2019 年你应该要知道的 11 个 React UI 组件库

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4893]
* 原文链接：[11 React UI Component Libraries you Should Know in 2019](https://blog.bitsrc.io/11-react-component-libraries-you-should-know-178eb1dd6aa4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/11-react-component-libraries-you-should-know.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4903
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ElizurHz** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@ElizurHz 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4903

**Comment by fanyijihua** [comment]
PR 地址：#4904

**Comment by Ivocin** [comment]
@leviding  这个文章的标题有问题，写的是 2019 的趋势，但是写作时间确实 2017 年 11 月，内容有些过时了。尤其是最后一句：
As it seems, in 2018 the popularity of React will continue to rise and its components will grow to become the modular building blocks of more of the apps we use every day.

**Comment by ElizurHz** [comment]
@Ivocin 这个作者的博客里把所有的之前写的有年份的博客标题全部改成 2019 了。但这篇如果去掉前后那些东西，主要内容也并不完全会过时就是了

**Comment by ElizurHz** [comment]
@Ivocin @leviding 这个作者的博客里把所有的之前写的有年份的博客标题全部改成 2019 了，内容不知道有没有变更，因为看不到更新时间，但是查了下 material ui 现在已经更新到 3.7 了，它里面还写的 v1 即将发布。。。

**Comment by Ivocin** [comment]
> @Ivocin @leviding 这个作者的博客里把所有的之前写的有年份的博客标题全部改成 2019 了，内容不知道有没有变更，因为看不到更新时间，但是查了下 material ui 现在已经更新到 3.7 了，它里面还写的 v1 即将发布。。。

是的，本来想校对这篇文章的，结果看了一下内容，发现确实有些滞后了，一年可以发生太多的事情了。

**Comment by ElizurHz** [comment]
> > @Ivocin @leviding 这个作者的博客里把所有的之前写的有年份的博客标题全部改成 2019 了，内容不知道有没有变更，因为看不到更新时间，但是查了下 material ui 现在已经更新到 3.7 了，它里面还写的 v1 即将发布。。。
> 
> 是的，本来想校对这篇文章的，结果看了一下内容，发现确实有些滞后了，一年可以发生太多的事情了。

最近的文章好像不少和这个 Bit 相关的，感觉质量都不是很高，而且很多写法感觉也很奇怪

**Comment by leviding** [comment]
嗯嗯，标题你可以根据文章内容拟定，文章内容不是很确定的可以加译者注。

**Comment by ElizurHz** [comment]
> 嗯嗯，标题你可以根据文章内容拟定，文章内容不是很确定的可以加译者注。他的内容不好，之后就不翻译他的了。

我倒是觉得很像是标题党 + 他那个 Bit 的硬广，技术含量基本没有，这种文章我其实不是很想发在掘金上

**Comment by leviding** [comment]
OK，以后不放 Bit 的文章了

**Comment by ElizurHz** [comment]
> OK，以后不放 Bit 的文章了

现在已经做了的要怎办，我现在刚好还接了一个 @Ivocin 之前翻译的 Bit 的校对 #4898

**Comment by leviding** [comment]
已经做了的就继续 😀 不影响
