### ISSUE TITLE
一份关于色彩无障碍性产品设计的指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4894]
* 原文链接：[A guide to color accessibility in product design](https://medium.com/inside-design/a-guide-to-color-accessibility-in-product-design-516e734c160c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-guide-to-color-accessibility-in-product-design.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4930
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ivocin** [comment]
@leviding  这个 Markdown 文件多了一大部分：https://github.com/xitu/gold-miner/blob/master/TODO1/a-guide-to-color-accessibility-in-product-design.md

**Comment by leviding** [comment]
@Ivocin 已改

**Comment by fanyijihua** [comment]
PR 地址：#4930
