### ISSUE TITLE
UX 设计实践：如何设计可扫描的 Web 界面

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4895]
* 原文链接：[UX Design Practices: How to Make Web Interface Scannable](https://uxplanet.org/ux-design-practices-how-to-make-web-interface-scannable-2010125c710e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/ux-design-practices-how-to-make-web-interface-scannable.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4947
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5-6 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ivocin** [comment]
我来认领吧，看着放好久了 @leviding

**Comment by Ivocin** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Ivocin 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4947
