### ISSUE TITLE
利用 Python中的 Bokeh 实现数据可视化，第二部分：交互

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4896]
* 原文链接：[Data Visualization with Bokeh in Python, Part II: Interactions](https://towardsdatascience.com/data-visualization-with-bokeh-in-python-part-ii-interactions-a4cf994e2512)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/data-visualization-with-bokeh-in-python-part-ii-interactions.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4941
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
本系列第一篇在这儿 → https://github.com/xitu/gold-miner/issues/4866

**Comment by Starriers** [comment]
翻译认领

**Comment by leviding** [comment]
@Starriers OK

**Comment by leviding** [comment]
@Starriers 记得这篇文章

**Comment by fanyijihua** [comment]
PR 地址：#4941
