### ISSUE TITLE
Rust 2018 已经发布...但它是到底什么呢？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4899]
* 原文链接：[Rust 2018 is here… but what is it?](https://hacks.mozilla.org/2018/12/rust-2018-is-here/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/rust-2018-is-here-but-what-is-it.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4992
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：9-10 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoolRice** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@CoolRice 棒极啦 :tada:

**Comment by leviding** [comment]
@CoolRice 记得这篇文章哈

**Comment by leviding** [comment]
@CoolRice 翻译的怎么样啦~

**Comment by kuangbao9** [comment]
@leviding 翻译认领
