### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zhangchen91** [xitu/gold-miner#490]
从事前端开发4年多，平时会阅读一些前端相关的英文技术文档，也会上StackOverflow等英文网站，非常喜欢掘金的文章，也希望自己能翻译/校对一些英文文章。

**Comment by antonia0912** [comment]
@zhangchen91 欢迎参加掘金翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群
