### ISSUE TITLE
值类型导向编程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4901]
* 原文链接：[Value-Oriented Programming](https://matt.diephouse.com/2018/08/value-oriented-programming)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/value-oriented-programming.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4909
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nanjingboy** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@nanjingboy 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4909
