### ISSUE TITLE
Flutter 从 0 到 1

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4902]
* 原文链接：[Zero to One with Flutter](https://medium.com/flutter-io/zero-to-one-with-flutter-43b13fd7b354)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/zero-to-one-with-flutter.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4923
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hongruqi** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@hongruqi 棒极啦 :tada:
