### ISSUE TITLE
Android 上一次编写，到处测试

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4906]
* 原文链接：[Write Once, Run Everywhere Tests on Android](https://medium.com/androiddevelopers/write-once-run-everywhere-tests-on-android-88adb2ba20c5)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/write-once-run-everywhere-tests-on-android.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4916
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gs666** [comment]
翻译认领@leviding

**Comment by fanyijihua** [comment]
@gs666 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4916

**Comment by leviding** [comment]
@xiaxiayang 好的，下次记得在对应 PR 下认领
