### ISSUE TITLE
CSS Shapes 简介

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4911]
* 原文链接：[An Introduction to CSS Shapes](https://tympanus.net/codrops/2018/11/29/an-introduction-to-css-shapes/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/an-introduction-to-css-shapes.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4957
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4957
