### ISSUE TITLE
为什么我放弃了 React 而转向 Vue

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4912]
* 原文链接：[Why I left React for Vue.](https://blog.sourcerer.io/why-you-should-leave-react-for-vue-and-never-use-it-again-5e274bef27c2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-you-should-leave-react-for-vue-and-never-use-it-again.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4924
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6.5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
认领翻译 @leviding

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:
