### ISSUE TITLE
一文带你看完 2018 年浏览器之争的最新进展

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4918]
* 原文链接：[The State of Web Browsers: Late 2018 edition](https://ferdychristant.com/the-state-of-web-browsers-f5a83a41c1cb)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-state-of-web-browsers.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4971
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：10-12 分
  * 校对积分：2-6 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by HumesFork** [comment]
文章很长，需要延迟2天，周末交货 @ @leviding

**Comment by leviding** [comment]
@HumesFork 翻译的怎么样啦~

**Comment by HumesFork** [comment]
@leviding 下午提交

**Comment by fanyijihua** [comment]
PR 地址：#4971
