### ISSUE TITLE
我们采用 GraphQL 技术的经验：营销技术活动

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4919]
* 原文链接：[Our learnings from adopting GraphQL: A Marketing Tech Campaign](https://medium.com/netflix-techblog/our-learnings-from-adopting-graphql-f099de39ae5f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/our-learnings-from-adopting-graphql.md)
  * PR 地址：
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xutaogit** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@xutaogit 棒极啦 :tada:
