### ISSUE TITLE
Flutter 从 0 到 1 第二部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4926]
* 原文链接：[Zero to One with Flutter, Part Two](https://medium.com/flutter-io/zero-to-one-with-flutter-part-two-5aa2f06655cb)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/zero-to-one-with-flutter-part-two.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5023
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：1 天
  * 翻译积分：7.5-8.5 分
  * 校对积分：1.5-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@hongruqi 第二篇来啦~

**Comment by hongruqi** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@hongruqi 棒极啦 :tada:

**Comment by leviding** [comment]
@hongruqi 翻译的怎么样啦~

**Comment by leviding** [comment]
@hongruqi 好滴～辛苦啦

**Comment by leviding** [comment]
@hongruqi 记得这篇翻译哈~
