### ISSUE TITLE
Lenses：可组合函数式编程的 Getter 和 Setter

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4927]
* 原文链接：[Lenses: Composable Getters and Setters for Functional Programming](https://medium.com/javascript-scene/lenses-b85976cb0534)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/lenses-composable-getters-and-setterssfor-functional-programming.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4961
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
认领翻译～

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4961
