### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by gfwfail** [xitu/gold-miner#493]
从事后端+前端开发4年多，平时会阅读一些技术相关的英文技术文档，也会上一些英文网站，在澳洲留学7年，非常喜欢掘金翻译的一些文章，也希望自己能翻译/校对一些英文文章。

**Comment by antonia0912** [comment]
@gfwfail 欢迎参加掘金翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群
