### ISSUE TITLE
新愿景: 未来的程序应用平台

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4935]
* 原文链接：[A New Hope: The Future of Application Platforms](https://medium.com/javascript-scene/a-new-hope-e2021fce7c7b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-new-hope-the-future-of-application-platforms.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4955
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by skychenbo** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@skychenbo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4955
