### ISSUE TITLE
充分利用多摄像头 API

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4936]
* 原文链接：[Getting the Most from the New Multi-Camera API](https://medium.com/androiddevelopers/getting-the-most-from-the-new-multi-camera-api-5155fb3d77d9)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/getting-the-most-from-the-new-multi-camera-api.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4972
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6-7.5 分
  * 校对积分：1-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xiaxiayang** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@xiaxiayang 棒极啦 :tada:
