### ISSUE TITLE
降维技术中常用的几种降维方法

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4937]
* 原文链接：[Reducing Dimensionality from Dimensionality Reduction Techniques](https://towardsdatascience.com/reducing-dimensionality-from-dimensionality-reduction-techniques-f658aec24dfe)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/reducing-dimensionality-from-dimensionality-reduction-techniques.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4993
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：1 天
  * 翻译积分：7-8 分
  * 校对积分：1-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by haiyang-tju** [comment]
翻译认领 @leviding @fanyijihua

**Comment by fanyijihua** [comment]
@haiyang-tju 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4993
