### ISSUE TITLE
理解异步 JavaScript

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4939]
* 原文链接：[Understanding Asynchronous JavaScript](https://blog.bitsrc.io/understanding-asynchronous-javascript-the-event-loop-74cd408419ff)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/understanding-asynchronous-javascript-the-event-loop.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4944
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by H246802** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@H246802 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4942

**Comment by fanyijihua** [comment]
PR 地址：#4944
