### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by macarthor** [xitu/gold-miner#494]
天津大学电信学院本硕，11年工作经验，android开发2年余，创业公司暂时保密行么。。。
英语双学位，TEM-8，研究生期间兼职笔译。
国外什么网站都上。。。自带翻墙。

**Comment by antonia0912** [comment]
@macarthor hey 译者申请请参考 [往期译者申请](https://github.com/xitu/gold-miner/issues/249)，内容包括公司/学校、工作内容/专业、英语水平、常浏览的国外网站、英语水平、有无翻译经验、个人博客等。

**Comment by macarthor** [comment]
@antonia0912 review ag plz~

**Comment by antonia0912** [comment]
@macarthor Bravo~请加我微信 antonia0912 备注 github ID 我来拉你进译者群
