### ISSUE TITLE
2019 区块链平台与技术展望

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4948]
* 原文链接：[Blockchain Platforms & Tech to Watch in 2019](https://medium.com/the-challenge/blockchain-platforms-tech-to-watch-in-2019-f2bfefc5c23)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/blockchain-platforms-tech-to-watch-in-2019.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5081
  * 文章分类：**区块链**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：1 天
  * 翻译积分：7-8.5 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gs666** [comment]
翻译认领@leviding

**Comment by fanyijihua** [comment]
@gs666 棒极啦 :tada:

**Comment by leviding** [comment]
@gs666 翻译的怎么样啦~

**Comment by gs666** [comment]
> @gs666 翻译的怎么样啦~

正在努力，最迟明天一定搞定。（最近事多，而这篇文章好长长长。。。）

**Comment by leviding** [comment]
@gs666 确实好长. . . 我就是问下进度，按你的时间来~

**Comment by leviding** [comment]
@gs666 记得这一篇翻译哈～

**Comment by gs666** [comment]
> @gs666 记得这一篇翻译哈～

其实最近一直在翻译呢，还有八段，明天提交！

**Comment by leviding** [comment]
@gs666 好，辛苦啦 😆

**Comment by fanyijihua** [comment]
PR 地址：#5081

**Comment by gs666** [comment]
@leviding 终于完成啦
