### ISSUE TITLE
提高营销效率的工程（二）—— 广告制作和管理的规模化

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4949]
* 原文链接：[Engineering to Improve Marketing Effectiveness (Part 2) — Scaling Ad Creation and Management](https://medium.com/netflix-techblog/https-medium-com-netflixtechblog-engineering-to-improve-marketing-effectiveness-part-2-7dd933974f5e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/https-medium-com-netflixtechblog-engineering-to-improve-marketing-effectiveness-part-2.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4998
  * 文章分类：**软件开发**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6-7 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
第一篇在这 https://github.com/xitu/gold-miner/issues/4920

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by leviding** [comment]
@Starriers 这篇记得抓紧翻译提交，旧的没提交，就暂时不要认领新的了。
