### ISSUE TITLE
移动开发中用 1x 视觉稿设计的好处

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#495]
原文链接：[Design at 1x—It’s a Fact](https://medium.com/shyp-design/design-at-1x-its-a-fact-249c5b896536)
掘金链接：[移动开发中用 1x 视觉稿设计的好处](http://gold.xitu.io/entry/577c70630a2b58005734a112)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/design-at-1x-its-a-fact.md)
[校对地址](https://github.com/xitu/gold-miner/pull/518/files?diff=split)
翻译时间：4天
校对时间：3天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by wild-flame** [comment]
@antonia0912 羊三这篇要是没人要就给我吧~

**Comment by antonia0912** [comment]
@wild-flame 吼~注意时间限制哈~

**Comment by wild-flame** [comment]
@antonia0912 刚好四天 [地址](https://github.com/xitu/gold-miner/pull/518/files)

**Comment by antonia0912** [comment]
@wild-flame wonderful~我来联系校对者哈 辛苦了

**Comment by llp0574** [comment]
@antonia0912 校对认领~

**Comment by antonia0912** [comment]
@llp0574 好的 校对地址见issue描述 注意校对时间限制哈~

**Comment by tanglie1993** [comment]
校对认领

**Comment by antonia0912** [comment]
@tanglie1993 好的 校对地址见issue描述 注意校对时间限制哈~
