### ISSUE TITLE
2018 前端全面回顾

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4958]
* 原文链接：[A comprehensive look back at front-end in 2018](https://blog.logrocket.com/a-comprehensive-look-back-at-frontend-in-2018-8122e724a802)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-comprehensive-look-back-at-frontend-in-2018.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4981
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：7.5-9 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ivocin** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@Ivocin 棒极啦 :tada:
