### ISSUE TITLE
2019 年值得学习的顶级 JavaScript 框架与主题

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4963]
* 原文链接：[Top JavaScript Frameworks and Topics to Learn in 2019](https://medium.com/javascript-scene/top-javascript-frameworks-and-topics-to-learn-in-2019-b4142f38df20)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/top-javascript-frameworks-and-topics-to-learn-in-2019.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4974
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ElizurHz** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ElizurHz 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4974
