### ISSUE TITLE
如何写一篇软件工程必杀简历

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4964]
* 原文链接：[How to write a killer Software Engineering résumé](https://medium.freecodecamp.org/writing-a-killer-software-engineering-resume-b11c91ef699d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/writing-a-killer-software-engineering-resume.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5090
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：8.5-10 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by leviding** [comment]
@EmilyQiRabbit 翻译的怎么样啦~

**Comment by EmilyQiRabbit** [comment]
@leviding 不好意思，前两个礼拜一直在生病 >.< 争取两天内提交哈。

**Comment by leviding** [comment]
好的哈，辛苦啦～

**Comment by fanyijihua** [comment]
PR 地址：#5090

**Comment by EmilyQiRabbit** [comment]
@leviding 翻译完成 🤣 终于～
