### ISSUE TITLE
使用 Stripe, Vue.js 和 Flask 接受付款

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4965]
* 原文链接：[Accepting Payments with Stripe, Vue.js, and Flask](https://testdriven.io/blog/accepting-payments-with-stripe-vuejs-and-flask/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/accepting-payments-with-stripe-vuejs-and-flask.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4976
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#4976
