### ISSUE TITLE
我作为软件工程师与一名数据科学家合作的经历

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4966]
* 原文链接：[I Worked With A Data Scientist As A Software Engineer. Here’s My Experience.](https://towardsdatascience.com/i-worked-with-a-data-scientist-heres-what-i-learned-2e19c5f5204)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/i-worked-with-a-data-scientist-heres-what-i-learned.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5037
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CasualJi** [comment]
认领

**Comment by leviding** [comment]
@CasualJi 好滴~

**Comment by fanyijihua** [comment]
PR 地址：#5037
