### ISSUE TITLE
为什么你的应用需要对各种尺寸屏幕做适配优化？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4967]
* 原文链接：[Why your app should be optimized for screens of all sizes](https://medium.com/googleplaydev/more-than-mobile-friendly-547e44bc085a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-your-app-should-be-optimized-for-screen-of-all-sizes.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5119
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MirosalvaSun** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MirosalvaSun 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5119
