### ISSUE TITLE
轻松发布私有 App

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4968]
* 原文链接：[Publishing private apps just got easier](https://medium.com/androiddevelopers/publishing-private-apps-just-got-easier-40399c424b8a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/publishing-private-apps-just-got-easier.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/4999
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Qiuk17** [comment]
翻译认领
@leviding

**Comment by fanyijihua** [comment]
@Qiuk17 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#4999
