### ISSUE TITLE
在 iOS 上使用 Carthage 建立依赖

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4970]
* 原文链接：[Building Dependencies on iOS with Carthage](https://appunite.com/blog/dependencies-ios-carthage)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/dependencies-ios-carthage.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5024
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iWeslie** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@iWeslie 棒极啦 :tada:

**Comment by leviding** [comment]
@iWeslie 翻译的怎么样啦~

**Comment by fanyijihua** [comment]
PR 地址：#5024
