### ISSUE TITLE
2019 前端性能优化年度总结 — 第一部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4975]
* 原文链接：[Front-End Performance Checklist 2019 — 1](https://www.smashingmagazine.com/2019/01/front-end-performance-checklist-2019-pdf-pages/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/front-end-performance-checklist-2019-pdf-pages-1.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5006
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：8-10 分
  * 校对积分：2-5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Hopsken** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@Hopsken 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5006
