### ISSUE TITLE
2019 前端性能优化年度总结 — 第二部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4977]
* 原文链接：[Front-End Performance Checklist 2019 — 2](https://www.smashingmagazine.com/2019/01/front-end-performance-checklist-2019-pdf-pages/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/front-end-performance-checklist-2019-pdf-pages-2.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5022
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：7-9 分
  * 校对积分：1.5-4.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by KarthusLorin** [comment]
@leviding 认领翻译

**Comment by fanyijihua** [comment]
@KarthusLorin 棒极啦 :tada:

**Comment by leviding** [comment]
@KarthusLorin 翻译的怎么样啦~

**Comment by KarthusLorin** [comment]
@leviding 昨天完成了，今天下午我再校对一遍~

**Comment by fanyijihua** [comment]
PR 地址：#5022
