### ISSUE TITLE
推荐翻译在哪里贴？

### ISSUE THREAD

**Issue by cerebrowang** [xitu/gold-miner#4983]

**Comment by Ivocin** [comment]
@singerswang Issues 就可以，标题命名为“推荐优秀文章”类似的

**Comment by singerswang** [comment]
掘金计划中，有浏览器第二次世界大战介绍，有JavaScript的介绍，就是没有2者完全相关的Google Polymer 介绍，https://www.polymer-project.org/，你们不感到奇怪吗？到底发生了神马？要不要我去日本找柯南来？

**Comment by leviding** [comment]
![image](https://user-images.githubusercontent.com/26959437/51095222-27dd9880-17ee-11e9-9926-487387e99b87.png)

看 README

**Comment by singerswang** [comment]
是呀，好像有点不大适合，我也在考虑贴还是不贴 :.(
