### ISSUE TITLE
讨论 JS ⚡：文档

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4994]
* 原文链接：[Let's talk JS ⚡: documentation](https://areknawo.com/lets-talk-js-documentation/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/lets-talk-js-documentation.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5000
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by leviding** [comment]
@Starriers ok
