### ISSUE TITLE
DNS over TLS：端到端加密的 DNS

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#4995]
* 原文链接：[DNS over TLS: Encrypting DNS end-to-end](https://code.fb.com/security/dns-over-tls/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/dns-over-tls.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5029
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：3 天
  * 翻译积分：1 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5000
