### ISSUE TITLE
认领：Android 的一个 MVP 基础项目模板

### ISSUE THREAD

**Issue by tycallen** [xitu/gold-miner#50]
两年前接触Android开发，一年前毕业后加入阿里巴巴从事Android开发相关工作。对开源有热情，英语水平不错。

**Comment by tycallen** [comment]
MVVM也很有兴趣，这两种模式的理解对于平时工作都有莫大帮助

**Comment by Glowin** [comment]
你好，我们的 Android 文章已经被认领完了呢 #12 ，您看看能不能挑一个其他的未被认领的文章呢，谢谢理解

**Comment by tycallen** [comment]
这个也行：Making React Native apps accessible(markdown）

**Comment by Glowin** [comment]
@tycallen 你好，这篇文章已经被 @void-main 认领并完成初稿了#73 。而且现在我挑选出来的文章也基本被认领完了，但是这个翻译计划还是会一直更新维护下去，我们很乐意邀请你加入并关注这个翻译计划，谢谢你的支持和理解。
