### ISSUE TITLE
Bye bye Mongo, Hello Postgres

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5002]
* 原文链接：[Bye bye Mongo, Hello Postgres](https://www.theguardian.com/info/2018/nov/30/bye-bye-mongo-hello-postgres)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/bye-bye-mongo-hello-postgres.md)
  * PR 地址：
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：1 天
  * 翻译积分：6.5-8 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by alexsnail** [comment]
申请翻译

**Comment by fanyijihua** [comment]
@alexsnail 棒极啦 :tada:

**Comment by leviding** [comment]
@alexsnail Hello，这篇翻译的怎么样啦±

**Comment by leviding** [comment]
@alexsnail Hello，这篇翻译的怎么样啦～

**Comment by leviding** [comment]
超期过久，重新释放。

**Comment by sunui** [comment]
@leviding 已经被翻译啦 https://www.infoq.cn/article/O*TADftw8KOhsfTArgiD

**Comment by leviding** [comment]
@sunui get！
