### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by jiaowoyongqi** [xitu/gold-miner#501]
您好！我叫yongqi，现在一家设计体验公司做交互设计师。具有较好的英语水平，经常访问Medium/Github/Quora/Behance/Dribbble等。我的博客是http://lilianlun.lofter.com/ 内有之前翻译的译文，微信公众号是jiaowoyongqi。希望加入翻译计划！互相学习！

**Comment by jiaowoyongqi** [comment]
@antonia0912 OK 已经发好了

**Comment by antonia0912** [comment]
@jiaowoyongqi 好的 请加我微信 antonia0912 备注 github ID 我来拉你进译者群~
