### ISSUE TITLE
通过垃圾回收机制理解 JavaScript 内存管理

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5010]
* 原文链接：[Understanding JavaScript Memory Management using Garbage Collection](https://medium.com/front-end-weekly/understanding-javascript-memory-management-using-garbage-collection-35ed4954a67f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/understanding-javascript-memory-management-using-garbage-collection.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5020
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wuzhengyan2015** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@wuzhengyan2015 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5020
