### ISSUE TITLE
使用 Proxy 来观测 Javascript 中的类

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5018]
* 原文链接：[Using Proxy to Track Javascript Class](https://medium.com/front-end-weekly/using-proxy-to-track-javascript-class-50a33a6ccb)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/using-proxy-to-track-javascript-class.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5032
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by SHERlocked93** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@SHERlocked93 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5032
