### ISSUE TITLE
使用 Recompose 来构建高阶组件

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5019]
* 原文链接：[Building HOCs with Recompose](https://medium.com/front-end-developers/building-hocs-with-recompose-7debb951d101)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/building-hocs-with-recompose.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5025
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by SHERlocked93** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@SHERlocked93 棒极啦 :tada:
