### ISSUE TITLE
十件你不知道的关于 WebPageTest.org 的事

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5027]
* 原文链接：[Ten Things you didn't know about WebPageTest.org](https://deanhume.com/ten-things-you-didnt-know-about-webpagetest-org/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/ten-things-you-didnt-know-about-webpagetest-org.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5141
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by leviding** [comment]
翻译的怎么样啦

**Comment by lsvih** [comment]
@leviding 忘了，回家就传。。。

**Comment by leviding** [comment]
记得传这篇哈

**Comment by fanyijihua** [comment]
PR 地址：#5141
