### ISSUE TITLE
为什么我不再使用 export default 来导出模块

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5030]
* 原文链接：[Why I've stopped exporting defaults from my JavaScript modules](https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/stop-using-default-exports-javascript-module.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5046
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by KarthusLorin** [comment]
@leviding 认领翻译

**Comment by fanyijihua** [comment]
@KarthusLorin 棒极啦 :tada:

**Comment by KarthusLorin** [comment]
@leviding 不好意思，最近收到紧急任务，要去出差，最近没什么时间翻译了。。。。
能不能把这篇重新释放出去~

**Comment by leviding** [comment]
@KarthusLorin 好的，没问题

**Comment by Hopsken** [comment]
@leviding 认领翻译

**Comment by fanyijihua** [comment]
@Hopsken 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5046
