### ISSUE TITLE
我与 Flutter 的一年

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5031]
* 原文链接：[One Year with Flutter: My Experience](https://hackernoon.com/one-year-with-flutter-my-experience-5bfe64acc96f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/one-year-with-flutter-my-experience.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5065
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1-2.5 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
PR 地址：#5065
