### ISSUE TITLE
Python的时间序列分析：简介

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5034]
* 原文链接：[Time Series Analysis in Python: An Introduction](https://towardsdatascience.com/time-series-analysis-in-python-an-introduction-70d5a5b1d52a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/time-series-analysis-in-python-an-introduction.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5058
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ppp-man** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ppp-man 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5058
