### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by Hermitvv** [xitu/gold-miner#5038]
- 原文链接：
- 简要介绍：介绍一下好不好啦，毕竟小编也看不太懂哎_(:з」∠

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
@Fengziyin1234 网上查了下，已经有一些译文了鸭 https://zhuanlan.zhihu.com/p/43106313
欢迎再推荐其他的哈~

**Comment by leviding** [comment]
@Hermitvv 推荐文章，是漏了文章介绍和文章链接吗？本 issue 关掉了哈，如有文章推荐请另开 issue。
