### ISSUE TITLE
5 个可以立刻在你的 Ionic App 中用上的动画包

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5041]
* 原文链接：[5 Animation Packages You Can Immediately Use Inside Your Ionic App](https://devdactic.com/5-animation-packages-ionic)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/5-animation-packages-ionic.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5048
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5048
