### ISSUE TITLE
2019版 web 浏览器现状 

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5042]
* 原文链接：[The State of Web Browsers 2019 edition](https://ferdychristant.com/the-state-of-web-browsers-88224d55b4e6)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-state-of-web-browsers-2019-edition.md)
  * PR 地址：#5349
  * 文章分类：**产品**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：9-11 分
  * 校对积分：2-5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CasualJi** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@CasualJi 棒极啦 :tada:

**Comment by leviding** [comment]
@CasualJi 翻译的怎么样啦

**Comment by leviding** [comment]
@CasualJi Hello，这篇翻译的怎么样啦～

**Comment by leviding** [comment]
超期过久，本文重新释放。

**Comment by xionglong58** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@xionglong58 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5349
