### ISSUE TITLE
React Native 与 iOS 和 Android 通信

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5043]
* 原文链接：[React Native Bridge for iOS and Android](https://hackernoon.com/react-native-bridge-for-ios-and-android-43feb9712fcb)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/react-native-bridge-for-ios-and-android.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5055
  * 文章分类：**iOS, Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MeandNi** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MeandNi 棒极啦 :tada:

**Comment by MeandNi** [comment]
@leviding
