### ISSUE TITLE
2019 年的 9 大设计趋势

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5044]
* 原文链接：[The 9 big design trends of 2019](https://www.fastcompany.com/90281299/the-9-big-design-trends-of-2019)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-9-big-design-trends-of-2019.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5160
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shixi-li** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@shixi-li 棒极啦 :tada:
