### ISSUE TITLE
Webpack 4 的故事以及如何用正确的方式去最终配置它【更新版】

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5047]
* 原文链接：[A tale of Webpack 4 and how to finally configure it in the right way. Updated.](https://hackernoon.com/a-tale-of-webpack-4-and-how-to-finally-configure-it-in-the-right-way-4e94c8e7e5c1)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-tale-of-webpack-4-and-how-to-finally-configure-it-in-the-right-way.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5102
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6-7 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TUARAN** [comment]
申请认领，第一次做，需要先从校对文章试试水吗？老司机带带我😀

**Comment by leviding** [comment]
@TUARAN 可以哒，等这篇文章译者翻译完，艾特你校对，你到时候在对应的 PR 下认领就行了。
你也可以现在申请 PR 下的其他校对哈~ 
https://github.com/xitu/gold-miner/pulls

**Comment by TUARAN** [comment]
🆗

**Comment by iceytea** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@iceytea 棒极啦 :tada:

**Comment by leviding** [comment]
@iceytea 翻译的怎么样啦？

**Comment by iceytea** [comment]
@leviding 这两天在外面，不大方便上传。明天晚上会提交一版

**Comment by iceytea** [comment]
> @leviding 这两天在外面，不大方便上传。明天晚上会提交一版

抱歉，由于各种原因，导致提交延期。深感抱歉~

**Comment by leviding** [comment]
@iceytea 好滴，辛苦啦，过年期间，好好休息，我就是例行提醒哈

**Comment by leviding** [comment]
@TUARAN 可以到 PR 下认领校对啦
