### ISSUE TITLE
使用多种服务来确定地理方位

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#505]
原文链接：[Geolocation using multiple services](https://blog.garage-coding.com/2016/07/06/geolocation-using-multiple-services.html)
掘金链接：[使用多种服务来确定地理方位](http://gold.xitu.io/entry/577f4cdc1532bc005f0fdbbb)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/geolocation-using-multiple-services.md)

翻译时间：4天
校对时间：3天
翻译积分：5
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by emmiter** [comment]
翻译认领~

**Comment by emmiter** [comment]
@antonia0912 我VR那篇校对完毕了，不过那篇文章还没发出去。这个我可以翻译吗~

**Comment by yifili09** [comment]
好不容易看到一个。。 :disappointed_relieved:

**Comment by wsdookadr** [comment]
@antonia0912 , @emmiter , @yifili09 
Hi friends,

I'm the author of the blog post. I'm enthusiastic about
your work towards translating the post to the Chinese language
that so many people speak and many of them are interested in
technology.

May I link back in my website to your Chinese translation ?

Thank you,
Stefan

**Comment by a-voyager** [comment]
认领校对

**Comment by wsdookadr** [comment]
the pull request #508 provides a markdown version of this post

**Comment by aleen42** [comment]
@wsdookadr Hah, @antonia0912 I think she should be pleasure with doing this.

**Comment by antonia0912** [comment]
@emmiter 可以的  等你PR 还有注意翻译时间限制哈~

**Comment by antonia0912** [comment]
@wsdookadr Of course！I will send you the Chinese link after finished. Feel free to do so ~

**Comment by emmiter** [comment]
@antonia0912 收到 : )

**Comment by jamweak** [comment]
认领校对

**Comment by antonia0912** [comment]
@a-voyager @jamweak  [校对地址](https://github.com/xitu/gold-miner/pull/531/files?diff=split)  注意校对时间限制哈~加油

**Comment by jamweak** [comment]
@antonia0912 校对完毕。
