### ISSUE TITLE
The TypeScript Tax: A Cost vs Benefit Analysis

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5053]
* 原文链接：[The TypeScript Tax: A Cost vs Benefit Analysis](https://medium.com/javascript-scene/the-typescript-tax-132ff4cb175b)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-typescript-tax.md)
  * PR 地址：
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8 分
  * 校对积分：1-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by SHERlocked93** [comment]
@leviding 翻译认领

**Comment by SHERlocked93** [comment]
很遗憾，前端之巅公众号已经发出译文了，这个issue关闭吧 @leviding    🤣
![image](https://user-images.githubusercontent.com/24636076/52118327-ffa8c300-2650-11e9-8afc-f2af33e0fb78.png)

**Comment by leviding** [comment]
@SHERlocked93 get！

**Comment by rambo-panda** [comment]
这个翻译简直误导人。博人眼球

The TypeScript Tax。A Cost vs Benefit Analysis

就算用百度翻译直接翻译，也应该是  typescript税，成本效益分析

文章作者也没说，ts不适合啊。 只是说成本(schema规范、团队约束) 以及 所获得的收益之间的比较


-------------------

连我这个不喜欢ts的人，都觉得这是在侮辱人家。
