### ISSUE TITLE
Vue.js  —  注意事项和技巧

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5054]
* 原文链接：[Vue.js — Considerations and Tricks](https://blog.webf.zone/vue-js-considerations-and-tricks-fa7e0e4bb7bb)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/vue-js-considerations-and-tricks.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5088
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：3 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xingqiwu55555** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@xingqiwu55555 棒极啦 :tada:
