### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by Jerry-FD** [xitu/gold-miner#5063]
- 原文链接：https://overreacted.io/why-isnt-x-a-hook/
- 简要介绍：Dan Abramov.最新文章，作者针对社区中常出现的关于react - hook的问题：xxx为什么不是一个hook，做出了简明分析和思考。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢您的推荐，已发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
