### ISSUE TITLE
X 为啥不是 hook?

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5068]
* 原文链接：[Why Isn’t X a Hook?](https://overreacted.io/why-isnt-x-a-hook/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-isnt-x-a-hook.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5082
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * 译者推荐：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Jerry-FD** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Jerry-FD 棒极啦 :tada:
