### ISSUE TITLE
Vue Router 实战手册

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5073]
* 原文链接：[Vue Router — The Missing Manual](https://blog.webf.zone/vue-router-the-missing-manual-ce51c21430b0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/vue-router-the-missing-manual.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5097
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xutaogit** [comment]
翻译认领。@leviding

**Comment by fanyijihua** [comment]
@xutaogit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5097
