### ISSUE TITLE
HTTP/2 常见问题解答

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5074]
* 原文链接：[HTTP/2 Frequently Asked Questions](https://http2.github.io/faq/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/http-2-frequently-asked-questions.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5094
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7.5-8.5 分
  * 校对积分：1.5-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@leviding Markdown 文件链接挂了

**Comment by YueYongDev** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@YueYongDev 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5094
