### ISSUE TITLE
谷歌搜索操作符大全（包含 42 个高级操作符）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5076]
* 原文链接：[Google Search Operators: The Complete List (42 Advanced Operators)](https://ahrefs.com/blog/google-advanced-search-operators/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/google-advanced-search-operators.md)
  * PR 地址：
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cdpath** [comment]
这篇好水哦 我来吧 😂

**Comment by leviding** [comment]
@cdpath 好滴 😂

**Comment by leviding** [comment]
@cdpath Hello，这篇翻译的怎么样啦～

**Comment by fanyijihua** [comment]
PR 地址：#5167
