### ISSUE TITLE
2019 年翻译计划礼物清单由你来定！快来推荐你喜欢的礼物并投票吧 👏

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5080]
Hello 亲爱的译者们 🎉

新年新气象，翻译计划决定更新 2019 年礼物列表，欢迎大家将你想要的（并且大家也会想要的）礼物推荐到本 issue 下，包括礼物名称和图片。

如果你喜欢这个礼物，就在对应的消息下点个赞 👍
如果你不喜欢这个礼物，就在对应的消息下点个 👎 

**大家的推荐和点赞，决定着 2019 年翻译计划的礼物清单喔** 😎 

---

掘金周边：

- 掘金鼠标垫
- 掘金水杯
- 掘金 T 恤
- 掘金套头衫
- 掘金限量手机壳
- 掘金笔记本
- 掘金纪念币/虚拟比特币

---

GitHub 周边：

- GitHub Octoplush 玩偶
- GitHub Activity Book

---

Google 周边：

- Google 手提包
- Google DIY 纸板音响
- Google 鲁班锁

---

其他：

- 树莓派 3 官方套餐

**Comment by leviding** [comment]
大 Enter 键！

<img width="773" alt="wx20190130-201507 2x" src="https://user-images.githubusercontent.com/26959437/51982965-73709180-24d2-11e9-90e6-a87c1f44e7ac.png">

**Comment by leviding** [comment]
怎么能缺了小黄鸭呢

![image](https://user-images.githubusercontent.com/26959437/51983190-03164000-24d3-11e9-9a59-b851acea0757.png)

**Comment by zhusimaji** [comment]
前排围观，先占个坑

**Comment by leviding** [comment]
惨叫鸡怎么样

![image](https://user-images.githubusercontent.com/26959437/51983309-4e305300-24d3-11e9-8f29-de44e733f277.png)

**Comment by Starriers** [comment]
腾讯会员 优酷会员 爱奇艺会员 月/年 都行

**Comment by Starriers** [comment]
纪梵希 口红一支

**Comment by Starriers** [comment]
[白色恋人 巧克力](https://item.taobao.com/item.htm?id=535604677849&ali_refid=a3_430673_1006:1103426914:N:%E7%99%BD%E8%89%B2%E6%81%8B%E4%BA%BA%E5%B7%A7%E5%85%8B%E5%8A%9B%E9%A5%BC%E5%B9%B2:06e7f12a6fc11c7b0b04df3663f93c24&ali_trackid=1_06e7f12a6fc11c7b0b04df3663f93c24&spm=a2e15.8261149.07626516002.1)

**Comment by Starriers** [comment]
[GODIVA歌帝梵巧克力](https://godiva.tmall.com/?spm=a220o.1000855.w5001-15372947712.2.45d018ddDGZ48j&scene=taobao_shop)

**Comment by TUARAN** [comment]
[金猪存钱罐](https://item.jd.com/40356182509.html) 现在都不流行存钱了...

**Comment by CoolRice** [comment]
[米家 LED 智能台灯](https://www.mi.com/mjsmartlamp/)

![](https://c1.mifile.cn/f/i/16/chain/mjsmartlamp/mj-leddeng1-v2.jpg)

**Comment by CoolRice** [comment]
[小米极简都市双肩包](https://item.mi.com/1154400038.html?cfrom=search)

![](https://i8.mifile.cn/a1/T1a3DvB7hv1RXrhCrK.jpg)

**Comment by CoolRice** [comment]
[米家声波电动牙刷](https://www.mi.com/electric-toothbrush/)
![](https://item.mi.com/1172500006.html)

**Comment by TobiasLee** [comment]
Kindle  盖泡面神器 😂😂
[入门版](https://www.amazon.cn/gp/product/B0184OCR9A/ref=s9_acss_bw_cg_kindlemc_9a1_w?pf_rd_m=A1U5RCOVU0NYF2&pf_rd_s=merchandised-search-1&pf_rd_r=E2NDW65H03QG6SGZ0RBP&pf_rd_t=101&pf_rd_p=6212d17d-ef69-4432-8838-1ba2f84147b1&pf_rd_i=1993419071)
[PaperWhite](https://www.amazon.cn/dp/B07746N2J9/ref=pd_rhf_se_s_cp_0_1?_encoding=UTF8&pd_rd_i=B07746N2J9&pd_rd_r=2869d60c-534c-4648-b629-dafc7e445993&pd_rd_w=1ED49&pd_rd_wg=kCNg0&psc=1&refRID=W7KQENFKK7FRMV5GC3CZ)

**Comment by DG-King** [comment]
女装一套？

**Comment by zhongdeming428** [comment]
掘金小册，可以来几波~

**Comment by gongshun** [comment]
阿里云服务器？？？

**Comment by calpa** [comment]
Bilibili 大会员

**Comment by ssshooter** [comment]
谷歌 play 充值卡

**Comment by Ivocin** [comment]
微信读书无限卡：
月卡、季卡、年卡

**Comment by leviding** [comment]
经过大家推荐以及投票，暂定增加如下礼品：

- 大 Enter 键
- 小黄鸭
- 米家 LED 智能台灯
- 掘金小册 5 折优惠码
- 亚马逊礼品卡（待商讨）
- Kindle PaperWhite（待商讨）

欢迎大家继续提意见和建议 🎁

**Comment by newraina** [comment]
网易蜗牛读书时间礼品卡

**Comment by GpingFeng** [comment]
实体书，提供书名即可。所需具体的积分可以根据价格区间来决定。

**Comment by leviding** [comment]
实体书，需要是受众广的那种。因为译者比较多，兑换礼物也比较多，只能进行礼品囤货。如果是单人兑换，然后分次报销，流程上过于繁琐，无法执行。

**Comment by ANWSY** [comment]
实体书

**Comment by haiyang-tju** [comment]
[Powerbeats3 Wireless ](https://www.beatsbydre.com/cn/earphones/powerbeats3-wireless)
![](https://raw.githubusercontent.com/haiyang-tju/images-gallery/master/imgs/%E6%97%A0%E6%A0%87%E9%A2%98.png)

**Comment by Gavin-Gong** [comment]
> @Gavin-Gong Kindle unlimited 充值码，是不是指的充值卡？
> 
> ![image](https://user-images.githubusercontent.com/26959437/52032428-e07c3980-255b-11e9-9980-846985438b5b.png)

@leviding 我记差了，刚看了一圈 Kindle unlimited  没在官方找到这个购买激活码的地方，好像一般出自信用卡积分兑换 （，所以购入不是很合适，忽略我这个提议吧。

**Comment by leviding** [comment]
> 也可以是这样的
> [DDJ 无线运动蓝牙耳机](https://mall.jd.com/index-107870.html)
> 很漂亮~
> ![image](https://user-images.githubusercontent.com/23120674/52038114-23460d80-256c-11e9-8027-ed3f0b2becc3.png)

感谢推荐，很多大佬喜欢高品质耳机，太贵。便宜点的，喜欢的人又少 🤣

**Comment by leviding** [comment]
欢迎大家继续推荐和投票，翻译计划争取每个季度更新一次礼物列表 🎉

**Comment by wznonstop** [comment]
树莓派 3 官方套餐。。。这是我今年参与翻译的目标

**Comment by leviding** [comment]
@wznonstop 安排上了，等你来换 🎁

**Comment by razertory** [comment]
condom，为了程序员的终身大事

**Comment by SevenOutman** [comment]
> 怎么能缺了小黄鸭呢
> 
> ![image](https://user-images.githubusercontent.com/26959437/51983190-03164000-24d3-11e9-9a59-b851acea0757.png)

哈哈哈哈没有小黄鸭怎么写代码！

**Comment by huimingwu** [comment]
实体书，最好不限制语言的那种。提供书名即可。

**Comment by WangLeto** [comment]
红宝书怎么样
