### ISSUE TITLE
HTTP 简史

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5085]
* 原文链接：[Brief History of HTTP](https://hpbn.co/brief-history-of-http/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/brief-history-of-http.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5095
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6.5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jerryOnlyZRJ** [comment]
@leviding 翻译认领
