### ISSUE TITLE
关于 Yarn 和 npm 你所需要知道的一切

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5086]
* 原文链接：[Yarn vs npm: Everything You Need to Know](https://www.sitepoint.com/yarn-vs-npm/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/yarn-vs-npm-everything-you-need-to-know.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5115
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领～

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5115
