### ISSUE TITLE
React Native 中那些令我收获颇丰的痛点

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5087]
* 原文链接：[Things about React Native I found the hard (but rewarding) way](https://blog.usejournal.com/things-about-react-native-i-found-the-hard-but-rewarding-way-1557a87a0c8)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/things-about-react-native-i-found-the-hard-but-rewarding-way.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5145
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jerryOnlyZRJ** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@jerryOnlyZRJ 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5145
