### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by MrYuJ** [xitu/gold-miner#509]
你好，我是广州加一网络公司的前端工程师，有较好的英语基础，看到你们这个项目很感兴趣！非常想加入你们！
       博客http://blog.csdn.net/qq_26598303       刚入门的菜鸟都不好意思贴博客……见谅

**Comment by antonia0912** [comment]
@MrYuJ 好的 请加我微信 antonia0912 备注 github ID 我来拉你进译者群~
