### ISSUE TITLE
PWA 会取代原生移动应用吗？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5091]
* 原文链接：[Will PWAs Replace Native Mobile Apps?](https://www.smashingmagazine.com/2018/12/pwa-native-mobile-apps)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/pwa-native-mobile-apps.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5098
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：7.5-8.5 分
  * 校对积分：1.5-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jerryOnlyZRJ** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@jerryOnlyZRJ 棒极啦 :tada:
