### ISSUE TITLE
从 Instagram 上的故事和反馈机器学习中收获的一些经验

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5092]
* 原文链接：[Lessons Learned at Instagram Stories and Feed Machine Learning](https://instagram-engineering.com/lessons-learned-at-instagram-stories-and-feed-machine-learning-54f3aaa09e56)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/lessons-learned-at-instagram-stories-and-feed-machine-learning.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5129
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TrWestdoor** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@TrWestdoor 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5129
