### ISSUE TITLE
绘制路径：Android 中矢量图渲染

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5093]
* 原文链接：[Draw a Path: Rendering Android VectorDrawables](https://medium.com/androiddevelopers/draw-a-path-rendering-android-vectordrawables-89a33b5e5ebf)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/draw-a-path-rendering-android-vectordrawables.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5163
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xiaxiayang** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@xiaxiayang 棒极啦 :tada:
