### ISSUE TITLE
论数据流的扩展性

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5104]
* 原文链接：[Data Streaming Scalability](http://tutorials.jenkov.com/data-streaming/scalability.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/data-streaming-scalability.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5306
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by leviding** [comment]
@Starriers 翻译的怎么样啦

**Comment by leviding** [comment]
@Starriers 翻译的怎么样啦

**Comment by leviding** [comment]
超期过久，重新释放。

**Comment by Park-ma** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Park-ma 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5306
