### ISSUE TITLE
谷歌迈出了消除 URL 的第一步

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5106]
* 原文链接：[GOOGLE TAKES ITS FIRST STEPS TOWARD KILLING THE URL](https://www.wired.com/story/google-chrome-kill-url-first-steps/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/google-chrome-kill-url-first-steps.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5114
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jerryOnlyZRJ** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@jerryOnlyZRJ 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5114
