### ISSUE TITLE
HTML 一直是我们编译的目标 — 我们可以解决好它吗？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5108]
* 原文链接：[HTML is and always was a compilation target – can we deal with that?](https://christianheilmann.com/2019/01/28/html-is-and-always-was-a-compilation-target-can-we-deal-with-that/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/html-is-and-always-was-a-compilation-target-can-we-deal-with-that.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5149
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoderMing** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@CoderMing 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5149
