### ISSUE TITLE
Android Dev Summit 2018 应用（instant app 的总结 + 开源）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5117]
* 原文链接：[The Android Dev Summit 2018 app (instant app takeaways + open source)](https://medium.com/androiddevelopers/the-android-dev-summit-2018-app-instant-app-takeaways-open-source-e5b590f78f38)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-android-dev-summit-2018-app-instant-app-takeaways-open-source.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5137
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DevMcryYu** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@DevMcryYu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5137
