### ISSUE TITLE
[保护我们的 Git Repos，立刻停止“狐步舞”] 文章中存在错误 

### ISSUE THREAD

**Issue by sfmDev** [xitu/gold-miner#5118]
link:https://github.com/xitu/gold-miner/blob/master/TODO/stop-foxtrots-now.md
error: git log –first-parent
fix: git log –-first-parent

**Comment by leviding** [comment]
@sfmDev 已修改，十分感谢 👍

**Comment by leviding** [comment]
近期更新译者积分时，会给您奖励积分，欢迎常来翻译计划玩儿～
