### ISSUE TITLE
高效的 iOS 版本检测方法

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#512]
原文链接：[Efficient iOS Version Checking](https://pspdfkit.com/blog/2016/efficient-iOS-version-checking/)
掘金链接：[高效的 iOS 应用版本支持方法](http://gold.xitu.io/entry/578333340a2b580057725254)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/efficient-iOS-version-checking.md)
[校对地址](https://github.com/xitu/gold-miner/pull/545/files?diff=split)

翻译时间：5天
校对时间：3天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by DeadLion** [comment]
@antonia0912  认领

**Comment by antonia0912** [comment]
@DeadLion 好的 注意翻译时间限制喔

**Comment by DeadLion** [comment]
@antonia0912  翻译完成 [校对地址](https://github.com/xitu/gold-miner/pull/545)

**Comment by sqrthree** [comment]
@DeadLion 妥妥哒~~ 辛苦啦❤️

**Comment by MAYDAY1993** [comment]
申请认领校对

**Comment by siegeout** [comment]
认领校对

**Comment by antonia0912** [comment]
@MAYDAY1993 收到 校对地址见issue 的 description

**Comment by antonia0912** [comment]
@siegeout 只有掘金翻译机的译者才可以申请校对和翻译文章喔 不是译者的点[这里](https://github.com/xitu/gold-miner/blob/master/README.md)查看怎么发译者申请。

**Comment by wild-flame** [comment]
我来校对吧。

**Comment by siegeout** [comment]
我已经申请过了

**Comment by sqrthree** [comment]
@siegeout 群里的 `siegen` 是你么？那可以校对了哟~ 地址见上面的传送门哈~

@wild-flame 两个校对者已经够了哟~ O(∩_∩)O

**Comment by siegeout** [comment]
@sqrthree 对的~潜水的时间长了点 =。=

**Comment by antonia0912** [comment]
@siegeout 校对完了要留言哈  我们这边才好跟进进度

**Comment by siegeout** [comment]
好的，我校对完了~ @antonia0912

**Comment by MAYDAY1993** [comment]
校对完成 @antonia0912

**Comment by sqrthree** [comment]
妥妥哒~ @DeadLion 两位校对者都已经校对完了~ 可以来修改了哈
