### ISSUE TITLE
sphinx-doc 官方站(sphinx-doc.org) ~ 一款优秀的技术文档生成工具

### ISSUE THREAD

**Issue by imvkmark** [xitu/gold-miner#5120]
- 原文链接：http://www.sphinx-doc.org/en/master/
- 简要介绍：这是一款优秀的文档生成工具, sphinx 是一种文档工具，它可以令人轻松的撰写出清晰且优美的文档, 由 Georg Brandl 在BSD 许可证下开发, 并且它已成为Python项目首选的文档工具, 支持 rst 语法, 支持 markdown 技术文档, 我们自己的公司就是使用这个软件生成文档, 想要用好花费的时间精力会特别多, 尤其是英文文档. 希望可以立项. 我会作为翻译者参与.

**Comment by leviding** [comment]
十分感谢推荐，内容挺好的，只是与现阶段翻译计划的重点不同。文档翻译呢，首先需要比较容易转成 MarkDown，并且更倾向于其本身就有 markdown 文件。再者就是，文档翻译出来，看的人并不是特别多，分发有问题。

近期翻译计划在重点做 GitHub 的 Topic 和 Google 的 TensorFlow 文档汉化，暂时没有经历做其他文档。这个已经收藏下来了，希望以后有机会的时候可以做。

再次感谢推荐 ❤️
