### ISSUE TITLE
数据科学领域十大必知机器学习算法

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5122]
* 原文链接：[Ten Machine Learning Algorithms You Should Know to Become a Data Scientist](https://towardsdatascience.com/ten-machine-learning-algorithms-you-should-know-to-become-a-data-scientist-8dc93d8ca52e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/ten-machine-learning-algorithms-you-should-know-to-become-a-data-scientist.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5210
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnJiangLA** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@JohnJiangLA 棒极啦 :tada:

**Comment by leviding** [comment]
@JohnJiangLA 翻译的怎么样啦

**Comment by JohnJiangLA** [comment]
@leviding 今天能搞定

**Comment by fanyijihua** [comment]
PR 地址：#5210
