### ISSUE TITLE
如何利用 Webpack4 为你的 React.js 开发提速

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5123]
* 原文链接：[How to streamline your React.js development process using Webpack 4](https://medium.freecodecamp.org/how-to-develop-react-js-apps-fast-using-webpack-4-3d772db957e4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-develop-react-js-apps-fast-using-webpack-4.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5127
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jerryOnlyZRJ** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@jerryOnlyZRJ 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5127
