### ISSUE TITLE
用这些 iOS 技巧让你的 APP 性能更佳

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5124]
* 原文链接：[iOS Performance Tricks To Make Your App Feel More Performant](https://www.smashingmagazine.com/2019/02/ios-performance-tricks-apps/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/ios-performance-tricks-apps.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5139
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-8 分
  * 校对积分：1-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LoneyIsError** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@LoneyIsError 棒极啦 :tada:
