### ISSUE TITLE
好的与坏的，Swift 语言面面观（一）

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#513]
原文链接：[Good Swift, Bad Swift — Part 1](https://medium.com/@ksmandersen/good-swift-bad-swift-part-1-f58f71da3575)
掘金链接：[好的与坏的，Swift 语言面面观（一）](http://gold.xitu.io/entry/577e6956a341310061a9b04e)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/good-swift-bad-swift-part-1.md)

翻译时间：3天
校对时间：2天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zhangjd** [comment]
认领

**Comment by Zhangjd** [comment]
不需要两篇一起认领的吧?

**Comment by antonia0912** [comment]
@Zhangjd 先认领一篇吧~

**Comment by Jack-Kingdom** [comment]
校对申请 @antonia0912

**Comment by antonia0912** [comment]
@Jack-Kingdom 收到  老样子校对~
