### ISSUE TITLE
Swift：通过示例避免内存泄漏

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5132]
* 原文链接：[Swift: Avoiding Memory Leaks by Examples](https://hackernoon.com/swift-avoiding-memory-leaks-by-examples-f901883d96e5)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/swift-avoiding-memory-leaks-by-examples.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5142
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2-2.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LoneyIsError** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@LoneyIsError 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5142

**Comment by LoneyIsError** [comment]
@leviding 翻译校验完成了
