### ISSUE TITLE
介绍一款使用 Flutter 编写的 Flutter 组件、应用生成器

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5133]
* 原文链接：[Introducing: Flutter Widget-Maker, a Flutter App-Builder written in Flutter](https://medium.com/flutter-community/introducing-flutter-widget-maker-a-flutter-app-builder-written-in-flutter-231e8d959348)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/introducing-flutter-widget-maker-a-flutter-app-builder-written-in-flutter.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5140
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jerryOnlyZRJ** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@jerryOnlyZRJ 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5140

**Comment by MirosalvaSun** [comment]
认领校对

**Comment by MirosalvaSun** [comment]
校对认领 @leviding

**Comment by leviding** [comment]
@MirosalvaSun 到对应的 PR 下认领哈 https://github.com/xitu/gold-miner/pull/5140
