### ISSUE TITLE
浏览器中 CSS 支持指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5134]
* 原文链接：[A Guide To CSS Support In Browsers](https://www.smashingmagazine.com/2019/02/css-browser-support/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-guide-to-css-support-in-browsers.md)
  * PR 地址：#5336
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jerryOnlyZRJ** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@jerryOnlyZRJ 棒极啦 :tada:

**Comment by leviding** [comment]
@jerryOnlyZRJ

**Comment by leviding** [comment]
超期过久，重新释放。

**Comment by sunui** [comment]
@leviding  已经被翻译啦 https://www.infoq.cn/article/O*TADftw8KOhsfTArgiD

**Comment by huimingwu** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@huimingwu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5336
