### ISSUE TITLE
理解数据库分片

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5135]
* 原文链接：[Understanding Database Sharding](https://www.digitalocean.com/community/tutorials/understanding-database-sharding)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/understanding-database-sharding.md)
  * PR 地址：
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5.5-7 分
  * 校对积分：1-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@Romeo0906 棒极啦 :tada:
