### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by xingqiwu55555** [xitu/gold-miner#5138]
- 原文链接：https://overreacted.io/react-as-a-ui-runtime/
- 简要介绍：了解 react

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢推荐，有中文版了 🤣 
![image](https://user-images.githubusercontent.com/26959437/52892617-01d15c80-31cf-11e9-9a67-f1705504668b.png)
