### ISSUE TITLE
好的与坏的，Swift 语言面面观（二）

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#514]
原文链接：[Good Swift, Bad Swift — Part 2](https://medium.com/@ksmandersen/good-swift-bad-swift-part-2-d6daebf53a5)
掘金链接：[好的与坏的，Swift 语言面面观（二）](http://gold.xitu.io/entry/577e69f779bc44003297e707)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/good-swift-bad-swift-part-2.md)

翻译时间：3天
校对时间：2天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zheaoli** [comment]
唔，抢了

**Comment by antonia0912** [comment]
@Zheaoli 注意翻译时间限制喔~

**Comment by Zheaoli** [comment]
@antonia0912 羊姐姐初稿Over，请校对者来吧

**Comment by antonia0912** [comment]
@Zheaoli 吼~辛苦啦~

**Comment by owenlyn** [comment]
认领校对 @antonia0912

**Comment by owenlyn** [comment]
@sqrthree

**Comment by antonia0912** [comment]
@owenlyn 收到  老样子校对就可以了  这几天有问题先我和根号三同学一起at 这几天要带根号三熟悉一下业务 哈哈

**Comment by owenlyn** [comment]
@antonia0912 @sqrthree @Zheaoli 不好意思问一下哪里可以找到翻译好的文章...？

**Comment by sqrthree** [comment]
@owenlyn https://github.com/xitu/gold-miner/pull/536

**Comment by Zheaoli** [comment]
@sqrthree 根号三大胸弟
@antonia0912  皮裤羊姐姐
唔，可能有点排版问题= =我能查的地方基本OK了。。剩下就麻烦了QAQ

**Comment by owenlyn** [comment]
@sqrthree @Zheaoli 校对完啦，大牛翻译的特别好~膜拜

**Comment by Zheaoli** [comment]
@sqrthree 小哥，修改完成啦~
