### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by LoneyIsError** [xitu/gold-miner#5143]
原文地址：https://www.didierboelens.com/2019/01/futures---isolates---event-loop/
讲解flutter线程运行相关的

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by LoneyIsError** [comment]
这个人还有一篇文章：https://www.didierboelens.com/2018/06/widget---state---context---inheritedwidget/ 
掘金里面有翻译，但是感觉直翻的，不怎么样

**Comment by leviding** [comment]
感谢您的推荐，已发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
