### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by EdmondWang** [xitu/gold-miner#5144]
原文链接：https://codeburst.io/javascript-generator-yield-next-async-await-e428b0cb52e4
简要介绍：Javascript Generator, Async Await相关

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢您的推荐，已发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
