### ISSUE TITLE
Flutter 异步编程：Future、Isolate 和事件循环

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5146]
* 原文链接：[Futures - Isolates - Event Loop](https://www.didierboelens.com/2019/01/futures---isolates---event-loop/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/futures-isolates-event-loop.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5307
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jerryOnlyZRJ** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@jerryOnlyZRJ 棒极啦 :tada:

**Comment by leviding** [comment]
@jerryOnlyZRJ 翻译的怎么样啦

**Comment by leviding** [comment]
超期过久，重新释放。

**Comment by nanjingboy** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@nanjingboy 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5307
