### ISSUE TITLE
Widget - State - Context - InheritedWidget

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5147]
* 原文链接：[Widget - State - Context - InheritedWidget](https://www.didierboelens.com/2018/06/widget---state---context---inheritedwidget/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/widget-state-context-inheritedwidget.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5220
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：9-11 分
  * 校对积分：2-5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nanjingboy** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@nanjingboy 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5220

**Comment by hanxiansen** [comment]
@leviding 校对认领

**Comment by leviding** [comment]
@hanxiansen 请看 WIKI 里的译者教程，认领校对是在对应的 PR 下，本文现在校对已被认领完毕，请认领其他需要认领的任务。
