### ISSUE TITLE
Javascript - Generator-Yield/Next 和 Async-Await

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5148]
* 原文链接：[Javascript - Generator-Yield/Next & Async-Await](https://codeburst.io/javascript-generator-yield-next-async-await-e428b0cb52e4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/javascript-generator-yield-next-async-await.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5273
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iceytea** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@iceytea 棒极啦 :tada:

**Comment by iceytea** [comment]
这两天有点事情，预计要延期一天提交。 @leviding

**Comment by leviding** [comment]
好的不急，这几天文章也有点多，慢点没关系。

**Comment by leviding** [comment]
@iceytea 翻译的怎么样啦

**Comment by leviding** [comment]
@iceytea 翻译的怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#5273

**Comment by iceytea** [comment]
@leviding 抱歉，久等了。
