### ISSUE TITLE
提供隐私和过滤功能的 DNS 服务器

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5151]
* 原文链接：[DNS Servers That Offer Privacy and Filtering](https://danielmiessler.com/blog/dns-servers-you-should-have-memorized/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/dns-servers-you-should-have-memorized.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5180
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ScDadaguo** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@ScDadaguo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5180
