### ISSUE TITLE
Web 开发者需要了解的基础色彩理论

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5152]
* 原文链接：[Basic Color Theory for Web Developers](https://dev.to/nzonnenberg/basic-color-theory-for-web-developers-15a0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/basic-color-theory-for-web-developers.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5162
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5162
