### ISSUE TITLE
在 GO 语言中创建你自己 OAuth2 服务：客户端凭据授权流程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5153]
* 原文链接：[Build your Own OAuth2 Server in Go: Client Credentials Grant Flow](https://hackernoon.com/build-your-own-oauth2-server-in-go-7d0f660732c3)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/build-your-own-oauth2-server-in-go.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5218
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shixi-li** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@shixi-li 棒极啦 :tada:

**Comment by leviding** [comment]
@shixi-li 翻译的怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#5218

**Comment by shixi-li** [comment]
@leviding 不好意思这次迟了些，已提交 PR。
