### ISSUE TITLE
资助 ESLint 的未来

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5154]
* 原文链接：[Funding ESLint’s Future](https://eslint.org/blog/2019/02/funding-eslint-future)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/funding-eslint-future.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5161
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EdmondWang** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@EdmondWang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5161
