### ISSUE TITLE
💅 styled-components 背后的魔力

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5168]
* 原文链接：[The magic behind 💅 styled-components](https://mxstbr.blog/2016/11/styled-components-magic-explained/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/styled-components-magic-explained.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5172
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@WangLeto 来认领翻译吧

**Comment by WangLeto** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@WangLeto 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5172
