### ISSUE TITLE
翻译计划公开招募管理员团队

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5170]
Hello，各位译者们，光阴荏苒，日月如梭，转眼间翻译计划成立已经接近四年了。这四年来我们取得了一些成就，翻译了 1500 余篇文章以及很多优秀的项目。我们项目的每一颗星星都离不开每一位译者的辛苦和贡献。翻译计划和掘金团队在此非常感谢你的奉献。

伴随着翻译计划译者队伍越来越壮大，产出新文章速度也愈来愈快，我们也需要更多的译者和成员一起来协作管理和运营翻译计划。因此经过讨论，翻译计划决定要开疆扩土、广纳贤士啦。

**我们的计划目前是这样的：**

- 成立翻译计划管理组，负责商讨和探索翻译计划的各种事项。
- 针对目前已有分类建立不同的 team，负责该分类下译文的质量把控。
- 每位成员至少加入一个分类下的 team，每个 team 下有 1 ~ 2 位成员。
- 每篇译文（PR）在 merge 之前至少需要一个该分类下的 team 成员进行 approve。

**管理员的工作内容：**

- 推荐你所擅长分类的优质英文文章
- 协助将英文文章转为 MarkDown 文档，并发布翻译任务
- 对经过校对者校对后的文章，进行最终的 Review
- 与团队成员一起商讨翻译计划未来发展，优化管理流程

**我们期望你是这样的：**

- 在翻译计划翻译过 2 篇以上文章，熟悉我们的流程。
- 对翻译计划译文格式要求很熟悉，耐心细致，有责任心。
- 对 GitHub 的使用非常熟悉，翻译计划管理过程中 Web 端使用的较多。
- 有一定的空闲时间，能及时的处理翻译计划的事项，能够坚持做一件事，而不是半途而废。
- 强调：能够长期坚持很重要！！！

**在管理员团队的收获：**

- 获得翻译计划 GitHub Repo 的管理权限，加入到团队中来。
- 接触到更多优秀、有趣的人，一起做有趣、有意义的事。
- 公司周边及其他礼品优先获得。
- 大会及其他活动门票优先获得。
- @leviding 会与你分享交流翻译计划的管理流程，让你也掌握这一切。

如果你对我们翻译计划很感兴趣，同时又想参与社区协作的话，欢迎一起来将翻译计划做的更好啦。选择你擅长的分类，微信私聊 LeviDing，发送关键字：分类 + 管理员（例如 前端 + 管理员）。

如果你有任何建议或是意见，欢迎告诉我们。

**Comment by jellycsc** [comment]
特地过来帮三代目捧场来了😊

**Comment by Starriers** [comment]
前端 + 管理员

**Comment by calpa** [comment]
前端 + 管理员

**Comment by swants** [comment]
iOS + 管理员

**Comment by TUARAN** [comment]
🙌

**Comment by zhmhhu** [comment]
AI + 管理员

**Comment by slyrx** [comment]
AI + 管理员🙌

**Comment by kirinzer** [comment]
iOS + 管理员

**Comment by leviding** [comment]
Android、iOS、后端、设计和区块链小伙伴，欢迎来哈

**Comment by Fengziyin1234** [comment]
后端 + 管理员

**Comment by Blazarstar** [comment]
前端/安全+管理员

**Comment by leviding** [comment]
@Blazarstar 申请管理员，需要至少翻译过两篇，可能暂时不满足呢
