### ISSUE TITLE
教程 — 用 C 写一个 Shell

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5173]
* 原文链接：[Tutorial - Write a Shell in C](https://brennan.io/2015/01/16/write-a-shell-in-c/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/tutorial-write-a-shell-in-c.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5184
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nettee** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@nettee 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5184
