### ISSUE TITLE
修改 Git 错误的高明方法

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5174]
* 原文链接：[The Smart Ways to Correct Mistakes in Git](https://css-tricks.com/the-smart-ways-to-correct-mistakes-in-git/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-smart-ways-to-correct-mistakes-in-git.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5187
  * 文章分类：**教程**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5187
