### ISSUE TITLE
避免那些可恶的 "cannot read property of undefined" 错误

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5175]
* 原文链接：[Avoiding those dang cannot read property of undefined errors](https://css-tricks.com/%E2%80%8B%E2%80%8Bavoiding-those-dang-cannot-read-property-of-undefined-errors/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/avoiding-those-dang-cannot-read-property-of-undefined-errors.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5237
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Xcco** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Xcco 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5237
