### ISSUE TITLE
Swift 5 强制独占性原则

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5176]
* 原文链接：[Swift 5 Exclusivity Enforcement](https://swift.org/blog/swift-5-exclusivity/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/swift-5-exclusivity.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5186
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LoneyIsError** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@LoneyIsError 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5186
