### ISSUE TITLE
What Hooks Mean for Vue

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5177]
* 原文链接：[What Hooks Mean for Vue](https://css-tricks.com/what-hooks-mean-for-vue/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-hooks-mean-for-vue.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5251
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ivocin** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@Ivocin 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5251
