### ISSUE TITLE
Golang 数据结构：树

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5178]
* 原文链接：[Golang Datastructures: Trees](https://ieftimov.com/golang-datastructures-trees)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/golang-datastructures-trees.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5317
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-7 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by steinliber** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@steinliber 棒极啦 :tada:

**Comment by Fengziyin1234** [comment]
@steinliber  这篇文章翻译的怎么样啦？ 有没有什么需要帮助的地方～

**Comment by fanyijihua** [comment]
PR 地址：#5317
