### ISSUE TITLE
如何学习 CSS

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5179]
* 原文链接：[How To Learn CSS](https://www.smashingmagazine.com/2019/01/how-to-learn-css/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-learn-css.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5207
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6-7.5 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mcskiller** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@Mcskiller 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5207

**Comment by hanxiansen** [comment]
@leviding 校对认领
