### ISSUE TITLE
bug: 翻译错误

### ISSUE THREAD

**Issue by aladdin-add** [xitu/gold-miner#5185]
https://juejin.im/post/5c47232b6fb9a049f8199ee2

![image](https://user-images.githubusercontent.com/13050025/53150910-b7941500-35ec-11e9-9744-2698b859fca4.png)

**Comment by leviding** [comment]
@aladdin-add 可以给出修改建议吗，提 PR 最好。

**Comment by Fengziyin1234** [comment]
直接就 servers workers 吧 

我看网上的 Service Worker 都没有翻译，那么这个和它对应， 应该也不用翻译了

**Comment by leviding** [comment]
DONE，感谢二位。
