### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by vance-liu** [xitu/gold-miner#519]
你好，我叫vance，GUET信计专业毕。英语基础一般，喜欢一边撸代码一边撸英文文档，最近常访问的是Github/Meteor/react。这是我的博客vance.ren，博客暂时没有内容。希望能够加入，交流学习。

**Comment by antonia0912** [comment]
@maxwellblog 希望你能跟翻译计划共同成长  请加我微信 antonia0912 备注github ID 我来拉你进译者群
