### ISSUE TITLE
模块化系统中的 event.stopPropagation ()

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5192]
* 原文链接：[event.stopPropagation() in a modular system](https://www.moxio.com/blog/19/event-stoppropagation-in-a-modular-system)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/event-stoppropagation-in-a-modular-system.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5214
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Fengziyin1234** [comment]
@lsvih  翻译认领

**Comment by fanyijihua** [comment]
@Fengziyin1234 棒极啦 :tada:
