### ISSUE TITLE
2019 跟上 AI 的脚步：AI 和 ML 接下来会发生什么重要的事？

### ISSUE THREAD

**Issue by zhmhhu** [xitu/gold-miner#5196]
* 标题： Keeping up with AI in 2019: What is the next big thing in AI and ML?
* 原文链接：[Keeping up with AI in 2019](https://medium.com/thelaunchpad/what-is-the-next-big-thing-in-ai-and-ml-904a3f3345ef)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/keeping-up-with-ai-in-2019.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5309
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：8-10 分
* 校对积分：1.5-5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TUARAN** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@TUARAN 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5309
