### ISSUE TITLE
用 Rust 写一个微服务

### ISSUE THREAD

**Issue by noahziheng** [xitu/gold-miner#5198]
* 原文链接：[Writing a Microservice in Rust](http://www.goldsborough.me/rust/web/tutorial/2018/01/20/17-01-11-writing_a_microservice_in_rust/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/writing-a-microservice-in-rust.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5245
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：7-8 分
  * 校对积分：1-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nettee** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@nettee 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5245
