### ISSUE TITLE
认领 编写高质量的 Swift 代码

### ISSUE THREAD

**Issue by supersheep** [xitu/gold-miner#52]
票牛 iOS工程师，最近正在切swift，曾今做过GDG的翻译者，可以胜任翻译工作。

**Comment by Glowin** [comment]
你好，原来是GDG翻译组的朋友，欢迎欢迎。

这篇文章被@skcheer 在昨天被@iThreeKing 认领了 #36 ，你看看能不能选一个其他的文章呢？谢谢理解。

**Comment by Glowin** [comment]
你好，现在我挑选出来的文章也基本被认领完了，但是这个翻译计划还是会一直更新维护下去，我们很乐意邀请你加入并关注这个翻译计划，谢谢你的支持和理解。

**Comment by Glowin** [comment]
你好，现在挑选出来的文章已经被认领完了，但是这个翻译计划还是会一直更新维护下去，我新建了一个掘金翻译计划的微信群，并会在群里面通报翻译活动的最新进展，希望你能加一下我微信 Glowjiang，感谢你的支持和理解。

**Comment by Glowin** [comment]
@supersheep 早上好，我们又有一批新的文章等待你的翻译，欢迎来认领文章，谢谢啦。
