### ISSUE TITLE
移动应用设计新趋势

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#520]
原文链接：[Complexion Reduction: A New Trend In Mobile Design](https://medium.com/swarm-nyc/complexion-reduction-a-new-trend-in-mobile-design-cef033a0b978)
掘金链接：[移动应用设计新趋势](http://gold.xitu.io/entry/578498a37db2a20063f923a1)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/complexion-reduction-a-new-trend-in-mobile-design.md)
校对地址：[快来戳我](https://github.com/xitu/gold-miner/pull/540)

翻译时间：3天
校对时间：2天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by sakurajiang** [comment]
挺喜欢掘金，所以希望贡献一份力

**Comment by cyseria** [comment]
认！

**Comment by antonia0912** [comment]
@sakurajiang 首先要申请成为我们的译者才可以校对翻译文章喔  翻译计划怎么玩点[这里](https://github.com/xitu/gold-miner/blob/master/README.md)

**Comment by antonia0912** [comment]
@cyseria 请问校对过的是哪篇文章呢  只有校对过文章之后新译者才可以翻译的哈

**Comment by shixinzhang** [comment]
翻译或者校对~~ @antonia0912

**Comment by antonia0912** [comment]
@shixinzhang 请问之前校对的是哪篇文章呀  新加入的译者只有校对过文章之后才可以翻译喔

**Comment by shixinzhang** [comment]
@antonia0912 三羊我是你的万千粉丝之一 校对过 [[译] 深度讲解 Android 主题层级](https://gold.xitu.io/entry/576b9f912e958a005715c7a0?utm_source=gold-miner&utm_medium=readme&utm_campaign=github)

**Comment by antonia0912** [comment]
@shixinzhang 完美~不得不佩服你的欣赏能力~看在你这么会选偶像的份儿上  拿去翻译吧  注意翻译时间限制喔~

**Comment by shixinzhang** [comment]
@antonia0912 好的，谢谢亲 (づ￣3￣)づ

**Comment by cyseria** [comment]
@antonia0912 校对过[【译】让你的网站更炫酷的一些小tips ](https://gold.xitu.io/entry/577f402b79bc4400329db962)，然后我发现我来晚了一步，哭TAT ，能给个校对么

**Comment by shixinzhang** [comment]
@antonia0912 翻译完了，请校对同学校对吧~~

**Comment by shixinzhang** [comment]
@cyseria 直接来校对吧，现在也没人

**Comment by cyseria** [comment]
@shixinzhang 哈哈好，这就飞奔着去做校对

**Comment by sqrthree** [comment]
@cyseria  妥妥哒，校对地址请猛戳 https://github.com/xitu/gold-miner/pull/540

**Comment by wild-flame** [comment]
校对+1

**Comment by tanglie1993** [comment]
申请校对

**Comment by sqrthree** [comment]
@wild-flame 妥妥哒~ 校对地址在上面撒~
@tanglie1993 来的有点晚了哟，已经有两个人在校对了，下次换个快点的坐骑撒~~

**Comment by cyseria** [comment]
话说我好像在掘金上已经看到了可乐橙翻译了这篇文章的样子
http://colachan.com/post/3511 
@sqrthree @shixinzhang

**Comment by shixinzhang** [comment]
- - 晕额，2016-07-17 15:54，被抢先一步发布了

**Comment by shixinzhang** [comment]
@antonia0912 @sqrthree 怎么办？要夭折了吗 T.T
