### ISSUE TITLE
根据网络速度进行视频播放懒加载

### ISSUE THREAD

**Issue by noahziheng** [xitu/gold-miner#5200]
* 原文链接：[Lazy Loading Video Based on Connection Speed](https://medium.com/dailyjs/lazy-loading-video-based-on-connection-speed-e2de086f9095)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/lazy-loading-video-based-on-connection-speed.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5269
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by SHERlocked93** [comment]
@noahziheng 翻译认领

**Comment by fanyijihua** [comment]
@SHERlocked93 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5269
