### ISSUE TITLE
Java Service 加载器 和 spring Factories 加载器的比较

### ISSUE THREAD

**Issue by JackEggie** [xitu/gold-miner#5202]
* 原文链接：[Java Service Loader vs. Spring Factories Loader](
https://dzone.com/articles/java-service-loader-vs-spring-factories-loader)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/java-service-loader-vs-spring-factories-loader.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5272
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by HearFishle** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@HearFishle 棒极啦 :tada:
