### ISSUE TITLE
推荐一本手册：ASCIIdoctor手册

### ISSUE THREAD

**Issue by sweepingmonk123** [xitu/gold-miner#5203]
- 原文链接：https://asciidoctor.org/docs/user-manual/
- 简要介绍：通常，网络上的普通用户倾向于使用markdown语言来写文档，markdown的特点是简单，缺点是太过简单了，很多基础功能都没有。
ASCIIdoctor是我一直在使用的文档组件，可定制化程度特别高，且易于集成，具备很完善的工具链，非常适合用来处理大型的文档网站

**Comment by sweepingmonk123** [comment]
https://asciidoctor.cn/docs/

这个是当前比较全面的中文文档了，但内容很不完善

**Comment by leviding** [comment]
您好，翻译计划近期精力可能还不在这种地方，暂时还不做。翻译文档有一个很大的问题，翻译消耗的成本非常大，但是翻译好之后，分发效果并不好，看的人也不是特别多。

**Comment by leviding** [comment]
再次十分感谢您的推荐 ❤️

**Comment by sweepingmonk123** [comment]
好的，这样的话，当前翻译哪些内容比较好？

**Comment by leviding** [comment]
@sweepingmonk123 优质的英文文章，翻译产出快，分发好。
