### ISSUE TITLE
推荐英文文章 Distributed Transaction Processing: The XA Specification

### ISSUE THREAD

**Issue by Honwhy** [xitu/gold-miner#5215]
- 原文链接：http://pubs.opengroup.org/onlinepubs/009680699/toc.pdf
- 简要介绍：关于分布式事务处理，关于XA协议规范，关于两阶段提交（2PC）

**Comment by leviding** [comment]
内容很赞，但是论文这种很长，很学术的，暂时还不翻译哈，主要是翻译一些技术文章，感谢推荐。
