### ISSUE TITLE
MDC-104 Flutter：Material 高级组件（Flutter）

### ISSUE THREAD

**Issue by DevMcryYu** [xitu/gold-miner#5216]
* 原文链接：[MDC-104 Flutter: Material Advanced Components (Flutter)](https://codelabs.developers.google.com/codelabs/mdc-104-flutter/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/mdc-104-flutter.md)
  * PR 地址：#5350
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：8-9 分
  * 校对积分：1.5-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DevMcryYu** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@DevMcryYu 棒极啦 :tada:

**Comment by nanjingboy** [comment]
@DevMcryYu 大佬翻译的如何了？

**Comment by DevMcryYu** [comment]
这几天在准备实习的事情导致翻译进度有点跟不上，实在抱歉。

**Comment by nanjingboy** [comment]
@DevMcryYu 抱歉，翻译超时超过了7天，本文翻译将重新释放文章于其他译者。

**Comment by DevMcryYu** [comment]
翻译好了可是....
@nanjingboy

**Comment by nanjingboy** [comment]
@DevMcryYu 你应该可以再次认领的吧。@leviding 对吧？

**Comment by DevMcryYu** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@DevMcryYu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5350

**Comment by DevMcryYu** [comment]
> @DevMcryYu 你应该可以再次认领的吧。@leviding 对吧？

感谢~
