### ISSUE TITLE
申请加入志愿者计划

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#522]
从一开始就在关注掘金，很是喜欢掘金的产品，一直以来也很都希望能够参与其中。这次看到志愿者招募，当然要马上报名啦。

😂 要不是人不在北京，早跑去参加面试了。

嗯。。申请表要认真写，怎么个认真法捏 [埋头苦思]

我先对照下要求好了~

* 至少翻译过 3 篇文章

    嗯，这个我得承认，目前来说只翻译过两篇文章，但是参与校对了 6 篇文章，希望能够中和一下 ^_^

* 无比无比的熟练 Git 以及时帮助译者解决 issue 和 PR 冲突问题

    2014 年 9 月加入 Github，但是对于 Git 已经有 2 年以上的使用经验。

* 逗比属性自带中二光环加分

    我会尽可能让他们开心的。(一言不合就表情包大战我会乱说？)

* 颜值高加分

    嗯。。做个志愿者还需要露脸么 _(:з」∠)_  (捂脸狂奔)

* 颜值高但是什么都不会你就不要来了，不认真的就不要来了，没责任感的就不要来了，不能持续发光发热达到 3 个月以上的你就不要来了……

    认真这种事情呢，说是很难说的清楚的，不过精心的你一定会发现，我把招募条件复制过来之后顺手把排版调整了下，比如英文关键字的大小写和空格。^_^

    至于『持续发光发热达到 3 个月以上』，接下来的时间我有大量的空闲时间来做这些事，因为马上就是一个自由职业者了。

最后，希望能够通过审核。O(∩_∩)O~

**Comment by antonia0912** [comment]
@sqrthree  给你打99分~晚点联系你思密达~
