### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by CoderMing** [xitu/gold-miner#5225]
- 原文链接：https://blog.sessionstack.com/how-javascript-works-inside-the-v8-engine-5-tips-on-how-to-write-optimized-code-ac089e62b12e
- 简要介绍：JavaScript 是如何运行的：深入 V8 引擎内部及优化代码的 5 个技巧

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
本文由 @CoderMing 翻译

**Comment by leviding** [comment]
Hello，这篇文章之前翻译计划已经翻译过了哈
https://github.com/xitu/gold-miner/blob/master/TODO/how-javascript-works-inside-the-v8-engine-5-tips-on-how-to-write-optimized-code.md
