### ISSUE TITLE
制定良好的路线图：产品负责人的六个实施步骤

### ISSUE THREAD

**Issue by pmwangyang** [xitu/gold-miner#5226]
* 原文链接：[Creating Good Roadmaps: 6 Practical Steps for Product Leaders](https://www.mindtheproduct.com/2018/02/creating-good-roadmaps-6-practical-steps-product-leaders/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/creating-good-roadmaps-6-practical-steps-product-leaders.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5527
  * 文章分类：**产品**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
---
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Jerry-FD** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Jerry-FD 棒极啦 :tada:

**Comment by Fengziyin1234** [comment]
@Jerry-FD   大佬，翻译进度如何，有没有什么需要帮助哒～

**Comment by leviding** [comment]
@Jerry-FD 翻译的怎么样啦？

**Comment by noahziheng** [comment]
@Jerry-FD 翻译的进度如何，翻译已到时限了哟，如果不能及时完成翻译，可能会被取消翻译资格～

**Comment by JackEggie** [comment]
翻译超期，重新释放。

**Comment by QiaoN** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@QiaoN 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5527
