### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by MAYDAY1993** [xitu/gold-miner#523]
你好，
我是一名前端开发 英语听说读写熟练 经常在google和so 上搜开发中遇到的问题 所以阅读相关领域的技术文章也能看懂 国外的有些技术分享其实已经能解决我们遇到的问题了 结果一看 这问题人家几年前就提出了 工作中也遇到了一些不具备基本的用英语搜索答案的人 不会翻墙只靠百度没什么干货。我关注掘金翻译一年多了  看到很多干货 希望成为其中的一员 为更多的人 提高阅读效率 毕竟国人看英文资料和看汉语的侧重点不同 。

**Comment by antonia0912** [comment]
@MAYDAY1993 欢迎来到翻译计划family 请加我微信 antonia0912 备注github ID 我来拉你进译者群  PS. 掘金翻译计划到目前为止才开始了半年多哈哈哈
