### ISSUE TITLE
我是怎么最终玩转了 Vue 的作用域插槽

### ISSUE THREAD

**Issue by TUARAN** [xitu/gold-miner#5231]
* 原文链接：[How I finally got my head around Scoped Slots in Vue](https://medium.com/@ross_65916/how-i-finally-got-my-head-around-scoped-slots-in-vue-c37238d4d4cc)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-i-finally-got-my-head-around-scoped-slots-in-vue.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5328
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shixi-li** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@shixi-li 棒极啦 :tada:

**Comment by nanjingboy** [comment]
@shixi-li 大佬翻译的如何了？

**Comment by shixi-li** [comment]
@nanjingboy 抱歉，这段时间我个人事情太多了。今明两天内肯定翻译完毕。

**Comment by fanyijihua** [comment]
PR 地址：#5328

**Comment by xionglong58** [comment]
认领校对

**Comment by xionglong58** [comment]
@fanyijihua 认领校对

**Comment by leviding** [comment]
@xionglong58 在对应的 PR 下认领
