### ISSUE TITLE
Why UX and UI should remain separate

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5232]
* 原文链接：[Why UX and UI should remain separate](https://uxdesign.cc/why-ux-and-ui-should-remain-separate-7d6e3addb46f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-ux-and-ui-should-remain-separate.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5244
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mirosalva** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Mirosalva 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5244
