### ISSUE TITLE
如何用 Python 从零开始构建你自己的神经网络

### ISSUE THREAD

**Issue by zhmhhu** [xitu/gold-miner#5233]
* 原文链接：[How to build your own Neural Network from scratch in Python](https://towardsdatascience.com/how-to-build-your-own-neural-network-from-scratch-in-python-68998a08e4f6)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-build-your-own-neural-network-from-scratch-in-python.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5287
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间： 4  天
  * 校对时间： 1 天
  * 翻译积分： 4 分
  * 校对积分：1-2  分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JackEggie** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@JackEggie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5287
