### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by mnikn** [xitu/gold-miner#5235]
* 原文链接：
[http://teropa.info/blog/2015/03/02/change-and-its-detection-in-javascript-frameworks.html](http://teropa.info/blog/2015/03/02/change-and-its-detection-in-javascript-frameworks.html)
* 简要介绍：
简要概括了前端框架的更新策略。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by kezhenxu94** [comment]
多谢推荐 @mnikn 原文已有[译文](https://www.jianshu.com/p/f672cbd98a14)
