### ISSUE TITLE
数字产品为人们授权的时代已来

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5239]
* 原文链接：[It’s Time for Digital Products to Start Empowering Us](https://medium.com/s/user-friendly/the-future-of-digital-product-design-is-about-human-empowerment-6a025bc330a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-future-of-digital-product-design-is-about-human-empowerment.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5295
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mirosalva** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Mirosalva 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5295
