### ISSUE TITLE
掘金翻译计划译者申请－墨筝

### ISSUE THREAD

**Issue by NealST** [xitu/gold-miner#524]
你好，我是美丽联合集团－蘑菇街－无线应用电商基础团队的前端工程师，个人拥有非常好英文水平，平时阅读英文技术文档毫无压力。以前在人人公司实习时为团队翻译了jqueryUI的全部英文技术文档。微信公众号shFED,里面也有以前自己写的英文文章http://mp.weixin.qq.com/s?__biz=MzI2NTA3ODc3NQ==&tempkey=%2BaqojuMNoGGhVb6%2BXOBGEW7X8gmDC73XqUTNkhF9YAcUm5jEjuYx7SnCPO7Sjt9EOiTjoekzqLYInxvln505F3D8w0QpMFvZRFIMZqdU9qXUeCrZRCwODokghYQjBa%2FsIo51ekgG1bVI1a%2FBaH2f4Q%3D%3D&#rd。我对技术翻译非常有兴趣，希望能与大家一起工作学习，分享新知识和见解。我的微信号longmaost

**Comment by antonia0912** [comment]
@NealST 欢迎来到翻译计划family 请加我微信 antonia0912 备注github ID 我来拉你进译者群
