### ISSUE TITLE
用长短期记忆网络预测股票市场（使用 Tensorflow）

### ISSUE THREAD

**Issue by slyrx** [xitu/gold-miner#5243]
* 原文链接：[Using LSTMs For Stock Market Predictions (Tensorflow)
](https://towardsdatascience.com/using-lstms-for-stock-market-predictions-tensorflow-9e83999d4653)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/using-lstms-for-stock-market-predictions-tensorflow.md)
* PR 地址：#5314
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：7.5-9 分
* 校对积分：1.5-4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Qiuk17** [comment]
翻译认领 @levding

**Comment by fanyijihua** [comment]
@Qiuk17 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5314
