### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by AceLeeWinnie** [xitu/gold-miner#5246]
- 原文链接：https://towardsdatascience.com/the-most-famous-data-visualisation-ever-and-what-we-can-learn-from-it-abcdfa772548
- 简要介绍：从著名「拿破仑东征图」到「可视化设计原理」，浅谈如何设计高效可视化作品。

**Comment by fanyijihua** [comment]
PR 地址：#5247

**Comment by leviding** [comment]
感谢您的推荐，已发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
感谢管理员 ❤️
