### ISSUE TITLE
从著名数据数据可视化中我们可以学到什么

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5248]
* 原文链接：[The most famous data visualisation ever and what we can learn from it](https://towardsdatascience.com/the-most-famous-data-visualisation-ever-and-what-we-can-learn-from-it-abcdfa772548)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-most-famous-data-visualisation-ever-and-what-we-can-learn-from-it.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5278
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by AceLeeWinnie** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@AceLeeWinnie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5278
