### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zhew117** [xitu/gold-miner#525]
公司/学校:万家热线
工作内容/专业:安卓开发
英语水平:还行,北美一年工作经验,可满足基本使用
常浏览的国外网站:https://techcrunch.com/ https://www.reddit.com/r/programming/
有无翻译经验:在博客有翻译一点点
个人博客:http://zhew117.github.io/

**Comment by antonia0912** [comment]
@zhew117 欢迎来到翻译计划family 请加我微信 antonia0912 备注github ID 我来拉你进译者群
