### ISSUE TITLE
Java 和 etcd：因为 jetcd 最终走到了一起

### ISSUE THREAD

**Issue by JackEggie** [xitu/gold-miner#5252]
* 原文链接：[Java and etcd: together at last, with jetcd](https://coreos.com/blog/java-and-etcd-together-with-jetcd)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/java-and-etcd-together-at-last-with-jetcd.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5441
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mingxing47** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@mingxing47 棒极啦 :tada:

**Comment by JackEggie** [comment]
@mingxing47 大佬翻译的怎么样啦？

**Comment by mingxing47** [comment]
@JackEggie 这两天异常加班多,周末搞定~

**Comment by JackEggie** [comment]
@mingxing47 大佬翻译的怎么样啦？有没有什么需要帮助哒？

**Comment by mingxing47** [comment]
这个周末一定搞定

**Comment by honwhy** [comment]
原文中的go get命令安装etcd已经不能正常运行了，
更新的安装文档请参考，https://github.com/etcd-io/etcd/blob/master/Documentation/dl_build.md

**Comment by noahziheng** [comment]
@mingxing47 翻译的进度如何，翻译快到时限了哟，如果两天后不能及时完成翻译，可能会被取消翻译资格～

**Comment by mingxing47** [comment]
明天上交哈~最近事情太多了不好意思

**Comment by mingxing47** [comment]
翻译完成
