### ISSUE TITLE
iOS：如何构建具有多种 Cell 类型的表视图

### ISSUE THREAD

**Issue by kirinzer** [xitu/gold-miner#5258]
* 原文链接：[iOS: How to build a Table View with multiple cell types](https://medium.com/@stasost/ios-how-to-build-a-table-view-with-multiple-cell-types-2df91a206429)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/ios-how-to-build-a-table-view-with-multiple-cell-types.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5298
* 文章分类：**iOS**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4.5-5.5 分
* 校对积分：1-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LoneyIsError** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@LoneyIsError 棒极啦 :tada:

**Comment by LoneyIsError** [comment]
@kirinzer @fanyijihua 这个几天几分？

**Comment by kirinzer** [comment]
@LoneyIsError 时间和积分已经更新上去啦~\(≧▽≦)/~

**Comment by fanyijihua** [comment]
PR 地址：#5298

**Comment by kirinzer** [comment]
@LoneyIsError tableView 不需要翻译，正文内容也修改一下哦
