### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by EdmondWang** [xitu/gold-miner#5259]
* 原文链接：https://medium.com/front-end-weekly/javascript-whats-new-in-ecmascript-2018-es2018-17ede97f36d5
* 介绍：ES2018 新特性
* 分类：前端

**Comment by JackEggie** [comment]
感谢推荐 @EdmondWang 原文已有[译文](https://www.zcfy.cc/article/javascript-what-s-new-in-ecmascript-2018-es2018)

**Comment by EdmondWang** [comment]
@JackEggie 谢谢告知。请问以后我自己怎么可以知道文章已经被翻译过了？

**Comment by JackEggie** [comment]
@EdmondWang 目前管理员使用的一般检查方式为：Google 搜索关键词组合 [原文 翻译 英文文章标题]
