### ISSUE TITLE
在 JSX 代码中可以加入 console.log 吗？

### ISSUE THREAD

**Issue by noahziheng** [xitu/gold-miner#5262]
* 原文链接：[Can you console.log in JSX?](https://medium.com/javascript-in-plain-english/can-you-console-log-in-jsx-732f2ad46fe1)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/can-you-console-log-in-jsx.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5288
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领...🤣

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5288
