### ISSUE TITLE
TSLint in 2019

### ISSUE THREAD

**Issue by Ivocin** [xitu/gold-miner#5264]
* 原文链接：[TSLint in 2019](https://medium.com/palantir/tslint-in-2019-1a144c2317a9)
  * Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/tslint-in-2019.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5292
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LucaslEliane** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@LucaslEliane 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5292
