### ISSUE TITLE
在 swift 中使用 errors 作为控制流

### ISSUE THREAD

**Issue by swants** [xitu/gold-miner#5266]
* 原文链接：[Using errors as control flow in Swift](https://www.swiftbysundell.com/posts/using-errors-as-control-flow-in-swift)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/using-errors-as-control-flow-in-swift.md)
  * PR 地址：#5375
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by swants** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@swants 棒极啦 :tada:

**Comment by swants** [comment]
最近离职入职，事情比较多，有点延期， 译文这两天就出炉。🙏

**Comment by fanyijihua** [comment]
PR 地址：#5375
