### ISSUE TITLE
用 Apache Shiro 来强化一个 Spring Boot 应用

### ISSUE THREAD

**Issue by kezhenxu94** [xitu/gold-miner#5268]
* 原文链接：[Protecting a Spring Boot App With Apache Shiro](https://dzone.com/articles/protecting-a-spring-boot-app-with-apache-shiro)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/protecting-a-spring-boot-app-with-apache-shiro.md)
  * PR 地址：#5343
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lihanxiang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lihanxiang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5343
