### ISSUE TITLE
用 Swift 以及 AI 创建你自己的 iOS 游戏

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#527]
原文链接：[Build Tic Tac Toe with AI Using Swift](https://medium.com/swift-programming/build-tic-tac-toe-with-ai-using-swift-25c5cd3085c9)
掘金链接：[用 Swift 以及 AI 创建你自己的 iOS 游戏](http://gold.xitu.io/entry/578486dd7db2a20063f8284b)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/build-tic-tac-toe-with-ai-using-swift.md)
[校对地址](https://github.com/xitu/gold-miner/pull/533/files?diff=split)
翻译时间：5天
校对时间：4天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by yifili09** [comment]
@antonia0912 求翻译。

**Comment by antonia0912** [comment]
@yifili09 新加入的译者只有校对过文章才可以翻译的喔 请问你校对的是哪篇文章呢

**Comment by yifili09** [comment]
@antonia0912 https://github.com/xitu/gold-miner/pull/506

**Comment by antonia0912** [comment]
@yifili09 原来是这个  因为还没有分享到掘金 所以就没有记录  不过就给你破例一次啦  拿去翻译吧 注意时间限制喔

**Comment by yifili09** [comment]
@antonia0912 羊羊羊 心好， 人也漂亮！ 😃

**Comment by yifili09** [comment]
@antonia0912 #533 需要校对。

**Comment by antonia0912** [comment]
@yifili09 收到 辛苦啦  给效率点赞

**Comment by yifili09** [comment]
@antonia0912 嘿嘿， 最近很闲，需要给自己找点事情干。。 😂 😂

**Comment by jamweak** [comment]
这么棒的文章，必须要申个校！！

**Comment by antonia0912** [comment]
@jamweak 好的  校对地址见issue的description

**Comment by cyseria** [comment]
申个校

**Comment by antonia0912** [comment]
@cyseria 好的 校对地址见issue的description

**Comment by cyseria** [comment]
@yifili09 校对完毕 ٩꒰ ⑅>∀<⑅ ꒱۶﻿

**Comment by jamweak** [comment]
@yifili09 @antonia0912 校对完毕

**Comment by yifili09** [comment]
@cyseria @jamweak  辛苦辛苦。


@antonia0912 修改已提交

- [x] 增加了校对同学的信息
- [x] 已按校对同学的建议进行了修改
