### ISSUE TITLE
如何在 Swift 5 中使用 Result

### ISSUE THREAD

**Issue by swants** [xitu/gold-miner#5271]
* 原文链接：[How to use Result in Swift 5](https://www.hackingwithswift.com/articles/161/how-to-use-result-in-swift)
  * Markdown文件：[https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-use-result-in-swift.md](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-use-result-in-swift.md)
  * PR 地址：#5391
  * 文章分类：**iOS**
  ---
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5.5-6.5 分
  * 校对积分：1-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Bruce-pac** [comment]
申请翻译

**Comment by fanyijihua** [comment]
@Bruce-pac 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5391
