### ISSUE TITLE
负载性能

### ISSUE THREAD

**Issue by Fengziyin1234** [xitu/gold-miner#5279]
* 原文链接：[Performance Under Load](https://medium.com/@NetflixTechBlog/performance-under-load-3e6fa9a60581)
  * Markdown文件：[https://github.com/xitu/gold-miner/blob/master/TODO1/performance-under-load.md](https://github.com/xitu/gold-miner/blob/master/TODO1/performance-under-load.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5297
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ---
  * 翻译时间：3 天
  * 校对时间：1天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by WangLeto** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@WangLeto 棒极啦 :tada:
