### ISSUE TITLE
iOS 开源图形库 Core Plot 使用教程

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#528]
原文链接：[Core Plot Tutorial: Getting Started](https://www.raywenderlich.com/131985/core-plot-tutorial-getting-started)
掘金链接：[iOS 开源图形库 Core Plot 使用教程](http://gold.xitu.io/entry/577f42fc79bc4400329ddf32)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/core-plot-tutorial-getting-started.md)
校对地址：[传送门](https://github.com/xitu/gold-miner/pull/544/files)

翻译时间：5天
校对时间：4天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by llp0574** [comment]
@antonia0912 get，首翻奉献给这篇了！

**Comment by llp0574** [comment]
@antonia0912 markdown文件位置没对？

**Comment by antonia0912** [comment]
@llp0574 markdown文件已经改过来啦  注意翻译时间限制喔~

**Comment by llp0574** [comment]
@antonia0912 翻译完了，[校对地址](https://github.com/xitu/gold-miner/pull/544/files)在此。

**Comment by wild-flame** [comment]
申请校对

**Comment by sqrthree** [comment]
@wild-flame 抱歉哈，刚刚已经有两个人认领过了，他们速度太快 _(:з」∠)_
