### ISSUE TITLE
选择 Grid 还是 Flex？

### ISSUE THREAD

**Issue by Ivocin** [xitu/gold-miner#5282]
* 原文链接：[To Grid or to Flex?](https://css-irl.info/to-grid-or-to-flex/)
  * Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/to-grid-or-to-flex.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5289
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Reaper622** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@Reaper622 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5289
