### ISSUE TITLE
A Zero-Math Introduction to Markov Chain Monte Carlo Methods

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5284]
* 原文链接：[A Zero-Math Introduction to Markov Chain Monte Carlo Methods](https://towardsdatascience.com/a-zero-math-introduction-to-markov-chain-monte-carlo-methods-dcba889e0c50)
  * Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-zero-math-introduction-to-markov-chain-monte-carlo-methods.md)
  * PR 地址：
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6.5-7.5 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by lsvih** [comment]
@leviding 放弃这篇。。。在翻译的过程中发现已经有很好的译文了：https://mp.weixin.qq.com/s?__biz=MzI0ODcxODk5OA==&mid=2247491981&idx=2&sn=383e255853a944f2eb74feeda27d4a1b

QAQ

**Comment by lsvih** [comment]
https://www.jiqizhixin.com/articles/2017-12-24-6 这篇做的更好

**Comment by leviding** [comment]
@lsvih 辛苦了，close 了
