### ISSUE TITLE
Android 生命周期备忘录 — 第二部分：多 Activity

### ISSUE THREAD

**Issue by DevMcryYu** [xitu/gold-miner#5291]
* 原文链接：[The Android Lifecycle cheat sheet — part II: Multiple activities](https://medium.com/androiddevelopers/the-android-lifecycle-cheat-sheet-part-ii-multiple-activities-a411fd139f24)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/The-Android-Lifecycle-cheat-sheet-part-II-Multiple-activities.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5305
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@DevMcryYu Hello, where is the part I, can you give me the link of the issue.

**Comment by gs666** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@gs666 棒极啦 :tada:

**Comment by DevMcryYu** [comment]
> @DevMcryYu Hello, where is the part I, can you give me the link of the issue.

# 3052

**Comment by fanyijihua** [comment]
PR 地址：#5305
