### ISSUE TITLE
JSX 的替代方案

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5299]
* 原文链接：[Alternatives to JSX](https://blog.bloomca.me/2019/02/23/alternatives-to-jsx.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/alternatives-to-jsx.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5311
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5311
