### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by EternalSpring** [xitu/gold-miner#530]
学校：SCNU
公司：21CN
英语水平：六级
外国网站：http://docs.spring.io/spring/docs/3.2.16.RELEASE/spring-framework-reference/htmlsingle/
翻译经验：写过一些短篇文章，技术文章的翻译经验暂无。

**Comment by antonia0912** [comment]
@EternalSpring 欢迎来到翻译计划family 请加我微信 antonia0912 备注github ID 我来拉你进译者群

**Comment by cathymeow** [comment]
学校：Agnes Scott College
英语水平：在美国待了三年，GRE 335

**Comment by Glowin** [comment]
@cathymeow 你好，需要新开一个 issue 提交呢
