### ISSUE TITLE
正在消失的小型网站

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5300]
* 原文链接：[Small Websites Are Dying](https://blog.bloomca.me/2018/12/03/small-websites.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/small-websites-are-dying.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5316
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5316
