### ISSUE TITLE
Node.js 基础知识: 没有依赖关系的 Web 服务器

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5301]
* 原文链接：[Node.js Fundamentals: Web Server Without Dependencies](https://blog.bloomca.me/2018/12/22/writing-a-web-server-node.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/writing-a-web-server-node.md)
  * PR 地址：#5338
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mirosalva** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Mirosalva 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5338
