### ISSUE TITLE
如何使用 Phaser 3 和 TypeScript 在浏览器中构建一个简单的游戏

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5302]
* 原文链接：[How to build a simple game in the browser with Phaser 3 and TypeScript](https://medium.freecodecamp.org/how-to-build-a-simple-game-in-the-browser-with-phaser-3-and-typescript-bdc94719135)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-build-a-simple-game-in-the-browser-with-phaser-3-and-typescript.md)
  * PR 地址：#5399
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iceytea** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@iceytea 棒极啦 :tada:

**Comment by xionglong58** [comment]
校对认领 @fanyijihua

**Comment by JackEggie** [comment]
@iceytea 大佬翻译的怎么样啦？
