### ISSUE TITLE
Rust 语言案例研究：社区使得 Rust 成为 npm 的简单选择

### ISSUE THREAD

**Issue by JackEggie** [xitu/gold-miner#5304]
* 原文链接：[Rust Case Study: Community makes Rust an easy choice for npm](https://www.rust-lang.org/static/pdfs/Rust-npm-Whitepaper.pdf)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/rust-case-study-community-makes-rust-an-easy-choice-for-npm.md)
  * PR 地址：#5339
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by WangLeto** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@WangLeto 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5339
