### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by AceLeeWinnie** [xitu/gold-miner#5310]
- 原文链接：https://fideloper.com/hexagonal-architecture
- 简要介绍：领域驱动设计（DDD）的经典入门架构 - 六角架构

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by Fengziyin1234** [comment]
https://fideloper.com/hexagonal-architecture 有 security 问题啊。。

**Comment by leviding** [comment]
这文章属于什么分类？

**Comment by AceLeeWinnie** [comment]
没有架构分类的话可以放在后端里

**Comment by leviding** [comment]
赞 👍感谢您的推荐，近期发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分

**Comment by leviding** [comment]
sorry，刚看到这篇文章已经有很多译文了，所以就不翻译了，欢迎继续推荐。
