### ISSUE TITLE
线框图变得不那么重要了 — 好事啊！

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5313]
* 原文链接：[Wireframes are becoming less relevant — and that’s a good thing](https://medium.com/@seandexter1/wireframes-are-becoming-less-relevant-and-thats-a-good-thing-e66b30724a27)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/wireframes-are-becoming-less-relevant-and-thats-a-good-thing.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5357
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hanxiansen** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@hanxiansen 棒极啦 :tada:
