### ISSUE TITLE
推荐文章

### ISSUE THREAD

**Issue by SinanJS** [xitu/gold-miner#5315]
推荐一篇文章 ：TypeScript With Babel: A Beautiful Marriage
https://iamturns.com/typescript-babel/
主要讲使用 Babel 7的 TypeScript preset 来做 TypeScript 开发，并将两者结合的实践

**Comment by leviding** [comment]
感谢您的推荐，近日发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分

**Comment by leviding** [comment]
@xitu/fe-miners

**Comment by lsvih** [comment]
Create article via #5320
