### ISSUE TITLE
TypeScript 和 Babel：美丽的结合

### ISSUE THREAD

**Issue by noahziheng** [xitu/gold-miner#5321]
* 原文链接：[TypeScript With Babel: A Beautiful Marriage](https://iamturns.com/typescript-babel/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/typescript-with-babel-a-beautiful-marriage.md)
  * PR 地址：#5363
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zsky** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@zsky 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5363

**Comment by brilliantGuo** [comment]
@leviding 校对认领
