### ISSUE TITLE
为什么我用 JavaScript 来编写 CSS

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5324]
* 原文链接：[Why I Write CSS in JavaScript](https://mxstbr.com/thoughts/css-in-js/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-i-write-css-in-javascript.md)
  * PR 地址：#5340
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ivocin** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@Ivocin 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5340
