### ISSUE TITLE
在 Android 应用中使用矢量资源

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5325]
* 原文链接：[Using vector assets in Android apps](https://medium.com/androiddevelopers/using-vector-assets-in-android-apps-4318fd662eb9)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/using-vector-assets-in-android-apps.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5392
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@YueYongDev 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5392
