### ISSUE TITLE
转化通用安卓音乐播放器为 instant 应用

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5326]
* 原文链接：[Making the UAMP sample an instant app](https://medium.com/androiddevelopers/making-the-uamp-sample-an-instant-app-30c3f0a050af)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/making-the-uamp-sample-an-instant-app.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5346
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mirosalva** [comment]
翻译认领

**Comment by Mirosalva** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Mirosalva 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5346
