### ISSUE TITLE
数据流简介

### ISSUE THREAD

**Issue by JackEggie** [xitu/gold-miner#5329]
* 原文链接：[Data Streaming](http://tutorials.jenkov.com/data-streaming/index.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/data-streaming.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5358
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by steinliber** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@steinliber 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5358
