### ISSUE TITLE
连接数据流

### ISSUE THREAD

**Issue by JackEggie** [xitu/gold-miner#5331]
* 原文链接：[Joining Data Streams](http://tutorials.jenkov.com/data-streaming/joining-data-streams.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/joining-data-streams.md)
  * PR 地址：#5341
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by whatbeg** [comment]
翻译认领 @fanyijihua

**Comment by fanyijihua** [comment]
@whatbeg 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5341
