### ISSUE TITLE
Vue.js 和第三方 JavaScript 的逐渐集成

### ISSUE THREAD

**Issue by Ivocin** [xitu/gold-miner#5337]
* 原文链接：[Sliding In And Out Of Vue.js](https://www.smashingmagazine.com/2019/02/vue-framework-third-party-javascript/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/sliding-in-and-out-of-vue-js.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5378
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：9-11 分
  * 校对积分：2-5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LucaslEliane** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@LucaslEliane 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5377

**Comment by fanyijihua** [comment]
PR 地址：#5378
