### ISSUE TITLE
使用 Zopfli 优化 PNG 图像

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#534]
原文链接：[Using Zopfli to Optimize PNG Images](https://ariya.io/2016/06/using-zopfli-to-optimize-png-images)
掘金链接：[使用 Zopfli 优化 PNG 图像](https://gold.xitu.io/entry/5787036b79bc44005fb66f20)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/using-zopfli-to-optimize-png-images.md)

翻译时间：2天
校对时间：1天
翻译积分：3
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by cyseria** [comment]
认领 ~

**Comment by antonia0912** [comment]
@cyseria 好的  注意时间限制  @MAYDAY1993 下手晚了  心疼哈哈哈  下次吧  这次给cyseria翻译啦

**Comment by MAYDAY1993** [comment]
呜呜呜 等着看校对吧

**Comment by rccoder** [comment]
申请校对啦
