### ISSUE TITLE
了解“多态”JSON 数据的性能问题

### ISSUE THREAD

**Issue by Fengziyin1234** [xitu/gold-miner#5347]
* 原文链接：[Understanding a Performance Issue with “Polymorphic” JSON Data](https://medium.com/wolfram-developers/understanding-a-performance-issue-with-polymorphic-json-data-e7e4cd079be0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/understanding-a-performance-issue-with-polymorphic-json-data.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5440
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shixi-li** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@shixi-li 棒极啦 :tada:

**Comment by sunui** [comment]
@shixi-li 翻译的怎么样啦

**Comment by noahziheng** [comment]
@shixi-li 翻译的进度如何，翻译快到时限了哟，如果两天后不能及时完成翻译，可能会被取消翻译资格～

**Comment by shixi-li** [comment]
@noahziheng 好的，明天内翻译完毕

**Comment by fanyijihua** [comment]
PR 地址：#5440
