### ISSUE TITLE
Javascript 中最长的关键字序列长什么样子？

### ISSUE THREAD

**Issue by Fengziyin1234** [xitu/gold-miner#5348]
* 原文链接：[What's the longest keyword sequence in Javascript?](https://gist.github.com/lhorie/c0d9fd9b2aa215f4984f3ce1c8fd01bf)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/longest-keyword-sequence.md)
  * PR 地址：#5364
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xionglong58** [comment]
@Fengziyin1234 翻译认领

**Comment by fanyijihua** [comment]
@xionglong58 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5364
