### ISSUE TITLE
字体加载策略全面指南

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#535]
原文链接：[A COMPREHENSIVE GUIDE TO FONT LOADING STRATEGIES](https://www.zachleat.com/web/comprehensive-webfonts/)
掘金链接：[字体加载策略全面指南](https://gold.xitu.io/entry/5786f969165abd0067f7488f)
markdown文件：[文件位置](https://github.com/xitu/gold-miner/blob/master/TODO/comprehensive-webfonts.md)
校对地址：[传送门](https://github.com/xitu/gold-miner/pull/547/files)

翻译时间：3天
校对时间：2天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by yifili09** [comment]
@antonia0912  大致看了下，这作者太能写了。。  我要先下手为强。 🀄

**Comment by aleen42** [comment]
這個也太多積分了

**Comment by antonia0912** [comment]
@yifili09 ok 注意时间限制  @aleen42 233

**Comment by yifili09** [comment]
@aleen42  我一点都不懂字体是怎么渲染的，感觉好复杂。。

**Comment by antonia0912** [comment]
@yifili09 没关系  感觉搞不定可以换个人来翻译  没关系的

**Comment by aleen42** [comment]
@yifili09 幹吧爹~

**Comment by antonia0912** [comment]
@yifili09 要不要换人？ @aleen42 上？

**Comment by yifili09** [comment]
@antonia0912 哈哈，问题不大。

**Comment by yifili09** [comment]
@sqrthree @antonia0912 https://github.com/xitu/gold-miner/blob/master/TODO/comprehensive-webfonts.md

原文空空如也。

**Comment by sqrthree** [comment]
@yifili09 改好了，抱歉哈疏忽了 _(:з」∠)_

**Comment by yifili09** [comment]
@antonia0912 @sqrthree Pull request ready at #547.

**Comment by sqrthree** [comment]
@yifili09 好的~ 辛苦了哈~

**Comment by cyseria** [comment]
校对认领♥（ﾉ´∀`）

**Comment by sqrthree** [comment]
@cyseria 好的~ 老样子，走你~ ╭(′▽`)╯

**Comment by wild-flame** [comment]
校对认领。

**Comment by sqrthree** [comment]
@wild-flame  妥妥哒~~

**Comment by yifili09** [comment]
@wild-flame 前辈多多给意见。 😄

**Comment by wild-flame** [comment]
@yifili09 看了一遍，有一个比较大的问题所以单独在这里说一下。文章原文有这样一张图片，对应了文章里所有的小标题，刚好也是本文的纲要。所以，如果标题都译成中文了，一定要把这张图也译为中文才行，不然读者是完全看不懂的。当然另一个选择就是，把文中所有的小标题都保持英文原文不变。

![](https://www.zachleat.com/web/img/posts/comprehensive-webfonts/strategies.svg)
