### ISSUE TITLE
设计不会拯救世界

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5353]
* 原文链接：[Design Won't Save the World](https://medium.com/@hairyelefante/design-is-not-going-to-save-the-world-8985870471a5)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/design-is-not-going-to-save-the-world.md)
  * PR 地址：#5407
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：5.5-6.5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by QiaoN** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@QiaoN 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5407
