### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by honwhy** [xitu/gold-miner#5356]
- 原文链接：http://tobert.github.io/pages/als-cassandra-21-tuning-guide.html
- 简要介绍：关于Cassandra 2.1调优指南
JVM参数调优指南

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢推荐，就是这个太长了，不太合适。

**Comment by honwhy** [comment]
我觉得并不长，只是图片多了

**Comment by leviding** [comment]
嗯嗯，感谢推荐，文章其实很赞的，那我们收进来这几天发布翻译认领。再次感谢。
