### ISSUE TITLE
如何在 Keras 中使用 LSTM 神经网络创作音乐

### ISSUE THREAD

**Issue by slyrx** [xitu/gold-miner#5359]
* 原文链接：[How to Generate Music using a LSTM Neural Network in Keras](https://towardsdatascience.com/how-to-generate-music-using-a-lstm-neural-network-in-keras-68786834d4c5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-generate-music-using-a-lstm-neural-network-in-keras.md)
* PR 地址：#5408
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：7.5-9 分
* 校对积分：1.5-4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by HearFishle** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@HearFishle 棒极啦 :tada:

**Comment by lsvih** [comment]
PR 地址：#5408
