### ISSUE TITLE
浏览器帧原理剖析

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5360]
* 原文链接：[The Anatomy of a Frame](https://aerotwist.com/blog/the-anatomy-of-a-frame/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-anatomy-of-a-frame.md)
  * PR 地址：#5424
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@WangLeto 认领吧

**Comment by WangLeto** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@WangLeto 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5424
