### ISSUE TITLE
React 钩子系统的原理

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5362]
* 原文链接：[Under the hood of React’s hooks system](https://medium.com/the-guild/under-the-hood-of-reacts-hooks-system-eb59638c9dba)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/under-the-hood-of-reacts-hooks-system.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5425
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by noahziheng** [comment]
@EmilyQiRabbit 翻译的进度如何，有没有需要帮忙的？

**Comment by EmilyQiRabbit** [comment]
@noahziheng 还在翻译...因为前一篇有点长就延迟了，所以这一篇也稍慢了些。本周内提交嗯嗯。

**Comment by fanyijihua** [comment]
PR 地址：#5425
