### ISSUE TITLE
Software Roles and Titles

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5368]
* 原文链接：[Software Roles and Titles](https://medium.com/javascript-scene/software-roles-and-titles-e3f0b69c410c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/software-roles-and-titles.md)
  * PR 地址：
  * 文章分类：**教程**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6.5-8 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by AceLeeWinnie** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@AceLeeWinnie 棒极啦 :tada:

**Comment by JackEggie** [comment]
@AceLeeWinnie 大佬翻译的怎么样啦？

**Comment by AceLeeWinnie** [comment]
好的，今晚交作业

**Comment by sunui** [comment]
@AceLeeWinnie  翻译的进度如何，翻译快到时限了哟，如果两天后不能及时完成翻译，可能会被取消翻译资格～

**Comment by AceLeeWinnie** [comment]
好的！

**Comment by sunui** [comment]
@AceLeeWinnie 这篇已经有译文出来了，https://36kr.com/p/5188441 ，你根据你的进度和这篇译文质量看下要不要继续翻译

**Comment by AceLeeWinnie** [comment]
这篇译文的质量确实不错... 我选择放弃...

**Comment by leviding** [comment]
希望之后领了文章能够按时完成，有问题可以及时沟通。
