### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by zhongdeming428** [xitu/gold-miner#5369]
- 原文链接：https://www.internalpointers.com/post/gentle-introduction-multithreading
- 简要介绍：一篇进程、线程、fiber 的简介。文章简单介绍了线程与进程的概念、线程的作用、线程安全的概念、并发和并行的原理、多道程序设计的利与弊～

**Comment by leviding** [comment]
感谢您的推荐，近期发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
