### ISSUE TITLE
志愿者申请

### ISSUE THREAD

**Issue by wuguidashi** [xitu/gold-miner#537]
北京工业大学大四毕业学生，在一家创业公司实习做移动H5开发三个月，即将去美国继续学习CS专业，英语水平中等，但对于新技术有极大的热情，每天关注掘金最新动态，希望能够帮上一些忙。

**Comment by antonia0912** [comment]
@wuguidashi 不好意思  目前我们的志愿者已经找到了  如果你对翻译计划感兴趣的话 可以来尝试翻译和校对文章  成为我们的译者  可以加我微信 antonia0912 备注github ID 我来拉你进译者群
