### ISSUE TITLE
Spring 的分布式事务实现 — 使用和不使用 XA — 第一部分

### ISSUE THREAD

**Issue by JackEggie** [xitu/gold-miner#5370]
* 原文链接：[Distributed transactions in Spring, with and without XA - Part I](https://www.javaworld.com/article/2077963/distributed-transactions-in-spring--with-and-without-xa.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/distributed-transactions-in-spring-with-and-without-xa-part-1.md)
  * PR 地址：#5683
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-7 分
  * 校对积分：1-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mirosalva** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Mirosalva 棒极啦 :tada:

**Comment by honwhy** [comment]
找到了一篇翻译
http://codin.im/2017/06/07/distributed-transactions-in-spring--with-and-without-xa-translate/

**Comment by leviding** [comment]
如果开始翻译了，可以继续翻译，没开始翻译，不翻译了也可以，影响不大。

**Comment by Mirosalva** [comment]
@leviding 
在周末翻译了30%左右，那就不继续翻译了吧，帮忙把issue closed一下呢？

**Comment by leviding** [comment]
@Mirosalva 想翻译，可以继续翻译。如果决定不翻译了，你 close 一下就可以了哈。

**Comment by Mirosalva** [comment]
@leviding 最近两天在准备公司的事情，这篇翻译需要帮忙释放一下，由别的同学帮忙翻，不好意思呀

**Comment by JackEggie** [comment]
@Mirosalva @leviding 已重新释放。

**Comment by Mirosalva** [comment]
你好，收到了你的邮件。在周末翻译了30%左右，那就不继续翻译了吧，帮忙把issue closed一下呢？发自我的华为手机-------- 原始邮件 --------主题：Re: [xitu/gold-miner] Distributed transactions in Spring, with and without XA - Part I (#5370)发件人：LeviDing 收件人：xitu/gold-miner 抄送：Mirosalva ,Mention 如果开始翻译了，可以继续翻译，没开始翻译，不翻译了也可以，影响不大。

**Comment by Mirosalva** [comment]
这两天要准备公司的事，所以暂时没有时间翻，见谅哈发自我的华为手机-------- 原始邮件 --------主题：Re: [xitu/gold-miner] Distributed transactions in Spring, with and without XA - Part I (#5370)发件人：LeviDing 收件人：xitu/gold-miner 抄送：Mirosalva ,Mention @Mirosalva 想翻译，可以继续翻译。如果决定不翻译了，你 close 一下就可以了哈。

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by sunui** [comment]
@Starriers 翻译的怎么样啦

**Comment by Starriers** [comment]
晚上发

**Comment by sunui** [comment]
@Starriers  ok了吗，抓紧时间啦

**Comment by JackEggie** [comment]
翻译认领。 @fanyijihua

**Comment by fanyijihua** [comment]
@JackEggie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5683
