### ISSUE TITLE
曝光！UX 行话大全

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5373]
* 原文链接：[A comprehensive (and honest) list of UX clichés](https://uxdesign.cc/a-comprehensive-and-honest-list-of-ux-clich%C3%A9s-96e2a08fb2e9)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-comprehensive-and-honest-list-of-ux-clichés.md)
  * PR 地址：#5411
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Fengziyin1234** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Fengziyin1234 棒极啦 :tada:

**Comment by Fengziyin1234** [comment]
@leviding 稍微延迟一天，我今天就给出来～

**Comment by fanyijihua** [comment]
PR 地址：#5411
