### ISSUE TITLE
四个理由让你使用灰度色调进行设计

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5374]
* 原文链接：[4 Reasons Why You Should Design Without Color First](https://medium.com/devsdesign/4-reasons-why-you-should-design-without-color-first-c0e38180f689)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/4-reasons-why-you-should-design-without-color-first.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5380
  * 文章分类：**设计**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xionglong58** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@xionglong58 棒极啦 :tada:

**Comment by noahziheng** [comment]
翻译的进度如何，有没有需要帮忙的？

**Comment by xionglong58** [comment]
@noahziheng 什么情况？文章已经翻译完成，并且处于校对中啊

**Comment by noahziheng** [comment]
@xionglong58 你在 PR 的 `resolve` 中应关联这个 Issue....你这波我来处理吧，下次注意哟～

**Comment by noahziheng** [comment]
PR 地址：#5380
