### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by horizon13th** [xitu/gold-miner#5376]
- 原文链接：https://daveceddia.com/redux-tutorial/
- 简要介绍：A Complete React Redux Tutorial for 2019，非常全面的react redux的教程，简单易懂

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢您的推荐，近期发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
