### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Yaowenjie** [xitu/gold-miner#538]
公司：ThoughtWorks
工作内容：DevOps + 前后端（后端以java为主）
英语水平：日常英文邮件+口语交流
有无翻译经验：有，请参考[博客](http://yaowenjie.github.io/page3/)部分译文，或者早期翻译的：[The DSC Book中文版](https://yaowenjie.gitbooks.io/the-dsc-book/content/)
个人博客：yaowenjie.github.io

**Comment by antonia0912** [comment]
@Yaowenjie 欢迎来翻译计划  请加我微信 antonia0912 备注github ID 我来拉你进译者群
