### ISSUE TITLE
JavaScript 中为什么会有 Symbols 类型？

### ISSUE THREAD

**Issue by noahziheng** [xitu/gold-miner#5386]
* 原文链接：[JavaScript Symbols: But Why?](https://medium.com/intrinsic/javascript-symbols-but-why-6b02768f4a5c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/javascript-symbols-but-why.md)
  * PR 地址：#5429
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xionglong58** [comment]
@noahziheng 翻译认领

**Comment by fanyijihua** [comment]
@xionglong58 棒极啦 :tada:

**Comment by EdmondWang** [comment]
@leviding 校对认领

**Comment by xionglong58** [comment]
@fanyijihua 你好，我的github出现了问题，目前正在修复
