### ISSUE TITLE
如何编写自动化、跨浏览器的 Javascript 单元测试？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#539]
原文链接：[Learning How to Set Up Automated, Cross-browser JavaScript Unit Testing](https://philipwalton.com/articles/learning-how-to-set-up-automated-cross-browser-javascript-unit-testing)
掘金链接：[如何编写自动化、跨浏览器的 Javascript 单元测试？](http://gold.xitu.io/entry/578861bd79bc44005fc4773b)
markdown文件：[文章地址](https://github.com/xitu/gold-miner/blob/master/TODO/learning-how-to-set-up-automated-cross-browser-javascript-unit-testing.md)
校对地址：[传送门](https://github.com/xitu/gold-miner/pull/554/files)

翻译时间：3天
校对时间：2天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by owenlyn** [comment]
@sqrthree 麻烦问下这篇文章有几天时间翻译呀 我想认领

**Comment by MAYDAY1993** [comment]
求认领

**Comment by zhangchen91** [comment]
只求校对

**Comment by sqrthree** [comment]
@owenlyn 时间稍等，等羊哥一会来更新哈 @antonia0912

**Comment by Yaowenjie** [comment]
期望参与校对

**Comment by antonia0912** [comment]
@owenlyn 可以拿去翻译了  注意时间限制哈

**Comment by antonia0912** [comment]
@MAYDAY1993 @zhangchen91 @Yaowenjie 文章还没有开始翻译  所以不可以认领校对喔 等译者提交了PR再来抢校对吧 思密达们

**Comment by owenlyn** [comment]
@sqrthree @antonia0912 翻译完了= = [校对地址](https://github.com/owenlyn/gold-miner/commit/45d5176aafbe176ec1ae59496ea9d486548b8458#diff-9097d5d26a4dfd6de5b6a927ba2a6727) 抱歉格式很糟糕。。。

**Comment by MAYDAY1993** [comment]
申请校对

**Comment by Yaowenjie** [comment]
同校对~

**Comment by antonia0912** [comment]
@owenlyn 是不是翻译完没有发PR。。。。 @MAYDAY1993 @Yaowenjie 两位校对者稍等

**Comment by sqrthree** [comment]
@owenlyn 发完 PR 才能校对哈~

**Comment by owenlyn** [comment]
嗷嗷嗷。。。抱歉= =忘记[PR](https://github.com/xitu/gold-miner/pull/554)了

**Comment by MAYDAY1993** [comment]
校对完成 @sqrthree  @antonia0912 @owenlyn
