### ISSUE TITLE
iOS 响应者链 UIResponder，UIEvent，UIControl 的使用

### ISSUE THREAD

**Issue by swants** [xitu/gold-miner#5390]
* 原文链接：[iOS Responder Chain: UIResponder, UIEvent, UIControl and uses](https://swiftrocks.com/understanding-the-ios-responder-chain.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/iOS-Responder-Chain-UIResponder-UIEvent-UIControl-and-uses.md)
* PR 地址：#5400
* 文章分类：**iOS**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
---
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：5 分
* 校对积分：1-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iWeslie** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@iWeslie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5400
