### ISSUE TITLE
Android 生命周期备忘录 — 第三部分：Fragments

### ISSUE THREAD

**Issue by DevMcryYu** [xitu/gold-miner#5394]
* 原文链接：[The Android Lifecycle cheat sheet — part III : Fragments](https://medium.com/androiddevelopers/the-android-lifecycle-cheat-sheet-part-iii-fragments-afc87d4f37fd)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/The-Android-Lifecycle-cheat-sheet-part-III-Fragments.md)
  * PR 地址：#5420
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Qiuk17** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Qiuk17 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5420
