### ISSUE TITLE
监测与调试 Vue.js 的响应式系统：计算属性树（Computed Tree）

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5397]
* 原文链接：[Tracing or Debugging Vue.js Reactivity: The computed tree](https://medium.com/dailyjs/tracing-or-debugging-vue-js-reactivity-the-computed-tree-9da0ba1df5f9)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/tracing-or-debugging-vue-js-reactivity-the-computed-tree.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5444
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@SHERlocked93 来认领吧

**Comment by SHERlocked93** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@SHERlocked93 棒极啦 :tada:
