### ISSUE TITLE
时间顺序的价格异常检测

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5398]
* 原文链接：[Time Series of Price Anomaly Detection](https://towardsdatascience.com/time-series-of-price-anomaly-detection-13586cd5ff46)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/time-series-of-price-anomaly-detection.md)
  * PR 地址：#5406
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kasheemlew** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@kasheemlew 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5406
