### ISSUE TITLE
多线程简介

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5402]
* 原文链接：[A gentle introduction to multithreading](https://www.internalpointers.com/post/gentle-introduction-multithreading)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/gentle-introduction-multithreading.md)
  * PR 地址：#5437
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by steinliber** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@steinliber 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5437
