### ISSUE TITLE
2019 React Redux 完全指南

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5404]
* 原文链接：[A Complete React Redux Tutorial for 2019](https://daveceddia.com/redux-tutorial/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/redux-tutorial.md)
  * PR 地址：
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：2 天
  * 翻译积分：11-13 分
  * 校对积分：2-6 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xilihuasi** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@xilihuasi 棒极啦 :tada:

**Comment by leviding** [comment]
@xilihuasi 翻译的怎么样啦

**Comment by xilihuasi** [comment]
抱歉延期了，待会儿整理一下就发 pr 啦！
