### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by Endone** [xitu/gold-miner#5405]
- 原文链接：https://medium.com/launch-school/how-to-read-source-code-without-ripping-your-hair-out-e066472bbe8d
- 简要介绍：介绍如何有效地阅读源代码

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
很赞的文章，感谢您的推荐，已发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
