### ISSUE TITLE
Chars2vec: 基于字符实现的可用于处理现实世界中包含拼写错误和俚语的语言模型

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5410]
* 原文链接：[Chars2vec: character-based language model for handling real world texts with spelling errors and…](https://hackernoon.com/chars2vec-character-based-language-model-for-handling-real-world-texts-with-spelling-errors-and-a3e4053a147d)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/chars2vec-character-based-language-model-for-handling-real-world-texts-with-spelling-errors-and.md)
  * PR 地址：#5422
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6.5-7.5 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kasheemlew** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@kasheemlew 棒极啦 :tada:

**Comment by kasheemlew** [comment]
@lsvih @leviding    markdown文件中缺失了原文链接中的几段代码，请问如何处理

**Comment by lsvih** [comment]
@kasheemlew 已添加，给您添麻烦了

**Comment by kasheemlew** [comment]
好的，辛苦了 @lsvih

**Comment by kasheemlew** [comment]
呃，最后面还有个表格 @lsvih

**Comment by lsvih** [comment]
@kasheemlew  好了 Orz

**Comment by fanyijihua** [comment]
PR 地址：#5422
