### ISSUE TITLE
The C10K problem

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5413]
* 原文链接：[The C10K problem](http://www.kegel.com/c10k.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-c10k-problem.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5594
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：10 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@kobehaha 认领吧

**Comment by kobehaha** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@kobehaha 棒极啦 :tada:

**Comment by leviding** [comment]
@kobehaha 翻译的怎么样啦

**Comment by kobehaha** [comment]
@leviding 你好，估计还得3天左右，最近有点忙，希望可以理解

**Comment by leviding** [comment]
@kobehaha 好滴

**Comment by leviding** [comment]
@kobehaha 好滴

**Comment by kobehaha** [comment]
已经翻译好了，我这边在详细的review下，明后天提交上来

**Comment by sunui** [comment]
@kobehaha 大佬，抓紧提交一下啦

**Comment by kobehaha** [comment]
你好，已提交内容 https://github.com/xitu/gold-miner/pull/5594
