### ISSUE TITLE
如何心平气和的阅读代码

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5416]
* 原文链接：[How to read code without ripping your hair out](https://medium.com/launch-school/how-to-read-source-code-without-ripping-your-hair-out-e066472bbe8d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-read-source-code-without-ripping-your-hair-out.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5432
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mcskiller** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Mcskiller 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5432
