### ISSUE TITLE
Amy's Cassandra 2.1 tuning guide

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5418]
* 原文链接：[Amy's Cassandra 2.1 tuning guide](https://tobert.github.io/pages/als-cassandra-21-tuning-guide.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/als-cassandra-21-tuning-guide.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：20 分
* 校对积分：4-8 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
真的好长的一篇。

**Comment by lsvih** [comment]
@leviding 我猜您是含泪放到 TODO 里去的？

**Comment by leviding** [comment]
@lsvih 是的，以后咱们不做这么长的了吧，10 分的文章已经够长了。

**Comment by leviding** [comment]
或者这篇文章，我们拆分成三或四篇，形成一个系列，你认为怎么样？
