### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by gs666** [xitu/gold-miner#5419]
- 原文链接：http://www.ianbicking.org/blog/2019/03/open-source-doesnt-make-money-by-design.html
- 简要介绍：作者讨论了开源与赚钱的话题，掘金站长分享的，看了一下很不错~

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢您的推荐，近期发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
