### ISSUE TITLE
写给大家看的 Cache-Control 指令配置

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5428]
* 原文链接：[Cache-Control for Civilians](https://csswizardry.com/2019/03/cache-control-for-civilians/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/cache-control-for-civilians.md)
* PR 地址：#5471
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：9-11 分
* 校对积分：2-5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sunui 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5471
