### ISSUE TITLE
开源是无法赚钱的，因为开源本身就不是为了赚钱

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5431]
* 原文链接：[Open Source Doesn't Make Money Because It Isn't Designed To Make Money](https://www.ianbicking.org/blog/2019/03/open-source-doesnt-make-money-by-design.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/open-source-doesnt-make-money-by-design.md)
* PR 地址：#5435
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2-3 分
* 校对积分：0.5-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
标题可以参考[开源是无法赚钱的，因为开源本身就不是为了赚钱](https://juejin.im/entry/5c91aed151882547e46dbe68)

**Comment by kasheemlew** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@kasheemlew 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5435
