### ISSUE TITLE
Spring 的分布式事务实现 — 使用和不使用XA — 第二部分

### ISSUE THREAD

**Issue by JackEggie** [xitu/gold-miner#5436]
* 原文链接：[Distributed transactions in Spring, with and without XA - Part II](https://www.javaworld.com/article/2077963/distributed-transactions-in-spring--with-and-without-xa.html?page=2)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/distributed-transactions-in-spring-with-and-without-xa-part-2.md)
  * PR 地址：#5470
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xiantang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@xiantang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5469

**Comment by fanyijihua** [comment]
PR 地址：#5470
