### ISSUE TITLE
从没有人告诉过我的 CSS 小知识

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5438]
* 原文链接：[Things nobody ever taught me about CSS.](https://medium.com/@devdevcharlie/things-nobody-ever-taught-me-about-css-5d16be8d5d0e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/things-nobody-ever-taught-me-about-css.md)
  * PR 地址：#5456
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@rottenpen 来认领啦

**Comment by Xuyuey** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Xuyuey 棒极啦 :tada:

**Comment by rottenpen** [comment]
好像迟了。。。

**Comment by leviding** [comment]
@rottenpen 好像是晚了...

**Comment by fanyijihua** [comment]
PR 地址：#5456
