### ISSUE TITLE
Android 生命周期备忘录 —— 第四部分：ViewModels、半透明 Activities 及启动模式

### ISSUE THREAD

**Issue by DevMcryYu** [xitu/gold-miner#5442]
* 原文链接：[The Android Lifecycle cheat sheet — part IV: ViewModels, Translucent Activities and Launch Modes](https://medium.com/androiddevelopers/the-android-lifecycle-cheat-sheet-part-iv-49946659b094)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/The-Android-Lifecycle-cheat-sheet-part-IV.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5515
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xiaxiayang** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@xiaxiayang 棒极啦 :tada:

**Comment by DevMcryYu** [comment]
@xiaxiayang 大佬翻译的怎么样啦~

**Comment by xiaxiayang** [comment]
抱歉，周末这两天有事情忘记了，明天应该会翻译完

**Comment by fanyijihua** [comment]
PR 地址：#5515
