### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by honwhy** [xitu/gold-miner#5443]
- 原文链接：https://www.demainilpleut.fr/your-first-cli-tool-with-rust/
- 简要介绍：一步步教程使用rust打造cli工具

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by JackEggie** [comment]
感谢您的推荐，近期发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
