### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by TBLGSn** [xitu/gold-miner#5447]
- 原文链接：https://blog.usejournal.com/10-signs-you-will-suck-at-programming-5497a6a52c5c
- 简要介绍：当你编程可能会遇见的10种迹象. “虽然编程可能是一项难以学习的技能，但它肯定是大多数人可以学习的技能。”

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by TBLGSn** [comment]
![u=2536700066,2184961913 fm=27 gp=0](https://user-images.githubusercontent.com/43395216/54893050-07694300-4eef-11e9-85c0-1bd66f1a8497.jpg)

**Comment by JackEggie** [comment]
感谢您的推荐，近期发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
