### ISSUE TITLE
你不能成为成功程序员的 10 个迹象

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5450]
* 原文链接：[10 Signs You Will Suck at Programming](https://blog.usejournal.com/10-signs-you-will-suck-at-programming-5497a6a52c5c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/10-signs-you-will-suck-at-programming.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5492
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：8-10 分
* 校对积分：2-4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xionglong58** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@xionglong58 棒极啦 :tada:

**Comment by xionglong58** [comment]
@leviding 文章已发布：https://juejin.im/post/5ca2f5ce51882565cb5b962c
