### ISSUE TITLE
用 Rust 打造你的第一个命令行工具

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5452]
* 原文链接：[Your first CLI tool with Rust](https://www.demainilpleut.fr/your-first-cli-tool-with-rust/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/your-first-cli-tool-with-rust.md)
* PR 地址：#5550
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：0.5-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JackEggie** [comment]
翻译认领 @fanyijihua

**Comment by fanyijihua** [comment]
@JackEggie 棒极啦 :tada:

**Comment by sunui** [comment]
@JackEggie 翻译的进度如何，有没有需要帮忙的？

**Comment by JackEggie** [comment]
不好意思，明后两天搞定。

**Comment by fanyijihua** [comment]
PR 地址：#5550
