### ISSUE TITLE
Data Binding 库使用的经验教训

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5454]
* 原文链接：[Data Binding — Lessons Learnt](https://medium.com/androiddevelopers/data-binding-lessons-learnt-4fd16576b719)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/data-binding-lessons-learnt.md)
* PR 地址：
* 文章分类：**Android**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：0.5-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mirosalva** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Mirosalva 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5555
