### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by Fengziyin1234** [xitu/gold-miner#5458]
- 原文链接：https://css-tricks.com/planning-for-responsive-images/
- 简要介绍：responsive images 的相关知识和简单实现

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢您的推荐，已发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分

**Comment by leviding** [comment]
已发布翻译认领 https://github.com/xitu/gold-miner/issues/5466
