### ISSUE TITLE
React 中的调度

### ISSUE THREAD

**Issue by Ivocin** [xitu/gold-miner#5459]
* 原文链接：[Scheduling in React](https://philippspiess.com/scheduling-in-react/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/scheduling-in-react.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5505
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：1-2 天
  * 翻译积分：6-7.5 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Xuyuey** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Xuyuey 棒极啦 :tada:

**Comment by Xuyuey** [comment]
这个没有标注翻译用时呢～

**Comment by leviding** [comment]
@Xuyuey 现在更新啦

**Comment by blizzardzheng** [comment]
这篇还能认领或者校对么，比较感兴趣

**Comment by leviding** [comment]
@blizzardzheng 现在还没翻译好，翻译好了在对应 PR 下认领。
麻烦 @Xuyuey 翻译好提交 PR 后艾特一下这位同学。
