### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by giraffe0813** [xitu/gold-miner#546]
去年毕业于华东师范大学，工作一年多，目前在点评，之前在饿了么，方向是后端，英语水平6级，翻译过spring-data-es的官方文档，地址：http://es.yemengying.com/  个人博客：http://yemengying.com 个人博客上也有一些翻译的文章。

**Comment by antonia0912** [comment]
@giraffe0813 欢迎来翻译计划玩 请加我微信 antonia0912 备注github ID 我来拉你进译者群
