### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5464]
- 原文链接：
      -http://www.davidsbatista.net/blog/2017/11/11/HHM_and_Naive_Bayes/
      -http://www.davidsbatista.net/blog/2017/11/12/Maximum_Entropy_Markov_Model/
      -http://www.davidsbatista.net/blog/2017/11/13/Conditional_Random_Fields/

- 简要介绍：HHM MEMM CRF 三部曲，简短且写的很清晰

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
赞，这文章可以啊

**Comment by lsvih** [comment]
近日添加
