### ISSUE TITLE
Swift 5.0 新特性

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5465]
* 原文链接：[What’s new in Swift 5.0](https://www.hackingwithswift.com/articles/126/whats-new-in-swift-5-0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/whats-new-in-swift-5-0.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5476
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6-7 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@iWeslie 来认领吧

**Comment by iWeslie** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@iWeslie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5476
