### ISSUE TITLE
使用网格布局实现响应式图片

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5466]
* 原文链接：[Planning for Responsive Images](https://css-tricks.com/planning-for-responsive-images/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/planning-for-responsive-images.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5487
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LucaslEliane** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@LucaslEliane 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5487

**Comment by portandbridge** [comment]
认领校对
