### ISSUE TITLE
懒加载变量在 iOS Swift

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5468]
* 原文链接：[lazy var in ios swift](https://medium.com/@abhimuralidharan/lazy-var-in-ios-swift-96c75cb8a13a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/lazy-var-in-ios-swift.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5494
* 文章分类：**iOS**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：0.5-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kirinzer** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@kirinzer 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5494
