### ISSUE TITLE
怎么简化你的设计

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5474]
* 原文链接：[How to simplify your design](https://uxplanet.org/how-to-simplify-your-design-69d97fde11b9)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-simplify-your-design.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5569
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：5-6 分
* 校对积分：1-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shixi-li** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@shixi-li 棒极啦 :tada:

**Comment by sunui** [comment]
@shixi-li 翻译的怎么样啦

**Comment by shixi-li** [comment]
@sunui 这一篇快完成了，今晚提交。

**Comment by fanyijihua** [comment]
PR 地址：#5569

**Comment by ezioyuan** [comment]
认领校对

**Comment by AceLeeWinnie** [comment]
校对认领

**Comment by leviding** [comment]
@ezioyuan @AceLeeWinnie 请在对应 PR https://github.com/xitu/gold-miner/pull/5569 下认领校对
