### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by nettee** [xitu/gold-miner#5477]
- 原文链接：http://willcrichton.net/notes/systems-programming/
- 简要介绍：这篇文章梳理了程序语言的发展历史，以及“系统编程”这个概念的演变过程，指出了人们对“系统编程”这个词的误解，也分析了最近新兴的 Go、Rust 等语言在系统编程中的作用。作者是斯坦福研究程序语言的在读博士

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
我查到，这篇文章你翻译过？ http://nettee.github.io/posts/2018/What-is-Systems-Programming-Really/
