### ISSUE TITLE
在 Swift Playgrounds 中使用 Core Data 模型

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#548]
原文链接：[using-a-core-data-model-in-swift-playgrounds](https://www.andrewcbancroft.com/2016/07/10/using-a-core-data-model-in-swift-playgrounds/)
掘金链接：[在 Swift Playgrounds 中使用 Core Data 模型](http://gold.xitu.io/entry/578c81cc0a2b5800684b4d52)
markdown文件：[文章地址](https://github.com/xitu/gold-miner/blob/master/TODO/using-a-core-data-model-in-swift-playgrounds.md)
校对地址：[传送门](https://github.com/xitu/gold-miner/pull/580/files)

翻译时间：3天
校对时间：2天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by MAYDAY1993** [comment]
申请认领

**Comment by sqrthree** [comment]
@MAYDAY1993 好哒~ 🐑🐑🐑 哥快来添加积分啦~ @antonia0912

**Comment by MAYDAY1993** [comment]
@sqrthree 翻译好了 校对地址https://github.com/xitu/gold-miner/pull/560/files

**Comment by owenlyn** [comment]
@sqrthree @antonia0912 申请校对

**Comment by siegeout** [comment]
@sqrthree @antonia0912 申请校对

**Comment by sqrthree** [comment]
@owenlyn @siegeout 好的，校对地址在上面哈~~

**Comment by sqrthree** [comment]
@owenlyn @siegeout 二位稍等哈，因为 PR 中出现了一点小差错，待更新之后再开始校对哈

**Comment by owenlyn** [comment]
@sqrthree @MAYDAY1993 额 可以开始校对了吗...?

**Comment by sqrthree** [comment]
@owenlyn 我昨天跟她联系，已经调整好了，只是还没有发 PR，我再联系下，稍等哈~

**Comment by sqrthree** [comment]
@owenlyn @siegeout 校对地址已经更新了~  https://github.com/xitu/gold-miner/pull/580 可以校对了哈

**Comment by MAYDAY1993** [comment]
@sqrthree  参考校对建议改好译文啦
