### ISSUE TITLE
你需要知道的 CSS 中所有 hyphenation 的使用

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5480]
* 原文链接：[All you need to know about hyphenation in CSS](https://clagnut.com/blog/2395)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/hyphenation-in-css.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5525
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4-5 分
* 校对积分：1-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Augustwuli** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@Augustwuli 棒极啦 :tada:

**Comment by Augustwuli** [comment]
@leviding 翻译认领。。不小心把那条消息删掉了

**Comment by fanyijihua** [comment]
PR 地址：#5525
