### ISSUE TITLE
How to manipulate CSS colors with JavaScript

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5482]
* 原文链接：[How to manipulate CSS colors with JavaScript](https://blog.logrocket.com/how-to-manipulate-css-colors-with-javascript-fb547113a1b8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-manipulate-css-colors-with-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xingqiwu55555** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@xingqiwu55555 棒极啦 :tada:

**Comment by xingqiwu55555** [comment]
@lsvih  这篇文章好像已经有译文了，还是大漠翻译的，还要译吗？

**Comment by leviding** [comment]
close  啦，不好意思哈
