### ISSUE TITLE
对 React 组件进行单元测试

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5485]
* 原文链接：[Unit Testing React Components](https://medium.com/javascript-scene/unit-testing-react-components-aeda9a44aae2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/unit-testing-react-components.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5573
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：6-7.5 分
* 校对积分：1.5-3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xionglong58** [comment]
@lsvih 翻译认领

**Comment by fanyijihua** [comment]
@xionglong58 棒极啦 :tada:

**Comment by sunui** [comment]
@xionglong58 翻译的怎么样啦

**Comment by xionglong58** [comment]
@sunui 不好意思，最近有事儿耽误了，正在加紧翻译
