### ISSUE TITLE
使用 WFST 进行语音识别

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5489]
* 原文链接：[An Introduction to Speech Recognition using WFSTs](https://medium.com/explorations-in-language-and-learning/an-introduction-to-speech-recognition-using-wfsts-288b6aeecebe)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/an-introduction-to-speech-recognition-using-wfsts.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5676
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3.5-4.5 分
* 校对积分：0.5-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shixi-li** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@shixi-li 棒极啦 :tada:

**Comment by sunui** [comment]
@shixi-li 翻译的怎么样啦

**Comment by shixi-li** [comment]
@leviding  @sunui 抱歉，这篇文章请释放吧。最近我个人临时产生的事情太多，确实没有时间完成。

**Comment by leviding** [comment]
@shixi-li 好，之后有这种情况麻烦及时沟通。

**Comment by sisibeloved** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@sisibeloved 棒极啦 :tada:

**Comment by sunui** [comment]
@sisibeloved 翻译的怎么样啦，有没有需要帮忙的？

**Comment by sisibeloved** [comment]
@sunui 这两天就可以完成啦
