### ISSUE TITLE
 iOS 开发中的 Flux 架构模式

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#549]
原文链接：[real-world-flux-ios](http://blog.benjamin-encz.de/post/real-world-flux-ios/)
掘金链接：[ iOS 开发中的 Flux 架构模式](http://gold.xitu.io/entry/578c53686be3ff006ce39a1f)
markdown文件：[文章地址](https://github.com/xitu/gold-miner/blob/master/TODO/real-world-flux-ios.md)
校对地址：[传送门](https://github.com/xitu/gold-miner/pull/569)

翻译时间：4天
校对时间：2天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by yifili09** [comment]
@sqrthree 认领！！

**Comment by sqrthree** [comment]
@yifili09  积分等 @antonia0912 🐑 哥一会来更新哈

**Comment by antonia0912** [comment]
@yifili09 已经添加了积分 请注意时间限制

**Comment by yifili09** [comment]
@antonia0912 恩。Okey的。

**Comment by yifili09** [comment]
@sqrthree RP-#569  可以校对了。

**Comment by sqrthree** [comment]
@yifili09 好的~

**Comment by PeijinHuang** [comment]
校对+1

**Comment by Graning** [comment]
校队+1

**Comment by rccoder** [comment]
申请校对

**Comment by rccoder** [comment]
简直长。。。
