### ISSUE TITLE
编写可以复用的 HTML 模板

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5495]
* 原文链接：[Crafting Reusable HTML Templates](https://css-tricks.com/crafting-reusable-html-templates/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/crafting-reusable-html-templates.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5508
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mirosalva** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Mirosalva 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5508
