### ISSUE TITLE
从头创建自定义元素

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5496]
* 原文链接：[Creating a Custom Element from Scratch](https://css-tricks.com/creating-a-custom-element-from-scratch/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/creating-a-custom-element-from-scratch.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5518
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yzw7489757** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@yzw7489757 棒极啦 :tada:
