### ISSUE TITLE
Workmanager 简介

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5498]
* 原文链接：[Introducing WorkManager](https://medium.com/androiddevelopers/introducing-workmanager-2083bcfc4712)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/introducing-workmanager.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5548
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gs666** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@gs666 棒极啦 :tada:

**Comment by sunui** [comment]
@gs666 翻译的怎么样啦

**Comment by gs666** [comment]
> @gs666 翻译的怎么样啦

清明太浪了，晚上上传～

**Comment by fanyijihua** [comment]
PR 地址：#5548
