### ISSUE TITLE
十字绣 Plaid 应用和 AndroidX

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5499]
* 原文链接：[Cross-stitching Plaid and AndroidX](https://medium.com/androiddevelopers/cross-stitching-plaid-and-androidx-7603a192348e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/cross-stitching-plaid-and-androidx.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5540
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mirosalva** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Mirosalva 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5540
