### ISSUE TITLE
认领MVVM模式介绍

### ISSUE THREAD

**Issue by lanarthur** [xitu/gold-miner#55]
我是一名大四英语专业学生，经常帮社区翻译文章，详细介绍请查看我的个人博客：www.lancelotarthur.com，谢谢。

**Comment by Sausure** [comment]
你好，这个我已经认领了，你可以在Issues里看到，抱歉

**Comment by Glowin** [comment]
@lanarthur 你好，这篇文章已经被 @Sausure 认领并完成初稿了。而且现在我挑选出来的文章也基本被认领完了，但是这个翻译计划还是会一直更新维护下去，我们很乐意邀请你加入并关注这个翻译计划，谢谢你的支持。

**Comment by lanarthur** [comment]
好的，我知道了，如果有下次有机会再参加

在 2015年12月27日 下午3:02，Glow Chiang <notifications@github.com>写道：
