### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by nettee** [xitu/gold-miner#5502]
- 原文链接：http://aosabook.org/en/nginx.html
- 简要介绍：这篇文章介绍了 nginx（Web 服务器、反向代理服务器），包括 nginx 的优势所在、内部工作原理、以及关键的架构

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by kezhenxu94** [comment]
HI @nettee 感谢推荐, 但是文章已经有译文了

https://blog.51cto.com/xuanwei/1905885
