### ISSUE TITLE
实用的 MVVM 和 RxSwift

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5503]
* 原文链接：[Practical MVVM + RxSwift](https://medium.com/flawless-app-stories/practical-mvvm-rxswift-a330db6aa693)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/practical-mvvm-rxswift.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5537
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iWeslie** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@iWeslie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5537
