### ISSUE TITLE
Python架构相关：我们需要更多吗？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5504]
* 原文链接：[Python Architecture Stuff: do we need more?](http://www.obeythetestinggoat.com/python-architecture-stuff-do-we-need-more.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/python-architecture-stuff-do-we-need-more.md)
  * PR 地址：
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by QiaoN** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@QiaoN 棒极啦 :tada:

**Comment by sunui** [comment]
@QiaoN 翻译的怎么样啦

**Comment by QiaoN** [comment]
不好意思，这两天略忙，周末前翻译出来！

**Comment by fanyijihua** [comment]
PR 地址：#5591
