### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by clxering** [xitu/gold-miner#5509]
- 公司/学校：中国南方电网广西分公司
- 工作内容/专业：集抄系统数据采集与分析，电气自动化专业
- 常浏览的国外网站：StackOverflow、javacodegeeks.com、infoq.com、Medium、Quora
- 英语水平：CET 4
- 翻译经验：Effective Java（第3版）、HttpClient 文档等
- 主要翻译方向：后端技术、前端技术
- 个人博客：http://www.dcheng.site/
- 个人介绍：主要技术栈为 JavaWeb、MySQL、MongoDB、Vue.js ，热爱开发，积极了解相关技术的发展及趋势。

**Comment by leviding** [comment]
Hi @clxering ，感谢你申请加入掘金翻译计划，你需要做以下的事：

**1.** 认真学习 [掘金翻译计划译者教程](https://github.com/xitu/gold-miner/wiki)，校对和翻译文章时，严格遵循教程，杜绝不看教程，只知道问的伸手党；

**2.** 确认认真学习了 [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)，翻译文章时严格遵循，校对文章时也要指出译者的格式错误；

**3.** 确认认真学习了 [翻译和校对文章的注意事项](https://github.com/xitu/gold-miner/wiki/%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88)，避免翻译校对过程中出错。

**4.** 确定已学习完上述内容，加管理员微信 517010193 或者扫描 [二维码](https://user-images.githubusercontent.com/26959437/49415379-74769280-f7b1-11e8-9581-ac87310af2ce.png) ，**验证信息格式**：姓名 + GitHub 用户名；

**注意**：管理员每天集中处理一次，稍安勿躁。加完微信后，管理员会在当天拉你进译者群，进群之后做下简单的自我介绍。加入微信群则代表申请译者成功，接下来你需要看译者教程，然后先校对至少一篇文章才能开始正式翻译文章。当然也可以继续校对文章。

**Comment by clxering** [comment]
感谢审核。
学习了上述几个要求后，有如下问题需要沟通确认。 @leviding 
- 「十万个为什么」中要求：不能领取擅长领域之外的文章。也看了译者擅长领域表，发现可以填写多个擅长领域。因此能否在原申请的主要翻译方向中，添加一项「前端」？
- 在学习「参与校对的正确姿势」时，发现该部分 Wiki 的最终修改时间为 2018 年 4 月，当时应该还没有增加「insert a suggestion」的功能。目前的校对页面如下图：
![20190402094442](https://user-images.githubusercontent.com/36018696/55370650-b7f9c700-552d-11e9-816b-6a6655d4fcdc.png)
该功能有助于译者及时接受修改意见，不必修改后重新提交分支，也可多个意见合并处理。如下图所示：
![20190402094555](https://user-images.githubusercontent.com/36018696/55370798-54bc6480-552e-11e9-805c-aed52b8a3611.png)
所以，我的问题是，在校对时能否按照「insert a suggestion」方式来给出校对意见。

**Comment by Fengziyin1234** [comment]
@clxering  欢迎加入大家庭哈哈哈。 我对你的两个问题的看法是这样哒

1. 我认为可以哒。
从社区的角度，列出一个或若干个擅长领域的目的本身是为了确保译文的质量。可能因为不了解导致一些理解上的偏差。
从个人的角度上，我个人觉得如果翻译一篇和自己工作学习都完全不相关的文章还是蛮辛苦的。和自己工作学习毫不相关的文章可能对自己的帮助也不是那么大（当然肯定是有帮助的）。我在翻译的过程中需要回顾我现有的知识并查阅一些新的知识，来更好的传达文章作者的含义。
我觉得定义这个擅长领域的原因就是为了帮助社区管理和帮助理解自身吧～

2.  谢谢推荐。其实很多小伙伴在平时校对时都已经开始使用这个功能啦。欢迎使用！我会帮忙看看如何把这个新功能加进「参与校对的正确姿势」哒。
我现在也会经常使用这个功能，觉得还是挺方便的。然后下面是我在使用时产生的一些看法。
    - 在段落较小时，我对段落有更佳翻译的情况时，使用该功能非常的方便有效，我觉得特别好～（尤其是关于格式方面的修订，因为不太会有异议，我觉得特别方便）。
    - 在段落较长时，行数较多时，不易很好的对应修改点。
    - 修改多处地方时，需要提出多个 suggestion （现在好像还不支持对整个段落的部分字句进行建议。如果有相关的方法，还请分享给我～谢谢）
    - 当我对于该段落有异议但是没有完整的翻译的时候，可能并不使用这个功能。
    - 很多时候我提出的意见只是被部分采纳，那么这个功能可能也不太会被使用。
    - 移动端体验极差（我为啥要在手机上校对哈哈哈）

**Comment by leviding** [comment]
@clxering 可以添加，自己认领自己熟悉领域，能翻译好的文章即可。
对于「insert a suggestion」功能，像你截图的那种小修改是很好的，但是对于调整语序，调整译法等复杂的修改，体验非常差，译者很难看出你到底修改了哪个地方，增加和沟通成本，所以暂时不建议全篇使用。你可以尝试一下，看看问题。

**Comment by clxering** [comment]
好的，感谢两位的反馈和建议。 @Fengziyin1234 @leviding
