### ISSUE TITLE
使用 Shadow DOM 封装样式和结构

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5512]
* 原文链接：[Encapsulating Style and Structure with Shadow DOM](https://css-tricks.com/encapsulating-style-and-structure-with-shadow-dom/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/encapsulating-style-and-structure-with-shadow-dom.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5545
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Xuyuey** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Xuyuey 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5545
