### ISSUE TITLE
伟大设计与好设计之间区别是什么？这里告诉你真相

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5513]
* 原文链接：[Great Design Vs Good Design: What’s The Difference? Here’s The Truth](https://medium.com/truthaboutdesign/great-design-vs-good-design-whats-the-difference-here-s-the-truth-da08557f6fdd)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/great-design-vs-good-design-whats-the-difference-here-s-the-truth.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5620
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：6-7 分
* 校对积分：1.5-3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mirosalva** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Mirosalva 棒极啦 :tada:

**Comment by sunui** [comment]
@Mirosalva 这篇翻译的怎么样了？

**Comment by leviding** [comment]
建议还是一次领一篇文章哈，这样能够更好的保证质量的同时，不耽误翻译进度。

**Comment by Mirosalva** [comment]
这两天在调代码，这篇翻译了50%左右，计划明晚提交吧

**Comment by fanyijihua** [comment]
PR 地址：#5620
