### ISSUE TITLE
Web Components 的高级工具

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5514]
* 原文链接：[Advanced Tooling for Web Components](https://css-tricks.com/advanced-tooling-for-web-components/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/advanced-tooling-for-web-components.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5547
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Xuyuey** [comment]
翻译认领 可以认领两篇吗 感觉他们关联性比较强

**Comment by fanyijihua** [comment]
@Xuyuey 棒极啦 :tada:

**Comment by Xuyuey** [comment]
我会尽量在假期之前搞定这两篇，不会辜负组织的期望

**Comment by leviding** [comment]
哈哈哈，手速这么快 🤣

**Comment by Xuyuey** [comment]
哈哈哈哈 正好在刷Github

**Comment by fanyijihua** [comment]
PR 地址：#5547
