### ISSUE TITLE
Swift 模块中的 API 污染

### ISSUE THREAD

**Issue by swants** [xitu/gold-miner#5517]
* 原文链接：[API Pollution in Swift Modules](https://nshipster.com/swift-api-pollution/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/swift-api-pollution.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5531
* 文章分类：**iOS**
*  **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
---
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：5-6 分
* 校对积分：1-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iWeslie** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@iWeslie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5531
