### ISSUE TITLE
在开发移动应用时你应该考虑的 「Empty State」

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#552]
原文链接：[empty-state-mobile-app-nice-to-have-essential](https://uxplanet.org/empty-state-mobile-app-nice-to-have-essential-f11c29f01f3)
掘金链接：[在开发移动应用时你应该考虑的 「Empty State」](http://gold.xitu.io/entry/578c46efd342d30058c5a719)
markdown文件：[文章地址](https://github.com/xitu/gold-miner/blob/master/TODO/empty-state-mobile-app-nice-to-have-essential.md)
校对地址：[传送门](https://github.com/xitu/gold-miner/pull/581)

翻译时间：3天
校对时间：2天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by MAYDAY1993** [comment]
申请认领

**Comment by antonia0912** [comment]
@MAYDAY1993 好的 注意时间限制

**Comment by sqrthree** [comment]
@antonia0912 还没有添加时间限制和积分呢 _(:з」∠)_

**Comment by shixinzhang** [comment]
申请校对

**Comment by jiaowoyongqi** [comment]
现在可以校对占坑嘛_(:зゝ∠)_

**Comment by sqrthree** [comment]
二位也太早了吧，竞争都已经激烈到这份上了吗 _(:з」∠)_

**Comment by shixinzhang** [comment]
竞争太激烈，先下手为强

**Comment by sqrthree** [comment]
@jiaowoyongqi @shixinzhang 二位可以校对了哈~ 校对地址已经更新了 https://github.com/xitu/gold-miner/pull/581

**Comment by jiaowoyongqi** [comment]
好的😃

**Comment by shixinzhang** [comment]
@MAYDAY1993  校对完成了

**Comment by jiaowoyongqi** [comment]
@sqrthree @MAYDAY1993 校对完成

**Comment by MAYDAY1993** [comment]
@sqrthree  参考校对建议后的译文commit好了

**Comment by sqrthree** [comment]
@MAYDAY1993 还有一些关于排版的小细节问题需要调整哈~
