### ISSUE TITLE
图解 Map、Reduce 和 Filter 数组方法

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5520]
* 原文链接：[An Illustrated (and Musical) Guide to Map, Reduce, and Filter Array Methods](https://css-tricks.com/an-illustrated-and-musical-guide-to-map-reduce-and-filter-array-methods/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/an-illustrated-and-musical-guide-to-map-reduce-and-filter-array-methods.md)
* PR 地址：#5549
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2-3 分
* 校对积分：0.5-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by FrankXiong** [comment]
认领

**Comment by lsvih** [comment]
@FrankXiong 棒极啦 🎉

**Comment by fanyijihua** [comment]
PR 地址：#5549
