### ISSUE TITLE
我们为什么看好加密收藏品（NFT）的前景

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5522]
* 原文链接：[Why We’re Bullish on Crypto Collectibles (NFTs)](https://medium.com/the-challenge/why-were-bullish-on-crypto-collectibles-nfts-5d47e4e39172)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-were-bullish-on-crypto-collectibles-nfts.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5543
* 文章分类：**区块链**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：0.5-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by portandbridge** [comment]
好像没人来译，我来试试看 😛 

翻译认领

**Comment by fanyijihua** [comment]
@portandbridge 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5543
