### ISSUE TITLE
哪一个深度学习框架增长最迅猛？TensorFlow 还是 PyTorch？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5524]
* 原文链接：[Which Deep Learning Framework is Growing Fastest?](https://towardsdatascience.com/which-deep-learning-framework-is-growing-fastest-3f77f14aa318)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/which-deep-learning-framework-is-growing-fastest.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4-5 分
* 校对积分：1-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ccJia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ccJia 棒极啦 :tada:

**Comment by ccJia** [comment]
我这边已经翻译完，再check一遍，预计明天晚上可以上传。

**Comment by lsvih** [comment]
@ccJia 好的~

**Comment by fanyijihua** [comment]
PR 地址：#5554
