### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by thaiwu0107** [xitu/gold-miner#5529]
- 原文链接：https://levelup.gitconnected.com/will-node-js-forever-be-the-sluggish-golang-f632130e5c7a

 简要介绍：中二病，嗆deno，被nodejs群ban掉的自負天才開發新的Nodejs http模塊，ssl下比沒有ssl的golang server還要快

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢您的推荐，一周内发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分

**Comment by lsvih** [comment]
已发布认领 issue #5534
