### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by thaiwu0107** [xitu/gold-miner#5530]
- 原文链接：https://medium.com/@alexhultman/millions-of-active-websockets-with-node-js-7dc575746a01

- 简要介绍：Nodejs使用一台筆電完成 一百萬Active WebSocket 連線，屌打Nodejs原生的http模塊，比golang server還要快

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢您的推荐，一周内发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分

**Comment by lsvih** [comment]
已发布认领 #5536
