### ISSUE TITLE
Node.js 提供百万的活跃 WebSocket 连接

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5536]
* 原文链接：[Millions of active WebSockets with Node.js](https://medium.com/@alexhultman/millions-of-active-websockets-with-node-js-7dc575746a01)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/millions-of-active-websockets-with-node-js.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5598
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2.5-3.5 分
* 校对积分：0.5-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mirosalva** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Mirosalva 棒极啦 :tada:

**Comment by sunui** [comment]
@Mirosalva  翻译的怎么样啦

**Comment by Mirosalva** [comment]
@sunui 上周已经翻译好了。阻塞原因在于#5540  这篇文件还没给合并，等它结束了，我重新拉一个分支提交本篇译文#5536 。

**Comment by fanyijihua** [comment]
PR 地址：#5598
