### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by Yangfan2016** [xitu/gold-miner#5538]
- 原文链接：https://overreacted.io/how-are-function-components-different-from-classes/
- 简要介绍：

作者：来自 React核心团队成员，Redux作者 [Dan Abramov](https://github.com/gaearon)       
文章：来源于他的博客     
概要：本文介绍了函数式组件和类的最大区别，文中也提及到了最新的 React 特性 Hooks 的使用
翻译情况：目前还无简体中文译文，可查看[链接](https://github.com/gaearon/overreacted.io/tree/master/src/pages/how-are-function-components-different-from-classes)验证
本人翻译的译文： [链接](https://github.com/Yangfan2016/learn-translate/blob/master/4-How-Are-Function-Components-Different-from-Classes_zh.md)  
本人整理的 markdown 地址：[链接](https://github.com/Yangfan2016/learn-translate/blob/master/4-How-Are-Function-Components-Different-from-Classes.md)

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by sunui** [comment]
@Yangfan2016 非常感谢推荐这么好的文章，但是很遗憾由于这篇文章已经有译文（[掘金](https://juejin.im/post/5c98310ff265da612d634730)、[ 简书](https://www.jianshu.com/p/26926857ff73) 、[github](https://github.com/xiaohesong/TIL/blob/master/front-end/react/overreact/%E5%87%BD%E6%95%B0%E7%BB%84%E4%BB%B6%E4%B8%8E%E7%B1%BB%E6%9C%89%E4%BB%80%E4%B9%88%E4%B8%8D%E5%90%8C.md)），就不放在翻译计划流程里了，您可以自己发表或者给原作者博客发 PR 呐。

以后有好文章欢迎继续推荐哈，推荐的时候直接标注推荐者自己翻译即可，我们制作完 markdown 文件后会@你的。

**Comment by Yangfan2016** [comment]
好吧~_~，下次咯😂
