### ISSUE TITLE
目前看到最好的分布式系统实现的课程的讲义与文章

### ISSUE THREAD

**Issue by harefield** [xitu/gold-miner#5544]
- 原文链接：推荐文章前 Google 一下，尽量保证本文未被翻译
http://nil.csail.mit.edu/6.824/2018/schedule.html
- 简要介绍：介绍一下好不好啦，毕竟小编也看不太懂哎_(:з」∠)_
麻省理工 6.824课程，边实践边讲课，课程所带若干个实验实现了多种协议下的分布式存储

**Comment by leviding** [comment]
@harefield 您好，首先感谢您的推荐，只是目前翻译计划还不做这种很大规模的课程类内容，并且该内容的结构也不适合翻译计划的运营模式。欢迎继续推荐其他优质内容。
