### ISSUE TITLE
创意运用 Console API！

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5557]
* 原文链接：[Getting creative with the Console API!](https://areknawo.com/getting-creative-with-the-console-api/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/getting-creative-with-the-console-api.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5617
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wznonstop** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@wznonstop 棒极啦 :tada:

**Comment by sunui** [comment]
@wznonstop 大佬，翻译得怎么样啦

**Comment by wznonstop** [comment]
不好意思，这几天出差比较忙，正在推进，已完成70%，尽量明晚完成@sunui
