### ISSUE TITLE
如何在远程服务器上运行 Jupyter Notebooks

### ISSUE THREAD

**Issue by JackEggie** [xitu/gold-miner#5558]
* 原文链接：[Running Jupyter Notebooks on Remote Servers](https://towardsdatascience.com/running-jupyter-notebooks-on-remote-servers-603fbcc256b3)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/running-jupyter-notebooks-on-remote-servers.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5576
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-4.5 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Daltan** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Daltan 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5576
