### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Graning** [xitu/gold-miner#556]
你好，Gran，软件工程大二在读，英语水平四级，常上的外国网站有 Github/Stackoverflow/Medium/Lifehacker等社区，目前每天坚持扇贝打卡[(打卡记录)](https://www.shanbay.com/checkin/user/2854624/)，有阅读原版计算机类书籍的经验，没有翻译经验，个人博客是 [gran.work](http://gran.work/)(暂时没有什么内容） 。希望能成为你们的一员。😁

PS：README.md 中的 “如何参与翻译” 第 1 项第二行出现了重复：出现了两个“英语水平”。

**Comment by antonia0912** [comment]
@Graning 欢迎来到翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群

**Comment by antonia0912** [comment]
@Graning 我刚刚去仔细看了看  没有找到你说的两个英语水平。。。。快来帮小公举指出来~

**Comment by sqrthree** [comment]
@antonia0912 我偷偷的修改了 😜
