### ISSUE TITLE
模式 — 使用 Typescript 和 Node.js 的通用仓储

### ISSUE THREAD

**Issue by JackEggie** [xitu/gold-miner#5563]
* 原文链接：[Patterns — Generic Repository with Typescript and Node.js](https://hackernoon.com/generic-repository-with-typescript-and-node-js-731c10a1b98e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/patterns-generic-repository-with-typescript-and-node-js.md)
  * PR 地址：
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Raoul1996** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Raoul1996 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5590
