### ISSUE TITLE
2019 前端工具调研

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5564]
* 原文链接：[Launching the Front-End Tooling Survey 2019](https://medium.freecodecamp.org/launching-the-front-end-tooling-survey-2019-4cb2b72f0b42)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/launching-the-front-end-tooling-survey-2019.md)
  * PR 地址：#5596
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5596

**Comment by xingqiwu55555** [comment]
校对认领
