### ISSUE TITLE
依赖注入在多模块工程中的应用

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5565]
* 原文链接：[Dependency injection in a multi module project](https://medium.com/androiddevelopers/dependency-injection-in-a-multi-module-project-1a09511c14b7)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/dependency-injection-in-a-multi-module-project.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5605
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mirosalva** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Mirosalva 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5605

**Comment by JasonLinkinBright** [comment]
校对认领
