### ISSUE TITLE
归一化和标准化 — 量化分析

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5568]
* 原文链接：[Normalization vs Standardization — Quantitative analysis](https://towardsdatascience.com/normalization-vs-standardization-quantitative-analysis-a91e8a79cebf)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/normalization-vs-standardization-quantitative-analysis.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5634
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：7-8.5 分
  * 校对积分：1.5-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ccJia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ccJia 棒极啦 :tada:

**Comment by sunui** [comment]
@ccJia 翻译的怎么样啦？

**Comment by ccJia** [comment]
我翻译完了，今天就可以上传，应该要晚上了
