### ISSUE TITLE
申请译者

### ISSUE THREAD

**Issue by neal1991** [xitu/gold-miner#557]
Hi,我是华东师大一名即将研三的学生，现在在一家公司做前端开发实习生。我本生对英语比较感兴趣，平常逛的比较多的国外网站github/quora/stachoverflow/freecodecamp,也偶尔参加过一些开源项目的翻译工作，比如djangogirls。我的个人网站是 http://neal1991.pythonanywhere.com 上面有我的csdn博客链接，里面有一些我翻译的博文，我的个人主页里面也有我的简历还有我有一篇被IEEE CEC会议接受的论文。

**Comment by antonia0912** [comment]
@neal1991 欢迎来到翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群
