### ISSUE TITLE
深度学习能力的三个等级

### ISSUE THREAD

**Issue by zhmhhu** [xitu/gold-miner#5572]
* 原文链接：[3 Levels of Deep Learning Competence](https://machinelearningmastery.com/deep-learning-competence/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/deep-learning-competence.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5653
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间： 8 天
  * 校对时间： 2 天
  * 翻译积分： 9-10 分
  * 校对积分：2-5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xionglong58** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@xionglong58 棒极啦 :tada:

**Comment by HearFishle** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@HearFishle 棒极啦 :tada:
