### ISSUE TITLE
如何让你的 CSS Grid 布局有良好可读性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5575]
* 原文链接：[How to Keep Your CSS Grid Layouts Accessible](https://webdesign.tutsplus.com/articles/a-guide-to-css-grid-and-accessibility--cms-32857)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-guide-to-css-grid-and-accessibility.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5616
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4-5 分
* 校对积分：1-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by lsvih** [comment]
文章发布的时候可以用这个作为封面大图：

![image](https://user-images.githubusercontent.com/5164225/56025274-5fec6d00-5d44-11e9-9aed-7fb9e88ae558.png)

**Comment by fanyijihua** [comment]
PR 地址：#5616

**Comment by hanxiansen** [comment]
校对认领 @leviding

**Comment by leviding** [comment]
@hanxiansen 青岛对应 PR 下认领哈
