### ISSUE TITLE
Building accessible websites and apps is a moral obligation

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5579]
* 原文链接：[Building accessible websites and apps is a moral obligation](https://machinelearningmastery.com/how-to-configure-image-data-augmentation-when-training-deep-learning-neural-networks/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/building-accessible-websites-and-apps-is-a-moral-obligation.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3-4 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lampui** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lampui 棒极啦 :tada:

**Comment by lampui** [comment]
@leviding @lsvih 请求close，感觉文章太水，没什么干货。

**Comment by leviding** [comment]
@lampui 好，辛苦啦。对了，欢迎多推荐点好英文文章，现在匮乏 2333
