### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by rottenpen** [xitu/gold-miner#558]
你好，我叫rottenpen，中山大学南方学院的准大三学生，在GCI进行暑假实习中，职位前端开发。英语基础一般，想通过翻译提高对技术类文章的阅读能力和提高个人的英文水平。最近常访问的是Github/almasaeed2010/AdminLTE。个人博客rottenpen.cn 主要是写些前端的东西。

**Comment by antonia0912** [comment]
@rottenpen 欢迎来到翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群
