### ISSUE TITLE
在深度学习训练过程中如何设置数据增强？

### ISSUE THREAD

**Issue by zhmhhu** [xitu/gold-miner#5580]
* 原文链接：[How to Configure Image Data Augmentation When Training Deep Learning Neural Networks](https://machinelearningmastery.com/how-to-configure-image-data-augmentation-when-training-deep-learning-neural-networks/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-configure-image-data-augmentation-when-training-deep-learning-neural-networks.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5635
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7.5-9 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ccJia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ccJia 棒极啦 :tada:

**Comment by zhmhhu** [comment]
翻译得怎么样啦 @ccJia

**Comment by ccJia** [comment]
翻译完了，今天可以上传，我晚上再check一遍就传
