### ISSUE TITLE
Kotlin 标准方法备忘

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5584]
* 原文链接：[Kotlin Standard Functions cheat-sheet](https://medium.com/androiddevelopers/kotlin-standard-functions-cheat-sheet-27f032dd4326)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/kotlin-standard-functions-cheat-sheet.md)
  * PR 地址：#5604
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：1 天
  * 校对时间：1 天
  * 翻译积分：1.5 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Feximin** [comment]
认领

**Comment by Feximin** [comment]
翻译认领？

**Comment by fanyijihua** [comment]
@Feximin 棒极啦 :tada:

**Comment by lsvih** [comment]
PR 地址：#5604

**Comment by Feximin** [comment]
修改完毕
