### ISSUE TITLE
使用 closest() 函数获取正确的 DOM 元素

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5588]
* 原文链接：[Using closest() to return the correct DOM element](https://allthingssmitty.com/2019/03/25/using-closest-to-return-the-correct-dom-element/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/using-closest-to-return-the-correct-dom-element.md)
  * PR 地址：#5602
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：1.5 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LucaslEliane** [comment]
@fanyijihua 翻译认领

**Comment by fanyijihua** [comment]
@LucaslEliane 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5602
