### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by c1rew** [xitu/gold-miner#559]
你好，我是c1rew，现在某安全信息相关公司工作，目前主要做Linux/Android、C/C++相关项目，英语水平毕业时是四级，不过坚持阅读听力熟悉单词，截止今天扇贝打卡785天，博客地址[c1rew.github.io](http://c1rew.github.io/)，第一篇就是之前翻译过的文章；想通过这个平台多多提高英文水平，并能及时分享给大家有用的信息，相互学习提高，谢谢。

**Comment by antonia0912** [comment]
@c1rew 欢迎来到翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群
