### ISSUE TITLE
移动界面设计的 10 项启发式原则

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5593]
* 原文链接：[10 heuristic principles for mobile interfaces](https://uxdesign.cc/heuristic-principles-for-mobile-interfaces-c226fbaa1d16)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/heuristic-principles-for-mobile-interfaces.md)
* PR 地址：#5608
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：1-2 天
* 翻译积分：6-7 分
* 校对积分：1.5-3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by HydeSong** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@HydeSong 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5607

**Comment by fanyijihua** [comment]
PR 地址：#5608
