### ISSUE TITLE
用 Flutter 打造一个圆形滑块（Slider）

### ISSUE THREAD

**Issue by DevMcryYu** [xitu/gold-miner#5597]
* 原文链接：[How to build a circular slider in Flutter](https://medium.com/@danaya/how-to-build-a-circular-slider-in-flutter-cab3fc5312df)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-build-a-circular-slider-in-flutter.md)
  * PR 地址：
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间： 4 天
  * 校对时间： 1 天
  * 翻译积分： 3-4 分
  * 校对积分： 1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DevMcryYu** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@DevMcryYu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5618
