### ISSUE TITLE
Flutter 官方中文文档译者招募中，要求中高级技术水平，英语及表达能力较好

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5601]
Flutter 官方中文文档招募译者，要求中高级技术水平，英语及表达能力较好，有感兴趣的可以在本 issue 下报名，并微信私聊 @leviding 

详情请见 👉https://github.com/cfug/flutter.cn/wiki

**Comment by dansunhappy** [comment]
报名

**Comment by leviding** [comment]
@dansunhappy 微信私聊我，我微信号是 517010193，拉微信群。

**Comment by DevMcryYu** [comment]
ding~

**Comment by leviding** [comment]
已拉群 👏
