### ISSUE TITLE
WorkManager 基础入门

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5609]
* 原文链接：[WorkManager Basics](https://medium.com/androiddevelopers/workmanager-basics-beba51e94048)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/workmanager-basics.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5696
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8 分
  * 校对积分：1.5-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gs666** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@gs666 棒极啦 :tada:

**Comment by sunui** [comment]
@gs666 翻译的怎么样啦？有没有需要帮忙的

**Comment by gs666** [comment]
> @gs666 翻译的怎么样啦？有没有需要帮忙的

最迟明天提交，最近工作突然忙起来，不好意思

**Comment by fanyijihua** [comment]
PR 地址：#5696

**Comment by Feximin** [comment]
校对

**Comment by Feximin** [comment]
认领校对？

**Comment by Feximin** [comment]
校对认领？
