### ISSUE TITLE
如何用 CSS Animations 实现图片滑动出文字

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5611]
* 原文链接：[Slide an Image to Reveal Text with CSS Animations](https://css-tricks.com/slide-an-image-to-reveal-text-with-css-animations/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/slide-an-image-to-reveal-text-with-css-animations.md)
  * PR 地址：#5758
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by sunui** [comment]
@EmilyQiRabbit 这篇怎么样啦？

**Comment by EmilyQiRabbit** [comment]
@sunui 抱歉抱歉🤣最近忽然超级忙超级忙...在翻译了嗯嗯，五一左右会上传哈。

**Comment by leviding** [comment]
@EmilyQiRabbit 这篇记得上传

**Comment by Fengziyin1234** [comment]
这篇文章又放出来了？ 如果是的话我来翻译认领

**Comment by fanyijihua** [comment]
@Fengziyin1234 棒极啦 :tada:

**Comment by leviding** [comment]
@Fengziyin1234 是哈

**Comment by fanyijihua** [comment]
PR 地址：#5758
