### ISSUE TITLE
通过 Play Cloud 的 ART 优化配置提升应用性能

### ISSUE THREAD

**Issue by JackEggie** [xitu/gold-miner#5613]
* 原文链接：[Improving app performance with ART optimizing profiles in the cloud](https://android-developers.googleblog.com/2019/04/improving-app-performance-with-art.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/improving-app-performance-with-art-optimizing-profiles-in-the-cloud.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5652
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nanjingboy** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@nanjingboy 棒极啦 :tada:

**Comment by phxnirvana** [comment]
预定校对位

**Comment by leviding** [comment]
@nanjingboy PR 后艾特一下 @phxnirvana

**Comment by fanyijihua** [comment]
PR 地址：#5652

**Comment by nanjingboy** [comment]
@phxnirvana 可以在 https://github.com/xitu/gold-miner/pull/5652 下认领校对了
