### ISSUE TITLE
在数据可视化中，我们曾经“画”下的那些错误

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5619]
* 原文链接：[Mistakes, we’ve drawn a few](https://medium.economist.com/mistakes-weve-drawn-a-few-8cdd8a42d368)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/mistakes-weve-drawn-a-few.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5717
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：1-2 天
* 翻译积分：5.5-6.5 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ccJia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ccJia 棒极啦 :tada:

**Comment by leviding** [comment]
@ccJia 这篇翻译的怎么样啦
