### ISSUE TITLE
如何处理 API 请求？你可以试试 Shoryuken 和 SQS

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#562]
原文链接：[Quickly Process API Requests with Shoryuken and SQS](https://www.sitepoint.com/quickly-process-api-requests-with-shoryuken-and-sqs/)
掘金链接：[如何处理 API 请求？你可以试试 Shoryuken 和 SQS](http://gold.xitu.io/entry/578ef229128fe10063cd84de)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/quickly-process-api-requests-with-shoryuken-and-sqs.md)
校对地址：[传送门](https://github.com/xitu/gold-miner/pull/595/files)

翻译时间：3天
校对时间：2天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by circlelove** [comment]
抢

**Comment by sqrthree** [comment]
妥妥哒~ @circlelove 时间和积分等羊姐姐稍后添加哈 ╭(′▽`)╯

**Comment by circlelove** [comment]
@sqrthree 羊三@antonia0912 也没有写啊不是出差了吗

**Comment by sqrthree** [comment]
@circlelove 😜 这个翻译进度如何了呀~~

**Comment by circlelove** [comment]
明天前交@sqrthree

**Comment by circlelove** [comment]
@sqrthree  弄完了

**Comment by rccoder** [comment]
申请校对

**Comment by sqrthree** [comment]
https://github.com/xitu/gold-miner/pull/595

**Comment by MAYDAY1993** [comment]
申请校对啦啦啦

**Comment by sqrthree** [comment]
@MAYDAY1993 妥妥哒
