### ISSUE TITLE
如何避免我作为初级开发者时所犯下的 7 个错误

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5621]
* 原文链接：[How to avoid these 7 mistakes I made as a Junior Developer](https://medium.freecodecamp.org/how-to-avoid-these-7-mistakes-i-made-as-a-junior-developer-a7f26ce0f7ed)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-avoid-these-7-mistakes-i-made-as-a-junior-developer.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5625
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by whatbeg** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@whatbeg 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5625

**Comment by Endone** [comment]
@fanyijihua 校对认领
