### ISSUE TITLE
你认为“figure”怎么用？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5622]
* 原文链接：[How do you figure?](https://www.scottohara.me/blog/2019/01/21/how-do-you-figure.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-do-you-figure.md)
  * PR 地址：#5661
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by HydeSong** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@HydeSong 棒极啦 :tada:

**Comment by HydeSong** [comment]
马上提交一版

**Comment by leviding** [comment]
不急，可以先自己检查下再 PR

**Comment by fanyijihua** [comment]
PR 地址：#5661
