### ISSUE TITLE
为什么我们要用网页端组件去构建服务器？该怎么做？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#563]
原文链接：[Server-side Web Components: How and Why?](https://scotch.io/tutorials/server-side-web-components-how-and-why)
掘金链接：[为什么我们要用网页端组件去构建服务器？该怎么做？](http://gold.xitu.io/entry/578ef5e2165abd0067433832)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/server-side-web-components-how-and-why.md)

翻译时间：3天
校对时间：2天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zhangjd** [comment]
认领

**Comment by sqrthree** [comment]
@Zhangjd 妥妥哒~ 还是老样子哈~

**Comment by Zhangjd** [comment]
这篇文章没有时间期限吗?

**Comment by sqrthree** [comment]
@antonia0912 羊姐姐快出来加时间和积分啦~

**Comment by rccoder** [comment]
申请校对
