### ISSUE TITLE
Swift 代码格式化

### ISSUE THREAD

**Issue by swants** [xitu/gold-miner#5631]
* 原文链接：[Swift Code Formatters](https://nshipster.com/swift-format)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/swift-code-formatters.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5659
* 文章分类：**iOS**
*  **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**

---

* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：7-8 分
* 校对积分：1.5-4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iWeslie** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@iWeslie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5659
