### ISSUE TITLE
我多希望在我学习 React.js 之前就已经知晓这些小窍门

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5636]
* 原文链接：[What I wish I knew when I started to work with React.js](https://medium.freecodecamp.org/what-i-wish-i-knew-when-i-started-to-work-with-react-js-3ba36107fd13)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-i-wish-i-knew-when-i-started-to-work-with-react-js.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5654
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：0.5-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xionglong58** [comment]
@sunui 翻译认领

**Comment by fanyijihua** [comment]
@xionglong58 棒极啦 :tada:
