### ISSUE TITLE
重试、超时和退避

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5637]
* 原文链接：[Retries, Timeouts and Backoff](https://namc.in/2019-04-15-retries-timeouts-backoff)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/retries-timeouts-backoff.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：1-2 天
* 翻译积分：7-8 分
* 校对积分：1.5-4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nettee** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@nettee 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5689
