### ISSUE TITLE
使用 VS Code 调试 Node.js 的超简单方法

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5638]
* 原文链接：[The Absolute Easiest Way to Debug Node.js — with VSCode](https://itnext.io/the-absolute-easiest-way-to-debug-node-js-with-vscode-2e02ef5b1bad)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-absolute-easiest-way-to-debug-node-js-with-vscode.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5700
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4-5 分
* 校对积分：1.5-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iceytea** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@iceytea 棒极啦 :tada:

**Comment by leviding** [comment]
@iceytea 翻译的怎么样啦
