### ISSUE TITLE
ES6 中 的 var、let 和 const 应该如何选择？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#564]
原文链接：[JavaScript ES6+: var, let, or const?](https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75#.jhosiskoz)
掘金链接：[ES6 中 的 var、let 和 const 应该如何选择？](http://gold.xitu.io/entry/5790ec42d342d30059c77f1c)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/javascript-es6-var-let-or-const.md)

**Comment by Graning** [comment]
文章认领

**Comment by rottenpen** [comment]
文章认领

**Comment by rottenpen** [comment]
不行就求个校对吧

**Comment by sqrthree** [comment]
@Graning 好哒~ 老样子就好了~ 积分和时间限制会在稍后添加哈

@rottenpen 表急撒，校对稍后等发完 PR 之后哈~ 😂

**Comment by sqrthree** [comment]
@rottenpen 你看，别人在 PR 下刚发就申请校对了，这就尴尬了，怎么办怎么办这可怎么办？ _(:з」∠)_ 要不让别人校对吧，下次在 PR 下申请嘛~ 蜜汁尴尬 😂
