### ISSUE TITLE
谷歌寻踪圣诞老人应用（Santa Tracker）迁移到 Android App Bundle 记录

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5641]
* 原文链接：[Google Santa Tracker — Moving to an Android App Bundle](https://medium.com/androiddevelopers/google-santa-tracker-moving-to-an-android-app-bundle-dde180716096)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/google-santa-tracker-moving-to-an-android-app-bundle.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5715
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by phxnirvana** [comment]
认领，别问我为啥，没分了。。

**Comment by phxnirvana** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@phxnirvana 棒极啦 :tada:

**Comment by sunui** [comment]
@phxnirvana Hello，翻译的怎么样啦？

**Comment by leviding** [comment]
@phxnirvana 翻译的怎么样了

**Comment by phxnirvana** [comment]
啊。。假期没看消息。。晚上传上去 @leviding @sunui

**Comment by fanyijihua** [comment]
PR 地址：#5715
