### ISSUE TITLE
Room 🔗 Coroutines

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5642]
* 原文链接：[Room 🔗 Coroutines](https://medium.com/androiddevelopers/room-coroutines-422b786dc4c5)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/room-coroutines.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5664
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：1 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Feximin** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Feximin 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5664
