### ISSUE TITLE
Elixir、Phoenix、Absinthe、GraphQL、React 和 Apollo：一次近乎疯狂的深度实践 —— 第二部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5646]
* 原文链接：[Elixir, Phoenix, Absinthe, GraphQL, React, and Apollo: an absurdly deep dive - Part 2](https://schneider.dev/blog/elixir-phoenix-absinthe-graphql-react-apollo-absurdly-deep-dive/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/elixir-phoenix-absinthe-graphql-react-apollo-absurdly-deep-dive-2.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5712
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7.5-9.5 分
  * 校对积分：2-4.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Fengziyin1234** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Fengziyin1234 棒极啦 :tada:

**Comment by Xuyuey** [comment]
@Fengziyin1234 太好了，咱俩一人一半 哈哈哈哈

**Comment by Fengziyin1234** [comment]
> @Fengziyin1234 太好了，咱俩一人一半 哈哈哈哈

嗯嗯 好咧 加油加油～ 等回头翻译好了我们可以相互 review 下～

**Comment by Fengziyin1234** [comment]
@leviding  我把电脑落在办公室了。。。我明天过去就给发不出来～

**Comment by fanyijihua** [comment]
PR 地址：#5712

**Comment by Xuyuey** [comment]
校对认领
