### ISSUE TITLE
Go 语言工具概述

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5649]
* 原文链接：[An Overview of Go's Tooling](https://www.alexedwards.net/blog/an-overview-of-go-tooling)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/an-overview-of-go-tooling.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5744
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：8-11 分
* 校对积分：2-5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iceytea** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@iceytea 棒极啦 :tada:

**Comment by leviding** [comment]
这篇有点长，辛苦啦

**Comment by sunui** [comment]
@iceytea 翻译的怎么样啦？

**Comment by iceytea** [comment]
@sunui 头两天有点事情，终于要翻译完了。今天中午提交吧~
