### ISSUE TITLE
iOS 开发，该如何解决弹窗的设计问题？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#565]
原文链接：[Preventing Popovers on Popovers](https://pspdfkit.com/blog/2016/popovers-on-popovers/)
掘金链接：[iOS 开发，该如何解决弹窗的设计问题？](http://gold.xitu.io/entry/57918629c4c9710054f56f54)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/popovers-on-popovers.md)
校对地址：[传送门](https://github.com/xitu/gold-miner/pull/572/files)

**Comment by llp0574** [comment]
get

**Comment by sqrthree** [comment]
@llp0574 好哒~ 这篇文章不太长，注意时间哈~ ╭(′▽`)╯

**Comment by llp0574** [comment]
@sqrthree 时间积分都还没贴出来哇

**Comment by sqrthree** [comment]
@llp0574 嗯，时间和积分等羊姐姐稍后添加，你先翻译好了~~

**Comment by llp0574** [comment]
@sqrthree 完成了，[PR地址](https://github.com/xitu/gold-miner/pull/572)

**Comment by yifili09** [comment]
@sqrthree 认领。

**Comment by sqrthree** [comment]
@yifili09 妥妥哒~ 校对地址在上面哈~
