### ISSUE TITLE
浅析深度学习神经网络的卷积层

### ISSUE THREAD

**Issue by zhmhhu** [xitu/gold-miner#5650]
* 原文链接：[A Gentle Introduction to Convolutional Layers for Deep Learning Neural Networks](https://machinelearningmastery.com/convolutional-layers-for-deep-learning-neural-networks/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/convolutional-layers-for-deep-learning-neural-networks.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5834
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7  天
  * 校对时间：2  天
  * 翻译积分： 7-8 分
  * 校对积分： 1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by QiaoN** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@QiaoN 棒极啦 :tada:

**Comment by QiaoN** [comment]
@leviding 为什么这篇翻译积分才2分呀？

**Comment by leviding** [comment]
@QiaoN Sorry，写错啦，已修正。

**Comment by leviding** [comment]
@QiaoN 翻译的怎么样了

**Comment by QiaoN** [comment]
@leviding 翻译一小半了，尽快翻译完，sorry

**Comment by sunui** [comment]
@QiaoN 什么进度啦？

**Comment by HearFishle** [comment]
冒昧的打扰一下这篇如果原译者没时间就交给我翻译吧@leviding

**Comment by leviding** [comment]
@HearFishle 真的感谢支持，出现这么久的超期情况，是翻译计划所杜绝的。本文译者前段时间忘了这个文章，这两天在抓紧翻译，应该今天或者明天就可以出来了。

感谢支持，这篇马上翻译好了，就这位译者翻译吧。欢迎你推荐英文文章给我，我发布给你翻译 ❤️

**Comment by HearFishle** [comment]
> @HearFishle 真的感谢支持，出现这么久的超期情况，是翻译计划所杜绝的。本文译者前段时间忘了这个文章，这两天在抓紧翻译，应该今天或者明天就可以出来了。
> 感谢支持，这篇马上翻译好了，就这位译者翻译吧。欢迎你推荐英文文章给我，我发布给你翻译 ❤️

感谢大佬的回复。刷到这个一直没有动静，就想问问。那就这么着，哈。

**Comment by QiaoN** [comment]
@HearFishle 实在对不起，最近超级忙，然后就把这篇忘了。。正在赶工中。

**Comment by fanyijihua** [comment]
PR 地址：#5834
