### ISSUE TITLE
Commit 提交指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5656]
* 原文链接：[Commit messages guide](https://github.com/RomuloOliveira/commit-messages-guide/blob/master/README.md)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/commit-messages-guide)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5688
  * 文章分类：**教程**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mirosalva** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Mirosalva 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5688
