### ISSUE TITLE
Inclusively Hidden

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5657]
* 原文链接：[Inclusively Hidden](https://www.scottohara.me/blog/2017/04/14/inclusively-hidden.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/inclusively-hidden.md)
  * PR 地址：
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Jenniferyingni** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Jenniferyingni 棒极啦 :tada:

**Comment by leviding** [comment]
@Jenniferyingni 翻译的怎么样了？

**Comment by Jenniferyingni** [comment]
不好意思，最近事情比较多，可以麻烦把这个issues重新改为等待认领的状态吗
非常抱歉

**Comment by leviding** [comment]
@Jenniferyingni 好的

**Comment by xujiujiu** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@xujiujiu 棒极啦 :tada:
