### ISSUE TITLE
理解 WebView

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5658]
* 原文链接：[Understanding WebViews](https://www.kirupa.com/apps/webview.htm)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/understanding-webviews.md)
  * PR 地址：#5769
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6-7 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoolRice** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@CoolRice 棒极啦 :tada:

**Comment by leviding** [comment]
@CoolRice 哈哈，归来啦~

**Comment by leviding** [comment]
@CoolRice 翻译的怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#5769
