### ISSUE TITLE
来谈谈 Swift 类型检查器的时间复杂度

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#566]
原文链接：[Exponential time complexity in the Swift type checker](http://www.cocoawithlove.com/blog/2016/07/12/type-checker-issues.html)
掘金链接：[来谈谈 Swift 类型检查器的时间复杂度](http://gold.xitu.io/entry/579189640a2b5800619f1f5c)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/type-checker-issues.md)
校对地址：[传送门](https://github.com/xitu/gold-miner/pull/603/files)

翻译时间：4天
校对时间：3天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Zheaoli** [comment]
收了

**Comment by sqrthree** [comment]
@Zheaoli Of course

**Comment by geeeeeeeeek** [comment]
@sqrthree 我校对

**Comment by sqrthree** [comment]
@Zheaoli 这个翻译进度如何了捏~~ 😁

**Comment by Zheaoli** [comment]
@sqrthree 周天晚上不交稿子就交头。。。

**Comment by sqrthree** [comment]
@Zheaoli 磨刀霍霍 [奸笑]

**Comment by Zheaoli** [comment]
@sqrthree 我选择交头，，这段时间家里琐事有点多，我尽力搞快搞定

**Comment by geeeeeeeeek** [comment]
@Zheaoli 哈哈哈哈哈哈哈

**Comment by Zheaoli** [comment]
@sqrthree 
@geeeeeeeeek 
死前交稿，我先去跳楼了

**Comment by sqrthree** [comment]
https://github.com/xitu/gold-miner/pull/603

**Comment by Zheaoli** [comment]
@sqrthree 二校一稿完成

**Comment by Zheaoli** [comment]
@sqrthree 校者信息添加，格式修改，请查收

**Comment by sqrthree** [comment]
@Zheaoli 妥妥哒，已经 merge 了，可以分享了哈 💯
