### ISSUE TITLE
减少 Python 中循环的使用

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5663]
* 原文链接：[Minimize for loop usage in Python](https://towardsdatascience.com/minimize-for-loop-usage-in-python-78e3bc42f03f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/minimize-for-loop-usage-in-python.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5678
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2-2.5 分
* 校对积分：0.5-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MollyAredtana** [comment]
fork 之后在仓库里搜不到此文件

**Comment by leviding** [comment]
@MollyAredtana `master/TODO1/minimize-for-loop-usage-in-python.md`

在对应路径找哈

**Comment by MollyAredtana** [comment]
我copy path 之后在fork 后的仓库里搜索，显示no matching files found呢

**Comment by lsvih** [comment]
@MollyAredtana 把 fork repo 更新一下就有了

**Comment by qiuyuezhong** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@qiuyuezhong 棒极啦 :tada:

**Comment by MollyAredtana** [comment]
@leviding 谢谢啦

**Comment by fanyijihua** [comment]
PR 地址：#5678
