### ISSUE TITLE
Structuring Your iOS App for Split Testing

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5666]
* 原文链接：[Structuring Your iOS App for Split Testing](https://heartbeat.fritz.ai/structuring-your-ios-app-for-split-testing-178eacf5aa7c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/structuring-your-ios-app-for-split-testing.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3-3.5 分
* 校对积分：0.5-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iWeslie** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@iWeslie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5667
