### ISSUE TITLE
Android Studio Project Marble: Apply Changes

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5668]
* 原文链接：[Android Studio Project Marble: Apply Changes](https://medium.com/androiddevelopers/android-studio-project-marble-apply-changes-e3048662e8cd)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/android-studio-project-marble-apply-changes.md)
  * PR 地址：
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1-2 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by qiuyuezhong** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@qiuyuezhong 棒极啦 :tada:

**Comment by sunui** [comment]
@qiuyuezhong 翻译的怎么样啦？

**Comment by qiuyuezhong** [comment]
@sunui 嗨嗨，不好意思，今天晚上应该ok

**Comment by qiuyuezhong** [comment]
目前已经翻译完成，今天晚上回去核对下格式再发出来

**Comment by fanyijihua** [comment]
PR 地址：#5742
