### ISSUE TITLE
如何在应用内设计一份调查？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#567]
原文链接：[Designing an in-app Survey](https://medium.com/budi-brain/designing-in-app-survey-6163304e88dd#.x7ux1yact)
掘金链接：[如何在应用内设计一份调查？](http://gold.xitu.io/entry/57918ba079bc440066176279)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/designing-in-app-survey.md)
校对地址：[有本事你来戳我啊](https://github.com/xitu/gold-miner/pull/583/files)

翻译时间：3天
校对时间：2天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Graning** [comment]
Get～申请认领

**Comment by rottenpen** [comment]
校对校对

**Comment by sqrthree** [comment]
@Graning 👌 还是之前的方式，还是熟悉的我们~ ┏ (゜ω゜)=☞

@rottenpen 校对莫着急啦哈，待发完 PR 之后 <(￣▽￣)>

**Comment by circlelove** [comment]
可以认领多篇？ @sqrthree

**Comment by sqrthree** [comment]
@circlelove 介个好像没有限制吧

**Comment by whyalwaysmea** [comment]
校对校对

**Comment by sqrthree** [comment]
@rottenpen @whyalwaysmea 可以校对了~ 地址在上面哈~

**Comment by sqrthree** [comment]
https://github.com/xitu/gold-miner/pull/583

**Comment by Graning** [comment]
@sqrthree    分享成功：https://gold.xitu.io/entry/579ae2a85bbb500064c9233e
