### ISSUE TITLE
使用 PyTorch 在 MNIST 数据集上进行逻辑回归

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5670]
* 原文链接：[Logistic Regression on MNIST with PyTorch](https://towardsdatascience.com/logistic-regression-on-mnist-with-pytorch-b048327f8d19)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/logistic-regression-on-mnist-with-pytorch.md)
* PR 地址：#5673 
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：0.5-1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
这篇文章正有用 👍

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5673

**Comment by lsvih** [comment]
@leviding 那我就把它翻了吧- -
