### ISSUE TITLE
使用 Python Flask 框架发布机器学习 API

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5672]
* 原文链接：[Publishing Machine Learning API with Python Flask](https://towardsdatascience.com/publishing-machine-learning-api-with-python-flask-98be46fb2440)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/publishing-machine-learning-api-with-python-flask.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5714
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：0.5-1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sisibeloved** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sisibeloved 棒极啦 :tada:

**Comment by leviding** [comment]
@sisibeloved 翻译的怎么样啦

**Comment by zhmhhu** [comment]
收回吧，我来翻译 @leviding

**Comment by leviding** [comment]
刚微信私信问了下，译者说今晚上传。感谢老哥 @zhmhhu 支持 👍

**Comment by fanyijihua** [comment]
PR 地址：#5714
