### ISSUE TITLE
现代 JavaScript 开发中的设计模式

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5675]
* 原文链接：[Design patterns in modern JavaScript development](https://levelup.gitconnected.com/design-patterns-in-modern-javascript-development-ec84d8be06ca)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/design-patterns-in-modern-javascript-development.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5729
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：1-2 天
* 翻译积分：5-6.5 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by HydeSong** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@HydeSong 棒极啦 :tada:

**Comment by HydeSong** [comment]
今晚提交一版

**Comment by fanyijihua** [comment]
PR 地址：#5729
