### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by sisibeloved** [xitu/gold-miner#5677]
+ 原文链接：[https://medium.com/building-the-system/gunicorn-3-means-of-concurrency-efbb547674b7](https://medium.com/building-the-system/gunicorn-3-means-of-concurrency-efbb547674b7)
+ 简要介绍：Gunicorn 进程启动方式原理剖析

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by lsvih** [comment]
@sisibeloved 感谢您的推荐，近期发布翻译认领 💝 近期更新译者积分时会奖励优秀英文文章推荐积分

**Comment by lsvih** [comment]
#5682
