### ISSUE TITLE
设计，其实一种获得认同感的过程

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#568]
原文链接：[Design Is Mainly About Empathy](https://trackchanges.postlight.com/design-is-mainly-about-empathy-c9d51ccb208a)
掘金链接：[设计，其实一种获得认同感的过程](http://gold.xitu.io/entry/57918e9f8ac247005f094607)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/design-is-mainly-about-empathy.md)
校对地址：[传送门](https://github.com/xitu/gold-miner/pull/574/files)

翻译时间：2天
校对时间：2天
翻译积分：5
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by rottenpen** [comment]
抢

**Comment by rottenpen** [comment]
认领认领

**Comment by Ruixi** [comment]
求校对

**Comment by sqrthree** [comment]
@rottenpen 好哒~ 文章正在路上狂奔哈，请做好迎接的准备~ 

@Ruixi 校对的莫着急啦，待译者发完 PR 之后也不迟~

**Comment by rottenpen** [comment]
@sqrthree 文章是要翻墙吗~~~

**Comment by geeeeeeeeek** [comment]
@sqrthree 我校对

**Comment by sqrthree** [comment]
@rottenpen 文章已经添加好了~ 可以翻译了哈

**Comment by wild-flame** [comment]
我也好想校对这一篇啊

**Comment by L9m** [comment]
我也好想校对这一篇啊。

**Comment by sqrthree** [comment]
@geeeeeeeeek @wild-flame 可以来校对了哈，校对地址见上面的传送门~

**Comment by sqrthree** [comment]
@L9m 抱歉哈，被他们俩先抢占了，下次赶早吧_(:з」∠)_

**Comment by Ruixi** [comment]
啊……

**Comment by wild-flame** [comment]
@sqrthree 校对完。@Ruixi 其实 Ruixi 先来的啊 (づ￣ 3￣)づ，么么哒

**Comment by geeeeeeeeek** [comment]
那我等 @rottenpen merge @wild-flame 的修改之后再校对吧。

**Comment by rottenpen** [comment]
@geeeeeeeeek 那要等我晚上回去用家里的电脑才commit了
