### ISSUE TITLE
通过优化 Gunicorn 配置提高性能

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5682]
* 原文链接：[Better performance by optimizing Gunicorn config](https://medium.com/building-the-system/gunicorn-3-means-of-concurrency-efbb547674b7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/gunicorn-3-means-of-concurrency.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5767
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3-4 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shixi-li** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@shixi-li 棒极啦 :tada:

**Comment by sunui** [comment]
@shixi-li 翻译的怎么样啦

**Comment by leviding** [comment]
@shixi-li 翻译的怎么样了？有事情延期需要及时沟通，本周末没回复就释放啦~

**Comment by fanyijihua** [comment]
PR 地址：#5767

**Comment by shixi-li** [comment]
@leviding @sunui 抱歉，提晚了。

**Comment by leviding** [comment]
@shixi-li 辛苦啦~
