### ISSUE TITLE
Web 使用 CSS Shapes 的艺术设计

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5685]
* 原文链接：[Art Direction For The Web Using CSS Shapes](https://www.smashingmagazine.com/2019/04/art-direction-for-the-web-using-css-shapes/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/art-direction-for-the-web-using-css-shapes.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5716
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：6-8 分
* 校对积分：1.5-3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xujiujiu** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@xujiujiu 棒极啦 :tada:
