### ISSUE TITLE
推荐优秀英文文章 

### ISSUE THREAD

**Issue by Chorer** [xitu/gold-miner#5692]
* 原文链接： http://dmitrysoshnikov.com/ecmascript/es6-notes-default-values-of-parameters/
* 简要介绍： 作者是Facebook知名工程师Dmitry Soshnikov，对ECMAScript规范有着优秀的
解析。本篇文章主要讲解了ES6中的参数默认值

可以的话希望我能认领翻译

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
发布 issue 了，去认领吧 https://github.com/xitu/gold-miner/issues/5702
