### ISSUE TITLE
机器学习可以建模简单的数学函数吗？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5698]
* 原文链接：[Can Machine Learning model simple Math functions?](https://towardsdatascience.com/can-machine-learning-model-simple-math-functions-d336cf3e2a78)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/can-machine-learning-model-simple-math-functions.md)
* PR 地址：#5699
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：0.5-1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Minghao23** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Minghao23 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5699
