### ISSUE TITLE
笔记 6. ES6：参数默认值

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5702]
* 原文链接：[Note 6. ES6: Default values of parameters](http://dmitrysoshnikov.com/ecmascript/es6-notes-default-values-of-parameters/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/es6-notes-default-values-of-parameters.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5703
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@Chorer 来认领吧

**Comment by Chorer** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@Chorer 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5703
