### ISSUE TITLE
开始尝试 DevOps：最适合你的是什么样的工具？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5704]
* 原文链接：[Moving to DevOps: what tools do you really need?](https://circleci.com/blog/what-tools-do-you-need-to-do-devops/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-tools-do-you-need-to-do-devops.md)
  * PR 地址：#5815
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by sunui** [comment]
@Starriers 翻译的怎么样啦

**Comment by Starriers** [comment]
这是机器人么？？

**Comment by fanyijihua** [comment]
PR 地址：#5815

**Comment by sunui** [comment]
😅不是，多有打扰啦。

**Comment by Starriers** [comment]
木事  现在还在 弄这个 有点厉害的 你
