### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by newraina** [xitu/gold-miner#5705]
- 原文链接：http://jeremymikkola.com/posts/2019_03_19_rules_for_autocomplete.html
- 简要介绍：关于自动补全交互的最佳实践，掺杂着作者的个人见解。可以分在「前端」类？虽然不是一门具体的技术，但是网页上有很多自动补全的场景，比如 Web base 的编辑器、搜索框。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢您的推荐，一会儿发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
