### ISSUE TITLE
项目世界 — 在数字设计中实现上帝模式

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5709]
* 原文链接：[Project Worlds — Achieving God Mode in Digital Design](https://uxdesign.cc/project-worlds-achieving-god-mode-in-digital-design-b7242dbe5770)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/project-worlds-achieving-god-mode-in-digital-design.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5797
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：9-10 分
* 校对积分：1.5-5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Charlo-O** [comment]
申请翻译

**Comment by fanyijihua** [comment]
@Charlo-O 棒极啦 :tada:
