### ISSUE TITLE
我们从招聘技术经理的过程中学到了什么

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5710]
* 原文链接：[What we've learned about hiring engineering managers](https://circleci.com/blog/what-we-ve-learned-about-hiring-engineering-managers/?utm_source=cooperpress&utm_medium=newsletter&utm_campaign=feb19&utm_content=javascript-weekly)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-we-ve-learned-about-hiring-engineering-managers.md)
* PR 地址：#5771
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JackEggie** [comment]
翻译认领， @fanyijihua

**Comment by fanyijihua** [comment]
@JackEggie 棒极啦 :tada:

**Comment by sunui** [comment]
@JackEggie 翻译的怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#5771
