### ISSUE TITLE
使用 Nodemailer 轻松构建能通过电子邮件的重置密码 React 应用程序

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5711]
* 原文链接：[Password Reset Emails In Your React App Made Easy with Nodemailer](https://itnext.io/password-reset-emails-in-your-react-app-made-easy-with-nodemailer-bb27968310d7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/password-reset-emails-in-your-react-app-made-easy-with-nodemailer.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5764
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：6-7 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fireairforce** [comment]
翻译认领。

**Comment by fanyijihua** [comment]
@fireairforce 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5764
