### ISSUE TITLE
自动补全规则

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5713]
* 原文链接：[Rules for Autocomplete](http://jeremymikkola.com/posts/2019_03_19_rules_for_autocomplete.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/rules-for-autocomplete.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5725
  * 文章分类：**前端/后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fireairforce** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@fireairforce 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5724

**Comment by fanyijihua** [comment]
PR 地址：#5725
