### ISSUE TITLE
Android中的简易协程：viewModelScope

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5718]
* 原文链接：[Easy Coroutines in Android: viewModelScope](https://medium.com/androiddevelopers/easy-coroutines-in-android-viewmodelscope-25bffb605471)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/easy-coroutines-in-android-viewmodelscope.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5833
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by twang1727** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@twang1727 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5833
