### ISSUE TITLE
C++ 和 Android 本地 Activity 初探

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5720]
* 原文链接：[Getting Started with C++ and Android Native Activities](https://medium.com/androiddevelopers/getting-started-with-c-and-android-native-activities-2213b402ffff)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/getting-started-with-c-and-android-native-activities.md)
  * PR 地址：#5774
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1-2 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Feximin** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Feximin 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5774
