### ISSUE TITLE
完美的 Javascript 单元测试

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5721]
* 原文链接：[The perfect JavaScript unit test](https://javascriptplayground.com/the-perfect-javascript-unit-test/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-perfect-javascript-unit-test.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5726
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Xuyuey** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Xuyuey 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5726
