### ISSUE TITLE
Swift 里的强制 @inline 注解

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5722]
* 原文链接：[The Forbidden @inline Attribute in Swift](https://swiftrocks.com/the-forbidden-inline-attribute-in-swift.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-forbidden-inline-attribute-in-swift.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5723
* 文章分类：**iOS**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3-3.5 分
* 校对积分：0.5-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iWeslie** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@iWeslie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5723
