### ISSUE TITLE
Javascript Array.push 要比 Array.concat 快 945 倍！🤯🤔

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5727]
* 原文链接：[Javascript Array.push is 945x faster than Array.concat 🤯🤔](https://dev.to/uilicious/javascript-array-push-is-945x-faster-than-array-concat-1oki)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/javascript-array-push-is-945x-faster-than-array-concat.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5739
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Xuyuey** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Xuyuey 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5739
