### ISSUE TITLE
开放讨论区：对翻译计划的建议、感受、成长和吐槽，欢迎大家畅所欲言

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5728]
开放讨论模块，在这里你可以畅所欲言 🤔

> 此外，翻译计划长期招募管理员，管理员职责详见 👉 [翻译计划管理员团队成员工作内容](https://github.com/xitu/gold-miner/wiki/%E7%BF%BB%E8%AF%91%E8%AE%A1%E5%88%92%E7%AE%A1%E7%90%86%E5%91%98%E5%9B%A2%E9%98%9F%E6%88%90%E5%91%98%E5%B7%A5%E4%BD%9C%E5%86%85%E5%AE%B9)
>
> 欢迎真正热爱翻译计划，愿意贡献，且在翻译计划中已有良好的贡献记录的小伙伴加入。有意者请微信私聊 @leviding （微信号：`517010193`）。杜绝 🙅‍♂“三天打鱼，两天晒网”

**Comment by Fengziyin1234** [comment]
哈哈哈，大家都不说话～～大家平时都在哪学习新的知识啊～有没有什么好的学习经验推荐推荐！

**Comment by Fengziyin1234** [comment]
哈哈哈，大家都不说话～～我觉得翻译计划都挺好的～我有在上面学习到很多，了解了一些基本的给 open source 做贡献的流程～我个人加入的原因是因为职业上面暂时不会有什么太大的变化，自认为自己的实力不那么强，但又希望能做些什么～ 英文上面还可以，为数不多能作出贡献的地方～所以就加入进来～也希望能认识新的朋友啊～话说。。大家平时都在哪学习新的知识啊～有没有什么好的学习经验推荐推荐！

**Comment by nettee** [comment]
翻译计划是个挺好的项目的，用 GitHub 这个平台也好。这是我第一个参与的开源项目，还巩固了一些 Git 操作的流程。还有就是不知道编辑放出来待翻译文章的流程是啥样的，有时候空闲了想找个文章翻译，发现正好当时没有能认领的，就比较难受。

**Comment by leviding** [comment]
@nettee 赞，你翻译的文章也很赞。是这样的，你提的问题有几种解决方式：

1. 有想要翻译的文章，通过点击这个链接 [通过 issue 推荐优质英文文章](https://github.com/xitu/gold-miner/issues/new?title=%E6%8E%A8%E8%8D%90%E4%BC%98%E7%A7%80%E8%8B%B1%E6%96%87%E6%96%87%E7%AB%A0&body=-%20%E5%8E%9F%E6%96%87%E9%93%BE%E6%8E%A5%EF%BC%9A%E6%8E%A8%E8%8D%90%E6%96%87%E7%AB%A0%E5%89%8D%20Google%20%E4%B8%80%E4%B8%8B%EF%BC%8C%E5%B0%BD%E9%87%8F%E4%BF%9D%E8%AF%81%E6%9C%AC%E6%96%87%E6%9C%AA%E8%A2%AB%E7%BF%BB%E8%AF%91%0A-%20%E7%AE%80%E8%A6%81%E4%BB%8B%E7%BB%8D%EF%BC%9A%E4%BB%8B%E7%BB%8D%E4%B8%80%E4%B8%8B%E5%A5%BD%E4%B8%8D%E5%A5%BD%E5%95%A6%EF%BC%8C%E6%AF%95%E7%AB%9F%E5%B0%8F%E7%BC%96%E4%B9%9F%E7%9C%8B%E4%B8%8D%E5%A4%AA%E6%87%82%E5%93%8E_(:%D0%B7%E3%80%8D%E2%88%A0)_)，可以在 issue 中告知，你想翻译这篇文章，管理员会留给你的；
2. 在微信群 @leviding 或者微信私聊 @leviding ，把文章链接给他即可；
3. 你还可以看一下管理员是怎么工作的，[管理员如何进行翻译认领的发布](https://github.com/xitu/gold-miner/wiki/%E7%BF%BB%E8%AF%91%E8%AE%A1%E5%88%92%E7%AE%A1%E7%90%86%E5%91%98%E5%9B%A2%E9%98%9F%E6%88%90%E5%91%98%E5%B7%A5%E4%BD%9C%E5%86%85%E5%AE%B9#%E7%AC%AC%E4%BA%8C%E9%83%A8%E5%88%86%E7%BF%BB%E8%AF%91%E8%AE%A4%E9%A2%86%E5%8F%91%E5%B8%83)，你可以自己按照这个说明 PR 一下想翻译的文章的 MarkDown 文件，管理员审核通过即可发布 issue 给你认领翻译啦 💯

**Comment by nettee** [comment]
> @nettee 赞，你翻译的文章也很赞。是这样的，你提的问题有几种解决方式：
> 
> 1. 有想要翻译的文章，通过点击这个链接 [通过 issue 推荐优质英文文章](https://github.com/xitu/gold-miner/issues/new?title=%E6%8E%A8%E8%8D%90%E4%BC%98%E7%A7%80%E8%8B%B1%E6%96%87%E6%96%87%E7%AB%A0&body=-%20%E5%8E%9F%E6%96%87%E9%93%BE%E6%8E%A5%EF%BC%9A%E6%8E%A8%E8%8D%90%E6%96%87%E7%AB%A0%E5%89%8D%20Google%20%E4%B8%80%E4%B8%8B%EF%BC%8C%E5%B0%BD%E9%87%8F%E4%BF%9D%E8%AF%81%E6%9C%AC%E6%96%87%E6%9C%AA%E8%A2%AB%E7%BF%BB%E8%AF%91%0A-%20%E7%AE%80%E8%A6%81%E4%BB%8B%E7%BB%8D%EF%BC%9A%E4%BB%8B%E7%BB%8D%E4%B8%80%E4%B8%8B%E5%A5%BD%E4%B8%8D%E5%A5%BD%E5%95%A6%EF%BC%8C%E6%AF%95%E7%AB%9F%E5%B0%8F%E7%BC%96%E4%B9%9F%E7%9C%8B%E4%B8%8D%E5%A4%AA%E6%87%82%E5%93%8E_(:%D0%B7%E3%80%8D%E2%88%A0)_)，可以在 issue 中告知，你想翻译这篇文章，管理员会留给你的；
> 2. 在微信群 @leviding 或者微信私聊 @leviding ，把文章链接给他即可；
> 3. 你还可以看一下管理员是怎么工作的，[管理员如何进行翻译认领的发布](https://github.com/xitu/gold-miner/wiki/%E7%BF%BB%E8%AF%91%E8%AE%A1%E5%88%92%E7%AE%A1%E7%90%86%E5%91%98%E5%9B%A2%E9%98%9F%E6%88%90%E5%91%98%E5%B7%A5%E4%BD%9C%E5%86%85%E5%AE%B9#%E7%AC%AC%E4%BA%8C%E9%83%A8%E5%88%86%E7%BF%BB%E8%AF%91%E8%AE%A4%E9%A2%86%E5%8F%91%E5%B8%83)，你可以自己按照这个说明 PR 一下想翻译的文章的 MarkDown 文件，管理员审核通过即可发布 issue 给你认领翻译啦 100

好，那我平时多寻找一些好的英文文章 😜

**Comment by leviding** [comment]
@nettee 热烈欢迎 🏃

**Comment by leviding** [comment]
> 对前端和英语很感兴趣，所以就加进来了，同时也是为了熟悉github的操作。感觉很棒啊，各个流程都把控得很好。如果翻译者和校对者之间的互相反馈可以更加即时，那就更好了。

嗯嗯，这一点是的，目前的话，可以在微信群里寻人，不知道是谁可以艾特我帮忙找，我一般都有备注可以找到的 😋

**Comment by HearFishle** [comment]
感觉奖品有些单调，种类太少。

**Comment by leviding** [comment]
> 感觉奖品有些单调，种类太少。

奖品需要公司批量采购，只会选择大多数人喜欢的奖品。另外，有什么喜欢的奖品 ，可以推荐在这，大家喜欢这个礼物的话就点个赞，不喜欢就踩一下，点赞多的会纳入下个季度的礼品采购。

**Comment by HearFishle** [comment]
> 感觉奖品有些单调，种类太少。
> 
> 奖品需要公司批量采购，只会选择大多数人喜欢的奖品。另外，有什么喜欢的奖品 ，可以推荐在这，大家喜欢这个礼物的话就点个赞，不喜欢就踩一下，点赞多的会纳入下个季度的礼品采购。

比如说移动电源啊，键盘啊，鼠标啊，u盘啊都不错。或者虚拟的游戏币什么的（比如DOTA2的本子😋)

**Comment by pdog18** [comment]
@leviding 刚刚查看了 Android 分类，看到很多 Flutter 的内容。感觉现在已经足够可以把 Flutter 单独提出来作为一个比较大的分类了？

**Comment by leviding** [comment]
> @leviding 刚刚查看了 Android 分类，看到很多 Flutter 的内容。感觉现在已经足够可以把 Flutter 单独提出来作为一个比较大的分类了？

暂时也不是说一个很大的分类，就是把 Flutter 独立出来成为一个分类运营，掘金现在很重视 Flutter 的发展，翻译计划这也有所侧重，欢迎推荐相关优质英文文章哈 😄

**Comment by pdog18** [comment]
> > @leviding 刚刚查看了 Android 分类，看到很多 Flutter 的内容。感觉现在已经足够可以把 Flutter 单独提出来作为一个比较大的分类了？
> 
> 暂时也不是说一个很大的分类，就是把 Flutter 独立出来成为一个分类运营，掘金现在很重视 Flutter 的发展，翻译计划这也有所侧重，欢迎推荐相关优质英文文章哈 😄

谢谢回复，我的意思是想说，能否在我查看 Android 优质内容的时候，不要显示 Flutter 的内容。或者我想查看 Flutter 的内容的时候，能否直接选择 Flutter 的分类，而不需要从 Android 中寻找？这是已经在计划中的吗？
感谢

**Comment by leviding** [comment]
> > @leviding 刚刚查看了 Android 分类，看到很多 Flutter 的内容。感觉现在已经足够可以把 Flutter 单独提出来作为一个比较大的分类了？
> 
> 暂时也不是说一个很大的分类，就是把 Flutter 独立出来成为一个分类运营，掘金现在很重视 Flutter 的发展，翻译计划这也有所侧重，欢迎推荐相关优质英文文章哈 😄

你是指在掘金网站里还是在翻译计划中？掘金网站暂时不会，翻译计划的在计划之中。

**Comment by EmilyQiRabbit** [comment]
礼品想要充电宝🤣～

**Comment by leviding** [comment]
> 礼品想要充电宝🤣～

同样想要的点个赞，说一下想要哪款

**Comment by EmilyQiRabbit** [comment]
> 同样想要的点个赞，说一下想要哪款

[B.Duck 小黄鸭暖手&充电宝](https://detail.tmall.com/item.htm?spm=a1z0d.6639537.1997196601.13.60027484jiCThY&id=580568205125&sku_properties=134942334:28383)

**Comment by EmilyQiRabbit** [comment]
> 同样想要的点个赞，说一下想要哪款

[罗小黑充电宝](https://detail.tmall.com/item.htm?spm=a1z10.1-b-s.w5003-18615336838.5.24c02085zhoMgH&id=558327318012&rn=631aa032e07ce59af38b0fb5b8aa9e8a&abbucket=19&skuId=3500945541253&scene=taobao_shop)

**Comment by EmilyQiRabbit** [comment]
> 同样想要的点个赞，说一下想要哪款
小黄鸭的容量太小了...只有 3800mAh，但是冬天可以暖手。罗小黑的是 6700mAh。🤣都是可爱款但是电量小啊噗...

**Comment by EmilyQiRabbit** [comment]
> 同样想要的点个赞，说一下想要哪款

小黄鸭的容量太小了...只有 3800mAh，但是冬天可以暖手。罗小黑的是 6700mAh。🤣都是可爱款但是电量小啊噗...

**Comment by HearFishle** [comment]
> 同样想要的点个赞，说一下想要哪款
> 
> 小黄鸭的容量太小了...只有 3800mAh，但是冬天可以暖手。罗小黑的是 6700mAh。🤣都是可爱款但是电量小啊噗...

小米华为这些充电宝是不是更实用呢

**Comment by EmilyQiRabbit** [comment]
> > 同样想要的点个赞，说一下想要哪款
> > 小黄鸭的容量太小了...只有 3800mAh，但是冬天可以暖手。罗小黑的是 6700mAh。🤣都是可爱款但是电量小啊噗...
> 
> 小米华为这些充电宝是不是更实用呢

那是当然的😏～哈哈～但我推荐的话还是可爱😆～

**Comment by HearFishle** [comment]
> 同样想要的点个赞，说一下想要哪款
> 小黄鸭的容量太小了...只有 3800mAh，但是冬天可以暖手。罗小黑的是 6700mAh。🤣都是可爱款但是电量小啊噗...
> 
> 小米华为这些充电宝是不是更实用呢
> 
> 那是当然的😏～哈哈～但我推荐的话还是可爱😆～

那是相当可爱😆～

**Comment by gs666** [comment]
> > 礼品想要充电宝🤣～
> 
> 同样想要的点个赞，说一下想要哪款

千万别选会爆炸的罗马仕充电宝😆

**Comment by iWeslie** [comment]
同上@nettee 嘿嘿，这也是我参加的一个超级大型的开源项目，虽然不是写代码的，但从中学到了好多，不管是Git的还是其他一些合作类的，当然技术上也有很大长进嘞。感觉参与issue讨论的人并不是很多诶，是不是还不够活跃啦，或者压根没看到

**Comment by zhenshub** [comment]
看了《中文文案排版指北》感觉里面很多东西可以通过写一个程序自动解决，这些强格式的东西我认为还是机器来做处理更加擅长。
不知道现在已经有人开发这个格式处理程序（脚本）了吗

**Comment by leviding** [comment]
> 看了《中文文案排版指北》感觉里面很多东西可以通过写一个程序自动解决，这些强格式的东西我认为还是机器来做处理更加擅长。
> 不知道现在已经有人开发这个格式处理程序（脚本）了吗

项目代码详见：https://github.com/sunui/robot
欢迎参与

**Comment by JalanJiang** [comment]
掘金翻译计划是一个非常赞的项目！参与计划两周，学习了一些 Git 基本操作流程，也第一次在 Github 上使用了 Review 功能。原本自己去阅读英文文章，经常会读到不靠谱的、质量较差的文章，而在掘金翻译计划有人帮你筛选把关，一点都不担心这一点了！

我会继续贡献微薄之力的！嘻嘻嘻下半年坐等树莓派 4 代（逃

**Comment by JackEggie** [comment]
断断续续在翻译计划贡献了一些文章，最大的感受还是通过翻译计划熟悉了 PR 的整个流程。平时我们可能忙于工作，很难参与到开源的贡献中去，而翻译计划给我们提供了一个门槛不那么高的贡献方式。

此外，还是要重点表扬翻译计划的氛围，即使学术氛围不那么浓厚，但群里讨论的大多还是技术向或翻译上的问题，在 PR 中的“商业互吹”也令我非常印象深刻。

总之，翻译计划作为一个技术组织，我作为其成员之一，持续分享是我未来会继续做的事情。毕竟，为社区做贡献是可以作为一辈子的事业的（为社会主义奉献一生 🤦‍♂ ）。

**Comment by EmilyQiRabbit** [comment]
大家都写得好认真哦
👍666...
我最开始加入掘金翻译其实就是想提高下英语 + 拓宽知识面～
平时在公司写代码写累了，就会打开 markdown 编辑器默默的翻译一会儿...
居然还有神奇的减压效果？😆
看到自己在掘金社区基本就靠着发翻译的文章收粉好多还是蛮有成就感的！
就是积分兑换的礼物希望再多一点啦，目前没看到什么特别想要的呢...
（💡❗️能不能兑换些猫零食啊🤣这样我翻译也算是在给🐱主子挣零食钱了哈哈哈
还要感谢各位耐心给我校对的小伙伴～棒棒哒！🎉@各位校对大佬
以后还要继续努力哦～💪～

**Comment by JalanJiang** [comment]
> 大家都写得好认真哦
> 👍666...
> 我最开始加入掘金翻译其实就是想提高下英语 + 拓宽知识面～
> 平时在公司写代码写累了，就会打开 markdown 编辑器默默的翻译一会儿...
> 居然还有神奇的减压效果？😆
> 看到自己在掘金社区基本就靠着发翻译的文章收粉好多还是蛮有成就感的！
> 就是积分兑换的礼物希望再多一点啦，目前没看到什么特别想要的呢...
> （💡❗️能不能兑换些猫零食啊🤣这样我翻译也算是在给🐱主子挣零食钱了哈哈哈
> 还要感谢各位耐心给我校对的小伙伴～棒棒哒！🎉@各位校对大佬
> 以后还要继续努力哦～💪～

我也有小猫咪耶嘻嘻 🐱

**Comment by EmilyQiRabbit** [comment]
> 
> 我也有小猫咪耶嘻嘻 🐱

跟我一起 @leviding 求增加猫主子零食吧🤣哈哈

**Comment by Ultrasteve** [comment]
为什么前端的文章这么多🤣

**Comment by leviding** [comment]
@leviding 马上不负责翻译计划了，会有新管理员来决策 🤣

**Comment by leviding** [comment]
@Ultrasteve 前端领得快，人多，所以文章相应也就多了
