### ISSUE TITLE
通过一些例子深入了解 JavaScript 的 Async 和 Await

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5732]
* 原文链接：[Deeply Understanding JavaScript Async and Await with Examples](https://blog.bitsrc.io/understanding-javascript-async-and-await-with-examples-a010b03926ea)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/understanding-javascript-async-and-await-with-examples.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5832
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1-2 天
  * 翻译积分：5.5-6.5 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xionglong58** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@xionglong58 棒极啦 :tada:

**Comment by sunui** [comment]
@xionglong58 Hi,这篇翻译的怎么样啦

**Comment by xionglong58** [comment]
@sunui 正抓紧翻译，不好意思
