### ISSUE TITLE
超快速的分析器（一）：优化扫描器

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5734]
* 原文链接：[Blazingly fast parsing, part 1: optimizing the scanner](https://v8.dev/blog/scanner)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/blazingly-fast-parsing-part-1-optimizing-the-scanner.md)
  * PR 地址：#5794
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1-2 天
  * 翻译积分：6-7 分
  * 校对积分：1-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nettee** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@nettee 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5794
