### ISSUE TITLE
Keras 速查表：使用 Python 构建神经网络

### ISSUE THREAD

**Issue by zhmhhu** [xitu/gold-miner#5735]
* 原文链接：[Keras Cheat Sheet: Neural Networks in Python](https://www.datacamp.com/community/blog/keras-cheat-sheet)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/keras-cheat-sheet.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5752
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Minghao23** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Minghao23 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5752
