### ISSUE TITLE
在 Google Apps 脚本中使用 ES6 和 npm 模块

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5749]
* 原文链接：[Using ES6 and npm modules in Google Apps Script](http://blog.gsmart.in/es6-and-npm-modules-in-google-apps-script/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/es6-and-npm-modules-in-google-apps-script.md)
* PR 地址：#5779
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4.5-6 分
* 校对积分：1-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xingqiwu55555** [comment]
@sunui  翻译认领

**Comment by fanyijihua** [comment]
@xingqiwu55555 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5779
