### ISSUE TITLE
用 Xamarin 和 Visual Studio 构建 iOS 应用

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#575]
原文链接：[Building iOS Apps with Xamarin and Visual Studio](https://www.raywenderlich.com/134049/building-ios-apps-with-xamarin-and-visual-studio)
掘金链接：[用 Xamarin 和 Visual Studio 构建 iOS 应用](https://gold.xitu.io/entry/57919c1a2e958a0065f37a9b)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/building-ios-apps-with-xamarin-and-visual-studio.md)
校对地址：[快来戳我](https://github.com/xitu/gold-miner/pull/582/files)

翻译时间：4天
校对时间：2天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by yifili09** [comment]
@sqrthree  认领！

**Comment by sqrthree** [comment]
@yifili09 好哒 O(∩_∩)O

**Comment by yifili09** [comment]
@sqrthree 求校对。#582

**Comment by sqrthree** [comment]
@yifili09 棒棒哒~ 翻译的这么快~

**Comment by DeadLion** [comment]
认领校对 @sqrthree

**Comment by sqrthree** [comment]
@DeadLion 妥妥哒~ 校对地址在这里哈 https://github.com/xitu/gold-miner/pull/582/files

**Comment by Graning** [comment]
校对+1

**Comment by sqrthree** [comment]
@Graning 好哒~~ 走你┏ (゜ω゜)=☞

**Comment by Graning** [comment]
@yifili09 校对完成。
