### ISSUE TITLE
帮你高效使用 VS Code 的秘诀

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5750]
* 原文链接：[Tips to use VSCode more efficiently](https://sudolabs.io/blog/tips-to-use-VSCode-more-efficiently/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/tips-to-use-VSCode-more-efficiently.md)
* PR 地址：#5757
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4.5-5.5 分
* 校对积分：1-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5757
