### ISSUE TITLE
化 Markdown 为 HTML：用 Node.js 和 Express 搭建接口

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5753]
* 原文链接：[Building A Node.js Express API To Convert Markdown To HTML](https://www.smashingmagazine.com/2019/04/nodejs-express-api-markdown-html/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/nodejs-express-api-markdown-html.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5759
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：6.5-7.5 天
* 翻译积分：2 分
* 校对积分：1.5-3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:
