### ISSUE TITLE
用 Word2vec 表示音乐？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5754]
* 原文链接：[Representing music with Word2vec?](https://towardsdatascience.com/representing-music-with-word2vec-c3c503176d52)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/representing-music-with-word2vec.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4.5-5 分
* 校对积分：1-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Minghao23** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Minghao23 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5775
