### ISSUE TITLE
最优控制：LQR

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5756]
* 原文链接：[Optimal Control: LQR](https://towardsdatascience.com/optimal-control-lqr-417b41e10d0d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/optimal-control-lqr.md)
* PR 地址：#5770
* 文章分类：**算法**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3-4 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5770
