### ISSUE TITLE
Javascript 中的对象字面量很酷，你觉得呢？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#576]
原文链接：[Why object literals in JavaScript are cool](https://rainsoft.io/why-object-literals-in-javascript-are-cool/)
掘金链接：[Javascript 中的对象字面量很酷，你觉得呢？](https://gold.xitu.io/entry/5795b19d0a2b580061c4df1a)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-object-literals-in-javascript-are-cool.md)
校对地址：[我是入口](https://github.com/xitu/gold-miner/pull/594/files)

翻译时间：3天
校对时间：2天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by neal1991** [comment]
终于抢到了

**Comment by sqrthree** [comment]
@neal1991 妥妥哒~~ 话说你是第一次翻译么？

**Comment by neal1991** [comment]
@sqrthree 是的，有什么要注意的吗

**Comment by sqrthree** [comment]
@neal1991  抱歉哈~ 新译者需要从校对文章开始 _(:з」∠)_

**Comment by neal1991** [comment]
@sqrthree 晕 不也有人是直接翻译的 只不过我实话说了而已 我觉得差别不是很大吧

**Comment by zhangchen91** [comment]
申请翻译

**Comment by antonia0912** [comment]
@neal1991 @zhangchen91 hey 哈尼们 翻译计划规定是新译者要从校对文章开始喔~校对完一篇之后就可以翻译啦~要不 你们先看看别的文章 校对一篇 怎么样思密达们~给后边的新译者做好榜样嘛么么扎~

**Comment by aleen42** [comment]
還能認領嗎？來遲一步

**Comment by sqrthree** [comment]
@aleen42 可以的~ 真是来的巧呢~

**Comment by aleen42** [comment]
@sqrthree 噗

**Comment by neal1991** [comment]
呵呵 [https://github.com/neal1991/articles-translator/blob/master/javascript中的对象字面量为啥这么酷.md](url)

**Comment by zhangchen91** [comment]
@antonia0912 我校对过了

**Comment by sqrthree** [comment]
@zhangchen91 你校对的文章是哪一篇呀？我查错了么_(:з」∠)_

**Comment by Graning** [comment]
@sqrthree 他校对的是我翻译的那篇  https://github.com/xitu/gold-miner/blob/master/TODO/javascript-es6-var-let-or-const.md
积分应该还没添加，所以你没有查到。

**Comment by sqrthree** [comment]
实在是抱歉哈，确实是我搞错了 _(:з」∠)_，沟通了下，这篇文章还是由 @aleen42 翻译，到时候 @zhangchen91 参与校对。大家辛苦了

**Comment by Graning** [comment]
吼吼  让🐑羊姐姐来添加积分吧

**Comment by sqrthree** [comment]
@Graning 你 ES6 那篇明天给你加积分哈，因为之前没有标记积分，所以一直没添加积分到 Wiki ，已经反馈过了。

**Comment by Graning** [comment]
@sqrthree   没事没事 辛苦了  ❤️ ❤️ ❤️ ❤️

**Comment by aleen42** [comment]
@zhangchen91 哥，你来吧。最近我也有点忙，给机会你好了

**Comment by zhangchen91** [comment]
提pl了

**Comment by rccoder** [comment]
申请校对

**Comment by sqrthree** [comment]
https://github.com/xitu/gold-miner/pull/594
