### ISSUE TITLE
关于 Flutter 页面路由过渡动画，你所需要知道的一切

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5760]
* 原文链接：[Everything you need to know about Flutter page route transition](https://medium.com/flutter-community/everything-you-need-to-know-about-flutter-page-route-transition-9ef5c1b32823)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/everything-you-need-to-know-about-flutter-page-route-transition.md)
  * PR 地址：#5820
  * 文章分类：**大前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by sunui** [comment]
@EmilyQiRabbit 这篇 翻译的怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#5820

**Comment by EmilyQiRabbit** [comment]
@sunui 抱歉晚了嗯嗯～已经提交～
