### ISSUE TITLE
属于 JavaScript 开发者的 Crypto 简介

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5761]
* 原文链接：[The JavaScript Developer’s Intro to Crypto](https://medium.com/the-challenge/the-javascript-developers-intro-to-crypto-3dcd7839f2e7)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-javascript-developers-intro-to-crypto.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5768
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1-2 天
  * 翻译积分：4.5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Xuyuey** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Xuyuey 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5768
