### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by Chorer** [xitu/gold-miner#5765]
- 原文链接：https://blog.bitsrc.io/understanding-mixins-in-vue-js-bdcf9e02a7c1
- 简要介绍：介绍Vue.js中的Mixins，包括其在工作流中的应用

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢您的推荐，已发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
