### ISSUE TITLE
理解 Vue.js 中的 Mixins

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5766]
* 原文链接：[Understanding Mixins in Vue JS](https://blog.bitsrc.io/understanding-mixins-in-vue-js-bdcf9e02a7c1)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/understanding-mixins-in-vue-js.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5776
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Reaper622** [comment]
@leviding  翻译认领

**Comment by fanyijihua** [comment]
@Reaper622 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5776

**Comment by yzw7489757** [comment]
@leviding  翻译认领

**Comment by leviding** [comment]
@yzw7489757 

1. 请在对应 PR 下认领校对
2. 本文的校对已被认领完
