### ISSUE TITLE
深入理解 Swift 中闭包的捕捉语义（一）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#577]
原文链接：[Closures Capture Semantics, Part 1: Catch them all!](http://alisoftware.github.io/swift/closures/2016/07/25/closure-capture-1/)
掘金链接：[深入理解 Swift 中闭包的捕捉语义（一）](https://gold.xitu.io/entry/5796308479bc440066443c8e)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/closure-capture-1.md)
校对地址：[戳我啊](https://github.com/xitu/gold-miner/pull/602/files)

**ℹ️️  本篇文章需要有 swift 语言经验的人翻译撒~**

翻译时间：3天
校对时间：2天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by yifili09** [comment]
@sqrthree  先认领吧， 都被你最后那句话忽悠到了么？ :trollface:

**Comment by wild-flame** [comment]
放着我来，正好写过 swift。

**Comment by sqrthree** [comment]
@wild-flame 棒棒哒~注意时间限制哈~

**Comment by wild-flame** [comment]
@sqrthree 好的三金。话说好长啊这篇，六分而且三天翻译完，这样真的好么= =

**Comment by sqrthree** [comment]
@wild-flame  hello, 这篇进度如何了捏？

**Comment by yifili09** [comment]
@wild-flame 还好当时没选这篇。 :trollface: :trollface:

**Comment by sqrthree** [comment]
@wild-flame 快粗来啦~~ 你是否收到了这来自远方的呼唤

**Comment by wild-flame** [comment]
@sqrthree 临时有事，申请换人

**Comment by sqrthree** [comment]
@wild-flame 好的~

**Comment by yifili09** [comment]
@sqrthree 我来接盘吧。

**Comment by sqrthree** [comment]
@yifili09 好哒~ 辛苦了哈

**Comment by yifili09** [comment]
@sqrthree #602 需要校对的小伙伴们。

**Comment by sqrthree** [comment]
@yifili09 好的，辛苦了~ 速度这么快~~

**Comment by lizwangying** [comment]
申请校对+1

**Comment by yifili09** [comment]
@sqrthree 原文作者写的太好了，不经意间就入局了。。

**Comment by lizwangying** [comment]
我校对完毕。吓屎我了，回头一看我加了好多comment都没有了，可能是译者改了吧，哈哈，
