### ISSUE TITLE
Swift 2 中为实存类型和泛型搭桥牵线

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#578]
原文链接：[Bridging Existentials & Generics in Swift 2](http://blog.benjamin-encz.de/post/bridging-existentials-generics-swift-2/)
掘金链接：[[英] Swift 2 中为实存类型和泛型搭桥牵线](https://gold.xitu.io/entry/5796347179bc440066445ff9)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/bridging-existentials-generics-swift-2.md)
校对地址：[传送门](https://github.com/xitu/gold-miner/pull/592/files)

**ℹ️️  本篇文章需要有 swift 语言经验的人翻译撒~**

翻译时间：3天
校对时间：2天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by yifili09** [comment]
@sqrthree 我还是认领这篇吧， 哈哈。

**Comment by sqrthree** [comment]
@yifili09 好的~ 注意时间限制哈~~

**Comment by yifili09** [comment]
@sqrthree 和我上次翻译的 #549 竟然是一个作者。。。

**Comment by yifili09** [comment]
@sqrthree #592 需要一波校对。

**Comment by Graning** [comment]
校对+1

**Comment by sqrthree** [comment]
@Graning 妥妥哒~ 校对地址在这哈 https://github.com/xitu/gold-miner/pull/592/files

**Comment by MAYDAY1993** [comment]
申请校对

**Comment by sqrthree** [comment]
@MAYDAY1993 好哒~

**Comment by Graning** [comment]
@yifili09 校对完成。

**Comment by MAYDAY1993** [comment]
@yifili09  校对完啦
