### ISSUE TITLE
声音设计与无声设计

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5780]
* 原文链接：[Designing Sound and Silence](https://medium.com/google-design/designing-sound-and-silence-1b9674301ec1)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/designing-sound-and-silence.md)
* PR 地址：
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：1.5-2 分
* 校对积分：0.5-1  分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CLOXnu** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@CLOXnu 棒极啦 :tada:

**Comment by CLOXnu** [comment]
初翻完成
