### ISSUE TITLE
高效地在 Flutter 中使用 BLoC 模式

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5784]
* 原文链接：[Effective BLoC pattern](https://medium.com/flutterpub/effective-bloc-pattern-45c36d76d5fe)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/effective-bloc-pattern.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5866
* 文章分类：**Flutter**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LucaslEliane** [comment]
@fanyijihua 翻译认领

**Comment by fanyijihua** [comment]
@LucaslEliane 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5866
