### ISSUE TITLE
Flutter 布局备忘录

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5787]
* 原文链接：[Flutter Layout Cheat Sheet](https://medium.com/flutter-community/flutter-layout-cheat-sheet-5363348d037e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/flutter-layout-cheat-sheet.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5896
* 文章分类：**Flutter**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2-3 分
* 校对积分：0.5-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5896

**Comment by smilemuffie** [comment]
校对认领
