### ISSUE TITLE
写给 iOS 的 ML Kit 教程：识别图像中的文字

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5788]
* 原文链接：[ML Kit Tutorial for iOS: Recognizing Text in Images](https://www.raywenderlich.com/6565-ml-kit-tutorial-for-ios-recognizing-text-in-images)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/ml-kit-tutorial-for-ios-recognizing-text-in-images.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5846
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by portandbridge** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@portandbridge 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5846

**Comment by Lobster-King** [comment]
校对认领
