### ISSUE TITLE
使用流动控制器（Flow Controller ）实现 MVVM 协议模型

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#579]
原文链接：[MVVM with Flow Controller-First Step](https://medium.com/@digoreis/mvvm-with-flow-controller-first-step-83e60ade0018)
掘金链接：[使用流动控制器（Flow Controller ）实现 MVVM 协议模型](https://gold.xitu.io/entry/5796d9b4a633bd006a5c2320)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/mvvm-with-flow-controller-first-step.md)
校对地址：[传送门](https://github.com/xitu/gold-miner/pull/596/files)

翻译时间：3天
校对时间：2天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by shixinzhang** [comment]
申请翻译~  ^_^

**Comment by siegeout** [comment]
申请校对~

**Comment by sqrthree** [comment]
@shixinzhang 好的👌 还是老样子哈~

**Comment by sqrthree** [comment]
@shixinzhang 翻译的怎么样了撒~~

**Comment by shixinzhang** [comment]
@sqrthree 周末家里有些事耽搁了，不好意思哈，刚才提交了 PR
@siegeout 可以校对了，地址是 https://github.com/xitu/gold-miner/pull/596/files ，太自信选了 iOS 相关的，翻译的时候好吃力，校对者辛苦了！

**Comment by yifili09** [comment]
@sqrthree 申请一个校对。

**Comment by rccoder** [comment]
申请校对

**Comment by sqrthree** [comment]
@siegeout 有时间校对么？
@yifili09 妥妥哒~ 
@rccoder 稍等看看 @siegeout 的回复哈~

**Comment by sqrthree** [comment]
https://github.com/xitu/gold-miner/pull/596

**Comment by sqrthree** [comment]
@rccoder 嗯。。你已经开始校对了么？那就你校对吧，以后还是以 PR 下面的先后为准好了，不然容易出现事故 _(:з」∠)_

**Comment by rccoder** [comment]
@sqrthree  对啊，就是按照 pr  来的

之前那个 @siegeout  的申请校对不是 5 天之前的吗

**Comment by sqrthree** [comment]
好的~ 没事了~ 你继续校对吧哈~

**Comment by siegeout** [comment]
@sqrthree 觉得这篇蛮有意思的，可惜没抢到文章就提前写了校对，下次会按照PR来的。

**Comment by sqrthree** [comment]
@siegeout 嗯，还是按照 PR 来吧，不然容易混乱~ 谢谢谅解哈~
