### ISSUE TITLE
Redux vs. React 的 Context API

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5792]
* 原文链接：[Redux vs. The React Context API](https://daveceddia.com/context-api-vs-redux/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/context-api-vs-redux.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5837
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Xuyuey** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Xuyuey 棒极啦 :tada:

**Comment by Xuyuey** [comment]
是不是速度很快 哈哈哈哈

**Comment by leviding** [comment]
神速！哈哈哈

**Comment by fanyijihua** [comment]
PR 地址：#5837
