### ISSUE TITLE
超快速的分析器（二）：惰性解析

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5793]
* 原文链接：[Blazingly fast parsing, part 2: lazy parsing](https://v8.dev/blog/preparser)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/blazingly-fast-parsing-part-2-lazy-parsing.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5853
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7.5-8.5 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by suhanyujie** [comment]
申请翻译 @leviding

**Comment by fanyijihua** [comment]
@suhanyujie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5853
