### ISSUE TITLE
认领文章'Absolute Beginner's Guide to Swift'

### ISSUE THREAD

**Issue by SeraZheng** [xitu/gold-miner#58]
本人从事iOS开发一年多了，因为一直维护和开发老产品，所以开发项目中一直都是在使用Objective-C语言，自从Apple提供了Swift这种新语言之后，我一直也在自学这门新语言！而且最近我也开始了分享博客得写作，大都是iOS开发相关的博客，希望可以得到这篇文章的翻译机会！

**Comment by Glowin** [comment]
你好，这篇文章已经被认领#18 并完成初稿，麻烦你能不能看看其他未被认领的文章呢？谢谢你的理解。
