### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by Baddyo** [xitu/gold-miner#5804]
- 原文链接：[https://medium.com/@devdevcharlie/things-nobody-ever-taught-me-about-css-5d16be8d5d0e](https://medium.com/@devdevcharlie/things-nobody-ever-taught-me-about-css-5d16be8d5d0e)
- 简要介绍：该文章介绍了一些CSS的冷知识。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢您的推荐，好赞的文章，最近一周发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分

**Comment by leviding** [comment]
本文已经翻译出来啦，欢迎继续推荐其他优秀译文！
https://github.com/xitu/gold-miner/blob/master/TODO1/things-nobody-ever-taught-me-about-css.md

**Comment by Baddyo** [comment]
哦哦，实在抱歉。我在百度和Google都搜索了，还真没发现，哈哈。

**Comment by leviding** [comment]
哈哈，可能还没收录就推荐了 😀 欢迎继续推荐文章哈

**Comment by suhanyujie** [comment]
@leviding 
* 推荐英文文章 https://bodil.lol/parser-combinators/
