### ISSUE TITLE
用 React 的钩子函数和调试工具提升应用性能

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5805]
* 原文链接：[Increase your App’s performance with React hooks and the React Dev Tools](https://medium.com/clever-franke/increase-your-apps-performance-with-react-hooks-and-the-react-dev-tools-bfa67e72299c)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/increase-your-apps-performance-with-react-hooks-and-the-react-dev-tools.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5818
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5813

**Comment by fanyijihua** [comment]
PR 地址：#5818
