### ISSUE TITLE
Swift 5 中的枚举冻结

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5807]
* 原文链接：[Swift 5 Frozen enums](https://useyourloaf.com/blog/swift-5-frozen-enums)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/swift-5-frozen-enums.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5808
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2.5 分
  * 校对积分：0.5-1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iWeslie** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@iWeslie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5808
