### ISSUE TITLE
为什么 HTML 中复选框样式难写 — 本文给你答案

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5809]
* 原文链接：[Styling HTML checkboxes is hard - here's why](https://areknawo.com/styling-html-checkboxes-is-hard-heres-why/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/styling-html-checkboxes-is-hard-heres-why.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5814
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jilanlan** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@jilanlan 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5814
