### ISSUE TITLE
将第三方动画库集成到项目中 —— 第 1 部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5810]
* 原文链接：[Integrating Third-Party Animation Libraries to a Project - Part 1](https://css-tricks.com/integrating-third-party-animation-libraries-to-a-project/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/integrating-third-party-animation-libraries-to-a-project-1.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5875
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6-7.5 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TUARAN** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@TUARAN 棒极啦 :tada:

**Comment by sunui** [comment]
@TUARAN Hi，翻译的怎么样啦？

**Comment by TUARAN** [comment]
@sunui 抱歉，最近有点事，翻译中，这两天就翻译出来-_-||

**Comment by fanyijihua** [comment]
PR 地址：#5875

**Comment by fanyijihua** [comment]
PR 地址：#5911
