### ISSUE TITLE
在项目中集成第三方动画库 — 第二部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5811]
* 原文链接：[Integrating Third-Party Animation Libraries to a Project - Part 2](https://css-tricks.com/integrating-third-party-animation-libraries-to-a-project/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5823
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5823
