### ISSUE TITLE
使用 What-If 工具来研究机器学习模型

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5812]
* 原文链接：[Using What-If Tool to investigate Machine Learning models.](https://towardsdatascience.com/using-what-if-tool-to-investigate-machine-learning-models-913c7d4118f)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/using-what-if-tool-to-investigate-machine-learning-models.md)
  * PR 地址：#5933
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Starriers 棒极啦 :tada:

**Comment by sunui** [comment]
@Starriers  Hi,翻译的怎么样啦

**Comment by Starriers** [comment]
@sunui  不怎么闲 等等吧

**Comment by leviding** [comment]
@Starriers 翻译的怎么样了？如果忙，可以在有空的时候认领，本文没空翻译的话可以沟通释放哈

**Comment by Starriers** [comment]
@leviding 晚上回去推送

**Comment by fanyijihua** [comment]
PR 地址：#5933
