### ISSUE TITLE
如何使用 Node.js 构建一个命令行界面（CLI）

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5817]
* 原文链接：[How to build a CLI with Node.js](https://www.twilio.com/blog/how-to-build-a-cli-with-node-js)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-build-a-cli-with-node-js.md)
* PR 地址：#5868
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4-5.5 分
* 校对积分：1-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by sunui** [comment]
@EmilyQiRabbit Hi，翻译的怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#5868

**Comment by EmilyQiRabbit** [comment]
@sunui 已提交
