### ISSUE TITLE
用 React 制作线性代数教程示例：网格与箭头

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5822]
* 原文链接：[React for Linear Algebra Examples: Grid and Arrows](https://medium.com/@geekrodion/react-for-linear-algebra-examples-grid-and-arrows-f34c07132921)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/react-for-linear-algebra-examples-grid-and-arrows.md)
* PR 地址：#5857
* 文章分类：**前端**，**算法**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：0.5-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by leviding** [comment]
这系列文章好赞 👍

**Comment by lsvih** [comment]
晚一天交

**Comment by fanyijihua** [comment]
PR 地址：#5857
