### ISSUE TITLE
时间序列分析、可视化、和使用 LSTM 预测

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5824]
* 原文链接：[Time Series Analysis, Visualization & Forecasting with LSTM](https://towardsdatascience.com/time-series-analysis-visualization-forecasting-with-lstm-77a905180eba)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/time-series-analysis-visualization-forecasting-with-lstm.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5848
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3.5-4.5 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Minghao23** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Minghao23 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5848
