### ISSUE TITLE
如何用 React Hooks 打造一个不到 100 行代码的异步表单校验库

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5826]
* 原文链接：[How I built an async form validation library in ~100 lines of code with React Hooks](https://medium.freecodecamp.org/how-i-built-an-async-form-validation-library-in-100-lines-of-code-with-react-hooks-81dbff6c4a04)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-i-built-an-async-form-validation-library-in-100-lines-of-code-with-react-hooks.md)
  * PR 地址：#5854
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4.5 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@Jerrt-FD 认领吧

**Comment by Jerry-FD** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@Jerry-FD 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5854
