### ISSUE TITLE
在 Keras 下使用自编码器分类极端稀有事件

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5827]
* 原文链接：[Extreme Rare Event Classification using Autoencoders in Keras](https://towardsdatascience.com/extreme-rare-event-classification-using-autoencoders-in-keras-a565b386f098)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/extreme-rare-event-classification-using-autoencoders-in-keras.md)
* PR 地址：#5905
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3.5-4.5 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ccJia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ccJia 棒极啦 :tada:

**Comment by sunui** [comment]
@ccJia Hi，翻译的怎么样啦
