### ISSUE TITLE
什么是 `this`？JavaScript 对象的内部工作原理

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5836]
* 原文链接：[What is `this`? The Inner Workings of JavaScript Objects](https://medium.com/javascript-scene/what-is-this-the-inner-workings-of-javascript-objects-d397bfa0708a)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-is-this-the-inner-workings-of-javascript-objects.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5850
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fireairforce** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@fireairforce 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5850
