### ISSUE TITLE
Node.js 日志记录指南

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5838]
* 原文链接：[A Guide to Node.js Logging](https://www.twilio.com/blog/guide-node-js-logging)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/guide-node-js-logging.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5864
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1-2 天
  * 翻译积分：6-7 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fireairforce** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@fireairforce 棒极啦 :tada:

**Comment by fireairforce** [comment]
翻完这两篇准备期末去了  = =

**Comment by fanyijihua** [comment]
PR 地址：#5864
