### ISSUE TITLE
如何在 Google Play 应用商店中发布 PWA

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5839]
* 原文链接：[How to Get a Progressive Web App into the Google Play Store](https://css-tricks.com/how-to-get-a-progressive-web-app-into-the-google-play-store/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-get-a-progressive-web-app-into-the-google-play-store.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5847
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5847
