### ISSUE TITLE
利用并行流渐进加载图片

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5840]
* 原文链接：[Parallel streaming of progressive images](https://blog.cloudflare.com/parallel-streaming-of-progressive-images/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/parallel-streaming-of-progressive-images.md)
  * PR 地址：#5906
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3.5-4.5 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by twang1727** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@twang1727 棒极啦 :tada:

**Comment by sunui** [comment]
@twang1727 Hi，翻译的怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#5906
