### ISSUE TITLE
从原型图到成品：步步深入 CSS 布局

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5843]
* 原文链接：[Implementing a Mockup: CSS Layout Step by Step](https://daveceddia.com/implement-a-design-with-css/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/implement-a-design-with-css.md)
* PR 地址：#5855
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：8-10 分
* 校对积分：2-5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5855
