### ISSUE TITLE
微设计系统 — 打破藩篱

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5844]
* 原文链接：[Micro Design Systems — breaking the monolith](https://uxdesign.cc/micro-design-systems-breaking-the-monolith-c2b4abcd7158)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/micro-design-systems-breaking-the-monolith.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5899
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：1-2 天
* 翻译积分：6-7 分
* 校对积分：1-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Charlo-O** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Charlo-O 棒极啦 :tada:

**Comment by sunui** [comment]
@Charlo-O Hi，翻译的怎么样啦？

**Comment by Charlo-O** [comment]
今天提交哈
