### ISSUE TITLE
推荐优秀英文文章 Learning Parser Combinators With Rust

### ISSUE THREAD

**Issue by suhanyujie** [xitu/gold-miner#5849]
- 推荐英文文章 https://bodil.lol/parser-combinators/
- 简要介绍：后端，Rust 语言，解析器相关，由浅入深地讲解，感觉很棒。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢您的推荐，已发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分

共分为四个部分，形成一个系列，逐步发布翻译认领。
