### ISSUE TITLE
通过 Rust 学习解析器组合器 — 第一部分 

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5851]
* 原文链接：[Learning Parser Combinators With Rust](https://bodil.lol/parser-combinators/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/learning-parser-combinators-with-rust-1.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5887
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8.5 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by suhanyujie** [comment]
翻译申请 @leviding

**Comment by leviding** [comment]
@suhanyujie 请阅读本 Repo 的 WIKI 中译者教程，按照教程中的规范进行认领。

**Comment by suhanyujie** [comment]
@leviding   什。。什么意思，是有哪儿不和规范吗？还请指出来。

**Comment by leviding** [comment]
@suhanyujie 不好意思，只有翻译认领和认领翻译两个关键词能成功触发认领，我刚看了下文档，是文档出了问题，现已修复。本文您已认领成功，再次说一声抱歉，辛苦了 ❤️

**Comment by fanyijihua** [comment]
PR 地址：#5887
