### ISSUE TITLE
JavaScript 线性代数：向量

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5859]
* 原文链接：[Linear Algebra: Vectors](https://medium.com/@geekrodion/linear-algebra-vectors-f7610e9a0f23)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/linear-algebra-vectors.md)
* PR 地址：#5909
* 文章分类：**前端**，**算法**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3+1 分
* 校对积分：0.5-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by lsvih** [comment]
晚一天完成

**Comment by fanyijihua** [comment]
PR 地址：#5882

**Comment by fanyijihua** [comment]
PR 地址：#5909
