### ISSUE TITLE
TypeScript 3.0: unknown 类型

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5863]
* 原文链接：[TypeScript 3.0: The unknown Type](https://mariusschulz.com/blog/typescript-3-0-the-unknown-type)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/typescript-3-0-the-unknown-type.md)
* PR 地址：#5929
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shixi-li** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@shixi-li 棒极啦 :tada:

**Comment by sunui** [comment]
Hi，翻译的怎么样了 @shixi-li

**Comment by shixi-li** [comment]
抱歉之前搞忘了，今明两日内翻译完毕。

**Comment by leviding** [comment]
好的

**Comment by fanyijihua** [comment]
PR 地址：#5929
