### ISSUE TITLE
为什么 Uber 的工程师选择了 MySQL 而不是 PostgreSQL

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#587]
原文链接：[WHY UBER ENGINEERING SWITCHED FROM POSTGRES TO MYSQL](https://eng.uber.com/mysql-migration/)
掘金链接：[为什么 Uber 的工程师选择了 MySQL 而不是 PostgreSQL](http://gold.xitu.io/entry/5799a8621532bc0060640ce8)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/mysql-migration.md)

翻译时间：4天
校对时间：2天
翻译积分：8
校对积分：2
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by edvardHua** [comment]
认领

**Comment by sqrthree** [comment]
@edvardHua 妥妥哒~ 时间和积分等 @antonia0912  羊姐姐稍后来添加哈

**Comment by yangzj1992** [comment]
这个文章貌似被高可用架构翻译过了.[链接](http://mp.weixin.qq.com/s?spm=5176.100239.blogcont58421.6.fuppWC&__biz=MzAwMDU1MTE1OQ==&mid=2653547609&idx=1&sn=cbb55ee823ddec9d98ef1fa984e001f6&scene=0#wechat_redirect)

**Comment by edvardHua** [comment]
@sqrthree @antonia0912 来看下，好像的确被翻译了，[译文](http://mp.weixin.qq.com/s?spm=5176.100239.blogcont58421.6.fuppWC&__biz=MzAwMDU1MTE1OQ==&mid=2653547609&idx=1&sn=cbb55ee823ddec9d98ef1fa984e001f6&scene=0#wechat_redirect)，好像也是在四天前发的。

**Comment by sqrthree** [comment]
我擦~ 我发的时候还专门搜了搜，当时还搜不到呢 _(:з」∠)_

**Comment by sqrthree** [comment]
@edvardHua 翻译的进度如何了？

**Comment by edvardHua** [comment]
@sqrthree 暂时只翻译了的200字左右。

**Comment by antonia0912** [comment]
@sqrthree @yangzj1992 @sqrthree 去看看他们翻译的质量怎么样 如果你们都觉得太辣鸡咱们就接着翻译 如果觉得质量还好 就不翻译了  给 @edvardHua 加两个积分 众爱卿这样处理 是否妥当？

**Comment by sqrthree** [comment]
经过沟通，该文章暂停翻译。
