### ISSUE TITLE
时间序列数据间量化同步的四种方法

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5872]
* 原文链接：[Four ways to quantify synchrony between time series data](https://towardsdatascience.com/four-ways-to-quantify-synchrony-between-time-series-data-b99136c4a9c9)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/four-ways-to-quantify-synchrony-between-time-series-data.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/6003
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by sunui** [comment]
@EmilyQiRabbit Hi,翻译的怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#6003
