### ISSUE TITLE
深入理解图片和框架的原生懒加载功能

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5873]
* 原文链接：[A Deep Dive into Native Lazy-Loading for Images and Frames](https://css-tricks.com/a-deep-dive-into-native-lazy-loading-for-images-and-frames/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-deep-dive-into-native-lazy-loading-for-images-and-frames.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5886
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5.5-6.6 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by sunui** [comment]
@Baddyo 这篇原文做了点改动，翻译前同步一下～

**Comment by Baddyo** [comment]
> @Baddyo 这篇原文做了点改动，翻译前同步一下～

收到。

**Comment by fanyijihua** [comment]
PR 地址：#5886
