### ISSUE TITLE
通过 Rust 学习解析器组合器 - 第二部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5874]
* 原文链接：[Learning Parser Combinators With Rust](https://bodil.lol/parser-combinators/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/learning-parser-combinators-with-rust-2.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5925
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by suhanyujie** [comment]
认领翻译 @leviding

**Comment by fanyijihua** [comment]
@suhanyujie 棒极啦 :tada:

**Comment by suhanyujie** [comment]
我的天，我以为跟这个系列文章的第一部分一样，有 7 天时间。。。

**Comment by leviding** [comment]
@suhanyujie 哈哈，按你节奏来

**Comment by fanyijihua** [comment]
PR 地址：#5925

**Comment by twang1727** [comment]
校对认领 @leviding
