### ISSUE TITLE
支持 JavaScript 三元运算符

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5879]
* 原文链接：[In Defense of the Ternary Statement](https://css-tricks.com/in-defense-of-the-ternary-statement/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/in-defense-of-the-ternary-statement.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5892
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3.5-4.5 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZavierTang** [comment]
翻译认领:cat::cat::cat:

**Comment by fanyijihua** [comment]
@ZavierTang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5892

**Comment by smilemuffie** [comment]
校对认领
