### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by lworld0x00** [xitu/gold-miner#588]
你好，我叫1world0x00，SICNU网络工程本科毕业，马上去UOW念Master of Computer Science。英语水平雅思阅读7，写作6，经常浏览的英文网站github/stackoverflow/各种team的blog....blog: 1world0x00.xyz。还没开学，就想翻译点东西为大家做点贡献。

**Comment by antonia0912** [comment]
@lworld0x00 欢迎来翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群
