### ISSUE TITLE
为什么我们要切换到 gRPC

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5880]
* 原文链接：[Why We’re Switching to gRPC](https://eng.fromatob.com/post/2019/05/why-were-switching-to-grpc/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-were-switching-to-grpc.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5938
  * 文章分类：**后端/前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3-3.5 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by suhanyujie** [comment]
> 翻译认领

快翻译，我要校对。你的翻译一般都很棒 ^^

**Comment by sunui** [comment]
@EmilyQiRabbit 翻译的怎么样啦

**Comment by EmilyQiRabbit** [comment]
@sunui 今天或明天就提交哈～

**Comment by EmilyQiRabbit** [comment]
> 快翻译，我要校对。你的翻译一般都很棒 ^^

哈哈哈感谢捧场～🤣忽然压力山大哈哈

**Comment by fanyijihua** [comment]
PR 地址：#5938
