### ISSUE TITLE
使用谷歌 FACETS 可视化机器学习数据集

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5881]
* 原文链接：[Visualising Machine Learning Datasets with Google’s FACETS.](https://towardsdatascience.com/visualising-machine-learning-datasets-with-googles-facets-462d923251b3)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/visualising-machine-learning-datasets-with-googles-facets.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5923
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1-2 天
* 翻译积分：4.5-5.5 分
* 校对积分：1-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by QiaoN** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@QiaoN 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5923
