### ISSUE TITLE
8 个有用的 JavaScript 技巧

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5888]
* 原文链接：[8 Useful JavaScript Tricks](https://devinduct.com/blogpost/26/8-useful-javascript-tricks)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/8-useful-javascript-tricks.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5927
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Xuyuey** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Xuyuey 棒极啦 :tada:

**Comment by Xuyuey** [comment]
不好意思啦，这几天家里有点事，可能会晚一点提交

**Comment by leviding** [comment]
好滴

**Comment by fanyijihua** [comment]
PR 地址：#5927
