### ISSUE TITLE
可维护的 ETL: 使管道更容易支持和扩展的技巧

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5890]
* 原文链接：[Maintainable ETLs: Tips for Making Your Pipelines Easier to Support and Extend](https://multithreaded.stitchfix.com/blog/2019/05/21/maintainable-etls/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/maintainable-etls.md)
  * PR 地址：#5930
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：8-9 分
  * 校对积分：1.5-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fireairforce** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@fireairforce 棒极啦 :tada:

**Comment by fireairforce** [comment]
留到周末翻译，下周考六级前的复习文章 = =

**Comment by fanyijihua** [comment]
PR 地址：#5930
