### ISSUE TITLE
JavaScript 线性代数：使用 ThreeJS 制作线性变换动画

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5895]
* 原文链接：[Linear Algebra with JavaScript: Animating Linear Transformations with ThreeJS](https://medium.com/@geekrodion/react-for-linear-algebra-examples-grid-and-arrows-fa654127c57b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/linear-algebra-animating-linear-transformations-with-threejs.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5956
* 文章分类：**前端**，**算法**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2+1 分
* 校对积分：0.5-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by lsvih** [comment]
晚一天提交

**Comment by lsvih** [comment]
抱歉有事延误了，今晚提交。

**Comment by fanyijihua** [comment]
PR 地址：#5956
