### ISSUE TITLE
认领 Android Guides - Github 

### ISSUE THREAD

**Issue by TingYa** [xitu/gold-miner#59]
我是一名在校大学生，正学习 Android，之前翻译过 <a href = "https://github.com/GDGNanyang/studyjam">Android 开发视频的中文字幕</a>
Blog: ppting.me

**Comment by Glowin** [comment]
你好，原来你是GDG字幕组的呢，欢迎欢迎。你选择的个 guide 因为是一个大的集合，里面有100多篇文章，你看看能不能和@SeniorZhai 一起合作一下呢？#13

**Comment by TingYa** [comment]
100篇啊 恐怕没有这么多时间呢 @Glowin

**Comment by Glowin** [comment]
@TingYa 所以问你能不能和@SeniorZhai 一起合作完成这个文章呢。

**Comment by TingYa** [comment]
@Glowin  那让我试试吧~ 请@SeniorZhai 多多指教

**Comment by Sausure** [comment]
这个还需要人么@Glowin

**Comment by antonia0912** [comment]
@Sausure 我们这个项目目前暂停了  sorry~~
