### ISSUE TITLE
如何在 Keras 中用 YOLOv3 进行对象检测

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5900]
* 原文链接：[How to Perform Object Detection With YOLOv3 in Keras](https://machinelearningmastery.com/how-to-perform-object-detection-with-yolov3-in-keras/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-perform-object-detection-with-yolov3-in-keras.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5961
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：1-2 天
  * 翻译积分：7-8 分
  * 校对积分：1.5-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Daltan** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Daltan 棒极啦 :tada:

**Comment by Daltan** [comment]
翻译完成 @leviding @fanyijihua

**Comment by leviding** [comment]
@Daltan PR 到翻译计划，不是你自己的 Repo，麻烦调整一下。

**Comment by fanyijihua** [comment]
PR 地址：#5941
