### ISSUE TITLE
JavaScript 简明代码 — 最佳实践

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5907]
* 原文链接：[JavaScript Clean Code - Best Practices](https://devinduct.com/blogpost/22/javascript-clean-code-best-practices)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/javascript-clean-code-best-practices.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5932
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3-4 分
* 校对积分：0.5-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xilihuasi** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@xilihuasi 棒极啦 :tada:

**Comment by leviding** [comment]
翻译的怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#5932
