### ISSUE TITLE
不到 10 分钟，让你的终端变好看

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5908]
* 原文链接：[Trick Out Your Terminal in 10 Minutes or Less](https://towardsdatascience.com/trick-out-your-terminal-in-10-minutes-or-less-ba1e0177b7df)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/trick-out-your-terminal-in-10-minutes-or-less.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5928
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：5-6 分
* 校对积分：1-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lihaobhsfer** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lihaobhsfer 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5928
