### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by fq050766** [xitu/gold-miner#591]
你好，我叫千百度。现在在广州市加减公司任职iOS工程师，英语水平过了四级，平时逛的英文网站github/stackoverflow，我的个人博客：thinkerfeng.com。以前在大学的时候翻译过四旋翼飞行器相关的文章。

**Comment by antonia0912** [comment]
@fq050766 欢迎来翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群
