### ISSUE TITLE
Xcode 和 LLDB 高级调试教程：第 1 部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5914]
* 原文链接：[Xcode and LLDB Advanced Debugging Tutorial: Part 1](https://medium.com/@fadiderias/xcode-and-lldb-advanced-debugging-tutorial-part-1-31919aa149e0)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/xcode-and-lldb-advanced-debugging-tutorial-part-1.md)
  * PR 地址：#5943
  * 文章分类：**iOS**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kirinzer** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@kirinzer 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5943
