### ISSUE TITLE
改善 Android Studio 的构建速度

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5916]
* 原文链接：[Improving build speed in Android Studio](https://medium.com/androiddevelopers/improving-build-speed-in-android-studio-3e1425274837)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/improving-build-speed-in-android-studio.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5978
* 文章分类：**Android**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3-4 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by qiuyuezhong** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@qiuyuezhong 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5978
