### ISSUE TITLE
ECMAScript 类 - 定义私有属性

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5919]
* 原文链接：[ECMAScript Classes - Keeping Things Private](https://devinduct.com/blogpost/23/ecmascript-classes-keeping-things-private)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/ecmascript-classes-keeping-things-private.md)
* PR 地址：#5942
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3-4 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZavierTang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ZavierTang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5942
