### ISSUE TITLE
Git：透过命令学概念 —— 第一部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5921]
* 原文链接：[Learn git concepts, not commands - Part 1](https://dev.to/unseenwizzard/learn-git-concepts-not-commands-4gjc)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/learn-git-concepts-not-commands-1.md)
  * PR 地址：#5963
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8.5 分
  * 校对积分：1.5-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by whatbeg** [comment]
part1是什么意思？

**Comment by leviding** [comment]
@whatbeg 系列文章的第一部分

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5963
