### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by suhanyujie** [xitu/gold-miner#5924]
- 原文链接：
    - https://www.ardanlabs.com/blog/2018/12/garbage-collection-in-go-part1-semantics.html
    - https://www.ardanlabs.com/blog/2019/05/garbage-collection-in-go-part2-gctraces.html
- 简要介绍：后端，讲的是 go 语言的垃圾回收

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by sunui** [comment]
感谢推荐，找到其他社区已有译文。是否还有必要加入？ @leviding 

- https://github.com/studygolang/GCTT/pull/1240
- https://github.com/studygolang/GCTT/pull/1231

**Comment by leviding** [comment]
@sunui Get，那就不翻译了。
@suhanyujie 欢迎继续推荐其他文章哈

**Comment by suhanyujie** [comment]
> @sunui Get，那就不翻译了。
> @suhanyujie 欢迎继续推荐其他文章哈

嗯，好的。我只 Google 了一下，没看到译文，所以就推荐了。
另外，建议把更多寻找文章是否已经被翻译的方法，写在 issue 模板中，这样我们就能自己“去重”了
