### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by JasonChengzi** [xitu/gold-miner#593]
你好，我叫Jason。北师大珠海软件工程专业，iOS开发工程师，有两年iOS开发经验。使用Swift已经有一年时间了。已经CET-6。业余中英翻译、写手。简书地址：http://www.jianshu.com/users/c6d724983e68

**Comment by antonia0912** [comment]
@JasonChengzi 欢迎来翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群
