### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by suhanyujie** [xitu/gold-miner#5936]
- 原文链接：https://divan.dev/posts/flutter_go/
- 简要介绍：关于移动端，后端。用 Golang 替代 Dart 实现 Flutter 的思路。

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by leviding** [comment]
感谢您的推荐，已发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
