### ISSUE TITLE
npm 的经济风云 —— 上半部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5940]
* 原文链接：[The economics of package management](https://github.com/ceejbot/economics-of-package-management/blob/master/essay.md)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-economics-of-package-management-1.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/6031
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：6.5-7.5 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6031
