### ISSUE TITLE
Python 实现排序算法

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5946]
* 原文链接：[Sorting Algorithms in Python](https://stackabuse.com/sorting-algorithms-in-python/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/sorting-algorithms-in-python.md)
* PR 地址：#6004
* 文章分类：**算法**，**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：1-2 天
* 翻译积分：6 分
* 校对积分：2-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fireairforce** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@fireairforce 棒极啦 :tada:

**Comment by sunui** [comment]
@fireairforce Hi，翻译的怎么样啦

**Comment by fireairforce** [comment]
快翻译完了，i am sorry,最近是真的比较忙 = =

**Comment by fanyijihua** [comment]
PR 地址：#6004
