### ISSUE TITLE
感受 4px 基线网格带来的便利

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5948]
* 原文链接：[The 4px baseline grid — the present](https://uxdesign.cc/the-4px-baseline-grid-89485012dea6)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-4px-baseline-grid-the-present.md)
* PR 地址：#5971
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3-4 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mcskiller** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Mcskiller 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5971
