### ISSUE TITLE
在 Python 中过度使用列表解析器和生成表达式

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5952]
* 原文链接：[Overusing list comprehensions and generator expressions in Python](https://treyhunner.com/2019/03/abusing-and-overusing-list-comprehensions-in-python/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/abusing-and-overusing-list-comprehensions-in-python.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6059
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4-5 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ccJia** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ccJia 棒极啦 :tada:

**Comment by sunui** [comment]
@ccJia Hi，翻译的怎么样啦

**Comment by sunui** [comment]
@ccJia Hi，什么进度了？要是还没翻译就释放啦

**Comment by ccJia** [comment]
@sunui 不好意思，今天可以搞完，最近新项目太忙了。。。
