### ISSUE TITLE
Android 数据绑定库  — 从可观察域到 LiveData 仅需两步

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5953]
* 原文链接：[Android Data Binding Library — From Observable Fields to LiveData in two steps](https://medium.com/androiddevelopers/android-data-binding-library-from-observable-fields-to-livedata-in-two-steps-690a384218f2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/android-data-binding-library-from-observable-fields-to-livedata-in-two-steps.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/5981
* 文章分类：**Android**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：0.5-1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gs666** [comment]
翻译认领@leviding

**Comment by fanyijihua** [comment]
@gs666 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5981
