### ISSUE TITLE
线性代数：矩阵基本运算

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5958]
* 原文链接：[Linear Algebra: Basic Matrix Operations](https://medium.com/swlh/linear-algebra-basic-matrix-operations-13a019633c15)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/linear-algebra-basic-matrix-operations.md)
* PR 地址：#5995
* 文章分类：**前端**，**算法**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2+1 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by lsvih** [comment]
明天提交

**Comment by fanyijihua** [comment]
PR 地址：#5995
