### ISSUE TITLE
思考实践：用 Go 实现 Flutter

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5966]
* 原文链接：[Thought Experiment: Flutter in Go](https://divan.dev/posts/flutter_go/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/flutter_go.md)
  * PR 地址：#6005
  * 文章分类：**Flutter**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：9-11 分
  * 校对积分：2.5-6 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by suhanyujie** [comment]
认领翻译 @leviding

**Comment by fanyijihua** [comment]
@suhanyujie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6005
