### ISSUE TITLE
JavaScript 中 JSON.stringify 的帕累托法则手册

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5967]
* 原文链接：[The 80/20 Guide to JSON.stringify in JavaScript](http://thecodebarbarian.com/the-80-20-guide-to-json-stringify-in-javascript.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-80-20-guide-to-json-stringify-in-javascript.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/6006
  * 文章分类：**前端/后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：1-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Jerry-FD** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@Jerry-FD 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6006
