### ISSUE TITLE
在 npm 上启用现在 JavaScript

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5969]
* 原文链接：[Enabling Modern JavaScript on npm](https://jasonformat.com/enabling-modern-js-on-npm/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/enabling-modern-js-on-npm.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6019
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：5.5-6.5 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mirosalva** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Mirosalva 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6019
