### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by lizwangying** [xitu/gold-miner#597]
您好，我叫王颖，英文名Liz，现在在两只老虎理财公司担任Android开发。英语六级水平，经常访问Github/Stackoverflow/，我的博客是http://lizwangying.github.io/ 希望加入翻译计划。

**Comment by antonia0912** [comment]
@lizwangying 欢迎来翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群
