### ISSUE TITLE
WebSockets 与长轮询的较量

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5972]
* 原文链接：[WebSockets vs Long Polling](https://www.ably.io/blog/websockets-vs-long-polling/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/websockets-vs-long-polling.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/5988
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JalanJiang** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@JalanJiang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#5988
