### ISSUE TITLE
Web 流式文字排版的现状

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#5973]
* 原文链接：[The State of Fluid Web Typography](https://betterwebtype.com/articles/2019/05/14/the-state-of-fluid-web-typography/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-state-of-fluid-web-typography.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6071
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：7-8 分
* 校对积分：2-4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Jenniferyingni** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Jenniferyingni 棒极啦 :tada:

**Comment by sunui** [comment]
Hi, @Jenniferyingni  翻译的怎么样啦？

**Comment by Jenniferyingni** [comment]
本周能完成 @sunui

**Comment by sunui** [comment]
@Jenniferyingni 什么进度了，抓紧啦

**Comment by fanyijihua** [comment]
PR 地址：#6071
