### ISSUE TITLE
区域设置更改和 AndroidViewModel 反面模式

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5975]
* 原文链接：[Locale changes and the AndroidViewModel antipattern](https://medium.com/androiddevelopers/locale-changes-and-the-androidviewmodel-antipattern-84eb677660d9)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/locale-changes-and-the-androidviewmodel-antipattern.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6080
* 文章分类：**Android**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：0.5-1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by solerji** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@solerji 棒极啦 :tada:
