### ISSUE TITLE
贫困线下的软件

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5977]
* 原文链接：[SOFTWARE BELOW THE POVERTY LINE](https://staltz.com/software-below-the-poverty-line.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/software-below-the-poverty-line.md)
  * PR 地址：#6026
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6-7 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Charlo-O** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Charlo-O 棒极啦 :tada:
