### ISSUE TITLE
推荐前端优秀英文文章

### ISSUE THREAD

**Issue by Chorer** [xitu/gold-miner#5979]
- 原文链接：https://blog.bitsrc.io/understanding-higher-order-components-in-react-12de3ab2cca5?
- 简要介绍：前端 ，介绍 React 中的高阶组件

-------
请完成并勾选一下三项：
* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他有序英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by leviding** [comment]
感谢您的推荐，已发布翻译认领 https://github.com/xitu/gold-miner/issues/5990  :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
