### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by JefferyFan** [xitu/gold-miner#598]
你好，我叫范杰。现在在广州市UC浏览器任职iOS工程师，英语水平过了六级，平时逛的英文网站github/stackoverflow/apple developer/objc.io，我的个人博客：[Jeffery's Blog](http://blog.duxevr.com/)。

以前翻译过一篇安卓相关的文章：[Android开发之最佳实践](http://blog.duxevr.com/2015/01/31/Translation/BestPraticeOfAndroidDev/)

**Comment by antonia0912** [comment]
@JefferyFan hey 欢迎来掘金翻译计划玩  请加我微信 antonia0912 备注github ID 我来拉你进译者群
