### ISSUE TITLE
Comparing the Same Project in Rust, Haskell, C++, Python, Scala and OCaml - Part 1

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5983]
* 原文链接：[Comparing the Same Project in Rust, Haskell, C++, Python, Scala and OCaml](http://thume.ca/2019/04/29/comparing-compilers-in-rust-haskell-c-and-python/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/comparing-compilers-in-rust-haskell-c-and-python-1.md)
  * PR 地址：
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：2-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
这篇译文已经有了 CSDN 翻译的： https://www.chainnews.com/articles/283625889219.htm
关闭啦
