### ISSUE TITLE
推荐后端/Rust英文文章

### ISSUE THREAD

**Issue by krircc** [xitu/gold-miner#5987]
- 原文链接：https://chilimatic.hashnode.dev/threads-in-rust-cjwmbxw9e003pzjs19n7pa0bt
- 简要介绍：该文全面介绍操作系统CPU，内存，进程，线程，协程到Rust线程，API使用，特点分类值得阅读分享
---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他有序英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by leviding** [comment]
感谢您的推荐，近期安排发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
