### ISSUE TITLE
移动开发中的极简化设计艺术

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#599]
原文链接：[The Art of Minimalism in Mobile App UI Design](http://babich.biz/the-art-of-minimalism-in-mobile-app-ui-design/)
掘金链接：[移动开发中的极简化设计艺术](http://gold.xitu.io/entry/579ebfce79bc440054853aa6/)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-art-of-minimalism-in-mobile-app-ui-design.md)
校对地址：[戳戳戳](https://github.com/xitu/gold-miner/pull/610/files)

翻译时间：3天
校对时间：2天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by edvardHua** [comment]
来一发

**Comment by Graning** [comment]
Get~

**Comment by sqrthree** [comment]
@edvardHua 妥妥哒~~

**Comment by jiaowoyongqi** [comment]
校对占坑！[捂脸跑

**Comment by Graning** [comment]
校对+1

**Comment by lizwangying** [comment]
加对+1

**Comment by Graning** [comment]
@jiaowoyongqi    我被你拐跑了，原来还没提交😂  我就说校对找不到

**Comment by owenlyn** [comment]
不是有PR才能抢校对嘛 🏃

**Comment by sqrthree** [comment]
@edvardHua 这篇文章翻译的进度如何了呀？:bomb:

**Comment by edvardHua** [comment]
@sqrthree 周末翻译的差不多了，明天发PR。

**Comment by edvardHua** [comment]
@sqrthree 七夕一发PR。

**Comment by owenlyn** [comment]
@edvardHua @sqrthree 七夕抢一发校对

**Comment by sqrthree** [comment]
https://github.com/xitu/gold-miner/pull/610

**Comment by jiaowoyongqi** [comment]
求校对入口！

**Comment by sqrthree** [comment]
@jiaowoyongqi 好的~ 地址已经添加在上面了哈

**Comment by owenlyn** [comment]
@sqrthree 校对完啦~~

**Comment by jiaowoyongqi** [comment]
@sqrthree 校对完成~校对到一半发现已经有两个小伙伴校对过了= =，但还是完成了校对。建议下次在放校对地址的时候可以艾特一下校对者。然后我再也不提前占坑了_(:зゝ∠)_
