### ISSUE TITLE
理解 React 中的高阶组件

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5990]
* 原文链接：[Understanding Higher-Order Components in React](https://blog.bitsrc.io/understanding-higher-order-components-in-react-12de3ab2cca5)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/understanding-higher-order-components-in-react.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/6014
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1-1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
@leviding 文件地址似乎有问题哦？

**Comment by leviding** [comment]
@EmilyQiRabbit 好了

**Comment by ZavierTang** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@ZavierTang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6014
