### ISSUE TITLE
使用 Gomobile 和 Gopherjs 的动态二维码数据传输

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#5992]
* 原文链接：[Animated QR data transfer with Gomobile and Gopherjs](https://divan.dev/posts/animatedqr/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/animated-qr-data-transfer-with-gomobile-and-gopherjs.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/6096
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by sunui** [comment]
@EmilyQiRabbit Hi，翻译的怎么样啦

**Comment by EmilyQiRabbit** [comment]
@sunui 还在翻译，后端的内容比较生疏，翻译比较慢🐶

**Comment by fanyijihua** [comment]
PR 地址：#6096
