### ISSUE TITLE
Threads in rust

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#5999]
* 原文链接：[Threads in rust](https://chilimatic.hashnode.dev/threads-in-rust-cjwmbxw9e003pzjs19n7pa0bt)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/threads-in-rust.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：9-11 分
* 校对积分：3-6 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JackEggie** [comment]
翻译认领 @fanyijihua

**Comment by fanyijihua** [comment]
@JackEggie 棒极啦 :tada:

**Comment by sunui** [comment]
@JackEggie Hi,翻译的怎么样啦？

**Comment by JackEggie** [comment]
不好意思，最近有点忙，今明两天抽空搞定。

**Comment by JackEggie** [comment]
@sunui 不好意思，最近太忙没时间翻译了，帮忙释放一下吧。 😂

**Comment by leviding** [comment]
已有译文 https://github.com/rustlang-cn/nutrition/issues/2
