### ISSUE TITLE
如何提高安卓代码的质量和语法

### ISSUE THREAD

**Issue by crackhy** [xitu/gold-miner#6]
在读机械电子工程研究生，熟悉C++编程，英语已过六级，平时给极客学院做Wiki编辑，熟悉Github和Markdown的使用。我有能力完成此篇文字的翻译工作。

**Comment by Glowin** [comment]
哎呀，你来晚了一点点，这篇文章两分钟前被[申请翻译<如何提高安卓代码的质量和语法> · Issue #5 · xitu/gold-miner](https://github.com/xitu/gold-miner/issues/5) 认领。

要不你换一篇其他的？

**Comment by crackhy** [comment]
苹果正在带坏整个设计圈

**Comment by Glowin** [comment]
好的，我给你加进 README 了
