### ISSUE TITLE
认领 教程 里的《Pokedex.org 给宠物小精灵爱好者的 web app 的技术选型》这篇文章翻译

### ISSUE THREAD

**Issue by RobertWang** [xitu/gold-miner#60]
认领 教程 里的《Pokedex.org 给宠物小精灵爱好者的 web app 的技术选型》这篇文章翻译
introducing-pokedex-org.md

**Comment by Glowin** [comment]
好的，这篇文章很赞啊，欢迎来翻译 :+1:

**Comment by RobertWang** [comment]
感觉贴过来的时候，有很多markdown语法上的问题。参照原文调整了一下，翻译的不好，参与一下。另外再问一下，怎样参与审核？如何审核？

**Comment by Glowin** [comment]
直接在 #84 里面留言选审核的文章就好，然后在选好的文章的 PR 里面直接添加 note 就行。
