### ISSUE TITLE
等不及集成 iOS 10 新特性？如何在应用维护与新特性集成之间找到平衡点

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#600]
原文链接：[Simultaneous Xcode 7 and Xcode 8 compatibility](http://radex.io/xcode7-xcode8/)
掘金链接：[等不及集成 iOS 10 新特性？如何在应用维护与新特性集成之间找到平衡点](http://gold.xitu.io/entry/579eb866d342d300571d6544/)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/xcode7-xcode8.md)
校对地址：[你敢点一个试试](https://github.com/xitu/gold-miner/pull/611/files)

翻译时间：3天
校对时间：2天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by lizwangying** [comment]
申请认领文章

**Comment by sqrthree** [comment]
@lizwangying 好哒~ 请问你这是第一次参与翻译计划么？

**Comment by lizwangying** [comment]
是的，是我第一次翻译😄，今晚尽量完成，如果不行您可以再找另外的大神翻译😄😄😄

**Comment by sqrthree** [comment]
@lizwangying 如果是第一次参与计划的话要从校对文章开始哟~~ 校对过文章之后才能认领翻译任务捏

**Comment by lizwangying** [comment]
好的，那我看一看校对文章，谢谢，打扰了

**Comment by sqrthree** [comment]
恩恩，你可以看一下流程指南哈~ [如何参与翻译](https://github.com/xitu/gold-miner#如何参与翻译)

**Comment by circlelove** [comment]
抢地主

**Comment by lizwangying** [comment]
好的我去看看，哈哈，翻倍！

**Comment by yifili09** [comment]
@circlelove 你叫了几分？我叫2分。 :trollface:

**Comment by lizwangying** [comment]
我申请审阅！哈哈

**Comment by sqrthree** [comment]
@circlelove 妥妥哒~ 归你了~

**Comment by sqrthree** [comment]
@lizwangying 校对要在等译者发 PR 之后再申请哈~╭(′▽`)╯

**Comment by lizwangying** [comment]
好的，时刻关注。

**Comment by sqrthree** [comment]
@circlelove 这篇文章的进度如何了呀？

**Comment by circlelove** [comment]
@sqrthree  我检查遍先～

**Comment by sqrthree** [comment]
https://github.com/xitu/gold-miner/pull/611

**Comment by yifili09** [comment]
@sqrthree 认领校对一个！

**Comment by MAYDAY1993** [comment]
申请校对啦啦啦

**Comment by sqrthree** [comment]
@yifili09 @MAYDAY1993 好哒~~

**Comment by circlelove** [comment]
@sqrthree 校对过了//
