### ISSUE TITLE
设计师如何成长为 Leader？

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6008]
* 原文链接：[How can a Designer become a Leader?](https://uxdesign.cc/how-can-a-designer-become-a-leader-90860a8a9bb)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-can-a-designer-become-a-leader.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6021
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：6-7 分
* 校对积分：1.5-3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TiaossuP** [comment]
@fanyijihua 认领翻译
虽然是标题是设计，不过内容与设计专业关系不大，讲的都是一些较为普遍的东西

**Comment by fanyijihua** [comment]
@TiaossuP 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6021
