### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by lijingpeng** [xitu/gold-miner#601]
Hi，我是蔬菜，在国内一家大型互联网公司工作，硕士学历，喜欢开源社区，现申请成为译者

**Comment by antonia0912** [comment]
@lijingpeng 之前有翻译过类似的英文文章吗 请问有没有个人博客呀

**Comment by lijingpeng** [comment]
之前有翻译过一些开源库的文档，有个人博客，可以看一下我的github主页，求关注啊

**Comment by antonia0912** [comment]
@lijingpeng 请加我微信 antonia0912 备注 github id 我来拉你进译者群
