### ISSUE TITLE
使用 Swift 5 构建一个 iOS 移动端群聊应用程序

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6010]
* 原文链接：[How to Build an iOS Mobile Group Chat App with Swift 5](https://www.pubnub.com/blog/how-to-build-ios-mobile-group-chat-app-swift-5-pubnub/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-build-ios-mobile-group-chat-app-swift-5-pubnub.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6084
* 文章分类：**iOS**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：8-10 分
* 校对积分：3-6 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LucaslEliane** [comment]
@fanyijihua 翻译认领

**Comment by fanyijihua** [comment]
@LucaslEliane 棒极啦 :tada:

**Comment by sunui** [comment]
@LucaslEliane Hi，什么进度啦

**Comment by LucaslEliane** [comment]
@sunui 抱歉，最近业务需求比较多。。已经完成一半了，这周末会 PR 上来

**Comment by fanyijihua** [comment]
PR 地址：#6084
