### ISSUE TITLE
推荐算法/其他优秀英文文章

### ISSUE THREAD

**Issue by JalanJiang** [xitu/gold-miner#6020]
- 原文链接：http://stevehanov.ca/blog/?id=132
- 简要介绍：业务中，我们通常使用 A/B Test 来测试哪一种实现更加有效。本文提出了另一种新的算法，可以同时测试 n 个选项，还能随意添加和删减选项。

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by leviding** [comment]
感谢您的推荐，近期发布翻译认领 :gift_heart: 近期更新译者积分时会奖励优秀英文文章推荐积分
