### ISSUE TITLE
微前端：未来前端开发的新趋势 — 第二部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6023]
* 原文链接：[Micro Frontends](https://martinfowler.com/articles/micro-frontends.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/micro-frontends-2.md)
  * PR 地址：#6068
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：5.5-7 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lihaobhsfer** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lihaobhsfer 棒极啦 :tada:

**Comment by sunui** [comment]
@lihaobhsfer 翻译的怎么样啦

**Comment by lihaobhsfer** [comment]
抱歉最近学校暑期临近期末事情有点多，预计还需一天
