### ISSUE TITLE
微前端：未来前端开发的新趋势 — 第三部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6024]
* 原文链接：[Micro Frontends](https://martinfowler.com/articles/micro-frontends.html)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/micro-frontends-3.md)
  * PR 地址：#6067
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5-6 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xilihuasi** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@xilihuasi 棒极啦 :tada:

**Comment by sunui** [comment]
@xilihuasi 翻译的怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#6067
