### ISSUE TITLE
敏捷也许是个问题

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6035]
* 原文链接：[Maybe Agile Is the Problem](https://www.infoq.com/articles/agile-agile-blah-blah/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/agile-agile-blah-blah.md)
* PR 地址：#6105
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4-5 分
* 校对积分：1-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Charlo-O** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Charlo-O 棒极啦 :tada:

**Comment by leviding** [comment]
@Charlo-O 翻译的怎么样啦，提交前记得检查好格式等细节问题哈

**Comment by Charlo-O** [comment]
@leviding  最近有点忙，要延期几天，不好意思(T ^ T)，

**Comment by leviding** [comment]
@Charlo-O 👌
