### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by lifajian** [xitu/gold-miner#604]
西大非计算机专业本硕，现在**程序员客栈**做运营。在校期间考过GRE，学过TOEFL，参加笔译培训，之前翻译的内容主要是商业类的，比如合同、信件。在校也帮别人翻译过自己专业的文献。工作后翻译的文章主要是互联网科技类的，所以常浏览的主要是techcrunch， quartz, theme等。没有博客，只有知乎专栏 https://zhuanlan.zhihu.com/intech-porter  #。专栏里翻译的文章《实现人类登月梦想的代码》《现今硅谷最酷的CEO系列1-7》《苹果的钱都去哪儿了》《预测分析如何预知数据泄露》。一般情况下，一天内就可以翻译出一篇文章。代码虽然不太懂，但目前对前后端语言都大致了解了，完全可以试试，我认为可以搞定的。我的个人微信 18702308145 Schuller

**Comment by antonia0912** [comment]
@lifajian 欢迎来翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群

**Comment by fanyijihua** [comment]
PR 地址：#6098
