### ISSUE TITLE
自托管你的静态资源

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6040]
* 原文链接：[Self-Host Your Static Assets](https://csswizardry.com/2019/05/self-host-your-static-assets/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/self-host-your-static-assets.md)
* PR 地址：#6060
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：5-6 分
* 校对积分：1-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by twang1727** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@twang1727 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6060
