### ISSUE TITLE
使用 Node.js 读取超大的文件（第一部分）

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6044]
* 原文链接：[Using Node.js to Read Really, Really Large Files (Pt 1)](https://itnext.io/using-node-js-to-read-really-really-large-files-pt-1-d2057fe76b33)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/using-node-js-to-read-really-really-large-files-pt-1.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6157
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4-5 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LucaslEliane** [comment]
@fanyijihua 翻译认领

**Comment by fanyijihua** [comment]
@LucaslEliane 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6156

**Comment by fanyijihua** [comment]
PR 地址：#6157

**Comment by LucaslEliane** [comment]
烦请按照#6157 的 PR 来进行校对认领，之前的 PR commit 记录有些混乱，已经 close 了。
