### ISSUE TITLE
胜者是 Stream：NodeJS 读取大数据集合几种方法的性能比较

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6046]
* 原文链接：[Streams For the Win: A Performance Comparison of NodeJS Methods for Reading Large Datasets (Pt 2)](https://itnext.io/streams-for-the-win-a-performance-comparison-of-nodejs-methods-for-reading-large-datasets-pt-2-bcfa732fa40e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/streams-for-the-win-a-performance-comparison-of-nodejs-methods-for-reading-large-datasets-pt-2.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6264
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4.5-5.5 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LucaslEliane** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@LucaslEliane 棒极啦 :tada:

**Comment by LucaslEliane** [comment]
@fanyijihua 翻译认领

**Comment by sunui** [comment]
@LucaslEliane Hi,翻译的怎么样啦

**Comment by sunui** [comment]
@LucaslEliane Hi，翻译到什么进度了？

**Comment by LucaslEliane** [comment]
@sunui 不好意思，这两天工作比较忙，今晚会提交 PR 上去~

**Comment by LucaslEliane** [comment]
@sunui 已提交 PR
