### ISSUE TITLE
Android 模拟器：Project Marble 中的改进

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6047]
* 原文链接：[Android Emulator : Project Marble Improvements](https://medium.com/androiddevelopers/android-emulator-project-marble-improvements-1175a934941e)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/android-emulator-project-marble-improvements.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/6134
  * 文章分类：**Android**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by qiuyuezhong** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@qiuyuezhong 棒极啦 :tada:

**Comment by sunui** [comment]
@qiuyuezhong Hi,翻译的怎么样啦？

**Comment by fanyijihua** [comment]
PR 地址：#6134

**Comment by qiuyuezhong** [comment]
> @qiuyuezhong Hi,翻译的怎么样啦？

不好意思延期了，刚翻译完，谢谢
