### ISSUE TITLE
如何运用最新的技术提升网页速度和性能

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#605]
原文链接：[Why our website is faster than yours](https://www.voorhoede.nl/en/blog/why-our-website-is-faster-than-yours/)
掘金链接：[如何运用最新的技术提升网页速度和性能](http://gold.xitu.io/entry/579ed0741532bc0060878049)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-our-website-is-faster-than-yours.md)
校对地址：[😏](https://github.com/xitu/gold-miner/pull/613/files)

翻译时间：3天
校对时间：2天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by hpoenixf** [comment]
报名翻译

**Comment by sqrthree** [comment]
@hpoenixf 好哒~~ 时间和积分稍后添加哈。

**Comment by shixinzhang** [comment]
@sqrthree @antonia0912 你们不觉得改成 PR 后再认领校对体验太差了吗？ 
本来文章就少，等到一篇合适新文章要好久。 : (
好不容易等到了，因为比别人慢一点，就得再等好几天才能申请校对，中间这个过程需要重复查看 N 次。太累了吧！！！ T.T

期待改善

**Comment by hpoenixf** [comment]
可以改成译者翻译好主动通知校对者..

**Comment by yifili09** [comment]
随缘。

**Comment by hpoenixf** [comment]
翻译完成

**Comment by sqrthree** [comment]
https://github.com/xitu/gold-miner/pull/613

**Comment by sqrthree** [comment]
@shixinzhang @yifili09 文章已经翻译好了，快去 PR 下申请校对哈~ 暂时还是以 PR 下的时间为准。

**Comment by MAYDAY1993** [comment]
认领校对啦啦啦

**Comment by sqrthree** [comment]
@shixinzhang 如果改成先在 issus 下占坑的话，有可能会出现前几天认领了，然后译者发 PR 之后忘了这茬的情况，导致延误周期，也影响别人的认领。 理解下哈 ❤️❤️❤️

**Comment by MAYDAY1993** [comment]
最近的校对地址怎么这么任性啊
