### ISSUE TITLE
Kubernetes 儿童插图指南

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6052]
* 原文链接：[The Illustrated Children’s Guide to Kubernetes](https://www.cncf.io/the-childrens-illustrated-guide-to-kubernetes/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-childrens-illustrated-guide-to-kubernetes.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6061
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JalanJiang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@JalanJiang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6061
