### ISSUE TITLE
使用 SVG 和 Vue.Js 构建动态树图

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6054]
* 原文链接：[Building a Dynamic Tree Diagram with SVG and Vue.Js](https://medium.com/@krutie/building-a-dynamic-tree-diagram-with-svg-and-vue-js-a5df28e300cd)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/building-a-dynamic-tree-diagram-with-svg-and-vue-js.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6075
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：6-7 分
* 校对积分：1-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@YueYongDev 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6075
