### ISSUE TITLE
Git：透过命令学概念 —— 第二部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6057]
* 原文链接：[Learn git concepts, not commands](https://dev.to/unseenwizzard/learn-git-concepts-not-commands-4gjc)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/learn-git-concepts-not-commands-2.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/6113
  * 文章分类：**其他**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-8 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Mirosalva** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Mirosalva 棒极啦 :tada:

**Comment by sunui** [comment]
@Mirosalva  Hi,翻译的怎么样啦

**Comment by Mirosalva** [comment]
今天提交呀

**Comment by fanyijihua** [comment]
PR 地址：#6113
