### ISSUE TITLE
产品设计怎样做才最优雅

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#606]
原文链接：[How To Make Your Not-So-Great Visual Design Better](https://medium.com/facebook-design/how-to-make-your-not-so-great-visual-design-better-67972eee3825#.4e6hpsbkz)
掘金链接：[如何改进你的产品视觉设计？](http://gold.xitu.io/entry/57a81fd7c4c971005a2d70bb)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-make-your-not-so-great-visual-design-better.md)
校对地址：[你想干啥？](https://github.com/xitu/gold-miner/pull/612/files)

翻译时间：3天
校对时间：2天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by lizwangying** [comment]
文章认领+1

**Comment by sqrthree** [comment]
@lizwangying 妥妥哒~

**Comment by Velacielad** [comment]
预定个校对～

**Comment by JolsonZhu** [comment]
这里也预定个校对~

**Comment by sqrthree** [comment]
@Velacielad @JolsonZhu 这个译者已经发 PR 了，快到 https://github.com/xitu/gold-miner/pull/612 下申请哈，为了避免混乱，最终以 PR 下的顺序为准。
