### ISSUE TITLE
推广 PWA 安装的模式（移动端）

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6064]
* 原文链接：[Patterns for Promoting PWA Installation](https://developers.google.com/web/fundamentals/app-install-banners/promoting-install-mobile?hl=zh-cn)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/promoting-install-mobile.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6087
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：1-2 天
* 翻译积分：5-6 分
* 校对积分：2-4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xutaogit** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@xutaogit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6087
