### ISSUE TITLE
如何开发一款高度模块化的 Android APP？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#607]
原文链接：[Creating Highly Modular Android Apps](https://medium.com/stories-from-eyeem/creating-highly-modular-android-apps-933271fbdb7d#.oez87prl8)
掘金链接：[如何开发一款高度模块化的 Android APP？](http://gold.xitu.io/entry/57a86b266be3ff006544e9af)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/creating-highly-modular-android-apps.md)
PR 地址：[嗯，换我了](https://github.com/xitu/gold-miner/pull/624)

翻译时间：3天
校对时间：2天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Graning** [comment]
get～

**Comment by sqrthree** [comment]
@Graning 👋

**Comment by sqrthree** [comment]
调整为 @DeadLion 翻译。

**Comment by sqrthree** [comment]
@DeadLion 这篇翻译的进度如何啦 ╭(′▽`)╯

**Comment by DeadLion** [comment]
@sqrthree 翻译完成 
[校稿地址](https://github.com/xitu/gold-miner/pull/624)

**Comment by sqrthree** [comment]
@DeadLion 好哒~ 辛苦啦

**Comment by hackerkevin** [comment]
校对认领
