### ISSUE TITLE
设计任何图表的六项原则

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6073]
* 原文链接：[Six Principles for Designing Any Chart](https://medium.com/google-design/redefining-data-visualization-at-google-9bdcf2e447c6)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/redefining-data-visualization-at-google.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6083
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MarchYuanx** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MarchYuanx 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6082

**Comment by fanyijihua** [comment]
PR 地址：#6083
