### ISSUE TITLE
申请翻译 《secret-of-good-electron-apps》

### ISSUE THREAD

**Issue by Jerry-FD** [xitu/gold-miner#6074]
- 原文链接：https://jlongster.com/secret-of-good-electron-apps
- 简要介绍：优秀的 electron 应用的秘密，简要介绍了搭建一个优秀的 electron 应用需要注意的地方

---

### 请完成并勾选一下三项：

* [x] 推荐前端
* [x] 自己翻译
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by sunui** [comment]
@Jerry-FD 不错的文章，不过 InfoQ 有一篇翻译了哦 https://www.infoq.cn/article/x0mysTBGoiF_jQGEJLNf 欢迎继续推荐其他文章
