### ISSUE TITLE
Web 端的 SwiftUI：SwiftWebUI

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6076]
* 原文链接：[The missing ☑️: SwiftWebUI](http://www.alwaysrightinstitute.com/swiftwebui/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/swiftwebui.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6125
* 文章分类：**iOS**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：1-2 天
* 翻译积分：5-6 分
* 校对积分：2-4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6125
