### ISSUE TITLE
Medium 内部使用 css/less 的代码风格指南

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#608]
原文链接：[ LESS Coding Guidelines](https://gist.github.com/fat/a47b882eb5f84293c4ed)
掘金链接：[Medium 内部使用 css/less 的代码风格指南](http://gold.xitu.io/entry/57a859472e958a0066ad643b)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/less-coding-guidelines.md)
校对地址：[没错，我就是](https://github.com/xitu/gold-miner/pull/618/files)

翻译时间：3天
校对时间：2天
翻译积分：5
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Graning** [comment]
get～

**Comment by DeadLion** [comment]
认领

**Comment by sqrthree** [comment]
@Graning 你这是同时认领两篇么？要不要这么拼嘛~~ 也给别人条活路撒~ 😜

**Comment by Graning** [comment]
@sqrthree  我这篇算了，这个我比较熟悉一些。那篇给别人吧。

**Comment by Graning** [comment]
@DeadLion   哥，你看看这个怎么样 https://github.com/xitu/gold-miner/issues/607
如果你熟悉的话，你去翻译这篇。

**Comment by sqrthree** [comment]
@Graning 好的，那这篇就交给你咯~ 
@DeadLion 你看看那一篇然后给我回复下哈~

**Comment by DeadLion** [comment]
@sqrthree 好的，android 那篇给我。都没写多少积分？

**Comment by sqrthree** [comment]
@DeadLion 好的~ 积分稍后羊姐姐添加哈~

**Comment by sqrthree** [comment]
PR 地址： https://github.com/xitu/gold-miner/pull/618
