### ISSUE TITLE
2019 年的 Android 网络 —— Retrofit 与 Kotlin 协程

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6086]
* 原文链接：[Android Networking in 2019 — Retrofit with Kotlin’s Coroutines](https://android.jlelse.eu/android-networking-in-2019-retrofit-with-kotlins-coroutines-aefe82c4d777)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/android-networking-in-2019-retrofit-with-kotlins-coroutines.md)
* PR 地址：#6147
* 文章分类：**Android**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3-3.5 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Feximin** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Feximin 棒极啦 :tada:

**Comment by sunui** [comment]
@Feximin Hello，翻译什么进度啦

**Comment by fanyijihua** [comment]
PR 地址：#6147
