### ISSUE TITLE
申请译者

### ISSUE THREAD

**Issue by cbangchen** [xitu/gold-miner#609]
您好！我叫SuperBang，华南师范大学／信息工程学院，现在在广州科腾公司担任iOS开发工程师。英语六级，Stackoverflow/Github等社区必须的啦，还有Dribble，兼有一点设计能力。希望加入翻译计划！互相学习！如果可以加入，我可以翻译内容为Objective-C,Swift,Python的文章。个人博客：cbang.info。

**Comment by antonia0912** [comment]
@cbangchen 欢迎来翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群
