### ISSUE TITLE
Go 语言概览

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6103]
* 原文链接：[A bird's eye view of Go](https://blog.merovius.de/2019/06/12/birdseye-go.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/birdseye-go.md)
* PR 地址：#6175
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：5.5-6.5 分
* 校对积分：1.5-3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JackEggie** [comment]
翻译认领 @fanyijihua

**Comment by fanyijihua** [comment]
@JackEggie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6175
