### ISSUE TITLE
使用 Cypress 进行 React 应用的端到端测试

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6106]
* 原文链接：[End to End Testing React Apps With Cypress](https://blog.bitsrc.io/testing-react-apps-with-cypress-658bc482678)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/testing-react-apps-with-cypress.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6137
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3-4 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Stevens1995** [comment]
@leviding 翻译认领。

**Comment by fanyijihua** [comment]
@Stevens1995 棒极啦 :tada:

**Comment by yzw7489757** [comment]
@leviding 校对认领

**Comment by leviding** [comment]
@yzw7489757 请到对应 PR 下认领校对，本次认领位置错误，认领无效。
