### ISSUE TITLE
Kotlin Clean 架构

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6108]
* 原文链接：[Kotlin Clean Architecture](https://proandroiddev.com/kotlin-clean-architecture-1ad42fcd97fa)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/kotlin-clean-architecture.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6135
* 文章分类：**Android**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JasonWu1111** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@JasonWu1111 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6135
