### ISSUE TITLE
在 Reddit 讨论中看到的 GraphQL 现状

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6109]
* 原文链接：[The state of GraphQL by Reddit](https://blog.graphqleditor.com/the-state-of-graphql-by-reddit/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-state-of-graphql-by-reddit.md)
* PR 地址：#6140
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4.5-5.5 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TiaossuP** [comment]
@fanyijihua 翻译认领

**Comment by fanyijihua** [comment]
@TiaossuP 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6140
