### ISSUE TITLE
喷泉码和动态二维码

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6115]
* 原文链接：[Fountain codes and animated QR](https://divan.dev/posts/fountaincodes/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/fountaincodes.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6166
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：5-6 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6166
