### ISSUE TITLE
仅使用 HTML 和 CSS 创建多级嵌套弹出式导航菜单

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6118]
* 原文链接：[Creating a multi-level hierarchical flyout navigation menu using only HTML and CSS](https://www.ghosh.dev/posts/creating-a-multi-level-hierarchical-flyout-navigation-menu-using-only-html-and-css/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/creating-a-multi-level-hierarchical-flyout-navigation-menu-using-only-html-and-css.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6154
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4-4.5 分
* 校对积分：1.5-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yzw7489757** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@yzw7489757 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6149

**Comment by fanyijihua** [comment]
PR 地址：#6154
