### ISSUE TITLE
多网站项目的 CSS 架构

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6120]
* 原文链接：[CSS Architecture for Multiple Websites](https://medium.com/@elad/css-architecture-for-multiple-websites-ad696c9d334)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/css-architecture-for-multiple-websites.md)
* PR 地址：#6215
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunshine940326** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sunshine940326 棒极啦 :tada:

**Comment by sunui** [comment]
@sunshine940326 Hi, 翻译的怎么样了

**Comment by sunui** [comment]
@sunshine940326  这篇什么进度 ，再不回应也要释放啦

**Comment by leviding** [comment]
@sunui @sunshine940326 已释放

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6215
