### ISSUE TITLE
How Google Pagespeed works: Improve Your Score and Search Engine Ranking

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6122]
* 原文链接：[How Google Pagespeed works: Improve Your Score and Search Engine Ranking](https://calibreapp.com/blog/how-pagespeed-works/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-pagespeed-works.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6153
* 文章分类：**前端 后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1-2 天
* 翻译积分：4-5 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Jerry-FD** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@Jerry-FD 棒极啦 :tada:
