### ISSUE TITLE
数据科学家需要掌握的十种统计技术

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6131]
* 原文链接：[The 10 Statistical Techniques Data Scientists Need to Master](https://medium.com/cracking-the-data-science-interview/the-10-statistical-techniques-data-scientists-need-to-master-1ef6dbd531f7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-10-statistical-techniques-data-scientists-need-to-master.md)
* PR 地址：#6194
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：7-8.5 分
* 校对积分：2-4.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by HearFishle** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@HearFishle 棒极啦 :tada:

**Comment by sunui** [comment]
@HearFishle Hi,翻译的怎么样啦？

**Comment by HearFishle** [comment]
> @HearFishle Hi,翻译的怎么样啦？

翻译完了，今晚整合一下就提上去。
