### ISSUE TITLE
XGBoost 算法万岁！

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6132]
* 原文链接：[XGBoost Algorithm: Long May She Reign!](https://towardsdatascience.com/https-medium-com-vishalmorde-xgboost-algorithm-long-she-may-rein-edd9f99be63d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/xgboost-algorithm-long-may-she-reign.md)
* PR 地址：#6247
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4-4.5 分
* 校对积分：1.5-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by lsvih** [comment]
晚上提交。

**Comment by lsvih** [comment]
今天提交。。

**Comment by JackEggie** [comment]
@lsvih 翻译的如何啦 😂

**Comment by lsvih** [comment]
@JackEggie 稍候上传。。。

**Comment by fanyijihua** [comment]
PR 地址：#6247
