### ISSUE TITLE
101 Tips For Being A Great Programmer (& Human)

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6133]
* 原文链接：[101 Tips For Being A Great Programmer (& Human)](https://dev.to/emmawedekind/101-tips-for-being-a-great-programmer-human-36nl)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/101-tips-for-being-a-great-programmer-human.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4-5 分
* 校对积分：1.5-3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunshine940326** [comment]
认领

**Comment by sunshine940326** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sunshine940326 棒极啦 :tada:

**Comment by sl2782087** [comment]
没想到掘金翻译计划里面有，我个人翻译了这篇，并发在了掘金。 https://juejin.im/post/5d2d8d3ff265da1b8467189a

**Comment by leviding** [comment]
@sunshine940326 本文的翻译进度怎么样了呢？如果翻译差不多了， @sl2782087 您是否可以来校对呢，如果没开始或者刚开始翻译，那就可以先不翻译了呢。

**Comment by sunui** [comment]
@sunshine940326  这篇延期过久  而且已经有了翻译，所以关闭啦。
