### ISSUE TITLE
这样做才能设计出更好的数据表

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#614]
原文链接：[Design Better Data Tables](https://medium.com/mission-log/design-better-data-tables-430a30a00d8c#.ju6qcpd2c)
掘金链接：[这样做才能设计出更好的数据表](http://gold.xitu.io/entry/57ab07cb165abd006179b466)
Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/design-better-data-tables.md)
校对地址：[别点我 o(>﹏<)o](https://github.com/xitu/gold-miner/pull/623/files)

翻译时间：3天
校对时间：2天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by yifili09** [comment]
@sqrthree 认领。

**Comment by sqrthree** [comment]
@yifili09 好的~

**Comment by yifili09** [comment]
@sqrthree #623 

这文章读的真累。。 校对，要辛苦了。

**Comment by sqrthree** [comment]
@yifili09 辛苦了❤️❤️❤️
