### ISSUE TITLE
响应式设计的基本原则

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6142]
* 原文链接：[Responsive design ground rules](https://polypane.rocks/blog/responsive-design-ground-rules/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/responsive-design-ground-rules.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6150
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3-4 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Pingren** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Pingren 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6150
