### ISSUE TITLE
CSS 开发必知必会的 16 个调试工具技巧

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6144]
* 原文链接：[16 DevTools tips and tricks every CSS developer needs to know](https://www.heartinternet.uk/blog/16-devtools-tips-and-tricks-every-css-developer-need-to-know/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/16-devtools-tips-and-tricks-every-css-developer-need-to-know.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6180
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4.5-6 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yzw7489757** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@yzw7489757 棒极啦 :tada:

**Comment by Usey95** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Usey95 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6180

**Comment by Baddyo** [comment]
认领校对。
