### ISSUE TITLE
给安全定时器设计模式

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#615]
* 原文链接：[Design patterns for safe timer usage](http://www.cocoawithlove.com/blog/2016/07/30/timer-problems.html)
* 掘金链接：[给安全定时器设计模式](http://gold.xitu.io/entry/57ab05942e958a0066cba774)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/timer-problems.md)
* 校对地址：[没错，就是我](https://github.com/xitu/gold-miner/pull/619/files)

翻译时间：3天
校对时间：2天
翻译积分：7
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by mypchas6fans** [comment]
没人抢？我来

**Comment by sqrthree** [comment]
@mypchas6fans 妥妥哒~~

**Comment by sqrthree** [comment]
PR 地址：https://github.com/xitu/gold-miner/pull/619
