### ISSUE TITLE
通过阅读源码提高您的 JavaScript 水平

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6152]
* 原文链接：[Improve Your JavaScript Knowledge By Reading Source Code](https://www.smashingmagazine.com/2019/07/javascript-knowledge-reading-source-code/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/javascript-knowledge-reading-source-code.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/6179
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：5-7 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MarchYuanx** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MarchYuanx 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6179

**Comment by smilemuffie** [comment]
校对认领
