### ISSUE TITLE
通过 Rust 学习解析器组合器 — 第四部分

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6155]
* 原文链接：[Learning Parser Combinators With Rust](https://bodil.lol/parser-combinators/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/learning-parser-combinators-with-rust-4.md)
  * PR 地址：https://github.com/xitu/gold-miner/pull/6266
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：6 天
  * 校对时间：4.5-6 天
  * 翻译积分：2 分
  * 校对积分：1-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by 40m41h42t** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@40m41h42t 棒极啦 :tada:

**Comment by todaycoder001** [comment]
翻译认领

**Comment by leviding** [comment]
@todaycoder001 本文正在校对，没有翻译认领。
