### ISSUE TITLE
CSS 的书写模式

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#616]
* 原文链接：[CSS Writing Mode](https://ishadeed.com/article/css-writing-mode/)
* 掘金链接：[CSS 的书写模式](http://gold.xitu.io/entry/57ab0c32165abd006179dbdb)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/css-writing-mode.md)
* PR 地址：[点我](https://github.com/xitu/gold-miner/pull/628)

翻译时间：3天
校对时间：1天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by huanglizhuo** [comment]
领认 @sqrthree

**Comment by sqrthree** [comment]
@huanglizhuo 好哒~~

**Comment by huanglizhuo** [comment]
翻译完成 [pr](https://github.com/xitu/gold-miner/pull/628)请求校对
@sqrthree

**Comment by sqrthree** [comment]
@huanglizhuo 妥妥哒~
