### ISSUE TITLE
如何用 JavaScript 编写扫雷游戏

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6160]
* 原文链接：[How To Build Minesweeper With JavaScript](https://mitchum.blog/how-to-build-minesweeper-with-javascript/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-build-minesweeper-with-javascript.md)
* PR 地址：#6260
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：5.5-7 分
* 校对积分：1.5-3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Pingren** [comment]
最后一段：
> Update (7/13/2019): This post became more popular than I thought it would, which is awesome! I’ve received a lot of great feedback from readers about areas that could be improved. I work daily in a code base that until recently was stuck in Internet Explorer quirks mode. Many of my daily habits there transferred to my work on minesweeper, resulting in some code that doesn’t take advantage of the bleeding edge of JavaScript technology. At some point I would like to do another post where I refactor the code. I plan to remove jQuery entirely and use the ES6 syntax instead of the ES5 syntax where appropriate. But you don’t have to wait for me! See if you can make these changes yourself! And let me know how it goes in the comments.

At some point I would like to do another post where I refactor the code. I plan to remove jQuery entirely and use the ES6 syntax instead of the ES5 syntax where appropriate.

也就是说作者很可能会写一个新帖重构代码（采用 ES6 语法并去掉 JQuery），所以是不是再等等，翻译作者的新帖比较好。@leviding

**Comment by leviding** [comment]
@Pingren 可以，那先关了，等有新的再开。

**Comment by leviding** [comment]
@Pingren Reopen 了，因为作者也说没必要等他， 不知道他啥时候才会做 🤣

**Comment by Pingren** [comment]
> @Pingren Reopen 了，因为作者也说没必要等他， 不知道他啥时候才会做 🤣

你指的是这句？

> But you don’t have to wait for me! See if you can make these changes yourself! And let me know how it goes in the comments.

是想让英文读者自己动手尝试迁移到 ES6，并且在原文下面评论。

翻译文章比改代码麻烦，所以作为等等党我还是继续等着😂

**Comment by ZavierTang** [comment]
翻译认领 ✌️

**Comment by fanyijihua** [comment]
@ZavierTang 棒极啦 :tada:

**Comment by ZavierTang** [comment]
@leviding 作者贴的代码都是截图，翻译的时候可不可以把它改成 MarkDown 形式的代码呢？

我觉得这样更方便各位掘友们 Ctrl-C Ctrl-V

**Comment by leviding** [comment]
@ZavierTang 你可以在校对、管理员 review 均完成，在 merge 前将其改为 markdown 格式，否则影响校对。

**Comment by ZavierTang** [comment]
> @ZavierTang 你可以在校对、管理员 review 均完成，在 merge 前将其改为 markdown 格式，否则影响校对。

🙆‍♂
