### ISSUE TITLE
申请译者

### ISSUE THREAD

**Issue by Kulbear** [xitu/gold-miner#617]
你好我是Kulbear，加拿大Alberta大学本科CS毕业，现在在实习，即将读研。之前也经常会翻译一些个人觉得好的东西，目前在公司实习，希望用课余时间来做一些翻译的东西，主要是觉得翻译的同时自己吸收的也更透彻一些。个人比较擅长Java Python 网页前后端 函数式编程 机器学习（主要是图像）都有项目／实习经验

个人博客 kulbear.github.io

不过因为hexo的markdown格式和简书不太一样很多没有po在上面 

微信457536691

**Comment by antonia0912** [comment]
@Kulbear 欢迎来翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群
