### ISSUE TITLE
后端：Uber 架构师分享如何运行一个大型分发系统的经验

### ISSUE THREAD

**Issue by Glowin** [xitu/gold-miner#6171]
- 原文链接：https://blog.pragmaticengineer.com/operating-a-high-scale-distributed-system/
- 简要介绍：Uber 架构师分享如何运行一个大型分发系统的经验

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [ ] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by leviding** [comment]
感谢您的推荐，马上发布翻译认领 :gift_heart:
