### ISSUE TITLE
如何使用 Keras 训练目标检测模型

### ISSUE THREAD

**Issue by zhmhhu** [xitu/gold-miner#6173]
* 原文链接：[How to Train an Object Detection Model with Keras](https://machinelearningmastery.com/how-to-train-an-object-detection-model-with-keras/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-train-an-object-detection-model-with-keras.md)
* PR 地址：#6269
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：10天
* 校对时间：3 天
* 翻译积分：11-14 分
* 校对积分：3-8 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by sunui** [comment]
@EmilyQiRabbit  翻译的怎么样啦？这篇好长

**Comment by EmilyQiRabbit** [comment]
> @EmilyQiRabbit 翻译的怎么样啦？这篇好长

是的呀好长哦🤣翻译一多半了，预计还要 2-3 天吧～

**Comment by EmilyQiRabbit** [comment]
终于完成了天啦噜～

**Comment by EmilyQiRabbit** [comment]
@sunui 写错了 id。。。这篇状态还是「正在翻译」
