### ISSUE TITLE
可靠地运维一个大型分布式系统：我的学习实践

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6177]
* 原文链接：[Operating a Large, Distributed System in a Reliable Way: Practices I Learned](https://blog.pragmaticengineer.com/operating-a-high-scale-distributed-system/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/operating-a-high-scale-distributed-system.md)
* PR 地址：#6259
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：10-12 分
* 校对积分：3-6 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Pingren** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Pingren 棒极啦 :tada:

**Comment by Pingren** [comment]
@leviding 刚刚翻译的过程中突然发现，这篇文章已经被翻译过了。

https://www.jdon.com/52796

**Comment by leviding** [comment]
@Pingren 咱们继续翻译
