### ISSUE TITLE
译文的代码有漏

### ISSUE THREAD

**Issue by raylhx** [xitu/gold-miner#6178]
原文地址：https://blog.sessionstack.com/how-javascript-works-event-loop-and-the-rise-of-async-programming-5-ways-to-better-coding-with-2f077c4438b5

对应翻译文章：[JavaScript 是如何工作的: 事件循环和异步编程的崛起 + 5个如何更好的使用 async/await 编码的技巧](https://github.com/xitu/gold-miner/blob/master/TODO/how-javascript-works-event-loop-and-the-rise-of-async-programming-5-ways-to-better-coding-with.md#5-%E4%B8%AA%E7%BC%96%E5%86%99%E5%8F%AF%E7%BB%B4%E6%8A%A4%E7%9A%84%E5%81%A5%E5%A3%AE%E7%9A%84%E5%BC%82%E6%AD%A5%E4%BB%A3%E7%A0%81%E7%9A%84%E6%8A%80%E5%B7%A7)

遗漏的区域：
定位到——第五点：5 个编写可维护的、健壮的异步代码的技巧的第二小点#错误处理#
原文中是有优化前的代码以及优化后的代码，译文中很明显是缺少优化前的代码，如下：
``` js
function loadData() {
    try { // Catches synchronous errors.
        getJSON().then(function(response) {
            var parsed = JSON.parse(response);
            console.log(parsed);
        }).catch(function(e) { // Catches asynchronous errors
            console.log(e); 
        });
    } catch(e) {
        console.log(e);
    }
}
```

**Comment by sunui** [comment]
已修复，非常感谢！🙏
