### ISSUE TITLE
Web 组件的问题

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6182]
* 原文链接：[The problem with web components](https://adamsilver.io/articles/the-problem-with-web-components/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-problem-with-web-components.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6243
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1-2 天
* 翻译积分：5 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Stevens1995** [comment]
翻译认领。

**Comment by fanyijihua** [comment]
@Stevens1995 棒极啦 :tada:

**Comment by Stevens1995** [comment]
周末搬家...不好意思耽误了,周一 一定完成。

**Comment by leviding** [comment]
好的不急，及时沟通了就行。

**Comment by fanyijihua** [comment]
PR 地址：#6243
