### ISSUE TITLE
作为初级开发人员，我没有学过的 7 个绝对真理

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6184]
* 原文链接：[7 absolute truths I unlearned as junior developer](https://monicalent.com/blog/2019/06/03/absolute-truths-unlearned-as-junior-developer/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/absolute-truths-unlearned-as-junior-developer.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6212
* 文章分类：**其他/前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：6-7 分
* 校对积分：2-4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6212
