### ISSUE TITLE
7 absolute truths I unlearned as junior developer

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6185]
* 原文链接：[7 absolute truths I unlearned as junior developer](https://monicalent.com/blog/2019/06/03/absolute-truths-unlearned-as-junior-developer/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/absolute-truths-unlearned-as-junior-developer.md)
* PR 地址：
* 文章分类：**其他/前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Weirdochr** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@Weirdochr 棒极啦 :tada:
