### ISSUE TITLE
人工智能何以留存

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6188]
* 原文链接：[Why AI is here to stay](https://medium.com/hackernoon/why-ai-is-here-to-stay-9c75b1868b9b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-ai-is-here-to-stay.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6230
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3-4 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@YueYongDev 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6230

**Comment by YueYongDev** [comment]
咋还没人校对啊
