### ISSUE TITLE
元设计师的崛起

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6190]
* 原文链接：[Rise of the meta-designer](https://interactions.acm.org/archive/view/july-august-2019/the-rise-of-the-meta-designer)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-rise-of-the-meta-designer.md)
* PR 地址：#6223
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：5 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6223
