### ISSUE TITLE
由浅入深理解主成分分析

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6192]
* 原文链接：[A step by step explanation of Principal Component Analysis](https://towardsdatascience.com/a-step-by-step-explanation-of-principal-component-analysis-b836fb9c97e2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-step-by-step-explanation-of-principal-component-analysis.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6231
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：1-2 天
* 翻译积分：5-6 分
* 校对积分：1.5-3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ultrasteve** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Ultrasteve 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6229

**Comment by fanyijihua** [comment]
PR 地址：#6231
