### ISSUE TITLE
什么时候需要进行数据的标准化? 为什么？

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6193]
* 原文链接：[When and why to standardize your data?](https://towardsdatascience.com/when-to-standardize-your-data-in-4-minutes-f9282190707e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/when-to-standardize-your-data.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6214
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3-3.5 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ultrasteve** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Ultrasteve 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6214
