### ISSUE TITLE
模板引擎的工作原理是什么？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#620]
* 原文链接：[How a template engine works](https://fengsp.github.io/blog/2016/8/how-a-template-engine-works/)
* 掘金链接：[模板引擎的工作原理是什么？](http://gold.xitu.io/entry/57ac5afe5bbb500062b5b0db)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/300ae627a36e20acb30eabbd81331b6dabe58102/TODO/how-a-template-engine-works.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/631

翻译时间：3 天
校对时间：1 天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Kulbear** [comment]
好想认领 0.0 正好是最喜欢的部分 搞flask和django很久了

**Comment by sqrthree** [comment]
@Kulbear Hello，你是第一次参与翻译计划么？新人要从校对文章开始哟~~ ❤️

**Comment by Kulbear** [comment]
是的～默默流口水ing
😊

**Comment by sqrthree** [comment]
哈哈~ 没事没事~ 先关注下抢个文章校对哈~ 以后就可以抢译文了~ 😉

**Comment by MAYDAY1993** [comment]
申请认领啦啦啦

**Comment by Zheaoli** [comment]
@MAYDAY1993 卧槽，这篇能让我么

**Comment by MAYDAY1993** [comment]
@Zheaoli  乖 姐姐要攒小猫

**Comment by Zheaoli** [comment]
@MAYDAY1993 嘤嘤嘤，我来校对？

**Comment by owenlyn** [comment]
@MAYDAY1993 你是一次认领的两篇么。。。[#621](https://github.com/xitu/gold-miner/issues/621)可不可以让给我= =

**Comment by MAYDAY1993** [comment]
@owenlyn  如果说同时翻译两篇不合适的话 那就让给 @Zheaoli 啦 他先你看到 污呜呜 喵～

**Comment by sqrthree** [comment]
@MAYDAY1993 你们商量吧，哈哈哈，要注意时间限制啊，基本上周日要搞定的~

**Comment by MAYDAY1993** [comment]
给 @Zheaoli吧  @sqrthree @owenlyn  时间优先

**Comment by sqrthree** [comment]
@Zheaoli 来确认下哟~ 注意时间限制哈~~ 
@owenlyn 下次赶早点啦~ ❤️❤️❤️

**Comment by Zheaoli** [comment]
@sqrthree 
@MAYDAY1993 抄收，都快感动哭了
@owenlyn 大兄弟，实在抱歉啦，来帮我校对吧

**Comment by owenlyn** [comment]
@Zheaoli 要是我能抢到的话T.T

**Comment by Zheaoli** [comment]
@owenlyn 大兄弟，我给你留了个校对的位置,[校对地址](https://github.com/xitu/gold-miner/pull/631/files)
@sqrthree 小哥可以改label了

**Comment by hpoenixf** [comment]
校对

**Comment by sqrthree** [comment]
PR 地址：https://github.com/xitu/gold-miner/pull/631
