### ISSUE TITLE
postMessage 很慢吗? 

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6202]
* 原文链接：[Is postMessage slow?](https://dassur.ma/things/is-postmessage-slow/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/is-postmessage-slow.md)
* PR 地址：#6224
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：7-8.5 分
* 校对积分：2-5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by linxiaowu66** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@linxiaowu66 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6224
