### ISSUE TITLE
逆向工程，如何在 JavaScript 中打造一个测试库

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6203]
* 原文链接：[Reverse Engineering, how YOU can build a testing library in JavaScript](https://dev.to/itnext/reverse-engineering-how-you-can-build-a-test-library-53e3)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/reverse-engineering-how-you-can-build-a-test-library.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6239
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2-3 分
* 校对积分：0.5-1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Usey95** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Usey95 棒极啦 :tada:

**Comment by sunui** [comment]
@Usey95  Hi,翻译的怎么样啦

**Comment by Usey95** [comment]
@sunui 晚点会发

**Comment by fanyijihua** [comment]
PR 地址：#6239
