### ISSUE TITLE
数据分片是如何在分布式 SQL 数据库中起作用的

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6204]
* 原文链接：[How Data Sharding Works in a Distributed SQL Database](https://blog.yugabyte.com/how-data-sharding-works-in-a-distributed-sql-database/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-data-sharding-works-in-a-distributed-sql-database.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6227
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4-4.5 分
* 校对积分：1-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ultrasteve** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Ultrasteve 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6227
