### ISSUE TITLE
开源难题：如何保持长久

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6205]
* 原文链接：[The Open Source Conundrum: How Do We Keep the Lights On?](https://codefund.io/blog/the-open-source-conundrum-how-do-we-keep-the-lights-on)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-open-source-conundrum-how-do-we-keep-the-lights-on.md)
* PR 地址：#6273
* 文章分类：**开源**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4-4.5 分
* 校对积分：1-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lihanxiang** [comment]
@leviding 翻译认领

**Comment by fanyijihua** [comment]
@lihanxiang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6273
