### ISSUE TITLE
Docker 的学习和应用

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6207]
* 原文链接：[Learn Enough Docker to be Useful](https://towardsdatascience.com/learn-enough-docker-to-be-useful-b7ba70caeb4b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/learn-enough-docker-to-be-useful-1.md)
* PR 地址：#6291
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3-3.5 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by EmilyQiRabbit** [comment]
🤣嗷嗷嗷不好意思了，稍等稍等 @-@ 前一篇太长了，这篇排在它后面了...

**Comment by fanyijihua** [comment]
PR 地址：#6291
