### ISSUE TITLE
使用 Typescript 使无效状态不可恢复

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6209]
* 原文链接：[Using Typescript to make invalid states irrepresentable](http://www.javiercasas.com/articles/typescript-impossible-states-irrepresentable)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/typescript-impossible-states-irrepresentable.md)
* PR 地址：#6274
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3-4 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by solerji** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@solerji 棒极啦 :tada:
