### ISSUE TITLE
我不是用户体验设计师，你呢？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#621]
* 原文链接：[I’m not a UX Designer, and neither are you?](http://www.webdesignerdepot.com/2016/08/im-not-a-ux-designer-and-neither-are-you/)
* 掘金链接：[我不是用户体验设计师，你呢？](http://gold.xitu.io/entry/57abed30165abd005402f080)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/im-not-a-ux-designer-and-neither-are-you.md)
* PR 地址： [不是我](https://github.com/xitu/gold-miner/pull/629)

翻译时间：2 天
校对时间：1 天
翻译积分：4
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Kulbear** [comment]
认领

**Comment by sqrthree** [comment]
@Kulbear Hello，你是第一次参与我们的翻译计划么？第一次的话要从校对文章开始哟~~

**Comment by sqrthree** [comment]
@Kulbear Hello，你是第一次参与我们的翻译计划么？第一次的话要从校对文章开始哟~~

**Comment by Kulbear** [comment]
你Label写的校对认领啊－ －

**Comment by sqrthree** [comment]
_(:з」∠)_ 抱歉哈，刚加错了，多谢提醒 ❤️❤️❤️

**Comment by MAYDAY1993** [comment]
申请认领啦啦啦

**Comment by sqrthree** [comment]
@MAYDAY1993 妥妥哒~

**Comment by sqrthree** [comment]
PR 地址： https://github.com/xitu/gold-miner/pull/629
