### ISSUE TITLE
你考虑清楚了吗就决定用 Bootstrap ？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#622]
* 原文链接：[Bootstrap considered harmful](https://hiddedevries.nl/en/blog/2016-08-09-bootstrap-considered-harmful)
* 掘金链接：[你考虑清楚了吗就决定用 Bootstrap ？](http://gold.xitu.io/entry/57ad7ce9d342d300570278dd)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/bootstrap-considered-harmful.md)
* PR 地址：[你猜对不对](https://github.com/xitu/gold-miner/pull/651)

翻译时间：2 天
校对时间：1 天
翻译积分：3
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by MAYDAY1993** [comment]
求翻译 我考虑清楚了

**Comment by sqrthree** [comment]
@MAYDAY1993 好好好...好快~~ 我得跪一个先

**Comment by Graning** [comment]
@MAYDAY1993   快来给我校对

**Comment by Kulbear** [comment]
@MAYDAY1993 光速抢。。。简直如同监控

**Comment by MAYDAY1993** [comment]
@Kulbear 嘿嘿  想知道咋办到的么

**Comment by Kulbear** [comment]
@MAYDAY1993 我写了个脚本crontab每分钟运行一次监控Github的API 有新的issue和pr我的电脑会说话告诉我 哈哈哈

**Comment by MAYDAY1993** [comment]
@Kulbear 少年 交个朋友吧

**Comment by lizwangying** [comment]
@Kulbear 我watch.....虽然没你快，但是还是你帅!

**Comment by Graning** [comment]
@Kulbear  👏👏👏

**Comment by Kulbear** [comment]
@Graning @lizwangying hahaha

**Comment by sqrthree** [comment]
可怕，我要逃。_(:з」∠)_

**Comment by sqrthree** [comment]
PR：https://github.com/xitu/gold-miner/pull/630
