### ISSUE TITLE
在你的 Instant 体验中使用 showInstallPrompt 的5个技巧

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6220]
* 原文链接：[5 tips for using showInstallPrompt in your instant experience](https://medium.com/androiddevelopers/5-tips-for-using-showinstallprompt-in-your-instant-experience-99d4681e0ae)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/5-tips-for-using-showinstallprompt-in-your-instant-experience.md)
* PR 地址：
* 文章分类：**Android**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Fxy4ever** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Fxy4ever 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6357

**Comment by lsvih** [comment]
@leviding 麻烦您啦= =

**Comment by leviding** [comment]
应该的
