### ISSUE TITLE
用 Rust 写编译器

### ISSUE THREAD

**Issue by JackEggie** [xitu/gold-miner#6222]
* 原文链接：[Writing a Compiler in Rust](http://thume.ca/2019/04/18/writing-a-compiler-in-rust/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/writing-a-compiler-in-rust.md)
* PR 地址：#6290
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：5.5-6.5 分
* 校对积分：1.5-3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by suhanyujie** [comment]
翻译认领 @leviding

**Comment by fanyijihua** [comment]
@suhanyujie 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6290
