### ISSUE TITLE
我用 Javascript 实现 tic tac toe 游戏

### ISSUE THREAD

**Issue by leviding** [xitu/gold-miner#6234]
* 原文链接：[I Built Tic Tac Toe With JavaScript](https://mitchum.blog/i-built-tic-tac-toe-with-javascript/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/i-built-tic-tac-toe-with-javascript.md)
  * PR 地址：#6251
  * 文章分类：**前端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-4.5 分
  * 校对积分：1-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lgh757079506** [comment]
翻译认领，但是TODO1文件夹中没有对应文件哦 @leviding

**Comment by fanyijihua** [comment]
@lgh757079506 棒极啦 :tada:

**Comment by leviding** [comment]
@lgh757079506 现在好啦
