### ISSUE TITLE
给我们其他人看的代数效应

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6235]
* 原文链接：[Algebraic Effects for the Rest of Us](https://overreacted.io/algebraic-effects-for-the-rest-of-us/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/algebraic-effects-for-the-rest-of-us.md)
* PR 地址：https://github.com/xitu/gold-miner/pull/6280
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：6-7.5 分
* 校对积分：1.5-4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TiaossuP** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@TiaossuP 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6280
