### ISSUE TITLE
深入理解 Python 类型提示

### ISSUE THREAD

**Issue by JackEggie** [xitu/gold-miner#6238]
* 原文链接：[A deep dive on Python type hints](https://veekaybee.github.io/2019/07/08/python-type-hints/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-deep-dive-on-python-type-hints.md)
* PR 地址：#6270
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：6.5-7.5 分
* 校对积分：1.5-4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hu7may** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@hu7may 棒极啦 :tada:

**Comment by hu7may** [comment]
fork之后的仓库内容不是最新的，找不到要翻译的文章，翻译说明里面提到要同步，指向的链接里面说要在命令行里面操作，那我必须把这个大仓库全下载到本地吗，在网页上能不能操作？

fork之后的仓库内容不是最新的，找不到要翻译的文章，翻译说明里面提到要同步，指向的链接里面说要在命令行里面操作，那我必须把这个大仓库全下载到本地吗，在网页上能不能操作？







在 2019-07-30 10:56:30，"掘金翻译计划" <notifications@github.com> 写道：


@hu7may 棒极啦

**Comment by JackEggie** [comment]
@hu7may 请根据 wiki 中提到的 [同步方法](https://help.github.com/en/articles/syncing-a-fork) 更新 fork 后的仓库。翻译是可以在网页中进行的，注意请新建 branch 后进行提交。

如有问题请再次学习 wiki 中的说明，或者到翻译群中进行讨论哈。

**Comment by fanyijihua** [comment]
PR 地址：#6270
