### ISSUE TITLE
[前端]A Future Without Webpack

### ISSUE THREAD

**Issue by GoToBoy** [xitu/gold-miner#6246]
- 原文链接：[A Future Without Webpack](https://www.pika.dev/blog/pika-web-a-future-without-webpack/)
- 简要介绍：从[阿里前端-支付宝重构引发的思考](https://github.com/pigcan/blog/issues/19)中就延伸到的没有webpack的文章链接

---

### 请完成并勾选一下三项：

* [ ok] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [ ok] 本文很值得翻译，我推荐
* [ ok] 已经过初步搜索，暂未发现中文版译文

**Comment by sunui** [comment]
感谢您的推荐，近期发布翻译认领 💝 近期更新译者积分时会奖励优秀英文文章推荐积分 @leviding
