### ISSUE TITLE
嘿，Logo，你应该是这个尺寸的！

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#625]
* 原文链接：[Practical SVG](http://alistapart.com/article/practical-svg)
* 掘金链接：[嘿，Logo，你应该是这个尺寸的！](http://gold.xitu.io/entry/57ad3a188ac247005ff496a4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/practical-svg.md)
* PR 地址：[嗯哼](https://github.com/xitu/gold-miner/pull/660)

翻译时间：4 天
校对时间：2 天
翻译积分：6
校对积分：1
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by MAYDAY1993** [comment]
认领啦啦啦

**Comment by sqrthree** [comment]
@MAYDAY1993 棒棒哒~~

**Comment by sqrthree** [comment]
同时翻译多篇注意分支和发送 PR 时分开发送哈~~ ┏ (゜ω゜)=☞

**Comment by MAYDAY1993** [comment]
@sqrthree  往事不要再提～～～ 我已经不是那个不会git的小姑凉了

**Comment by rottenpen** [comment]
申请校对

**Comment by sqrthree** [comment]
@rottenpen 好像还没有 PR 的吧

**Comment by rottenpen** [comment]
@sqrthree 插好队先咯

**Comment by sqrthree** [comment]
@rottenpen 哈哈，恐怕您老是要失望了~ 是以对应的 PR 下的时间先后为准的。没办法提前占坑啦

**Comment by rottenpen** [comment]
@sqrthree 没关系，我watching了3天了，居然没新文章！！

**Comment by hpoenixf** [comment]
申请校对
