### ISSUE TITLE
用户需要什么样的 Flutter 依赖包?  来自 Q2 用户调查的结果

### ISSUE THREAD

**Issue by JackEggie** [xitu/gold-miner#6250]
* 原文链接：[What do Flutter package users need? Findings from Q2 user survey](https://medium.com/flutter/what-do-flutter-package-users-need-6ecba57ed1d6)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-do-flutter-package-users-need-findings-from-q2-user-survey.md)
* PR 地址：#6272
* 文章分类：**Flutter**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4-5 分
* 校对积分：1-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by solerji** [comment]
翻译认领

**Comment by leviding** [comment]
@solerji 好滴

**Comment by fanyijihua** [comment]
PR 地址：#6272

**Comment by solerji** [comment]
@fanyijihua 我修改一下提交时的标题，因为有更改所以忘记改中文标题了
