### ISSUE TITLE
别再设计你的应用界面了，在用户体验上下点功夫吧

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#626]
* 原文链接：[Stop designing interfaces, Start designing experiences](https://medium.com/blablacar-design/stop-designing-interfaces-start-designing-experiences-d82def0b802c#.tm2nitn97)
* 掘金链接：[别再设计你的应用界面了，在用户体验上下点功夫吧](http://gold.xitu.io/entry/57ad3f71128fe10055a58547)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/stop-designing-interfaces-start-designing-experiences.md)
* PR 地址：[嗯，换我了](https://github.com/xitu/gold-miner/pull/627)

翻译时间：4 天
校对时间：2 天
翻译积分：5
校对积分：1 
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Kulbear** [comment]
认领

**Comment by sqrthree** [comment]
@Kulbear 好哒👌

**Comment by Kulbear** [comment]
完成了 #627

**Comment by sqrthree** [comment]
@Kulbear 好快( ⊙ o ⊙ )，我要给你点赞，别拦我。

**Comment by Kulbear** [comment]
@sqrthree 大力点不要停

**Comment by jiaowoyongqi** [comment]
校对！
