### ISSUE TITLE
愿未来没有 Webpack

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6261]
* 原文链接：[A Future Without Webpack](https://www.pika.dev/blog/pika-web-a-future-without-webpack/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/pika-web-a-future-without-webpack.md)
* PR 地址：#6268
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4-5 分
* 校对积分：1-2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
翻译认领。

**Comment by sunui** [comment]
认领翻译(测试)

**Comment by sunui** [comment]
认领翻译（测试）

**Comment by sunui** [comment]
认领翻译（测试）

**Comment by sunui** [comment]
@Baddyo  可以翻译的哈 ，robot 出故障了

**Comment by fanyijihua** [comment]
PR 地址：#6268
