### ISSUE TITLE
当每个产品设计都是一种意见

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6262]
* 原文链接：[When every product of design is one of opinion](https://tannerchristensen.com/blog/2019/7/22/when-every-product-of-design-is-one-of-opinion)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/when-every-product-of-design-is-one-of-opinion.md)
* PR 地址：#6311
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：4-5 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Charlo-O** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Charlo-O 棒极啦 :tada:

**Comment by sunui** [comment]
@Charlo-O 翻译的怎么样啦
