### ISSUE TITLE
Flutter 的状态管理方案：setState、BLoC、ValueNotifier、Provider

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6277]
* 原文链接：[Flutter State Management: setState, BLoC, ValueNotifier, Provider](https://medium.com/coding-with-flutter/flutter-state-management-setstate-bloc-valuenotifier-provider-2c11022d871b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/flutter-state-management-setstate-bloc-valuenotifier-provider.md)
* PR 地址：
* 文章分类：**Flutter**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 5天
* 校对时间： 2天
* 翻译积分： 5～6分
* 校对积分： 1～2分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by talisk** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@talisk 棒极啦 :tada:

**Comment by leviding** [comment]
@glown 管理员发布翻译认领，需要翻译计划负责人来更新翻译校对时间和积分，并同步更新到 Trello，本 PR 我已帮忙更新 Trello，麻烦你更新下时间和积分

**Comment by fanyijihua** [comment]
PR 地址：#6304

**Comment by itcodes** [comment]
https://juejin.cn/post/7079080839002193928

**Comment by lsvih** [comment]
@itcodes 收到
