### ISSUE TITLE
Python 的打包现状（写于 2019 年）

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6285]
* 原文链接：[Current State of Python Packaging - 2019](https://stefanoborini.com/current-status-of-python-packaging/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/current-status-of-python-packaging.md)
* PR 地址：#6322
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 13天
* 校对时间： 2天
* 翻译积分： 13 ～ 14分
* 校对积分： 3分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by suhanyujie** [comment]
@EmilyQiRabbit 额，你好像是前端。。我的意思这是 Python。。。

**Comment by EmilyQiRabbit** [comment]
@suhanyujie 嗯嗯我最近在学 python 😆

**Comment by suhanyujie** [comment]
> @suhanyujie 嗯嗯我最近在学 python

哈，我以为你在学 Flutter，或者 Golang 之类的。。。

**Comment by EmilyQiRabbit** [comment]
@suhanyujie 并不了解～不过翻译了一两篇文章，Golang 似乎很厉害诶～

**Comment by fanyijihua** [comment]
PR 地址：#6322
