### ISSUE TITLE
小提示：伪元素是子元素，吧。

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6287]
* 原文链接：[A Little Reminder That Pseudo Elements are Children, Kinda.](https://css-tricks.com/a-little-reminder-that-pseudo-elements-are-children-kinda/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-little-reminder-that-pseudo-elements-are-children-kinda.md)
* PR 地址：#6292
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6292
