### ISSUE TITLE
冲冠一怒为代码：论程序员与负能量

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6289]
* 原文链接：[Rage Against the Codebase: Programmers and Negativity](https://medium.com/@way/rage-against-the-codebase-programmers-and-negativity-d7d6b968e5f3)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/rage-against-the-codebase-programmers-and-negativity.md)
* PR 地址：#6330
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 10天
* 校对时间： 2天
* 翻译积分： 10～12分
* 校对积分： 2分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6330
