### ISSUE TITLE
关于现代应用样式的探讨

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6299]
* 原文链接：[Styling In Modern Web Apps](https://www.smashingmagazine.com/2019/06/styling-modern-web-apps/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/styling-modern-web-apps.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 13天
* 校对时间： 2天
* 翻译积分： 13～14分
* 校对积分： 2分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by Glowin** [comment]
@EmilyQiRabbit 翻译进度咋样啦？

**Comment by EmilyQiRabbit** [comment]
还在翻译，最近太忙了，不好意思～@Glowin

**Comment by fanyijihua** [comment]
PR 地址：#6366
