### ISSUE TITLE
现代脚本加载

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6301]
* 原文链接：[Modern Script Loading](https://jasonformat.com/modern-script-loading/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/modern-script-loading.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 5天
* 校对时间： 2天
* 翻译积分： 5~6分
* 校对积分： 1分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iceytea** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@iceytea 棒极啦 :tada:

**Comment by Glowin** [comment]
@iceytea 延期啦，请问现在翻译进度咋样了？

**Comment by JackEggie** [comment]
@iceytea 请问翻译进度怎么样啦？有任何困难需要帮助吗？

**Comment by liyunhestar** [comment]
抱歉，最近有些忙，把这个事情给忘了。。。最早今天晚上，最迟明天晚上之前会提交。

**Comment by fanyijihua** [comment]
PR 地址：#6385

**Comment by iceytea** [comment]
代码已经提交。
