### ISSUE TITLE
推荐前端优秀英文文章

### ISSUE THREAD

**Issue by Jerry-FD** [xitu/gold-miner#6307]
- 原文链接：https://overreacted.io/how-does-the-development-mode-work/
- 简要介绍：作者 Dan Abramov，React 核成员。介绍了 react 中使用环境变量的原因，以及环境变量产生的历史背景和原理。

---

### 请完成并勾选一下三项：

* [ x ] 推荐前端优秀英文文章
* [ x ] 本文很值得翻译，我推荐
* [ x ] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by Jerry-FD** [comment]
@Glowin

**Comment by sunui** [comment]
感谢您的推荐，已加入翻译计划 RESOURCE，管理员按期安排翻译认领 💝 近期更新译者积分时会奖励优秀英文文章推荐积分

**Comment by Jerry-FD** [comment]
@sunui 自己想认领翻译

**Comment by sunui** [comment]
@Jerry-FD  已发布 #6308
