### ISSUE TITLE
开发模式的工作原理是什么？

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6308]
* 原文链接：[How Does the Development Mode Work?](https://overreacted.io/how-does-the-development-mode-work/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-does-the-development-mode-work.md)
* PR 地址：#6327
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：7-8 分
* 校对积分：2-4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
@Jerry-FD 可以认领啦

**Comment by Jerry-FD** [comment]
翻译认领
@sunui

**Comment by fanyijihua** [comment]
@Jerry-FD 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6327

**Comment by Jerry-FD** [comment]
@sunui 翻译完成
