### ISSUE TITLE
深入解析 Flutter Provider 包

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6313]
* 原文链接：[A Closer Look at the Provider Package](https://medium.com/flutter-nyc/a-closer-look-at-the-provider-package-993922d3a5a5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-closer-look-at-the-provider-package.md)
* PR 地址：#6313
* 文章分类：**Flutter**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 6天
* 校对时间： 2天
* 翻译积分： 6～7分
* 校对积分： 2分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by talisk** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@talisk 棒极啦 :tada:

**Comment by Glowin** [comment]
@talisk 延期啦，请问现在翻译进度咋样？

**Comment by JackEggie** [comment]
@talisk  请问翻译进度怎么样啦？有任何困难需要帮助吗？

**Comment by talisk** [comment]
抱歉。这两天完成提交，稍等

**Comment by sunui** [comment]
@talisk 还在翻译吗？

**Comment by sunui** [comment]
超期重新释放

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6480
