### ISSUE TITLE
类型及其在参数中的应用：能优化代码的的 Dart 特性

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6315]
* 原文链接：[Dart Features for Better Code: Types and working with parameters](https://medium.com/coding-with-flutter/dart-features-for-better-code-types-and-working-with-parameters-896b802ef73a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/dart-features-for-better-code-types-and-working-with-parameters.md)
* PR 地址：#6462
* 文章分类：**Flutter**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 4天
* 校对时间： 2天
* 翻译积分： 3～4分
* 校对积分： 1分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by talisk** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@talisk 棒极啦 :tada:

**Comment by Glowin** [comment]
@talisk 延期啦，请问翻译进度咋样啦？

**Comment by JackEggie** [comment]
@talisk 请问翻译进度怎么样啦？有任何困难需要帮助吗？

**Comment by talisk** [comment]
抱歉。这两天完成提交，稍等

**Comment by sunui** [comment]
@talisk 这篇什么进度了，若无反馈，即将释放

**Comment by sunui** [comment]
本文重新释放

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6462
