### ISSUE TITLE
如何编写全栈 JavaScript 应用

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6317]
* 原文链接：[How We Write Full Stack JavaScript Apps](https://medium.com/@eliezer/how-writing-simple-javascript-got-us-6200-github-stars-in-a-single-day-420b17b4cff4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-writing-simple-javascript-got-us-6200-github-stars-in-a-single-day.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 7天
* 校对时间： 2天
* 翻译积分： 7~8分
* 校对积分： 2分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wuyanan** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@wuyanan 棒极啦 :tada:

**Comment by Glowin** [comment]
@wuyanan 延期啦，请问翻译进度咋样了？

**Comment by JackEggie** [comment]
@wuyanan 请问翻译进度怎么样啦？有任何困难需要帮助吗？

**Comment by wuyanan** [comment]
@JackEggie 不好意思，最近工作太忙了，没及时看信息，可以先释放给别人翻译吗？

**Comment by JackEggie** [comment]
本文已重新释放，小伙伴们快来认领翻译吧~

**Comment by fanyijihua** [comment]
@JackEggie 棒极啦 :tada:

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6384
