### ISSUE TITLE
React 16 生命周期函数：如何以及何时使用它们

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6320]
* 原文链接：[React 16 Lifecycle Methods: How and When to Use Them](https://blog.bitsrc.io/react-16-lifecycle-methods-how-and-when-to-use-them-f4ad31fb2282)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/react-16-lifecycle-methods-how-and-when-to-use-them.md)
* PR 地址：#6345
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 5天
* 校对时间： 2天
* 翻译积分： 5~6分
* 校对积分： 1分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MarchYuanx** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MarchYuanx 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6345
