### ISSUE TITLE
在Javascript应用内加入CSS的几种方式

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6329]
* 原文链接：[The Many Ways to Include CSS in JavaScript Applications](https://css-tricks.com/the-many-ways-to-include-css-in-javascript-applications/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-many-ways-to-include-css-in-javascript-applications.md)
* PR 地址：#6349
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 6天
* 校对时间： 2天
* 翻译积分： 6～7分
* 校对积分： 2分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by thisisandy** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@thisisandy 棒极啦 :tada:

**Comment by Glowin** [comment]
@thisisandy 延期啦，请问现在翻译进度是？

**Comment by fanyijihua** [comment]
PR 地址：#6349

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6867054761741549576/

**Comment by lsvih** [comment]
本文校对非常认真仔细，各多加 1 分
