### ISSUE TITLE
这样做你就可以通过 React 上传图片了

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#633]
* 原文链接：[Image Upload and Manipulation with React](https://css-tricks.com/image-upload-manipulation-react/)
* 掘金链接：[这样做你就可以通过 React 上传图片了](http://gold.xitu.io/entry/57ad8e315bbb500062bd88ee)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/image-upload-manipulation-react.md)
* PR 地址：[嗯哼](https://github.com/xitu/gold-miner/pull/652)

翻译时间：3 天
校对时间：1 天
翻译积分：5 分
校对积分：1 分
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by DeadLion** [comment]
我来我来

**Comment by sqrthree** [comment]
@DeadLion 好的好的

**Comment by DeadLion** [comment]
@sqrthree  翻译完成
[校对地址](https://github.com/xitu/gold-miner/pull/652)
