### ISSUE TITLE
推荐优秀后端英文文章

### ISSUE THREAD

**Issue by todaycoder001** [xitu/gold-miner#6331]
- 原文链接：https://medium.com/@kevalpatel2106/why-should-you-learn-go-f607681fad65
- 简要介绍：从软件和硬件方面介绍了我们为什么要学习Go这门编程语言。

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 自己用搜索引擎搜索了下，发现了有一篇翻译的文章在简书上。但我看了下，翻译不是很少，想借助大家的智慧，重新翻译一遍，文章的内容写的挺好的。

**Comment by lsvih** [comment]
@todaycoder001 感谢您的推荐，近期发布翻译认领 💝

**Comment by todaycoder001** [comment]
我想自己认领可以么？

**Comment by lsvih** [comment]
没问题，晚上编辑好格式就发

**Comment by todaycoder001** [comment]
啥时候发？

**Comment by lsvih** [comment]
@todaycoder001 整理好了，但是我找到一篇：https://studygolang.com/articles/12565 感觉翻的还挺不错的

**Comment by todaycoder001** [comment]
这篇 跟我发的不一样呀！

**Comment by lsvih** [comment]
@todaycoder001 眼花了.. 已经发布啦，请您翻译吧~ https://github.com/xitu/gold-miner/issues/6337
