### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ohooblueblue** [xitu/gold-miner#6332]
- 公司/学校：四三九九网络股份有限公司
- 工作内容/专业：Android开发工程师，负责公司游戏直播项目Android端部分功能模块开发、维护
- 常浏览的国外网站：StackOverflow，github，google developers
- 英语水平：CET-6
- 翻译经验：无
- 主要翻译方向：Android应用开发
- 个人博客：无
- 个人介绍：热爱技术，喜欢英语，希望能参与进翻译计划，为他人提供便利的同时也精进自己的技术能力与英文水平

**Comment by Glowin** [comment]
你好，加一下我微信 glowjiang ，拉你到译者群
