### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zhangguanpeng** [xitu/gold-miner#6333]
- 公司/学校：美团点评/北京师范大学
- 工作内容/专业：前端开发/软件工程
- 常浏览的国外网站：https://stackoverflow.com/
- 英语水平：CET-6
- 翻译经验：暂无
- 主要翻译方向：前端开发
- 个人博客：https://juejin.im/user/5acddb425188252b0b202546
- 个人介绍：

**Comment by Glowin** [comment]
你好，加一下我微信 glowjiang ，拉你到以这群
