### ISSUE TITLE
为什么你要学习 Go？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6337]
* 原文链接：[Why should you learn Go?](https://medium.com/@kevalpatel2106/why-should-you-learn-go-f607681fad65)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-should-you-learn-go.md)
* PR 地址：#6351
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 6天
* 校对时间： 2天
* 翻译积分： 6～7分
* 校对积分： 2分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由 @todaycoder001 认领

**Comment by todaycoder001** [comment]
翻译认领 @Glowin

**Comment by fanyijihua** [comment]
@todaycoder001 棒极啦 :tada:
