### ISSUE TITLE
如何使用 Mountebank 和 Node.js 来 Mock 服务

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6338]
* 原文链接：[How To Mock Services Using Mountebank and Node.js](https://www.digitalocean.com/community/tutorials/how-to-mock-services-using-mountebank-and-node-js)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-mock-services-using-mountebank-and-node-js.md)
  * PR 地址：#6406
  * 文章分类：**后端**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间： 8天
  * 校对时间： 3天
  * 翻译积分： 12～13分
  * 校对积分： 3分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Pingren** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Pingren 棒极啦 :tada:

**Comment by Glowin** [comment]
@Pingren 翻译内容挺多的，辛苦啦

**Comment by Pingren** [comment]
@sunui 刚刚提了PR~
