### ISSUE TITLE
如何杀死一个进程和它的所有子进程

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6342]
* 原文链接：[Killing a process and all of its descendants](http://morningcoffee.io/killing-a-process-and-all-of-its-descendants.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/killing-a-process-and-all-of-its-descendants.md)
* PR 地址：#6347
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
@JalanJiang 可以认领了

**Comment by JalanJiang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@JalanJiang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6347
