### ISSUE TITLE
Syslog：《系统管理员完整指南》

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6344]
* 原文链接：[Syslog : The Complete System Administrator Guide](https://devconnected.com/syslog-the-complete-system-administrator-guide/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/syslog-the-complete-system-administrator-guide.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 7天
* 校对时间： 2天
* 翻译积分： 7～8分
* 校对积分： 1分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by githubmnume** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@githubmnume 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6391

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6858168312388386824
