### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by TobbiChen** [xitu/gold-miner#635]
Hi, I'm Tobbi. 
· 一枚产品汪。硕士，英语熟练。
· 最常看Quora, Product Hunt, Business Insider, Design Milk... 
· 有翻译经验，文章可以在www.woshipm.com搜索Tobbi即可。
· 暂无可以展示的个人博客。

**Comment by antonia0912** [comment]
@TobbiChen 欢迎来翻译计划 请加我微信 antonia0912 备注github ID 我来拉你进译者群  P.S 你头像跟我们一位译者的头像一样哎
