### ISSUE TITLE
使用 JavaScript 实现一个高效的 LRU cache

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6356]
* 原文链接：[Implementing an efficient LRU cache in JavaScript](https://yomguithereal.github.io/posts/lru-cache)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/lru-cache.md)
* PR 地址：
* 文章分类：**前端**，**算法**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：3 天
* 翻译积分：11-13 分
* 校对积分：3-7 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hanxiaosss** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@hanxiaosss 棒极啦 :tada:

**Comment by hanxiaosss** [comment]
@Glowin 弱弱的问一下我没有找到Markdown文件

**Comment by lsvih** [comment]
@hanxiansen 我放错目录了。。马上修复

**Comment by lsvih** [comment]
@hanxiansen 好了。。

**Comment by hanxiaosss** [comment]
@lsvih    好的 。话说谁是hanxiansen哈哈哈哈我是ladyHan好伐

**Comment by lsvih** [comment]
@hanxiaosss hanxiaosss Fixed..

**Comment by fanyijihua** [comment]
PR 地址：#6368
