### ISSUE TITLE
在 Flutter 中使用 Provider 构建底部导航栏

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6359]
* 原文链接：[Bottom Navigation Bar using Provider | Flutter](https://medium.com/flutterdevs/bottom-navigation-bar-using-provider-flutter-8b607beb2e5a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/bottom-navigation-bar-using-provider-flutter.md)
* PR 地址：
* 文章分类：**Flutter**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：0.5-1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@XatMassacrE 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6361

**Comment by itcodes** [comment]
https://juejin.cn/post/6930515324815015949 已经更新。 @lsvih

**Comment by lsvih** [comment]
收到
