### ISSUE TITLE
Activity 的正确打开方式

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#636]
* 原文链接：[Explain Activity Launch Mode With Examples](http://www.songzhw.com/2016/08/09/explain-activity-launch-mode-with-examples/)
* 掘金链接：[Android 中的 Activity 启动模式](http://gold.xitu.io/entry/57aafd265bbb5000644bc8a0)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/explain-activity-launch-mode-with-examples.md)
* PR 地址：[没错，就是我](https://github.com/xitu/gold-miner/pull/649)

翻译时间：3 天
校对时间：1 天
翻译积分：4 分
校对积分：1 分
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by lizwangying** [comment]
+++++1翻译

**Comment by sqrthree** [comment]
@lizwangying  妥妥哒~~

**Comment by lizwangying** [comment]
终于有一个android的了。等得我好辛苦。

**Comment by shixinzhang** [comment]
曾经有一篇翻译在我面前，我却没有珍惜

**Comment by hackerkevin** [comment]
预约校对

**Comment by sqrthree** [comment]
@hackerkevin 不能提前占坑哈，还是等译者 PR 之后再在对应的 PR 下申请校对吧~~ ❤️

**Comment by sqrthree** [comment]
@hackerkevin 这个已经 PR 了，快到 PR 下申请校对哈~ 还有一个名额。

**Comment by hackerkevin** [comment]
@lizwangying @sqrthree 校对完成！
