### ISSUE TITLE
Node.js 新特性将颠覆 AI、物联网等更多惊人领域

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6363]
* 原文链接：[New Node.js 12 features will see it disrupt AI, IoT and more surprising areas](https://tsh.io/blog/new-node-js-features/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/new-node-js-features.md)
* PR 地址：#6454
* 文章分类：**后端**，**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：7-8 分
* 校对积分：2-4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hanxiaosss** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@hanxiaosss 棒极啦 :tada:

**Comment by sunui** [comment]
@hanxiaosss  有在翻译吗，若没有反馈即将释放。

**Comment by sunui** [comment]
本文重新释放

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6454
