### ISSUE TITLE
喂，这是「我的」电脑，不是「你的」

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#637]
* 原文链接：：[Is this my interface or yours?](https://medium.com/@jsaito/is-this-my-interface-or-yours-b09a7a795256?ref=uxdesignweekly#.8o975gug5)
* 掘金链接：[喂，这是「我的」电脑，不是「你的」](http://gold.xitu.io/entry/57b179e46be3ff006bb31a9a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/is-this-my-interface-or-yours.md)
* PR 地址：[不是我](https://github.com/xitu/gold-miner/pull/654)

翻译时间：3 天
校对时间：1 天
翻译积分：5 分
校对积分：1 分
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by jiaowoyongqi** [comment]
翻译！

**Comment by sqrthree** [comment]
@jiaowoyongqi 好哒~ 👌

**Comment by shliujing** [comment]
校对认领？
