### ISSUE TITLE
如何提升你的数据结构、算法以及解决问题的能力

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6370]
* 原文链接：[How to improve your data structures, algorithms, and problem-solving skills](https://medium.com/@fabianterh/how-to-improve-your-data-structures-algorithms-and-problem-solving-skills-af50971cba60)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-improve-your-data-structures-algorithms-and-problem-solving-skills.md)
  * PR 地址：
  * 文章分类：**算法**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间： 天
  * 校对时间： 天
  * 翻译积分： 分
  * 校对积分： 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由 @todaycoder001 于 #6367 推荐，同时由 @todaycoder001 认领

**Comment by todaycoder001** [comment]
翻译认领 @lsvih

**Comment by Weirdochr** [comment]
翻译认领

**Comment by lsvih** [comment]
@Weirdochr 本文已经由 todaycoder001 认领，处于正在翻译状态了，近日会发布一些新的文章，敬请关注哈。

**Comment by lsvih** [comment]
@Weirdochr 也欢迎校对已经翻译完毕的文章

**Comment by fanyijihua** [comment]
PR 地址：#6386
