### ISSUE TITLE
推荐前端优秀英文文章

### ISSUE THREAD

**Issue by Jerry-FD** [xitu/gold-miner#6371]
- 原文链接：https://medium.com/the-non-traditional-developer/checking-the-network-connection-with-a-react-hook-ec3d8e4de4ec
- 简要介绍：作者使用 react-hooks 实现了一种简单的方式来监控页面的网络情况，来让开发者更有效的提升用户体验

---

### 请完成并勾选一下三项：

* [ x ] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [ x ] 本文很值得翻译，我推荐
* [ x ] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by Jerry-FD** [comment]
自己翻译
@Glowin

**Comment by sunui** [comment]
感谢推荐，已经发布 #6373
