### ISSUE TITLE
使用 React Hook 来检查网络连接状态

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6373]
* 原文链接：[Checking The Network Connection With a React Hook](https://medium.com/the-non-traditional-developer/checking-the-network-connection-with-a-react-hook-ec3d8e4de4ec)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/checking-the-network-connection-with-a-react-hook.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
可以认领了 @Jerry-FD

**Comment by Jerry-FD** [comment]
@sunui 翻译认领

**Comment by fanyijihua** [comment]
@Jerry-FD 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6374

**Comment by Weirdochr** [comment]
翻译认领
