### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Weirdochr** [xitu/gold-miner#6375]
- 公司/学校：斯伦贝谢技术（北京）有限公司/ 北京第二外国语学院
- 工作内容/专业：
    专业：硕士-英语翻译 | 本科：软件工程+英语
    工作内容：
    1.DrillPlan软件文档开发 
       DrillPlan是一款将人工智能、数据分析和自动化用于油田开发的软件，客户分布全球。我负责DrillPlan在线帮助和用户手册（全英文）的开发工作，所有文档均采用DITA结构化、模块化写作模式，使用XMetal编辑器设计、撰写、管理和发布该软件XML英文文档。
       另外我还负责公司其他油田相关软件API文档、软件UI界面文字内容审校、修改的工作以及公司网站界面的内容维护；使用Premiere CC、Shotcut制作技术传播相关视频，使用Illustrator、Photoshop制作Logo、UI图标也是我日常工作的一部分。

- 常浏览的国外网站：Reddit、Hongkiat
- 英语水平：英语专业八级、全国翻译资格水平考试二级笔译
- 翻译经验：三年兼职译员
- 主要翻译方向：广告、文学、技术
- 个人博客：https://github.com/Weirdochr （基本没有内容，希望能通过掘金丰富自己git上的内容，谢谢！）
- 个人介绍：一个想成为设计师的小翻译、渴望不断学习进步的在职技术文档工程师

**Comment by sunui** [comment]
Hi @Weirdochr ，感谢你申请加入掘金翻译计划，你需要做以下的事：

**1.** 认真学习 [掘金翻译计划译者教程](https://github.com/xitu/gold-miner/wiki)，校对和翻译文章时，严格遵循教程，杜绝不看教程，只知道问的伸手党；

**2.** 确认认真学习了 [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)，翻译文章时严格遵循，校对文章时也要指出译者的格式错误；

**3.** 确认认真学习了 [翻译和校对文章的注意事项](https://github.com/xitu/gold-miner/wiki/%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88)，避免翻译校对过程中出错。

**4.** 确定已学习完上述内容，加管理员微信 `glowjiang`，**验证信息格式**：姓名 + GitHub 用户名；

**注意**：管理员每天集中处理一次，稍安勿躁。加完微信后，管理员会在当天拉你进译者群，进群之后做下简单的自我介绍。加入微信群则代表申请译者成功，接下来你需要看译者教程，然后先校对至少一篇文章才能开始正式翻译文章。当然也可以继续校对文章。
