### ISSUE TITLE
写一个愚蠢的 flutter 图标包

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6377]
* 原文链接：[Writing a dumb icon flutter package](https://medium.com/flutter-community/writing-a-dumb-icon-flutter-package-9682d949002f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/writing-a-dumb-icon-flutter-package.md)
* PR 地址：
* 文章分类：**Flutter**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2~3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由 @talisk 于 #6242 推荐

**Comment by YueYongDev** [comment]
翻译认领

**Comment by lsvih** [comment]
@YueYongDev 棒极啦 🎉

**Comment by lsvih** [comment]
PR 地址：#6392

**Comment by lsvih** [comment]
地址：https://juejin.im/post/5dad820ce51d4524ce222642
