### ISSUE TITLE
数学编程 — 为推进数据科学发展而培养的一个关键习惯

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6379]
* 原文链接：[Mathematical programming — a key habit to build up for advancing in data science](https://towardsdatascience.com/mathematical-programming-a-key-habit-to-built-up-for-advancing-in-data-science-c6d5c29533be)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/mathematical-programming-a-key-habit-to-built-up-for-advancing-in-data-science.md)
  * PR 地址：
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Weirdochr** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Weirdochr 棒极啦 :tada:

**Comment by Glowin** [comment]
@Weirdochr 请问你是否翻译或者校对过翻译计划的文章？

**Comment by Weirdochr** [comment]
> @Weirdochr 请问你是否翻译或者校对过翻译计划的文章？

你好，此前没有翻译过翻译计划的文章。
