### ISSUE TITLE
Swift 中的后端 API 文件

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#638]
* 原文链接：[Backend API Documentation in Swift](https://medium.com/ios-os-x-development/backend-api-documentation-in-swift-92b4874e4f78#.g2ofuey9d)
* 掘金链接：[Swift 中的后端 API 文件](http://gold.xitu.io/entry/57b2f63979bc440058f180a0)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/backend-api-documentation-in-swift.md)

翻译时间：2 天
校对时间：1 天
翻译积分：3 分
校对积分：1 分
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by yifili09** [comment]
@sqrthree 认领

**Comment by sqrthree** [comment]
@yifili09 好哒👌

**Comment by yifili09** [comment]
@sqrthree 召唤校对小伙伴。

**Comment by rottenpen** [comment]
校对认领

**Comment by siegeout** [comment]
校对认领

**Comment by sqrthree** [comment]
@rottenpen @siegeout 妥妥哒~
