### ISSUE TITLE
Flutter: 使用 Redux 实现无限 ListView

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6380]
* 原文链接：[Flutter: Infinite ListView with Redux](https://medium.com/flutter-community/flutter-redux-infinite-listview-b57e81ca4ef4)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/flutter-infinite-listview-with-redux.md)
  * PR 地址：
  * 文章分类：**Flutter**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：3 天
  * 校对时间：1~2 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@XatMassacrE 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6388
