### ISSUE TITLE
如何用 Keras 从头搭建一维生成对抗网络

### ISSUE THREAD

**Issue by zhmhhu** [xitu/gold-miner#6383]
* 原文链接：[How to Develop a 1D Generative Adversarial Network From Scratch in Keras](https://machinelearningmastery.com/how-to-develop-a-generative-adversarial-network-for-a-1-dimensional-function-from-scratch-in-keras/)
  * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-develop-a-generative-adversarial-network-for-a-1-dimensional-function-from-scratch-in-keras.md)
  * PR 地址：
  * 文章分类：**AI**
  * **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
  ----
  * 翻译时间：10 天
  * 校对时间：4 天
  * 翻译积分：12-15 分
  * 校对积分：3-7 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TokenJan** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@TokenJan 棒极啦 :tada:

**Comment by todaycoder001** [comment]
认领校对
