### ISSUE TITLE
如何通过 OS 平台设计一款手机 APP

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#639]
* 原文链接：[How to design a mobile app across OS platforms?](https://medium.com/@ooceanzou/designers-problem-d7f70d4f4d6c#.8mr6hednc)
* 掘金链接：[如何通过 OS 平台设计一款手机 APP](http://gold.xitu.io/entry/57b28611165abd005434e66b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/designers-problem.md)
* PR 地址：[我是](https://github.com/xitu/gold-miner/pull/665)

翻译时间：5 天
校对时间：2 天
翻译积分：8 分
校对积分：2 分
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Kulbear** [comment]
认领

**Comment by sqrthree** [comment]
@Kulbear 妥妥哒
