### ISSUE TITLE
学习 CSS 布局中有趣的地方 —— 第一部分：弹性布局

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6400]
* 原文链接：[Fun places to learn CSS Layout –  Part 1: Flexbox](https://stephaniewalter.design/blog/fun-places-learn-css-layout-part-1-flexbox/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/ces-learn-css-layout-part-1-flexbox.md)
* PR 地址：#6437
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MarchYuanx** [comment]
翻译认领

**Comment by sunui** [comment]
@MarchYuanx  棒极啦 🎉

**Comment by sunui** [comment]
@MarchYuanx 在翻译吗

**Comment by MarchYuanx** [comment]
@sunui 抱歉😂 忘记了 会尽快完成的

**Comment by fanyijihua** [comment]
PR 地址：#6437
