### ISSUE TITLE
趣味学习 CSS 布局 —— 第二部分：网格布局

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6401]
* 原文链接：[Fun places to learn CSS Layout –  Part 2: Grid Layout](https://stephaniewalter.design/blog/fun-places-to-learn-css-layout-part-2-grid-layout/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/un-places-to-learn-css-layout-part-2-grid-layout.md)
* PR 地址：#6452
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by liyunhestar** [comment]
翻译认领

**Comment by iceytea** [comment]
翻译认领

**Comment by sunui** [comment]
@iceytea 棒极啦 🎉

**Comment by sunui** [comment]
@iceytea 这篇什么进度了？

**Comment by sunui** [comment]
翻译释放

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6452
