### ISSUE TITLE
如何计划你的一天 —— 这里有一份攻略请查收

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6403]
* 原文链接：[This Is How To Plan A Day.](https://medium.com/swlh/this-is-how-to-plan-a-day-94dc24135e1f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/this-is-how-to-plan-a-day.md)
* PR 地址：#6403
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4-5 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by todaycoder001** [comment]
认领翻译 @sunui

**Comment by sunui** [comment]
@todaycoder001 棒极啦 🎉

**Comment by sunui** [comment]
@todaycoder001 翻译什么进度了？

**Comment by todaycoder001** [comment]
已经翻译完了，再稍微调整下格式，估计今晚或者明天就可以commit了 @sunui

**Comment by fanyijihua** [comment]
PR 地址：#6436
