### ISSUE TITLE
TypeScript 3.7 Beta 版发布

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6419]
* 原文链接：[Announcing TypeScript 3.7 Beta](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/announcing-typescript-3-7-beta.md)
* PR 地址：#6449
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：8-9 分
* 校对积分：2-4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Xuyuey** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Xuyuey 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6449
