### ISSUE TITLE
设置 git 别名

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6420]
* 原文链接：[Git Aliases I Use (Because I'm Lazy)](https://victorzhou.com/blog/git-aliases/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/git-aliases.md)
* PR 地址：#6435
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2-3 分
* 校对积分：1-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6435
