### ISSUE TITLE
使用 `import()` 执行 JavaScript 代码

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6421]
* 原文链接：[Evaluating JavaScript code via `import()`](https://2ality.com/2019/10/eval-via-import.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/eval-via-import.md)
* PR 地址：#6427
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6427

**Comment by HytonightYX** [comment]
翻译认领

**Comment by EmilyQiRabbit** [comment]
> 翻译认领

翻译认领要在 pr 地址下评论哦
