### ISSUE TITLE
这么多编程语言，我该怎么选？

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6425]
* 原文链接：[How I decide between many programming languages](https://drewdevault.com/2019/09/08/Enough-to-decide.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/enough-to-decide.md)
* PR 地址： #6485
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3-3.5 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mingxing47** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@mingxing47 棒极啦 :tada:

**Comment by sunui** [comment]
@mingxing47 什么进度了

**Comment by sunui** [comment]
@mingxing47 本文重新释放

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6485
