### ISSUE TITLE
用户体验设计的未来

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#643]
* 原文链接：[The Future of UX Design](https://uxdesign.cc/the-future-of-ux-design-8942e8fe0e8f#.83cutbv0n)
* 掘金链接：[UI 设计的未来](http://gold.xitu.io/entry/5791d746d342d30059cf2253/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-future-of-ux-design.md)
* 文章分类：**设计**
* PR 地址：[:apple:](https://github.com/xitu/gold-miner/pull/646)

翻译时间：3 天
校对时间：1 天
翻译积分：4 分
校对积分：1 分
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by Kulbear** [comment]
认领 一会就搞定

**Comment by sqrthree** [comment]
@Kulbear 质量最重要~质量最重要哈~~ \(^o^)/~

**Comment by rottenpen** [comment]
申请校对

**Comment by yifili09** [comment]
认领一个。

**Comment by rottenpen** [comment]
认领
