### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by sleepingxixi** [xitu/gold-miner#6432]
- 公司/学校：北京汉光百货有限责任公司
- 工作内容/专业：微信小程序前端开发
- 常浏览的国外网站：目前没怎么看过国外的网站
- 英语水平：英语六级
- 翻译经验：无
- 主要翻译方向：前端文档
- 个人博客：https://juejin.im/user/5d638f21518825271f67d09b
- 个人介绍：我不是一个技术大牛，但希望能不断提高自己。大学毕业两年，之前从事java开发及运维，虽然得到了领导和同事们的认可，但是相比后台的逻辑，我更喜欢可视化的界面，现在从事前端开发。虽然没怎么看过国外的网站，但是有时候看一些其他人分享的英文文章还是可以看懂。平时也比较喜欢看书画画，希望有机会参与到此项目中。

**Comment by kezhenxu94** [comment]
Hi, @sleepingxixi 感谢你申请加入掘金翻译计划，你需要做以下的事：

1. 认真学习 [掘金翻译计划译者教程](https://github.com/xitu/gold-miner/wiki)，校对和翻译文章时，严格遵循教程，杜绝不看教程，只知道问的伸手党；
2. 确认认真学习了 [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)，翻译文章时严格遵循，校对文章时也要指出译者的格式错误；
3. 确认认真学习了 [翻译和校对文章的注意事项](https://github.com/xitu/gold-miner/wiki/%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88)，避免翻译校对过程中出错；
4. 确定已学习完上述内容，加管理员微信 `CynicalKid`，**验证信息格式**：姓名 + GitHub 用户名；
5. 进群后修改群昵称为 GitHub id。

**注意**：管理员每天集中处理一次，稍安勿躁。加完微信后，管理员会在当天拉你进译者群，进群之后做下简单的自我介绍。加入微信群则代表申请译者成功，接下来你需要看译者教程，然后先校对至少一篇文章才能开始正式翻译文章。当然也可以继续校对文章。
