### ISSUE TITLE
为什么编码自己能让你成为更好的开发者

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6441]
* 原文链接：[Why Coding Your Own Makes You a Better Developer](https://medium.com/better-programming/why-coding-your-own-makes-you-a-better-developer-5c53439c5e4a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-coding-your-own-makes-you-a-better-developer.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3.5 分
* 校对积分：1-2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by quzhen12** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@quzhen12 棒极啦 :tada:

**Comment by sunui** [comment]
@quzhen12 翻译怎么样啦？抓紧啦，延期了

**Comment by quzhen12** [comment]
前段时间有点忙，这周有空闲，我会抓紧弄完的

**Comment by sunui** [comment]
@quzhen12 怎么样啦

**Comment by quzhen12** [comment]
还有一段没弄好，是在不好意思
