### ISSUE TITLE
JavaScript 的发布者/订阅者（Publisher/Subscriber）模式

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6443]
* 原文链接：[The Publisher/Subscriber Pattern in JavaScript](https://medium.com/better-programming/the-publisher-subscriber-pattern-in-javascript-2b31b7ea075a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-publisher-subscriber-pattern-in-javascript.md)
* PR 地址：#6459
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1-1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by weisiwu** [comment]
前排mark，准备校对。

**Comment by fanyijihua** [comment]
PR 地址：#6459
