### ISSUE TITLE
什么将会替代 JavaScript 呢

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6445]
* 原文链接：[What Replaces JavaScript](https://medium.com/young-coder/what-replaces-javascript-a6493b4e2d6e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-replaces-javascript.md)
* PR 地址：#6446
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：2 天
* 翻译积分：5-6 分
* 校对积分：1.5-3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6446
