### ISSUE TITLE
Swift + Initialization with Closures

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#645]
* 原文链接：[Swift + Initialization with Closures](https://medium.com/the-traveled-ios-developers-guide/swift-initialization-with-closures-5ea177f65a5#.dt9an4mzn)
* 掘金链接：[Swift + Initialization with Closures](http://gold.xitu.io/entry/57b424d37db2a200546b0978)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/swift-initialization-with-closures.md)
* 文章分类：**IOS**
* PR 地址：[快点我](https://github.com/xitu/gold-miner/pull/664)

翻译时间：3 天
校对时间：1 天
翻译积分：5 分
校对积分：1 分
（[积分有什么用](https://github.com/xitu/gold-miner/wiki)）

**Comment by circlelove** [comment]
收一个

**Comment by yifili09** [comment]
来晚了

**Comment by sqrthree** [comment]
@circlelove 好哒~~ 
@yifili09 哈哈，就差辣么一点

**Comment by yifili09** [comment]
@sqrthree 校对🈸

**Comment by StrThree** [comment]
厉害~~

**Comment by sqrthree** [comment]
@STRThree 撞名了 = =

**Comment by STRThree** [comment]
人们常常会欺骗你，是为了让你明白，有时候，你唯一应该相信的人就是你自己
——宫崎骏 《千与千寻》
