### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by jokingzhang** [xitu/gold-miner#6460]
- 公司：滴滴
- 工作内容：前端
- 常浏览的国外网站：https://medium.com https://dev.to/ https://reactresources.com
- 英语水平：4级
- 翻译经验：目前翻译过 18 篇文章，在掘金发表：https://juejin.im/user/59534d5bf265da6c4602bb8d
- 主要翻译方向：前端
- 个人博客：https://juejin.im/user/59534d5bf265da6c4602bb8d 个人博客正在搞：http://www.jokingzhang.com/
- 个人介绍：@joking_zhang 目前北京，现就职于滴滴/基础平台，前端小白，poppin新手。

开始写这个专栏文章的初衷是：
1、英文没有那么好，阅读英文文档有些吃力；
2、处于瓶颈期，想要进步，希望系统的学习前端的知识，但是市面上中文的技术书籍，博客文章很多，能让我自己读起来赏心悦目，又十分符合自己目前想学的却比较少。
3、老外写的东西还不错，质量很高，且包含大量示例（作者一直认为：不包含示例的技术博客就是耍流氓🤣）

于是，我开始了我的翻译之旅...

如果，有幸文章被您看到，您觉得有用处的话，就是我最大的荣幸了；写的不对的地方也欢迎吐槽~

**Comment by sunui** [comment]
Hi @jokingzhang ，感谢你申请加入掘金翻译计划，你需要做以下的事：

**1.** 认真学习 [掘金翻译计划译者教程](https://github.com/xitu/gold-miner/wiki)，校对和翻译文章时，严格遵循教程，杜绝不看教程，只知道问的伸手党；

**2.** 确认认真学习了 [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)，翻译文章时严格遵循，校对文章时也要指出译者的格式错误；

**3.** 确认认真学习了 [翻译和校对文章的注意事项](https://github.com/xitu/gold-miner/wiki/%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88)，避免翻译校对过程中出错。

**4.** 确定已学习完上述内容，加管理员微信 `glowjiang`，**验证信息格式**：姓名 + GitHub 用户名；

**注意**：管理员每天集中处理一次，稍安勿躁。加完微信后，管理员会在当天拉你进译者群，进群之后做下简单的自我介绍。加入微信群则代表申请译者成功，接下来你需要看译者教程，然后先校对至少一篇文章才能开始正式翻译文章。当然也可以继续校对文章。

**Comment by leviding** [comment]
灰常赞喔 👍
