### ISSUE TITLE
如何将 SVG 图标用做 React 组件？

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6467]
* 原文链接：[How to use SVG Icons as React Components?](https://www.robinwieruch.de/react-svg-icon-components)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/react-svg-icon-components.md)
* PR 地址：#6474
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TiaossuP** [comment]
@fanyijihua 翻译认领

**Comment by HydeSong** [comment]
@fanyijihua 翻译认领

**Comment by EmilyQiRabbit** [comment]
奇怪，两个人认领了翻译？而且并没有触发自动回复诶？ @sunui

**Comment by EmilyQiRabbit** [comment]
感觉有 bug

**Comment by sunui** [comment]
翻译认领

**Comment by sunui** [comment]
robot 挂掉了 @TiaossuP 开始翻译吧

**Comment by EmilyQiRabbit** [comment]
@HydeSong 友情提示，这篇翻译已经被认领了哦～你来晚了一步～

**Comment by fanyijihua** [comment]
PR 地址：#6474
