### ISSUE TITLE
申请译者

### ISSUE THREAD

**Issue by EdwardDing** [xitu/gold-miner#647]
你好，我是Edward，耶鲁CS毕业，目前在Oracle HQ的Mobile Cloud Service组负责Intelligent Bots Cloud Service项目的框架开发。平时喜欢自己捣鼓iOS开发，经常访问[Ray Wenderlich](https://www.raywenderlich.com/)和[AppCoda](https://www.appcoda.com/tutorials/ios/)。曾和朋友联合翻译并出版[《Python语言及其应用》](https://www.amazon.cn/%E5%9B%BE%E7%81%B5%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E4%B8%9B%E4%B9%A6-Python%E8%AF%AD%E8%A8%80%E5%8F%8A%E5%85%B6%E5%BA%94%E7%94%A8-%E5%8D%A2%E5%B8%83%E8%AF%BA%E7%BB%B4%E5%85%8B/dp/B018EOG4PI/ref=sr_1_1?ie=UTF8&qid=1471455733&sr=8-1&keywords=python%E8%AF%AD%E8%A8%80%E5%8F%8A%E5%85%B6%E5%BA%94%E7%94%A8)，个人博客：[jiarui-blog.com](http://www.jiarui-blog.com/)，微信公众号刚开没多久，叫[程序猴猴猴](http://www.jiarui-blog.com/wp-content/uploads/2016/07/qrcode.jpg)。

**Comment by antonia0912** [comment]
@EdwardDing 欢迎来掘金翻译计划玩 请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群

**Comment by EdwardDing** [comment]
@antonia0912 好的谢谢
