### ISSUE TITLE
简单的谬误

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6473]
* 原文链接：[The fallacy of easy](https://uxdesign.cc/the-fallacy-of-easy-a89ef864759b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-fallacy-of-easy.md)
* PR 地址：#6496
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Charlo-O** [comment]
翻译认领

**Comment by EmilyQiRabbit** [comment]
@sunui 机器人又坏了吧 =。=

**Comment by sunui** [comment]
这篇手动加的，忘记添加翻译认领标签啦，可以翻译了

**Comment by Charlo-O** [comment]
https://juejin.im/post/5eca7e8ee51d45784a354d1c
@lsvih  已发布~
