### ISSUE TITLE
设计离线优先的网络应用

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6479]
* 原文链接：[Designing Offline-First Web Apps](https://alistapart.com/article/offline-first/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/offline-first.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
我我我🙌 认领翻译

**Comment by fanyijihua** [comment]
@EmilyQiRabbit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6501
