### ISSUE TITLE
让字母“i”的点动起来的秘密

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6487]
* 原文链接：[The Trick to Animating the Dot on the Letter “i”](https://css-tricks.com/the-trick-to-animating-the-dot-on-the-letter-i/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-trick-to-animating-the-dot-on-the-letter-i.md)
* PR 地址：#6502
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by vitoxli** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@vitoxli 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6502
