### ISSUE TITLE
推荐后端优秀英文文章

### ISSUE THREAD

**Issue by nettee** [xitu/gold-miner#6489]
- 原文链接：https://medium.com/swlh/real-world-dynamic-programming-seam-carving-9d11c5b0bfca
- 简要介绍：这篇文章用一个图片处理的 seam carving 的例子讲解了动态规划算法的实际应用，一方面能让人理解动态规划的各个步骤，包括子问题的划分、递归矩阵、以及迭代式的代码；另一方面也是对 seam carving 方法的一个很好的讲解。

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by EmilyQiRabbit** [comment]
好长，先 Mark 一下...

**Comment by sunui** [comment]
感谢推荐 已发布 #6491  @nettee @EmilyQiRabbit
