### ISSUE TITLE
动态规划算法的实际应用：接缝裁剪

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6491]
* 原文链接：[Real-world dynamic programming: seam carving](https://medium.com/swlh/real-world-dynamic-programming-seam-carving-9d11c5b0bfca)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/real-world-dynamic-programming-seam-carving.md)
* PR 地址：#6497
* 文章分类：**后端/算法**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nettee** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@nettee 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6497

**Comment by nettee** [comment]
翻译时间、翻译积分这些都不写的吗。。
