### ISSUE TITLE
如何确定团队工作的优先级

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6493]
* 原文链接：[How To Prioritize Your Team’s Work](https://medium.com/better-programming/how-to-prioritize-your-teams-work-9e68f5e571c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-prioritize-your-teams-work.md)
* PR 地址：#6519
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by todaycoder001** [comment]
领取翻译 @sunui

**Comment by todaycoder001** [comment]
翻译认领 @sunui

**Comment by fanyijihua** [comment]
@todaycoder001 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6519
