### ISSUE TITLE
推荐前端优秀英文文章

### ISSUE THREAD

**Issue by HytonightYX** [xitu/gold-miner#6498]
- 原文链接：https://softwareontheroad.com/nodejs-jwt-authentication-oauth/
- 简要介绍：通过登录、注册一个简单例子，node.js + argon2 / jwt，并且介绍其中加密原理，推荐！

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by EmilyQiRabbit** [comment]
👍👍🏻👍🏼👍🏽👍🏾👍🏿，Mark

**Comment by sunui** [comment]
感谢推荐  已发布 #6500  @HytonightYX @EmilyQiRabbit
