### ISSUE TITLE
认领 Things I Wish I Were Told About React Native

### ISSUE THREAD

**Issue by void-main** [xitu/gold-miner#65]
Hi 我是voidmain，从11年左右就开始做移动开发，自从fb推出了react native就十分关注这项技术，并且跟自己的朋友专门开设了rn学习小组。希望通过翻译这方面的文章帮助更多的朋友了解rn并在工作中用上rn。

**Comment by Glowin** [comment]
鹏神，这篇文章已经有人认领并完成初稿了哎
