### ISSUE TITLE
你不需要 passport.js — node.js认证指南

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6500]
* 原文链接：[You don't need passport.js - Guide to node.js authentication](https://softwareontheroad.com/nodejs-jwt-authentication-oauth/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/nodejs-jwt-authentication-oauth.md)
* PR 地址：#6512
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
@HytonightYX 你是不是要寄几翻译呀～？

**Comment by HytonightYX** [comment]
@EmilyQiRabbit 嗯嗯 😂

**Comment by HytonightYX** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@HytonightYX 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6512
