### ISSUE TITLE
设计的变革 —— 从用户体验到个人体验

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6505]
* 原文链接：[The evolution of the Design — from UX towards personal experience](https://uxdesign.cc/the-evolution-of-the-design-from-ux-towards-personal-experience-7585687927ef)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-evolution-of-the-design-from-ux-towards-personal-experience.md)
* PR 地址：#6530
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Charlo-O** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Charlo-O 棒极啦 :tada:
