### ISSUE TITLE
将 GraphQL 概念可视化

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6517]
* 原文链接：[GraphQL Concepts Visualized](https://blog.apollographql.com/the-concepts-of-graphql-bc68bd819be3)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-concepts-of-graphql.md)
* PR 地址： #6520
* 文章分类：**前端/后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6520
