### ISSUE TITLE
推荐前端优秀英文文章

### ISSUE THREAD

**Issue by lihaobhsfer** [xitu/gold-miner#6521]
- 原文链接：https://medium.com/skillshare-team/how-we-ditched-redux-for-mobx-a05442279a2b
- 简要介绍：对比 Redux 和 Mobx 的优劣，提供两种方式实现状态管理的示例

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lihaobhsfer** [comment]
顺便问一下可否预定自己翻译？

**Comment by sunui** [comment]
可以认领了 #6526

**Comment by lihaobhsfer** [comment]
翻译认领

**Comment by lihaobhsfer** [comment]
已认领，感谢～
