### ISSUE TITLE
推荐后端优秀英文文章

### ISSUE THREAD

**Issue by cyz980908** [xitu/gold-miner#6524]
- 原文链接：https://tsh.io/blog/how-to-write-video-chat-app-using-webrtc-and-nodejs/
- 简要介绍：利用 WebRTC 和Node，开发一个实时视频聊天应用。简洁精炼，推荐推荐！

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by cyz980908** [comment]
是不是因为我推荐的文章太烂了...

**Comment by lsvih** [comment]
不是啦，单纯是这篇文章比较难处理，大家在偷懒www  内容还是挺好的，我一会儿加上

**Comment by lsvih** [comment]
Proposed #6586
