### ISSUE TITLE
我们为何抛弃 Redux 拥抱 MobX

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6526]
* 原文链接：[How We Ditched Redux for MobX](https://medium.com/skillshare-team/how-we-ditched-redux-for-mobx-a05442279a2b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-we-ditched-redux-for-mobx.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
本文由 @lihaobhsfer 认领

**Comment by lihaobhsfer** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lihaobhsfer 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6538
