### ISSUE TITLE
申请译者

### ISSUE THREAD

**Issue by Chunyulo** [xitu/gold-miner#653]
你好，我是Chunyulo，CS 研究生毕业，目前在做Android开发，经常访问的英文网站developer.google 跟stackoverflow。并没有翻译过文章，因此感兴趣过来申请成为译者试试。

**Comment by antonia0912** [comment]
@Chunyulo 欢迎来掘金翻译计划玩 请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群

**Comment by Chunyulo** [comment]
@antonia0912 微信已申请，谢谢
