### ISSUE TITLE
PHP 7.4 有什么新功能？你必须掌握的 10 大特性

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6532]
* 原文链接：[What’s new in PHP 7.4? Top 10 features that you need to know](https://medium.com/@daniel.dan/whats-new-in-php-7-4-top-10-features-that-you-need-to-know-e0acc3191f0a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/whats-new-in-php-7-4-top-10-features-that-you-need-to-know.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
本文由 @todaycoder001 认领

**Comment by todaycoder001** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@todaycoder001 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6549
