### ISSUE TITLE
使用 Redux Offline 和 Apollo 进行离线 GraphQL 查询

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6534]
* 原文链接：[Offline GraphQL Queries with Redux Offline and Apollo](http://www.petecorey.com/blog/2017/07/24/offline-graphql-queries-with-redux-offline-and-apollo/?from=east5th.co)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/offline-graphql-queries-with-redux-offline-and-apollo.md)
* PR 地址：#6541 
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by vitoxli** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@vitoxli 棒极啦 :tada:

**Comment by sunui** [comment]
@vitoxli 翻译怎么样了？

**Comment by vitoxli** [comment]
@sunui 已经根据校对进行修改啦
