### ISSUE TITLE
C++ 中清晰明了的状态机代码

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6536]
* 原文链接：[Expressive Code for State Machines in C++](https://www.fluentcpp.com/2019/09/24/expressive-code-for-state-machines-in-cpp/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/expressive-code-for-state-machines-in-cpp.md)
* PR 地址：#6552
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by todaycoder001** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@todaycoder001 棒极啦 :tada:

**Comment by zh1an** [comment]
翻译认领

**Comment by todaycoder001** [comment]
@sunui  这篇文章已经有人翻译完了，麻烦重新assign给他

**Comment by zh1an** [comment]
翻译认领

**Comment by fanyijihua** [comment]
PR 地址：#6552
