### ISSUE TITLE
推荐前端/后端

### ISSUE THREAD

**Issue by zyfsuzy** [xitu/gold-miner#6540]
- 原文地址:   https://dev.to/antjanus/my-personal-git-tricks-cheatsheet-23j1
- 简要介绍：个人珍藏的 Git 使用技巧

---
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by vitoxli** [comment]
这个可以，马了

**Comment by sunui** [comment]
已发布 #6547
