### ISSUE TITLE
我个人的 Git 技巧备忘录

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6547]
* 原文链接：[My Personal Git Tricks Cheatsheet](https://dev.to/antjanus/my-personal-git-tricks-cheatsheet-23j1)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/my-personal-git-tricks-cheatsheet.md)
* PR 地址：#6548
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Pingren** [comment]
翻译认领

**Comment by sunui** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@sunui 棒极啦 :tada:

**Comment by sunui** [comment]
@Pingren  可以翻译了哈  机器人抽了

**Comment by fanyijihua** [comment]
PR 地址：#6548
