### ISSUE TITLE
申请译者

### ISSUE THREAD

**Issue by zhouzihanntu** [xitu/gold-miner#655]
你好，我叫脚板，准大四前端汪，目前还在实习。英语水平：通过BECV考试；除Github外常晃悠的社区/问答类网站Reddit/StackOverflow/Quora，工具网站JSFiddle/Codepen，学习网站Coursera/Udacity/Codecademy等，浏览英文文档和观看YouTube上的tutorial基本无压力，暂时没有完整的博客不过在Github上有个笔记性质的仓库[FE-DEV-DIARY](https://github.com/zhouzihanntu/FE-DEV-DIARY)，对翻译计划很感兴趣希望能加入你们！

**Comment by antonia0912** [comment]
@zhouzihanntu 欢迎来掘金翻译计划玩 请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群

**Comment by zhouzihanntu** [comment]
好的 谢谢~
