### ISSUE TITLE
理解递归、尾调用优化和蹦床函数优化

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6554]
* 原文链接：[Understanding Recursion, Tail Call and Trampoline Optimizations](https://marmelab.com/blog/2018/02/12/understanding-recursion.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/understanding-recursion.md)
* PR 地址： #6557
* 文章分类：**前端/后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
本文由 @cyz980908  认领

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6557
