### ISSUE TITLE
使用 JavaScript 编写 JSON 解析器

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6565]
* 原文链接：[JSON Parser with JavaScript](https://lihautan.com/json-parser-with-javascript/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/json-parser-with-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
本文由 @Gavin-Gong 翻译

**Comment by Gavin-Gong** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Gavin-Gong 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6582
