### ISSUE TITLE
如何用 Nest.js、MongoDB 和 Vue.js 搭建一个博客

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6568]
* 原文链接：[How To Build a Blog with Nest.js, MongoDB, and Vue.js](https://www.digitalocean.com/community/tutorials/how-to-build-a-blog-with-nest-js-mongodb-and-vue-js)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-build-a-blog-with-nest-js-mongodb-and-vue-js.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by sunui** [comment]
Hello @cyz980908 翻译什么进度啦

**Comment by cyz980908** [comment]
> Hello @cyz980908 翻译什么进度啦

2/3这样了，年末有点忙，抱歉哦

**Comment by fanyijihua** [comment]
PR 地址：#6617
