### ISSUE TITLE
申请译者

### ISSUE THREAD

**Issue by xzpjerry** [xitu/gold-miner#657]
Hi，在下下学期大三，即将赴美（大二转学至美国），专业CS，常访问英文网站-->Github/Stackoverflow/Youtube， 没有翻译文章的经验，想通过申请成为译者翻译感兴趣的文章提升自己英语水平，个人博客'https://blog.starr.vip/', 希望能互相交流学习。

**Comment by antonia0912** [comment]
@xzpjerry 欢迎来掘金翻译计划玩 请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群
