### ISSUE TITLE
树莓派 4 GPIO 简介及使用 Node.js 控制树莓派

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6571]
* 原文链接：[An introduction to Raspberry Pi 4 GPIO and controlling it with Node.js](https://itnext.io/an-introduction-to-raspberry-pi-4-gpio-and-controlling-it-with-node-js-10f2ce41af12)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/an-introduction-to-raspberry-pi-4-gpio-and-controlling-it-with-node-js.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Weirdochr** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Weirdochr 棒极啦 :tada:

**Comment by Weirdochr** [comment]
@sunui @Glowin 你好 我fork了以后在TODO1里没有找到本篇文章..

**Comment by sunui** [comment]
@Weirdochr  https://github.com/xitu/gold-miner/blob/master/TODO1/an-introduction-to-raspberry-pi-4-gpio-and-controlling-it-with-node-js.md

**Comment by sunui** [comment]
@Weirdochr Hello，翻译进度怎么样啦

**Comment by Glowin** [comment]
@Weirdochr 译者你好，请问一下这篇文章翻译进度咋样了？如果放弃翻译的话，我们让其他译者翻译了。

**Comment by fanyijihua** [comment]
PR 地址：#6749

**Comment by Weirdochr** [comment]
> @Weirdochr 译者你好，请问一下这篇文章翻译进度咋样了？如果放弃翻译的话，我们让其他译者翻译了。

不好意思实在拖得太久了，已经完成翻译了。

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6868946182325043207/
