### ISSUE TITLE
9 月 10 月及 TC39 文档积分已更新

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6576]
请在 https://github.com/xitu/gold-miner/blob/master/integrals.md 查询积分~

如有问题请在此 issue 留言 😃

如需兑换奖品请按 wiki 说明联系负责人

---

目前正在统计与更新积分的文章如下表所示：

https://github.com/xitu/gold-miner/issues?q=is%3Aissue+label%3Areward-pending+is%3Aclosed

如有出现文章一直在审核中情况的，请在 issue 中 at 我或者在群里呼叫管理员 🤝 

---

目前仍有下述文章未发布至掘金故暂未统计（待作者及运营处理）：

https://github.com/xitu/gold-miner/issues?q=is%3Aclosed+is%3Aissue+label%3Awaiting-for-publish

**Comment by lsvih** [comment]
TODO list:

- [x] 统计 2020 年 2 月推荐文章积分
- [ ] 统计 2020 年 1 月 2 月翻译与校对积分

**Comment by lsvih** [comment]
计划之后一周更新一次（

**Comment by snowyYU** [comment]
hi,突然发现我之前翻的一篇文章积分加到别的同学下面啦
[文章链接](https://juejin.im/post/5c26c1b65188252dcb312ad6)

**Comment by lsvih** [comment]
@snowyYU 收到，确实加错了，这几天更新积分的时候会更正过来，不好意思！

**Comment by snowyYU** [comment]
tks~

**Comment by YueYongDev** [comment]
#6377 已经发布到掘金，地址：https://juejin.im/post/5dad820ce51d4524ce222642

**Comment by lsvih** [comment]
抱歉前段时间赶毕业设计去了，这两天会把前面落下的分数算好

**Comment by lsvih** [comment]
@CoolRice 马上 🤦 前两个月太惨了

**Comment by zenblo** [comment]
之前的译文补发掘金https://juejin.im/post/6878561756793454599

**Comment by PingHGao** [comment]
TC39啥时候才能计算啊

**Comment by KimYangOfCat** [comment]
> TC39啥时候才能计算啊

同问

**Comment by lsvih** [comment]
@PingHGao @KimYangOfCat 我论文投完稿就弄.....本来以为掘金那边会整的

**Comment by lsvih** [comment]
@PingHGao @KimYangOfCat  TC 39 的专题已经向领导请示确认了，再不上线我也先把积分计算了 😵‍💫
