### ISSUE TITLE
如何为求职准备你的 GitHub

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6584]
* 原文链接：[How to prep your GitHub for job seeking](https://www.reddit.com/r/webdev/comments/90xmpw/how_to_prep_your_github_for_job_seeking/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how_to_prep_your_github_for_job_seeking.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：4~5 分
* 校对积分：1~3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nettee** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@nettee 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6604
