### ISSUE TITLE
5 个简单步骤为您的网站创建 Sitemap

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6590]
* 原文链接：[5 Easy Steps to Creating a Sitemap For a Website](https://www.quicksprout.com/creating-website-sitemap/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/creating-website-sitemap.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
本文由 @cyz980908 翻译

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6621
