### ISSUE TITLE
使用 Web Workers 优化事件监听器

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6592]
* 原文链接：[For the Sake of Your Event Listeners, Use Web Workers](https://macarthur.me/posts/use-web-workers-for-your-event-listeners)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/use-web-workers-for-your-event-listeners.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by vitoxli** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@vitoxli 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6614

**Comment by Alfxjx** [comment]
校对认领
