### ISSUE TITLE
推荐其他优秀英文文章

### ISSUE THREAD

**Issue by lihaobhsfer** [xitu/gold-miner#6593]
- 原文链接：https://towardsdatascience.com/top-7-modern-programming-language-to-learn-now-156863bd1eec
- 简要介绍：介绍当下（英文文章发布时间为2019年12月23日）受欢迎、比较具有前景的编程语言，对比其诞生缘由、优势和主要应用场景，供广大开发者参考

---

### 请完成并勾选以下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lihaobhsfer** [comment]
申请自己翻译，感谢！

**Comment by sunui** [comment]
感谢推荐 可以认领了 #6596

**Comment by lihaobhsfer** [comment]
翻译认领
