### ISSUE TITLE
现在就该学习的 7 门现代编程语言

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6596]
* 原文链接：[Top 7 Modern programming languages to learn now](https://towardsdatascience.com/top-7-modern-programming-language-to-learn-now-156863bd1eec)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/top-7-modern-programming-language-to-learn-now.md)
* PR 地址：#6618
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
本文由 @lihaobhsfer 翻译

**Comment by lihaobhsfer** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lihaobhsfer 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6618

**Comment by todaycoder001** [comment]
翻译认领
