### ISSUE TITLE
JavaScript 简史

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6603]
* 原文链接：[Brief History of JavaScript](https://roadmap.sh/guides/history-of-javascript)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/history-of-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunui** [comment]
本文由 @Pingren 翻译

**Comment by Pingren** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Pingren 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6606
