### ISSUE TITLE
我并不讨厌箭头函数

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6610]
* 原文链接：[I Don’t Hate Arrow Functions](https://davidwalsh.name/i-dont-hate-arrow-functions)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/i-dont-hate-arrow-functions.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TiaossuP** [comment]
@fanyijihua 翻译认领

**Comment by fanyijihua** [comment]
@TiaossuP 棒极啦 :tada:

**Comment by sunui** [comment]
@TiaossuP 大佬翻译得怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#6659
