### ISSUE TITLE
在什么时候你需要使用 Web Workers？

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6611]
* 原文链接：[When should you be using Web Workers?](https://dassur.ma/things/when-workers/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/when-workers.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by weibinzhu** [comment]
@fanyijihua 翻译认领

**Comment by fanyijihua** [comment]
@weibinzhu 棒极啦 :tada:

**Comment by sunui** [comment]
@weibinzhu Hello，翻译进度如何啦

**Comment by weibinzhu** [comment]
已完成，正准备提交pr

**Comment by fanyijihua** [comment]
PR 地址：#6643
