### ISSUE TITLE
推荐翻译VSCodeAPI

### ISSUE THREAD

**Issue by x1shi** [xitu/gold-miner#6612]
- 原文链接：https://code.visualstudio.com/api
- 简要介绍：VSCode官方文档

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [X] 本文很值得翻译，我推荐
* [X] 已经过初步搜索，暂未发现中文版译文

**Comment by sunui** [comment]
感谢推荐，找到了还不错的译文 https://liiked.github.io/VS-Code-Extension-Doc-ZH/#/api/README
