### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by jiecuoren** [xitu/gold-miner#662]
Hi, This is jiecuoren

Education: GIS MS
Carrer: Nokia/Microsoft/Funplus/BMW
Blog: www.bala.new
English: CET6
Experience:  6+ years developer and manager in R&D center in Foreign companies.

Hope can get reply soon. Thanks a lot. #661

**Comment by antonia0912** [comment]
@jiecuoren 欢迎来掘金翻译计划玩 请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群
