### ISSUE TITLE
用Nuxt（Vue.js）、strapi和 Apollo 建立博客

### ISSUE THREAD

**Issue by cyz980908** [xitu/gold-miner#6624]
- 原文链接：https://strapi.io/blog/build-a-blog-using-nuxt-strapi-and-apollo
- 简要介绍：前段时间有人推荐了如何使用nest、vue、mongodb，搭建博客。这篇文章是使用Nuxt.js、strapi 和 Apollo 搭建博客。其中Nuxt.js 是Vue的服务端渲染框架、strapi是一个很方便且开源的内容管理平台（这里用来管理数据库里的博客帖子），Apollo 用于 graphQL ，也就是前后端的交互。可以说是上次那篇博客的另一种实现方案。
另外...[strapi](https://strapi.io/)现在在公测的beta版本，如果有正式版本发布，掘金翻译计划有没有兴趣翻译一下文档。。。strapi 在GitHub 上有21k 的star，还挺多的。

### 请完成并勾选一下三项：

* [ x ] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [ x ] 本文很值得翻译，我推荐
* [ x ] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by vitoxli** [comment]
翻译认领

**Comment by sunui** [comment]
感谢推荐。


@vitoxli 可以认领了 #6628
