### ISSUE TITLE
NestJS 实现基本用户认证和会话

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6627]
* 原文链接：[NestJS Basic Auth and Sessions](https://blog.exceptionfound.com/2018/06/07/nestjs-basic-auth-and-sessions/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/nestjs-basic-auth-and-sessions.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by sunui** [comment]
@cyz980908 这篇怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#6731
