### ISSUE TITLE
使用 Nuxt (Vue.js)、Strapi 和 Apollo 构建博客

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6628]
* 原文链接：[Build a blog with Nuxt (Vue.js), Strapi and Apollo](https://strapi.io/blog/build-a-blog-using-nuxt-strapi-and-apollo)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/build-a-blog-using-nuxt-strapi-and-apollo.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by vitoxli** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@vitoxli 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6646
