### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by xzycn** [xitu/gold-miner#663]
Hello，我是ddddn。211 本科学士，已工作2年有余。
常浏览stackoverflow[http://stackoverflow.com/users/4447404/zhaoyang-xu] , google developer , github及各种开源项目官方网站。
曾经翻译过一点nodejs相关文档，最近正在翻译ES官方[参考指南](https://github.com/Infinite-Explorer/Elasticsearch-Reference)。
觉知本人英语水平还有很大提升空间，并且认为该项目非常有意义，利人利己。所以现在请求加入译者行列。

**Comment by antonia0912** [comment]
@xzycn 欢迎来掘金翻译计划玩 请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群
