### ISSUE TITLE
再见，整洁的代码

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6632]
* 原文链接：[Goodbye, Clean Code](https://overreacted.io/goodbye-clean-code/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/goodbye-clean-code.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zh1an** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@zh1an 棒极啦 :tada:

**Comment by zh1an** [comment]
@fanyijihua @sunui 翻译完成！
