### ISSUE TITLE
荐优秀后端英文文章

### ISSUE THREAD

**Issue by cyz980908** [xitu/gold-miner#6634]
- 原文链接：https://www.freecodecamp.org/news/a-thorough-introduction-to-distributed-systems-3b91562c9b3c/
- 简要介绍：对分布式系统的全面介绍。就分布式而言，个人感觉没有写的特别好的入门文章，但是这篇写的不错。这篇文章并没有复杂的分布式的算法与理论，用通俗地话来全面地介绍分布式系统。从什么是分布式系统、为什么要使用分布式系统、再深入到分布式数据存储、从而提出 CAP 理论、再而讨论分布式计算、分布式文件系统、分布式消息系统、区块链等，在讨论的同时，还举了许多优秀框架的例子和推荐拓展阅读。是一篇很不错的分布式入门文章。

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by cyz980908** [comment]
申请自己翻译～

**Comment by sunui** [comment]
文章比较经典，市面上已经有不少译文啦，你看一下翻译的怎么样。

* https://www.jianshu.com/p/bc764647169c
* https://www.jianshu.com/p/a4d2a4c84605
* https://blog.csdn.net/weixin_34366546/article/details/93791430
* https://www.cnblogs.com/yufengzhang/p/9473912.html

**Comment by cyz980908** [comment]
啊谢谢啦～
