### ISSUE TITLE
推荐优秀后端英文文章

### ISSUE THREAD

**Issue by cyz980908** [xitu/gold-miner#6635]
- 原文链接：https://towardsdatascience.com/how-to-choose-the-right-database-afcf95541741
- 简要介绍：如何选择一个合适的数据库。文章末尾有总结：对于缓存—使用键值DB，对于类似图形的数据—使用图形数据库，倾向于查询列/特性的子集，请使用列DB，对于所有其他用例——关系数据库或文档数据库。

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by sunui** [comment]
感谢推荐 已发布 #6639
