### ISSUE TITLE
推荐优秀后端英文文章

### ISSUE THREAD

**Issue by cyz980908** [xitu/gold-miner#6636]
- 原文链接：https://towardsdatascience.com/is-no-sql-killing-sql-3b0daff69ea
- 简要介绍：在 NoSQL 数据库流行的当下，作者解释了 SQL 永远不会消亡的两个原因。
1. NoSQL 数据库不会取代分析数据库
2. NoSQL 数据库的优点并不是因为它们不支持 SQL 语言

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by nettee** [comment]
原文链接忘贴了啊

**Comment by cyz980908** [comment]
> 原文链接忘贴了啊

谢谢。。。已更新

**Comment by sunui** [comment]
感谢推荐  已发布 #6640
