### ISSUE TITLE
如何选择合适的数据库

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6639]
* 原文链接：[How to choose the right database](https://towardsdatascience.com/how-to-choose-the-right-database-afcf95541741)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-choose-the-right-database.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6660
