### ISSUE TITLE
SQL 将死于 No-SQL 之手？

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6640]
* 原文链接：[Is No-SQL killing SQL?](https://towardsdatascience.com/is-no-sql-killing-sql-3b0daff69ea)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/is-no-sql-killing-sql.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JalanJiang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@JalanJiang 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6662
