### ISSUE TITLE
使用 Python 进行边缘检测

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6647]
* 原文链接：[Edge Detection in Python](https://towardsdatascience.com/edge-detection-in-python-a3c263a13e03)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/edge-detection-in-python.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@lsvih 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6650
