### ISSUE TITLE
算法不是产品

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6649]
* 原文链接：[The Algorithm Is Not The Product](https://towardsdatascience.com/the-algorithm-is-not-the-product-2e0b3740bdfa)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-algorithm-is-not-the-product.md)
* PR 地址：
* 文章分类：**算法**，**产品**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fireairforce** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@fireairforce 棒极啦 :tada:

**Comment by fireairforce** [comment]
最近过年，拖延几天吧hhh

**Comment by fanyijihua** [comment]
PR 地址：#6652
