### ISSUE TITLE
推荐后端优秀英文文章

### ISSUE THREAD

**Issue by ahabhgk** [xitu/gold-miner#6653]
- 原文链接：https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#restful
- 简要介绍：如何设计实用的 Restful API 的最佳实践，非常全面值得借鉴

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
这篇有译文了哈~ https://www.oschina.net/translate/best-practices-for-a-pragmatic-restful-api

**Comment by ahabhgk** [comment]
好吧，之前没太注意
