### ISSUE TITLE
8 UI design trends for 2020

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6657]
* 原文链接：[8 UI design trends for 2020](https://uxdesign.cc/8-ui-ux-design-trends-for-2020-68e37b0278f6)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/8-ui-ux-design-trends-for-2020.md)
* PR 地址：
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Charlo-O** [comment]
有翻译了

**Comment by lsvih** [comment]
http://www.pursuer.cn/pro/detail?articleId=590 已有
