### ISSUE TITLE
Translator Application

### ISSUE THREAD

**Issue by richardo2016** [xitu/gold-miner#666]
Hello, I am Richardo (yep, not Richard but the one with one 'o' ), Graduation in 2012.
Major: MIS.
English: CET 6
Employee in one Startup Company in Cheng Du City, Junior Front-end Engineer.
Skill Tag: Vuejs, React, VanillaJS, npm, stylus/less, jade/pug, WordPress(Woo Commerce),  laravel, etc.

**Comment by Kulbear** [comment]
Laravel?

**Comment by richardo2016** [comment]
thx to @Kulbear , my spelling mistake,it has been corrected to Laravel  : )

**Comment by sqrthree** [comment]
😄 I am a Front-end Engineer, too.

**Comment by antonia0912** [comment]
@richardo2016 hi 欢迎来翻译计划玩 请加我微信 antonia0912 备注GitHub ID 我来拉你进译者群

**Comment by richardo2016** [comment]
@antonia0912 好的，很期待与翻译计划中的朋友们一起讨论。已于昨日加微信（备注了 ID），烦请查看 :)
