### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by DeepMissea** [xitu/gold-miner#667]
你好，我是deepmissea。
计算机专业毕业，现在在红袖添香担任iOS软件工程师。
英语基础还不错，经常访问Github/Stackoverflow/raywenderlich/NSHiper/objc.io。
至今每天坚持扇贝打卡([打卡记录](https://www.shanbay.com/checkin/user/calendar/32341231/201608))，有完整阅读英文书籍文章经验(function programming swift，iOS Animations等)。
这是我的[博客](http://deepmissea.com/),希望有机会交流提高。

**Comment by Zheaoli** [comment]
麦克斯？

**Comment by DeepMissea** [comment]
哈哈，是的。

**Comment by antonia0912** [comment]
@DeepMissea hi 欢迎来翻译计划玩 请加我微信 antonia0912 备注GitHub ID 我来拉你进译者群
