### ISSUE TITLE
用 6 分钟学习如何用 Redis 缓存您的 NodeJS 应用！

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6673]
* 原文链接：[Learn to Cache your NodeJS Application with Redis in 6 Minutes!](https://itnext.io/learn-to-cache-your-nodejs-application-with-redis-in-6-minutes-745a574a9739)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/learn-to-cache-your-nodejs-application-with-redis-in-6-minutes.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8~9 天
* 校对时间：2 天
* 翻译积分：8~9 分
* 校对积分：2~3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6677
