### ISSUE TITLE
TypeScript 中带生成器的惰性管道

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6675]
* 原文链接：[Lazy Pipelines with Generators in TypeScript](https://itnext.io/fast-pipelines-with-generators-in-typescript-85d285ae6f51)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/fast-pipelines-with-generators-in-typescript.md)
* PR 地址：
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 ~ 6 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：2 ~ 3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by febrainqu** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@febrainqu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6694
