### ISSUE TITLE
给 UX 设计师的 6 个超实用技巧指南

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#668]
* 原文链接：[6 Practical Skills for UX Designers](https://uxdesign.cc/6-practical-skills-for-ux-designers-22c852d6c576#.vjeb02dwq)
* 掘金链接：[给 UX 设计师的 6 个超实用技巧指南](http://gold.xitu.io/entry/57bbbfa62e958a00694051ff)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/6-practical-skills-for-ux-designers.md)
* PR 地址：[不是我](https://github.com/xitu/gold-miner/pull/674)
* 文章分类：**设计**

----

* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Kulbear** [comment]
renling

**Comment by sqrthree** [comment]
@Kulbear Greet.

**Comment by siegeout** [comment]
有没抢到，心痛

**Comment by jiaowoyongqi** [comment]
手速好快。。。

**Comment by ldhlfzysys** [comment]
校对认领....

**Comment by sqrthree** [comment]
@ldhlfzysys 抱歉啦，已经有两个人认领了，另外下次在对应的 PR 下申请校对哈。
