### ISSUE TITLE
图像修复：人类和 AI 的对决

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6682]
* 原文链接：[Image Inpainting: Humans vs. AI](https://towardsdatascience.com/image-inpainting-humans-vs-ai-48fc4bca7ecc)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/image-inpainting-humans-vs-ai.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：3 天
* 翻译积分：6 ~ 7 分
* 校对积分：3 ~ 4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starry316** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@Starry316 棒极啦 :tada:
