### ISSUE TITLE
在 Vue 中编写 SVG 图标组件

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6688]
* 原文链接：[Making SVG Icon Component in Vue](https://medium.com/js-dojo/making-svg-icon-component-in-vue-cb7fac70e758)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/making-svg-icon-component-in-vue.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：1 ~ 2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fireairforce** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@fireairforce 棒极啦 :tada:

**Comment by fireairforce** [comment]
明天晚上交付吧= =最近在办公了

**Comment by lsvih** [comment]
辛苦了~

**Comment by fanyijihua** [comment]
PR 地址：#6703
