### ISSUE TITLE
用 Swift 开发我的第一个 iOS 应用前，我想要知道这些内容

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#669]
* 原文链接：[What I would like to know before I code my first iOS application in Swift](https://medium.com/@bkzl/what-i-would-like-to-know-before-i-code-my-first-ios-application-in-swift-f11fcdde7887#.oeafmue7p)
* 掘金链接：[用 Swift 开发我的第一个 iOS 应用前，我想要知道这些内容](http://gold.xitu.io/entry/57bbf625c4c97100615744ca)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-i-would-like-to-know-before-i-code-my-first-ios-application-in-swift.md)
* PR 地址：[PR 地址](https://github.com/xitu/gold-miner/pull/682)
* 文章分类：**IOS**

----

* 翻译时间：`4` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jiaowoyongqi** [comment]
抢！

**Comment by sqrthree** [comment]
@jiaowoyongqi Greet.

**Comment by jiaowoyongqi** [comment]
@sqrthree 翻译完成辣
