### ISSUE TITLE
停止在任何地方使用 ===

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6691]
* 原文链接：[Stop Using === Everywhere](https://medium.com/better-programming/stop-using-everywhere-fd025342132d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/stop-using-everywhere.md)
* PR 地址：
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 9 天
* 校对时间： 3 天
* 翻译积分： 7 分
* 校对积分： 3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZavierTang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ZavierTang 棒极啦 :tada:

**Comment by sunui** [comment]
@ZavierTang 这篇翻译怎么样啦

**Comment by fanyijihua** [comment]
PR 地址：#6750

**Comment by ZavierTang** [comment]
> @ZavierTang 这篇翻译怎么样啦

抱歉呀，特殊情况被隔离了呜呜呜...
