### ISSUE TITLE
关于 icon 设计的 7 大准则

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6700]
* 原文链接：[7 Principles of Icon Design](https://uxdesign.cc/7-principles-of-icon-design-e7187539e4a2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/7-principles-of-icon-design.md)
* PR 地址：
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：9 天
* 校对时间：3 天
* 翻译积分：7 ~ 8 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6739
