### ISSUE TITLE
一份数据科学 A/B 测试的简单指南

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6706]
* 原文链接：[A Simple Guide to A/B Testing for Data Science](https://towardsdatascience.com/a-simple-guide-to-a-b-testing-for-data-science-73d08bdd0076)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-simple-guide-to-a-b-testing-for-data-science.md)
* PR 地址：#6732
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：3 天
* 翻译积分：5 分
* 校对积分：2 ~ 3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Amberlin1970** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Amberlin1970 棒极啦 :tada:
