### ISSUE TITLE
用 Swift 的 Enums 类型帮你的应用实现 3D Touch 功能

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#671]
* 原文链接：[Using Swift’s Enums for Quick Actions](https://medium.com/the-traveled-ios-developers-guide/using-swifts-enums-for-quick-actions-a08c0f6d5b8b#.lbt8itrxd)
* 掘金链接：[用 Swift 的 Enums 类型帮你的应用实现 3D Touch 功能](http://gold.xitu.io/entry/57bbfb7479bc440063abce03/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/using-swifts-enums-for-quick-actions.md)
* PR 地址：[:smile:](https://github.com/xitu/gold-miner/pull/687)
* 文章分类：**IOS**

----

* 翻译时间：`4` 天
* 校对时间：`2` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeadLion** [comment]
@sqrthree  认领

**Comment by sqrthree** [comment]
@DeadLion 好哒

**Comment by EdwardDing** [comment]
可以申请校对吗？

**Comment by sqrthree** [comment]
@EdwardDing 表急啦，译者还在翻译呢~ 等到译者翻译完提 PR 之后，在对应的 PR 下申请校对哈~

**Comment by EdwardDing** [comment]
@sqrthree 原来如此，新人不太懂规矩哈哈😁 多谢说明
