### ISSUE TITLE
密码哈希的方法：PBKDF2，Scrypt，Bcrypt 和 ARGON2

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6715]
* 原文链接：[Password Hashing: PBKDF2, Scrypt, Bcrypt and ARGON2](https://medium.com/@mpreziuso/password-hashing-pbkdf2-scrypt-bcrypt-and-argon2-e25aaf41598e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/password-hashing-pbkdf2-scrypt-bcrypt-and-argon2.md)
* PR 地址：#6792
* 文章分类：**算法**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by todaycoder001** [comment]
认领翻译

**Comment by todaycoder001** [comment]
翻译认领
