### ISSUE TITLE
About `rel=noopener`

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6717]
* 原文链接：[About `rel=noopener`](https://mathiasbynens.github.io/rel-noopener/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/rel-noopener.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fireairforce** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@fireairforce 棒极啦 :tada:

**Comment by fireairforce** [comment]
这篇文章翻译起来8太行，这个文章里面涉及到跨域的演示了，，，，，= =

**Comment by fireairforce** [comment]
![image](https://user-images.githubusercontent.com/32598811/75349054-f2efb080-58de-11ea-99f2-8a7955cb8784.png)
这里按照文章标红的地方，无法演示出来

**Comment by sunui** [comment]
@fireairforce 继续翻译了吗，继续翻译了的话演示不了的保持原文就好，没有的话就关闭啦。

**Comment by fireairforce** [comment]
这个我释放掉吧。。。我感觉我翻译不了

**Comment by sunui** [comment]
该文废弃
