### ISSUE TITLE
Git 的历史: 软件版本控制的主导之路

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6719]
* 原文链接：[The History of Git: The Road to Domination in Software Version Control](https://www.welcometothejungle.com/en/articles/btc-history-git)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/btc-history-git.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fireairforce** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@fireairforce 棒极啦 :tada:

**Comment by todaycoder001** [comment]
翻译好了直接@我翻译校验，谢谢 @fireairforce

**Comment by fanyijihua** [comment]
PR 地址：#6768

**Comment by fireairforce** [comment]
> 翻译好了直接@我翻译校验，谢谢 @fireairforce

已经翻译完成了，可以来校验了，谢谢哈
