### ISSUE TITLE
「最简单」的 Core Data 上手指南

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#672]
* 原文链接：[The Easiest Core Data](http://albertodebortoli.com/blog/2016/08/05/the-easiest-core-data/)
* 掘金链接：[「最简单」的 Core Data 上手指南](http://gold.xitu.io/entry/57bc06eaa633bd005d3f1e8a/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-easiest-core-data.md)
* PR 地址：[:smile:](https://github.com/xitu/gold-miner/pull/683)
* 文章分类：**iOS**

----

* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zheaoli** [comment]
抢了。。

**Comment by sqrthree** [comment]
@Zheaoli 妥~

**Comment by Zheaoli** [comment]
另外是iOS，，不是IOS。。。。。

**Comment by LoneyIsError** [comment]
翻译完我要认领校对
