### ISSUE TITLE
A Beginner’s Guide to Simulating Dynamical Systems with Python

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6727]
* 原文链接：[A Beginner’s Guide to Simulating Dynamical Systems with Python](https://towardsdatascience.com/a-beginners-guide-to-simulating-dynamical-systems-with-python-a29bc27ad9b1)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-beginners-guide-to-simulating-dynamical-systems-with-python.md)
* PR 地址：
* 文章分类：**算法**，**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：3 天
* 翻译积分：8~9 分
* 校对积分：3~4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
完成校对后我来输入公式

**Comment by Weirdochr** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Weirdochr 棒极啦 :tada:

**Comment by sunui** [comment]
@Weirdochr Hello,这篇翻译怎么样啦

**Comment by sunui** [comment]
@Weirdochr Closing soon if no response
