### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by todaycoder001** [xitu/gold-miner#6728]
- 原文链接：https://medium.com/swlh/the-7-programming-languages-frameworks-to-learn-in-2020-6f9ac923ec5d
- 简要介绍：2020年要学习的7种编程语言和框架

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端后端优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by todaycoder001** [comment]
指定自己翻译

**Comment by lsvih** [comment]
已发布 #6730
