### ISSUE TITLE
一些 NSFetchedResultsController 使用报错解决方案

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#673]
* 原文链接：[NSFetchedResultsController Woes](https://medium.com/bpxl-craft/nsfetchedresultscontroller-woes-3a9b485058#.5gva2sils)
* 掘金链接：[一些 NSFetchedResultsController 使用报错解决方案](http://gold.xitu.io/entry/57bbfe9da633bd005d3ebc22/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/nsfetchedresultscontroller-woes.md)
* PR 地址：[:apple:](https://github.com/xitu/gold-miner/pull/678)
* 文章分类：**iOS**

----

* 翻译时间：`4` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by siegeout** [comment]
认领

**Comment by lizwangying** [comment]
认领

**Comment by sqrthree** [comment]
@siegeout 好哒~ 
@lizwangying 来晚啦~~

**Comment by LoneyIsError** [comment]
翻译完我要认领校对

**Comment by sqrthree** [comment]
@LoneyIsError 等译者发了 PR 之后在对应的 PR 下申请校对哈。
