### ISSUE TITLE
2020 年要学习的 7 种编程语言和框架

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6730]
* 原文链接：[The 7 Programming Languages & Frameworks to Learn in 2020](https://medium.com/swlh/the-7-programming-languages-frameworks-to-learn-in-2020-6f9ac923ec5d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-7-programming-languages-frameworks-to-learn-in-2020.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 8 天
* 校对时间： 3 天
* 翻译积分： 7~8 分
* 校对积分： 3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
由@todaycoder001 认领

**Comment by todaycoder001** [comment]
翻译认领

**Comment by fanyijihua** [comment]
PR 地址：#6763
