### ISSUE TITLE
解决 web 应用程序中的内存泄漏问题

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6736]
* 原文链接：[Fixing memory leaks in web applications](https://nolanlawson.com/2020/02/19/fixing-memory-leaks-in-web-applications/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/fixing-memory-leaks-in-web-applications.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by febrainqu** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@febrainqu 棒极啦 :tada:

**Comment by sunui** [comment]
@febrainqu  Hello,这篇翻译怎么样啦
