### ISSUE TITLE
你的设计应该「所见即所得」

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#675]
* 原文链接：[What You See is What You Use](https://medium.com/the-year-of-the-looking-glass/what-you-see-is-what-you-use-5a97677a8c71?ref=uxdesignweekly#.8n33go9m6)
* 掘金链接：[你的设计应该「所见即所得」](http://gold.xitu.io/entry/57bd6d2bdf0eea005c6f5291/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-you-see-is-what-you-use.md)
* PR 地址：[:smile:](https://github.com/xitu/gold-miner/pull/685)
* 文章分类：**设计**

----

* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jiaowoyongqi** [comment]
抢_(:зゝ∠)_

**Comment by sqrthree** [comment]
@jiaowoyongqi 好哒~~
