### ISSUE TITLE
Go 发布新版 Protobuf API

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6753]
* 原文链接：[A new Go API for Protocol Buffers](https://blog.golang.org/a-new-go-api-for-protocol-buffers)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-new-go-api-for-protocol-buffers.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@todaycoder001 要求认领

**Comment by todaycoder001** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@todaycoder001 棒极啦 :tada:
