### ISSUE TITLE
眼动跟踪和移动世界的最佳用户体验实践

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6756]
* 原文链接：[Eye Tracking and The Best UX Practices in The Mobile World](https://medium.com/nyc-design/eye-tracking-and-the-best-ux-practices-in-the-mobile-world-a101f67f20dd)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/eye-tracking-and-the-best-ux-practices-in-the-mobile-world.md)
* PR 地址：#6806
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Charlo-O** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Charlo-O 棒极啦 :tada:

**Comment by lsvih** [comment]
发布专栏 https://zhuanlan.zhihu.com/p/120424545
