### ISSUE TITLE
给 NodeJS 的 Logs 点颜色看看！

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6757]
* 原文链接：[Making Logs Colorful in NodeJS](https://medium.com/front-end-weekly/making-logs-colorful-in-nodejs-b26b6cf9f0bf)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/making-logs-colorful-in-nodejs.md)
* PR 地址：
* 文章分类：**后端**，**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by lsvih** [comment]
PR 地址：#6788
