### ISSUE TITLE
推荐后端优秀英文文章

### ISSUE THREAD

**Issue by suhanyujie** [xitu/gold-miner#6758]
- 原文链接：https://fasterthanli.me/blog/2020/working-with-strings-in-rust/
- 简要介绍：计算机的基础知识相关，详述 Rust 中的字符串为何如此设计

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by suhanyujie** [comment]
不好意思 请忽略吧。此文 rust 社区今天刚发布了中文译文 https://rust.cc/article?id=08bc71ca-7aa1-4fce-93aa-614712430c66

**Comment by lsvih** [comment]
👌
