### ISSUE TITLE
如何编写更少的代码？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#676]
* 原文链接：[Writing Less Damn Code](http://www.heydonworks.com/article/on-writing-less-damn-code)
* 掘金链接：[如何编写更少的代码？](http://gold.xitu.io/entry/57bfaeb6128fe1005fb3d0e7/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/on-writing-less-damn-code.md)
* PR 地址：[:smile:](https://github.com/xitu/gold-miner/pull/684)
* 文章分类：**前端**

----

* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by richardo2016** [comment]
认领

**Comment by sqrthree** [comment]
@richardo2016 Hello，你是第一次参与我们的翻译计划么？第一次要从校对文章开始哟~ 校对过之后就可以申请翻译任务了

**Comment by Graning** [comment]
Get ？

**Comment by richardo2016** [comment]
@sqrthree 好的，刚阅读了规则，感谢提醒 : ）

**Comment by sqrthree** [comment]
@Graning Yes.

**Comment by circlelove** [comment]
撞头像了吗？ //

**Comment by circlelove** [comment]
认领。这个短。

**Comment by sqrthree** [comment]
@circlelove 好哒~
