### ISSUE TITLE
前端代码顶部的 Header 标签里都有些什么？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6761]
* 原文链接：[What’s going on in that front end head?](https://medium.com/front-end-weekly/whats-going-on-in-that-front-end-head-dd443f3fb7d5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/whats-going-on-in-that-front-end-head.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：3 天
* 翻译积分：4.5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6781
