### ISSUE TITLE
JSON.stringify() 的 5 个秘密特性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6767]
* 原文链接：[5 Secret features of JSON.stringify()](https://medium.com/javascript-in-plain-english/5-secret-features-of-json-stringify-c699340f9f27)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/5-secret-features-of-json-stringify.md)
* PR 地址：#6793
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：2 天
* 翻译积分：2.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fireairforce** [comment]
翻译认领

**Comment by lsvih** [comment]
@fireairforce 你要一次弄这两篇吗0.0

**Comment by fireairforce** [comment]
哈哈哈 那这篇我不要了= =

**Comment by fireairforce** [comment]
> @fireairforce 你要一次弄这两篇吗0.0

已经移除了领取

**Comment by lsvih** [comment]
@fireairforce 要忙得过来也可以把这篇要了的，也不怎么长

**Comment by fireairforce** [comment]
ok

**Comment by fireairforce** [comment]
翻译领取
