### ISSUE TITLE
人人都应该用的 Python 开源库

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#677]
* 原文链接：[The One Python Library Everyone Needs](https://glyph.twistedmatrix.com/2016/08/attrs.html)
* 掘金链接：[人人都应该用的 Python 开源库](http://gold.xitu.io/entry/57bc2962128fe1005f97be5a/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-one-python-library-everyone-needs.md)
* PR 地址：[:smile:](https://github.com/xitu/gold-miner/pull/688)
* 文章分类：**Python**

----

* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Graning** [comment]
认领

**Comment by sqrthree** [comment]
@Graning 你又要这个了？

**Comment by sqrthree** [comment]
@Graning 好吧，就这个了。那个我让别人了啊。

**Comment by Graning** [comment]
@sqrthree 恩😅
