### ISSUE TITLE
如何在 JavaScript 中使用新特性“顶层 await”

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6770]
* 原文链接：[How the new ‘Top Level Await’ feature works in JavaScript](https://medium.com/javascript-in-plain-english/javascript-top-level-await-in-a-nutshell-4e352b3fc8c8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/javascript-top-level-await-in-a-nutshell.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ssshooter** [comment]
翻译认领

**Comment by fanyijihua** [comment]
PR 地址：#6776
