### ISSUE TITLE
用依赖注入来解耦你的代码

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6774]
* 原文链接：[Decouple Your Code With Dependency Injection](https://medium.com/better-programming/decouple-your-code-with-dependency-injection-d893ae9edcf8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/decouple-your-code-with-dependency-injection.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JalanJiang** [comment]
翻译认领

**Comment by JalanJiang** [comment]
@lsvih 机器人好像坏掉了

**Comment by lsvih** [comment]
@JalanJiang 好像是的。。

**Comment by fanyijihua** [comment]
PR 地址：#6823
