### ISSUE TITLE
创建一个 Settings icon 的五种方法

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6780]
* 原文链接：[5 Ways to Create a Settings Icon](https://medium.com/@minoraxis/5-ways-to-create-a-settings-icon-fff8dc95e36d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/5-ways-to-create-a-settings-icon.md)
* PR 地址：
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by lsvih** [comment]
已发布 https://juejin.im/post/5e9e845be51d454709221d1f
