### ISSUE TITLE
11 个能让你的 App 像原生 App 的 Chrome API

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6785]
* 原文链接：[11 Chrome APIs That Will Give Your Web App a Native Feel](https://blog.bitsrc.io/11-chrome-apis-that-give-your-web-app-a-native-feel-ad35ad648f09)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/11-chrome-apis-that-give-your-web-app-a-native-feel.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：13 天
* 校对时间：4 天
* 翻译积分：10 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by lsvih** [comment]
@cyz980908 这篇咋样啦0.0

**Comment by Gesj-yean** [comment]
校对认领
