### ISSUE TITLE
8 个值得了解的树形数据结构

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6787]
* 原文链接：[8 Useful Tree Data Structures Worth Knowing](https://towardsdatascience.com/8-useful-tree-data-structures-worth-knowing-8532c7231e8c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/8-useful-tree-data-structures-worth-knowing.md)
* PR 地址：
* 文章分类：**算法**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Amberlin1970** [comment]
翻译认领

**Comment by lsvih** [comment]
@Amberlin1970 好的

**Comment by fanyijihua** [comment]
PR 地址：#6804
