### ISSUE TITLE
认领《探索Stripe Dashboard产品设计之道》～

### ISSUE THREAD

**Issue by CaesarPan** [xitu/gold-miner#68]

**Comment by Glowin** [comment]
好的，给你添加到 readme 里面了，欢迎加入 :+1:

**Comment by Glowin** [comment]
你好，我拉了一个掘金翻译计划译者的微信群，译者都在群里面，我会在群里面更新活动的最新进展，如果方便的话可以加我一下微信 Glowjiang。
