### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Grace-xhw** [xitu/gold-miner#680]
你好，我叫Grace, 英语专业毕业。
* 工作： 现任南京厚建云计算前端工程师
* 常浏览的国外网站： Github/Stackoverflow/YouTube
* 英语水平： 英语专业八级
* 翻译经验：这是我最近一个月的[翻译内容](http://www.zcfy.cc/@grace_wang/article)
* 个人blog： [Segmentfault](https://segmentfault.com/u/grace_xhw/articles)
* 目前接触技术： Vuejs、React、ES6、HTML(5)、CSS(3)等
* 爱前端，爱英语

以上是我的个人简介，希望能有幸参与掘金翻译计划。

**Comment by antonia0912** [comment]
@Grace-xhw 欢迎来掘金翻译计划玩 请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群
