### ISSUE TITLE
关于 JavaScript 中 Symbol 数据类型你需要了解的一切

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6801]
* 原文链接：[Everything you need to know about JavaScript symbols](https://levelup.gitconnected.com/everything-you-need-to-know-about-javascript-symbols-24650a163038)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/everything-you-need-to-know-about-javascript-symbols.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：9 天
* 校对时间：3 天
* 翻译积分：8.5 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by lsvih** [comment]
@cyz980908 这篇咋样啦~

**Comment by fanyijihua** [comment]
PR 地址：#7038
