### ISSUE TITLE
如何写一份能让你获得面试机会的前端求职简历

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6803]
* 原文链接：[How To Write a Front-End Developer Resume That Will Land You an Interview](https://medium.com/better-programming/how-to-write-a-front-end-developer-resume-that-will-land-you-an-interview-f188ba4fe68b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-write-a-front-end-developer-resume-that-will-land-you-an-interview.md)
* PR 地址： #7191
* 文章分类：**前端**，**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：10 天
* 校对时间：4 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by GJXAIOU** [comment]
翻译认领@lsvih

**Comment by fanyijihua** [comment]
@GJXAIOU 棒极啦 :tada:

**Comment by lsvih** [comment]
@GJXAIOU 这篇咋样啦

**Comment by sunui** [comment]
@GJXAIOU 请问这篇怎么样了

**Comment by sunui** [comment]
@GJXAIOU 超期释放

**Comment by febrainqu** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@febrainqu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7191
