### ISSUE TITLE
[request]: Eric 的组合软件系列文章

### ISSUE THREAD

**Issue by seognil** [xitu/gold-miner#6805]
Eric 的组合软件系列文章

之前我了解 FP 的时候发现的，
发现有一些完成的翻译版，
整理了一下还有一些没有翻译的，希望更新

（以及调整顺序之后编号有可能对不上了）

#### 这些是没翻译的

- [Composing Software: The Book](https://medium.com/javascript-scene/composing-software-the-book-f31c77fc3ddc)
- 出书重新排版后未翻译的章节
  - [The Dao of Immutability](https://medium.com/javascript-scene/the-dao-of-immutability-9f91a70c88cd)
  - [Master the JavaScript Interview: What is a Pure Function?](https://medium.com/javascript-scene/master-the-javascript-interview-what-is-a-pure-function-d1c076bec976)
  - [Master the JavaScript Interview: What is Functional Programming?](https://medium.com/javascript-scene/master-the-javascript-interview-what-is-functional-programming-7f218c68b3a0)
  - [Elements of JavaScript Style](https://medium.com/javascript-scene/elements-of-javascript-style-caa8821cb99f)

#### 这些是现有的翻译

- [0 - 简介](https://github.com/xitu/gold-miner/blob/master/TODO1/composing-software-an-introduction.md)
- [1 - 跌宕起伏的函数式编程](https://github.com/xitu/gold-miner/blob/master/TODO/the-rise-and-fall-and-rise-of-functional-programming-composable-software.md)
- [2 - 为什么用 JavaScript 学习函数式编程](https://github.com/xitu/gold-miner/blob/master/TODO/why-learn-functional-programming-in-javascript-composing-software.md)
- [3 - 函数式程序员的 JavaScript 简介](https://github.com/xitu/gold-miner/blob/master/TODO/a-functional-programmers-introduction-to-javascript-composing-software.md)
- [4 - 高阶函数](https://github.com/xitu/gold-miner/blob/master/TODO/higher-order-functions-composing-software.md)
- [5 - Reduce](https://github.com/xitu/gold-miner/blob/master/TODO/reduce-composing-software.md)
- [6 - Functor 与 Category](https://github.com/xitu/gold-miner/blob/master/TODO/functors-categories.md)
- [7 - 函数式 Mixin](https://github.com/xitu/gold-miner/blob/master/TODO/functional-mixins-composing-software.md)
- [8 - ES6+ 中的 JavaScript 工厂函数](https://github.com/xitu/gold-miner/blob/master/TODO/javascript-factory-functions-with-es6.md)
- [9 - 为什么在使用了类之后会使得组合变得愈发困难](https://github.com/xitu/gold-miner/blob/master/TODO/why-composition-is-harder-with-classes.md)
- [10 - 借助函数完成可组合的数据类型](https://github.com/xitu/gold-miner/blob/master/TODO/composable-datatypes-with-functions.md)
- [11 - JavaScript 让 Monad 更简单](https://github.com/xitu/gold-miner/blob/master/TODO/javascript-monads-made-simple.md)
- [12 - 模拟是一种代码异味](https://github.com/xitu/gold-miner/blob/master/TODO/mocking-is-a-code-smell.md)
- [13 - 对象组合中的宝藏](https://github.com/xitu/gold-miner/blob/master/TODO/the-hidden-treasures-of-object-composition.md)
- [14 - 优秀的嵌套三元表达式](https://github.com/xitu/gold-miner/blob/master/TODO/nested-ternaries-are-great.md)
- [15 - 抽象与组合](https://github.com/xitu/gold-miner/blob/master/TODO1/abstraction-composition.md)
- [16 - 被遗忘的面向对象编程史](https://github.com/xitu/gold-miner/blob/master/TODO1/the-forgotten-history-of-oop.md)
- [17 - 柯里化与函数组合](https://github.com/xitu/gold-miner/blob/master/TODO1/curry-and-function-composition.md)
- [18 - Transducers：JavaScript 中高效的数据处理 Pipeline](https://github.com/xitu/gold-miner/blob/master/TODO1/transducers-efficient-data-processing-pipelines-in-javascript.md)
- [19 - Lenses：可组合函数式编程的 Getter 和 Setter](https://github.com/xitu/gold-miner/blob/master/TODO1/lenses-composable-getters-and-setterssfor-functional-programming.md)

**Comment by sunui** [comment]
👍 感谢整理，待我逐一发布一下

**Comment by sunui** [comment]
#6812 #6813 #6814 #6815 #6816

**Comment by lsvih** [comment]
感谢整理，目前多的几章已经全部翻译完毕，后续会再进行统一收录一次！
