### ISSUE TITLE
JavaScript 风格元素

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6812]
* 原文链接：[Elements of JavaScript Style](https://medium.com/javascript-scene/elements-of-javascript-style-caa8821cb99f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/elements-of-javascript-style.md)
* PR 地址：
* 文章分类：** **
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by febrainqu** [comment]
翻译认领 @sunui

**Comment by fanyijihua** [comment]
@febrainqu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6866

**Comment by fanyijihua** [comment]
PR 地址：#6878
