### ISSUE TITLE
掌握 JavaScript 面试：什么是函数式编程

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6813]
* 原文链接：[Master the JavaScript Interview: What is Functional Programming?](https://medium.com/javascript-scene/master-the-javascript-interview-what-is-functional-programming-7f218c68b3a0)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/master-the-javascript-interview-what-is-functional-programming.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fireairforce** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@fireairforce 棒极啦 :tada:

**Comment by fireairforce** [comment]
明天来翻译～

**Comment by fanyijihua** [comment]
PR 地址：#6903

**Comment by fireairforce** [comment]
文章的pr地址是 https://github.com/xitu/gold-miner/pull/6902 这个～
