### ISSUE TITLE
掌握 JavaScript 面试：什么是纯函数？

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6814]
* 原文链接：[Master the JavaScript Interview: What is a Pure Function?](https://medium.com/javascript-scene/master-the-javascript-interview-what-is-a-pure-function-d1c076bec976)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/master-the-javascript-interview-what-is-a-pure-function.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by niayyy-S** [comment]
翻译认领

**Comment by niayyy-S** [comment]
翻译认领@lsvih

**Comment by niayyy-S** [comment]
@sunui 翻译认领

**Comment by niayyy-S** [comment]
@fanyijihua 翻译认领

**Comment by lsvih** [comment]
@niayyy-S 好的 🍺 （机器人坏了）
