### ISSUE TITLE
不变性之道

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6815]
* 原文链接：[The Dao of Immutability](https://medium.com/javascript-scene/the-dao-of-immutability-9f91a70c88cd)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-dao-of-immutability.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by niayyy-S** [comment]
@Glowin 翻译认领

**Comment by niayyy-S** [comment]
@fanyijihua 翻译认领

**Comment by fanyijihua** [comment]
@niayyy-S 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6857
