### ISSUE TITLE
组合软件：书

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#6816]
* 原文链接：[Composing Software: The Book](https://medium.com/javascript-scene/composing-software-the-book-f31c77fc3ddc)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/composing-software-the-book.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fireairforce** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@fireairforce 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6832
