### ISSUE TITLE
推荐前端优秀英文文章

### ISSUE THREAD

**Issue by Baddyo** [xitu/gold-miner#6819]
- 原文链接：https://zenodo.org/record/3710954#.XnSXuKgzZhE
- 简要介绍：[编程语言历史大会](https://link.zhihu.com/?target=https%3A//hopl4.sigplan.org/)上关于 JavaScript 的历史的论文《JavaScript: The first 20 years》。

---

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
这个过于长了。。翻完都能出本书了

**Comment by Baddyo** [comment]
> 这个过于长了。。翻完都能出本书了

哈哈，我也觉得 190 页太长了，不过要是分成系列文章呢？
