### ISSUE TITLE
JavaScript 中的 Generator 函数

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6842]
* 原文链接：[Generator Functions in JavaScript](https://medium.com/better-programming/generator-functions-in-javascript-571ba4cda69e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/generator-functions-in-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：2 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by niayyy-S** [comment]
@fanyijihua 翻译认领

**Comment by fanyijihua** [comment]
@niayyy-S 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6893
