### ISSUE TITLE
怎样让依赖库保持安全和最新

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6844]
* 原文链接：[How to Keep Your Dependencies Secure and Up to Date](https://medium.com/better-programming/how-to-keep-your-dependencies-secure-and-up-to-date-92578c7f3c9c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-keep-your-dependencies-secure-and-up-to-date.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@chaingangway 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6864
