### ISSUE TITLE
深入了解 React Fiber 内部实现

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6846]
* 原文链接：[A deep dive into React Fiber internals](https://blog.logrocket.com/deep-dive-into-react-fiber-internals/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/deep-dive-into-react-fiber-internals.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：20 天
* 校对时间：6 天
* 翻译积分：14 分
* 校对积分：7 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MarchYuanx** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@MarchYuanx 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7078
