### ISSUE TITLE
MySQL 最佳实践—— 高效插入数据

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6854]
* 原文链接：[High-speed inserts with MySQL](https://medium.com/@benmorel/high-speed-inserts-with-mysql-9d3dcd76f723)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/high-speed-inserts-with-mysql.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由 @todaycoder001 认领

**Comment by todaycoder001** [comment]
翻译认领

**Comment by GJXAIOU** [comment]
@lsvih 校对认领

**Comment by lsvih** [comment]
@GJXAIOU 得到 PR #6863 里面去认领
