### ISSUE TITLE
iOS APP 中的不可变模型以及一致性数据

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#686]
* 原文链接：[Immutable models and data consistency in our iOS App](https://engineering.pinterest.com/blog/immutable-models-and-data-consistency-our-ios-    app)
* 掘金链接：[iOS APP 中的不可变模型以及一致性数据](http://gold.xitu.io/entry/57c0092b2e958a0069645132/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/immutable-models-and-data-consistency-our-ios-app.md)
* PR 地址：[:smile:](https://github.com/xitu/gold-miner/pull/697)
* 文章分类：**iOS**

----

* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Kulbear** [comment]
认领

**Comment by sqrthree** [comment]
@Kulbear OK.
