### ISSUE TITLE
2020 年排名前 6 位的 JavaScript 框架

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6862]
* 原文链接：[The Top 6 JavaScript frameworks for 2020](https://medium.com/javascript-in-plain-english/6-best-javascript-frameworks-in-2020-102babf80196)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/6-best-javascript-frameworks-in-2020.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：1.5 分
* 校对积分：0.5 ~ 1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by QinRoc** [comment]
翻译认领

**Comment by snowyYU** [comment]
原文评论区吵翻天

**Comment by lsvih** [comment]
@snowyYU 看到了hh，其实这篇写的不咋地而且很引战

**Comment by lsvih** [comment]
@QinRoc 认领成功，机器人挂掉了所以没回应

**Comment by QinRoc** [comment]
@lsvih 收到，这就开工😀

**Comment by todaycoder001** [comment]
哈哈，这篇文章是medium 推给我的，哈哈哈哈😂

**Comment by lsvih** [comment]
@todaycoder001 其实我也被推荐了哈哈，没事，这类分析趋势或者评 TopN 的文章都是这样的

**Comment by todaycoder001** [comment]
算了不装了，PHP 是最好的语言，不接受反驳 😂

**Comment by fanyijihua** [comment]
PR 地址：#6867

**Comment by Chorer** [comment]
估计这篇文章发布在掘金会产生争议，太误导人了
