### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by todaycoder001** [xitu/gold-miner#6865]
- 原文链接：https://medium.com/better-programming/the-importance-of-why-docs-c8ffba0ea520
- 简要介绍：最近 Rust 官方文档团队宣布解散，今日看到 medium 推送了这篇文章，我觉得很有必要重温一下 “文档” 在团队之间沟通的重要性！
---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by fanyijihua** [comment]
:heart: 感谢有你 ♪(*´▽｀*)ノ

**Comment by lsvih** [comment]
#6869 已发布

**Comment by lsvih** [comment]
这文章不错。。不过要翻译好有点难
