### ISSUE TITLE
“为什么”文档的重要性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6869]
* 原文链接：[The Importance of “Why” Docs](https://medium.com/better-programming/the-importance-of-why-docs-c8ffba0ea520)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-importance-of-why-docs.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by QinRoc** [comment]
翻译认领

**Comment by lsvih** [comment]
@QinRoc 您确定要一次接两篇吗？。。一般不推荐这么赶的

**Comment by QinRoc** [comment]
@lsvih 看到感兴趣的文章就认领了。另外一篇翻译得差不多了😀。 如果不能同时认领的话，就算了哈。

**Comment by lsvih** [comment]
@QinRoc 那就认领了吧哈哈

**Comment by lsvih** [comment]
@QinRoc 已认领

**Comment by QinRoc** [comment]
> @QinRoc 已认领

@lsvih 感谢😃

**Comment by fanyijihua** [comment]
PR 地址：#6904
