### ISSUE TITLE
编写类型安全的多态 React 组件（不会导致 TypeScript 崩溃）

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6871]
* 原文链接：[Writing Type-Safe Polymorphic React Components (Without Crashing TypeScript)](https://blog.andrewbran.ch/polymorphic-react-components/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/polymorphic-react-components.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：8 分
* 校对积分：3 ~ 4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fireairforce** [comment]
翻译认领

**Comment by lsvih** [comment]
@fireairforce 好的~

**Comment by fireairforce** [comment]
mark一下，明天开始翻译～

**Comment by lsvih** [comment]
@fireairforce 辛苦啦

**Comment by fireairforce** [comment]
> @fireairforce 辛苦啦

哈哈哈，我就是担心timeline里面看不见就mark一下

**Comment by fireairforce** [comment]
今晚把pr开上来，已经翻译了一半了

**Comment by fireairforce** [comment]
开上来了~
