### ISSUE TITLE
机器学习中的主动学习

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6873]
* 原文链接：[Active Learning in Machine Learning](https://towardsdatascience.com/active-learning-in-machine-learning-525e61be16e5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/active-learning-in-machine-learning.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PingHGao** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@PingHGao 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6946
