### ISSUE TITLE
Kafka vs. RabbitMQ：为什么使用 Kafka？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6875]
* 原文链接：[Kafka vs. RabbitMQ: Why Use Kafka?](https://medium.com/better-programming/kafka-vs-rabbitmq-why-use-kafka-8401b2863b8b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/kafka-vs-rabbitmq-why-use-kafka.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by QinRoc** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@QinRoc 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6892
