### ISSUE TITLE
使用 JavaScript ES2020 中所有的 7 个新特性构建 App

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6877]
* 原文链接：[I Built an App That Uses All 7 New Features in JavaScript ES2020](https://levelup.gitconnected.com/i-built-an-app-that-uses-all-7-new-features-in-javascript-es2020-647205024984)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/i-built-an-app-that-uses-all-7-new-features-in-javascript-es2020.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：3 天
* 翻译积分：8 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yvonneit** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@yvonneit 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6906

**Comment by lsvih** [comment]
已发布 https://juejin.im/post/5e9a685951882573834edc9e
