### ISSUE TITLE
推荐 iOS 优秀英文文章

### ISSUE THREAD

**Issue by chaingangway** [xitu/gold-miner#6880]
- 原文链接：https://www.raywenderlich.com/7864801-combine-getting-started
- 简要介绍：SwiftUI 中数据流的处理，由于该技术较新，中文社区资料很少，很值得翻译

---

### 请完成并勾选一下三项：

- [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
- [x] 本文很值得翻译，我推荐
- [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by chaingangway** [comment]
另外想提个建议：看到 iOS 板块好像很久没有更新，本人愿意长期专注于本版块的文章推荐及其翻译工作，建议任务池多来一些 iOS 相关的 task 😄

**Comment by lsvih** [comment]
@chaingangway 哈哈欢迎欢迎

**Comment by lsvih** [comment]
#6884 已发布
