### ISSUE TITLE
推荐其他优秀英文文章

### ISSUE THREAD

**Issue by EmilyQiRabbit** [xitu/gold-miner#6881]
- 原文链接：https://www.brianstorti.com/understanding-shell-script-idiom-redirect/
- 简要介绍：2>&1 是什么意思

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
感谢推荐，不过我处理的太晚了，貌似有译文了 http://wangjieqiang.com/2020/04/27/%E7%90%86%E8%A7%A3Shell%E8%84%9A%E6%9C%AC%E4%B8%AD-2-1-%E7%9A%84%E5%90%AB%E4%B9%89/
