### ISSUE TITLE
0202 年了，是时候学习 Combine 了

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6884]
* 原文链接：[Combine: Getting Started](https://www.raywenderlich.com/7864801-combine-getting-started)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/combine-getting-started.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：15 天
* 校对时间：6 天
* 翻译积分：13 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
（建议取个更明了的标题

**Comment by chaingangway** [comment]
好的，翻译认领 @lsvih

**Comment by fanyijihua** [comment]
@chaingangway 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6952
