### ISSUE TITLE
如何成为一名优秀的远程开发者

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6886]
* 原文链接：[How to Be a Good Remote Developer](https://levelup.gitconnected.com/how-to-be-a-good-remote-developer-e399607d5532)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/how-to-be-a-good-remote-developer.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by lsvih** [comment]
@Baddyo 好的！

**Comment by Baddyo** [comment]
> @Baddyo 好的！

哈哈哈，人肉回复。

**Comment by fanyijihua** [comment]
PR 地址：#6923
