### ISSUE TITLE
为什么对象不变性很重要？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6888]
* 原文链接：[Why is object immutability important?](https://levelup.gitconnected.com/why-is-object-immutability-important-d6882929e804)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-is-object-immutability-important.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by IAMSHENSH** [comment]
认领翻译 @lsvih

**Comment by IAMSHENSH** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@IAMSHENSH 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6909
