### ISSUE TITLE
Shadow DOM 到底是什么？它为什么重要？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6889]
* 原文链接：[What on Earth Is the Shadow DOM and Why Does It Matter?](https://medium.com/better-programming/what-on-earth-is-the-shadow-dom-and-why-it-matters-eff0884bd33d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-on-earth-is-the-shadow-dom-and-why-it-matters.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mengrenzi** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@mengrenzi 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6910
