### ISSUE TITLE
3 分钟掌握 CSS Flexbox

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#689]
* 原文链接：[Learn CSS Flexbox in 3 Minutes](https://medium.com/learning-new-stuff/learn-css-flexbox-in-3-minutes-c616c7070672)
* 掘金链接：[[英] 3 分钟掌握 CSS Flexbox ](http://gold.xitu.io/entry/57c69bf0c4c9710061a775d2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/learn-css-flexbox-in-3-minutes.md)
* PR 地址： [咦](https://github.com/xitu/gold-miner/pull/708)
* 文章分类：**前端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cbangchen** [comment]
认领

**Comment by cbangchen** [comment]
想认领的，但不是我做的端，我怕翻译的不好，让给其他人吧，我等着做校对。

**Comment by sqrthree** [comment]
@cbangchen 好的，可以留意一会的文章哈

**Comment by Graning** [comment]
get~

**Comment by sqrthree** [comment]
@Graning OK.

**Comment by cbangchen** [comment]
(*☻-☻*) 一会会发生什么 @sqrthree

**Comment by Graning** [comment]
@sqrthree 已分享 http://gold.xitu.io/entry/57ce68bf2e958a00543a7df9/detail
