### ISSUE TITLE
防止 Git 泄漏的 5 种最佳做法

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6895]
* 原文链接：[5 Best Practices To Prevent Git Leaks](https://levelup.gitconnected.com/5-best-practices-to-prevent-git-leaks-4997b96c1cbe)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/5-best-practices-to-prevent-git-leaks.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by lsvih** [comment]
@YueYongDev 认领成功~

**Comment by fanyijihua** [comment]
PR 地址：#6907
