### ISSUE TITLE
用 SwiftUI 实现 3D Scroll 效果

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6897]
* 原文链接：[SwiftUI 3D Scroll Effect](https://levelup.gitconnected.com/swiftui-3d-scroll-effect-fa5310665738)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/swiftui-3d-scroll-effect.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@chaingangway 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6920

**Comment by fanyijihua** [comment]
PR 地址：#6921
