### ISSUE TITLE
推荐文章：何时使用var、let、const

### ISSUE THREAD

**Issue by mengrenzi** [xitu/gold-miner#6899]
- 原文链接：https://www.freecodecamp.org/news/var-vs-let-vs-const-in-javascript-2954ae48c037/
- 简要介绍：var、let、const

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：前端
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by mengrenzi** [comment]
【补充】简要介绍：ES6引入let和const，本文介绍了let、const和var之间的区别，并涵盖诸如函数与块作用域，变量提升和不变性之类的主题。

**Comment by lsvih** [comment]
这篇文章有译文啦 https://juejin.im/post/5c39e3ff6fb9a04a027a9421

**Comment by lsvih** [comment]
谢谢推荐
