### ISSUE TITLE
好的设计准则是如何塑造更强大的产品形态的？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#690]
* 原文链接：[Why design principles shape stronger products](https://uxdesign.cc/why-design-principles-shape-stronger-products-ae677bdd831b#.20fz1utbj)
* 掘金链接：[[英] 好的设计准则是如何塑造更强大的产品形态的？](http://gold.xitu.io/entry/57c67c990a2b58006c0ea672)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-design-principles-shape-stronger-products.md)
* PR 地址：[PR ](https://github.com/xitu/gold-miner/pull/711)
* 文章分类：**设计**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`7` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rottenpen** [comment]
认领

**Comment by sqrthree** [comment]
@rottenpen 好哒
