### ISSUE TITLE
关于 Swift，我不喜欢的几点

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#691]
* 原文链接：[My Least Favorite Thing About Swift](http://khanlou.com/2016/08/my-least-favorite-thing-about-swift/)
* 掘金链接：[[英] 关于 Swift，我不喜欢的几点](http://gold.xitu.io/entry/57c685c2a633bd005d8db403/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/my-least-favorite-thing-about-swift.md)
* PR 地址：[:apple:](https://github.com/xitu/gold-miner/pull/698)
* 文章分类：**iOS**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`7` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cbangchen** [comment]
认领，我能不能领两篇，我可以翻译完的

**Comment by sqrthree** [comment]
@cbangchen 那你注意好时间和质量哈
