### ISSUE TITLE
高性能 JavaScript 最佳实践

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6912]
* 原文链接：[Performant JavaScript Best Practices](https://levelup.gitconnected.com/performant-javascript-best-practices-c5a49a357e46)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/performant-javascript-best-practices.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by IAMSHENSH** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@IAMSHENSH 棒极啦 :tada:
