### ISSUE TITLE
开发者应该写博客的各种原因

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6914]
* 原文链接：[More Reasons Why Developers Should Blog](https://levelup.gitconnected.com/more-reasons-why-developers-should-blog-ba947be9e869)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/more-reasons-why-developers-should-blog.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PingHGao** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@PingHGao 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6937
