### ISSUE TITLE
5 个优化技巧助你提高移动 Web 应用的用户留存率

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6916]
* 原文链接：[5 optimization tips for your mobile web app for higher user retention](https://levelup.gitconnected.com/5-optimization-tips-for-your-mobile-web-app-for-higher-user-retention-3d6d158aadb7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/5-optimization-tips-for-your-mobile-web-app-for-higher-user-retention.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by QinRoc** [comment]
翻译认领

**Comment by lsvih** [comment]
@QinRoc 好的~

**Comment by fanyijihua** [comment]
PR 地址：#6976
