### ISSUE TITLE
您知道 HTML 的键盘标签吗？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6918]
* 原文链接：[Do You Know About the Keyboard Tag in HTML?](https://medium.com/better-programming/do-you-know-about-the-keyboard-tag-in-html-55bb3986f186)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/do-you-know-about-the-keyboard-tag-in-html.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：1 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by IAMSHENSH** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@IAMSHENSH 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6922
