### ISSUE TITLE
推荐 AI 优秀英文文章

### ISSUE THREAD

**Issue by PingHGao** [xitu/gold-miner#6919]
- 原文链接：https://github.com/rafaelpadilla/Object-Detection-Metrics
- 简要介绍：介绍目标检测领域用于评估算法好坏的标准。这对做目标检测的相关人员十分重要，但是很多人都没有弄得特别清楚。看完这篇文章，能够解决很多人的疑问。所以十分有必要有一篇格式整洁优美、翻译准确的译文。

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [ ] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by PingHGao** [comment]
如果通过了，能提前认领翻译吗？已经翻译了一大半了

**Comment by lsvih** [comment]
好的，感谢推荐

**Comment by lsvih** [comment]
#6930 已发布
