### ISSUE TITLE
如何给你的产品写文案？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#692]
* 原文链接：[How to design words](https://medium.com/@jsaito/how-to-design-words-63d6965051e9?ref=uxdesignweekly#.97vnoptue)
* 掘金链接：[[英] 如何设计你的产品语言？](http://gold.xitu.io/entry/57c3dc4ac4c97100619472f0)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-design-words.md)
* PR 地址： [PR](https://github.com/xitu/gold-miner/pull/709)
* 文章分类：**设计**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jiaowoyongqi** [comment]
认领！

**Comment by sqrthree** [comment]
@jiaowoyongqi OK.

**Comment by funtrip** [comment]
我可不可以预定校对……=。=

**Comment by jiaowoyongqi** [comment]
@funtrip 艾玛，竟然这里遇见你，喜欢你在少数派的文章！╰(*°▽°*)╯

**Comment by funtrip** [comment]
@jiaowoyongqi 艾玛，喜欢你喜欢我！！(>///<

**Comment by cbangchen** [comment]
PY 交易

**Comment by sqrthree** [comment]
@funtrip 等译者提交 PR 之后在对应的 PR 下申请校对哈~ 为了避免有人提前占坑到时候遗忘，改为在 PR 下申请了。

**Comment by jiaowoyongqi** [comment]
http://gold.xitu.io/entry/57d3a12067f3560057d58eba/detail
@sqrthree OK囖
