### ISSUE TITLE
The Art of System Performance for Engineers

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6926]
* 原文链接：[The Art of System Performance for Engineers](https://levelup.gitconnected.com/the-art-of-system-performance-for-engineers-1c85a398d6f2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/the-art-of-system-performance-for-engineers.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zh1an** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@zh1an 棒极啦 :tada:

**Comment by lsvih** [comment]
@zh1an 别忘了这篇哦~

**Comment by sunui** [comment]
@zh1an 还在翻译吗

**Comment by lhd951220** [comment]
可以重新认领翻译吗？ @sunui

**Comment by sunui** [comment]
@lhd951220 可以，你认领吧

**Comment by sunui** [comment]
@zh1an 已释放

**Comment by lhd951220** [comment]
翻译认领 @fanyijihua

**Comment by lhd951220** [comment]
翻译认领 @zh1an

**Comment by lhd951220** [comment]
翻译认领 @fanyijihua

**Comment by sunui** [comment]
@lhd951220 robot 抽风，开始翻译就好哈

**Comment by lhd951220** [comment]
> @lhd951220 robot 抽风，开始翻译就好哈

好的

**Comment by fghpdf** [comment]
@sunui 校对认领

**Comment by sunui** [comment]
@fghpdf  去对应的 PR 里认领
