### ISSUE TITLE
Google Tag Manager 的真相大揭秘

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6928]
* 原文链接：[What is Google Tag Manager and why use it? The truth about Google Tag Manager](https://www.orbitmedia.com/blog/what-is-google-tag-manager-and-why-use-it/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-is-google-tag-manager-and-why-use-it.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：10 天
* 校对时间：4 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhanght9527** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@zhanght9527 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6940
