### ISSUE TITLE
用 RxSwift 实现 Reactive Generic Segue

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#693]
* 原文链接：[iOS: Let’s create Reactive Generic Segue with RxSwift](https://medium.com/@SergDort/reactive-generic-segue-with-rxswift-e20a5219aeea)
* 掘金链接：[[英] iOS: 用 RxSwift 实现 Reactive Generic Segue ](http://gold.xitu.io/entry/57c69837165abd00667d6b2e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/reactive-generic-segue-with-rxswift.md)
* PR 地址： [:smile:](https://github.com/xitu/gold-miner/pull/696)
* 文章分类：**iOS**

----
* 翻译时间：`2` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rottenpen** [comment]
用 RxSwift 实现 Reactive Generic Segue

**Comment by cbangchen** [comment]
用响应式编程框架 RxSwift 来进行通用的响应式转场实现

**Comment by mypchas6fans** [comment]
什么情况，算是有人认领了吗？没有的话我来~

**Comment by yifili09** [comment]
什么情况，算是有人认领了吗？没有的话我来~

**Comment by sqrthree** [comment]
@mypchas6fans 好👌
