### ISSUE TITLE
目标检测评价标准

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6930]
* 原文链接：[Metrics for object detection](https://github.com/rafaelpadilla/Object-Detection-Metrics)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/object-detection-metrics.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：- 天
* 校对时间：5 天
* 翻译积分：12 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文档由 @PingHGao 翻译

**Comment by PingHGao** [comment]
翻译认领

**Comment by fanyijihua** [comment]
PR 地址：#6939
