### ISSUE TITLE
你可能会错过的 CSS 伪选择器

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6934]
* 原文链接：[CSS Pseudo-Classes You Might Have Missed](https://blog.bitsrc.io/css-pseudo-selectors-you-never-knew-existed-b5c0ddaa8116)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/css-pseudo-selectors-you-never-knew-existed.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：2 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by niayyy-S** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@niayyy-S 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6969
