### ISSUE TITLE
恋爱 5 年的消息看起来是什么样

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6935]
* 原文链接：[What 5 Years of a Relationship’s  Messages Look Like](https://towardsdatascience.com/what-5-years-of-a-relationships-messages-look-like-45921155e3f2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-5-years-of-a-relationships-messages-look-like.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：8 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Amberlin1970** [comment]
翻译认领

**Comment by lsvih** [comment]
@Amberlin1970 好的

**Comment by Amberlin1970** [comment]
在掘金上发布时，显示内容违禁，无法发布，这个怎么解决呀 @lsvih

**Comment by lsvih** [comment]
@Amberlin1970 我反馈一下。。不好意思哈

**Comment by lsvih** [comment]
@Amberlin1970 要不麻烦您往知乎投个稿。。

专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

**Comment by PassionPenguin** [comment]
喵来催发布啦

**Comment by Amberlin1970** [comment]
文章发布地址：https://juejin.cn/post/6944711045449515038

**Comment by lsvih** [comment]
收到
