### ISSUE TITLE
幻数并没有我们想象中的那么奇幻

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6936]
* 原文链接：[Magic Numbers Are Not That Magic](https://medium.com/better-programming/magic-numbers-are-not-that-magic-132297d435f5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/magic-numbers-are-not-that-magic.md)
* PR 地址：
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：3 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@samyu2000 棒极啦 :tada:

**Comment by lsvih** [comment]
@samyu2000 别忘了这篇吖~

**Comment by lhd951220** [comment]
这篇是否可以重新认领 @lsvih

**Comment by PassionPenguin** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@PassionPenguin 好的~

**Comment by PassionPenguin** [comment]
woc我竟然没发juejin发小破站去了？

**Comment by PassionPenguin** [comment]
https://juejin.cn/post/6944588994915074062/

**Comment by lsvih** [comment]
收到
