### ISSUE TITLE
用 Swift 实现二叉树以及二叉树遍历数据结构

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#694]
* 原文链接：[Swift Algorithm Club: Swift Binary Search Tree Data Structure](https://www.raywenderlich.com/139821/swift-algorithm-club-swift-binary-search-tree-data-structure)
* 掘金链接：[[英] 用 Swift 实现二叉树以及二叉树遍历数据结构](http://gold.xitu.io/entry/57c68422a633bd005d8da5be)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/swift-algorithm-club-swift-binary-search-tree-data-structure.md)
* PR 地址： [_(:з」∠)_](https://github.com/xitu/gold-miner/pull/704)
* 文章分类：**iOS**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cbangchen** [comment]
认领

**Comment by sqrthree** [comment]
@cbangchen OK.
