### ISSUE TITLE
在 JavaScript 中为什么 Math.max() 会比 Math.min() 小？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6945]
* 原文链接：[Why Math.max() is Less Than Math.min() in JavaScript](https://levelup.gitconnected.com/why-math-max-is-less-than-math-min-in-javascript-7aaf2c39ee36)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/why-math-max-is-less-than-math-min-in-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhanght9527** [comment]
翻译认领

**Comment by lsvih** [comment]
@zhanght9527 好的
