### ISSUE TITLE
在 Node.js 中用 Puppeteer 实现网络爬虫

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6948]
* 原文链接：[Web Scraping with Puppeteer in Node.js](https://medium.com/javascript-in-plain-english/web-scraping-with-puppeteer-in-node-js-4a32d85df183)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/web-scraping-with-puppeteer-in-node-js.md)
* PR 地址：
* 文章分类：**后端**，**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by lsvih** [comment]
@Baddyo 好的

**Comment by fanyijihua** [comment]
PR 地址：#6992
