### ISSUE TITLE
推荐 iOS 优秀英文文章

### ISSUE THREAD

**Issue by chaingangway** [xitu/gold-miner#6949]
- 原文链接：https://www.raywenderlich.com/8440907-getting-started-with-the-viper-architecture-pattern
- 简要介绍：介绍用 SwiftUI 和 Combine 框架实现 iOS 中的 VIPER 架构，本文 4 月 20 号才发，国内没这方面的资料

---

### 请完成并勾选一下三项：

- [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章- 
- [x] 本文很值得翻译，我推荐
- [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
这篇实在太长了，现在暂时没有开文档翻译的企划，所以一直没加进来，感谢推荐= =
