### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zhangliukun** [xitu/gold-miner#695]
# Hi,this is zale.
- 现在一家互联网公司任 Android 开发工程师
- 常看的外文网站也就 [Android手册](https://developer.android.com/index.html) 和 [纽约时报](http://international.nytimes.com/)，当然也经常逛逛 github
- 英文的水平呢 CET6 吧，希望能够不断提高
- 个人翻译过几篇 Android 官方文档,目前收录在自己的 Blog中
- 技术博客 [www.zalezone.cn](www.zalezone.cn)，目前技术沉淀尚且不深，不太敢下笔

**Comment by antonia0912** [comment]
@zhangliukun 欢迎来掘金翻译计划玩 请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群
