### ISSUE TITLE
在 Swift 中对 JSON 进行自定义编码和解码的小技巧

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6955]
* 原文链接：[Custom encoding and decoding JSON in Swift](https://levelup.gitconnected.com/custom-encoding-and-decoding-json-in-swift-a99c80b280e7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/custom-encoding-and-decoding-json-in-swift.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：3 天
* 翻译积分：5.5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
翻译认领

**Comment by lsvih** [comment]
@chaingangway 好的

**Comment by fanyijihua** [comment]
PR 地址：#6967
