### ISSUE TITLE
VueJS 3.0.0 Beta：那些令人兴奋的功能

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6957]
* 原文链接：[VueJS 3.0.0 Beta: Features I’m Excited About](https://blog.bitsrc.io/vuejs-3-0-0-beta-features-im-excited-about-c70b82fac163)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/vuejs-3-0-0-beta-features-im-excited-about.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：3~7 天
* 校对时间：1 天
* 翻译积分：4~6 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhanght9527** [comment]
翻译认领

**Comment by lsvih** [comment]
@zhanght9527 好的！

**Comment by fanyijihua** [comment]
PR 地址：#6991
