### ISSUE TITLE
2020 十大 JavaScript 图像处理库

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6959]
* 原文链接：[10 JavaScript Image Manipulation Libraries for 2020](https://blog.bitsrc.io/image-manipulation-libraries-for-javascript-187fde1ad5af)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/image-manipulation-libraries-for-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by IAMSHENSH** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@IAMSHENSH 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6989
