### ISSUE TITLE
你的 REST API 准备好部署了吗？7 个问题帮助你做出决定

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6961]
* 原文链接：[Is Your REST API Ready for Deployment? 7 Questions to Help You Decide](https://codeburst.io/is-your-rest-api-ready-for-deployment-7-questions-to-help-you-decide-a371de9faa76)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/is-your-rest-api-ready-for-deployment-7-questions-to-help-you-decide.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mengrenzi** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@mengrenzi 棒极啦 :tada:
