### ISSUE TITLE
使用 Django 构建一个简单的邮件服务

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6963]
* 原文链接：[Build a Simple Mailing Service with Django](https://medium.com/python-in-plain-english/simple-mailer-with-django-2a7e2ad34b34)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/simple-mailer-with-django.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shixi-li** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@shixi-li 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#6993

**Comment by shixi-li** [comment]
已发布到掘金

https://juejin.im/post/5eb6171c5188256d7a3cac97
