### ISSUE TITLE
什么是无障碍？为什它对于用户体验很重要？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6965]
* 原文链接：[What is accessibility and why is it crucial for your user’s experience?](https://medium.com/ux-in-plain-english/what-is-accessibility-and-why-is-it-crucial-for-your-users-experience-2079e9829076)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/what-is-accessibility-and-why-is-it-crucial-for-your-users-experience.md)
* PR 地址：
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by QinRoc** [comment]
翻译认领

**Comment by lsvih** [comment]
好的

**Comment by fanyijihua** [comment]
PR 地址：#7039
