### ISSUE TITLE
实际项目中关于 JavaScript 中 Promises 的最佳实践

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6971]
* 原文链接：[5 Better Practices for JavaScript Promises in Real Projects](https://medium.com/javascript-in-plain-english/5-better-practices-for-javascript-promises-in-real-projects-4917a9daec01)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/5-better-practices-for-javascript-promises-in-real-projects.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by febrainqu** [comment]
翻译认领

**Comment by lsvih** [comment]
@febrainqu 好的

**Comment by fanyijihua** [comment]
PR 地址：#7014
