### ISSUE TITLE
用 SwiftUI 实现酷炫的颜色切换动画

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6973]
* 原文链接：[SwiftUI: Animating Color Changes](https://levelup.gitconnected.com/swiftui-animating-color-changes-6a87d237dcea)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/swiftui-animating-color-changes.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：9 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
翻译认领

**Comment by lsvih** [comment]
@chaingangway 好的！

**Comment by fanyijihua** [comment]
PR 地址：#6990
