### ISSUE TITLE
寻找 2020 年最有意义的十大网页设计流行趋势

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6979]
* 原文链接：[Find Top 10 meaningful web design trends in 2020](https://medium.com/ux-in-plain-english/find-top-10-meaningful-web-design-trends-in-2020-76c2a8301997)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/find-top-10-meaningful-web-design-trends-in-2020.md)
* PR 地址：
* 文章分类：**设计**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Charlo-O** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Charlo-O 棒极啦 :tada:

**Comment by Charlo-O** [comment]
https://juejin.im/post/5ed74ee0e51d45788a6d686e  @fanyijihua @lsvih @sunui 已经发布了～
