### ISSUE TITLE
深入浅出 array.fill() 函数

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6981]
* 原文链接：[An In-Depth Exploration of the Array.fill() Function](https://levelup.gitconnected.com/an-in-depth-exploration-of-the-array-fill-function-800155bf9dd)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/an-in-depth-exploration-of-the-array-fill-function.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：9 天
* 校对时间：3 天
* 翻译积分：7.5 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by niayyy-S** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@niayyy-S 棒极啦 :tada:
