### ISSUE TITLE
如何运用 Swift 的属性包装器实现应用本地化

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6983]
* 原文链接：[Localize Swift Application](https://levelup.gitconnected.com/localize-swift-application-f1fd0f4af800)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/localize-swift-application.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@chaingangway 棒极啦 :tada:
