### ISSUE TITLE
纯 JavaScript 版本的 Lodash 数组 Filtering 和 Manipulation 方法

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6985]
* 原文链接：[Plain JavaScript versions of Lodash Array Filtering and Manipulation Methods](https://medium.com/javascript-in-plain-english/plain-javascript-versions-of-lodash-array-filtering-and-manipulation-methods-2469e2c6a5fa)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/plain-javascript-versions-of-lodash-array-filtering-and-manipulation-methods.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CoolRice** [comment]
翻译认领

**Comment by lsvih** [comment]
@CoolRice 好的

**Comment by fanyijihua** [comment]
PR 地址：#7043

**Comment by CoolRice** [comment]
@lsvih 文章已发布啦~  https://juejin.im/post/5ec614196fb9a047b46b14f3
