### ISSUE TITLE
如何在自己的计算机上模拟 UDP Flood DoS 攻击

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6988]
* 原文链接：[How to simulate a UDP Flood DoS attack on your computer](https://levelup.gitconnected.com/how-to-simulate-a-udp-flood-dos-attack-on-your-computer-863b40c44f3f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-to-simulate-a-udp-flood-dos-attack-on-your-computer.md)
* PR 地址：
* 文章分类：**后端**，**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
校对认领

**Comment by lsvih** [comment]
@chaingangway 好的
