### ISSUE TITLE
基于浏览器的 MapReduce

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#699]
* 原文链接：[Collaborative Map-Reduce in the Browser](https://www.igvita.com/2009/03/03/collaborative-map-reduce-in-the-browser/)
* 掘金链接：[[英] 基于浏览器的 MapReduce](http://gold.xitu.io/entry/57c7fcb8165abd0068d538f5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/collaborative-map-reduce-in-the-browser.md)
* PR地址： [链接](https://github.com/xitu/gold-miner/pull/703)
* 文章分类：**前端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mypchas6fans** [comment]
认领

**Comment by sqrthree** [comment]
@mypchas6fans 好哒
