### ISSUE TITLE
使用 GraphQL 的 6 个月

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#6999]
* 原文链接：[6 Months Of Using GraphQL](https://levelup.gitconnected.com/6-months-of-using-graphql-faa0fb68b4af)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/6-months-of-using-graphql.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：4 天
* 校对时间：2 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@YueYongDev 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7013
