### ISSUE TITLE
认领《2015 年底 JS 必备工具集》

### ISSUE THREAD

**Issue by vlux** [xitu/gold-miner#70]
前端狗
JS狗
可视化狗
热爱各种新鲜技术
vyue.me

**Comment by Glowin** [comment]
你好，这篇文章已经被@zxc0328 认领了，你可以看看其他没有认领的文章，谢谢你的理解哈

**Comment by Glowin** [comment]
你好，现在挑选出来的文章已经被认领完了，但是这个翻译计划还是会一直更新维护下去，我新建了一个掘金翻译计划的微信群，并会在群里面通报翻译活动的最新进展，希望你能加一下我微信 Glowjiang，感谢你的支持和理解。

**Comment by Glowin** [comment]
@vlux 早上好，我们又有一批新的文章等待你的翻译，欢迎来认领文章，谢谢啦。
