### ISSUE TITLE
响应式设计的真正挑战：RSS

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#700]
* 原文链接：[The real responsive design challenge? RSS.](https://begriffs.com/posts/2016-05-28-rss-responsive-design.html)
* 掘金链接：[[英] 响应式设计的真正挑战：RSS](http://gold.xitu.io/entry/57c7fd8079bc440063e92cf2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/rss-responsive-design.md)
* PR 地址：[你猜](https://github.com/xitu/gold-miner/pull/715)
* 文章分类：**前端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cdpath** [comment]
认领~

**Comment by sqrthree** [comment]
@cdpath OK。
