### ISSUE TITLE
最常用的 4 种 JavaScript 设计模式

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7000]
* 原文链接：[4 Useful JavaScript Design Patterns You Should Know](https://medium.com/javascript-in-plain-english/4-useful-javascript-design-patterns-you-should-know-b4e1404e3929)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/4-useful-javascript-design-patterns-you-should-know.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：8 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZavierTang** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@ZavierTang 棒极啦 :tada:

**Comment by CuteSunLee** [comment]
校对认领

**Comment by lsvih** [comment]
@CuteSunLee 等译者翻译好我 @ 你来校对哈

**Comment by fanyijihua** [comment]
PR 地址：#7082

**Comment by lsvih** [comment]
@ZavierTang  大佬大佬，这篇文章能不能麻烦您在掘金重新发一遍呀- -服务器下午出了问题，碰巧在那会儿发布的几篇文章没同步上去打不开 🤦

**Comment by ZavierTang** [comment]
@lsvih 还以为是网络问题呢，已重新发布了

https://juejin.im/post/5ec4bd4851882542e2692e65

**Comment by fanyijihua** [comment]
PR 地址：#7130
