### ISSUE TITLE
小品 JavaScript Proxy

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7002]
* 原文链接：[JavaScript Proxies](https://medium.com/javascript-in-plain-english/javascript-proxies-b41abcdd2bda)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/javascript-proxies.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by Gesj-yean** [comment]
校对认领

**Comment by lsvih** [comment]
@Gesj-yean 好的

**Comment by lsvih** [comment]
@Gesj-yean 您得到 PF 里去认领，下会儿记得哈
