### ISSUE TITLE
识别网络中连接紧密的用户

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7004]
* 原文链接：[Identify well-connected Users in a Network](https://towardsdatascience.com/identify-well-connected-users-in-a-social-network-19ea8dd50b16)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/identify-well-connected-users-in-a-network.md)
* PR 地址：
* 文章分类：**算法**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TUARAN** [comment]
翻译认领

**Comment by cf020031308** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cf020031308 棒极啦 :tada:
