### ISSUE TITLE
如何编写整洁代码？从 Robert C. Martin 的“代码整洁之道”中吸取的教训

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7006]
* 原文链接：[How to write clean code? Lessons learnt from “The Clean Code” — Robert C. Martin](https://medium.com/mindorks/how-to-write-clean-code-lessons-learnt-from-the-clean-code-robert-c-martin-9ffc7aef870c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-to-write-clean-code-lessons-learnt-from-the-clean-code-robert-c-martin.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由@todaycoder001 翻译

**Comment by todaycoder001** [comment]
翻译认领

**Comment by todaycoder001** [comment]
翻译认领

**Comment by lsvih** [comment]
@todaycoder001 已经改了状态啦

**Comment by PingHGao** [comment]
不知道怎么预约校对，好了请@我一下 @todaycoder001

**Comment by todaycoder001** [comment]
> 不知道怎么预约校对，好了请@我一下 @todaycoder001

等我开了pr就@你，指定你校对哈

**Comment by fanyijihua** [comment]
PR 地址：#7017
