### ISSUE TITLE
异步编程和多线程，我该选择哪个方案？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7008]
* 原文链接：[Which Should You Use: Asynchronous Programming or Multi-Threading?](https://medium.com/better-programming/which-should-you-use-asynchronous-programming-or-multi-threading-7435ec9adc8e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/which-should-you-use-asynchronous-programming-or-multi-threading.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@chaingangway 棒极啦 :tada:

**Comment by niayyy-S** [comment]
翻译认领

**Comment by fanyijihua** [comment]
PR 地址：#7075

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6844904168159707150
