### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Newt0n** [xitu/gold-miner#701]
- 某国民手机厂从事 PHP/Go/Pyhton 后端工作
- 前端及 UI/UX 都有涉猎，勉强全栈
- stackoverflow/reddit/dribbble
- 英文阅读能力尚可，CET6

为社区贡献一点业余时间。

**Comment by antonia0912** [comment]
@Newt0n 欢迎来掘金翻译计划玩 请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群
