### ISSUE TITLE
用户体验案例学习：Mood Talk ——  一个心理健康应用

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7010]
* 原文链接：[UX Case Study: Mood Talk — A mental health app](https://medium.com/ux-in-plain-english/mood-talk-tell-how-you-feel-to-others-who-face-the-same-challenges-5e885ae7bd3)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/mood-talk-tell-how-you-feel-to-others-who-face-the-same-challenges.md)
* PR 地址：
* 文章分类：**设计**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by niayyy-S** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@niayyy-S 棒极啦 :tada:
