### ISSUE TITLE
贪心算法，你入门了吗？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7012]
* 原文链接：[Greedy Algorithms 101](https://codeburst.io/greedy-algorithms-101-957842232cf2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/greedy-algorithms-101.md)
* PR 地址：
* 文章分类：**算法**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@chaingangway 棒极啦 :tada:

**Comment by todaycoder001** [comment]
麻烦译者开了PR后指定我校对，并且@我一下，谢谢啦。

**Comment by chaingangway** [comment]
@todaycoder001 好的👌

**Comment by fanyijihua** [comment]
PR 地址：#7035

**Comment by chaingangway** [comment]
@todaycoder001 老哥，来校对咯

**Comment by lsvih** [comment]
BTW，您现在 PR 里 history commit 实在太多了。。虽然没啥影响，不过还是建议更新一下 fork 或者直接在 https://github.com/xitu/gold-miner/tree/master/article/2020 里找到对应文章点左上角的铅笔图标来提交 🤦

**Comment by chaingangway** [comment]
@lsvih 这就是 fork 更新过后的，不知道为啥🤦‍♂️，我待会拉条新分支看看

**Comment by lsvih** [comment]
@chaingangway 没事没事，下回儿试试就行啦

**Comment by lsvih** [comment]
已发布 https://juejin.im/post/5ebc0f626fb9a043383d7c2b
