### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Airmacho** [xitu/gold-miner#702]
Hi, I'm Will, Ruby developer, 目前对elixir感兴趣。

现就职于China Renaissance，后端开发。

活跃于twitter（潜水态）／Quora／Medium／GitHub（吃瓜态）

英语正在复习备考雅思，扇贝打卡308天。可无障碍阅读英文文档，技术书，学习mooc课程。

业余翻译，翻译较少，有技术翻译经验，例：http://get.ftqq.com/7870.get

**Comment by antonia0912** [comment]
@Airmacho 欢迎来掘金翻译计划玩 请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群
