### ISSUE TITLE
在图像中隐藏数据:用 Python 来实现图像隐写术

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7022]
* 原文链接：[Hiding data in an image : Image Steganography using Python](https://towardsdatascience.com/hiding-data-in-an-image-image-steganography-using-python-e491b68b1372)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/hiding-data-in-an-image-image-steganography-using-python.md)
* PR 地址： #7192
* 文章分类：**算法**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by sunui** [comment]
@cyz980908 Hi，进度如何

**Comment by sunui** [comment]
@cyz980908 还在翻译吗

**Comment by cyz980908** [comment]
> @cyz980908 还在翻译吗

在的在的，之前在忙毕业答辩。马上就提哈
