### ISSUE TITLE
在 Swift 中使用 MVVM 架构实现无限滚动和图片加载

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7023]
* 原文链接：[MVVM in Swift: Infinite Scrolling and Image Loading](https://medium.com/better-programming/mvvm-in-swift-infinite-scrolling-and-image-loading-d47780b06e23)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/mvvm-in-swift-infinite-scrolling-and-image-loading.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：9 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
翻译认领

**Comment by lsvih** [comment]
@chaingangway 好的
