### ISSUE TITLE
无服务器实际上是什么意思？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7025]
* 原文链接：[What Does Serverless Actually Mean?](https://medium.com/better-programming/what-does-serverless-actually-mean-c68bde4cdc0d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/what-does-serverless-actually-mean.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by QinRoc** [comment]
翻译认领

**Comment by fanyijihua** [comment]
PR 地址：#7117

**Comment by Ultrasteve** [comment]
校对认领

**Comment by Ultrasteve** [comment]
校对认领 @lsvih
