### ISSUE TITLE
如何且为何要在单页应用中防止跨域资源共享

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7027]
* 原文链接：[How and Why You Should Avoid CORS in Single Page Apps](https://blog.bitsrc.io/how-and-why-you-should-avoid-cors-in-single-page-apps-db25452ad2f8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-and-why-you-should-avoid-cors-in-single-page-apps.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZiXYu** [comment]
领~
@lsvih

**Comment by lsvih** [comment]
@ZiXYu 好的
