### ISSUE TITLE
5 大 JavaScript 字符串操作库

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7030]
* 原文链接：[5 String Manipulation Libraries for JavaScript](https://blog.bitsrc.io/5-string-manipulation-libraries-for-javascript-5de27e48ee62)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/5-string-manipulation-libraries-for-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by IAMSHENSH** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@IAMSHENSH 棒极啦 :tada:
