### ISSUE TITLE
看我如何把网站性能提升 422%

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7031]
* 原文链接：[How I Increased Our Web Performance by 422%](https://blog.bitsrc.io/how-i-increased-our-web-performance-by-422-84e4997132ff)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-i-increased-our-web-performance-by-422.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:
