### ISSUE TITLE
理解 zip 和 gzip 压缩格式背后的压缩算法

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7033]
* 原文链接：[Understand the DEFLATE Compression behind the zip and gzip Formats](https://codeburst.io/understand-the-deflate-compression-behind-the-zip-and-gzip-formats-47e88b13bf3f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/understand-the-deflate-compression-behind-the-zip-and-gzip-formats.md)
* PR 地址：
* 文章分类：**算法**，**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnieXu** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@JohnieXu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7042
