### ISSUE TITLE
TypeScript 中的 never 类型

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7046]
* 原文链接：[TypeScript’s never Type](https://levelup.gitconnected.com/typescripts-never-type-d5f28271fcd6)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/typescripts-never-type.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：1 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnieXu** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@JohnieXu 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7064
