### ISSUE TITLE
用 JavaScript 中的蹦床函数实现安全递归

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7048]
* 原文链接：[Safe Recursion with Trampoline in JavaScript](https://levelup.gitconnected.com/safe-recursion-with-trampoline-in-javascript-dbec2b903022)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/safe-recursion-with-trampoline-in-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gesj-yean** [comment]
翻译认领

**Comment by lsvih** [comment]
@Gesj-yean 好的

**Comment by fanyijihua** [comment]
PR 地址：#7063
