### ISSUE TITLE
视觉设计本地化的重要性

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#705]
* 原文链接：[Lost in Translation: the importance of visual design localisation](https://medium.com/carwow-product-engineering/lost-in-translation-the-importance-of-visual-design-localisation-b75586eec030#.i73b3ayad)
* 掘金链接：[[英] 视觉设计本地化的重要性](http://gold.xitu.io/entry/57c930cd128fe10069634570)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/lost-in-translation-the-importance-of-visual-design-localisation.md)
* PR 地址：[PR](https://github.com/xitu/gold-miner/pull/712)
* 文章分类：**设计**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cbangchen** [comment]
认领

**Comment by sqrthree** [comment]
@cbangchen 好哒
