### ISSUE TITLE
如何编写可节省您时间的日志文件

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7050]
* 原文链接：[How to Write Log Files That Save You Hours of Time](https://medium.com/better-programming/how-to-write-log-files-that-save-you-hours-of-time-1ff0cd9ae2ed)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-to-write-log-files-that-save-you-hours-of-time.md)
* PR 地址：
* 文章分类：**后端**，**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PingHGao** [comment]
翻译认领 @lsvih

**Comment by fanyijihua** [comment]
@PingHGao 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7084

**Comment by Ultrasteve** [comment]
校对认领

**Comment by Ultrasteve** [comment]
校对认领 @lsvih
