### ISSUE TITLE
Python 内存管理之垃圾回收

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7052]
* 原文链接：[Garbage Collection in Python](https://medium.com/better-programming/garbage-collection-in-python-6dca154ae1dd)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/garbage-collection-in-python.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@chaingangway 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7076
