### ISSUE TITLE
用户体验案例学习：重新设计 KoinStreet 主页

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7054]
* 原文链接：[UX Case Study: KoinStreet Homepage Redesign](https://medium.com/ux-in-plain-english/ux-case-study-koinstreet-homepage-redesign-9da7686acd5b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/ux-case-study-koinstreet-homepage-redesign.md)
* PR 地址：#7179
* 文章分类：**设计**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zhengjian-L** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Zhengjian-L 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7179

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6869757477928304654
