### ISSUE TITLE
在 SwiftUI 中构建服务端驱动的 UI 组件

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7056]
* 原文链接：[Build a Server-Driven UI Using UI Components in SwiftUI](https://medium.com/better-programming/build-a-server-driven-ui-using-ui-components-in-swiftui-466ecca97290)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/build-a-server-driven-ui-using-ui-components-in-swiftui.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
翻译认领

**Comment by lsvih** [comment]
@chaingangway 好的

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6844904186862108679
