### ISSUE TITLE
ECMAScript 2020 新特性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7058]
* 原文链接：[The Latest Features Added to JavaScript in ECMAScript 2020](https://www.telerik.com/blogs/latest-features-javascript-ecmascript-2020)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/latest-features-javascript-ecmascript-2020.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gesj-yean** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Gesj-yean 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7069
