### ISSUE TITLE
为什么用户会打开你发的营销邮件

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#706]
* 原文链接：[Why do people open emails?](https://blog.mixpanel.com/2016/07/12/why-do-people-open-emails/)
* 掘金链接：[[英] 为什么用户会打开你发的营销邮件](http://gold.xitu.io/entry/57c9358c7db2a2007885506f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-do-people-open-emails.md)
* PR 地址：[:apple:](https://github.com/xitu/gold-miner/pull/721)
* 文章分类：**产品**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeadLion** [comment]
认领@sqrthree

**Comment by sqrthree** [comment]
@DeadLion OK.
