### ISSUE TITLE
如何使用内联框架元素 IFrames 的沙箱属性提高安全性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7060]
* 原文链接：[Play safely in sandboxed IFrames](https://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/sandboxed-iframes.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：20 天
* 校对时间：5 天
* 翻译积分：9 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gesj-yean** [comment]
翻译认领

**Comment by lsvih** [comment]
@Gesj-yean 好的

**Comment by fanyijihua** [comment]
PR 地址：#7128
