### ISSUE TITLE
推荐前端优秀英文文章

### ISSUE THREAD

**Issue by HytonightYX** [xitu/gold-miner#7068]
- 原文链接：https://mariosfakiolas.com/blog/my-react-components-render-twice-and-drive-me-crazy/
- 简要介绍：解释了为什么在 development 模式下组建会渲染两次。

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
#7150 已发布，感谢推荐！
