### ISSUE TITLE
设计一个你自己不会去用的产品

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#707]
* 原文链接：[Designing a Product You’re Not Going To Use](https://medium.com/@michalbaryoseph/designing-a-product-youre-not-going-to-use-7c3d069e84e8#.706sfym6k)
* 掘金链接：[[英] 设计一个你自己不会去用的产品](http://gold.xitu.io/entry/57c93b550e3dd90063e3e0ff)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/designing-a-product-youre-not-going-to-use.md)
* PR 地址：[PR](https://github.com/xitu/gold-miner/pull/710)
* 文章分类：**设计**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jiaowoyongqi** [comment]
认领！

**Comment by sqrthree** [comment]
@jiaowoyongqi 👌
