### ISSUE TITLE
在 Swift 使用 User Defaults 的小技巧

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7085]
* 原文链接：[User Defaults in Swift](https://levelup.gitconnected.com/user-defaults-in-swift-dfe228f684c6)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/user-defaults-in-swift.md)
* PR 地址：#7186
* 文章分类：**iOS**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@chaingangway 棒极啦 :tada:

**Comment by sunui** [comment]
@chaingangway Hi，进度如何

**Comment by sunui** [comment]
@chaingangway 这篇怎么样了

**Comment by chaingangway** [comment]
@lsvih 完成了
