### ISSUE TITLE
Ubuntu 20.04 会不会偷走更多的 Windows 用户？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7087]
* 原文链接：[Will Ubuntu 20.04 Steal More Windows Users?](https://codeburst.io/will-ubuntu-steal-more-windows-users-4745f52a73c4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/will-ubuntu-20-04-steal-more-windows-users.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by z0gSh1u** [comment]
翻译认领 @lsvih

**Comment by fanyijihua** [comment]
@z0gSh1u 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7102
