### ISSUE TITLE
Deno 会对 Node 造成威胁吗？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7089]
* 原文链接：[Is Deno a Threat to Node?](https://medium.com/better-programming/is-deno-a-threat-to-node-1ec3f177b73c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/is-deno-a-threat-to-node.md)
* PR 地址：
* 文章分类：**前端**，**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZiXYu** [comment]
@lsvih 领~

**Comment by lsvih** [comment]
@ZiXYu 好的！
