### ISSUE TITLE
可以用来构建 Deno Web 应用程序的 7 个模块

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7091]
* 原文链接：[7 modules you can use right now to build your first Deno web app](https://medium.com/javascript-in-plain-english/7-modules-you-can-use-right-now-to-build-your-first-deno-web-app-b041a156a346)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/7-modules-you-can-use-right-now-to-build-your-first-deno-web-app.md)
* PR 地址：
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by niayyy-S** [comment]
@fanyijihua 翻译认领

**Comment by lsvih** [comment]
@niayyy-S 好的

**Comment by fanyijihua** [comment]
PR 地址：#7095
