### ISSUE TITLE
记一次 —— 构建 API 网关服务的经历

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7093]
* 原文链接：[My experiences with API gateways…](https://medium.com/@mahesh.mahadevan/my-experiences-with-api-gateways-8a93ad17c4c4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/my-experiences-with-api-gateways.md)
* PR 地址：#7180
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：20 天
* 校对时间：5 天
* 翻译积分：10 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由@todaycoder001 翻译

**Comment by todaycoder001** [comment]
翻译认领

**Comment by sunui** [comment]
@todaycoder001 Hi，翻译得怎么样啦

**Comment by todaycoder001** [comment]
> @todaycoder001 Hi，翻译得怎么样啦

抱歉，最近比较忙，周末应该能翻译好。

**Comment by fanyijihua** [comment]
PR 地址：#7180
