### ISSUE TITLE
用 Python 写一个俄罗斯方块游戏

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7104]
* 原文链接：[Writing Tetris in Python](https://levelup.gitconnected.com/writing-tetris-in-python-2a16bddb5318)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/writing-tetris-in-python.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by z0gSh1u** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@z0gSh1u 好的

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6844904183456350221
