### ISSUE TITLE
重新思考前端：微前端

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7106]
* 原文链接：[Rethinking the Front-end: Micro Frontend](https://medium.com/front-end-weekly/rethinking-the-front-end-micro-frontend-4cf21f0e22e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/rethinking-the-front-end-micro-frontend.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：1.5 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by IAMSHENSH** [comment]
翻译认领

**Comment by IAMSHENSH** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@IAMSHENSH 棒极啦 :tada:

**Comment by tanglie1993** [comment]
校对认领。

**Comment by IAMSHENSH** [comment]
要到对应的 PR 下认领校对 @tanglie1993 

[在这里](https://github.com/xitu/gold-miner/pull/7123#issuecomment-631938259)
