### ISSUE TITLE
知识的极限

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7108]
* 原文链接：[The limits of knowledge](https://towardsdatascience.com/the-limits-of-knowledge-b59be67fd50a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/the-limits-of-knowledge.md)
* PR 地址：
* 文章分类：**AI**，**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by QinRoc** [comment]
翻译认领

**Comment by lsvih** [comment]
@QinRoc 好的！

**Comment by lsvih** [comment]
已发布于 https://juejin.im/post/6874475968325484552
