### ISSUE TITLE
三个哈希在 Python 中不可不知的问题

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7110]
* 原文链接：[3 Essential Questions About Hashable in Python](https://medium.com/better-programming/3-essential-questions-about-hashable-in-python-33e981042bcb)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/3-essential-questions-about-hashable-in-python.md)
* PR 地址：#7188
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shixi-li** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@shixi-li 棒极啦 :tada:

**Comment by sunui** [comment]
@shixi-li Hi，进度如何？

**Comment by shixi-li** [comment]
@sunui 抱歉，我这边有延期，预计本周六翻译完成

**Comment by sunui** [comment]
@shixi-li Hi，进度如何

**Comment by shixi-li** [comment]
一不小心又拖了好久才弄完  -.-||
