### ISSUE TITLE
Swift 5.3 的新功能，你了解吗?

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7112]
* 原文链接：[What’s New in Swift 5.3?](https://medium.com/better-programming/whats-new-in-swift-5-3-142d89d4d1f7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/whats-new-in-swift-5-3.md)
* PR 地址：#7185
* 文章分类：**iOS**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@chaingangway 棒极啦 :tada:

**Comment by sunui** [comment]
@chaingangway  Hi，进度如何？

**Comment by fanyijihua** [comment]
PR 地址：#7185
