### ISSUE TITLE
手机端 WebKit 内核浏览器 100vh 问题的 CSS 修复方法

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7114]
* 原文链接：[CSS fix for 100vh in mobile WebKit](https://allthingssmitty.com/2020/05/11/css-fix-for-100vh-in-mobile-webkit/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/css-fix-for-100vh-in-mobile-webkit.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by z0gSh1u** [comment]
翻译认领 @lsvih

**Comment by fanyijihua** [comment]
@z0gSh1u 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7125

**Comment by lhd951220** [comment]
校对认领 @Glowin
