### ISSUE TITLE
一个你不知道但可能会需要的 Vue 插件

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7116]
* 原文链接：[Vue Plugins You Don’t Know You May Need](https://medium.com/swlh/vue-plugins-you-dont-know-you-may-need-573902dfdbae)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/vue-plugins-you-dont-know-you-may-need.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gesj-yean** [comment]
翻译认领 @lsvih

**Comment by fanyijihua** [comment]
@Gesj-yean 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7129
