### ISSUE TITLE
使用 Deno 和 Oak 构建 CRUD API

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7120]
* 原文链接：[Building CRUD APIs using Deno and oak](https://medium.com/javascript-in-plain-english/building-crud-apis-using-deno-and-oak-9f71ec106b0e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/building-crud-apis-using-deno-and-oak.md)
* PR 地址：
* 文章分类：**后端**，**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：1.5 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lhd951220** [comment]
翻译认领 @Glowin

**Comment by fanyijihua** [comment]
@lhd951220 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7124
