### ISSUE TITLE
改善 CSS 的 10 个最佳实践 #7178

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7122]
* 原文链接：[10 Best Practices for Improving Your CSS](https://medium.com/better-programming/10-best-practices-for-improving-your-css-84c69aac66e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/10-best-practices-for-improving-your-css.md)
* PR 地址：#7178
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：13 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by febrainqu** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@febrainqu 棒极啦 :tada:

**Comment by sunui** [comment]
@febrainqu Hi，翻译进度如何
