### ISSUE TITLE
如何使用 Python 生成随机文本验证码

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7134]
* 原文链接：[How to Generate Random Text CAPTCHAs Using Python](https://medium.com/better-programming/how-to-generate-random-text-captchas-using-python-e734dd2d7a51)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-to-generate-random-text-captchas-using-python.md)
* PR 地址：#7170
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lhd951220** [comment]
翻译认领 @Glowin

**Comment by fanyijihua** [comment]
@lhd951220 棒极啦 :tada:

**Comment by sunui** [comment]
@lhd951220  Hi，进度如何？

**Comment by lhd951220** [comment]
已翻译完成，马上上传 @sunui
