### ISSUE TITLE
你理解数据库死锁发生的原因吗? 

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7142]
* 原文链接：[Understanding why a database deadlock occurs](https://levelup.gitconnected.com/understanding-why-a-database-deadlock-occurs-8bbd32be8026)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/understanding-why-a-database-deadlock-occurs.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gesj-yean** [comment]
翻译认领 @lsvih

**Comment by fanyijihua** [comment]
@Gesj-yean 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7162

**Comment by samyu2000** [comment]
校对认领 @lsvih

**Comment by samyu2000** [comment]
@glowin 校对认领

**Comment by lsvih** [comment]
@samyu2000 到 #7162 这里面认领哈~
