### ISSUE TITLE
关于 let 和 const 的对比

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7144]
* 原文链接：[On let vs const](https://overreacted.io/on-let-vs-const/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/on-let-vs-const.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gesj-yean** [comment]
翻译认领 @lsvih

**Comment by fanyijihua** [comment]
@Gesj-yean 棒极啦 :tada:

**Comment by tanglie1993** [comment]
@fanyijihua 不是默认让推荐人翻译的吗？
@Gesj-yean 请问可以把翻译让给我吗……这个对我比较重要。谢谢。

**Comment by tanglie1993** [comment]
@lsvih

**Comment by lsvih** [comment]
@tanglie1993 啊，一般说一声就会提前分配

@Gesj-yean 您二位商量一下？

**Comment by Gesj-yean** [comment]
@tanglie1993 @lsvih 好的，由推荐者翻译吧～

**Comment by tanglie1993** [comment]
@Gesj-yean 感谢！
