### ISSUE TITLE
Schema.org: 你未曾耳闻的流行网页标准 🤫

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7146]
* 原文链接：[Schema.org: The Popular Web Standard You’ve Never Heard Of 🤫](https://levelup.gitconnected.com/schema-org-the-popular-web-standard-youve-never-heard-of-d9b7ff28a22d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/schema-org-the-popular-web-standard-youve-never-heard-of.md)
* PR 地址：#7177
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lhd951220** [comment]
翻译认领 @lsvih

**Comment by fanyijihua** [comment]
@lhd951220 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7177
