### ISSUE TITLE
我的 React 组件会渲染两次，我快疯了

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7150]
* 原文链接：[My React components render twice and drive me crazy](https://mariosfakiolas.com/blog/my-react-components-render-twice-and-drive-me-crazy/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/my-react-components-render-twice-and-drive-me-crazy.md)
* PR 地址：#7166
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tanglie1993** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@tanglie1993 棒极啦 :tada:
