### ISSUE TITLE
CSS Flexbox 中安全/不安全的对齐方式

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7152]
* 原文链接：[Safe/unsafe alignment in CSS flexbox](https://www.stefanjudis.com/today-i-learned/safe-unsafe-alignment-in-css-flexbox/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/safe-unsafe-alignment-in-css-flexbox.md)
* PR 地址：#7173
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by fanyijihua** [comment]
@Baddyo 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7173
