### ISSUE TITLE
Object.freeze VS Object.seal —— JavaScript 数据不变性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7154]
* 原文链接：[Object.freeze vs Object.seal — Immutability](https://medium.com/javascript-in-plain-english/object-freeze-vs-object-seal-immutability-7c22f80aa8ae)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/object-freeze-vs-object-seal-immutability.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gesj-yean** [comment]
翻译认领 @lsvih

**Comment by fanyijihua** [comment]
@Gesj-yean 棒极啦 :tada:
