### ISSUE TITLE
鲜为人知的 GraphQL 特性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7157]
* 原文链接：[Some Arbitrary Number of Lesser-Known GraphQL Features](https://medium.com/front-end-weekly/some-arbitrary-number-of-lesser-known-graphql-features-7fe3feeda72)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/some-arbitrary-number-of-lesser-known-graphql-features.md)
* PR 地址：
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hansonfang** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
这也太快了！
