### ISSUE TITLE
我是如何用 20 小时学会 Sass 的以及为什么你也应该这么做

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7159]
* 原文链接：[How I Learned SASS in 20 Hours and Why You Should Too.](https://medium.com/front-end-weekly/how-i-learned-sass-in-20-hours-and-why-you-should-too-a2fb92d0359c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-i-learned-sass-in-20-hours-and-why-you-should-too.md)
* PR 地址：#7172
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：3.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by z0gSh1u** [comment]
翻译认领  @lsvih

**Comment by lsvih** [comment]
@z0gSh1u 好的！

**Comment by fanyijihua** [comment]
PR 地址：#7172
