### ISSUE TITLE
开发移动应用，你应该注意这些小细节

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#716]
* 原文链接：[Little Big Details For Your Mobile App](http://babich.biz/little-big-details-for-your-mobile-app/)
* 掘金链接：[[英] 开发移动应用，你应该注意这些小细节](http://gold.xitu.io/entry/57cd1dee8ac2470064580457)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/little-big-details-for-your-mobile-app.md)
* PR：[你敢点？](https://github.com/xitu/gold-miner/pull/720)
* 文章分类：**产品**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mypchas6fans** [comment]
认领

**Comment by sqrthree** [comment]
@mypchas6fans OK.
