### ISSUE TITLE
Android 中的意料之外的应用崩溃以及解决它们的方法

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7161]
* 原文链接：[Unexpected App Crashes on Android and How to Deal with Them](https://levelup.gitconnected.com/unexpected-app-crashes-on-android-and-how-to-deal-with-them-c5d07512d99f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/unexpected-app-crashes-on-android-and-how-to-deal-with-them.md)
* PR 地址：
* 文章分类：**Android**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ultrasteve** [comment]
翻译认领

**Comment by Ultrasteve** [comment]
翻译认领 @fanyijihua

**Comment by fanyijihua** [comment]
@Ultrasteve 棒极啦 :tada:

**Comment by sunui** [comment]
@Ultrasteve 进度如何？

**Comment by sunui** [comment]
@Ultrasteve 还在翻译吗

**Comment by PassionPenguin** [comment]
@lsvih  翻译认领

**Comment by lsvih** [comment]
@PassionPenguin 好的~
