### ISSUE TITLE
Redux 中过时的 props 和僵尸子节点

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#7168]
* 原文链接：[Stale props and zombie children in Redux](https://kaihao.dev/posts/Stale-props-and-zombie-children-in-Redux)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/Stale-props-and-zombie-children-in-Redux.md)
* PR 地址： #7197
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by niayyy-S** [comment]
校对认领 @fanyijihua

**Comment by niayyy-S** [comment]
翻译认领 @fanyijihua

**Comment by fanyijihua** [comment]
@niayyy-S 棒极啦 :tada:

**Comment by sunui** [comment]
@niayyy-S 进度如何？

**Comment by niayyy-S** [comment]
woc，差点忘记了，这短时间在准备考试，我马上开始翻译，非常抱歉
________________________________

**Comment by sunui** [comment]
@nia3y 加油咯

**Comment by nia3y** [comment]
好的，这两天肯定翻译完
