### ISSUE TITLE
Hi 设计师，你需要的只是在设计中多用点 “心”

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#717]
* 原文链接：[The Art of Designing With Heart](https://m.signalvnoise.com/the-art-of-designing-with-heart-f5dc4df21697?swoff=true#.bwkktzgf7)
* 掘金链接：[[英] Hi 设计师，你需要的只是在设计中多用点 “心”](http://gold.xitu.io/entry/57ce8111165abd005f04b4bf)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-art-of-designing-with-heart.md)
* PR 地址：[PR 地址](https://github.com/xitu/gold-miner/pull/727)
* 文章分类：**设计**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mypchas6fans** [comment]
认领

**Comment by sqrthree** [comment]
@mypchas6fans 认领两篇？

**Comment by mypchas6fans** [comment]
不太合适就等下一位吧~~

**Comment by llp0574** [comment]
get

**Comment by sqrthree** [comment]
@llp0574 好的，顺便说一下你最擅长的一到两个分类吧，以后就可以认领自己擅长的分类的文章啦

**Comment by llp0574** [comment]
@sqrthree 设计、前端和iOS开发，是以后不能领自己不擅长分类的文章了吗？

**Comment by sqrthree** [comment]
@llp0574 嗯嗯，尽量吧，因为毕竟如果不是擅长的领域，有些专业名词还是翻译的不太准确的，出现过几次这种情况了~ 理解下啦 ❤️

**Comment by llp0574** [comment]
@sqrthree [校对地址](https://github.com/xitu/gold-miner/pull/727)
