### ISSUE TITLE
[AI 优秀文章推荐] How powerful are Graph Convolutions?

### ISSUE THREAD

**Issue by ccJia** [xitu/gold-miner#7174]
- 原文链接：推荐文章前 Google 一下，尽量保证本文未被翻译
https://www.inference.vc/how-powerful-are-graph-convolutions-review-of-kipf-welling-2016-2/
- 简要介绍：介绍一下好不好啦，毕竟小编也看不太懂哎_(:з」∠)_

--- 对图神经网络的经典文章的回顾。

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by ccJia** [comment]
@sunui  推荐新文章 ^-^

**Comment by sunui** [comment]
感谢推荐，已发布 #7184
