### ISSUE TITLE
Diverse Mini-Batch Active Learning: A Reproduction Exercise

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7176]
* 原文链接：[Diverse Mini-Batch Active Learning: A Reproduction Exercise](https://medium.com/data-from-the-trenches/diverse-mini-batch-active-learning-a-reproduction-exercise-2396cfee61df)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/diverse-mini-batch-active-learning-a-reproduction-exercise.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：15 天
* 校对时间：3 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by z0gSh1u** [comment]
翻译认领  @fanyijihua

**Comment by fanyijihua** [comment]
@z0gSh1u 棒极啦 :tada:
