### ISSUE TITLE
顾虑越少，设计越好

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#718]
* 原文链接：[Think Less. Design Better.](https://medium.com/@xtianmiller/think-less-design-better-f812c1617888)
* 掘金链接：[[英] 顾虑越少，设计越好](http://gold.xitu.io/entry/57cf7ce48ac2470062dbbaae)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/think-less-design-better.md)
* PR 地址：[PR](https://github.com/xitu/gold-miner/pull/726)
* 文章分类：**设计**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mypchas6fans** [comment]
我是不是应该让一个……

**Comment by sqrthree** [comment]
@mypchas6fans 你是做什么的呀？给我说下你擅长的领域，我方便给加到 [wiki](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E8%80%85%E6%93%85%E9%95%BF%E9%A2%86%E5%9F%9F%E8%A1%A8) 里吧

**Comment by sqrthree** [comment]
@mypchas6fans 感觉你会被群殴的~ 哈哈哈

**Comment by mypchas6fans** [comment]
@sqrthree 后端。为了避免被打，我还是只要移动开发那篇吧~

**Comment by sqrthree** [comment]
好的👌

**Comment by Zheaoli** [comment]
我抢了这篇吧。。

**Comment by siegeout** [comment]
认领一发

**Comment by sqrthree** [comment]
@siegeout 好哒，顺便说一下你最擅长的一到两个分类吧，以后就可以认领自己擅长的分类的文章啦
