### ISSUE TITLE
How powerful are Graph Convolutions? (review of Kipf & Welling, 2016)

### ISSUE THREAD

**Issue by sunui** [xitu/gold-miner#7184]
* 原文链接：[How powerful are Graph Convolutions? (review of Kipf & Welling, 2016)](https://www.inference.vc/how-powerful-are-graph-convolutions-review-of-kipf-welling-2016-2/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-powerful-are-graph-convolutions-review-of-kipf-welling.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by noirlyrik** [comment]
翻译认领

**Comment by lsvih** [comment]
@noirlyrik 好的~
