### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ddiiiik** [xitu/gold-miner#719]
Hi 我是 Dominic，一家媒体的产品经理。常去网站有 [Medium](https://medium.com/@ddiiiik) / Inside Intercom / Sidebar / First Round Review 等等。过往翻译作品 [请见此处](http://dwz.cn/46cGAI)。目前在养着一个微信公众号 BuildForever，每天推荐一篇产品/设计/用户体验相关的英文文章，已做到第 221 期。希望可以加入多多学习交流，谢谢！

**Comment by antonia0912** [comment]
@ddiiiik 欢迎来掘金翻译计划玩 请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群
