### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by Candy-design** [xitu/gold-miner#7209]
- 原文链接：https://uxdesign.cc/ui-cheat-sheet-pagination-infinite-scroll-and-the-load-more-button-e5c452e279a8
- 简要介绍：UI 备忘单：分页、无限滚动和“加在更多”按钮

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by Candy-design** [comment]
@fanyijihua  翻译认领

**Comment by Candy-design** [comment]
@fanyijihua 已经翻译完成，能否开个翻译的issue，指定我本人翻译

**Comment by Candy-design** [comment]
@fanyijihua  前几天我已经翻译好了发到知乎上去了，账号是B端设计笔记，我想提交到掘金的开源项目上

**Comment by lsvih** [comment]
https://zhuanlan.zhihu.com/p/160263152 是这个吗

**Comment by Candy-design** [comment]
@lsvih 对的，就是这个。

**Comment by lsvih** [comment]
您直接提 PR 把译文替换 https://github.com/xitu/gold-miner/blob/master/article/2020/ui-cheat-sheet-pagination-infinite-scroll-and-the-load-more-button.md 这个文件吧~
