### ISSUE TITLE
如何在字符串中隐藏秘密 —— JavaScript 中的现代文本隐藏

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7214]
* 原文链接：[How to Hide Secrets in Strings — Modern Text hiding in JavaScript](https://blog.bitsrc.io/how-to-hide-secrets-in-strings-modern-text-hiding-in-javascript-613a9faa5787)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-to-hide-secrets-in-strings-modern-text-hiding-in-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nia3y** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@nia3y 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7254
