### ISSUE TITLE
在商业智能中使用 MongoDB 的 4 种方式 - 如何在非结构化数据中使用结构化查询分析

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7216]
* 原文链接：[4 Options for Using MongoDB with Business Intelligence](https://levelup.gitconnected.com/4-options-for-using-mongodb-with-business-intelligence-ec278738b5d2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/4-options-for-using-mongodb-with-business-intelligence.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：6 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by cyz980908** [comment]
@fanyijihua 翻译认领

**Comment by itcodes** [comment]
@cyz980908 翻译的咋样了。兄弟。

**Comment by huifrank** [comment]
@cyz980908 兄弟怎么样了？

要不这个文章我来 内容挺对胃口的？@itcodes @lsvih

**Comment by cyz980908** [comment]
感谢🙏，你来吧

**Comment by huifrank** [comment]
@fanyijihua @lsvih 翻译认领

**Comment by lsvih** [comment]
@huifrank 欢迎翻译，加油 →_→
