### ISSUE TITLE
Python: smart coding with locals() and global()

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7218]
* 原文链接：[Python: smart coding with locals() and global()](https://medium.com/python-in-plain-english/python-smart-coding-with-locals-and-global-257ae25461ee)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/python-smart-coding-with-locals-and-global.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：1 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by actini** [comment]
认领翻译

**Comment by lsvih** [comment]
@actini 好的
