### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by lix90** [xitu/gold-miner#722]
大家好，我叫 lix90，目前是西南大学心理学部硕士三年级学生，专业是认知神经科学。具有较好的英文阅读和写作基础，已独立完成一篇英文学术论文的写作。常访问的英文网站为 Github、stackexchange、youtube、谷歌学术、一些编程语言文档和社区。目前对前端设计以及产品开发感兴趣，业余做过一段时间的平面设计。最近开了自己的博客 [lix90.github.io](https://lix90.github.io) 目前还未更新内容。希望能为社区做微薄贡献。

**Comment by antonia0912** [comment]
请问计算机相关的英文文章有翻译经验吗？

**Comment by lix90** [comment]
@antonia0912 你好，虽然没有翻译过计算机方面的文章，但我自学编程语言的书籍都是英文的，也看一些英文技术类博客。自认为基本能胜任这项工作。
