### ISSUE TITLE
给前端开发者的 14 个 JavaScript 代码优化建议

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7220]
* 原文链接：[14 JavaScript Code Optimization Tips for Front-End Developers](https://blog.bitsrc.io/14-javascript-code-optimization-tips-for-front-end-developers-a44763d3a0da)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/14-javascript-code-optimization-tips-for-front-end-developers.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：16 天
* 校对时间：4 天
* 翻译积分：11 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gesj-yean** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Gesj-yean 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7237

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6859562506721951751
