### ISSUE TITLE
学习 SwiftUI 框架中 Text 和 Label 控件的用法（iOS 14）

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7222]
* 原文链接：[Learn About SwiftUI Text and Label in iOS 14](https://medium.com/better-programming/learn-about-swiftui-text-and-label-in-ios-14-bfee41252117)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/learn-about-swiftui-text-and-label-in-ios-14.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@chaingangway 棒极啦 :tada:

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6881526224934420488
