### ISSUE TITLE
使用 JavaScript 解构让代码更优雅

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7224]
* 原文链接：[Write Cleaner Code by Using JavaScript Destructuring](https://medium.com/better-programming/write-cleaner-code-by-using-javascript-destructuring-cd6b55c25bac)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/write-cleaner-code-by-using-javascript-destructuring.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chaingangway** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@chaingangway 棒极啦 :tada:

**Comment by zenblo** [comment]
@chaingangway @lsvih 好久没动静了，我接过来翻译吧

**Comment by lsvih** [comment]
@zenblo 好的~
