### ISSUE TITLE
如何创建一个可复用的网页爬虫

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7228]
* 原文链接：[How to Create a Reusable Web Scraper](https://medium.com/better-programming/how-to-create-a-reusable-web-scraper-5a5aa9af62d9)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-to-create-a-reusable-web-scraper.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@YueYongDev 棒极啦 :tada:
