### ISSUE TITLE
10 个你应该现在启用的绝佳的 Chrome Flags

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7229]
* 原文链接：[10 Awesome Chrome Flags You Should Enable Right Now](https://medium.com/better-programming/10-awesome-chrome-flags-you-should-enable-right-now-2684e4518cb5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/10-awesome-chrome-flags-you-should-enable-right-now.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyz980908** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@cyz980908 棒极啦 :tada:

**Comment by PassionPenguin** [comment]
申请翻译 @lsvih
