### ISSUE TITLE
不服跑个分 - 顶级 Swift 服务端框架对决 Node.js

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#723]
* 原文链接：[Benchmarks for the Top Server-Side Swift Frameworks vs. Node.js](https://medium.com/@rymcol/benchmarks-for-the-top-server-side-swift-frameworks-vs-node-js-24460cfe0beb)
* 掘金链接：[[英] 不服跑个分 - 顶级 Swift 服务端框架对决 Node.js](http://gold.xitu.io/entry/57d0fea5816dfa00542aaf86)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/benchmarks-for-the-top-server-side-swift-frameworks-vs-node-js.md)
* PR 地址：[表点我](https://github.com/xitu/gold-miner/pull/737)
* 文章分类：**iOS**

----
* 翻译时间：`4` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mypchas6fans** [comment]
还真用这种标题啊……认领

**Comment by sqrthree** [comment]
@mypchas6fans 好的，顺便在 [译者擅长领域表](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E8%80%85%E6%93%85%E9%95%BF%E9%A2%86%E5%9F%9F%E8%A1%A8) 填一下你最擅长的一到两个领域吧 😘

**Comment by mypchas6fans** [comment]
@sqrthree 不好意思……这周事情比较多，可以放弃这篇另外请人翻吗？

**Comment by sqrthree** [comment]
@mypchas6fans 好

**Comment by Tuccuay** [comment]
收 （

**Comment by sqrthree** [comment]
@Tuccuay 妥妥哒

**Comment by sqrthree** [comment]
@Tuccuay 这篇文章的进度如何了呀？

**Comment by Tuccuay** [comment]
😂今晚吧（

**Comment by Tuccuay** [comment]
@sqrthree 校对辣（ #737

**Comment by sqrthree** [comment]
@Tuccuay 好哒~ 辛苦啦
