### ISSUE TITLE
JavaScript Tips — Child Constructors, Text Selection, Inline Workers, and More

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7231]
* 原文链接：[JavaScript Tips — Child Constructors, Text Selection, Inline Workers, and More](https://medium.com/front-end-weekly/javascript-tips-child-constructors-text-selection-inline-workers-and-more-606bc050ee24)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/javascript-tips-child-constructors-text-selection-inline-workers-and-more.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by plusmultiply0** [comment]
校对认领

**Comment by plusmultiply0** [comment]
翻译认领
打错了

**Comment by fanyijihua** [comment]
@plusmultiply0 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7232
