### ISSUE TITLE
前端开发 8 大性能分析工具

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7234]
* 原文链接：[8 Performance Analysis Tools for Front-End Development](https://blog.bitsrc.io/performance-analysis-tools-for-front-end-development-a7b3c1488876)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/performance-analysis-tools-for-front-end-development.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by IAMSHENSH** [comment]
翻译认领

**Comment by IAMSHENSH** [comment]
认领翻译
@lsvih

**Comment by lsvih** [comment]
@IAMSHENSH 好的

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6860664312504320014
