### ISSUE TITLE
使用 Shpinx 为 Python 项目自动生成文档

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7236]
* 原文链接：[Auto-Documenting a Python Project Using Sphinx](https://medium.com/better-programming/auto-documenting-a-python-project-using-sphinx-8878f9ddc6e9)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/auto-documenting-a-python-project-using-sphinx.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by actini** [comment]
认领翻译

**Comment by fanyijihua** [comment]
@actini 棒极啦 :tada:

**Comment by actini** [comment]
@lsvih 不好意思啊，最近太忙了，还没来得及翻译，我抓紧时间交作业

**Comment by actini** [comment]
@lsvih 还在翻译中……我尽快完成

**Comment by lsvih** [comment]
@actini 没事没事
