### ISSUE TITLE
打包用于分发的 UI 库 —— 当你要发布一个 UI 组件库时，你可能需要遵守的指南

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7239]
* 原文链接：[Packaging a UI Library for Distribution](https://blog.bitsrc.io/packaging-a-ui-library-for-distribution-d153219def28)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/packaging-a-ui-library-for-distribution.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by plusmultiply0** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@plusmultiply0 棒极啦 :tada:

**Comment by fanyijihua** [comment]
PR 地址：#7261

**Comment by zenblo** [comment]
校对认领

**Comment by lsvih** [comment]
@zenblo 您得在 #7261 这里认领 🤦
