### ISSUE TITLE
构建设计系统和组件库

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7243]
* 原文链接：[Building a design system and a component library](https://medium.com/javascript-in-plain-english/building-a-design-system-and-a-component-library-3f4e01a7b0b4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/building-a-design-system-and-a-component-library.md)
* PR 地址：
* 文章分类：**设计**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：9 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Charlo-O** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@Charlo-O 棒极啦 :tada:
