### ISSUE TITLE
使用合成数据改善机器学习中的极度不平衡数据集

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7245]
* 原文链接：[Improving massively imbalanced datasets in machine learning with synthetic data](https://towardsdatascience.com/improving-massively-imbalanced-datasets-in-machine-learning-with-synthetic-data-7dd3d856bbdf)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/improving-massively-imbalanced-datasets-in-machine-learning-with-synthetic-data.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PingHGao** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@PingHGao 棒极啦 :tada:
