### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by esong** [xitu/gold-miner#725]
* 公司/学校：加拿大的一个创业公司/University of Waterloo 软件工程
* 工作内容/专业：Android工程师
* 常浏览的国外网站: HackerNews/TechCrunch/The Verge
* 英语水平: Working proficiency 
* 有无翻译经验: 无

**Comment by antonia0912** [comment]
@esong 请加我微信 antonia0912 备注 github id 我来拉你进译者群
