### ISSUE TITLE
从头开始到最初的 10 个客户：我是如何设计并推出一个 SaaS 产品

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7251]
* 原文链接：[From scratch to the first 10 customers: How I designed and launched a SaaS product](https://codeburst.io/from-scratch-to-the-first-10-customers-how-i-designed-and-launched-a-saas-product-9176a8996b89)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/from-scratch-to-the-first-10-customers-how-i-designed-and-launched-a-saas-product.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：16 天
* 校对时间：5 天
* 翻译积分：12 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@YueYongDev 棒极啦 :tada:

**Comment by scarqin** [comment]
校对认领

**Comment by lsvih** [comment]
@scarqin 等翻译完了 at 您来校对哈 🤦

**Comment by YueYongDev** [comment]
@fanyijihua @lsvih 已经翻译完成了，这篇文章翻译起来有点难受，辛苦校对人员了 @scarqin

**Comment by lsvih** [comment]
@YueYongDev 辛苦啦。。

**Comment by scarqin** [comment]
@YueYongDev 辛苦啦，我明天开始校对。
