### ISSUE TITLE
Vue 应用的代码覆盖率

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7256]
* 原文链接：[Code Coverage for Vue Applications](https://vuejsdevelopers.com/2020/07/20/code-coverage-vue-cypress/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/code-coverage-vue-cypress.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tonylua** [comment]
认领

**Comment by lsvih** [comment]
@tonylua 好的！

**Comment by tonylua** [comment]
https://github.com/tonylua/gold-miner/commit/641e80c4e32c2f8576b2fe3d888958d160aa6485  @lsvih 提交了一次以后还有怎样操作？

**Comment by lsvih** [comment]
@tonylua 您在 https://github.com/xitu/gold-miner/compare/master...tonylua:patch-1 这里点 Create pull request 创建一个 pr

**Comment by tonylua** [comment]
已提交 @lsvih

**Comment by tonylua** [comment]
@lsvih 是不是可以替他加一下信息后关闭了

**Comment by lsvih** [comment]
@tonylua 是的。。

**Comment by tonylua** [comment]
@lsvih 已更新译文

**Comment by lsvih** [comment]
@tonylua 您是不是没传上来= =在 pr 里看不到更新的内容 🤦

**Comment by tonylua** [comment]
https://github.com/xitu/gold-miner/pull/7270/commits @lsvih 这里有11号最新的提交不对吗？

**Comment by lsvih** [comment]
@tonylua 恩恩看到啦。麻烦您把校对者信息加一下吧，这篇翻译的挺好的，一位校对就够了

**Comment by tonylua** [comment]
@lsvih 校对者信息已添加

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6872653403177254919
