### ISSUE TITLE
推荐优秀英文文章

### ISSUE THREAD

**Issue by kasheemlew** [xitu/gold-miner#7257]
- 原文链接：https://dropbox.tech/infrastructure/how-we-migrated-dropbox-from-nginx-to-envoy
- 简要介绍：envoy 与 nginx 对比，以及 dropbox 如何从 nginx 迁移到 envoy

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：后端
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
这篇文章很好，但是太长了，所以一直没有加进来，直到今天看到 http://www.dockone.io/article/450995 已经有翻译了。总之，感谢推荐！
