### ISSUE TITLE
My Favorite JavaScript Tips and Tricks

### ISSUE THREAD

**Issue by zenblo** [xitu/gold-miner#7266]
- 原文链接：https://blog.greenroots.info/my-favorite-javascript-tips-and-tricks-ckd60i4cq011em8s16uobcelc
- 简要介绍：有关JS编程技巧

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端
* [ ] 本文很值得翻译，我推荐
* [ ] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
已发布 #7268
