### ISSUE TITLE
分享我喜欢的十五条 JavaScript 编程技巧

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7268]
* 原文链接：[My Favorite JavaScript Tips and Tricks](https://blog.greenroots.info/my-favorite-javascript-tips-and-tricks-ckd60i4cq011em8s16uobcelc)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/my-favorite-javascript-tips-and-tricks.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
#7266 推荐

**Comment by zenblo** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@zenblo 棒极啦 :tada:

**Comment by zenblo** [comment]
@fanyijihua @lsvih 译文翻译完成
