### ISSUE TITLE
8 Unheard of Browser APIs You Should Be Aware Of

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7272]
* 原文链接：[8 Unheard of Browser APIs You Should Be Aware Of](https://medium.com/better-programming/8-unheard-of-browser-apis-you-should-be-aware-of-45247e7d5f3a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/8-unheard-of-browser-apis-you-should-be-aware-of.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
翻译认领

**Comment by lsvih** [comment]
@zenblo 您确定要认领吗- -  一般不太推荐同时认领很多篇给自己太大压力的

**Comment by zenblo** [comment]
我现在有空闲时间，应该可以的

**Comment by lsvih** [comment]
好的！那辛苦你啦！

**Comment by zenblo** [comment]
@lsvih 翻译完成
