### ISSUE TITLE
自己写一个 redux

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7279]
* 原文链接：[Build Yourself a Redux](https://zapier.com/engineering/how-to-build-redux/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-to-build-redux.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：30 天
* 校对时间：10 天
* 翻译积分：16 分
* 校对积分：7 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文内容很好，但是篇幅较长，请慎重认领

**Comment by tanglie1993** [comment]
翻译认领。可以切成多个部分吗？

**Comment by fanyijihua** [comment]
@tanglie1993 棒极啦 :tada:

**Comment by lsvih** [comment]
@tanglie1993 可以的
