### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zwgg** [xitu/gold-miner#728]
姓名：zwgg
公司：吃货平台-觅食
工作内容/专业：Android工程师 / 计算机科学与技术
常浏览的国外网站: stackoverflow leetcode
英语水平: CET 4
有无翻译经验: 虽无正式的翻译经验，但开发Android免不了读译大量的英文文档

**Comment by antonia0912** [comment]
@zwgg 请加我微信 antonia0912 备注 github id 我来拉你进译者群
