### ISSUE TITLE
8 个有用的 SCSS 最佳实践

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7282]
* 原文链接：[8 SCSS Best Practices to Keep in Mind](https://dev.to/liaowow/8-css-best-practices-to-keep-in-mind-4n5h)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/8-scss-best-practices-to-keep-in-mind.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：1.5 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by snowyYU** [comment]
翻译认领

**Comment by fanyijihua** [comment]
@snowyYU 棒极啦 :tada:
