### ISSUE TITLE
Create your own ‘CamScanner’ using Python & OpenCV

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7287]
* 原文链接：[Create your own ‘CamScanner’ using Python & OpenCV](https://levelup.gitconnected.com/create-your-own-camscanner-using-python-opencv-66251212270)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/create-your-own-camscanner-using-python-opencv.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnJiangLA** [comment]
认领

**Comment by lsvih** [comment]
@JohnJiangLA 好的！
