### ISSUE TITLE
Interactive WebGL Hover Effects

### ISSUE THREAD

**Issue by zenblo** [xitu/gold-miner#7288]
- 原文链接：https://tympanus.net/codrops/2020/04/14/interactive-webgl-hover-effects/
- 简要介绍：这是关于前端图形化方向，也是我目前学习的

---

### 请完成并勾选一下三项：

* [ ] 按文章分类填写 issue 标题：推荐前端英文文章
* [x] 本文很值得翻译，我推荐
* [ ] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by zenblo** [comment]
@lsvih 我想翻译这个

**Comment by lsvih** [comment]
@zenblo 👍 我晚上加一下

**Comment by lsvih** [comment]
#7304 已发布
