### ISSUE TITLE
利用映射提高 MongoDB 性能

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7290]
* 原文链接：[Improve MongoDB Performance Using Projection](https://medium.com/better-programming/improve-mongodb-performance-using-projection-c08c38334269)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/improve-mongodb-performance-using-projection.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by onlinelei** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@onlinelei 好的！
