### ISSUE TITLE
认领 Making React Native apps accessible

### ISSUE THREAD

**Issue by void-main** [xitu/gold-miner#73]
Hi 我是voidmain，从11年左右就开始做移动开发，自从fb推出了react native就十分关注这项技术，并且跟自己的朋友专门开设了rn学习小组。希望通过翻译这方面的文章帮助更多的朋友了解rn并在工作中用上rn。

之前我做过无障碍(Accessibility)相关的工作

**Comment by Glowin** [comment]
鹏神你好，你来翻译必须给通过！膝盖请收好。
![image](https://cloud.githubusercontent.com/assets/1147941/12005685/da76f448-abed-11e5-9e20-c1011ac34f2e.png)



![Uploading timg.jpg…]()
