### ISSUE TITLE
如何实现交互式 WebGL 悬停效果

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7304]
* 原文链接：[Interactive WebGL Hover Effects](https://tympanus.net/codrops/2020/04/14/interactive-webgl-hover-effects/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/interactive-webgl-hover-effects.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
好的~

**Comment by fanyijihua** [comment]
PR 地址：#7314
