### ISSUE TITLE
TypeScript 4.0 终于发布了我一直在等待的东西

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7306]
* 原文链接：[TypeScript 4.0 finally delivers what I’ve been waiting for](https://medium.com/javascript-in-plain-english/typescript-4-0-i-want-a-list-of-generic-params-with-good-labels-c6087d2df935)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/typescript-4-0-i-want-a-list-of-generic-params-with-good-labels.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rocwong-cn** [comment]
@lsvih 翻译认领

**Comment by fanyijihua** [comment]
@rocwong-cn 棒极啦 :tada:
