### ISSUE TITLE
What to Expect in Python 3.9

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7308]
* 原文链接：[What to Expect in Python 3.9](https://levelup.gitconnected.com/what-to-expect-in-python-3-9-206b486ec2a4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/what-to-expect-in-python-3-9.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by 92hackers** [comment]
@lsvih 翻译认领

**Comment by fanyijihua** [comment]
@92hackers 棒极啦 :tada:

**Comment by lsvih** [comment]
@92hackers 哈罗，请问这篇进度咋样啦~
