### ISSUE TITLE
奋起的 IBM 凭什么成为世界上最大最精致的设计公司？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#731]
* 原文链接：[IBM is gearing up to become the world’s largest and most sophisticated design company](http://qz.com/755741/ibm-is-becoming-the-worlds-largest-design-company/)
* 掘金链接：[奋起的 IBM 凭什么成为世界上最大最精致的设计公司？](http://gold.xitu.io/entry/57de3d09a22b9d0061153661/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/ibm-is-becoming-the-worlds-largest-design-company.md)
* PR 地址：[#755](https://github.com/xitu/gold-miner/pull/755)
* 文章分类：**设计**

----

* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jiaowoyongqi** [comment]
认领

**Comment by sqrthree** [comment]
@jiaowoyongqi 👌
