### ISSUE TITLE
让神经网络变得更小巧以方便部署

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7310]
* 原文链接：[Making Neural Networks Smaller for Better Deployment](https://medium.com/data-from-the-trenches/making-neural-networks-smaller-for-better-deployment-55aa9bf4b795)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/making-neural-networks-smaller-for-better-deployment.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：18 天
* 校对时间：5 天
* 翻译积分：11 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PingHGao** [comment]
翻译认领

**Comment by lsvih** [comment]
@PingHGao 好的！

**Comment by samyu2000** [comment]
@lsvih 校对认领
