### ISSUE TITLE
Creating a Menu Image Animation on Hover

### ISSUE THREAD

**Issue by zenblo** [xitu/gold-miner#7316]
- 原文链接：https://tympanus.net/codrops/2020/07/01/creating-a-menu-image-animation-on-hover/
- 简要介绍：这是前端动画效果方面的优秀文章，我推荐，我想翻译。
---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by zenblo** [comment]
这是前端动画效果方面的优秀文章，我推荐，我想翻译。

**Comment by lsvih** [comment]
#7327 已发布

**Comment by lsvih** [comment]
感谢推荐
