### ISSUE TITLE
Python 的优化 — 驻留机制

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7317]
* 原文链接：[Optimization in Python — Interning](https://towardsdatascience.com/optimization-in-python-interning-805be5e9fd3e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/optimization-in-python-interning.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好的！
