### ISSUE TITLE
为什么用户体验最最最重要？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#732]
* 原文链接：[Why User Experience Always Has to Come First](https://hbr.org/2016/09/why-user-experience-always-has-to-come-first)
* 掘金链接：[[英] 为什么用户体验最最最重要？](http://gold.xitu.io/entry/57de3f5d7db2a24eb1b8bbf1)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/why-user-experience-always-has-to-come-first.md)
* PR 地址：[PR](https://github.com/xitu/gold-miner/pull/738)
* 文章分类：**产品**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
认领!

**Comment by sqrthree** [comment]
@yifili09 好的

**Comment by yifili09** [comment]
@sqrthree 

#738 欢迎小伙伴们前来指导。
