### ISSUE TITLE
世界比以往任何时候都更需要 Web 可访问性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7321]
* 原文链接：[The World Needs Web Accessibility Now More Than Ever](https://levelup.gitconnected.com/the-world-needs-web-accessibility-now-more-than-ever-df8dc4aab2b6)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/the-world-needs-web-accessibility-now-more-than-ever.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tonylua** [comment]
@fanyijihua 可以继续了吧

**Comment by lsvih** [comment]
@tonylua 还差一位校对呢，不急不急，等明天还没有就继续哈

**Comment by wangqinggang** [comment]
@glowin 认领校对

**Comment by wangqinggang** [comment]
@fanyijihua 认领校对

**Comment by lsvih** [comment]
@wangqinggang 不好意思哈= =本文的校对已经完成了，您可以看看别的文章 😃

**Comment by tonylua** [comment]
@lsvih 已更新译文
