### ISSUE TITLE
使用 Chrome 的 Shape Detection API 检测人脸，文本甚至条形码

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7323]
* 原文链接：[Detect Faces, Texts and Even Barcodes With Chrome’s Shape Detection API](https://blog.bitsrc.io/detect-faces-texts-and-even-barcodes-with-chromes-shape-detection-api-34e40c55bb30)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/detect-faces-texts-and-even-barcodes-with-chromes-shape-detection-api.md)
* PR 地址：
* 文章分类：**前端**，**AI**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rocwong-cn** [comment]
@lsvih 翻译认领

**Comment by fanyijihua** [comment]
@rocwong-cn 棒极啦 :tada:
