### ISSUE TITLE
在 iOS 14 中处理位置权限和管理近似地址访问

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7325]
* 原文链接：[Handling Location Permissions in iOS 14](https://medium.com/better-programming/handling-location-permissions-in-ios-14-2cdd411d3cca)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/handling-location-permissions-in-ios-14.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Godlowd** [comment]
翻译认领

**Comment by lsvih** [comment]
@Godlowd 好的！

**Comment by lsvih** [comment]
已发布：https://juejin.cn/post/6944895612001189924
