### ISSUE TITLE
如何在悬停时创建菜单图像动画

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7327]
* 原文链接：[Creating a Menu Image Animation on Hover](https://tympanus.net/codrops/2020/07/01/creating-a-menu-image-animation-on-hover/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/creating-a-menu-image-animation-on-hover.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的~

**Comment by zenblo** [comment]
掘金文章发布链接 https://juejin.im/post/6878561756793454599
