### ISSUE TITLE
用 Cordova 和 Vue.js 构建一个 APP

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#733]
* 原文链接：[Building a Mobile App with Cordova and Vue.js](https://coligo.io/building-a-mobile-app-with-cordova-vuejs/)
* 掘金链接：[用 Cordova 和 Vue.js 构建一个 APP](http://gold.xitu.io/entry/57de419e0bd1d00057f2fe45/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/building-a-mobile-app-with-cordova-vuejs.md)
* PR 地址：[PR](https://github.com/xitu/gold-miner/pull/752)
* 文章分类：**前端**

----

* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by circlelove** [comment]
认领！

**Comment by sqrthree** [comment]
@circlelove 好的

**Comment by circlelove** [comment]
cool 现在有文章进度了

**Comment by sqrthree** [comment]
哈，是你加的么？

**Comment by circlelove** [comment]
不是我。可能是别人做了一半吧。要不然，就我这一个有进度 - - @sqrthree

**Comment by circlelove** [comment]
我也没有权限= =

**Comment by sqrthree** [comment]
😁我昨晚上还纳闷来着，为啥只有一个。 🤔 最后也没想出来答案。
