### ISSUE TITLE
让你的 Web 应用和移动应用选择 PWA 的 5 个理由

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7333]
* 原文链接：[5 Reasons to Choose PWA for Your Web and Mobile Apps](https://blog.bitsrc.io/5-reasons-to-choose-pwa-for-your-web-and-mobile-apps-515c6d0e784d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/5-reasons-to-choose-pwa-for-your-web-and-mobile-apps.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：6 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rocwong-cn** [comment]
@lsvih 翻译认领

**Comment by fanyijihua** [comment]
@rocwong-cn 棒极啦 :tada:

**Comment by scotteau** [comment]
@fanyijihua 校对认领
