### ISSUE TITLE
JavaScript 生成器：何时用 yield，何时用 yield* ？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7339]
* 原文链接：[Generators in JavaScript: When should I use yield, and yield*?](https://medium.com/javascript-in-plain-english/generators-in-javascript-when-should-i-use-yield-and-yield-a5dbea6ad625)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/generators-in-javascript-when-should-i-use-yield-and-yield.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Isildur46** [comment]
翻译认领

**Comment by lsvih** [comment]
@Isildur46 好的~

**Comment by fanyijihua** [comment]
PR 地址：#7350
