### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Tina92** [xitu/gold-miner#734]
你好，我叫Tina92，数字媒体技术专业毕业，现在在润和软件任职前端工程师。具有较好的英语基础，经常访问Github/Stackoverflow/Medium社区，比较习惯使用英文版教程学习前端技术。希望能互相交流学习。

**Comment by antonia0912** [comment]
@Tina92 欢迎来翻译计划玩~请加我微信 antonia0912 备注github ID 我来拉你进译者群
