### ISSUE TITLE
如何利用 Polyfill 和转译在所有浏览器中使用最新 JavaScript 特性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7341]
* 原文链接：[How to use the latest JavaScript features in any browser](https://medium.com/javascript-in-plain-english/use-the-latest-javascript-features-in-any-browser-f047f5c426a8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/use-the-latest-javascript-features-in-any-browser.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MangoTsing** [comment]
@lsvih  翻译认领

**Comment by fanyijihua** [comment]
@MangoTsing 棒极啦 :tada:

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6868513605055643662
