### ISSUE TITLE
React vs. Svelte：虚拟与真实 DOM 间的战争

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7345]
* 原文链接：[React vs. Svelte: The War Between Virtual and Real DOM](https://blog.bitsrc.io/react-vs-sveltejs-the-war-between-virtual-and-real-dom-59cbebbab9e9)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/react-vs-sveltejs-the-war-between-virtual-and-real-dom.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nia3y** [comment]
翻译认领@fanyijihua

**Comment by fanyijihua** [comment]
@nia3y 棒极啦 :tada:
