### ISSUE TITLE
颜色为何成为数据可视化的关键，怎样使用它？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7347]
* 原文链接：[Why Color Is Key for Data Visualization and How to Use It](https://towardsdatascience.com/why-color-is-key-for-data-visualization-and-how-to-use-it-b24627116b71)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/why-color-is-key-for-data-visualization-and-how-to-use-it.md)
* PR 地址：
* 文章分类：**设计**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by snow1991bloom** [comment]
@lsvih 翻译认领

**Comment by fanyijihua** [comment]
@snow1991bloom 棒极啦 :tada:
