### ISSUE TITLE
减少认知超载能够给用户带来更好的用户体验

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#736]
* 原文链接：[Reducing Cognitive Overload For A Better User Experience](https://www.smashingmagazine.com/2016/09/reducing-cognitive-overload-for-a-better-user-experience/)
* 掘金链接：[[英] 减少认知超载能够给用户带来更好的用户体验](http://gold.xitu.io/entry/57de3b650bd1d00057f2c9a2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/reducing-cognitive-overload-for-a-better-user-experience.md)
* PR 地址：[#785](https://github.com/xitu/gold-miner/pull/785)
* 文章分类：**产品**

----
* 翻译时间：`5` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DeadLion** [comment]
认领

**Comment by sqrthree** [comment]
@DeadLion 好哒，顺便填下这个哈 [wiki](https://github.com/xitu/gold-miner/wiki/译者擅长领域表)

**Comment by DeadLion** [comment]
@sqrthree  这篇文章没时间翻译啦，重新安排下吧。

**Comment by Ruixi** [comment]
我我我！

**Comment by sqrthree** [comment]
@Ruixi 好的

**Comment by sqrthree** [comment]
@Ruixi 进度如何了呀

**Comment by Ruixi** [comment]
@sqrthree 今天才看见😂
