### ISSUE TITLE
Python 定义函数的 5 种参数

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7362]
* 原文链接：[5 Types of Arguments in Python Function Definition](https://levelup.gitconnected.com/5-types-of-arguments-in-python-function-definition-e0e2a2cafd29)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/5-types-of-arguments-in-python-function-definition.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zhengjian-L** [comment]
@lsvih 翻译认领

**Comment by Zhengjian-L** [comment]
@fanyijihua 翻译认领

**Comment by lsvih** [comment]
@Zhengjian-L 好的！
