### ISSUE TITLE
加速 vue.js 应用的六种绝技

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7364]
* 原文链接：[6 Ways to Speed Up Your Vue.js Application](https://medium.com/better-programming/6-ways-to-speed-up-your-vue-js-application-2673a6f1cde4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/6-ways-to-speed-up-your-vue-js-application.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MangoTsing** [comment]
翻译认领

**Comment by lsvih** [comment]
@MangoTsing 好的~

**Comment by lsvih** [comment]
https://juejin.im/post/6870808442911588365 已发布
