### ISSUE TITLE
使用 Rust 构建单页应用

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7368]
* 原文链接：[Single Page Applications using Rust](http://www.sheshbabu.com/posts/rust-wasm-yew-single-page-application/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/rust-wasm-yew-single-page-application.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：18 天
* 校对时间：5 天
* 翻译积分：11 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
> 推荐理由：前端/后端语言 Rust （前后端都能使用的语言） 实现的 SPA 应用。Rust 本是后端语言，但由于可以通过工具它能将代码编译为 WebAssembly，从而可以用 Rust 实现前端的应用。通过具体的示例分享，给前后端开发者带来了很大的想象空间。未来也许前后端的界限会变得越来越模糊。

**Comment by lsvih** [comment]
> 摘要：网页汇编（WebAssembly）是常见的网页编程方式，十分之九以上的浏览器都支持它。本篇文章里，作者尝试搭建只有一个网页、一两行JavaScript代码的网页应用。这样的应用应该只在一个页面里加载内容，就可以访问多个模块，而不需要页面刷新，能复用多个网页的用户交互模块，还能同时更新不同层次的用户页面。作者给了出这种前提下的设计方法，还提供一个设计好的网购网站作为例子。
完成整个开发流程，需要安装Rust和它与网页汇编相关的工具链。文章挑选了Rust语言的yew项目作为开发框架，将网购的商品、购物车、交互信息等等都抽象成Rust语言的结构体和枚举类型，最终完成开发目的。每次用户交互，都会通过一个特殊的“生命圈”方法传给状态机，最终状态机将重新绘制用户界面，达到更新用户界面的目的——比如按下加入购物车的按钮，侧边栏的总价信息将会相应改变。
本篇文章的开发方法中，初始化部分的信息也是由接口提供的。后端服务将访问后续的结构，得到所有的信息，通过应用程序接口和消息结构返回，如果出错也会给出错误的类型。不同的页面之间通过层次结构相互关联，但不同层次的结构共同维护一个全局状态存储空间，以给出数据同步的解决方案。在文章的例子里，所有页面共享同一个购物车内容，这是通过全局状态实现的。状态还可以提升到不同的层级，比如提高侧边栏页面的状态，我们就能在所有页面同时显示一个相同、统一的侧边栏。
文章使用了yew社区提供的大量方便的抽象设计，这和Rust语言灵活的宏系统是分不开的。虽然文章给出的设计方法仍有一定提升空间，作者也在探究问题的解决方案，他希望将来这能作为流行的Vue、React等网页设计框架的替代品。

**Comment by DerekDick** [comment]
@lsvih 认领翻译

**Comment by juu574** [comment]
@lsvih 校对认领
