### ISSUE TITLE
我的网站加载时间不到 1 秒，这是我如何做到的！

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7372]
* 原文链接：[My website now loads in less than 1 sec! Here's how I did it! ⚡](https://dev.to/cmcodes/my-website-now-loads-in-less-than-2-sec-here-s-how-i-did-it-hoj)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/my-website-now-loads-in-less-than-2-sec-here-s-how-i-did-it-hoj.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wangqinggang** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@wangqinggang 好的~

**Comment by wangqinggang** [comment]
@lsvih 翻译完成 请求校对

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6870329885034807310
