### ISSUE TITLE
如何处理 JavaScript 比较中的临界情况

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7374]
* 原文链接：[How to handle JavaScript comparison corner cases](https://medium.com/javascript-in-plain-english/how-to-handle-comparison-corner-cases-c96ae9a17d4a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-to-handle-comparison-corner-cases.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tonylua** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@tonylua 好的！

**Comment by tonylua** [comment]
https://github.com/xitu/gold-miner/pull/7388 翻译完成 @lsvih

**Comment by tonylua** [comment]
认可校对结果 @lsvih

**Comment by tonylua** [comment]
@lsvih 已更新译文

**Comment by lsvih** [comment]
@tonylua 您再确认一下= =这几篇都还没找到您的提交

**Comment by tonylua** [comment]
@lsvih 30310e39b6f3b198d75469a39089be0f0dbbad80 在这次提交里
