### ISSUE TITLE
如何利用潜在因素模型在图形数据库中建立推荐系统

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7379]
* 原文链接：[How to build a recommendation system in a graph database using a latent factor model](https://towardsdatascience.com/how-to-build-a-recommendation-system-in-a-graph-database-using-a-latent-factor-model-fa2d142f874)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-to-build-a-recommendation-system-in-a-graph-database-using-a-latent-factor-model.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：20 天
* 校对时间：4 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by todaycoder001** [comment]
翻译认领

**Comment by lsvih** [comment]
@todaycoder001 好的~

**Comment by todaycoder001** [comment]
最近有点忙，这篇文章有点拖沓，预计这周末能翻译完，抱歉。

**Comment by lsvih** [comment]
@todaycoder001 辛苦啦，这篇挺难翻的

**Comment by TrWestdoor** [comment]
预定一个校对位置：）

**Comment by todaycoder001** [comment]
> 预定一个校对位置：）

好哒，这篇拖了很久，这两天应该就可以发出来了。
