### ISSUE TITLE
JavaScript 函数中一些你不知道的秘密

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7381]
* 原文链接：[Function in JavaScript Has Much More Secrets Than You Think](https://medium.com/javascript-in-plain-english/function-in-javascript-has-much-more-secrets-than-you-think-b3bf64055c99)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/function-in-javascript-has-much-more-secrets-than-you-think.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Isildur46** [comment]
翻译认领

**Comment by lsvih** [comment]
@Isildur46 好的~
