### ISSUE TITLE
Python logging 使用指南

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7394]
* 原文链接：[Tutorial on Python Logging](https://levelup.gitconnected.com/tutorial-on-python-logging-ac5f21e0a00)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/tutorial-on-python-logging.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
翻译认领

**Comment by lsvih** [comment]
@samyu2000 好的~

**Comment by wangqinggang** [comment]
@lsvih @samyu2000 校对认领

**Comment by lsvih** [comment]
@wangqinggang 请在 #7424 里面认领哈~
