### ISSUE TITLE
使用 JSON.stringify 处理 JavaScript 对象

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7396]
* 原文链接：[Using JSON.stringify to Work with JavaScript Object](https://levelup.gitconnected.com/using-json-stringify-to-work-with-javascript-object-9416c1e2c7c4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/using-json-stringify-to-work-with-javascript-object.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Inchill** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@Inchill 好的~

**Comment by Inchill** [comment]
@lsvih 翻译完成，请求校对

**Comment by Inchill** [comment]
@lsvih 翻译完成[#7401](https://github.com/xitu/gold-miner/pull/7401)
