### ISSUE TITLE
Golang 切片综合指南

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7398]
* 原文链接：[A Comprehensive Guide to Slices in Golang](https://codeburst.io/a-comprehensive-guide-to-slices-in-golang-bacebfe46669)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/a-comprehensive-guide-to-slices-in-golang.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：14 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JalanJiang** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@JalanJiang 好的！
