### ISSUE TITLE
VueJS 中更好的组件组合方式

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7403]
* 原文链接：[Better Component Composition in VueJS](https://itnext.io/better-composition-in-vue-fd35b9fe9c79)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/better-composition-in-vue.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tonylua** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@tonylua 好的~

**Comment by tonylua** [comment]
https://github.com/xitu/gold-miner/pull/7423 翻译完成 @lsvih

**Comment by dupanpan** [comment]
校对认领 @lsvih
