### ISSUE TITLE
探索 Android 中的 ConstraintLayout 2.0

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7405]
* 原文链接：[Exploring ConstraintLayout 2.0 in Android](https://medium.com/better-programming/exploring-constraintlayout-2-0-in-android-317584003ee9)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/exploring-constraintlayout-2-0-in-android.md)
* PR 地址：
* 文章分类：**Android**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by keepmovingljzy** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@keepmovingljzy 好的~
