### ISSUE TITLE
爱 GraphQL 胜过 REST

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7407]
* 原文链接：[Loving GraphQL More than REST](https://medium.com/javascript-in-plain-english/loving-graphql-more-than-rest-4e213c568635)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/loving-graphql-more-than-rest.md)
* PR 地址：
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by noahziheng** [comment]
@fanyijihua 翻译认领

**Comment by NieZhuZhu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@NieZhuZhu 好的~
