### ISSUE TITLE
Swift 3 中的函数命名规范指南

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#741]
* 原文链接：[Function Naming In Swift 3](http://inaka.net/blog/2016/09/16/function-naming-in-swift-3/)
* 掘金链接：[[英] Swift 3 中的函数命名规范指南](http://gold.xitu.io/entry/57e14f1167f3560056bcdd6f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/function-naming-in-swift-3.md)
* PR 地址：[#761](https://github.com/xitu/gold-miner/pull/761)
* 文章分类：**iOS**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zheaoli** [comment]
收

**Comment by sqrthree** [comment]
@Zheaoli 妥妥哒

**Comment by sqrthree** [comment]
@Zheaoli 我对照原文修改了一下 md 文件的代码，你翻译的时候先同步一下掘金的仓库哈

**Comment by Zheaoli** [comment]
@sqrthree [校对地址](https://github.com/xitu/gold-miner/pull/761/files)
