### ISSUE TITLE
5 个鲜为人知的 Chrome 开发工具的特性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7410]
* 原文链接：[5 lesser-known features of Chrome Devtools](https://levelup.gitconnected.com/5-lesser-known-features-of-chrome-devtools-1ff3cd2a7518)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/5-lesser-known-features-of-chrome-devtools.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：1 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Amy-Designer** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Amy-Designer 好的！

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6875240551390642189
