### ISSUE TITLE
前端应用的性能指标

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7413]
* 原文链接：[Performance Metrics for Front-End Applications](https://blog.bitsrc.io/performance-metrics-for-front-end-applications-a04fdfde217a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/performance-metrics-for-front-end-applications.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：14 天
* 校对时间：4 天
* 翻译积分：8.5 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nia3y** [comment]
翻译认领 @lsvih @fanyijihua

**Comment by lsvih** [comment]
@nia3y 好的~

**Comment by zenblo** [comment]
@lsvih @nia3y 这篇文章搁置的有点久，我想认领翻译

**Comment by nia3y** [comment]
抱歉，文章晚点 push，最近在准备面试，差点忘记了😱

zenblo <notifications@github.com> 于2020年10月9日周五 上午9:30写道：

**Comment by lsvih** [comment]
@zenblo hh等译者上传了欢迎校对哈

**Comment by HurryOwen** [comment]
校对认领 @lsvih
