### ISSUE TITLE
NextJS vs. NuxtJS vs. GatsbyJS

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7414]
* 原文链接：[NextJS vs. NuxtJS vs. GatsbyJS](https://medium.com/better-programming/nextjs-vs-nuxtjs-vs-gatsbyjs-1a1fffb8895b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by z0gSh1u** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@z0gSh1u 好的~
