### ISSUE TITLE
使用 React 和 localStorage 实现的简易 Dark Mode 开关

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7417]
* 原文链接：[Easy Dark Mode Switch with React and localStorage](https://dev.to/alekswritescode/easy-dark-mode-switch-with-react-and-localstorage-3k6d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/easy-dark-mode-switch-with-react-and-localstorage-3k6d.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Inchill** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Inchill 好的！

**Comment by Inchill** [comment]
@lsvih 翻译完成

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6875538309934743560
