### ISSUE TITLE
[英] 迁移到 Swift 3，这些陷阱在等你

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#742]
* 原文链接：[Swift 3 migration pitfalls](http://codelle.com/blog/2016/9/swift-3-migration-pitfalls/)
* 掘金链接：[[英] 迁移到 Swift 3，这些陷阱在等你](http://gold.xitu.io/entry/57e14f920bd1d0005705c71c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/swift-3-migration-pitfalls.md)
* PR 地址：[#760](https://github.com/xitu/gold-miner/pull/760)
* 文章分类：**iOS**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shliujing** [comment]
只校队了一次，可以认领么~@sqrthree

**Comment by sqrthree** [comment]
@shliujing 可以的，记得到 [wiki](https://github.com/xitu/gold-miner/wiki/译者擅长领域表) 填下自己的信息哈

**Comment by sqrthree** [comment]
@shliujing 更正了下译文中的部分代码，你如果已经 Fork 过的话，记得先同步下掘金的仓库哈

**Comment by shliujing** [comment]
@sqrthree 好的，谢谢提醒。

**Comment by sqrthree** [comment]
@Tina92 Of course.
