### ISSUE TITLE
抽象数据类型 ADT 与软件危机

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7421]
* 原文链接：[Abstract Data Types and the Software Crisis](https://medium.com/javascript-scene/abstract-data-types-and-the-software-crisis-671ea7fc72e7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/abstract-data-types-and-the-software-crisis.md)
* PR 地址：
* 文章分类：**前端**，**系列任务**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：14 天
* 校对时间：5 天
* 翻译积分：10 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译请参考 #6805 中的各个文章。

本文翻译完成后会收录与编辑到《组合软件系列》合集和

**Comment by Shirley-He-Maker** [comment]
@lsvih 翻译认领！

**Comment by lsvih** [comment]
@Shirley-He-Maker 好的~

**Comment by Shirley-He-Maker** [comment]
@lsvih 不好意思，国庆假临时有事情，翻译工作可能没办法进行了，请问可以申请取消翻译吗？

**Comment by lsvih** [comment]
@Shirley-He-Maker 没问题

**Comment by zenblo** [comment]
@lsvih 翻译认领！

**Comment by lsvih** [comment]
@zenblo 好的~
