### ISSUE TITLE
让你的应用支持 iOS 10 系统扩展

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#743]
* 原文链接：[Preparing Your iOS App for Extensions](https://www.raizlabs.com/dev/2016/09/preparing-ios-app-for-extensions/)
* 掘金链接：[[英] 让你的应用支持 iOS 10 系统扩展](http://gold.xitu.io/entry/57e1516679bc44610a4c8e4e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/preparing-ios-app-for-extensions.md)
* PR 地址：[PR](https://github.com/xitu/gold-miner/pull/757)
* 文章分类：**iOS**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xuxiaokang** [comment]
文章认领

**Comment by sqrthree** [comment]
@xuxiaokang 新译者要从校对文章开始哟~ 具体的你可以看一下这个 [如何参与翻译](https://github.com/xitu/gold-miner#如何参与翻译)，顺便到 [wiki](https://github.com/xitu/gold-miner/wiki/译者擅长领域表) 中修改下自己擅长的分类撒

**Comment by jiakeqi** [comment]
文章认领

**Comment by jiakeqi** [comment]
嗷嗷嗷 翻译过 校对过

**Comment by sqrthree** [comment]
@jiakeqi 好哒

**Comment by jiakeqi** [comment]
@sqrthree http://gold.xitu.io/entry/57eb20592e958a005457e038/detail 积分没有增加啊 = =

**Comment by sqrthree** [comment]
@jiakeqi 稍后给你添加哈
