### ISSUE TITLE
Python 模拟动力系统的初学者指南

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7432]
* 原文链接：[A Beginner’s Guide to Simulating Dynamical Systems with Python](https://towardsdatascience.com/a-beginners-guide-to-simulating-dynamical-systems-with-python-a29bc27ad9b1)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/a-beginners-guide-to-simulating-dynamical-systems-with-python.md)
* PR 地址：
* 文章分类：**算法**，**其他**
* **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
----
* 翻译时间：14 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnieXu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@JohnieXu 好的~
