### ISSUE TITLE
使用 Node.js 实现蒙特卡洛树搜索

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7434]
* 原文链接：[Implementing Monte Carlo Tree Search in Node.js](https://medium.com/@quasimik/implementing-monte-carlo-tree-search-in-node-js-5f07595104df)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/implementing-monte-carlo-tree-search-in-node-js.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：30 天
* 校对时间：7 天
* 翻译积分：12 分
* 校对积分：6 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnieXu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@JohnieXu 好的！

**Comment by zenblo** [comment]
@lsvih @JohnieXu 好久没动静，我想接过来翻译

**Comment by lsvih** [comment]
@zenblo 好的
