### ISSUE TITLE
ES2017 最佳特性  —  数组中的异步函数以及共享缓冲

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7436]
* 原文链接：[Best Features of ES2017 — Async Functions and Arrays and Shared Buffers](https://medium.com/javascript-in-plain-english/best-features-of-es2017-async-functions-and-arrays-and-shared-buffers-74dace23aa59)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/best-features-of-es2017-async-functions-and-arrays-and-shared-buffers.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tonylua** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@tonylua 好的！

**Comment by tonylua** [comment]
https://github.com/xitu/gold-miner/pull/7451 @lsvih
