### ISSUE TITLE
为什么要让你的代码尽可能简单

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7438]
* 原文链接：[Why You Should Make Your Code as Simple as Possible](https://medium.com/better-programming/why-you-should-make-your-code-as-simple-as-possible-3b35e89f137)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/why-you-should-make-your-code-as-simple-as-possible.md)
* PR 地址：
* 文章分类：**前端**，**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：14 天
* 校对时间：4 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CaptainWang98** [comment]
翻译认领

**Comment by lsvih** [comment]
@CaptainWang98 好的~

**Comment by NieZhuZhu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@NieZhuZhu 好的~
