### ISSUE TITLE
[英] 使用'currentColor' 属性写出更好的 CSS 代码

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#744]
* 原文链接：[Writing better CSS with currentColor](https://hashnode.com/post/writing-better-css-with-currentcolor-cit5mgva31co79c53ia20vetq)
* 掘金链接：[[英] 使用'currentColor' 属性写出更好的 CSS 代码](http://gold.xitu.io/entry/57e152b60bd1d0005705de77)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/writing-better-css-with-currentcolor.md)
* PR 地址：[#758](https://github.com/xitu/gold-miner/pull/758)
* 文章分类：**前端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yangzj1992** [comment]
文章认领

**Comment by sqrthree** [comment]
@yangzj1992 好哒
