### ISSUE TITLE
在 Swift 中玩转 emoji

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7440]
* 原文链接：[Working With Emoji in Swift](https://medium.com/better-programming/working-with-emoji-in-swift-f76118e6b6d6)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/working-with-emoji-in-swift.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lcx-seima** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@lcx-seima 好的~
