### ISSUE TITLE
TypeScript：一个好泛型的价值

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7442]
* 原文链接：[TypeScript: The Value of a Good Generic](https://blog.bitsrc.io/typescript-the-value-of-a-good-generic-bfd820d52995)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/typescript-the-value-of-a-good-generic.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tonylua** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@tonylua 好的！

**Comment by tonylua** [comment]
https://github.com/xitu/gold-miner/pull/7453 @lsvih 翻译完成

**Comment by lsvih** [comment]
这也太快了！

**Comment by tonylua** [comment]
> 这也太快了！

节前大放送
