### ISSUE TITLE
掌握 JavaScript ES6 中的 Symbol 类型

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7444]
* 原文链接：[Mastering JavaScript ES6 Symbols](https://blog.bitsrc.io/mastering-javascript-es6-symbols-6453da3bd46c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/mastering-javascript-es6-symbols.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：16 天
* 校对时间：4 天
* 翻译积分：9 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Inchill** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Inchill 好的！加油这篇还挺长的

**Comment by Inchill** [comment]
@lsvih @Glowin 翻译完成

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6880485630501978126
