### ISSUE TITLE
微服务是你的最佳解决方案么？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7446]
* 原文链接：[Microservices: The Right Solution for You?](https://blog.bitsrc.io/microservices-the-right-solution-for-you-869e916ded09)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/microservices-the-right-solution-for-you.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wangqinggang** [comment]
@lsvih  翻译认领

**Comment by lsvih** [comment]
@wangqinggang 好的~

**Comment by wangqinggang** [comment]
@lsvih 翻译完成  请求校对  想尽快参加国庆的活动 哈哈
