### ISSUE TITLE
Blitz.js 简介

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7448]
* 原文链接：[Introduction to Blitz.js](https://blog.bitsrc.io/introduction-to-blitz-js-ff1e48ea5714)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/introduction-to-blitz-js.md)
* PR 地址：
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：13 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by plusmultiply0** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@plusmultiply0 好的！

**Comment by plusmultiply0** [comment]
@lsvih 文章已发布，麻烦更改下状态和积分
链接：https://juejin.im/post/6887201657801670669/ | https://github.com/xitu/gold-miner/pull/7464#issuecomment-715927491

**Comment by plusmultiply0** [comment]
另外，请看一下[这里](https://github.com/xitu/gold-miner/issues/7413)。文章好像也已经发布了，麻烦您也顺便更新下issue状态和积分:smile:

**Comment by lsvih** [comment]
@plusmultiply0 收到~
