### ISSUE TITLE
哪个跨平台框架才是最好的选择？React Native、Flutter 还是 Ionic。

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7450]
* 原文链接：[React Native vs. Flutter vs. Ionic](https://medium.com/better-programming/react-native-vs-flutter-vs-ionic-46d3350f96ee)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/react-native-vs-flutter-vs-ionic.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：18 天
* 校对时间：5 天
* 翻译积分：10 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MangoTsing** [comment]
翻译认领

**Comment by lsvih** [comment]
@MangoTsing 好的！

**Comment by HurryOwen** [comment]
校对认领 @lsvih

**Comment by lsvih** [comment]
@HurryOwen 好的~下会儿记得在 pr 里面认领哈！

**Comment by lsvih** [comment]
已发布：https://juejin.cn/post/6884099570435883022
