### ISSUE TITLE
MVC、MVP、MVVM 对比

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7456]
* 原文链接：[MVC vs MVP vs MVVM](https://levelup.gitconnected.com/mvc-vs-mvp-vs-mvvm-35e0d4b933b4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/mvc-vs-mvp-vs-mvvm.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by snowyYU** [comment]
翻译认领

**Comment by lsvih** [comment]
@snowyYU 好的！
