### ISSUE TITLE
通过“四不要”掌握 Python 中的 Lambda 函数

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7458]
* 原文链接：[Master Python Lambda Functions With These 4 Don’ts](https://medium.com/better-programming/master-python-lambda-functions-with-these-4-donts-655b212d36d7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/master-python-lambda-functions-with-these-4-donts.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by loststar** [comment]
@lsvih 翻译认领
第一次尝试翻译可能不会很熟练🍻

**Comment by lsvih** [comment]
@loststar 好的~加油！

**Comment by loststar** [comment]
@lsvih 翻译完成
