### ISSUE TITLE
WebAssembly 及其 JavaScript API 的完整介绍

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7461]
* 原文链接：[A Complete Introduction to WebAssembly and It’s JavaScript API](https://blog.bitsrc.io/a-complete-introduction-to-webassembly-and-its-javascript-api-3474a9845206)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/a-complete-introduction-to-webassembly-and-its-javascript-api.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：14 天
* 校对时间：4 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by weibinzhu** [comment]
翻译认领

**Comment by lsvih** [comment]
@weibinzhu 好的~

**Comment by weibinzhu** [comment]
> @weibinzhu 好的~

不好意思，临时忙了起来，可以换另外的人来翻译吗

**Comment by lsvih** [comment]
@weibinzhu 行

**Comment by JohnieXu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@JohnieXu 好的！
