### ISSUE TITLE
基于内容安全策略增强 JavaScript 安全性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7467]
* 原文链接：[Enhance JavaScript Security with Content Security Policies](https://blog.bitsrc.io/enhance-javascript-security-with-content-security-policies-5847e5def227)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/enhance-javascript-security-with-content-security-policies.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的！

**Comment by zenblo** [comment]
@lsvih 译文翻译完成

**Comment by HurryOwen** [comment]
校对认领 @lsvih

**Comment by beipiaoyu2011** [comment]
@lsvih 校对认领

**Comment by lsvih** [comment]
@beipiaoyu2011 好的~

**Comment by lsvih** [comment]
@beipiaoyu2011 请到 #7474 里面校对哈

**Comment by zenblo** [comment]
掘金文章地址   https://juejin.im/post/6885887317609807886
