### ISSUE TITLE
用 Python 完成猎词游戏：字典树

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7468]
* 原文链接：[Solving Word Hunt in Python: The Trie](https://codeburst.io/solving-word-hunt-in-python-the-trie-9acedc1f2637)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/solving-word-hunt-in-python-the-trie.md)
* PR 地址：
* 文章分类：**算法**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TrWestdoor** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@TrWestdoor 好的！

**Comment by Lvyaqian123** [comment]
https://juejin.cn/post/7109305485483835428   已在掘金发布

**Comment by lsvih** [comment]
收到
