### ISSUE TITLE
在 React 中使用 Service Worker

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7470]
* 原文链接：[Using Service Workers with React](https://blog.bitsrc.io/using-service-workers-with-react-27a4c5e2d1a9)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/using-service-workers-with-react.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by plusmultiply0** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@plusmultiply0 好的~

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6881616183158636552
