### ISSUE TITLE
如何基于 D3.js 使用外部数据源创建图表

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7483]
* 原文链接：[How to Create Charts from External Data Sources with D3.js](https://blog.bitsrc.io/how-to-create-charts-from-external-data-sources-with-d3-js-4abbcb574706)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-to-create-charts-from-external-data-sources-with-d3-js.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：3 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Alfxjx** [comment]
翻译认领~

**Comment by lsvih** [comment]
@Alfxjx 好的~

**Comment by qq1037305420** [comment]
校对认领

**Comment by itcodes** [comment]
@lsvih https://juejin.cn/post/6931294639609774087

**Comment by lsvih** [comment]
好嘞
