### ISSUE TITLE
用 JavaScript 实现堆

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7486]
* 原文链接：[Implementing Heaps in JavaScript](https://blog.bitsrc.io/implementing-heaps-in-javascript-c3fbf1cb2e65)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/implementing-heaps-in-javascript.md)
* PR 地址：
* 文章分类：**前端**，**算法**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：14 天
* 校对时间：4 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
可参考 https://juejin.im/post/6854573210761003022

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by HurryOwen** [comment]
认领翻译

**Comment by HurryOwen** [comment]
认领翻译 @lsvih

**Comment by lsvih** [comment]
@HurryOwen 好的！
