### ISSUE TITLE
单页应用程序的哈希 URL 与普通 URL

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7488]
* 原文链接：[Using Hashed vs. Non-Hashed URL Paths in Single Page Apps](https://blog.bitsrc.io/using-hashed-vs-nonhashed-url-paths-in-single-page-apps-a66234cefc96)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/using-hashed-vs-nonhashed-url-paths-in-single-page-apps.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的~

**Comment by zenblo** [comment]
@lsvih 译文翻译完成
