### ISSUE TITLE
大数据：简述 Lambda 架构

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7490]
* 原文链接：[Big Data: Lambda Architecture in a nutshell](https://levelup.gitconnected.com/big-data-lambda-architecture-in-a-nutshell-fd5e04b12acc)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/big-data-lambda-architecture-in-a-nutshell.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jackwener** [comment]
认领翻译
最近正好在读《streaming system》，看到相关内容的，想尝试翻译

**Comment by lsvih** [comment]
@jackwener 好的！
