### ISSUE TITLE
Express vs. http - API 基准测试

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7492]
* 原文链接：[I built the same API with & without Express. Here are the differences.](https://medium.com/javascript-in-plain-english/i-built-the-same-api-with-without-express-here-are-the-differences-83bbeb7ddad)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/i-built-the-same-api-with-without-express-here-are-the-differences.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lhd951220** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@lhd951220 好的~
