### ISSUE TITLE
Python List 使用注意事项

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7501]
* 原文链接：[The Do’s and Don’ts of Python List Comprehension](https://medium.com/better-programming/the-dos-and-don-ts-of-python-list-comprehension-5cd0f5d18500)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/the-dos-and-don-ts-of-python-list-comprehension.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好的！

**Comment by samyu2000** [comment]
@lsvih 翻译完成

**Comment by lsvih** [comment]
@samyu2000 您好像还没有开 PR 😆
