### ISSUE TITLE
UIKit 和 SwiftUI：我该选择哪一个运用在实际产品开发中？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7504]
* 原文链接：[UIKit or SwiftUI: Which Should You Use in Production?](https://medium.com/better-programming/uikit-or-swiftui-which-should-you-use-in-production-f57258bc6ad5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/uikit-or-swiftui-which-should-you-use-in-production.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：15 天
* 校对时间：5 天
* 翻译积分：9 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Godlowd** [comment]
翻译认领

**Comment by lsvih** [comment]
@Godlowd 好的！

**Comment by PassionPenguin** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@PassionPenguin 好的~
