### ISSUE TITLE
使用原生 CSS 实现自适应视频

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7506]
* 原文链接：[Adaptive video with CSS Math](https://medium.com/@yokselzok/adaptive-video-with-css-math-d71640c6068a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/adaptive-video-with-css-math.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：1 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 原文的标题好像还有内容

**Comment by lsvih** [comment]
@zenblo 改啦

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by kikooo** [comment]
翻译认领

**Comment by lsvih** [comment]
@kikooo 好的！

**Comment by zenblo** [comment]
@lsvih 好久没有动静，我接过来翻译吧
