### ISSUE TITLE
给初学者的示例：什么是 WSGI？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7511]
* 原文链接：[DemoForBeginner: What is WSGI?](https://levelup.gitconnected.com/demoforbeginner-what-is-wsgi-ac3c2a67089)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/demoforbeginner-what-is-wsgi.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JalanJiang** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@JalanJiang 好的！
