### ISSUE TITLE
Web Locks API：跨 Tab 资源同步

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7513]
* 原文链接：[Web Locks API: Cross-Tab Resource Synchronization](https://blog.bitsrc.io/web-locks-api-cross-tab-resource-synchronization-54326e079756)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/web-locks-api-cross-tab-resource-synchronization.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：14 天
* 校对时间：4 天
* 翻译积分：9 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Raoul1996** [comment]
翻译认领

**Comment by lsvih** [comment]
@Raoul1996 好的~

**Comment by Raoul1996** [comment]
https://juejin.im/post/6895792867080405005/
