### ISSUE TITLE
机器学习系统设计相关面试问题的剖析

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7515]
* 原文链接：[The Anatomy of a Machine Learning System Design Interview Question](https://medium.com/better-programming/the-anatomy-of-a-machine-learning-system-design-interview-question-1d9a1a5d23e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/the-anatomy-of-a-machine-learning-system-design-interview-question.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：15 天
* 校对时间：4 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by caiyundong** [comment]
@Isvih 翻译认领

**Comment by lsvih** [comment]
@caiyundong 好的~

**Comment by Lvyaqian123** [comment]
https://juejin.cn/post/7109306303285051406/   已在掘金发布

**Comment by lsvih** [comment]
收到
