### ISSUE TITLE
使用 clamp() 进行响应式设计

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7517]
* 原文链接：[clamp() for Responsive Design](https://calebhearth.com/clamp-for-responsive-design)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/clamp-for-responsive-design.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Alfxjx** [comment]
翻译认领

**Comment by lsvih** [comment]
@Alfxjx 好的！

**Comment by lsvih** [comment]
https://juejin.cn/post/6890830054134611976 已发布
