### ISSUE TITLE
只使用 CSS 进行用户追踪

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7525]
* 原文链接：[User-Tracking With CSS Only](https://medium.com/javascript-in-plain-english/tracking-with-css-ec98e3d81046)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/user-tracking-with-css-only.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MangoTsing** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@MangoTsing 好的~

**Comment by lsvih** [comment]
已发布：https://juejin.cn/post/6887478219662950414
