### ISSUE TITLE
Python 开发垃圾邮件检测应用

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7527]
* 原文链接：[Email Spam Detector in Python](https://medium.com/python-in-plain-english/example-of-a-machine-learning-algorithm-to-predict-spam-emails-in-python-76addb1514d1)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/example-of-a-machine-learning-algorithm-to-predict-spam-emails-in-python.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnieXu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@JohnieXu 好的！
