### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by qianxiaoai** [xitu/gold-miner#753]
你好！我叫qianxiaoai，安徽财经大学，现在在宝宝树担任Android开发工程师。具有较好的英语水平，经常访问Github/Stackoverflow/Android官网等。我的博客是http://lovexiaoai.cn/ ，经常阅读技术型英文博客，文档，暂时还没有翻译经验。希望加入翻译计划，互相学习！

**Comment by antonia0912** [comment]
@qianxiaoai 欢迎来到翻译计划 请加我微信 antonia0912 备注 github ID 我来拉你进译者群
