### ISSUE TITLE
迪米特法则

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7530]
* 原文链接：[The Law of Demeter](https://levelup.gitconnected.com/the-law-of-demeter-4bd40aa21cbe)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/the-law-of-demeter.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好的！

**Comment by lsvih** [comment]
已发布：https://juejin.im/post/6890050952049950733
