### ISSUE TITLE
设计模式：设计类和对象的结构性模式

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7531]
* 原文链接：[Design Patterns: Structural Patterns of Design Classes and Objects](https://levelup.gitconnected.com/design-patterns-structural-patterns-of-design-classes-and-objects-79d58a6519b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/design-patterns-structural-patterns-of-design-classes-and-objects.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：19 天
* 校对时间：4 天
* 翻译积分：9 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lhd951220** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@lhd951220 好的！
