### ISSUE TITLE
使用原生 CSS 设置“响应式”字体

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7536]
* 原文链接：[“Responsive” Font-Size Using Vanilla CSS](https://levelup.gitconnected.com/responsive-font-size-using-vanilla-css-51f81fe999db)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/responsive-font-size-using-vanilla-css.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的

**Comment by zenblo** [comment]
@lsvih 翻译完成，但是提交的时候带上了多余的东西，那些不知道怎么清除删掉？
