### ISSUE TITLE
JavaScript 颜色处理库 Chroma.js 的应用

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7538]
* 原文链接：[Color Scales in JavaScript with Chroma.js](https://levelup.gitconnected.com/color-scales-in-javascript-with-chroma-js-b9f59d2a68d7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/color-scales-in-javascript-with-chroma-js.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：1 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的~

**Comment by zenblo** [comment]
@lsvih 翻译完成

**Comment by lsvih** [comment]
🤦 您又提交了三个文件..

**Comment by zenblo** [comment]
8 好意思，就是提交的时候要怎么做调整呀？我不是用Git命令弄的[(lll￢ω￢)]

**Comment by lsvih** [comment]
没事，我处理了，您的操作时是的= = 回头另外几个 merge 就不会有这么多文章了

**Comment by zenblo** [comment]
掘金文章地址  https://juejin.im/post/6886263418907688974
