### ISSUE TITLE
申请译者

### ISSUE THREAD

**Issue by bbmovistar** [xitu/gold-miner#754]
您好，我是bbmovistar。应用心理学专业，现在在浙江万航任职前端开发工程师。英语6级，经常阅读英文专业论文以及技术型的博客、文档和书籍。常浏览的网站有GitHub/Stackoverflow/MDN等，希望能加入掘金翻译计划，和小伙伴们互相学习交流。

**Comment by antonia0912** [comment]
@bbmovistar 请加我微信 antonia0912 备注 github ID 我来拉你进译者群
