### ISSUE TITLE
Comparing API Architectural Styles: SOAP vs REST vs GraphQL vs RPC

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7540]
* 原文链接：[Comparing API Architectural Styles: SOAP vs REST vs GraphQL vs RPC](https://www.altexsoft.com/blog/soap-vs-rest-vs-graphql-vs-rpc/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/comparing-api-architectural-styles-soap-vs-rest-vs-graphql-vs-rpc.md)
* PR 地址：
* 文章分类：**后端**，**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：20 天
* 校对时间：5 天
* 翻译积分：11 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnieXu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@JohnieXu 好的！

**Comment by lsvih** [comment]
这篇比较长，辛苦啦
