### ISSUE TITLE
JavaScript ES2021 Exciting Features

### ISSUE THREAD

**Issue by zenblo** [xitu/gold-miner#7549]
- 原文链接：https://codeburst.io/exciting-features-of-javascript-es2021-es12-1de8adf6550b
- 简要介绍：是关于JavaScript ES2021新添加功能的

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
感谢推荐，#7581 已发布~
