### ISSUE TITLE
Light/Dark Mode toggle in React JS using Context API

### ISSUE THREAD

**Issue by zenblo** [xitu/gold-miner#7553]
- 原文链接：https://dev.to/g3dev/light-dark-mode-toggle-in-react-js-using-context-api-m7i
- 简要介绍：这是前端开发文章，主要是讲React的使用

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
前不久翻译过一篇类似的文章 [使用 React 和 localStorage 实现的简易 Dark Mode 开关](https://github.com/xitu/gold-miner/blob/master/article/2020/easy-dark-mode-switch-with-react-and-localstorage-3k6d.md)，然后这篇文章以代码为主的，就不发布了哈 😄
