### ISSUE TITLE
0-1 背包问题解读

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7556]
* 原文链接：[Demystifying the 0-1 Knapsack Problem](https://medium.com/better-programming/demystifying-the-0-1-knapsack-problem-56e7ac4dfcf7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/demystifying-the-0-1-knapsack-problem.md)
* PR 地址：
* 文章分类：**算法**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Usualminds** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Usualminds 好的~

**Comment by jaredliw** [comment]
@lsvih 接手

**Comment by lsvih** [comment]
好的 @jaredliw
