### ISSUE TITLE
分享九个流行 JavaScript 图片懒加载库

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7558]
* 原文链接：[Top Image Lazy Loading Libraries for JavaScript](https://blog.bitsrc.io/top-image-lazy-loading-libraries-for-javascript-dc39fbc9511f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/top-image-lazy-loading-libraries-for-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：8 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的！

**Comment by zenblo** [comment]
@lsvih 翻译完成，还是老问题没解决又带了之前的文件😵
