### ISSUE TITLE
JavaScript 调用 Web API 与 History 使用

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7560]
* 原文链接：[Understanding The Web History API in JavaScript](https://medium.com/javascript-in-plain-english/understanding-the-web-history-api-in-javascript-eac987071d4d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/understanding-the-web-history-api-in-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：1.5 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的~

**Comment by zenblo** [comment]
@lsvih 翻译完成，还是老问题没解决又带了之前的文件😵
