### ISSUE TITLE
如何避免 Android 设备的 WiFi 扫描节流

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7562]
* 原文链接：[How to Avoid WiFi Throttling on Android Devices](https://medium.com/better-programming/how-to-avoid-wifi-throttling-on-android-devices-494a0cc29dd8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-to-avoid-wifi-throttling-on-android-devices.md)
* PR 地址：
* 文章分类：**Android**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by regon-cao** [comment]
翻译认领

**Comment by lsvih** [comment]
@regon-cao 好的~
