### ISSUE TITLE
推荐 AI 优秀英文文章

### ISSUE THREAD

**Issue by z0gSh1u** [xitu/gold-miner#7563]
- 原文链接：https://medium.com/@jonathan_hui/gan-why-it-is-so-hard-to-train-generative-advisory-networks-819a86b3750b
- 简要介绍：GAN（生成对抗网络）是深度学习的常用网络类型，但它一直有不稳定、难以训练的问题。本文介绍了 GAN 难以训练的原因，探索了一些解决方案。

---

### 请完成并勾选一下三项：

* [ √ ] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [ √ ] 本文很值得翻译，我推荐
* [ √ ] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
有译文了 https://www.jianshu.com/p/93f6c62eadbb

这篇文章写的很好，之前我也看了~
