### ISSUE TITLE
Gunicorn 配置疑问

### ISSUE THREAD

**Issue by fuyunliu** [xitu/gold-miner#7565]
[Gunicorn 配置提高性能](https://github.com/xitu/gold-miner/blob/master/TODO1/gunicorn-3-means-of-concurrency.md)

> 建议的 workers 数量是 (2*CPU)+1

我理解没错的话，这个`+1`就是gunicorn的父进程，2*cpu就是守护进程，父进程用于控制workers的数量，守护进程处理请求。

> 因此如果我们使用四核（4 个 CPU）机器并且我们想使用 workers 和多线程模式，我们可以使用 3 个 worker 和 3 个线程来得到最大为 9 的并发请求数量。

这里不应该是(3+1)个 workers 和 3 个线程才能得到最大为9的并发请求数量吗？

> gunicorn --worker-class=gevent --worker-connections=1000 --workers=3 main:app
> (2*CPU)+1 仍然是建议的workers 数量。因为我们仅有一核，我们将会使用 3 个worker。
> 在这种情况下，最大的并发请求数量是 3000。（3 个 worker * 1000 个连接/worker）

这里的最大并发请求不应该是2 * 1000吗？

因为我觉得workers的数量应该是包含主进程（父进程）的吧？
然后主进程不负责处理请求，那么不应该算进并发里面去的吧？

![image](https://user-images.githubusercontent.com/13273942/97251368-b2b44980-1842-11eb-9563-730355fbed5e.png)

**Comment by lsvih** [comment]
不，2n + 1 就是 worker 的数量，master 单独作为一个进程。2n + 1 的数量来自于先验知识 https://github.com/benoitc/gunicorn/issues/1045#issuecomment-269575459 ，这个知识的具体来源没查到
