### ISSUE TITLE
为什么如今 Deno 正全面取代 Node.js

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7570]
* 原文链接：[Why Deno is Perfectly Ready To Take Over Node.js Now](https://medium.com/front-end-weekly/why-deno-is-perfectly-ready-to-take-over-node-js-now-3f768efe530c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/why-deno-is-perfectly-ready-to-take-over-node-js-now.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好的！

**Comment by lsvih** [comment]
已发布：https://juejin.cn/post/6897420951592534030/
