### ISSUE TITLE
Deno 已经死了吗？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7572]
* 原文链接：[Is Deno Already Dead?](https://medium.com/javascript-in-plain-english/is-deno-already-dead-661ce807338a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/is-deno-already-dead.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Inchill** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Inchill 好的~
