### ISSUE TITLE
负载平衡算法高级概述

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7574]
* 原文链接：[A High-Level Overview of Load Balancing Algorithms](https://medium.com/better-programming/a-high-level-overview-of-load-balancing-algorithms-8c7d3368276)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/a-high-level-overview-of-load-balancing-algorithms.md)
* PR 地址：
* 文章分类：**后端**，**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jackwener** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@jackwener 好的~
