### ISSUE TITLE
JavaScript ES2021 中激动人心的特性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7581]
* 原文链接：[JavaScript ES2021 Exciting Features](https://codeburst.io/exciting-features-of-javascript-es2021-es12-1de8adf6550b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/exciting-features-of-javascript-es2021-es12.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tonylua** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@tonylua 好的

**Comment by tonylua** [comment]
https://github.com/xitu/gold-miner/pull/7591 @lsvih 翻译完成
