### ISSUE TITLE
如何在 Nextjs 中使用 cookies 来持久化保存用户信息

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7585]
* 原文链接：[How to use cookies for persisting users in Nextjs](https://dev.to/debosthefirst/how-to-use-cookies-for-persisting-users-in-nextjs-4617)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-to-use-cookies-for-persisting-users-in-nextjs.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by plusmultiply0** [comment]
翻译认领@lsvih

**Comment by lsvih** [comment]
@plusmultiply0 好的！
