### ISSUE TITLE
SwiftUI 中的 PageTabViewStyle

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7588]
* 原文链接：[PageTabViewStyle in SwiftUI](https://medium.com/better-programming/pagetabviewstyle-in-swiftui-7a2aba16e439)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/pagetabviewstyle-in-swiftui.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by FranzWang666** [comment]
认领翻译

**Comment by lsvih** [comment]
@FranzWang666 您还没有进行过校对，翻译时请多加留意[翻译排版](https://github.com/xitu/gold-miner/wiki/译文排版规则指北)哈

**Comment by FranzWang666** [comment]
> @FranzWang666 您还没有进行过校对，翻译时请多加留意[翻译排版](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)哈

收到，因为比较擅长iOS领域，看了校对列表没有对应文章，后续如果有的话会参与哈。已仔细阅读排版要求，一定会注意。

**Comment by lsvih** [comment]
@FranzWang666 哈哈没事，期待您的译文
