### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Danny1451** [xitu/gold-miner#759]
姓名：dannyLau
工作：移动开发工程师 [南京炫彩互动网络科技有限公司]
英语水平：六级，经常阅读英文相关网站[Github/Stackoverflow/Medium]
技术：iOS/android/RN 跨平台技术开发 
有无翻译经验: 暂无正式的翻译经验，但是有翻译过文章在自己的blog [http://danny-lau.com/](url)
希望能和大家一起分享国外的优秀的技术文章

**Comment by antonia0912** [comment]
@Danny1451 请加我微信 antonia0912 备注 github ID 我来拉你进译者群呀
