### ISSUE TITLE
对象展开运算符在 JavaScript 中的 5 大应用

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7604]
* 原文链接：[5 Useful Things The Spread Operator Can Do in JavaScript](https://medium.com/javascript-in-plain-english/5-useful-things-the-spread-operator-can-do-in-javascript-f0306358bc9c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/5-useful-things-the-spread-operator-can-do-in-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Alfxjx** [comment]
翻译认领

**Comment by lsvih** [comment]
@Alfxjx 好的！

**Comment by lsvih** [comment]
https://juejin.cn/post/6895525536039174151 已发布
