### ISSUE TITLE
使用 SpringBoot 和 MySQL 构建 GraphQL 服务端应用程序

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7607]
* 原文链接：[Build a GraphQL Server With Spring Boot and MySQL](https://medium.com/better-programming/build-a-graphql-server-with-spring-boot-and-mysql-df427cbba26d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/build-a-graphql-server-with-spring-boot-and-mysql.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：20 天
* 校对时间：4 天
* 翻译积分：10 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好的~
