### ISSUE TITLE
为什么说 ES2020 的可选链和模块动态导入特性将会改变现有生态规则

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7608]
* 原文链接：[ES2020 Optional Chaining and Dynamic Imports Are Game-Changers. Here’s Why.](https://blog.bitsrc.io/es2020-optional-chaining-and-dynamic-imports-are-game-changers-heres-why-cbbf7efae3ee)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/es2020-optional-chaining-and-dynamic-imports-are-game-changers-heres-why.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnieXu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@JohnieXu 好的~
