### ISSUE TITLE
四种跨浏览器选项卡实时通信方法

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7610]
* 原文链接：[4 Ways to Communicate Across Browser Tabs in Realtime](https://blog.bitsrc.io/4-ways-to-communicate-across-browser-tabs-in-realtime-e4f5f6cbedca)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/4-ways-to-communicate-across-browser-tabs-in-realtime.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的

**Comment by HurryOwen** [comment]
@lsvih 校对认领
