### ISSUE TITLE
如何打造一个好的 GitHub 用户档案？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7613]
* 原文链接：[What Makes a Good Github Profile?](https://codeburst.io/what-makes-a-good-github-profile-ced754284e3d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/what-makes-a-good-github-profile.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by caiyundong** [comment]
翻译认领

**Comment by lsvih** [comment]
@caiyundong 好的~

**Comment by lsvih** [comment]
已发布：https://juejin.cn/post/6950529817469157384
