### ISSUE TITLE
函数式编程 —— 使用 Python、JavaScript 和 Java 描述

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7614]
* 原文链接：[Functional Programming Explained in Python, JavaScript, and Java](https://medium.com/better-programming/functional-programming-explained-in-python-javascript-and-java-2dbf875046a9)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/functional-programming-explained-in-python-javascript-and-java.md)
* PR 地址：
* 文章分类：**其他**，**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：20 天
* 校对时间：5 天
* 翻译积分：10 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by z0gSh1u** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@z0gSh1u 好的~
