### ISSUE TITLE
了解 React Portals（传送门）

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7616]
* 原文链接：[Understanding React Portals](https://blog.bitsrc.io/understanding-react-portals-ab79827732c7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/understanding-react-portals.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnieXu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@JohnieXu 好的~

**Comment by NieZhuZhu** [comment]
@lsvih  翻译认领——可以重新认领吗

**Comment by lsvih** [comment]
@NieZhuZhu 好的，这篇超时太久了，您来吧
