### ISSUE TITLE
使用 Svelte 开发前端应用的五个理由

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7625]
* 原文链接：[5 reasons why you should use Svelte for Front End Development in 2021](https://medium.com/javascript-in-plain-english/5-reasons-why-you-should-use-svelte-for-front-end-development-in-2021-c9e84db4f55c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/5-reasons-why-you-should-use-svelte-for-front-end-development-in-2021.md)
* PR 地址：
* 文章分类：**前端**、**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的~
