### ISSUE TITLE
在几秒钟内为你的开发环境创建一个私有 PostgreSQL 数据库

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7627]
* 原文链接：[Create a Private PostgreSQL Database for Your Development Environment in Seconds](https://medium.com/better-programming/create-a-private-postgresql-database-for-your-development-environment-in-seconds-b781640ed01b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/create-a-private-postgresql-database-for-your-development-environment-in-seconds.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：14 天
* 校对时间：4 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by lsvih** [comment]
@YueYongDev 好的！

**Comment by YueYongDev** [comment]
翻译完成，等待校对 @lsvih
