### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Evibee** [xitu/gold-miner#763]
掘金您好！我叫GreenViper，一直工作在一家知名外企8年，工作语言为英语，具有较好的中英文阅读书写水平，经常查看英文书籍，英文博客，国外网站主要有google/wiki/Github/Quora/等, 暂无博客，微信公众号是shibinliao_public。希望能够加入掘金翻译计划！共同学习提高！谢谢！

**Comment by antonia0912** [comment]
@Evibee 欢迎来掘金翻译计划玩 请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群
