### ISSUE TITLE
Pury — 一个新的 Android App 性能分析工具

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#764]
* 原文链接：[Pury — New Way to Profile Your Android Application](https://medium.com/@nikita.kozlov/pury-new-way-to-profile-your-android-application-7e248b5f615e)
* 掘金链接：[Pury-- 配置 Android 应用程序的新方式](http://gold.xitu.io/entry/57eb87945bbb50005d7846cf)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/pury-new-way-to-profile-your-android-application.md)
* PR 地址： [#775](https://github.com/xitu/gold-miner/pull/775)
* 文章分类：**Android**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by owenlyn** [comment]
认领~~

**Comment by antonia0912** [comment]
@owenlyn OK 注意翻译细节 题目可以重新翻译哈

**Comment by owenlyn** [comment]
@sqrthree @antonia0912 初稿完成啦，可能有些小错误，还请校对不要手下留情

**Comment by Graning** [comment]
@owenlyn   我想认领，但是你好像没有提交 PR ？
