### ISSUE TITLE
理解 JavaScript 中模块的导入和导出

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7644]
* 原文链接：[Understanding Modules and Import and Export Statements in JavaScript](https://www.digitalocean.com/community/tutorials/understanding-modules-and-import-and-export-statements-in-javascript)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/understanding-modules-and-import-and-export-statements-in-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：14 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by regon-cao** [comment]
@lsvih Markdown文件地址404了

**Comment by lsvih** [comment]
@regon-cao 已修复！感谢提醒= =

**Comment by NieZhuZhu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@NieZhuZhu 好的~
