### ISSUE TITLE
5 分钟内从单体架构迁移到微服务架构

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7646]
* 原文链接：[From Monolith to Microservices in 5 Minutes](https://levelup.gitconnected.com/from-monolith-to-microservices-in-5-minutes-83069677d021)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/from-monolith-to-microservices-in-5-minutes.md)
* PR 地址：
* 文章分类：**其他**，**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by lsvih** [comment]
@YueYongDev 好的~
