### ISSUE TITLE
上手 Python 数据类前需要知道的 6 件事

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7648]
* 原文链接：[6 Things to Know to Get Started With Python Data Classes](https://medium.com/better-programming/6-things-to-know-to-get-started-with-python-data-classes-c795bf7e0a74)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/6-things-to-know-to-get-started-with-python-data-classes.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：11 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JalanJiang** [comment]
翻译认领

**Comment by JalanJiang** [comment]
@lsvih

**Comment by lsvih** [comment]
@JalanJiang 好的~
