### ISSUE TITLE
探索Android大杀器——Handler

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#765]
* 原文链接：[Android Handler Internals](https://medium.com/@jagsaund/android-handler-internals-b5d49eba6977)
* 掘金链接：[Android 中 Handler 详解](http://gold.xitu.io/entry/57eb83898ac247005beb8e36/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/android-handler-internals.md)
* PR 地址： [#786](https://github.com/xitu/gold-miner/pull/786)
* 文章分类：**Android**

----
* 翻译时间：`4` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jamweak** [comment]
认领～～～

**Comment by jacksonke** [comment]
申请校对

**Comment by antonia0912** [comment]
@jamweak OK 注意翻译细节 题目可以重新翻译哈  @jacksonke 不可以提前占坑喔 等译者发PR了再去认领校对吧 这里不算数

**Comment by jamweak** [comment]
@antonia0912 好的，注意细节。

**Comment by futureshine** [comment]
申请校对

**Comment by sqrthree** [comment]
@futureshine  不可以提前占坑喔 等译者发 PR 了再去认领校对吧 这里不算数的啦

![sorry](https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSWnzqNfQ9PnrsI_hd__zj72UGb4BqF8RJ6AVziBAyyj294Iyg4xvrKlsg)

**Comment by jamweak** [comment]
翻译完毕，请求校对~

**Comment by sqrthree** [comment]
@jamweak 辛苦啦~ 顺便重新翻译下题目哈~~
