### ISSUE TITLE
从零开始了解 JavaScript 装饰器

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7650]
* 原文链接：[JavaScript Decorators From Scratch](https://blog.bitsrc.io/javascript-decorators-from-scratch-c4cfd6c33d70)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/javascript-decorators-from-scratch.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：18 天
* 校对时间：5 天
* 翻译积分：10 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by regon-cao** [comment]
翻译认领

**Comment by lsvih** [comment]
@regon-cao 好的
