### ISSUE TITLE
寻找最优化 AutoML 库

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7654]
* 原文链接：[Hunting for the Optimal AutoML Library](https://medium.com/data-from-the-trenches/hunting-for-the-optimal-automl-library-34e93c84bdba)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/hunting-for-the-optimal-automl-library.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：16 天
* 校对时间：4 天
* 翻译积分：9 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhusimaji** [comment]
@lsvih  翻译认领

**Comment by lsvih** [comment]
@zhusimaji 好的~
