### ISSUE TITLE
关于 Android Adapter，你的实现方式可能一直都有问题

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#766]
* 原文链接：[Writing Better Adapters](https://medium.com/@dpreussler/writing-better-adapters-1b09758407d2)
* 掘金链接：[Writing Better Adapters](http://gold.xitu.io/entry/57eb8d91d20309006969c7fd)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/writing-better-adapters.md)
* PR 地址：[#776](https://github.com/xitu/gold-miner/pull/776)
* 文章分类：**Android**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by siegeout** [comment]
认领

**Comment by jacksonke** [comment]
申请校对

**Comment by antonia0912** [comment]
@siegeout OK 注意翻译细节 题目可以重新翻译哈
