### ISSUE TITLE
在浏览器中处理自然语言

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7663]
* 原文链接：[Natural Language Processing in the Browser](https://medium.com/better-programming/natural-language-processing-in-the-browser-8ca5fdf2488b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/natural-language-processing-in-the-browser.md)
* PR 地址：
* 文章分类：**前端**，**AI**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by regon-cao** [comment]
@lsvih  翻译认领

**Comment by lsvih** [comment]
@regon-cao 好的
