### ISSUE TITLE
如何使用 useRef 修复 React 性能问题

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7667]
* 原文链接：[How to useRef to Fix React Performance Issues](https://medium.com/better-programming/how-to-useref-to-fix-react-performance-issues-4d92a8120c09)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-to-useref-to-fix-react-performance-issues.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by NieZhuZhu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@NieZhuZhu 好的~
