### ISSUE TITLE
APK 里有什么? 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#767]
* 原文链接：[Whats in the APK?](http://crushingcode.co/whats-in-the-apk/)
* 掘金链接：[Android 应用程序中如何通过 APK 获取信息](http://gold.xitu.io/entry/57eb89ce8ac247005bebc328)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/whats-in-the-apk.md)
* PR 地址：[#770](https://github.com/xitu/gold-miner/pull/770)
* 文章分类：**Android**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Newt0n** [comment]
认领

**Comment by sqrthree** [comment]
@Newt0n 请问你有 Android 相关开发经验么？

**Comment by Newt0n** [comment]
@sqrthree 不是专职 Android 开发，不过工作中也开发过内部用的 Android App，大致看了下这篇应该没问题。

**Comment by sqrthree** [comment]
@Newt0n 好的
