### ISSUE TITLE
黑暗主题 — 现代 UI 设计

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7672]
* 原文链接：[Dark Theme: A Modern UI Design](https://levelup.gitconnected.com/dark-theme-a-modern-ui-design-dec879313194)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/dark-theme-a-modern-ui-design.md)
* PR 地址：
* 文章分类：**设计**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的~
