### ISSUE TITLE
一些知名算法的应用

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7676]
* 原文链接：[Applications of Some of The Famous Algorithms](https://levelup.gitconnected.com/applications-of-some-of-the-famous-algorithms-cdaecee58ed1)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/applications-of-some-of-the-famous-algorithms.md)
* PR 地址：
* 文章分类：**算法**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：15 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好的~

**Comment by samyu2000** [comment]
@lsvih 翻译完成
