### ISSUE TITLE
TypeScript 的 5 个建议

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7686]
* 原文链接：[5 Tips for Better TypeScript Code](https://levelup.gitconnected.com/5-tips-for-better-typescript-code-5603c26206ef)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/5-tips-for-better-typescript-code.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5.5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ZavierTang** [comment]
翻译认领

**Comment by lsvih** [comment]
@ZavierTang 好的~
