### ISSUE TITLE
Flutter 可能是下一个大事件，但 Kotlin Multiplatform 一直都是大事件

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7688]
* 原文链接：[Flutter May or May Not Be the Next Big Thing, But Kotlin Multiplatform Is Here to Stay](https://medium.com/better-programming/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay-baf1a44a692d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md)
* PR 地址：
* 文章分类：**Flutter**，**Android**，**iOS**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by keepmovingljzy** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@keepmovingljzy 好的~
