### ISSUE TITLE
10月第一周【后端】备选文章

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#769]
**新规则**：这里是一些备选文章，大家看完之后觉得那一篇或者那几篇质量不错请在下边留言喔~一周之后被选出的优质文章将放在翻译计划进行翻译哈~爱你们么么哒~

1、[Improve PostgreSQL on Windows performance by 100%](http://www.openscg.com/2016/09/improve-postgresql-windows-performance-by-100/)
2、[Tracking KPIs using SQL for Effective Revenue Growth Analysis](https://periscopedata.com/blog//effective-revenue-chart.html)
3、[BUILDING A SCALABLE MYSQL PROXY IN RUST](http://www.agildata.com/building-scalable-mysql-proxy-rust/)
4、[Moving Average Pipeline Aggregations in Elasticsearch](https://qbox.io/blog/moving-average-pipeline-aggregations-elasticsearch)
5、[Dynamic Pivot Tables with JSON and PostgreSQL](http://bender.io/2016/09/18/dynamic-pivot-tables-with-json-and-postgresql/)
6、[Using http/2 for App Engine Local Development](https://medium.com/dev-channel/using-http-2-for-app-engine-local-development-e0b0dd6782a4)

**Comment by DeadLion** [comment]
7 应该算是前端的吧，讲的是 chrome 开发者工具。

**Comment by antonia0912** [comment]
@DeadLion 宝宝假装无辜的样子  使劲儿眨了眨自己的小眼睛

**Comment by DeadLion** [comment]
质量就不知道了
感兴趣的 3 6
