### ISSUE TITLE
虚拟 DOM 来源于文档片段吗？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7690]
* 原文链接：[Is Virtual DOM Derived From Document Fragments?](https://medium.com/better-programming/is-virtual-dom-derived-from-document-fragments-74f8841f9e6d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/is-virtual-dom-derived-from-document-fragments.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by regon-cao** [comment]
@lsvih  翻译认领

**Comment by lsvih** [comment]
@regon-cao 好的~

**Comment by lsvih** [comment]
https://juejin.cn/post/6902211857244028941 已发布
