### ISSUE TITLE
四个优秀 Vue.js 静态站点生成器

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7692]
* 原文链接：[Best Static Site Generators for Vue.js](https://blog.bitsrc.io/best-static-site-generators-for-vue-js-e273d52ea208)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/best-static-site-generators-for-vue-js.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wynn-w** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@wynn-w 您还没有进行过校对哈，建议先完成校对一篇文章，了解流程之后再认领翻译 😃

**Comment by zenblo** [comment]
@lsvih 我想接过来翻译

**Comment by lsvih** [comment]
@zenblo 好的
