### ISSUE TITLE
页面生命周期 API：每一个前端开发者都应该知道的浏览器 API

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7694]
* 原文链接：[Page Lifecycle API: A Browser API Every Frontend Developer Should Know](https://blog.bitsrc.io/page-lifecycle-api-a-browser-api-every-frontend-developer-should-know-b1c74948bd74)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/page-lifecycle-api-a-browser-api-every-frontend-developer-should-know.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：7 天
* 校对时间：1 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xutaogit** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@xueshuai 好的~
