### ISSUE TITLE
Python 中的运算符重载

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7696]
* 原文链接：[Operator overloading in Python](https://medium.com/python-in-plain-english/operator-overloading-in-python-6dbf90be9d3e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/operator-overloading-in-python.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好的~

记得新鲜 branch 哈
