### ISSUE TITLE
SwiftUI 黑暗模式——最简单的方法

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7698]
* 原文链接：[SwiftUI Dark Mode — the Easiest Way](https://medium.com/level-up-programming/swiftui-dark-mode-the-easiest-way-81e48d055189)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/swiftui-dark-mode-the-easiest-way.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhuzilin** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zhuzilin 好的~

**Comment by keepmovingljzy** [comment]
@lsvih 校对认领

**Comment by lsvih** [comment]
@keepmovingljzy 好的~

**Comment by lsvih** [comment]
@keepmovingljzy 请到 PR #7743 里面认领校对哈

**Comment by keepmovingljzy** [comment]
@lsvih 好的，认领了哈
