### ISSUE TITLE
推荐AI优秀英文文章：DeepSpeed: Extreme-scale model training for everyone

### ISSUE THREAD

**Issue by zhuzilin** [xitu/gold-miner#7706]
- 原文链接：https://www.microsoft.com/en-us/research/blog/deepspeed-extreme-scale-model-training-for-everyone/
- 简要介绍：关于微软今年发布的DeepSpeed加速库的详细介绍。这个库给超大规模模型训练提供了工具，让trillion级NLP模型变得可能。顺便也展示了一下微软爸爸的财力...

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
您要自己翻译这篇文章嘛？ 这篇文章专业性质比较强，一般译者不太适合翻译这种

**Comment by zhuzilin** [comment]
> 您要自己翻译这篇文章嘛？ 这篇文章专业性质比较强，一般译者不太适合翻译这种

我可以来翻译这个，这个和我的工作内容比较近～以及不用说您，太客气了...

**Comment by lsvih** [comment]
@zhuzilin 好哒我一会儿加上

**Comment by lsvih** [comment]
#7771 已发布~
