### ISSUE TITLE
增量 DOM 与虚拟 DOM 的对比使用

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7713]
* 原文链接：[Incremental vs Virtual DOM](https://blog.bitsrc.io/incremental-vs-virtual-dom-eb7157e43dca)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/incremental-vs-virtual-dom.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的~
