### ISSUE TITLE
JavaScript 的面向切面编程

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7715]
* 原文链接：[Aspect-Oriented Programming in JavaScript](https://blog.bitsrc.io/aspect-oriented-programming-in-javascript-c4cb43f6bfcc)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/aspect-oriented-programming-in-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Liusq-Cindy** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Liusq-Cindy 欢迎翻译~
