### ISSUE TITLE
继承 vs 组合：哪一个更适合你的 JavaScript 项目？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7717]
* 原文链接：[Inheritance vs Composition: Which is Better for Your JavaScript Project?](https://blog.bitsrc.io/inheritance-vs-composition-which-is-better-for-your-javascript-project-16f4a077de9)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/inheritance-vs-composition-which-is-better-for-your-javascript-project.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by regon-cao** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@regon-cao 好的~

**Comment by HurryOwen** [comment]
@lsvih 校对认领
