### ISSUE TITLE
GitHub Package Registry 是否值得尝试

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7719]
* 原文链接：[GitHub Package Registry: Is it Worth Trying Out?](https://blog.bitsrc.io/github-package-registry-is-it-worth-trying-out-62163aa3d518)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/github-package-registry-is-it-worth-trying-out.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的~
