### ISSUE TITLE
iOS 中的 widget

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7721]
* 原文链接：[Widgets on iOS](https://medium.com/@nrakshith94/widgets-on-ios-e0156a2e7239)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/widgets-on-ios.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：13 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhuzilin** [comment]
@lsvih 申请翻译~

**Comment by lsvih** [comment]
@zhuzilin 好的~
