### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by XatMassacrE** [xitu/gold-miner#773]
Hello, 我是XatMassacrE, 毕业于西南财经大学数学系, 通过CET-6, 大学有字幕翻译经验. 目前在深圳从事前端开发工程师一职(已工作一年), 通常会浏览Github, Stackoverflow, quora, coursera等网站, 希望可以加入多多学习和交流.

**Comment by antonia0912** [comment]
@XatMassacrE 欢迎来到掘金翻译计划 请加我微信 antonia0912 备注 github ID 我来拉你进译者群

**Comment by XatMassacrE** [comment]
感谢回复，微信好友申请已发送。

祝好，
杨文涛

2016-10-08 10:38 GMT+08:00 antonia0912 <notifications@github.com>:
