### ISSUE TITLE
The 2020 State of the OCTO— —VERSE

### ISSUE THREAD

**Issue by captainfod** [xitu/gold-miner#7731]
- 原文链接：The 2020 State of theOCTO——VERSE
- 简要介绍：Github年度开发者报告
---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by leviding** [comment]
三个待认领文件，直接在 pdf 上写译文即可：

- [ ] 2020-productivity-report @leviding 
- [ ] 2020-security-report
- [ ] 2020-community-report

**Comment by leviding** [comment]
大佬们在这评论一下认领哪个就行哈，我就拉个微信小群，有小伙伴会给大家寄礼物 😀

**Comment by leviding** [comment]
[2020-reports.zip](https://github.com/xitu/gold-miner/files/5650955/2020-reports.zip)

**Comment by lsvih** [comment]
@leviding 这仨文件应该都完成了叭-。-  要不把翻译完的 pdf 传一下然后登记积分了

**Comment by lsvih** [comment]
这几个积分怎么算来着= =@leviding

**Comment by leviding** [comment]
这个不计算积分啦
