### ISSUE TITLE
推荐前端优秀英文文章

### ISSUE THREAD

**Issue by proYang** [xitu/gold-miner#7733]
- 原文链接：https://www.joshwcomeau.com/css/rules-of-margin-collapse/#more-than-two-margins-can-collapse
- 简要介绍：讲解了前端 CSS Margin 重叠规则，文章有较生动的例子

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
感谢推荐！这篇文章确实挺好的，不过鉴于现在掘金的代码演示功能还在开发中，没法像这篇文章一样把示例给放出来，阅读体验估计不怎么好，因此暂时不会发布这种交互性很强的文章= =

总之感谢您的推荐~

**Comment by lsvih** [comment]
如果他们近期能开放代码演示的功能，还是会把这篇给放上去的 😄

**Comment by proYang** [comment]
好的。:rose:
