### ISSUE TITLE
Elasticsearch 新手指南

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7736]
* 原文链接：[The Beginners Guide to Elasticsearch](https://levelup.gitconnected.com/the-beginners-guide-to-elasticsearch-8fc237fc3209)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/the-beginners-guide-to-elasticsearch.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yqian1991** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@yqian1991 好的~
