### ISSUE TITLE
提高开发效率的五个 Chrome 扩展程序

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7738]
* 原文链接：[5 Chrome Extensions For Improving Developers’ Productivity](https://medium.com/javascript-in-plain-english/5-chrome-extensions-for-developers-productivity-11de7c343e58)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/5-chrome-extensions-for-developers-productivity.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：1 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的~
