### ISSUE TITLE
单体应用与微前端开发对比

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7740]
* 原文链接：[Monolith vs. Micro Frontends](https://blog.bitsrc.io/monolith-vs-micro-frontend-e6e9772a068b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/monolith-vs-micro-frontend.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：13 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 刚才那篇就几句话。。这篇我想接过来译

**Comment by lsvih** [comment]
@zenblo 好的~  刚才那篇本来就是几句话（
