### ISSUE TITLE
Security Best Practices for Node.js

### ISSUE THREAD

**Issue by zenblo** [xitu/gold-miner#7756]
- 原文链接：https://blog.appsignal.com/2020/08/12/security-best-practices-for-nodejs.html
- 简要介绍：Node.js的安全性最佳实践，有关前端安全方面的

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
#7762 已发布，感谢推荐~~

您推荐的这两篇文章都挺好的 😄
