### ISSUE TITLE
在 Node.js 中避免内存泄漏：性能最佳实践

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7760]
* 原文链接：[Avoiding Memory Leaks in Node.js: Best Practices for Performance](https://blog.appsignal.com/2020/05/06/avoiding-memory-leaks-in-nodejs-best-practices-for-performance.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/avoiding-memory-leaks-in-nodejs-best-practices-for-performance.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：14 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by laampui** [comment]
翻译认领

**Comment by lsvih** [comment]
@laampui 好的~
