### ISSUE TITLE
Node.js 安全编程的最佳实践

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7762]
* 原文链接：[Security Best Practices for Node.js](https://blog.appsignal.com/2020/08/12/security-best-practices-for-nodejs.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/security-best-practices-for-nodejs.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：15 天
* 校对时间：4 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 那篇 GitHub 的上午可以搞完，这篇我想接过来翻译

**Comment by lsvih** [comment]
@zenblo 好的~

**Comment by zenblo** [comment]
@lsvih 我想放弃翻译这篇。

**Comment by lsvih** [comment]
@zenblo 好的

**Comment by Ashira97** [comment]
翻译认领

**Comment by Ashira97** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@Ashira97 好的~
