### ISSUE TITLE
2021 年你应该掌握的 15 个 VSCode 扩展

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7767]
* 原文链接：[15 VSCode extensions every Web Developer must have in 2021.](https://levelup.gitconnected.com/15-vscode-extensions-every-web-developer-must-have-in-2021-9388a38c70fc)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/15-vscode-extensions-every-web-developer-must-have-in-2021.md)
* PR 地址：
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by regon-cao** [comment]
@lsvih  翻译认领

**Comment by lsvih** [comment]
@regon-cao 好的~
