### ISSUE TITLE
使用 CSS 提升页面渲染速度

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7769]
* 原文链接：[Improve Page Rendering Speed Using Only CSS](https://blog.bitsrc.io/improve-page-rendering-speed-using-only-css-a61667a16b2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/improve-page-rendering-speed-using-only-css.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：15 天
* 校对时间：3 天
* 翻译积分：6.5 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Usualminds** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Usualminds 好的~
