### ISSUE TITLE
如何测试 Service 中的 Singleton (1)

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#777]
* 原文链接：[How to test a singleton in an Android Service (1)?](http://www.songzhw.com/2016/09/30/how-to-test-a-singleton-in-an-android-service-one/)
* 掘金链接：[如何测试 Service 中的 Singleton (1)](http://gold.xitu.io/entry/57f8a15767f356005867eea3)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-test-a-singleton-in-an-android-service-one.md)
* PR 地址：[#782](https://github.com/xitu/gold-miner/pull/782)
* 文章分类：**Android**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Newt0n** [comment]
认领

**Comment by sqrthree** [comment]
@Newt0n 好的，注意时间限制哈

**Comment by huanglizhuo** [comment]
来晚一步 ：（

**Comment by hackerkevin** [comment]
校对

**Comment by sqrthree** [comment]
@hackerkevin 很抱歉，这个已经有两个校对者了，下次早点啦~ 另外需要到对应的 PR 下申请哈~ 以 PR 下的顺序为准的啦
