### ISSUE TITLE
理解 LSM 树：一种适用于频繁写入的数据库的结构

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7771]
* 原文链接：[Understanding LSM Trees: What Powers Write-Heavy Databases](https://yetanotherdevblog.com/lsm/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/lsm.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好的~

**Comment by samyu2000** [comment]
@lsvih 翻译完成
