### ISSUE TITLE
WebTransport 会在不久的将来取代 WebRTC 吗？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7777]
* 原文链接：[Will WebTransport Replace WebRTC in Near Future?](https://blog.bitsrc.io/will-webtransport-replace-webrtc-in-near-future-436c4f7f3484)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/will-webtransport-replace-webrtc-in-near-future.md)
* PR 地址：
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Usualminds** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Usualminds 好的~
