### ISSUE TITLE
Web 应用缓存的基础知识

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7779]
* 原文链接：[Fundamentals of Caching Web Applications](https://blog.bitsrc.io/fundamentals-of-caching-web-applications-a215c4333cbb)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/fundamentals-of-caching-web-applications.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by regon-cao** [comment]
@lsvih翻译认领

**Comment by lsvih** [comment]
@regon-cao 好的~

**Comment by Usualminds** [comment]
@lsvih 校对认领
