### ISSUE TITLE
如何测试 Service 中的 Singleton (2)?

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#778]
* 原文链接：[How to test a singleton in an Android Service (2)?](http://www.songzhw.com/2016/10/03/how-to-test-a-singleton-in-an-android-service-2/)
* 掘金链接：[如何测试 Service 中的 Singleton (2)?](http://gold.xitu.io/entry/57f4800b7db2a200592cca5a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-test-a-singleton-in-an-android-service-2.md)
* PR 地址：[#783](https://github.com/xitu/gold-miner/pull/783)
* 文章分类：**Android**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Newt0n** [comment]
认领

**Comment by sqrthree** [comment]
@Newt0n 好的
