### ISSUE TITLE
为什么我的数据会漂移？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7781]
* 原文链接：[Why Is My Data Drifting?](https://medium.com/data-from-the-trenches/why-is-my-data-drifting-a8ecc74920a5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/why-is-my-data-drifting.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：15 天
* 校对时间：2 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chzh9311** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@chzh9311 好的~

**Comment by samyu2000** [comment]
@lsvih 校对认领

**Comment by lsvih** [comment]
@samyu2000 好的~
