### ISSUE TITLE
Swift 代码的可测试性

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#779]
* 原文链接：[How Can Swift Language Features Improve Testability?](http://qualitycoding.org/swift-testability/)
* 掘金链接：[Swift 代码的可测试性](http://gold.xitu.io/entry/57f8e6a30bd1d00058b69a0e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/swift-testability.md)
* PR 地址：[#807](https://github.com/xitu/gold-miner/pull/807)
* 文章分类：**iOS**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by steinliber** [comment]
认领

**Comment by sqrthree** [comment]
@steinliber 好的，顺便填下这个吧 [wiki](https://github.com/xitu/gold-miner/wiki/译者擅长领域表)

**Comment by steinliber** [comment]
翻译OK了 @sqrthree
