### ISSUE TITLE
为用户体验设计绘制草图，你所需要知道的一切

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#780]
* 原文链接：[Everything You Need to Know about UX Sketching](https://www.toptal.com/designers/ux/guide-to-ux-sketching)
* 掘金链接：[关于用户体验设计你需要知道的事](http://gold.xitu.io/entry/57f8e427da2f60004f8d26ba)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/guide-to-ux-sketching.md)
* PR 地址：[#799](https://github.com/xitu/gold-miner/pull/799)
* 文章分类：**设计**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by funtrip** [comment]
抢！

**Comment by cs686** [comment]
我抢

**Comment by sqrthree** [comment]
@funtrip 好的，顺便填下这个吧 [wiki](https://github.com/xitu/gold-miner/wiki/译者擅长领域表)

@cs686 第一次参加翻译计划的话需要从校对文章开始哟~  [如何参与翻译](https://github.com/xitu/gold-miner#如何参与翻译)

**Comment by funtrip** [comment]
@sqrthree OKAY!
