### ISSUE TITLE
如何成为谷歌开发专家（GDE）—实用指南

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7802]
* 原文链接：[How to Become a Google Developer Expert (GDE) — A Practical Guide](https://medium.com/firebase-developers/how-to-become-a-google-developer-expert-gde-a-practical-guide-83621d2c8087)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Usualminds** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Usualminds 好的~
