### ISSUE TITLE
我们应该在什么时候使用 @State、@Binding、@ObservedObject、@EnvironmentObject 和 @Environment？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7804]
* 原文链接：[When Should I Use @State, @Binding, @ObservedObject, @EnvironmentObject, or @Environment?](https://jaredsinclair.com/2020/05/07/swiftui-cheat-sheet.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2020/swiftui-cheat-sheet.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2020` 文件夹中，不是之前的 `TODO1` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LoneyIsError** [comment]
翻译认领

**Comment by lsvih** [comment]
@LoneyIsError 好的~
