### ISSUE TITLE
如何使用 Node.js 执行多线程

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7806]
* 原文链接：[How To Do Multithreading With Node.js](https://medium.com/javascript-in-plain-english/how-to-do-multithreading-with-node-js-207aabdaddfb)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/how-to-do-multithreading-with-node-js.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的~
