### ISSUE TITLE
不同类型的浏览器存储

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7809]
* 原文链接：[The Different Types of Browser Storage](https://medium.com/better-programming/the-different-types-of-browser-storage-82b918cb3cf8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/the-different-types-of-browser-storage.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by flashhu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@flashhu 好的~
