### ISSUE TITLE
iOS 10 中的 NSPersistentContainer

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#781]
* 原文链接：[25 Core Data in iOS10: NSPersistentContainer](https://swifting.io/blog/2016/09/25/25-core-data-in-ios10-nspersistentcontainer/)
* 掘金链接：[iOS 10 中的 NSPersistentContainer](http://gold.xitu.io/entry/57f8e7720bd1d00058b6a21e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/25-core-data-in-ios10-nspersistentcontainer.md)
* PR 地址：[#801](https://github.com/xitu/gold-miner/pull/801)
* 文章分类：**iOS**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lizwangying** [comment]
认领~

**Comment by yifili09** [comment]
@sqrthree 认领！

**Comment by sqrthree** [comment]
@yifili09 Great.

**Comment by yifili09** [comment]
@sqrthree #801 初稿需要小伙伴们校对。

**Comment by sqrthree** [comment]
@yifili09 好的
