### ISSUE TITLE
减少 Web 应用程序中 CORS 预检时间的 4 种方法

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7811]
* 原文链接：[4 Ways to Reduce CORS Preflight Time in Web Apps](https://blog.bitsrc.io/4-ways-to-reduce-cors-preflight-time-in-web-apps-1f47fe7558)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/4-ways-to-reduce-cors-preflight-time-in-web-apps.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by regon-cao** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@regon-cao 好的~
