### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Ashira97** [xitu/gold-miner#7812]
- 公司/学校：某银行信科部门
- 工作内容/专业：前后端开发/计算机科学
- 常浏览的国外网站：infoq/slashdot/w3cschools/stackoverflow
- 英语水平：TOEFL 93 三级笔译/口译考试准备中...
- 翻译经验：抱歉~暂无...
- 主要翻译方向：前端开发及性能优化/nodejs/v8引擎相关/人工智能/
- 个人博客：抱歉~暂无...
- 个人介绍：
 
  首先为没有个人博客和成型的翻译经验感到抱歉。实不相瞒，我是最近才意识到成果记录和分享的重要性。
 1. 我目前在信科部门从事前后端开发的工作，主要技术栈是Vue/nodejs/redis。从2020年下半年开始备考三级笔译和三级口译，对翻译中的概念有了基本的了解。对于英文技术文章，翻译的过程也是理解和学习的过程，在翻译的过程中，我能体会到专注和学习到新知识的快乐。最近我刚刚翻译了一篇与v8引擎内联缓存有关的[文章](https://github.com/Ashira97/aboutV8/blob/master/%E5%86%85%E8%81%94%E7%BC%93%E5%AD%98%E4%BC%98%E5%8C%96js%E4%BB%A3%E7%A0%81.md)，由于没有翻译经验，此处提供github地址供您参考。

 2. 在日常工作和学习中，我经常上掘金社区查资料、看文章，掘金翻译计划的文章帮助我解决了不少问题，所以也非常希望能加入掘金翻译计划，在自己学习的同时为社区分享添一份力。

**Comment by kezhenxu94** [comment]
Hi, 感谢你申请加入掘金翻译计划，你需要做以下的事：

1. 认真学习 [掘金翻译计划译者教程](https://github.com/xitu/gold-miner/wiki)，校对和翻译文章时，严格遵循教程，杜绝不看教程，只知道问的伸手党；
2. 确认认真学习了 [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)，翻译文章时严格遵循，校对文章时也要指出译者的格式错误；
3. 确认认真学习了 [翻译和校对文章的注意事项](https://github.com/xitu/gold-miner/wiki/%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88)，避免翻译校对过程中出错；
4. 确定已学习完上述内容，加管理员微信 `kezhenxu94`，**验证信息格式**：姓名 + GitHub 用户名；
5. 进群后修改群昵称为 GitHub id。

**注意**：管理员每天集中处理一次，稍安勿躁。加完微信后，管理员会在当天拉你进译者群，进群之后做下简单的自我介绍。加入微信群则代表申请译者成功，接下来你需要看译者教程，然后先校对至少一篇文章才能开始正式翻译文章。当然也可以继续校对文章。

**Comment by kezhenxu94** [comment]
@Ashira97 非常欢迎喜欢 / 有意愿分享的朋友加入
