### ISSUE TITLE
Python 中的列表和元组

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7818]
* 原文链接：[Lists and Tuples in Python](https://medium.com/python-in-plain-english/python-lists-and-tuples-760d45ebeaa8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/python-lists-and-tuples.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jeayu** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@jeayu 感谢您对翻译计划的支持，不过按照流程，您可能需要先校对至少一篇译文，熟悉基本的排版等标准哈：）

**Comment by PassionPenguin** [comment]
翻译认领@lsvih
