### ISSUE TITLE
解构标志性的 Apple Watch Bubble UI

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7820]
* 原文链接：[Deconstructing the  Iconic Apple Watch Bubble UI](https://codeburst.io/deconstructing-the-iconic-apple-watch-bubble-ui-aba68a405689)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/deconstructing-the-iconic-apple-watch-bubble-ui.md)
* PR 地址：
* 文章分类：**前端**，**设计**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：16 天
* 校对时间：4 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by NieZhuZhu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@NieZhuZhu 好的~
