### ISSUE TITLE
翻译建议

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7825]
建议将原文为外文的代码，便于读者阅读、开发调试中读取。毕竟不是每一个读者都有很优秀的英文阅读功底，遇到长句，将会瞬间卡壳，被迫打开 Google Translate 。

例如

```html
    <button>Show Model</button>
```

```flutter
OutlineButton(
      onPressed: () {
        print('Received click');
      },
      child: Text('Click Me'),
    );
```

翻译为

```html
    <button>显示弹窗</button>
```

```flutter
OutlineButton(
      onPressed: () {
        print('接收到点击事件');
      },
      child: Text('点击我'),
    );
```

**Comment by NieZhuZhu** [comment]
我认为这种代码中简单的英文文本信息，是开发基本门槛吧，毕竟代码都是用英文写的，如果这都不认识的话，那大家要怎么写代码呢？🙈

**Comment by lsvih** [comment]
其实比较倾向于代码不译，注释译；因为代码翻译了有时候会和前后文或者其它 code snippet 对应不上，另外有可能翻译了反而更难理解 😄

**Comment by PassionPenguin** [comment]
是啊，这倒也的确，
那如果不修改code snippet，或者注释code snippet的内容
倘若改成中文，那会极大的提升以汉语为母语的程序员的反应速度啊（
