### ISSUE TITLE
When “Compat” libraries won’t save you

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7827]
- 原文链接：https://proandroiddev.com/when-compat-libraries-do-not-save-you-dc55f16b4160
- 简要介绍：Compat库转向AndroidX库的理由，给广大安卓开发者们转向AndroidX库的建议

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐Android
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
感谢推荐，#8420 已发布认领
