### ISSUE TITLE
Messengers-like ImageView

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7828]
- 原文链接：https://proandroiddev.com/messengers-like-imageview-90e9f1da19f4
- 简要介绍：深入浅出介绍了ImageVIew的不同尺寸、边裁、保持比例

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐Android
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
#7909 已发布认领，感谢推荐！
