### ISSUE TITLE
Flutter Quotes App

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7829]
- 原文链接：https://medium.com/flutterdevs/flutter-quotes-app-bb30ef27b255
- 简要介绍：Flutter打造一个名言显示器

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端Android/iOS/Flutter
* [x] 本文很值得翻译，我推荐，【但同时建议找专业人员添加相关知识与后续内容？文章不仅适合吸引潜在flutter学习者，而且在flutter用户中也应该有很高的实践价值】
* [x] 已经过初步搜索，暂未发现中文版译文

文章从理论上具有较高价值，但是作者对于代码并没有逐句解析，应该是面对潜在的flutter学习者。
建议文章可以发两个part？一个part就按照原文，用于吸引潜在用户。并在文末添加完整解析的文章链接。

值得注意的是，本文若要翻译需要译者具有flutter开发水平，整理原文中的未格式化代码

**Comment by lsvih** [comment]
这篇原文不见了

**Comment by lsvih** [comment]
#8426 已发布认领，感谢推荐~
