### ISSUE TITLE
Built-in Explicit Animations in Flutter

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7830]
- 原文链接：https://medium.com/flutterdevs/built-in-explicit-animations-in-flutter-438a039dd90
- 简要介绍：介绍Flutter中内置动画的使用

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐Android/iOS/Flutter
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by PassionPenguin** [comment]
该文章代码从单一角度，较为全面地概括了Flutter中动画的使用，能够较好的推广到其他动画

**Comment by lsvih** [comment]
感谢推荐！#7836 已发布认领

**Comment by PassionPenguin** [comment]
认领翻译
