### ISSUE TITLE
分区提议

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7831]
实际上，macOS开发在国内帖子极度稀缺，便是稀土。

本人日前在学习开发macOS时便遇到了极大的阻力，包括Apple Dev Docs上的介绍的不完整，以及国内相关教程的稀缺。

即便是在英文网站上，相关资料仍然稀缺，但公认的是，他们的质量普遍都很高

鉴于近期翻译的macOS隐私的官方文档，建议开一个macOS的分区/label

不管怎么说，毕竟macOS也是Flutter&iPadOS/iOS Catalyst的重要组成部分

**Comment by lsvih** [comment]
macOS 区暂时不开放哈，太小众了= =  不过收集了一份可能可以开的新分区列表，视国内相关技术社区用户活跃程度开叭。。
