### ISSUE TITLE
The State of Design Systems: 2020

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7832]
- 原文链接：https://material.io/blog/research-state-of-design-systems-2020
- 简要介绍：2020年设计系统的总结概括，为设计师们在选择设计系统上提供建议

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很有点值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
#7858 已发布认领，感谢推荐！

**Comment by PassionPenguin** [comment]
认领翻译：）
