### ISSUE TITLE
Flutter 中的交织动画

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7835]
* 原文链接：[Staggered Animation In Flutter](https://medium.com/flutterdevs/staggered-animation-in-flutter-e7282a936b99)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/staggered-animation-in-flutter.md)
* PR 地址：
* 文章分类：**Flutter**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领翻译～

**Comment by lsvih** [comment]
@PassionPenguin 好的，不过尽量一次认领翻译一篇哈

**Comment by PassionPenguin** [comment]
> @PassionPenguin 好的，不过尽量一次认领翻译一篇哈

这个嘛，昨天看文章的时候已经有了大概的翻译思路了～放心吧！

**Comment by lsvih** [comment]
已发布：https://juejin.cn/post/6918693294083932173
