### ISSUE TITLE
Flutter 中内置的显式动画

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7836]
* 原文链接：[Built-in Explicit Animations in Flutter](https://medium.com/flutterdevs/built-in-explicit-animations-in-flutter-438a039dd90)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/built-in-explicit-animations-in-flutter.md)
* PR 地址：
* 文章分类：**Flutter**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：13 天
* 校对时间：2 天
* 翻译积分：5.5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领翻译

**Comment by lsvih** [comment]
@PassionPenguin 欢迎翻译~

**Comment by lsvih** [comment]
已发布：https://juejin.cn/post/6918698096109191175
