### ISSUE TITLE
Node.js 缓冲区的完整指南

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7838]
* 原文链接：[A Complete Guide of Node.js Buffer](https://medium.com/javascript-in-plain-english/a-complete-guide-of-node-js-buffer-3a38d2d949b1)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/a-complete-guide-of-node-js-buffer.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
申请翻译 @lsvih

**Comment by PassionPenguin** [comment]
忘了发链接了（

@regon-cao @flashhu @lsvih  🍻  已经发布啦！～
- [x] Published at https://juejin.cn/post/6917192648424390669
- [x] Published at https://zhuanlan.zhihu.com/p/344064333
- [x] https://www.bilibili.com/read/cv9259870
