### ISSUE TITLE
2021 年 Web 应用开发常用的五个图标库

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7840]
* 原文链接：[Top 5 Icon Packs for Web Apps in 2021](https://blog.bitsrc.io/top-5-icon-packs-for-web-apps-in-2021-f0321653980e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/top-5-icon-packs-for-web-apps-in-2021.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的~
