### ISSUE TITLE
打开简历的正确方法 Have a design portfolio? Great, but that’s not enough

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7843]
- 原文链接：https://medium.com/design-bootcamp/dont-show-me-your-design-portfolio-e46053651055
- 简要介绍：打开简历的正确方法

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐设计
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

个人觉得嘛，这个东西不仅适用于设计师，对每个人的简历设计或许都有用吧（

**Comment by lsvih** [comment]
#7888 已发布，感谢推荐！
