### ISSUE TITLE
为什么 React Hooks 是错误的抽象

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7856]
* 原文链接：[Why React Hooks Are the Wrong Abstraction](https://medium.com/better-programming/why-react-hooks-are-the-wrong-abstraction-8a44437747c1)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/why-react-hooks-are-the-wrong-abstraction.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by fltenwall** [comment]
翻译认领

**Comment by lsvih** [comment]
@fltenwall 欢迎翻译！

**Comment by itcodes** [comment]
https://juejin.cn/post/6930529765048713229/ @lsvih

**Comment by lsvih** [comment]
收到
