### ISSUE TITLE
2020 年设计系统情况

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7858]
* 原文链接：[The State of Design Systems: 2020](https://material.io/blog/research-state-of-design-systems-2020)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/research-state-of-design-systems-2020.md)
* PR 地址：
* 文章分类：**设计**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：14 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领一下下～

**Comment by lsvih** [comment]
@PassionPenguin 好的~
