### ISSUE TITLE
I Got Into MIT, Refused the Offer, and Still Became a Highly Valued Developer

### ISSUE THREAD

**Issue by keepmovingljzy** [xitu/gold-miner#7859]
- 原文链接：https://medium.com/better-programming/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer-a4bff1b8cac2
- 简要介绍：作者拒绝了麻省理工的Offer，但仍然是一个高价值的开发者，作者介绍了自己的经历，很有价值，值得翻译一波~

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by keepmovingljzy** [comment]
@lsvih 这篇推荐文章我自己翻译，谢谢~

**Comment by lsvih** [comment]
抱歉这个之前漏了。。

**Comment by lsvih** [comment]
#7907 已发布认领，感谢推荐

这篇文章有点凡尔赛 XD
