### ISSUE TITLE
2019版设计年终总结

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7862]
- 原文链接：https://medium.com/google-design/state-of-design-systems-2019-ff5f26ada71
- 简要介绍：2019版设计年终总结

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文
* [x] Related to exist article. 
* [x] 自行翻译 

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by PassionPenguin** [comment]
reference to https://material.io/blog/research-state-of-design-systems-2020

**Comment by PassionPenguin** [comment]
@lsvih 幸苦啦

**Comment by lsvih** [comment]
#7905 已发布认领，请按流程提交译文~~

**Comment by lsvih** [comment]
PS：尽量让译文和原文的行对齐哈，方便校对

**Comment by PassionPenguin** [comment]
okok我会重新翻译一遍的

**Comment by lsvih** [comment]
@PassionPenguin 稍微对齐就好了哈，不用太麻烦了= =
