### ISSUE TITLE
构建应用时，你应该避免不必要的复杂性

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#787]
* 原文链接：[Avoiding Accidental Complexity When Structuring Your App State](https://hackernoon.com/avoiding-accidental-complexity-when-structuring-your-app-state-6e6d22ad5e2a#.g8yecdw1m)
* 掘金链接：[构建应用时，你应该避免不必要的复杂性](http://gold.xitu.io/entry/57f9fb12a22b9d005bf94caa/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/avoiding-accidental-complexity-when-structuring-your-app-state.md)
* PR 地址：[#805](https://github.com/xitu/gold-miner/pull/805)
* 文章分类：**前端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyseria** [comment]
认！

**Comment by sqrthree** [comment]
@cyseria 好的

**Comment by cyseria** [comment]
@sqrthree 最近有点事情略微忙，文章能找其他译者来帮忙么，谢谢~

**Comment by sqrthree** [comment]
@cyseria 好

**Comment by chemzqm** [comment]
认！

**Comment by sqrthree** [comment]
@chemzqm 好的，注意时间哈~~ 另外麻烦到 [wiki](https://github.com/xitu/gold-miner/wiki/译者擅长领域表) 填下这个把
