### ISSUE TITLE
掌握这 5 个 TypeScript 高级技巧，成为更好的开发者

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7878]
* 原文链接：[5 Advanced TypeScript Tips To Make You a Better Programmer](https://levelup.gitconnected.com/5-advanced-typescript-tips-to-make-you-a-better-programmer-bd4070aa2ab4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：15 天
* 校对时间：2 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Usualminds** [comment]
@lsvih  翻译认领

**Comment by lsvih** [comment]
@Usualminds 好的~
