### ISSUE TITLE
VUE 和 VUEX 中的数据流

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#788]
* 原文链接：[DATA FLOW IN VUE AND VUEX](https://benjaminlistwon.com/blog/data-flow-in-vue-and-vuex/)
* 掘金链接：[VUE 和 VUEX 中的数据流](http://gold.xitu.io/entry/57fb432c2e958a005593ab5c/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/data-flow-in-vue-and-vuex.md)
* PR 地址：[#800](https://github.com/xitu/gold-miner/pull/800)
* 文章分类：**前端 Vue**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by llp0574** [comment]
get

**Comment by sqrthree** [comment]
@llp0574 Great.

**Comment by llp0574** [comment]
[PR地址](https://github.com/xitu/gold-miner/pull/800)
