### ISSUE TITLE
2021 年 JavaScript 测试框架回顾

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7880]
* 原文链接：[A Review of JavaScript Testing Frameworks in 2021](https://medium.com/javascript-in-plain-english/a-review-of-javascript-testing-frameworks-in-2021-fe5934567c2a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/a-review-of-javascript-testing-frameworks-in-2021.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领

**Comment by lsvih** [comment]
@PassionPenguin 好的（建议一次不要领这么多，给别人留一些..

**Comment by PassionPenguin** [comment]
发布啦 @lsvih @zenblo @Ashira97 

- [x] https://juejin.cn/post/6927585452253790216
- [x] https://zhuanlan.zhihu.com/p/350367389
- [x] https://www.bilibili.com/read/preview/9761139
