### ISSUE TITLE
你应该知道的 3 个罕见的 Bash 技巧

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7882]
* 原文链接：[3 Uncommon Bash Tricks That You Should Know](https://medium.com/better-programming/3-uncommon-bash-tricks-that-you-should-know-c0fc988065c7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/3-uncommon-bash-tricks-that-you-should-know.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：3.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领

**Comment by lsvih** [comment]
@PassionPenguin 好的
