### ISSUE TITLE
深入了解 JavaScript 模块

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7884]
* 原文链接：[A Deep Dive Into JavaScript Modules](https://blog.bitsrc.io/a-deep-dive-into-javascript-modules-550ad88d8839)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/a-deep-dive-into-javascript-modules.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：15 天
* 校对时间：3 天
* 翻译积分：6.5 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by regon-cao** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@regon-cao 好的~
