### ISSUE TITLE
Javascript Memoization 入门指南

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7886]
* 原文链接：[A Beginner’s Guide to Memoization with JavaScript](https://blog.bitsrc.io/a-beginners-guide-to-memoization-with-javascript-59d9c818f4c8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/a-beginners-guide-to-memoization-with-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领

**Comment by lsvih** [comment]
@PassionPenguin 等你把手头的几篇弄完再认领叭。。

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好的~
