### ISSUE TITLE
你有设计作品的作品集吗？挺好的，但这还不够

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7888]
* 原文链接：[Have a design portfolio? Great, but that’s not enough](https://medium.com/design-bootcamp/dont-show-me-your-design-portfolio-e46053651055)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/dont-show-me-your-design-portfolio.md)
* PR 地址：
* 文章分类：**设计**，**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：20 天
* 校对时间：5 天
* 翻译积分：10 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领～

**Comment by lsvih** [comment]
@PassionPenguin 好的
