### ISSUE TITLE
Swift 中的面向接口编程是如何点亮我的人生的

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#789]
* 原文链接：[How Protocol Oriented Programming in Swift saved my day?](https://medium.com/ios-os-x-development/how-protocol-oriented-programming-in-swift-saved-my-day-75737a6af022)
* 掘金链接：[Swift 中的面向接口编程是如何点亮我的人生的](http://gold.xitu.io/entry/57d114a20e3dd90069be3878/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-protocol-oriented-programming-in-swift-saved-my-day.md)
* PR 地址：[#796](https://github.com/xitu/gold-miner/pull/796)
* 文章分类：**iOS**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Danny1451** [comment]
申请认领

**Comment by sqrthree** [comment]
@Danny1451 好的~ 顺便到 [wiki](https://github.com/xitu/gold-miner/wiki/译者擅长领域表) 里填下你的信息哈~~
