### ISSUE TITLE
使用 Lottie 在 Flutter 应用中制作原生启动页

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7898]
- 原文链接：https://medium.com/swlh/native-splash-screen-in-flutter-using-lottie-121ce2b9b0a4
- 简要介绍：Lottie在Flutter的implementation

---

* [x] 按文章分类填写 issue 标题：推荐Android/iOS/Flutter
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
#7981 已发布认领，感谢推荐
