### ISSUE TITLE
与时俱进的 Reactivity

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#790]
* 原文链接：[Modernization of Reactivity](https://davidwalsh.name/modernization-reactivity)
* 掘金链接：[Reactivity 的现代化](http://gold.xitu.io/entry/57de48b467f3560056aa3652)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/modernization-reactivity.md)
* PR 地址：[811](https://github.com/xitu/gold-miner/pull/811)
* 文章分类：**前端**

----
* 翻译时间：`4~5` 天
* 校对时间：`2` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lizwangying** [comment]
认领认领

**Comment by sqrthree** [comment]
@lizwangying 好的，还请到 [wiki](https://github.com/xitu/gold-miner/wiki/译者擅长领域表) 里填下你的信息哈~

**Comment by lizwangying** [comment]
好的

**Comment by sqrthree** [comment]
@lizwangying 这篇文章的进度怎么样了呀！！！！！

**Comment by lizwangying** [comment]
不好意思，应该昨晚交的，结果搬家这事闹的我最近没空翻译，明晚可以提交……真的对不起了……

**Comment by lizwangying** [comment]
今天还在搬家，所以晚上翻译下，明天调整下，下班前应该可以提交……

**Comment by lizwangying** [comment]
真的不好意思了……积分我就不领啦，想想还是深深歉意，现在能做的就是明天高质量的提交。再次抱歉……

**Comment by lizwangying** [comment]
我真的好不好意思哈……昨晚太困了睡着了，然后直接合上笔记本，然后自动关机了，没保存，今天到现在也没翻译完，我明天早起来翻译，争取中午提交……真心对不起

**Comment by sqrthree** [comment]
@lizwangying  Oh, no! I'm so sorry to hear that. Sublime Text, You really deserve it.

**Comment by lizwangying** [comment]
Haha, Nice, but I forgot..... I will use that from now on. Thanks for your kindness

**Comment by lizwangying** [comment]
翻译完啦~~~ @sqrthree

**Comment by sqrthree** [comment]
@lizwangying 好的~ 辛苦啦
