### ISSUE TITLE
使用 Flutter Container 构建优雅的布局

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7901]
- 原文链接：https://maneesha-erandi.medium.com/flutter-creating-elegant-uis-with-containers-1d05ca90fccf
- 简要介绍：使用 Flutter `Container` 构建优雅的布局（简述 `Container` 的使用）

---

* [x] 按文章分类填写 issue 标题：推荐前端/Flutter
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
#7911 已发布认领，感谢推荐
