### ISSUE TITLE
Medium 鼓掌的动画制作教程

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7902]
- 原文链接：https://proandroiddev.com/flutter-animation-creating-mediums-clap-animation-in-flutter-3168f047421e
- 简要介绍：Medium 鼓掌的动画制作教程

---

* [x] 按文章分类填写 issue 标题：推荐前端/Flutter
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by PassionPenguin** [comment]
这篇我自己翻译哈

**Comment by lsvih** [comment]
#8421 已发布认领，感谢推荐
