### ISSUE TITLE
使用 Angular 6/8 构建一个真实的美丽的 Web 应用程序

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7903]
- 原文链接：见下文
- 简要介绍：40k 的 Angular 教程项目，一共有2part

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

唯一搜到part1有一篇机译在简书上，看了看格式啊翻译语言都是乱的

[part 1](https://hamedbaatour.medium.com/build-a-real-world-beautiful-web-app-with-angular-6-a-to-z-ultimate-guide-2018-part-i-e121dd1d55e)
[part 2](https://hamedbaatour.medium.com/build-a-real-world-beautiful-web-app-with-angular-8-the-ultimate-guide-2019-part-ii-fe70852b2d6d)

Part I 有 40k 鼓掌，Part II 有1.6k 鼓掌

> （就是感觉有些过时了）

**Comment by lsvih** [comment]
angular 没啥人看的...

**Comment by PassionPenguin** [comment]
哈哈哈哈哈，但不得不说ng真的挺棒的（
就是这篇太老了...噗

**Comment by lsvih** [comment]
我也很喜欢 ng。。但是国内用 ng 的公司和开发者是真的少
