### ISSUE TITLE
我拒绝了 MIT 的 Offer，依然是一个高价值的开发者

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7907]
* 原文链接：[I Got Into MIT, Refused the Offer, and Still Became a Highly Valued Developer](https://medium.com/better-programming/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer-a4bff1b8cac2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：14 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由@keepmovingljzy 认领

**Comment by keepmovingljzy** [comment]
@lsvih 翻译完成
