### ISSUE TITLE
构建和 `Messenger` 一样的 ImageView

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7909]
* 原文链接：[Messengers-like ImageView](https://proandroiddev.com/messengers-like-imageview-90e9f1da19f4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/messengers-like-imageview.md)
* PR 地址：
* 文章分类：**Android**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：13 天
* 校对时间：3 天
* 翻译积分：6.5 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领：）

**Comment by keepmovingljzy** [comment]
@lsvih 认领校对
