### ISSUE TITLE
给跨平台应用开发者的 4 个小 tips

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#791]
* 原文链接：[4 must-know tips for building cross platform Electron apps](https://blog.avocode.com/blog/4-must-know-tips-for-building-cross-platform-electron-apps)
* 掘金链接：[给跨平台应用开发者的 4 个小 tips](http://gold.xitu.io/entry/57fb441b0bd1d00058c90103/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/4-must-know-tips-for-building-cross-platform-electron-apps.md)
* PR 地址：[#798](https://github.com/xitu/gold-miner/pull/798)
* 文章分类：**前端 Electron**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by huanglizhuo** [comment]
认领 @sqrthree

**Comment by sqrthree** [comment]
@huanglizhuo 好哒~ 顺便看下这个哈 [wiki](https://github.com/xitu/gold-miner/wiki/%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88#%E8%AE%A4%E9%A2%86%E7%BF%BB%E8%AF%91%E4%BB%BB%E5%8A%A1%E6%97%B6%E6%9C%89%E6%B2%A1%E6%9C%89%E6%9D%A1%E4%BB%B6%E9%99%90%E5%88%B6)，在 [这个](https://github.com/xitu/gold-miner/wiki/译者擅长领域表) 填一下信息吧~~
