### ISSUE TITLE
使用 Flutter 的 Container 控件构建优美的用户界面

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7911]
* 原文链接：[Flutter — Creating Elegant UIs with Containers](https://maneesha-erandi.medium.com/flutter-creating-elegant-uis-with-containers-1d05ca90fccf)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/flutter-creating-elegant-uis-with-containers.md)
* PR 地址：
* 文章分类：**Flutter**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：1.5 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领：）
