### ISSUE TITLE
如何让 JavaScript 中的循环慢下来

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7913]
* 原文链接：[How To Slow Down A For-Loop in JavaScript](https://medium.com/javascript-in-plain-english/javascript-slow-down-for-loop-9d1caaeeeeed)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/how-to-slow-down-a-for-loop-in-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
这文章好水啊哈哈哈哈哈
翻译认领：）

要是我写估计直接settimeout，或者其实这种方式slow down并非人为指定，要真正意义上部分步骤停顿那就是简简单单async Promise到时间再start promise

**Comment by lsvih** [comment]
```
import sleep from 'await-sleep'
```

**Comment by PassionPenguin** [comment]
> ```
> import sleep from 'await-sleep'
> ```

https://net2.com/how-to-shut-down-restart-suspend-and-hibernate-linux/
