### ISSUE TITLE
揭开图着色算法的神秘面纱

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7915]
* 原文链接：[Demystify Graph Coloring Algorithms](https://medium.com/better-programming/demystify-graph-coloring-algorithms-9ae51351ea5b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/demystify-graph-coloring-algorithms.md)
* PR 地址：
* 文章分类：**算法**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
这是加权图嘛？（萌新发言

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的！
