### ISSUE TITLE
人人都能够理解的身份认证和授权访问

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7918]
* 原文链接：[Authorization and Authentication For Everyone](https://dev.to/kimmaida/authorization-and-authentication-for-everyone-27j3)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/authorization-and-authentication-for-everyone.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：20 天
* 校对时间：5 天
* 翻译积分：11 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ashira97** [comment]
@lsvih 翻译认领~

**Comment by lsvih** [comment]
@Ashira97 欢迎认领，这篇文章还是挺长的，加油！

**Comment by Ashira97** [comment]
哈哈哈~ 好的~
