### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by freeOnex** [xitu/gold-miner#792]
你好，我叫 Ryan，现在一家互联网公司任职 Android开发经理，有计算机和英语两个专业背景，有纯英文工作的经历。现在经常浏览Medium，Github，android官网，希望能加入翻译计划，相互学习！

**Comment by antonia0912** [comment]
@freeOnex 欢迎来到掘金翻译计划，请加我微信 antonia0912 备注 github id 我来拉你进译者群
