### ISSUE TITLE
为什么你应该使用 Picture 标签而不是 Img 标签

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7923]
* 原文链接：[Why You Should Use Picture Tag Instead of  Img Tag](https://blog.bitsrc.io/why-you-should-use-picture-tag-instead-of-img-tag-b9841e86bf8b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by plusmultiply0** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@plusmultiply0 好的~
