### ISSUE TITLE
在 TypeScript 中引入 JSON 模块

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7925]
* 原文链接：[Importing JSON Modules in TypeScript](https://mariusschulz.com/blog/importing-json-modules-in-typescript)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/importing-json-modules-in-typescript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：1 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领～

**Comment by lsvih** [comment]
@PassionPenguin 好的

**Comment by lsvih** [comment]
@PassionPenguin 好的
