### ISSUE TITLE
telegram 的图片上传动画

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7928]
- 原文链接：https://proandroiddev.com/telegram-like-uploading-animation-e284f1404f63
- 简要介绍：telegram 的图片上传动画，似乎与 #7909 是同一类型/系列的
---

* [x] 按文章分类填写 issue 标题：推荐Android
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by PassionPenguin** [comment]
这篇我自己翻译哈

**Comment by lsvih** [comment]
#8422 已发布认领，感谢推荐
