### ISSUE TITLE
Android 11 上的机器学习

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7929]
- 原文链接：https://proandroiddev.com/machine-learning-with-android-11-whats-new-1a8d084c7398
- 简要介绍：Android 11 上的机器学习

---

* [x] 按文章分类填写 issue 标题：推荐Android
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
#8003 已发布认领，感谢推荐！
