### ISSUE TITLE
Facebook 发布了新的 Node 模块管理器 Yarn，或取代 npm

### ISSUE THREAD

**Issue by antonia0912** [xitu/gold-miner#793]
* 原文链接：[Yarn: A new package manager for JavaScript](https://code.facebook.com/posts/1840075619545360)
* 掘金链接：[Facebook 发布了新的 Node 模块管理器 Yarn，或取代 npm](http://gold.xitu.io/entry/57fd0b98d203090068db194e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/facebook-yarn-a-new-package-manager.md)
* 文章分类：**前端 JavaScript**

----
* 翻译完成时间：10月13日周四上午8点前
* 校对完成时间：10月13日周四下午3点前
* 翻译积分：`5` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**请务必确定自己能在规定时间内翻译完成再认领，此文章为紧急类**译者需要等管理员来审核

**Comment by Zhangjd** [comment]
认领

**Comment by sqrthree** [comment]
@Zhangjd 好的~

**Comment by antonia0912** [comment]
@Zhangdroid 达仔  注意翻译完成时间哈

**Comment by Zhangjd** [comment]
突然想起来，这篇文章的积分没加上去呢

**Comment by sqrthree** [comment]
@Zhangjd 😯 一会就加~ 疏忽了
