### ISSUE TITLE
RxJava2 与 Kotlin 数据流的结合

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7931]
- 原文链接：https://proandroiddev.com/from-rxjava-2-to-kotlin-flow-threading-8618867e1955
- 简要介绍：RxJava2 与 Kotlin 数据流的结合

---

* [x] 按文章分类填写 issue 标题：推荐Android
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
#7974 已发布认领，感谢推荐
