### ISSUE TITLE
表单的设计（指正错误的表单设计，如控件的不同用法）

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#7932]
- 原文链接：https://medium.com/nextux/design-better-forms-96fadca0f49c
- 简要介绍：表单的设计（指正错误的表单设计，如控件的不同用法）

---

* [x] 按文章分类填写 issue 标题：推荐设计
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
这篇文章挺经典的了

https://zhuanlan.zhihu.com/p/22253501

**Comment by PassionPenguin** [comment]
没搜到（

> 这篇文章挺经典的了
> 
> https://zhuanlan.zhihu.com/p/22253501
