### ISSUE TITLE
SwiftUI 2 应用生命周期的终极指导

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7934]
* 原文链接：[The Ultimate Guide to the SwiftUI 2 Application Life Cycle](https://peterfriese.dev/ultimate-guide-to-swiftui2-application-lifecycle/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhuzilin** [comment]
申请翻译~

**Comment by lsvih** [comment]
@zhuzilin 欢迎认领！
