### ISSUE TITLE
2021 年 JavaScript 的前景

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7936]
* 原文链接：[The JavaScript Landscape in 2021](https://medium.com/javascript-in-plain-english/the-javascript-landscape-in-2021-573d5e7a43c6)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/the-javascript-landscape-in-2021.md)
* PR 地址：
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by regon-cao** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@regon-cao 好的~
