### ISSUE TITLE
缓存踩踏事件是如何导致 Facebook 最大的宕机事件之一发生的

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7938]
* 原文链接：[How A Cache Stampede Caused One Of Facebook’s Biggest Outages](https://medium.com/better-programming/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages-dbb964ffc8ed)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：20 天
* 校对时间：5 天
* 翻译积分：11 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领：）

**Comment by lsvih** [comment]
@PassionPenguin 好的

**Comment by PassionPenguin** [comment]
Published at https://juejin.cn/post/6989528598365339662

**Comment by lsvih** [comment]
收到~
