### ISSUE TITLE
Declarative API 在 Swift 语言中的设计

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#794]
* 原文链接：[Declarative API Design in Swift](http://blog.benjamin-encz.de/post/declarative-api-design-in-swift/)
* 掘金链接：[Declarative API 在 Swift 语言中的设计](http://gold.xitu.io/entry/57fcc6a50e3dd90057d46f9c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/declarative-api-design-in-swift.md)
* PR 地址：[#819](https://github.com/xitu/gold-miner/pull/819)
* 文章分类：**iOS**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zheaoli** [comment]
苟利国家生死以，岂因祸福避趋之

收了

**Comment by sqrthree** [comment]
@Zheaoli Great.

**Comment by sqrthree** [comment]
@Zheaoli 这篇的文章进度如何了呀？
