### ISSUE TITLE
如何为空间索引创建高教的数据结构

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7941]
* 原文链接：[How do you create an Efficient Data Structure for Spatial Indexing?](https://edward-huang.com/algorithm/programming/tech/java/2021/01/11/data-structure-for-spatial-indexing/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/how-do-you-create-an-efficient-data-structure-for-spatial-indexing.md)
* PR 地址：
* 文章分类：**算法**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by lsvih** [comment]
@Starriers 欢迎翻译！~
