### ISSUE TITLE
推荐前端优秀英文文章

### ISSUE THREAD

**Issue by flashhu** [xitu/gold-miner#7942]
- 原文链接：[We’ve analysed 500,000 browser fingerprints. Here is what we found.](https://medium.com/slido-dev-blog/we-collected-500-000-browser-fingerprints-here-is-what-we-found-82c319464dc9)
- 简要介绍：简单介绍了浏览器指纹的概念，用途及现状

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by PassionPenguin** [comment]
interesting result 但毫不意外，毕竟移动端的设备的隐身模式可以常开，而桌面端如果不设置open-argument，总是得手动再次开启，麻烦死了

**Comment by PassionPenguin** [comment]
况且为了工作效率，一般来说cookies啊这些保留什么的还是挺重要的

**Comment by lsvih** [comment]
#7977 已发布认领，感谢推荐！
