### ISSUE TITLE
推荐优秀 iOS 英文文章

### ISSUE THREAD

**Issue by zhuzilin** [xitu/gold-miner#7944]
- 原文链接：https://medium.com/@anuragajwani/how-to-consume-c-code-in-swift-b4d64a04e989
- 简要介绍：一篇比较新的介绍如何在 Swift 中使用 C++ 的文章。不过感觉文末的项目推广就不用搬了~

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by PassionPenguin** [comment]
看来 Swift / Objc 以及 Java / Kotlin 与原生 C++ 之间的 interface 一样的变态（

**Comment by zhuzilin** [comment]
> 看来 Swift / Objc 以及 Java / Kotlin 与原生 C++ 之间的 interface 一样的变态（

@PassionPenguin 
Swift 貌似支持原生的 C header，而 C++ 里面的 template 黑魔法太多了，所以在慢慢做。
some references:
[1] https://forums.swift.org/t/manifesto-interoperability-between-swift-and-c/33874
[2] https://forums.swift.org/t/how-developed-is-c-interoperability/42429

**Comment by PassionPenguin** [comment]
> > 看来 Swift / Objc 以及 Java / Kotlin 与原生 C++ 之间的 interface 一样的变态（
> 
> @PassionPenguin
> Swift 貌似支持原生的 C header，而 C++ 里面的 template 黑魔法太多了，所以在慢慢做。
> some references:
> [1] https://forums.swift.org/t/manifesto-interoperability-between-swift-and-c/33874
> [2] https://forums.swift.org/t/how-developed-is-c-interoperability/42429

其实光是看 Java 看到各种各样的 JString 那些不同的 type 转换就心累（

**Comment by zhuzilin** [comment]
> 其实光是看 Java 看到各种各样的 JString 那些不同的 type 转换就心累（

嗯，这是我最开始选择尝试 Swift 和 iOS 那条路的很重要一点:joy: 不太想碰 java 那一套东西...

**Comment by lsvih** [comment]
这篇是不是有翻译了= = 

https://blog.csdn.net/weixin_26711867/article/details/108971301

**Comment by zhuzilin** [comment]
@lsvih 啊，还真是...抱歉...

**Comment by lsvih** [comment]
@zhuzilin 感谢推荐= =
