### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Yannyezixin** [xitu/gold-miner#795]
掘金您好！我叫Yannyezixin，是广东工业大学的在校大四学生，现实习于广州大学城一家创业公司，我具有良好的英语阅读能力，时常浏览国外网站主要有google/wiki/Github/Stackoverflow/等, 博客为[鲲鹏之志](http://youbookee.com)
希望能够加入掘金翻译计划！共同学习提高！谢谢！

**Comment by antonia0912** [comment]
@Yannyezixin 欢迎来到掘金翻译计划，请加我微信 antonia0912 备注 github id 我来拉你进译者群
