### ISSUE TITLE
简述 HTTP 请求与跨域资源共享 CORS

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7960]
* 原文链接：[An Overview of HTTP Requests & Cross-Origin Resource Sharing (CORS)](https://medium.com/javascript-in-plain-english/quick-overview-of-http-requests-cross-origin-resource-sharing-cors-db139b41d71)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md)
* PR 地址：
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的
