### ISSUE TITLE
数据科学中的 9 种距离度量

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7962]
* 原文链接：[9 Distance Measures in Data Science](https://towardsdatascience.com/9-distance-measures-in-data-science-918109d069fa)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/9-distance-measures-in-data-science.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：16 天
* 校对时间：3 天
* 翻译积分：9 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译完成后我把图片换成 latex 公式

**Comment by chzh9311** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@chzh9311 好的~
