### ISSUE TITLE
我后悔没有在成为 React 开发者之时做的 6 件事

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7964]
* 原文链接：[6 Regrets I Have As a React Developer](https://medium.com/better-programming/6-regrets-i-have-as-a-react-developer-52e95a8ff8a4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/6-regrets-i-have-as-a-react-developer.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领

这篇文章说到心头上了，但应该再加一个：语句分类

类似的 Flutter 项目真的是，不断嵌套什么的，嵌套一百层不是问题

**Comment by lsvih** [comment]
@PassionPenguin 欢迎认领
