### ISSUE TITLE
为什么我还在用Lisp（而且你也应该用）

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7966]
* 原文链接：[Why I Still Lisp (and You Should Too)](https://medium.com/better-programming/why-i-still-lisp-and-you-should-too-18a2ae36bd8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/why-i-still-lisp-and-you-should-too.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：25 天
* 校对时间：5 天
* 翻译积分：12 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by elliott-zhao** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@elliott-zhao 好的~

**Comment by PassionPenguin** [comment]
@lsvih https://juejin.cn/post/6935225210278772766
