### ISSUE TITLE
如何在浏览器上使用 NoSQL 数据库 IndexedDB

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7968]
* 原文链接：[How to Use IndexedDB — A NoSQL DB on the Browser](https://blog.bitsrc.io/how-to-use-indexeddb-a-nosql-db-on-the-browser-f845da3caf35)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 我先把这篇翻译吧，昨天那篇要稍微久一点时间

**Comment by lsvih** [comment]
@zenblo 好的~
