### ISSUE TITLE
如何基于已有的 REST API 实现 GraphQL API

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7972]
* 原文链接：[How to Implement a GraphQL API on Top of an Existing REST API](https://codeburst.io/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api-db8b343ddb5a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好的~

**Comment by samyu2000** [comment]
@lsvih 翻译完成
