### ISSUE TITLE
从 RxJava 2 转向使用 Kotlin 流：多线程

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7974]
* 原文链接：[From RxJava 2 to Kotlin Flow: Threading](https://proandroiddev.com/from-rxjava-2-to-kotlin-flow-threading-8618867e1955)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/from-rxjava-2-to-kotlin-flow-threading.md)
* PR 地址：
* 文章分类：**Kotlin**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：23 天
* 校对时间：5 天
* 翻译积分：12 分
* 校对积分：6 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领翻译

**Comment by lsvih** [comment]
@PassionPenguin 好的，这篇比较长，慢慢来哈

**Comment by PassionPenguin** [comment]
这个也忘了……
