### ISSUE TITLE
在 Flutter 项目中使用 Lottie 构建原生 Splash 启动页

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7981]
* 原文链接：[Native Splash Screen in Flutter Using Lottie](https://medium.com/swlh/native-splash-screen-in-flutter-using-lottie-121ce2b9b0a4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/native-splash-screen-in-flutter-using-lottie.md)
* PR 地址：
* 文章分类：**Flutter**，**Android**，**iOS**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领ψ(｀∇´)ψ

**Comment by lsvih** [comment]
@PassionPenguin 好的~
