### ISSUE TITLE
代码可视化 － 使用图技术为 Python 项目绘制结构图

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7995]
* 原文链接：[Building a Map of Your Python Project Using Graph Technology — Visualize Your Code](https://towardsdatascience.com/building-a-map-of-your-python-project-using-graph-technology-visualize-your-code-6764e81f3500)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/building-a-map-of-your-python-project-using-graph-technology-visualize-your-code.md)
* PR 地址：
* 文章分类：**后端**，**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：17 天
* 校对时间：3 天
* 翻译积分：8 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ashira97** [comment]
@lsvih 翻译认领~

**Comment by lsvih** [comment]
@Ashira97 欢迎认领
