### ISSUE TITLE
为什么 Service Mesh 应该淡出人们的视野

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#7997]
* 原文链接：[Why the Service Mesh Should Fade Out of Sight](https://medium.com/better-programming/why-the-service-mesh-should-fade-out-of-sight-878bfd30f5a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/why-the-service-mesh-should-fade-out-of-sight.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by nettee** [comment]
翻译认领

**Comment by nettee** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@nettee 好的~
