### ISSUE TITLE
苹果正在带坏整个设计圈

### ISSUE THREAD

**Issue by crackhy** [xitu/gold-miner#8]
我翻译这篇吧

**Comment by Glowin** [comment]
好的呢，刚刚在 #6 里回复你了

**Comment by crackhy** [comment]
内容比较多，短时间内完不成，有截止日期吗

**Comment by Glowin** [comment]
没问题，元旦后也可以的，这篇文章确实很长，你不用太赶。
曹康 <notifications@github.com>于2015年12月25日 周五下午9:06写道：

**Comment by crackhy** [comment]
好的。

**Comment by Glowin** [comment]
你好，我拉了一个掘金翻译计划译者的微信群，译者都在群里面，我会在群里面更新活动的最新进展，如果方便的话可以加我一下微信 Glowjiang。
