### ISSUE TITLE
通过集群提高 Node.js 应用程序性能

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8001]
* 原文链接：[Improving Node.js Application Performance With Clustering](https://blog.appsignal.com/2021/02/03/improving-node-application-performance-with-clustering.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/improving-node-application-performance-with-clustering.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：17 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的
