### ISSUE TITLE
使用 Android 11 进行机器学习：新功能

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8003]
* 原文链接：[Machine Learning with Android 11: What’s new](https://proandroiddev.com/machine-learning-with-android-11-whats-new-1a8d084c7398)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/machine-learning-with-android-11-whats-new.md)
* PR 地址：
* 文章分类：**Android**，**AI**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：19 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领 ψ(｀∇´)ψ

**Comment by lsvih** [comment]
@PassionPenguin 好的~

**Comment by keepmovingljzy** [comment]
@lsvih 认领校对
