### ISSUE TITLE
使用 Kafka、MongoDB 和 Maxwell's Daemon 构建 SQL 数据库审计系统

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8010]
* 原文链接：[Building an SQL Database Audit System Using Kafka, MongoDB and Maxwell's Daemon](https://www.infoq.com/articles/database-audit-system-kafka/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/Building-an-SQL-Database-Audit-System-Using-Kafka%2C-MongoDB-and-Maxwell's-Daemon.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：13 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by joyking7** [comment]
@itcodes 翻译认领

**Comment by lsvih** [comment]
@joyking7 欢迎认领！

**Comment by lsvih** [comment]
@joyking7 哈哈好的

**Comment by PassionPenguin** [comment]
哈喽 @joyking7 记得发布嗷
