### ISSUE TITLE
我希望多年前就知道的 Nginx 概念

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8011]
* 原文链接：[Nginx concepts I wish I knew years ago(Nginx concepts I wish I knew years ago)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/Nginx%20concepts%20I%20wish%20I%20knew%20years%20ago.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：3 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by joyking7** [comment]
@itcodes 翻译认领

**Comment by itcodes** [comment]
@joyking7 欢迎认领

**Comment by PassionPenguin** [comment]
哈喽 @joyking7 记得发布嗷

**Comment by itcodes** [comment]
https://juejin.cn/post/6948810167618109448  @lsvih 这个已经发布。

**Comment by lsvih** [comment]
收到
