### ISSUE TITLE
恭喜 Safari 荣获「第二个 Internet Explorer」的美誉

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8013]
* 原文链接：[Safari Has Become The Second Internet Explorer](https://medium.com/javascript-in-plain-english/safari-has-become-the-second-internet-explorer-e2c2dd114837)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/safari-has-become-the-second-internet-explorer.md)
* PR 地址：
* 文章分类：**其他**，**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
笑死了这个标题

**Comment by PassionPenguin** [comment]
认领认领，认领这个垃圾 Safari ¯\_(ツ)_/¯

**Comment by lsvih** [comment]
@PassionPenguin 欢迎吐槽
