### ISSUE TITLE
3 个最棒的最值得你去在产品中使用的 CSS Grid 功能

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8018]
* 原文链接：[Top 3 CSS Grid Features To Start Using in Production](https://medium.com/better-programming/top-3-css-grid-features-to-start-using-in-production-b0fe59b2e0f7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/top-3-css-grid-features-to-start-using-in-production.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领 ψ(｀∇´)ψ

**Comment by lsvih** [comment]
好的
