### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Edison-Hsu** [xitu/gold-miner#802]
Hello, 我想成为译者，之前完成了RxSwift的中文文档翻译，想加入更大的团队互相学习

- 公司/学校：上海相誉网络科技有限公司
- 工作内容/专业：前端工程师 / 软件工程，互联网5级水管工
- 擅长领域：`后端`, `前端`, `iOS`
- 常浏览的国外网站：[Stackoverflow](http://stackoverflow.com/),  [Hacker News](https://news.ycombinator.com/), [Quora](https://www.quora.com/)
- 英语水平/有无翻译经验: [RxSwfit 中文文档](https://github.com/jhw-dev/RxSwift-CN)
- 个人博客：[Blog](http://edison-hsu.com)

**Comment by antonia0912** [comment]
@Edison-Hsu 欢迎来到掘金翻译计划，请加我微信 antonia0912 备注 github id 我来拉你进译者群
