### ISSUE TITLE
使用 CSS Painting API 自动生成图像

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8020]
* 原文链接：[Programmatically generate images with CSS Painting API](https://blog.bitsrc.io/programmatically-generate-images-with-css-painting-api-3b1a860dae3b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/programmatically-generate-images-with-css-painting-api.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：1 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领 ψ(｀∇´)ψ

**Comment by lsvih** [comment]
好的
