### ISSUE TITLE
2021 年应该了解的 34 种优化 JavaScript 的方法

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#8026]
- 原文链接：34 JavaScript Optimization Techniques to Know in 2021
- 存在机译：https://www.isolves.com/it/cxkf/yy/js/2021-01-11/35302.html
- 简要介绍：2021 年应该了解的 34 种优化 JavaScript 的方法

---

* [x] 按文章分类填写 issue 标题：推荐前端
* [x] 本文很值得翻译，我推荐
* [ ] 已经过初步搜索，暂未发现中文版译文

存在的机译文章读起来非常别扭 = =

> 1.如果有多个条件
> 我们可以在数组中存储多个值，并且可以使用数组include方法。
> 
> 2.If true … else 简写
> 当我们具有不包含更大逻辑的if-else条件时，这是一个更大的捷径。我们可以简单地使用三元运算符来实现该速记。

**Comment by itcodes** [comment]
收到

**Comment by itcodes** [comment]
https://github.com/xitu/gold-miner/issues/8041 已经发布任务
