### ISSUE TITLE
6 CSS Properties Nobody Is Talking About

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#8027]
- 原文链接：https://medium.com/javascript-in-plain-english/6-css-properties-nobody-is-talking-about-e6cab5138d02
- 简要介绍：6 CSS Properties Nobody Is Talking About

---

* [x] 按文章分类填写 issue 标题：推荐前端
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
#8068 已发布认领，感谢推荐
