### ISSUE TITLE
Which type of loop is fastest in JavaScript?

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#8028]
- 原文链接：https://medium.com/javascript-in-plain-english/which-type-of-loop-is-fastest-in-javascript-ec834a0f21b9
- 简要介绍：Which type of loop is fastest in JavaScript?

---

* [x] 按文章分类填写 issue 标题：推荐前端
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

这个倒还真没有研究，不是哪个方便用哪个嘛（

**Comment by itcodes** [comment]
已经更新。https://github.com/xitu/gold-miner/issues/8040
