### ISSUE TITLE
承载了巨大访问量的热门游戏 Pokémon GO 的后端架构是什么？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#803]
* 原文链接：[Bringing Pokémon GO to life on Google Cloud](https://cloudplatform.googleblog.com/2016/09/bringing-Pokemon-GO-to-life-on-Google-Cloud.html)
* 掘金链接：[承载了巨大访问量的热门游戏 Pokémon GO 的后端架构是什么？](http://gold.xitu.io/entry/57fdfafaa22b9d005b178c21)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/bringing-Pokemon-GO-to-life-on-Google-Cloud.md)
* PR 地址：[#808](https://github.com/xitu/gold-miner/pull/808)
* 文章分类：**后端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cdpath** [comment]
认领这篇~

**Comment by sqrthree** [comment]
@cdpath 好的~ 顺便填下这个吧 [wiki](https://github.com/xitu/gold-miner/wiki/译者擅长领域表)

**Comment by shliujing** [comment]
我观望了2个小时，终于有人认领了。话说根号三同志还在上班，还是义务加班？
