### ISSUE TITLE
Rust in production at Figma

### ISSUE THREAD

**Issue by youngjuning** [xitu/gold-miner#8032]
- 原文链接：https://medium.com/figma-design/rust-in-production-at-figma-e10a0ec31929
- 简要介绍：How Mozilla’s new language dramatically improved our server-side performance

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by itcodes** [comment]
https://github.com/xitu/gold-miner/issues/8036 已经发布。该条issues将于5分钟后closed
