### ISSUE TITLE
Figma 生产中的 Rust

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8036]
* 原文链接：[Rust in production at Figma](https://medium.com/figma-design/rust-in-production-at-figma-e10a0ec31929)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/Rust%20in%20production%20at%20Figma.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：19 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领 @itcodes ψ(｀∇´)ψ
