### ISSUE TITLE
Bash IF-ELSE

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#8037]
- 原文链接：https://linuxize.com/post/bash-if-else-statement/
- 简要介绍：Bash IF-ELSE 介绍

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐后端/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by itcodes** [comment]
https://github.com/xitu/gold-miner/issues/8038 已经更新！
