### ISSUE TITLE
Bash 中的 if else 语句

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8038]
* 原文链接：[Bash if..else Statement](https://linuxize.com/post/bash-if-else-statement/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/Bash%20if..else%20Statement.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领 ψ(｀∇´)ψ @lsvih @itcodes
