### ISSUE TITLE
JavaScript 中哪一种循环更快呢？

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8040]
* 原文链接：[Which type of loop is fastest in JavaScript?](https://medium.com/javascript-in-plain-english/which-type-of-loop-is-fastest-in-javascript-ec834a0f21b9)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/Which-type-of-loop-is-fastest-in-JavaScript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领 ψ(｀∇´)ψ

**Comment by lsvih** [comment]
@PassionPenguin 好的
