### ISSUE TITLE
2021 年需要了解的 34 个 JavaScript 优化技巧

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8041]
* 原文链接：[34 JavaScript Optimization Techniques to Know in 2021
](https://medium.com/javascript-in-plain-english/34-javascript-optimization-techniques-to-know-in-2021-d561afdf73c3)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/34-javascript-optimization-techniques-to-know-in-2021.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@itcodes 翻译认领

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 欢迎翻译~

**Comment by samyu2000** [comment]
@lsvih 翻译完成
