### ISSUE TITLE
深入理解 Rust 所有权、借用、生命周期

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8045]
* 原文链接：[Understanding Rust: ownership, borrowing, lifetimes
](https://medium.com/@bugaevc/understanding-rust-ownership-borrowing-lifetimes-ff9ee9f79a9c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/understanding-rust-ownership-borrowing-lifetimes.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by youngjuning** [comment]
认领

**Comment by itcodes** [comment]
> @itcodes 翻译认领

辛苦！

**Comment by itcodes** [comment]
@youngjuning 好的

**Comment by youngjuning** [comment]
@itcodes 上周工作忙，这两天翻译完

**Comment by lsvih** [comment]
https://juejin.cn/post/6937098861152305160 已发布   @youngjuning 老哥下会儿您发完记得留个链接哈

**Comment by youngjuning** [comment]
@lsvih ojbk
