### ISSUE TITLE
The Why and How of Microservice Messaging in Kubernetes

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8050]
* 原文链接：[The Why and How of Microservice Messaging in Kubernetes](https://levelup.gitconnected.com/the-why-and-how-of-microservice-messaging-in-kubernetes-1d54a4717bf1)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/the-why-and-how-of-microservice-messaging-in-kubernetes.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by joyking7** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@joyking7 老哥稳
