### ISSUE TITLE
面向 JavaScript 开发人员的 Monads

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8058]
* 原文链接：[Monads For JavaScript Developers](https://js.plainenglish.io/monads-for-javascript-developers-af29819823c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/monads-for-javascript-developers.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好的~

**Comment by ZavierTang** [comment]
校对认领
