### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by luoyaqifei** [xitu/gold-miner#806]
您好，我叫luoyaqifei，关注掘金翻译计划很久了，想申请成为译者，以下是我的资料
公司：500强外企
工作内容：网站应用开发
常浏览的国外网站：Quora和Stackoverflow等
英语水平：六级
法语水平：B2
翻译经验：帮人翻译过几篇博士论文（中译英），加入过兼职翻译网站等
个人博客：[blog link](http://www.zengmingxia.com/)

**Comment by antonia0912** [comment]
@luoyaqifei 欢迎来到掘金翻译计划，请加我微信 antonia0912 备注 github id 我来拉你进译者群
