### ISSUE TITLE
How Jessica Alba Turned a Hopeless Situation into a Successful Business

### ISSUE THREAD

**Issue by keepmovingljzy** [xitu/gold-miner#8062]
- 原文链接：https://medium.com/swlh/how-jessica-alba-turned-a-hopeless-situation-into-a-successful-business-d6ecf9d02009
- 简要介绍：很多人都熟悉神奇四侠中的那个女主角，，这篇文章就是知名女星杰西卡·阿尔巴如何从低谷翻身的励志故事，值得翻译一下。

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by keepmovingljzy** [comment]
@lsvih 这篇文章我自己翻译哈

**Comment by itcodes** [comment]
> @lsvih 这篇文章我自己翻译哈

@keepmovingljzy 麻烦更新下原文链接。

**Comment by keepmovingljzy** [comment]
@itcodes 更新完毕

**Comment by keepmovingljzy** [comment]
@itcodes @lsvih
