### ISSUE TITLE
System Design Interview: All or None, Ordered Peer-to-Peer Broadcast

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8066]
* 原文链接：[System Design Interview: All or None, Ordered Peer-to-Peer Broadcast](https://levelup.gitconnected.com/system-design-interview-all-or-none-ordered-peer-to-peer-broadcast-45b33fb2f6be)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/system-design-interview-all-or-none-ordered-peer-to-peer-broadcast.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：14 天
* 校对时间：3 天
* 翻译积分：7分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by joyking7** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@joyking7 欢迎翻译→_→
