### ISSUE TITLE
6 个没人讲过的 CSS 属性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8068]
* 原文链接：[6 CSS Properties Nobody Is Talking About](https://js.plainenglish.io/6-css-properties-nobody-is-talking-about-e6cab5138d02)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/6-css-properties-nobody-is-talking-about.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领翻译 🍈

**Comment by lsvih** [comment]
@PassionPenguin 欢迎认领

**Comment by husiyu** [comment]
https://juejin.cn/post/6937995501719519240

**Comment by lsvih** [comment]
收到
