### ISSUE TITLE
Why Discord is switching from Go to Rust

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8069]
* 原文链接：[Why Discord is switching from Go to Rust
](https://blog.discord.com/why-discord-is-switching-from-go-to-rust-a190bbca2b1f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/why-discord-is-switching-from-go-to-rust.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by youngjuning** [comment]
@itcodes 翻译认领

**Comment by itcodes** [comment]
@youngjuning 辛苦。

**Comment by lsvih** [comment]
https://www.infoq.cn/article/0sce4vcqzm8jwc50jzsm 已完成
