### ISSUE TITLE
Using Rust to Scale Elixir for 11 Million Concurrent Users

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8070]
* 原文链接：[Using Rust to Scale Elixir for 11 Million Concurrent Users
](https://blog.discord.com/using-rust-to-scale-elixir-for-11-million-concurrent-users-c6f19fc029d3)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/8c2d0b214dd2ec96890c3c6e539dcff066731afa/article/2021/using-rust-to-scale-elixir-for-11-million-concurrent-users.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by youngjuning** [comment]
@itcodes 翻译认领

**Comment by lsvih** [comment]
https://segmentfault.com/a/1190000019360263 已完成
