### ISSUE TITLE
Swift 5.4 的新特性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8073]
* 原文链接：[What’s New in Swift 5.4?](https://medium.com/better-programming/whats-new-in-swift-5-4-88949071d538)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/whats-new-in-swift-5-4.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LoneyIsError** [comment]
翻译认领

**Comment by lsvih** [comment]
@LoneyIsError  欢迎翻译-。-  忘了回复了
