### ISSUE TITLE
5 Kotlin Extensions To Make Your Android Code More Expressive

### ISSUE THREAD

**Issue by keepmovingljzy** [xitu/gold-miner#8074]
- 原文链接：https://medium.com/better-programming/5-kotlin-extensions-to-make-your-android-code-more-expressive-4c9243cb9466
- 简要介绍：在 Kotlin 中 5 个应该扩展的设计，让代码更有可读性和便利性，值得翻译

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐Android优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by keepmovingljzy** [comment]
@lsvih 本文我自己翻译哈

**Comment by lsvih** [comment]
#8087 已发布认领，感谢推荐
