### ISSUE TITLE
关于 Node.js 中的异步迭代器

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8076]
- 原文链接：[About Async Iterators in Node.js](https://blog.risingstack.com/async-iterators-in-node-js/)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/About-Async-Iterators-in-Node.js.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：10 天
- 校对时间：2 天
- 翻译积分：3 分
- 校对积分：1 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Isildur46** [comment]
翻译认领
