### ISSUE TITLE
5 个 Kotlin 扩展技巧让你的 Android 代码更具表现力

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8087]
* 原文链接：[5 Kotlin Extensions To Make Your Android Code More Expressive](https://betterprogramming.pub/5-kotlin-extensions-to-make-your-android-code-more-expressive-4c9243cb9466)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/5-kotlin-extensions-to-make-your-android-code-more-expressive.md)
* PR 地址：
* 文章分类：**Kotlin**，**Android**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由@keepmovingljzy 认领

**Comment by keepmovingljzy** [comment]
@lsvih 翻译完成
