### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zhaochuanxing** [xitu/gold-miner#809]
中国海洋大学计算机小硕，android 两年开发者，主要开发手机和电视的应用，常浏览的国外网站有stackoverflow /android blog/Quora/Quora，自己翻译过android和tv几篇相关的博客。申请加入翻译计划，谢谢.

**Comment by antonia0912** [comment]
@zhaochuanxing 欢迎来到掘金翻译计划，请加我微信 antonia0912 备注 github id 我来拉你进译者群
