### ISSUE TITLE
推荐Kotlin优秀英文文章

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#8091]
- 原文链接：https://betterprogramming.pub/an-introduction-to-jetpack-compose-for-desktop-5c3bf8629dc5
- 简要介绍：An Introduction to Jetpack Compose for Desktop【Kotlin Jetpack Compose UI Windows】

* [x] 按文章分类填写 issue 标题：推荐Kotlin优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
#8705 已发布认领，感谢推荐
