### ISSUE TITLE
推荐Dart英文文章

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#8092]
- 原文链接：https://betterprogramming.pub/top-7-dart-tips-and-tricks-for-cleaner-flutter-apps-562664a15826
- 简要介绍：Top 7 Dart Tips and Tricks for Cleaner Flutter Apps【Dart 技巧】

* [x] 按文章分类填写 issue 标题
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
#8214 已发布认领，感谢推荐
