### ISSUE TITLE
推荐前端英文文章

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#8093]
- 原文链接：https://js.plainenglish.io/5-html-tricks-nobody-is-talking-about-a0480104fe19
- 简要介绍：5 HTML Tricks Nobody is Talking About【HTML技巧】

* [x] 按文章分类填写 issue 标题：推荐前端英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
这篇之前看到了，但是因为内容类似的文章太多了就没有添加，而且有人翻译过了 https://segmentfault.com/a/1190000039240225
