### ISSUE TITLE
Deno 将停用 TypeScript 的五个原因

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8094]
- 原文链接：[5 reasons why Deno will stop using TypeScript - StartFunction](https://startfunction.com/deno-will-stop-using-typescript/)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/5-reasons-why-Deno-will-stop-using-TypeScript-%20StartFunction.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：2 天
- 校对时间：1 天
- 翻译积分：4 分
- 校对积分：2 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@itcodes 翻译认领

**Comment by lsvih** [comment]
@itcodes 文件地址不太对

**Comment by lsvih** [comment]
@zenblo 欢迎翻译！

**Comment by itcodes** [comment]
官方发了。 @zenblo @lsvih 这类内容，我后续发出的时候备注下，我来校验，翻译速度嘛，期待越快越好。

**Comment by lsvih** [comment]
收到

**Comment by zenblo** [comment]
收到
