### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by fighting300** [xitu/gold-miner#810]
嗨, 你好，我是fighting300，关注掘金计划一段时间了，我想加入翻译计划，成为译者

公司：去哪儿网
工作内容：iOS开发
常浏览的国外网站：Stackoverflow，Quora
英语水平: 六级

**Comment by antonia0912** [comment]
@fighting300 hi 请问之前有翻译过英文文章吗？有没有个人博客呢？

**Comment by fighting300** [comment]
没有个人博客～

**Comment by waychane** [comment]
@fighting300 Hi，感谢支持掘金翻译计划，成为译者还是需要一定的审核资料，可以先在 gold.xitu.io 给我们投稿，这个 Issue 我先 close 喽。
