### ISSUE TITLE
自适应 CSS 栅格：自由布局的最终版本

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8106]
* 原文链接：[Responsive CSS Grid: The Ultimate Layout Freedom](https://medium.muz.li/understanding-css-grid-ce92b7aa67cb)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/understanding-css-grid.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领：）

**Comment by lsvih** [comment]
欢迎翻译
