### ISSUE TITLE
Typescript 4.2 Released, Improves Types and Developer Experience

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8114]
- 原文链接：[Typescript 4.2 Released, Improves Types and Developer Experience](https://www.infoq.com/news/2021/02/typescript-4-2-released/)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/Typescript-4-2-Released-Improves-Types-and-Developer-Experience.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：2 天
- 校对时间：1  天
- 翻译积分：3 分
- 校对积分：2 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领

**Comment by itcodes** [comment]
> 认领

。。。你认领太多了，能翻译得过来吗？比如这个我可能希望他更及时一点。

**Comment by PassionPenguin** [comment]
> > 认领
> 
> 。。。你认领太多了，能翻译得过来吗？比如这个我可能希望他更及时一点。

那几个翻译完了已经 = =

**Comment by itcodes** [comment]
https://juejin.cn/post/6935255387893399560 @lsvih

**Comment by lsvih** [comment]
收到
