### ISSUE TITLE
如何通过 ArrayMap 和 SparseArray 优化 Android App

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#812]
* 原文链接：[Android App Optimization Using ArrayMap and SparseArray](https://medium.com/@amitshekhar/android-app-optimization-using-arraymap-and-sparsearray-f2b4e2e3dc47#.w9iubhupn)
* 掘金链接：[如何通过 ArrayMap 和 SparseArray 优化 Android App](http://gold.xitu.io/entry/58071ee70bd1d00058266e28)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/android-app-optimization-using-arraymap-and-sparsearray.md)
* PR 地址：[#824](https://github.com/xitu/gold-miner/pull/824)
* 文章分类：**Android**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jamweak** [comment]
已经认领了一篇？还能认吗？如果没人要的话一起认了，短文好翻。 @sqrthree

**Comment by sqrthree** [comment]
@jamweak Yes, of course.

**Comment by jamweak** [comment]
@sqrthree 翻译完成。
