### ISSUE TITLE
重新审视 undefined 和 null

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8122]
* 原文链接：[undefined vs. null revisited](https://2ality.com/2021/01/undefined-null-revisited.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/undefined-null-revisited.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领：）

**Comment by lsvih** [comment]
@PassionPenguin 欢迎翻译
