### ISSUE TITLE
How an Anti-TypeScript “JavaScript developer” like me became a TypeScript fan

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8126]
- 原文链接：[How an Anti-TypeScript “JavaScript developer” like me became a TypeScript fan](https://chiragswadia.medium.com/how-an-anti-typescript-javascript-developer-like-me-became-a-typescript-fan-a4e043151ad7)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/edit/master/article/2021/how-an-anti-typescript-javascript-developer-like-me-became-a-typescript-fan.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：1 天
- 校对时间：1 天
- 翻译积分：5 分
- 校对积分：2 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领

**Comment by itcodes** [comment]
> 翻译认领

辛苦。

**Comment by lsvih** [comment]
已发布：https://juejin.cn/post/6935629277870161957
