### ISSUE TITLE
Deno 1.8 发行公告

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8129]
- 原文链接：[Deno 1.8 Release Notes](https://deno.land/posts/v1.8)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/Deno-1-8-Release-Notes.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：5 天
- 校对时间：1 天
- 翻译积分：5 分
- 校对积分：2 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领翻译

**Comment by husiyu** [comment]
Deno 1.8 正式发布：支持 WebGPU API、deno lsp 现在进入了稳定状态
https://juejin.cn/post/6936083986644992013

**Comment by lsvih** [comment]
收到
