### ISSUE TITLE
让 iOS 10 通知中心 Widgets 向后兼容的技巧

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#813]
* 原文链接：[Tips for Backwards Compatibility with iOS 10 Today Widgets](https://kristina.io/backwards-compatibility-with-ios-10-today-widgets/)
* 掘金链接：[让 iOS 10 通知中心 Widgets 向后兼容的技巧](http://gold.xitu.io/entry/58071d560bd1d00058265f86)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/backwards-compatibility-with-ios-10-today-widgets.md)
* PR 地址：[#833](https://github.com/xitu/gold-miner/pull/833)
* 文章分类：**iOS**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Edison-Hsu** [comment]
@sqrthree 文章认领

**Comment by sqrthree** [comment]
@Edison-Hsu 第一次参加翻译计划要从校对文章开始哟~~

**Comment by Edison-Hsu** [comment]
@sqrthree 前几天已经校队过一篇文章啦

**Comment by sqrthree** [comment]
@Edison-Hsu 好的~~ 哈哈这边文章还没分享，所以我刚看 wiki 的时候没找到你的信息~~ 那你快快翻译了哈~~
