### ISSUE TITLE
实现响应式图像的四种技术策略

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8134]
* 原文链接：[Responsive Images: Different Techniques and Tactics](https://blog.bitsrc.io/responsive-images-different-techniques-and-tactics-6045a1fa7ea2)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/responsive-images-different-techniques-and-tactics.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 欢迎翻译！
