### ISSUE TITLE
简述 JavaScript 三个不应使用的功能

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8136]
* 原文链接：[The Dark Side of Javascript: A Look at 3 Features You Never Want to Use](https://blog.bitsrc.io/the-dark-side-of-javascript-a-look-at-3-features-you-never-want-to-use-83b6f0b3804b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/the-dark-side-of-javascript-a-look-at-3-features-you-never-want-to-use.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JackEggie** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@JackEggie 欢迎翻译！

**Comment by PassionPenguin** [comment]
@JackEggie 翻译的咋样了，:喵:

**Comment by JackEggie** [comment]
> @JackEggie 翻译的咋样了，:喵:

抱歉，有点拖延，近几天完成。

**Comment by zenblo** [comment]
@JackEggie @lsvih 好久没动静，我接过来翻译吧

**Comment by lsvih** [comment]
@zenblo  麻烦你啦~
