### ISSUE TITLE
UserNotifications Framwork 入门介绍

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#814]
* 原文链接：[An Introduction to the UserNotifications Framework](https://code.tutsplus.com/tutorials/an-introduction-to-the-usernotifications-framework--cms-27250)
* 掘金链接：[UserNotifications Framwork 入门介绍](http://gold.xitu.io/entry/58071e42a22b9d005b6344ce)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/an-introduction-to-the-usernotifications-framework.md)
* PR 地址：[#835](https://github.com/xitu/gold-miner/pull/835)
* 文章分类：**iOS**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Danny1451** [comment]
@sqrthree  认领文章

**Comment by sqrthree** [comment]
@Danny1451 好的
