### ISSUE TITLE
和 Node.js 创始人 Ryan Dahl 的对话

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8140]
- 原文链接：[Interview with Ryan Dahl, Creator of Node.js](https://evrone.com/ryan-dahl-interview)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/Interview-with-Ryan-Dahl-Creator-of-Node-js.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：5 天
- 校对时间：2 天
- 翻译积分：5 分
- 校对积分：2 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领

**Comment by lsvih** [comment]
@PassionPenguin 好的

**Comment by itcodes** [comment]
https://juejin.cn/post/6937483576594137096

**Comment by lsvih** [comment]
收到
