### ISSUE TITLE
Python 的 JSON 库 — 按速度，成熟度和操作安全性进行比较

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8143]
* 原文链接：[JSON encoding/decoding with Python](https://levelup.gitconnected.com/json-encoding-decoding-with-python-62a2cae63a6a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/json-encoding-decoding-with-python.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by youngjuning** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@youngjuning 欢迎翻译！
