### ISSUE TITLE
Python 类的 6 种替代方案

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8144]
* 原文链接：[6 Alternatives to Classes in Python](https://betterprogramming.pub/6-alternatives-to-classes-in-python-6ecb7206377)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/6-alternatives-to-classes-in-python.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Alfxjx** [comment]
翻译认领

**Comment by lsvih** [comment]
@Alfxjx 好的~
