### ISSUE TITLE
2021 年 1 月 RedMonk 编程语言排名

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8148]
- 原文链接：[The RedMonk Programming Language Rankings: January 2021](https://redmonk.com/sogrady/2021/03/01/language-rankings-1-21/)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/The-RedMonk-Programming-Language-Rankings-January-2021.md)
- PR 地址：
- 文章分类：**其他**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：10 天
- 校对时间：2 天
- 翻译积分：5 分
- 校对积分：2 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领翻译

**Comment by itcodes** [comment]
> 认领翻译

好的

**Comment by PassionPenguin** [comment]
@lsvih ??????您操作错issue啦hhh
怪不得我找了半天没找到issue

**Comment by lsvih** [comment]
@PassionPenguin 我的错..手滑了

**Comment by PassionPenguin** [comment]
@lsvih https://juejin.cn/post/6937849069721092110
