### ISSUE TITLE
NumPy 1.20 问世，带来了运行时 SIMD 的支持和类型注释

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8149]
- 原文链接：[NumPy 1.20 Released with Runtime SIMD Support and Type Annotations](https://www.infoq.com/news/2021/03/numpy-120-typed-SIMD/)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/NumPy-1-20-Released-with-Runtime-SIMD-Support-and-Type-Annotations.md)
- PR 地址：
- 文章分类：**后端**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：10 天
- 校对时间：2 天
- 翻译积分：5 分
- 校对积分：2 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领翻译

**Comment by husiyu** [comment]
https://juejin.cn/post/6943542858792042510/

**Comment by lsvih** [comment]
收到
