### ISSUE TITLE
如何使用 UIFeedbackGenerator 让应用支持 iOS 10 的 Haptic Feedback

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#815]
* 原文链接：[How to generate haptic feedback with UIFeedbackGenerator](https://www.hackingwithswift.com/example-code/uikit/how-to-generate-haptic-feedback-with-uifeedbackgenerator)
* 掘金链接：[如何使用 UIFeedbackGenerator 让应用支持 iOS 10 的 Haptic Feedback](http://gold.xitu.io/entry/580722f8bf22ec0064f7c6a3)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-generate-haptic-feedback-with-uifeedbackgenerator.md)
* PR 地址：[#830](https://github.com/xitu/gold-miner/pull/830)
* 文章分类：**iOS**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by owenlyn** [comment]
认领~

**Comment by sqrthree** [comment]
@owenlyn 好的~ 顺便填下这个 [wiki](https://github.com/xitu/gold-miner/wiki/译者擅长领域表) 哈

**Comment by owenlyn** [comment]
@sqrthree 初稿完成啦~~
