### ISSUE TITLE
11 Easy UI Design Tips for Web Devs

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#8158]
- 原文链接：https://dev.to/doabledanny/11-easy-ui-design-tips-for-web-devs-j3j
- 简要介绍：11 Easy UI Design Tips for Web Devs

* [x] 按文章分类填写 issue 标题：推荐前端/设计优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
#8510 已发布认领，感谢推荐~
