### ISSUE TITLE
Exploring @property and its Animating Powers

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#8159]
- 原文链接：https://css-tricks.com/exploring-property-and-its-animating-powers/
- 简要介绍：Exploring @property and its Animating Powers

* [x] 按文章分类填写 issue 标题：推荐前端优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by PassionPenguin** [comment]
这个我自己翻译哈

**Comment by PassionPenguin** [comment]
我人傻了，翻译出来 5w 字 = =

https://juejin.cn/post/6937336524543361031

**Comment by lsvih** [comment]
大多是代码= =
