### ISSUE TITLE
循序渐进地代码重构

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#816]
* 原文链接：[Refactoring -- Not on the backlog!](http://ronjeffries.com/xprog/articles/refactoring-not-on-the-backlog/)
* 掘金链接：[循序渐进地代码重构](http://gold.xitu.io/entry/580729a3128fe10054cda258)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/refactoring-not-on-the-backlog.md)
* PR 地址：[#831](https://github.com/xitu/gold-miner/pull/831)
* 文章分类：**我也不知道，反正是编程**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by rottenpen** [comment]
认领

**Comment by sqrthree** [comment]
@rottenpen 好的

**Comment by rottenpen** [comment]
PR一直validation failed不知为什么= =
