### ISSUE TITLE
推荐 前端 相关文章

### ISSUE THREAD

**Issue by momodiy** [xitu/gold-miner#8160]
- 原文链接：10 Years of Open-Source Visualization
- 简要介绍：D3作者在d3.js 1.0版本开源十周年分享出的10条感悟，值的翻译

---

* [x] 按文章分类填写 issue 标题：前端
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 已通过Google搜索关键字`10 Years of Open-Source Visualization 原文 翻译`，未发现已完成的翻译版本

**Comment by momodiy** [comment]
@lsvih 本文已由我开始翻译

**Comment by lsvih** [comment]
#8166 已发布认领，感谢推荐
