### ISSUE TITLE
Chrome 88 DevTools 中的新功能

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8161]
- 原文链接：[New Features in Chrome 88 Devtools](https://www.infoq.com/news/2021/03/new-features-chrome-88/?topicPageSponsorship=eb89fa44-b190-43ef-87d0-4bc8727e7413)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/new-features-chrome-88.md)
- PR 地址：
- 文章分类：**前端**，**其他**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：1 天
- 校对时间：1 天
- 翻译积分：2.5 分
- 校对积分：1 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by husiyu** [comment]
https://juejin.cn/post/6938248665219727391

**Comment by lsvih** [comment]
收到
