### ISSUE TITLE
Android 启动技巧：不要使用 Kotlin 协程

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8168]
* 原文链接：[Android App Startup Tip: Don’t Use Kotlin Coroutines](https://medium.com/specto/android-startup-tip-dont-use-kotlin-coroutines-a7b3f7176fe5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/android-startup-tip-dont-use-kotlin-coroutines.md)
* PR 地址：
* 文章分类：**Android**，**Kotlin**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由@keepmovingljzy 认领翻译

**Comment by keepmovingljzy** [comment]
@lvsheng 翻译完成

**Comment by PassionPenguin** [comment]
@keepmovingljzy 记得发布嗷

**Comment by keepmovingljzy** [comment]
@lsvih https://juejin.cn/post/6940071555330211847 发布完成
