### ISSUE TITLE
探索 firebase 在Android 和 iOS 的使用： Remote Config

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#817]
- 原文链接：[Exploring Firebase on Android & iOS: Remote Config](https://medium.com/@hitherejoe/exploring-firebase-on-android-ios-remote-config-3e1407b088f6#.hb0blxber)
- 掘金链接：[探索 firebase 在Android 和 iOS 的使用： Remote Config](http://gold.xitu.io/entry/58071c95a22b9d005b63378c)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/exploring-firebase-on-android-ios-remote-config.md)
- PR 地址：#844 
- 文章分类：**Android**
---
- 翻译时间：`4` 天
- 校对时间：`2` 天
- 翻译积分：`9` 分
- 校对积分：`2` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jamweak** [comment]
认领文章～～～ @sqrthree

**Comment by sqrthree** [comment]
@jamweak Okay.

**Comment by jamweak** [comment]
@sqrthree 翻译完成。 #844
