### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by GreatV** [xitu/gold-miner#818]
你好，我叫GreatV。具有较好的英语基础。经常访问Github/Stackoverflow/Behance。我的博客是 http://blog.csdn.net/and_w 内有之前的翻译文章。希望加入翻译计划。

**Comment by antonia0912** [comment]
@GreatV  欢迎参加掘金翻译计划，请加我微信 antonia0912 备注GitHub ID 我来拉你进译者群
