### ISSUE TITLE
Go 语言全球开发者调查报告

### ISSUE THREAD

**Issue by husiyu** [xitu/gold-miner#8182]
- 原文链接：https://blog.golang.org/survey2020-results
- 简要介绍：Go 语言全球开发者调查报告
- Markdown文件 : [文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/Go-developer-survey-2020-results.md)
- PR 地址：
- 文章分类：其他

* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：1 天
* 校对时间：1 天
* 翻译积分：7 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by youngjuning** [comment]
翻译认领

**Comment by husiyu** [comment]
@youngjuning  🚗 耶 明天交货哟

**Comment by samyu2000** [comment]
@lsvih @husiyu 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好嘞

**Comment by husiyu** [comment]
> @lsvih @husiyu 翻译认领

@samyu2000 翻译有进度了吗？

**Comment by PassionPenguin** [comment]
https://www.baidu.com/s?ie=utf-8&wd=Go%20Developer%20Survey%202020%20Results%20%E7%BF%BB%E8%AF%91

已有大量翻译，并且翻译超时了吧hhh @husiyu @lsvih

**Comment by husiyu** [comment]
https://juejin.cn/post/6943540695030300708/

**Comment by lsvih** [comment]
收到
