### ISSUE TITLE
新发布的 TypeScript 手册！先睹为快！

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8186]
- 原文链接：[Announcing the New TypeScript Handbook](https://devblogs.microsoft.com/typescript/announcing-the-new-typescript-handbook/)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/announcing-the-new-typescript-handbook.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：2 天
- 校对时间：1 天
- 翻译积分：4 分
- 校对积分：2 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@itcodes 翻译认领

**Comment by lsvih** [comment]
已发布，地址：https://juejin.cn/post/6938614411397431304
