### ISSUE TITLE
Don’t Run Benchmarks on a Debuggable Android App (Like I Did for Coroutines)

### ISSUE THREAD

**Issue by keepmovingljzy** [xitu/gold-miner#8189]
- 原文链接：https://medium.com/specto/dont-run-benchmarks-on-a-debuggable-android-app-like-i-did-34d95331cabb
- 简要介绍：文章是关于不要在 debug 模式下运行基准测试，作者做了一些数据测试和对比，值得翻译。

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by keepmovingljzy** [comment]
@lsvih 本文我自己翻译哈

**Comment by lsvih** [comment]
今天稍晚添加

**Comment by lsvih** [comment]
#8209 已发布认领
