### ISSUE TITLE
Raspberry Pi 九岁啦：你可能不知道的 9 件事

### ISSUE THREAD

**Issue by husiyu** [xitu/gold-miner#8193]
* 原文链接：[Raspberry Pi’s Ninth Birthday: 9 Things You Might Not Know](https://www.tomshardware.com/news/raspberry-pi-9th-birthday)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md)
* PR 地址：
* 文章分类：**其他**，**资讯**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领

**Comment by lsvih** [comment]
@PassionPenguin 好的

**Comment by husiyu** [comment]
校对认领
