### ISSUE TITLE
让机器学习更加公平

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8195]
* 原文链接：[Working toward fairer machine learning](https://www.amazon.science/research-awards/success-stories/algorithmic-bias-and-fairness-in-machine-learning)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/working-toward-fairer-machine-learning.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PingHGao** [comment]
翻译认领

**Comment by lsvih** [comment]
@PingHGao 好的~
