### ISSUE TITLE
React Native 0.64 发布，已在 iOS 支持 Hermes

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8212]
* 原文链接：[Announcing React Native 0.64 with Hermes on iOS](https://reactnative.dev/blog/2021/03/11/version-0.64)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/announcing-react-native-0.64-with-hermes-on-ios.md)
* PR 地址：
* 文章分类：**iOS**，**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：1 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由 @youngjuning 认领翻译

**Comment by youngjuning** [comment]
@lsvih 来了

**Comment by itcodes** [comment]
https://juejin.cn/post/6939117135331328030 发布链接在此。 @lsvih

**Comment by lsvih** [comment]
收到
