### ISSUE TITLE
7 个最能用于构造更整洁的 Flutter 应用的 Dart 小贴士和小技巧

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8214]
* 原文链接：[Top 7 Dart Tips and Tricks for Cleaner Flutter Apps](https://betterprogramming.pub/top-7-dart-tips-and-tricks-for-cleaner-flutter-apps-562664a15826)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/top-7-dart-tips-and-tricks-for-cleaner-flutter-apps.md)
* PR 地址：
* 文章分类：**Flutter**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领翻译

**Comment by lsvih** [comment]
@PassionPenguin 好的~

**Comment by PassionPenguin** [comment]
published at https://juejin.cn/post/6955828244016791566/

**Comment by lsvih** [comment]
收到
