### ISSUE TITLE
无服务器化：2021 年该项技术何去何从？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8215]
* 原文链接：[Serverless: Where Is the Industry Going in 2021?](https://dzone.com/articles/serverless-where-is-the-industry-going-in-2021)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/serverless-where-is-the-industry-going-in-2021.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Ashira97** [comment]
@lsvih 翻译认领~

**Comment by lsvih** [comment]
@Ashira97 欢迎翻译~

**Comment by csbingao** [comment]
校对认领

**Comment by lsvih** [comment]
@csbingao 在 #8297 里认领哈
