### ISSUE TITLE
Snowpack：一个可替代 Webpack 的构建工具

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8217]
* 原文链接：[Snowpack: An Alternative Build Tool to Webpack](https://blog.bitsrc.io/snowpack-an-alternative-build-tool-to-webpack-9e8da197071d)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/snowpack-an-alternative-build-tool-to-webpack.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by felixliao** [comment]
@lsvih 认领翻译

**Comment by lsvih** [comment]
@felixliao  好的~
