### ISSUE TITLE
对产品经理而言的 Web 性能

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8223]
- 原文链接：[Web Performance for Product Managers](https://speedcurve.com/blog/web-performance-product-managers/)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/Web-Performance-for-Product-Managers.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：5 天
- 校对时间：2 天
- 翻译积分：5 分
- 校对积分：2 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by flying-yogurt** [comment]
翻译认领。

**Comment by Ashira97** [comment]
@itcodes 翻译认领~

**Comment by itcodes** [comment]
> 翻译认领。

加油

**Comment by flying-yogurt** [comment]
昨晚是第五天的截止日期，但是由于我个人有一点突发情况，希望能稍微推迟交稿时间😭。翻译的工作已经完成了一大半，预计能在周二晚上或周三白天提交 commit。给大家添麻烦了，实在抱歉！

**Comment by flying-yogurt** [comment]
对不起大家！我前两天生病发烧实在难受，没顾上完成手头的翻译工作。第二次给大家添麻烦了，实在是抱歉。我目前已经完成了约85%的工作量，尚余一些内容再次斟酌，希望能再通融一两天时间，我会尽快提交commit的。给大家鞠躬了！
