### ISSUE TITLE
Dropbox 公布了 Atlas —— 一个托管服务编排平台

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8232]
* 原文链接：[Dropbox Reveals Atlas - a Managed Service Orchestration Platform](https://www.infoq.com/news/2021/03/dropbox-atlas/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/dropbox-reveals-Atlas.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：4 天
* 校对时间：2 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by husiyu** [comment]
建议用“前沿技术瞭望官”发布

**Comment by PassionPenguin** [comment]
翻译认领

**Comment by lsvih** [comment]
@PassionPenguin 好的

**Comment by lsvih** [comment]
本文由官方账号发布，另奖励 1 分

**Comment by husiyu** [comment]
https://juejin.cn/post/6943068367125381127

**Comment by lsvih** [comment]
收到
