### ISSUE TITLE
SREs 和 DevOps 十大开源项目

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8233]
* 原文链接：[Top 10 Open Source Projects for SREs and DevOps](https://dzone.com/articles/top-open-source-projects-for-sres-and-devops)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/top-open-source-projects-for-sres-and-devops.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：1 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by keepmovingljzy** [comment]
@lsvih 认领翻译

**Comment by lsvih** [comment]
@keepmovingljzy 好的，您同时认领了两篇文章，请注意时效哈~

**Comment by Lvyaqian123** [comment]
已发布https://juejin.cn/post/7089270839475978253/

**Comment by lsvih** [comment]
收到 @Lvyaqian123
