### ISSUE TITLE
SQLite 3.35 版本有什么新的东西？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8234]
* 原文链接：[What's new in SQLite 3.35](https://nalgeon.github.io/sqlite-3-35/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/whats-new-in-sqlite-3-35.md)
* PR 地址：
* 文章分类：**后端**，**资讯**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：1.5 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领翻译

**Comment by lsvih** [comment]
@PassionPenguin 好的~

**Comment by husiyu** [comment]
“前沿技术瞭望官” 发布

**Comment by husiyu** [comment]
已发布 https://juejin.cn/post/6945709972365770760/

**Comment by lsvih** [comment]
收到
