### ISSUE TITLE
Rust 与 C 的速度

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8236]
* 原文链接：[Speed of Rust vs. C](https://kornel.ski/rust-c-speed)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/speed-of-rust-vs-c.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：3 天
* 翻译积分：6.5 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好的~

**Comment by PassionPenguin** [comment]
@samyu2000  翻译的咋样了，:喵:

**Comment by PassionPenguin** [comment]
这个我来接啦

**Comment by lsvih** [comment]
@samyu2000  这篇要不给楼下吧？
