### ISSUE TITLE
谷歌抨击微软“试图破坏开放 web 的运作方式”

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8237]
* 原文链接：[Google slams Microsoft for trying ‘to break the way the open web works’](https://www.theverge.com/2021/3/12/22327306/google-microsoft-attack-open-web-online-news-australia-laws)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/google-microsoft-attack-open-web-online-news-australia-laws.md)
* PR 地址：
* 文章分类：**Google**，**资讯**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lhd951220** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@lhd951220 欢迎翻译

**Comment by husiyu** [comment]
“前沿技术瞭望官”帐号发布。

**Comment by itcodes** [comment]
@lhd951220 
咋样了。

**Comment by lhd951220** [comment]
正在翻译，差不多好了

**Comment by lhd951220** [comment]
@itcodes 重新找人翻译吧，最近挺忙的，没什么时间，麻烦你了

**Comment by lsvih** [comment]
@lhd951220 好的- -

**Comment by youngjuning** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@youngjuning 好的
