### ISSUE TITLE
Google 的开源模糊测试工具 OSS-Fuzz 现在支持 Java 应用了

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8238]
* 原文链接：[Google’s OSS-Fuzz extends fuzzing to Java apps](https://www.infoworld.com/article/3611510/googles-oss-fuzz-extends-fuzzing-to-java-apps.html#tk.rss_devops)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md)
* PR 地址：
* 文章分类：**Google**，**后端**，**资讯**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：1 天
* 校对时间：1 天
* 翻译积分：1 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by husiyu** [comment]
> * 原文链接：[Google’s OSS-Fuzz extends fuzzing to Java apps](https://www.infoworld.com/article/3611510/googles-oss-fuzz-extends-fuzzing-to-java-apps.html#tk.rss_devops)
> * Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md)
> * PR 地址：
> * 文章分类：**Google**，**后端**，**资讯**
> * **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
> 
> * 翻译时间：1 天
> * 校对时间：1 天
> * 翻译积分：1 分
> * 校对积分：0.5 分
> * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

“前沿技术瞭望官”帐号发布。

**Comment by PassionPenguin** [comment]
翻译认领：）

**Comment by lsvih** [comment]
本文使用官方账号发布，另奖励 1 分

**Comment by lsvih** [comment]
已发布，地址：https://juejin.cn/post/6942674729597665310
