### ISSUE TITLE
新增分类：资讯

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8239]
由于最近新增了不少的资讯相关文章，故此新建此 [资讯](https://github.com/xitu/gold-miner/issues?q=label%3A资讯) 分类。

技术资讯包含互联网公司最新技术相关新闻、知名开源库更新通告等内容。

------

TODO:

- [x] 新建 label
- [ ] 迁移已有文章标签
- [ ] （Optional）新建文章目录

**Comment by PassionPenguin** [comment]
> 申请译者的时候没有这个分类, 以后可以申请翻译这个分类的文章吗

都可以的，但需要注意时效性，注意在 `翻译时间` 和 `校对时间` 内完成
