### ISSUE TITLE
Kotlin MultiPlatform 系列文章

### ISSUE THREAD

**Issue by keepmovingljzy** [xitu/gold-miner#8246]
- 原文链接：
- Part 1: [The D-KMP architecture and the Declarative UIs](https://danielebaroncelli.medium.com/the-future-of-apps-declarative-uis-with-kotlin-multiplatform-d-kmp-part-1-3-c0e1530a5343)
- Part 2: [Kotlin MultiPlatform and the MVI pattern](https://danielebaroncelli.medium.com/the-future-of-apps-declarative-uis-with-kotlin-multiplatform-d-kmp-part-2-3-1bbadaf19aef)
- Part 3: [D-KMP layers and Team organization](https://danielebaroncelli.medium.com/the-future-of-apps-declarative-uis-with-kotlin-multiplatform-d-kmp-part-3-3-959a2628526d)

- 简要介绍：本系列有三篇，是介绍Kotlin MultiPlatform 和 现如今流行的声明式 UI 配置所产生的一种新模式，以及同其他模式的对比，值得翻译~

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/Android/iOS/设计优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by keepmovingljzy** [comment]
@lsvih 该系列文章我自己翻译哈

**Comment by lsvih** [comment]
@keepmovingljzy  抱歉这个 issue 搁置了这么久哈，您现在是否还有兴趣翻译这个系列呀？我打算分成三个 issue 放出来
