### ISSUE TITLE
实现二叉树以及二叉树遍历数据结构

### ISSUE THREAD

**Issue by 3omething** [xitu/gold-miner#825]
原文：
Unlike the traversal algorithms, the search algorithm will traverse only 1 side at every recursive step. On average, this leads to a time complexity of O(log n), which is considerably faster than the O(n) traversal.

译文：
与遍历算法不同，每一个递归步骤搜索算法只会遍历一次。平均而言,这会导致时间复杂度为 O(o(log n)) ,远远大于 O(n) 时间复杂度的遍历操作。

1. “1 side”我认为应该是指”一边“（左边或右边），而不是一次。
2. O(o(log n))应该是O(log n)。
3. “faster than”应该是指“速度快于”，而不是译文中的“远远大于”。

**Comment by sqrthree** [comment]
@3omething O(∩_∩)O谢谢提出校对意见哈~~ 如果对翻译计划感兴趣的话， 欢迎来到掘金翻译计划一起玩~ 我们一起努力做的更好咯~~~

**Comment by sqrthree** [comment]
@cbangchen 紧急召唤~~ 辛苦来看一下啦

**Comment by cbangchen** [comment]
@sqrthree 已提交 Pull Request

**Comment by sqrthree** [comment]
@cbangchen 辛苦啦~~ 

@3omething 已经调整好了 [#828](https://github.com/xitu/gold-miner/pull/828)~ 再次感谢你的反馈哈~
