### ISSUE TITLE
Git 2.31 中的闪光点

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8252]
* 原文链接：[Highlights from Git 2.31](https://github.blog/2021-03-15-highlights-from-git-2-31/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/2021-03-15-highlights-from-git-2-31.md)
* PR 地址：
* 文章分类：**其他**，**资讯**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by lsvih** [comment]
@Baddyo 欢迎翻译

**Comment by zhanhongzhu** [comment]
认领校对

**Comment by lsvih** [comment]
@zhanhongzhu 本文校对已完成了哈= =  您下会儿可以在 PR 里认领校对~
