### ISSUE TITLE
为什么 Java 在 25 年之后依旧如此年轻：一个架构师的看法

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8256]
* 原文链接：[Why Java Is so Young After 25 Years: An Architect’s Point of View](https://dzone.com/articles/why-java-is-so-young-after-25-years-an-architects)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/why-java-is-so-young-after-25-years-an-architects.md)
* PR 地址：
* 文章分类：**后端**，**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by keepmovingljzy** [comment]
@lsvih 认领翻译

**Comment by lsvih** [comment]
@keepmovingljzy 好的
