### ISSUE TITLE
探索 firebase 在 Android 和 iOS 的使用： Analytics

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#826]
* 原文链接：[Exploring Firebase on Android & iOS: Analytics](https://medium.com/exploring-android/exploring-firebase-on-android-ios-analytics-8484b61a21ba#.b0hgigy3r)
* 掘金链接：[探索 firebase 在 Android 和 iOS 的使用： Analytics](http://gold.xitu.io/entry/5808afd867f3560057a27764)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/exploring-firebase-on-android-ios-analytics.md)
* PR 地址：[#836](https://github.com/xitu/gold-miner/pull/836)
* 文章分类：**Android & iOS**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
@sqrthree 收了！ 我觉得这个文章很好！

**Comment by sqrthree** [comment]
@yifili09 棒棒哒~~

**Comment by yifili09** [comment]
@sqrthree #836 需要校对伙伴。
