### ISSUE TITLE
斯坦福发布 2021 年人工智能指数报告

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8263]
* 原文链接：[Stanford Publishes AI Index 2021 Annual Report](https://www.infoq.com/news/2021/03/stanford-ai-report-2021)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/stanford-ai-report-2021.md)
* PR 地址：
* 文章分类：**AI**，**资讯**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文为资讯类文章，使用官方账号发布并时效内完成另外奖励 1 分

**Comment by PingHGao** [comment]
翻译认领
