### ISSUE TITLE
谷歌云公开发布医疗保健同意管理 API

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8265]
* 原文链接：[Google Cloud Releases Its Healthcare Consent Management API to General Availability](https://www.infoq.com/news/2021/03/gcp-healthcare-consent-api)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/gcp-healthcare-consent-api.md)
* PR 地址：
* 文章分类：**资讯**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文为资讯类文章，使用官方账号发布并时效内完成另外奖励 0.5 分

**Comment by chzh9311** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
已发布，地址：https://juejin.cn/post/6942398996048510989
