### ISSUE TITLE
这会是渐进式应用程序 PWA 衰落的开始吗？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8269]
* 原文链接：[Is It the Beginning of the End for PWAs?](https://blog.bitsrc.io/is-it-the-beginning-of-the-end-for-pwas-da0fb032d545)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/is-it-the-beginning-of-the-end-for-pwas.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领翻译
