### ISSUE TITLE
“高级”黑客使用 11 个零日漏洞去感染 Windows、iOS 还有 Android 用户

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8285]
* 原文链接：[“Expert” hackers used 11 zerodays to infect Windows, iOS, and Android users](https://arstechnica.com/information-technology/2021/03/expert-hackers-used-11-zerodays-to-infect-windows-ios-and-android-users/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/expert-hackers-used-11-zerodays-to-infect-windows-ios-and-android-users.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：1 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文翻译完成后使用官方账号发布，额外奖励 1 分

**Comment by PassionPenguin** [comment]
认领翻译

**Comment by PassionPenguin** [comment]
> 本文翻译完成后使用官方账号发布，额外奖励 1 分

这个不属于 前沿科技 的范畴吧……（

哈哈哈哈哈哈随便

**Comment by PassionPenguin** [comment]
see https://www.163.com/dy/article/G5FJA3280511D6RL.html

**Comment by PassionPenguin** [comment]
这个原文是洗稿？https://googleprojectzero.blogspot.com/2021/03/in-wild-series-october-2020-0-day.html

**Comment by lsvih** [comment]
@husiyu 这篇文章好像有点问题，您看看哈

**Comment by husiyu** [comment]
已发布 https://juejin.cn/post/6945702690047557669/

**Comment by lsvih** [comment]
收到
