### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by o1xhack** [xitu/gold-miner#829]
你好我是o1xhack，现在在美国Boston University读本科，专业是Computer Science，浏览的网站非常杂，因为在学习 iOS开发其中swift的资源外国相对较多，所以各种网站和播客都回搜着看，英语水平因为在国外应该还是可以的，没有翻译专业文章的经验，目前没有个人搭建的播客。

**Comment by antonia0912** [comment]
@o1xhack 欢迎来到掘金翻译计划，请加我微信 antonia0912 备注 github id 我来拉你进译者群

**Comment by waychane** [comment]
@o1xhack Hi，如果你还没有添加 antonia 的微信，加我微信 waychane 我来加你进群吧，这个 Issue 我先 close 掉了。
