### ISSUE TITLE
10 个新的 CSS 功能你可能不知道（2021 年版本）

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8293]
* 原文链接：[10 New CSS Features You Might Not Know About (2021 Edition)](https://torquemag.io/2021/03/new-css-features/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/new-css-features-2021.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领

**Comment by lsvih** [comment]
@PassionPenguin 好的~
