### ISSUE TITLE
到了下一代图像编码来罢黜 JPEG 编码的时候了

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8294]
* 原文链接：[Time for Next-Gen Codecs to Dethrone JPEG](https://cloudinary.com/blog/time_for_next_gen_codecs_to_dethrone_jpeg)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/time-for-next-gen-codecs-to-dethrone-jpeg.md)
* PR 地址：
* 文章分类：**前端**，**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领

**Comment by lsvih** [comment]
@PassionPenguin 好的

**Comment by lsvih** [comment]
本文翻译积分增加 1.5 分

**Comment by Kimhooo** [comment]
@lsvih 认领校对。
