### ISSUE TITLE
网络年鉴大研究表明热门的前端框架依然是互联网的一小部分

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8296]
* 原文链接：[Web Almanac Mega Study Reveals That Popular Front-End Frameworks Are Still a Small Part of the Web](https://www.infoq.com/news/2021/03/web-almanac-2020)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/web-almanac-2020.md)
* PR 地址：
* 文章分类：**前端**，**资讯**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文使用官方账号发布，额外奖励 0.5 分

**Comment by felixliao** [comment]
翻译认领

**Comment by lsvih** [comment]
@felixliao 好的~

**Comment by lsvih** [comment]
已发布：https://juejin.cn/post/6944674906684686366
