### ISSUE TITLE
解决方案架构师技巧：架构图的5种类型

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8303]
* 原文链接：[Solutions Architect Tips — The 5 Types of Architecture Diagrams](https://betterprogramming.pub/solutions-architect-tips-the-5-types-of-architecture-diagrams-eb0c11996f9e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/solutions-architect-tips-the-5-types-of-architecture-diagrams.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：13 天
* 校对时间：2 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by youngjuning** [comment]
@Isvih 翻译认领

**Comment by lsvih** [comment]
@youngjuning 欢迎翻译  注意健康作息呀
