### ISSUE TITLE
在 PostgreSQL 中解码 Django 会话数据

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8305]
- 原文链接：[Decoding Django Sessions in PostgreSQL](https://dzone.com/articles/decoding-django-sessions-in-postgresql)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/Decoding-Django-Sessions-in-PostgreSQL.md)
- PR 地址：
- 文章分类：**后端**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：10 天
- 校对时间：2 天
- 翻译积分：5 分
- 校对积分：2 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@itcodes @lsvih 翻译认领

**Comment by Miigon** [comment]
翻译认领

**Comment by lsvih** [comment]
@itcodes 这篇文章原文的 md 文件格式有少许问题哈
