### ISSUE TITLE
React vs. Vue 谁是 2021 年最佳 JavaScript 框架

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8309]
- 原文链接：[React vs. Vue in 2021: Best JavaScript Framework](https://dzone.com/articles/react-vs-vue-in-2021-best-javascript-framework)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/react-vs-vue-in-2021-best-javascript-framework.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：10 天
- 校对时间：2 天
- 翻译积分：5 分
- 校对积分：2 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
咦？标题好像不一致。

**Comment by itcodes** [comment]
> 咦？标题好像不一致。

更新了感谢大佬反馈。

**Comment by Baddyo** [comment]
认领翻译。

**Comment by keepmovingljzy** [comment]
@翻译认领

**Comment by lsvih** [comment]
@keepmovingljzy 好的

**Comment by PassionPenguin** [comment]
有点问题，先别发 @lsvih @keepmovingljzy

**Comment by PassionPenguin** [comment]
See #8360

**Comment by keepmovingljzy** [comment]
@PassionPenguin 啥问题？

**Comment by PassionPenguin** [comment]
> @PassionPenguin 啥问题？

See #8360

**Comment by lsvih** [comment]
@keepmovingljzy 作者名字改动了，您记得同步一下再发哈

**Comment by keepmovingljzy** [comment]
@lsvih 好的

**Comment by husiyu** [comment]
掘金链接 https://juejin.cn/post/6944674279141146632

**Comment by lsvih** [comment]
收到
