### ISSUE TITLE
Applets 应用程序的终结

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8314]
- 原文链接：[The End of Applets](https://www.infoq.com/news/2021/03/end-of-applets/?itm_source=infoq&itm_medium=popular_widget&itm_campaign=popular_content_list&itm_content=)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/The-End-of-Applets.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：10 天
- 校对时间：2 天
- 翻译积分：5 分
- 校对积分：2 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by 5Reasons** [comment]
翻译认领

**Comment by itcodes** [comment]
> 翻译认领

可以的。给力。
