### ISSUE TITLE
Postgres 和 MySQL 之间的性能差异

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8319]
* 原文链接：[Performance Differences Between Postgres and MySQL](https://dzone.com/articles/performance-differences-between-postgres-and-mysql)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/performance-differences-between-postgres-and-mysql.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by greycodee** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@greycodee 好嘞

**Comment by kamly** [comment]
@lsvih 校对认领
