### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Professor-Z** [xitu/gold-miner#832]
北京邮电大学计算机本硕，2年前端开发经验，有数个已上线项目。英语六级532分，考研英语80分，常浏览的国外网站有github/stackoverflow /twitter/Quora，博客blog.vuuihc.com。申请加入翻译计划，谢谢。

**Comment by antonia0912** [comment]
@Professor-Z 欢迎来到掘金翻译计划，请加我微信 antonia0912 备注 github id 我来拉你进译者群
