### ISSUE TITLE
为什么 Java 服务端不采用 Kotlin 开发？

### ISSUE THREAD

**Issue by keepmovingljzy** [xitu/gold-miner#8320]
- 原文链接：https://medium.com/google-developer-experts/why-are-java-server-side-developers-not-adopting-kotlin-8eb53e06ee99
- 简要介绍：作者介绍了为什么java 服务端不采用 kotlin 开发，值得翻译~
---

### 请完成并勾选一下三项：

* [ ] 按文章分类填写 issue 标题：推荐后端优秀英文文章
* [ ] 本文很值得翻译，我推荐
* [ ] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by keepmovingljzy** [comment]
@lsvih 本文我自己翻译哈

**Comment by lsvih** [comment]
这篇有译文了哈 https://markdowner.net/article/161588779273293824

**Comment by keepmovingljzy** [comment]
> 这篇有译文了哈 https://markdowner.net/article/161588779273293824

好的
