### ISSUE TITLE
推荐其他（资讯？）优秀英文文章

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#8322]
- 原文链接：https://github.blog/2021-03-16-using-github-code-scanning-and-codeql-to-detect-traces-of-solorigate-and-other-backdoors/
- 简要介绍：GitHub Code Scanning 检测后门漏洞

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐其他优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
#8425 已发布认领，感谢推荐~
