### ISSUE TITLE
Rust 1.51.0 发布

### ISSUE THREAD

**Issue by husiyu** [xitu/gold-miner#8339]
* 原文链接：[Announcing Rust 1.51.0](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/Rust-1.51.0.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：1 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by youngjuning** [comment]
@husiyu 翻译认领

**Comment by youngjuning** [comment]
@lsvih @husiyu 翻译完成

**Comment by lsvih** [comment]
@youngjuning 感谢翻译，真快~
