### ISSUE TITLE
使用多背景图片来提高可感知的性能

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#834]
- 原文链接：[Improving Perceived Performance with Multiple Background Images](http://csswizardry.com/2016/10/improving-perceived-performance-with-multiple-background-images/)
- 掘金链接：[Improving Perceived Performance with Multiple Background Images](http://gold.xitu.io/entry/580de2c8c4c97100589988e6)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/improving-perceived-performance-with-multiple-background-images.md)
- PR 地址：#863
- 文章分类：**前端**
---
- 翻译时间：`3` 天
- 校对时间：`1` 天
- 翻译积分：`4` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyseria** [comment]
认!

**Comment by sqrthree** [comment]
@cyseria 好的

**Comment by rottenpen** [comment]
认
