### ISSUE TITLE
1993 年的 CGI 脚本和早期服务端 Web 编程

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8341]
* 原文链接：[1993: CGI Scripts and Early Server-Side Web Programming](https://webdevelopmenthistory.com/1993-cgi-scripts-and-early-server-side-web-programming/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/1993-cgi-scripts-and-early-server-side-web-programming.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文使用 掘金翻译计划 官方号发布，额外奖励积分 1 分

**Comment by PassionPenguin** [comment]
翻译认领

**Comment by lsvih** [comment]
@PassionPenguin 好的~

**Comment by husiyu** [comment]
https://juejin.cn/post/6947898773569962020/

**Comment by lsvih** [comment]
收到
