### ISSUE TITLE
Mongodb 和 mysql 使用场景分析

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8351]
* 原文链接：[MongoDB Vs. MySQL: When to Use?](https://dzone.com/articles/mongodb-vs-mysql-when-to-use)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/mongodb-vs-mysql-when-to-use.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
文本使用官号发布，额外奖励 1 分

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 欢迎翻译

**Comment by samyu2000** [comment]
@lsvih 翻译完成
