### ISSUE TITLE
2021 年 Kubernetes 的开发者工具：Helm、Kustomize 和 Skaffold

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8352]
* 原文链接：[Developer Tooling for Kubernetes in 2021: Helm, Kustomize, and Skaffold](https://dzone.com/articles/developer-tooling-for-kubernetes-in-2021-helm-kust)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/developer-tooling-for-kubernetes-in-2021-helm-kust.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：5.5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文使用官方账号发布，额外奖励 1 分

**Comment by kamly** [comment]
@lsvih 认领翻译

**Comment by lsvih** [comment]
@kamly 欢迎翻译~

**Comment by husiyu** [comment]
掘金链接：https://juejin.cn/post/6951201659301134343/

**Comment by lsvih** [comment]
收到
