### ISSUE TITLE
谷歌 DeepMind 发布 NFNet：高效的深度网络

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8353]
* 原文链接：[Google DeepMind’s NFNets Offers Deep Learning Efficiency](https://www.infoq.com/news/2021/03/deepmind-NFNets-deep-learning/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/deepmind-NFNets-deep-learning)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by chzh9311** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@chzh9311 好的~
