### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zhanhongzhu** [xitu/gold-miner#8355]
- 公司/学校：湖南省创智和宇宙信息技术有限公司 湖北工业大学
- 工作内容/专业：国家医疗保障信息一体化建设web前端开发，主要开发信息管理系统，涉及广东、青海、甘肃、西藏等省。
- 常浏览的国外网站：https://developer.mozilla.org/zh-CN/;https://stackoverflow.com
- 英语水平：CET 6
- 翻译经验：暂时没有
- 主要翻译方向：比较喜欢tensorflow;其他方向也可以；
- 个人博客：https://zhanhongzhu.top;https://zhanhongzhu.gitee.io
- 个人介绍：喜欢研究技术；学习新的知识技能，同时也积极向优秀的前辈、同事和同龄人学习；不断提升自己的技术水平和知识储备；连续在两家中大型软件开发企业前端部门担任组长，负责项目环境搭建、基础组件开发、功能模块拆分、任务评估和任务分配工作，工作认真积极负责，对所负责的模块，严格把关，竭力将项目前端部分做到最好。同时积极向技术社区贡献自己的微博之力，帮助技术社区更好地建设，也跟其他开发者一起成长和进步。

**Comment by kezhenxu94** [comment]
Hi, 感谢你申请加入掘金翻译计划，你需要做以下的事：

1. 认真学习 [掘金翻译计划译者教程](https://github.com/xitu/gold-miner/wiki)，校对和翻译文章时，严格遵循教程，杜绝不看教程，只知道问的伸手党；
2. 确认认真学习了 [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)，翻译文章时严格遵循，校对文章时也要指出译者的格式错误；
3. 确认认真学习了 [翻译和校对文章的注意事项](https://github.com/xitu/gold-miner/wiki/%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88)，避免翻译校对过程中出错；
4. 加管理员微信 `kezhenxu94`，**验证信息格式**：翻译计划 + GitHub ID + 申请的 Issue Number；
5. 进群后修改群昵称为 GitHub ID。

**注意**：加完微信后，管理员会在当天拉你进译者群，进群之后做下简单的自我介绍。加入微信群则代表申请译者成功，接下来你需要看译者教程，然后先校对至少一篇文章才能开始正式翻译文章。当然也可以继续校对文章。
