### ISSUE TITLE
人工智能系统 Project Debater 即将提供 12 个新的云 API

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8361]
* 原文链接：[12 new Project Debater AI technologies available as cloud APIs](https://www.ibm.com/blogs/research/2021/03/project-debater-api/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/ibm-12-project-debater-api.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文使用官方账号发布，额外奖励 0.5 分

**Comment by Kimhooo** [comment]
翻译认领

**Comment by lsvih** [comment]
@Kimhooo 好的~

**Comment by husiyu** [comment]
https://juejin.cn/post/6955657126647857159/

**Comment by lsvih** [comment]
收到
