### ISSUE TITLE
Page Shield：保护浏览器中的用户数据

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8362]
* 原文链接：[Page Shield: Protect User Data In-Browser](https://blog.cloudflare.com/introducing-page-shield/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/introducing-page-shield.md)
* PR 地址：
* 文章分类：**资讯**，**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
翻译认领

**Comment by lsvih** [comment]
@PassionPenguin 好的

**Comment by PassionPenguin** [comment]
啊我漏了这个issue……

**Comment by PassionPenguin** [comment]
我漏了push了……

**Comment by itcodes** [comment]
这个现在啥进度了

**Comment by PassionPenguin** [comment]
？
