### ISSUE TITLE
每位 Web 开发者都应该知道的 7 个 JavaScript 基础知识

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8364]
- 原文链接：[7 JavaScript Fundamentals Every Web Developer Should Know](https://betterprogramming.pub/7-javascript-fundamentals-every-web-developer-should-know-8c0f7e491167)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/7-JavaScript-Fundamentals-Every-Web-Developer-Should-Know.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：10 天
- 校对时间：2 天
- 翻译积分：5 分
- 校对积分：2 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by HydeSong** [comment]
翻译认领

**Comment by lsvih** [comment]
@HydeSong 好的~
