### ISSUE TITLE
These Modern Programming Languages Will Make You Suffer

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8367]
- 原文链接：[These Modern Programming Languages Will Make You Suffer](https://betterprogramming.pub/modern-languages-suck-ad21cbc8a57c)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/These-Modern-Programming-Languages-Will-Make-You-Suffer.md)
- PR 地址：
- 文章分类：**通用**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：12 天
- 校对时间：5 天
- 翻译积分：15 分
- 校对积分：7 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by youngjuning** [comment]
翻译认领

**Comment by lsvih** [comment]
@youngjuning 好的

**Comment by PingHGao** [comment]
校对认领 @lsvih （可以预定校对不?）

**Comment by youngjuning** [comment]
@PingHGao 欢迎，我这个估计要假期才能翻完，贼长

**Comment by lsvih** [comment]
@youngjuning 辛苦啦 ❤️

**Comment by youngjuning** [comment]
> @youngjuning 辛苦啦 ❤️

介意加点积分吗 ？哈哈

**Comment by PingHGao** [comment]
> @PingHGao 欢迎，我这个估计要假期才能翻完，贼长

没问题，就是感兴趣又能涨分，哈哈

**Comment by 5Reasons** [comment]
这篇感觉是我见过最长的了 牛的

**Comment by PassionPenguin** [comment]
@youngjuning 翻译的咋样了，:喵:

**Comment by youngjuning** [comment]
这个周末写，抱歉，拖了这么久

**Comment by PassionPenguin** [comment]
-> 1m

**Comment by PassionPenguin** [comment]
=> see one possible translation https://read01.com/zh-cn/BJxKzD7.html#.YJKDwmQzZB0

**Comment by PassionPenguin** [comment]
=> 51cto https://developer.51cto.com/art/202012/634613.htm?pc
=> other results: https://www.baidu.com/s?wd=%E9%82%A3%E4%BA%9B%E8%AE%A9%E7%A0%81%E5%86%9C%E5%80%8D%E6%84%9F%E7%97%9B%E8%8B%A6%E7%9A%84%E7%8E%B0%E4%BB%A3%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80

**Comment by youngjuning** [comment]
@PassionPenguin 最近工作太忙了，大佬接了吧？

**Comment by lsvih** [comment]
这篇已经有翻译了，要是还没怎么翻我关了算啦

**Comment by youngjuning** [comment]
@lsvih 大大，抱歉，工作有点多最近

**Comment by lsvih** [comment]
@youngjuning 没事没事，工作辛苦啦，翻译只是调剂，别整成负担了
