### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by voidhug** [xitu/gold-miner#837]
哈尔滨工业大学软件学院大三学生，现负责 [Wi 输入法](http://wi.hit.edu.cn/) Android 开发，擅长技术领域为 JavaSE、Python、Android，四六级已过，非常想加入掘金翻译机会，谢谢。

**Comment by antonia0912** [comment]
@voidhug hi 欢迎来掘金翻译计划玩~请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群
