### ISSUE TITLE
Grafana 为其可视化产品栈新增企业级日志服务

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8371]
* 原文链接：[Grafana Adds Enterprise Logs to Its Managed Observability Stack](https://www.infoq.com/news/2021/03/grafana-managed-observability/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/grafana-managed-observability.md)
* PR 地址：
* 文章分类：**资讯**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
文本使用官方账号发布，额外奖励 0.5 分

**Comment by 5Reasons** [comment]
@lsvih 认领翻译~

**Comment by lsvih** [comment]
@5Reasons 欢迎翻译

**Comment by husiyu** [comment]
掘金链接 https://juejin.cn/post/6951201259495882788/

**Comment by lsvih** [comment]
收到
