### ISSUE TITLE
假如浏览器支持原生的“跳至内容”链接……

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8372]
* 原文链接：[Imagining native skip links](https://kittygiraudel.com/2021/03/07/imagining-native-skip-links/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/imagining-native-skip-link.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领翻译（ @lsvih

**Comment by PassionPenguin** [comment]
https://juejin.cn/post/6955827696731914271/

**Comment by lsvih** [comment]
收到
