### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by acechao** [xitu/gold-miner#838]
理工科男生，毕业1年，现在在一家互联网公司从事产品岗。熟悉Git ,android,前端，产品设计知识，业务时间活跃在简书、知乎、掘金社区，希望可以和更多志同道和的人一起学习进步；

**Comment by antonia0912** [comment]
@acechao 欢迎来到掘金翻译计划，请加我微信 antonia0912 备注 github id 我来拉你进译者群
