### ISSUE TITLE
推荐Kotlin资讯文章

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/gold-miner#8385]
- 原文链接：https://www.infoq.com/news/2021/03/the-road-to-kotlin-1-5
- 简要介绍：Kotlin 1.5 前最后一个1.4.x版本发布的功能探秘

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐Kotlin资讯文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
#8505 已发布校对，感谢推荐！

**Comment by PassionPenguin** [comment]
> #8505 已发布校对，感谢推荐！

歪！是不是打错字啦

**Comment by lsvih** [comment]
校对 => 认领
