### ISSUE TITLE
CSS 遮罩的过渡效果

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#839]
- 原文链接：[Transition Effect with CSS Masks](http://tympanus.net/codrops/2016/09/29/transition-effect-with-css-masks/)
- 掘金链接：[Transition Effect with CSS Masks](http://gold.xitu.io/entry/580dea3f2f301e005c47aa5b)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/transition-effect-with-css-masks.md)
- PR 地址：#851
- 文章分类：**前端**
---
- 翻译时间：`3` 天
- 校对时间：`1` 天
- 翻译积分：`4` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luoyaqifei** [comment]
认领

**Comment by sqrthree** [comment]
@luoyaqifei 好的
