### ISSUE TITLE
没有CS学历的我如何进入Google

### ISSUE THREAD

**Issue by keepmovingljzy** [xitu/gold-miner#8390]
- 原文链接：https://betterprogramming.pub/how-i-got-into-google-without-a-cs-degree-f1d3c0a3f10e
- 简要介绍：介绍了没有 CS学历如何进入 Google，我们应该学习他们身上的一些特质，值得翻译~

---

### 请完成并勾选一下三项：

* [ ] 按文章分类填写 issue 标题：推荐其他优秀英文文章
* [ ] 本文很值得翻译，我推荐
* [ ] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by keepmovingljzy** [comment]
@lsvih 本文我自己翻译哈

**Comment by lsvih** [comment]
这篇和国内情况啥的不太符合啊，而且介绍的网站、视频和书籍都没法直接用....

**Comment by keepmovingljzy** [comment]
> 这篇和国内情况啥的不太符合啊，而且介绍的网站、视频和书籍都没法直接用....

好吧
