### ISSUE TITLE
译者审核文章列表

### ISSUE THREAD

**Issue by Glowin** [xitu/gold-miner#84]
这个 issue 用来收集整理完成初稿的 Pull Request 文章，每个译者需要审核两篇其他译者发布 PR 的文章，一篇文章在两个译者都审核无误后才能 merge 到此项目中。

> 完成 PR 的译者朋友加我微信 Glowjiang，注明 Github ID，我来拉进翻译群哈

## 如何审核

1. 译者在下面留言，写上你希望审核的文章
2. @Glowin 添加审核员的名字到文章的后面
3. 审核员直接审核选中的文章的 PR，在觉得有问题的翻译地方添加 note，举个例子：#76
4. 每篇文章需要至少两个审核员

文章列表如下：
（还有14篇文章未发布PR）
[2015 年度 Android 开发者必备的 5 个开源库](https://github.com/xitu/gold-miner/pull/30/files) @lihb @xiuweikang (merged)
[3D Force Touch 的新玩儿法](https://github.com/xitu/gold-miner/pull/38/files) @cdpath @nathanwhy (merged)
[Things I Wish I Were Told About React Native](https://github.com/xitu/gold-miner/pull/51/files) @void-main @aleen42 (merged)
[Android 上的数据格式 FlatBuffers 介绍](https://github.com/xitu/gold-miner/pull/53/files) @404neko @yinshudi (merged)
[Retrofit 入门教程](https://github.com/xitu/gold-miner/pull/61/files) @kassadin @foolishgao (merged)
[通过 Electron 开发一个简单地桌面应用](https://github.com/xitu/gold-miner/pull/62/files) @sqrthree @void-main (merged)
[Absolute Beginner's Guide to Swift](https://github.com/xitu/gold-miner/pull/66/files) @Zhangjd @CaesarPan (merged)
[如何发布一个 React components](https://github.com/xitu/gold-miner/pull/74/files) @Aaaaaashu @achilleo (merged)
[《MVVM模式介绍》](https://github.com/xitu/gold-miner/pull/76/files) @EthanWu @foolishgao (merged)
[Slack如此成功的秘诀](https://github.com/xitu/gold-miner/pull/77/files) @cdpath @CaesarPan (merged)
[Making React Native apps accessible](https://github.com/xitu/gold-miner/pull/78/files) @aleen42 (merged)
[《JavaScript 开发者年度调查报告》](https://github.com/xitu/gold-miner/pull/79/files) @Zhangdroid @Yves-X (merged)
[Chrome Devtools Tips & Tricks](https://github.com/xitu/gold-miner/pull/80/files) @Zhangdroid @EthanWu @zxc0328 (merged)
[Android 的一个 MVP 基础项目模板](https://github.com/xitu/gold-miner/pull/82/files) @kassadin @Sausure (merged)
[探索 Stripe Dashboard 产品设计之道](https://github.com/xitu/gold-miner/pull/83/files) @404neko @Zhangjd (merged)
[《Pokedex.org 给宠物小精灵爱好者的 web app 的技术选型》](https://github.com/xitu/gold-miner/pull/85/files) @Zhangjd 
[《Making Learning Easier by Design》](https://github.com/xitu/gold-miner/pull/86/files) @Yves-X @boycechang @achilleo (merged)
[如何高效的使用Okhttp](https://github.com/xitu/gold-miner/pull/87/files) @Sausure @yinshudi
[《How do Promises Work?》](https://github.com/xitu/gold-miner/pull/89/files) @zxc0328 @Aaaaaashu (merged)
[《2015 年底 JS 必备工具集》](https://github.com/xitu/gold-miner/pull/91/files) @achilleo (merged)
[《如何提高安卓代码的质量和语法》](https://github.com/xitu/gold-miner/pull/92/files) @laobie (merged)
[Artsy 工程师总结的一些 Cocoa 开发设计误区](https://github.com/xitu/gold-miner/pull/93/files) @iThreeKing @walkingway (merged)
[Android Studio Tips](https://github.com/xitu/gold-miner/pull/95/files?diff=split) @Glowin @void-main (merged)
[An Introduction to Sprite Animation](https://github.com/xitu/gold-miner/pull/96/files) @iThreeKing (merged)
[Animated SVG vs GIF](https://github.com/xitu/gold-miner/pull/97/files) @ychow (merged)
[让 Toolbar 随着 RecyclerView 的滚动而显示/隐藏](https://github.com/xitu/gold-miner/pull/98/files) @laobie (merged)
[《编写高质量的 Swift 代码》](https://github.com/xitu/gold-miner/pull/99/files) @nathanwhy @walkingway (merged)
[UIKit 里如何面向协议编程](https://github.com/xitu/gold-miner/pull/100/files) @ychow (merged)
[6 Things I wish I Knew before I Wrote my first Android App](https://github.com/xitu/gold-miner/pull/101/files) @achilleo @Glowin (merged)
[苹果正在带坏整个设计圈](https://github.com/xitu/gold-miner/pull/103/files?diff=split) @iThreeKing  (merged)

特殊情况：
下面这些文章没有认领就已经翻译的

[Chrome Devtools Tips](https://github.com/xitu/gold-miner/pull/48/files)
[人人须知的jQuery技巧](https://github.com/xitu/gold-miner/pull/49/files) @sqrthree (merged)
[6 Things I wish I Knew before I Wrote my first Android App by bobmayuze](https://github.com/xitu/gold-miner/pull/56/files) @lihb @xiuweikang
[things i wish i were told about react native by void-main](https://github.com/xitu/gold-miner/pull/71)

**Comment by RobertWang** [comment]
如何审核？只需要留言确认审核通过就行吗？

**Comment by lihb** [comment]
> 如何审核? 只需要留言确认审核通过就行吗？

同问。我选这两篇把。#30，#56，大家不要和我抢，哈哈。

**Comment by xiuweikang** [comment]
对Android比较熟悉，我和 @lihb  一起审核#30和#56吧。

**Comment by Glowin** [comment]
@RobertWang @lihb 我把审核过程加到 issue 里面咯，你看看，如果有需要补充的请留言哈。

@lihb @xiuweikang 我来加你们到 issue 里面。

**Comment by 404neko** [comment]
你们掘金就是想要翻译的文章罢了 完全不讲道理是吧

**Comment by kassadin** [comment]
审核标准是什么？不用逐字逐句精准翻译吧
我撸 #61 #82 吧

**Comment by Zhangdroid** [comment]
我选 #79 #80 吧～

**Comment by nathanwhy** [comment]
iOS #38 #66

**Comment by Sausure** [comment]
刚开始没说让我们校对的......掘金做事也这么不靠谱？我#87和#82吧

**Comment by EthanWu** [comment]
我对前端开发和设计模式比较感兴趣，选#80 和 #76 。

**Comment by Yves-X** [comment]
#79 #86

**Comment by sqrthree** [comment]
我是做前端开发的，就选这两个吧， #49  #80

**Comment by void-main** [comment]
我来审核 #51 #62 吧～

**Comment by Glowin** [comment]
楼上的朋友我已经加到 issue 里面了。

@Sausure 因为翻译计划里面只是翻译的安排，没有把审核算在里面，因为我没有把这个说明白导致误会，我给大家道歉。

**Comment by Zhangjd** [comment]
我选 #85 #66

**Comment by cdpath** [comment]
I choose  #38 and #77 .

**Comment by aleen42** [comment]
#78 #51

**Comment by foolishgao** [comment]
#61  #76

**Comment by zxc0328** [comment]
#80 #89

**Comment by Glowin** [comment]
楼上的都加上咯，欢迎多多提建议哈

**Comment by boycechang** [comment]
#36 #86

**Comment by 404neko** [comment]
#83 #53

**Comment by Glowin** [comment]
@boycechang #36 《编写高质量的 Swift 代码》这个文章还没有发布 PR，等作者完成后我再添加你哈。

**Comment by yinshudi** [comment]
我选#53 和 #87

**Comment by nathanwhy** [comment]
#36 #38

**Comment by CaesarPan** [comment]
#66 #77

**Comment by Aaaaaashu** [comment]
#89 #74

**Comment by rainyear** [comment]
#97 初稿完成，请求加入审核队列

**Comment by kassadin** [comment]
#30 #61 #82 已完成翻译+校对+二次修改，@Glowin 看看还要干点儿啥

**Comment by Glowin** [comment]
@Aaaaaashu @CaesarPan 添加你们到审核文章里面咯

@kassadin 辛苦啦，你加到活动微信群了么？

**Comment by Sausure** [comment]
@Glowin #76 已完成翻译+校正+二次修改

**Comment by Sausure** [comment]
@Glowin 对了，请问活动微信群是什么？我还没加耶。。。

**Comment by iThreeKing** [comment]
#93 #96  @Glowin 另外 #99 已经翻译完成 请求加入审核列表

**Comment by cdpath** [comment]
#66 已完成校对。@Glowin

**Comment by yinshudi** [comment]
#53 已完成校对

**Comment by lihb** [comment]
#30，#56 校对完成

**Comment by nathanwhy** [comment]
之前选的 #36  人满了，麻烦改为 #99

**Comment by MiJack** [comment]
#98 完成翻译

**Comment by Sausure** [comment]
@Glowin 请问现在怎么没消息了？我的已经翻译+校正+二次修改已经完成，那说好的奖品呢？

**Comment by Glowin** [comment]
@Sausure 我这边还在按照发送 PR 的顺序撸翻译中，你加一下我微信 Glowjiang 拉你进群哈

**Comment by Glowin** [comment]
Android Studio Tips #95 我已经修改好格式了，不像上次显示大段大段的 diff，大家可以认领啦

**Comment by walkingway** [comment]
我来认领审核 #99 #93 ，另外我的 #100 已经翻译完毕，求加入审核列表

**Comment by ychow** [comment]
我来认领审核 #97 #100

**Comment by Glowin** [comment]
@walkingway @ychow 二位都加到列表里面啦

**Comment by Glowin** [comment]
@Aaaaaashu 请问一下 #74 这个 PR 审核进度如何呢？

**Comment by laobie** [comment]
#92 #98 我来审核下

**Comment by void-main** [comment]
认领 #95

**Comment by walkingway** [comment]
#99 #93 这两篇我这块已经审核完毕

**Comment by sqrthree** [comment]
#49 #62 这两篇我之前也已经审核完毕，这里记录一下。

**Comment by laobie** [comment]
@Glowin #95 根据审核意见修改完成
#92 #98 校对完成

**Comment by achilleo** [comment]
#91 已审核

**Comment by adamin1990** [comment]
你们英文都好棒啊

**Comment by aleen42** [comment]
@Glowin #74 have a look, is there any problems?

**Comment by iThreeKing** [comment]
@Glowin  #93 #96 审核完毕

**Comment by Glowin** [comment]
@adamin1990 欢迎加入我们的翻译计划哟

@aleen42 #74 还是有冲突，麻烦你和主仓库的 merge 一下先

@iThreeKing #93 已经 merge 啦

**Comment by void-main** [comment]
@adamin1990 居然是老乡～2333

**Comment by Glowin** [comment]
#100 和 #103 两篇文章因为完成的比较晚，哪位译者愿意认领一下呢？

这两篇文章都很长的

**Comment by iThreeKing** [comment]
#103 认领 @Glowin

**Comment by Glowin** [comment]
@iThreeKing 收到，我来添加到 issue 里面

**Comment by lfkdsk** [comment]
@Glowin 选择[#94](https://github.com/xitu/gold-miner/pull/94)和[#97](https://github.com/xitu/gold-miner/pull/97)

**Comment by Glowin** [comment]
@lfkdsk 这些都是上次活动的 issue 呢，上次活动已经结束啦，所有的文章都翻译+审核完了。
