### ISSUE TITLE
Android 动画的灵魂—— Interpolator 

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#840]
- 原文链接：[Timing is Everything](https://medium.com/google-developers/timing-is-everything-8218b8df5485#.tlp6t4pxv)
- 掘金链接：[Timing is Everything](http://gold.xitu.io/entry/580f03f867f3560057c73291)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/timing-is-everything.md)
- PR 地址：#849
- 文章分类：**Android**
---
- 翻译时间：`3` 天
- 校对时间：`1` 天
- 翻译积分：`4` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luoyaqifei** [comment]
感觉是安卓动画方面的文章

**Comment by sqrthree** [comment]
@luoyaqifei 哈哈好的~ 那就安卓了~

**Comment by siegeout** [comment]
认领

**Comment by sqrthree** [comment]
@siegeout 好的

**Comment by yifili09** [comment]
@sqrthree  还有校对的位置么？

**Comment by sqrthree** [comment]
@yifili09 有的有的，地址在这哈~ https://github.com/xitu/gold-miner/pull/849 给你算一个~
