### ISSUE TITLE
Android 开发者如何通过运动视觉 API 进行机器学习？Part 1 — 人脸检测

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#841]
- 原文链接：[Machine Learning for Android Developers with the Mobile Vision API— Part 1 — Face Detection](https://hackernoon.com/machine-learning-for-android-developers-with-the-mobile-vision-api-part-1-face-detection-e7e24a3e472f#.9ay7ilk9b)
- 掘金链接：[Android 开发者如何通过运动视觉 API 进行机器学习？Part 1 — 人脸检测](http://gold.xitu.io/entry/580ef2502f301e005c4d28bb)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/machine-learning-for-android-developers-with-the-mobile-vision-api-part-1-face-detection.md)
- PR 地址：#880
- 文章分类：**Android**

---
- 翻译时间：`3` 天
- 校对时间：`1` 天
- 翻译积分：`4` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
@sqrthree 收！

**Comment by sqrthree** [comment]
@yifili09 好的

**Comment by yifili09** [comment]
@sqrthree #880 欢迎校对光临。

**Comment by yifili09** [comment]
@sqrthree  @antonia0912 我推荐原文链接中的提到的每一篇文章 😸 😸 !!
