### ISSUE TITLE
当 Android 的 Compat 库不能拯救你的时候

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8420]
* 原文链接：[When “Compat” libraries won’t save you](https://proandroiddev.com/when-compat-libraries-do-not-save-you-dc55f16b4160)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/when-compat-libraries-do-not-save-you.md)
* PR 地址：
* 文章分类：**Andoird**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
published at https://juejin.cn/post/6955828449210548261/

**Comment by lsvih** [comment]
收到
