### ISSUE TITLE
Flutter 动画：构建一个和 Medium 一样的鼓掌动画

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8421]
* 原文链接：[Flutter Animation : Creating medium’s clap animation in flutter](https://proandroiddev.com/flutter-animation-creating-mediums-clap-animation-in-flutter-3168f047421e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/flutter-animation-creating-mediums-clap-animation-in-flutter.md)
* PR 地址：
* 文章分类：**Flutter**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：- 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
published at https://juejin.cn/post/6955826124345573384/

**Comment by lsvih** [comment]
收到
