### ISSUE TITLE
没有 UI 团队怎么办？分享 6 款能为独立网页开发者提效的免费工具

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8424]
* 原文链接：[6 amazing free tools that will save you some time when u are building websites. (Especially for 'non-designer' developers)](https://dev.to/devggaurav/6-amazing-free-tools-that-will-save-you-some-time-when-u-are-building-websites-especially-for-non-designer-developers-2930)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/6-amazing-free-tools-that-will-save-you-some-time-when-u-are-building-websites-especially-for-non-designer-developers.md)
* PR 地址：
* 文章分类：**其他**，**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：1.5 分
* 校对积分：0.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by 5Reasons** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@5Reasons 欢迎翻译~
