### ISSUE TITLE
使用 Flutter 构建一个名言名句应用程序

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8426]
* 原文链接：[Flutter Quotes App](https://medium.com/flutterdevs/flutter-quotes-app-bb30ef27b255)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/flutter-quotes-app.md)
* PR 地址：
* 文章分类：**Flutter**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
published at https://juejin.cn/post/6955827325254500360/

**Comment by lsvih** [comment]
收到
