### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by xuzaixian** [xitu/gold-miner#843]
本人大四，现在金山云担任前端开发实习生。平时逛Github，可以在StackOverflow中查找并解决自己的问题。以前一直有在掘金看一些文章，从中受益匪浅。前端的内容更新很快，很多新东西一直在蹦出来。现在想回馈一下社区，让更多的人阅读到更好的文章。平时接触英语较多，虽然没有翻译经验！有信心翻译出一些高质量文章…请组织收了我吧！
个人博客:hyuni.cn

**Comment by antonia0912** [comment]
@xuzaixian 欢迎来到掘金翻译计划，请加我微信 antonia0912 备注 github id 我来拉你进译者群
