### ISSUE TITLE
推荐后端优秀英文文章

### ISSUE THREAD

**Issue by huifrank** [xitu/gold-miner#8435]
- 原文链接：[http://db-oriented.com/2018/02/15/adding-a-unique-constraint-in-an-online-way/](http://db-oriented.com/2018/02/15/adding-a-unique-constraint-in-an-online-way/)
- 简要介绍：以在线（online）方式添加唯一约束-oracle

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐后端优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by huifrank** [comment]
如果我早点看到这篇文章    哎   不说了

**Comment by lsvih** [comment]
#8448 已发布认领，感谢推荐
