### ISSUE TITLE
从 React 转换到 Next.js 的五个理由

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8439]
- 原文链接：[5 Reasons to Switch from React to Next.js](https://javascript.plainenglish.io/5-reasons-to-switch-from-react-to-next-js-f776413693d0)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/5-Reasons-to-Switch-from-React-to-Next-js.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**

---

- 翻译时间：10 天
- 校对时间：2 天
- 翻译积分：8 分
- 校对积分：3 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好嘞
