### ISSUE TITLE
Mozilla 对行业最大的贡献是 Rust，而不是火狐浏览器

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8444]
* 原文链接：[Rust, not Firefox, is Mozilla's greatest industry contribution](https://www.techrepublic.com/article/rust-not-firefox-is-mozillas-greatest-industry-contribution/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/rust-not-firefox-is-mozillas-greatest-industry-contribution.md)
* PR 地址：
* 文章分类：**资讯**，**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：3.5 + 1 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文使用官方账号发布

**Comment by lsvih** [comment]
本文使用官方账号发布

**Comment by greycodee** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@greycodee  好的~

**Comment by husiyu** [comment]
https://juejin.cn/post/6952819591269580813/

**Comment by lsvih** [comment]
收到
