### ISSUE TITLE
Google 的 Apollo 芯片设计人工智能框架将深度学习芯片的性能提高了 25％

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8445]
* 原文链接：[Google's Apollo AI for Chip Design Improves Deep Learning Performance by 25%](https://www.infoq.com/news/2021/03/google-ai-chip-design)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/google-ai-chip-design.md)
* PR 地址：
* 文章分类：**资讯**，**AI**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：4.5 + 1 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文使用官方账号发布~

**Comment by PingHGao** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
PingHGao 好嘞

**Comment by husiyu** [comment]
https://juejin.cn/post/6952819856429285407/
