### ISSUE TITLE
在线添加唯一索引

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8448]
* 原文链接：[Adding a Unique Constraint in an Online Way](http://db-oriented.com/2018/02/15/adding-a-unique-constraint-in-an-online-way/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/adding-a-unique-constraint-in-an-online-way.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：4 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kamly** [comment]
@lsvih 认领翻译

**Comment by lsvih** [comment]
@kamly 欢迎翻译

**Comment by husiyu** [comment]
https://juejin.cn/post/6955659229311008781

**Comment by lsvih** [comment]
收到
