### ISSUE TITLE
Swift 3 语言中的全模块优化

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#845]
- 原文链接：[Whole-Module Optimization in Swift 3](https://swift.org/blog/whole-module-optimizations/)
- 掘金链接：[Swift 3 语言中的全模块优化](http://gold.xitu.io/entry/580f5bf25bbb50005b6d2f45)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/whole-module-optimizations.md)
- PR 地址：#866
- 文章分类：**iOS**
---
- 翻译时间：`3` 天
- 校对时间：`1` 天
- 翻译积分：`4` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Edison-Hsu** [comment]
@sqrthree 文章认领

**Comment by sqrthree** [comment]
@Edison-Hsu 好的
