### ISSUE TITLE
可以在下一个项目中使用的 20 个 Go 三方库

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8457]
* 原文链接：[20 Go Packages You Can Use in Your Next Project](https://medium.com/vacatronics/20-go-packages-you-can-use-in-your-next-project-7515426559c0)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/20-go-packages-you-can-use-in-your-next-project.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由 @tmpbook 认领翻译

**Comment by tmpbook** [comment]
@lsvih 收到，多谢
