### ISSUE TITLE
如何设计应用的推送通知？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#846]
- 原文链接：[What You Must Know To Build Savvy Push Notifications](http://firstround.com/review/what-you-must-know-to-build-savvy-push-notifications/)
- 掘金链接：[如何设计应用的推送通知？](http://gold.xitu.io/entry/580f5885570c350068fefaa0)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-you-must-know-to-build-savvy-push-notifications.md)
- PR 地址：#865
- 文章分类：**产品**
---
- 翻译时间：`4` 天
- 校对时间：`2` 天
- 翻译积分：`8` 分
- 校对积分：`2` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by laobie** [comment]
认领翻译

**Comment by sqrthree** [comment]
@laobie 好的
