### ISSUE TITLE
使用 VPython 进行物理模拟

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8461]
* 原文链接：[Physics Simulations Using VPython](https://levelup.gitconnected.com/physics-simulations-using-vpython-a3d6ee69d121)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/physics-simulations-using-vpython.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tmpbook** [comment]
认领

**Comment by lsvih** [comment]
@tmpbook 好嘞
