### ISSUE TITLE
Cross-site Scripting (XSS)

### ISSUE THREAD

**Issue by MoonBall** [xitu/gold-miner#8462]
- 原文链接：https://www.acunetix.com/websitesecurity/cross-site-scripting/
- 简要介绍：讲述跨站脚本攻击的方式、目的以及如何防止。

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/Kotlin/其他/资讯优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by MoonBall** [comment]
认领翻译

**Comment by lsvih** [comment]
#8465 已发布认领，感谢推荐
