### ISSUE TITLE
JavaScript ES6 核心功能一览

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#848]
- 原文链接：[Overview of JavaScript ES6 features (a.k.a ECMAScript 6 and ES2015+)](http://adrianmejia.com/blog/2016/10/19/Overview-of-JavaScript-ES6-features-a-k-a-ECMAScript-6-and-ES2015/)
- 掘金链接：[JavaScript ES6 核心功能一览](http://gold.xitu.io/entry/580f4ffd5bbb50005b6c847b)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/Overview-of-JavaScript-ES6-features-a-k-a-ECMAScript-6-and-ES2015.md)
- PR 地址：#864
- 文章分类：**前端**
---
- 翻译时间：`3` 天
- 校对时间：`1` 天
- 翻译积分：`5` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by L9m** [comment]
认

**Comment by antonia0912** [comment]
@L9m got~
