### ISSUE TITLE
Numpy 运行于 GPU/TPU 时的性能

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8482]
* 原文链接：[Numpy on GPU/TPU](https://medium.com/ml-mastery/numpy-on-gpu-tpu-efb8d367020a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/numpy-on-gpu-tpu.md)
* PR 地址：
* 文章分类：**算法**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好的~

**Comment by samyu2000** [comment]
@lsvih 翻译完成
