### ISSUE TITLE
推荐其他优秀英文文章

### ISSUE THREAD

**Issue by mengrenzi** [xitu/gold-miner#8484]
- 原文链接：https://blog.janestreet.com/what-a-jane-street-dev-interview-is-like/
- 简要介绍：文章出自于 Jane Street 的官方博客，介绍了著名高频交易公司 Jane Street 如何选拔优秀的软件开发工程师。Jane Street 是一家很酷、超前的公司，擅长运用现代科技协助决策，公司技术氛围浓厚，员工离职率低。对于计算机专业毕业生来说，Jane Street 的 offer 甚至比谷歌的 offer 更具吸引力。

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐 其他 优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
这篇的招聘广告意味太重了，不太好加哈 🤣
