### ISSUE TITLE
关于更新《译文排版规则指北》提议

### ISSUE THREAD

**Issue by KimYangOfCat** [xitu/gold-miner#8487]
Hello，大家好，最近想要参与社区校对工作时，发现了一个问题，译文和原文行数不一致导致`File Changed` 排版混乱，给校对工作带来了非常大的困难，例如:  #8432  等 PR。

而这个问题可以通过约定，要求译文和原文行数一致，得到有效解决，例如：#8486 等 PR；如此，不仅能提升文章的校对体验，还能大幅提升校对效率。

但是在 [《译文排版规则指北》](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97) 一文中，我并没有找到与之相关的明确约定。

故此提出一个提议，请问大家觉得是否有必要在[《译文排版规则指北》](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97) 中添加上`译文与原文行数要求一致`的约定？

**Comment by PassionPenguin** [comment]
### 有一说一做不到，或者说，会有别的特性冒出来

1. 我到现在都还没摸清 github 的 line rules
2. 本地 ide（idea 全系）与 github 的识别不一
3. 文章会包含错误，不管是推介的时候的格式问题或是原文本身的问题。倘若保留错误，会增加译者与管理员在 merge 时候的痛苦，非常容易落下问题没有修改
  A. 谁晓得到时候还记不记得这里应该改什么......而且这样预留内容反而也会让校对者无法校对这部分，如果单独贴出来那更麻烦了...
  B. 不少原文代码都有问题，尤其出现在 medium 上的文章，在标题层级、代码全角半角甚至代码本身都是错的或是段落本身都是无关不知所言的。（还有人能够瞎扯扯热力学定理宇宙消寂的）

校正译文本来就不是 suggestion，suggestion 那部分的补充还是我添加的...一开始还有不少人在用 =》 表示修改

奈何 github 的功能太...也不支持 pdf，另一个仓库的校对者校对我的 pdf 的时候还得用 acrobat

还是不要太过依赖于平台，诚然它挺好用，我也喜欢，毕竟译者能够 quickly get the proposal changes

**Comment by lsvih** [comment]
这个暂时没办法完全保持一致，很多时候英文的分段不一定适用于中文的分段。此外也有@PassionPenguin 说的代码排版的问题（虽然一致不建议 reformat 代码..）也会造成段落识别错误。

目测 github 用了不同层级的标签（比如 h1 h2 codeblock 等）找最小编辑距离来匹配

**Comment by lsvih** [comment]
#8432 这样的 pr 是例外，因为一般来说是译者从开始就在平台上翻译的，这样自然行数啥的一般都能对上，这个 pr 是译者自己先翻译完了，再直接替换的源文件，所以很多内容对应不上了

**Comment by PassionPenguin** [comment]
> #8432 这样的 pr 是例外，因为一般来说是译者从开始就在平台上翻译的，这样自然行数啥的一般都能对上，这个 pr 是译者自己先翻译完了，再直接替换的源文件，所以很多内容对应不上了

并不是，是推文的时候没处理好...图片重复了...

![Screenshot_2021-04-23-18-23-14-472_com.github.android.jpg](https://user-images.githubusercontent.com/41184947/115858027-0950b800-a461-11eb-972a-bf24c65f1b31.jpg)

**Comment by lsvih** [comment]
@PassionPenguin 好叭
