### ISSUE TITLE
使用 Web Workers 来加速 JavaScript 应用

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8495]
* 原文链接：[Using Web Workers to Speed-Up JavaScript Applications](https://blog.bitsrc.io/using-web-workers-to-speed-up-javascript-applications-5c567f209bdb)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/using-web-workers-to-speed-up-javascript-applications.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：1 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Usualminds** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Usualminds 好嘞
