### ISSUE TITLE
“绿色”和“棕色”的编程语言

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8497]
* 原文链接：[Green Vs. Brown Programming Languages](https://earthly.dev/blog/brown-green-language/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/brown-green-language.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：6.5 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by tmpbook** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@tmpbook  好的

**Comment by lsvih** [comment]
本文释放，可重新被认领

**Comment by chzh9311** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@chzh9311 好的

**Comment by chzh9311** [comment]
@lsvih 翻译完成~
