### ISSUE TITLE
Android Material 搜索框实现详细说明

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#850]
- 原文链接：[Exposing the Searchbar Implementing a Dialer-like Search transition](https://medium.com/@alexstyl/https-medium-com-alexstyl-animating-the-toolbar-7a8f1aab39dd#.waucttqbf)
- 掘金链接：[Android Material 搜索框实现详细说明](http://gold.xitu.io/entry/5810759bbf22ec0058424e1a)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/https-medium-com-alexstyl-animating-the-toolbar.md)
- PR 地址：#871
- 文章分类：**Android**

----
- 翻译时间：`3` 天
- 校对时间：`1` 天
- 翻译积分：`4` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by siegeout** [comment]
认领

**Comment by sqrthree** [comment]
@siegeout 好的
