### ISSUE TITLE
深入理解 CORS：发展史、工作原理和最佳实践

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8503]
* 原文链接：[Deep dive in CORS: History, how it works, and best practices](https://ieftimov.com/post/deep-dive-cors-history-how-it-works-best-practices/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/deep-dive-cors-history-how-it-works-best-practices.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：20 天
* 校对时间：5 天
* 翻译积分：10 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by snowyYU** [comment]
翻译认领

**Comment by snowyYU** [comment]
@lsvih

**Comment by lsvih** [comment]
@snowyYU 好的~

**Comment by snowyYU** [comment]
@lsvih 翻译完成
