### ISSUE TITLE
走向 kotlin 1.5

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8505]
* 原文链接：[The Road to Kotlin 1.5](https://www.infoq.com/news/2021/03/the-road-to-kotlin-1-5/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/the-road-to-kotlin-1-5.md)
* PR 地址：
* 文章分类：**Kotlin**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好的

**Comment by samyu2000** [comment]
@lsvih 翻译完成
