### ISSUE TITLE
Github Actions 是如何渲染超大日志的

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8512]
* 原文链接：[How GitHub Actions renders large-scale logs](https://github.blog/2021-03-25-how-github-actions-renders-large-scale-logs/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/how-github-actions-renders-large-scale-logs.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by felixliao** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@felixliao 好嘞
