### ISSUE TITLE
TypeScript 中的依赖注入

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8517]
* 原文链接：[Dependency Injection in TypeScript](https://levelup.gitconnected.com/dependency-injection-in-typescript-2f66912d143c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/dependency-injection-in-typescript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：5.5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Usualminds** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
好嘞
