### ISSUE TITLE
以下就是你需要知道的有关苹果 App Tracking Transparency（应用追踪透明）的信息

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8519]
* 原文链接：[Here’s Exactly What You Need to Know About Apple’s App Tracking Transparency](https://onezero.medium.com/heres-exactly-what-you-need-to-know-about-apple-s-app-tracking-transparency-bdb06c0b58c0)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/heres-exactly-what-you-need-to-know-about-apple-s-app-tracking-transparency.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：12 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LoneyIsError** [comment]
翻译认领

**Comment by lsvih** [comment]
@LoneyIsError 欢迎翻译~
