### ISSUE TITLE
推荐其他资讯优秀英文文章

### ISSUE THREAD

**Issue by PingHGao** [xitu/gold-miner#8524]
- 原文链接：https://towardsdatascience.com/stop-using-print-to-debug-in-python-use-icecream-instead-79e17b963fcc
- 简要介绍：介绍了代替 print 函数调试 python 程序的 ICream 包。这个包是真的非常好用，粗略搜索没有搜到任何相关信息。

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/Kotlin/其他/资讯优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
这篇有译文了 https://zhuanlan.zhihu.com/p/368731625  =。=
