### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by fengzhihao123** [xitu/gold-miner#853]
你好，我叫fengzhihao123，计算机科学与技术专业毕业，现在在天津空弦科技任职iOS开发工程师。具有较好的英语基础，经常访问Github/Stackoverflow/Quora社区。这是我的github地址：https://github.com/fengzhihao123 ,非常希望加入掘金大家庭，为开源贡献自己的一份力量。

**Comment by antonia0912** [comment]
@fengzhihao123 欢迎来到掘金翻译计划  请加我微信antonia0912 备注 GitHub ID 我来拉你进译者群
