### ISSUE TITLE
推荐iOS优秀英文文章

### ISSUE THREAD

**Issue by LoneyIsError** [xitu/gold-miner#8531]
- 原文链接：Swift 并发四部曲
1. Parallel programming with Swift: Basics：https://medium.com/flawless-app-stories/basics-of-parallel-programming-with-swift-93fee8425287
2. Parallel programming with Swift: Operations：https://medium.com/flawless-app-stories/parallel-programming-with-swift-operations-54cbefaf3cb0
3. Parallel programming with Swift: Promises：https://medium.com/flawless-app-stories/parallel-programming-with-swift-promises-740be1a260ed
4. Parallel Programming with Swift: What could possibly go wrong?https://medium.com/flawless-app-stories/parallel-programming-with-swift-what-could-possibly-go-wrong-f5bcc38b1814
- 简要介绍： 讲解一下Swift 中的并发，系列很全，目前看来并没有什么译者翻译过，并且在 medium 👏 不低
部分文章存在繁体译文，未发现简体中文译文
---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/Kotlin/其他/资讯优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
好像有一些已经有了

https://www.appcoda.com.tw/promises/
https://appcoda.com.tw/parallel-programming/

**Comment by LoneyIsError** [comment]
部分文章存在繁体译文，但是这个大而全的一个系列没有全部翻译成功

**Comment by lsvih** [comment]
@LoneyIsError 可以的，我们重新弄一下
