### ISSUE TITLE
Dagger，Hilt 以及 Koin 的本质区别是什么？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8537]
* 原文链接：[How Dagger, Hilt and Koin differ under the hood?](https://proandroiddev.com/how-dagger-hilt-and-koin-differ-under-the-hood-c3be1a2959d7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md)
* PR 地址：
* 文章分类：**Kotlin**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由@keepmovingljzy 认领

**Comment by keepmovingljzy** [comment]
@lsvih 翻译完成
