### ISSUE TITLE
有关 ECMAScript 最新版本的所有信息｜ECMAScript 2021

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8539]
* 原文链接：[Everything about the latest ECMAScript release | ECMAScript 2021](https://levelup.gitconnected.com/everything-about-the-latest-ecmascript-release-ecmascript-2021-c011e817f41a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/everything-about-the-latest-ecmascript-release-ecmascript-2021.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：6 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领翻译

**Comment by PassionPenguin** [comment]
噗哈哈哈哈哈逻辑赋值运算符当时我就出了一份力（
