### ISSUE TITLE
再见，汉堡包式菜单，我们有了新的 Android 交互设计方案

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#854]
- 原文链接：[Bye, Bye Burger! What we learned from implementing the new Android Bottom Navigation](https://medium.com/startup-grind/bye-bye-burger-5bd963806015#.b1x3w6elg)
- 掘金链接：[再见，汉堡包式菜单，我们有了新的 Android 交互设计方案](http://gold.xitu.io/entry/58108e18bf22ec0058431559)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/bye-bye-burger.md)
- PR 地址：#874
- 文章分类：**Android**

---
- 翻译时间：`3` 天
- 校对时间：`1` 天
- 翻译积分：`5` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by haoyh** [comment]
认领

**Comment by shenxn** [comment]
认领！一万年没有来翻译了。

**Comment by sqrthree** [comment]
好的👌🏻
