### ISSUE TITLE
Kotlin Multiplatform Mobile 的三模块问题

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8545]
* 原文链接：[Three-framework problem with Kotlin Multiplatform Mobile](https://medium.com/xorum-io/three-framework-problem-with-kotlin-multiplatform-mobile-16267c5afa53)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/three-framework-problem-with-kotlin-multiplatform-mobile.md)
* PR 地址：
* 文章分类：**Kotlin**，**iOS**，**Android**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领翻译
