### ISSUE TITLE
Is AI Already an Essential Part of Content Marketing?

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8547]
* 原文链接：[Is AI Already an Essential Part of Content Marketing?](https://ai.plainenglish.io/ai-in-content-marketing-1d0d4b926769)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/ai-in-content-marketing.md)
* PR 地址：
* 文章分类：**AI**，**资讯**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by 5Reasons** [comment]
@lsvih 认领翻译~

**Comment by lsvih** [comment]
@5Reasons  好的~
