### ISSUE TITLE
未经测试的 Python 代码已经损坏

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8549]
* 原文链接：[Untested Python Code is Already Broken](https://python.plainenglish.io/untested-python-code-is-already-broken-934cb40b547b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/untested-python-code-is-already-broken.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：17 天
* 校对时间：3 天
* 翻译积分：8 分
* 校对积分：3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@greycodee 好的

**Comment by jaredliw** [comment]
@lsvih 闲置好久了，能接手吗？

**Comment by greycodee** [comment]
> @lsvih 闲置好久了，能接手吗？

不好意思。最近没有时间翻译。@jaredliw 你来翻译吧

**Comment by lsvih** [comment]
@jaredliw 麻烦您
啦

**Comment by jaredliw** [comment]
@greycodee 抱歉哈，不是有意要抢，想到放着也是放着，就问了一下，在此谢过啦

**Comment by jaredliw** [comment]
@lsvih 翻译完成~
