### ISSUE TITLE
什么是移动端 DevOps，为什么值得你关注？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8551]
* 原文链接：[What Is Mobile DevOps, and Why Should You Care?](https://betterprogramming.pub/what-is-mobile-devops-and-why-should-you-care-7e9094c8b034)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/what-is-mobile-devops-and-why-should-you-care.md)
* PR 地址：
* 文章分类：**Android**，**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：20 天
* 校对时间：4 天
* 翻译积分：11.5 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@Kimhooo  好的，这篇比较长，慢慢来哈~

**Comment by jaredliw** [comment]
#8559 怎么关了 我来代理发布吧
文章很棒 我就不做修改了 单纯改改标点符号
