### ISSUE TITLE
Node.js 与 Python ：为你的项目选择哪一个？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8564]
* 原文链接：[Node.js vs. Python: Which One to Choose for Your Project?](https://javascript.plainenglish.io/node-js-vs-python-which-one-to-choose-for-your-project-331c33c958a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/node-js-vs-python-which-one-to-choose-for-your-project.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kamly** [comment]
@lsvih 认领翻译

**Comment by lsvih** [comment]
@kamly  好嘞
