### ISSUE TITLE
快停止在 CSS 中使用像素单位

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8566]
* 原文链接：[Stop Using the Pixel Unit in CSS](https://betterprogramming.pub/stop-using-the-pixel-unit-in-css-8b8788a1301f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/stop-using-the-pixel-unit-in-css.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：12 天
* 校对时间：3 天
* 翻译积分：6.5 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tong-H** [comment]
@lsvih 我可以认领翻译吗

**Comment by lsvih** [comment]
@Tong-H  您可以先完成一次校对熟悉一下流程哈~

**Comment by Tong-H** [comment]
> @Tong-H 您可以先完成一次校对熟悉一下流程哈~

好的

**Comment by PassionPenguin** [comment]
认领翻译

**Comment by lsvih** [comment]
@PassionPenguin 好的
