### ISSUE TITLE
在 TC39 提起一项提案

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8590]
- 原文链接：[Championing a proposal at TC39](https://github.com/tc39/how-we-work/blob/master/champion.md)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/ECMA-TC39/Championing-a-proposal-at-TC39.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/ECMA-TC39` 文件夹中，不是之前的 `article/2021` 了。**

---

- 翻译时间：10 天
- 校对时间：3 天
- 翻译积分：10 分
- 校对积分：4 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)
- [ECMAScript翻译指南（2021.5）](https://github.com/xitu/gold-miner/wiki/ECMAScript%E7%BF%BB%E8%AF%91%E6%8C%87%E5%8D%97%EF%BC%882021.5%EF%BC%89)

**Comment by PassionPenguin** [comment]
认领翻译

**Comment by lsvih** [comment]
@itcodes TC39 单个文档翻译完之后怎么处理？是直接发掘金还是弄个专题啥的组织起来
