### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by kimberlyohq** [xitu/gold-miner#8603]
- 公司/学校：新加坡国立大学
- 工作内容/专业：计算机科学
- 常浏览的国外网站：https://medium.com/， https://kentcdodds.com/blog/， https://react.statuscode.com/, GitHub, Reddit
- 英语水平：英文教育
- 翻译经验：无， 不过目前正在帮忙翻译一篇文章
- 主要翻译方向：前端
- 个人博客：无
- 个人介绍：想通过翻译提升中文水平，接触好的文章并从中学习相关的技术

**Comment by kimberlyohq** [comment]
@itcodes 你好， 打扰了！我昨天已经加了微信不过还没通过😅

**Comment by itcodes** [comment]
没有加到你。。求指导。

**Comment by kimberlyohq** [comment]
> 没有加到你。。求加微信。

好的，我加了
