### ISSUE TITLE
How to experiment with a proposal before Stage 4

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8609]
- 原文链接：[How to experiment with a proposal before Stage 4](https://github.com/tc39/how-we-work/blob/master/experiment.md)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/ECMA-TC39/How-to-experiment-with-a-proposal-before-Stage-4.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/ECMA-TC39` 文件夹中，不是之前的 `article/2021` 了。**

---

- 翻译时间：5 天
- 校对时间：2 天
- 翻译积分：3 分
- 校对积分：1 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)
- [ECMAScript翻译指南（2021.5）](https://github.com/xitu/gold-miner/wiki/ECMAScript%E7%BF%BB%E8%AF%91%E6%8C%87%E5%8D%97%EF%BC%882021.5%EF%BC%89)

**Comment by PassionPenguin** [comment]
认领翻译

**Comment by lsvih** [comment]
@PassionPenguin 哈罗，这篇别忘了哈=。=

**Comment by zaviertang** [comment]
这篇我来接手吧，PassionPenguin 可能忘记了 @lsvih

**Comment by lsvih** [comment]
@zaviertang 好的

**Comment by PassionPenguin** [comment]
啊我忘了。。。等下翻

**Comment by PassionPenguin** [comment]
sorry..

**Comment by lsvih** [comment]
@zaviertang 嘛，作者回来了= = 还是让他翻完吧，欢迎来校对

**Comment by zaviertang** [comment]
哈哈蹲一个校对

**Comment by PassionPenguin** [comment]
@zaviertang 来吧来吧～已经推送啦
