### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by supertong** [xitu/gold-miner#861]
你好，我叫supertong，计算机科学毕业，现在在澳洲工作，主要工作内容是后端开发，熟悉aws和nodejs，也对其他领域的新语言和框架感兴趣。能熟悉使用英文进行文档编写，经常访问 Hacker News社区。暂无翻译经验，希望能互相交流学习。

**Comment by antonia0912** [comment]
@supertong 欢迎来到掘金翻译计划  请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群
