### ISSUE TITLE
简述 TC39 提案的传送和执行流程

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8613]
- 原文链接：[How to experiment with a proposal before Stage 4](https://github.com/tc39/how-we-work/blob/master/implement.md)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/ECMA-TC39/Implementing-and-shipping-TC39-proposals.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/ECMA-TC39` 文件夹中，不是之前的 `article/2021` 了。**

---

- 翻译时间：10 天
- 校对时间：4 天
- 翻译积分：7 分
- 校对积分：2 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)
- [ECMAScript翻译指南（2021.5）](https://github.com/xitu/gold-miner/wiki/ECMAScript%E7%BF%BB%E8%AF%91%E6%8C%87%E5%8D%97%EF%BC%882021.5%EF%BC%89)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo  好的
