### ISSUE TITLE
阅读一份提案草案

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8615]
- 原文链接：[Reading a proposal draft](https://github.com/xitu/gold-miner/blob/master/article/ECMA-TC39/Reading-a-proposal-draft.md)
- Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/ECMA-TC39/Reading-a-proposal-draft.md)
- PR 地址：
- 文章分类：**前端**
- **注意：文件位置在 `article/ECMA-TC39` 文件夹中，不是之前的 `article/2021` 了。**

---

- 翻译时间：5 天
- 校对时间：2 天
- 翻译积分：3 分
- 校对积分：1 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)
- [ECMAScript翻译指南（2021.5）](https://github.com/xitu/gold-miner/wiki/ECMAScript%E7%BF%BB%E8%AF%91%E6%8C%87%E5%8D%97%EF%BC%882021.5%EF%BC%89)

**Comment by PassionPenguin** [comment]
翻译认领
