### ISSUE TITLE
推荐前端优秀英文文章

### ISSUE THREAD

**Issue by AnsonZnl** [xitu/gold-miner#8641]
- 原文链接：https://dev.to/ovi/20-javascript-one-liners-that-will-help-you-code-like-a-pro-4ddc
- 简要介绍：专业人士的 20 个 JavaScript 技巧

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by AnsonZnl** [comment]
这篇我打算自己翻译，谢谢大家！！

**Comment by lsvih** [comment]
这篇已经有译文啦 https://www.jianshu.com/p/a02d1adf578d
