### ISSUE TITLE
推荐后端优秀英文文章

### ISSUE THREAD

**Issue by Miigon** [xitu/gold-miner#8643]
- 原文链接：https://www.mongodb.com/blog/post/performance-best-practices-transactions-and-read--write-concerns
- 简要介绍：MongoDB 高性能最佳实践: 事务，读取关心程度与写入关心程度
MongoDB 官方博客中的系列文章《MongoDB 高性能最佳实践》其中一篇，介绍关于事务，读取关心程度与写入关心程度的高性能最佳实践。
---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐后端优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by Miigon** [comment]
这一篇自己领了😘

**Comment by lsvih** [comment]
#8657 已发布认领，感谢推荐
