### ISSUE TITLE
提高 Firefox 在 Linux 上的稳定性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8644]
* 原文链接：[Improving Firefox stability on Linux – Mozilla Hacks - the Web developer blog](https://hacks.mozilla.org/2021/05/improving-firefox-stability-on-linux/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/improving-firefox-stability-on-linux.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：3.5 + 1 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文使用官方账号发布，额外增加 1 分

**Comment by Tong-H** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Tong-H 好的~

**Comment by itcodes** [comment]
加下我微信哈。chnyifan
