### ISSUE TITLE
简述自动生成的社交媒体图片

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8645]
* 原文链接：[Auto-Generated Social Media Images](https://css-tricks.com/auto-generated-social-media-images/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/auto-generated-social-media-images.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo  好的
