### ISSUE TITLE
用 Sass 的 !default 创建样式表的特征标识

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8646]
* 原文链接：[Creating Stylesheet Feature Flags With Sass !default](https://css-tricks.com/creating-stylesheet-feature-flags-with-sass-default/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/creating-stylesheet-feature-flags-with-sass-default.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gesj-yean** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Gesj-yean 好的
