### ISSUE TITLE
Chrome 浏览器的自定义状态伪类

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8647]
* 原文链接：[Custom State Pseudo-Classes in Chrome](https://css-tricks.com/custom-state-pseudo-classes-in-chrome/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/custom-state-pseudo-classes-in-chrome.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by iceytea** [comment]
翻译认领

**Comment by iceytea** [comment]
翻译认领

**Comment by lsvih** [comment]
@iceytea  欢迎翻译，翻译过程和格式请您参阅 [如何参与翻译](https://github.com/xitu/gold-miner/wiki/如何参与翻译) 及 [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/译文排版规则指北) 哈 😄
