### ISSUE TITLE
CSS是编程语言吗？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8650]
* 原文链接：[Is CSS a Programming Language?](https://css-tricks.com/is-css-a-programming-language/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/is-css-a-programming-language.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cncuckoo** [comment]
翻译认领

**Comment by lsvih** [comment]
@cncuckoo 欢迎翻译，请您留意一下[排版](https://github.com/xitu/gold-miner/wiki/译文排版规则指北)格式哈~

**Comment by cncuckoo** [comment]
@lsvih 收到～
