### ISSUE TITLE
什么是 http/3，为什么它很重要？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8659]
* 原文链接：[What is HTTP/3, and Why Does it Matter?](https://javascript.plainenglish.io/what-is-http-3-and-why-does-it-matter-cb7d7b4b600f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/what-is-http-3-and-why-does-it-matter.md)
* PR 地址：
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by keepmovingljzy** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@keepmovingljzy 好的

**Comment by keepmovingljzy** [comment]
@lsvih 初步翻译完成
