### ISSUE TITLE
使用 CI/CD 优化前端构建的五种策略

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8661]
* 原文链接：[5 Strategies to Reduce Frontend Build Time with CI/CD](https://blog.bitsrc.io/5-strategies-to-reduce-frontend-build-time-with-ci-cd-3ce429304d1a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/5-strategies-to-reduce-frontend-build-time-with-ci-cd.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo  好的
