### ISSUE TITLE
推荐产品优秀英文文章

### ISSUE THREAD

**Issue by JalanJiang** [xitu/gold-miner#8667]
- 原文链接：[Tiny Wins - The big benefits of little changes](https://joelcalifa.com/blog/tiny-wins/)
- 简要介绍：作者通过亲身经历的案例，讲诉了产品上的微小改进给用户体验带来的巨大收益。

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/Kotlin/其他/资讯优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
这篇里面设计了大量推特，然后很多纯英文图片，不太好放哈= =
