### ISSUE TITLE
对角线分割的圆锥渐变式可变纵横比卡片

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8675]
* 原文链接：[Variable Aspect Ratio Card With Conic Gradients Meeting Along the Diagonal](https://css-tricks.com/variable-aspect-ratio-card-with-conic-gradients-meeting-along-the-diagonal/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/variable-aspect-ratio-card-with-conic-gradients-meeting-along-the-diagonal.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由 @PassionPenguin  认领翻译

**Comment by Usualminds** [comment]
@lsvih 申请校对

**Comment by lsvih** [comment]
@Usualminds 您记得到 PR 里去认领哈~
