### ISSUE TITLE
羊先森！！我申请成为掘金翻译计划的译者！！

### ISSUE THREAD

**Issue by Romeo0906** [xitu/gold-miner#869]
我是 Romeo0906， 先后就读于 NUDT 和 XTU ，现任 一猫汽车 PHP开发工程师，经常访问的国外网站有 Github、Ins、Openshift 等网站。具有良好的英语基础，通过大学英语四六级， NAETI 英语笔译四级证书考试，遗憾的是至今未有拿得出手的翻译经验，个人博客地址 http://romeo.wang ，博客最近在改版下线了，所以随手放了一个蛮久以前做的商城项目上去（当时学习Laravel框架，所以练手做的项目，慎点！辣眼睛！）。 @antonia0912

**Comment by antonia0912** [comment]
@Romeo0906 晓得啦~我拉你进译者群哈~
