### ISSUE TITLE
推荐前端优秀英文文章

### ISSUE THREAD

**Issue by darkyzhou** [xitu/gold-miner#8695]
- 原文链接：https://blog.theodo.com/2021/04/library-tree-shaking/
- 简要介绍：文章从如何编写一个可以被摇树优化的库出发，介绍了现代JS打包器的许多概念，以及如何让我们的库更好的被它们打包。

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/Kotlin/其他/资讯优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by darkyzhou** [comment]
自己认领翻译

**Comment by lsvih** [comment]
这篇文章篇幅非常长，您是否确定要翻译呢= =

**Comment by darkyzhou** [comment]
我ok的，虽然可能需要多点时间

或许可以考虑拆成两部分，太长了也不利于校对和发布

**Comment by Usualminds** [comment]
@darkyzhou 这篇文章很棒，提前申请下校对，也可以协助翻译

**Comment by lsvih** [comment]
@darkyzhou  @Usualminds  我今天会处理这篇

**Comment by darkyzhou** [comment]
@lsvih 请问处理进度如何了呢，我这边前几天就基本翻译完成了

**Comment by lsvih** [comment]
#8815 已发布认领，感谢推荐
