### ISSUE TITLE
JetPack Compose for Desktop 初体验

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8705]
* 原文链接：[An Introduction to JetPack Compose for Desktop](https://betterprogramming.pub/an-introduction-to-jetpack-compose-for-desktop-5c3bf8629dc5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/an-introduction-to-jetpack-compose-for-desktop.md)
* PR 地址：
* 文章分类：**Kotlin**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by lsvih** [comment]
@YueYongDev 好嘞

**Comment by YueYongDev** [comment]
@lsvih  翻译完成

**Comment by YueYongDev** [comment]
已经发布到掘金了，麻烦看一下👉https://juejin.cn/post/6988811890780536839/
——————————————
另外，我的这篇文章提示审核不通过，发沸点反馈了也没有消息，运营如果看见了麻烦告知一下，麻烦啦
👉 https://juejin.cn/post/6988532992239435784

**Comment by lsvih** [comment]
收到~

**Comment by lsvih** [comment]
@YueYongDev 您的那篇文章放出来了 - -
