### ISSUE TITLE
简述 JavaScript 高阶函数的开发使用

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8709]
* 原文链接：[All You Need to Know About Higher-Order Functions in JavaScript](https://javascript.plainenglish.io/all-you-need-to-know-about-higher-order-functions-in-javascript-19d30c8cc8e5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/all-you-need-to-know-about-higher-order-functions-in-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5.5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblo** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblo 好嘞！
