### ISSUE TITLE
编译成 JavaScript 接口框架的案例

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8711]
* 原文链接：[A Case for Compile to JavaScript Interface Frameworks](https://javascript.plainenglish.io/a-case-for-compile-to-javascript-interface-frameworks-a684b361884f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/a-case-for-compile-to-javascript-interface-frameworks.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5.5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tong-H** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Tong-H 好的~
