### ISSUE TITLE
解密 Java Lambda 表达式

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8713]
* 原文链接：[Demystifying Java Lambda Expressions](https://betterprogramming.pub/demystifying-java-lambda-expressions-d122b4b23b70)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/demystifying-java-lambda-expressions.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5.5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好嘞

**Comment by samyu2000** [comment]
@lsvih 翻译完成
