### ISSUE TITLE
使用 Husky 和 Hooks 保证 JavaScript 代码质量

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8717]
* 原文链接：[Ensure JavaScript Code Quality with Husky and Hooks](https://blog.bitsrc.io/ensure-javascript-code-quality-with-husky-and-hooks-6e338222662)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/ensure-javascript-code-quality-with-husky-and-hooks.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Usualminds** [comment]
@lsvih 翻译认领

**Comment by zenblo** [comment]
@Usualminds @lsvih 好久没动静，我接过来翻译吧

**Comment by Usualminds** [comment]
> @Usualminds @lsvih 好久没动静，我接过来翻译吧

@zenblo 正在翻译，今天就翻译完了

**Comment by lsvih** [comment]
@Usualminds  哈哈加油
