### ISSUE TITLE
全方位提升网站打开速度：前端、后端、新的技术

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#872]
* 原文链接：[Building a Shop with Sub-Second Page Loads: Lessons Learned](https://medium.baqend.com/building-a-shop-with-sub-second-page-loads-lessons-learned-4bb1be3ed07#.svcz7qtdn)
* 掘金链接：[全方位提升网站打开速度：前端、后端、新的技术](http://gold.xitu.io/entry/580dcdf1128fe1005fdd5280)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/building-a-shop-with-sub-second-page-loads-lessons-learned.md)
* PR 地址：#906 #927
* 文章分类：**前端/后端**

----
* 翻译时间：`4 ~ 5` 天
* 校对时间：`2` 天
* 翻译积分：`10` 分
* 校对积分：`3` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luoyaqifei** [comment]
认领

**Comment by sqrthree** [comment]
@luoyaqifei 好的

**Comment by luoyaqifei** [comment]
@sqrthree http://gold.xitu.io/entry/582492025bbb5000590ef04d/detail
