### ISSUE TITLE
如何举办一个 TC39 会议

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8729]
* 原文链接：原文地址：[How to host a TC39 meeting](https://github.com/tc39/how-we-work/blob/master/host.md)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/ECMA-TC39/How-to-host-a-TC39-meeting.md)
* PR 地址：
* 文章分类：**前端**
- **注意：文件位置在 `article/ECMA-TC39` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PingHGao** [comment]
翻译认领 @itcodes
