### ISSUE TITLE
如何召开在线会议

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8732]
* 原文链接：[How to run an online meeting](https://github.com/tc39/how-we-work/blob/master/call.md)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/ECMA-TC39/How-to-run-an-online-meeting.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：6 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PingHGao** [comment]
翻译认领 @itcodes
