### ISSUE TITLE
推荐Android优秀英文文章

### ISSUE THREAD

**Issue by Mao0509** [xitu/gold-miner#8755]
- 原文链接：https://proandroiddev.com/dont-use-livedata-in-repositories-f3bebe502ed3
- 简要介绍：不要在Repositories中使用LiveData

* [x] 按文章分类填写 issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/Kotlin/其他/资讯优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

**Comment by lsvih** [comment]
这篇已经有翻译了哈，不过也感谢推荐=。=   https://blog.csdn.net/weixin_26739079/article/details/108259731
