### ISSUE TITLE
在学写了六个功能一样的函数之后，我学到了什么

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#876]
* 原文链接：[What I learned from writing six functions that all did the same thing](https://medium.freecodecamp.com/what-i-learned-from-writing-six-functions-that-all-did-the-same-thing-b38fd48f0d55#.tt79h3s25)
* 掘金链接：[在学写了六个功能一样的函数之后，我学到了什么](http://gold.xitu.io/entry/5817084e2e958a0054a370c0)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/what-i-learned-from-writing-six-functions-that-all-did-the-same-thing.md)
* PR 地址：#894
* 文章分类：**前端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
Can I take a try ? @sqrthree

**Comment by sqrthree** [comment]
@Romeo0906 Of course, you can.
