### ISSUE TITLE
构建 Android APP 一定要绕过的 30 个坑

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#879]
* 原文链接：[Building Android Apps — 30 things that experience made me learn the hard way](https://medium.com/@cesarmcferreira/building-android-apps-30-things-that-experience-made-me-learn-the-hard-way-313680430bf9#.6cszf7t9m)
* 掘金链接：[构建 Android APP 一定要绕过的 30 个坑](http://gold.xitu.io/entry/58170aaaa0bb9f00587c4032)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/building-android-apps-30-things-that-experience-made-me-learn-the-hard-way.md)
* PR 地址：#896
* 文章分类：**Android**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
@sqrthree 送分题。。

**Comment by sqrthree** [comment]
@yifili09 好的

**Comment by yifili09** [comment]
@sqrthree #896 可以召唤我们的校对啦。

**Comment by yifili09** [comment]
@sqrthree  @antonia0912 我推荐原文链接中提到的每一篇文章 😸 😸 !!

**Comment by XHShirley** [comment]
可以认领了吗？求认领。 @sqrthree

**Comment by sqrthree** [comment]
@XHShirley 好的，在 #896 校对哈
