### ISSUE TITLE
Swift 中的内存布局

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8792]
* 原文链接：[Memory layout in Swift](https://theswiftdev.com/memory-layout-in-swift/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/memory-layout-in-swift.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by LoneyIsError** [comment]
翻译认领

**Comment by lsvih** [comment]
@LoneyIsError 好嘞
