### ISSUE TITLE
DevTools 的新功能（Chrome 92）

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8795]
* 原文链接：[What's New In DevTools (Chrome 92)](https://developer.chrome.com/blog/new-in-devtools-92/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/new-in-devtools-92.md)
* PR 地址：
* 文章分类：**前端**，**资讯**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Usualminds** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Usualminds  好嘞！
