### ISSUE TITLE
React 18 中新的 Suspense SSR 架构

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8797]
* 原文链接：[New Suspense SSR Architecture in React 18](https://github.com/reactwg/react-18/discussions/37)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/new-suspense-ssr-architecture-in-react-18.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：16 天
* 校对时间：4 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by NieZhuZhu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@NieZhuZhu  好嘞，加油，这篇还挺长的！
