### ISSUE TITLE
你真的应该在黑暗模式下进行编码吗？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8799]
* 原文链接：[Should You Really be Coding in Dark Mode?](https://dev.to/codesphere/should-you-really-be-coding-in-dark-mode-4ng8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/should-you-really-be-coding-in-dark-mode.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kamly** [comment]
@lsvih 认领翻译

**Comment by lsvih** [comment]
@kamly 好嘞！
