### ISSUE TITLE
《每个 Android 开发者都应该读的 Android Studio Tips》还没有 markdown 的待翻译文件

### ISSUE THREAD

**Issue by Glowin** [xitu/gold-miner#88]
[每个 Android 开发者都应该读的 Android Studio Tips](https://github.com/pavlospt/Android-Studio-Tips-by-Philippe-Breault/wiki) 这篇文章暂时还没有 markdown 文件，需要整理一份出来方便译者翻译。

PS：这篇文章已经被@laobie 认领 #24

**Comment by kassadin** [comment]
63页 wiki…撸成一篇文章真的好么…@Glowin一个人翻译真的好么…@laobie

**Comment by laobie** [comment]
我之前是准备写成一篇的，拆分也可以的，不过确实比较多😂

**Comment by Glowin** [comment]
@kassadin 这篇文章给 @laobie 是因为他认领的时候说之前翻译过一部分，所以就安排给 @laobie 翻译了。

@laobie 如果你觉得工作量大的话，我可以邀请其他人来一同翻译这个。

**Comment by brucezz** [comment]
我正在和 @laobie 一起翻译这个tips呢

**Comment by Glowin** [comment]
@brucezz 好的呢，但是我们这篇文章只有一个奖品哎

**Comment by laobie** [comment]
@Glowin 就是他让我继续的~他要手办，我正好上次在翻译这个嘛
@brucezz 奖品归你
