### ISSUE TITLE
让 JavaScript 在 WebAssembly 上疾速运行

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8801]
* 原文链接：[Making JavaScript run fast on WebAssembly](https://bytecodealliance.org/articles/making-javascript-run-fast-on-webassembly)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/making-javascript-run-fast-on-webassembly.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：20 天
* 校对时间：5 天
* 翻译积分：11 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by lsvih** [comment]
@Baddyo  好嘞~
