### ISSUE TITLE
面向具有 React 开发经验的开发者介绍 Svelte

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8806]
* 原文链接：[Svelte for the Experienced React Dev](https://css-tricks.com/svelte-for-the-experienced-react-dev/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/svelte-for-the-experienced-react-dev.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：15 天
* 校对时间：3 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tong-H** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Tong-H 好嘞
