### ISSUE TITLE
2021 年 Node.js 的发展趋势

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8808]
* 原文链接：[Top Node.js Development Trends in 2021](https://javascript.plainenglish.io/top-node-js-development-trends-in-2021-807f27fdf1b8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/top-node-js-development-trends-in-2021.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by youngjuning** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@youngjuning 好嘞

**Comment by youngjuning** [comment]
@lsvih 人生无常，放弃翻译

**Comment by Tong-H** [comment]
可以认领吗

**Comment by lsvih** [comment]
@Tong-H 欢迎认领~
