### ISSUE TITLE
成为 TC39 代表

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8809]
* 原文链接：[Becoming-a-TC39-delegate](https://github.com/tc39/how-we-work/blob/master/call.md)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/ECMA-TC39/Becoming-a-TC39-delegate.md)
* PR 地址：
* 文章分类：**ECMA-TC39**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by finalwhy** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@finalwhy  好的

**Comment by Lvyaqian123** [comment]
文章已发布https://juejin.cn/post/7088145329685692452/
