### ISSUE TITLE
Yarn 更快更可靠的 CI 创建工具

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#881]
* 原文链接：[Faster, More Reliable CI Builds with Yarn](https://medium.com/javascript-scene/faster-more-reliable-ci-builds-with-yarn-7dbc0ef31580#.8jbyo2k64)
* 掘金链接：[Faster, More Reliable CI Builds with Yarn](http://gold.xitu.io/entry/58183af6128fe100559b492b)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/faster-more-reliable-ci-builds-with-yarn.md)
* PR 地址：#895
* 文章分类：**前端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
May I have the honor?

**Comment by sqrthree** [comment]
@Romeo0906 Sure.
