### ISSUE TITLE
外行人说量子计算机

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8811]
* 原文链接：[A Layman’s Intro to Quantum Computers](https://betterprogramming.pub/a-laymans-intro-to-quantum-computers-67b7a7126695)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/a-laymans-intro-to-quantum-computers.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：20 天
* 校对时间：5 天
* 翻译积分：11 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PingHGao** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@PingHGao  好的~
