### ISSUE TITLE
V8 有个非优化的编译阶段去提高性能

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8817]
* 原文链接：[V8 Gets a Non-Optimizing Compiler Stage to Improve Performance](https://www.infoq.com/news/2021/06/v8-sparkplug-compiler/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/v8-sparkplug-compiler.md)
* PR 地址：
* 文章分类：**资讯**，**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CarlosChenN** [comment]
@lsvih 翻译认领

**Comment by Lvyaqian123** [comment]
已发布https://juejin.cn/post/7088956826263224350/

**Comment by lsvih** [comment]
收到~
