### ISSUE TITLE
给 iOS APP 开发者的 39 个完全开放的 Swift UI 库

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#882]
* 原文链接：[39 Open Source Swift UI Libraries For iOS App Development](https://medium.mybridge.co/39-open-source-swift-ui-libraries-for-ios-app-development-da1f8dc61a0f#.tg0lhb6r8)
* 掘金链接：[给 iOS APP 开发者的 39 个完全开放的 Swift UI 库](http://gold.xitu.io/entry/58183e982e958a0054b0f56c)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/39-open-source-swift-ui-libraries-for-ios-app-development.md)
* PR 地址：#891
* 文章分类：**iOS**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jiaowoyongqi** [comment]
好干货！这篇字数不多，可以再认领一个嘛？

**Comment by sqrthree** [comment]
好的👌🏻，注意时间和翻译质量哈
