### ISSUE TITLE
A Deep Dive Into Actors in Swift 5.5

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8821]
* 原文链接：[A Deep Dive Into Actors in Swift 5.5](https://betterprogramming.pub/a-deep-dive-into-actors-in-swift-5-5-8cc2fa004ded)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/a-deep-dive-into-actors-in-swift-5-5.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：13 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Weirdochr** [comment]
翻译认领

**Comment by lsvih** [comment]
@Weirdochr  好嘞！
