### ISSUE TITLE
TC39 and IP

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8824]
* 原文链接：[TC39 and IP](https://github.com/tc39/how-we-work/blob/master/ip.md)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/ECMA-TC39/TC39-and-IP.md)
* PR 地址：
* 文章分类：**ECMA-TC39**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by finalwhy** [comment]
翻译认领

**Comment by lsvih** [comment]
@finalwhy  好嘞

**Comment by Lvyaqian123** [comment]
已发布 https://juejin.cn/post/7087877275076526088/

**Comment by lsvih** [comment]
收到， @Lvyaqian123 这个 TC 39 系列确定是这样发的嘛 = =，不用开个专题或者系列之类的吗

**Comment by Lvyaqian123** [comment]
可以开个TCP专栏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lsvih ***@***.***&gt;
发送时间: 2022年4月18日 20:02
收件人: xitu/gold-miner ***@***.***&gt;
抄送: Lvyaqian123 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [xitu/gold-miner] TC39 与知识产权（IP） (#8824)
