### ISSUE TITLE
用 Yarn 你还能做这 5 件事

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#883]
* 原文链接：[5 things you can do with Yarn](https://auth0.com/blog/five-things-you-can-do-with-yarn/)
* 掘金链接：[用 Yarn 你还能做这 5 件事](http://gold.xitu.io/entry/5818435ea0bb9f0058838f18)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/five-things-you-can-do-with-yarn.md)
* PR 地址： #904
* 文章分类：**前端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jiakeqi** [comment]
get

**Comment by sqrthree** [comment]
好的👌🏻
