### ISSUE TITLE
成为一个编译器之「使用 JavaScript 来制作编译器」

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#884]
* 原文链接：[How to be* a compiler — make a compiler with JavaScript](https://medium.com/@kosamari/how-to-be-a-compiler-make-a-compiler-with-javascript-4a8a13d473b4#.r832qh7i8)
* 掘金链接：[How to be* a compiler — make a compiler with JavaScript](http://gold.xitu.io/entry/58184953bf22ec0068a0d42f)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-to-be-a-compiler-make-a-compiler-with-javascript.md)
* PR 地址：#905
* 文章分类：**前端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luoyaqifei** [comment]
我抢！周末有空！哈哈！

**Comment by sqrthree** [comment]
好的👌🏻

**Comment by antonia0912** [comment]
@luoyaqifei 👌
