### ISSUE TITLE
我喜欢的微服务间通信模式

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8850]
* 原文链接：[My Favorite Interservice Communication Patterns for Microservices](https://blog.bitsrc.io/my-favorite-interservice-communication-patterns-for-microservices-d746a6e1d7de)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/my-favorite-interservice-communication-patterns-for-microservices.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：18 天
* 校对时间：4 天
* 翻译积分：10 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by finalwhy** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@finalwhy  抱歉哈，@samyu2000  这位老哥已经认领了这篇文章的翻译了，我忘了改状态了。。

今天晚上会上新一批新的文章~

**Comment by samyu2000** [comment]
@lsvih 翻译完成

**Comment by lsvih** [comment]
@finalwhy  欢迎来校对哈~
