### ISSUE TITLE
用于 JavaScript 应用的前 5 大嵌入式数据库

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8852]
* 原文链接：[Top 5 Embedded Databases for JavaScript Applications](https://blog.bitsrc.io/top-5-embedded-databases-for-javascript-applications-1c68496aebac)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/top-5-embedded-databases-for-javascript-applications.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：15 天
* 校对时间：4 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tong-H** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@Tong-H 好嘞
