### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by phxnirvana** [xitu/gold-miner#886]
Hi, 我的id是PhxNirvana，任职android开发，常浏览的网站有github，stackoverflow，quora，英语水平6级过了，上学时候做过游戏翻译算有经验么（貌似可以搜到我的id），博客只有一个荒芜的csdn。。

**Comment by antonia0912** [comment]
@phxnirvana 欢迎来到掘金翻译计划  请加我微信 antonia0912 备注 GitHub ID  我来拉你进译者群~
