### ISSUE TITLE
FFmpeg + WebAssembly

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8898]
* 原文链接：[FFmpeg + WebAssembly](https://dev.to/alfg/ffmpeg-webassembly-2cbl)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/ffmpeg-webassembly.md)
* PR 地址：
* 文章分类：**前端**，**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：15 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by finalwhy** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@finalwhy 好嘞
