### ISSUE TITLE
使用接口编写更优雅的 PHP 代码

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8899]
* 原文链接：[Using Interfaces to Write Better PHP Code](https://dev.to/ashallendesign/using-interfaces-to-write-better-php-code-391f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/using-interfaces-to-write-better-php-code.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：14 天
* 校对时间：3 天
* 翻译积分：6.5 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kamly** [comment]
@lsvih 认领翻译

**Comment by lsvih** [comment]
@kamly 好嘞！

**Comment by kamly** [comment]
近日处理

**Comment by lsvih** [comment]
@kamly  辛苦啦
