### ISSUE TITLE
Understanding Cross-Site Request Forgery (CSRF or XSRF)

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8914]
* 原文链接：[Understanding Cross-Site Request Forgery (CSRF or XSRF)](https://dev.to/danilo/understanding-cross-site-request-forgery-csrf-or-xsrf-3d95)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/understanding-cross-site-request-forgery-csrf-or-xsrf.md)
* PR 地址：
* 文章分类：**后端**，**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：16 天
* 校对时间：5 天
* 翻译积分：9 分
* 校对积分：4.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by finalwhy** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@finalwhy  好的~
