### ISSUE TITLE
HTTP 严格传输安全协议常见问题解答

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8916]
* 原文链接：[HTTP Strict Transport Security FAQs](https://levelup.gitconnected.com/http-strict-transport-security-faqs-844e00ac385c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/http-strict-transport-security-faqs.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CarlosChenN** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@CarlosChenN 好嘞
