### ISSUE TITLE
JavaScript 实现图数据结构

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8918]
* 原文链接：[Graph Data Structure Implementation in JavaScript](https://javascript.plainenglish.io/graph-data-structure-implementation-in-javascript-668f291a8a16)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/graph-data-structure-implementation-in-javascript.md)
* PR 地址：
* 文章分类：**前端**，**算法**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：17 天
* 校对时间：4 天
* 翻译积分：8.5 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CarlosChenN** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@CarlosChenN  您这一次弄两篇不会太辛苦嘛= =

**Comment by CarlosChenN** [comment]
@lsvih 不会哈，会尽快完成的

**Comment by lsvih** [comment]
@CarlosChenN 哈哈好的，不着急，悠着点哈~

**Comment by CarlosChenN** [comment]
@lsvih 
For this graph implementation ill be using the adjacency list for ****simplicity and the graph I'll show you is general-purpose and unweighted.
这句是不是有问题，是不是漏了一些？

**Comment by lsvih** [comment]
这句话写的确实奇怪，意思大概能理解，加两符号应该是

For this graph implementation, I'll be using the adjacency list for simplicity, and the graph which I'll show you is general-purpose and unweighted.

**Comment by CarlosChenN** [comment]
@lsvih 
推荐一篇文章哈
https://itnext.io/v8-deep-dives-understanding-map-internals-45eb94a183df
