### ISSUE TITLE
Flutter 比 React Native 更优秀的五个理由

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8926]
* 原文链接：[5 Reasons Why Flutter Is Better Than React Native](https://betterprogramming.pub/5-reasons-why-flutter-is-better-than-react-native-cf2e9b077f66)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/5-reasons-why-flutter-is-better-than-react-native.md)
* PR 地址：
* 文章分类：**Flutter**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：6.5 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblofe** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblofe  好嘞
