### ISSUE TITLE
CSS 是魔法, 是时候试试 3D 了

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8938]
* 原文链接：[CSS is magic, its time you try 3D](https://levelup.gitconnected.com/css-is-magic-its-time-you-try-3d-91a2dd49c781)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/css-is-magic-its-time-you-try-3d.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tong-H** [comment]
翻译认领

**Comment by lsvih** [comment]
@Tong-H  好嘞
