### ISSUE TITLE
通过 Redis 构建一个响应式架构

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8940]
* 原文链接：[Building a Reactive Architecture Around Redis](https://blog.bitsrc.io/building-a-reactive-architecture-around-redis-bc53662b81c8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/building-a-reactive-architecture-around-redis.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：14 天
* 校对时间：3 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by lsvih** [comment]
@YueYongDev  好嘞

**Comment by lsvih** [comment]
已发布，https://juejin.cn/post/6996660780389122062
