### ISSUE TITLE
推荐iOS

### ISSUE THREAD

**Issue by LoneyIsError** [xitu/gold-miner#8942]
- 原文链接：推荐文章前 Google 一下，尽量保证本文未被翻译
- 简要介绍：介绍一下好不好啦，毕竟小编也看不太懂哎_(:з」∠)_
- 翻译计划处理能力有限，请勿一次性提交超过 3 篇文章的推荐哦

---
[Reverse engineering the .car file format (compiled Asset Catalogs)](https://blog.timac.org/2018/1018-reverse-engineering-the-car-file-format/) 关于Asset 编译成功后的 .car 文件分析 

### 请完成并勾选一下三项：

* [√ ] 按文章分类填写 Issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/Kotlin/其他/资讯优秀英文文章
* [√ ] 本文很值得翻译，我推荐
* [√ ] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
这篇文章好

**Comment by lsvih** [comment]
得等等哈。。这篇文章里面好多代码有问题

**Comment by LoneyIsError** [comment]
内容价值高

**Comment by lsvih** [comment]
我整理完了，@LoneyIsError 您要认领这一篇吗

**Comment by LoneyIsError** [comment]
是的

**Comment by lsvih** [comment]
#8944 已发布认领，辛苦啦
