### ISSUE TITLE
逆向 `.car` 文件（已编译的 Asset Catalogs）

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8944]
* 原文链接：[Reverse engineering the .car file format (compiled Asset Catalogs)](https://blog.timac.org/2018/1018-reverse-engineering-the-car-file-format/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/reverse-engineering-the-car-file-format.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：16 天
* 校对时间：5 天
* 翻译积分：10 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由@LoneyIsError 认领

**Comment by LoneyIsError** [comment]
@lsvih https://juejin.cn/post/7002491722550919198/发布了

**Comment by lsvih** [comment]
收到了~
