### ISSUE TITLE
使用 CDN 构建直读式缓存

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8946]
* 原文链接：[Building a read-through cache using CDN](https://levelup.gitconnected.com/building-a-read-through-cache-using-cdn-59988a3d75ce)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/building-a-read-through-cache-using-cdn.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：15 天
* 校对时间：3 天
* 翻译积分：7.5 分
* 校对积分：3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by PassionPenguin** [comment]
认领翻译
