### ISSUE TITLE
2021 年，jQuery 过得还好吗？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8949]
* 原文链接：[What is the State of jQuery in 2021?](https://javascript.plainenglish.io/jquery-7be2b63d720e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/so-whats-the-state-of-jquery-in-2021.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by lsvih** [comment]
@Baddyo 好嘞
