### ISSUE TITLE
V8 v9.2 发布

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8953]
* 原文链接：[V8 release v9.2](https://v8.dev/blog/v8-release-92)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/v8-release-92.md)
* PR 地址：
* 文章分类：**资讯**，**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：2 天
* 校对时间：1 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by finalwhy** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@finalwhy  好的
