### ISSUE TITLE
如何使用 ES6 新增 Symbols 代替 null

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8966]
* 原文链接：[Replace null with ES6 Symbols](https://javascript.plainenglish.io/replace-null-with-es6-symbols-c0e77d74542e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/replace-null-with-es6-symbols.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：1 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblofe** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblofe 好的~

**Comment by jaredliw** [comment]
@lsvih 漏了这篇
