### ISSUE TITLE
我用 Python 创建了一个自己的编程语言

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8968]
* 原文链接：[I Used Python to Create My Own Programming Language](https://python.plainenglish.io/introduction-to-creating-interpreter-using-python-c2a9a6820aa0)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/introduction-to-creating-interpreter-using-python.md)
* PR 地址：
* 文章分类：**后端**，**算法**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@jaredliw 好的！

**Comment by jaredliw** [comment]
#8999 翻译完成！

**Comment by jaredliw** [comment]
> 真快

头也秃得挺快的😂😂
