### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by SumiMakito** [xitu/gold-miner#897]
你好，我是SumiMakito，目前就读英语专业，方向翻译学。因专业需要，平时也经常阅读及互译英语文章。我较熟悉Android、产品及后端，有兴趣探索新事物和技术，曾编写过一些软件，我的部分开源项目含有中英双语文档。喜欢浏览Stackoverflow、Quora社区，也比较关注一些开源项目的Mailing list。目前暂无翻译完整作品的经验，希望能够在互相学习提高自己，谢谢。

**Comment by antonia0912** [comment]
@SumiMakito hi  欢迎来到掘金翻译计划  请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群~
