### ISSUE TITLE
Web 的未来

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8970]
* 原文链接：[The Future Of The Web](https://www.hazem.cool/blog/the-future-of-the-web)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/the-future-of-the-web.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：14 天
* 校对时间：3 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gesj-yean** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@Gesj-yean  好的~

**Comment by proYang** [comment]
鸽了吗 @Gesj-yean 😭

**Comment by Gesj-yean** [comment]
@proYang 翻译完了，今日提交哈
