### ISSUE TITLE
使用 RabbitMQ 和 SpringBoot 实现实时消息

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#8976]
* 原文地址：[RabbitMQ and SpringBoot for Real-Time Messaging](https://medium.com/codex/rabbitmq-springboot-for-real-time-messaging-e450bde4e8cc)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/RabbitMQ-and-SpringBoot-for-Real-Time-Messaging.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好嘞~

**Comment by samyu2000** [comment]
@lsvih 翻译完成

**Comment by jaredliw** [comment]
@lsvih 校对认领

**Comment by lsvih** [comment]
@jaredliw  您得在 PR 里认领校对哈，在 issue 里认领有时候会漏掉= =

**Comment by jaredliw** [comment]
> @jaredliw 您得在 PR 里认领校对哈，在 issue 里认领有时候会漏掉= =

好的勒~
