### ISSUE TITLE
实践 Redux，第 0 部分：简介

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#898]
* 原文链接：[Practical Redux, Part 0: Introduction](http://blog.isquaredsoftware.com/2016/10/practical-redux-part-0-introduction/)
* 掘金链接：[实践 Redux，第 0 部分：简介](http://gold.xitu.io/entry/581c020cbf22ec0068bb9b63)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/practical-redux-part-0-introduction.md)
* PR 地址：#901
* 文章分类：**前端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luoyaqifei** [comment]
认领

**Comment by sqrthree** [comment]
@luoyaqifei 😯 注意保证质量啊

**Comment by luoyaqifei** [comment]
http://gold.xitu.io/entry/5820552eda2f60005d09c33c/detail 掘金地址@sqrthree

**Comment by sqrthree** [comment]
@luoyaqifei copythat.
