### ISSUE TITLE
Chrome 93: Multi-Screen Window Placement, PWAs as URL Handlers, and More

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8985]
* 原文链接：[Chrome 93: Multi-Screen Window Placement, PWAs as URL Handlers, and More](https://blog.chromium.org/2021/07/chrome-93-multi-screen-window-placement.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/chrome-93-multi-screen-window-placement.md)
* PR 地址：
* 文章分类：**前端**，**资讯**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Usualminds** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Usualminds 好嘞

**Comment by huilingaa** [comment]
认领翻译
