### ISSUE TITLE
实践 Redux，第 1 部分：Redux-ORM 入门

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#899]
* 原文链接：[Practical Redux, Part 1: Redux-ORM Basics](http://blog.isquaredsoftware.com/2016/10/practical-redux-part-1-redux-orm-basics/)
* 掘金链接：[实践 Redux，第 1 部分：Redux-ORM 入门](http://gold.xitu.io/entry/581c04b32f301e005c076f50)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/practical-redux-part-1-redux-orm-basics.md)
* PR 地址：#902
* 文章分类：**前端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luoyaqifei** [comment]
认领

**Comment by sqrthree** [comment]
@luoyaqifei 你任务量可不小了😯

**Comment by luoyaqifei** [comment]
@sqrthree 表担心，哈哈

**Comment by luoyaqifei** [comment]
http://gold.xitu.io/entry/58249792a0bb9f0058dd30ab/detail @sqrthree
