### ISSUE TITLE
在 React 中使用 BLoC 模式

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8990]
* 原文链接：[Using BLoC Pattern with React](https://blog.bitsrc.io/using-bloc-pattern-with-react-cb6fdcfa623b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/using-bloc-pattern-with-react.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by flashhu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zflashhu 好嘞
