### ISSUE TITLE
I Can’t Believe It’s Not Better — Active Learning Flavor

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#8992]
* 原文链接：[I Can’t Believe It’s Not Better — Active Learning Flavor](https://medium.com/data-from-the-trenches/i-cant-believe-it-s-not-better-active-learning-flavor-ded7e367a6ff)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/i-cant-believe-it-s-not-better-active-learning-flavor.md)
* PR 地址：
* 文章分类：**AI**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：17 天
* 校对时间：3 天
* 翻译积分：9 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
建议有主动学习（active learning）方向背景的译者翻译

**Comment by shixi-li** [comment]
翻译认领

**Comment by shixi-li** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@shixi-li  辛苦了
