### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ychow** [xitu/gold-miner#90]
文章都被领取完了。。

**Comment by Glowin** [comment]
欢迎来申请加入，能不能麻烦你介绍一下自己呢，或者以往的翻译经历也行。

**Comment by ychow** [comment]
目前是一名前端。
翻译过的文章：
 [Ionic中文指南](https://github.com/ychow/ionic-guide)   
[Ionic 1.0 (RC) 来了！！！【译】](https://github.com/ychow/Blog/issues/8)   
[全面解析ECMAScript 6模块系统](http://www.csdn.net/article/2015-04-30/2824595-Modules-in-ES6)

**Comment by Glowin** [comment]
欢迎加入，可以加一下我微信 Glowjiang 进群
