### ISSUE TITLE
实践 Redux，第 2 部分：Redux-ORM 的概念和技术

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#900]
* 原文链接：[Practical Redux, Part 2: Redux-ORM Concepts and Techniques](http://blog.isquaredsoftware.com/2016/10/practical-redux-part-2-redux-orm-concepts-and-techniques/)
* 掘金链接：[实践 Redux，第 2 部分：Redux-ORM 的概念和技术](http://gold.xitu.io/entry/581c0549bf22ec0068bbbad0)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/practical-redux-part-2-redux-orm-concepts-and-techniques.md)
* PR 地址：#903 -> #926
* 文章分类：**前端**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luoyaqifei** [comment]
认领

**Comment by sqrthree** [comment]
@luoyaqifei 好的~注意时间限制哈。

**Comment by markzhai** [comment]
认领校对

**Comment by sqrthree** [comment]
@markzhai 好的~ 校对地址在 #926 哈
