### ISSUE TITLE
推荐后端/其他优秀英文文章

### ISSUE THREAD

**Issue by jaredliw** [xitu/gold-miner#9005]
- 原文链接：
> https://medium.com/@bathinivijaysimhareddy/tale-of-account-takeovers-part-1-b24e1f3c3187
> https://medium.com/@bathinivijaysimhareddy/tale-of-account-takeovers-part-2-9abf62de4ca3
- 简要介绍：一篇在我收藏夹里的文章，看到这里只有一篇类似的文章（CSRF 那篇）于是就推荐了，希望能够多普及普及类似的内容。主题：网络安全，作者是个漏洞赏金猎人，文章分上下两篇，阅读时长 9 分钟，详细说明了 5 个开发中错误的实现而导致的“盗号”情况，文章相对来说比较入门，容易明白。
- 翻译计划处理能力有限，请勿一次性提交超过 3 篇文章的推荐哦

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 Issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/Kotlin/其他/资讯优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
感谢推荐~
