### ISSUE TITLE
11 个让你惊叹的 罕见 JavaScript 单行代码

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9012]
* 原文链接：[11 Rare JavaScript One-Liners That Will Amaze You](https://betterprogramming.pub/11-rare-javascript-one-liners-that-will-amaze-you-331659832301)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/11-rare-javascript-one-liners-that-will-amaze-you.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@jaredliw 好的

**Comment by jaredliw** [comment]
@lsvih 已发布：https://juejin.cn/post/6998734064773660702
