### ISSUE TITLE
简述 JavaScript 的事件捕获和事件冒泡

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9014]
* 原文链接：[Event Bubbling and Capturing in JavaScript](https://blog.bitsrc.io/event-bubbling-and-capturing-in-javascript-6bc908321b22)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/event-bubbling-and-capturing-in-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：3 天
* 翻译积分：5.5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblofe** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblofe 好的

**Comment by zhaoqi1992** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zhaoqi1992 您好，感谢您对翻译计划的关注，不过这篇文章已经有人在翻译啦-。-  今天应该会上新一批文章，届时欢迎再来认领翻译哈~
