### ISSUE TITLE
常见的社会工程攻击策略

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9016]
* 原文链接：[Common Social Engineering Attack Strategies](https://blog.bitsrc.io/common-social-engineering-attack-strategies-23357db3d2d5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/common-social-engineering-attack-strategies.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：18 天
* 校对时间：5 天
* 翻译积分：10 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@jaredliw  好嘞
