### ISSUE TITLE
在 Python 中用最快的速度发送 HTTP 请求

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9018]
* 原文链接：[Send HTTP Requests As Fast As Possible in Python](https://python.plainenglish.io/send-http-requests-as-fast-as-possible-in-python-304134d46604)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/send-http-requests-as-fast-as-possible-in-python.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ItzMiracleOwO** [comment]
认领翻译

**Comment by lsvih** [comment]
@ItzMiracleOwO 欢迎翻译~

**Comment by ItzMiracleOwO** [comment]
完成啦~
