### ISSUE TITLE
使用人工智能/机器学习构建文章推荐引擎

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9030]
* 原文链接：[Build an Article Recommendation Engine With AI/ML](https://betterprogramming.pub/build-an-article-recommendation-engine-with-ai-ml-c6e931e34d3b)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/build-an-article-recommendation-engine-with-ai-ml.md)
* PR 地址：
* 文章分类：**后端**，**AI**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：5.5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@lsvih 这篇也发布了
