### ISSUE TITLE
JavaScript 最被误解的变量类型 Symbol

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9032]
* 原文链接：[JavaScript Symbols: the Most Misunderstood Feature of the Language?](https://blog.bitsrc.io/javascript-symbols-the-most-misunderstood-feature-of-the-language-282b6e2a220e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zaviertang** [comment]
校对认领 @lsvih

**Comment by lsvih** [comment]
@zaviertang  好嘞

**Comment by KimYangOfCat** [comment]
> 校对认领 @lsvih

@lsvih 他不是写的 校对认领 的吗？？？

**Comment by lsvih** [comment]
@KimYangOfCat  ....我没注意


@zaviertang 您这篇文章是认领的翻译还是校对呀

**Comment by zaviertang** [comment]
> @KimYangOfCat ....我没注意
> 
> @zaviertang 您这篇文章是认领的翻译还是校对呀

翻译，手误

**Comment by zaviertang** [comment]
> @KimYangOfCat ....我没注意
> 
> @zaviertang 您这篇文章是认领的翻译还是校对呀

🤧
