### ISSUE TITLE
可以在 GitHub.dev 做的十件有趣的事

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9051]
* 原文链接：[10 Fun Things You Can Do With GitHub.dev](https://dev.to/lostintangent/10-awesome-things-you-can-do-with-github-dev-5fm7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/10-awesome-things-you-can-do-with-github-dev.md)
* PR 地址：
* 文章分类：**其他**，**资讯**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由@greycodee  认领翻译

PS 这篇文章富文本太多了，效果出来应该没原文好..

**Comment by greycodee** [comment]
@lsvih 翻译完成 #9067 ，后期发布掘金的时候看看能不能把视频加上

**Comment by lsvih** [comment]
@greycodee  辛苦了-。-
