### ISSUE TITLE
React Native 开发者的流行存储方案

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9055]
* 原文链接：[Trending Storage Options for React Native Developers](https://javascript.plainenglish.io/trending-storage-options-for-react-native-developers-8671fbffb686)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/trending-storage-options-for-react-native-developers.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：5.5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by KimYangOfCat** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@KimYangOfCat  好嘞

**Comment by KimYangOfCat** [comment]
@lsvih 我认为这篇文章不应该被添加前端标签，而应该添加安卓和 ios 的标签，因为本文主要讲的是移动端的数据存储的内容。当然如果标签的前端指的是大前端这一类概念的话是可以的，如果指的是 web 前端的话，那就不合适了

**Comment by lsvih** [comment]
行，我换一下，RN 其实不太好归类

**Comment by lsvih** [comment]
像 Flutter 有单独的标签，RN 这个就很尴尬

**Comment by KimYangOfCat** [comment]
> 像 Flutter 有单独的标签，RN 这个就很尴尬

确实蛮尴尬，根据文章具体内容来可能合适点儿
