### ISSUE TITLE
使用 WasmEdge 在 WebAssembly 中运行 JavaScript

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9057]
* 原文链接：[Running JavaScript in WebAssembly with WasmEdge](https://javascript.plainenglish.io/running-javascript-in-webassembly-883ec71438e1)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/running-javascript-in-webassembly.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CarlosChenN** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@CarlosChenN 好嘞

**Comment by zhaoqi1992** [comment]
@lsvih 校对认领

**Comment by lsvih** [comment]
@zhaoqi1992 这篇文章还没有翻译完哈，等译者放出来您可以在 PR 页面里认领校对~
