### ISSUE TITLE
在安卓开发中使用 SQLDelight 入门

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9059]
* 原文链接：[Getting Started With SQLDelight in Android Development](https://betterprogramming.pub/getting-started-with-sqldelight-in-android-development-eecd0ae9bbdd)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/getting-started-with-sqldelight-in-android-development.md)
* PR 地址：
* 文章分类：**Android**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by airfri** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@airfri 好的~
