### ISSUE TITLE
5 个 JavaScript 的字符操作库

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9061]
* 原文链接：[5 String Manipulation Libraries for JavaScript](https://blog.bitsrc.io/5-string-manipulation-libraries-for-javascript-9ca5da8b4eb8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/5-string-manipulation-libraries-for-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@jaredliw 好嘞

**Comment by jaredliw** [comment]
@lsvih 额，这篇已经被翻译过了：https://www.gushiciku.cn/pl/gSQC

**Comment by lsvih** [comment]
@jaredliw 这篇才出来没几天=。=也太快了   没关系，可以按他的翻译参考校对
