### ISSUE TITLE
别让轮播毁了你的应用程序

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9063]
* 原文链接：[Don’t Let Carousels Kill Your Application](https://blog.bitsrc.io/dont-let-carousels-kill-your-application-ba5ce27f6d10)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/dont-let-carousels-kill-your-application.md)
* PR 地址：
* 文章分类：**设计**，**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@jaredliw 好的
