### ISSUE TITLE
React Native Android 的 native 模块

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#907]
* 原文链接：[Native Modules for React Native Android](https://shift.infinite.red/native-modules-for-react-native-android-ac05dbda800d#.cdjn1o88w)
* 掘金链接：[React Native Android 的 native 模块](http://gold.xitu.io/entry/581ad67167f356005882a970)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/native-modules-for-react-native-android.md)
* PR 地址： #936
* 文章分类：**React Native**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XHShirley** [comment]
认领。明天开始翻译。

**Comment by sqrthree** [comment]
好的👌🏻
