### ISSUE TITLE
详解 React Native 使用 OneSignal 推送通知

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#908]
* 原文链接：[React Native Push Notifications with OneSignal](https://medium.com/differential/react-native-push-notifications-with-onesignal-9db6a7d75e1e#.ji9dbcxv7)
* 掘金链接：[详解 React Native 使用 OneSignal 推送通知](http://gold.xitu.io/entry/581ad42f0ce46300586eb166)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/react-native-push-notifications-with-onesignal.md)
* PR 地址：#952
* 文章分类：**React Native**

----
* 翻译时间：`4` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xiaoheiai4719** [comment]
认领一篇

**Comment by sqrthree** [comment]
@xiaoheiai4719 好的
