### ISSUE TITLE
`integrals.md` 为啥叫 `integrals`？

### ISSUE THREAD

**Issue by jaredliw** [xitu/gold-miner#9081]
刚刚查看积分更新时发现到记录积分的文件名叫 `integrals`。这个单词不是 **微积分** 里的 “积分” 吗，和这里的积分有啥关系？是不小心取错名了吗？

**Comment by lsvih** [comment]
这方面主题可以在 discussions 板块讨论，且文件命名由于历史原因不会变更

**Comment by jaredliw** [comment]
okay～
