### ISSUE TITLE
无密码认证，安全更有保障

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9089]
* 原文链接：[Passwordless Authentication for Better Security](https://blog.bitsrc.io/passwordless-authentication-for-better-security-ba986df663b7)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/passwordless-authentication-for-better-security.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by NieZhuZhu** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@NieZhuZhu  好嘞
