### ISSUE TITLE
利用 React Native 对 Android APP 进行内存调查

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#909]
* 原文链接：[React Native Android App Memory Investigation](https://shift.infinite.red/react-native-android-app-memory-investigation-55695625da9c#.a1m35m6jb)
* 掘金链接：[利用 React Native 对 Android APP 进行内存调查](http://gold.xitu.io/entry/581ad583128fe10055ae5b29)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/react-native-android-app-memory-investigation.md)
* PR 地址：#938
* 文章分类：**React Native**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by huanglizhuo** [comment]
认领

**Comment by huanglizhuo** [comment]
sorry 想了想最近可能没什么时间翻译  不占坑了 : (  @sqrthree

**Comment by sqrthree** [comment]
@huanglizhuo copythat.

**Comment by phxnirvana** [comment]
领第一篇~

**Comment by sqrthree** [comment]
@phxnirvana 好的。
