### ISSUE TITLE
手工制作 SVG 条形图（具有一些 SVG 定位陷阱）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#910]
* 原文链接：[A Handmade SVG Bar Chart (featuring some SVG positioning gotchas)](https://css-tricks.com/handmade-svg-bar-chart-featuring-svg-positioning-gotchas/)
* 掘金链接：[手工制作 SVG 条形图（具有一些 SVG 定位陷阱）](http://gold.xitu.io/entry/58219076a0bb9f0058c61433)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/handmade-svg-bar-chart-featuring-svg-positioning-gotchas.md)
* PR 地址：#956
* 文章分类：**前端 SVG**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cyseria** [comment]
认领

**Comment by sqrthree** [comment]
@cyseria 好的

**Comment by sqrthree** [comment]
@cyseria 这篇进度如何了？

**Comment by cyseria** [comment]
正在，差不多了

2016-11-15 17:54 GMT+08:00 根号三 <notifications@github.com>:

**Comment by cyseria** [comment]
@sqrthree 来了来了搞定了

**Comment by wild-flame** [comment]
@sqrthree 认领校对啦

**Comment by cyseria** [comment]
@sqrthree 已经调整完啦
