### ISSUE TITLE
掌握了这 8 个简单的规则，你就可以构建一个稳固的、可扩展的 CSS 架构了

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#911]
* 原文链接：[8 simple rules for a robust, scalable CSS architecture](https://github.com/jareware/css-architecture)
* 掘金链接：[掌握了这 8 个简单的规则，你就可以构建一个稳固的、可扩展的 CSS 架构了](http://gold.xitu.io/entry/58219292128fe1005a190fd2)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/css-architecture.md)
* PR 地址：#950
* 文章分类：**前端**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by llp0574** [comment]
get

**Comment by sqrthree** [comment]
@llp0574 好的

**Comment by llp0574** [comment]
@sqrthree [校对传送门](https://github.com/xitu/gold-miner/pull/950)

**Comment by galenyuan** [comment]
@sqrthree 认领校对

**Comment by sqrthree** [comment]
@galenyuan 下次到对应的 PR 下申请校对哈~ [校对地址](https://github.com/xitu/gold-miner/pull/950/files)  有问题随时@我
