### ISSUE TITLE
10 个准则，让你的网页动画更流畅

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#912]
* 原文链接：[10 principles for smooth web animations](https://blog.gyrosco.pe/smooth-css-animations-7d8ffc2c1d29#.oqnbskp19)
* 掘金链接：[10 个准则，让你的网页动画更流畅](http://gold.xitu.io/entry/582193f3128fe1005a191fa0)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/smooth-css-animations.md)
* PR 地址：#944
* 文章分类：**前端**

----
* 翻译时间：`5` 天
* 校对时间：`2` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
我也想翻译一篇很长很长的文章，然后拿很多很多的积分~ @sqrthree

**Comment by sqrthree** [comment]
@Romeo0906 好的~
