### ISSUE TITLE
开发无障碍网站的必备工具

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#913]
* 原文链接：[Tools for Developing Accessible Websites](https://bitsofco.de/tools-for-developing-accessible-websites/)
* 掘金链接：[开发无障碍网站的必备工具](http://gold.xitu.io/entry/58219b09da2f60005d12c133)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/tools-for-developing-accessible-websites.md)
* PR 地址：#917
* 文章分类：**前端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
Asking for an opportunity ~~ @sqrthree

**Comment by sqrthree** [comment]
@Romeo0906 OK.
