### ISSUE TITLE
CSS 变量的条件

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#914]
* 原文链接：[Conditions for CSS Variables](http://kizu.ru/en/fun/conditions-for-css-variables/)
* 掘金链接：[CSS 变量的条件](http://gold.xitu.io/entry/58219fe3128fe1005a19a08f)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/conditions-for-css-variables.md)
* PR 地址：#951
* 文章分类：**前端**

----
* 翻译时间：`4` 天
* 校对时间：`2` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sqrthree** [comment]
好的👌🏻

**Comment by rottenpen** [comment]
@sqrthree PR了哦
