### ISSUE TITLE
申请成为remix译者

### ISSUE THREAD

**Issue by williamhatch** [xitu/gold-miner#9140]
- 公司/学校：harmoney
- 工作内容/专业：架构师
- 常浏览的国外网站：medium.com
- 英语水平：很好
- 翻译经验：有点
- 主要翻译方向：计算机方面
- 个人博客：没有
- 个人介绍：资深IT人士，大部分时间在外企。希望翻译一些好的文章给国内的读者

**Comment by williamhatch** [comment]
原文地址： https://github.com/remix-run

**Comment by lsvih** [comment]
您好，现在暂时没有开系列翻译的企划，您可以直接在 remix 项目里向 maintainer 提交希望翻译的 issue 试试哈~
