### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by Macaronsyc** [xitu/gold-miner#9141]
- 公司/学校：京东 / 德国汉堡工业大学
- 工作内容/专业：前端开发
- 常浏览的国外网站：StackOverflow、Medium、Quora
- 英语水平：大学六级564 / 托福103
- 翻译经验：一般
- 主要翻译方向：前端

**Comment by yukui123** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
