### ISSUE TITLE
了解 iOS 应用程式的 code signing

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#915]
* 原文链接：[Understanding code signing for iOS apps](https://engineering.nodesagency.com/articles/iOS/Understanding-code-signing-for-iOS-apps/)
* 掘金链接：[了解 iOS 应用程式的 code signing](http://gold.xitu.io/entry/5821a5a72e958a0054000f5d)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/Understanding-code-signing-for-iOS-apps.md)
* PR 地址：#925
* 文章分类：**iOS**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
@sqrthree 收一个。 :)

**Comment by sqrthree** [comment]
@yifili09 好的~~ 注意翻译质量哈~ :smiley:

**Comment by yifili09** [comment]
@sqrthree 那个坑对我造成了成吨的伤害。 😞

**Comment by yifili09** [comment]
@sqrthree 

#925 召唤校对。
