### ISSUE TITLE
100 个能提升软件开发效率的小技巧

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#9155]
* 原文链接：[100 Tips on Software Developer Productivity](https://dev.to/apkoponen/100-tips-on-software-developer-productivity-36if)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/100-tips-on-software-developer-productivity.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：1 0 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@itcodes @lsvih 
翻译认领

**Comment by lsvih** [comment]
@jaredliw 好嘞
