### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by AceLeeWinnie** [xitu/gold-miner#916]
你好，我叫acewinnielee，计算机专业，现在在阿里云任职前端工程师。具有较好的英语基础，经常访问Github,Stackoverflow,以及一些国外程序员博客,文档也都是看英文官网的。现在在学GRE和托福，每天用背单词，完整读过英文原著，翻译也曾通过中级口译笔试。个人博客正在建设中, 非常想加入掘金翻译计划，为国内开发者献上第一手资料。

**Comment by antonia0912** [comment]
@AceLeeWinnie hi 欢迎来到掘金翻译计划 请加我微信 antonia0912 备注 GitHub ID 我来拉你进译者群~
