### ISSUE TITLE
不要信任 JavaScript 里的 `const`

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9160]
* 原文链接：[Avoid trusting const in JavaScript](https://medium.com/front-end-weekly/avoid-trusting-const-in-javascript-69c1c0b59942)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/avoid-trusting-const-in-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：3 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@jaredliw 好嘞！
