### ISSUE TITLE
作为一名前端工程师我浪费时间学习了这些技术

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9162]
* 原文链接：[Here’s a list of technologies I wasted time learning as a Web Developer](https://javascript.plainenglish.io/heres-a-list-of-technologies-i-wasted-my-time-learning-as-a-web-developer-e427d0bfafc3)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/heres-a-list-of-technologies-i-wasted-my-time-learning-as-a-web-developer.md)
* PR 地址：
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by airfri** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@airfri 欢迎翻译~

**Comment by lylyqqy** [comment]
@lsvih 校对认领

**Comment by lsvih** [comment]
@lylyqqy 您好，这篇文章已经完成校对了，您可以选择认领并校对其它文章哈，记得在 Pull requests 中认领哦

**Comment by lsvih** [comment]
收到~ @Lvyaqian123
