### ISSUE TITLE
如何使用 Python 管道 Pipe 高效编码

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9165]
* 原文链接：[Use Pipe Operations in Python for More Readable and Faster Coding](https://towardsdatascience.com/pipe-operations-in-python-1e8f8debe26)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/pipe-operations-in-python.md)
* PR 地址：
* 文章分类：**后端**，**AI**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：3 天
* 翻译积分：5.5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblofe** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblofe 好嘞

**Comment by Adolescent0** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@Adolescent0  你好，这篇文章已经翻译完了，您可以在 PR 中认领校对

**Comment by Adolescent0** [comment]
@lsvih 认领校对

**Comment by lsvih** [comment]
@Adolescent0 请在 PR - #9180 中认领校对谢谢~
