### ISSUE TITLE
你应该知道的 Node.js 内存限制

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9167]
* 原文链接：[Node.js Memory Limits - What You Should Know](https://blog.appsignal.com/2021/12/08/nodejs-memory-limits-what-you-should-know.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/nodejs-memory-limits-what-you-should-know.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：11 天
* 校对时间：4 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by airfri** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@airfri 您要同时认领这两篇吗-。-

**Comment by airfri** [comment]
@lsvih 是的

**Comment by lsvih** [comment]
好嘞

**Comment by lsvih** [comment]
由@CarlosChenN 继续翻译
