### ISSUE TITLE
使用 Python 模拟实现行星际空间旅行

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9169]
* 原文链接：[Simulate Interplanetary Space Travel in Python](https://python.plainenglish.io/simulating-interplanetary-space-travel-in-python-95116b14b6a9)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/simulating-interplanetary-space-travel-in-python.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：4.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblofe** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblofe  好嘞！
