### ISSUE TITLE
5个关于 UI 设计系统的误解

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9176]
* 原文链接：[5 Misconceptions About UI Design Systems](https://blog.bitsrc.io/5-misconceptions-about-design-systems-82453ff10acf)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2021/5-misconceptions-about-design-systems.md)
* PR 地址：
* 文章分类：**设计**
* **注意：文件位置在 `article/2021` 文件夹中，不是之前的 `article/2020` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CarlosChenN** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@CarlosChenN 好嘞

**Comment by Lvyaqian123** [comment]
已发布：https://juejin.cn/post/7086291006286462990/

**Comment by lsvih** [comment]
收到 @Lvyaqian123
