### ISSUE TITLE
使用 “Google 抓取方式” 测试 React 驱动的网站 SEO

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#918]
* 原文链接：[Testing a React-driven website’s SEO using “Fetch as Google”](https://medium.freecodecamp.com/using-fetch-as-google-for-seo-experiments-with-react-driven-websites-914e0fc3ab1#.sv5ov6im3)
* 掘金链接：[使用 “Google 抓取方式” 测试 React 驱动的网站 SEO](http://gold.xitu.io/entry/5822970267f3560058b8e1d4)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/using-fetch-as-google-for-seo-experiments-with-react-driven-websites.md)
* PR 地址：#935
* 文章分类：**前端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
@sqrthree 有意思，我领走了。

**Comment by sqrthree** [comment]
@yifili09 好的

**Comment by yifili09** [comment]
@sqrthree 

#918 召唤校对同学啦。

**Comment by markzhai** [comment]
认领校对

**Comment by sqrthree** [comment]
@markzhai 好的~ 下次到对应的 PR 下认领校对哈
