### ISSUE TITLE
停止这样构建你的组件❌

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#9182]
* 原文链接：[Stop Building Your UI Components like this❌](https://dev.to/harshkc/stop-building-your-ui-components-like-this-19il)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/Stop-Building-Your-UI-Components-like-this.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zaviertang** [comment]
翻译认领

**Comment by lsvih** [comment]
@zaviertang 好嘞

**Comment by Lvyaqian123** [comment]
发布啦~https://juejin.cn/post/7085634227177259022

**Comment by lsvih** [comment]
收到 @Lvyaqian123
