### ISSUE TITLE
用 React Native 创建实时医疗应用

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#9184]
* 原文链接：[Create A Real-Time Medical App With React Native](https://medium.com/javascript-in-plain-english/create-a-real-time-medical-app-with-react-native-637618b7883f)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/Create-A-Real-Time-Medical-App-With-React-Native.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：6 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Baddyo** [comment]
认领翻译。

**Comment by lsvih** [comment]
@Baddyo 好的
