### ISSUE TITLE
HTTP/3 为什么这么快？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9187]
* 原文链接：[HTTP/3 is Fast](https://requestmetrics.com/web-performance/http3-is-fast)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/http3-is-fast.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：15 天
* 校对时间：4 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@jaredliw 好的
