### ISSUE TITLE
WasmEdge 的安装与卸载

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#9189]
* 原文链接：[Install and uninstall WasmEdge](https://wasmedge.org/book/en/start/install.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/Install-and-uninstall-WasmEdge.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@itcodes 翻译认领

**Comment by lsvih** [comment]
@jaredliw 好嘞
