### ISSUE TITLE
研读 NodeJS 文档，我知道了这 19 件事

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#919]
* 原文链接：[19 things I learnt reading the NodeJS docs](https://hackernoon.com/19-things-i-learnt-reading-the-nodejs-docs-8a2dcc7f307f#.8iaiz8xls)
* 掘金链接：[研读 NodeJS 文档，我知道了这 19 件事](http://gold.xitu.io/entry/58229cfc570c350060c425d8)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/19-things-i-learnt-reading-the-nodejs-docs.md)
* PR 地址：#953
* 文章分类：**Node**

----
* 翻译时间：`4` 天
* 校对时间：`2` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jacksonke** [comment]
认领

**Comment by sqrthree** [comment]
@jacksonke 好的

**Comment by sqrthree** [comment]
@jacksonke please check this [link](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E8%80%85%E6%93%85%E9%95%BF%E9%A2%86%E5%9F%9F%E8%A1%A8) and add your infomation. 😄
