### ISSUE TITLE
css-is-magic-its-time-you-try-3d 仓库跳转问题

### ISSUE THREAD

**Issue by anstxy-vi** [xitu/gold-miner#9193]
![image](https://user-images.githubusercontent.com/77254335/148338748-f3202f95-c221-4e81-8502-0f4c0d69196c.png)

**Comment by anstxy-vi** [comment]
文章位置 article/2021 就不pr

**Comment by lsvih** [comment]
@anstxy-vi 已修复，感谢您的捉虫！
