### ISSUE TITLE
简述 JavaScript 软件包管理器是如何工作的

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#920]
* 原文链接：[An introduction to how JavaScript package managers work](https://medium.freecodecamp.com/javascript-package-managers-101-9afd926add0a#.746vwi3oh)
* 掘金链接：[简述 JavaScript 软件包管理器是如何工作的](http://gold.xitu.io/entry/5822bfc52f301e005c36e1b0)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/javascript-package-managers.md)
* PR 地址：#961
* 文章分类：**JS / NPM**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luoyaqifei** [comment]
认领

**Comment by sqrthree** [comment]
@luoyaqifei 好的~ 不过你等先把之前的问题咱俩都弄好了再开始翻译这个吧。😂😂

**Comment by luoyaqifei** [comment]
文章里少了那个推特，不知道原来的markdown应该是怎样的？
lockfiles = awesome for apps, bad for libs this is not a new thought, i'm confused why's everyone mad about this

 — @ag_dubs

**Comment by sqrthree** [comment]
@luoyaqifei 你直接加上就好~ 有可能是导出的时候疏忽了。

**Comment by sqrthree** [comment]
@luoyaqifei 这篇进度如何了？
