### ISSUE TITLE
如何使用 Python 构建 GUI 程序

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9203]
* 原文链接：[How to Build a GUI Program with Python](https://python.plainenglish.io/how-to-build-gui-with-python-1e953f5c697c)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/how-to-build-gui-with-python.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by lsvih** [comment]
@YueYongDev 好嘞
