### ISSUE TITLE
5 个原因告诉你：找对象就得找程序员！

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9206]
* 原文链接：[5 Extremely Amusing Reasons to Date a Programmer](https://javascript.plainenglish.io/5-extremely-amusing-reasons-to-date-a-programmer-7061ce80798a)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/5-extremely-amusing-reasons-to-date-a-programmer.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@jaredliw 好嘞
