### ISSUE TITLE
使用 React.js 的渐进式 Web 应用程序：第 I 部分 - 简介

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#921]
* 原文链接：[Progressive Web Apps with React.js: Part I — Introduction](https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-i-introduction-50679aef2b12#.g5r0gv9j5)
* 掘金链接：[使用 React.js 的渐进式 Web 应用程序：第 I 部分 - 简介](http://gold.xitu.io/entry/5822c3340ce4630058a72ce5)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/progressive-web-apps-with-react-js-part-i-introduction.md)
* PR 地址：#934
* 文章分类：**前端 / React**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by markzhai** [comment]
认领

**Comment by sqrthree** [comment]
@markzhai 好

**Comment by markzhai** [comment]
https://github.com/xitu/gold-miner/pull/934
