### ISSUE TITLE
用 PNPM Workspaces 替换 Lerna + Yarn

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9219]
* 原文链接：[Replacing Lerna + Yarn with PNPM Workspaces](https://www.raulmelo.dev/blog/replacing-lerna-and-yarn-with-pnpm-workspaces)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/replacing-lerna-and-yarn-with-pnpm-workspaces.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：20 天
* 校对时间：6 天
* 翻译积分：11 分
* 校对积分：5.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CarlosChenN** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@CarlosChenN 好的
