### ISSUE TITLE
使用 React.js 的渐进式 Web 应用程序：第 2 部分 - 页面加载性能

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#922]
* 原文链接：[Progressive Web Apps with React.js: Part 2 — Page Load Performance](https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-2-page-load-performance-33b932d97cf2#.o0f4vf64s)
* 掘金链接：[使用 React.js 的渐进式 Web 应用程序：第 2 部分 - 页面加载性能](http://gold.xitu.io/entry/5822d0ef2e958a12991dacb1)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/progressive-web-apps-with-react-js-part-2-page-load-performance.md)
* PR 地址：#946
* 文章分类：**前端 / React**

----
* 翻译时间：`4 ~ 5` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`3` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by markzhai** [comment]
认领

**Comment by sqrthree** [comment]
@markzhai OK.

**Comment by markzhai** [comment]
见 https://github.com/xitu/gold-miner/pull/946

**Comment by markzhai** [comment]
@sqrthree 根据校对意见改好啦

**Comment by sqrthree** [comment]
好的

**Comment by markzhai** [comment]
http://gold.xitu.io/post/583576f3c4c9710054a3e212

发好了
@sqrthree @antonia0912
