### ISSUE TITLE
双向绑定会使你的 React 代码更棒

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9225]
* 原文链接：[Two-way binding will make your React code better](https://medium.com/front-end-weekly/two-way-binding-will-make-your-react-code-better-f58865923538)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/two-way-binding-will-make-your-react-code-better.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：5 天
* 校对时间：1 天
* 翻译积分：2 分
* 校对积分：1 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
p.s. 可以把图片中的代码换成代码块

**Comment by Tong-H** [comment]
翻译认领

**Comment by lsvih** [comment]
@Tong-H 好嘞
