### ISSUE TITLE
4 个鲜为人知的 Swift 特性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9227]
* 原文链接：[4 Lesser-Known Swift Features](https://betterprogramming.pub/4-lesser-known-swift-features-ddfbc9268aa9)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/4-lesser-known-swift-features.md)
* PR 地址：
* 文章分类：**iOS**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：5.5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@jaredliw  好的
