### ISSUE TITLE
使用 React.js 的渐进式 Web 应用程序：第 3 部分 - 离线支持和网络恢复能力

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#923]
* 原文链接：[Progressive Web Apps with React.js: Part 3 — Offline support and network resilience](https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-3-offline-support-and-network-resilience-c84db889162c#.i71vp23vj)
* 掘金链接：[使用 React.js 的渐进式 Web 应用程序：第 3 部分 - 离线支持和网络恢复能力](http://gold.xitu.io/entry/5822d1902f301e005c377a8d/)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/progressive-web-apps-with-react-js-part-3-offline-support-and-network-resilience.md)
* PR 地址：#966 -> #968 -> #969
* 文章分类：**前端 / React**

----
* 翻译时间：`4 ~ 5` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by markzhai** [comment]
认领

**Comment by sqrthree** [comment]
@markzhai 好的

**Comment by sqrthree** [comment]
译者放弃。

**Comment by AceLeeWinnie** [comment]
认领

**Comment by sqrthree** [comment]
@AceLeeWinnie 好的

**Comment by sqrthree** [comment]
@AceLeeWinnie 这篇进度如何了？

**Comment by AceLeeWinnie** [comment]
啊 差不多了 明天可以发出来校对
