### ISSUE TITLE
Cookie 通知的最佳实践方案

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9231]
* 原文链接：[Best Practices for Cookie Notifications](https://blog.bitsrc.io/best-practices-for-cookie-notifications-956aa9ded8d5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/best-practices-for-cookie-notifications.md)
* PR 地址：
* 文章分类：**设计**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@lsvih 再领一篇行不？

**Comment by lsvih** [comment]
@jaredliw 行= =

**Comment by lsvih** [comment]
@jaredliw 别整太辛苦了啊

**Comment by jaredliw** [comment]
> @jaredliw 别整太辛苦了啊

哈哈哈哈 多谢关心~

**Comment by jaredliw** [comment]
@lsvih 
https://juejin.cn/post/7066985086876385293
谢谢大家~
