### ISSUE TITLE
如何编写更简洁优雅的 React 代码

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9238]
* 原文链接：[How to Write Cleaner React code](https://medium.com/front-end-weekly/how-to-write-cleaner-react-code-a46aa179a0a1)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/how-to-write-cleaner-react-code.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblofe** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblofe 好嘞
