### ISSUE TITLE
使用 React.js 的渐进式 Web 应用程序：第 4 部分 -  逐步增强

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#924]
* 原文链接：[Progressive Web Apps with React.js: Part 4 — Progressive Enhancement](https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-4-site-is-progressively-enhanced-b5ad7cf7a447#.7fmhi469z)
* 掘金链接：[使用 React.js 的渐进式 Web 应用程序：第 4 部分 -  逐步增强](http://gold.xitu.io/entry/5822d232bf22ec0068eba796/)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/progressive-web-apps-with-react-js-part-4-site-is-progressively-enhanced.md)
* PR 地址：#962
* 文章分类：**前端 / React**

----
* 翻译时间：`4 ~ 5` 天
* 校对时间：`2` 天
* 翻译积分：`8` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by markzhai** [comment]
认领

**Comment by sqrthree** [comment]
@markzhai Sure.

**Comment by sqrthree** [comment]
译者放弃。

**Comment by rccoder** [comment]
我来翻译吧 @sqrthree

**Comment by sqrthree** [comment]
@rccoder 好的。

**Comment by rccoder** [comment]
校对地址：https://github.com/xitu/gold-miner/pull/962

**Comment by markzhai** [comment]
认领校对

**Comment by sqrthree** [comment]
@markzhai 下次记得在对应的 PR 下认领校对哈

**Comment by rccoder** [comment]
掘金链接：http://gold.xitu.io/entry/58345f5cc4c9710054e187a5/detail

感谢校对者辛苦工作，感谢根号三的时长提醒
