### ISSUE TITLE
使用了三个月的 Github Copilot，这是我的一些看法……

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9240]
* 原文链接：[Github Copilot: Review After 3 Months of Usage with Examples](https://javascript.plainenglish.io/github-copilot-review-after-3-months-of-usage-with-examples-74335cd45478)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/github-copilot-review-after-3-months-of-usage-with-examples.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：11 天
* 校对时间：2 天
* 翻译积分：5.5 分
* 校对积分：2.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@jaredliw 好嘞
