### ISSUE TITLE
自动化测试：你应当了解的一切

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9242]
* 原文链接：[Automation Testing: Everything You Should Know](https://blog.bitsrc.io/everything-you-need-to-know-about-automation-testing-c051e2e3444)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/everything-you-need-to-know-about-automation-testing.md)
* PR 地址：
* 文章分类：**其他**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：18 天
* 校对时间：4 天
* 翻译积分：10 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好嘞

**Comment by samyu2000** [comment]
@lsvih 翻译完成
