### ISSUE TITLE
使用 Stream 构建高性能的 Node.js 应用

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9244]
* 原文链接：[Use Streams to Build High-Performing Node.js Applications](https://blog.appsignal.com/2022/02/02/use-streams-to-build-high-performing-nodejs-applications.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/use-streams-to-build-high-performing-nodejs-applications.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：17 天
* 校对时间：4 天
* 翻译积分：8.5 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tong-H** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@Tong-H 好嘞
