### ISSUE TITLE
如何在网页中使用响应式图像

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9255]
* 原文链接：[What Are Responsive Images And Why You Should Use Them](https://levelup.gitconnected.com/what-are-responsive-images-and-why-you-should-use-them-ac1042d6d1ff)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/what-are-responsive-images-and-why-you-should-use-them.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：9 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zenblofe** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@zenblofe 好嘞
