### ISSUE TITLE
你需要了解的 Python 3.10 新特

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9259]
* 原文链接：[New Features In Python 3.10 You Should Know](https://python.plainenglish.io/new-features-in-python-3-10-you-should-know-18aab7ebc911)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/new-features-in-python-3-10-you-should-know.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by samyu2000** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@samyu2000 好嘞

**Comment by samyu2000** [comment]
@lsvih 翻译完成
