### ISSUE TITLE
如何运用 Memoization 来提高 React 性能

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9262]
* 原文链接：[How to Implement Memoization in React to Improve Performance](https://www.sitepoint.com/implement-memoization-in-react-to-improve-performance/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/implement-memoization-in-react-to-improve-performance.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：19 天
* 校对时间：5 天
* 翻译积分：11 分
* 校对积分：5.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zaviertang** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@zaviertang 好嘞

**Comment by xionglong58** [comment]
@lsvih 校对认领
