### ISSUE TITLE
多语言横向对比 Python 有多慢？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9265]
* 原文链接：[How Slow is Python?](https://levelup.gitconnected.com/how-slow-is-python-6f2fc1fbfbaa)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/how-slow-is-python.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Alfxjx** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@Alfxjx 好嘞
