### ISSUE TITLE
当用户跳转到其它页面时，使用 JavaScript 发送数据给服务器

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9268]
* 原文链接：[Send Data to the Server When the User Navigates to Another Page using JavaScript](https://javascript.plainenglish.io/send-data-to-the-server-when-the-user-navigates-to-another-page-using-javascript-d98a0a4a0539)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/send-data-to-the-server-when-the-user-navigates-to-another-page-using-javascript.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：3 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xyj1020** [comment]
认领翻译

**Comment by lsvih** [comment]
@xyj1020 欢迎翻译，请参考 wiki 和您之前校对文章的翻译方法提交文件，如果有任何问题请留言~

**Comment by Lvyaqian123** [comment]
https://github.com/xitu/gold-miner/labels/%E6%96%87%E7%AB%A0%E6%8E%A8%E8%8D%90
