### ISSUE TITLE
安卓多点触控指南

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9270]
* 原文链接：[Introduction to Android Multi-Touch](https://medium.com/better-programming/introduction-to-android-multi-touch-bdae5f8002f4)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/introduction-to-android-multi-touch.md)
* PR 地址：
* 文章分类：**Android**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by YueYongDev** [comment]
翻译认领

**Comment by lsvih** [comment]
@YueYongDev 好嘞

**Comment by YueYongDev** [comment]
@lsvih 翻译结束，等待校对

**Comment by lsvih** [comment]
@YueYongDev 好嘞

**Comment by YueYongDev** [comment]
@lsvih 还没人校对吗？
