### ISSUE TITLE
过度使用懒加载对 Web 性能的影响

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9281]
* 原文链接：[Effects of Too Much Lazy Loading on Web Performance](https://blog.bitsrc.io/effects-of-too-much-lazy-loading-on-performance-4dbe8df33c37)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/effects-of-too-much-lazy-loading-on-web-performance.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：10 天
* 校对时间：2 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tong-H** [comment]
翻译认领

**Comment by Tong-H** [comment]
好嘞
