### ISSUE TITLE
为什么 console.log() 会返回 ‘undefined’？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9283]
* 原文链接：[Why does console.log() return ‘undefined’?](https://blog.bitsrc.io/why-does-console-log-return-undefined-e06d44b4d0f8)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/why-does-console-log-return-undefined.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：7 天
* 校对时间：2 天
* 翻译积分：4 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xyj1020** [comment]
翻译认领@[lsvih](https://github.com/lsvih)

**Comment by lsvih** [comment]
@xyj1020 好的

**Comment by xionglong58** [comment]
@lsvih @xyj1020 校对认领

**Comment by Adolescent0** [comment]
@lsvih @xyj1020 校对认领

**Comment by lsvih** [comment]
@Adolescent0 本文已完成校对，暂时不需要再新加校对了哈~感谢您的支持

**Comment by zaviertang** [comment]
好久没来逛逛，最近 issues 里怎么没什么需求了呢？ @lsvih
