### ISSUE TITLE
Python 中 requirements.txt 与 setup.py 的对比

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9285]
* 原文链接：[A Comparison of requirements.txt vs setup.py in Python](https://python.plainenglish.io/requirements-txt-vs-setup-py-in-python-325bca3939af)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/requirements-txt-vs-setup-py-in-python.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：11 天
* 校对时间：3 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by w1187501630** [comment]
原文地址已不存在。

**Comment by lsvih** [comment]
@w1187501630 确实不存在了，不过这个译文还是可以继续的~

**Comment by w1187501630** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@w1187501630 好嘞
