### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by leo-mao** [xitu/gold-miner#9318]
- 公司/学校：慕尼黑大学
- 工作内容/专业：算法 计算机
- 常浏览的国外网站：Github/USA Today/web.de
- 英语水平：托福100/看论文/
- 翻译经验：少
- 主要翻译方向：前端/后端/算法
- 个人博客：
- 个人介绍：

**Comment by leo-mao** [comment]
@lsvih 管理员微信不通过，也进不了群

**Comment by lsvih** [comment]
@itcodes

**Comment by leo-mao** [comment]
已进, closed
