### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ZongWenlong** [xitu/gold-miner#932]
你好,我是ZongWenlong，目前在北邮读硕士，专业是计算机科学与技术，常浏览的国外网站：Quora/InfoQ、英语水平:CET-6、暂无翻译经验、个人博客：https://zongwenlong.github.io

**Comment by antonia0912** [comment]
@ZongWenlong 欢迎来到掘金翻译计划，请加我微信 antonia0912 备注 github id 我来拉你进译者群

**Comment by waychane** [comment]
@ZongWenlong Hi，如果你还没有添加 antonia 的微信，加我微信 waychane 我来加你进群吧，这个 Issue 我先 close 掉了。
