### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by fluency03** [xitu/gold-miner#933]
你好, github id：fluency03，本科学校UESTC，研究生毕业于 荷兰TU/e 和 瑞典KTH，现已在阿姆斯特丹工作，做software development，英语水平完全没问题，已发过一些英文paper，常浏览github/stackoverflow/medium，博客 https://fluency03.github.io/ ， 内容不多，大多是学习笔记，正在建设完善。 希望通过这个计划push自己阅读更多的文章，也希望把好的英文文章翻译成中文给国内的开发者。

**Comment by antonia0912** [comment]
@fluency03 欢迎来到掘金翻译计划，请加我微信 antonia0912 备注 github id 我来拉你进译者群
