### ISSUE TITLE
ES2022 有什么新特性？

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9344]
* 原文链接：[What's new in ES2022?](https://dev.to/jasmin/whats-new-in-es2022-1de6)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/whats-new-in-es2022.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：6 天
* 校对时间：2 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by HydeSong** [comment]
翻译认领@[lsvih](https://github.com/lsvih)

**Comment by lsvih** [comment]
@HydeSong 好嘞

**Comment by CarlosChenN** [comment]
@HydeSong @lsvih 要是还没开始翻译的话，我接过来翻译吧？

**Comment by lsvih** [comment]
@CarlosChenN 可以的，已经放了挺久啦

**Comment by CarlosChenN** [comment]
好的

**Comment by CarlosChenN** [comment]
@lsvih 
https://juejin.cn/post/7114676836851777566/
