### ISSUE TITLE
如何使用 Python 中的 PyPA setuptools 打包和部署 CLI 应用程序

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9368]
* 原文链接：[How to package and deploy CLI applications with Python PyPA setuptools build](https://pybit.es/articles/how-to-package-and-deploy-cli-apps/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/how-to-package-and-deploy-cli-apps.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：18 天
* 校对时间：4 天
* 翻译积分：10 分
* 校对积分：5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by earthaYan** [comment]
对这个topic感兴趣，提前认领校对哈哈哈

**Comment by haiyang-tju** [comment]
这个我来翻译吧~
翻译认领@lsvih

**Comment by lsvih** [comment]
@haiyang-tju 好嘞

**Comment by haiyang-tju** [comment]
@lsvih 
已发布，https://juejin.cn/post/7125323312321789989
正在审核中了~
