### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by ZiXYu** [xitu/gold-miner#937]
你好，我叫虞子轩，多伦多大学Computer Engineering硕士毕业，现在在杭州一金融公司做安卓开发。英语基础不错，也会在Coursera的GTC上翻译一些公开课程。有阅读和翻译英文文章的能力和经验，希望能加入大家一起学习。

**Comment by antonia0912** [comment]
@ZiXYu 欢迎来到掘金翻译计划，请加我微信 antonia0912 备注 github id 我来拉你进译者群
