### ISSUE TITLE
推荐Android优秀英文文章

### ISSUE THREAD

**Issue by MacroGoo** [xitu/gold-miner#9379]
- 原文链接：https://medium.com/androiddevelopers/locale-changes-and-the-androidviewmodel-antipattern-84eb677660d9
- 简要介绍：Google发布了官方推荐的架构，但是很多细节并没有描述清楚，Demo代码也较少，面对复杂场景时开发者无所适从，使用ViewModel同时还要用到Context是非常常见的场景，这篇文章针对这种常见场景提供了非常有意义的参考和最佳实践，是Google官方推荐的文章。
- 翻译计划处理能力有限，请勿一次性提交超过 3 篇文章的推荐哦
- 由于 markdown 的局限性以及掘金和 GitHub 的排版限制，不建议推荐包含特别多富文本或者代码沙盒的文章哈

---

### 请完成并勾选一下三项：

* [x] 按文章分类填写 Issue 标题：推荐前端/后端/AI/Android/iOS/产品/设计/Flutter/Kotlin/其他/资讯优秀英文文章
* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

> 首先通过 [Google](https://google.com) / [Bing](https://bing.com) / Baidu 等搜索关键词组合：**原文 翻译 英文文章标题** 确认没有中文译文。例如搜索：原文 翻译 Garbage Collection In Go : Part I - Semantics

**Comment by lsvih** [comment]
这篇文章已经有译文了，感谢推荐~ https://github.com/xitu/gold-miner/blob/master/TODO1/locale-changes-and-the-androidviewmodel-antipattern.md
