### ISSUE TITLE
使用令牌桶和熔断器进行重试

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9394]
* 原文链接：[Fixing retries with token buckets and circuit breakers](https://brooker.co.za/blog/2022/02/28/retries.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/retries.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：13 天
* 校对时间：4 天
* 翻译积分：6 分
* 校对积分：3 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wangxuanni** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@wangxuanni 好嘞
