### ISSUE TITLE
十大 Java 语言特性

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9396]
* 原文链接：[Top 10 Java Language Features](https://foojay.io/today/top-10-java-language-features/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/top-10-java-language-features.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：17 天
* 校对时间：4 天
* 翻译积分：8 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@lsvih 翻译认领

**Comment by lsvih** [comment]
@jaredliw 好嘞
