### ISSUE TITLE
WebRTC 与 WebSockets 教程 — Web 端的实时通信

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9398]
* 原文链接：[WebRTC vs WebSockets Tutorial — Web Real-Time Communication](https://requestum.com/webrtc-vs-websockets)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/webrtc-vs-websockets.md)
* PR 地址：
* 文章分类：**前端**，**后端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：15 天
* 校对时间：3 天
* 翻译积分：7 分
* 校对积分：3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DylanXie123** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@DylanXie123 好嘞
