### ISSUE TITLE
云上使用 Redis？你应该知道这十件事

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9426]
* 原文链接：[Using Redis on Cloud? Here are ten things you should know](https://itnext.io/using-redis-on-cloud-here-are-ten-things-you-should-know-a1026624441e)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/using-redis-on-cloud-here-are-ten-things-you-should-know.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：15 天
* 校对时间：3 天
* 翻译积分：9 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by timerring** [comment]
翻译认领 @lsvih

**Comment by lsvih** [comment]
@timerring 好嘞
