### ISSUE TITLE
用 Isabelle/HOL 验证分布式系统

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9428]
* 原文链接：[Verifying distributed systems with Isabelle/HOL](https://martin.kleppmann.com/2022/10/12/verifying-distributed-systems-isabelle.html)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/verifying-distributed-systems-isabelle.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：16 天
* 校对时间：4 天
* 翻译积分：8.5 分
* 校对积分：4 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由 @wangxuanni 认领翻译

**Comment by Quincy-Ye** [comment]
@lsvih 校对认领

**Comment by lsvih** [comment]
@Quincy-Ye 好嘞
