### ISSUE TITLE
WebGPU 与 WebGL 的计算性能差异

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9430]
* 原文链接：[WebGPU computations performance in comparison to WebGL](https://pixelscommander.com/javascript/webgpu-computations-performance-in-comparison-to-webgl/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/webgpu-computations-performance-in-comparison-to-webgl.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：8 天
* 校对时间：2 天
* 翻译积分：3.5 分
* 校对积分：1.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由 @CarlosChenN 认领翻译

**Comment by HydeSong** [comment]
认领校对

**Comment by lsvih** [comment]
@HydeSong  好嘞
