### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by StarCrew** [xitu/gold-miner#945]
您好！我叫 StarCrew，现在在华南农业大学就读，网络工程专业。具有较好的英语水平，已过CET-6，经常访问Github/Stackoverflow/Leetcode等，暂无翻译经验，个人博客是https://github.com/StarCrew。
希望加入翻译计划！

**Comment by antonia0912** [comment]
@StarCrew 欢迎来到掘金翻译计划，请加我微信 antonia0912 备注 github id 我来拉你进译者群
