### ISSUE TITLE
为什么 Websockets 难以扩展？

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#9458]
* 原文地址：[why Websockets are Hard To Scale？](https://dev.to/nooptoday/why-websockets-are-hard-to-scale-1267)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/why-websockets-are-hard-to-scale.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：10 天
* 校对时间：3 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tong-H** [comment]
校对认领

**Comment by lsvih** [comment]
@CompetitiveLin 好嘞
