### ISSUE TITLE
An Analysis of Hash Map Implementations in Popular Languages

### ISSUE THREAD

**Issue by lsvih** [xitu/gold-miner#9464]
* 原文链接：[An Analysis of Hash Map Implementations in Popular Languages](https://rcoh.me/posts/hash-map-analysis/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2022/hash-map-analysis.md)
* PR 地址：
* 文章分类：**后端**
* **注意：文件位置在 `article/2022` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：14 天
* 校对时间：5 天
* 翻译积分：7.5 分
* 校对积分：3.5 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
本文由 @wangxuanni 认领翻译

**Comment by CompetitiveLin** [comment]
文件位置是不是该换成2023了哈哈哈😂😂

**Comment by lsvih** [comment]
@CompetitiveLin 感谢提醒😂  这篇先不换了
