### ISSUE TITLE
Node.js v6 LTS 的六个 ES6 新特性

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#947]
* 原文链接：[6 of the Most Exciting ES6 Features in Node.js v6 LTS](https://nodesource.com/blog/six-of-the-most-exciting-es6-features-in-node-js-v6-lts?utm_source=nodeweekly&utm_medium=email)
* 掘金链接：[6 of the Most Exciting ES6 Features in Node.js v6 LTS](http://gold.xitu.io/entry/581b64ab2f301e005c04bf14)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/six-of-the-most-exciting-es6-features-in-node-js-v6-lts.md)
* PR 地址：#955
* 文章分类：**Node**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
@sqrthree I'm attracted by this, and I want to have it~

**Comment by Romeo0906** [comment]
@sqrthree

**Comment by sqrthree** [comment]
@Romeo0906 Sure. Go ahead.
