### ISSUE TITLE
无需配置即可创建 React Apps

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#948]
* 原文链接：[Create React apps with no build configuration](https://github.com/facebookincubator/create-react-app?utm_source=javascriptweekly&utm_medium=email)
* 掘金链接：[无需配置即可创建 React Apps](http://gold.xitu.io/entry/579ac8fac4c971005abf2dd3)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/create-react-app.md)
* PR 地址：#964
* 文章分类：**前端 / React**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by malcolmyu** [comment]
这是个啥，react 脚手架么= =

**Comment by sqrthree** [comment]
@malcolmyu 似的 😂

**Comment by jiakeqi** [comment]
get

**Comment by sqrthree** [comment]
@jiakeqi OK.
