### ISSUE TITLE
使用 GPT 基于个人文档建立聊天机器人的逐步教程

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#9484]
* 原文链接：[A step-by-step guide to building a chatbot based on your own documents with GPT](https://bootcamp.uxdesign.cc/a-step-by-step-guide-to-building-a-chatbot-based-on-your-own-documents-with-gpt-2d550534eea5)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2023/A-step-by-step-guide-to-building-a-chatbot-based-on-your-own-documents-with-GPT.md)
* PR 地址：
* 文章分类：**人工智能**
* **注意：文件位置在 `article/2023` 文件夹中，不是之前的 `article/2022` 了。**
----
* 翻译时间：14 天
* 校对时间：5 天
* 翻译积分：6 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tong-H** [comment]
校对认领

**Comment by Tong-H** [comment]
不好意思，写错了

**Comment by lsvih** [comment]
@Tong-H 哈哈欢迎翻译
