### ISSUE TITLE
Facebook 的内容占位图（Content Placeholder）是如何实现的？

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#949]
* 原文链接：[Facebook content placeholder deconstruction](http://cloudcannon.com/deconstructions/2014/11/15/facebook-content-placeholder-deconstruction.html)
* 掘金链接：[Facebook 的内容占位图（Content Placeholder）是如何实现的？](http://gold.xitu.io/entry/578df4e00a2b5800685ac741)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/facebook-content-placeholder-deconstruction.md)
* PR 地址：待添加
* 文章分类：**前端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by llp0574** [comment]
get

**Comment by sqrthree** [comment]
@llp0574 好的

**Comment by llp0574** [comment]
@sqrthree 才发现这是14年的文章。。。没问题吗？

**Comment by sqrthree** [comment]
@llp0574 我去再确认下

**Comment by sqrthree** [comment]
取消翻译
