### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by MarriotZ** [xitu/gold-miner#9516]
- 公司/学校：南京信息工程大学
- 工作内容/专业：计算机科学与技术
- 常浏览的国外网站：Stackoverflow, ByteBytego, Google Scholar
- 英语水平：CET-6, TOEFL iBT 111
- 翻译经验：2年
- 主要翻译方向：网络编程, C/C++, Go, Socket编程, 数据库, DevOps
- 个人博客：https://blog.csdn.net/weixin_42839065?type=blog
- 个人介绍：B站教育类博主 - 老美你怎么看，独立翻译优质教育类视频11片次；关注计算机领域最新技术且专业对口，定期在个人博客上分享翻译的优质海外技术文献。热爱技术传播及翻译事业。

**Comment by yukui123** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
