### ISSUE TITLE
申请兑换奖品数月，未被受理。劳烦各位管理者，有空帮忙处理一下，谢谢。

### ISSUE THREAD

**Issue by Quincy-Ye** [xitu/gold-miner#9518]
2023年7月10号，与文档中提到的工作人员申请兑换，奖品。截止到今天已经过去2个月了，期间也多次发消息与工作人员沟通。但是消息基本没有被回复过。在7月27号，回复：“好的，这周已经处理了。”，然后就杳无音讯了。

**Comment by CompetitiveLin** [comment]
掘金是不是快不行了，这个repo也好久没更新了

**Comment by Quincy-Ye** [comment]
> 掘金是不是快不行了，这个repo也好久没更新了

非常不愿意是你说的这样的情况，希望它只是到了发展瓶颈，而不是在走下坡路。
