### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by parkin-lin** [xitu/gold-miner#9519]
- 公司/学校：广东海洋大学
- 工作内容/专业：物联网工程
- 常浏览的国外网站：https://devblogs.microsoft.com/typescript/
- 英语水平：CET 6
- 翻译经验：没有从事翻译工作，自己翻译过 TS 官方博客版本公告等
- 主要翻译方向：前端生态的技术博客
- 个人博客：https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzU3NjY3NTQwMg==&action=getalbum&album_id=3121480436737671169#wechat_redirect
- 个人介绍：喜欢浏览前端社区技术博客的铲屎官兼 UP 主

**Comment by yukui123** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
