### ISSUE TITLE
Why Naming is #1 Skill for Writing Clean Code

### ISSUE THREAD

**Issue by itcodes** [xitu/gold-miner#9530]
* 原文链接：[Why Naming is #1 Skill for Writing Clean Code](https://dev.to/wasp/why-naming-is-1-skill-for-writing-clean-code-4a5p)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/article/2023/why-naming-is-1-skill-for-writing-clean-code.md)
* PR 地址：
* 文章分类：**前端**
* **注意：文件位置在 `article/2023` 文件夹中，不是之前的 `article/2021` 了。**
----
* 翻译时间：15 天
* 校对时间：3 天
* 翻译积分：5 分
* 校对积分：2 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jaredliw** [comment]
@lsvih 好久不见 翻译认领

**Comment by lsvih** [comment]
@jaredliw 好嘞
