### ISSUE TITLE
你好！申请成为译者！

### ISSUE THREAD

**Issue by Gocy015** [xitu/gold-miner#957]
你好，我是Gocy，希望能成为译者！

公司：欢聚时代
工作内容：iOS开发
常浏览的国外网站：StackOverflow，[Raywenderlich](https://www.raywenderlich.com/)
英语水平：CET-6
有无翻译经验 ：无
个人博客：[这里这里](http://blog.gocy.tech/)

说两句：从接触iOS以来，就常在Raywenderlich上寻找相关教程，能较流利阅读英文文档与教程，基本可以听懂不带字幕的WWDC Session，希望能加入翻译团队，为开发者社区尽一份力！

**Comment by dark19940411** [comment]
牛

**Comment by waychane** [comment]
Hi，加我的微信 waychane，我来添加你到译者群。

**Comment by Gocy015** [comment]
已发送申请~ @waychane
