### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by JesseJia** [xitu/gold-miner#9572]
- 公司/学校：字节跳动（已离职）/澳大利亚新南威尔士大学
- 工作内容/专业：后端研发/计算机
- 常浏览的国外网站：Youtube、Github、StackOverflow
- 英语水平：IELTS 6.5
- 翻译经验：暂无
- 主要翻译方向：计算机技术类、互联网类
- 个人博客：B站账号：程序员艾噗Ape
- 个人介绍：有过海外留学经验，硕士，主修专业是IT。之前在字节跳动抖音电商部分工作，目前已经离职成为一名自由职业者。有机会的话愿意尝试一些和计算机、互联网相关的翻译工作。

**Comment by yukui123** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
