### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by aqm857886159** [xitu/gold-miner#9574]
- 公司/学校：中北大学
- 工作内容/专业：飞行器制造工程
- 常浏览的国外网站：twitter，投资网站
- 英语水平：四级
- 翻译经验：没啥
- 主要翻译方向：金融，产品
- 个人博客：
- 个人介绍：常读书，思考，拍知识类视频。

**Comment by yukui123** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
