### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by zi-zhao** [xitu/gold-miner#9576]
- 公司/学校：西安电子科技大学
- 工作内容/专业：前端/信息工程专业
- 常浏览的国外网站：
1.英国BBC：https://www.bbc.co.uk 
2.dev：https://dev.to   
3.stackoverFlow：https://stackoverflow.com
- 英语水平：四六级
- 翻译经验：无正式翻译技术文章的经验
- 主要翻译方向：前端
- 个人博客：无
- 个人介绍：一名大四学生，目前在学习前端，想为翻译文章这方面贡献一份力量。曾参加过美国大学生数学建模大赛，拥有基本的外文论文理解能力与写作能力。

**Comment by rubbidh** [comment]
如何添加管理员微信呢
