### ISSUE TITLE
Python/Numpy 语音指纹与识别 (dejavu)

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#958]
* 原文链接：[Audio Fingerprinting with Python and Numpy](http://willdrevo.com/fingerprinting-and-audio-recognition-with-python/)
* 掘金链接：[Python/Numpy 语音指纹与识别 (dejavu)](http://gold.xitu.io/entry/582a78e30ce463006cd2315d)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/fingerprinting-and-audio-recognition-with-python.md)
* PR 地址：#1018
* 文章分类：**Python**

----
* 翻译时间：`8` 天
* 校对时间：`3` 天
* 翻译积分：`10` 分
* 校对积分：`3` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Airmacho** [comment]
认领

**Comment by sqrthree** [comment]
好的👌🏻

**Comment by sqrthree** [comment]
@Airmacho 这篇文章进度如何了？

**Comment by Airmacho** [comment]
@sqrthree 我尽快，sorry，这篇大部分是信号处理方面的知识，我查了很多资料，但是有的地方还是不敢下手。

**Comment by sqrthree** [comment]
@Airmacho 好的~ 辛苦啦
