### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by saderickhuang** [xitu/gold-miner#9581]
- 公司/学校：曾任职应用材料/IBM等外企，目前任职国内半导体智能制造行业公司，毕业于香港城市大学
- 工作内容/专业：项目经理/软件工程师，工作内容主要是半导体行业计算机集成制造(CIM)系统相关
- 常浏览的国外网站：Quora,Reddit,StackOverflow
- 英语水平：满足工作需要的水平，IELTS 7.0
- 翻译经验：内部技术文档翻译,软件提示信息和UI专业术语翻译(中译英+英译中)，博客文章翻译
- 主要翻译方向：软件工程内容，半导体制造和智能制造相关内容等
- 个人博客：http://blog.learnext.xyz/
- 个人介绍：希望在离开外企后继续保持英语水平，也希望为社区贡献一点力量

**Comment by yukui123** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
