### ISSUE TITLE
带你声明 Python 中的可变属性

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#959]
* 原文链接：[Python: Declaring Dynamic Attributes](http://amir.rachum.com/blog/2016/10/05/python-dynamic-attributes/)
* 掘金链接：[Python: Declaring Dynamic Attributes](http://gold.xitu.io/entry/582a86b00ce463006cd2a7e4)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/python-dynamic-attributes.md)
* PR 地址：#963
* 文章分类：**Python**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
我敢说我抢到一篇好文章，给不给？ @sqrthree

**Comment by sqrthree** [comment]
@Romeo0906 Sure, go ahead.
