### ISSUE TITLE
Python 数据可视化概览（涵盖 ggplot 和 Altair）

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#960]
* 原文链接：[A Dramatic Tour through Python’s Data Visualization Landscape (including ggplot and Altair)](https://dansaber.wordpress.com/2016/10/02/a-dramatic-tour-through-pythons-data-visualization-landscape-including-ggplot-and-altair/)
* 掘金链接：[A Dramatic Tour through Python’s Data Visualization Landscape (including ggplot and Altair)](http://gold.xitu.io/entry/582a889e8ac247006188913b)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-dramatic-tour-through-pythons-data-visualization-landscape-including-ggplot-and-altair.md)
* PR 地址：#990
* 文章分类：**Python**

----
* 翻译时间：`8` 天
* 校对时间：`4` 天
* 翻译积分：`12` 分
* 校对积分：`4` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by cdpath** [comment]
认领~ 大爱 ggplot2

**Comment by sqrthree** [comment]
@cdpath 好的~ 这篇文章有点长~ 辛苦啦

**Comment by cdpath** [comment]
申请延期一天。目前进度 4/5。

**Comment by sqrthree** [comment]
好的~ 辛苦啦
