### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by jieniu** [xitu/gold-miner#965]
公司/学校：深圳迅雷网络，掌玩网络
工作内容/专业：互联网
常浏览的国外网站：medium.com
英语水平：一般
有无翻译经验：有，参见[我的博客](http://jieniu.me)
个人博客：http://jieniu.me

**Comment by DvilAwn** [comment]
睡觉刷掘金时候发现了你的,从草根到英雄...
挺不错的,可惜都是英文资源  - -然后就放弃了

2016-11-18 13:36 GMT+08:00 jieniu <notifications@github.com>:

**Comment by waychane** [comment]
Hi，欢迎加入掘金翻译计划，加我的微信 waychane，我添加你进译者群。
