### ISSUE TITLE
Android 界面的性能优化 —— 减少过度绘制

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#971]
* 原文链接：[Optimizing Layouts in Android – Reducing Overdraw](http://riggaroo.co.za/optimizing-layouts-in-android-reducing-overdraw/)
* 掘金链接：[Optimizing Layouts in Android – Reducing Overdraw](http://gold.xitu.io/entry/56c13b5da633bd0058784a77)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/optimizing-layouts-in-android-reducing-overdraw.md)
* PR 地址：#984
* 文章分类：**Android**

----
* 翻译时间：`2 ~ 3` 天
* 校对时间：`1` 天
* 翻译积分：`3` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
认领 啊哈哈

**Comment by sqrthree** [comment]
@yifili09 好的
