### ISSUE TITLE
移动端设计最佳实践

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#972]
* 原文链接：[Mobile Design Best Practices](http://babich.biz/mobile-design-best-practices/)
* 掘金链接：[设计手机 App 的最佳实践](http://gold.xitu.io/entry/583402e567f35600659c1b08)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/mobile-design-best-practices.md)
* PR 地址：#973
* 文章分类：**设计**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gocy015** [comment]
想翻，但我不是产品 0.0 可以翻吗 @sqrthree

**Comment by sqrthree** [comment]
@Gocy015 那你可要保证质量哈~
