### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by cwen0** [xitu/gold-miner#974]
您好, 我是 cwen，目前大四，计算机专业，[ PingCAP](https://github.com/pingcap)  实习生, 做一些 go 语言开发以及 sre 相关的工作, 英语过CET-4，经常浏览Github/golang.org/StackOverflow, 无翻译经历，但想为社区贡献一点自己的力量，并且希望通过翻译，来锻炼自己的英语能力和专业能力，接触最新的技术文章，认识一些志同道合的朋友。  
github: [cwen0](https://github.com/cwen0)  ~[cwen-coder](https://github.com/cwen-coder)~   
blog: [cwen's blog](http://int64.me)     
希望可以加入多多学习交流，谢谢！

**Comment by waychane** [comment]
Hi，加我微信 waychane，加你进译者群。

**Comment by cwen0** [comment]
@waychane 谢谢，已添加
