### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by SUT-GC** [xitu/gold-miner#975]
您好，我是Icarus.gc，21岁， 计算机专业，现阶段在 饿了么 工作，主要作java和python的后台开发，英语水平中等，经常浏览Github/golang.org/StackOverflow, 无翻译经历，想要给“掘金”提供一份贡献的同时，提高自己的英语能力与专业能力，希望接触技术前沿文章并且将其传递给大家，想认识一些志同道合的小伙伴，大家一起玩耍。。。
github:https://github.com/SUT-GC
blog:http://blog.csdn.net/gc_chao/

我会认真对待，谢谢

**Comment by waychane** [comment]
Hi，加我微信 waychane，加你进译者群。
