### ISSUE TITLE
从 Node.js 到 Golang 的迁徙之路

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#977]
* 原文链接：[Making the Switch from Node.js to Golang](https://medium.com/@theflapjack103/the-way-of-the-gopher-6693db15ae1f#.f1purx7x4)
* 掘金链接：[Digg Blog, Making the Switch from Node.js to Golang](http://gold.xitu.io/entry/57bd528d2e958a00694c3a52)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/the-way-of-the-gopher.md)
* PR 地址：#1004
* 文章分类：**后端**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
@下手晚了，好姑娘都被抢走了，所以我只能认领一篇大龄剩女了~ @sqrthree

**Comment by sqrthree** [comment]
@Romeo0906 好的
