### ISSUE TITLE
webhook 该做的和不该做的

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#978]
* 原文链接：[Webhooks do’s and dont’s: what we learned after integrating +100 APIs](https://restful.io/webhooks-dos-and-dont-s-what-we-learned-after-integrating-100-apis-d567405a3671)
* 掘金链接：[Webhooks 最佳实践](http://gold.xitu.io/entry/58356fba128fe10062c92dd4)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/webhooks-dos-and-dont-s-what-we-learned-after-integrating-100-apis.md)
* PR 地址：#991
* 文章分类：**我也不知道这是哪个分类，反正是讲 Webhooks 的**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by steinliber** [comment]
认领了

**Comment by sqrthree** [comment]
@steinliber 好的

**Comment by steinliber** [comment]
翻译完成 @sqrthree
