### ISSUE TITLE
Node & Express 入门指南

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#979]
* 原文链接：[Introduction to Node & Express](https://medium.com/javascript-scene/introduction-to-node-express-90c431f9e6fd#.xffyxajza)
* 掘金链接：[Node & Express 入门指南](http://gold.xitu.io/entry/5832d497c4c971005f55cf88)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/introduction-to-node-express.md)
* PR 地址：#1000
* 文章分类：**Node & Express**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
终于等到你~

**Comment by sqrthree** [comment]
@Romeo0906 好的

**Comment by Romeo0906** [comment]
@sqrthree这两天有事，我尽量周日的时候做完，不然的话可能要延期一天😂😂😂

**Comment by sqrthree** [comment]
好的👌🏻
