### ISSUE TITLE
在 Android App 中检测来电信息

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#980]
* 原文链接：[Detecting Incoming Phone Calls In Android](http://www.theappguruz.com/blog/detecting-incoming-phone-calls-in-android)
* 掘金链接：[在 Android App 中检测来电信息](http://gold.xitu.io/entry/5832bf17d203090067214399)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/detecting-incoming-phone-calls-in-android.md)
* PR 地址：#993
* 文章分类：**Android**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by phxnirvana** [comment]
领~

**Comment by sqrthree** [comment]
@phxnirvana 好的

**Comment by jamweak** [comment]
啊，我推荐的文章啊，来晚了一步。。。这块我熟，让我校对吧。

**Comment by sqrthree** [comment]
@jamweak 哈哈那等到校对的时候@你下
