### ISSUE TITLE
如何用 JavaScript 作图

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#981]
* 原文链接：[How to draw in JavaScript](https://aleen42.gitbooks.io/personalwiki/content/post/how_to_draw/how_to_draw.html)
* 掘金链接：[How to draw in JavaScript](http://gold.xitu.io/entry/581c2ba82f301e005c088a23)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how_to_draw.md)
* PR 地址：#1003
* 文章分类：**前端**

----
* 翻译时间：`5` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by aleen42** [comment]
Markdown 文件暂时有问题，可以先看我这边的：https://github.com/aleen42/personalwiki/blob/master/post/how_to_draw/how_to_draw.md

**Comment by AceLeeWinnie** [comment]
合我口味
认领 @sqrthree

**Comment by sqrthree** [comment]
@AceLeeWinnie 好的

**Comment by sqrthree** [comment]
已经更新好了哈

**Comment by aleen42** [comment]
@sqrthree http://gold.xitu.io/entry/581c2ba82f301e005c088a23 这个也更新一下吧 好丑

**Comment by sqrthree** [comment]
@waychane 掘金上的你更新一下吧。

**Comment by waychane** [comment]
@sqrthree 要更新啥，原文链接么？

**Comment by aleen42** [comment]
@waychane 掘金的那個排版

**Comment by waychane** [comment]
@sqrthree 明天跟周玉说一下让他重新抓一下。

**Comment by sqrthree** [comment]
好的👌

**Comment by AceLeeWinnie** [comment]
#1003
