### ISSUE TITLE
通过 Python 和 Pandas 调用 SQLite Databases

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#983]
* 原文链接：[Working with SQLite Databases using Python and Pandas](https://www.dataquest.io/blog/python-pandas-databases/)
* 掘金链接：[通过 Python 和 Pandas 调用 SQLite Databases](http://gold.xitu.io/entry/582a80738ac2470061884fc3)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/python-pandas-databases.md)
* PR 地址：#992
* 文章分类：**Python 后端**

----
* 翻译时间：`5` 天
* 校对时间：`3` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
收。。啊哈哈

**Comment by sqrthree** [comment]
@yifili09 好的

**Comment by yifili09** [comment]
@sqrthree 这个 “梗"，我们是过不去了对么。 😥  😥

**Comment by yifili09** [comment]
@sqrthree 
#992 现在召唤小伙伴校对。
