### ISSUE TITLE
来写一个 Python 说明文档生成器吧

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#985]
* 原文链接：[How to write your own Python documentation generator](https://medium.com/python-pandemonium/python-introspection-with-the-inspect-module-2c85d5aa5a48#.hcqq6xtl8)
* 掘金链接：[如何写一个 Python 文档生成器](http://gold.xitu.io/entry/58292a4b5bbb50004f1d8203)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/python-introspection-with-the-inspect-module.md)
* PR 地址：#1029
* 文章分类：**Python 后端**

----
* 翻译时间：`4` 天
* 校对时间：`2` 天
* 翻译积分：`5` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
我又来认领老姑娘了，手痒痒 @sqrthree

**Comment by sqrthree** [comment]
好的👌🏻哈哈哈 come on
