### ISSUE TITLE
JavaScript 测试︰ 单元 vs 功能 vs 集成测试

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#986]
* 原文链接：[JavaScript Testing: Unit vs Functional vs Integration Tests](http://www.sitepoint.com/javascript-testing-unit-functional-integration)
* 掘金链接：[JavaScript Testing: Unit vs Functional vs Integration Tests](http://gold.xitu.io/entry/5722c99d39b057006ad469ef/)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/javascript-testing-unit-functional-integration.md)
* PR 地址：#1001
* 文章分类：**前端 JavaScript**

----
* 翻译时间：`4` 天
* 校对时间：`2` 天
* 翻译积分：`6` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wild-flame** [comment]
认领啦。

**Comment by sqrthree** [comment]
@wild-flame 好的~ 顺便看下这个 [wiki](https://github.com/xitu/gold-miner/wiki/译者擅长领域表) 哈

**Comment by wild-flame** [comment]
4天时间好快~~ 不过马上就要好啦。

**Comment by sqrthree** [comment]
@wild-flame 恩恩辛苦啦

**Comment by wild-flame** [comment]
已经完毕啦，文中我有几个有一些疑问的地方留了注解，校对顺便帮忙看看：D
