### ISSUE TITLE
TensorFlow —  第三部分: 所有的模型

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#987]
* 原文链接：[TensorFlow in a Nutshell — Part Three: All the Models](https://hackernoon.com/tensorflow-in-a-nutshell-part-three-all-the-models-be1465993930?gi=ce7ca5538f3e#.ji73p7x7j)
* 掘金链接：[TensorFlow in a Nutshell — Part Three: All the Models](http://gold.xitu.io/entry/582a7c76d203090067e36f52)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/tensorflow-in-a-nutshell-part-three-all-the-models.md)
* PR 地址：#1035
* 文章分类：**好像是讲 Python 的**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yifili09** [comment]
@sqrthree 收 收 收。。

**Comment by sqrthree** [comment]
@yifili09 好的，一和二正在路上哈~ 稍后就来

**Comment by yifili09** [comment]
@sqrthree 

#992 都没有小伙伴校对。 这篇都没心情搞了。。 😿 😿

**Comment by sqrthree** [comment]
@yifili09 😯别急，让他们飞一会

**Comment by yifili09** [comment]
@sqrthree  这篇还没翻译呢啊。。。。

**Comment by yifili09** [comment]
@sqrthree 我准备去接 「特别任务」去了，这个我还是割爱让给其他人吧。。

**Comment by sqrthree** [comment]
@yifili09 别着急嘛，等「特别任务」结果出来了再换也不迟哎~

**Comment by edvardHua** [comment]
认领

**Comment by sqrthree** [comment]
@edvardHu 好的

**Comment by sqrthree** [comment]
@edvardHua 这篇文章的进度怎么样了？

**Comment by edvardHua** [comment]
@sqrthree 明天提交。
