### ISSUE TITLE
用 Python 建立一个简单的对象模型

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#988]
* 原文链接：[A Simple Object Model](http://aosabook.org/en/500L/a-simple-object-model.html)
* 掘金链接：[关于面向对象编程语言的对象模型](http://gold.xitu.io/entry/5836a31eda2f600062849001/)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/a-simple-object-model.md)
* PR 地址：#1026
* 文章分类：**反正是编程**

----
* 翻译时间：`6 ~ 7` 天
* 校对时间：`2` 天
* 翻译积分：`9` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Zheaoli** [comment]
接了，，对了，这个分能不能往上再调一点啊233

**Comment by sqrthree** [comment]
好，回去了我看看

**Comment by sqrthree** [comment]
@Zheaoli 这篇文章的进度如何了？
