### ISSUE TITLE
申请成为译者

### ISSUE THREAD

**Issue by xekri** [xitu/gold-miner#989]
学校：南京邮电大学 大四
曾实习于：南京人人保网络技术有限公司
学习、工作内容：前端方面，包括React、jQuery等
常浏览的国外网站：StackOverflow、CSS-Tricks.com、EloquentJavaScript.net（其实是本电子书）和维基百科等。
英语水平：TOEFL 90（口语不行）
翻译经验：这篇文章原来翻译的不太好，我重译了一下：[立即执行函数表达式(IIFE)](https://segmentfault.com/a/1190000007569312)。还曾在维基上翻译过一些前端方面的词条（账号forBlone）
个人博客：建过几个，正在建新的😓，希望能缓几天。。（买了域名qianduan.blog 2333）
希望能成为译者，为掘金社区贡献一份力量~

**Comment by waychane** [comment]
Hi，加我微信 waychane，加你进译者群，周末可能不能及时回复。

**Comment by xekri** [comment]
Hi，我微信昵称是blanu，已经加您。等工作日回复没事的。
