### ISSUE TITLE
彻底理解引用在 Android 和 Java 中的工作原理

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#994]
* 原文链接：[Finally understanding how references work in Android and Java](https://medium.com/google-developer-experts/finally-understanding-how-references-work-in-android-and-java-26a0d9c92f83#.x1m4ykp6m)
* 掘金链接：[Finally understanding how references work in Android and Java](http://gold.xitu.io/entry/5833fc0f570c35006c23e0fe)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/finally-understanding-how-references-work-in-android-and-java.md)
* PR 地址：#1012
* 文章分类：**Android**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jacksonke** [comment]
认领

**Comment by sqrthree** [comment]
@jacksonke 好的

**Comment by jacksonke** [comment]
完成 @sqrthree 
https://github.com/xitu/gold-miner/pull/1012
