### ISSUE TITLE
用不可变的基础设施提高攻击者的攻击成本

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#995]
* 原文链接：[Increasing Attacker Cost Using Immutable Infrastructure](https://diogomonica.com/2016/11/19/increasing-attacker-cost-using-immutable-infrastructure/)
* 掘金链接：[Immutable Infrastructure 让系统更安全](http://gold.xitu.io/entry/58340444d203090061662ddd)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/increasing-attacker-cost-using-immutable-infrastructure.md)
* PR 地址：#1021
* 文章分类：**后端**

----
* 翻译时间：`3` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Airmacho** [comment]
认领

**Comment by sqrthree** [comment]
@Airmacho 妥妥哒
