### ISSUE TITLE
全新的 Uber App 与全新的设计

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#996]
* 原文链接：[Designing the new Uber App](https://medium.com/uber-design/designing-the-new-uber-app-16afcc1d3c2e#.kaoghc61m)
* 掘金链接：[全新的 Uber App 与全新的设计](http://gold.xitu.io/entry/58357580a22b9d006bc16958)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/designing-the-new-uber-app.md)
* PR 地址：#1017
* 文章分类：**设计**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by phxnirvana** [comment]
领~

**Comment by sqrthree** [comment]
@phxnirvana 这篇是设计类的哟~ 翻译的话要保证质量撒，不然要有惩罚措施的啦

**Comment by phxnirvana** [comment]
好的~

**Comment by Ruixi** [comment]
我去我居然没看到这篇……

**Comment by sqrthree** [comment]
@phxnirvana 这篇进度如何了呀

**Comment by phxnirvana** [comment]
基本完成了，等我把键盘晾干就传。。鼠标打字好痛苦

**Comment by sqrthree** [comment]
哈哈哈好的~
