### ISSUE TITLE
Yammer 的 iOS app 代码升级到 Swift 3 的经验

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#997]
* 原文链接：[Yammer iOS App ported to Swift 3](https://medium.com/@yammereng/yammer-ios-app-ported-to-swift-3-e3496525add1)
* 掘金链接：[Yammer 的 iOS app 代码升级到 Swift 3 的经验](http://gold.xitu.io/entry/5835768167f3560065ecf3f6)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/yammer-ios-app-ported-to-swift-3.md)
* PR 地址：#1019
* 文章分类：**iOS**

----
* 翻译时间：`4` 天
* 校对时间：`1` 天
* 翻译积分：`6` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Danny1451** [comment]
@sqrthree  认领啦 好久没有iOS的文章了啊

**Comment by sqrthree** [comment]
@Danny1451 好的

**Comment by sqrthree** [comment]
@Danny1451 这篇进度如何了呀
