### ISSUE TITLE
如何避免应用崩溃

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#998]
* 原文链接：[How Not to Crash](http://blog.supertop.co/post/152615019837/how-not-to-crash-1)
* 掘金链接：[如何避免应用崩溃](http://gold.xitu.io/entry/5836ba398ac2470065d3ffcf)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/how-not-to-crash-1.md)
* PR 地址：#1005
* 文章分类：**iOS**

----
* 翻译时间：`5` 天
* 校对时间：`2` 天
* 翻译积分：`7` 分
* 校对积分：`2` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Gocy015** [comment]
@sqrthree 要了！

**Comment by sqrthree** [comment]
@Gocy015 好的
