### ISSUE TITLE
利用好 Android Studio 中的 APK Analyzer

### ISSUE THREAD

**Issue by sqrthree** [xitu/gold-miner#999]
* 原文链接：[Making the most of the APK analyzer](https://medium.com/google-developers/making-the-most-of-the-apk-analyzer-c066cb871ea2#.k0s1s1kgl)
* 掘金链接：[利用好 Android Studio 中的 APK Analyzer](http://gold.xitu.io/entry/5837f0eb0ce463006b90bed2)
* Markdown 文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO/making-the-most-of-the-apk-analyzer.md)
* PR 地址：#1014 => #1023
* 文章分类：**Android**

----
* 翻译时间：`4` 天
* 校对时间：`2` 天
* 翻译积分：`4` 分
* 校对积分：`1` 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XHShirley** [comment]
认领！

**Comment by sqrthree** [comment]
@XHShirley 好的

**Comment by sqrthree** [comment]
@XHShirley 这篇进度如何了呀
